### ISSUE TITLE
Update VPN goals in GA to support variable pricing options.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10003]
## Description

When VPN launches in France & Germany there will be three variable pricing options for subscriptions. We need to update goals in GA so we can understand which subscription options convert the best on the landing page. We'll also need to ensure that the current subscription intent goal continues to register in existing wave 1 markets.

---

#### Success Criteria
- [x] VPN GA goals are updated and tested on demo.
- [ ] Goals are applied to production before DE/FR launch.

**Comment by alexgibson** [comment]
@rraue I took a pass at implementing goals for the new pricing models in GA on www-demo1. When you have some time, can you please review to help me sanity check? If you reach out to me on Slack I'll provide a demo link where you can test.

**Comment by slightlyoffbeat** [comment]
from @rraue: reviewed and it looks good.

**Comment by alexgibson** [comment]
I've added the new 6 and 12 month subscription goals to the production VPN view, so I think we're fine to close this.

Thanks for helping out @rraue!
