### ISSUE TITLE
Update /firefox/central redirect to point to /firefox

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#10004]
## Description

Currently, http://mozilla.org/firefox/central points to https://support.mozilla.org/kb/get-started-firefox-overview-main-features. It needs to point to the root /firefox instead. 

---

#### Success Criteria
- [ ] Visiting the /firefox/central redirects correctly.

**Comment by maxxcrawford** [comment]
Prevous Bugzilla Bug, originally putting this in place: https://bugzilla.mozilla.org/show_bug.cgi?id=979527

**Comment by maxxcrawford** [comment]
@mhoye We should confirm that we have the same level of l10n coverage for this page, as the SUMO page.

**Comment by Ayushsunny** [comment]
I would like to work on this issue
