### ISSUE TITLE
Update subnav component to support tertiary navigation

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#10037]
## Description

The current subnav only supports one level of links. What is it needs to support more? 

Part of Epic #10036

---

#### Success Criteria
- [ ] Sub nav supports adding tertiary (third-level) links

## Screenshots

Desktop: 
![image](https://user-images.githubusercontent.com/2692333/112199684-66481c80-8bdc-11eb-9aa4-4c4c1f59283d.png)

Mobile:
![image](https://user-images.githubusercontent.com/2692333/112199702-6ba56700-8bdc-11eb-8011-53128775cad3.png)

**Comment by alexgibson** [comment]
This was done without needing a tertiary level of sub navigation, so closing for now. We can revisit this in the future if a need arises again.
