### ISSUE TITLE
Change "Addons" to "Add-ons" on mozilla.org

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10047]
In an effort to be more consistent, we should change "Addons" to "Add-ons" so that we are aligned with AMO.

One example where this will need to be changed is the subnav:

https://www.mozilla.org/en-US/firefox/new/

**Comment by prsndp** [comment]
Hii, @slightlyoffbeat I want to work on this issue can you assign me, please?

**Comment by tublitzed** [comment]
Thank you!
