### ISSUE TITLE
Convert the 85 WNP to a moments page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10046]
There is a request to convert the 85 WNP to a moments page. This page would be used to compare engagement in the moments channel vs the WNP.

Notes:
- The request is to have the page be identical in order to have a good point of comparison.
- EN only

**Comment by slightlyoffbeat** [comment]
I suspect that the request is actually to convert the 85 WNP. I'll confirm with Lauren.

**Comment by alexgibson** [comment]
There may be some overlap here with what the EU team want to create for VPN, as a replacement for WNP 89. We can likely consolidate some efforts here.

**Comment by alexgibson** [comment]
I'm going to bundle this into https://github.com/mozilla/bedrock/issues/10151

**Comment by alexgibson** [comment]
URL for this will be: https://www.mozilla.org/en-US/firefox/welcome/9/

**Comment by alexgibson** [comment]
Rolling this issue up into https://github.com/mozilla/bedrock/issues/10151
