### ISSUE TITLE
In GA events fired using `data-cta-type` are not captured correctly in older browsers.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10054]
## Description

Over the past year we've seen nearly 3 million events fired in GA with an event action label of `cta:` (where the value after `cta` is blank/missing). A total of 43% of these events are from Internet Explorer, and the rest are from older versions of other browsers (legacy Firefox versions mostly).

This means that any goals that rely on the event action label are likely misreporting conversions from older browsers.

### Steps to reproduce

The easiest way to see this bug occur is to test on demo and observe the event in the real-time dashboard.

1. In GA, open the real-time dashboard and click on the events tab (make sure you have demo1 selected for the view).
2. Using IE visit any page where there's a link with `data-cta-type` on it (let's use this example: https://www-demo1.allizom.org/en-US/firefox/browsers/)
3. Scroll down and click a link that uses the `data-cta-type` attribute (for this example let's click the heading that says "Desktop" that links to /firefox/new/).
4. In the GA dashboard observe the event that should fire.

### Expected result

An event should fire with the following values:

Event category: `cta click`
Event action: `cta: link`

### Actual result
In IE the event fires with the following values:

Event category: `cta click`
Event action: `cta:`

The bug seems to happen for any value of `data-cta-type` (e.g. `link`, `button` etc). There are currently 177 different occurences of this data atttribute throughout the website.

### Environment

IE 11, Windows 10.

**Comment by alexgibson** [comment]
From what I can tell, this is a bug in Google Tag Manager and not something specific to code in bedrock.

**Comment by slightlyoffbeat** [comment]
I've reached out to Data Science, but they do not have any resources to fix, so we will need to fix ourselves, or mark as blocked.

I did some investigating. GTM uses this to fill in that action field:

```
function () {
  return {{Click Element}}.closest('[data-cta-type]').dataset.ctaType;
}
```

According to MDN, `.closest` does not work for IE.

https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by alexgibson** [comment]
@slightlyoffbeat that would certainly point to the problem.  It's not 100% clear to me what `closest` is used for here seeing as we're dealing with link clicks. But I'm assuming it's for when we have nested content inside a link, such as a protocol [card component](https://protocol.mozilla.org/patterns/molecules/card.html)? We should probably also favour `getAttribute()` over `dataset` for broader compatibility.

I'm a bit hesitent to start changing things in production. I'm not 100% clear on:

a) where this code lives in GTM, and how changes there are reviewed (this has never had code review from a developer afaik).
b) how to safely test changes on a staging environment.

I don't think we really have any defined process here, as it's always been handled by someone else.

**Comment by stephaniehobson** [comment]
It's watching all elements for clicks, not just links, that's why it's using closest.

**Comment by alexgibson** [comment]
Wouldn’t `{{ Click Element }}` target more than just links already? Seems like `closest` would be looking for child nodes of the click target.

**Comment by slightlyoffbeat** [comment]
If there was a process for GTM, it no longer exists. There is no ownership and no one who is looking after GTM. If we want to test and fix, we'll need to find our own process.

We should be able to create an environment in GTM and test safely before pushing live.

**Comment by alexgibson** [comment]
This one might get fixed hopefully when we migrate to GA4? /cc @stephaniehobson

**Comment by stephaniehobson** [comment]
Not sure yet. Implementing custom events for "cta clicks" is pretty far down my list, but this is good information for me when I get there.

**Comment by stephaniehobson** [comment]
I think there is still a problem (200,000 empty values in the last 30 days) but I'm going to close this in favour of https://github.com/mozilla/bedrock/issues/15267 which is GA4 specific.
