### ISSUE TITLE
“Join to Waitlist” success page has an incomplete URL 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10057]
*Affected versions:*
 * All Firefox;

*Affected FxA versions:*
* 1.203.2;

*Affected Platforms:*
* Windows 10;

 *Prerequisites:*
* Be in a region were VPN is not available;

*Steps to reproduce:*
1. Open VPN homepage https://www-demo1.allizom.org/en-US/products/vpn/ 
2. Click on “Join to Waitlist” button;
3. Fill all mandatory fields;
4. Click “Join to Waitlist” from the bottom;

*Expected result:*
- User is redirected to the https://www-demo1.allizom.org/en-US/products/vpn/invite/success page.

*Actual result:*
- User is redirected to the https://www-demo1.allizom.org/en-US/products/vpn/invite/ page.

*Notes: *
- The https://www-demo1.allizom.org/en-US/products/vpn/invite/success returns a 404 page
- The https://www-demo1.allizom.org/en-US/products/vpn/invite/ has incomplete details. (The VPN is available for other platforms too)
![waitlisnt](https://user-images.githubusercontent.com/15685960/112852824-f68ed180-90b4-11eb-950b-d2b2b53b7494.png)

**Comment by alexgibson** [comment]
@ValentinaPC hi, can you explain why the expected result is a different page URL? (we originally decided this was surplus to requirements when migrating, as the form doesn't strictly require a server-rendered URL on mozorg).

**Comment by ValentinaPC** [comment]
@alexgibson hello, I misunderstood the expected results for redirections in Sarah's [doc](https://docs.google.com/document/d/1uTp-j0A_01A4WrNKmrKC2ynnpgdHuzAEHdcPLOh_8pA/edit?ts=605c1eac#heading=h.mvkppc1mtpae), that mentions that for both `/vpn/invite`, `/vpn/invite/success` we should load the same invite page.
Sorry about the noise.
