### ISSUE TITLE
The “Join to Waitlist” success page has incomplete description

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10060]
*Affected versions:*
 * All Firefox;

*Affected FxA versions:*
* 1.203.2;

*Affected Platforms:*
* Windows 10;

 *Prerequisites:*
* Be in a region were VPN is not available;

*Steps to reproduce:*
- Open VPN homepage https://www-demo1.allizom.org/en-US/products/vpn/ 
- Click on “Join to Waitlist” button;
- Fill all mandatory fields;
- Click “Join to Waitlist” from the bottom;
- See the page content;

*Expected result:*
- The page mentions all platforms: Windows, Linux, Mac, Android and iOS.

*Actual result:*
- The page only mentions: Windows, Android and iOS platforms.
![image](https://user-images.githubusercontent.com/15685960/112964395-f7754100-9150-11eb-9199-cefc7be89f98.png)

*Notes:*
- we should keep in mind, to add here also the FR and DE regions.

**Comment by alexgibson** [comment]
The aforementioned string is obsolete and has been removed on the demo server linked above.
