### ISSUE TITLE
VPN subscriptions can't be created from the staging website

### ISSUE THREAD

**Issue by madalincm** [mozilla/bedrock#10066]
#### Affected Platforms:
- all platforms
 
#### Prerequisites:
- Have a FxA account with no subscriptions made;
 
#### Steps to reproduce:
1. Open https://www-demo1.allizom.org/en-US/products/vpn/
2. Click on Get Mozilla VPN
 
#### Expected result:
- User is redirected to Mozilla VPN subscription page.
 
#### Actual result:
- Error page is displayed.
 
#### Notes:
- This error page is displayed whether the user is logged in or not.
- This issue is blocking the QA Team from testing VPN subscription flows for the FxA train release.
![image](https://user-images.githubusercontent.com/15685441/113111299-b93f5680-9210-11eb-95c8-6b852bcfdd20.png)

**Comment by alexgibson** [comment]
@madalincm this is a known issue and not yet ready for QA (the dev site is still WIP). Please speak to Sarah Bird as to when this is ready for testing. Thanks

**Comment by madalincm** [comment]
@alexgibson thanks for the responses here and in the mail!
We received, eventually, an up and running VPN stage site and managed to test the vpn subscription.

**Comment by alexgibson** [comment]
Glad everything makes sense now, thanks @madalincm!
