### ISSUE TITLE
Firefox for Android Beta release notes outdated by over one year

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10064]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1701489

**Comment by slightlyoffbeat** [comment]
I reached out to Mei in product marketing to see how release notes are handled for beta. That conversation should lead to a recommendation on how to proceed.

**Comment by slightlyoffbeat** [comment]
Mei has no problem removing it, but is checking with the product team in case we are missing something. 

@rraue traffic is minimal, but any concerns if we remove?

**Comment by slightlyoffbeat** [comment]
Link has been removed. 

@slightlyoffbeat to take a look at where people are coming in from before closing.

**Comment by slightlyoffbeat** [comment]
In-app link for 'what's new' takes users to a support page that is currently up to date Closing.
