### ISSUE TITLE
Update the email preference center

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10092]
Requested changes outlined here:

https://docs.google.com/document/d/10n--vAjUiSpYDsxG1oY4ImuCzoeaJtTwQF1gnHz9N4A/edit?usp=sharing

A summary of changes requested included:

- [ ] Updating the email provided in the copy that instructs how to whitelist us.
- [ ] update blurb for Mozilla News (copy to be provided)
- [ ] Nest Mozilla Festival and Insights under Mozilla News
- [ ] Add Common Voice and nest it under Mozilla News
- [ ] remove facebook mention from the unsubscribe confirmation

**Comment by krattliff** [comment]
Confirmed w/ MoFo/MoCo teams that we'll continue to support langs beyond DE, EN and FR. This item can be removed -->
 update supported languages to only include FR, DE, EN
