### ISSUE TITLE
The number displayed for VPN available countries is not correct

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/bedrock#10099]
### Build:
Stage

### Affected platforms:
Windows 10 x64
Chrome browser v. 89.0.4389.114

### Preconditions:
VPN is activated for a non-available region.

### Steps to reproduce

1. Navigate to https://www-dev.allizom.org/en-US/products/vpn.
2. Go to Availability section and observe the number of countries.

### Expected result
The number displayed for VPN available countries is correct. The number is 8.

### Actual result
The number displayed for VPN available countries is not correct. The number is 6.

![Wrong number of countries](https://user-images.githubusercontent.com/79697848/113981595-81f42980-9850-11eb-8372-c84b822daf73.PNG)

**Comment by alexgibson** [comment]
Thanks for spotting, will add a fix for this behind a feature flag.

**Comment by Bianca-O** [comment]
The issue is verified as Fixed on Stage under Windows 10 x64. The correct number of countries is displayed.
![new situation](https://user-images.githubusercontent.com/79697848/115212290-04aa9d80-a109-11eb-9b52-e07f764c1805.PNG)
