### ISSUE TITLE
Red warning message displayed when user wants to Join the Waitlist

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/bedrock#10101]
### Build:
Stage

### Affected platforms:
Windows 10
Chrome browser v. 89.0.4389.114

### Preconditions:
VPN is activated for a non-available region.

### Steps to reproduce:
1. Navigate to https://www-dev.allizom.org/en-US/products/vpn.
2. Click 'Join the Waitlist' button in the upper-right corner.
3. Fill in all the mandatory fields and click 'Join the Waitlist'.

### Expected result: 
No warning message is displayed and the user is on the waitlist.
### Actual result: 
A red warning message is displayed.

![warning message](https://user-images.githubusercontent.com/79697848/114015813-d0b2bb00-9872-11eb-9153-52e28fb9a511.PNG)

**Comment by alexgibson** [comment]
Looks like www-dev is missing the right basket token for this email form.

@pmac can we please get the right setting added for https://www-dev.allizom.org/en-US/products/vpn/invite/ ?

**Comment by alexgibson** [comment]
Looks like this one has been resolved.

**Comment by Bianca-O** [comment]
The issue was verified as Fixed on Stage under Windows 10. No red warning message is displayed anymore. 

![Join the waitlist - new situation](https://user-images.githubusercontent.com/79697848/114520916-99655500-9c4a-11eb-8dc9-5e901a077ad1.PNG)
