### ISSUE TITLE
”Join to Waitlist” buttons remain selected when coming back from a previous page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10103]
#### Affected versions:
 - All Firefox;

#### Affected FxA versions:
- 1.203.6;

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Steps to reproduce:
1. Open homepage: https://www-dev.allizom.org/en-US/products/vpn/
2. Click “Join to Waitlist”;
3. Click the “back” option form the browser;

#### Expected result:
- The button has no UI issues.

#### Actual result:
- The button remains selected.

#### Notes:
- Same for "Get Mozilla VPN" buttons

![image](https://user-images.githubusercontent.com/15685960/114036816-0f537000-9889-11eb-9df7-54500930f748.png)

**Comment by alexgibson** [comment]
This is Protocol bug https://github.com/mozilla/protocol/issues/655, and should be fixed by https://github.com/mozilla/bedrock/issues/10075

**Comment by alexgibson** [comment]
Fixed by #10075
