### ISSUE TITLE
Last Get Mozilla VPN button from the homepage does not center the pricing section correctly

### ISSUE THREAD

**Issue by madalincm** [mozilla/bedrock#10109]
#### Affected Platforms:
- iOS 14.3, Iphone 11, Safari Browser;
 
#### Prerequisites:
- The user is in FR/DE or is using a VPN with the location set to FR/DE;
 
#### Steps to reproduce:
1. Open https://www-demo1.allizom.org/en-US/products/vpn/ ;
2. Scroll down to the section immediately under FAQs;
3. Click the Get Mozilla VPN button;
 
#### Expected result:
- The user is redirected to the pricing section and there are no display issues;
 
#### Actual result:
- The page is not correctly centered, the section title is cut off by the address bar;
 
![image](https://user-images.githubusercontent.com/15685441/114186809-f792ef00-994f-11eb-9341-7a51e39d48f9.png)

#### Notes:
The issue is only reproducing using the Safari browser. Not reproducing on Chrome or Firefox;

**Comment by alexgibson** [comment]
Thank you for filing this. If this was happening in Safari on iOS for all "Get Mozilla VPN" buttons then I think this would warrant a fix, but seeing as the visitor must have already scrolled past the content in question to reach this button, then I'm not sure it makes sense to start coding around individual browser scrolling quirks when the overscroll is in the region of +/1 10px.

Closing this for now, but if you feel this is a larger issue then I'm happy to discuss further.
