### ISSUE TITLE
Only 3 language options in the VPN invite form

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10100]
#### Affected versions:
 - All Firefox;

#### Affected FxA versions:
- 1.203.6;

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have a FxA account;
- Be in a country where the Mozilla VPN is not available;

#### Steps to reproduce:
1. Open homepage: https://www-dev.allizom.org/en-US/products/vpn/
2. Click “Join to Waitlist”;
3. Click the languages dropdown;

#### Expected result:
- All languages are displayed.

#### Actual result:
- Only english, french and german are.

#### Notes:
- maybe the user is from Italy, and wanna wait for the VPN for his location, that means that he would also like to be able to select Italian as preferred language.

![image](https://user-images.githubusercontent.com/15685960/114015337-410d0c80-9872-11eb-9508-0141b3ca3367.png)

**Comment by alexgibson** [comment]
This is as expected for the upcoming launch in Germany and France. The waitlist email journey can be localized for more languages as we prepare to expand into further markets later in the year. Closing for now.

**Comment by ValentinaPC** [comment]
@alexgibson I was not talking about the Invite page being localized, but about the language that the user joins the waitlist for (see note above).

**Comment by alexgibson** [comment]
@ValentinaPC I understand that. The invite page is already localized in over 20 languages. The waitlist email journey only supports English, German, and French right now.
