### ISSUE TITLE
Update Mozilla VPN waitlist name in newsletter subscriptions page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10116]
## Description

If you're on the Mozilla VPN waitlist and want to remove yourself, the wrong product name is displayed in the newsletter subscriptions page.

### Steps to reproduce

1.) Sign up to the Mozilla VPN waitlist at: https://www.mozilla.org/en-US/products/vpn/invite/
2.) Generate a link to manage your subscriptions by entering the same email at: https://www.mozilla.org/en-US/newsletter/recovery/
3.) Click the link in the email to open the neswletter subscriptions page.

### Expected result

The page should list "Mozilla VPN Waitlist" as a newsletter subscription.

### Actual result

The page lists "Guardian VPN Waitlist", which is the wrong product name.

![image](https://user-images.githubusercontent.com/400117/114407752-a3cb1480-9ba0-11eb-8022-f3291f0f3839.png)

### Environment

N/A

**Comment by alexgibson** [comment]
@pmac I'm guessing this lives in basket/acoustic somewhere - can we get the product name updated to `Mozilla VPN`?

**Comment by pmac** [comment]
I updated the name in the basket admin. When the data syncs to bedrock this should be fixed.

**Comment by alexgibson** [comment]
Thanks @pmac 💯

**Comment by alexgibson** [comment]
Confirmed fixed:

![image](https://user-images.githubusercontent.com/400117/114568455-0b9a6180-9c6c-11eb-8bb6-ddc819522539.png)
