### ISSUE TITLE
Contentful, design system integration tasks.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#10127]
- [x] Create Firefox themed preview page & use it for pages in /firefox folders
- [x] Rich text support
    - [x] content model
    - [x] bedrock integration
      - [x] text  support
      - [ ] image support
- [ ] high/low res image solutions
  - [ ] Split
  - [ ] Hero
  - [ ] Cards
  - [ ] Rich text
- [ ] include CSS as needed
  - [x] for high level components (cards, split, text...)
  - [ ] for nested components (youtube videos in cards, logos in splits...)
- [x] include JS as needed
  - [x] for high level components (lazy load card images)
  - [ ] for nested components (youtube videos in cards)
- [ ] Figure out sections/background wrappers
- [ ] Add split support inside rich text areas
- [ ] Filter improvements
  - [x] don't insert empty paragraph tags
  - [x] add CTA link class to links if they are the only child in the last paragraph element
  - [x] stop list items from being wrapped in paragraph tags
  - [ ] solve download button being wrapped in p tags (but not logos or regular buttons)
  - [ ] safe guard against links to dev and staging
- [ ] cta button
  - [x] FxA
  - [x] Download Firefox
  - [x] Pocket
  - [ ] Monitor
  - [ ] tracking params
- [ ] cta app store links
  - [ ] Firefox mobile
  - [ ] Pocket
- [x] cta link
- [ ] L10N
  - [ ] translated feature pages
  - [ ] German homepage
- [ ] analytics
  - [x] add UTM params to links to other moz properties
  - [x] add data-cta to external links
  - [ ] identify CTAs by postion on page (right now everything is "primary")
- [ ] way to include Pocket feed on homepage
- [ ] add all Protocol icons to media library
- [ ] add product OG images to media library
- [ ] docs
  - [ ] page (in Protocol?) showing all components available in Contentful
  - [x] developer docs
- [x] Homepage content type
- [x] "all the things" page content type
- [x] "feature" page content type
- [x] Logo & wordmark support
    - [x] content model
    - [x] bedrock integration
    - [ ] center when in centered text
- [x] Split block support
  - [x] content model
  - [x] bedrock integration
  - [x] theme support
- [x] Callout support
  - [x] content model
  - [x] bedrock integration
  - [x] theme support
- [ ] Picto support
    - [x] content model
    - [x] bedrock integration
    - [x] theme support
    - [x] icon size options
    - [ ] request icon without aspect ratio
- [ ] Section Heading support
    - [x] content model
    - [x] bedrock integration
    - [ ] zap support
- [x] Hero support
  - [x] content model
  - [x] bedrock integration
  - [ ] need opinionated image sizing
- [x] Card support
  - [x] card
    - [x] content model
    - [x] bedrock integration
  - [x] large card
  - [x] youtube
  - [x] play button overlay for youtube cards
- [ ] Card layout support
    - [x] content model
    - [x] bedrock integration
  - [x] 2
  - [x] 3
  - [x] 4
  - [x] 5/hero
  - [x] 1:1, 3:2, 16:9
  - [ ] "ragged" image aspect ratios
- [x] Remove theme support from components that are not full width
- [x] add "max" width to width dropdowns where appropriate (picto layout...)
- [x] entry type to publish homepage
- [x] Multi column support
    - [x] content model
    - [x] bedrock integration
    - [ ] centered text option

**Comment by alexgibson** [comment]
@stephaniehobson we might not have checked all of these boxes, but can this issue be closed out today?

**Comment by stephaniehobson** [comment]
closing in favor of more specific issues and updated label organization ([see Contentful labelled issues](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3AContentful))
