### ISSUE TITLE
Add Mozilla VPN Get help band to French Mozilla VPN homepage 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/bedrock#10125]
### Build:
Stage

### Steps to reproduce

1. Navigate to https://www-dev.allizom.org/fr/products/vpn/.
2. Look for Mozilla VPN Get Help band.
3. Compare with US or DE homepage.

### Expected result

Mozilla VPN Get Help band is available for French homepage too.

### Actual result

Mozilla VPN Get Help band is not available for French homepage.

![no Mozilla VPN band for FR](https://user-images.githubusercontent.com/79697848/114707150-89c13b80-9d32-11eb-8686-1a17ad7cf4a6.PNG)

**Comment by alexgibson** [comment]
The sub navigation will be shown automatically once a particular locale has translated the strings required for it. As it stands, the french localizations for these strings have not been completed yet, so it's expected not to show until that has happened. We'll get those completed soon, but I'm going to declassify this as a bug. Closing
