### ISSUE TITLE
Sub navigation component has UI issues on mobile

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10123]
#### Affected versions:
 - Safari;

#### Affected FxA versions:
- 1.203.7;

#### Affected Platforms:
- iOS 14.02;

#### Steps to reproduce:
1. Open homepage: https://www-dev.allizom.org/en-US/products/vpn/
2. Observe the Mozilla VPN banner;

#### Expected result:
- The banner can be expanded. There are no UI issues.

#### Actual result:
- The drop-down arrow is over the Mozilla VPN text.

#### Notes:
- Not reproducing on Android;

![image](https://user-images.githubusercontent.com/15685960/114688809-bf0f5e80-9d1d-11eb-9933-c07b6ad47f4d.png)

**Comment by alexgibson** [comment]
I couldn't reproduce this, but after some careful testing it saeems this bug shows up only when the viewport is exactly 768px wide.

**Comment by ValentinaPC** [comment]
Verified as fixed on iOS 14.3 - iPad Air 2.
The sub menu has no UI or layout issues.
Postfix screenshot.
![image](https://user-images.githubusercontent.com/15685960/115210374-2f93f200-a107-11eb-9e18-7f8307f83a14.png)
