### ISSUE TITLE
Missing logo in the Featured in section

### ISSUE THREAD

**Issue by madalincm** [mozilla/bedrock#10133]
#### Affected Platforms:
- all platforms;
 

 
#### Steps to reproduce:
1. Open https://www-dev.allizom.org/en-US/products/vpn/ ;
2. Scroll to the featured in section;
3. Observe the logos displayed;

#### Expected result:
- There are 5 logos displayed;
 
#### Actual result:
- Only 4 logos are displayed. Engadget logo is missing;
![image](https://user-images.githubusercontent.com/15685441/114866495-4e8b3f00-9dfc-11eb-93b6-39f663f0de40.png)

**Comment by alexgibson** [comment]
Invalide, see https://github.com/mozilla/bedrock/issues/10114
