### ISSUE TITLE
Unnecessary redirection when clicking the links from the FAQ - What devices is Mozilla VPN compatible with section

### ISSUE THREAD

**Issue by madalincm** [mozilla/bedrock#10132]
#### Affected Platforms:
- all platforms;
 
#### Prerequisites:
- The user is in en-us or is using a VPN with the location set to en-us;
 
#### Steps to reproduce:
1. Open https://www-dev.allizom.org/en-US/products/vpn/ ;
2. Scroll to the FAQ section;
3. Click on the What devices is Mozilla VPN compatible with? link;
4. Click on the mobile or desktop link;
5. Click on the See pricing & availability button;
 
#### Expected result:
- The user is redirected to a section to see the product price and the available platforms;
 
#### Actual result:
- The user is redirected to the https://www-dev.allizom.org/en-US/products/vpn/ page;
 
![redirection](https://user-images.githubusercontent.com/15685441/114865896-92ca0f80-9dfb-11eb-8731-d3443a7ddb0c.gif)

**Comment by alexgibson** [comment]
I agree this is a bit of a weird loop. I'm not sure if we should classify this as a bug, but I'll see what relevant stakeholders think.

**Comment by rraue** [comment]
As much as I agree that this isn't the perfect solution yet (we will get universal pricing boxes and then the sub pages will not need to link to the main landing page anymore), I don't think its a real loop. 

- Users that just want to know which OS/Devices are available do not need to click on the links, the answer is there in the FAQ. 
- Users that want to know more about a specific OS, will find more information on the OS pages and can follow the link and get more information. If they decide to get VPN then only the extra click is no doubt a bit weird. 

But once the pricing model is finalized, these pages will have the same cta as the landing page so there is no loop anymore.

For now I would keep it as it is, as its more important to have correct pricing information and for now we can only show them on the main landing page.

I checked in GA and user coming from the main landing page to one of the OS pages have no lower conversion rate than our average user. And the number actually doing it is relativity small.

**Comment by alexgibson** [comment]
Ok thanks for the input @rraue, closing this one for now.
