### ISSUE TITLE
 [l10n] UI issues for “german” language in VPN homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10130]
#### Affected versions:
 - All Firefox;

#### Affected FxA versions:
- 1.203.7;

#### Affected Platforms:
- Android 11;

#### Prerequisites:
- Have the browser localized in “German”;

#### Steps to reproduce:
1. Open homepage: https://www-dev.allizom.org/de/products/vpn/
2. Scroll down to #pricing section;

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- The text from the section is not wrapped and appears cut. There is an horizontal scroll bar.

#### Notes:
- This also happens at the beginning of the page with the first title.
- Also happens while in a region where VPN is available;
- This does not happen on iOS.

![ui](https://user-images.githubusercontent.com/15685960/114839618-a61ab200-9dde-11eb-8dc3-ab93cd675a87.png)

**Comment by alexgibson** [comment]
Thanks for filing, I'll take a look at this.

**Comment by ValentinaPC** [comment]
This issue is also happening in Privacy Notice page for "de".
![image](https://user-images.githubusercontent.com/15685960/115026390-19015700-9ecb-11eb-94fc-67e551e0e87f.png)

**Comment by alexgibson** [comment]
> This issue is also happening in Privacy Notice page for "de".

Please file a different issue for this, as it's unrelated to the VPN landing page. Thanks

**Comment by ValentinaPC** [comment]
Verified as fixed on Android 11.
There are no UI issues in VPN homepage.
Postfix screenshots below.
![image](https://user-images.githubusercontent.com/15685960/115212946-b6e26500-a109-11eb-8240-8fd34609b66e.png)
