### ISSUE TITLE
Replace twofactorauth.org References

### ISSUE THREAD

**Issue by ApCoder123** [mozilla/bedrock#10137]
## Description

The site that was at twofactorauth.org is now at https://2fa.directory

See 2factorauth/twofactorauth#5238 for more info

The following references should probably be updated:

https://github.com/mozilla/bedrock/blob/7f6e3ea9e002360a62ceeb3aa6ed76477b55da7b/bedrock/firefox/templates/firefox/privacy/passwords.html#L98

https://github.com/mozilla/bedrock/blob/7f6e3ea9e002360a62ceeb3aa6ed76477b55da7b/l10n/en/firefox/privacy/passwords.ftl#L64

**Comment by alexgibson** [comment]
Thanks for the report, sounds like we should get these updated 👍

**Comment by Patil2099** [comment]
Can I work on this @alexgibson?

**Comment by Kaushal-Dhungel** [comment]
Hello. I would like to work on this.
