### ISSUE TITLE
'An error has occurred' message is displayed when accessing the Mozilla VPN homepage

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/bedrock#10134]
### Build
Stage

### Affected platforms:
Android 6
Android 11
iOS

### Steps to reproduce

1. Navigate to https://www-dev.allizom.org/en-US/products/vpn/.
2. Observe the page.

### Expected result
No error. Mozilla VPN homepage is displayed.

### Actual result
'An error has occurred' message is displayed.

![1618491383507](https://user-images.githubusercontent.com/79697848/114878870-59989c00-9e09-11eb-9121-607a7a82be2d.JPEG)

**Comment by alexgibson** [comment]
This is an issue with our CDN. Folks are working on it and I'll close this when resolved.

**Comment by Bianca-O** [comment]
The issue was verified as Fixed on Stage under Windows 10 x64 and Android 11.
