### ISSUE TITLE
VPN homepage is not geo-restricted

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10139]
#### Affected versions:
 - All Firefox;

#### Affected FxA versions:
- 1.204.2;

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Be in a region where VPN is not available (i.e Italy);

#### Steps to reproduce:
1. Open homepage: https://www-dev.allizom.org/de/products/vpn/

#### Expected result:
- “Join to Waitlist” buttons are displayed through the page.

#### Actual result:
- “Get Mozilla VPN” buttons are displayed through the page.

### Notes:
- Having ourselves put in FR/DE (using another VPN solution), will not trigger the correct behavior and the 3 euro plans.
![image](https://user-images.githubusercontent.com/15685960/114987162-84cccb00-9e9d-11eb-861f-0cb37a72a389.png)

**Comment by alexgibson** [comment]
I believe this is a regression caused by https://github.com/mozilla/bedrock/pull/10136

The response returned by country_code.json is always `{"country_code": "US", "data_source": "cdn"}`, so geo is currently not enabled on www-dev.

**Comment by alexgibson** [comment]
Ok, just as soon as this landing on ww-dev the issue should be resolved. I'll verify when that's happened.

**Comment by alexgibson** [comment]
Ok, I now see the following response so this should be workign again. Sorry for the holdup here.

`{"country_code": "GB", "data_source": "cdn"}`

**Comment by ValentinaPC** [comment]
Verified as fixed.
The VPN homepage uses geo-restriction.
