### ISSUE TITLE
Update homepage for MR1

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10167]
Placeholder for work related to updating the homepage for MR1

**Comment by craigcook** [comment]
Prototyping on demo: https://www-demo4.allizom.org/en-US/

**Comment by slightlyoffbeat** [comment]
@craigcook will we be able to compare the CTR across the 4 variations?

**Comment by craigcook** [comment]
> @craigcook will we be able to compare the CTR across the 4 variations?

Yeah, we can tag them to differentiate. I'd be surprised to see much difference between them, but who knows.
