### ISSUE TITLE
Replace Lockwise with VPN on various pages

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10166]
The lockwise app is being phased out. A full communication plan and strategy around the future of lockwise is coming. In the meantime, we should replace lockwise with VPN in various discovery pages/paths. 

Remove lockwise from:
- [ ] the floating promo box on /new (and anywhere else it shows up)

Replace Lockwise with VPN on:

- [ ] https://www.mozilla.org/en-US/firefox/
- [ ] https://www.mozilla.org/en-US/firefox/products/
- [ ] https://www.mozilla.org/en-US/firefox/privacy/products/
- [ ] https://www.mozilla.org/en-US/firefox/accounts/

We will not touch the lockwise landing page for now. Work on that page will be covered by a separate issue at a later time.

Success Criteria:
- [x] Thumbs up on visuals and copy from creative studio
- [x] Thumbs up on approach by UX
- [x] coded on demo
- [x] Creative has reviewed visuals + copy on demo and given thumbs up.
- [ ] Links have appropriate parameters
- [x] Don't show content to non-EN if it isn't localized yet.
- [ ] Launched

**Comment by slightlyoffbeat** [comment]
There is overlap with other cards that reference removing lockwise, but also try and cover additional changes. We should consider closing or reworking those cards after this work is completed:

https://github.com/mozilla/bedrock/issues/9976

https://github.com/mozilla/bedrock/issues/9905

**Comment by slightlyoffbeat** [comment]
Affected pages include:

/firefox/products
/firefox/privacy/products
/firefox/new (the floating box with products)
/firefox/lockwise
/firefox/accounts

**Comment by alexgibson** [comment]
@slightlyoffbeat where should we redirect /firefox/lockwise to? Is there some SUMO article or blog post that explains to people what is happening with the product?

**Comment by slightlyoffbeat** [comment]
@alexgibson either just /firefox or a SUMO article. I reached out to SUMO to see if an article exists (if not, I'll request one gets made). I also reached out to Mei to see if she has an opinion on this. I'll update here when I have an answer.

**Comment by slightlyoffbeat** [comment]
As of writing this comment, this is still blocked, but things are moving fast and this may be prioritized for next week.

**Comment by slightlyoffbeat** [comment]
No longer blocked.

**Comment by slightlyoffbeat** [comment]
@craigcook added a bullet to success criteria that we shouldn't show to non-EN unless it is translated.

**Comment by slightlyoffbeat** [comment]
Creative has delivered assets! See below:

Trello Card: https://trello.com/c/wgtWXf0P/365-add-vpn-to-mozillaorg?menu=filter&filter=member:alexandergibson2
Figma File: https://www.figma.com/file/X1el5pAvN9hIaIqUWmnokj/Add-VPN-to-Moz.org?node-id=0%3A1
Copy: https://docs.google.com/document/d/1RTEJoSg5g7NcVRyaQ7tnctlZO5NpXdyVLN_KMvO_0Rs/edit?usp=sharing

They have requested a review before we go live on staging/demo. I've added to success criteria.

**Comment by Foggalong** [comment]
> A full communication plan and strategy around the future of lockwise is coming

@slightlyoffbeat do you have any idea when that post is coming? I migrated to lockwise over the summer so was very frustrating to come across this thread and find out that the decision to sunset it had been made but not announced months prior :confused:

**Comment by rustup6** [comment]
You can change your mind and make lockwise a paid password manager like 1password/lastpass/Dashlane.Mitchell Baker attributed Mozilla's failure to the current business model, believing that all of this was caused by the "old free model" and declared that the future focus will be on "money-making" commercial projects. This is likely to include Mozilla's VPN product, which is newly launched by Mozilla. Virtual Private Network (VPN) applications are one of the most profitable technologies today. Password manager is also a profitable project, firefox has Firefox Monitor/lockwise basis!

**Comment by rustup6** [comment]
You should do a poll to see how many people are willing to pay for Mozilla VPN.Judging from the current discussions on Twitter, few people are willing to pay for Mozilla VPN. The project may end up being the same as Lockwise, so you don’t need to promote Mozilla VPN on all pages!

**Comment by Foggalong** [comment]
To update for those also interested in the state of lockwise, I emailed Mozilla about this too and got a generic reply saying my query wasn't one they'd have time to reply to so who knows what's happening :shrug:

**Comment by igor-kobzev** [comment]
> A full communication plan and strategy around the future of lockwise is coming.

And in the end no communication happened! WTF. I just found out Lockwise was discontinued entirely by accident. I've been using it on my iPhone for half a year without security updates. What. The. Actual. F? The app didn't even say anything about it being discontinued.
