### ISSUE TITLE
Custom dimension for AMO experiments

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/bedrock#10175]
## Description

We have determined that we cannot currently use `utm_campaign` for recording an experiment variation when we are linking to the Download Firefox page from within AMO. We would like to be able to record the experiment variation in order to use Google Analytics to analyze the conversion rate of these referrals during an experiment. We would like to use a custom GA dimension for this, either a new one that could be created for this purpose, or we could use an existing one if there is one available that makes sense.

---

#### Success Criteria
- [x] AMO is able to create a link to Download Firefox which includes a custom dimension which will be stored in GA for mozilla.org and can be used for reporting conversions.

ccing @alexgibson and @slightlyoffbeat with both of whom I have discussed this on Slack.

**Comment by bobsilverberg** [comment]
@alexgibson When analyzing the data from the current experiment we have running, we have realized that our use of `utm_term`, while making analysis possible, is not optimal. Having a custom dimension in place that AMO can use for our next experiment would be good. However, I want to check to see if we can actually make use of it.

If a custom dimension is defined in GA for our use, will we be able to populate it by passing a query param on the URL that links to mozilla.org? We won't have access to the GA API for mozilla.org, so we'd need to be able to populate the data into GA via a query param. Is that currently possible?

**Comment by alexgibson** [comment]
In GA we have custom dimensions already set up for experiments and variations, both of which rely on the following dataLayer event in JS: https://bedrock.readthedocs.io/en/latest/abtest.html#viewing-the-data

The main thing I think we'd want to avoid is passing in untrusted content to JS/GA via a query param, so we'd need to decide on a set of allowed values/formats.




    
    
      
    <span class="blob-code-inner blob-code-marker" data-code-marker="+">                <span class="pl-kos">}</span><span class="pl-kos">)</span><span class="pl-kos">;</span></span>

**Comment by bobsilverberg** [comment]
Nice! So those dimensions are available, but I take it from your comment above that we cannot currently write to them simply by passing a URL param? All we would need to pass are a fairly short string for each of those, so it might not be difficult to define a format that would be safe. Defining a set of allowed values might be trickier as the experiment name will change each time, and ideally the the variant would be descriptive based on the current experiment.

**Comment by alexgibson** [comment]
> Defining a set of allowed values might be trickier as the experiment name will change each time, and ideally the the variant would be descriptive based on the current experiment.

I'll lean on your good-self to propose what might work here :)

Sticking to something simple like alpha-numeric values for the experiment name (something with amo in?), and an integer for the variation might be enough. Perhaps we could rely on the same `experiment` and `variation` parameters that stub attribution uses?

**Comment by bobsilverberg** [comment]
> > Defining a set of allowed values might be trickier as the experiment name will change each time, and ideally the the variant would be descriptive based on the current experiment.
> 
> I'll lean on your good-self to propose what might work here :)
> 
> Sticking to something simple like alpha-numeric values for the experiment name (something with amo in?), and an integer for the variation might be enough. Perhaps we could rely on the same `experiment` and `variation` parameters that stub attribution uses?

We're already passing `experiment` and `variation` in the URLs when we run an experiment, so being able to reuse those would be ideal. I.e., if we pass `experiment` and/or `variation` on the URL, they'd get written to the corresponding GA custom dimensions. Are you saying there is already validation in place around `experiment` and `variation`? Or do we still need to define acceptable formats?

**Comment by alexgibson** [comment]
I'd say some level of sanitisation / format checks are always worth adding.

**Comment by bobsilverberg** [comment]
The format that we have adopted thus far for `experiment` is `YYYYMMDD_experiment_name`, which we check, somewhat casually, via `/\d{8}_.+/`. We haven't defined a length, but we could have a maximum if that would help. In terms of `variation`, we prefer to use a string over an integer to make the reports in GA easier to read/interpret. We could limit that to alpha-numeric values and could keep it fairly short (<=20 chars, for example). Would those suffice, or would you also like an identifier (for example, you suggested using `amo` in the name)?

**Comment by alexgibson** [comment]
I think this should be fine, thank you

**Comment by bobsilverberg** [comment]
@alexgibson We are planning on running the download funnel experiment soon (as you know) and we have another experiment in the pipeline which will also interact with mozilla.org, and for which it would be helpful to have this in place. Do you have any thoughts about when your team might be able to get to this issue?

**Comment by alexgibson** [comment]
> Do you have any thoughts about when your team might be able to get to this issue?

I'd say probably not until after the wellness week. Sorry this is taking a while to get to.

**Comment by bobsilverberg** [comment]
> > Do you have any thoughts about when your team might be able to get to this issue?
> 
> I'd say probably not until after the wellness week. Sorry this is taking a while to get to.

No problem. Thanks for the update. 😄

**Comment by alexgibson** [comment]
@bobsilverberg just reading back through this issue to refresh my brain before picking this up. Is it safe to assume that the target URL for your experiments would be /firefox/new/, and that this custom code would only really need to exist at that URL?

**Comment by bobsilverberg** [comment]
> @bobsilverberg just reading back through this issue to refresh my brain before picking this up. Is it safe to assume that the target URL for your experiments would be /firefox/new/, and that this custom code would only really need to exist at that URL?

Well, the experiment we are about to run will actually be targeting both `/firefox/new/` and `/firefox/download/thanks/`, and if it determines that using the latter is advantageous, then we will probably switch to something other than `/firefox/new/` once we've figured out what a decent permanent implementation will be.

We are also planning to run an experiment that will target `/products/vpn/`, so it's not really accurate to say that the target for experiments will always be `/firefox/new/`.

Having said that, if it is better for implementation purposes, we could define a set of targets, which would need to be able to be added to, but we'd be able to give advance notice if we need to add a new target. Do you think that would work?

**Comment by alexgibson** [comment]
@bobsilverberg I think my main concern is this having the potential to clash with other experiments that either the websites team, or other teams at Mozilla, might run. The `experiment` and `variation` parameters are not really unique to AMO, and first-party experiments will also likely already define their own custom event in GA.

To avoid clobbering other experiments this way, I think it makes sense to try and more tightly define the parameters that your team will pass through. So what I propose is:

1.) We can add this script to our base JS bundle, so it will be available at almost all URLs.
2.) We more explicitly define the accepted parameters for this custom GA event to fire. Let's try and identify it as something coming directly from AMO.

I suggest we use something like `experiment=YYYYMMDD_amo_experiment_name`. The key would be that `_amo_` would need to be in there for this to happen. That way other experiments won't accidentally trigger this code path and risk muddying data. Does this make sense to you?

**Comment by bobsilverberg** [comment]
> 
> I suggest we use something like `experiment=YYYYMMDD_amo_experiment_name`. The key would be that `_amo_` would need to be in there for this to happen. That way other experiments won't accidentally trigger this code path and risk muddying data. Does this make sense to you?

Sure, that makes sense. I'll open an issue to update our naming convention so that we always include something that matches `YYYYMMDD_amo` for our experiment names.

**Comment by alexgibson** [comment]
Great thanks. Ok, I think I have enough info here to get started on this 👍

**Comment by alexgibson** [comment]
@bobsilverberg for transparency, the regex I landed on for these values are as follows:

experiment: /^\d{8}_amo_.[\w/.%-]{1,20}$/;
variation: /^[\w/.%-]{1,20}$/;

This should meet your set date format and the `_amo_` identifier we discussed for the experiment name. I also limited the remainder of the characters to be basically alpha-numeric with an upper limit of 20 characters.

Does this sound ok to you?

**Comment by willdurand** [comment]
Hello!

> I also limited the remainder of the characters to be basically alpha-numeric with an upper limit of 20 characters.

We use snake case for experiment identifiers (sometimes), e.g., https://github.com/mozilla/addons-frontend/blob/b5414773c029bb8b96c390b8b7122a5d0ae3eebd/config/development.js#L86

20 chars does not seem like a lot for both. I don't remember where these values end up in Telemetry events: if they are extra props, then we could have values up to 80 chars.

**Comment by alexgibson** [comment]
> We use snake case for experiment identifiers (sometimes), e.g., https://github.com/mozilla/addons-frontend/blob/b5414773c029bb8b96c390b8b7122a5d0ae3eebd/config/development.js#L86

Things like underscores and hyphens should be fine here, thanks.

> 20 chars does not seem like a lot for both. I don't remember where these values end up in Telemetry events: if they are extra props, then we could have values up to 80 chars.

80 seems like rather a lot, but not unreasonable. I'll update to use this, thanks.

**Comment by alexgibson** [comment]
> 80 seems like rather a lot, but not unreasonable. I'll update to use this, thanks.

Actually I think it's sensible to cap this at 50

**Comment by bobsilverberg** [comment]
> > 80 seems like rather a lot, but not unreasonable. I'll update to use this, thanks.
> 
> Actually I think it's sensible to cap this at 50

Thanks for chiming in @willdurand. 50 sounds reasonable to me, thanks @alexgibson!

**Comment by alexgibson** [comment]
@bobsilverberg this should now be in production

**Comment by bobsilverberg** [comment]
Thanks @alexgibson! We're launching the next experiment on Thursday, so we can make use of this right away!
