### ISSUE TITLE
contradictory statements about VPN compatibility

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/bedrock#10183]
### Description

The VPN page on https://www.mozilla.org/en-US/products/vpn/ says in the accordion below the "What devices is Mozilla VPN compatible with?" caption that macOS 10.14+, Android 8+ and iOS 12+ are supported. After login the download page says that macOS 10.15+, Android 6+ and iOS 13+ are supported. Both sources can't be true, they should have the same compatibility information.

The Linux support is noted as Ubuntu 18.04+ in the accordion, the download page doesn't mention a version at all. Maybe it makes sense to add it here as well since all other download buttons have a version information.

### Environment

What browser and operating system are you using?
=> macOS 11.3, Firefox 90 Nightly, German language

**Comment by alexgibson** [comment]
I believe the download page may be the outdated info, as opposed to the landing page. We should check with the product team to verify.

**Comment by alexgibson** [comment]
Moved this over to https://github.com/mozilla-services/guardian-website/issues/1151
