### ISSUE TITLE
Create 5 Firefox Mobile Evergreen Pages

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10182]
There are 5 evergreen pages for Firefox Mobile that are ready to develop. Each page is based on the layout of an existing page.

Overall brief: https://docs.google.com/document/d/102A3ZzjDf6v_ZWr-bQODBDmEuNxMaBxin1yQb_KV1S4/edit

***

**Page 1:** Mobile Overview Page
**URL:** /firefox/browsers/mobile/ (redirect from /firefox/mobile/)
**Title:** Firefox Mobile Browsers put your privacy first
**Keywords:** Firefox mobile, mobile browser

[Template]( https://www.mozilla.org/en-US/firefox/browsers/)
[Copy](https://docs.google.com/document/d/1zt2Dw70gZ32lFSK4kuFXu8EHevVy1J3PIXROWnoBNm8/edit?usp=sharing)

***

**Page 2:** Firefox iOS
**URL:** /firefox/browsers/mobile/ios/ 
**Title:** Firefox Browsers iOS (iPhone & iPad)
**Keywords:** Firefox ios, firefox iphone, firefox ipad, iphone browser, default browser

[Template](https://www.mozilla.org/en-US/firefox/mobile/)
[Copy](https://docs.google.com/document/d/1YdSDt4VlvRhHmNJNMJl2Rd1tZ2Haj5nvXBXSvsvxJbA/edit?usp=sharing)

***

**Page 3:** Firefox Android
**URL:** /firefox/browsers/mobile/android/ 
**Title:** Firefox Browser Android
**Keywords:** Firefox android, best android browser

[Template](https://www.mozilla.org/en-US/firefox/mobile/)
[Copy](https://docs.google.com/document/d/1qpTYZrumyyP1AfEngXCZoVURL6TwFrNVCI3Ya0g9p3w/edit?usp=sharing)

***

**Page 4:** Firefox Focus
**URL:** /firefox/browsers/mobile/focus/ 
**Title:** Firefox Focus: The privacy browser
**Keywords:** Firefox Focus, best browser for privacy
**NOTE**: This should have a look/feel of focus and will need designer resources to provide direction

[Template](https://www.mozilla.org/en-US/firefox/mobile/)
[Copy](https://docs.google.com/document/d/18TQqIMtXfEY1mg0ampNVRsiTfUas9q9mwOV1XigXKCA/edit?usp=sharing)

***

**Page 5:** Mobile Comparison Page
**URL:** /firefox/browsers/browsers/mobile/compare/ 
**Title:** 5 of the best mobile Browsers in direct comparison
**Keywords:** 

[Template](https://www.mozilla.org/en-US/firefox/browsers/compare/)
[Copy](https://docs.google.com/document/d/1YchZPfFm2uNywfiO6dHZ0o58n0-DOS4vHmIl-deIrp0/edit?usp=sharing)

**Comment by slightlyoffbeat** [comment]
Design resources are currently not available, so we should use the design and illustrations in the existing layouts for now.

**Comment by rraue** [comment]
**Here is the structured data for Focus:**

 {
    "@context": "https://schema.org/",
    "@graph": [
      {
  "@context": "https://schema.org/",
  "@type": "MobileApplication",
  "@id": "https://www.mozilla.org/#firefoxfocus",
  "url": "https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/",
  "name": "Firefox Focus",
  "image": "https://raw.githubusercontent.com/mozilla/bedrock/master/media/img/logos/firefox/logo-focus.png",
  "sameAs": [
    "https://www.wikidata.org/wiki/Q31020870",
    "https://en.wikipedia.org/wiki/Firefox_Focus",
    "https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=en",
    "https://apps.apple.com/us/app/firefox-focus-privacy-browser/id1055677337"
  ],
  "offers":
  {
    "@type": "Offer",
    "url": "https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/",
    "priceCurrency": "USD",
    "price": "0",
    "availability": "https://schema.org/InStock"
  },
  "OperatingSystem": "Android, iOS",
  "applicationCategory": "Mobile Browser",
  "applicationSuite": "Firefox",
  "author":
  {
    "@type": "Organization",
    "@id": "https://www.mozilla.org/#organization",
    "name": "Mozilla Corporation"
  },
  "softwareHelp":
  {
    "@type": "Webpage",
    "url": "https://support.mozilla.org/en-US/products/focus-firefox"
  }
}
