### ISSUE TITLE
Redirect firefox/central to support article

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#10185]
## Description

In fresh Firefox profiles there is a [pinned "Getting Started" link](https://searchfox.org/mozilla-central/source/browser/locales/generic/profile/bookmarks.html.in#26) to `/firefox/central` which redirects to `/firefox`.

`/firefox` is more of a marketing page for our products and we should redirect to a support article like https://support.mozilla.org/en-US/products/firefox/get-started instead.

[Bedrock redirect docs: https://bedrock.readthedocs.io/en/latest/redirects.html]

**Comment by maxxcrawford** [comment]
This was intentionally done. See more at https://github.com/mozilla/bedrock/issues/10004

**Comment by amychurchwell** [comment]
Closing WONTFIX 🌈 🦄
