### ISSUE TITLE
Mozilla VPN sub navigation component is not present for French lang

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/bedrock#10188]
*Affected versions:*
* All Firefox;
* Chrome 90.0.4430.100;

*Affected FxA versions:*
* 1.205.0;

*Affected Platforms:*
* Windows 10;
* Chrome OS;

 *Prerequisites:*
* Simulate France location;

*Steps to reproduce:*
1. Open VPN homepage https://www-dev.allizom.org/fr/products/vpn/ 
2. Observe the page header

*Expected result:*
- There is a Mozilla VPN sub nav menu localized in French;

*Actual result:*
- The sub nav menu is missing;

*Notes:*
- The Mozilla VPN sub nav menu is displayed while in Germany;

![image](https://user-images.githubusercontent.com/15685960/117254983-c8d63e80-ae51-11eb-92ab-f83a3d3a3e7f.png)

**Comment by alexgibson** [comment]
Localizers have now translated the sub nav string, so this show up on /fr/.
