### ISSUE TITLE
Website vague about subscription vs one time purchase

### ISSUE THREAD

**Issue by birdsarah** [mozilla/bedrock#10189]
Originally brought up on https://github.com/mozilla-mobile/mozilla-vpn-client/issues/933

Reported by @rbillings from user feedback: 

The website makes almost no reference that this is a subscription. Only the button which redirects to the payments process mentiones it ("Abo").while "X Monat(e)" ("X month(s)") could be interpreted as a one-time purchase for this timeframe.

**Comment by alexgibson** [comment]
This will be fixed in https://github.com/mozilla/bedrock/pull/10195
