### ISSUE TITLE
Update Firefox comparison pages with more recent information

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10196]
## Description
Some of the comparison tables are out of date, see: https://www.reddit.com/r/firefox/comments/n9aqtx/the_firefox_versus_edge_comparison_page_has_been/

---

#### Success Criteria
- [x] Comparison pages are updated to reflect the latest browser features.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/9750

**Comment by alexgibson** [comment]
This popped up on Reddit again https://www.reddit.com/r/firefox/comments/oedx7r/incorrect_information_on_mozillas_website/

Looks like someone kindly took the time to submit a pull request, which (at least) addresses the chart for Edge: https://github.com/mozilla/bedrock/pull/10312

@slightlyoffbeat is there anything else we wanted to update here, or does this pull request cover the scope of the changes needed here?

**Comment by slightlyoffbeat** [comment]
@alexgibson LGTM. We should revisit all of this (working with Mei on this), but for now this addresses a short-term need.
