### ISSUE TITLE
Beta install link seems to always give a 32-bit installer

### ISSUE THREAD

**Issue by squarewave** [mozilla/bedrock#10194]
## Description

I always get a 32-bit installer when I go to https://www.mozilla.org/en-US/firefox/channel/desktop/#beta and click Download for the Beta version.

### Steps to reproduce

- Go to https://www.mozilla.org/en-US/firefox/channel/desktop/#beta
- Click the top Download link
- Go through the full installation
- In the Firefox that launches, go to Hamburger Menu -> Help -> About Firefox

### Expected result

If you're on a 64-bit OS, you should see something like "89.0b10 (64-bit)" under "Firefox Browser"

### Actual result

You see something like "89.0b10 (32-bit)" under "Firefox Browser"

### Environment

Nightly, Windows 10 64-bit.

**Comment by alexgibson** [comment]
Thanks for filing. The website doesn't do 64bit detection for Windows, since it's not always reliable via UA string detection.

For the main Firefox release download, this kind of logic is handled by the stub installer which can get this right with much greater confidence. But for pre-release builds such as Beta, here you can still download the 64bit version via the "All Languages and Platforms" link.

**Comment by squarewave** [comment]
Thanks, Alex. But do we ever get false positives from UA string detection? Does a browser running on a 32-bit Windows install ever have WOW64 or Win64 in the UA string? I think best effort here is better than nothing, assuming we don't get false positives.

I'm not concerned about being able to get a 64-bit Beta install. I'm more concerned about the Beta population's experience drifting further away from our Release population and thus becoming a less effective means of flushing out potential problems.

**Comment by alexgibson** [comment]
> Thanks, Alex. But do we ever get false positives from UA string detection? Does a browser running on a 32-bit Windows install ever have WOW64 or Win64 in the UA string? I think best effort here is better than nothing, assuming we don't get false positives.

I believe the Firefox/Installer team has some historic data here, although I don't have it to hand (or know if it's still accurate today). But this is why 64bit download links were never enabled by default, and we rely on the stub installer instead.

Some browsers today, such as Chrome, are phasing out the UA string altogether in favor of Client Hints, where this type of information isn't guaranteed either.

> I'm not concerned about being able to get a 64-bit Beta install. I'm more concerned about the Beta population's experience drifting further away from our Release population and thus becoming a less effective means of flushing out potential problems.

If this is a concern, then perhaps another alternative is to consider serving 64bit downloads as default for the Beta population? Alternatively, does the Beta build have a stub installer we could lean on?

**Comment by alexgibson** [comment]
Taking a peek, this seems to exist: https://download.mozilla.org/?product=firefox-beta-stub&os=win&lang=en-US

Would serving this stub installer link instead of the full installer help resolve the issue?

**Comment by alexgibson** [comment]
Oh huh, looks like it's the full installer for a reason: https://github.com/mozilla/bedrock/issues/9836

**Comment by alexgibson** [comment]
If we can't serve the stub installer because of the reasons cited in https://github.com/mozilla/bedrock/issues/9836, then perhaps some UA detection would be an action we could consider, although I'm still hesitant to start relying on a technology that browsers are starting to phase out/freeze.
