### ISSUE TITLE
AMO download attribution experiment

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10207]
## Description

The AMO team would like to run an experiment whereby Firefox download links on AMO point directly to /thanks, as opposed to /new (which is the current behaviour). To support this experiment they need to measure the effect it has on installs, but the /thanks page does not (currently) do the stub-attribution dance before triggering a Firefox download (it assumes you have done a mozorg page navigation before deciding to download).

We met to discuss the work/risks involved in adding stub attribution to /thanks and settled on the following:

- To satisfy the experiment we can build a custom /thanks page that gets triggered by a specific query param (TBD). Making this available via a custom page / parameter lowers the risk of this breaking the download funnel, and confines the new logic only to those who enter into the experiment.
- The custom page can look exactly the same as the current /thanks page, but can have some bespoke JS that will attempt to make a stub attribution call before triggering a download.

If the experiment proves successful, then we can work toward a plan to add this logic to the regular / thanks page.

---

#### Success Criteria
- [x] A custom /thanks page is available via a specific query param (TBD)
- [x] Custom page will make a stub attribution call before triggering a Firefox download (if visitor is on Windows)

**Comment by bobsilverberg** [comment]
Thanks for filing, @alexgibson! When you say the custom /thanks page will be available via a specific query param, does that mean that the URL will remain /thanks, and that we'll be passing the custom query param to that URL, or will it be an entirely different URL (e.g., /amo-thanks)?

We would intend to pass all of the other query params we are currently using for the download link to this new URL, and would expect them to continue to work for GA and telemetry. Specifically, those are:
- experiment
- variation
- utm_campaign
- utm_content
- utm_medium
- utm_source
- utm_term

**Comment by alexgibson** [comment]
@bobsilverberg I propose we use a query param on the regular /thanks URL, something similar to:

https://www.mozilla.org/firefox/download/thanks/?source=amo (open to other suggestions if something else might be better)

You can still pass along any other params you need here to attribute your experiment.

**Comment by bobsilverberg** [comment]
Thanks @alexgibson. I have a question regarding IE<=9, which you have indicated should be excluded from using this new URL. The number of users we see on IE<=9 is extremely small (e.g., 40 over a 2 week period), plus we do not support IE at all on AMO and know that the site has rendering issues for anyone on IE. For these reasons we intend to simply ignore this issue, rather than add code to address it.

If we do send someone to the new /thanks page who is on IE<=9, even though the automatic download will fail, is it still possible for them to download manually from that page? For example, would there be a button or a link somewhere they could use to download? We are curious about exactly what they might experience.

**Comment by alexgibson** [comment]
IE visitors on older browsers should still see this notification:

![image](https://user-images.githubusercontent.com/400117/120291318-14e29a80-c2bb-11eb-8d5d-2bb88da9eee5.png)

Clicking "Try downloading again" will take them to where they have to manually choose the right download: https://www.mozilla.org/en-US/firefox/all/

**Comment by bobsilverberg** [comment]
Thank you @alexgibson

**Comment by alexgibson** [comment]
@bobsilverberg sorry this has taken me a while to get round to. I've submitted a pull request for this work, and we'll try and get it reviewed soon (we're a little under staffed right now, but hopefully it shouldn't take too long).

Some notes that may be of interest to you:

- The experiment URL will be https://www.mozilla.org/en-US/firefox/download/thanks/?xv=rtamo
- Only the `xv=rtamo` is required to trigger the custom logic. You can pass in any of the other additional stub attribution params to this URL as you see fit.
- The experiment template will trigger for /en-US/ locale only.
- The logic will wait for up to a maximum of 5 seconds for both GA and Stub Attribution to load before starting the download. This means that if a visitor is on a slow connection and they exceed this threshold, stub attribution data will not be added to the download link. If we ever roll this out as a new feature, then this is something I think we'd need to keep a careful eye on to make sure we're not losing out on too many installs.

If you have any questions on any of the above, please let me know. Thanks

**Comment by bobsilverberg** [comment]
> @bobsilverberg sorry this has taken me a while to get round to. I've submitted a pull request for this work, and we'll try and get it reviewed soon (we're a little under staffed right now, but hopefully it shouldn't take too long).
>

Thanks @alexgibson!
 
> Some notes that may be of interest to you:
> 
> * The experiment URL will be [mozilla.org/en-US/firefox/download/thanks/?xv=rtamo](https://www.mozilla.org/en-US/firefox/download/thanks/?xv=rtamo)
>

This is fine, but the name is a bit misleading as this actually has nothing to do with RTAMO. This link might be in a header on AMO, for example, in which case RTAMO will not apply. I think it's fine to just leave this as is for the experiment, but if we end up wanting to implement something similar permanently we should change the name of the `xv` param.
 
> * Only the `xv=rtamo` is required to trigger the custom logic. You can pass in any of the other additional stub attribution params to this URL as you see fit.
>

Perfect!
 
> * The experiment template will trigger for `/en-US/` locale only.
>

This isn't something we discussed. This will require a change in our experiment infrastructure because we will want to exclude anyone not using `en-US` from the experiment. This is actually a feature we had planned to implement, just not necessarily before running this experiment. How important is it from the bedrock side that this be restricted to `en-US` users?

@jvillalobos Do you think it's okay for us to run the experiment only for en-US users? I imagine that will still give us a pretty big audience to draw upon.
 
> * The logic will wait for up to a maximum of 5 seconds for both GA and Stub Attribution to load before starting the download. This means that if a visitor is on a slow connection and they exceed this threshold, stub attribution data will not be added to the download link. If we ever roll this out as a new feature, then this is something I think we'd need to keep a careful eye on to make sure we're not losing out on too many installs.
> 

Is it possible to have some sort of instrumentation that would allow us to measure how often this happens?

**Comment by alexgibson** [comment]
> This is fine, but the name is a bit misleading as this actually has nothing to do with RTAMO. This link might be in a header on AMO, for example, in which case RTAMO will not apply. I think it's fine to just leave this as is for the experiment, but if we end up wanting to implement something similar permanently we should change the name of the xv param.

Ok, I can easily enough change this to just `amo`.

> This isn't something we discussed. This will require a change in our experiment infrastructure because we will want to exclude anyone not using en-US from the experiment. This is actually a feature we had planned to implement, just not necessarily before running this experiment. How important is it from the bedrock side that this be restricted to en-US users?

From bedrock's side, limiting this to en-US only will make this experiment code easier to reason about, as some locales still get served a different / older thanks page template.

> Is it possible to have some sort of instrumentation that would allow us to measure how often this happens?

I can include a couple of GA events to log timeouts, sure.

**Comment by jvillalobos** [comment]
> @jvillalobos Do you think it's okay for us to run the experiment only for en-US users? I imagine that will still give us a pretty big audience to draw upon.

Yes, limiting to `/en-US/` should be fine for this.

**Comment by bobsilverberg** [comment]
@alexgibson Just FYI, we have everything in place on our side for the experiment, including limiting it to `en-US` users.

**Comment by bobsilverberg** [comment]
@alexgibson Just checking in to see where we are with this. We would like to run the experiment as soon as bedrock is able to handle it. We have other experiments in our backlog, and might consider running a different one first, depending on the projected timing of this.

**Comment by alexgibson** [comment]
@bobsilverberg this is currently in the queue for code review, we'll try and get to it as soon as we can. Sorry the end of the quarter was busy and we're a little short-staffed currently. Thanks for your patience.

**Comment by alexgibson** [comment]
@bobsilverberg this is now in production. Please test before launching your experiment and let me know if you run into any issues. Thanks again https://www.mozilla.org/en-US/firefox/download/thanks/?xv=amo
