### ISSUE TITLE
Most of the "Learn more" links on https://www.mozilla.org/en-US/about/manifesto/ are broken or out of date

### ISSUE THREAD

**Issue by globau** [mozilla/bedrock#10210]
I was hoping to share our manifesto with friends, thought I'd give it a quick re-read before I did so.

Unfortunately most of the "Learn more" links on https://www.mozilla.org/en-US/about/manifesto/ are broken or out of date.

### Principle 1

- <a href="http://openbadges.org/">Use Open Badges to share your skills and interests</a>
  - ✅
- <a href="http://mozillascience.org/">Explore how the web impacts science</a>
  - ❌ mozillascience.org no longer exists
- <a href="https://opennews.org/getinvolved/">Learn about open source code in journalism</a>
  - ✅

### Principle 2

- <a href="https://blog.mozilla.org/netpolicy/">Read about open internet policy initiatives and developments</a>
  - ✅
- <a href="https://teach.mozilla.org/web-literacy/participate/open-practice/">Explore how to help keep the web open</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 3

- <a href="https://blog.mozilla.org/blog/2014/04/09/firefox-os-and-medic-mobile-use-the-web-to-connect-the-world-to-healthcare/">See how the web can connect the world to healthcare</a>
  - ❌ Firefox OS is dead
- <a href="https://teach.mozilla.org/web-literacy/read/navigate/">Explore how the web works</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 4

- <a href="https://foundation.mozilla.org/internet-health/">See how Mozilla works to put your privacy first</a>
  - ✅
- <a href="https://blog.mozilla.org/netpolicy/">Read about developments in privacy and data safety</a>
  - ✅
- <a href="https://teach.mozilla.org/web-literacy/participate/protect/">Learn more about how to protect yourself online</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 5

- <a href="https://teach.mozilla.org/tools/">Use these free tools to teach the web</a>
  - ❌ teach.mozilla.org no longer exists
- <a href="https://teach.mozilla.org/web-literacy/write/compose/">Learn about creating and curating content for the web</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 6

- <a href="http://ascendproject.org/">Add new voices to open source technology</a>
  - ❌ http://ascendproject.org/ (note http only, not https) redirects to http://mozilla.github.io/ascendproject/ which redirects to http://ascendproject.org/
- <a href="https://support.mozilla.org/kb/how-do-i-turn-do-not-track-feature">Set your Do Not Track preference</a>
  - ✅
- <a href="https://teach.mozilla.org/web-literacy/read/navigate/">Understand the web ecosystem</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 7

- <a href="https://teach.mozilla.org/web-literacy/participate/open-practice/">Explore how open practices keep the web accessible</a>
  - ❌ teach.mozilla.org no longer exists
- <a href="https://teach.mozilla.org/web-literacy/write/remix/">Learn how to remix content to create something new</a>
  - ❌ teach.mozilla.org no longer exists
- <a href="https://teach.mozilla.org/web-literacy/write/code/">Learn how to maximize the interactive potential of the web</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 8

- <a href="https://groups.google.com/forum/#!forum/mozilla.governance">Participate in our governance forum</a>
  - ✅
- <a href="/en-US/contribute/">Join us as a volunteer</a>
  - ✅
- <a href="https://teach.mozilla.org/web-literacy/skills/">Learn how to collaborate online</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 9

- <a href="https://addons.mozilla.org/firefox/addon/lightbeam-3-0/">Visualize who you interact with on the web with Lightbeam</a>
  - ❌ [Lightbeam is no longer maintained](https://support.mozilla.org/en-US/kb/lightbeam-extension-firefox-no-longer-supported) (since October 2019)
- <a href="https://teach.mozilla.org/web-literacy/participate/share/">Learn about creating web resources with others</a>
  - ❌ teach.mozilla.org no longer exists

### Principle 10

- <a href="https://teach.mozilla.org/events/">Host or join a Maker Party</a>
  - ❌ teach.mozilla.org no longer exists
- <a href="https://teach.mozilla.org/web-literacy/skills/">Learn how to build online collaboration skills</a>
  - ❌ teach.mozilla.org no longer exists

**Comment by alexgibson** [comment]
Thank you for taking the time to capture all this, adding to our intake board 💯

**Comment by alexgibson** [comment]
It looks like we don't have any alternative links for this issue yet, so rather than let it sit for a long time I think it's probably best we remove the links for now, and update the page later once we have fresh content.
