### ISSUE TITLE
homepage cards update for MR1

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10212]
the top cards section on the homepage of Mozilla.org will be refreshed for MR1 launch.

**Comment by stephaniehobson** [comment]
Card content and links are here: https://docs.google.com/spreadsheets/d/1Fsx_b-Vs0GOyLi_MoTBK_ZUdoNWsN2L76EUjX2l1aa8/edit#gid=633567359 (Mozilla only)
