### ISSUE TITLE
"Get the Firefox app" button on /firefox/mobile-promo/ is broken

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10215]
## Description

The main call-to-action button on /firefox/mobile-promo/ is broken.

### Steps to reproduce

1.) Visit https://www.mozilla.org/en-US/firefox/mobile-promo/
2.) Click on either of the "Get the Firefox app" buttons.

### Expected result

Not entirely sure, a modal should open with send-to-device?

### Actual result

Nothing happens.

### Environment

Firefox Nightly

**Comment by alexgibson** [comment]
Looking in GA, this page has (fortunately) had next to no traffic in the past year. I'm not sure where it originates, or why it's loading files from the /firefox/welcome/4/ page (this is probably the source of the breakage).

@slightlyoffbeat Can we just retire this page?

**Comment by craigcook** [comment]
Looks like this page was part of an experiment last April (https://github.com/mozilla/bedrock/pull/8816) and began life as a copy of welcome/4 ... but welcome/4 changed in https://github.com/mozilla/bedrock/commit/d9602db5d1719271d8e9c92d6b8717f2a2565c9c#diff-18666bfc979fbd1e351835e281e8bf2fa0e310f5aa92fc5690d5ae685be4ced7 to remove the modal and use the inline widget but this stale copy wasn't updated.

I assume that experiment is long over and the pages probably need to be deleted.

**Comment by alexgibson** [comment]
Ah! Yeah we can probably retire `firefox/privacy-by-default`, and `firefox/privacy-tools` as well 👍

**Comment by slightlyoffbeat** [comment]
These all look like dead pages so we should remove.

I just sent a note to the engineering manager of the team that originally built/requested to confirm that we can remove.

**Comment by slightlyoffbeat** [comment]
Confirmed that these pages are no longer in use and all three can be removed.
