### ISSUE TITLE
Migrate VPN blog posts to www

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10224]
We want to redirect the evergreen vpn blog posts to /products/vpn/ so they rank better long term.

****

This can use a layout similar to:
https://www.mozilla.org/en-US/firefox/features/block-fingerprinting/

We should design a template that will have the VPN Look & Feel

**** 

Brief:

https://docs.google.com/document/d/1PDVv1I-jkTFvRX-jYDtPhgn9Zhq16EUUZS5EH7hJjjM/edit?usp=sharing

****
Success Criteria
- [x] Design template to use for all pages
- [x] Code template to use for all pages
- [x] Code pages
- [x] Link to FAQ on homepage
- [ ] Launch pages (Date to be provided by Rebecca)
- [ ] Redirect the blog posts to www when they are online

**Comment by slightlyoffbeat** [comment]
@rraue Do we need a landing page for these types of posts, similar to the features landing page? Or is the scope of this project only the pages?

**Comment by rraue** [comment]
The only additional thing to do is linking these pages where appropriate from the faq section of the vpn homepage. Then for now I do not think we need an overview page. 

Even if not all pages (tbd) will be linked from the homepage, they will link to each other in content and subnav, so they will be crawlable.

Once we have more and more explainers we should create a informative and fun faq page that links out to all these explainers, but not just as an overview.

**Comment by rraue** [comment]
@craigcook 

Urls for the pages:
- https://blog.mozilla.org/firefox/what-is-an-ip-address/ -> /products/vpn/more/what-is-an-ip-address/
- https://blog.mozilla.org/firefox/vpn-or-proxy/ -> /products/vpn/more/vpn-or-proxy/
- https://blog.mozilla.org/firefox/vpns-explained/ -> /products/vpn/more/what-is-a-vpn/
- https://blog.mozilla.org/firefox/when-to-use-a-vpn/ -> /products/vpn/more/when-to-use-a-vpn/

After Rebeccas Test is finished: In all four cases the original blog post should be directly redirected to the new url and a second redirect is needed for the new urls. So if I see this right we need 8 rewrites in the blog:

- https://blog.mozilla.org/firefox/what-is-an-ip-address/ -> /products/vpn/more/what-is-an-ip-address/
- https://blog.mozilla.org/en/internet-culture/what-is-an-ip-address/ -> /products/vpn/more/what-is-an-ip-address/

- https://blog.mozilla.org/firefox/vpn-or-proxy/ -> /products/vpn/more/vpn-or-proxy/
- https://blog.mozilla.org/en/privacy-security/vpn-or-proxy/ -> /products/vpn/more/vpn-or-proxy/

- https://blog.mozilla.org/firefox/vpns-explained/ -> /products/vpn/more/what-is-a-vpn/
- https://blog.mozilla.org/en/privacy-security/vpns-explained/ -> /products/vpn/more/what-is-a-vpn/

- https://blog.mozilla.org/firefox/when-to-use-a-vpn/ -> /products/vpn/more/when-to-use-a-vpn/
- https://blog.mozilla.org/en/products/mozilla-vpn/when-to-use-a-vpn/ -> /products/vpn/more/when-to-use-a-vpn/
If some of these articles are translated (not sure how to check) we need to rewrite the translations as well.

**Comment by rraue** [comment]
@craigcook waiting for review from Rebecca for title and description. I had to change them a bit from what they are currently on the blog:

https://blog.mozilla.org/firefox/what-is-an-ip-address/ -> /products/vpn/more/what-is-an-ip-address/
**title:** What is an IP address? 
**decription:** Mozilla answers all of your questions about IP addresses from what is an IP address, to how it works, and if you should hide it.

https://blog.mozilla.org/firefox/vpn-or-proxy/ -> /products/vpn/more/vpn-or-proxy/
**title:** The difference between a VPN and a web proxy
**decription:** VPNs and proxies are solutions for online privacy and security. Here’s how these protect you and how to choose the best option.


https://blog.mozilla.org/firefox/vpns-explained/ -> /products/vpn/more/what-is-a-vpn/
**title:** What is a VPN? 
**decription:** Get answers to nine common questions about VPNs so you feel informed on what they do, when to use one and why.


https://blog.mozilla.org/firefox/when-to-use-a-vpn/ -> /products/vpn/more/when-to-use-a-vpn/
**title:** 5 reasons you should use a VPN
**decription:** Here are five situations a trustworthy VPN will come in handy that you might not have considered. Close the gap in your online security with Mozilla VPN.

**Comment by rraue** [comment]
Here is a mockup of how the pages will look like.
- Above the fold with less white space on top from https://www.mozilla.org/en-US/products/vpn/desktop/
- Text area like on https://www.mozilla.org/en-US/firefox/features/block-fingerprinting/

![mockup-vpn-articles](https://user-images.githubusercontent.com/36700618/120495974-77bc5a80-c3bd-11eb-9994-4974736cb52f.jpg)

**Comment by rraue** [comment]
@craigcook I updated the links on vpn homepage: https://docs.google.com/document/d/1vWD7GX13fasCkLudPsdZN1-u24EEzLmWkuFNIZ4WiKo/edit?usp=sharing No string changes needed, the only page that doesnt fit is the proxy page but that one will be crawlable via the subnav on the other three pages.

**Comment by craigcook** [comment]
https://www-demo4.allizom.org/en-US/products/vpn/more/what-is-a-vpn/
https://www-demo4.allizom.org/en-US/products/vpn/more/what-is-an-ip-address/
https://www-demo4.allizom.org/en-US/products/vpn/more/when-to-use-a-vpn/
https://www-demo4.allizom.org/en-US/products/vpn/more/vpn-or-proxy/
