### ISSUE TITLE
Update copy for daylight banners.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10226]
Daylight is no longer new.

This banner still drives significant installs from /firefox. Short term solution is to update the copy to no longer say "new".  Long term solution is to develop the native app banners (see: #10225)

Todo:

- [ ] Submit request/brief to creative to ask for new copy
- [ ] provide copy to developer
- [ ] update banner

**Comment by alexgibson** [comment]
I'm removing this banner as part of https://github.com/mozilla/bedrock/issues/10225, so closing as wontfix.
