### ISSUE TITLE
Create native-looking app banners for mobile users on /Firefox

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10225]
## Description

Last year we ran a test that tested native app banners

[Android Designs](https://docs.google.com/document/d/16W-gpAmN4ZE7WIYiUh3ux1-GisF_0VYrH-qqkVr4RZI/edit?usp=sharing)

[iOS designs](https://docs.google.com/document/d/1rhYim7UcdISepGMSnyiv7ekxrWdL7oBOr0v59YfcWjk/edit?usp=sharing)

---

#### Success Criteria
- [x] Remove Daylight banner from mozilla.org
- [x] Decide if we use native or html/css
- [x] Appears on /firefox. 
- [x] Switch to enable on homepage
- [x] shows correct banner based on operating system (android vs iOS)
- [x] attribution is set up
- [x] events to track clicks on android vs iOS

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/10111

Perhaps we can leverage the code that this experiment used here ^

**Comment by alexgibson** [comment]
Looks like the code for these variations might still be in bedrock from a past experiment: https://github.com/mozilla/bedrock/tree/master/bedrock/firefox/templates/firefox/home/exp

**Comment by alexgibson** [comment]
Gonna pick this one up

**Comment by alexgibson** [comment]
@slightlyoffbeat which variation was the winner here? I can't seem to find any link to the data

**Comment by slightlyoffbeat** [comment]
For Android, the version without stars was a narrow winner:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/2030656/129631595-abf5563d-9cf9-4e1f-996d-e4cf8554f40b.png">

For Android we can assume the same for now.

Here are some codepen links with the code used for the convert test.. I know this doesn't translate directly to what we can use in bedrock, but perhaps it will be useful:

https://codepen.io/mozilladevelopers/pen/wvdbgEj

https://codepen.io/mozilladevelopers/pen/bGWygxK

**Comment by alexgibson** [comment]
Ok thanks,

> For Android we can assume the same for now.

I'm assuming you meant iOS here, so both versions will match visually but point to the respective app stores.

**Comment by alexgibson** [comment]
The Adjust links I'm using for this are:

- https://app.adjust.com/2uo1qc?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dorg.mozilla.firefox&campaign=www.mozilla.org&adgroup=mobile-app-banner (Android)
- https://app.adjust.com/2uo1qc?redirect=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Ffirefox-private-safe-browser%2Fid989804926&campaign=www.mozilla.org&adgroup=mobile-app-banner (iOS)

**Comment by alexgibson** [comment]
@slightlyoffbeat whilst working on this I noticed we already have a similar mobile banner to this on platform page such as https://www.mozilla.org/en-US/firefox/windows/

<img src="https://user-images.githubusercontent.com/400117/129722547-ffd4b9d4-f337-465e-92ac-b84250b1e2e5.png" alt="image" width="300">

Do we want to replace this older banner with this new version whilst we're at it? It seems a little confusing to me having two very similar things in the codebase. Thoughts?

**Comment by slightlyoffbeat** [comment]
Oops, I meant iOS, thanks.

Yes, we should just replace the older banner as well. We tested a similar banner to the screenshot above and the native-looking banners always out performed.

**Comment by alexgibson** [comment]
Sounds good 👍

**Comment by alexgibson** [comment]
Screenshot for iOS:

<img src="https://user-images.githubusercontent.com/400117/129875965-23fd81fc-e898-4a02-91dc-92d260a2fb1f.png" alt="image" width="460">

**Comment by alexgibson** [comment]
@slightlyoffbeat please see comments below:

> @alexgibson screenshot for ios and android are the same. Just confirming that it is a blue text link for iOS

My understanding was the designs for each banner would be the same. They differ in that one says "Free in Google Play", and the other says "Free in the App Store". But I missed that the button should look different for iOS - I'll make sure to add this.

> Can you also confirm this will appear on the homepage? (I know we turned off the daylight banner)

I'll make sure to add this as well, thanks.

**Comment by slightlyoffbeat** [comment]
@alexgibson Thanks! Yes the blue text for iOS is a more common pattern for iOS users, so if we can lets use that.
