### ISSUE TITLE
Allow vpn.mozilla.org to pass FXA params

### ISSUE THREAD

**Issue by birdsarah** [mozilla/bedrock#10241]
In #10213 we allow vpn.mozilla.org to pass through flow params if experiment params are present (https://github.com/mozilla/bedrock/pull/10213/files#diff-59964e1536d4ba55340d0ca8b047b434ae1d25e380aea2094b9e6a825cd94db6)

In this issue I'd like to discuss allowing vpn.mozilla.org to always be able to pass fxa flow params (flow_id, flow_begin_time, device_id) to the vpn landing page and have them appended to outgoing links that point back to vpn.mozilla.org. 

This will enable us to see flows through the VPN ecosystem of applications (fxa, bedrock, guardian) and see where problems are occurring. 

cc @alexgibson

**Comment by alexgibson** [comment]
As far as I'm aware, there are no other FxA services that try to pass flow params back to mozorg. So I think allowing them to pass through (provided the values are well formatted) should be fairly low risk. Let's discuss further 👍

**Comment by alexgibson** [comment]
@birdsarah if you want to work on this, I _think_ all you need to do is delete this conditional block:

https://github.com/mozilla/bedrock/blob/master/media/js/base/fxa-utm-referral.js#L92-L111

You'll probably also need to update some tests in https://github.com/mozilla/bedrock/blob/master/tests/unit/spec/base/fxa-utm-referral.js

**Comment by birdsarah** [comment]
I can't self-assign, but I'm working on this.

**Comment by birdsarah** [comment]
I'm not working on this at the moment while we organize priorities at our end and echo and tcinotto are in charge of funnel work.

**Comment by alexgibson** [comment]
@birdsarah thanks for the update. Is this feature still useful? If so, I'll see if I can pick it up.

One question that did occur to me: how many sessions do you think would be referred back to bedrock on a daily basis that included these params? One thing we might need to be mindful of is that each of these URLs would be counted as a unique URL / cached page on our CDN. If the number of cached pages was of a really high volume, we might need to be careful not to inadvertantly DDoS ourselves.

**Comment by birdsarah** [comment]
Currently unclear to me. The subscription flow is about to change dramatically and Google In App Purchase is coming.

Additionally the data team should now be being more proactive in making sure the measurements that are needed happen.

Perhaps we should close for now and then we can pick it up later if the request comes from data team.

**Comment by alexgibson** [comment]
Works for me, thanks!
