### ISSUE TITLE
VPN pages should use logo assets from Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10243]
## Description

Now that Mozilla VPN logos have been added to Protocol's asset bundles (see https://github.com/mozilla/protocol/issues/663), we should update bedrock landing pages to use Protocol as the canonical source for VPN logos, and remove the assets in bedrock.

---

#### Success Criteria
- [ ] VPN pages use logo assets from Protocol.

**Comment by maureenlholland** [comment]
still exists in 3 files: https://github.com/mozilla/bedrock/search?q=vpn%2Flogo-with-wordmark

**Comment by reemhamz** [comment]
closed with https://github.com/mozilla/bedrock/pull/11100
