### ISSUE TITLE
Publish MR1 homepage cards 

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#10240]
Homepage card updates are on dev and staging. They need to go to prod Tuesday morning but not until after the blog posts publish at 6am Pacific.

MJ will be on Slack if you have questions.

To publish: pull down the latest from the www-admin repo and then `git push origin master:prod`.

**Comment by alexgibson** [comment]
PR for banner and imae updates: https://github.com/mozmeao/www-config/pull/383

**Comment by alexgibson** [comment]
Blog posts seem to be live on https://www.allizom.org/en-US/, so going to push to prod.

**Comment by alexgibson** [comment]
Looks good on https://bedrock-prod.gcp.moz.works/en-US/. Prod should update shortly as soon as caches expire
