### ISSUE TITLE
Over-scroll background color on whats new page should match background.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#10251]
## Description

On Mac, the rubber-banding effect that happens when you over-scroll shows a strip of white on the wnp (https://www.mozilla.org/en-US/firefox/91.0a1/whatsnew/all/?oldversion=90.0a1). I noticed the `html` and `body` tags both have a `background: #fff`, I think it would be better to have the over-scroll color reflect the background color of the rest of the page so it is more seamless.

**Comment by Prasanna0908** [comment]
Hey, I am a beginner at open source. Can you guide me on how to proceed further?

**Comment by nikhils4** [comment]
Is this issue still open to work on? @amychurchwell

**Comment by amychurchwell** [comment]
> Hey, I am a beginner at open source. Can you guide me on how to proceed further?

Hi @Prasanna0908, sorry for the delayed response. (I am not an active contributor on this repository anymore.) Are you still interested in working on this?

If Prasanna is no longer interested, I'll assign you @nikhils4. We should give them a chance to reply seeing as they were the first to ask and I missed it.

**Comment by nikhils4** [comment]
Sure @amychurchwell, sounds good. Please tag me here once you are sure that you can assign me this.

**Comment by amychurchwell** [comment]
@nikhils4 Are you still interested in working on this?

**Comment by nikhils4** [comment]
Sure @amychurchwell, can you please give me more information about this bug?

**Comment by amychurchwell** [comment]
@nathan-barrett would you or someone else on the websites team be able/willing to mentor this bug? I worry it will slip past my radar again as I am not super active on GitHub these days.

**Comment by nathan-barrett** [comment]
@amychurchwell Yup - on it. Thanks!

**Comment by nathan-barrett** [comment]
Hi @nikhils4 - I'd suggest taking a look through the docs [here](https://bedrock.readthedocs.io/en/latest/install.html) and go through the installation and the "Making it run" sections. Bedrock uses jinja templates which you can read more about [here](https://jinja2docs.readthedocs.io/en/stable/templates.html#). The templates for this issue can be found in `bedrock/firefox/templates/firefox/whatsnew` and the css files are located in the `media/css/firefox/whatsnew`.

Let me know if you have any questions, more than happy to help. Thanks for working on this!

**Comment by nikhils4** [comment]
Thank you so much @nathan-barrett for the quick reply, will go through the links 😄

**Comment by nikhils4** [comment]
@nathan-barrett Just a heads up on the status, I have done the setup and seems to work just fine locally, I am on it and will be giving a fix soon. 🤞🏻

**Comment by alexgibson** [comment]
This bug has been hanging out for some time, and despite some interest no one submitted a patch yet. I'm going to go ahead and make a fix for this so we can close it out. 

Thanks for the interest
