### ISSUE TITLE
WNP 90 for EU

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10270]
## Description

Card for NA is tracked here: #10269

We will have a new WNP for Firefox 90. The focus of this page is not yet determined.

---

#### Success Criteria

- [ ] Proper attribution for any signups that originate from this page
- [ ] ~(if pocket) Pocket team (back-end) is properly notified of any URLs that we will direct traffic towards.~

**Comment by alexgibson** [comment]
Brief (Mozilla access only) https://docs.google.com/document/d/1KUYIne116bry16HJ8EyddZaELFTGqoyA_ZX5QvPWoAk/edit?usp=sharing

**Comment by alexgibson** [comment]
Figma: https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/Firefox-WNP-EU-(Copy-June-2021)?node-id=2%3A30

**Comment by alexgibson** [comment]
Demo: https://www-demo1.allizom.org/de/firefox/90.0/whatsnew/all/
