### ISSUE TITLE
Add VPN to homepage of Mozilla.org.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10285]
## Description

Its time to add VPN to the homepage of Mozilla.org.

Target language: EN-*

Visuals available here: https://trello.com/c/Eueo7kaQ/366-add-vpn-to-mozillaorg-homepage-wireframe
Copy: The privacy-focused headline, subhead, and CTA [in this document](https://docs.google.com/document/d/1RTEJoSg5g7NcVRyaQ7tnctlZO5NpXdyVLN_KMvO_0Rs/edit?usp=sharing).

---

#### Success Criteria
- [x] Design & Copy approved by creative studio
- [x] coded and on demo
- [ ] launched

**Comment by slightlyoffbeat** [comment]
The visuals are already in use on mozilla.org, so there should be no need to provide.

**Comment by slightlyoffbeat** [comment]
@alexgibson This is planned for en-* only, but the EU team may want to consider for FR/DE as well?

**Comment by alexgibson** [comment]
> @alexgibson This is planned for en-* only, but the EU team may want to consider for FR/DE as well?

I asked Jen on this and she says thanks but she doesn't think the DE/FR pages need this. They plan to use cards a little differently in the future (focusing on surfacing products rather than editorial content).
