### ISSUE TITLE
Lockwise still not removed on bottom of /firefox

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla/bedrock#10299]
## Description

Lockwise was supposed to be removed from all pages, including /firefox, in favor of Mozilla VPN. While this mostly happened, the Lockwise logo is still visible on the bottom of /firefox.

### Steps to reproduce

1. Open https://mozilla.org/en-US/firefox/

2. Scroll down.

3. Observe that bottom part with all logos does not have VPN and instead has Lockwise.

### Expected result

The bottom part should have Mozilla VPN, not Lockwise.

### Actual result

The bottom part shows Lockwise instead of Mozilla VPN.

### Environment

Firefox Nightly 91.0 build 2015817867 on Android 11.

![Screenshot_20210622-225453.png](https://user-images.githubusercontent.com/17863082/123028530-7c1cd780-d3ad-11eb-85e1-47afa9011e8a.png)

**Comment by alexgibson** [comment]
Thanks for the report

**Comment by Prasanna0908** [comment]
Hey, can I proceed further with this issue, and also where can I find the correct logo?

**Comment by craigcook** [comment]
Sorry @Prasanna0908, we've assigned this to another team member.
