### ISSUE TITLE
Update VPN subscription links to point to FxA

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10333]
## Description

To support the VPN team's funnel optimisation work in H2, we'll need to update the VPN subscription links to point directly to FxA instead of vpn.mozilla.org.

- Target date is August 18th.
- URL specs are to be provided by the VPN team.
- New format will likely need to be behind a feature switch for pre-launch QA.

---

#### Success Criteria
- [x] Subscription links are updating to point directly to FxA.

**Comment by chenba** [comment]
The new funnel optimization flow won't have new urls for the plans.

**Comment by alexgibson** [comment]
The above comment is incorrect, bedrock does need new subscription URLs (confirmed with Sarah Bird)

**Comment by chenba** [comment]
I see that currently the plan URLs are in the format of https://vpn.mozilla.org/r/vpn/subscribe/products/prod_FvnsFHIfezy3ZI?plan=price_1Iw85dJNcmPzuWtRyhMDdtM7 plus some additional query params.  To use direct FxA urls, change to https://accounts.firefox.com/subscribe/products/prod_FvnsFHIfezy3ZI?plan=price_1Iw85dJNcmPzuWtRyhMDdtM7 plus some additional query params.

**Comment by alexgibson** [comment]
Thanks 👍

**Comment by alexgibson** [comment]
@chenba for our staging server used for QA, would the appropriate domain to use here be https://stable.dev.lcip.org/ ?

**Comment by chenba** [comment]
FxA stage is at https://accounts.stage.mozaws.net/

**Comment by alexgibson** [comment]
@chenba both of the below URLs give me a 404. Do you know if there is an additional dependency we need to wait on here before these links will become active?

https://accounts.firefox.com/subscribe/products/prod_FiJ42WCzZNRSbS?plan=price_1J0Y1iKb9q6OnNsLXwdOFgDr
https://accounts.stage.mozaws.net/subscribe/products/prod_FiJ42WCzZNRSbS?plan=price_1J0Y1iKb9q6OnNsLXwdOFgDr

**Comment by chenba** [comment]
@alexgibson Oh very sorry, replace `subscribe` with `subscriptions` in the URLs.
