### ISSUE TITLE
Add vanity URL for VPN product

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#10335]
## Description

The VPN page lives at mozilla.org/products/vpn, but I find myself typing mozilla.org/vpn and hoping that that will take me to where I want to be. I propose we add a redirect from `/vpn` to `/products/vpn/`.

**Comment by pmac** [comment]
@reemhamz this should be a lot like https://github.com/mozilla/bedrock/pull/9572

**Comment by reemhamz** [comment]
Created a redirect that enables a user to add `/vpn` at the end of the mozorg URL to redirect them directly to `/products/vpn`
