### ISSUE TITLE
Limit RTAMO attribution to AMO referrals

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/bedrock#10337]
## Description

Ignore attribution for RTAMO if the referral wasn't from addons.mozilla.org, using a referer header check.

RTAMO attribution can be identified by the presence of  a `utm_content` param with  `rta%3A<base64_string>`. See any add-ons details page for an example link, using a non-firefox browser. 

---

#### Success Criteria
- [x] RTAMO attribution should be present if the user started from AMO and all other data validation is ok.
- [x] RTAMO attribution should be ignored if the user did not start on AMO.

**Comment by alexgibson** [comment]
Picking this up 👍

**Comment by alexgibson** [comment]
The changes for this are now in production
