### ISSUE TITLE
Logos on error pages are the wrong size and misaligned

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#10357]
## Description

At some point the Mozilla and Firefox logos at the top of the error page template got messed up, perhaps due to upstream changes in Protocol assets.

![image](https://user-images.githubusercontent.com/205591/127520570-38e6b3ce-dc6b-4da5-adad-5c3f512e1a2e.png)

### Steps to reproduce

https://www.mozilla.org/404/

Go to an error page. Look at the logos. They're messed up.

### Expected result

Logos shouldn't be messed up.

### Actual result

They're messed up.

**Comment by craigcook** [comment]
It looks like just the Mozilla logo is too big and that's throwing off the alignment of the Firefox logo. The Mozilla logo is an SVG but the `img` element has no size attributes so it's just showing at its native size. I think we could just size it down to fit.

**Comment by AtharvaParkale** [comment]
Can I work on this issue?

**Comment by craigcook** [comment]
I think the Mozilla logo just needs to be scaled down to roughly the same height as the Firefox logo.

**Comment by AtharvaParkale** [comment]
> I think the Mozilla logo just needs to be scaled down to roughly the same height as the Firefox logo.

Noted !
Will do the needful👍

**Comment by AtharvaParkale** [comment]
> I think the Mozilla logo just needs to be scaled down to roughly the same height as the Firefox logo.

![image](https://user-images.githubusercontent.com/71985594/128757041-5dd1a6fd-5a1d-40d2-81af-f735d914cc0f.png)
Getting this error while running it locally

**Comment by AtharvaParkale** [comment]
> > I think the Mozilla logo just needs to be scaled down to roughly the same height as the Firefox logo.
> 
> ![image](https://user-images.githubusercontent.com/71985594/128757041-5dd1a6fd-5a1d-40d2-81af-f735d914cc0f.png)
> Getting this error while running it locally

I have python installed in my system

**Comment by AtharvaParkale** [comment]
Sure, I will try this 👍🏻
Thankyou !

**Comment by AtharvaParkale** [comment]
![image](https://user-images.githubusercontent.com/71985594/129074587-3ab24bbb-caaf-4da3-832c-d4161210090d.png)

**Comment by AtharvaParkale** [comment]
Hey,
Made these changes......should I create a pull request?

**Comment by AtharvaParkale** [comment]
This is how it looks after proper alignment.
![image](https://user-images.githubusercontent.com/71985594/129078653-68490ae8-0543-480e-adb7-9ed8bb0818c9.png)

**Comment by craigcook** [comment]
Looks great! Please submit a pull request and we'll review it. Thanks!

**Comment by AtharvaParkale** [comment]
> Looks great! Please submit a pull request and we'll review it. Thanks!

Okay

**Comment by AtharvaParkale** [comment]
Should I create a different branch after forking?

**Comment by AtharvaParkale** [comment]
> Looks great! Please submit a pull request and we'll review it. Thanks!

Sir I have created the pull request plz do review it

**Comment by Ayushsunny** [comment]
Hey @craigcook as I can see, no one has created any PR related to this issue.
So, can I work on this?

**Comment by craigcook** [comment]
> Hey @craigcook as I can see, no one has created any PR related to this issue.
> So, can I work on this?

Sorry, @AtharvaParkale is working on this in https://github.com/mozilla/bedrock/pull/10383 (which I still need to review, apologies for the delay).

**Comment by Ayushsunny** [comment]
> > Hey @craigcook as I can see, no one has created any PR related to this issue.
> > So, can I work on this?
> 
> Sorry, @AtharvaParkale is working on this in #10383 (which I still need to review, apologies for the delay).

Sorry, @craigcook I didn't went through that, my bad.

Can you please suggest to me if any other issue's are opened like this?
