### ISSUE TITLE
Document relevant Protocol component macros

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#10371]
## Description

We have a good chunk of components in Protocol that have parameters/macros, and sometimes, even unique parameters per component. This can lead us down a rabbit hole to figure out all relevant parameters we could use for any component, leading to feeling a little lost trying to use correct parameters, and confused with figuring out which each one means. 

For example, here are the parameters for a `Picto` component:
```
title,
heading_level,
image_url',
image_width,
body,
base_el
```

and for the `Split` component:
```
image_url,
include_highres_image,
block_class,
theme_class,
media_class,
```
--- 
Will be documenting the list of parameters for each component, along with an explanation here: https://docs.google.com/document/d/1Ux8iu8e7lbopwjogQywbCtbKAYuQoZW4Kkfj85WNL18/edit. Once done, will be writing this up, with proper formatting, for the [Bedrock docs](https://bedrock.readthedocs.io/en/latest/).

Find Protocol docs [here](https://protocol.mozilla.org/).

## Components to document:
- [x] Feature Card
- [x] Picto
- [x] Call Out
- [x] Split
- [x] Billboard
- [x] Card
- [ ] Card Layout

**Comment by Ayushsunny** [comment]
Hey @reemhamz actually I'm not getting this like what exactly I've to do here?
and also "https://docs.google.com/document/d/1Ux8iu8e7lbopwjogQywbCtbKAYuQoZW4Kkfj85WNL18/edit" this link is asking for some permission which I don't have.

**Comment by maureenlholland** [comment]
Feature Card

Name | Explanation | Required? | Default Value | Example
-- | -- | -- | -- | --
title | String indicating heading text (usually a translation id wrapped in ftl function) | No | None | title=ftl('firefox-home-firefox-browser')
ga_title | String used as an identifying name on a link for google analytics. Only used if link_url and link_cta are provided as well | No | None | ga_title='Firefox Windows'
image_url | Path to image location | Yes | N/A | image_url=’img/firefox/accounts/trailhead/value-respect.jpg’
class | String adding class(es) to the section tag | No | None | class=’mzp-l-card-feature-left-half t-mozvpn’
link_url | String or url helper function provides href value for cta link. Only used if link_cta is provided as well. | No | None | link_url=url('firefox.privacy.index')
link_cta | String indicating link text (usually a translation id wrapped in an ftl function). Only used if link_url is provided as well. | No | None | link_cta=ftl('ui-learn-more')
include_highres_image | Boolean that determines whether the image can also appear in high res | No | False | include_highres_image=True
l10n_image | Boolean to indicate if image has translatable text | No | False | l10n_image=True
aspect_ratio | String with an mzp class name indicating desired aspect ratio (adds class to section tag) | No | False | aspect_ratio='mzp-has-aspect-3-2'
heading_level | Number indicating heading level for title text. Should be based on semantic meaning, not presentational styling. | No | 2 | heading_level=3
media_after | Boolean to determine if image appears before or after text when stacked on mobile size screens | No | False | media_after=True

</div>

Picto

Name | Explanation | Required? | Default Value | Example
-- | -- | -- | -- | --
title | A string indicating the heading text of the card. Usually a Fluent file reference | No | None | title=ftl('misinformation-why-trust-firefox')
heading_level | Number indicating heading level for title text. Should be based on semantic meaning, not presentational styling. | No | 3 | heading_level=2
body | A boolean attribute. If true, it will show the contents of the card, if false, it will hide the contents. | No | False | body=True,
image_url | image location to be used. Start it off with ‘img/…’ | No | None | image_url='img/icons/mountain-purple.svg',
base_el | the element the content of the picto will be read as in HTML. For example, if the Picto macro is wrapped in a ul tag, the base_el would be an li tag. | No | div | base_el='li'
class | String adding class(es) to the base el tag | No | None | class='trust'
image_width | Number indicating width of image | No | 64 | image_width='153px'
include_highres_image | Boolean that determines whether the image can also appear in high res | No | False | include_highres_image=True
l10n_image | Boolean to indicate if image has translatable text | No | False | l10n_image=True
lazy_loading | Boolean to provide “lazy” value for “loading” attribute. This will be “eager” by default. Lazy loading defers fetching of images to a browser decision based on user scroll and connection. | No | False | lazy_loading=True

Call Out


Name | Explanation | Required? | Default Value | Example
-- | -- | -- | -- | --
title | String indicating heading text (usually a translation id wrapped in ftl function) | Yes | N/A | title=ftl('firefox-privacy-hub-read-the-privacy-notice-for')
desc | String indicating paragraph text (usually a translation id wrapped in ftl function) | No | None | desc=ftl('firefox-channel-test-beta-versions-of-firefox-ios')
class | String adding class(es) to the section tag | No | None | class='mzp-t-firefox ' + product_class
include_cta | Boolean indicating whether or not to include the body of the macro call (usually a mix of text and html) | No | False | include_cta=True
heading_level | Number indicating heading level for title text. Should be based on semantic meaning, not presentational styling. | No | 2 | heading_level=1

Split

id | String providing id to the section tag (usually if it needs to be used as an in-page link) | No | None | id='nextgen'
-- | -- | -- | -- | --
block_class | String providing class(es) to the section tag | No | None | block_class='mzp-l-split-reversed mzp-l-split-center-on-sm-md'
theme_class | String providing theme class(es) to a container div tag inside the section | No | None | theme_class='mzp-t-dark'
body_class | String providing class(es) to the body (text content) div inside the section | No | None | Not currently in use
image_url | Path to image location | No | None | image_url=’img/firefox/accounts/trailhead/value-respect.jpg’
media_class | String providing class(es) to the media div inside the section | No | None | media_class='mzp-l-split-h-center'
include_highres_image | Boolean that determines whether the image can also appear in high res | No | False | include_highres_image=True
l10n_image | Boolean to indicate if image has translatable text | No | False | l10n_image=True
image_alt | String providing alt text to the image | No | ‘’ | Not currently in use
media_after | Boolean to determine if image appears before or after text when stacked on mobile size screens | No | False | media_after=True
media_include | Path to video media | No | None | media_include='firefox/facebookcontainer/includes/video.html'

Billboard

Name | Explanation | Required? | Default | Example
-- | -- | -- | -- | --
title | String indicating heading text (usually a translation id wrapped in ftl function) | Yes | N/A | title=ftl('about-the-mozilla-manifesto')
ga_title | String providing value for data-link-name attribute on cta | Yes | N/A | ga_title='The Mozilla Manifesto',
desc | String indicating paragraph text (usually a translation id wrapped in ftl function) | Yes | N/A | desc=ftl('about-the-principles-we-wrote-in')
link_cta | String indicating link text (usually a translation id wrapped in an ftl function). | Yes | N/A | link_cta=ftl('about-read-the-manifesto')
link_url | String or url helper function provides href value for cta link. | Yes | N/A | link_url=url('mozorg.about.manifesto')
image_url | Path to image location | Yes | N/A | image_url='img/home/2018/billboard-healthy-internet.png'
include_highres_image | Boolean that determines whether the image can also appear in high res | No | False | include_highres_image=True
reverse | Uses default layout: mzp-l-billboard-rightReverse will switch to billboard (text) left | No | False | reverse=True
heading_level | Number indicating heading level for title text. Should be based on semantic meaning, not presentational styling. | No | 2 | heading_level=1

Card

Name | Explanation | Required? | Default | Example
-- | -- | -- | -- | --
title | String indicating heading text (usually a translation id wrapped in ftl function) | Yes | N/A | title=ftl('about-the-mozilla-manifesto')
ga_title | String providing value for data-link-name attribute on cta | Yes | N/A | ga_title='The Mozilla Manifesto',
desc | String indicating paragraph text (usually a translation id wrapped in ftl function) | Yes | N/A | desc=ftl('about-the-principles-we-wrote-in')
aspect_ratio | String indicating size/aspect ratio of the card (make sure to have it even if it’s in a defined Card Layout | No | N/A | aspect_ratio=’mzp-has-aspect-16-9’
link_url | String or url helper function provides href value for cta link. | Yes | N/A | link_url=url('mozorg.about.manifesto')
image_url | Path to image location | Yes | N/A | image_url='img/home/2018/billboard-healthy-internet.png'
include_highres_image | Boolean that determines whether the image can also appear in high res | No | False | include_highres_image=True
heading_level | Number indicating heading level for title text. Should be based on semantic meaning, not presentational styling. | No | 2 | heading_level=3

</div>

**Comment by maureenlholland** [comment]
Hi @Ayushsunny, thanks for letting us know about the permissions issue. I've added the google doc content as a comment above.

What we want to do is add a subsection to the bedrock docs under "[Developing on Bedrock](https://bedrock.readthedocs.io/en/latest/coding.html#)" called "Working with Protocol" to include this information.

We want to encourage contributors to use the Protocol macros for Bedrock development and that's easier to do if folks know they exist and have customizable parameter options. Feel free to open a PR referencing this issue to add that section to the docs!

**Comment by Ayushsunny** [comment]
Hello @maureenlholland I'm doing like this 

![Screenshot from 2021-09-02 11-34-17](https://user-images.githubusercontent.com/73520373/131790730-a47347b2-e552-49d4-b83a-2fee4e09dad4.png)

Am i going right ?

**Comment by maureenlholland** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/10416
