### ISSUE TITLE
The link “Tips for filing a bug” goes nowhere

### ISSUE THREAD

**Issue by fitojb** [mozilla/bedrock#10374]
## Description

Broken link to MDN Web Docs, which since its pivot to exclusively web-related content, seems like the wrong place to have Mozilla bug-filing information.

### Steps to reproduce

1. Go to https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly
2. Click “Tips for filing a bug” below the section “See something that isn’t working? Let us know.”
3. You will land on https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines, which is 404.

### Expected result

The link should work, perhaps linking to content at support.mozilla.org, wiki.mozilla.org or any other adequate place

### Actual result

The link is broken.

### Environment

Debian Bullseye, Firefox ESR 78.12.0 (64-bit)

**Comment by craigcook** [comment]
This has been fixed in https://github.com/mozilla/bedrock/commit/6eaa749606ab44b9bc07dd60114e82c9b62f3cc9
