### ISSUE TITLE
Create VPN info pages for Firefox product team

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10388]
## Description

The Firefox product team is going to be experimenting with ways to drive signups for VPN. They have requested the creation of a few new pages with specific copy and calls-to-action.

---

Copy: [Page 1 ](https://docs.google.com/document/d/1V46qDz2p4NmAUNOk4mjcOm5Jd0dZ0iY6G8fi2k3MQp8/edit?usp=sharing) [Page 2 ](https://docs.google.com/document/d/1lRHEO9LOJBNA60jd3RukIbAvG2j3GdHE30A-kTAI4Vk/edit?usp=sharing) [Page 3](https://docs.google.com/document/d/1YH5Otrj56wdoWgTZhZk_YzI-qzo21IBkm2SohZa6BHw/edit?usp=sharing)
Creative: Only creative would be in hero. Just use the same hero as this: [this](https://www.mozilla.org/en-US/products/vpn/more/when-to-use-a-vpn/)

Layout: Same as [this](https://www.mozilla.org/en-US/products/vpn/more/when-to-use-a-vpn/)

Notes: We should have a hero section on top, similar to the example layout. The copy docs do not have copy provided for this. Just use ipsum until we can get copy delivered.

#### Success Criteria
- [x] no-index / no-robots. This page should not be crawled (for now). This will only be found through traffic sent directly from product.
- [x] CTA should link to https://www.mozilla.org/en-US/products/vpn/#pricing
- [ ] Attribution/event tracking in place (from landing page to purchase)
- [x] Legal approval
- [ ] product team approval
- [ ] design approval (Elise)

**Comment by slightlyoffbeat** [comment]
For URLs: lets keep in the /vpn/more/[slug]. If this is a duplicate slug, lets add a number or get creative.

**Comment by slightlyoffbeat** [comment]
@alexgibson do we need to do anything special with mozilla.org pages in order to properly have attribution all the way to signup? I recall doing something for a previous WNP.

**Comment by alexgibson** [comment]
> @alexgibson do we need to do anything special with mozilla.org pages in order to properly have attribution all the way to signup? I recall doing something for a previous WNP.

Yes, we'd need to either add a new condition, or update the existing logic to https://github.com/mozilla/bedrock/blob/master/media/js/base/fxa-utm-referral.js#L62-L90
