### ISSUE TITLE
GTM google tag manager might not be getting loaded for some subset of WNP/VPN product page visitors

### ISSUE THREAD

**Issue by shell1** [mozilla/bedrock#10392]
## Description

YeonJoo analysed and compared the VPN acquisition funnel from WNP (What’s new Page) CTA (click through action) for the VPN service for Firefox90(/de/,/en-ES/,/fr/,/nl/,/it/) and Firefox88(/de/,/en-US/,/fr/) first 28 days from the release.

The flow is: (1)Hit WNP ->(2)click CTA in WNP ->(3)hit VPN product->(4)click subscription CTA -> (5)new subscription 

There was a discrepancy found (with the Relud's help) in measuring (2), only 53% of them were captured. I am wondering if there is similar discrepancy in measuring (4)

Possible theories from Alex Gibson (GTM google tag manager might not be getting loaded for some subset of WNP/VPN product page visitors)

### Steps to reproduce
Ask Relud and YeonJoo - I believe this is more "seen in data" while investigating 
[Jira ticket](https://mozilla-hub.atlassian.net/browse/DVPN-17), WNP90 investigation [data](https://colab.research.google.com/drive/1k0ZWHPtNUUKVWqabyWLDogBo4An3lJjF#scrollTo=nzpDVkUb5f1E), [Slack discussion](https://mozilla.slack.com/archives/G018SNLQP6C/p1628793524053800)
Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result
Similar attributable funnel to what was seen in Firefox 88.

What should happen?

### Actual result
1/2 are unknown sources - so unattributed

What happened.

### Environment

What browser and operating system are you using?

**Comment by shell1** [comment]
tagging @relud @yeonjoo

**Comment by alexgibson** [comment]
I've dug into this a bit and I don't think the assumption re: Google Tag Manager not being loaded is correct. If that was true, then the original session hits on both WNP & VPN page wouldn't be registering either. At this time, I can't see any issues with our setup. I expect quite a number of people block GTM with extensions and adblockers, but those are users we would have zero data on in GA, not partial data.

As to the discrepency here, I still don't understand it.

**Comment by YeonjooSmith** [comment]
**Steps to reproduce**
[This colab notebook has the queries that calculated the numbers for the claim](https://colab.research.google.com/drive/1oZrAZA0xiCIBAdA6b1ZiUXNJdfx9QwP4?usp=sharing). 
`wnp_cta`(~260K) is the number of sessioins that clicked the VPN product CTA in the WNP site for Firefox90 and it was compared with `wnp_hit_AND_vpn_hit` (~450K) which is the number of the VPN product site hit that are from the WNP traced by the bedrock source added in the page path(`/?source=whatsnew90... `). Then about 58% (my apologies, the 53% that I provided was a typo) of traffic coming from the WNP to the VPN product site is captured by the CTA click logged.

**Comment by alexgibson** [comment]
@YeonjooSmith just checking in on this old issue - is this a problem with GA that we still see today?

**Comment by alexgibson** [comment]
@YeonjooSmith I'm just checking in on this old issue. The `?source=` param is not something we use today any longer, so I was wondering if we could close this issue, unless this is something that's still an issue. Thanks
