### ISSUE TITLE
WNP 92 (EN & FR)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10402]
## Description

Whats New Page 92 for EN and FR will feature VPN. This WNP will be different from previous WNP. We will build on the success of 91 and remove a step in the purchase process by sending people directly to the purchase flow from this page (if they click on a CTA).

- Geo redirect will send people from US, UK, and Canada of this new WNP. The pricing is hard coded for dollar.
- Geo redirect will send people from France to a localized version of this new WNP. This is hard coded for euro.
- EN: If doesn't meet geo, then fallback to page used for WNP 89.
- FR: If doesn't meet geo, then fall back to TBD (assume evergreen for now)
- Put this behind a flag so that we can turn off geo redirect if necessary
---

Design: To Be Delivered.
Copy: To Be Delivered.

#### Success Criteria
- [ ] User in US, UK, Canada will see new WNP
- [ ] User in France will see localized version of WNP
- [ ] EN user outside of US/UK/Canada will see fallback VPN WNP page
- [ ] FR user outside of France will see fallback VPN WNP
- [ ] Can turn off flag for geo redirect and have everything safely go to fallback
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by craigcook** [comment]
English - https://www-demo4.allizom.org/en-US/firefox/92.0/whatsnew/en/
French - https://www-demo4.allizom.org/fr/firefox/92.0/whatsnew/france/

**Comment by slightlyoffbeat** [comment]
@pmac Can you take a look at the python for this.
