### ISSUE TITLE
Implement attribution flow for VPN subscription referrals

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10409]
## Description

Now that we're starting to promote Mozilla VPN more widely on mozorg pages, we need to implement a system that will enable us to track attribution more easily as people click through to the product page. Up until now we've used a `?source=` query param on the page URL (we can't use utm params for same-site links). This was OK enough for in-product pages such as /whatsnew, but if we want to do this on more public surfaces (example see: https://github.com/mozilla/bedrock/issues/10403), then we should probably make a better solution since these URLs can easily be crawled and shared.

The solution is up for discussion, but it could be something like setting a cookie on CTA click, which we then read when someone lands on the product page before updating the subscription link parameters.

---

#### Success Criteria
- [x] When people click on same-site CTA links to the VPN landing page, we can attribute those conversions at the subscription level.

**Comment by slightlyoffbeat** [comment]
Thanks @alexgibson. I'd like to prioritize this if you have an idea for a solution.

**Comment by alexgibson** [comment]
@slightlyoffbeat happy to work on this next week. I'll assign myself and add it to the ready column. Thanks

**Comment by alexgibson** [comment]
Attribution flow will work as follows:

1. Page implements a VPN referral link (via a new Python helper).
2. Visitor clicks on a referral link and a 1 hour cookie is set with a referral ID.
3. Visitor navigates to VPN product landing page and on page load the cookie is checked.
4. If a cookie exists and there are no existing UTM parameters in the page URL, then custom UTM params are set using the cookie referral ID.

For example, a referral cookie with a value of `navigation` would result in:

- ``entrypoint=www.mozilla.org``.
- ``utm_source=www.mozilla.org``.
- ``utm_campaign=navigation``.
- ``utm_medium=referral``.

I'm also going to propose we respect DNT for this functionality, since we also do that in other scenarios where we set cookies such as GA and Traffic Cop.

**Comment by slightlyoffbeat** [comment]
@alexgibson looks good to me.
