### ISSUE TITLE
Change navbar CTA for Firefox users to "Get Mozilla VPN"

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10403]
## Description

The CTA in the navbar for Firefox users calls users to get a Firefox account.

Currently accounts is not a priority and we should switch this to something that aligns with our goals. 

Old text: "Get a Firefox Account"
New text: "Get Mozilla VPN"

Link: https://www.mozilla.org/products/vpn/
---

#### Success Criteria
- [x] Shows up in all places where the current "Get a Firefox Account" CTA is
- [x] Does not appear for non-fx users (that remains a download firefox CTA
- [ ] Attribution is set up so that we can properly track purchases that came from this CTA

**Comment by maureenlholland** [comment]
@slightlyoffbeat do we want to link directly to the VPN pricing section? https://www.mozilla.org/en-US/products/vpn/#pricing

It might be a little annoying to have two "Get Mozilla VPN" clicks in a row (although the second link will change will the direct payment click experiment)

And should we hide this CTA on the VPN page?

**Comment by slightlyoffbeat** [comment]
@maureenlholland The VPN page already has "Get Mozilla VPN" as the CTA. Lets leave that one as is for now.

Linking directly to the pricing section sounds like the right way to go. Lets do it.
