### ISSUE TITLE
CRO: Test sending users directly to payment if they click on top CTA

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10404]
## Description

We have data that shows that most users prefer the 12 month subscription plan. How can we use this info to help reduce scrolling or eliminate a click in the buying process.

Proposal:
Target: en-US page
percentage: 20%
Length: 1 Week (longer if needed)

Design (rough mock):
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/2030656/131045235-d77104cc-8beb-4238-8820-d1f7beb15157.png">

---

#### Success Criteria
- [x] Attribution is in place to compare base page with this test
- [x] Agree that this not a negative pattern.

**Comment by alexgibson** [comment]
Note that even though this test is for en-US only, we'll still need to display the right price/currency depending on country (and also make sure the button links to the right plan for said country)

**Comment by alexgibson** [comment]
Also: I'd be happy tp pick this one up just as soon as I'm finished wrapping up the app banner work (unless someone else wants to take this on).

**Comment by reemhamz** [comment]
@alexgibson I'd love to work with you on this, especially to understand the workflow of payments + user behaviours + displaying different currencies for different countries.

**Comment by alexgibson** [comment]
@reemhamz if you'd like to take this on then feel free. Happy to walk you through what needs doing if that helps. Let me know!
