### ISSUE TITLE
Contentful: CTA component should have an option for black buttons.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10443]
## Description

The CTA component in contentful can create a blue button or an alt blue outline button.

We should also have the option for a black button and a black outline button.

**Comment by maureenlholland** [comment]
Blue buttons used to have specific meaning: this is a Firefox product-related action (https://protocol.mozilla.org/patterns/atoms/buttons.html#product)

We could continue that in code by automatically adding the `mzp-t-product` (blue) class to CTAs with Firefox product-related actions and defaulting other actions to black.

Or we could add a new content editor option in contentful, allowing any product to be associated with blue or black.

Which is preferred? Or is there another option to consider?

**Comment by maureenlholland** [comment]
It's worth noting the CTA colors are already mixed on the homepage: https://www.mozilla.org/en-US/
- navbar CTA used to be Firefox Account, but switched to Mozilla VPN and kept blue outline
- further down, pocket CTA is blue and Mozilla VPN is black
<img width="1175" alt="Screen Shot 2021-09-22 at 2 25 25 PM" src="https://user-images.githubusercontent.com/19650432/134355341-38e282ad-0472-4b97-a08c-383b42d4964d.png">
e

**Comment by craigcook** [comment]
I think this is at least partly due to VPN essentially having its own branding so the rules aren't clear. According to Protocol's guidelines, product buttons are for product actions (downloading, signing up, etc). But at the time we made that blue button we were only targeting Firefox products, so it's a very Firefoxy blue. 

This is where UX and branding meet. We want a distinctive button for a product action, but that button should invoke that particular product. Should we reserve the blue ONLY for Firefox and other products get the standard black? Or should ALL products be blue? Should VPN and Pocket (products with their own brands) have their own distinct buttons? To that end, is it time to add VPN and Pocket as separate brand themes in Protocol?

**Comment by maureenlholland** [comment]
> To that end, is it time to add VPN and Pocket as separate brand themes in Protocol

I'd be happy to support this.

**Comment by reemhamz** [comment]
I have a designer pal on the VPN team and he showed me some of the designs he was working on. Would we be able to coordinate directly with the VPN design system created + its colors to integrate similar VPN product design on Protocol?

**Comment by slightlyoffbeat** [comment]
In this case, I think since they are on the same page, I'd argue for both buttons on the homepage being the same color, even thought the products themselves may have different color schemes. This page is a mozilla page, and should follow a Mozilla color scheme.

On the VPN landing page, or on the pocket website, there may be a vpn/pocket theme.

But as pointed out, we already violate this, so there's a question of what we do for near-term and long-term.

@maureenlholland As far as your questions and suggestions for how to handle this in Contentful...I think my vote is simply allowing the CTA component to default to black, but also able to be blue. Other solutions may be better in the long term, but I don't want to block the creation of new content till we figure out what that is.

Thoughts?

**Comment by maureenlholland** [comment]
@slightlyoffbeat This works for me. I will add a new Color field on the CTA content type with radio button selection for Black or Blue (default Black). That should be easy enough to remove down the line if we want to tie colors to Product actions instead.

**Comment by maureenlholland** [comment]
Considering this blocked technically until we get a local Contentful preview going.
It could be blocked for design reasons as well, depending on how strictly we want to enforce branding guidelines.

**Comment by maureenlholland** [comment]
This was blocked due to local dev workflow issues with Contentful, but should be fairly straightforward to implement now. Must have Contentful access to work on this issue.

- Add color field on CTA component in Contentful
- Add `mzp-t-product` class based on the value of color field in Bedrock
