### ISSUE TITLE
Add a hyphen to links that say "12 month plan" and "6 month Plan"

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10441]
## Description

From Mary:

 We are missing hyphens in the links that say “12-month plan” and “6-month plan.”
(We don’t need the hyphen when the word “plan” isn’t present)

This means we should add a hyphen to the buttons inside the variable pricing unit

Page: https://www.mozilla.org/en-US/products/vpn/

**Comment by Prasanna0908** [comment]
Hello, I would like to work on this issue. I am not able to find the location of the link which has "12-month plan" so can you just share a screenshot of that.

**Comment by reemhamz** [comment]
Hey @Prasanna0908, if you're still interested to work on this ticket I can help you out with getting started. Just [install the repository](https://bedrock.readthedocs.io/en/latest/install.html), and it should be easy to get started. 
The file name for the page should be in `products/vpn/landing.html`. However, since we use Fluent files for translation purposes, you could just add the hyphens in the Fluent file that corresponds to the `landing.html` file for the VPN page. Once you submit a PR, kindly assign me as a reviewer and/or tag me if you need anymore help.

**Comment by Prasanna0908** [comment]
Okay, I would like to work on this.

**Comment by reemhamz** [comment]
@Prasanna0908 Perfect, thanks for taking this on! Excited to see your contribution to our code 🎉 Once again, let me know if you need any help with the ticket.

**Comment by Prasanna0908** [comment]
Hey @reemhamz, I believe it is the 88th and 89th line of the code of the file [bedrock/l10n/en/products/vpn/shared.ftl ](bedrock/l10n/en/products/vpn/shared.ftl) is where I need to add a hyphen. Also, what are fluent files? It would be great if there is any documentation related to that.

**Comment by reemhamz** [comment]
@Prasanna0908 Yup, those are the correct file and lines 👍🏼

Fluent files are what we use for Mozilla.org's internationalization. When we have pages that we'd like translated into other languages for different locations around the globe, we utilize [Fluent](https://projectfluent.org/). We documented how we use it in Bedrock [here](https://bedrock.readthedocs.io/en/latest/fluent-conversion.html).

We basically have translators working with us globally who have access to the Fluent files we create. Once we merge Fluent files containing strings, translators get notified and are able to help us translate the pages. It's an automated process, but this was a quick and easy rundown. I hope that was clear enough!

**Comment by reemhamz** [comment]
Hey @Prasanna0908, kindly wondering if you have been able to get through the code alright?
If so, you can create a PR and assign me as the reviewer and I will be notified to review the code before merging 🧁

If not, let me know if you've ran into any blockers and I can help you out 💫

**Comment by reemhamz** [comment]
Hey @Prasanna0908, I've picked up this ticket. Please feel free to keep an eye out for any opportunities to help with other tickets with us on Bedrock!

**Comment by craigcook** [comment]
@reemhamz Looks like we need to treat these as new strings. Just changing the English strings won't be picked up by other locales. 
https://github.com/mozilla-l10n/www-l10n/pull/232
