### ISSUE TITLE
Contentful: Card components font size is too big

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10444]
## Description

Contentful cards (small/medium) font size seems to be too big. We should investigate and make sure they are correct, or are using the correct version of protocol.

### Steps to reproduce

Compare this contentful homepage:

https://www-dev.allizom.org/en-US/contentful-preview/69xQvSpz9F6fmsyaSxLrjW/

To the Mozilla homepage:

https://www.mozilla.org/en-US/

The font size on the row of 4 cards is different.

### Expected result

We should make sure that the default font size for cards is correct and consistent and is up-to-date.

**Comment by alexgibson** [comment]
It looks like the Pocket cards under "What we're reading" are using `mzp-c-card-medium` instead of `mzp-c-card-extra-small`.

**Comment by alexgibson** [comment]
@slightlyoffbeat I took a look in Contentful and it appears like there is no notion of a "small" card in the content types. There is only "Card", and for a large card it's a layout type.

I'm not sure why this is, but I'm guessing there's probably a reason? This would explain the font size bug anyway.

Do we want to add specific `extra_small_card` component data type to use in a 4 card layout? I'm not sure where I can set that, or even if I have access to see where this is.

**Comment by alexgibson** [comment]
Moving this from in-progress back to the backlog until we know how this should be fixed.

**Comment by alexgibson** [comment]
After discussing this with @pmac on Slack, we're going to fix this by hard-coding the card size depending on the 4-card layout type, as this is easier than adding a new field in Contentful.

**Comment by alexgibson** [comment]
@slightlyoffbeat thoughts on the above? ^

Do we want to hard code this and assume 4 card layouts will only ever use the extra-small card type, or do we want to add a new field to the layout in Contentful?

**Comment by pmac** [comment]
This one sounds easy as all cards will use the same size. So we could pretty easily add a choice field with a default to `extra-small`, and allow selection of `small` or `medium`, or which ever sizes make sense.

**Comment by slightlyoffbeat** [comment]
I believe that the proposed solution is not just easier, but preferred

The content creators should have fewer options, and the content should display in the best way possible (In this case, having cards in a 4 card layout default to being extra small)

**Comment by alexgibson** [comment]
Ok sounds like we have consensus, thanks!
