### ISSUE TITLE
Contentful: Build simplified split component for most common usecase.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10445]
## Description

Contentful currently has a Hero content type that utilizes Protocol's hero component (that is being depreciated).

Contentful also has a split content type that has several options that could confuse content creators.

I propose we build a new contentful content type that utilizes protocol's split component to build the most common of usecases (see screenshot below):

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/2030656/132929803-a43484c0-c7ad-4356-9b0c-d21cd8270493.png">

This would include:
- image (left or right)
- product horizontal lockup (optional)
- Title
- text (optional)
- CTA Button (optional)
- CTA Text (optional

If picking this up, please set up time to talk to @slightlyoffbeat before starting work for additional context and details.
---

#### Success Criteria
- [ ] Can successfully re-create the homepage split-compents for Pocket & VPN

**Comment by maureenlholland** [comment]
We can present a simplified view with the Compose App tabs, moving the lesser-used fields to an Advanced field group
