### ISSUE TITLE
Docs: add Make it run documentation section

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#10452]
We're trying to make Bedrock documentation easier to update and it helps to be able to preview your changes locally. 

To that end, we want to add a Documentation section under "[Installing Bedrock > Make it run](https://bedrock.readthedocs.io/en/latest/install.html#make-it-run)". Content below:

> ### Documentation
> 
> This is a great place for coders and non-coders alike to contribute! Please note most of the documentation is currently in [reStructuredText](https://bashtage.github.io/sphinx-material/basics.html) but we also support [Markdown](https://www.markdownguide.org/) files.
> 
> If you see a typo or similarly small change, you can use the "Edit in GitHub" link to propose a fix through GitHub. Note: you will not see your change directly committed to the master branch. You will commit the change to a separate branch so it can be reviewed by a staff member before merging to master.
> 
> If you want to make a bigger change or [find a Documentation issue on the repo](https://github.com/mozilla/bedrock/labels/Documentation), it is best to edit and preview locally before submitting a pull request. You can do this with Docker or Local installations. Run the commands from your root folder. They will build documentation and start a live server to auto-update any changes you make to a documentation file.
> 
> Docker:
> ```
> $ make docs
> ```
> 
> Local: 
> ```
> $ pip install -r requirements/docs.txt
> $ make livedocs
> ```

**Comment by Ayushsunny** [comment]
> ### Documentation
> This is a great place for coders and non-coders alike to contribute! Please note most of the documentation is currently in [reStructuredText](https://bashtage.github.io/sphinx-material/basics.html) but we also support [Markdown](https://www.markdownguide.org/) files.
> 
> If you see a typo or similarly small change, you can use the "Edit in GitHub" link to propose a fix through GitHub. Note: you will not see your change directly committed to the master branch. You will commit the change to a separate branch so it can be reviewed by a staff member before merging to master.
> 
> If you want to make a bigger change or [find a Documentation issue on the repo](https://github.com/mozilla/bedrock/labels/Documentation), it is best to edit and preview locally before submitting a pull request. You can do this with Docker or Local installations. Run the commands from your root folder. They will build documentation and start a live server to auto-update any changes you make to a documentation file.
> 
> Docker:
> 
> ```
> $ make docs
> ```
> 
> Local:

Hello @maureenlholland , The same content above under "Make it run" that's it?

**Comment by maureenlholland** [comment]
@Ayushsunny yep, super-simple. We would add this to the bottom of the Make it run subsection (under Prod Mode).
