### ISSUE TITLE
Docs: fix clipboard code snippets

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#10453]
We added a new copy button to code snippets in our docs. For the most part, this works great out of the box, but we need to check the snippets across the documentation to see if the clipboard output causes problems or errors.

<img width="709" alt="copy-button" src="https://user-images.githubusercontent.com/19650432/133246582-73b34cf7-6ee2-494a-b136-7c7d3e55b171.png">

example: [Installation instructions](https://bedrock.readthedocs.io/en/latest/install.html)

Good
```
make build-prod run-prod
```

Bad
```
python3 -m venv venv                         # create a virtual env in the folder `venv`
source venv/bin/activate                     # activate the virtual env. On Windows, run: venv\Scripts\activate.bat
pip install --upgrade pip                    # securely upgrade pip
pip install -r requirements/dev.txt          # installs dependencies
```

This will require checking all the documentation pages for code snippets and using the copy button to confirm the output works as expected. ~If something breaks, move information out of the code snippet and into regular text or break the code snippet into multiple blocks.~

UPDATE (15-09-2021): after some [discussion](https://github.com/mozilla/bedrock/issues/10453#issuecomment-919427098), we have a few general rules we'd like to apply consistently:

1.    If the code is meant for the terminal, it should go one command per code block
2.   If the code is meant for a code editor, it can have multi-line code blocks (emphasis on the can, not should)
3.    Do not include comments in terminal command code, as it can cause errors

**Comment by Ayushsunny** [comment]
So for snippets like this -
```
python3 -m venv venv                         # create a virtual env in the folder `venv`
source venv/bin/activate                     # activate the virtual env. On Windows, run: venv\Scripts\activate.bat
pip install --upgrade pip                    # securely upgrade pip
pip install -r requirements/dev.txt          # installs dependencies
```
I think we should separate all four into different lines by then it will work fine? like this -

```
python3 -m venv venv                         # create a virtual env in the folder `venv` 
```

```
source venv/bin/activate                     # activate the virtual env. On Windows, run: venv\Scripts\activate.bat
```

```
pip install --upgrade pip                    # securely upgrade pip`
```

```
pip install -r requirements/dev.txt          # installs dependencies
```

**Comment by maureenlholland** [comment]
@Ayushsunny This will be a bit trickier and require some judgment calls. Basically, anytime we have a code snippet, we want users to be able to click the copy button and paste the code into their terminal or code editor without error. At the moment, that won't happen in every case.

If we can keep the code all in one code block, that's preferable because it's less clicking but if things run out of sequence, or the combination is confusing, we can break out into multiple sections. I think the main issue with the above code is the commenting beside the commands. Try moving the comments to an explanatory section below the code block and keeping the multi-line commands.

```
python3 -m venv venv                         
source venv/bin/activate                     
pip install --upgrade pip                   
pip install -r requirements/dev.txt          
```

NOTE: If you are on Windows, run the second command with venv\Scripts\activate.bat

These commands will do the following:
1. create a virtual env in the folder `venv` 
2. activate the virtual env
3. securely upgrade pip
4. install dependencies

**Comment by reemhamz** [comment]
@maureenlholland Great ticket! Although, I was wondering, though I know that we can definitely find the grouped multi-line commands useful, I think splitting them up wouldn't be too bad of a call as well, especially since sometimes we just need to run one of the commands (i.e. just running `pip install -r requirements/dev.txt` to update some of the new commands installed from the backend). What do you think? Should we raise the question to get more opinions on this?

**Comment by reemhamz** [comment]
@Ayushsunny The team's agreed to split up the grouped code into separate snippets instead. So I want to say, good job on suggesting it! 

Here are some good-to-know code snippet rules:

1. If the code is meant for the terminal, it should go one command per code block
2. If the code is meant for a code editor, it can have multi-line code blocks (emphasis on the _can_, not _should_)
3. Do not include comments in terminal command code, as it can cause errors

For this specific scenario, I would include the code snippet explanation above the code block itself, rather than have them be as comments within the code blocks. 

Let me know if you have any questions!

**Comment by Ayushsunny** [comment]
Okay, I'll make a PR for this issue.
Also I have a doubt that we are going to fix the entire clipboard present or just in `installation instruction `part? @maureenlholland @reemhamz

**Comment by maureenlholland** [comment]
> Also I have a doubt that we are going to fix the entire clipboard present or just in `installation instruction `part? 

@Ayushsunny Awesome! We want all the clipboards in the docs to be checked and fixed if necessary. Whatever you can update to match our new code snippet rules is appreciated. 

You can ignore some legacy localization docs though. No need to check the following:
- https://bedrock.readthedocs.io/en/latest/l10n.html#legacy
- https://bedrock.readthedocs.io/en/latest/fluent-conversion.html

@reemhamz does that sound about right to you?
