### ISSUE TITLE
Update division operators in Sass/SCSS

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#10459]
## Description

[Using `/` as a division operator is being deprecated](https://sass-lang.com/documentation/breaking-changes/slash-div) in Sass. It still works for now but will throw a warning during compiling. 

We should weed out all our uses of `/` for division in our Sass/SCSS and change them to the new `math.div()` function. Sass provides a migration tool that should help automate this but we'll want to take care to make sure nothing breaks along the way.

The current version of node-sass doesn't seem to be using the latest Sass yet so it doesn't show any warnings at this time, but it'll become an issue in the near future. We might as well get ahead of it.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/10469
