### ISSUE TITLE
Redirect loop on https://www.mozilla.org/en-US/mission/

### ISSUE THREAD

**Issue by jezdez** [mozilla/bedrock#10456]
## Description

When I tried to open https://www.mozilla.org/en-US/mission/ I got in a redirect loop.

### Steps to reproduce

- open https://www.mozilla.org/en-US/mission/ in a browser
- see the error message from the browser about a redirect loop

### Expected result

- seeing the Mozilla mission landing page similar to https://www.mozilla.org/en-GB/mission/

### Actual result

- redirect loop error

### Environment

What browser and operating system are you using?

Firefox, Chrome, Safari on latest macOS

**Comment by pmac** [comment]
Thanks for the report, but we can't replicate. From where in the world did you see this? I'm wondering if one of our cache nodes has an issue.

**Comment by Ayushsunny** [comment]
Hello @jezdez I'm not getting any redirect loop error on this link  https://www.mozilla.org/en-US/mission/ 
I'm using Chrome.

![Screenshot 2021-09-14 204440](https://user-images.githubusercontent.com/73520373/133285082-9101857c-6bca-4310-a536-5d30f9a52867.png)

Can you try again after deleting your cookies from this specific link?

**Comment by pmac** [comment]
I have reproduced this when connected via a VPN in Frankfurt, Germany. Still investigating.

**Comment by jezdez** [comment]
Yeah, this was from Germany :)

**Comment by alexgibson** [comment]
I *think* we resolved this, can this one be closed out @pmac?

**Comment by pmac** [comment]
Oh yes. Thanks.
