### ISSUE TITLE
Host image asset for CFR message

### ISSUE THREAD

**Issue by piatra** [mozilla/bedrock#10457]
## Description

For [UJET-117](https://mozilla-hub.atlassian.net/browse/UJET-117) campaign that contains user messages we need to host an image asset that can be accessed by Firefox clients. Users will get a JSON configuration that contains a URL to this asset.

Image:
![party_emoji](https://user-images.githubusercontent.com/810040/133291920-e4021fd0-81b3-4bf6-8257-87b379517ea6.png)

**Comment by pmac** [comment]
Ah! I was able to find it hosted for snippets after all.

https://snippets.cdn.mozilla.net/media/icons/0c6337e3-8a11-4435-9732-cabb79f59f78.png

**Comment by pmac** [comment]
I'll keep this open for a bit in case you run into any issues with that URL. We have alternate hosting possibilities if we need them.

**Comment by piatra** [comment]
Thanks. I'll close this once it passes QA and we've confirmed everything is ok.

**Comment by piatra** [comment]
we launched and did qa, no issues. thanks again.
