### ISSUE TITLE
Update video links in Firefox tips and tools page

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#10465]
## Description

Update the video links in the Firefox tips and tools page to new videos that exclude the last names of folks in featured in the videos.

---

#### Update the following video links:

- [x] Picture-in-picture
- [x] Protections dashboard
- [x] Pocket button
- [x] Email/relay
- [x] Restore sessions

#### Update the following variation links:

- [x] [Picture-in-picture](https://www.mozilla.org/en-US/firefox/features/tips/?v=picture-in-picture)

**Comment by kellymj** [comment]
Update:

Change links for 
<google-sheets-html-origin><style type="text/css"></style>

Picture in picture
Protections dashboard
Relay
Restore session

[Here's a spreadsheet with new YT links](https://docs.google.com/spreadsheets/d/1mxPBzSdVjI9iERc6FMdYPKZFjrgrkRC42habqFXy4Fc/edit#gid=0)

The priority page to update on Tuesday is v=eyedropper, as we are sending email traffic to that page on Wednesday.
