### ISSUE TITLE
Sentry JS bundle is surprisingly large

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10473]
## Description

Webpack gives a warning about the size of our Sentry JS script when compiling:

```
WARNING in entrypoint size limit: 
The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). 
This can impact web performance.
[1] Entrypoints:
[1]   sentry (389 KiB)
[1]       js/sentry.js
```

Thankfully it compresses down to ~24Kb in production, but this is still suprisingly large for an error reporting lib.

It looks like others have also reported this problem, and it's on Sentry's upcomng roadmap to improve: 

- [x] https://github.com/getsentry/sentry-javascript/issues/2707
- [ ] https://github.com/getsentry/sentry-javascript/issues/4240

Filing this issue as a reminder to keep an eye out for updates.

**Comment by vladanpaunovic** [comment]
You can track this better here getsentry/sentry-javascript#4240 

We are targeting this release in May.

**Comment by vladanpaunovic** [comment]
Thanks for watching over for us @alexgibson!

I saw that getsentry/sentry-javascript/issues/5184 is closed too. Making this one a good candidate for "closed" :)
