### ISSUE TITLE
Power homepage with Contentful

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10508]
## Description

Contentful is merged, and homepage is recreated in Contentful. This issue will track what is needed to complete the transition.

---

#### Steps
- [x] Recreate Contentful homepage to be 1:1 with current homepage
- [ ] Make a decision on how to handle the Pocket section on homepage. (#10514)
- [x] [Add horizontal lockups to the hero component (currently its just the logo)](https://github.com/mozilla/bedrock/pull/10636)
- [ ] publish all individual components and resolve all issues (images too small, too many characters, etc)

#### Success Criteria
- [ ] TBD

**Comment by slightlyoffbeat** [comment]
@pmac can you jump in and add steps and success criteria? We can break into smaller issues if necessary.

**Comment by slightlyoffbeat** [comment]
One of the biggest hurdles to publishing is how we handle the "what we are reading on pocket" section on the homepage. It is a custom component.

@pmac and I were talking, and I think we should have some sort of content type in Contentful that takes in something like an ID number. That ID number would correspond with code in bedrock and pull it in. 

Inserting custom code will most likely be a reoccurring need. Thoughts on the approach? Should I write up a proposal?

**Comment by pmac** [comment]
I do think that each of the remaining check boxes above should be an individual issue, or at least the 2nd and 3rd ones. Is the 3rd one (horizontal lockups) referring to using the wordmark rather than just the logo?
