### ISSUE TITLE
Update Firefox Focus page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10506]
## Description

Product Marketing team has requested some simple changes to the Firefox focus page.

Changes can be found here:
https://docs.google.com/document/d/1d7FYq7vfZNosENMWaGrJXXUztgKqiM_X1aZ6ma_t5yA/edit?usp=sharing

Questions for clarification can go to @slightlyoffbeat or you can reach out to Mei Loo directly. 

---

#### Success Criteria
- [ ] Stage the page and send to Mei for approval

**Comment by craigcook** [comment]
Can we get an SVG of the new logo?

**Comment by slightlyoffbeat** [comment]
@craigcook on it!

**Comment by Ayushsunny** [comment]
Hello, @reemhamz are you working on it? and if not, do you think I can work on this issue?

**Comment by reemhamz** [comment]
Hi @Ayushsunny! I'm currently actively working on it and requires some internal work to be updated. Thank you for asking though 💫
