### ISSUE TITLE
Create cross-site Firefox download attribution page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10520]
## Description

We're going to take the experiment download page we created in https://github.com/mozilla/bedrock/issues/10207 and turn this into a long-term public URL, so that sites such as AMO and SUMO can link to a page that directly downloads Firefox (rather than lining to /firefox/new/ and requiring a visitor to click the button again).

Requirements:

- Page available via either a query param or a new URL (e.g. `/firefox/download/now/`) TBD.
- Page will capture attribution data for stub installer before initiating a download.
- Page may contain some new messaging tailored to context of referral.
- Available for all locales.

---

#### Success Criteria
- [ ] New download page is available in production for AMO to use.

**Comment by slightlyoffbeat** [comment]
Lets set Tue 16 at a deadline for making a decision on the first bullet point.

@alexgibson @pmac could you very briefly recap the pros and cons between the options.

**Comment by alexgibson** [comment]
Add attribution call to existing /thanks page:

Pros:
- No need to maintain two separate pages / URLs.
- May catch attribution for other external sites that might link directly to /thanks.

Cons:
- Makes the existing /thanks page logic slightly more complex to maintain (more edge cases to consider).
- If a user blocks GA, and does not already have a stub attribution cookie, it can delay the Firefox download by several seconds.

Add attribution call to a new URL / template via a query param:

Pros:
- Logic does not impact users coming from /new.
- Opportunity to incorporate new messaging / design elements if they make sense.

Cons:
- We need to maintain two separate thanks pages / templates.
- We only capture attribution if external sites link specifically to this new URL.

**Comment by slightlyoffbeat** [comment]
I lean towards a new URL because of simplicity. Do you have a strong opinion?

**Comment by alexgibson** [comment]
> I lean towards a new URL because of simplicity

A new URL is certainly the least amount of effort in order to complete this, as we essentially already have the code to support it. We'd just need to decide on a more pernament URL for it to be accessed. I also agree on trying to keep our main download logic as simple as possible.

As for the URL, personally I'd lean toward using a query parameter e.g. `/firefox/download/thanks/?xv=external`, as this is less work in the future to roll this into one single page/URL if we wanted to.

**Comment by slightlyoffbeat** [comment]
This sounds good to me, especially with the point of it being easier if we move towards a single URL in the future.

How about `/firefox/download/thanks/?s=external` (vague enough, but still conveys the purpose)

alt: `/firefox/download/thanks/?xv=direct` (a bit redundant)

**Comment by alexgibson** [comment]
@slightlyoffbeat if we're going to use the same template / design as the current /thanks page, then I like the sound of `?s=external`. We typically use `xv=` for serving different visual designs ("experience version"), so if we want to introduce some design new elements here then I think we should stick to using that.

If we just want to stick with the current design / messaging for now, let me know and I'll get to work on this and use `?s=external`. Thanks

**Comment by slightlyoffbeat** [comment]
`?s=external` works for me. Lets move forward with it.

**Comment by alexgibson** [comment]
Ok, gonna pick this up - thanks!

**Comment by alexgibson** [comment]
> Thanks for taking care of this @alexgibson! When will this land on prod and be ready for use? Will its use be documented anywhere?

I'll let you know when it's live and make sure to document the URL.

**Comment by alexgibson** [comment]
@bobsilverberg this is now in production and ready to use. Please see docs here for reference: https://bedrock.readthedocs.io/en/latest/download-buttons.html#external-referrers

**Comment by bobsilverberg** [comment]
Thanks @alexgibson!
