### ISSUE TITLE
Newsletter section on Contentful home page is misaligned

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10521]
## Description

The newsletter section on the Contentful home page should be inside `.mzp-l-content` container in order for it to be correctly aligned.

### Steps to reproduce

https://www-dev.allizom.org/en-US/

### Expected result

![image](https://user-images.githubusercontent.com/400117/135128765-ad5d79ad-364e-4f52-b0d6-7e0b3c236196.png)

### Actual result

![image](https://user-images.githubusercontent.com/400117/135128709-94d36424-1f96-4749-bf36-5cbed3e6a8d8.png)

### Environment

Firefox Nightly

**Comment by Ayushsunny** [comment]
Hey, @alexgibson I want to work on this issue. 
Could you guide more on this

**Comment by alexgibson** [comment]
@Ayushsunny the template in question is here: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/contentful-homepage.html
