### ISSUE TITLE
Update "already a subscriber" link url

### ISSUE THREAD

**Issue by birdsarah** [mozilla/bedrock#10535]
When Guardian v1.16 is released (week of Oct 4 2021), the subscription required and login gate on the vpn download page will be removed.

Suggest updating the "Already a Subscriber?" link location on https://www.mozilla.org/en-US/products/vpn from https://vpn.mozilla.org/oauth/init to https://vpn.mozilla.org/vpn/download to reduce unnecessary steps for the user to get to the downloads page.

This also means that there won't be any cause for a user to be redirected back to bedrock from guardian with `?vpn-sub-not-found=true`, so for code cleanliness you could get rid of this if you wanted to.

#### Success Criteria
- [x] "Already a subscriber?" link on https://www.mozilla.org/en-US/products/vpn points to https://vpn.mozilla.org/vpn/download
- [x] Optional: Clean-up / Remove "vpn-sub-not-found" handling.

@alexgibson hope this makes sense to you - should be small.

Also note that there's not a need for a timed release, you are just welcome to make this change after v1.16 of guardian is released. The link that you have (`/oauth/init`) will still work and will direct users to the download page after having them login.

**Comment by alexgibson** [comment]
Thanks @birdsarah, quick clarifying question: when the link points to https://vpn.mozilla.org/vpn/download, is it still going to be behind auth? I'm assuming we still want to add all the existing FxA metrics flow params etc? Thanks

**Comment by birdsarah** [comment]
It is not going to be behind auth, no. That is the motivation for this issue.

Adding all the FxA metric flow params is good as we log them guardian side so we'll be able to count successful flows through to the download page.

**Comment by birdsarah** [comment]
On the timing. I've thought about it more and actually you're welcome to deploy the link change whenever. When the auth gate is still up, we'll gracefully handle people coming direct to download page.

Removing the vpn-sub-not-found code should only be done after we've released v1.16 though.

**Comment by alexgibson** [comment]
> Removing the vpn-sub-not-found code should only be done after we've released v1.16 though.

I think it makes sense to wait a bit until you've released v1.16, thanks 👍

**Comment by birdsarah** [comment]
If you want to get started on this, v1.16 is now on staging (v1.16.b2) - https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn/download

**Comment by alexgibson** [comment]
@birdsarah I'm hitting a 502 on this URL is there are FxA flow params included: 

https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn/download?entrypoint=www.mozilla.org-vpn-product-page&form_type=button&utm_source=www.mozilla.org-vpn-product-page&utm_medium=referral&utm_campaign=vpn-product-page&data_cta_position=navigation&device_id=2a6e0ec30e5045329a23f70a2116db15&flow_begin_time=1633423105295&flow_id=adcd66a1f70808ea3440499fc19825672dd33351db4bfff88a0765bf6209943a

**Comment by alexgibson** [comment]
The above URLs are fixed on staging for me, but not yet on prod. @birdsarah is there likely to be a deployment this week?

**Comment by jbuck** [comment]
@alexgibson we deployed v1.16 this morning, and I think prod is working correctly now

**Comment by alexgibson** [comment]
Thanks @jbuck

**Comment by birdsarah** [comment]
The 502 bug was fixed in Guardian 1.17. Guardian 1.17 was temporarily taken down yesterday, but has now been restored on prod. So yes, this should be unblocked.
