### ISSUE TITLE
Update VPN EN landing page for 4.99 Cyber security month sale.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10539]
## Description

For Cyber Security Month we want to offer $4.99 / month pricing in EN, CA and UK. This would mean anyone who subscribes in these countries will get no commitment $4.99 pricing for as long as they keep the account. 

Current recommendation will be to change the top of the page to advertise a Cyber Security Month sale.

Copy and UX to be provided by Mary and Elise.

Brief: https://docs.google.com/document/d/1pd38js6cqChH_3Dqx-N3sXZdS_VfSjU5KaK4UEqmShU/edit?usp=sharing

This issue will be updated when more info is available.

---

#### Success Criteria
- [ ] Approved copy from Mary.
- [ ] Approved UX from Elise
- [ ] Send staging to Lauren for review and approval before merge.
- [ ] can be reverted at the end of October

**Comment by slightlyoffbeat** [comment]
For EN, CA and UK

**Comment by slightlyoffbeat** [comment]
This is terrible copy, but here is a rough idea to help with brainstorming
<img width="1170" alt="Screen Shot 2021-09-30 at 11 53 48 PM" src="https://user-images.githubusercontent.com/2030656/135578402-89aae6b3-6629-4461-9b2a-d6a4f3586071.png">
:

**Comment by alexgibson** [comment]
I'm going to make a start on the subscription button / geo logic, whilst we figure out the right UX/Copy.

**Comment by alexgibson** [comment]
Demo: https://www-demo1.allizom.org/en-US/products/vpn/

**Comment by slightlyoffbeat** [comment]
Looks good. Added do-not-merge per Lauren's email as we talk to legal and finance to make sure we communicate this as clearly and transparently as possible.

**Comment by alexgibson** [comment]
@slightlyoffbeat is this something that's still happening? Can we close this issue / PR if not? Thanks

**Comment by alexgibson** [comment]
@slightlyoffbeat I'm guessing seeing as it's November and this wasn't taken any further, we can close it?

**Comment by slightlyoffbeat** [comment]
@alexgibson I am sorry for the late response here. Yes this won't be taken further and can be closed.
