### ISSUE TITLE
Use an SQS queue for Contentful change notification

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#10544]
Bedrock currently polls Contentful for data changes, but this results in much more API use and data transfer than we need. We should be updating data only when notified by a webhook or the like. 

Contentful has a "webhook" type that will instead place the messages on a queue in SQS:

https://www.contentful.com/marketplace/webhook/aws-sqs/

All we need is an SQS queue with which to work. I believe we'll need 3 queues actually, one each for dev, stage, and prod. 

This issue can cover the work of setting up the queue and switching bedrock to using it. 

Success criteria:

- [ ] DB update code (`update_contentful`) only pulls from Contentful if there's a message in the SQS queue
- [ ] Local/developer users can always get new Contentful content, regardless of SQS state via a `--force` option

**Comment by pmac** [comment]
@duallain how should we go about getting the SQS work done here? Can we just make the via the AWS console, or would SRE prefer that we get this done via some automation of yours?

**Comment by duallain** [comment]
Pulled this in with https://mozilla-hub.atlassian.net/browse/SE-2694. Plan would be to pull it in this week or next.  Not 100% where our commitments are, but SQS queues are pretty easy and that doc has a nice outline of what we need to give to contentful to get everything working.  

We could also use this to teach a backend dev the tf bits if you'd like, it's simple enough this would be a great training ticket.

**Comment by pmac** [comment]
> We could also use this to teach a backend dev the tf bits if you'd like, it's simple enough this would be a great training ticket.

Excellent suggestion. We should involve @robhudson, @stevejalim and me.
