### ISSUE TITLE
Create re-usable system for determining when or when not to trigger VPN A/B tests

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10559]
## Description

There are several teams running a variety of tests on VPN. This includes the activation team (paid search, etc), product team (sending users from firefox to VPN) and the websites team (CRO tests).

We do not want to place users into our A/B tests if they are already coming from certain sources, or are already in a test. 

Historically, we have put rules into individual tests (ex: do not trigger if there is a certain UTM parameter).

We need a system that can be re-used across a/b tests so that we know our A/B tests.

This list can grow over time. For now, A/B tests should not trigger if URL:

- already has `entrypoint_experiment` or `entrypoint_variation`
- contains `utm_source=firefox-browser`
- contains `utm_medium=cpc`
- contains `automation=true` (to exclude automated tests)
- contains `experiment` (stub attribution experiments)
- contains `variation` (stub attribution experiments)

---

#### Success Criteria
- [ ] Able to easily apply criteria to multiple A/B tests

**Comment by alexgibson** [comment]
Suggest adding:

- `automation=true` (to exclude automated tests)
- `experiment` (stub attribution experiments)
- `variation` (stub attribution experiments)

**Comment by slightlyoffbeat** [comment]
@alexgibson good for the time being.
