### ISSUE TITLE
EPIC: Update mozilla.org for MR2

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10563]
## Description

This issue will be updated as we get more info.

Go Live: November 2nd.

Requested updates include:
- landing page for MR2. Current recommendation is a variation of /new with updated headline and MR2 image.
- 4 landing pages for facebook ads. This will use the new custom landing page designs Elise worked on. Everything will be the same between the 4 pages except for the headlines
- Change top promo on mozilla.org to mobile. Current recommendation is keep the same but have CTA lead to mobile
- Update 5 cards for MR2
- Update header and visual for /firefox/browsers/mobile/

---

#### Success Criteria
- [ ] TBD

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/10649
