### ISSUE TITLE
Feature VPN at top of mozilla.org homepage

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10560]
## Description

From now until Nov 2 (MR2) we should feature VPN at the top of mozilla.org. Lets keep this very simple.

- remove the Firefox MR1 unit (but keep ready to bring back Nov 2)
- Move the VPN unit to top of page
- Add a Firefox unit in the spot where the VPN unit was before moving it to the top.

Rough design:

![Screenshot 2021-10-06 at 20-57-48 Internet for people, not profit](https://user-images.githubusercontent.com/2030656/136318274-b055a2a0-b6f4-4e90-a122-45c19f99ce85.png)

**Comment by slightlyoffbeat** [comment]
Lets not worry about a Firefox unit for now. Lets simply:
1. remove the firefox promo at the top of the page (but keep in bedrock because it will be re-used for MR2
2. move the VPN unit to the top of the page

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/10603
