### ISSUE TITLE
Evaluate a front-end JS framework for bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10566]
## Description

Whilst most of the content we create is rendered server-side, occasionally we need to create interactive components that are almost entirely dependent on JS and need to manage some kind of state. Some examples might include:

- A custom pop up or notification.
- An interactive form or widget.
- Conditional messaging based on a set criteria (e.g user agent, FxA sign in state).

Using a front-end templating library of view framework could help make some of this work faster to build and easier to maintain. The purpose of this issue is to evaluate some possible options, and then to make a recommendation for what we should use in bedrock for these types of task. Some options might include:

- React
- Preact
- Vue
- Svelte
- Web components (?)

Requirements and considerations:

- How to manage localized strings.
- Progressive enhancement.
- Page load performance / impact.
- Rendering speed.
- Framework stability / quality of maintenance.

To help assess what a suitable tool might look like, it may be worth to build a few demos for comparison.

---

#### Success Criteria
- [ ] Evaluation of chosen 2-3 frameworks.
- [ ] Document recommended choice.

**Comment by alexgibson** [comment]
I'd like to try and wrap this up in Q1 to make some kind of formal recommendation, if only based on an initial evaluation if that's all we get time for. Real-world usage is always the best measure, but that's not something we may have the luxury of affording time and effort to do.

I think we can likely rule out option 1 (native web components), given that it appears to have quite deep learning curve with some potential quirks?

Maybe we could test out a short list from options 2 and 3? Given that we're looking for something more lightweight than React/Vue, perhaps we could decide between:

- Lit: https://lit.dev/
- Preact: https://preactjs.com/
- Svelte: https://svelte.dev/

**Comment by maureenlholland** [comment]
> Maybe we could test out a short list from options 2 and 3? Given that we're looking for something more lightweight than React/Vue, perhaps we could decide between:
> 
>     * Lit: https://lit.dev/
> 
>     * Preact: https://preactjs.com/
> 
>     * Svelte: https://svelte.dev/

This list looks good to me. I can start with demos of Lit and Svelte by the end of January and we can add options or test tougher cases depending on initial impressions of these options.

**Comment by reemhamz** [comment]
Thanks for the reminder on this issue -- it has slipped my mind. @maureenlholland sounds like a plan. I'm also happy to pick up Lit or Preact.

**Comment by maureenlholland** [comment]
Slowly but surely moving forward on this. We have decided to run initial comparison between Lit and Svelte, dropping Preact for the following reasons:

1. **lagging feature compatibility**: React changes in v16 (released Sept. 2017) and v16.8 (released Feb. 2019) took a long time for Preact to adopt (v10 included fragments and a hooks add-on, released Oct. 2019). 
2. **maintenance**: Preact doesn’t have official sponsored development (Svelte now has Vercel backing, Lit has Google)
3. **onboarding**: steeper learning curve with the use of JSX and React-y boilerplate

**Comment by alexgibson** [comment]
@maureenlholland @reemhamz not urgent at all, but did we manage to get any closer on deciding between Svelte and Lit? I seem to remember seeing a comparison spreadsheet at some point, but not sure if it was ready or not?

**Comment by maureenlholland** [comment]
Comparison sheet is here (Mozilla access only): https://docs.google.com/spreadsheets/d/1eN_9oYLnlriNwPImbEtWxpiywNEUezLFNeNZVZJZsGI/edit#gid=287914988

I'm not sure how far along the Lit demo is, but maybe we can aim for next Dev Extravaganza meeting or a Front-end specific meeting early June to show demos and discuss further. How does that sound to you @reemhamz ?

**Comment by alexgibson** [comment]
Thanks @maureenlholland! We have a couple of things where a framework might be useful. So whichever thing we choose might be a good test candidate for one of the following:

- https://github.com/mozilla/bedrock/issues/11149
- https://github.com/mozilla/bedrock/issues/9845

Probably the basket preference centre would be first.

**Comment by alexgibson** [comment]
Also I really like the idea of doing a demo / walk through of both when we're ready 👍

**Comment by reemhamz** [comment]
Unfortunately, it has been a tad challenging finding much time to work on this with some tickets coming in + working on professional goals. However, while working on it and studying up on it a bit more, I was hearing some opinions from other developers stating they don't know how long Google will maintain this, as they do have a history of deprecating certain things. I also know Svelte is highly revered in the dev community and there is much support and respect for it. 
I'm happy to see the pros of Svelte when Maureen demos it and seeing its implementation and not moving forward with Lit, seeing as Svelte may be the safer route.

**Comment by maureenlholland** [comment]
No worries @reemhamz - thanks for noting the maintenance concern! I'm going to put together something small for Lit to give a sense of what a web component framework might look like.

**Comment by reemhamz** [comment]
That's great, thank you @maureenlholland!

**Comment by alexgibson** [comment]
Thanks both for pushing this forward. I think we can likely decide what to do with after watching Maureen's demo, and then we can close this issue out :)

**Comment by reemhamz** [comment]
Same here. Thanks @maureenlholland for demoing!
