### ISSUE TITLE
Optimise images on /firefox/privacy/book/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10580]
## Description

The following page weighs in at a surprising 5.58MB: https://www.mozilla.org/en-US/firefox/privacy/book/

Requests are almost entirely images: 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/400117/136964868-22ac94f7-6a6d-4c31-b412-465fd44b47fd.png">

Some assets, such as `privacy-book-arrow-on-face.png` weigh in at over 1MB each.

There is likely a bit we could do to make this page perform better.

- Lazy load images with `loading="lazy"`
- Reduce the overall dimensions of some images? (is it just me, or are some of them way bigger than they need to be visually?)
- Can images be compressed better?

**Comment by joneskj55** [comment]
Hi @alexgibson I'd like to take this on. I have a few ideas on how to optimize the images and enhance the performance of this page.

**Comment by alexgibson** [comment]
This was fixed - the page is now ~600kb on first page load 🔥
