### ISSUE TITLE
Remove Yarn as a dependency

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10588]
## Description

We added Yarn as a dependency for installing NPM packages in bedrock some years ago. This was mostly because Yarn created a lockfile of dependencies to make installs more predictable, which as a feature was ahead of NPM at that time. Since then, I believe NPM has caught up in this respect and now creates an equivalent lockfile of its own.

We should remove Yarn as a dependency, rather than keep it around for the sake of another dependency.

---

#### Success Criteria
- [x] Yarn is removed as a dependency for installing packages.
- [x] Docs are updated.

**Comment by Ayushsunny** [comment]
Hi @alexgibson Can I take this one?
