### ISSUE TITLE
Split Sentry into FE and BE buckets 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10593]
## Description

At the moment, all Bedrock's Sentry logging goes into one place, whether it's backend or frontend. 

To make spotting and triaging issues easier, it seems sensible to split them into two projects - eg `bedrock-{dev|stage|prod}-frontend` and `bedrock-{dev|stage|prod}-backend`.

---

#### Success Criteria
- [ ] Separate, working, FE and BE projects exist in bedrock for each of dev, staging and prod envs

**Comment by alexgibson** [comment]
Closing this as fixed, but feel free to reopen @stevejalim if there's still something that needs doing here

**Comment by stevejalim** [comment]
👍👍
