### ISSUE TITLE
Build a contentful-powered landing page for instagram links

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10598]
## Description

We were approached with an idea for a project to create our own linktree for instagram that is GDRP compliant and lives on our website.

Brief: https://docs.google.com/document/d/1YZrgiL3j4UnW9tArKSoEMMvxCC5UCr3ibNE1obYxe6E/edit?usp=sharing

---

**Comment by alexgibson** [comment]
@slightlyoffbeat is this something still relevant today? If not, can we close it?

**Comment by alexgibson** [comment]
Closing stale issue
