### ISSUE TITLE
[contentful] Image components should have the option to lazyload

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10669]
## Description

https://www-dev.allizom.org/en-US/contentful-preview/01i30zNjYwlPkmcAoc1hy0/

I believe card components support lazy loading already, but none of the components on the redesigned home page seem to, which can hurt performance. We should add support for `loading="lazy"` or `"loading="eager"`.

**Comment by nathan-barrett** [comment]
Not sure if this ticket is actually ready but I was just taking a look through this and noticed that a lot of the images on the home page use the `high_res_img` or `lazy_img` helpers in bedrock - would there be any issue with adding and loading argument to the protocol macros (which would then cascade down to one of those two python helpers).

As far as I could see the two components would `hero` and `split` (with hero, i'm not sure how long that will be used)
@alexgibson @craigcook

**Comment by alexgibson** [comment]
@nathan-barrett I think it's safe enough to start using the `loading` attribute, migrating away from the older `lazy_img` helper.

Adding this attribute to the jinja macros is definitely the way forward. I'd suggest using `eager` by default, and then allowing `lazy` to be configured via a paremeter. I guess the more complex part of this will be how to choose the right value in Contentful powered pages. Images that appear at the top of the page should likely use `eager`, whilst images that appear below the fold would benefit from `lazy`. My gut says we should probably try and keep this logic in bedrock, as opposed to make it an option in Contentful, but other ideas / suggestions are welcome.

**Comment by alexgibson** [comment]
Now that https://github.com/mozilla/bedrock/issues/8752 has merged, all the the Protocol macros used in the home page should support a paramter for enabling native lazy loading. 

How we make use of this in Contentful powered pages remains to be seen. It seems like a lot to expect content publishers to remember a checkbox for this, so perhaps we can build some logic in bedrock to make a best guess if an image appears below the top section of a given page?

**Comment by alexgibson** [comment]
@nathan-barrett not sure if you were actively working on this as it's quite an old issue, but I took a go at making a quick PR to hopefully help improve things: https://github.com/mozilla/bedrock/pull/11447
