### ISSUE TITLE
[contentful] change firefox link for CTA button content type

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10662]
## Description

The Firefox option currently links to: /firefox/download/thanks/

It should be updated to link to just /firefox

**Comment by maureenlholland** [comment]
@slightlyoffbeat Can the link be more Firefox Browser-specific? https://www.mozilla.org/en-US/firefox/browsers/

**Comment by slightlyoffbeat** [comment]
cc: @maureenlholland 

After discussion on Slack, there is a proposed change to this issue:

Instead of changing the existing "Download Firefox" destination, we instead add a new "Explore Firefox" option.

Download Firefox - downloads firefox
Explore Firefox - /firefox/browsers
