### ISSUE TITLE
[Comparison page update] Edge now available on Linux

### ISSUE THREAD

**Issue by ElijahPepe** [mozilla/bedrock#10676]
## Description

Edge for Linux has now [officially released](https://arstechnica.com/gadgets/2021/11/microsoft-edge-for-linux-enters-stable-channel-after-a-year-of-betas/) in the stable channel.

---

#### Success Criteria
- [ ] Comparisons between Firefox and Edge should be updated to reflect such change in Edge.

**Comment by alexgibson** [comment]
Linux availability is now reflected here:

- https://www.mozilla.org/en-US/firefox/new/
- https://www.mozilla.org/en-US/firefox/browsers/compare/edge/
