### ISSUE TITLE
FxA metrics flow requests are broken when Dev=True

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10670]
## Description

When `Dev=True` bedrock's FxA links all point to https://stable.dev.lcip.org/, which is currently 500. Talking to jbuck, this instance has gone unmaintained intentionally, so we need to switch to another staging instance.

We're still discussing what a suitable alternative might be (ideally we need an environment that supports CORS requests for localhost). Will update when ready.

**Comment by jbuck** [comment]
Yep, absolutely! just add the domains you need to https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/fxa/puppet/yaml/type/fxa.content_server.stage.yaml#L9

**Comment by alexgibson** [comment]
@jbuck looks like I don't have access to this repo, which I asume is private?

**Comment by jbuck** [comment]
I've requested access for you in https://github.com/mozilla-services/github-management/issues/128 (which you also won't be able to view until you're granted access 😅 )

**Comment by alexgibson** [comment]
PR to enable CORS for localhost: https://github.com/mozilla-services/cloudops-deployment/pull/4452

**Comment by alexgibson** [comment]
This is now fixed for both www-dev and localhost. Thanks @jbuck 💯
