### ISSUE TITLE
[Contentful] Add CTA Location field

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#10678]
## Description

We noticed [blank location values in the CTA fix PR](https://github.com/mozilla/bedrock/pull/10665#pullrequestreview-796291293). This is due to a hardcoded empty string in the [API](https://github.com/mozilla/bedrock/blob/master/bedrock/contentful/api.py#L191).

We want to hook up a location field value from Contentful to Bedrock to record click location for analytics.

---

#### Success Criteria
- [ ] Contentful Component:CTA Button needs Location field with [validated value options](https://bedrock.readthedocs.io/en/latest/analytics.html)
- [ ] Bedrock CTA template needs to conditionally set the location value with the appropriate attribute or argument (it is an optional value)

**Comment by maureenlholland** [comment]
still relevant as a comment TODO in code, but should check in on analytics to make sure it's still helpful (and see if any other analytics params are needed in the content model/api)

**Comment by alexgibson** [comment]
@stephaniehobson is this an attribute we'll still be using in GA4? If not, can we close this issue?

**Comment by stephaniehobson** [comment]
I was not planning to migrate it unless someone requested it specifically (and no one has yet). So, good to close.
