### ISSUE TITLE
New Pocket homepage

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10686]
Studio team will have designs for a new homepage for getpocket.com. This will include a promotion for the integrated Pocket Best Of campaign.

### Design & Copy:

To be provided when ready (see timeline)

### Notes

- English only. Because this is a static/flat/scraped site (for now) we've only committed to delivering for en
- German as a stretch goal, if time and resources allow
- This page can be built using whatever method the developer chooses. Because of timing, it does not need to align with the build tool work that is currently underway for getpocket.com

### Timeline:
Nov 5: Low-fi wireframes & mockups
Nov 11: Design handoff
Dec 1: Go-Live

**Comment by slightlyoffbeat** [comment]
Assets are coming in! I'll attach en in another comment.

[German Copy doc](https://docs.google.com/document/d/1Ha9Hqp7XOU3fo0yNmw1H_YJCXngF4X5Da-My3dcDLY4/edit#)

[German Figma file](https://www.figma.com/file/BueH10hbfo96Xg8dhIQzgw/Site%3A-getpocket.com-LP?node-id=26%3A199)

Notes: 
- it was previously discussed that other locales besides english is a stretch goal. German is now in scope and all other languages are a no.
- If any assistance is needed with exporting from the figma file, please reach out to me, or ask for help in the project slack channel.

**Comment by slightlyoffbeat** [comment]
Assets for English

[Figma File](https://www.figma.com/file/BueH10hbfo96Xg8dhIQzgw/Site%3A-getpocket.com-LP?node-id=0%3A1)

[Copy Document](https://docs.google.com/document/d/1qDCX0b_gbNpBkbbMa0Pbl77JXAdOrDgtu5_x4w6ure0/edit?usp=sharing)

Exported visual assets: coming soon.

Notes: there was a question around whether the hero image at the top of the page should be cropped or not. I asked studio team to provide both.

**Comment by slightlyoffbeat** [comment]
@maureenlholland I wanted to make sure you also saw the Best-of promo in the figma file that should be added to the top of these pages above navigation.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozmeao/pocket-marketing-pages/pull/38
