### ISSUE TITLE
State of Mozilla 2020

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10685]
State of Mozilla 2020 will require a new page.

This card will be updated as details are available.

[For reference: State of Mozilla 2019](https://www.mozilla.org/en-US/foundation/annualreport/2019/)

Details and content are not ready. Here is what we know so far:

- We will use the same style/theme as last year
- This will live at `/foundation/annualreport/2020/`
- There will be less content than last year, but it will follow a similar pattern.

Current recommendation is to scaffold out the page and get a much done as possible in order to be ready for last-minute content. Use last year's content, placeholder images, and ipsum until content can be provided.

Go-live date: 1st week of December (TBD)

Here is the proposed structure of the page. It uses patterns and layouts from last years page, but is simplified.

![Artboard](https://user-images.githubusercontent.com/2030656/140251962-e63e0f80-5653-4ed7-94e3-103883ba792b.png)

===

### Success Criteria

- [x] `/foundation/annualreport/ `redirects to `/foundation/annualreport/2020/`

**Comment by slightlyoffbeat** [comment]
Launch date will be either Dec 9 or Dec 14.

**Comment by alexgibson** [comment]
This is live https://www.mozilla.org/en-US/foundation/annualreport/2020/
