### ISSUE TITLE
VPN landing page and/or FAQs should call out that the 30 day money back guarantee is only for purchases on the website

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10696]
## Description

Our landing page calls out the 30 day money back guarantee prominently. Our FAQs call out the 30 day money back guarantee, but does not provide info that purchases from app stores are not included.

Details and suggestions for how to fix are available at this Jira ticket: https://mozilla-hub.atlassian.net/browse/VPN-1173

**Comment by alexgibson** [comment]
@slightlyoffbeat the proposed updated copy for the FAQ section is: "You can get your money back within 30 days of purchasing your subscription through your Firefox account or through Firefox, from this website”.

There is also a suggestion of adding an asterisk to the end of other places that mention "30-day money-back guarantee *".

However an asterisk should really have a footnote, or something visible on the page that it relates to. What would you suggest here? The Jira comments don't seem very clear. 

Also, does this proposed copy need to be passed by legal at all?

**Comment by alexgibson** [comment]
We could possibly add a foot note below the legal links / copy here?

![image](https://user-images.githubusercontent.com/400117/140498718-2e78708d-57af-4ae3-88dd-524689a92539.png)

**Comment by alexgibson** [comment]
We should also consider that this guarantee copy is on several other SEO pages: https://www.mozilla.org/en-US/products/vpn/more/what-is-a-vpn/

**Comment by alexgibson** [comment]
@slightlyoffbeat ok here's what I propose:

1. Add an astersik to all occurences of  "30-day money-back guarantee" on VPN web pages.

<img src="https://user-images.githubusercontent.com/400117/140501445-7af2cd7e-66f5-4d24-8f3f-bf4e6e40cc0d.png" alt="image" width="600">

2. Add an astersik to the FAQ section title to connect the guarantee copy to, together with updates copy when you click to expand:

![image](https://user-images.githubusercontent.com/400117/140501592-961290c4-47da-48d7-ba71-3446804be533.png)

For the SEO pages, I suppose just item 1. might be enough, since those pages all link to the main product page?

Does this look / sound ok? Let me know, thanks.

**Comment by alexgibson** [comment]
@slightlyoffbeat here's a demo of where things are https://www-demo1.allizom.org/en-US/products/vpn/

**Comment by slightlyoffbeat** [comment]
Demo has been shared with stakeholders and we are waiting for a thumbs up.

**Comment by slightlyoffbeat** [comment]
Feedback from stakeholders:

They like the implementation, but have requested a copy change for the "What is Mozilla VPN's refund policy. They would like to use the language from the T&C which is more clear (and I agree).

New copy is below. No further feedback rounds are needed with stakeholders as long as we are good change the copy.

### Current is:
_You can get your money back within 30 days of purchasing your subscription through your Firefox Account or through Firefox, from this website. Contact us and submit the refund request by tapping the “Get Help” button in Settings on your Mozilla VPN app._

### New copy is:
_The first time you subscribe to Mozilla VPN through Mozilla's website, if you cancel your account within the first 30 days, you may request a refund and Mozilla will refund your first subscription term._

_If you purchase your subscription through in-app purchase from the Apple App Store or the Google Play Store, your payment is subject to the terms and conditions of the App Store. You must direct any billing and refund inquiries for such purchases to Apple or Google, as appropriate._

**Comment by alexgibson** [comment]
Thanks @slightlyoffbeat I've updated with the approved copy and marked as ready for code review.
