### ISSUE TITLE
https://www.firefox.com/set_hsts.gif redirects back to /firefox/new/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10692]
## Description

In every page load for mozorg there's a request being made to the /firefox/new/ page when an image tries to load.

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/400117/140376580-42886b10-2f2e-45fd-a0f0-42a64ad544af.png">

### Steps to reproduce

1. Load https://www.firefox.com/set_hsts.gif

### Expected result

It should load a gif.

### Actual result

It redirects to https://www.mozilla.org/en-US/firefox/new/?redirect_source=firefox-com

### Environment

Firefox Nightly

**Comment by robhudson** [comment]
See also https://github.com/mozilla/bedrock/issues/9898
