### ISSUE TITLE
Newletter recovery page renders hyperlink as text in error message

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10691]
## Description

On https://www.mozilla.org/en-GB/newsletter/recovery/ if you enter an email address that is not in the newsletter DB, the error message shows raw HTML markup

<img width="529" alt="Screenshot 2021-11-04 at 14 31 00" src="https://user-images.githubusercontent.com/101457/140332560-c8312e44-915b-40ef-be96-a2a4e487b361.png">

### Steps to reproduce

* Go to https://www.mozilla.org/en-GB/newsletter/recovery/
* Enter an email address that does not appear in the newsletter system (eg stevejalim@example.com)
* Submit

### Expected result

The error message should contain a clickable hyperlink to the subscription page

### Actual result

The error message shows raw/escaped HTML for the link to the subscrioption page

### Environment

Nightly, MacOS Big Sur

**Comment by abhisharsinha** [comment]
Hi @stevejalim @pmac, could you please review my pull request and give feedback.
