### ISSUE TITLE
Newsletter management page leaking MPL notice

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/bedrock#10690]
## Description

When managing the Email Preferences for my Firefox Account there is a section to choose the format of your email. It appears we have an MPL-2.0 notice rendering in this section.

### Steps to reproduce

1. Visit the Newsletter Subscriptions page (`https://www.mozilla.org/newsletter/existing/abc123/?fxa=1`)
2. Observe the "Format" section on the page

### Expected result

Radio buttons to choose your email format.

### Actual result

The following visible text:

```
{# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/. #} 
```

### Additional information

Best I can tell is it's coming from [here](https://github.com/mozilla/bedrock/blob/master/bedrock/newsletter/templates/newsletter/existing.html#L1-L5).

<img width="780" alt="Screen Shot 2021-11-04 at 10 40 31 AM" src="https://user-images.githubusercontent.com/6392049/140330653-a2c4b179-7a0a-436a-aef6-21365a5dda3a.png">

**Comment by stevejalim** [comment]
@pmac Dang, this looks like a side effect of the pre-commit licence hook on a partial

**Comment by stevejalim** [comment]
Thanks for the report @jodyheavener - I appreciate the code-rummaging, too. I think it's actually coming from a template partial which is rendered by the relevant form, which would explain why it's not getting ignored as a regular Jinja comment. 

We're on it!
