### ISSUE TITLE
Fundraising banner for Mozilla Foundation

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10700]
## Description

[Issue for previous banner for reference](https://github.com/mozilla/bedrock/issues/6693#)

Functionality can stay stay the same. We will update the design and background image.

Mofo has requested a fundraising banner for two dates:
1. Nov 30 (giving tuesday)
2. Dec 21 - 31

---

### Design
Mockup images in google drive: [desktop & mobile](https://drive.google.com/drive/folders/1VmFhMURm0ipFwc8k2nRTuHybcibgmSAx?usp=sharing)
Banner image in google drive: [blue banner](https://drive.google.com/open?id=1VcBPsENRH-VcJT8IFPlPhzJ2xZpRb9xg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
Figma files: [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A270) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=116%3A625&viewport=501%2C48%2C0.25&scaling=scale-down&starting-point-node-id=116%3A625&show-proto-sidebar=1)

### Copy
Used Giving Tuesday copy from the No Testing section for mockups: [google doc](https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing)
This contains text for both Giving Tuesday (November 30), and Year-End of December (between 12/20/21 and 12/31/21) banners.

#### Success Criteria
- [ ] Launch Giving Tuesday version on Nov 30
- [ ] Turn off Giving Tuesday Version on Wed 1
- [ ] Turn on Holiday version on Dec 21
- [ ] Turn off Holiday version on Dec 31
- [ ] Switch

**Comment by alexgibson** [comment]
Gonna pick this one up seeing as it hasn’t been claimed yet.

**Comment by alexgibson** [comment]
@slightlyoffbeat the suggested headline copy is pretty long here, even for English (other locales will be longer still):

![image](https://user-images.githubusercontent.com/400117/141306436-bf5e6b3b-beb2-416e-8b7a-733ee487b12f.png)

May I suggest using a shortened version instead?

![image](https://user-images.githubusercontent.com/400117/141306542-2e7e62e9-c8f2-433e-b5dd-1d053c8aa8e2.png)

**Comment by alexgibson** [comment]
Oh, please disregard the last comment. I see the mockup differs a little to the copy doc. They have moved the second line of heading to the banner copy. It should look like this which is fine:

![image](https://user-images.githubusercontent.com/400117/141307985-c1e22207-3497-4a20-8224-f37378ad0309.png)

**Comment by alexgibson** [comment]
@slightlyoffbeat WIP banner is up on demo: https://www-demo1.allizom.org/en-US/

**Comment by slightlyoffbeat** [comment]
Looks good. Sharing with stakeholders and I should have feedback next week.

**Comment by sabrinang** [comment]
Thanks for the progress on this @alexgibson ! I have design questions/feedback after looking at the demo:

**Interaction:**

- To clarify my understanding, if a person dismisses the banner by tapping X it will never return again (on that browser)?
- Close animation: could it ease out the top to close in 200ms when the X icon is tapped? (animation in [prototype](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=116%3A625&viewport=270%2C48%2C0.66&scaling=scale-down&starting-point-node-id=116%3A625&show-proto-sidebar=1))


**Design:**

- Banner position: could it be above navigation like the mockup? (or does it have to stay below)
- Button alignment: the donate button is a bit off on desktop (a bit low) and mobile (a bit right)
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/2492510/141835830-8918d273-ac79-4db0-9e64-6538d49cb9bf.png">

- Button on mobile: could the donate button be wider on mobile? (like how the `Sign up now` button by the bottom of the mozilla.org page spans across columns)

**Comment by alexgibson** [comment]
> To clarify my understanding, if a person dismisses the banner by tapping X it will never return again (on that browser)?

The fundraising banner uses the standard banner component we use across mozorg, which features a close button. Pressing the close button will set a cookie that prevents the banner from being shown again for 1 day.

> Close animation: could it ease out the top to close in 200ms when the X icon is tapped? (animation in prototype)

I'm going to say no to introducing changes to the base banner functionality at this time, as it's beyond scope of just the fundraising banner. But thatnks for the suggestion.

> Banner position: could it be above navigation like the mockup? (or does it have to stay below)

Yes this is a configurable option, I'll set it to above the navigation.

> Button alignment: the donate button is a bit off on desktop (a bit low) and mobile (a bit right)

I'll take a look here, thanks.

> Button on mobile: could the donate button be wider on mobile?

I'll update, thank you.

**Comment by alexgibson** [comment]
@sabrinang feedback changes are now updated on demo, thank you.

**Comment by sabrinang** [comment]
@alexgibson Thanks for making those updates!

I checked with fundraising and they'd want to flip the order of `One-time` & `Monthly` radio buttons so the banner matches the order seen on the donate page and to also make `Monthly` the default selection instead of `One-time`.

**Comment by alexgibson** [comment]
@sabrinang good suggestion - updated, thanks again.

**Comment by sabrinang** [comment]
@alexgibson Sorry to revise one last time, the team decided to default back to `One-time` instead so it sticks to existing revenue expectations. Thanks for all your help and it'll be good to go!

**Comment by alexgibson** [comment]
@sabrinang got it, thank you
