### ISSUE TITLE
Add Relay copy to Firefox Products page

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#10709]
## Description

In the [products](https://www.mozilla.org/en-US/firefox/) page, each product has its own section describing its uses, however Relay doesn't have one just yet. We've added the icons in relevant places (#10699), now we just need to add a section for it. 

---

#### Success Criteria
- [ ] Receive copy from team
- [ ] Add it to the page

**Comment by slightlyoffbeat** [comment]
@slightlyoffbeat check on assets

**Comment by reemhamz** [comment]
@slightlyoffbeat any updates on this?

**Comment by slightlyoffbeat** [comment]
Lets move this forward:

Text: Un-spam your life with Firefox Relay 
CTA: Try Relay
Photo: lets re-use the relay photo from the homepage
Link: https://relay.firefox.com/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=firefox-home
