### ISSUE TITLE
Firefox Accounts CTA at bottom of the home page is a total mystery

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10706]
## Description

The Firefox Accounts promo at the bottom of the home page (visible to Firefox users) is now orphaned from the primary FxA content that used to be on the page. On its own (at least to me) it now makes little sense, as the messaging is way too cryptic.

### Steps to reproduce

Open https://www.mozilla.org/en-US/ and scroll all the way to the bottom:

![image](https://user-images.githubusercontent.com/400117/140495011-30f5d9f0-4ff5-4575-8dc0-1620b651ab8f.png)

### Expected result

The promo should at least let people know that "account" is actually a "Firefox Account", and give an idea of what the benefits are to entice people to click "Learn more".

### Actual result

The CTA doesn't even say what "account" means. It's a total mystery, unless someone actually clicks "Learn more".

### Environment

Firefox Nightly

**Comment by Ayushsunny** [comment]
Hey @alexgibson So, what should be the exact message you want to show on the promo?

**Comment by alexgibson** [comment]
> So, what should be the exact message you want to show on the promo?

This has not been discussed / decided yet.
