### ISSUE TITLE
Contentful HRs are rendered as escaped HTML

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10712]
## Description

When a Horizontal Rule element is added to a rich-text field in Contentful, it is rendered incorrectly:

1. it is escaped as `&lt;hr&gt;`
2. it is rendered as a self-closing tag `<hr />` but it should just be `<hr>` [mdn link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)

(This issue may be specific to the Page: Resource Center type, but maybe not)

### Steps to reproduce

Add a HR to a rich-text field between some text content and preview the page

### Expected result

I should see a horizontal line between the two items of text

### Actual result

I see "`<hr />`" instead

**Comment by Ayushsunny** [comment]
Hey @stevejalim I don't see any `<hr />` here 

![image](https://user-images.githubusercontent.com/73520373/141266286-f074685b-b042-4390-a3ec-37c4dc0cef9f.png)

**Comment by stevejalim** [comment]
Heya @Ayushsunny thanks for the note. I was talking with a colleague yesterday about this and it's specifically down to the allowed tags when we pass contenful rich text through `bleach`, so it's very specific to bedrock. 

I'll be fixing it today, but thanks for looking and asking!
