### ISSUE TITLE
Adblock page contains outdated content

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#10720]
## Description

This page contains outdated information, Content Blocking feature is not in the dropdown menu.

### Steps to reproduce

https://www-dev.allizom.org/en-US/firefox/features/adblocker/ - Description is out dated. `To start, click on the Firefox menu in the top right-hand corner of your screen. It looks like three lines stacked on top of each other. In the drop-down menu, click on Content Blocking.`

### Expected result

Rewrite part of the page to reflect how it works now.

**Comment by Ayushsunny** [comment]
Hey @peiying2 Could you please send the description which replace the current description as i've never used this feature so i don't know what should be written here?.

**Comment by denyshon** [comment]
Here's the Support article that could be useful: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop

**Comment by alexgibson** [comment]
@craigcook is this something we could fix as part of your feature pages update?

**Comment by craigcook** [comment]
> @craigcook is this something we could fix as part of your feature pages update?

Yeah, we can update this.
