### ISSUE TITLE
Pocket best-of promo on mozilla.org

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10738]
## Description

There is a request to advertise the pocket best-of promo on mozilla.org

Recommendation for discussion:

Use the promo that is designed for getpocket.com. It would sit above navigation.

Thoughts on this approach
- we be very intentional for how long we keep a promo like this up. It is very prominent.
- We should confirm what pages to show it on. If it is on all of Mozilla.org, it may detract from clicks for other products that have end-of-year pushes. I'd recommend keeping it off of /new and vpn landing page.
- We would need to be sure that we avoid conflicts with the mofo donation banner.

Another option is updating the image and copy for the pocket section on the mozilla homepage.

My vote is the first option. It will get more eyeballs and this is a large integrated campaign.

Screenshot:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/2030656/141386331-43aab2ed-d260-4b94-bc1c-43864252d359.png">

[Figma File](https://www.figma.com/file/BueH10hbfo96Xg8dhIQzgw/Site%3A-getpocket.com-LP?node-id=0%3A1)

@maureenlholland is building the pocket site and promo for getpocket.com so there may be an opportunity to use some of the work happening there.

---

#### Success Criteria
- [ ] Switch

**Comment by alexgibson** [comment]
@slightlyoffbeat for some added context here, our banner system is designed so that users visiting our pages will only see a single banner at a time (as in, our code only affords to one banner per page/locale). So if someone sees the Pocket promo banner, they won't see the fundraising banner, as an example. The original intent here was we should avoid potential overloading of promo content.

If we do want to start introducing multiple banners on a single page, then we would need to make the necessary code changes to accomodate it such a system.

**Comment by slightlyoffbeat** [comment]
I want to avoid ever showing more than one banner on a single page at the same time. 

Right now, there is no overlap between banners. MoFo is requesting Nov 30 & Dec 21 - 31

Pocket banners would be Dec 1 - Dec 15.

**Comment by maureenlholland** [comment]
I can probably pick this up, but I'm hoping to get Pocket Home ready for review first. If someone else wants to jump on it, these are the relevant files from the Pocket repo:
https://github.com/mozmeao/pocket-marketing-pages/pull/38/files#diff-0cf0e4440bab46e815d12d2c9b4cd1372b301d01fe5f708772a8b3e2ea0589af
https://github.com/mozmeao/pocket-marketing-pages/pull/38/files#diff-d3937b0e5a1df9650afd08ef4cbf8835c7e0f1699ce4319b388026840840eab8

Note: German page had a different banner style, but I assume on moz.org we can stick with the 2021 image version for all languages

**Comment by maureenlholland** [comment]
@slightlyoffbeat To confirm, we only want one version of this banner in bedrock, correct?

The German figma files have a different banner: https://www.figma.com/file/BueH10hbfo96Xg8dhIQzgw/Site%3A-getpocket.com-LP?node-id=333%3A6763

**Comment by slightlyoffbeat** [comment]
Yes, lets just have one single banner. We can go with the En design
