### ISSUE TITLE
11/29 VPN Moments page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10737]
## Description

Part of Epic https://github.com/mozilla/bedrock/issues/10702

[Copy Document](https://docs.google.com/document/d/1_TNRdo4t0yrNO5RBfSPTRrCkxEJ94rGHAKdEgS31Fp0/edit?usp=sharing)

Designs: https://www.figma.com/file/UFZ8R9V3lVxpZFQ34g0fN9/VPN-Moments

Slack Channel: `#www-moments`

Go Live Date: 11/29
---

#### Success Criteria
- [ ] Localize Page
- [ ] Develop Page
- [ ] Go live 11/29

**Comment by slightlyoffbeat** [comment]
Designs are not handed off yet, but this is a WIP preview shared
![Screen Shot 2021-11-11 at 1 29 05 PM](https://user-images.githubusercontent.com/2030656/141371889-112015e0-6de2-4125-b214-4f5f561d2a41.png)
:

**Comment by craigcook** [comment]
On demo: https://www-demo4.allizom.org/firefox/welcome/11/
