### ISSUE TITLE
Remove unused picto card code from Privacy Products JS

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#10731]
We updated our code to use [Picto](https://protocol.mozilla.org/patterns/molecules/picto.html) components after Picto Cards were deprecated.

A side effect of this was breaking the Picto Card Title JS selector in [Firefox's Privacy Products page](https://www.mozilla.org/en-US/firefox/privacy/products/)

Because we already have two links allowing users to open the Protection Report on this page. We don't need to reinstate title links. The Picto Card JS code should be removed.

To set up UITour locally: https://bedrock.readthedocs.io/en/latest/uitour.html#local-development

Success Criteria:

- [ ] Firefox Privacy Products JS code should no longer reference Picto Cards. See relevant file here: https://github.com/mozilla/bedrock/blob/master/media/js/firefox/privacy/products.js#L36
- [ ] Firefox Privacy Product page should still show Protection Report when users click on "See what Firefox has blocked for you" **while using a Firefox Browser**

ℹ️ The Protection Report is part of a Firefox user's `about:protections` page. This will not be available on other browsers. When you click "See what Firefox has blocked for you", you should see something like this:
<img width="804" alt="firefox protection dashboard, personal to each user" src="https://user-images.githubusercontent.com/19650432/141302676-4b24fa47-b627-4a8a-a166-846ec0b99c52.png">

**Comment by menghif** [comment]
@maureenlholland Hi, I'm trying to reproduce this locally but when I click on "See what Firefox has blocked for you" it takes me to the [support page](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?utm_source=mozilla.org-privacy-products&utm_medium=referral&utm_campaign=privacy-products&entrypoint=mozilla.org-privacy-products) instead of `about:protections`.

`Mozilla.UITour.showProtectionReport()` returns 'undefined' instead of taking me to `about:protections`.

Is there any steps I am missing?

**Comment by maureenlholland** [comment]
> Is there any steps I am missing?

@menghif great question - yes, I've linked it in the description now. There are some changes to you have to make in your Firefox config to get UITour working locally, relevant part of the docs below: 

**Local development**

To develop or test using Mozilla.UITour locally you need to create some custom preferences in `about:config`.

browser.uitour.testingOrigins (string) (value: local address e.g. http://127.0.0.1:8000)
browser.uitour.requireSecure (boolean) (value: false)

**Comment by menghif** [comment]
Thank you for your help @maureenlholland! I'm sending a PR now
