### ISSUE TITLE
Contentful: Support getting better quality images

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10743]
## Description

At the moment we pull the 'preview_image' field from Contentful data, but (based on the fact that there us `TODO request proper size image` in the original code), this looks like it may not always be the ideal choice.

This might be a good moment to support `srcset`s of any particular image.

Exact spect TBD

---

#### Success Criteria
- [ ] The BE provides a variety of image sizes, so that the browser can use the most appropriate version
- [ ] FE code is updated to take advantage of this

**Comment by stevejalim** [comment]
heya @alexgibson - this feels like a good ticket to collaborate on, particularly re the image sizes we need (and what we might have available). What are your thoughts on this?

**Comment by alexgibson** [comment]
@stevejalim Can you give more detail as to which image you mean by `preview_image`?

**Comment by alexgibson** [comment]
If this relates to the [page image](https://www.mozilla.org/media/img/products/vpn/common/social-share.fd20884beaac.png), that is used in social sharing contexts, then I'm not sure we need to serve different sizes / formats to different clients. It only needs to meet a minimum size to be used in social feeds. Looking at our existing images, this seems to be `1200px / 600px`.

**Comment by maureenlholland** [comment]
this was made possible with https://github.com/mozilla/bedrock/pull/12627
we will have to follow up to make sure the api is preparing images at the right dimensions in different situations, but the ability to do so is there
