### ISSUE TITLE
Migrate /explore/pocket-hits-signup from pocket-marketing-pages

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/bedrock#10756]
Moving the [/explore/pocket-hits-signup](https://www.getpocket.com/en/explore/pocket-hits-signup) page from pocket-marketing-pages to bedrock

**Comment by stevejalim** [comment]
@nathan-barrett heya dude - what's the blocke here? Feel free to DM me if it can't be shared publicly

**Comment by nathan-barrett** [comment]
@stevejalim same as what I listed [here](https://github.com/mozilla/bedrock/issues/10761#issuecomment-1084854992)

**Comment by alexgibson** [comment]
Is this something that we're still aiming to do, or should this be a wontfix?
