### ISSUE TITLE
Migrate /pocket-hits/confirmation from pocket-marketing-pages

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/bedrock#10761]
Moving the [/pocket-hits/confirmation](https://getpocket.com/en/pocket-hits/confirmation) page from pocket-marketing-pages to bedrock

**Comment by reemhamz** [comment]
Note that this ticket includes working on the two following pages:

- Subscription confirmation: https://getpocket.com/en/pocket-hits/confirmation?success=1
- Link expired: https://getpocket.com/en/pocket-hits/confirmation?success=0

**Comment by pmac** [comment]
Nathan is right. Pocket newsletters don't go through basket. We have a separate project to come back to this with a new way pocket is doing these signups. So this is just on hold and should not affect anything with l10n.

**Comment by stevejalim** [comment]
OK, thanks @pmac @nathan-barrett - if there's nothing to localise on them for now, that's great

**Comment by alexgibson** [comment]
Is this something that we're still aiming to do, or should this be a wontfix?

**Comment by reemhamz** [comment]
@alexgibson Seems that Pocket and our team leadership have discussed how to move forward with this. Timeline to launch this is still TBD, but it's definitely on the table to launch soon if I understand correctly

**Comment by pmac** [comment]
We just had a meeting on this today actually. We'll be moving forward soon. We need to get the bedrock-hosted pocket pages live on the site first, and then we'll move toward getting this one ported. Thanks for keeping an eye on things.
