### ISSUE TITLE
[Contentful] Enable page preview directly from Compose's authoring view

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10776]
## Description

While exploring https://github.com/mozilla/bedrock/issues/10771 @pmac and I spotted that the ideal behaviour is to have a preview available from the Compose view, but when we try to use it, it says 'Please ask an admin to enable content preview' even when one is an admin for the core Contentful webapp.

#### Success Criteria
- [x] We're able to trigger a preview in bedrock directly from the Compose view

**Comment by slightlyoffbeat** [comment]
Should be fixed now. If you can confirm, feel free to close.

Trick was using `{entry.linkedBy.sys.id}`

<img width="621" alt="image" src="https://user-images.githubusercontent.com/2030656/142356683-d4544e2e-c99a-41e9-83de-ea2cbf132790.png">

**Comment by stevejalim** [comment]
Yep, works for me! Thanks @slightlyoffbeat 🥁
