### ISSUE TITLE
Contentful: rogue escaped `<u>` tags in dev content

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10774]
## Description

https://www-dev.allizom.org/en-US/products/vpn/resource-center/how-your-location-is-tracked-and-how-you-can-limit-sharing-it/ features contnet styled with an underline, which then renders as escaped `u` tags, because we're not treating them as allowable in rich text

### Steps to reproduce

Visit https://www-dev.allizom.org/en-US/products/vpn/resource-center/how-your-location-is-tracked-and-how-you-can-limit-sharing-it and scroll down to `How to disable location request prompts`

### Expected result

The browsers listed should not have `u` around them - eg `<u>Firefox</u>`

### Actual result

The browsers listed have `u` around them - eg `<u>Firefox</u>`

### Environment

Nightly, MacOS

**Comment by stevejalim** [comment]
Pinging you @slightlyoffbeat - but let me know if you don't mind me fixing this kind of content niggle myself - happy to

**Comment by slightlyoffbeat** [comment]
Should be fixed, but I can't confirm till dev updates.
