### ISSUE TITLE
[Contentful] Forward pages that now have content hosted in VPN Resource Center

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10785]
## Description

The content that is now hosted in the VPN Resource Center was previously hosted on either the blog or has an older page on mozilla.org.

The resource center should be the canonical source now and older sources of content should forward. 

---

#### Success Criteria
- [ ] Forward https://www.mozilla.org/en-US/products/vpn/more/what-is-a-vpn/
- [ ] Forward https://www.mozilla.org/en-US/products/vpn/more/what-is-an-ip-address/
- [ ] Forward https://www.mozilla.org/en-US/products/vpn/more/when-to-use-a-vpn/
- [ ] Forward https://www.mozilla.org/en-US/products/vpn/more/vpn-or-proxy/
- [ ] Forward (in WP Engine) https://blog.mozilla.org/en/internet-culture/mozilla-explains/location-history/
- [ ] Forward (in WP Engine) https://blog.mozilla.org/en/products/mozilla-vpn/do-you-need-a-vpn-at-home-here-are-5-reasons-you-might/

**Comment by slightlyoffbeat** [comment]
I'll take the blog content since that is handled in WP Engine, but someone else will need to pick up the rest of this task for the bedrock content.

**Comment by slightlyoffbeat** [comment]
VRC is soft launched for now, but will eventually need to have a spot in the VPN sub navigation.

We should also remove old links from that sub navigation, and ideally it should all happen at once. 

I can create another issue for that.

**Comment by alexgibson** [comment]
@slightlyoffbeat many of these mozorg pages are localized in dozens of languages. Are we sure we want to lose those translations, or should we only redirect `/en-US/` for the time being?

**Comment by maureenlholland** [comment]
this is still relevant, if we have translated pages for the hardcoded templates of these urls, we can forward to the VPN Contentful ones

**Comment by stevejalim** [comment]
The Contentful versions of the non-WPEngine pages are now all localised into 10 locales
