### ISSUE TITLE
[Nov 30] Enable home page fundraising banner for Giving Day

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10792]
## Description

Enable morning of Nov 30

- `SWITCH_FUNDRAISING_BANNER_EOY2021=on`
- `SWITCH_FUNDRAISING_BANNER_GIVING_TUESDAY_2021=on`

Can be turned off the following day.

---

#### Success Criteria
- [ ] Fundraising banner is live for Giving Tuesday

**Comment by slightlyoffbeat** [comment]
@alexgibson looks like you have this covered, but pinging just in case.

**Comment by alexgibson** [comment]
Looks good on stage: https://www.allizom.org/en-US/

**Comment by alexgibson** [comment]
Live on prod: https://www.mozilla.org/en-US/
