### ISSUE TITLE
Whats New Page (de)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10800]
## Description

WNP for Fx95 de is Pocket focused. Fx95 releases on Dec 7.

[Design](https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/Firefox-WNP-EU-(Copy-June-2021)?node-id=916%3A2249)

[Copy](https://docs.google.com/document/d/1Ef1UPSKEqxTropynqe_hlEgou56eX3Rd7GSLkceDFSU/edit?usp=sharing)

No split test. No languages for EU besides DE.

**Comment by alexgibson** [comment]
I'm going to pick this up and work on it as US folks are out over Thanks Giving.

**Comment by alexgibson** [comment]
Demo: https://www-demo1.allizom.org/de/firefox/95.0/whatsnew/

**Comment by alexgibson** [comment]
The UTM parameters for the Pocket CTA on this page are as follow:

- `utm_source=mozilla.org-whatsnew95`
- `utm_medium=referral`
- `utm_campaign=whatsnew95-de`
- `utm_content=signup-fxa`
