### ISSUE TITLE
Add run command for Bedrock documentation

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#10802]
## Description

[Bedrock's documentation](https://bedrock.readthedocs.io/en/latest/) is able to be edited straight from our code. Running the `make livehtml` command runs a live preview server that benefits whoever is editing it docs. We should add that command in the Bedrock documentation page for better reference for developers and contributors.

---

#### Success Criteria
- [ ] Create a new section for Bedrock documentation contribution
- [ ] Add the `make livehtml` command (local installs)
- [ ] Add the `make docs` command (Docker container)

**Comment by pmac** [comment]
You can run the docs stuff from the main Makefile; i.e. you don't have to cd to the docs directory.

- `make livedocs`: Generates the docs and starts a server with live reload
- `make docs`: Does the same as above, but runs it all in a Docker container

**Comment by reemhamz** [comment]
@pmac Ah! Perfect, thanks for the heads up.

**Comment by reemhamz** [comment]
Closing because the section [already exists](https://bedrock.readthedocs.io/en/latest/install.html?highlight=markdown#documentation) (i just couldn't find it before 😂)
