### ISSUE TITLE
Moments Page - 12/15

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10801]
## Description

Our third moments page for Q4 2020.

Two moments pages will be built:

1st:  MAC (multi account container) users
Messaging: Mozilla's VPN can help you more than you might think! (Focus on MAC integration)

2nd: Remaining Fx account holders
Messaging: Give the gift of Mozilla VPN to your loved ones

Copy: current WIP. Working doc [here](https://docs.google.com/document/d/1zrSH7DOO_fZSbopzHiaGFykWu0IxSXIjd26meeDRiJE/edit).

Design: [Figma](https://www.figma.com/file/UFZ8R9V3lVxpZFQ34g0fN9/VPN-Moments-%26-Email?node-id=50%3A490)

**Comment by craigcook** [comment]
https://www-demo4.allizom.org/firefox/welcome/12/
https://www-demo4.allizom.org/firefox/welcome/13/
