### ISSUE TITLE
Windows 11 string not displayed on the VPN Waitlist page

### ISSUE THREAD

**Issue by punster-moz** [mozilla/bedrock#10819]
## Description

Windows 11 string not displayed on the VPN Waitlist page

### Steps to reproduce

Be on https://www-dev.allizom.org/en-US/products/vpn/invite/ VPN Waitlist page (stage);

### Expected result

Windows 11 string is correctly displayed in the platforms section;

### Actual result

Windows 11 string is not displayed in the platforms section;

### Environment
Affected versions:

    All;

Affected FxA versions:

    1.220.0;

Affected Guardian versions:

    v1.20.b2;

**Comment by alexgibson** [comment]
@punster-moz thanks for the report!

**Comment by madalincm** [comment]
Verified this on Guardian v1.20.b2. "Windows 10/11" string is displayed on the VPN Waitlist Page, but only when the EN-US/EN-CA/EN-GB locales are used.
"Windows 10" string is displayed when using any other locale.

**Comment by alexgibson** [comment]
> "Windows 10" string is displayed when using any other locale.

Please give time for locales to translate the new string.
