### ISSUE TITLE
Add service=guardian-vpn parameter to VPN metrics-flow and FxA links

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10811]
## Description

In order to make querying data easier, Data Science (yeonjoo) would like to add a unique identifier `service=guardian-vpn` to all Mozilla VPN subscription / sign-in links, as well as to the metrics-flow request that happens on page load.

This will need testing on demo/FxA stage to make sure the param is kept throughout the subscription flow.

---

#### Success Criteria
- [ ] `service=guardian-vpn` param is added to all FxA requests from the VPN landing page.

**Comment by alexgibson** [comment]
I'm seeing a 400 error when including this new param in the metrics-flow API call:

https://accounts.stage.mozaws.net/metrics-flow?form_type=button&service=guardian-vpn&entrypoint=www.mozilla.org-vpn-product-page&utm_source=www.mozilla.org-vpn-product-page&utm_campaign=vpn-product-page&utm_medium=referral

`child \"service\" fails because [\"service\" with value \"guardian-vpn\" fails to match the required pattern: /^(sync|content-server|none|[0-9a-f]{16})$/]`

This is blocked until we can add support for it on the FxA side.

**Comment by alexgibson** [comment]
@vbudhram hi, can you help with the error here in comment https://github.com/mozilla/bedrock/issues/10811#issuecomment-979272243 ?

**Comment by vbudhram** [comment]
Hey @alexgibson I have landed a change on our side, https://github.com/mozilla/fxa/pull/11180, that should fix the error you are getting. We should be deploying to stage shortly and production next week.

**Comment by alexgibson** [comment]
Many thanks @vbudhram 💯

**Comment by alexgibson** [comment]
@YeonjooSmith this is not ready for testing up on staging. I set up a demo link here, can you please test?

https://www-demo1.allizom.org/en-US/products/vpn/

**Comment by YeonjooSmith** [comment]
@alexgibson  I tested four possible routes that users can take(New FxA users, 2 different ways for existing FxA users who are signed off , and existing FxA users who are signed in). I see that the service parameter is passed in url when utm parameters are included. I pasted urls in this [doc](https://docs.google.com/document/d/16bZcAQ-DiC-XsF1U1ICYfaL3BpQfKtmmAuHAkEPgXFY/edit?usp=sharing) for all four cases. Thank you so much!!

**Comment by alexgibson** [comment]
Thanks @YeonjooSmith! I'll mark this as ready for review. I'll let you know as soon as it's live.

**Comment by vbudhram** [comment]
Hey @alexgibson, I tried to verify this fix with @YeonjooSmith and it turns out that we actually need to use ` service=e6eb0d1e856335fc` (which is the vpn client id). 

Unfortuntely, FxA has some sutble differences on how it handles metrics for different clients. If you use the updated value for service, FxA will convert this to the `guardian-vpn` value before it is sent through the metrics pipeline.

**Comment by alexgibson** [comment]
@vbudhram thanks, filed a followup issue for this here: https://github.com/mozilla/bedrock/issues/11074
