### ISSUE TITLE
[subplat] Windows 11 string not displayed on the VPN homepages 

### ISSUE THREAD

**Issue by madalincm** [mozilla/bedrock#10821]
#### Affected versions:
- All;

#### Affected FxA versions:
- 1.220.0;

#### Affected Guardian versions:
- v1.20.b2;

#### Prerequisites:
- Have the browser or system language set to French;
- Be on https://www-dev.allizom.org/en-US/products/vpn/ VPN homepage;

#### Steps to reproduce:
1. Navigate to the FAQs section;
2. Click on “What device is Mozilla VPN compatible with?” option;
3. Observe the Windows versions displayed;
4. Click on “Windows” link option;
5. Observe the Windows versions displayed on the page;

#### Expected result:
- For both step 3 and 5: “Windows 10/11” string is displayed;

#### Actual result:
- For step 3: “Windows 10” string is displayed when French language is set;
- For step 5: Windows 10” string is displayed on the:
  - “Stay connected and protected with Mozilla VPN for Windows 10” title, 
  - “Your privacy is our promise” section;
  - “One subscription for all your devices” section;

#### Notes:
- Step 3 is ONLY reproducible for French;
- Step 5 is reproducible regardless of the language;
- This was found during Guardian 1.20 testing coverage;
- See the attached screenshots.
![Screenshot 2021-11-25 at 09 23 36](https://user-images.githubusercontent.com/15685441/143403200-b0d56a7d-382a-40d0-9148-9c6be5b2a2be.png)
![Screenshot 2021-11-25 at 09 22 42](https://user-images.githubusercontent.com/15685441/143403214-32fb481a-881b-495f-adef-d5ad21679c2c.png)
![Screenshot 2021-11-25 at 09 22 52](https://user-images.githubusercontent.com/15685441/143403241-6da23558-1152-426a-b5a2-1295749636e6.png)
![Screenshot 2021-11-25 at 09 23 07](https://user-images.githubusercontent.com/15685441/143403258-b0a4b050-440a-449b-b3a2-83e57fab2023.png)

**Comment by alexgibson** [comment]
Fixed https://www-dev.allizom.org/fr/products/vpn/
