### ISSUE TITLE
Improve consistency between Mozilla and Firefox themed footers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10830]
## Description

There may be some explaination for this I'm not aware of, but I find it a bit hard to figure out - so an issue might be a good place discuss things. We have two main variations of page footer on mozorg, one which is Mozilla themed and one which is Firefox themed. The content for each is identical, despite the difference in styling.

The following things are minor details, but I noticed them during code review and I'm not sure why they are this way. Maybe it's something we can improve?

- The Mozilla themed footer has underline links by default, whilst the Firefox footer theme does not.
- The Firefox footer theme has only a very slight link color change on hover / focus. It's a bit difficult to see (imho), and contrast could probably be improved.
- The social icons on the Firefox themed footer have a strange bottom border styling on hover, whilst the Mozilla theme does not.

**Mozilla theme:**

![image](https://user-images.githubusercontent.com/400117/143594705-ce328366-0542-4ee4-8cf5-c8d64af6d526.png)

**Firefox theme:**

![image](https://user-images.githubusercontent.com/400117/143594759-8fbc7fcb-45dc-47d5-92bd-9630b8c063f2.png)

![image](https://user-images.githubusercontent.com/400117/143595232-f18ab785-4774-4f88-950b-4b59d4c835b4.png)

A bigger question might be - do we really need these separate brand theme styles? I'm not clear on what value they are adding. Each seems closer to generic a light / dark theme, as opposed to something related to each brand. Maybe this is something we could repurpose them as?

Neither of the current footers seems to be what's in Protocol: https://protocol.mozilla.org/patterns/organisms/footer.html

**Comment by maureenlholland** [comment]
@craigcook do you recall why there are differences between these footers and Protocol footer?

I'd like to make it match up with Protocol footer by default and add a light theme option for bedrock use

**Comment by craigcook** [comment]
There's no specific reasoning for the differences I'm aware of, apart from the background colors. It would have just been oversight during development. 100% in favor of bringing them in line.
