### ISSUE TITLE
UI / responsive issues on /pocket/add/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10843]
## Description

The following page has several UI issues

### Steps to reproduce

1. Visit https://www-dev.allizom.org/en-US/external/pocket/add/

### Expected result

1. The hero image does not maintain it's correct aspect ratio when viewed at different page widths:

<img src="https://user-images.githubusercontent.com/400117/144035130-d038cdd5-4383-4b5f-8b87-25d49820ec82.png" alt="image" width="400">

2. The "Get Pocket for" links are missing icons:

<img src="https://user-images.githubusercontent.com/400117/144034723-58b2d175-c2d2-47fe-86e0-dd35d943c615.png" alt="image" width="200">

3. The Feedly icon is truncated:

<img src="https://user-images.githubusercontent.com/400117/144034928-c349b265-b8f9-420d-b424-d647dc835420.png" alt="image" width="200">

4. The pages doe not resize well for small viewports:

<img src="https://user-images.githubusercontent.com/400117/144035339-1ab7179b-d6a9-47ea-9b1d-b7dabd150814.png" alt="image" width="400">

### Actual result

None of the above UI issues should be present.

### Environment

Firefox Nightly
macOS

**Comment by nathan-barrett** [comment]
I think @reemhamz's PR #10858 should have solved most if not all of these issues - the only thing that I still have a question about was the icon looking like it was cut off. Solution would be to use the icons that are used on the /add page in production or we can leave as is.

**Comment by reemhamz** [comment]
@nathan-barrett the icon for Feedly is essentially just a square that has a cut-off. We _could_ replace it with its old icon, but I don't think it's a deterrent, especially considering we're revamping most of these pages come 2022.
