### ISSUE TITLE
Contentful: Backend support for translations 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10867]
## Description

We'll soon be getting translations from Contentful, so it's a good time to skech out how we'll pull in and render out the appropriate content based on locale.

### Related tasks
- https://github.com/mozilla/bedrock/issues/10892

### Related PRs:
- https://github.com/mozilla/bedrock/pull/11002

---

#### Success Criteria
- [ ] Multiple locale-specifc versions of the same overall document can be ingested from Contentful and saved in the DB

**Comment by stevejalim** [comment]
@pmac @slightlyoffbeat Skeched in a ticket - feel free to add more points

Open question: if we have 12 VRC articles, for example, but only two are localised to, say, French, do we show 2 or 12 articles on the french VRC landing page? I imagine the answer to that will also steer what we do with related articles.

**Comment by pmac** [comment]
I assume 2, as showing a mix of languages is never a good experience.

**Comment by stevejalim** [comment]
> showing a mix of languages is never a good experience

Agreed, but it does bring the downside that as soon as we start adding translations, our 'visible content' in that locale drops until our translation team have caught up and translated the lot. 

I guess that just might mean we have to plan to do a big drop of localised content (eg, all 12 French in one go) perhaps. More of a product/marketing decision than a tech one, I appreciate, but the tech side would be that we should probably have some way to enable/disable a showing a locale's translations (even if we have some imported from Contentful) until there are 'enough' and we flip the switch

**Comment by pmac** [comment]
Yes, we could only say that the main page for a locale is only activated after a certain number of articles are available in said language.
