### ISSUE TITLE
Trademark infringement reporting form is broken

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#10860]
Copied from [bug 1743922](https://bugzilla.mozilla.org/show_bug.cgi?id=1743922):

Reporting form at https://www.mozilla.org/en-US/about/legal/defend-mozilla-trademarks/ is broken. We haven't received reports since November 17 (even spam) so it appears to be broken for all users. Attempted to submit a test report and received the following error message (in both Firefox and Chrome):

Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

More information is available with DEBUG=True.

**Comment by stevejalim** [comment]
Updating ticket after exploring: CSRF is present and working locally in prod mode. Wondering if this is because the new CDN isn't forwarding the `Cookie` header, which we need to compare the submitted CSRF token with the one referenced by the session. @duallain would you have a spare moment to check/tweak this, please?

**Comment by duallain** [comment]
I've found two recommended changes that seem to have fixed it on dev, caching with x-csrfmiddlewaretoken as a header, and including the csrftoken as a cookie.  pr here - https://github.com/mozmeao/infra-services/pull/155

**Comment by pmac** [comment]
Working for me on prod! Thanks! 🍰
