### ISSUE TITLE
Tidy up home page templates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10871]
## Description

We currently have 5 different home page templates:

- mozorg
  - home
    - `home-de.html` (German home page)
    - `home-en.html` (Fallback English home page)
    - `home-fr.html` (French home page)
    - `home.html` (Rest of world home page)
  - `contentful-homepage.html` (Contentful English home page)

Some tidy up work that might make updating the home pages easier:

1. The template `contentful-homepage.html` is in a different directory to all the other templates. Moving it into `mozorg/home/` seems like a no brainer, as I nearly always make changes to `home-en.html` and then wonder why I can't see any updates.
2. The template `home-en.html` is not easy to view locally without making code changes, and copy/pasting changes in `contentful-home-page.html` over to `home-en.html` seems like a chore people are going to forget over time. I wonder if it makes sense to rename the Contentful home page to `mozorg/home/home-en.html`, and then fallback to showing `home.html` (the rest-of-world home page) should there be a problem with Contentful. This might also nudge us to make updates that also benefit the rest of world more? Essentially we'd be back down to 4 templates.

---

#### Success Criteria
- [ ] Home page templates are updated depending on consensus to the above.

**Comment by maureenlholland** [comment]
Sounds reasonable to me, particularly regarding keeping home-en updated under current structure. I think the tricky thing is when products are not available yet in certain markets, but that's more a country code conditional than a locale one.

We might want to split the task into two parts, depending on how ready home.html looks as a fallback:
1. Update home.html (?)
2. Replace home-en.html with Contentful content and update view logic/bundles/etc.

**Comment by alexgibson** [comment]
> I think the tricky thing is when products are not available yet in certain markets, but that's more a country code conditional than a locale one.

Yep, this should really be dependent on country and not page language.

**Comment by alexgibson** [comment]
I also don’t think 1. necessarily needs to be a blocker here, as Contentful errors should hopefully be few and short lived.
