### ISSUE TITLE
Update fundraising banner design for EOY 2021

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10870]
## Description

The foundation team would like to update the design of the home page fundraising banner for EOY to match the "dear internet" campaign visuals.

- Mockup images: https://drive.google.com/open?id=1WSPn5iWDK6vu3j4XkeBzqmo_1uHEINKA&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- Banner image: https://drive.google.com/open?id=1WJsmFbDW3pRP-R6pBsRr5dQCHviiZsCz&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- Figma mockup: https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?node-id=115%3A270
- Prototypes: https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=317%3A526&viewport=287%2C48%2C0.2&scaling=scale-down&starting-point-node-id=317%3A526&show-proto-sidebar=1
- Copy doc: https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing

---

#### Success Criteria
- [ ] Banner design is updated to match the above assets

**Comment by alexgibson** [comment]
@slightlyoffbeat this is up on demo for review. 

https://www-demo1.allizom.org/en-US/

Please note one issue below:

I decided to omit the background image on smaller screens (instead opting for a simpler gradient background), as the graphic was creating readability issues with copy and buttons at various breakpoints. Example:

![image](https://user-images.githubusercontent.com/400117/144858160-9dbc16c8-7499-4a66-9714-bea74a0c117a.png)

If the designer would like to provide a less noisy version of the background image for mobile, than I'd be happy to use that instead. Just let me know, thanks.

**Comment by sabrinang** [comment]
@alexgibson Thanks for your work on this and for the readability feedback.
I created the simplified mobile version here: https://drive.google.com/open?id=1WWUupwqOXDyqLIbxzwPXSCRIrFmJbP11&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
I also lowered the opacity on some background elements for the desktop banner to be less noisy instead — revised banner here: https://drive.google.com/open?id=1WYBACDqqQdjLAV8GP2SBbAWxKHH4imSe&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by alexgibson** [comment]
@sabrinang thanks, updated. I think this should be good enough to move forward with.

**Comment by sabrinang** [comment]
Update looks good to me @alexgibson, thank you!
