### ISSUE TITLE
Remove session-related code from Bedrock

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10872]
## Description

Bedrock is stateless and we no longer support any session-based behaviour in Bedrock itself. There are some bits of stale code which should be cleaned up to make it easier to understand.

---

#### Success Criteria
- [ ] Settings should no longer reference the cache backend as session storage
- [ ] Session-related settings and middleware should be removed from the codebase

**Comment by ratika-12** [comment]
@stevejalim I want to work on this. Please assign me :)

**Comment by stevejalim** [comment]
@ratika-12 Thanks for your interest. Feel free to take a look and submit a PR, sure thing. 

If it helps, I don't think there's a lot to fix up here (which is a good thing), but if you have any questions, just post them here and we'll work it out together if we need to.

**Comment by ratika-12** [comment]
Thankyou! I'm new here and was looking for good first issue and found this interesting. Can you give me a pointer where to start.

**Comment by stevejalim** [comment]
Hi @ratika-12 Sure thing - but to help me gauge how best to advise, can you let me know how experienced you are in Python and Django at the moment? Feel free to email me (stevejalim@mozilla.com) if you prefer

**Comment by stevejalim** [comment]
Hi @ratika-12 - thanks for the interest, but given things went a little quiet, I've fixed this while working on related code. Please do keep an eye open for more things marked `Good first bug` - am sure we'll find a nice one for you to pick up. If you want to email me/the team to discuss contributing, feel free to use github@stevejalim.mozmail.com
