### ISSUE TITLE
Variable not displayed: text shown instead of numerical number

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#10883]
## Description

The variable `{ $devices }`  should be shown as a numerical number, but instead, the word `devices` is shown on production.

### Steps to reproduce
1) URL: https://www-dev.allizom.org/products/vpn/desktop/mac

GitHub: https://github.com/mozilla-l10n/www-l10n/blob/a956c6641dd2002287eae80161e63176fa67e18e/en/products/vpn/platforms/mac.ftl#L36 

`Your computer, tablet and smartphone all deserve to be secure. Use { -brand-name-mozilla-vpn } to protect up to { $devices } { -brand-name-mac-short } and { -brand-name-ios } devices (in addition to { -brand-name-windows }, { -brand-name-linux } and { -brand-name-android }).`

`{ $devices }` in this case should be a number, but on the production site, it's shown as `devices`

2). URL:  https://www-dev.allizom.org/en-US/products/vpn/desktop/linux/

GitHub: https://github.com/mozilla-l10n/www-l10n/blob/b190c77f1d8cc6adcca3d5c823dfb0a318947d6d/en/products/vpn/platforms/linux.ftl#L40

`With one subscription, you can get { -brand-name-mozilla-vpn } on up to { $devices } different devices across operating systems, including { -brand-name-linux }, { -brand-name-windows }, { -brand-name-android }, { -brand-name-mac-short }, and { -brand-name-ios } for { -brand-name-iphone } and { -brand-name-ipad }.`

### Expected result

`{ $devices }` should be displayed on production as a number (of devices), not the code

### Actual result

currently it is shown as `devices`

### Environment

Production and staging sites.

**Comment by peiying2** [comment]
<img width="533" alt="Screen Shot 2021-12-07 at 10 03 42 AM" src="https://user-images.githubusercontent.com/6090393/145087437-9ee88eab-300f-46de-91dd-c590b4c972ef.png">

**Comment by craigcook** [comment]
The template is missing the variable assignment here: https://github.com/mozilla/bedrock/blob/master/bedrock/products/templates/products/vpn/platforms/mac.html#L114

**Comment by peiying2** [comment]
<img width="531" alt="Screen Shot 2021-12-08 at 11 34 34 AM" src="https://user-images.githubusercontent.com/6090393/145272650-4446ca7f-df74-436a-867b-52240b49a273.png">

@craigcook Another one is reported - on Linux page
