### ISSUE TITLE
[l10n][es-AR]: outdated content/template needs to be removed

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#10894]
## Description

An extra text only appears (at least reported) for es-AR. The string can't be found in Pontoon or the new mozilla.org repo. The information is outdated, especially the mention of IRC.

https://github.com/mozilla/bedrock/blob/a8ed6ae9c48c93474fbefa8b91d3dd2887b13c3c/bedrock/firefox/templates/firefox/nightly/firstrun.es-AR.html

`<p>Mozilla es una organización sin fines de lucro conformada por una comunidad en la que cualquiera puede ser parte. Sólo tenés que traer tus ganas de participar y aprender. Desde la página de colabora podés acercar tus ganas de participar. También podés visitar <a href="http://www.mozilla-hispano.org/">la página de Mozilla Hispano</a> para enterarte de las últimas novedades sobre Mozilla.</p>`
`<p>Y si querés juntarte con vecinos en Argentina, podés suscribirte a la <a href="https://listas.usla.org.ar/cgi-bin/mailman/listinfo/mozilla-general">lista de correo</a>, o pasearte por la sala de IRC de Mozilla Hispano.</p>`
`<p>¡Gracias por usar Firefox Nightly!</p>` 

### Steps to reproduce

The outdated string/paragraph appears on the lower half of the page, only available in es-AR: https://www.mozilla.org/es-AR/firefox/nightly/firstrun/)](https://www.mozilla.org/es-AR/firefox/nightly/firstrun/

### Expected result

Remove the template containing outdated and misleading information.

**Comment by craigcook** [comment]
Is the request to remove the entire block of text? 

There's very similar content in es-ES with the same outdated link to mozilla-hispano.org. Should we remove that one as well?

**Comment by gaby2300** [comment]
In es-AR " o pasearte por la sala de IRC de Mozilla Hispano" should be changed to " o conectarte a la sala de Element de Mozilla Hispano."

As it would be the same for es-ES, I suppose it could be changed the same way.

**Comment by craigcook** [comment]
The changes are staged temporarily at https://www-demo-pr-11037.herokuapp.com/es-AR/firefox/nightly/firstrun/

@gaby2300 can you review and let us know if it's correct or needs any other changes?

https://www-demo-pr-11037.herokuapp.com/es-ES/firefox/nightly/firstrun/ didn't mention IRC so I only updated the link to mozilla-hispano.org there.

**Comment by gaby2300** [comment]
Hi Craig, thank you so much for fixing this so quickly!

I reviewed it and it's correct now.

Many thanks  again!
Best regards,
Gabriela

http://www.mozilla-hispano.org







<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
