### ISSUE TITLE
Allow adding/editing of redirects

### ISSUE THREAD

**Issue by jlongster** [mozilla/bedrock#11]
A very common use case of mozilla.org is to have top-level redirects like mozilla.org/b2g which would redirect to a b2g wiki page.

It would alleviate workload and help engagement if we could allow them to manage these redirects themselves. No idea how this should work, as speed is an issue. I doubt we want to load up all of django just to do a redirect, or do we? Zeus caches them anyway.

**Comment by pmclanahan** [comment]
We will finally be doing this soon. Will file new issues/bugs though. Thanks :)
