### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by icaaq** [mozilla/bedrock#110]
A more general question, why do Mozilla implement input fields on their websites without associating a descriptive label?

On http://www.mozilla.org/en-US/ there are 4 input fields (including the one in tabzilla) 3 of them does not have a associated label!

It's a level A guideline of the WCAG 2.0 http://www.w3.org/TR/2008/REC-WCAG20-20081211/#minimize-error-cues and I cant see why it isn't followed

**Comment by alexgibson** [comment]
I believe we can close this - all form inputs on the home page (including Tabzilla search) have associated labels. They remain visually hidden, but screen readers should be able to access them. We try and do this across the site everywhere if a visible label is not used in a design (if we do spot any missing, let's file specific bugs).

In the future we should try and explain to our creative team that placeholder attributes and labels should not serve the same common purpose. But at least for now, we *should* be using labels everywhere needed.
