### ISSUE TITLE
A special whatsnew page for Firefox 100

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#11036]
## Description

I am not sure if marketing has any plans for Firefox 100, but I think that a special whatsnew page for users upgrading would be a fun way to acknowledge this amazing milestone. Perhaps something like adding a CSS animation of confetti that falls on page load. Thoughts? 🥳

**Comment by alexgibson** [comment]
I'm sure that marketing will want to do something specific for when FF v100 hits general release, but perhaps we might have a little more freedom to do something fun when Nightly hits v100 on March 8?

https://www.mozilla.org/en-US/firefox/100.0a1/whatsnew/

**Comment by alexgibson** [comment]
Something is happening in-product for this so there won't be a WNP for 100, closing.
