### ISSUE TITLE
Specify sameSite property on cookies set by JS

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11058]
## Description

In https://github.com/mozilla/bedrock/issues/8670 we updated bedrock's cookie JS helper to support the `sameSite` attribute, however our code doesn't actually use this to explicitly define the property yet in places where we set cookies. This results in `sameSite=Lax` being assumed by browsers, which is fine.  Here's an example of a warning given in the console by Firefox:

```
Cookie “vpn-promo-banner” has “SameSite” policy set to “Lax” because it is missing a “SameSite” attribute, and “SameSite=Lax” is the default value for this attribute.
```

We should really start to explicitly set this value in our code (if only to silence all the messages in the web console right now). There is a useful primer here on the `sameSite` property: https://web.dev/samesite-cookies-explained/

---

#### Success Criteria
- [ ] Cookies set by 1st party JS all specify the `sameSite=Lax` property.

**Comment by eemeli** [comment]
This is a blocker for [bug 1501881](https://bugzilla.mozilla.org/show_bug.cgi?id=1501881), as a page from mozilla.org is rendered during first startup and the warning string source is currently in a .properties file.

**Comment by alexgibson** [comment]
@eemeli can you help us understand how this issue (as well as https://github.com/mozilla/bedrock/issues/11326) is blocking progress of [bug 1501881](https://bugzilla.mozilla.org/show_bug.cgi?id=1501881)? From a website perspective, both of these issues are pretty harmless and are currently low priority. We can change that, if it's helpful in some way. Or are inclusion of these issues in bug 1501881 simply highlighting some strings you have yet to migrate?

**Comment by eemeli** [comment]
It's probably fine to keep these as low-priority for now.

The blocked bug tracks a collection of strings from .properties files that end up being formatted during the first startup of Firefox without any profile, which includes opening a tab that shows the Firefox Privacy Notice from mozilla.org. This has a side effect of including the loading and formatting of any warning messages encountered during its rendering into the nominal startup path of Firefox.

The specific warnings shown for mozilla.org are currently coming from `necko.properties` and `layout_errors.properties`, which are a little tricky to migrate to Fluent, so it might take a while before that happens.

But as I mention above, this should be fine, as this isn't really blocking new feature development and should have at most a nominal effect on perf. I just figured it'd be good to flag the cross-dependency.

**Comment by alexgibson** [comment]
Thanks for following up! We may get to fix both of these before too long, but it's good to know this isn't blocking you for now.
