### ISSUE TITLE
Update service param value for VPN referrals.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11074]
## Description

The `service=guardian-vpn` param added in https://github.com/mozilla/bedrock/issues/10811 should in fact use the client ID for guardian directly: `service=e6eb0d1e856335fc`

See: https://github.com/mozilla/bedrock/issues/10811#issuecomment-999696157

**Comment by YeonjooSmith** [comment]
@alexgibson  I checked the url after clicking the CTA from the vpn product site(https://www.mozilla.org/en-US/products/vpn/) and the service parameter did not change and it is still `guardian-vpn` and it is still not emitted to the data.

**Comment by alexgibson** [comment]
@YeonjooSmith this change has not yet been deployed to production. I'll try and make that happen a little later today. I'll let you know as soon as it's live. Thanks again!

**Comment by alexgibson** [comment]
@YeonjooSmith this is now in production, thank for your patience!

**Comment by YeonjooSmith** [comment]
@alexgibson   I just checked the url and I see service parameter (`service=e6eb0d1e856335fc`)! I will check if the service parameter shows up correctly in the data and let you know. I really appreciate your help and Happy New Year!
