### ISSUE TITLE
Start new-spec discussions for Careers-page filtering logic

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11081]
While fixing a bug on the [careers listing page](https://www.mozilla.org/en-US/careers/listings/) to do with filters, I noticed that the filtering is based upon a single location related to a Position, but the Position itself has a _separate_ field for displaying a fuller/verbose list of location options which aren't used for filtering. 

This might cause end users confusion, in terms of seeing/not seeing things they are expecting to see after filtering, and may also mean that some potential candidates pick a particular filter and miss out on roles they might have otherwise considered. 

Also, this overall setup means there there can be significant mismatches between the value used for filtering and the displayed locations. For example, we have `Berlin Office` in a filter option and one particular role has `Berlin, Germany` named as one of its displayed location options. However, filtering by Berlin Office doesn't show up the Position mentioning `Berlin, Germany` because the role's location is actually specced as `Remote France` - which doesn't feature at all in the verbose location description.

It feels like we might need to revisit the filtering in general, and it'd be a good opportunity to chat with the People Team to find out what behaviour they ideally want, and see how we can deliver that. 

#### Success criteria
- [ ] Stakeholders have been consulted about ideal/better filtering
- [ ] We have a spec for how careers filtering should behave

**Comment by stevejalim** [comment]
> The problem we noticed seems to be that not all jobs are set up this way, which leads me to suspect this is a data entry issue, rather than a process change.

This is good news, thanks!

**Comment by alexgibson** [comment]
See also https://github.com/mozilla/bedrock/issues/11112
