### ISSUE TITLE
Improve "Remote" job filtering?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11112]
## Description

Selecting different "Remote" job location options in the listings page produces inconsistent results.

### Steps to reproduce

1. Open https://www.mozilla.org/en-US/careers/listings/
2. From the locations drop down, select `Remote`.
3. Look at the results.
4. From the locations drop down, select `Remote US`.
5. Look at the results again.

### Expected result

When selecting `Remote US`, the results for `Remote` should also be included (since those jobs are also open to remote candidates in the US?)

### Actual result

The page excludes jobs explicitly labelled as `Remote` when selecting any other kind of remote location (e.g. `Remote US`, `Remote UK`).

### Environment

N/A

**Comment by robhudson** [comment]
It seems like more of an exact match type of filter. Notice that the greenhouse filter also has this problem: https://boards.greenhouse.io/mozilla

**Comment by alexgibson** [comment]
Yeah, I can see it was set up this way. Just seems like people might be missing out on possible remote roles, unless they realise there's more than one category to check 🤷‍♂️

**Comment by Ayushsunny** [comment]
> It seems like more of an exact match type of filter. Notice that the greenhouse filter also has this problem: https://boards.greenhouse.io/mozilla

Hey, @robhudson shall we fix this too?
