### ISSUE TITLE
Pocket pages throw a 404 trying to load js/base/mozilla-cookie-helper.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11123]
## Description

Not sure where this is used, but the pocket pages seem to throw a 404 looking for: https://www-dev.allizom.org/en-US/external/pocket/about/js/base/mozilla-cookie-helper.js

https://www-dev.allizom.org/en-US/external/pocket/about/

**Comment by maureenlholland** [comment]
This is used in the snowplow analytics script, for `Mozilla.Cookies.getItem` functionality: https://github.com/mozmeao/pocket-marketing-pages/blob/master/content/marketing-assets/js/snowplow.js#L10

Might need to check in with Dan or pmac for details when they are back. I think we want to keep snowplow but we don't necessarily need to use this helper.

**Comment by alexgibson** [comment]
Snowplough isn’t yet used in the bedrock repo though, I think?

If so, we can solve this when that does migrate over?

**Comment by maureenlholland** [comment]
Hmm, interesting, I'll ping the migration issue to check on this. Yeah, if there's no snowplow then there's no need for the cookie helper as far as I know.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/11124
