### ISSUE TITLE
Remove calendar data that existed from Thunderbird

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#11126]
## Description

Hosting of Thunderbird content was removed and redirected in 6858eb80 ([bug 1388914](https://bugzilla.mozilla.org/show_bug.cgi?id=1388914)) but the calendar data remains in [`/media/caldata`](https://github.com/mozilla/bedrock/tree/master/media/caldata). It looks like the Thunderbird website has their own copy of the caldata files here: https://github.com/thundernest/thunderbird-website/tree/master/media/caldata

This issue is to make sure these are no longer required in bedrock, and if so, remove them and associated code that verifies them.

**Comment by robhudson** [comment]
@Sancus Could I get your thoughts here, please?

**Comment by Sancus** [comment]
I haven't used the bedrock calendar files since we copied 'em. People have been updating them in our repository. That data is definitely no longer necessary nor used. I am kind of surprised they weren't removed before!

**Comment by robhudson** [comment]
Great, thank you! I just wanted to make sure.
