### ISSUE TITLE
[Epic] Redesign & Rebuild careers site

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11143]
This is a placeholder for the epic: Redesigning and rebuilding the Mozilla Careers section of mozilla.org

**Comment by slightlyoffbeat** [comment]
For illustrations:

[Trello Card](https://trello.com/c/LWLbLHu5).

[Figma File](https://www.figma.com/file/TGvwHTS9vuD3V3UxQtKPWo/Mozilla-Careers-Illustrations?node-id=2234%3A40182)

[Google Drive](https://drive.google.com/drive/folders/1_AJsifaTP9HETWcM7PwiF687J-KGOSOH?usp=sharing)

**Comment by reemhamz** [comment]
I thought the deadline for this was for November 17th?
