### ISSUE TITLE
Error messages on the "Join the waitlist page" are not stuck to the corresponding fields

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#11182]
## Description

When triggering error messages on the Join the waitlist page and scrolling on the page, the error message are not stuck to the fields

### Steps to reproduce

Open VPN page, on Firefox, while you are not in a VPN supported country: https://www-dev.allizom.org/en-US/products/vpn/
Click on the “Join the Waitlist” button.
Do not fill in any information and click the “Join the Waitlist” button.
Scroll up/down the page and observe the “Please fill out this field” tooltip.

### Expected result

The error message goes along with the corresponding field, while scrolling

### Actual result

The error message is stuck on the page while scrolling. Clicking the “Join the Waitlist” button makes the error disappear for good.

### Environment
Firefox on Windows 10

https://user-images.githubusercontent.com/52028275/151979319-85c3b6e0-ced5-4854-a59c-56125bbffa42.mp4

**Comment by alexgibson** [comment]
I believe this is a native form field error message, and not part of the website / web page. See https://bugzilla.mozilla.org/show_bug.cgi?id=1504161 for a possible similar Firefox bug

**Comment by alexgibson** [comment]
Closing as this is not a website issue.
