### ISSUE TITLE
[March 23] Create privacy notice / legal terms pages for MDN Plus

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11184]
## Description

Requested URLs:

- https://www.mozilla.org/privacy/mdn-plus/
- https://www.mozilla.org/about/legal/terms/mdn-plus/

Associated markdown files:

- https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_privacy.md
- https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_terms.md

Privacy pages need to be live on March 23 (one day before the MDN Plus launch)

**Comment by alexgibson** [comment]
Updated to March 24

**Comment by alexgibson** [comment]
Talked to the stakeholders and they agree we can push this live 1 day before (23rd) to make launch scheduling easier.

**Comment by gianlucadecola** [comment]
Hi, first time here, can I work on this?
