### ISSUE TITLE
Menu items on Join the waitlist page are not correctly displayed in French language 

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#11183]
## Description

The menu items on the Join the waitlist page are not displayed with capital letters, as they are in English.
### Steps to reproduce

1. Access https://www-dev.allizom.org/fr/products/vpn/invite/ ;
2. Take a look at the menu items on the page.

### Expected result

All the menu items are displayed using capital letter, even the ones with multiple words , as for the English language.

### Actual result

Some of the items are not displayed using capital letters: "**n**avigateurs Firefox", "Qui **n**ous **s**ommes" .

### Environment

Firefox and Chrome on Windows 10
![EN](https://user-images.githubusercontent.com/52028275/152160216-8e192e9e-8265-4d38-8277-1fba539364ec.PNG)
![FR](https://user-images.githubusercontent.com/52028275/152160220-2496a010-1569-49f5-82d4-b97e91fea757.PNG)

**Comment by alexgibson** [comment]
@peiying2 is this something that can be fixed in Smartling?

**Comment by Ayushsunny** [comment]
Hey, @alexgibson any update on this issue? 
I thought to pick this up

**Comment by peiying2** [comment]
Sorry to have missed this ping. I have updated Firefox Browsers in Smartling.  The platform can't  handle upper and lower case differences so one version is applied across the board. I have to spell out the translation by removing the variable, which is not advised to do in normal circumstance.

As for the other lower case Nav bar term, it's normal to have it in lower case the rest of the term, unlike English. I will leave that unchanged.

**Comment by peiying2** [comment]
It appears that the fix didn't  come through. Working with the vendor on the route cause of this.

**Comment by peiying2** [comment]
This is fixed: https://www.mozilla.org/fr/.

There were some glitches with sync and we had to involve someone technical to look into it.

**Comment by alexgibson** [comment]
Thanks @peiying2 💯
