### ISSUE TITLE
Remove broken MDN link from XUL page 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11196]
## Description

https://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul is an XML namespace and the page features a link to an explanation on MDN.

However, that explanation has been retired, so the link 404s.

We should avoid sending people to that page.

Resolves https://github.com/mdn/content/issues/12890

---

#### Success Criteria
- [x] Link to MDN is removed 
- [x] Alternative link that gives some context about what XUL is (eg a link to https://en.wikipedia.org/wiki/XUL) is used instead

**Comment by k4awon** [comment]
I can take a try here

**Comment by stevejalim** [comment]
@k4awon Thanks! Let me know if you have any questions
