### ISSUE TITLE
Remove non-functional stylesheet URL from credits page

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11197]
## Description
If you view source on https://www.mozilla.org/credits/ you will see there are two stylesheets referenced in the `<head>`, the second of which is 

```
<link rel="stylesheet" href="chrome://global/skin/about.css" type="text/css">

```
This a) doesn't work and b) doesn't look like it's an appropriate way to load styles anyway. 

Digging into it, colleagues on FF confirmed that the file was removed relatively recently from inside FF. As there no longer is an in-tree consumer of those styles, it makes sense to pull these styles into a file which is served by the website codebase, not assumes FF

The last state of that about.css file is [here](https://hg.mozilla.org/releases/mozilla-esr91/raw-file/tip/toolkit/themes/shared/about.css)
---

#### Success Criteria
- [X] Confirmed that this won't break some behaviour in FF
- [x] Link to `about:` removed from `bedrock/mozorg/templates/mozorg/credits.html`
- [x] The CSS from the last version of the Firefox-hosted `about.css` is used in the `credits` CSS bundle in bedrock

**Comment by Ayushsunny** [comment]
Hey @stevejalim, So first we'll remove this stylesheet `<link rel="stylesheet" href="chrome://global/skin/about.css" type="text/css">`
then we'll add that file to bedrock doc?
Actually, I'm a little confused about this  
- [ ] CSS added to bedrock instead

**Comment by stevejalim** [comment]
Heya @Ayushsunny - thanks for looking at this. I've rephrased the final step to make it a bit clearer, and the detail of how I'd approach it is this:

* Look at [the original about.css from Firefox](https://hg.mozilla.org/releases/mozilla-esr91/raw-file/tip/toolkit/themes/shared/about.css)
* Take those rules and add them to `credits` bundle in `bedrock` instead. This looks like it's just a straightforward combination of those CSS rules from `about.css` to `media/css/mozorg/credits.scss`, possibly dropping some unnecessary rules.
* Ensure those CSS rules being used in the /credits/ page locally. (If the effect of the rule change isn't clear, check that webpack is running and rebuilding the credits bundle - https://bedrock.readthedocs.io/en/latest/coding.html?highlight=bundles#asset-bundling says webpack should automatically update bundles when the source files change)

Hope that helps! Thanks for the assistance!

**Comment by stevejalim** [comment]
@Ayushsunny Are you still interested in doing this? If not, am happy to pick it up, but don't want to duplicate effort

**Comment by Ayushsunny** [comment]
> @Ayushsunny Are you still interested in doing this? If not, am happy to pick it up, but don't want to duplicate effort

Sorry for the delay,
Actually, i was busy with my upcoming Uni test.

**Comment by Ayushsunny** [comment]
> No worries at all - hope the test goes well!

All the tests have passed.
I've already mentioned you there for a review.

**Comment by stevejalim** [comment]
> All the tests have passed.

Yeah I saw - i meant good luck for the uni tests!

**Comment by Ayushsunny** [comment]
> > All the tests have passed.
> 
> Yeah I saw - i meant good luck for the uni tests!

I didn't understand what test you were talking about, lol.
Thank you, Steve Sir.
