### ISSUE TITLE
Create dedicated page for "Knowledge is Power" newsletter

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11207]
## Description

1st: lets confirm there isn't a dedicated page for this newsletter already :)

This will be updated when more info becomes available.

- Duplicate /newsletter
- swap copy for copy that is specific for 'Knowledge is Power' newsletter
- (TBD) update design to be appropriate for 'Knowledge is Power' newsletter
- URL `/newsletter/knowledge-is-power`
---

**Comment by slightlyoffbeat** [comment]
I received additional information that should be enough to scope:

- Design: (see attached). 
- URL: `/newsletter/knowledge-is-power`
- Newsletter: uncertain of ID, but it is the 'Knowledge is Power' newsletter
- Languages: ideally Chinese - China, Chinese - Taiwan, Portuguese - Brazil, Portuguese - Portugal, Italy, French - Canada, Korean, Japanese, Polish, Dutch, Spanish-Spain, Spanish-LATAM, Swedish, Finish
- Copy: [Copy for En, Fr, De](https://docs.google.com/document/d/13ibOXaHzuALIl8vojPpD8uwjBvFGSn8I2AL8poS4s3s/edit?usp=sharing)

Requested timeline is live by June 29.
![KIP Landing Page Mockup 6](https://user-images.githubusercontent.com/2030656/172688388-0db447d6-fb51-4b61-ad2a-3214277b4c55.png)

**Comment by reemhamz** [comment]
> Languages: ideally Chinese - China, Chinese - Taiwan, Portuguese - Brazil, Portuguese - Portugal, Italy, French - Canada, Korean, Japanese, Polish, Dutch, Spanish-Spain, Spanish-LATAM, Swedish, Finish

^ @slightlyoffbeat  Do you mean we should include these languages for the user to select from on which language to receive the newsletter? If so, based on the [Basket JSON data](https://basket.mozilla.org/news/newsletters/), the `Knowledge is Power` newsletter only comes in 3 languages: EN, DE, and FR
