### ISSUE TITLE
Create variation of /firefox/mobile/get-app/ for product test

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11206]
## Description

Product team has requested a variation of a page be built for:

`/firefox/mobile/get-app/`

It can live at: `/firefox/mobile/get-app/?v=mfm`

This variation would be 100% the same, except that it will send users to a different email list that will allow the product team to perform a test with more accurate attribution.

The updated email list is created, but I do not have the ID at the time of writing this issue. I will update this issue when I have it.

Venetia is the primary stakeholder for this request

---

#### Success Criteria
- [ ] a user can visit the variation URL, enter their email, and be signed up to a list that is different/unique from the the list that they would be signed up to on the non-variation URL

**Comment by slightlyoffbeat** [comment]
Basket/Newsletter ID: 2560328

**Comment by pmac** [comment]
> Basket/Newsletter ID: 2560328

This is not a basket ID. This ID needs to be entered into basket so that it can be used when communicating with Acoustic.

**Comment by pmac** [comment]
Basket ID: `download-firefox-mobile-reco-exp`
