### ISSUE TITLE
WNP 98 - EU

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11211]
## Description

Design: https://www.mozilla.org/en-US/firefox/96.0/whatsnew/

Locales:  DE & FR 

Copy: https://docs.google.com/document/d/13b-AqtjiD-JrtpNrO4ZuINNr935SUaieAtxD8McPER8/edit#heading=h.9ejy2rvy4tnp

Lets use the QR code variation (that was the winner in the last WNP).

**Comment by slightlyoffbeat** [comment]
For German:

https://app.adjust.com/b2arekk
![QRCode-1](https://user-images.githubusercontent.com/2030656/155249362-a7b468ce-6a54-454b-b76f-a6dade183804.svg)

**Comment by slightlyoffbeat** [comment]
For French:
![QRCode-2](https://user-images.githubusercontent.com/2030656/155249440-e794e832-47f9-45ed-a82a-b755044cccb8.svg)

https://app.adjust.com/caisb08

**Comment by alexgibson** [comment]
There seems to be some misalignment between what's suggested here and the string we have in the copy doc. Going to ask Jennifer Balaco to clarify which variation the EU team want to use.

**Comment by alexgibson** [comment]
Missing string for German `Scanne den QR-Code und los geht's`

French is incoming.

**Comment by alexgibson** [comment]
@slightlyoffbeat when testing the adjust links on demo the EU team observed that all the URLs are blocked by uBlock Origin.

I don't think this is necessarily new or a suprise, but it's worth calling out. I guess it depends just how important attribution is here, and how many downloads we might lose out on?

![image](https://user-images.githubusercontent.com/400117/155502563-4e08ec32-1f73-4667-9063-1f3f68f425a6.png)

**Comment by alexgibson** [comment]
Going to ask Jeniffer Balaco for input here also seeing as this is for a French / German audience.

**Comment by slightlyoffbeat** [comment]
@alexgibson Thanks for flagging. We generally need attribution data so I'd like to keep the adjust links. Ublock users are used to this behavior and can make a decision when they see this screen.

My guidance is to keep for QR code no matter what. With that said:
- I will likely not be looking at this data since this is for the EU team. If they do not need this data and would prefer to just use regular links, then I'm fine removing
- Since WNP is 100% desktop users, adjust links for the play store and ios store buttons are not needed. Adjust provides click data but not attribution data for Android users who install apps via desktop. iOS users cannot install from desktop. I'm fine removing. If we do this, we should attach UTM parameters to the google play store link:
- We should make sure we have click events in place for the buttons. I believe we do, but just calling out.

`https://play.google.com/store/apps/details?id=org.mozilla.firefox&referrer=utm_source%3DWNP%26utm_campaign%3DWNP98FR`

`https://play.google.com/store/apps/details?id=org.mozilla.firefox&referrer=utm_source%3DWNP%26utm_campaign%3DWNP98DE`

**Comment by alexgibson** [comment]
I’ll open a follow up PR to remove the adjust links for the badges, seeing as they serve little purpose for desktop visitors. Thanks!
