### ISSUE TITLE
Fluent templates for a non-Contentful VPN page are missing a `url` param

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11219]
Testing out the new linkchecker, we got back this report

```
Unexpected href value: "url"
Found in:
	https://www.mozilla.org/ar/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/es-AR/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/es-CL/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/hi-IN/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/es-MX/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/hu/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/fy-NL/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/ia/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/ka/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/it/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/ja/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/es-ES/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/fr/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/id/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/de/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/en-CA/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/en-GB/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/cs/products/vpn/more/what-is-an-ip-address/
	https://www.mozilla.org/cy/products/vpn/more/what-is-an-ip-address/
```

Looking into it it appears that there are fluent strings marked up to expect a `url` variable - eg 
* https://github.com/mozilla/bedrock/blob/master/l10n/en/products/vpn/more/ip-address.ftl#L23
* https://github.com/mozilla-l10n/www-l10n/blob/master/en-GB/products/vpn/more/ip-address.ftl#L20

However, that variable doesn't appear to be provided in the HTML template (as far as I can see): 
https://github.com/mozilla/bedrock/blob/master/bedrock/products/templates/products/vpn/more/ip-address.html#L24

Success criteria
* Following the hyperlink in the equivalent of the `Does it travel with you?` section on each of the pages above takes the user to the intended/appropriate destination, rather than 404ing

**Comment by k4awon** [comment]
If it is okay I can take a look here?

**Comment by stevejalim** [comment]
This should be automatically taken care of when l10n changes are made as a result of https://github.com/mozilla/bedrock/pull/11225/

Closing, but thanks for the offer of help @k4awon !
