### ISSUE TITLE
Create a banner on /contribute page

### ISSUE THREAD

**Issue by couci** [mozilla/bedrock#11233]
## Description

In preparation for the promotional work on Firefox ideas , we want to create a banner on the https://www.mozilla.org/contribute to prompt people to join the new platform and submit their ideas around new products.

The copy should be: "[platform name] is here[link]. Submit your ideas for Firefox and other Mozilla products and participate to conversations with Mozilla's product managers."

This should go up on March 24th.
---

#### Success Criteria
- [x] Copy for banner is approved
- [x] Banner is ready on staging website
- [x] Banner is published

**Comment by craigcook** [comment]
A few questions:

1. The copy above has placeholders... what is the platform name and what the URL will be? 
2. Do you have analytics on the site and if so, are there any related parameters you want included in the link to count incoming traffic?
3. Do you have any suggestions on the design? It'll be a simple banner, so maybe just a background color?

**Comment by couci** [comment]
1. New platform's name is Mozilla Connect. URL is not yet public since they are launching on the 28th.
2. I will ask for analytics on the site, thanks for bringing this up.
3. Nothing fancy for the design really, I would go with light blue as the background colour or light green.

**Comment by couci** [comment]
Platform just launched: https://connect.mozilla.org/

Waiting for an answer on the analytics

**Comment by maureenlholland** [comment]
Thanks @couci !

You can see a demo of the banner here: https://www-demo5.allizom.org/en-US/contribute/
This is using our default banner styles + accent background color picked from the page. We have an option available to place the banner above or below the navigation bar. It is above the nav for now, but easily changed. Let me know if you have any design requests.

I also have a question regarding translated content.
Do you want this to show regardless of whether the content has been translated? (current behaviour: https://www-demo5.allizom.org/de/contribute/). We could also restrict it to only show when translations are available.

**Comment by couci** [comment]
This looks pretty cool, thanks for that! Could you send also an example of how it would look under the navigation bar?
It's ok if it's not translated, the platform isn't translated anyways so that's alright

**Comment by maureenlholland** [comment]
> Could you send also an example of how it would look under the navigation bar? 
<img width="1421" alt="Screen Shot 2022-03-04 at 2 34 04 PM" src="https://user-images.githubusercontent.com/19650432/156782338-aed9df5d-280d-4688-8829-fca45aa1a69a.png">

**Comment by couci** [comment]
I think this looks better :) We are still missing the trackable link to give to you. Let's also change the date for putting this up on March 14th.
I will be off next week but my colleague @Francescaminelli will be covering for me in case there are questions

**Comment by maureenlholland** [comment]
Sounds good! Will update the position and standby for the trackable link.

**Comment by maureenlholland** [comment]
Hi @Francescaminelli, I'm following up on the trackable link params. Any news?

If it helps, bedrock UTM params on the contribute page are usually: `?utm_source=mozilla.org-contribute&utm_medium=referral&utm_campaign=contribute-page`

In this case, I would update to `utm-campaign=mozilla-connect-banner` and add any other params you need.

**Comment by Francescaminelli** [comment]
Hi, thank you for that.  I am following this up. If I do not have a link by tomorrow, I'll produce one. Would that work?

**Comment by maureenlholland** [comment]
Sounds great, thanks!

**Comment by maureenlholland** [comment]
Hi @Francescaminelli, do you have a trackable link for the banner? If we still want to release Monday (March 14), I'll need to put the PR into review today. We could also do a fast follow to update the link later.

**Comment by Francescaminelli** [comment]
Hi Apologies for this. I generated this link (I hope it works). We are pushing the campaign to Tuesday (15), would that work? https://connect.mozilla.org?utm_source=contribute+website&utm_medium=banner&utm_campaign=Connect+Campaign&utm_content=15032022

**Comment by maureenlholland** [comment]
Thanks @Francescaminelli ! I made some minor adjustments to keep everything lowercase and separated with hyphens instead of plus signs because those are fairly well established conventions within Mozilla from what I've seen. 

This makes the url: https://connect.mozilla.org?utm_source=contribute-website&utm_medium=banner&utm_campaign=connect-campaign&utm_content=15032022

The PR is now in review.

**Comment by Francescaminelli** [comment]
Thank you very much!

**Comment by couci** [comment]
@maureenlholland @craigcook we need to delay the banner for a week. So new date should be March 22nd.

**Comment by maureenlholland** [comment]
@couci no problem, thanks for letting us know!

**Comment by maureenlholland** [comment]
@couci sorry for the extra ping but translation review brought up the question of whether we should translate the banner content at all since there's not much content to translate and the site itself is not localized.

Would you like to go ahead with translations on the banner content or stick with English content only for now?

**Comment by couci** [comment]
@maureenlholland we are still experiencing high spamming activity on the connect page so we don't want to send extra traffic there. Thus, we are moving the new date for this for the 24th.

**Comment by maureenlholland** [comment]
@couci Understood. Will hold until 24th. Thanks for the update 👍

**Comment by maureenlholland** [comment]
Hi @couci, is there a specific time today to push the banner live? We are ready to flip the switch once you give us the go-ahead. Thanks

**Comment by maureenlholland** [comment]
Banner live: https://www.mozilla.org/en-US/contribute/
