### ISSUE TITLE
Broken link on H2 2021 Transparency Report

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11256]
## Description

On https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2021/ the hyperlink in the phrase 
> a [webinar](https://event.webinarjam.com/register/135/2zmv8i8z) on Lean Data Practice

is 404ing. Maybe it's expired/been archived now the event has passed.

We may need to either remove it, or link to different page.

Source: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2021.html#L243

**Comment by danielnazer** [comment]
Fine to just remove the link, thanks

**Comment by stevejalim** [comment]
@danielnazer A colleague found this video - https://www.youtube.com/watch?v=GH2sjPmlxnM via an Afrilabs tweet - we could link to that recording instead, if you prefer

**Comment by danielnazer** [comment]
Even better! Thanks
