### ISSUE TITLE
Add ADR for the move to pip-compile-multi

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#11252]
We should get back into the habit of writing [ADRs](https://bedrock.readthedocs.io/en/latest/architectural-decisions.html) for major decisions in bedrock. It would be nice to go back and document our reasoning for moving to pip-compile-multi in this way. 

@stevejalim would you mind writing one of these? The tool we've used in the past to start these is documented in the [first ADR for the site](https://bedrock.readthedocs.io/en/latest/architecture/decisions/0001-record-architecture-decisions.html).

**Comment by stevejalim** [comment]
@pmac v happy to, yeah
