### ISSUE TITLE
The "Donate" link from the footer of the page redirect to a "403 ERROR" while using a VPN connection

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/bedrock#11264]
[Affected Versions]:
- Nightly 99.0a1;
- Chrome 98.0.4758.102

[Affected Platforms]:
- Windows 10 x64
- Linux Mint 20 x64
- macOS 10.15.7

[Prerequisites]:
- Be connected to "US" country using a VPN connection, eg: MozillaVPN.

[Steps to reproduce]:
1. Navigate to https://www.mozilla.org/.
2. Scroll down the page until the footer is displayed.
3. Click the "Donate" button link.
4. Observe the behavior.

[Expected result]:
- You are redirected to the "Donate" page and the page is correctly loaded.
 
[Actual result]:
- You are redirected to the "Donate" page but a "403 ERROR" error is displayed.

[Notes]:
- The issue is NOT reproducible if you are not connected to a VPN service.
- I have managed to reproduce the issue using MozillaVPN and NordVPN.
- Attached is a screen recording of the issue.

https://user-images.githubusercontent.com/19226534/156201949-5a5da0b4-a4a4-4f5f-8a34-bc70acf4da7a.mov

**Comment by alexgibson** [comment]
@SoftVision-CosminMuntean please file bugs for donate.mozilla.org [here](https://github.com/mozilla/donate-wagtail), thanks!

**Comment by SoftVision-CosminMuntean** [comment]
Oh sorry, @alexgibson. I have moved this issue to "donate-wagtail" repo:[ #1645](https://github.com/mozilla/donate-wagtail/issues/1645). Considering this I will close this one.

**Comment by alexgibson** [comment]
@SoftVision-CosminMuntean no problem, thanks for filing!
