### ISSUE TITLE
Add Our Third Party Software Injection Policy to mozilla.org

### ISSUE THREAD

**Issue by hafta** [mozilla/bedrock#11276]
## Description

Add our new third party software injection policy to our policy documents on mozilla.org.

The document has been reviewed but may need some changes to fit the mozilla.org style. Here's the latest version of the policy.

https://docs.google.com/document/d/1jx2AE165zEttyXJEaQQOfewWUqsKO0yKWD6ScqtyNac/edit?usp=sharing

Once the policy is available online, we'll announce it via blog post.

---

#### Success Criteria
- [ ] The policy exists on mozilla.org in an appropriate discoverable location

**Comment by alexgibson** [comment]
@hafta would the URL https://www.mozilla.org/en-US/about/governance/policies/third-party-software-injection/ be a suitable location for this document?

**Comment by hafta** [comment]
I think so. And it could be linked from https://www.mozilla.org/en-US/about/governance/policies/

@danielnazer what do you think?

**Comment by danielnazer** [comment]
It's not quite a governance or a licensing policy. Probably better in "Security" or "Hacking"

**Comment by alexgibson** [comment]
@danielnazer @hafta so https://www.mozilla.org/en-US/security/third-party-software-injection/?

If you have something specific in mind, please suggest it.

**Comment by danielnazer** [comment]
That works for me, thanks

**Comment by alexgibson** [comment]
Ok thanks, this is in our teams backlog so can be picked as soon as someone has bandwidth. We'll push this to a demo server for review before it goes live.

**Comment by hafta** [comment]
Please change "Even where the desired behavior might be beneficial to users" to "Even **when** the desired behavior might be beneficial to users".

Otherwise it looks good to me. I'm not available next week so could we hold off for now before pushing to production so I'm around if questions come up?

It couldn't see how to navigate to this content from the root mozilla.org page. Is there a way?

**Comment by alexgibson** [comment]
> Please change "Even where the desired behavior might be beneficial to users" to "Even when the desired behavior might be beneficial to users".

Sure, done

> Otherwise it looks good to me. I'm not available next week so could we hold off for now before pushing to production so I'm around if questions come up?

I'll put a do-not-merge label on the PR for this week. Should be fine to merge once you're back thanks.

> It couldn't see how to navigate to this content from the root mozilla.org page. Is there a way?

Mozilla.org has a lot of different sections and pages, so not everything is discoverable directly from the home page. The content that is featured there tries to reflect the most immediate needs of our visitros, and is curated carefully by our UX and marketing teams.

**Comment by hafta** [comment]
> > Otherwise it looks good to me. I'm not available next week so could we hold off for now before pushing to production so I'm around if questions come up?
> 
> I'll put a do-not-merge label on the PR for this week. Should be fine to merge once you're back thanks.

Thanks. I'm back and I think we're ready to ship this.

**Comment by alexgibson** [comment]
This is now in production https://www.mozilla.org/en-US/security/third-party-software-injection/

**Comment by hafta** [comment]
> This is now in production https://www.mozilla.org/en-US/security/third-party-software-injection/

Thanks, @alexgibson
