### ISSUE TITLE
Migrate to SaSS Sentry instance [May 31]

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11278]
Objective: migrate our applications to use the new SaaS Sentry from our hosted Sentry.

(See Context below for original notification email)

----

### Success criteria

 - [x] Team set up in SaaS Sentry 
    - [x] Same-as-current/All team members members of it 
 - [x] All existing MEAO projects set up in SaaS Sentry with same config as hosted Sentry + new DSN (OR skipped if Sentry project is definitely retired/unnecessary)
   - [x] basket-dev
   - [x] basket-prod
   - [x] basket-stage
   - [x] bedrock-demos
   - [x] bedrock-dev
   - [x] bedrock-frontend-prod
   - [x] bedrock-prod
   - [x] bedrock-stage
   - [x] bedrock-test
   - [x] nucleus-prod
   - [x] ~snippets~ NOT BEING PORTED
 - [x] Config updated with new DSNs and changes applied to use them
   - [x] basket-dev
   - [x] basket-admin (ie prod admin)
   - [x] basket-prod
   - [x] basket-stage
   - [x] basket-admin-stage
   - [x] bedrock-demos
   - [x] bedrock-dev
   - [x] bedrock-frontend-prod
   - [x] bedrock-prod
   - [x] bedrock-stage
   - [x] bedrock-test
   - [x] ~nucleus-dev~ - doesn't talk to Sentry at the mo
   - [x] nucleus-prod
   - [x] ~snippets~ NOT BEING PORTED
   - [x] DOUBLE CHECKED AGAINST https://github.com/search?q=org%3Amozmeao+sentry.prod.mozaws.net&type=code
- [x] All current MEAO project groupings set up in SaaS Sentry:
   - [x] #basket
   - [x] #bedrock
   - [x] #nucleus 
   - [x] ~#snippets~ NOT BEING PORTED
- [x] Data confirmed as flowing to SaaS Sentry for all projects
   - [x] basket-dev
   - [x] basket-admin (ie prod admin)
   - [x] basket-prod
   - [x] basket-stage
   - [x] basket-admin-stage
   - [x] bedrock-demos
   - [x] bedrock-dev
   - [x] bedrock-frontend-prod
   - [x] bedrock-prod
   - [x] bedrock-stage
   - [x] bedrock-test
   - [x] ~nucleus-dev~ - doesn't talk to Sentry at the mo
   - [x] nucleus-prod
   - [x] ~snippets~ NOT BEING PORTED

# Sentry tuning
- [ ] Set up alerts for high volumes of errors in prod and dev
    - [ ] bedrock-dev 
    - [ ] bedrock-frontend-prod 
    - [ ] bedrock-prod 
    - [ ] basket-dev 
    - [ ] basket-prod
    - [ ] nucleus-prod 

- [x] https://github.com/mozmeao/infra/issues/1374

---
## Context

From email:

Your Involvement:

We will need you to migrate your application to use the new SaaS Sentry. We have just finished a small beta period and the migration is now open to the whole company. The SaaS Sentry is SSO enabled. The login URL is https://sentry.io/organizations/mozilla/issues/ . 

Further set up instructions can be found on this mana page here: https://mana.mozilla.org/wiki/display/SRE/SaaS+Sentry

Timeline:

The target date to migrate to SaaS Sentry is no later than May 31, 2022. This timeline applies to both sentry.prod and the sentry-fm.prod instances. That gives 90 days to change your application code from your current Sentry to the new SaaS solution.

Milestones and project status can be found on this mana page here: https://mana.mozilla.org/wiki/display/IP/Sentry+Migration

Communication:

If you have any questions or issues, feel free to message Tom, Wei, or Rosanna We can also be found via our slack channel, `#sentry-migration`

**Comment by alexgibson** [comment]
Filed this after receiving via email ^

cc @pmac @stevejalim @robhudson

**Comment by stevejalim** [comment]
Looks like we'll first need a Team set up for us in the new Sentry. I lack sufficient permissions, but maybe you have them already @pmac?

**Comment by stevejalim** [comment]
I've updated the description with some checklists, but I think / hope there are some redundant projects in the current Sentry setup that we won't need to migrate. @pmac and/or @alan would you mind confirming if all of the projects listed above are still needed - eg the ones that are region specific

**Comment by stevejalim** [comment]
@robhudson Fancy splitting this with me?

**Comment by pmac** [comment]
A lot of those apps listed in the issue are no longer needed. All of the ones with cluster names are the main ones we don't need to migrate. I'll clean up the lists.

**Comment by pmac** [comment]
done

**Comment by stevejalim** [comment]
Note that for now we've internally agreed to use SaaS Sentry's PII-scrubbing behaviour (as we do with self-hosted Sentry currently), but we do want to move away from that. The relevant work is explored in https://github.com/mozmeao/infra/issues/1373

**Comment by stevejalim** [comment]
OK @pmac @robhudson @alexgibson I've swept through all the things that used hosted Sentry and swapped them to new SaaS Sentry. We could do some tuning as part of this ticket, but in reality we'll probably do it down the line when we get more data in.

As such, I think we can close this, yeap?
