### ISSUE TITLE
Styling and link issues on Firefox Developer firstrun

### ISSUE THREAD

**Issue by crpz1** [mozilla/bedrock#11281]
## Description

The link to learn more about the CSS engine sends you to information about the browser's developer features which is misaligned.

### Steps to reproduce

Visit [https://www.mozilla.org/en-US/firefox/98.0a2/firstrun/](https://www.mozilla.org/en-US/firefox/98.0a2/firstrun/)

### Expected result

The link to learn more about the CSS engine sends you to information about the engine.

### Actual result

You get linked to information about the browser's developer features which isn't aligned.
![](https://ralsei-appreciation.club/i/0yynzmp4.png)

### Environment

Windows 10 Education 21H1
Firefox Developer Edition 98.0b10

**Comment by Ayushsunny** [comment]
Hey @alexgibson, Can I make a PR for this issue?

**Comment by craigcook** [comment]
The same issue appears on the Dev Edition whatsnew page at https://www.mozilla.org/firefox/98.0a2/whatsnew/

Both pages are missing the `protocol-split` bundle in the `page_css` block. See https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/developer/index.html#L19

> Hey @alexgibson, Can I make a PR for this issue?

Feel free to submit a PR, it should be a quick fix.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/11298  and https://github.com/mozilla/bedrock/pull/11282
