### ISSUE TITLE
Port webvision.mozilla.org to bedrock

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#11352]
## Description

The team that built https://webvision.mozilla.org/ would like to move hosting of the content to bedrock at a URL like `/about/webvision/` (possibly not final).

---

#### Success Criteria
- [ ] 2 pages from the current site live on www.mozilla.org at the approved URLs
- [ ] The content of the pages should be imported and rendered and automatically updated from the [Markdown files in the GitHub repo](https://github.com/mozilla/webvision/tree/main/input).
- [ ] The content should be styled in accordance with our website standards.

Once this is done we'll work with Web SRE to add a redirect from the subdomain to these new pages.

/cc @bgrins

**Comment by bholley** [comment]
This LGTM, thanks.

**Comment by reemhamz** [comment]
@pmac @slightlyoffbeat do we want this page to be easily accessible through some nav on the main website? How can we make it easy for users to navigate to it?

**Comment by slightlyoffbeat** [comment]
Lets hold on adding to main nav.

We can replace the facebook container card on `/about` with a link to this.
      
we can also add a section similar to "our products" and "get involved" on the `/about` side nav

<img width="415" alt="image" src="https://user-images.githubusercontent.com/2030656/160482263-607817f7-c67a-41cf-a6cc-a7056c8592fd.png">

**Comment by reemhamz** [comment]
@slightlyoffbeat you mean `/about/manifesto/details/` for the second section you mentioned (not `/about`)?
Also, if replacing with the Facebook Container card in `/about`, is there an image you'd like me to use?

**Comment by slightlyoffbeat** [comment]
Yes, the same one that is on `https://www.mozilla.org/en-US/mission/`

I don't have a photo. Current site is using bg-8 from this repo for their meta image. That should work fine: https://github.com/mozmeao/foxtail/tree/master/assets/images/fallback

**Comment by pmac** [comment]
This is now done and in production! Great work team! https://www.mozilla.org/en-US/about/webvision/

There's also the vanity URL redirect  https://www.mozilla.org/webvision/
