### ISSUE TITLE
[Contentful] Add MDN Plus as an option for Contentful Components

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11356]
## Description

There are a few components that need to be updated to include support for MDN Plus:

1st Component:♟ Component: CTA Button
- Add "Get MDN Plus" option
- Link: https://developer.mozilla.org/plus
- UTM parameters: use Relay as a reference

2nd Component: ✏️ Component: Hero
- add MDN Plus as a product icon option (see SVG below)

![mdn-plus-logo-transparent](https://user-images.githubusercontent.com/2030656/159840049-6abaca53-b207-41e5-ad27-bc96844cff8a.svg)

---

**Comment by alexgibson** [comment]
To add the logo as a hero icon option we might need to add support for it to Protocol (unless that's going to take too lang and we might want to override). There's an issue to add the logo to protocol/assets here: https://github.com/mozilla/protocol-assets/issues/83

**Comment by alexgibson** [comment]
I'm going to hard-code the MDN logo option to the feature component, and we can remove the override if / when it's added as an option to Protocol.

**Comment by alexgibson** [comment]
Preview added to the sandbox environment:

![image](https://user-images.githubusercontent.com/400117/160400849-d0cfa262-1593-40b0-83e3-bc4e2ce50712.png)

**Comment by alexgibson** [comment]
@slightlyoffbeat if you add a new `Get MDN Plus` action to the CTA Component, and an `MDN Plus` option to the product icons for the Hero component, then this should now work. I tested this in the sandbox here: https://app.contentful.com/spaces/w5er3c7zdgmd/environments/sandbox/entries/4E6typcA8PGriib6XETFv2
