### ISSUE TITLE
Add ability for `page()` URL helper to accept URL names with trailing slash

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#11395]
Doing this will add consistency with the built-in Django `path()` method. Confusion around this has come up several times recently. The [function is defined here](https://github.com/mozilla/bedrock/blob/7690d95755f8387fd480d159a6eb320a2d1fac75/bedrock/mozorg/util.py#L24).

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/11396
