### ISSUE TITLE
Create WNP for Firefox 99

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#11393]
## Description

Firefox 99.0 releases on 5 April 2022. We'll have whatsnew pages for English, French, and German.

EN copy: https://docs.google.com/document/d/1N8jDLZdav-loEmRqS14btZ3Urb6RD_tWuX2lqMy4XBw/
FR/DE copy: https://docs.google.com/document/d/1QjCSv4CBPvtTzF8z_sLosnsjIqGwMkRerjZIiPYHzxU/

**Comment by slightlyoffbeat** [comment]
English: 90% Pocket, 10% Rally

Pocket creative & copy: Not available. Will be delivered by EOD. Will generally follow the layout of WNP 91

Rally: Same as WNP 96. The rally team requested minor changes, but is also fine if we keep it exactly as it was. Their request was to:

1. Reduce image size and padding a bit to tighten up the amount of vertical spacing before the CTA
2. Removing the first phrase of the opening sentence to reduce the text and start with an verb/action. This means the text would be "Help us uncover Facebook's...." (remove "Join Mozilla Rallies studies and")

**Comment by slightlyoffbeat** [comment]
Rally team provided this mock of tightening things up.

I defer on this. If you can incorporate feedback/changes go for it. If not, I fully support using the page as-is without changes.

![image](https://user-images.githubusercontent.com/2030656/160919629-6cff586a-c6f8-465b-a4bf-9395eb363be7.png)

**Comment by slightlyoffbeat** [comment]
WNP 99 NA: 

[Copy](https://docs.google.com/document/d/1N8jDLZdav-loEmRqS14btZ3Urb6RD_tWuX2lqMy4XBw/edit?usp=sharing
) (approved)

[Design](https://www.figma.com/file/CZvzHgU9NQMQUm34lomIl5/?node-id=1741%3A39533) (also approved)
