### ISSUE TITLE
Enable ERTAMO referer check for the custom thanks page for AMO

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/bedrock#11467]
## Description

In #10337 a change was landed to support Enhanced Return to AMO (ERTAMO) which checks that the referer is AMO before enabling RTAMO for the Firefox download. In #10520 the `/firefox/download/thanks/` page was enhanced to allow a direct link via the `s=direct` query param. It appears that the logic added for ERTAMO in #10337 does not work on this new `/thanks/` page. The missing check means we'll pass RTAMO attribution unconditionally whereas we only want that for AMO referrals. This issue is about enabling the referer logic for the `/thanks/` page to resolve that problem.

---

#### Success Criteria
- [ ] A user who visits a `/thanks/` link to download Firefox which includes the query param for RTAMO for a non-recommended add-on, which does not include AMO as a referer, should not have the RTAMO flow enabled.

**Comment by bobsilverberg** [comment]
cc @willdurand @diox

**Comment by alexgibson** [comment]
Looks like we need to add a check for `hasValidData()` to the custom script we created for the special /thanks page

**Comment by alexgibson** [comment]
@bobsilverberg please help test:

- [ ] https://www-demo1.allizom.org/en-US/firefox/download/thanks/?s=direct&utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=rta%3Acm9uaW4td2FsbGV0QGF4aWVpbmZpbml0eS5jb20 (no stub attribution cookie created)
- [ ] https://www-demo1.allizom.org/en-US/firefox/download/thanks/?s=direct&utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=rta%3Acm9uaW4td2FsbGV0QGF4aWVpbmZpbml0eS5jb20 (stub attribution cookie is created).

**Comment by willdurand** [comment]
That seems to work as intended, thanks!

I only checked the presence (and absence) of the cookie, the stubattribution never returned a FF installer with the expected data (for the first link) but it is very likely that the demo instance isn't compatible with the (prod) stubattribution. We'll verify on prod when the patch for this issue gets deployed.

**Comment by willdurand** [comment]
@acornestean fyi, this is the issue for the problem you identified today (PI Request QA-1454)
