### ISSUE TITLE
Refresh evergreen WNP for developer edition

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11462]
Current Link: https://www.mozilla.org/en-US/firefox/100.0a2/whatsnew/

**Comment by alexgibson** [comment]
Throwing in some ideas that may help to keep an evergreen page engaging without needing regular updates:

- Show a Dev Tools feature highlight (maybe we could cycle through different features from a finite list, so each release shows something different).
- Feature a random MDN article / link each update.
- Pull in hacks blog post feed.

**Comment by alexgibson** [comment]
We should also try and cover the /firstrun page here (right now both /firstrun and /whatsnew share the same template)

**Comment by slightlyoffbeat** [comment]
Another idea: include a unit to let users know about MDN+

**Comment by stephaniehobson** [comment]
Another idea: link to the release notes.

**Comment by stephaniehobson** [comment]
Another idea: Open the release notes.

**Comment by alexgibson** [comment]
@slightlyoffbeat could we just retire this page and redirect to the release notes page, if this is something we're no longer planning to do?

**Comment by stephaniehobson** [comment]
Superseded by #14244
