### ISSUE TITLE
WNP footers no longer apply dark-theme styles

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11465]
## Description

This might be a regression from https://github.com/mozilla/bedrock/issues/10830

http://localhost:8000/en-US/firefox/99.0/whatsnew/

![image](https://user-images.githubusercontent.com/400117/162165334-cd466084-b48b-4679-a19d-d6e5f51937d7.png)

**Comment by maureenlholland** [comment]
yep, forgot to update the selector from `c-footer` to `mzp-c-footer` 🙈
