### ISSUE TITLE
Add global CSS style for hidden attribute

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11476]
## Description

In a few places we've started using the [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) attribute, for example to hide [newsletter checkboxes](https://github.com/mozilla/bedrock/blob/master/bedrock/newsletter/templates/newsletter/includes/form.html#L14-L16) when there's only a single newsletter. This works fine in all modern browsers we support, but the checkbox still remains visible in some older browsers such as IE10.

Adding a default CSS style for the hidden attribute could provide a (presentational) level of backward compatibility in older browsers:

```css
[hidden] { 
    display: none;
}
```

**Comment by msolorio** [comment]
Hello, I would be happy to take this bug.
