### ISSUE TITLE
Explain how to test pages that don't have obvious URL structure 

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11479]
Thinking in particular of Firefox whatsnew (release, dev, nightly), firstrun, new (desktop and basic) but any pages that were hard to test because you didn't know what url to use would belong here.

Might live near https://bedrock.readthedocs.io/en/latest/coding.html#writing-url-patterns

**Comment by alexgibson** [comment]
Release notes URLs would also be a good addition here.
