### ISSUE TITLE
Mozilla VPN Website is not intuitive/obvious as to where to go for existing users

### ISSUE THREAD

**Issue by JC-Support** [mozilla/bedrock#11471]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

Customer Feedback: As a user and active subscriber, it is not intuitive where I should go on https://www.mozilla.org/en-US/products/vpn/  to download or even access my account. “Already a subscriber” link is not intuitive. Should be an explicit call to action.
---
Also tracked on https://mozilla-hub.atlassian.net/browse/VPN-2031

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by alexgibson** [comment]
This is especially true for visitors on mobile, where the "Already a subscriber?" link is hidden behind a menu. We should have another link in-page that's always visible.

**Comment by alexgibson** [comment]
I'm going to try and fix this issue this as we migrate the download page to bedrock in https://github.com/mozilla/bedrock/issues/11659.

My proposal is to add a new FAQ question (in addition to the "Already a subscriber?" link in the nav).

![image](https://user-images.githubusercontent.com/400117/169247414-f4bb95ad-192e-4251-b922-bd7b9bc7d098.png)

@slightlyoffbeat I'm not sure who we have for copy writing at the minute, but this seems like a simple enough change I wonder if we can just run with this. Does the copy above look / sound OK to you?
