### ISSUE TITLE
.well-known/matrix/ 404s

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11485]
## Description

https://www.mozilla.org/.well-known/matrix/ seems to throw a 404, but the codebase implies it should be there

### Environment

MacOS, FF Nightly 100

**Comment by pmac** [comment]
I don't recall that there's anything supposed to be at that URL. The URLs for the necessary files within that folder work, and I believe that's the important part. 

* https://www.mozilla.org/.well-known/matrix/client
* https://www.mozilla.org/.well-known/matrix/server
