### ISSUE TITLE
Enhance docs to use abbreviations with tool tip definitions for acronyms

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11481]
We have a lot of acronyms. They're hard to learn and easy to forget. We should include acronym definitions as much as possible where they are used throughout the docs.

Thinking of `:abbr:` or similar
https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#other-semantic-markup

**Comment by robhudson** [comment]
https://github.com/mozilla/bedrock/pull/11527
