### ISSUE TITLE
[Affiliate marketing] 404 for cjms call and error in the console

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#11506]
## Description

While testing the Affiliate Marketing initiative, we came across a potential issue 
We have the:
- Uncaught (in promise) Error: Unknown aicID: 92afb117-c2d8-455d-b262-5cf6743fd3fd error in the console.
- 404 response for the cjms PUT call, where the aicID should be in the response, which is empty
see screenshots and video

### Steps to reproduce
Steps performed:
1. Accessed the affiliate link in a new profile on Firefox: https://www-dev.allizom.org/en-US/products/vpn/?cjevent=4a39c2b8bccc11ec806c00a40a18050c
2. Left profile as is until next day, to perform a subscription with the affiliate code at a later date
3. The next day, opened the profile and refreshed the page

NOTE: 
- We did use that specific cjevent (4a39c2b8bccc11ec806c00a40a18050c) for other subscriptions. Could it be that the aicID has been assigned to one of those and it is no longer valid?
- We checked the same URL on a Firefox clean profile and it works as expected. It also works on Chrome.

### Expected result
The cookie banner should be displayed.
There are no errors in the console and the cjms call is made successfully

### Actual result

The cookie banner is not displayed, there are errors in the console and the cjms put call fails with 404

### Environment

Firefox, with a separate profile.

https://user-images.githubusercontent.com/52028275/164012156-849000f0-09f9-48fa-8a9f-b1095ee7534b.mp4

![error in console](https://user-images.githubusercontent.com/52028275/164012174-226f0260-f4d5-46d1-a187-fd8c49a35980.PNG)
![APIs](https://user-images.githubusercontent.com/52028275/164012177-6cc1a73d-d07a-4d7d-a18b-137399c2861c.PNG)
![cjms response](https://user-images.githubusercontent.com/52028275/164012179-70a55db8-f93f-430b-b3cf-5f41f38bffe9.PNG)

**Comment by birdsarah** [comment]
OK. Discussed with Lauren. 

@alexgibson in the case of a 404 can you initiate a new POST request with the cjevent and the flow id and override the existing browser cookie. The 404 means the cookie is no longer active server side because it has been archived so creating a fresh cookie early is appropriate.

This is and edge case and not a blocker for launch but would be good to get done sooner rather than later.

**Comment by alexgibson** [comment]
Thanks @birdsarah I'll see to this asap.

**Comment by alexgibson** [comment]
I think I've discovered another edge case in this which my first fix didn't cover. Currently we still throw an un-handled 404 if the following conditions are true:

- Visitor already has a marketing cookie set
- aic id has expired in the CJMS database
- Visitor lands on the page **without** a CJ Event parameter (my first fix only covered the condition where a CJ event parameter does exist on the repeat visit).

I'll follow up with another fix soon

**Comment by alexgibson** [comment]
@birdsarah seeing as in the above scenario there's no cjevent parameter and we can't treat it as a new request, I'm going to suggest we simply delete the marketing cookie.

Does that sound sensible to you?
