### ISSUE TITLE
Port the Pocket homepage to Bedrock

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11513]
## Description

If you run Bedrock in its new Pocket mode locally (`npm run in-pocket-mode` or `make run-pocket`) and you go to `/` there is no page available - we still need to port the homepage into bedrock and @pmac mentioned we now have the go-ahead to do that.

---

#### Success Criteria
- [ ] / in Pocket mode serves the Pocket homepage, locally, from bedrock
- [ ] The Pocket homepage looks exactly the same as the one currently at getpocket.com
- [ ] The Pocket homepage is marked up with Fluent strings

**Comment by reemhamz** [comment]
Would we be porting over the homepage from https://github.com/mozmeao/pocket-marketing-pages/? I know @maureenlholland  was the one who developed the homepage on that repo. Do we want to port it manually the way @nathan-barrett and I have done it for the other Pocket pages, or is there another way you and @pmac were thinking?

**Comment by maureenlholland** [comment]
@reemhamz the only thing that's really different with the homepage is there is a new design for EN and DE only, the rest of languages are using the old homepage design. I think that's the only page so far where we have different templates/styles based on languages.

**Comment by stevejalim** [comment]
Thanks @maureenlholland! In which case, I guess we need to port both, and have a little bit of Django that picks the appropriate template based on the active locale. 

@reemhamz I'll start a branch now with empty templates that should set you up for both

**Comment by pmac** [comment]
Why do we have different templates for EN/DE and the rest? Do we need to keep that, or is it just a case of not having done the rest of the work yet? If it's the latter, we should just port the new one to bedrock and let that be the rest of the porting work. 

@slightlyoffbeat thoughts?

**Comment by maureenlholland** [comment]
@pmac that's a good point. We did the two languages for the new design because there was no time to translate the others before Dec. and there was no build system in place so each template would have had to have been individually updated. Makes sense to just port the new design for bedrock.

**Comment by pmac** [comment]
Great! That matches my vague memory of that work. Thanks for the confirmation. Let's just port the new one and let the new l10n machinery do its work.

**Comment by stevejalim** [comment]
In that case, I'm deleting `11513--pocket-in-bedrock-homepage` -- @reemhamz just make a regular branch off `main` for this one after all!

**Comment by slightlyoffbeat** [comment]
@pmac @maureenlholland is correct. We only had time/resources to do homepage refresh in en and de because these pages were static and l10n was manual.

With this new system, we should apply the en/de template to all languages.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/11592
