### ISSUE TITLE
[macOS] Firefox about pane says "Firefox is up to date" but it's not

### ISSUE THREAD

**Issue by wonbug** [mozilla/bedrock#11514]
## Description

Firefox says it's up to date in the About menu pane on macOS, but it's version 99.0.1 which is not the latest. Firefox nags from the top-right hamburger menu to update, which takes me to Mozilla's website to download Firefox.

### Steps to reproduce

Use Firefox 99.0.1 (64-bit) on macOS 12.3.1

### Expected result

It shouldn't both say the browser is up to date while another menu in Firefox tells me it isn't.

### Actual result

I get conflicting messages.

**Comment by stevejalim** [comment]
Hi @wonbug - thanks for the report. However, Firefox-related bugs are best reported in [Bugzilla](https://bugzilla.mozilla.org/home). Would you mind re-submitting over there please? I could paste it in for you, but if you generate the bug yourself you'll more easily get updates.

Closing this ticket, with thanks.

**Comment by stevejalim** [comment]
Update: the direct link for raising a Firefox-categorised bug is https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

**Comment by wonbug** [comment]
Looks like it's already a bug for 2+ years https://bugzilla.mozilla.org/show_bug.cgi?id=1643309

Not great for security. Would appreciate additional attention on this issue.
