### ISSUE TITLE
Update the documented `redirect` method definition

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#11525]
The method definition for `redirect` has drifted since written. Update the docs to match the current code.

**Comment by shubhamvrs** [comment]
assign\

**Comment by stevejalim** [comment]
Go for it @shubhamvrs  😄

**Comment by nox1134** [comment]
Hi @stevejalim ! If no one is working on this issue, I'd like to take up this issue and work on it.
Could you please assign the issue to me?

**Comment by nox1134** [comment]
Hi @stevejalim ! If no one is working on this issue, I'd like to take up this issue and work on it.
Could you please assign the issue to me?
