### ISSUE TITLE
Update Contentful's branch naming

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11528]
## Description

Now we've got bedrock using `main` as its default branch, we should do the same with Contentful, where we currently have a production environment called `master`.

---

#### Steps
- [x] Environment alias created in Contentful called `main`, pointing to the same environment as `master` currently does (`V1.0`)
- [x] Bedrock updated to use `main` as its default Contentful branch
- [x] Bedrock documentation updated re `main` rather than `master`
- [ ] Once the change to `main` is in production, the `master` environment alias can be removed

#### Success Criteria
- [ ] Contentful integration working as before, just with `main` as its default, production environment

**Comment by pmac** [comment]
We can't actually change this. `master` is special in Contentful, we could use a different alias for our stuff, but the one that will be the published content will always be `master` and others won't.

**Comment by pmac** [comment]
> Master environment and master alias can’t be deleted and their names can’t be changed.

https://www.contentful.com/developers/docs/concepts/multiple-environments/

**Comment by pmac** [comment]
we asked them about this during setup. Haven't heard any plans on their side to change things.

**Comment by stevejalim** [comment]
ugh, dang. thanks for the catch @pmac!
