### ISSUE TITLE
Enable GA4 on mozilla.org properties

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11537]
## Description

Universal Analytics is being sunset. We should enable GA4 alongside GA3. This will allow us to become familiar with GA4 and to work with it to ensure a smooth transition next year.

---

#### Success Criteria
- [ ] Universal Analytics (GA3) is not affected and remains as is for now.

#### Properties
- [x] Mozilla.org
- [x] support.mozilla.org
- [ ] relay.firefox.com ([relay issue](https://github.com/mozilla/fx-private-relay/issues/1927))
- [x] blog.mozilla.org
- [ ] monitor.firefox.com ([monitor issue](https://github.com/mozilla/blurts-server/issues/2556))

Relevant Links:
[https://support.google.com/analytics/answer/11583528](https://support.google.com/analytics/answer/11583528)

**Comment by maureenlholland** [comment]
ongoing research (Mozilla only): https://docs.google.com/document/d/1A3QK6DZgrZ4guIVMVCfGG7hN2B63phWLzp-cyVbDJS8/edit?usp=sharing

**Comment by pmac** [comment]
@slightlyoffbeat I think we've done all we can on this one. The issues are filed for the Monitor and Relay teams. Can we close this, or do you want to keep it open for your own followup?

**Comment by maureenlholland** [comment]
Closing as the GA4 properties are available and basic implementation has been enabled where possible.
