### ISSUE TITLE
Create /firefox/mobile/get-app/ variations for product experiment

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11547]
## Description

Product teams have additional experiments that require some temporary variations created for /firefox/mobile/get-app.

Notes:
- experiment is EN only
- these variations can be deleted after the experiment is over (timing TBD)

### Details:

3 variations needed

For each variation:
- remove google play and app store buttons
- Swap out basket ID with new basket ID that will be used for attribution

Page Variants:
- https://www.mozilla.org/en-US/firefox/mobile/get-app/?v=eco-a
- https://www.mozilla.org/en-US/firefox/mobile/get-app/?v=eco-b
- https://www.mozilla.org/en-US/firefox/mobile/get-app/?v=eco-c

Message Group ID in Acoustic Transact (used to created Basket IDs)
variant A: 2680692 (EcoTest-TreatmentA-FxMobile-Download_EN_HTML)
variant B: 2680695 (EcoTest-TreatmentB-FxMobile-Download_EN_HTML)
Variant C: 2680696 (EcoTest-TreatmentC-FxMobile-Download_EN_HTML)

Pmac or someone from backend can generate basket IDs from the information above

**Comment by slightlyoffbeat** [comment]
@pmac can you (or someone you assign) generate the basket IDs needed with the information above?

**Comment by pmac** [comment]
Done. IDs are:

```
download-firefox-mobile-reco-exp-a
download-firefox-mobile-reco-exp-b
download-firefox-mobile-reco-exp-c
```
