### ISSUE TITLE
Frontend-specific improvements for Pocket mode: Static bundle separation

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11544]
## Description

Following on from #11494's comments there are some frontend-specific changes that it would be good to make. This ticket is focused on creating separate static-bundles.json files for both Pocket and Mozorg modes, so we don't need to build the front end for both sites each time.
 
---

#### Success Criteria
- [ ] Pocket runs its own, slimmer, static bundle, separate from Mozorg's

**Comment by stevejalim** [comment]
Note from @pmac in the original PR:
> This is more tricky because we want the full set of frontend stuff to be built and uploaded during deployment because we're not going to separate that, we'll just reference those assets from the same bucket they're uploaded to today. That said I'm sure we could separate them for local dev mode while still making deployment work as expected.

**Comment by alexgibson** [comment]
Another potential solution for this is in: https://github.com/mozilla/bedrock/pull/12522
