### ISSUE TITLE
Frontend-specific improvements for Pocket mode: CSP config

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11543]
## Description

Following on from #11494's comments there are some frontend-specific changes that it would be good to make.

Sepecfically, we could have a separate CSP config for both mozorg vs pocket mode
 
---

#### Success Criteria
- [ ] Pocket runs its own CSP config, separate from that for Mozorg

**Comment by stevejalim** [comment]
@alexgibson What specifically do we need to support a Pocket-mode CSP config?

**Comment by alexgibson** [comment]
@stevejalim right now both sites share a single CSP config, so for example if we permit third party JS to be loaded by `example.com` for mozorg, then it's also permitted for pocket when it doesn't really need to be.

It would be a bit better for security if both modes had their own CSP config in settings. I believe Pocket requires GA, `cdn.cookielaw.org`, `privacyportal.onetrust.com`, but I'm not 100% sure what else? (another good reason for splitting this out is to make future changes easier to figure out).
