### ISSUE TITLE
Check MDN links (https://developer.mozilla.org/) and replace where applicable

### ISSUE THREAD

**Issue by caugner** [mozilla/bedrock#11555]
## Description

Some pages link to old archived MDN pages that redirect to Firefox Source Docs.

See: https://github.com/mozilla/bedrock/search?q=https%3A%2F%2Fdeveloper.mozilla.org

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/nightly/firstrun/
2. Hover over "Tools" in the footer, and notice that it links to https://developer.mozilla.org/docs/Tools/
3. Click on the link, and notice that it redirects to https://firefox-source-docs.mozilla.org/devtools-user/index.html

### Expected result

The links should be replaced to point to the redirected location.

### Actual result

The links point at MDN, which has to redirect.

### Environment

Irrelevant, but FIrefox Nightly on Mac OS.

**Comment by conradylx** [comment]
https://github.com/mozilla/bedrock/pull/11578
