### ISSUE TITLE
Hook up translation vendor for Pocket l10n

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11575]
## Description

Blocked by #11521 (and soft-blocked by #11519) 

We'll be using Smartling for github.com/mozilla-l10n/pocket-www-l10n translation. We need to hook up their side to read from and write to that new repo.

---

#### Success Criteria
- [ ] Smartling integration with github.com/mozilla-l10n/pocket-www-l10n works as well as it does for Mozorg (github.com/mozilla-l10n/www-l10n)

**Comment by alexgibson** [comment]
@stevejalim is this one good to close out now?
