### ISSUE TITLE
The revision.txt file is empty

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#11595]
Back in #5976 we setup the `/revision.txt` URL to be a text file containing the git revision ID for easy discovery of the deployed revision. We don't need it as much any more as that info is also at the `/healthz-cron/` URL, but this one makes it easy for scripts to discover the revision. This file was broken at some point and in production is is currently empty. We should fix that.

**Comment by stevejalim** [comment]
This will also let us re-enable whatdeployed.io for Bedrock. Nice!

**Comment by alexgibson** [comment]
Looks like this was fixed in https://github.com/mozilla/bedrock/pull/11596
