### ISSUE TITLE
www-dev.allizom.org is running in Pocket mode

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11607]
https://www-dev.allizom.org/en-US/ is 500 for many pages

Error in Sentry is `Reverse for 'mozorg.home' not found. 'mozorg.home' is not a valid view function or pattern name.`

Example: https://sentry.io/organizations/mozilla/issues/3263521681/?project=6260211&query=is%3Aunresolved

It is not clear to me what's caused this just yet. Is it maybe something related to Pocket mode?

**Comment by alexgibson** [comment]
Turns out, the site is deplyed in pocket mode: https://www-dev.allizom.org/en-US/about/

The error is due to the codebase trying to render mozorg's 404 page

**Comment by alexgibson** [comment]
Possibly related to https://github.com/mozmeao/www-config/pull/453

**Comment by pmac** [comment]
Fixed. @bkochendorfer figured out the issue with some routing in our infra.
