### ISSUE TITLE
Display issues on basic /firefox/download/thanks/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11608]
## Description

The basic version of the `/firefox/download/thanks/` page has some visual display issues.

### Steps to reproduce

1. Open https://www.mozilla.org/en-US/firefox/download/thanks/?xv=basic

### Expected result

1. The headline should be horizontally centered on the page.
2. The headline should be preceded by a Firefox logo? (pretty sure this used to be part of the page).

### Actual result

![image](https://user-images.githubusercontent.com/400117/167844153-0cbdbd9e-b95c-41fa-98b9-4cad683deafb.png)

### Environment

Firefox Nightly
macOS

**Comment by Ayushsunny** [comment]
Hey @alexgibson,
So the headline should be like this?
![Screenshot 2022-05-13 091139](https://user-images.githubusercontent.com/73520373/168206950-f633dbf4-41c2-4e5b-bb20-aff415353ecb.png)

**Comment by alexgibson** [comment]
@Ayushsunny close but not quite. Thanks for the interest, but I'm going to go ahead and get this one fixed quick.
