### ISSUE TITLE
Serve full FF installer for users on Windows 7

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11606]
## Description

There's an [ongoing issue](https://docs.google.com/document/d/1DG2OBw30Cc0vyYmKNkBS_Pd4rPqdXrUA-RScT8eJoy8/edit?usp=sharing) where a large number of users on Windows 7 are encountering an error running the stub installer.

Until that error is Fixed, the Firefox team would like to serve Windows 7 users the full installer when clicking download on `/firefox/new/`.

Detecting CPU architecture is out of scope for now. Serving the 32bit full installer is OK as this is a temporary measure.

---

#### Success Criteria
- [ ] When clicking download, users on Windows 7 are served the full installer when redirecting to `/firefox/download/thanks/`

**Comment by willdurand** [comment]
FTR: I verified the RTAMO flow after the patch for this issue has landed on prod. We get a full installer with attribution data and that triggers the RTAMO flow in `about:welcome` as long as the extension is recommended (everything works as expected).
