### ISSUE TITLE
Decommission the Unfck campaign pages

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#11613]
## Description

The "Unfck the Internet" campaign hasn't been active since early 2021 and the landing pages aren't receiving much traffic. We should clean them up and redirect the URL, probably to /firefox/new/ (or maybe just /firefox/?). 

#### Success Criteria
- [ ] Pages at /firefox/unfck/ (templates, assets, tests) are deleted.
- [ ] URL is redirected.

**Comment by alexgibson** [comment]
This page has had less than 6000 page views in the last year, between ~5-20 page views per day on average.

+1 for decommissioning

**Comment by craigcook** [comment]
Done in https://github.com/mozilla/bedrock/commit/bb05b298c78e0129f8dc5baa17c4b292d50b3d36
