### ISSUE TITLE
Adding a separate `l10n` directory under Pocket's `img` directory

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#11619]
## Description
While working on Pocket migration, we have to also migrate images that are localized (if an image has text in it, we use different versions of the image with different languages that show up under the respective locale URL). Historically in Bedrock, we'd store these images inside [this image l10n directory](https://github.com/mozilla/bedrock/tree/main/media/img/l10n) and use the [`l10n_image()` helper](https://bedrock.readthedocs.io/en/latest/coding.html#l10n-img) to display localized images. This helper specifically looks inside the main `/img/l10n` directory.

We could use Bedrock's image l10n directory to store the Pocket images, however, this would separate Pocket images from the Pocket directory, which we've been working on keeping separate from most mozilla.org-related code. 

A discussion was brought up around if it would be a good idea to create a separate `l10n` directory under Pocket's `img` directory: 
```
media/img/pocket/l10n/en
media/img/pocket/l10n/de
etc
```
and we would then create a new `l10n` helper: `pocket_l10n_img` to be used when adding localized images in Pocket templates.

For now, we'll stick to adding pictures in the already-set `l10n` image directory as we continue working on setting up the Pocket page migration and localization.

This issue is open for further discussion.

---

#### Success Criteria (if agreed upon)
- [ ] Create `l10n` directory under Pocket's `img` directory
- [ ] Create new `pocket_l10n_img` helper

**Comment by stevejalim** [comment]
One thing we need to bear in mind is that the current l10n_image helper treats all `es` locales as being the es-ES, which is not what we may want for Pocket - it def treats International Spanish (es) and Castilian Spanish (es-ES) differently. 

So, at the least we'll need a `settings.IS_POCKET_MODE` check in the helper - or we write a pocket-specific version (`pocket_l10n_img`)

**Comment by alexgibson** [comment]
The fact that we need to handle locales a bit differently for Pocket makes me think it's worth moving forward with @stevejalim's suggestion

**Comment by pmac** [comment]
I don't think it need to change to make that work. If the locale of the page is `es` it will look in an `es` folder for the image.

**Comment by pmac** [comment]
It will fall-back to `es-ES` to look for an image for all Spanish locales if the image doesn't exist in the specific one, but it'll use it if it does exist.

**Comment by pmac** [comment]
The main remaining question is whether we want to keep these files in separate folders or not. To me it makes sense to keep all localized images together for "bedrock", but if the consensus of the frontend folks, who have to use this system, is that it should be separate then we can make that happen.

**Comment by reemhamz** [comment]
So far we mainly have my take and @alexgibson's. Would love to hear from the rest of you folks @maureenlholland @nathan-barrett @craigcook on what you think!

**Comment by nathan-barrett** [comment]
My vote aligns with @alexgibson and leverage the current helper (but just check if the app is currently in pocket mode).

**Comment by stevejalim** [comment]
Looking at the code, I agree with pmac that we need no code changes around the handling of `es` with the current helper.

However, if we did put the pocket images into their own dir, it looks like these two parts are opinionated: 
https://github.com/mozilla/bedrock/blob/67fd925b4d621dde0e48e27738c4b9c397ac5169/bedrock/mozorg/templatetags/misc.py#L66 

https://github.com/mozilla/bedrock/blob/67fd925b4d621dde0e48e27738c4b9c397ac5169/bedrock/mozorg/templatetags/misc.py#L35-L37

But we can easily make them less opinionated about the images being in an `l10n` folder without needing to write a separate helper. e.g
```
if settings.IS_POCKET_MODE:
    l10n_dir = "l10n_pocket"
else:
    l10n_dir = "l10n"  # Mozorg default
return path.join("img", l10n_dir, locale, url)
```
plus something similar for `_l10n_media_exists`

**Comment by maureenlholland** [comment]
Ok, so we currently have

Translations
`l10n`
`l10n-pocket`

Localized images
`media/img/l10n/`

Non-localized Images
`media/img`
`media/img/pocket`

For me, it feels like images are part of the build system the we brought pocket over to bedrock to take advantage of. If we can leverage the existing l10n folder and helper, I would prefer that.

I think I'd find it odd to see `media/img/l10n-pocket` because it doesn't line up with my understanding that these modes share an img folder in general. That said, if we need to be careful about different locale handling or if the majority finds the separation more intuitive, I would prefer `media/img/l10n-pocket` over `media/img/pocket/l10n` because it's consistent with the l10n folder naming.

**Comment by stevejalim** [comment]
Is `media/img/l10n/{locale}/pocket/*` still on the table, cos that looks like it would just work as-is (like `media/img/l10n/{locale}/firefox`)

**Comment by maureenlholland** [comment]
Yep, working out of the box in the home PR: https://github.com/mozilla/bedrock/pull/11592/files#diff-f996da2dbdfde7a3a703c466a700b013a6c3bd41231582be4e51611df483bcddR57
https://github.com/mozilla/bedrock/pull/11592/files#diff-bf9c70ec288c4bcaa098a92d227a31b67271436277ca2e64c68d2def801accc7

I like `media/img/l10n/{locale}/pocket/*` but I'm easily swayed on the basis of what folks find most clear to work with. If the [Pocket l10n locales](https://github.com/mozilla/bedrock/blob/main/bedrock/settings/__init__.py#L157) become confusing when mixed with Mozorg, then we should keep them separate.

**Comment by stevejalim** [comment]
OK, so shall we close this? Can i get some 👍 or 👎 ?

**Comment by reemhamz** [comment]
Sounds good to me -- good discussion team 👍🏼! Thanks for all the inputs :)
