### ISSUE TITLE
Send to Device submit button should have GA data attributes

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11618]
## Description

From Adria: Buttons on https://www.mozilla.org/en-US/firefox/browsers/mobile/ios/ and https://www.mozilla.org/en-US/firefox/browsers/mobile/android/ need event listeners to send events for those interactions. I didn't see any very obvious Event Names that fit, but I guess lead_generation would work.

<img width="531" alt="download-link-form" src="https://user-images.githubusercontent.com/19650432/168036997-12113191-bfda-4458-9154-29d2ac473980.png">

The "Send" button on the [send to device widget](https://bedrock.readthedocs.io/en/latest/send-to-device.html) should send an event to GA (when analytics are enabled). 

Likely it best fits the ["generic button" category](https://bedrock.readthedocs.io/en/latest/analytics.html#gtm-listeners-data-attributes) and should include the expected data-attributes.

## Success Criteria

- [ ] Confirm data attribute values (particularly event name)
- [ ] When analytics are enabled, "Send" button click triggers GA event with expected values
- [ ] No regression in Send to Device behaviour

**Comment by maureenlholland** [comment]
Ah, ok, thanks for the context @alexgibson!

**Comment by a-kyne** [comment]
Okay, so if I understand correctly, then I need to create an Event for "send-to-device-success" in GA4, and then I can mark it as a Conversion. I'll check back when I can confirm that data is showing up.

**Comment by a-kyne** [comment]
@alexgibson Is there a list of conversion Events somewhere? I think I've got Ff download covered now, but VPN appears to have a thank-you page on subscriptions.mozilla.com and there is a download page on vpn.mozilla.org that has some sort of button interaction. Are there Events for those? How about for Monitor and Relay?

**Comment by alexgibson** [comment]
@a-kyne I think both subscriptions.mozilla.com and vpn.mozilla.org have separate GA implementations that live outside of bedrock. They are separate sub domains, so will likely have event set up for each of their respective properties in GA. Unortunately I don't think I have acces to see either of them :/

**Comment by a-kyne** [comment]
@alexgibson But surely we have events for when we send visitors to them? There are buttons on .../products/vpn/, for example.

**Comment by alexgibson** [comment]
@a-kyne can you provide links / examples for where you mean?

**Comment by a-kyne** [comment]
https://subscriptions.firefox.com/products/prod_...... and [https://vpn.mozilla.org/vpn/download?](https://vpn.mozilla.org/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download&email=akyne%40mozilla.com)

**Comment by maureenlholland** [comment]
@a-kyne is the send-to-device-success event working as you'd like? Do you need a send-to-device-failure event or should I close this issue as resolved?

**Comment by a-kyne** [comment]
@maureenlholland The event doesn't seem to be triggering in GA4. I set up an Event where "event_name = send-to-device-success" and it's not firing. I'm not sure why. Any suggestions?

**Comment by maureenlholland** [comment]
@a-kyne have we got this working through GA4 now? I'll close this issue out if so.

**Comment by a-kyne** [comment]
Yes, we now have thousands of "send_to_device_success" being recorded. Thank you for your help!
