### ISSUE TITLE
[Epic] SEM Landing pages for mobile products

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11629]
## Description

We need landing pages for our mobile products that are optimized for paid search.

Guidance:
- Super simple. Logo. Text. Image. App Store Links
- Remove everything else. No navigation. No footer. (we may need a minimal footer for legal purposes)

Nice to have:
- Platform detection that will detect if the user is on android or iOS and only show the app store link for that platform.

---

#### Issues
- [x] #11630
- [x] #11631
- [x] #11632

Rough sketch:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/2030656/168397148-fcd896ab-91b2-4e38-93e0-6ba8f4761229.png">

**Comment by ehot** [comment]
![Firefox - SEM - Full](https://user-images.githubusercontent.com/2040610/169409400-b02169d0-e2b1-4087-8616-c054f8b479d1.png)
![Firefox - SEM - mobile](https://user-images.githubusercontent.com/2040610/169409402-d4d6ce85-6ed2-4742-8ec6-e58529aabef8.png)
![Pocket - SEM - Full](https://user-images.githubusercontent.com/2040610/169409403-5807d70a-ed29-4531-b890-044514aa02b3.png)
![Pocket - SEM - mobile](https://user-images.githubusercontent.com/2040610/169409404-b4b52fc8-6397-48bb-832d-9fe908b7b9ea.png)
![VPN - SEM - Full](https://user-images.githubusercontent.com/2040610/169409405-4697a27a-33f2-4fe1-8da3-d981e2811ca7.png)
![VPN - SEM - mobile](https://user-images.githubusercontent.com/2040610/169409407-c119bb1f-6309-48fa-9204-511db9ef52cc.png)

**Comment by slightlyoffbeat** [comment]
Thanks @ehot!

Lets use the minimal footer from here so that we still have our privacy policy, cookie, and legal links.

Links: We will start to use `/landing` for this type of content.

`/landing/vpn-mobile`
`/landing/firefox-mobile`
`/landing/pocket-mobile`

`/landing` can just redirect to `/landing/firefox-mobile`

**Comment by slightlyoffbeat** [comment]
@nathan-barrett I'd like to default to this behavior:
- if iOS, only show app Store button
- if Android only show Google Play Button
- if cannot neither or cannot detect, show both

We believe this is all allowed, but there's a risk that we may run into approval issues if our page changes by platform. If that is the case, we will need to remove detection and just show both buttons at all times.

Elise can provide image assets.

- Copy will be provided soon
- Adjust links will be provided soon.

**Comment by nathan-barrett** [comment]
@slightlyoffbeat do we know who we should talk with about approving the page changes by platform?

**Comment by slightlyoffbeat** [comment]
Firefox copy:

------

### Go your own way with Firefox mobile

Firefox mobile adapts to you and makes it easier than ever to see all your open tabs, past searches, and favorite sites.

**Comment by slightlyoffbeat** [comment]
VPN Copy:

------

### Secure your privacy on mobile with Mozilla VPN

Protect your smartphone and tablet with a VPN from Mozilla, the trusted pioneer in internet privacy.

**Comment by nathan-barrett** [comment]
First pass at these designs are up on demo/4: 
[Firefox](https://www-demo4.allizom.org/en-US/landing/firefox/)
[VPN](https://www-demo4.allizom.org/en-US/landing/vpn/)
[Pocket](https://www-demo4.allizom.org/en-US/landing/firefox/)

**Comment by alexgibson** [comment]
Are all of these pages done? If so, can we close this epic and the dependant issues?

**Comment by alexgibson** [comment]
Closing this as it looks like this is done. Feel free to reopen if not
