### ISSUE TITLE
VPN Mobile SEM Page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11631]
Part of epic #11629 

This is for a simple VPN Mobile SEM Page

See epic for additional details.

Copy: TBD.
Visuals: TBD
Adjust links: to be provided by Lauren.

Requirements:
- [ ] Platform detection. Only show apple or android play store button depending on if user is on ios or android
- [ ] Simple events tracking to track clicks and be able to attribute to this specific page.

**Comment by slightlyoffbeat** [comment]
Design: Elise will work on the week of the 17th

Copy: TBD, but will likely borrow from existing copy. @slightlyoffbeat will be the contact for this

Links: Lauren from activation team will provide adjust links

**Comment by alexgibson** [comment]
Closing this as it looks like this is done. Feel free to reopen if not
