### ISSUE TITLE
MDN+ focused WNP for Developer Edition

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11633]
## Description

We would like to create an MDN+ focused WNP that will show to anyone running developer edition.

Target is Firefox 101.

Design & Copy: lets borrow heavily from the MDN+ page. I marked up the MDN+ page to show an example of layout. Our UX Designer can use this as a reference point to create a final design.

CTA for all links: https://developer.mozilla.org/en-US/plus (with proper UTM parameters)

---

Reference Image:
![Screenshot 2022-05-13 at 15-53-22 MDN Plus](https://user-images.githubusercontent.com/2030656/168399311-de9da4af-120c-4460-975f-788909c9418d.png)

**Comment by ehot** [comment]
![MDM - What's New Page - Basic](https://user-images.githubusercontent.com/2040610/169615604-ff8af18b-955c-42ab-b239-281e826a29e2.png)
![MDM - What's New Page - CTA](https://user-images.githubusercontent.com/2040610/169615605-739cb9b7-58af-48da-979a-daeebde07d9a.png)
![MDM - What's New Page - Info](https://user-images.githubusercontent.com/2040610/169615607-bfa988e3-33ea-46db-a845-268e4b8c0d9f.png)

**Comment by ehot** [comment]
![MDM - What's New Page - Info](https://user-images.githubusercontent.com/2040610/169895888-72ddcea0-1c62-4d35-a139-c17fe26cff9c.png)

**Comment by ehot** [comment]
Final:
![MDM - What's New Page - Info](https://user-images.githubusercontent.com/2040610/169901627-8827439c-2938-4868-af7a-4ff4dfb2a6b4.png)
