### ISSUE TITLE
www-sitemap-generator is not working

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11642]
## Description

Sitemap generation is currently broken, so it does note get updated.

eg https://gitlab.com/mozmeao/www-sitemap-generator/-/pipelines/540069788

Generation is tripping up on `/<locale>/privacy/firefox-lite/` including `en-US`

---

#### Success Criteria
- [ ] Sitemap generation is working again

**Comment by stevejalim** [comment]
@pmac I'm wonderining if https://github.com/mozilla/legal-docs/pull/1738 is related, but it got merged so long ago that I'd expect us to have seen this long before Friday

**Comment by pmac** [comment]
it is indeed related, but the changes don't affect prod until they're moved to the `prod` branch there. I've been looking at this today, and it seems that when bedrock has `DEBUG=False` that what should be 404 responses don't result in the URL being skipped during the creation of `sitemap.json`. I'm about to file a PR for bedrock to remove the firefox-lite URLs and fix this, but that is strange as well. When I run `manage.py update_sitemaps` locally with `DEBUG=True` it correctly skips those URLs.

**Comment by stevejalim** [comment]
> but the changes don't affect prod until they're moved to the prod branch there. 

Ah, yeah, of course - `main`/`master` in legal docs isn't what gets used in production. Nice one 🕵️ 

As for the 404s/non-404s locally - that is strange... Will have a think
