### ISSUE TITLE
Migrate Mozilla VPN download page to bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11659]
## Description

The product team would like the VPN download page to move to bedrock.

Implementation details are being ironed out in https://mozilla-hub.atlassian.net/browse/PSP-400

---

#### Success Criteria
- [x] Download page is migrated to bedrock.
- [x] Download goals are set up in GA.
- [x] Downloads are blocked in countries specified by legal
- [x] Strings are ready for L10n.
- [x] GA events / goals are in place.

**Comment by alexgibson** [comment]
I think it makes sense to also tackle https://github.com/mozilla/bedrock/issues/11471 as part of this work.

**Comment by alexgibson** [comment]
Think I have enough to get started on this whilst the finer details are figured out.

**Comment by alexgibson** [comment]
Demo page: https://www-demo1.allizom.org/en-US/products/vpn/download/

Still need to figure out:

- Any attribution specific details we need.
- Localisation / rollout plan.

**Comment by alexgibson** [comment]
Added some download goals in GA for www-demo1 and verified they appear as expected in the real-time dashboard. Will have to copy over to prod closer to the time when we're ready:

![image](https://user-images.githubusercontent.com/400117/169503477-a50d2f5d-dafe-490a-ac8b-a0b73362493e.png)

**Comment by alexgibson** [comment]
Migration of the page template / design is pretty much done. I still need to sync up with Sarah to figure out attribution requirements, and to make sure we have a roll out / transition plan.

**Comment by alexgibson** [comment]
@slightlyoffbeat this is now ready for review https://www-demo1.allizom.org/en-US/products/vpn/download/

It's pretty much a straight port of the existing page. I'm sure there are things we can improve here over time, but for now does this look OK to you? If so, I'll move forward with code review / L10n.

Thanks

**Comment by slightlyoffbeat** [comment]
@alexgibson reviewed and this looks good.

We should add `vpn.mozilla.org/products/download` to our to-do list post launch.

**Comment by alexgibson** [comment]
Thanks @slightlyoffbeat, Sarah is going to take care of deprecating the older guardian download page, just as soon as locales have had a chance to catch up with translations.
