### ISSUE TITLE
Consistent markup for Pocket subdomain links

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11666]
## Description

We need to decide if we want Pocket subdomain links like `help.getpocket` to open automatically in a new tab and have `target="_blank" rel="external noopener"` attributes.

Currently, our implementation is mixed, see:
New tab: https://github.com/mozilla/bedrock/blob/main/bedrock/pocket/templates/pocket/add.html#L31
Same tab: https://github.com/mozilla/bedrock/blob/main/bedrock/pocket/templates/pocket/includes/platform-nav.html#L19

To consider:
- what is the most accessible, most expected UX?
- are there SEO implications?

Worth noting:
SUMO links on mozorg do not open in a new tab
Pocket currently links to support in a new tab (https://getpocket.com/add/?ep=1)

---

#### Success Criteria
- [x] Decision is made
- [x] All instances of Pocket subdomains in bedrock adhere to this practice

**Comment by alexgibson** [comment]
I vote for removing `target=_blank` for support links. If someone is having a technical issue, then they likely won't convert (e.g. sign up / in) right there and then anyways.

There are also accessibility downsides to surprising people by opening links in new tabs, without first announcing what will happen when someone clicks a link. I'm not aware of any SEO implications from using these attributes (or not).
