### ISSUE TITLE
Update Mozilla homepage masthead with '10 years of Pocket'

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11716]
## Description

The mozilla homepage will be updated for "10 years of Pocket"

This is for US_EN only

[Figma file.](https://www.figma.com/file/nbtCgmjXpY8YUxFy3E01dS/Pocket-Is-For-You?node-id=631%3A1036)

Image for reference:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/2030656/171962561-8844ecd2-7f22-4b8e-b665-7323059cabe9.png">

Signup link should link to `getpocket.com/signup' with appropriate UTM parameters.

---

#### Success Criteria
- [x] Homepage masthead changes from Fx100 to Pocket 10 year for English
- [x] Any other language that has fx100 masthead should revert to the firefox mobile color promo

**Comment by alexgibson** [comment]
@slightlyoffbeat this is up on demo1 for review:

https://www-demo1.allizom.org/en-US/

**Comment by slightlyoffbeat** [comment]
@alexgibson Reviewed and it looks good to me. Also got a thumbs up from design and copy.

**Comment by alexgibson** [comment]
This is now in prod: https://www.mozilla.org/en-US/
