### ISSUE TITLE
Typo in Fx v Chrome page

### ISSUE THREAD

**Issue by plwt** [mozilla/bedrock#11736]
## Description

At https://www.mozilla.org/en-GB/firefox/browsers/compare/chrome/, there is typo under the "Portability" highlights:- page uses "Synchrnoises", instead of "Synchronises" (for en-GB).

### Steps to reproduce

Open https://www.mozilla.org/en-GB/firefox/browsers/compare/chrome/ (see image for location in page)

![Screenshot 2022-06-07 at 19-14-52 Firefox vs  Chrome Which is better](https://user-images.githubusercontent.com/31939113/172453828-7b7e654a-0d56-493a-8ec2-ac6e12499355.png)

### Environment

Fx 102.0b4 (current Dev Edition), Debian 11 Xfce

**Comment by craigcook** [comment]
Fixed!
