### ISSUE TITLE
[mozilla.org] Remove obsolete locales disabled on Pontoon

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#11739]
## Description

In a recent locale comparison check, we identified these disabled locales on Pontoon because of inactive communities. They should be removed from the GitHub repo as well. Here is the locale list:
`hto`, `nv`, `pai`, `pbb`, `ppl`, `qvi`, `sw`, `zu`

### Expected result

After the removal of the above stated locales, the GitHub repo and Pontoon are in sync.

**Comment by stevejalim** [comment]
@peiying2 Thanks - am doing this now. 

Please note that `ppl` isn't currenlty in the Pontoon config in bedrock:

https://github.com/mozilla/bedrock/blob/main/l10n/configs/pontoon.toml#L74-L82

**Comment by stevejalim** [comment]
Was it meant to be just `pl` @peiying2 ?

**Comment by stevejalim** [comment]
PR is here if you wish to review it https://github.com/mozilla/bedrock/pull/11745
