### ISSUE TITLE
Input field stacks on top of other elements when Relay extension is enabled

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#11765]
## Description
When [Relay extension](https://relay.firefox.com/) is enabled on a Firefox browser, the input field seems to sstack on top of other elements. 
For example, if the input field is close to the https://mozilla.org top navigation, when a user hovers over one of the list items that opens a menu of items, the input field stacks on top of the menu rather than remaining "under" the hovered stacked element.

### Steps to reproduce
1. Open a Firefox browser that has Relay enabled
2. Go to https://www.mozilla.org/en-US/newsletter/recovery/
3. Hover over one of the top navigation items and see the list of items it brings up

### Expected result
Input field to remain behind the menu appearing on hover
### Actual result
The input field stacked on top of the menu appearing on hover
<img width="724" alt="Screen Shot 2022-06-13 at 3 42 36 PM" src="https://user-images.githubusercontent.com/42309026/173287371-ddadb31e-158a-46bf-aea5-488669dedeee.png">

### Environment
Firefox browsers with Relay extension enabled. I tested this on:
- Firefox (regular)
- Firefox Developer
- Firefox Nightly

**Comment by alexgibson** [comment]
This should probably be a bug over at https://github.com/mozilla/fx-private-relay

**Comment by reemhamz** [comment]
Good call, I'll get on that soon 👍🏼

**Comment by reemhamz** [comment]
Migrated this issue over to https://github.com/mozilla/fx-private-relay/issues/2075
