### ISSUE TITLE
[l10n] Download page has missing items when the browser / system language is set to Finnish (suomi)

### ISSUE THREAD

**Issue by biancahidecuti** [mozilla/bedrock#11769]
### Prerequisites:
- Have the system language / browser language set to Finnish (suomi);
- Be on [Download page](https://www-dev.allizom.org/fi/products/vpn/download/);

### Steps to reproduce
1. Hover over each option from the menu bar displayed at the top of the Download page;
2. Observe the content of each sub-menu;
3. Observe the section displayed under the header;
4. Observe the content of the page;

### Expected result
- For step 2: Every item from every sub-menu has a description displayed under it;
- For step 3: The following are displayed under the header:
    - "Mozilla VPN" link, placed on the left side of the page 
    - "Subscribe to Mozilla VPN" link, placed on the right side of the page 
    - "Get help" link, placed on the right side of the page.
- For step 4: The content of the page is fully displayed in Finnish (suomi);

### Actual result
- For step 2: The following items are missing their description: 
    - “Release notes” from “Firefox Browsers” sub-menu;
    - “Facebook Container” / “Product Promise” / “Firefox Relay” / “Firefox Private Network (beta)” / “MDN Plus” from “Products” sub-menu;
    - “Mozilla Manifesto” / “Leadership” / “Mozilla Blog” from “Who We Are” sub-menu;
- For step 3: The following are NOT displayed under the header: 
    - "Mozilla VPN" link, placed on the left side of the page 
    - "Subscribe to Mozilla VPN" link, placed on the right side of the page 
    - "Get help" link, placed on the right side of the page.
- For step 4: The content of the page is not fully displayed in Finnish, as the sub-menus are displayed in both Finnish and English; the platforms section is displayed only in English and the disclaimer placed above the footer is displayed in English. 

Notes:
- Not reproducing for the rest of the locales (DE/NL/FR/ES/IT/), including Swedish, which was part of the same Wave/expansion;
- See the attached screenshots;

### Affected versions:
- Guardian v1.25.b.6;

### Affected Browsers:
- All;

<img width="1748" alt="Näyttökuva 2022-6-14 kello 15 44 39" src="https://user-images.githubusercontent.com/95906750/173586135-5eef1e44-6c93-459e-974c-946fc4f1dd40.png">
<img width="929" alt="Näyttökuva 2022-6-14 kello 15 50 19" src="https://user-images.githubusercontent.com/95906750/173586183-3e0d1066-12a9-4c8d-9580-9fdaae67c576.png">

**Comment by alexgibson** [comment]
@biancahidecuti note that all locales are enabled by default on www-dev.allizom.org. This is so that localizers can preview their work as they provide translation. So you can expect to see some mixed language content like above. I don't think that constitutes a bug.

Please file L10n bugs against testing on production, rather than the dev server. 

Note that: https://www.mozilla.org/fi/products/vpn/download/ is not yet active in production (because it has not yet met the translation threshold).

Thank you
