### ISSUE TITLE
Refresh the contribute page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11760]
## Description

There has been a request from the community team to refresh the community page.

[Brief]([a brief about updating the Contribute page](https://docs.google.com/document/d/1fOeQCZhPJOlS1WzMhiaXs433dpU3U2qAKfPFnytOc8g/edit#) t)

---

**Comment by slightlyoffbeat** [comment]
Rough sketch that outlines the community team vision for this page: 
https://drive.google.com/file/d/18Ea-pSk3oclUQ3WXAIPWegpOzuUhY_LS/view?usp=sharing
https://drive.google.com/file/d/18EbEFgkBhJOZNXoL9W9x2YKVkE9C0qVg/view?usp=sharing

**Comment by slightlyoffbeat** [comment]
Early mock from UX:
![Contribute-v2-6-9-2022](https://user-images.githubusercontent.com/2030656/173156748-138fcf41-8cb8-421c-860a-841629b24fbb.png)

**Comment by audrey-kho** [comment]
Hello! I'm new to the open source community and was hoping to take this issue on if it hasn't been resolved yet. Please let me know if this would be a good place to start. Thank you! :)

**Comment by alexgibson** [comment]
@slightlyoffbeat was this one done? (the mockup looks similar but not the same to the version in prod)

**Comment by slightlyoffbeat** [comment]
This can be closed for now
