### ISSUE TITLE
Pocket mode: Footer displays wrong year 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11779]
## Description

Cross-posting from https://github.com/mozmeao/pocket-marketing-pages/issues/54 - we need to make the copyright year dynamic:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2030656/173156928-dcd09642-344a-4f1a-be07-0074e82ea73f.png">

---

#### Success Criteria
- [ ] Footer copyright year is everygreen

**Comment by itachi9604** [comment]
hi @stevejalim , The link is not accessible, it shows 404.

**Comment by stevejalim** [comment]
@itachi9604 Yeah it looks like that's currently a restricted-access repo. However, I just tried to replicate with Bedrock in Pocket Mode (which isn't yet used on production) and I've seen we have updated the date to 2022, so am going to close this one for now. Thanks for looking!
