### ISSUE TITLE
Epic: VPN / Relay bundle offer

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11781]
## Description

The Privacy and Security team would like to begin offering VPN subscribers the chance to opt into adding in Relay to their subscription as a bundle. Specific details on pricing / country / language offerings are still being worked out, but the idea is that we would show an "Add Relay" option to the [VPN subscription offers](https://www.mozilla.org/en-US/products/vpn/#pricing).

- Mana page: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=169411025
- Jira issue: https://mozilla-hub.atlassian.net/browse/VPN-2642

**Comment by slightlyoffbeat** [comment]
Possible dupe, or related: https://github.com/mozilla/bedrock/issues/11982

**Comment by alexgibson** [comment]
Production product ID: prod_MIex7Q079igFZJ
Production plan ID: price_1La3d7JNcmPzuWtRn0cg2EyH

Figma file: https://www.figma.com/file/vje77igIFc5wnW4lkP5thl/VPN-Bundle-Touchpoints?node-id=354%3A4679

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/12156
