### ISSUE TITLE
Devedition What's New page pegs CPU

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/bedrock#11793]
## Description

High CPU on https://www.mozilla.org/en-US/firefox/102.0a2/whatsnew/?oldversion=101.0

I filed https://bugzilla.mozilla.org/1775033 to get investigation on the root cause.

I am filing this bug for a short term solution on the website side.

Thanks

**Comment by alexgibson** [comment]
@pascalchevrel here's a demo page with the suggestion SVG change. Can you verify if this helps at all with whoever reported the issue? I can't seem to replicate the high CPU on my machine. Thanks

https://www-demo1.allizom.org/en-US/firefox/102.0a2/whatsnew/?oldversion=101.0

**Comment by pascalchevrel** [comment]
There is a small improvement, with the page on production all my cores are at 50-60%, with the page on demo1 it's more like 40-50%. Still very high.

**Comment by alexgibson** [comment]
A small improvement is better than nothing I guess. I’m kinda reluctant to start defeating the actual design / animation. Hopefully this can be improved in Firefox.

**Comment by alexgibson** [comment]
Also curious is this is also an issue on https://developer.mozilla.org/en-US/plus, and if anyone has reported a similar problem

**Comment by pascalchevrel** [comment]
> Also curious is this is also an issue on https://developer.mozilla.org/en-US/plus, and if anyone has reported a similar problem

Yes, t he MDN page also causes the same constant high CPU use for me.

**Comment by alexgibson** [comment]
I think at this point we should move forward with the small optimisation suggested in the bugzilla bug. I took a look at open issues for kuma/yari, but I don't see any similar type bugs reported.
