### ISSUE TITLE
Upgrade to Customizable Compose Content Model  

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11810]
We installed Compose in 2021. This is now considered "legacy Compose". The new model has been available since April 2022.

Version differences
https://www.contentful.com/help/compose-content-model-versions/

Upgrade guide
https://www.contentful.com/developers/docs/compose/upgrade-to-customizable-compose-content-model

It sounds likely they will phase out "legacy Compose" over time and we haven't used it extensively*, so it would be an ideal time to switch if we want to do so. The bigger question is, do we trust the stability of this new Compose model?

(*we are using them in production with VPN Resource Center)

From Contentful

> Is upgrading required?

> Compose supports both legacy and customizable content models.

> Upgrading to the customizable Compose content model is totally optional. You can continue working with the legacy Compose content model if you prefer.

> However, some future improvements for Compose may only be supported by the customizable content model due to technical reasons. Also, installing the legacy Compose content model in a newly added space is not supported.

> In case support for the legacy Compose content model will be phased out in the future, we will give you enough time and tooling support to make the upgrade as frictionless as possible. 

**UPDATE 27/06/2022:** After discussion, we are happy with the Compose App functionality and want to be compatible with any future additions, so will upgrade to new Compose model. The demo sandbox `sandbox-compose-migration` simply archived existing Compose pages, removed the Compose page model validation, and created new Compose page types through the Compose UI. The actual migration should follow the official upgrade steps linked above and checklisted below.

IN NEW SANDBOX
- [ ] Duplicate the fields from the “Compose: Page” content type to the page type content type
- [ ] Add the “Aggregate Root” annotation to the page type (This can be done in [Compose UI](https://www.contentful.com/help/set-up-page-types-in-compose/) or with [Contentful API](https://www.contentful.com/developers/docs/references/content-management-api/#assigning-annotations))
- [ ] Activate the page type
- [ ] Copy content from “Compose: Page” into duplicated fields of the page type
- [ ] Delete “Compose: Page” entries (any published entries will need to be unpublished first)
- [ ] Delete “Compose: Page” content type

IN BEDROCK
- [ ] Check existing legacy Compose page API code still functions as expected with new model Compose pages. Update as needed.
- [ ] Review and if necessary refactor `update_contentful` management command
   - [ ] Update importer to import the newer/alternative page type
   - [ ] After migration: drop explicit support for `Compose: Page` entries in the importer 

NOT APPLICABLE

On all content types except "Compose: Page"
- ~Replace “Composition relationship” setting with an “Aggregate Component” annotation~ (No reference fields have the "Composition relationship" checkbox checked.)
- ~Replace validations that restrict linking to “Compose: Page”~ (No reference fields restrict linking like this)

On all content entries except type "Compose: Page"
- ~Update references linking to a “Compose: Page” entry`~ (No entries link to a Compose page)

**Comment by stevejalim** [comment]
Thanks for laying this out so well @maureenlholland 💯 I'll take a look at it and do as much as I can to get us moved over.
