### ISSUE TITLE
Implement VPN Coupon Promo

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11826]
## Description

We have 2500 coupons available to test how much more likely a user is to sign up when a coupon is available.

We will set up a banner on the VPN landing page and implement a split tet. 50% of traffic goes to control (current page as-is). Other 50% will see a banner offering a coupon for 20% off our 12 month plan.

## Details

**Test Approach:** 50% Traffic split (tbd based on Website teams recommendation)
- Version A - Banner with 20% Coupon with travel message + CTA
- Version B - Banner with no coupon with travel message + CTA

**Page:** `/products/vpn/`

**Markets**
- Germany
- France
- UK
- USA
- Canada

Requirements:
- Let users copy pasts the coupon code texts (VPN20)
- The CTA should bring users to the 3 price tiles
- Sticky banner when scrolling down would be highly recommended from a marketing perspective
- Launch Date: 7/7 (tbd based on Website team’s availability)
- Run Time: 7 Days max.
- A switch to quickly and easily turn off, and default all traffic back to not seeing a banner

---

Links to Key Docs:
- [Figma Files](https://www.figma.com/file/prb7n2K4njq7k5sLwBFoJv/EU_VPN-Ads)
- [copy doc](https://docs.google.com/document/d/1DALl95Id_AcHl389sRlLtqhgJ3nSCZprNfDTc9YZ6Vk/edit)
- [GTM/Brief](https://docs.google.com/document/d/1elG_2PcHh0hl9b81X5LcdTlF7Ermy7mBwNIoxzj63Uo/edit#)

**Comment by cadeyrn** [comment]
Can you please update the German translation?

"Nutze jetzt den code" has to be "Nutze jetzt den Code" (uppercase "C")
"beim checkout" has to be "beim Checkout" (uppercase "C")

It's wrong to write everything lowercase in German. Thanks!

**Comment by alexgibson** [comment]
Thanks for the report here @cadeyrn, I'll get someone to take a look at your comments / suggestions

**Comment by alexgibson** [comment]
For posterity, the redirect in this experiment was mis-configured and causes errors in the CJMS affiliate attribution flow. I'm writing up what happened in https://github.com/mozilla/bedrock/issues/11998
