### ISSUE TITLE
500 on /es-ES/firefox/retention/thank-you/

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11846]
## Description

Sentry is flagging a 500 on /es-ES/firefox/retention/thank-you/ and it also appear to happen for other locales (eg `en-US`)

`Reverse for 'firefox.set-as-default.landing' not found. 'firefox.set-as-default.landing' is not a valid view function or pattern name.`

https://sentry.io/organizations/mozilla/issues/3353178437/

---

#### Success Criteria
- [ ] The page no longer 500s 
OR
- [ ] If that page genuinely should not exist, links to it have been removed

**Comment by alexgibson** [comment]
Looks like it was renamed to `firefox.set-as-default` in https://github.com/mozilla/bedrock/pull/11774/
