### ISSUE TITLE
Improve Mozilla VPN download page

### ISSUE THREAD

**Issue by brizental** [mozilla/bedrock#11875]
## Description

This is the page I mean: https://www-dev.allizom.org/en-US/products/vpn/download/

Currently, only Linux has some sort of installation instruction. When the users clicks on the "Download" button for that platform, they are redirected to a SUMO page with instructions. It is not clear right now if that is the experience we want when we add instructions for all other platforms, I have not yet consulted design about this change, but the extra click and redirect feels suboptimal.

This task should include:

- [ ] Design to define the layout and experience for adding the instructions information.
- [ ] Support to write the instructions for each platform.
- [ ] Engineering to implement the changes.

---

#### Success Criteria

- [ ] Approved design attached to this issue
- [ ] Approved texts attached to this issue
- [ ] Implementation of the new layouts

**Comment by slightlyoffbeat** [comment]
Jira ticket: https://mozilla-hub.atlassian.net/browse/VPN-2525?focusedCommentId=574322&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-574322

**Comment by reemhamz** [comment]
We're finally tackling this ticket, and the task has started. 
To update, here is the Figma design I'll be following: https://www.figma.com/file/FjeA0eZw4GIxBAlQfz06c1/VPN-Download-page-%255B%252B-Archived-Landing-page%255D?node-id=2608-7141&t=t2u25N2eTn0JS30T-0&fuid=1005135947042770759

**Comment by alexgibson** [comment]
Closed by https://github.com/mozilla/bedrock/pull/12980
