### ISSUE TITLE
Pocket migration - update homepage in bedrock

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11917]
## Description

Comparing the Pocket homepage currently supported by Bedrock with the one currently in production on Netlify, they no longer match. ie, https://dev.tekcopteg.com/en/ is stale compared to  https://getpocket.com/en/
 
I don't recall the history of the Pocket homepage work, and it might be we have that version waiting in the wings - or not. 

So, we may well need to update the one in Bedrock to keep up ahead of the switch-over, _but_ we should also check if there's another homepage change about to happen, to avoid further rework. If a newer design is about to land with Pocket, that newer one is the one to port, I think.
 
---

#### Success Criteria
- [ ] Confirmed with Pocket team whether a new-new homepage is coming or if we can port the current live one - @stevejalim 
- [ ] The homepage in Bedrock Pocket matches the current homepage in Pocket production/Netlify

**Comment by stevejalim** [comment]
Yeah have updated the description

**Comment by alexgibson** [comment]
@stevejalim I'm still not quite clear on what the difference is. Both look the same to me at a glance, but I may be missing or blind to something obvious.

**Comment by alexgibson** [comment]
@stevejalim I believe that's the old home page design, not something new
