### ISSUE TITLE
Edge's "shopping feature" suggests a coupon when downloading Firefox

### ISSUE THREAD

**Issue by willdurand** [mozilla/bedrock#11925]
## Description

Edge's shopping feature seems to propose coupons for Mozilla (`MOZILLA20`). @alexgibson found out that it could be a coupon for Mozilla VPN. It doesn't look great, though, because Edge does not mention VPN and we shouldn't have such a coupon when downloading a free product like Firefox.

### Steps to reproduce

I went to www to download Firefox (from AMO but that isn't relevant I think)

### Expected result

No coupon for a free product?

### Actual result

Edge's shopping feature offered me a coupon:

<img width="1392" alt="Screenshot 2022-07-15 at 10 24 29" src="https://user-images.githubusercontent.com/217628/179187207-be8c526f-49e6-49df-ba48-5244e4c4f7ab.png">

### Environment

Windows 10 / Edgium 103.0.1264.49 (Official build) (64-bit)

**Comment by alexgibson** [comment]
Passed this bug over to our marketing / affiliate folks to take a look at. Thanks for filing!
