### ISSUE TITLE
GCP demo deployments should ping Slack upon success or failure

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11920]
## Description

Given that the entire Marketing Webites team does not have Google Cloud Platform acccess, we can't all see the progress or logs from our demo services. We should do something to improve visibility of demo rollout

---

#### Success Criteria
- [x] Successful deploys ping the `www-notify` channel, for both Mozorg Mode and Pocket Mode
- [ ] Build/deployment errors should ping the `www-notify` channel, for both Mozorg Mode and Pocket Mode

**Comment by alexgibson** [comment]
Possibly related https://github.com/mozilla/bedrock/issues/11392

**Comment by stevejalim** [comment]
Thanks @alexgibson - I'll make sure #11392 gets some better visibility on the backend board, but the code for this one won't transplant into main Bedrock. We could, though, use the same (new) Slack App's webhook when we resurrect the original notifications

**Comment by stevejalim** [comment]
This is done, using the older Slack webhook for now. Once I get the 👍 from the relevant people, I'll still probably make a standalone Slack App to be the webhook for this one, because that might let us do a bit more with the limited data we get (eg look up the branch name from the UUID we get in the notification, etc),
Closing and will spin up a new ticket for that
