### ISSUE TITLE
Automatically update list of demo server use

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11927]
## Description

At the moment, we manually curate a list on wiki.m.o of who is using what demo server. It would be good if we can keep this up to date automatically, based on successful demo builds, to reduce the risk of stepping on each other's toes.

This could be a Google Sheet, for instance, which we'd link to from the exisiting wiki page.

---

#### Success Criteria
- [ ] An automatically updated doc exists showing:
  - [ ] When a demo site was last pushed to
  - [ ] By whom
  - [ ] With what commit

**Comment by robhudson** [comment]
Looking at the already-in-use https://whatsdeployed.io/s/RuO/mozilla/bedrock, I wonder if it could be as simple as adding extra rows for each demo. That would give all the data except "by whom", which is only a click of the SHA away.

**Comment by alexgibson** [comment]
I like this idea ^ 👍

**Comment by alexgibson** [comment]
@stevejalim is this one still relevant now we've migrated demos to GCP?

**Comment by stevejalim** [comment]
This is working as best we can - the demo page in the wiki shows links to the sha of the code deployed to each
