### ISSUE TITLE
Pocket-mode deploys not working for stage or dev

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11938]
This popped up in Sentry, and it looks like Pocket Mode isn't working as we expect on Stage

https://sentry.io/organizations/mozilla/issues/3436814558/

Update: or dev, or test

It's not the DNS/domain level, either - these origin servers all 500

https://bedrock-pocket-dev.gcp.moz.works/
https://bedrock-pocket-stage.gcp.moz.works/
https://bedrock-pocket-test.gcp.moz.works/

but https://bedrock-pocket-prod.gcp.moz.works/ _does_ handle Pocket mode fine

I wonder what regressed...

**Comment by robhudson** [comment]
It’s because the new l10n code is catching an unsupported locale and wanting to render the locale selection 404 page which includes the bedrock header with links to `mozorg.home`, which pocket mode doesn’t have.

**Comment by stevejalim** [comment]
@robhudson Ah, great catch. I guess we could only apply that locale-404 logic if `settings.IS_MOZORG_MODE` is `True`. Given we won't be hosting all the pages for Pocket, I doubt it's worth us supporting locale-404 for Pocket, yeah?

**Comment by stevejalim** [comment]
Mind if I pop this one over to you, Rob? I don't think i'll get to it before PTO

**Comment by stevejalim** [comment]
Ah, looks like it's because the fix from #11939 hasn't been [auto-]deployed to Dev yet: https://whatsdeployed.io/s/RuO/mozilla/bedrock

**Comment by stevejalim** [comment]
Working after the rollback of the locale rejig, but was also working BEFORE the rollback because the fix was on point ⭐
