### ISSUE TITLE
Instagram link in footer is 404 for /de/ locale

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11953]
## Description

The Mozilla Instagram icon/link in the main footer is 404 for /de/

### Steps to reproduce

1. Open https://www.mozilla.org/de/
2. Scroll to the footer
3. Click the Instagram icon "@Mozilla folgen"

### Expected result

It should load the Mozilla Instagram German feed.

### Actual result

404 page not found: https://www.instagram.com/unfcktheinternet/

### Environment

N/A

**Comment by reemhamz** [comment]
My guess is just to have it link to Mozilla's main instagram page. @slightlyoffbeat thoughts?

**Comment by alexgibson** [comment]
I checked with Leoine on the EU team and the new name for the German Instagram account is https://www.instagram.com/mozilla_deutschland/
