### ISSUE TITLE
[July 26] Enable Firefox taskbar message on /thanks/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11952]
## Description

When Firefox 103 releases on July 26, we need to enable the taskbar message which was added to the /thanks/ page in https://github.com/mozilla/bedrock/issues/11759.

The switch is called `SWITCH_FIREFOX_103_TASKBAR_MESSAGE`

---

#### Success Criteria
- [ ] Switch is enable on stage / prod on July 26th.

**Comment by alexgibson** [comment]
PR to merge on above date: https://github.com/mozmeao/www-config/pull/474

**Comment by maureenlholland** [comment]
closed with switch merge July 26
