### ISSUE TITLE
Text and link in the comparision box don't match

### ISSUE THREAD

**Issue by lime124** [mozilla/bedrock#11975]
## Description

At the bottom of the mobile browsers page, there is a box that tells people they can read more about firefox compared to other browsers. The text in the box refers to desktop though the compare link goes to a page comparing mobile browsers. Additionally there is a much less visually prominent chunk of text to the left of the box that also talks about comparing mobile browsers. Thanks!

### Steps to reproduce
1. go to https://www.mozilla.org/en-US/firefox/browsers/mobile/
2. scroll to the bottom and observe

<img width="1552" alt="Screen Shot 2022-07-27 at 8 46 25 AM" src="https://user-images.githubusercontent.com/287322/181291351-e3b80ed3-e25a-4612-883b-378db5bff620.png">

### Expected result
I would love to see the "desktop" word in the comparison box updated to say mobile and then remove the redundant  block of text on the left. I think the comparison box is more visually prominent whereas the block of text on the left matches the same visual layout as the products making it easy to scan over and miss.  I believe references to desktop should be removed from the page because the primary goal of the page is to highlight the benefits of our mobile browsers as folks decide if Firefox mobile is the right choice for them. 

Ultimately this is up to your design team to decide how to handle this but at very least the text in the compare box should match  wherever the compare link goes. e.g text says compare desktop browsers, link goes to desktop comparison page.

### Actual result

I click on compare link in the desktop comparison box and i see a chart comparing mobile browsers.

### Environment

What browser and operating system are you using?

**Comment by craigcook** [comment]
Oops, that desktop link should point to https://www.mozilla.org/firefox/browsers/compare/
