### ISSUE TITLE
Improve VPN Download Page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11981]
## Description

Now that the VPN download page is on bedrock, we have an opportunity to improve it. The VPN product team has design recommendations.

This issue will be updated when more info is available.

[Jira ticket](https://mozilla-hub.atlassian.net/browse/VPN-2525?focusedCommentId=574322&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-574322)

**Comment by alexgibson** [comment]
Possibly either related to, or a duplicate of https://github.com/mozilla/bedrock/issues/11875

**Comment by slightlyoffbeat** [comment]
closing in favor of https://github.com/mozilla/bedrock/issues/11875
