### ISSUE TITLE
A new page for Privacy & Security products

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11982]
## Description

Details on the new page can be found at [this Jira link](https://mozilla-hub.atlassian.net/browse/VPN-2495?focusedCommentId=573803&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-573803)

---

**Comment by slightlyoffbeat** [comment]
possible dupe, or related: https://github.com/mozilla/bedrock/issues/11781

**Comment by alexgibson** [comment]
Closing this as a duplicate of https://github.com/mozilla/bedrock/issues/11781
