### ISSUE TITLE
Can we retire `feature_card()` ?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12009]
## Description

The [Feature Card](https://protocol.mozilla.org/components/detail/feature-card--default.html) component has been marked as deprecated in Protocol for a while now, and I think we might have replaced it everywhere in bedrock with [Split](https://protocol.mozilla.org/components/detail/split--default.html).

I still see the [macro](https://github.com/mozilla/bedrock/blob/main/bedrock/base/templates/macros-protocol.html) exists, and a bunch of pages seem to import it - but I'm not sure if it's actively used in any of those pages? There also seem to be a handful of pages still importing the feature card CSS, which seems redundant.

Can we remove the macro, and all traces of feature card CSS?

---

#### Success Criteria
- [x] Feature card macro is removed.
- [x] Feature card CSS is removed.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12018
