### ISSUE TITLE
Landing page: Firefox for Families

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12004]
## Description

Landing page for Firefox for Families campaign.

official URL: `https://www.mozilla.org/en-US/firefox/family`
friendly url: `firefox.com/family`

Note: this is meant to be an evergreen page that will outlive the campaign

**Creative review with channel owners Aug. 12**

**In production Sept. 5** (needed for paid media testing before go live date)

**Go live Sept. 6**

Design (Mozilla only): https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=100%3A1597
Copy (Mozilla only): https://docs.google.com/document/d/1ImKQwtKGMwlKYT8_y6gCpnVBbh98q2YAtA9cqGbQxjk (probably worth double checking if there are discrepancies between design and copy text)

To-do:

- [x] New page scaffold (template folder and view logic)
- [x] Layout with placeholder content
- [x] Meta [preview content](https://docs.google.com/presentation/d/1jjd96ODHV_lbdQCFg7BWcFjN5TXu-KzcuFvdKutvCeo/edit#slide=id.g144d4c3ce2c_2_19) ([preview image asset](https://drive.google.com/drive/u/1/folders/1tGMronAKiIbH0TyQAjVK8otNrxgy6fSk)) (@nathan-barrett)
- [x] Interaction: Horizontal scroll card content (public wifi section on mobile)
- [x] Animation: Marquee
- [x] [Downloadable PDF](https://drive.google.com/drive/u/1/folders/1z6l7ZtEJq4YIOh6pozMCqjT50skjbrYN) in agreement section (@nathan-barrett )
- [x] A11y review
- [ ] [GA data attributes & UTM params](https://github.com/mozilla/bedrock/pull/12087) (utm_campaign: firefox-for-families )
- [ ] Final content
- [ ] Final media

If time:
- [ ] Social share in agreement section
- [ ] Subtle content appearance animations on scroll

Demo link: https://www-demo1.allizom.org/en-US/firefox/family/

**Comment by maureenlholland** [comment]
@slightlyoffbeat is there a URL approved for this?

**Comment by slightlyoffbeat** [comment]
@maureenlholland there is not. We can work with studio team to come up with some options.

**Comment by maureenlholland** [comment]
Grab-bag tasks:
- [ ] Dad jokes banner (Styling: fixed to bottom, JS: dismiss on "Agree" click)
- [ ] Private mode section browser container overflow on mobile
- [ ] Mental health section responsive layout overlaps
- [ ] Tests for Download button and subnav links
- [ ] Tech Talk lockup (can we do this with HTML/CSS instead of image?)

**Comment by maureenlholland** [comment]
utm_campaign: firefox-for-families
