### ISSUE TITLE
Fixes for 'Licensed to Build Together' Page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12003]
## Description

Reported by Ethan Piper:

- the main article content container spills over into the left article credits column.
- If you make the page really wide or really small via zoom this happens
- Note I checked the other two article pages and they  work as expected. they do not spill over in the article credits column

---

Current:

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/2030656/182752341-06f7ad3c-d33f-420b-9488-8e0876da3c0e.png">

Expected:

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/2030656/182752378-0b01f341-d907-45a6-a960-37c399025e4e.png">

Copy changes: There was a mixup on what was the final document. Changes are all minor text changes. They are highlighted in this document: https://docs.google.com/document/d/1IVOR4jICeW1OdBDh5wdJk7xs7Gw039vGpIU2eDrwu7g/edit

#### Success Criteria
- [ ] Article content does not spill into left column (see screenshots)
- [ ] Copy is updated according to the changes highlighted in the document above

**Comment by alexgibson** [comment]
Looks like this was done
