### ISSUE TITLE
Fast-follow: F3 landing page

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12091]
F3 feature branch is in review and to avoid scope creep, we are moving non-blocking tasks to this issue. 

DESIGN/COPY notes (Mozilla only): https://docs.google.com/spreadsheets/d/17SH9BTWKnYtmU1ukek2fEKLqMFr4kc1ctDSeyEtV6sg/edit#gid=0

P1
- [x] Tests for Download button and subnav links @maureenlholland 
- [x] [Download section fine-tuning](https://github.com/mozilla/bedrock/pull/12105): https://github.com/mozilla/bedrock/pull/12081#discussion_r960092930 and incorporate design feedback: <3 emoji is sitting high, can lower on the baseline and close up spacing on either side @maureenlholland 
- [x] ["The Tech Talk" Hero graphic looks low res](https://github.com/mozilla/bedrock/pull/12114). @maureenlholland 
- [x] [Replace Stop & cursor combined image with separate images](https://github.com/mozilla/bedrock/pull/12125) (one for text & one for cursor) @maureenlholland 
- [x] [Reduce ticker text size on mobile](https://github.com/mozilla/bedrock/pull/12126) @maureenlholland 
- [x] CTA for "Set Fx as Default Browser" and "Download PDF" in Agreement section are different sizes—[match to download section CTA sizing](https://github.com/mozilla/bedrock/pull/12132) @maureenlholland 
- [x] [Update doomscroll grid background asset](https://github.com/mozilla/bedrock/pull/12115) @maureenlholland 
- [x] Check border widths with [9/1 figma version](https://github.com/mozilla/bedrock/pull/12135/files), reduce border with on heart illustration (need re-exports) @maureenlholland 
- [x] [Mobile: center agreement CTA](https://github.com/mozilla/bedrock/pull/12132) @maureenlholland 

P2
- [x] [Move the ticker display and animation](https://github.com/mozilla/bedrock/pull/12086#discussion_r962023816) into a `prefers-reduced-motion: no-preference` query 
- [x] [Decrease bottom padding](https://github.com/mozilla/bedrock/pull/12136) in 'never ending stories' , 'private browsing mode paradox' , and topic 1 'what to do' boxes @maureenlholland 
- [x] Nudge Hero grid up so [horizontal grid line doesn't sit directly below sub nav](https://github.com/mozilla/bedrock/pull/12135/files). Keep grid center as it scales. @maureenlholland (should be fixed with grid re-export PR)
- [x] Windows that have "drop shadows". [Offset X & Y axis more](https://github.com/mozilla/bedrock/pull/12134) to reflect figma comp. @maureenlholland 
- [x] [Mobile: drop all to next line in download section headline](https://github.com/mozilla/bedrock/pull/12140)

Note: this issue is for clean-up of existing code, new styling will be handled in [a different issue](https://github.com/mozilla/bedrock/issues/12111)

**Comment by maltman-moz** [comment]
Are the link icons supposed to copy the anchored section to a clipboard? Example:  https://a.cl.ly/8Lu1wnDw

**Comment by maureenlholland** [comment]
> Are the link icons supposed to copy the anchored section to a clipboard? Example: https://a.cl.ly/8Lu1wnDw

@maltman-moz - original intention was simply to have a visual indicator that these sections are linkable, which matches with my experience based off [anchor links in css tricks](https://css-tricks.com/overlapping-bar-charts/#aa-the-html). 

copy-to-clipboard is possible through a [web api](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) though we have mostly used this for coupon codes/email addresses in the past, with a[ layered page icon](https://github.com/mozilla/protocol-assets/blob/main/icons/copy.svg) instead of the chain link icon to indicate the copy functionality

Current link icons are functioning as intended but it's certainly worth adding copy-to-clipboard if that's the more expected behaviour, I will check in with our UX designer for her perspective.

**Comment by ehot** [comment]
<img width="576" alt="Screen Shot 2022-09-08 at 11 01 21 AM" src="https://user-images.githubusercontent.com/2040610/189170240-13ffa95d-06f4-4184-8e4d-631a9a576d07.png">
 
Having interacted with the UI, I do believe that it should copy to clipboard, but it should also have a tooltip on hover / touch to let the user know that that interaction will happen.

**Comment by maureenlholland** [comment]
Thanks for the input @ehot ! @maltman-moz copy-to-clipboard functionality has been added as a new style to-do in the following issue: https://github.com/mozilla/bedrock/issues/12111

We should be able to get it in production early next week

**Comment by reemhamz** [comment]
Regarding moving the ticket animation into a `prefers-reduced-motion` query, do we just want the content to not move entirely? I'm curious how useful the ticker might be if the content isn't moving and showing more words. If we stop the animation completely and keep it, it'll probably have some cut-off words.

**Comment by alexgibson** [comment]
> Regarding moving the ticket animation into a prefers-reduced-motion query, do we just want the content to not move entirely? I'm curious how useful the ticker might be if the content isn't moving and showing more words. If we stop the animation completely and keep it, it'll probably have some cut-off words.

Perhaps we could make the content fully accessible when `prefers-reduced-motion` is set? (i.e. make it flow onto multiple lines instead of being cropped via overflow)

**Comment by maureenlholland** [comment]
@reemhamz @alexgibson intention with the query change is to prevent older browsers that don't support `prefers-reduced-motion` from showing the ticker to users who would prefer reduced motion if they could

The idea is it's more of a design element than a content element, so by default would be hidden and only available to users who are using a modern enough browser and have no motion preference.

If we feel the ticker content is worthwhile in every case, let's make it a user-scrollable element, because there is quite a lot of content and it will take up too much space if allowed to wrap onto multiple lines
