### ISSUE TITLE
Remove "More Mozilla Innovation" link from Innovation Drop Down

### ISSUE THREAD

**Issue by emclaren** [mozilla/bedrock#12103]
## Description
The Hubs Team is working on refreshing our online assets. We notice that the link "More Mozilla Innovation" [see below] points to labs.mozilla.org, a site which is not currently maintained. It appears to have last been updated sometime around 2018. We would like to remove this link so people aren't taken to outdated information. 
<img width="1660" alt="Screen Shot 2022-09-01 at 4 41 05 PM" src="https://user-images.githubusercontent.com/6835324/188720444-5228c3e0-92c1-4fb1-9bc6-c87f174201b5.png">

The code appears to be located here:
https://github.com/mozilla/bedrock/blob/67fd925b4d621dde0e48e27738c4b9c397ac5169/bedrock/base/templates/includes/protocol/navigation/menus/innovation.html#L53

---

#### Success Criteria
- [x] link that says "More Mozilla Innovation" should be removed from the innovation drop down

**Comment by craigcook** [comment]
Fixed in https://github.com/mozilla/bedrock/commit/e0edc43c8308642e9749482e8b93462624e0d8c3
