### ISSUE TITLE
Update homepage for Firefox for Families

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12144]
## Description

We are replacing the top unit on the english homepage with a Firefox for Families promotion. Currently it is promoting Pocket 10 year.

Language: en_US

Creative & Copy: https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=1387%3A7813

Live date: as soon as possible

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12147
