### ISSUE TITLE
Unexpected advice on "Firefox for Families" topic 6 (private mode)

### ISSUE THREAD

**Issue by yoasif** [mozilla/bedrock#12150]
As seen on https://www.reddit.com/r/firefox/comments/xg7o41/private_browsing_firefox_tech_talk_vs_mozilla/

## Description

Firefox for families private mode copy erroneously claims that private browsing mode "keeps your kid’s data from being collected".

This is inconsistent with official firefox help, eg https://support.mozilla.org/en-US/kb/common-myths-about-private-browsing

### Steps to reproduce

Navigate to https://www.mozilla.org/en-US/firefox/family/#private-mode

![image](https://user-images.githubusercontent.com/152493/190837462-8f96a78f-b975-47f5-9e9b-cd70d6997e31.png)

### Expected result

Copy more consistent with the myths about private browsing. 

### Actual result

Erroneous/incorrect copy. 

### Environment

Irrelevant.

**Comment by Mte90** [comment]
Yes it is like a clickbait message but this is not should be written on the official Mozilla website.

**Comment by maureenlholland** [comment]
Thanks for pointing that out! We've made the statement less broad, closing with https://github.com/mozilla/bedrock/pull/12166

**Comment by yoasif** [comment]
Thanks @maureenlholland!
