### ISSUE TITLE
Epic: {{ How to Prevent Remote Access/ control to change the original policies }}

### ISSUE THREAD

**Issue by DiqahLer** [mozilla/bedrock#12174]
## Description

What is the overall outcome we aim to achieve? 

Link to pitch, brief, or background documents.

---

#### Issues
- [ ] #issue-number
- [ ] #issue-number

**Comment by stevejalim** [comment]
Hi @DiqahLer - this doesn't look like a real issue. If you have a draft saved or similar, and it didn't post, please submit it as a new issue and/or re-open this one with a fuller description.

For now, at least, am closing this.
