### ISSUE TITLE
Scrolljacking on "Does this button work?" article

### ISSUE THREAD

**Issue by yoasif** [mozilla/bedrock#12183]
## Description

There is a fake scrollbar on https://foundation.mozilla.org/en/youtube/user-controls/ that messes with normal scroll behavior. 

### Steps to reproduce

1. Navigate to https://foundation.mozilla.org/en/youtube/user-controls/
2. Scroll with touchpad or look for scrollbar

### Expected result

Normal scrolling, I should see a scrollbar. 

### Actual result

Scrolling is weird - doesn't follow normal Firefox scroll behavior. Also, the scrollbar is not present, but a fake one appears instead. 

### Environment

Firefox Nightly on Linux.

**Comment by AveYo** [comment]
It's fine with [NSS (Natural Smooth Scrolling)](https://www.reddit.com/r/firefox/comments/lev5wy/natural_smooth_scrolling/) preset.
Maybe it should be the default smooth scrolling experience for everybody.

**Comment by maureenlholland** [comment]
Hi @yoasif, the foundation website is actually maintained in a different repo, you will need to file the issue here: https://github.com/mozilla/foundation.mozilla.org/issues

Hope they are able to help. Closing here as we do not control that page.
