### ISSUE TITLE
Remove image macro

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12190]
As noted in the[ card highres image](https://github.com/mozilla/bedrock/pull/12169#pullrequestreview-1128615261) fix, the [image macro](https://github.com/mozilla/bedrock/blob/main/bedrock/base/templates/macros.html#L143) is very complex. It was created to encapsulate shared complexity across several protocol macros using images.

We need to handle:
- static images
- localized images
- high res images
- images with multiple sources (picture elements, entirely different images or image formats)
- images with multiple sizes

We also have some python helpers for:
- resp_img
- picture
- high_res_img (deprecated)

In most cases, resp_img should cover what we need to handle. We should investigate if we can remove the image macro and simplify our protocol macro image calls.

Success Criteria:

- [x] Protocol macro use of image macro is replaced
- [x] Standalone use of image macro is replaced
- [x] Image macro and related docs/tests are removed

**Comment by alexgibson** [comment]
+1 for this - having helpers inside macros, inside other macros feels like too many layers of abstraction to me.

Agree `res_img()` should be enough in most cases.

**Comment by nathan-barrett** [comment]
Couple questions:
- Is there anytime that we would use `high_res_image` over `resp_image`?
- When would we use picture vs resp_image? Based on what is passed? - Currently the `image` macro will use a the picture element if the sources attribute has been passed to the macro

Mainly wondering how we should replace the logic that selects which python image helper to use - and if that logic should exist in the different macros or within a new helper

**Comment by alexgibson** [comment]
@nathan-barrett some answers to some of your questions:

> Is there anytime that we would use high_res_image over resp_image?

Not really, `resp_img()` can do exactly the same thing as `high_res_img()`, it just needs slightly different syntax (see [example](https://bedrock.readthedocs.io/en/latest/coding.html#resp-img) in the docs). Hence `high_res_img()` should now be considered deprecated.

> When would we use picture vs resp_image? Based on what is passed?

There's a [section in the docs](https://bedrock.readthedocs.io/en/latest/coding.html#which-image-helper-should-you-use) that has some common use cases for both `picture()` and `resp_img()` Right now the `image()` macro selects which one is used based on the parameters passed, which is not ideal in terms of being straight forward.

> Mainly wondering how we should replace the logic that selects which python image helper to use - and if that logic should exist in the different macros or within a new helper

What we'd like to try and do is remove `image()` altogether, as right now passing all these variables around through three different macros/helpers is pretty confusing (imho). What that ends up looking like is up to the discussion in the bug I guess.

One possible solution I thought of was removing all the image logic from Protocol macros altogether, and leaving it to the Python image helpers (which are already well tested for this type of thing). In a template that could look something like:

```jinja
{% set billboard_image = resp_img(
  url='img/home/2018/billboard-more-power.png',
  srcset={
    'img/home/2018/billboard-more-power-high-res.png': '2x'
  }
) %}

{{ billboard(
  title='Für Dich & das Internet. <br>Schon seit 1998.'|safe,
  ga_title='Für Dich & das Internet. Schon seit 1998.',
  desc='Mozilla setzt sich für ein gesundes Internet ein – und damit für die Menschen, die es nutzen. Damals. Heute. Morgen.',
  link_cta='Erfahre mehr über Mozilla',
  link_url=url('mozorg.about.manifesto'),
  image=billboard_image
)}}
```

This nice thing about this method could be that `billboard_image` can be anything, so `resp_img()` or `picture()` or just a straight forward `<img>`, and the macro doesn't really need to worry about any of the parameters. I guess the downside is this would require more changes to the templates that use the macros.

**Comment by maureenlholland** [comment]
Great questions. For a little extra context, before the image macro, the logic in individual protocol macros was selecting between the following helpers:

Billboard
- high res
- static

Hero
- high res
- absolute path (`image_url.startswith('https')`)
- l10n
- static

Split
- high res
- absolute path (`image_url.startswith('https')`)
- l10n
- static

Card
- lazy_img (high res)
- lazy_img (static)

Picto
- high res
- absolute path (`image_url.startswith('https')`)
- l10n
- static

Given that `resp_img` can manage high-res, l10n, and static, we can use it as a straight replacement for the `image` macro in Billboard and Card. 

For Hero, Split, Picto, and Billboard, it's probably worth investigating if they are actually using absolute path image in any case. Maybe that's unused logic and we can remove it completely. Otherwise, we need to keep that logic in the separate macros.

Picture is a great capability, but not much used as it's newly introduced. I think it's only on Split calls: 
https://github.com/mozilla/bedrock/blob/30b608d8718105ef81c4a80c02d0f48c54f9e209/bedrock/firefox/templates/firefox/privacy/index.html
https://github.com/mozilla/bedrock/blob/30b608d8718105ef81c4a80c02d0f48c54f9e209/bedrock/firefox/templates/firefox/more.html#L24

For this version, we could add that logic (selecting between resp_img or picture) only to the Split macro. Hero is being deprecated in any case and Picto is unlikely to need different image sources. We could update later if needed.

Worth discussing further if we want to move images to a variable set outside the macro (my initial hesitation with this is potentially unexpected values slipping through if there are multiple split image vars on a page and one var declaration is forgotten or misspelled). But I do like the idea of fewer image params.

**Comment by alexgibson** [comment]
I’ll leave it to both of you to figure out what’s best, but I’ll vote for code simplicity over adding more hidden complexity 👍

**Comment by maureenlholland** [comment]
@nathan-barrett let's try to replace `image` with `resp_img` across all protocol macros 
for split, we will need some extra logic to decide between `resp_img` and `picture`
for absolute image paths, we can add that logic where needed (if needed)

if that gets too repetitive/complicated across protocol macros, let's try moving the image logic out altogether and using the desired helper on the call itself (i.e. Alex's `billboard_image` example above)

**Comment by nathan-barrett** [comment]
@alexgibson @maureenlholland Thanks for the extra info, appreciate both of your comments 😃

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/12513

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/11493
