### ISSUE TITLE
TestExistingNewsletterView test failing in CircleCI

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12198]
## Description

See: https://circleci.com/api/v1.1/project/github/mozilla/bedrock/48385/output/103/0?file=true&allocation-id=633d7739f62e3807bfc1b66d-0-build%2F5310B29B

This just started happening today, seemingly out of the blue. So far we can't replicate the failures locally at all.

**Comment by stevejalim** [comment]
Alex also confirmed this happens on multiple branches, including one with just a change to the README, so it's not a code regression in the relevant branch

**Comment by stevejalim** [comment]
Circle CI status is reporting no issues at the moment

**Comment by alexgibson** [comment]
Specific errors seem to be:

`TypeError: '>=' not supported between instances of 'MagicMock' and 'int'`

and

```
>       request, template_name, context = render.call_args[0]
E       ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by alexgibson** [comment]
Current thinking is that something has changed in the CircleCI Python 3.9 image, which was updated around 15 hours ago: https://hub.docker.com/r/cimg/python/tags?page=1&name=3.9

**Comment by alexgibson** [comment]
Looks like it might actually be the docker image: https://github.com/docker-library/python/blob/008e5da2192428c97437191969d9b71a05d8acae/3.9/slim-bullseye/Dockerfile

**Comment by stevejalim** [comment]
Right now, with a 3.9.14 base python image for our Docker stack, I am unable to replicate the test failures with local docker.

I have a separate branch where i am trying to downpin our Docker base python image to 3.9.13, but Circle CI is currently having a partial outage, so we can't test whether this sidesteps the issue as a short-term fix. If it does not, next thing to try is downpinning the python image that Circle CI is using to run our build - but this seems a long shot
