### ISSUE TITLE
Add moz-fluent-lint GH action to bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12209]
## Description

The [www-l10n repo](https://github.com/mozilla-l10n/www-l10n/) has an [FTL linter](https://pypi.org/project/moz-fluent-linter/) that is way more robust than what we have in bedrock right now. We should add it directly to bedrock, as this will close a (sometimes) painful feedback loop that creates manual back and forth for developers.

/cc @flodolo

**Comment by alexgibson** [comment]
I took a look at adding this, but looks like we're blocked due to the `fluent-runtime` package requiring an outdated version of `fluent-syntax`:

```
There are incompatible versions in the resolved dependencies:
  fluent-syntax==0.17.0 from https://files.pythonhosted.org/packages/f4/8e/2bb1faa3ec29f52a5609bc1712227cfed8a808671448e2b450c65411135c/fluent.syntax-0.17.0-py2.py3-none-any.whl (from -r requirements/prod.txt (line 255))
  fluent.syntax<0.19,>=0.18.0 (from compare-locales==8.2.1->-r requirements/dev.in (line 25))
  fluent.syntax<0.19,>=0.18.0 (from moz-fluent-linter==0.3.4->-r requirements/dev.in (line 26))
  fluent.syntax<0.19,>=0.17 (from fluent-runtime==0.3.1->-r requirements/prod.txt (line 251))
```

**Comment by flodolo** [comment]
Might want to file an [issue for it](https://github.com/projectfluent/python-fluent/issues)? (cc @eemeli)

**Comment by alexgibson** [comment]
Filed: https://github.com/projectfluent/python-fluent/issues/176

**Comment by flodolo** [comment]
> I took a look at adding this, but looks like we're blocked due to the `fluent-runtime` package requiring an outdated version of `fluent-syntax`:

I was thinking again about this: why do you need to add the requirements to Bedrock? It can be installed in the workflow, or have a separate requirement just for the workflow, to avoid the conflict.

For example, this would work
https://github.com/mozilla/bedrock/compare/main...flodolo:bedrock:fluent_linter

**Comment by alexgibson** [comment]
@flodolo thanks for the suggestion!

**Comment by stevejalim** [comment]
If we're happy with https://github.com/mozilla/bedrock/pull/12739 then that PR would unblock the discussed use of the lib in bedrock, if that's the way we go with it
