### ISSUE TITLE
Fix CI runs on Python 3.9.14

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12203]
## Description

For some reason, still TBD, Circle CI triggers a bunch of failures in a particular set of tests but only when the "outer" container (the one Circle stands up, inside which we then build our own Docker container for tests), is using Python 3.9.14 (which on 5 Oct 2022 became the default for the `cimg/python:3.9` image we're using).

For now, and after looking at what 3.9.14 gives us, we've had to downpin the CI image to 3.9.13 to unblock releases. Note that the actual Bedrock containers, whcih use the official latest Python 3.9 release of 3.9.14 build fine and tests all pass fine in the container (either locally or when circle is using 3.9.13 for the outer container).

Of course, this isn't a sustainable fix and should be as temporary as possible.

(If we can't get tests passing on CircleCI 3.9.14, we should be open to moving away from Circle and on to GH Actions)

---

#### Success Criteria
- [ ] All Bedrock tests pass using a CI solution that uses the latest patch version of Python 3.9 (currently 3.9.14)

**Comment by alexgibson** [comment]
@stevejalim I can't quite remember if this was still an issue, or is it something we fixed along the way?

**Comment by stevejalim** [comment]
We're no longer using CircleCI, so this ticket is redundant now
