### ISSUE TITLE
Mozilla Stories October Udpate

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12220]
## Description

There is a new story to add to the Mozilla Stories blog. Unlike the previous entry, it will only be a single article.

[Final article + assets](https://docs.google.com/document/d/15ITjTen7PaQ6x9s4GRi9W7rdnrkybz77fP-K1MySM_Q/edit)

Hero Image: N/A. JR is currently creating

Homepage update: [Here is a layout from Elise](https://mozilla.slack.com/archives/C03FMS5AU49/p1661880469694379) that will handle this update for now (Links to a slack conversation).

Requested Go-Live date: October 17th.

**Comment by slightlyoffbeat** [comment]
URL: `https://mozilla.com/stories/joy-of-color`

**Comment by maureenlholland** [comment]
I think Demo 3 is free, so I'll push to that branch soon. I haven't done responsive testing yet. A couple of notes:

Single article styling issues:
- overflow from credits to article content on tablet/desktop sizes
- overlapping header text in related articles section (this seems to be ok with updated, longer article content, but worth keeping an eye on)
<img width="336" alt="overflow" src="https://user-images.githubusercontent.com/19650432/195100337-d004594c-665e-4425-bcb0-f6708acb25a9.png">
<img width="1014" alt="overlap" src="https://user-images.githubusercontent.com/19650432/195100340-8c2da791-643a-4090-b455-a7b5cf842a38.png">

Images will need to be properly sized 
- credits images are all low res, need high res versions
- need to confirm in-article image sizing, then create responsive images

Long blockquotes are not very readable with current styling
- in  longer term, we could add a variant blockquote style to handle longer content
- for quicker turnaround, we should change these blockquotes to shorter versions (i.e. just first line of each?)

<img width="946" alt="over-long-quote" src="https://user-images.githubusercontent.com/19650432/195101159-6332641e-0fae-4b06-a7fb-51daaaa554a6.png">

**Comment by maureenlholland** [comment]
Note to self, need to confirm if color is same b/w landing and single article. If so, need to fix scrollbar color (not sure why it's also picking up the green bg)

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12264
