### ISSUE TITLE
Firefox for Families: PTA Signup Page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12227]
## Description

There is a request to duplicate [this page](https://www.mozilla.org/en-US/newsletter/), with slightly updated designs to be used for PTA signup.

Details, design should be made available on Oct 12.

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by slightlyoffbeat** [comment]
[Figma file](https://www.figma.com/file/zEWcXI6tFGtGcEvdwBWYz0/Firefox-Families?node-id=2411%3A9188).

[Design Assets](https://drive.google.com/drive/folders/1Nu2E-ttwbGIGl65viYORnB6NR1AsqYDL)

**Comment by slightlyoffbeat** [comment]
my domain recommendation is `https://www.mozilla.org/newsletter/?v=family`

**Comment by alexgibson** [comment]
> my domain recommendation is https://www.mozilla.org/newsletter/?v=family

There's quite a bit of logic wrapped up in the `/newsletter/` view (it's also an API endpoint in addition to a web page), so seeing as this page is just a straight forward newsletter form, I'd like to propose we use a well-formed URL instead to keep things separate:

https://www.mozilla.org/newsletter/family/

Does this sound ok @slightlyoffbeat?

**Comment by alexgibson** [comment]
@slightlyoffbeat I pushed a first pass for this up on demo below. Let me know if you have any feedback / need anything else?

https://www-demo5.allizom.org/en-US/newsletter/family/

The form contains a `source_url` hidden field with a value that matches the URL of the page. Providing this maps through to Acoustic OK (possibly to `newsletter_source`?), this should be enough to provide attribution to the page.
