### ISSUE TITLE
WNP 108

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12231]
## Description

This will be Pocket focused, and have a tie-in to Pocket Best of 2022 campaign.

[Assets](https://drive.google.com/drive/folders/1LjXNnjfQmExtrAUoAIEuLNDdCwggtaR0?usp=share_link)

[Mockups](https://www.figma.com/file/Os9FNPNQvz0bHjZDUUYZBP/Pocket-Best-of-2022?node-id=108%3A646&t=2r0GuE0UQ7xyzuBh-1)

[Mockups for additional breakpoints](https://www.figma.com/file/Os9FNPNQvz0bHjZDUUYZBP/Pocket-Best-of-2022?node-id=295%3A3143&t=2r0GuE0UQ7xyzuBh-1)

This will make use of:
1. traffic cop for splitting variants
2. UI Tour to update CTA based on if user has FxA + FxA is associated with a pocket account.

Flow diagram:
![Flow](https://user-images.githubusercontent.com/2030656/202826849-ca5d7072-b820-445e-a5da-3ac3eb3d114b.png)

---

#### Success Criteria & Considerations
- [ ] Traffic cop sending splitting traffic
- [ ] UI Tour successfully detecting if a user has FxA and that FxA is associated with pocket and updating CTA accordingly
- [ ] Lets make all CTA event labels unique to help with rapid reporting. We can use an identifier such as `best2022_`
- [ ] Easy to put 100% of traffic to winning variant (info will be provided by Benton 3 days after initial launch of WNP

**Comment by alexgibson** [comment]
EU requirements:

- `/de/` shares the same test setup as US
- `/fr/` only has once version, but uses a different design.
- UK only has one version, but shares the same design.
- For UK, they would like to target both `en-US` and `en-GB` by country.
- Implement a GA event for "has pocket" and "doesn't have pocket".

EU deliverables:

- [Copy doc](https://docs.google.com/document/d/1gmODKqDTldpnYXU5j2_Iz0GHZLx4SOWj1MLmbNUeNAA/edit#)
- [Figma doc](https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-22?node-id=2212%3A400&t=aUg3g6PbgRbDNTRQ-1)

**Comment by alexgibson** [comment]
OK, I have enough info to get going here :)

**Comment by slightlyoffbeat** [comment]
- We do not have the alternate CTA currently. I'll track down, and we can use a placeholder for now.
- Thank you for coordinating on the EU requirements.

**Comment by alexgibson** [comment]
WIP demo links:

- NA Curation focused: https://www-demo4.allizom.org/en-US/firefox/108.0/whatsnew/?v=1
- NA Feature focused: https://www-demo4.allizom.org/en-US/firefox/108.0/whatsnew/?v=2
- DE Curation focused: https://www-demo4.allizom.org/de/firefox/108.0/whatsnew/?v=1
- DE Feature focused: https://www-demo4.allizom.org/de/firefox/108.0/whatsnew/?v=2
- UK: https://www-demo4.allizom.org/en-GB/firefox/108.0/whatsnew/?geo=gb
- FR: https://www-demo4.allizom.org/fr/firefox/108.0/whatsnew/
