### ISSUE TITLE
State of Mozilla 2021/22

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12234]
## Description

Placeholder for State of Mozilla 2021. Requested go-live date is 2nd week of November

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/12384
