### ISSUE TITLE
WNP 107 (eu)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12230]
## Description

Design: [here](https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-22?node-id=2138%3A400)

Copy: [here](https://docs.google.com/document/d/1RWZoDMGpdl5RlZnUMAFAGvDN33sd9SR5yZTqb3W6Nao/edit#)

Adjust Links: TBD (@slightlyoffbeat  to deliver)

---

#### Success Criteria
- [ ] Test and confirm android attribution
- [ ] Test and confirm iOS attribution

**Comment by maureenlholland** [comment]
@slightlyoffbeat any word on the Adjust links?

**Comment by slightlyoffbeat** [comment]
adjust links:

fr: `https://app.adjust.com/xbd7d33_7sv2j5x?campaign=wnp107&adgroup=fr`
de: `https://app.adjust.com/xbd7d33_7sv2j5x?campaign=wnp107&adgroup=de`

**Comment by slightlyoffbeat** [comment]
@craigcook @maureenlholland see above. I am sorry for my mistake last week. I generated VPN mobile links and not Fx Mobile links. The adjust links above have been updated
