### ISSUE TITLE
Add Separate sentry profiles for Pocket mode

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12289]
## Description

At the moment all Bedrock deployments are using the same Sentry DSN for the given environment (dev, stage, test, prod), regardless of whether they are operating in Mozorg mode or Pocket Mode. It makes sense to split those up so we get more useful error tracking/alerting

---

#### Success Criteria
- [ ] Current Bedrock Sentry projects continue to be used for Mozorg - and are renamed accordingly
- [ ] New Sentry projects are set up for Pocket mode and are named clearly
- [ ] Both Modes are capturing data

**Comment by alexgibson** [comment]
@stevejalim was this one done?

**Comment by stevejalim** [comment]
No, still valid / needs mopping up. Will add it to my queue
