### ISSUE TITLE
Mozilla home page displays outdated content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12282]
## Description

For every locale except English, German and French, the home page for www.mozilla.org displays some pretty outdated content. It no longer reflects much of what Mozilla has been working on in the past 4-5 years.

### Steps to reproduce

1. Open https://www.mozilla.org/es-ES/
2. Observe the links under "Our impact". More than one link goes to a blog post from 2017. Nothing more recent is shown.
3. Observe the links under "Our innovations". It only lists "Common Voice" and "Virtual Reality Platform" (Firefox Reality is now defunct).
4. There is no mention to any of the products Mozilla has worked on in the last 4-5 years, such as Mozilla VPN, Firefox Relay, or Firefox Monitor, or Pocket.

This represents the experience roughly 40% of traffic to the home page sees (worldwide) ^

**Comment by alexgibson** [comment]
See also https://github.com/mozilla/bedrock/issues/5824

**Comment by alexgibson** [comment]
See also https://github.com/mozilla/bedrock/issues/9880

**Comment by reemhamz** [comment]
Who would be the best group of people we can speak to to get this into our roadmap?

**Comment by alexgibson** [comment]
I believe there's already a work-stream happening with Elise and the studio team to redesign the home page (which includes all locales). I'm not sure on the timeline though.

**Comment by reemhamz** [comment]
Will be reaching out to studio team as I just confirmed with @ehot that she's not entirely in the loop for the homepage redesign. I'll post updates here

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/13447
