### ISSUE TITLE
WNP for Firefox 107

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#12329]
## Description

Firefox 107 releases on **15 November, 2022**

EU copy: https://docs.google.com/document/d/1RWZoDMGpdl5RlZnUMAFAGvDN33sd9SR5yZTqb3W6Nao/
EU design: https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-22?node-id=2138%3A400
NA copy: https://docs.google.com/document/d/1gtie8VFq0uDJgffyZppkv-1GwJCS3MqLKKpoVYWAM60/
NA design: https://www.figma.com/file/CZvzHgU9NQMQUm34lomIl5/Firefox-WNP?node-id=2478%3A39707

**Comment by maureenlholland** [comment]
ah, sorry, I grabbed [a duplicate EU WNP issue](https://github.com/mozilla/bedrock/issues/12230) without realizing they were all covered here

Duplicate NA issue here: https://github.com/mozilla/bedrock/issues/12229

**Comment by craigcook** [comment]
Duped elsewhere.
