### ISSUE TITLE
Remove image macro from split

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/bedrock#12331]
## Description

Removing the image macro from the split component and replacing it with either picture or responsive image

This is a list of here we call split in bedrock and how many times it appears on the pages:

| page        | # of calls           | completed?  |
| ------------- |:-------------:| -----:|
| `firefox/more.html`  | 1 |  x |
| `contentful/templates/includes/contentful/all.html` | 1 |  |
| `/firefox/pocket.html` | 2  |  x | 
| `firefox/switch.html` | 1 | x |
| `firefox/sync.html`| 1| x |
| `firefox/browsers/chromebook.html`| 2 | x |
| `firefox/browsers/index.html`| 1| x |
| `firefox/browsers/quantum.html`| 1|  x |
| `firefox/browsers/mobile/android.html`| 11| x |
| `firefox/browsers/mobile/compare.html`| 1| x  |
| `firefox/browsers/mobile/focus.html`| 7| x |
| `firefox/browsers/mobile/index.html`| 2| x |
| `firefox/browsers/mobile/ios.html`| 10| x |
| `firefox/developer/index.html`| 1| x |
| `firefox/developer/includes/for-developers.html`| 1| x |
| `firefox/developer/includes/nightly.html`| 1| x |
| `firefox/developer/includes/performance.html`| 1| x |
| `firefox/enterprise/index.html`| 1| x|
| `firefox/features/bookmark.html`| 3| x|
| `firefox/features/fast.html`| 3| x |
| `firefox/features/fingerprinting.html`| 1| x |
| `firefox/features/independent.html`| 3| x |
| `firefox/features/index.html`| 1| x  |
| `firefox/features/memory.html`| 3| x |
| `firefox/features/password-manager.html`| 3| x |
| `firefox/features/picture-in-picture.html`| 1| x |
| `firefox/features/private-browsing.html`| 3| x |
| `firefox/features/translate.html`| 1| x |
| `firefox/home/index-master.html`| 5| x |
| `firefox/mobile/index.html`| 4|  x|
| `firefox/privacy/book.html`| 9|  x |
| `firefox/more/misinformation.html`| 4| x  |
| `firefox/privacy/index.html`| 4|  x |
| `firefox/privacy/passwords.html`| 1| x |
| `firefox/privacy/products.html`| 4| x |
| `firefox/products/index.html`| 1| x |
| `firefox/whatsnew/whatsnew-fx98-mobile-de.html`| 1|  |
| `firefox/whatsnew/whatsnew-fx98-mobile-fr.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx101-vpn-de.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx101-vpn-fr.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx101-vpn-mobile-unfree-en.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx101-vpn-mobile.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx102-fr.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-de-coupon.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-de.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-en-coupon.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-en.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-fr-coupon.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx104-vpn-fr.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx105-de-1.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx105-de-2.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx105-fr.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx105-uk-1.html` | 1 | | 
| `firefox/whatsnew/whatsnew-fx105-uk-2.html` | 1 | | 
| `foundation/annualreport/2019/index.html` | 6 | | 
| `foundation/annualreport/2020/index.html` | 5 | | 
| `mozorg/about/policy/lean-data/build-security.html` | 1 | | 
| `mozorg/about/policy/lean-data/engage-users.html` | 1 | | 
| `mozorg/about/policy/lean-data/index.html` | 1 | | 
| `mozorg/about/policy/lean-data/stay-lean.html` | 1 | | 
| `mozorg/templates/mozorg/about/index.html` | 1 | | 
| `mozorg/home/includes/firefox-family-promo.html` | 1 | | 
| `mozorg/home/includes/firefox-mr106-promo.html` | 2 | | 
| `mozorg/home/includes/mr2-promo-eu.html` | 1 | | 
| `mozorg/home/includes/mr2-promo.html` | 1 | | 
| `mozorg/home/includes/pocket-10-years-promo.html` | 1 | | 
| `mozorg/home/home.html` | 1 | | 
| `mozorg/templates/mozorg/contribute.html` | 1 | | 
| `newsletter/family.html` | 1 | | 
| `pocket/firefox/new-tab-learn-more.html` | 4 | | 
| `pocket/templates/pocket/add.html` | 1 | | 
| `pocket/base-platform.html` | 1 | | 
| `pocket/get-inspired.html` | 3 | | 
| `pocket/home.html` | 3 | | 
| `pocket/pocket-and-firefox.html` | 4 | | 
| `pocket/save-to-pocket.html` | 4 | |

**Comment by alexgibson** [comment]
Gonna see if I can finish the rest of these out
