### ISSUE TITLE
Download Token Log are Mis-labeling GA clientId and Not Recording GA visitId

### ISSUE THREAD

**Issue by SuYoungHong** [mozilla/bedrock#12355]
## Description

On download, we're creating a unique DL token for a download event and passing it to client side telemetry in order to attribute the new profiles. 

As part of this process, we're logging the DL token along with the corresponding Google Analytics clientId in a restricted database to be able to match GA data with attributed Firefox profiles. 

There are currently 2 issues with the current implementation: 
* 1) We're only recording Google Analytics clientId in our logs. However, we need to log **both** the clientId as well as the visitId in order to attribute (since attribution is a session level datapoint, not client level). 
* 2) We're recording the Google Analytics clientId as a `visit_id` in our logs, which is confusing. 

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

The Download Token Log table should report both the Google Analytics clientId as well as Google Analytics visitId associated with the download event. 

The Download Token Log table should rename `visit_id` (which reports the Google Analytics clientId field) to `visitor_id`, or something less confusing.

**Comment by alexgibson** [comment]
We may need to hold here until we can figure out what the changes should be. I'm not 100% certain GA exposes visit ID (which seems to be why we currently pass only client ID).

Adding additional params or renaming things will likely require work across multiple teams.

**Comment by alexgibson** [comment]
Gist of all available GA objects via `window.ga.getAll()` : https://gist.github.com/alexgibson/1d68e6a9a8115a51eec11aa08f15033a

**Comment by alexgibson** [comment]
It looks like `window.ga.getAll()[0].model.data.ea[':_gt']` or `window.ga.getAll()[0].model.data.ea[':_gtb']` might be what we want.

**Comment by SuYoungHong** [comment]
I've filed a ticket for getting the logging on the Stubattribution side here: https://mozilla-hub.atlassian.net/browse/SVCSE-947

I think I've found owners for making the necessary changes on that side of the service. (https://mozilla.slack.com/archives/CSQKWNMEE/p1669935695600629) 

Not sure what needs to happen to coordinate the work on the Bedrock side and the Stubattribution side from this point. 

Should I schedule a meeting to coordinate the parties?

**Comment by alexgibson** [comment]
Thanks @SuYoungHong, happy to attend a meeting if that might be useful to make sure we're all aligned. Thanks for helping to schedule!

**Comment by willdurand** [comment]
> The Download Token Log table should rename `visit_id` (which reports the Google Analytics clientId field) to `visitor_id`, or something less confusing.

Why couldn't it be `client_id` if what we're passing is the GA client ID?

**Comment by willdurand** [comment]
> We may need to hold here until we can figure out what the changes should be. I'm not 100% certain GA exposes visit ID (which seems to be why we currently pass only client ID).

I agree with that. Can we actually read and pass the GA visitor ID like we do for the client ID?

**Comment by alexgibson** [comment]
> Can we actually read and pass the GA visitor ID like we do for the client ID?

Yes we can, see https://github.com/mozilla/bedrock/issues/12355#issuecomment-1315040568. It's worth noting that none of these are in official Google API docs however, so we should consider them as being non-permanent or subject to change imho.

> Should we get some kind of data review and/or ping secops since we are talking about collecting and storing new data?

Let's discuss this in out upcoming meeting ^ /cc @SuYoungHong

**Comment by SuYoungHong** [comment]
added data steward review request here: https://bugzilla.mozilla.org/show_bug.cgi?id=1809120

**Comment by SuYoungHong** [comment]
Data steward review has been granted, we are good to go forward with data collection

**Comment by alexgibson** [comment]
@SuYoungHong happy to pick this up when ready. Let me know when all the other downstream parts are in place.

**Comment by willdurand** [comment]
I just merged https://github.com/mozilla-services/stubattribution/pull/148 that adds support for the `session_id` field.

**Comment by alexgibson** [comment]
This is currently deployed for testing on https://www-demo3.allizom.org/en-US/
