### ISSUE TITLE
Donation Banner for Giving Tuesday

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12373]
## Description

We will be adding a donation banner for Mozilla Foundation on the website for Giving Tuesday.

They requested to use this creative to tie in to the overall look and feel of their campaign. My initial reaction is it is too busy for a banner, but perhaps if we play with opacity:

![Giving Tuesday website hero](https://user-images.githubusercontent.com/2030656/202057695-388dbf8e-ee2a-4906-bf70-0e1934f67943.png)

Also provided:
Wagtail donation form: https://donate.mozilla.org/en-US/help-mozilla-fight-for-a-better-internet-this-holiday-season/
Salesforce campaign ID: (reach out to Dan if this is needed)

---

#### Success Criteria
- [ ] Live globally for Tuesday, Nov 29. Taken down on 30th.
- [ ] Update default donation amounts in bedrock to match those on donate.mozilla.org

**Comment by craigcook** [comment]
Looks like the default amounts have changed. Our current highest amount is $50 but donate.mozilla.org is now $60 for the same button so we'll need to update bedrock to match (and update all the other currencies as well).
