### ISSUE TITLE
Create pocket site style bundle

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12378]
Should be cache-able and include Protocol base elements

Spun off from https://github.com/mozilla/bedrock/pull/12287#pullrequestreview-1180858710

The base element styling affects all pages and some discrepancies need to be fixed:

Spacing under buttons
<img width="313" alt="home-padding" src="https://user-images.githubusercontent.com/19650432/202240573-6742540f-ec52-49e1-a54a-6a2902585304.png">

Spacing under headings
<img width="687" alt="contact-spacing-color" src="https://user-images.githubusercontent.com/19650432/202240738-20a31ff5-767f-4556-afac-60856782a73b.png">

Font color (too light on body) and weight 
<img width="382" alt="welcome-spacing-font-color" src="https://user-images.githubusercontent.com/19650432/202241010-8a233fc9-63c0-4730-82ab-bcabf8aef733.png">

Misc.
Add page issues
<img width="930" alt="fix-add" src="https://user-images.githubusercontent.com/19650432/202240838-f8973a54-13d1-4e35-9282-f54d841b7913.png">
Job page issues
<img width="802" alt="jobs-spacing-color" src="https://user-images.githubusercontent.com/19650432/202240908-087adacc-0b01-4804-b754-bfad2fbfb0f1.png">

**Comment by aarushisoni** [comment]
Hi, I want to work on this issue. Can you please tell me in which file I need to make changes? It will be helpful.

**Comment by maureenlholland** [comment]
Hi @aarushisoni, thanks for your interest! The issue requires a larger refactoring change touching multiple files so I am handling this one. I can see we don't have any [Help Wanted](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+wanted+%F0%9F%91%8B%22) issues at the moment but please do check back in future.

**Comment by maureenlholland** [comment]
Closing in favour of waiting for a design update before putting more effort into refactoring
