### ISSUE TITLE
https://www.mozilla.org/en-US/firefox/android/beta/notes/ is redirected to Firefox Android 68.7beta

### ISSUE THREAD

**Issue by makotokato** [mozilla/bedrock#12370]
## Description
Although https://www.mozilla.org/en-US/firefox/channel/android/#beta has "Release Notes" link for Firefox Android beta, [this link](https://www.mozilla.org/en-US/firefox/android/beta/notes/) is redirected to https://www.mozilla.org/en-US/firefox/android/68.7beta/releasenotes/ that is outdated version. We should redirect to release note of the latest beta version or remove "Release Notes" link from beta.

Describe the issue that you're seeing.

### Steps to reproduce
1. Browse https://www.mozilla.org/en-US/
2. Click "[Beta for Android](https://www.mozilla.org/en-US/firefox/channel/android/#beta)" link of Developers  in footer.
3. Click "[Release Notes](https://www.mozilla.org/en-US/firefox/android/beta/notes/)" link in Beta.

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result
- If we have release note of the current beta, we should navigate to release node of current beta
- If we don't have release note of Firefox Android beta, remove "Release Notes" link.

What should happen?

### Actual result
Firefox Android 68.7beta's release note page is shown.

What happened.

### Environment
Firefox 109 for Linux. and Firefox 109 for Android.

What browser and operating system are you using?
Linux and Android

**Comment by alexgibson** [comment]
Thanks for filing!

I believe Android Beta release notes are no longer being published on mozorg (see https://github.com/mozilla/bedrock/issues/10064)

We should remove this link (assuming release notes are not now published in some other place)

**Comment by itachi9604** [comment]
Hi @alexgibson , Please review this PR.
