### ISSUE TITLE
Update Hubs Logo on Innovation Dropdown

### ISSUE THREAD

**Issue by katetaylormoz** [mozilla/bedrock#12399]
## Description

The Hubs team is launching a new product and visual rebrand on Nov 29th 2022. We would like to change the current Hubs logo on the innovation drop down to the new Hubs logo.

LOGO HERE: https://drive.google.com/file/d/1uxSRBsn-pOmP0tNLlF0yBVk3bAcfFTpb/view?usp=share_link

---

#### Success Criteria
![Desktop Screenshot 2022 11 21 - 13 19 13 1](https://user-images.githubusercontent.com/100849201/203165575-b6075519-b686-446a-80f5-1fdc20922618.jpg)
![32x32 Hubs Logo](https://user-images.githubusercontent.com/100849201/203166061-4415ba0e-d417-4fce-912d-844d1a8667a3.svg)

- [ ] Change the Hubs Logo from the duck to our new logo image (blue)

**Comment by yzAlvin** [comment]
Never contributed to mozilla before, but I think I can do this one -- I requested access to the google drive

**Comment by katetaylormoz** [comment]
> Never contributed to mozilla before, but I think I can do this one -- I requested access to the google drive

Thank you so much! I am linking the new logo image below:
https://user-images.githubusercontent.com/100849201/203166061-4415ba0e-d417-4fce-912d-844d1a8667a3.svg
