### ISSUE TITLE
Migrate from CircleCI to GitHub Actions for pull requests

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12393]
# Description

Run both Python and JS tests against PRs using GitHub Actions, instead of Circle CI

## Success Criteria

- [ ] Python tests run and pass using GH Actions
- [ ] JS tests run and pass using GH Actions
- [ ] Failing tests block a PR merge, just a Circle currently does

**Comment by nathan-barrett** [comment]
Interested, If I get some time I may look more into this

**Comment by stevejalim** [comment]
@nathan-barrett This one will need a fair bit of backendy stuff, incl probably building runner machines on GCP. It's currently on my H1 2023 goals list, so gonna bag it, I'm afraid, but happy to run you through the outcome so you know more about how it all works

**Comment by stevejalim** [comment]
Updated the description with more context/info

**Comment by nathan-barrett** [comment]
Fair! Was interesting to look into this more yesterday!
