### ISSUE TITLE
possibly missing Firefox feature in mobile compare page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/bedrock#12403]
https://www.mozilla.org/en-US/firefox/browsers/mobile/compare/

I am not 100 % sure but does "Automatically fills out payments" mean the credit card autofill feature? If so, it's implemented in Firefox for Android, but the compare page says that Firefox don't support it.

**Comment by stephaniehobson** [comment]
The mobile comparison page has been decomissioned
