### ISSUE TITLE
Homepage update for pocket best of

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12406]
## Description

We will be updating the homepage to reflect Pocket's 'best of' campaign. 

The design will be mostly shared with the designs we are using for our December WNP.

[Deck with designs & copy](https://docs.google.com/presentation/d/1YWjdaK_A6y_CNA-3d0XULHzsmKG0Nc7pZXiNqVLBQLs/edit?usp=sharing)

---

#### Success Criteria
- [x] proper UTM params in place for tracking.

**Comment by alexgibson** [comment]
Demo links:

- English https://www-demo4.allizom.org/en-US/
- German https://www-demo4.allizom.org/de/
