### ISSUE TITLE
update  press/speakerrequest

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12404]
## Description

Update  `/press/speakerrequest/` to send requests to `press@mozilla.com`

**Comment by slightlyoffbeat** [comment]
@pmac @stevejalim @robhudson can one of you help size this request (XS/S/M/L). It seems small, but want to confirm. Can also ping a front-end dev is this is a front end question.

**Comment by robhudson** [comment]
It should be a one-line change here:
https://github.com/mozilla/bedrock/blob/main/bedrock/press/views.py#L20
