### ISSUE TITLE
Add a link to jobs RSS feed on /careers/listings/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12422]
## Description

We have an RSS feed of all open positions at Mozilla here: https://www.mozilla.org/en-US/careers/feed/

Adding a "Subscribe to our open positions RSS feed" link at the bottom of https://www.mozilla.org/en-US/careers/listings/ could be helpful, especially if people are keen to work at Mozilla but are waiting for the right position / location / role to open up.

---

#### Success Criteria
- [ ] RSS feed is linked from the careers listings page

**Comment by KiskaLE** [comment]
Hi, I am new to contributing to a big project, where do I find HTML files in the repository?

**Comment by reemhamz** [comment]
This is going to be added in https://github.com/mozilla/bedrock/pull/12286

**Comment by alexgibson** [comment]
Looks like this one was done
