### ISSUE TITLE
Careers RSS feed should include geographic locations relevant to a role

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12439]
## Description

[#12422](https://github.com/mozilla/bedrock/issues/12422) talks about surfacing the RSS feed for Careers more prominently. Trying that out now, I notice that the feed lacks the areas a role is available in. This would help a lot for consumers of the RSS feed.

---

#### Success Criteria
- [ ] Subscribers to the RSS feed are shown, in the body of the post, from which regions people are able to work from (e.g. "US Remote, Germany Remote, Berlin Office")

**Comment by Ayush-Kori** [comment]
Hey, I would like to work on this issue. Can u guide me??

**Comment by stevejalim** [comment]
Actually I've just noticed this is supported already. Thanks for the offer, though @Ayush-Kori
