### ISSUE TITLE
Move PBJ to Contentful

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12438]
## Description

We'd like to try moving Stories [Landing](https://www.mozilla.org/en-US/stories/) and [Article](https://www.mozilla.org/en-US/stories/joy-of-color/) pages to pull content from Contentful.

This will allow us to schedule releases and avoid time-sensitive prod pushes for copy updates (i.e. https://github.com/mozilla/bedrock/pull/12294). It also saves developer time from copy-heavy updates (i.e. https://github.com/mozilla/bedrock/pull/12420) and avoids any need for private development (i.e. https://github.com/mozilla/bedrock/pull/12264).

This content will be English only. The setup should be fairly similar to VRC Contentful (https://github.com/mozilla/bedrock/pull/10697 & https://github.com/mozilla/bedrock/pull/10806/).

---

#### Success Criteria

**Bedrock (test with Contentful sandbox env)** 
- [ ] Add Contentful templates for landing and article (Maureen)
- [ ] Refactor article styles to handle one block of content (Maureen)
- [ ] Update API logic to handle new PBJ-related content (Nathan & Maureen)
- [ ] Behind SWITCH_CONTENTFUL_PBJ, add url logic to serve content from Contentful templates*
- [ ] Add functional test to ensure switch is working as intended 
- [ ] Create migrations for the relevant sandbox Content Models and Content Entries (Compose pages) to be published on master env (test with new MERGE app first, fallback: code migrations)

**Contentful (in sandbox env)**
- [ ] Create _Contributor_ Content Model (Nathan)
- [ ] Create _Story_ (single article) Content Model (Nathan & Maureen)

basic structure here (Mozilla only): https://docs.google.com/document/d/1EihwjDN37JgJOrWKMipOvIEMMUCQr1VDIhCQ6bqLTlQ/edit

**Contentful Compose (same sandbox env)**
- [ ] Add Story Content Model as Compose Page Type (Nathan)
- [ ] Recreate existing articles (Nathan & Maureen)

~*Will this be problematic for the article pages that already have URLs?~ Nope, Django controls our URL logic so we can manage this behind the switch

## Deployment (WIP)

Part 1: ADDITIONS
1. Migrate content models and new PBJ content to pre-production env
2. Merge code changes to ??? (staging? to-be-created contentful branch? merging to main would block other prod pushes)
3. Test on ???
4. Migrate content models and new PBJ content to master env
5. Merge code changes to main

(once all is well on prod, create new issue for removal of deprecated code)

Part 2: SUBTRACTIONS
1. Remove bedrock static PBJ pages and related code (including www-config switch)
2. Merge code changes to ??? (staging? to-be-created contentful branch? merging to main would block other prod pushes)
3. Test on ???
4. Merge code changes to main

**Comment by stevejalim** [comment]
@maureenlholland @nathan-barrett Would it help if i write up a How To for using the Contentful migrations framework we've settled on? You can test drive the migration against your own fork of Sandbox

**Comment by maureenlholland** [comment]
@stevejalim sounds good, thanks!
