### ISSUE TITLE
Migrate l10n pipeline from Gitlab to GH Actions

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12440]
## Description

Our current l10n ingestion pipleine uses Gitlab CI. We should move that to GH Actions, in order to have one less step in the chain.

---

#### Success Criteria
- [ ] Gitlab-based behaviour is understood prior to the move
- [ ] Overall behaviour when using GHActions is the same as with Gitlab - no degradation in service

**Comment by alexgibson** [comment]
Pretty sure this one is done, but feel free to re-open if not
