### ISSUE TITLE
What's New Page inappropriately tells the user to restart to update

### ISSUE THREAD

**Issue by bytesized** [mozilla/bedrock#12444]
## Description

The What's New Pages ([example](https://www.mozilla.org/en-US/firefox/103.0/whatsnew/?oldversion=102.0.1&v=1)) show a banner at the top that seems to either say "Congrats! You’re using the latest version of Firefox." or "An even newer Firefox is available. Restart to update."

The first message is fine, but the second message is not. The site does not seem to have any way of knowing if the update has actually been downloaded. And if one hasn't, restarting will do nothing. Generally, the What's New page is shown directly after an update and Firefox checks for new updates on a timer. So, typically, when this message is shown, there is no update downloaded yet and the message will simply be incorrect.

### Steps to reproduce

1. Install an out-of-date copy of Firefox such as [this one](https://archive.mozilla.org/pub/firefox/releases/105.0/).
2. Open a what's new page such as [this one](https://www.mozilla.org/en-US/firefox/103.0/whatsnew/?oldversion=102.0.1&v=1).

### Expected result

It would be fine if it linked to an article on how to update. It would be kinda cool if it could hook into the browser to provide a link that could open the in-browser update interface. Frankly, it would be ok for it to say absolutely nothing. But giving the user incorrect instructions on how to update is not appropriate.

### Actual result

Incorrect update instructions were given.

**Comment by alexgibson** [comment]
Thanks for filing this issue @bytesized.

I think adding a SUMO link to the message is a good suggestion. Unfortunately the website has no way to tell if there's an update pending in the background, which as you say isn't guaranteed.

**Comment by alexgibson** [comment]
This seems like the appropriate SUMO article to link to: https://support.mozilla.org/kb/update-firefox-latest-release
