### ISSUE TITLE
Codecov is very confused

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12477]
## Description

Codecov seems to be confused in the comments it adds to pull requests. Looking at https://app.codecov.io/gh/mozilla/bedrock/pulls shows many PRs have reported a ~13%~ 0.13% increase in coverage recently, which is incorrect. It seems that commit https://github.com/mozilla/bedrock/commit/851b333fa27aeeed02e76f16435caad8f55dcb37 is often considered as base, by Codecov, which is used to compare and calculate the coverage report.

This lines up to around the time we renamed `master` to `main`, so it's possibly been incorrect for a good while.  

The branch context has been updated to `main` in [settings](https://app.codecov.io/gh/mozilla/bedrock/settings), but the issue still seems to remain.

**Comment by stevejalim** [comment]
@alexgibson I see a bump of 0.13%, not 13%. However, we could zap the coverage history and regenerate new stats - that should give us a new baseline - gonna try that now

**Comment by stevejalim** [comment]
Update: I got 

> We were unable to delete coverage for this repository

So it's possible something's up at the CC end. Will drop them a line

**Comment by stevejalim** [comment]
Also, when i look at the stats when using the Mozilla identity not my personal identity, I don't see the 0.13 change at all. Odd.

**Comment by alexgibson** [comment]
Closing this, haven't seen any weirdness for the last couple of weeks :)
