### ISSUE TITLE
Search listing for Desktop page is truncated, doesn't say "Desktop"

### ISSUE THREAD

**Issue by a-kyne** [mozilla/bedrock#12487]
## Description

Search listing for .../en-US/firefox/new/ doesn't say "Desktop", and is truncated in search results
![image](https://user-images.githubusercontent.com/104653010/207909070-37fdbfb5-6d52-4e57-a37f-acc8ec28708c.png)

Current title is:
 <title>
    Download Firefox Browser — Fast, Private &amp; Free — from Mozilla
  </title>

Description is:
content="Get Firefox, a free web browser backed by Mozilla, a non-profit dedicated to internet health and privacy. Available now on Windows, Mac, Linux, Android and iOS.">

**Update title to:**
<title>Download Firefox for Desktop — from Mozilla</title>

**Update description to:**
content="Get Firefox for Windows, Mac, or Linux. Firefox is a free web browser backed by Mozilla, a non-profit dedicated to internet health and privacy.">

**Comment by Ayush-Kori** [comment]
Hey can I take up this issue ??

**Comment by alexgibson** [comment]
@Ayush-Kori thanks for showing interest in contributing!

If you would like to take a go at working on this issue please feel free. You can find our getting started information here: 

- https://bedrock.readthedocs.io/en/latest/install.html
- https://bedrock.readthedocs.io/en/latest/contribute.html

Please note that Mozilla employees may not always have spare time to help mentor contributors. However, if you have any questions on this particular issue at hand, then feel free to ask here. Thanks again!
