### ISSUE TITLE
Users cannot join the waitlist for Mozilla VPN

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#12484]
## Description

Users cannot join the waitlist for Mozilla VPN

### Steps to reproduce

1. Go to [Mozilla VPN: Protect Your Entire Device](https://www-dev.allizom.org/en-US/products/vpn/);
2. Click on the “Join the Waitlist” button;
3. Fill in all the mandatory fields;
4. Click on “Join the Waitlist” button;
![image-20221214-114757](https://user-images.githubusercontent.com/52028275/207820316-607ca5b1-f679-4742-baa1-ea9d2d3df6ea.png)

### Expected result

A success page is loaded.

### Actual result

An error message is displayed on the page

### Environment

Staging environment, all browsers

**Comment by alexgibson** [comment]
@LuminitaB Hi, the page you have linked to here is our [dev server](https://www-dev.allizom.org/en-US/products/vpn/invite/), which isn't configured for the waitlist email. Please test against the production page: https://www.mozilla.org/en-US/products/vpn/invite/

**Comment by alexgibson** [comment]
I'll see if there's any way we can set this up so the email works for dev, but it's not a user facing issue.

**Comment by alexgibson** [comment]
@pmac think we can enable this on www-dev, so that product QA can test the basic form functionality? (even if they won't get an actual email)

**Comment by pmac** [comment]
Should work now.

**Comment by alexgibson** [comment]
Great, thanks!
