### ISSUE TITLE
Updates to Firefox Focus page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12499]
## Description

There is an updated needed for all languages at /firefox/browsers/mobile/focus/

Updates will be described in [this document](https://docs.google.com/document/d/15dtdpiHLTymvaYVyrZMO8hRLBBqYwVAiH6TpcfdR4Oc/edit?usp=sharing).

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by alexgibson** [comment]
I don't have edit access to the doc, so I'll not here that there's another update that needs changing in the "See it all faster" section. The meta description also needs updating.

They both seem like straight forward things to update without needing new copy, so I'll make those additionally in the PR here.
