### ISSUE TITLE
Add config for recommended VSCode extensions

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12515]
## Description

See: https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions

Possible list of extensions we could recommend for bedrock dev?

- [ms-python.python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
- ~[wholroyd.jinja](https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja)~
- [EditorConfig.EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
- [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [streetsidesoftware.code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by reemhamz** [comment]
My suggestions: 

- [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens): We have a large and old code repository, I like to make sure I have this extension enabled when scouring some old code so I can go to the PRs + issues the code is related to
- [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext): Support for our Bedrock docs. Includes linting and previews

**Comment by pmac** [comment]
* [.env file support](https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv)
* [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)
* [Fluent](https://marketplace.visualstudio.com/items?itemName=macabeus.vscode-fluent)

**Comment by nathan-barrett** [comment]
I prefer to use [this jinja extension](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml) than the other (i've even contributed to it!)

**Comment by alexgibson** [comment]
> I prefer to use [this jinja extension](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml) than the other (i've even contributed to it!)

Happy to switch to whichever one we prefer!

**Comment by alexgibson** [comment]
I should also add - these are just recommendations. Folks don't have to install them if they don't want to, or prefer to use something else.
