### ISSUE TITLE
Legal documents are taken from default branch instead of prod

### ISSUE THREAD

**Issue by flodolo** [mozilla/bedrock#12529]
It looks like the Pocket website is getting documents from the default branch `main` instead of `prod`.

This morning I visited
https://getpocket.com/it/tos/
https://getpocket.com/it/privacy/

And they're localized in Italian. But the localized version was only available on the default branch (`main`), I've merged the [PR to copy](https://github.com/mozilla/legal-docs/pull/1857) them to production only a few minutes ago.

**Comment by flodolo** [comment]
This just happened for the Firefox PN, so it's not just Pocket.

**Comment by flodolo** [comment]
The code [seems correct](https://github.com/mozilla/bedrock/blob/30aded18640f67e417ccd077914a77c89e8ad8f6/bedrock/settings/base.py#L1131). Can it be that we're running prod as DEV??

For reference, mozilla.org had [this change](https://github.com/mozilla/legal-docs/pull/1859/files) before I pushed the change to the `prod` branch.

**Comment by pmac** [comment]
Everything I can see when checking production says that the value for `LEGAL_DOCS_BRANCH=prod` and `DEV=False`. I can't see how this could be happening unless we have a rogue automation moving everything to prod or something else is uploading databases for prod. I'm still looking.

**Comment by flodolo** [comment]
The legal-docs repository is safe. Push to production is only manual, and it's clear from the 2 PRs that the documents in question were not available in `prod` yet.

But here's another proof: I've just pushed a [small change](https://github.com/mozilla/legal-docs/commit/f0daa62f5619e4f8d3c35e282c58b9f101d97bfd) to the Italian version of Focus PN, and that's only in `main`.

You need to click the `Ulteriori informazioni` link to expand, but both [production](https://www.mozilla.org/it/privacy/firefox-focus/) and [dev server](https://www-dev.allizom.org/it/privacy/firefox-focus/) are showing `campagne di marketing`, while prod should still show `campagne marketing`(see [markdown file here](https://github.com/mozilla/legal-docs/blob/prod/it/focus_privacy_notice.md) in the `prod` branch).

**Comment by alexgibson** [comment]
What's odd here is that neither of the actual deployments are showing the latest change in https://github.com/mozilla/bedrock/issues/12529#issuecomment-1368171475

- https://bedrock.prod.fr.moz.works/it/privacy/firefox-focus/
- https://bedrock-prod.gcp.moz.works/it/privacy/firefox-focus/

Are we pointing to something else at the CDN level?

The newer (not yet supposed to be live) infra is showing `di marketing`: https://stage.bedrock.nonprod.webservices.mozgcp.net/it/privacy/firefox-focus/

**Comment by alexgibson** [comment]
Oh weird, now I no longer see it at https://www.mozilla.org/it/privacy/firefox-focus/ either

**Comment by alexgibson** [comment]
I see the issue again: the back-end sever is: `bedrock-prod-web-55c8c87fbf-h7dw4.mozmeao-fr`

**Comment by alexgibson** [comment]
Can confirm there is something happening where commits from the `main` branch are being used in prod:

https://bedrock.prod.fr.moz.works/healthz-cron/

<img width="385" alt="image" src="https://user-images.githubusercontent.com/400117/210357931-0613fd6a-9dd0-469b-801c-5adc3c4812df.png">



https://github.com/mozilla/legal-docs/commit/f0daa62f5619e4f8d3c35e282c58b9f101d97bfd

**Comment by stevejalim** [comment]
Can confirm this also applies to GCP prod, not just AWS / Frankfurt prod at this point in time

<img width="731" alt="Screenshot 2023-01-03 at 12 34 07" src="https://user-images.githubusercontent.com/101457/210358292-2f73b166-96cb-4f76-ab3b-d0c97fecc32b.png">

**Comment by alexgibson** [comment]
This turned out to be a DB/clock sync issue, which was fixed by our backend / infra folks yesterday. Should be good now.
