### ISSUE TITLE
Some locales are intermittently redirected to a 404 on dev

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12521]
## Description

Whist investigating some intermittent [test failures](https://gitlab.com/mozmeao/www-config/-/pipelines/729109771/failures) on dev I happened to spot a locale redirection issue that might be the cause of said failures.

### Steps to reproduce

1. Open https://dev.bedrock.nonprod.webservices.mozgcp.net/nl/firefox/
2. Keep refreshing the page

### Expected result

The URL should always return a 200 response.

### Actual result

About 1 times out of ten or so, the URL redirects to a 404:

https://dev.bedrock.nonprod.webservices.mozgcp.net/en-US/nl/firefox/

### Environment

N/A (reproducible in any browser / env)

**Comment by alexgibson** [comment]
Another observation from the test failures:

1. Open https://dev.bedrock.nonprod.webservices.mozgcp.net/sv-SE/firefox/welcome/4/
2. Refresh the page a bunch of times

Expected result:

The `sv-SE` locale should always return a 200

Actual result:

Sometimes the page simply redirects to en-US: https://dev.bedrock.nonprod.webservices.mozgcp.net/en-US/firefox/welcome/4/

I wonder if there's a pod somewhere that doesn't have locales enabled?

**Comment by alexgibson** [comment]
I'm not clear if anything was done here, but I'm no longer able to reproduce either of the two issues above today.

I guess we'll need to keep an eye on dev test runs to see if we see any more failures like this.

**Comment by bkochendorfer** [comment]
Yeah I just tried and was unable to recreate as well.

**Comment by alexgibson** [comment]
Gonna close this one as can't reproduce, but will keep an eye out for more test failures like this.

**Comment by alexgibson** [comment]
We had a couple more redirect failures after a merge to dev, so going to re-open this:

https://gitlab.com/mozmeao/www-config/-/jobs/3552743956#L5048

**Comment by alexgibson** [comment]
Ok yeah, I can hit this manually also by visiting https://dev.bedrock.nonprod.webservices.mozgcp.net/pt-BR/ and refreshing the page. Sometimes it redirects to `/en-US/` instead.

**Comment by alexgibson** [comment]
Looks like we also saw a similar failure on stage yesterday as well: https://gitlab.com/mozmeao/www-config/-/jobs/3549470186

**Comment by stevejalim** [comment]
It's not always the same locale - i just saw an expected `/nl/` getting redirected to `/en-US/`, too

**Comment by alexgibson** [comment]
Can we close this out as fixed? (I think we can but wasn't 100% sure)
