### ISSUE TITLE
Wrong translation in donation banner (German)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/bedrock#12531]
German version of the donation banner on mozilla.org:

<img width="758" alt="Bildschirm­foto 2023-01-01 um 11 50 07" src="https://user-images.githubusercontent.com/1100614/210168097-100f4776-644f-4b61-9524-7cc724f3040e.png">

"Helfen Sie Mozilla diese Weihnachten" should be "Helfen Sie Mozilla diese**s** Weihnachten" (diese -> dieses; it's singular in English and should therefore be Singular in German as well -- and the Plural of "Weihnachten" is unusal in German anyway, except in wish formulas like "merry christmas!" / "Frohe Weihnachten!", but that's not the case here).

**Comment by alexgibson** [comment]
This banner text no longer exists, closing
