### ISSUE TITLE
Release notes redirection behaviour isn't consistent across Desktop and Mobile

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12536]
## Description

If a user goes to https://www.mozilla.org/en-US/firefox/releasenotes/ they get redirected to the latest release notes URL for Firefox - eg currently https://www.mozilla.org/en-US/firefox/108.0.1/releasenotes/

However, that behaviour doesn't exist for mobile FF release notes - eg the following two links trigger a 500

* https://www.mozilla.org/en-US/firefox/android/releasenotes/
* https://www.mozilla.org/en-US/firefox/ios/releasenotes/ 

### Steps to reproduce

See above

### Expected result

The URLs for mobile Firefox should redirect to the latest releasenotes for the relevant mobile platform

### Actual result

The user gets the HTTP 500 / "Something went wrong" page

### Environment

All

## Success criteria

The expected result, above, is achieved, and we have new unit test coverage to confirm this

### Developer tips:

* To get the latest data, including all the releasenotes data, into your local build, you can use the `make preflight` command in your local checkout of Bedrock

**Comment by itachi9604** [comment]
Hi @stevejalim , I have checked locally , it shows release_notes is missing 1 positional  argument 'version'. Also checked redirects file in bedrock/firefox looks like the version is not getting through when redirecting.

**Comment by stevejalim** [comment]
Hi @itachi9604 - thanks for starting to explore. If you think there's a refactor/improvement you can carry out that might catch this error and redirect to the latest version of the release notes, that'd be great.

If you need suggestions, I can have a think. Off the top of my head, I am wondering if we can set a default parameter of `version='latest'` in the view and redirect to the appropriate release notes page if, in the body of the function, `version` is `"latest"`

**Comment by stevejalim** [comment]
Thanks for looking into the ticket @itachi9604 - I've just had a go and raised https://github.com/mozilla/bedrock/pull/12605 to fix it. If you'd like to take a look at the PR and review, you're welcome to!
