### ISSUE TITLE
Redirects from mozilla.org -> www.mozilla.org duplicate query params

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12535]
## Description

When hitting a redirect from mozilla.org to www.mozilla.org, query parameters are duplicated.

### Steps to reproduce

1. Open https://mozilla.org/en-US/?foo=bar

### Expected result

URL should be redirected to https://www.mozilla.org/en-US/?foo=bar

### Actual result

URL is redirected to https://www.mozilla.org/en-US/?foo=bar?foo=bar

### Environment

Firefox Nightly
macOS

**Comment by bkochendorfer** [comment]
https://github.com/mozilla-it/refractr/pull/265

**Comment by bkochendorfer** [comment]
Fix is finally out in production!
