### ISSUE TITLE
WNP 109 (EU)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12542]
## Description

Request to create WNP for Firefox 109 (EU) featuring PDF editor.

- Figma file: https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-23?node-id=2391%3A723&t=7ubxCwfXGy16qAf9-1
- Copy doc: https://docs.google.com/document/d/1tQtq15R2ZigjZpFOvvYzoOacraEUckIkdw6Y6mhpvL0/edit#
- Image assets / PDF: https://drive.google.com/drive/folders/13CAItW-fyfqwAQArDSH_9n-kq_rYtFPH

We'll need to upload the PDF to assets.mozilla.net.

Target countries / locales are: UK (en-gb + en-us geo=gb), DE and FR.

Needs to be live for 17th Jan.

---

#### Success Criteria
- [ ] WNP 109 is live for EU countries / locales for requested date.

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12561
