### ISSUE TITLE
Mozilla home page banner (VPN)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12540]
## Description

Request to create a new Mozilla home page banner featuring VPN (replaces Pocket banner).

- Mock here: https://docs.google.com/presentation/d/13f-jnIQwOhEE_GH8lrPP0aRUIR8rGi2ht6nPz_VWSUg/edit#slide=id.g1c02f3c223e_6_80
- Figma: https://www.figma.com/file/bGYqaFkQ2GYAt4clq6aaeu/Q1-Everyday-Privacy?node-id=2765%3A2&t=rVnvqXilNlOF3g89-1
- Image files: https://drive.google.com/drive/folders/12pD7YVpAluEtrdsmTAenaPZQKD4TlBGU

Go live date is 17th Jan

---

#### Success Criteria
- [ ] VPN home page banner is live for the requested date.

**Comment by stephaniehobson** [comment]
Since the Pocket banner was deactivated (https://github.com/mozilla/bedrock/issues/12543) is this replacing the `homepage-firefox-mr106-promo` banner now?

**Comment by stephaniehobson** [comment]
Also, just to confirm - English only?

**Comment by alexgibson** [comment]
@stephaniehobson I think the answer is yes to both questions. If you would like to confirm, I'd suggest contacting `@Celia` (lead creative producer) on Slack.

**Comment by stephaniehobson** [comment]
Do we have a  way to scheduled the Jan 17th flip? Or do we still just bribe someone in the UK?

**Comment by alexgibson** [comment]
@stephaniehobson I'm not sure if they have specified a time, so my guess is early on the 17th (PT) will be fine. Happy to help flip the switch earlier that day if needed though - just let me know!
