### ISSUE TITLE
WNP 109 (en-US)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12541]
## Description

Request to create WNP for Firefox 109 (en-US) featuring Mozilla VPN.

- Mock: https://docs.google.com/presentation/d/13f-jnIQwOhEE_GH8lrPP0aRUIR8rGi2ht6nPz_VWSUg/edit#slide=id.g1bc2ed3eb87_0_22
- Copy doc: https://docs.google.com/document/d/1MhYYhE1BVVldzu9BFbuYXTYl1zQ5Gn8yvi9b2Wy4F8Y/edit?usp=sharing
- Figma https://www.figma.com/file/bGYqaFkQ2GYAt4clq6aaeu/Q1-Everyday-Privacy?node-id=2765%3A2&t=rVnvqXilNlOF3g89-1
- Image files: https://drive.google.com/drive/folders/1Mj8IogWKh_nEqYRGCwH-R0k4cwAbKZlp

Needs to be live for 17th Jan.

---

#### Success Criteria
- [ ] WNP 109 is live for en-US for requested date.

**Comment by reemhamz** [comment]
Updated mock URL: https://docs.google.com/presentation/d/1mR8scfQyU9wu2nFONAdbLRtQJqECV1bSnOnV_gsSyTk/edit#slide=id.g1bc2ed3eb87_0_22

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12561
