### ISSUE TITLE
[L10n]: CSS for locale `skr` should be for RTL

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#12567]
## Description

The current setting for locale `skr` is incorrect. This is an RTL locale. The display is LTR.

### Steps to reproduce

https://www-dev.allizom.org/skr/. 

### Expected result

Fix the CSS so RTL is used for `skr`.

**Comment by peiying2** [comment]
<img width="1352" alt="Screenshot 2023-01-06 at 11 53 45" src="https://user-images.githubusercontent.com/6090393/211089150-33eb2ef2-429f-4008-8305-ac2270a4252e.png">

**Comment by pmac** [comment]
Followup to #12553

**Comment by pmac** [comment]
We use Django's default list of RTL languages currently:

```python
LANGUAGES_BIDI = ["he", "ar", "ar-dz", "ckb", "fa", "ur"]
```

Is `skr` the only new one we need to add?
