### ISSUE TITLE
Remove /exp/ experiments app

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12563]
## Description

We have an `/exp/` app in bedrock that was at one time used for experiment pages, integrated with a tool called Convert.

We still have a license for Convert, but it has not been used in well over a year. Even if we do return to using it, I think it's likely we would want to reconsider our approach, especially because we are no longer using the CloudFlare workers that used to redirect traffic to it.

I think it's probably best if we remove this `/exp/` app for now. But we could still keep the Convert bundle / integration code for if/when we next use it.

---

#### Success Criteria
- [ ] `/exp/` app is removed from bedrock

**Comment by itachi9604** [comment]
Hi @alexgibson , should I start working on this?

**Comment by alexgibson** [comment]
@itachi9604 thank you for showing interest, but I want to make sure we retain certain files related to this issue, so I'm going to work on it myself. Thanks for your understanding.

**Comment by alexgibson** [comment]
@slightlyoffbeat I've made a PR that removes these old `/exp/` pages, whilst retaining the ability to load Convert on a page behind a feature switch, should we ever revisit using it again. I think this makes the most sense for now, rather than retaining the setup we once had. We're no longer using the Cloud Flare workers to redirect traffic now anyways.

Does this sound OK to move forward with to you? Thanks

**Comment by slightlyoffbeat** [comment]
@alexgibson We haven't had an active convert subscription for a few months, but we will be re-upping in the next month or two. But:
1. There is not a clear plan for how it will be used, or how often it will be used
2. I agree that we should revisit our entire approach.

Good with me to move forward.
