### ISSUE TITLE
Update /truecolors/ vanity redirects to point directly to /firefox/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12613]
## Description

We have some [vanity redirects](https://github.com/mozilla/bedrock/blob/main/bedrock/mozorg/redirects.py#L546) that point to https://truecolors.firefox.com/. That website no longer exists, and now redirects to https://www.mozilla.org/firefox/.

We might as well update those redirects to point directly to /firefox/ now

**Comment by Soumya0803** [comment]
Hi @alexgibson 
I would like to work on this issue.

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/13998
