### ISSUE TITLE
Typo on privacy page

### ISSUE THREAD

**Issue by wsmwk** [mozilla/bedrock#12616]
https://www.mozilla.org/en-US/privacy/ should read "if it is up to date", missing the word "it", in  this bullet 

we collect it automatically through our products and services (e.g., when your Firefox browser checks with us to see if is up to date);

**Comment by stevejalim** [comment]
Thanks for flagging. Transferring over to the legal-docs repo

**Comment by stevejalim** [comment]
Closing after porting to https://github.com/mozilla/legal-docs/issues/1864
