### ISSUE TITLE
Add Google Tag Manager to Pocket Bedrock pages

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12624]
## Description

We have a dedicated container for getpocket.com. We can implement in the same way we do for GTM on mozilla.org

For GTM snippets, please contact @slightlyoffbeat, and he will provide.

**Comment by maureenlholland** [comment]
**note:** the new GTM container will replace the direct link to GA4 tag we implemented via gtag.js (the GTM_CONTAINER_ID setting variable already exists, it's just not currently pointing to a GTM ID or loading the gtm.js script)
https://github.com/mozilla/bedrock/pull/12433
