### ISSUE TITLE
Nightly release notes RSS feed throws XML parsing error

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12622]
## Description

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Fnightly%2Fnotes%2Ffeed%2F

Reported via Mastodon: https://mastodon.social/@simevidas/109725975684671231

**Comment by stevejalim** [comment]
The content had an unnecessary line break in it, so I've removed that in Nucleus as the fastest fix for end users. 

However, it would be good to check these feeds parse correctly, too. One for www-site-checker @alexgibson ?

**Comment by alexgibson** [comment]
@stevejalim adding it to the checker sounds good to me, but I also wonder if we could sanitize this type of thing in bedrock better using bleach?

**Comment by stevejalim** [comment]
💯 yep!

**Comment by stevejalim** [comment]
Feed is now valid, following Release Notes tweak https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Fnightly%2Fnotes%2Ffeed%2F

**Comment by stevejalim** [comment]
As discussed in Slack, the actual `<br>` making its way into the feed was a source-data niggle that's not necesarily worth building a mitigation for right now. Going to capture more data via www-site-checker (https://github.com/mozmeao/www-site-checker/issues/133) and see how things look
