### ISSUE TITLE
Update the "Donate" link in the footer to use our new donation platform

### ISSUE THREAD

**Issue by mtdenton** [mozilla/bedrock#12628]
## Description

On the MoFo side, we're actively transitioning from donate.mozilla.org to a new donation platform named Fundraise Up. We'd like to request an update to the "Donate" footer link on mozilla.org to reflect that change and point users to the appropriate donation form.

![mozilladonate](https://user-images.githubusercontent.com/41487159/214437147-e2558c4e-f019-425f-8ac8-5524cd0fc777.jpg)

---

#### Success Criteria
- [ ] `href` of the footer link circled above is changed to `https://foundation.mozilla.org/?form=donate&utm_source=mozilla.org&utm_medium=referral&utm_content=company&utm_campaign=footer`

**Comment by alexgibson** [comment]
@mtdenton thanks for filing this issue. A couple more questions that might be useful here to complete this task:

1. Should we continue to provide suggested currency and presets as query parameters? Here's an [example footer link](https://donate.mozilla.org/?presets=60,30,20,10&amount=30&utm_source=mozilla.org&utm_medium=referral&utm_content=company&currency=gbp&utm_campaign=footer) that we currently render to someone in the UK. Note the `presets`, `amount`, and `currency` parameters ^

2. Do we also need to update the fundraising form? (visible on our [dev server here](https://www-dev.allizom.org/en-US/)). This currently relies on passing through the same parameters.

**Comment by mtdenton** [comment]
@alexgibson sorry for the delay, missed this tag somehow.

1. For the presets, Fundraise Up is pretty good about detecting currency based on IP address so no need to send that info along any more from what we can see. In place of `presets=` we now only have `amount=` available to us, so we can safely drop `presets=`.

2. Eventually, the MoFo Fundraising Team may make the request to move to a one-button CTA on this banner just to simplify things for the user. In the meantime however (and assuming this is much simpler), you can use the same `amount=` parameter to retain that functionality, and `recurring=once`/`recurring=monthly` to account for the radio buttons. As with the footer link, we can keep the currently implemented UTM parameters as well. For reference, a list of available parameters is [here].(https://fundraiseup.com/docs/url-api/)

Let me know if there are any additional details needed and thank you for the questions!
