### ISSUE TITLE
Ensure prod-only data stream for GA4

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12630]
## Description

No views in GA4. No ability to filter by hostname. That means we're probably getting mixed data in our single GA4 property for mozorg (the script is available across localhost, dev, staging, and prod).

GA4 offers [a filter option to identify and exclude internal traffic](https://support.google.com/analytics/answer/10104470), but it is based on IP addresses and likely too brittle to be sustainable.

We need to be certain we are not mixing data. Does this mean a separate GA4 property for development use or a separate GTM container (or both)?

---

#### Success Criteria
- [x] We can identify Mozorg GA4 data from prod only
- [x] We can identify Pocket GA4 data from prod only

**Comment by maureenlholland** [comment]
are purpose-built testing options available? better than GA debug view?

also, if we can't use the internal traffic filter, does the developer traffic filter work?
https://support.google.com/analytics/answer/10108813

> Developer traffic originates from your app on development devices, and is identified with the event parameter debug_mode=1 or debug_event=1. If you exclude developer traffic via a filter, you can still see it in [DebugView](https://support.google.com/analytics/answer/7201382), so your developers can always validate their Analytics instrumentation.
> 
> If you don't specifically exclude developer traffic via filter, then that traffic appears in your reports.

**Comment by maureenlholland** [comment]
https://support.google.com/analytics/answer/7201382?hl=en#zippy=%2Cgoogle-tag-websites%2Cgoogle-tag-manager-websites

GTM container:
- no obvious way to add the `debug_mode` field in the init script, [examples from the docs only handle GA4 configuration tag in GTM dashboard](https://support.google.com/analytics/answer/7201382#zippy=%2Cgoogle-tag-manager-websites), which would affect all events in all environments, not viable since we're already in prod use
- preview mode or [chrome extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jiokjpcfnipnicblkgdklknjjeohnfln?hl=en) are in debug mode by default

> If debug_mode is true (either on the Configuration Tag or single tags/events), all consequent events (i.e., ecomm transactions) will not appear on Google Analytics reports.

GTAG:
- has a `debug_mode` param in config code
- **important**: the param must be OMITTED when you do not want to be in debug mode, setting it to false will have no effect

> To disable debug mode, exclude the 'debug_mode' parameter; setting the parameter to false doesn't disable debug mode.

**Comment by maureenlholland** [comment]
I would recommend we **do not set GTM_CONTAINER_ID anywhere other than prod.**
**Locally, devs can add the ID and use Preview mode** in the GTM dashboard for specific tasks.

**Comment by maureenlholland** [comment]
Having a separate GA4/GTM test property/container research in progress

**Comment by alexgibson** [comment]
> I would recommend we do not set GTM_CONTAINER_ID anywhere other than prod.

My 2 pence here: I think it's still important we have GA enabled on staging, which should mimic prod as closely as possible. That way we can catch any GA related errors that might occur before things reach production.

**Comment by alexgibson** [comment]
Another thing to consider here:

How much data is actually generated by dev / stage / demos currently? It might actually be not that much.

for automated tests, we attach an `?automation=true` parameter to all page loads. For Glean, we filter those out from prod data tables [here](https://github.com/mozilla/bedrock/blob/main/media/js/glean/init.es6.js#L26-L30). Perhaps this is something more easily achievable in GA4's reporting?

**Comment by maureenlholland** [comment]
Leaving open as this has not been completed for Pocket yet but the Mozorg fix was completed with the 2.3 version update in Mozorg GTM Container

**Comment by maureenlholland** [comment]
closed with https://github.com/mozilla/bedrock/pull/12638 and update to version 1.0 in Pocket GTM Container
