### ISSUE TITLE
Images not loading on the VPN staging page

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#12633]
## Description

The carousel images are not loading on the VPN staging page: https://www-dev.allizom.org/en-US/products/vpn/

### Steps to reproduce

1. Go to https://www-dev.allizom.org/en-US/products/vpn/ and tke a look at the images on the page.

### Expected result

The page is loaded without iossues and all the images are displayed

### Actual result

The carousel images are not loading and a **404 Not Found** error is dislayed in the console
 (see attached screenshot)
![image](https://user-images.githubusercontent.com/52028275/214610319-2afa13bc-cf03-49c8-8953-574ae0647ef2.png)

### Environment

Staging, Firefox Release v.109.0
The issue reproduces on Chrome as well.

**Comment by stevejalim** [comment]
Looks like 404s on the images themselves eg https://www-dev.allizom.org/en-US/products/vpn/img/products/vpn/landing/vpn-hero-01-high-res.png

**Comment by stevejalim** [comment]
@alexgibson Could this be the img helper change that just landed? I'd expect to see /media/ at the route of that path. Looks like we're appending the image path of /img/products/vpn/landing/vpn-hero-01-high-res.png to the main url of https://www-dev.allizom.org/en-US/products/vpn/

**Comment by LuminitaB** [comment]
Although, whem I inspect the element, I see another link, which loads the image: https://www-dev.allizom.org/media/img/products/vpn/landing/vpn-hero-05.b4e62ce229a0.png
![image](https://user-images.githubusercontent.com/52028275/214611576-9688ac5d-1fc5-4aa4-af82-b5b3d1beac50.png)

**Comment by alexgibson** [comment]
Thanks for the report, will take a look at this

**Comment by alexgibson** [comment]
PR with fix here: https://github.com/mozilla/bedrock/pull/12635

**Comment by LuminitaB** [comment]
This issue has been verified as **Fixed**.
Thank you.
