### ISSUE TITLE
Pocket site should only load GA after it gets an active signal from OneTrust

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12670]
## Description

The logged out Pocket marketing pages should only be loading GA after we get a signal from the OneTrust cookie consent banner.

### Steps to reproduce

1. Open https://getpocket.com/en/about/
2. Click "Manage" in the cookie consent popup
3. Click "Analytics Cookies" in the cookie preferences window.
4. Click the toggle to disable analytics cookies.
5. Click "Confirm"
6. Reload the page.

### Expected result

Google Analytics should not be loaded.

### Actual result

Google Analytics is still loaded.

### Environment

Reproducible in any browser

**Comment by alexgibson** [comment]
Pseudo code:

```
function OptanonWrapper() {
  var activeGroups = window.OptanonActiveGroups;

   if (typeof activeGroups === 'string' && activeGroups.indexOf('C0002') === -1) {
       console.log('load analytics');
   } else {
       console.log('do not load analytics');
   }
}
```

**Comment by Aadijindal07** [comment]
function OptanonWrapper() {
  var activeGroups = window.OptanonActiveGroups;

  if (typeof activeGroups === 'string' && activeGroups.indexOf('C0002') !== -1) {
    // Check if the "Analytics Cookies" toggle is enabled
    var analyticsCookiesEnabled = localStorage.getItem("analyticsCookiesEnabled");
    if (analyticsCookiesEnabled === "true") {
      console.log("load analytics");
      // Load Google Analytics code here
    } else {
      console.log("do not load analytics");
    }
  } else {
    console.log("do not load analytics");
  }
}

try this possibly it would work
