### ISSUE TITLE
[pocket] Some pages are missing "Cookie preferences" link in footer

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12678]
## Description

As per https://help.getpocket.com/article/1163-pocket-website-cookies-faq there should be a "Cookie preferences" link  in the footer of every Pocket web page.

### Steps to reproduce

1. Open https://getpocket.com/en/
2. Scroll to footer

### Expected result

"Cookie preferences" link should exist.

### Actual result

Link does not exist.

It looks like the link is missing from pages that load `pocket/includes/footer-platform.html`

### Environment

Firefox Nightly
macOS

**Comment by stevejalim** [comment]
That link is added by the OneTrust JS.

If it helps, according to Joel K in [this doc](https://docs.google.com/document/d/1cGSNdRfyjEvloNESYCNkSlVWjJX8KEMGlkh_d-Fnzrw/edit#heading=h.7iygif20vzg): 

> That is link is injected based on the presence of id="ot-sdk-btn"

**Comment by alexgibson** [comment]
I don't believe it gets added by the JS, it needs to be manually inserted like here: https://github.com/mozilla/bedrock/blob/main/bedrock/pocket/templates/pocket/includes/footer.html#L91

The trick is to make sure it has the right ID and class name

**Comment by stevejalim** [comment]
That's kind of what I meant - I think when the OneTrust JS sees `id="ot-sdk-btn"` it replaces the element's contentwith its own string. That's just based on me seeing that the localised label isn't used - eg at the bottom of https://getpocket.com/fr/about/ we see "Cookie Preferences" but the page source for that page has "Préférences en matière de cookies" for the `id=ot-sdk-btn` button

**Comment by alexgibson** [comment]
How weird - yeah, if I disable JS then I can see the translated string:

```
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Préférences en matière de cookies</button>
```

The HTML that OneTrust generates is exactly the same as the source HTML, it just overwrites the L10n string :/
