### ISSUE TITLE
LCP is slow on mobile on /new

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#12675]
It's possible that removing the background image from the first element on the page will fix that.

**Comment by alexgibson** [comment]
Could it also be because the page relies on JS to show the mobile header? https://github.com/mozilla/bedrock/blob/main/media/js/firefox/new/desktop/download.js#L7-L25

Possibly related: https://github.com/mozilla/bedrock/issues/9824

**Comment by stephaniehobson** [comment]
Removing the background image seems to have been a ~1.5s improvement according to Webpage Speed Test.

| Before  | After |
| ------------- | ------------- |
| <img width="1372" alt="Screenshot 2023-02-02 at 14 59 13" src="https://user-images.githubusercontent.com/854701/217066911-8fd3bae9-3711-4d14-8e3b-1ab7a173d9ee.png">  | <img width="1372" alt="Screenshot 2023-02-02 at 15 01 51" src="https://user-images.githubusercontent.com/854701/217066922-d2aa9889-4ddf-4754-8b43-d5c5d1ab4c0c.png">  |

The banner itself will always need JS to render since it relies on the `.android` or `.ios` classes to be added by JS. I would think that removing the check in `download.js` and just relying on `updateHTML` in `site.js` would not be any faster because they are both render blocking scripts. But please check my assumptions, it's been a while 😵‍💫

**Comment by stephaniehobson** [comment]
I'm waiting for the Google Search Console to validate my fix. I'll provide an update here once that's done.

**Comment by stephaniehobson** [comment]
I suppose this also raises the question, could we defer loading of `site.js` 🤔 Though, I'm not sure what the hit to SEO would be to move the mobile CTAs above the desktop one.

**Comment by alexgibson** [comment]
> The banner itself will always need JS to render since it relies on the .android or .ios classes to be added by JS. I would think that removing the check in download.js and just relying on updateHTML in site.js would not be any faster because they are both render blocking scripts. But please check my assumptions, it's been a while 😵‍💫

It's true they are both render blocking, but we also need to consider when each of the scripts run. The `site.js` script runs in the `<head>` of the page, so it will always apply the `.ios` and `.android`  class names to `<html>` _before_ first paint to avoid content fllicker. The `download.js` script comes almost last in the DOM, after HTML/CSS has been downloaded and parsed. So relying on that script to render or reposition content is always going to be a bit slower in comparison, especially on mobile. 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/400117/217217759-756fd131-a831-4cf4-b42f-d674644a4b76.png">

Thankfully our CDN and HTTP/s is pretty good these days. I only see roughly half a second difference on a 3G connection.

Removing the background image was certainly worthwhile still I think :)

> I suppose this also raises the question, could we defer loading of site.js 🤔 

Whilst the `site.js` script is certainly render blocking, moving it out of the head and deferring it may actually have a negative impact in other ways, especially with content flickering that could hurt LCP (and maybe introduce some CLS) as things would potentially need re-painting again if class names change.

> Though, I'm not sure what the hit to SEO would be to move the mobile CTAs above the desktop one.

This is an interesting one. At one point we were told having the content up top is bad for SEO (despite being semantically OK). But today Google uses Core Web Vitals in their SEO rankings, and content layout shift affects that score. So today the advise seems a bit contradictory.

**Comment by stephaniehobson** [comment]
The /new page is no longer part of the LCP report in the CWV. 🎉 

There's lots more speed optimizations to be done but we can track them in other issues.
