### ISSUE TITLE
Add T&C page for upcoming raffle

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12699]
## Description

T&C: https://docs.google.com/document/d/1EqVOD4O_oimZJwC4KslK6QO9M9nzL-whlfbUkrGqLkw/edit

Slug: `/about/legal/terms/{SLUG}` (TBD)

Date: TBD

**Comment by slightlyoffbeat** [comment]
`/about/legal/terms/peopleofdeutschland` is the requested slug

**Comment by slightlyoffbeat** [comment]
This will be translated into German. Michael F is working to get it into the legal repo.

**Comment by alexgibson** [comment]
Once the markdown file has been added here we can pull it into bedrock: https://github.com/mozilla/legal-docs/commits/main

The file(s) will also need to be available in the `prod` branch of the legal docs repo before we can push the bedrock URL live.

**Comment by slightlyoffbeat** [comment]
It looks like the translation will be done in a google doc. If that's the case, it may be best to just hard code english and german. We should be able to start english now, and DE will be delivered on Tuesday.

**Comment by alexgibson** [comment]
Cool, will get started on this today 👍

**Comment by alexgibson** [comment]
I have a PR ready with English copy. Will drop in German as soon as we have it ready

**Comment by alexgibson** [comment]
German doc: https://docs.google.com/document/d/1oPhOReE0s-MKo2IJWZp4uxZwm172to4x/edit?usp=sharing&ouid=114883578042681483400&rtpof=true&sd=true
