### ISSUE TITLE
/healthz-cron/ is 500ing

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12705]
## Description

Just noticed [in Sentry](https://sentry.io/organizations/mozilla/issues/3905420831/?project=6260211&query=is%3Aunresolved&referrer=issue-stream) that Dev origin server was 500ing for /healthz-cron, but it looks OK now : https://www-dev.allizom.org/healthz-cron/ - looks like an issue with the Fluent sync

However, Prod is 500ing for the same page and also related to the latest Fluent sync: https://www.mozilla.org/healthz-cron/ -- [Sentry issue here](https://sentry.io/organizations/mozilla/issues/3911053873/?project=6249535&query=error.unhandled%3Atrue+is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d)

This is the part blowing up

`latest_ref[:10]` 

from 

```        
<td><a href="{{ fluent_repo.repo_url }}/commit/{{ fluent_repo.latest_ref }}">{{ fluent_repo.latest_ref[:10] }}</a></td>
```

Stage (https://www.allizom.org/healthz-cron/) is fine at the moment

**Comment by stevejalim** [comment]
Going straight to the prod origins, I can see this happening on both US and EU clusters

**Comment by stevejalim** [comment]
At least translations seem to be working OK still - eg https://www.mozilla.org/es-MX/ has content

**Comment by pmac** [comment]
We've traced this to a [security change in git](https://github.blog/2022-04-18-highlights-from-git-2-36/#stricter-repository-ownership-checks) that prevents git from running commands against a repo owned by a different system user. We can add a git config to the docker container to allow these commands to run again.
