### ISSUE TITLE
Organic search referrals for VPN are not passed through to subscription links.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12706]
## Description

When someone visits the VPN landing page via organic search, we should attribute the referral appropriately when someone clicks through to sub plat.

### Steps to reproduce

1. Open https://www.google.com/
2. Search for "Mozilla VPN"
3. Click "Mozilla VPN: Protect Your Entire Device" to visit https://www.mozilla.org/en-US/products/vpn/
4. Scroll down to pricing and click a subscription link.

### Expected result

UTM parameters should attribute organic traffic:

- `utm_source=google`
- `utm_medium=organic`
- `utm_campaign=vpn-product-page`

### Actual result

UTM parameters incorrectly attribute direct/referral  traffic:

- `utm_source=www.mozilla.org-vpn-product-page`
- `utm_medium=referral`
- `utm_campaign=vpn-product-page`

We should do this for multiple search engines based on referrer.

### Environment

N/A

**Comment by alexgibson** [comment]
@a-kyne to provide list of search engines

**Comment by a-kyne** [comment]
> @a-kyne to provide list of search engines

- google
- bing
- yahoo
- duckduckgo
- yandex
- baidu
- naver
