### ISSUE TITLE
WNP 111 for EU

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#12720]
## Description

The request is to reuse the copy/layout done for 109 but translate into additional locales: es-ES, IT, pt-PT, PL, and NL. 

We'll need translated PDFs as well, presumably with strings provided via Smartling but Studio will have to create the actual PDFs once we get translations. So I think we'll need to set up some kind of web page to preview the strings for l10n even if we end up putting them into a PDF for the final product.

The design also features an image-as-text header but maybe we can recreate it with live text. Failing that, we'll at least need the translated string as alt text anyway.

Firefox 111 releases **14 March, 2023**

**Comment by alexgibson** [comment]
In addition to what we stubbed out above, we now also have the designs for DE / FR / UK:

Copy: https://docs.google.com/document/d/10yEs8FDicVLGUgJi8ud-Sm3n4FV2PH4Q-xJCQtmmCEo/edit?usp=sharing
Figma: https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-23?node-id=2705%3A520&t=UIzUV3O2fnSls4jY-1

**Comment by alexgibson** [comment]
Drive link with assets for localized headlines and PDFs: https://drive.google.com/drive/folders/13CAItW-fyfqwAQArDSH_9n-kq_rYtFPH

**Comment by alexgibson** [comment]
Gonna take this one on
