### ISSUE TITLE
MDN Plus Privacy Notice Missing Logo

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#12722]
Most privacy notices have a logo on them but not https://www.mozilla.org/en-US/privacy/mdn-plus/

We have a logo, since we use it in the main navigation, we could reuse it here.

**Comment by janbrasna** [comment]
The icon in main menu [`nav/icons/icon-mdn-web-docs.svg`](https://github.com/mozilla/bedrock/blob/6a7ac6b4f5f25279bfc805174c5e2afd4297ef34/media/img/nav/icons/icon-mdn-web-docs.svg) is unfortunately not a true MDN logo. However there was recently added a full [`logos/mdn/mdn-wordmark-white.svg`](https://github.com/mozilla/bedrock/blob/6a7ac6b4f5f25279bfc805174c5e2afd4297ef34/media/img/logos/mdn/mdn-wordmark-white.svg) that can be used now, and for this case probably the most correct is the red MDN Plus itself [`logos/mdn/mdn-plus-wordmark.svg`](https://github.com/mozilla/bedrock/blob/6a7ac6b4f5f25279bfc805174c5e2afd4297ef34/media/img/logos/mdn/mdn-plus-wordmark.svg)

All the current privacy pages link either the logo vectors from `protocol_assets`, or some of the older pages have the logo PNGs locally in `img/privacy`. MDN is neither case. This would have to tap into `img/logos` ~ but that's what it probably is for anyways. Just checking whether that's okay for `/legal` page not to have the copy of the asset and just link to `/logos`.

**Comment by stephaniehobson** [comment]
The nav menu should be updated too :)

**Comment by janbrasna** [comment]
That's what I thought;) I'll open an issue for it separately.

I'll also try adding the red MDN Plus logo to its legal page how that looks, not duplicating the asset and just linking it from the existing location.

**Comment by janbrasna** [comment]
@stephaniehobson The full MDN Plus wordmark looks like this:

![Screenshot 2024-04-02 at 0 00 02](https://github.com/mozilla/bedrock/assets/1784648/e486be39-7d33-4436-8108-938a74e914cd)

 Unlike all the other Privacy Notices that use square/round icons, this may look too wide. If it's OK like this the PR #14398 can be marked ready.

Another alternative would be using the MDN Plus "favicon" as currently linked for main nav "Products" menu item for MDN Plus to match the other Privacy pages logos better. That would look like this:

![Screenshot 2024-04-02 at 0 00 22](https://github.com/mozilla/bedrock/assets/1784648/0d486991-cf0a-420d-ab07-64c3751d75ec)

Better/worse?

**Comment by stephaniehobson** [comment]
Go with the favicon please :)
