### ISSUE TITLE
Audit use of analytics data attributes

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12737]
## Description

Our current [UA analytics setup using data attributes](https://bedrock.readthedocs.io/en/latest/analytics.html#some-notes-on-how-this-looks-in-ga) likely needs updating to work better with GA4

From Adria
> There are limits to the number of events and parameters that we can create, and the current variables probably go over those.
> 
> Wherever possible we should limit ourselves to using Automatically Collected events, for example, since those don't impact the limits.

## Success Criteria

- [x] we only use custom events for data that cannot come through automatically collected events
- [x] we configure tag manager with GA4 event tags using the custom data

**Comment by stephaniehobson** [comment]
Still early in my reading of the docs but I believe [the limit only applies to apps not websites](https://support.google.com/analytics/answer/9267744?hl=en&ref_topic=9756175)..

**Comment by a-kyne** [comment]
I'm looking at this page on [Configuration limits](https://support.google.com/analytics/answer/11202874).

**Comment by stephaniehobson** [comment]
Working on an audit here: https://docs.google.com/spreadsheets/d/1js1bLK4hL2jhswrqz_bWgiT1jLA389LzoHoIL2iMF9c/edit#gid=2066592652 (mozilla only)

**Comment by stephaniehobson** [comment]
This is all making my head spin but @a-kyne I'm pretty sure we have an unlimited number of "named" events and the "event parameters" limits apply to each of those named events.

**Comment by a-kyne** [comment]
@stephaniehobson Yes! This is why our atypical category naming in GA3 cannot be reproduced. Page URL is an existing dimension, there is no good reason to rebuild Events named by Page in GA4.
