### ISSUE TITLE
Include attribution data with macOS bouncer links

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#12761]
## Description

So far we only add attribution data to bouncer (download.m.o) links for the windows stub installer. There is now a desire to have these attributes added to macOS downloads as well. See [the request document](https://docs.google.com/document/d/1NLobogbVfSYofcm7b61tesTirlXpmxwIRYd6Gsd3tt8/edit?usp=sharing) for more details.

Updated timeline:

 - January 8th: Enable macOS attribution in Nightly (123)
 - January 9th: Ready for QA (QA-2111 and production testing of QA-2145)
 - January 22nd: 123 uplifts to Beta 
 - February 19th: release channel ready for QA testing in production
 - February 20th: 123 release date

**Comment by alexgibson** [comment]
Sounds like folks are ready to get this going

**Comment by alexgibson** [comment]
Updated timeline here:

- January 8th: Enable macOS attribution in Nightly (123)
- January 9th: Ready for QA (QA-2111 and production testing of QA-2145)
- January 22nd: 123 uplifts to Beta

**Comment by alexgibson** [comment]
We only did this for Nightly links initially in the end, so re-opening until we roll it out fully.

**Comment by bhearsum** [comment]
> Updated timeline here:
> 
>     * January 8th: Enable macOS attribution in Nightly (123)
> 
>     * January 9th: Ready for QA (QA-2111 and production testing of QA-2145)
> 
>     * January 22nd: 123 uplifts to Beta

To complete this list, 123 will be released on February 20th.

Ideally, we would update Bedrock to start including attribution codes just ahead of the release. (This is safe to do, as the attribution service will fall back on unattributed installers if it is unable to perform attribution.)

**Comment by alexgibson** [comment]
@bhearsum is there a date where you would like attribution for both Beta and release to be ready for QA? And if so, what environment should that take place on (demo, www-dev?). Thanks

**Comment by bhearsum** [comment]
> @bhearsum is there a date where you would like attribution for both Beta and release to be ready for QA? And if so, what environment should that take place on (demo, www-dev?). Thanks

I was anticipating that we would do all of that verification in prod, as we need the Gecko changes in 123 for this to be testable. (The earlier testing we did in dev was done against simulated nightly builds done on Try, fwiw.)

I don't think there's any need to test the Gecko, stubattribution, or bouncer changes in dev - those are all channel independent. If you'd like to test whatever Bedrock changes are needed in dev I can arrange for simulated Betas & Releases to be made available on Try to facilitate that - just let me know!

**Comment by alexgibson** [comment]
@bhearsum If you're happy testing in prod, then I'm OK just to test the bedrock functionality herein review, and then push the changes to prod just prior to each launch date. Does that sound OK?

**Comment by bhearsum** [comment]
> @bhearsum If you're happy testing in prod, then I'm OK just to test the bedrock functionality here in review, and then push the changes to prod just prior to each launch date. Does that sound OK?

I'm good with that if you think the Bedrock changes are pretty straightforward. (We can do some basic verification that Bedrock is redirecting properly as soon as the changes land, even before 123 hits Beta/Release, at the very least...)

**Comment by alexgibson** [comment]
That sounds good to me, I think the bedrock changes should be pretty small

**Comment by alexgibson** [comment]
@bhearsum I've opened PR https://github.com/mozilla/bedrock/pull/14104 to enable attribution for macOS beta/devedition links (in addition to nightly). We'll try and get this reviewed and pushed to prod on Monday.

In the meantime, if you would like to do any preliminary testing I pushed the branch to a demo instance here: https://www-demo3.allizom.org/en-US/firefox/channel/desktop/

If you need anything else, let me know. Thanks!

**Comment by bhearsum** [comment]
Thank you! I will try to give it a sanity check today.

**Comment by bhearsum** [comment]
Quick sanity check looks good!

**Comment by alexgibson** [comment]
PR https://github.com/mozilla/bedrock/pull/14207 will be the last step in closing this issue.

Target is to deploy around 9am ET on Monday 19th Feb and to alert @bhearsum when this has happened.
