### ISSUE TITLE
New featured section for en-us homepage

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12765]
## Description

We will be updating the en-us homepage to hightlight the new video with iJustine.

[Figma](https://www.figma.com/file/WVJm8IHsq80lQQt5kMOEwg/iJustine-Promo-assets?node-id=102%3A2358&t=FrKqKZWtqoGtbOh8-0)
[Image export](https://drive.google.com/drive/folders/1whuCofID7kZLBNbnnaLtegwFzsJd9nCJ)
[Copy](https://docs.google.com/document/d/1FAfq76wBHWkvnHOi8K6YcpLPH6GKauu8fkdKbm9xRLk/edit#bookmark=id.bmr9ziao58qs)
Video URL: https://www.youtube.com/watch?v=HsoSSfZP0Cs

CTA behavior: open video in modal

Timeline: live for ~3 weeks, but negotiable.
---

#### Success Criteria
- [ ] Event is captured when clicking CTA

**Comment by slightlyoffbeat** [comment]
Its ready to go live whenever we are able to push it live.

**Comment by craigcook** [comment]
Reopening with some requested changes:

1. Switch to the Firefox browser logo rather than the parent logo.
2. New copy:
    title: Reclaiming privacy online
    desc: Learn about creator iJustine’s work to protect her private life in the latest Firefox Presents.
