### ISSUE TITLE
Data strings bleeding into HTML on newsletter pref center 

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#12789]
## Description

The newsletter pref center seems to be improperly escaping the data strings and they bleed into the HTML at the top of the page. The page still works to edit the newsletter settings in my testing, so low impact here.

![Screenshot 2023-02-22 at 14-40-15 Newsletter Subscriptions](https://user-images.githubusercontent.com/1106/220776643-67da3664-a6ce-4077-8d30-557f76c4385f.png)

### Steps to reproduce

Get your newsletter pref center link by going here:
https://www.mozilla.org/en-US/newsletter/recovery/

Then click through the email you receive to see something like the screenshot.

### Expected result

No data string leakage.

**Comment by stevejalim** [comment]
I wonder if this is a regression from https://github.com/mozilla/bedrock/pull/12730

**Comment by stevejalim** [comment]
This is in the source for that page:

<img width="1203" alt="Screenshot 2023-02-22 at 22 44 25" src="https://user-images.githubusercontent.com/101457/220777311-73030b85-3beb-4e0a-948f-8fb64b1a2f0d.png">

**Comment by stevejalim** [comment]
While the HTML is broken, the error messages understandably fail to find the strings they need:

<img width="687" alt="Screenshot 2023-02-23 at 00 03 09" src="https://user-images.githubusercontent.com/101457/220791793-b61f2c91-bed9-4d5e-9f50-4baad86854fe.png">

**Comment by stevejalim** [comment]
Nope - the fix didn't fix it. It resulted in a bad hyperlink in the error box `<li>The supplied link has expired. Please <a href="" en-us="" newsletter="" recovery="" ""="">request a new link here</a>.</li>` 

so, more work needed
