### ISSUE TITLE
[GA4] Ensure GA client_id and session_id is passed to stub attribution

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12801]
## Description

Using Universal Analytics we pass the GA client ID ~and session ID~ to stub attribution to help measure Firefox installs. We need to check that this still works as expected in GA4, and if not work out what's possible.

The objects we currently rely on are:

- client id: `window.ga.getAll()[0].get('clientId')`
- ~session id: `window.ga.getAll()[0].get('_gt')`~

---

#### Success Criteria
- [ ] Understand if switching to GA4 impacts this measurement
- [ ] Identify possible remedy if needed.

**Comment by bobsilverberg** [comment]
For future reference, you can retrieve both the client ID and session ID in GA4 via: 

`gtag('get', {measurementId}, 'client_id', (client_id) => console.log(client_id))`

Not sure if that is officially supported though, but it works for now.

**Comment by alexgibson** [comment]
Possibly useful also: https://www.simoahava.com/gtmtips/write-client-id-other-gtag-fields-datalayer/

**Comment by alexgibson** [comment]
@maureenlholland is it easy/possible to configure a demo instance to only load GA4, to help assess what might need to be done here?

**Comment by maureenlholland** [comment]
@alexgibson Good question, because UA and GA4 share the same GTM container, I'm not sure how easy this will be. A couple of thoughts:
- create a GA4-only workspace on our GTM container (hopefully this results in a new tag)
- create a new and temporary GA4-only container
- no demo, remove the UA config tag in an existing workspace change  and test in preview mode (this feels shakiest to me)

**Comment by maureenlholland** [comment]
In the Mozorg Demo GTM Container, a new version deletes all UA tags and only has GA4 config tag (this is connected to the Mozorg GA4 Testing property)

Once this version is published, it can be tested locally or on Mozorg demos with the Demo GTM container ID

**Comment by alexgibson** [comment]
I deployed the new demo GTM container here which loads only the GA4 script: https://www-demo2.allizom.org/en-US/

Initial findings:

- `window.ga` is `undefined`, so the current object we rely on for passing to stub attribution no longer exists.

There is still a `window.gaGlobal` object, which gives the following:

```
Object { vid: "390634927.1673876266", from_cookie: true, hid: 1159447894 }
```

So `vid` seems to be the client ID. I'm not clear on if `hid` is the session ID or not.

**Comment by alexgibson** [comment]
I was able to follow the GTM tutorial above to expose the client ID and session ID in `window.dataLater` using a custom tag:

```
const data = window.dataLayer.reduce((acc, cur) => {
  if (typeof cur.h === 'object' && cur.h.gtagApiResult !== undefined) {
    return cur.h.gtagApiResult;
  }
});
```

This returns ` { client_id: "1458376848.1678111445", session_id: "1678111444" }`

**Comment by stephaniehobson** [comment]
Do we have any reason to think those aren't the same client and session ID that UA uses?

**Comment by alexgibson** [comment]
The tag is configured to use the GA4 measurement ID, but the values could well be the same. We’ll need to try and verify on our regular container.

**Comment by alexgibson** [comment]
I re-enabled page views for both GA4 and UA on demo to test.

GA4 gives: `{client_id: '1633344113.1673625439', session_id: '1678367677'}`

Whilst UA gives: `'1633344113.1673625439'` and `1678367687`.

So the client IDs match, but the session IDs are slightly different :/

The syntax for how to retrieve the data from `dataLayer` also changes when both versions are enabled 🤬

This to me says we need to coordinate when to make this change carefully :(

**Comment by alexgibson** [comment]
OK, this is slightly more flexible and might get the values irrespective of the changes in object names:

```javascript
const iterate = (obj) => {
    Object.keys(obj).forEach(key => {

    if (typeof obj[key] === 'object' && obj[key] !== null) {
            if (key === 'gtagApiResult') {
                console.log(obj[key]);
            } else {
                iterate(obj[key]);
            }
        }
    })
};

dataLayer.forEach(layer => {
    iterate(layer);
});
```

**Comment by alexgibson** [comment]
Given that the session IDs are very slightly different (my guess is this is down to how long each tag takes to load), the most sensible time to make this change seems to be *after* we have Firefox click/download events instrumented in GA4.

**Comment by stephaniehobson** [comment]
The new method for getting the client ID out of GA4 is working reliably according to the test in #13898

Data Science has asked that we not do a 1:1 swap of the UA derived client ID with the GA4 derived client ID so I am waiting for their guidance on that. Changes will need to be made to the stub attribution log and bouncer to accommodate that so we're in a holding pattern for now.

**Comment by stephaniehobson** [comment]
@willdurand #14235 is on [demo9](https://www-demo9.allizom.org/en-US/) and ready for testing.

**Comment by willdurand** [comment]
> @willdurand #14235 is on [demo9](https://www-demo9.allizom.org/en-US/) and ready for testing.

Thanks, this looks good to me on dev.
