### ISSUE TITLE
Careers listing page can show repeated locations

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12811]
## Description

I noticed a career listing with repeated locations:

![Screenshot_20230225-210056](https://user-images.githubusercontent.com/101457/221528633-d845178a-8777-4d64-9761-efeb57dc6396.png)

Currently still live on https://www.mozilla.org/en-US/careers/listings/

Whether or not this is down to misconfigured input data from Greenhouse, it's worth de-duplicating locations before we show them.

## Success criterion:
- [ ] Career listings do now show duplicated listings

**Comment by stevejalim** [comment]
@robhudson Fancy this one? If not I'll take a look tomorrow

**Comment by robhudson** [comment]
It was updated in Greenhouse. Thanks for catching it!

https://www.mozilla.org/en-US/careers/position/gh/4865076/
