### ISSUE TITLE
Move integration tests from Gitlab to Github Actions

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12820]
### Details

_(Evolving - consider these draft)_

Using https://gitlab.com/mozmeao/www-config/-/pipelines/722686073 as an example, the tests in scope are:

* test-chrome-remote
* test-firefox-remote
* test-headless
* test-ie-saucelabs

(CircleCI used to run the non-headless/non-Selenium Python tests, but these have since been moved to GHA in #12822 and #12824) 

We chose Gitlab originally because it gives us the opportunity to use self-hosted (ie, Mozilla-managed) runner machines to build our Docker images, so we trust the infra they are built on (ours). We used these same runners to drive our integration/browser tests. Now we're on GH Enterprise, we can now use custom runners _if we need to_ for running these test. (However, we might not need to use a custom runner, because the images are being built by SRE as part of a separate step, on self-hosted runners). 

In parallel with this, our Gitlab runners are on AWS, but we are moving our infra to GCP, so if we _do_ continue to use runners, the should be on GCP.

---

#### Related work
- [X] Determine whether we can use self-hosted runners with GH Enterprise 
- [x] Understand current headless/remote test suite workflow _completely_
- [x] Explore whether we need to run tests off self-hosted runners, if we already have Docker containers built on our infra.
- [x] Add new Github-only pipeline, running in dummy mode, parallel with GH->GL
  - [x] Trigger this with a webhook from the mozit once the dev/stage/prod containers are built
  - [x] Trigger this on push to `run-integration-tests` - this may need to build a container on GHE runners that isn't built already 
  - [x] Update documentation
- [x] Ensure integration tests are not started until the deployment has completed
- [X] Enable GHA for dev, stage, prod
- [x] https://github.com/mozilla/bedrock/issues/12984 
- [x] confirm happy on dev, then stage then prod
- [x] Decommission the Gitlab pipeline for headless tests

### Success criteria
- [x] Headless tests no longer involve using Gitlab
- [x] We have a documented, easy place to spot the state of integration tests

**Comment by stevejalim** [comment]
@bkochendorfer Am I remembering correctly that we're already building Dev, Stage and Prod Bedrock images on the new infra? If so, are we also building Test?

**Comment by bkochendorfer** [comment]
That's right, I am working on standing up Test now
