### ISSUE TITLE
Explore Contentful Custom Apps

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#12823]
## Description

[Contentful Apps](https://www.contentful.com/help/apps-at-contentful/) can be used to improve editor experience by creating new field appearances or functionality

Some use cases:
- Individual ✏️  component previews (similar to https://github.com/mozilla/bedrock/issues/9991)
- SEO card preview
- A dropdown that includes predefined options and "Create new" option
![create-new-option](https://user-images.githubusercontent.com/19650432/221939335-c34e98df-19db-47b5-ade6-c650b2ce4046.png)

- Theme color preview
![theme-preview](https://user-images.githubusercontent.com/19650432/221939366-ba2f4130-d2ad-4c00-9a68-b561f697f0a3.png)

## Success Criteria

- [ ] Demo new custom app appearance
- [ ] Evaluate usefulness vs. dev effort

**Comment by alexgibson** [comment]
Closing as not planned
