### ISSUE TITLE
Localization is not working on the Mozilla VPN page (Stage)

### ISSUE THREAD

**Issue by LuminitaB** [mozilla/bedrock#12839]
## Description

Localization is not working on the Mozilla VPN page (Stage). No matter where we localize ourselves using a VPN, whether it is a supported or an unsupported country, the page still displays the US version (US$, Bundle product, the VPN is available for download - no waitlist) 

### Steps to reproduce

1. Access https://www-dev.allizom.org/en-US/products/vpn/ while in an unsupported country (Romania)
2. Access https://www-dev.allizom.org/en-US/products/vpn/ while in a supported country, other that US

### Expected result

The page displays the correct version for every scenario - waitlist for unsupported, correct products, plans and currency for supported country

### Actual result

No matter where we localize ourselves using a VPN, whether it is a supported or an unsupported country, the page still displays the US version

### Environment

Tested on Firefox release 110.0.1 using STAGE environment. This does not reproduce on Production.
**However, it is blocking the testing efforts for Train 253.**

![image](https://user-images.githubusercontent.com/52028275/222703066-bafd96ee-def3-4f09-bd4b-0f68e0a99240.png)

**Comment by alexgibson** [comment]
Thanks for filing this! We'll get on it and try to fix asap

**Comment by alexgibson** [comment]
@LuminitaB until we get a proper fix in here, if it helps to unblock you there's a special query param you can add to the page on www-dev that will mock a country code e.g. https://www-dev.allizom.org/en-US/products/vpn/?geo=ru

**Comment by alexgibson** [comment]
@LuminitaB this issue should be fixed now, thanks for your patience

**Comment by LuminitaB** [comment]
Thank you Alex,
The localization sems to work as expected. We will let you know if we encounter any further issues.
Thank you.
