### ISSUE TITLE
Some of the generated pages are overlooked in the UI tests

### ISSUE THREAD

**Issue by martynamalecka** [mozilla/bedrock#12831]
I've noticed that in the [test_generated_pages.py](https://github.com/mozilla/bedrock/blob/main/tests/functional/test_generated_pages.py) file there is a list of paths which have not been updated for several years. The list does not contain some newly created pages, e.g. "[about/legal/terms/subscription-services/](https://www.mozilla.org/en-US/about/legal/terms/subscription-services/)". There would be probably 10+ new pages to test.

I see two solutions at the moment:
1. First, not ideal, update all paths manually. Harder to maintain as they would need to be updated with every change.
2. The second option is a simple script within the test to search for the relative links by the href attribute using Selenium. It would explicitly exclude absolute links to make sure it is not testing links to external websites.

I've just started my journey with programming and automation testing, so I would appreciate your help and feedback.

**Comment by alexgibson** [comment]
Hi @martynamalecka!

This particular test is to verify that pages which are generated by content that is external to this repo give a 200 response. We can certainly expand the list if we think there are generated pages that could warrant some extra coverage, but I don't think it necessarily has to include everything. Looking at the list though, I'm sure there are some others more recent page that might be worth adding.

I don't think we should do 2, as crawling relative links on our site could take a long time seeing as we have so many pages. We have to balance test coverage with the time it takes our integration tests to run during deploys.

If you would like to submit a pull request that adds some more generated pages to the list though, that would be welcome :)

**Comment by stevejalim** [comment]
Hi @martynamalecka - just to supplement Alex's comment, we do also have https://github.com/mozmeao/www-site-checker/ that runs regularly against our production services. 

`www-site-checker` uses Bedrock's automatically-generated `sitemap.xml` as its source of truth and explores every single URL in its child sitemaps. This implicitly includes checking for a 200 OK, which does overlap with what `test_generated_pages.py` does. Feel free to take a look at that, too - it's in a beta state at the moment, and contributions or suggestions are very welcome there, if that also appeals.

**Comment by martynamalecka** [comment]
Hi @alexgibson and @stevejalim!

Thank you for all the information provided. Your explanation makes it clearer to me.

I'll check if there is any recently added pages, which are important and worth checking, and I'll add them to the list.
