### ISSUE TITLE
Wrong language version of the installer downloaded by clicking Download Firefox

### ISSUE THREAD

**Issue by martynamalecka** [mozilla/bedrock#12841]
## Description

I see a problem when redirecting from the [Main Page](https://www.mozilla.org/pl/) in any other language than English (for example Polish) to the [Download Page](https://www.mozilla.org/en-GB/firefox/download/thanks/) by clicking on the Download Firefox button. 

1. The selected on the Main Page language (e.g. Polish) gets changed to English on the Download Page. Therefore, the English version of the browser installer is downloaded instead of the Polish version. If users get the English version, and they don't speak English, it may be hard for them to use the browser. I understand that we probably can't fix that issue easily for all the generated pages which contain the Download Firefox button, but I feel it's essential to fix the Main Page --> Download Page redirection, as that's probably how most of the users download the installer.

2. The text displayed on the Download Page is not in the same language we chose on the Main Page, even though the translation exists. I believe it's important from a business perspective that all Non-English-speaking people could read the download and installation instructions in their mother tongue.

Furthermore, I've checked what happens when you download the installer from the [Polish Download Page](https://www.mozilla.org/pl/firefox/download/thanks/) and through the [Download In Another Language Page](https://www.mozilla.org/en-GB/firefox/all/#product-desktop-release) by choosing Polish version of the installer and in both cases I successfully installed the Polish version.

### Steps to reproduce

1.  Open the [English Main Page](https://www.mozilla.org/en-GB/) and choose the language from the drop-down list (other than English, for example Polish) or go directly to [Polish Main Page](https://www.mozilla.org/pl/).

2. Click "Pobierz Firefoxa" as shown in the screenshot below.
<img width="1266" alt="Screenshot 2023-03-04 at 6 14 55 pm" src="https://user-images.githubusercontent.com/76040511/222881822-725c5d17-444c-41e5-8f33-20e78d845ba1.png">

3. Download the file and install Firefox. 

4. Open Firefox browser.

5. Check which language is set as a default language.

### Expected result

1. The [Polish Download Page](https://www.mozilla.org/pl/firefox/download/thanks/) should remain in the chosen on the [Main Page](https://www.mozilla.org/pl/) language (in this case - Polish).

<img width="1129" alt="Screenshot 2023-03-04 at 6 18 52 pm" src="https://user-images.githubusercontent.com/76040511/222881884-eac99114-517f-4ac4-98b2-764a6da06a16.png">

2. The Polish version of the Firefox installer should be downloaded.

<img width="1436" alt="Screenshot 2023-03-04 at 9 20 51 pm" src="https://user-images.githubusercontent.com/76040511/222894426-f3dc118b-f326-4b35-aeb3-4c7d01773bff.png">

### Actual result

1. The English version of [Download Page](https://www.mozilla.org/en-GB/firefox/download/thanks/) is opened.

<img width="1124" alt="Screenshot 2023-03-04 at 6 19 45 pm" src="https://user-images.githubusercontent.com/76040511/222881924-cdad50b3-c4ff-46e4-8d14-d6a7e9dcb5d6.png">

2. The English version of the Firefox installer is downloaded.

<img width="1440" alt="Screenshot 2023-03-04 at 9 16 03 pm" src="https://user-images.githubusercontent.com/76040511/222894237-e7dcc8ab-6ba6-4a66-98bb-7ea8514d9309.png">

### Environment

MacOS Ventura 13.2
I've reproduced the bug in the following browsers: Chrome, Safari, Opera.

**Comment by alexgibson** [comment]
Hi @martynamalecka,

is your preferred language set to English in the browsers you are testing with? This might explain why you are seeing this issue.

When clicking download from pages like the home page, we go by the users preferred language (set in their web browser) rather than the locale of the page. If we just used the page language, it would be possible to download Firefox in the languages that the home page is translated in. Firefox is available in many more languages than most of our web pages.

**Comment by martynamalecka** [comment]
Hi @alexgibson,

Thank you for your reply. 

Yeah, my browser is set to English, my mistake, sorry for bothering you. 

I'm closing the issue as there is no actual bug in this case.
