### ISSUE TITLE
Epic: Migrate Relay pages to bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#12876]
## Description

This is an epic that covers migrating the logged out pages at https://relay.firefox.com/ to bedrock. This is a large piece of work, and should be broken down into smaller individual issues to reference here, if it makes things easier.

### Requirements

Migrate the following pages:

- Landing page https://relay.firefox.com/
- FAQ page https://relay.firefox.com/faq/
- Premium page https://relay.firefox.com/premium/
- Phone masking wait list page https://relay.firefox.com/phone/waitlist/
- VPN / Relay bundle wait list page https://relay.firefox.com/vpn-relay/waitlist/

Design considerations:

- We need to involve Jess Cook (S&P team designer) as a consulted person in the migration.
- There are no hard requirements for maintaining any existing visual components that need to persist between the logged out and logged in pages (such as the nav or footer).
- Existing designs should be ported to use Protocol's base styles and stock components where it makes sense, similar to how we did for VPN. Non standard things can be ported as custom, one-off components for now.
- The Add-on reviews section on the [landing page](https://relay.firefox.com/) is all hard coded, and is actually out of date in terms or review score.
- We should consider discoverability of other products (such as Monitor and VPN), if the bento box in the existing Relay navigation is going away.
- We should make sure the new migrated pages are where we want them to be in terms of content for SEO.

L10n:

- The bedrock pages need to be localized in at least the same number of languages before we redirect the old pages to bedrock.
- The current Relay site uses Fluent, and string translations can be [found here](https://github.com/mozilla-l10n/fx-private-relay-l10n). I'm not sure if we can practically re-use the existing translations, but I guess it's a possibility.

Geo-location:

- Relay Premium is only available in certain countries.
- Phone masking is only available in US and Canada.
- In unsupported countries, a wait list button is shown instead of a subscription button.
- Multiple currencies and price plans are also supported, in the same type of setup we have for VPN.
- We need to work with the Relay team to get data on all country and pricing requirements.

Subscription flows:

- In the same way we do for VPN, subscription links need to point to the FxA subscription server. Each country / currency requires a different stripe ID.
- For the free version of Relay, we can [link to this flow](https://relay.firefox.com/accounts/fxa/login/?process=login), but we should consult with Luke Crouch to make sure this is as simple as it seems.

Attribution and analytics:

- Goals will need to be set up in GA to capture CTA clicks and subscription intent.
- Existing attribution on the current page is not where the Relay team would like it to be. They would be **very** happy if we could replicate what we already have for VPN (which should mostly come for free by migrating to bedrock).

Environments:

- The bedrock pages on www-dev should link to the Relay & FxA staging servers.
- The bedrock pages on prod should link to the Relay & FxA prod servers.
- Subscription links should use different stripe IDs for www-dev / prod.

Migration plan:

- We need one!
- Both sites will need to run in tandem in production for a period of time most likely. Once we're happy with the new pages on bedrock, we can work with the Relay team to redirect the logged out state to www.

### Notes

Q&A from my recent meeting with Maxx are here: https://docs.google.com/document/d/1rewL_Pqz9geVE5XXOTZAZNR4_GGewR4v0GR4jP6wmh8/edit?usp=sharing

---

#### Issues
- [x] #12963
- [x] #13204
- [x] #12932
- [x] #12933
- [x] Migrate "[Premium](https://relay.firefox.com/premium/waitlist/)" waitlist page 
- [x] #13008
- [x] #13322
- [x] #13432
- [ ] #13656

**Comment by stephaniehobson** [comment]
URL structure:

    Landing page: /products/relay/
    FAQ page /products/relay/faq/
    Premium page /products/relay/premium/
    Phone masking wait list page /products/relay/waitlist/phone
    VPN / Relay bundle wait list page /products/relay/waitlist/vpn

**Comment by venbee001** [comment]
@alexgibson

**Comment by stephaniehobson** [comment]
I think we are missing a waitlist page for paid email masks.

**Comment by stephaniehobson** [comment]
The Relay migration to bedrock is paused.
