### ISSUE TITLE
I Want to add Animation on Scroll

### ISSUE THREAD

**Issue by minhaj-313** [mozilla/bedrock#12901]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**I Want to add Animations while scrolling the Pages, Please assign this task to me**

**Comment by craigcook** [comment]
Thanks for your suggestion but this isn't something we intend to do without a lot more thought and planning internally.
