### ISSUE TITLE
Dedicated Affiliate Page for VPN

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#12912]
## Description

Currently, we send affiliate traffic to the VPN landing page (or a version of it). It displays the cookie banner.

We are looking to have a dedicated page for affiliate traffic that is a highly simplified version of the page, with everything but pricing stripped away.

It would be great if we could find a technical solution to direct affiliate traffic to this updated page, however we also have the option to provide a new URL to our affiliates. 

Design: see attached image. It would use the same design that we used when we had a column based pricing plan. 

Copy: 
- For our pricing plan, same copy as what we currently have on the site.:
- header: `One subscription for all your devices` 
- subheader: `Choose a plan that works for you`

URL:
I believe we will be moving towards having a dedicated pricing page. When we do, i assume that will be at `/products/vpn/pricing/`. We could either have this be:
- `/products/vpn/pricing/{slug}` or
- `/products/vpn/pricing?v={slug}`

---

#### Success Criteria
- [x] Displays cookie banner
- [x] Redirect Affiliate Traffic to this page (if possible).
- [x] Highlighted plan is 12 month plan

![image](https://user-images.githubusercontent.com/2030656/227653879-cd0dbdc3-4d3d-4284-96fb-15c6750d8b6d.png)

**Comment by slightlyoffbeat** [comment]
@alexgibson Can you take a look at this issue, and see what else is needed to begin work? You would be best suited to take this task since you have the most knowledge of the affiliate page, and what flags we need to raise here.

Ideally we start work on this early next week.

**Comment by alexgibson** [comment]
@slightlyoffbeat a couple of clarifying questions:

1. Is this the exact same requirements as setting up a dedicated stand-alone pricing page, which we discussed in Slack the other day? The affiliate flow has a dependency on a fully-baked pricing section, and a fully-baked pricing section also has a dependency on an affiliate marketing flow. With that in mind, could we in-fact make this the stand-alone pricing page we talked about, that also supports affiliate marketing? It could live at `/products/vpn/pricing/` and the affiliate flow would be triggered via the `cjevent` param e.g. `/products/vpn/pricing/?cjevent=1234567890`. Obviously we wouldn't be linking to it from the landing page just yet, until we figure out the best course of action for attribution. Does this sound sensible?
2. Is there a hard requirement for this stand-alone page to use a different (older) design to the one on the current landing page? From a maintainability point of view, using a consistent design component here will likely make future changes easier.
3. I think we can definitely redirect existing affiliate params to this new page, however the existing landing page will still need to support the attribution flow with cookie banner, since it's possible for someone to return to the site later on when they still have a valid attribution cookie. Does that raise any red flags for the context of this new page?
4. Should this page also support the VPN + Relay bundle, like we do on the landing page (it's not visible in the mock up)?

**Comment by slightlyoffbeat** [comment]
@alexgibson 

1. That sounds sensible. When this task was discussed, there was no plan for a dedicated pricing page. Now we know a pricing page is also in the works for Q2. I think what you proposed works. We won't be doing any linking from the landing page for a decent amount of time since that work hasn't even kicked off yet.
2. For this page, the hypthesis is a simpler design, similar to what we had on the older design will work best. This means 2 design, however I believe we can align with the landing page and future pricing page work to make this a single design. It just does not line up for now.
3. No flags from me. I will check with Lauren
4. No bundle on this page
5. Yes, if we can re-use behavior/work/copy that is ideal

**Comment by alexgibson** [comment]
@slightlyoffbeat a couple more smaller details to figure out:

1. When it comes to attribution, do we want to differentiate subscription traffic from the main VPN landing page? i.e. do we want to change from the current default of `utm_source=www.mozilla.org-vpn-product-page` to something like `utm_source=www.mozilla.org-vpn-pricing-page`?
2. Do we want to have this page indexed by search engines? If so, should we specify a distinct page title and description?

/cc @a-kyne

**Comment by a-kyne** [comment]
>     2. Do we want to have this page indexed by search engines? If so, should we specify a distinct page title and description?

If we only want affiliate traffic to see it, then no, we don't want it indexed by search engines. I'd use a noindex tag/header. Also, it never hurts to have appropriate metadata, but for a channel landing page that won't be indexed, it's not _necessary_.

**Comment by slightlyoffbeat** [comment]
Eventually, when we do this for the general audience flow, this may need a larger discussion. For now, i'd be good with changing to the pricing page. Is there a way to specify that its coming from attribution if it is attribution traffic? Do we do that right now?

In the future, its possible a user could arrive at the pricing page by way of the landing page, or a WNP, or other sources. With that in mind, we may want to have a fallback if nothing is carried over, (vpn-pricing-page-direct ?).

Open to thoughts and ideas on this. But in the short-term, we can have something that is pricing page specific with little risk.

**Comment by alexgibson** [comment]
This new page will have all the same attribution logic as the main landing page (which is currently limited to last touch), so we can point to it from other sources (such as WNP) and attribution will still happen as it does currently.

The change I'm suggesting is only for the default set of utm params we add to subscription links. Does that make sense?

**Comment by alexgibson** [comment]
@slightlyoffbeat got something up on demo. How does this look?

- VPN available in country https://www-demo3.allizom.org/en-US/products/vpn/pricing/?cjevent=123456789
- VPN not available: https://www-demo3.allizom.org/en-US/products/vpn/pricing/?geo=cn

It doesn't match the old design exactly, but it's the same layout so kind of a middle ground between the old / new component. Let me know what you think, or if you have any suggestions. Thanks

**Comment by slightlyoffbeat** [comment]
@alexgibson Looks great.

Here's feedback:
- headline: `One subscription for all your devices`
- subheader: `Choose a plan that works for you`
- add mozilla VPN logo above headline/subheadline (all centered. logo, then header, then subheader)

![logo-word-hor-stack 8f9444bb577e](https://user-images.githubusercontent.com/2030656/229243803-59ea3070-c674-45df-a33f-411e13e2e681.svg)

**Comment by alexgibson** [comment]
@slightlyoffbeat updated, let me know if you need anything else, or if this is good to move forward with? Thanks

https://www-demo3.allizom.org/en-US/products/vpn/pricing/?cjevent=123456789

**Comment by slightlyoffbeat** [comment]
@alexgibson can we update the logo to be bigger? It is currently 48px in height. Can we updated to be 72px in height?

Is it possible to push to production, but hold on forwarding affiliate traffic in order to run some tests and be confident we can start redirecting traffic?

**Comment by slightlyoffbeat** [comment]
Everything else is a thumnbs up, so if we can get the larger logo, we should be good to start moving to production.

Only ask is we hold on redirecting traffic so that we can run some tests after its live.

**Comment by alexgibson** [comment]
Made the logo bigger (64px is the next largest standard logo size for VPN that we have in protocol)

Also put the redirect behind a switch, so will be off in production until we're ready 👍
