### ISSUE TITLE
Create Pocket iOS License Page

### ISSUE THREAD

**Issue by bassrock** [mozilla/bedrock#12910]
## Description

Pocket is getting ready to launch the next version of it's iOS App. Today pocket hosts open source acknowledgements at https://getpocket.com/opensource_notices_ios via some older pocket systems.

Instead of updating the Pocket hosted page in the old system we would like to move to Bedrock since this is a static page and can be a part of our marketing pages.

We would like to request the following:
* Create a new url: https://getpocket.com/opensource_licenses_ios  <-- Note the change from notices to licenses, we will shut down the old url once we launch
* Use the content from https://docs.google.com/document/d/16trRWFNBsQrfusdISL4BXchSkkOCWVOQp_X6tOtCFtw/edit
* No localization is needed

This page will then be opened in app via a mobile browser when requested by the user, i'll leave the styling to the Marketing team here.

**Comment by reemhamz** [comment]
@bassrock Looks like the copy you provided is over 50 pages long, whereas the old copy on the Pocket site is rather short. Can you please point me to which content you want me to copy over exactly?

**Comment by bassrock** [comment]
@reemhamz Correct, the new app uses a few more libraries then the old one and generates a longer acknowledgement page. The old page is for the old application we will be retiring soon. I generated a version markdown, but could generate an HTML one if helpful

**Comment by reemhamz** [comment]
@bassrock that would be great with the markdown or HTML just to get a headstart since it's a _very long_ document. I'll take some clean-up from my end but i'd be happy to do that to fit our design standards.
Looks like Google Docs makes it easy to get HTML code from a document:

```
    Open the Google Doc you want to convert to HTML.

    Click on "File" in the menu bar, and then select "Publish to the web" from the drop-down menu.

    In the pop-up window, click on the "Embed" tab.

    Here, you can customize the settings for your HTML code, such as whether to include the document title or the document's table of contents. You can also choose to automatically republish the document whenever changes are made.

    Once you've made your selections, click the "Publish" button.

    You'll then be given a code snippet that you can copy and paste into your HTML file.
```

**Comment by bassrock** [comment]
@reemhamz Try this [file out](https://drive.google.com/file/d/16jjjf9G0mF2KxjFrnGxtDgnE6j0EeTyR/view?usp=share_link)

**Comment by reemhamz** [comment]
Closing for #12951 being merged
