### ISSUE TITLE
Invite Debian-based distribution users to use Mozilla's .deb package instead of our current .tar.gz file

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla/bedrock#12966]
## Description

Meta-bug: [bug firefox-deb-repackage](https://bugzilla.mozilla.org/show_bug.cgi?id=firefox-deb-repackage).
Additional context: [FFXP-2363](https://mozilla-hub.atlassian.net/browse/FFXP-2363)

In a few Firefox release cycles, the Release Engineering team will ship Firefox as a `.deb` package for Ubuntu and Debian users. Unlike we've always done so far, we won't redirect users to our latest binaries this time. Instead, we will display instructions on how they can set up their package manager to use our package. This is a standard practice in the Linux community ([e.g.](https://www.spotify.com/us/download/linux/)). 

## Timeline

We currently aim to get our first nightly users in Firefox 115 whose Nightly cycle starts [a month from now](https://wiki.mozilla.org/Release_Management/Calendar). Depending the feedback we get from users, we may either ride the 115 train or let it bake in Nightly. 

We plan to first announce it through Nightly's blog post ([bug 1826540](https://bugzilla.mozilla.org/show_bug.cgi?id=1826540)). So no need to have the [nightly download page](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly) ready on the first day. That said, early in the 115 cycle would be appreciated. 

Then, we can adjust the [beta download page](https://www.mozilla.org/en-US/firefox/channel/desktop/#beta) and then the release depending on the user feedback. 

## Expected behavior 

The ultimate goal is to display the instructions (exhaustive list still to be determined) to Debian-based distribution users (e.g. users on Debian, Ubuntu, Linux mint). If we have a way to reliably detect the distro, then we should prevent these users from downloading the `.tar.gz` archive and show the instructions. If we have no easy way, then all Linux should see the instructions then confirm they want to download the `.tar.gz` anyway.

These changes should be reflected on the pages liked above as well as the [main landing page](https://www.mozilla.org/en-US/firefox/new/). Instructions have to be localized too. 

How does that sound to you all? 

I'm happy to provide additional details. 

---

#### Success Criteria

Let's agree on the right approach first, I'll be happy to define the success criteria afterwards 🙂

**Comment by alexgibson** [comment]
@JohanLorenzo thanks for the heads up. Would it make sense to have the instructions as a SUMO page perhaps? Alternatively we could make a localized instructions page here on mozorg.

We can't detect specific distributions, but we do have existing logic to detect Linux as a general platform. We could use that to redirect people to an instructions page when they click a Firefox download link, instead of triggering a file download.

**Comment by JohanLorenzo** [comment]
I filed [bug 1826748](https://bugzilla.mozilla.org/show_bug.cgi?id=1826748) for the SUMO request.

**Comment by alexgibson** [comment]
@JohanLorenzo just checking in here - is there anything you need us to do here still?

**Comment by JohanLorenzo** [comment]
Hey @alexgibson! Thanks for checking in! Yeah, we'll eventually need this change. That said, the timeline is not as clear as it was in April. The project got delayed because of a longstanding issue in Firefox. I'll get back to you once the schedule gets clearer again.

**Comment by JohanLorenzo** [comment]
@alexgibson 👋 I have some new info on the timeline. We are targeting Firefox 122 which goes to release on January 23rd. How does that sound to you?

**Comment by alexgibson** [comment]
@JohanLorenzo can you give an update on what's hoped for here on our side of things?

**Comment by JohanLorenzo** [comment]
So, if SUMO is the source of truth for instructions, then we should point Linux users there. Something like:

 1. a Linux user wants to download Firefox
 2. before downloading the tar.gz, we display a text like: "Using Debian, Ubuntu, or any Debian-based distribution? You can [set up our APT repository instead](link-to-sumo)." 
 3. a Linux should then choose which option to pick

Does that sounds okay? I don't have any strong preferences, I'm just getting the ball rolling 🙂

**Comment by sylvestre** [comment]
I would like to see it here too:
https://www.mozilla.org/fr/firefox/all/#product-desktop-release
and having Debian/Ubuntu/Mint in the list ?

and redirect to the sumo page ?

**Comment by JohanLorenzo** [comment]
> @JohanLorenzo can you please provide the SUMO URL you would like to link people to?

Okay, I just asked in [bug 1826748#c4](https://bugzilla.mozilla.org/show_bug.cgi?id=1826748#c4)

**Comment by JohanLorenzo** [comment]
> 1. A Linux user lands on http://www.mozilla.org/firefox/new/ and clicks download.
> 2. When redirected to http://www.mozilla.org/firefox/download/thanks/, instead of auto-starting the download, we instead display two options:
>    a. Link to SUMO for set up instructions
>    b. Link to download the tar.gz binary

LGTM!

**Comment by JohanLorenzo** [comment]
> Is there any expectations for what should happen for Beta / Dev / Nightly?

Could we do the same for Nightly and DevEdition? We mustn't do anything with Beta for now.

**Comment by alexgibson** [comment]
I'll make sure this gets on our team's radar, thanks all!

**Comment by alexgibson** [comment]
@JohanLorenzo circling back to this work. Is it OK for us to deliver the changes here any time *after* 122 ships?

**Comment by JohanLorenzo** [comment]
Discussed over Slack with @enavajas. We clarified the priority and agreed this ticket needs to ship at the same time as Firefox 122. Thank you folks for working on this! 😃

**Comment by nathan-barrett** [comment]
Closed as fixed in #14096
