### ISSUE TITLE
Migrate ftl strings from fx-private-relay into bedrock

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13008]
The following Relay pages are migrating to bedrock:

- **Landing page** https://relay.firefox.com/
- **FAQ page** https://relay.firefox.com/faq/
- **Premium page** https://relay.firefox.com/premium/
- **Phone masking wait list page** https://relay.firefox.com/phone/waitlist/
- **VPN / Relay bundle wait list page** https://relay.firefox.com/vpn-relay/waitlist/

There is no specific deadline for this work but it is unlikely to complete before the end of April.

As part of that we would like to migrate the existing translations (and credit for translators!) from https://github.com/mozilla-l10n/fx-private-relay-l10n/

I spoke with @peiying2 and was excited to hear we can migrate strings and credit!

At the moment the websites-team is aware that we need to keep the string IDs the same. Note about what else we can do to help can be collected here.

- https://github.com/mozilla/bedrock/issues/12876
-  https://github.com/mozilla/bedrock/issues/12963

**Comment by stephaniehobson** [comment]
@flodolo Peiying said you would be mostly working on this. Please let us know what we can do to make it easiest for you.

**Comment by stephaniehobson** [comment]
@bcolsson I hear you are working on this too? Instead? Let me know how I can help.

**Comment by bcolsson** [comment]
Hi @stephaniehobson , I believe some discussions might be happening separately with Peiying, but as I'm reviewing this request I couple questions came up.

- Have done any investigation into how you would be handling the migrated strings on the back end?

I've taken a look at some of Relay's strings, but they are using React to process things like tags and variables in strings ([example](https://github.com/mozilla/fx-private-relay/blob/1b41206be7cc4c49cdec951f2f80d49f10434662/frontend/src/components/dashboard/ProfileBanners.tsx#L132-L149)). 

- Will you provide the list of files/strings that need to be migrated from Relay?

- How are you going to resolve discrepancies in brand terms?
Similarly there are some brand terms that need to be added. And one inconsistency with a particular term ([Firefox Accounts](https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/c8f118caf8a0923b1016ac495c7022b3097125ff/en/brands.ftl#L23-L27)) that would need to be resolved.

**Comment by stephaniehobson** [comment]
>     * Have done any investigation into how you would be handling the migrated strings on the back end?

I'm not sure what you mean by this. I am happy to take direction from the L10n team. 

What would be easiest for me would be to copy the en bundle.ftl, landing.ftl, and phones.ftl into bedrock. I'd like to split them into smaller files as well.

> I've taken a look at some of Relay's strings, but they are using React to process things like tags and variables in strings ([example](https://github.com/mozilla/fx-private-relay/blob/1b41206be7cc4c49cdec951f2f80d49f10434662/frontend/src/components/dashboard/ProfileBanners.tsx#L132-L149)).

I'm not sure what we're going to do with the <vpn-logo> tag.

The python helpers can fill in the variables. We will have to make a look up table in bedrock that contains the variable values. I plan on modelling this after the ones we have for VPN but have not started work yet.

>     * Will you provide the list of files/strings that need to be migrated from Relay?

I can if that is helpful. At the moment my list is just the file names above. Once we are further into the migration I will have a better idea if there are any strings in those files we don't need.

>     * How are you going to resolve discrepancies in brand terms?

I didn't know there were any, so I hadn't thought about this yet 😬 My preference would be to defer to the bedrock brand terms and add new terms if necessary. I'll have to look and see

>       Similarly there are some brand terms that need to be added. And one inconsistency with a particular term ([Firefox Accounts](https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/c8f118caf8a0923b1016ac495c7022b3097125ff/en/brands.ftl#L23-L27)) that would need to be resolved.

I'll have a look at these and get back to you.

**Comment by stephaniehobson** [comment]
@bcolsson 

I had a look at the differences between the two brand files

| Relay | bedrock |
|--------|--------|
| -brand-name-firefox | ✅ |
| -brand-name-firefox-relay | ✅  |
| -brand-name-relay | ✅  
| -brand-name-relay-premium | ✅ |
| -brand-name-premium | ❌ |
| -brand-name-firefox-relay-premium | ❌ |
| -brand-name-firefox-browser | ✅ |
| -brand-name-mozilla | ✅ |
| -brand-name-vpn | ✅  |
| -brand-name-mozilla-vpn | ✅ |
| -brand-name-mozilla-privacy-pack |  |
| -brand-name-firefox-lockwise | ✅ |
| -brand-name-firefox-monitor | ✅ |
| -brand-name-pocket | ✅ |
| -brand-name-firefox-account (with capitalization) | ? |
| -brand-name-chrome | ✅ |
| -brand-name-google-chrome | ❌ |

**Comment by stephaniehobson** [comment]
@bcolsson Oops, hit publish too soon.

**Comment by stephaniehobson** [comment]
@bcolsson 

I had a look at the differences between the two brand files.

**The following brand terms have 1:1 equivalents:**

- `-brand-name-firefox`
- `-brand-name-firefox-relay`
- `-brand-name-relay`
- `-brand-name-relay-premium`
- `-brand-name-firefox-browser`
- `-brand-name-mozilla`
- `-brand-name-vpn`
- `-brand-name-mozilla-vpn` 
- `-brand-name-firefox-lockwise` 
- `-brand-name-firefox-monitor`
- `-brand-name-pocket`
- `-brand-name-chrome`

**These are not a problem:**

`-brand-name-mozilla-privacy-pack` 
This is not in use and does not need to be migrated.

`-brand-name-firefox-relay-premium` 
I will add this to bedrock as part of the mirgration.

**These should use a different term:**

`-brand-name-google-chrome`
This only used once and in this context it could be replaced with bedrock's `-brand-name-chrome`

`-brand-name-premium` 
I don't think we should be using the term "Premium" and recommend replacing it with `-brand-name-relay-premium`. I will see if there is a brand specialist I can confirm this with.

`-brand-name-firefox-account` 
Is only complicated because it has upper and lowercase versions. However, only the uppercase variant is used so we use bedrock's `-brand-name-firefox-account` 

**So now I have the following questions:**
- Can we do a find and replace with the brand terms I would like to change? Or would it be better to leave the old terms in the migrated strings and create an alias referencing the bedrock term?
- If we can't replace`{ -brand-name-firefox-account(capitalization: "uppercase") }`  with `{ -brand-name-firefox-account }` strings. I'm not totally sure what we will do. I'll have to see how the bedrock helpers handle it.

**Comment by bcolsson** [comment]
>Can we do a find and replace with the brand terms I would like to change?

This, could potentially be possible. I'll need to cross-reference across locales, but a find/replace may be straightforward for most of the terms (except for `-brand-name-firefox-account` which is more complicated with many variants). 

>Or would it be better to leave the old terms in the migrated strings and create an alias referencing the bedrock term?

I don't quite understand this. Is this a suggestion to have a separate ftl file that points one brand term to another?

>If we can't replace{ -brand-name-firefox-account(capitalization: "uppercase") } with { -brand-name-firefox-account } strings. I'm not totally sure what we will do. I'll have to see how the bedrock helpers handle it.

I need to do some more investigation into this. While English only uses `uppercase` here, that's not necessarily the case for other languages which may have other fluent variants and uses (for example `cs` or `uk` locales). It can get quite complex.

It's possible that instead we would need to trigger re-translation if we want to replace the string with the bedrock brand term.


 >>* Have done any investigation into how you would be handling the migrated strings on the back end?

>I'm not sure what you mean by this. I am happy to take direction from the L10n team.

Sorry for not being clear. I was asking whether you've looked into whether you can handle the strings from Relay that were developed around @fluent/react, where bedrock does not seem to use React.

**Comment by stephaniehobson** [comment]
@bcolsson I've been thinking about [the `<vpn-logo>` tag ](https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/main/en/bundle.ftl#L33) and I think the options are:

1) do a global find/replace to remove the open and closing tags, presumably leaving the `{ -brand-name-mozilla-vpn }` as fallback text

2) trigger re-translation

**Comment by bcolsson** [comment]
@stephaniehobson  - looking into the files/strings that contain the tags, I don't see any major complications if we migrated the file then find/replace with a different tag (or I suppose eliminating the tag).

We could also replace brand terms in a similar fashion, though `-brand-name-firefox-account` might need some manual review for certain locales.

For `-brand-name-premium` if we consider replacing with the bedrock term, you'd want to make sure visually it doesn't cause issues due to the increase in length, but other than that I don't see an issue.

**Comment by stephaniehobson** [comment]
Here's a list of the find and replace we need to do during the migration:

- `<vpn-logo>{ -brand-name-mozilla-vpn }</vpn-logo>` to `{ -brand-name-mozilla-vpn }`
- `-brand-name-google-chrome` to  `-brand-name-chrome`
- `-brand-name-premium` to `-brand-name-relay-premium`

And we were going to see if this is possible too:

- `{ -brand-name-firefox-account(capitalization: "uppercase") }` to `{ -brand-name-firefox-account }`
- `{ -brand-name-firefox-account(capitalization: "lowercase") }` to `{ -brand-name-firefox-account }`

**Comment by stephaniehobson** [comment]
I had a look through the final strings and I don't see any places where we are migration strings with `-brand-name-premium` or `-brand-name-google-chrome` or `<vpn-logo>`. That should simplify things :)
