### ISSUE TITLE
Help Google to distinguish between EN pages localized to different regions.

### ISSUE THREAD

**Issue by a-kyne** [mozilla/bedrock#13019]
## Description
Google is still showing the root page as the main link for 'mozilla' in en-US search results. It also is not using the <title> tags to create the titles for several other pages in the sitelinks.
![image](https://user-images.githubusercontent.com/104653010/233718897-dc746c16-cbf2-40d7-bcbd-6533df73a93a.png)

It is possible that one of the reasons why Google does not yet understand that https://www.mozilla.org/ is the global landing page, and not the en-US home page, is because the root document only includes the hreflang x-default tag, and does not include the hreflang tags for all of the actual home pages (which I believe Google considers to be the necessary reciprocal values).

It is likely that Google is not using the provided values for <title> tags in the sitelinks for 'mozilla' because the titles are duplicated across EN pages.

---

#### Success Criteria
- The root document at https://www.mozilla.org/ includes not only the hreflang x-default tag, but also the hreflangs for the localized home pages.
- The <title> tags of key pages on the en sites use unique values ([provided here](https://docs.google.com/spreadsheets/d/1RIuM1b23UfqtKEtNu1-f-pb_yihr8z0swoWW4v0BzMg/edit?usp=sharing))

**Comment by alexgibson** [comment]
@a-kyne I took these suggestions and pushed them to a demo so you can review. I also asked a couple of clarifying questions in the page title spreadsheet. Let me know if this looks ok, or you need any other changes? Thanks

- [ ] https://www-demo5.allizom.org/ (you may need to empty your accept-language preference to test this page)
- [ ] https://www-demo5.allizom.org/en-US/
- [ ] https://www-demo5.allizom.org/en-GB/
- [ ] https://www-demo5.allizom.org/en-US/firefox/browsers/
- [ ] https://www-demo5.allizom.org/en-GB/firefox/browsers/
- [ ] https://www-demo5.allizom.org/en-US/firefox/new/
- [ ] https://www-demo5.allizom.org/en-GB/firefox/new/
- [ ] https://www-demo5.allizom.org/en-US/firefox/browsers/mobile/ios/
- [ ] https://www-demo5.allizom.org/en-GB/firefox/browsers/mobile/ios/
- [ ] https://www-demo5.allizom.org/en-US/firefox/browsers/mobile/android/
- [ ] https://www-demo5.allizom.org/en-GB/firefox/browsers/mobile/android/
- [ ] https://www-demo5.allizom.org/en-US/firefox/products/
- [ ] https://www-demo5.allizom.org/en-GB/firefox/products/
- [ ] https://www-demo5.allizom.org/en-US/products/vpn/
- [ ] https://www-demo5.allizom.org/en-GB/products/vpn/

**Comment by a-kyne** [comment]
The GB titles aren't supposed to be duplicates of the UK ones; we're trying to make them actually different. We're keeping the same tagline on the home pages only because getting a new one approved for one of the countries will be challenging.

**Comment by a-kyne** [comment]
Hreflang tags look good and EN titles are updated as requested!
