### ISSUE TITLE
Update Firefox /thanks/ page messaging to address SmartScreen / Safe Browsing issues

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13037]
## Description

We should add a message to the [`/thanks/`](https://www.mozilla.org/en-US/firefox/download/thanks/) page (shown to all desktop users) that can help assure people who have [SmartScreen](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview) / [Safe Browsing](https://support.google.com/chrome/answer/9890866?hl=en&co=GENIE.Platform%3DDesktop) modes disabled that the Firefox installer is safe to download & install.

Also beneficial: link to a SUMO article that explains more about Safe Browsing / SmartScreen features, and why it is generally a good thing to have turned on.

### Context

A recent incident highlighted an issue where browsers such as Edge, Chrome and Brave can block the Firefox downloads and flag them as potentially harmful.

<img src="https://user-images.githubusercontent.com/400117/234273984-065aff87-c398-4861-a106-da86f5c86f60.png" alt="image" width="500" style="max-width: 100%;">

After [some investigation](https://docs.google.com/document/d/1frNkdgXGRfnvWq-Gli3fr9d7VldV7tzjl9It2a4YG5c/edit?usp=sharing), it has come to light that this is happening when users disable SmartScreen on Windows, or disable Safe Browsing on Chromium browsers such as Chrome / Brave on macOS. Both of these features default to `enabled`, but when `disabled`, all file downloads are blocked as potentially unsafe. It is unclear how many users are disabling these features (or why), but it's possible that some users don't realize what happens when they do.

### Important

We have also seen downloads blocked in Edge even when SmartScreen is enabled. Right now we think this happened when there was an intermittent outage in the SmartScreen service on Microsoft's end, so Edge defaulted to the `ALLOW_ON_USER_GESTURE` heuristic.

It is not possible for the website to detect when a download has been blocked (since the file is downloaded to a temporary directory and only then flagged as unsafe).

See [this doc](https://docs.google.com/document/d/1frNkdgXGRfnvWq-Gli3fr9d7VldV7tzjl9It2a4YG5c/edit?usp=sharing) for a more detailed explanation of events.

### Treatment

We could use styling similar to this message:

<img src="https://user-images.githubusercontent.com/400117/234272376-c18e3f2d-fe62-4da9-a853-70597e92c38c.png" alt="image" width="500" style="max-width: 100%;">

---

#### Success Criteria
- [ ] Thanks page messaging is updated to help users if their download is blocked.

**Comment by slightlyoffbeat** [comment]
Two questions:

Would we need to prioritize for windows users if we show them the 'install anyway' message or this message?

Do we have any idea of the % of users affected? I'm concerned about unintended consequences of adding messaging like this to all users -- possible overhead, distraction, etc.

**Comment by alexgibson** [comment]
Both good questions.

> Would we need to prioritize for windows users if we show them the 'install anyway' message or this message?

It looks like the current message was added in https://github.com/mozilla/bedrock/issues/9407 to address installing non-verified apps that aren't from the MS store. Is this still an issue today? (I'm not 100% sure). If so, I wonder if we could have an updated message that tries to address both issues.

> Do we have any idea of the % of users affected? I'm concerned about unintended consequences of adding messaging like this to all users -- possible overhead, distraction, etc.

Agree it's good to be both cautious and deliberate here. All I can say for certain is this effected all Edge downloads for roughly 24 hours, but is no longer the case.

@willdurand do we have any idea how many users this might effect day to day? Without some idea, it's hard to say how prominent this message should be, and who to show it to?

**Comment by willdurand** [comment]
I don't think we know the % of users affected unfortunately, and I am not sure we can find out. As mentioned above, the file is fully downloaded before the warning is shown to the user.

**Comment by alexgibson** [comment]
If we have no real idea, then it's a bit hard to prioritize what should be done here. Adding a message that gets shown to 100% of users for something that might only effect a tiny fraction of that seems like it could risk providing more distraction than benefit potentially

**Comment by alexgibson** [comment]
I've reached out to JR on Slack to see if we can have a SUMO article created for this.

**Comment by slightlyoffbeat** [comment]
I agree with Alex, that we should make sure we have some clear help articles on SUMO for this, and that they can be accessed or discovered with clicking on the 'get help' link shown above. 

If we get more clarity around severity or impact of the issue, we can start to entertain other solutions.

**Comment by alexgibson** [comment]
The SUMO team helped us create this article, which we’re going to link as a related article from our existing “get help” page

https://support.mozilla.org/en-US/kb/why-do-i-get-harmful-download-message-when-downloading-firefox-windows

**Comment by alexgibson** [comment]
Closing this out, thanks all
