### ISSUE TITLE
Use local newsletter data for email prefs page instead of requesting it from basket

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#13031]
We're seeing [issues with basket](https://github.com/mozmeao/basket/issues/1023) as a result of (I believe) the move to front-end email preferences. It is a lot more requests to the `/news/newsletters/` endpoint of basket, and it may not be scaling well for that. I propose that we move to using bedrock's cache of this data in its DB and injecting that into the page for use by the script.

**Comment by alexgibson** [comment]
Happy to try and help improve this 👍

**Comment by pmac** [comment]
Thanks Alex. I'm wondering if we can't just output some JSON in a script tag when rendering the template and have the script use that for the newsletter data it needs? Is that feasible?

**Comment by alexgibson** [comment]
My first thought was we could perhaps bundle the data in the existing JSON file we load for the newsletter strings. I think that would be a bit nicer than having things as an in-line script?

**Comment by pmac** [comment]
oh yeah, good call 👍
