### ISSUE TITLE
Feature Request - Automatically applying discount codes for users (discussion)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13043]
## Description

Normally, while offering discounts to VPN customers we show the discount on the UI and add the ability for the user to copy it to the clipboard as it’s shown below. This approach has the potential to cause friction if a user forgets that they’ve copied to code when they are on the checkout page. Furthermore, currently the back button isn’t working on the checkout page. So, if a user lands there, sees a price and doesn't feel comfortable with it, they can’t go back to the pricing page. 

## Current Capabilities

On the checkout page, as long as a discount code passed via the URL params, there is a functionality to automatically apply the discount to a selected plan.  

If the link below is tested on a private window, this functionality can be reproduced: 

https://subscriptions.firefox.com/checkout/prod_FvnsFHIfezy3ZI?&plan=price_1Iw85dJNcmPzuWtRyhMDdtM7&coupon=FIREFOX105 

## Goals

1. As we land our users on a marketing page (pricing page) after they click on a promo (with a discount code), we should automatically add the discount code to the URL and keep it there until they click on a plan. Once they click on a plan, the same promo code should be passed to the checkout page and automatically applied. 

2. The VPN product team would like a system in place to have different types of coupons applied depending if a user clicks on monthly, or 12 month plans. This logic could be handled by subplat or bedrock, and I'll add thoughts in comments.

---

#### Success Criteria
- [x] If a user comes to the VPN landing page by way of a "coupon link", then they will have the coupon automatically applied when leaving for subplat to make a purchase.

**Comment by slightlyoffbeat** [comment]
**From Umit:**

We should think about the logic that we want to add to create the custom URLs when someone clicks on monthly or yearly plan.

For instance, let's say coupon A gives yearly subscriptions, 20% off for once and coupon B gives monthly subscriptions 20% for 12 months. Logic should go like this:

When a user clicks on a yearly plan, this should be the generated URL: `https://subscriptions.firefox.com/checkout/prod_FvnsFHIfezy3ZI?&plan=price_1Iw85dJNcmPzuWtRyhMDdtM7&coupon=coupon_A`

When a user clicks on a yearly plan, this should be the generated URL: `https://subscriptions.firefox.com/checkout/prod_FvnsFHIfezy3ZI?&plan=price_1Iw85dJNcmPzuWtRyhMDdtM7&coupon=coupon_B`

Ps: The product and pricing ids above are only for example purposes.

**Comment by slightlyoffbeat** [comment]
Now that I've added everything from docs/slack I'm going to respond to Umit's request above:

My concern is that approach potentially means that bedrock would need to be continually updated with logic when new coupon codes are created. For example: 

- Coupon A is created
- Bedrock must know what parameter to pass to subplat when coupon A is used for 12 month plan, and what parameter to pass for monthly plan

I'd instead encourage a system that keeps the logic on subplat, or can be handled by coupon creation.

Some ideas for discussion. Lets say that a user lands on VPN landing page from a coupon with this example URL:

`https://www.mozilla.org/en-US/products/vpn/?coupon=springsale`

### Idea 1

We pass the selected plan along as a URL. Something like `?coupon=springsale&plan=monthly`

This would require subplat to be able to take those two items and correctly apply the correct discount at checkout. This, or something similar would be most preferable if it is possible.

### Idea 2 

We append the plan to the coupon. Like `?coupon=springsale_monthly`

This would require that every time we make a coupon code, that we also generate for `{coupon}_monthly` `{coupon}_yearly` and any other plans. This would assume that idea 1 isn't possible, but that we do have the ability to create multiple coupon codes.

------

I'd like to hear other ideas. There may be subplat capabilities that can simplify this that I'm not aware of.

**Comment by slightlyoffbeat** [comment]
Tagging @alexgibson for his input.

**Comment by alexgibson** [comment]
This all makes good sense to me, but I'm not sure i fully understand the requirements for supporting multiple coupons simultaneously though. Have I got this right?

1. User lands on https://www.mozilla.org/en-US/products/vpn/?coupon=springsale
2. The `springsale` coupon offers 20% off a one time yearly purchase, or 20% off 12 monthly payments.
3. When the user clicks to purchase either a 12-month or monthly plan, the `springsale` coupon needs to be passed to subplat so they know which type of discount to apply?

If the above is true, then I think (?) all we'd need to do is pass `coupon=springsale` on each subscription link. The `plan_id` for each link (e.g. `plan=price_1Iw85dJNcmPzuWtRyhMDdtM7`) already tells subplat if the subscription should be monthly or 12-month.

Does that make sense? (happy to chat through this in person if easier)

**Comment by slightlyoffbeat** [comment]
After a discussion with Umit, it seems the issue is that a single coupon code cannot have different behaviors for different pricing plans. A 20% of coupon for a yearly plan can only give 20% off of the first month for a monthly plan -- the desire is to have 20% off for every payment for the monthly plan. This requires different coupons.

So the proposed approach would be:
1. User lands on https://www.mozilla.org/en-US/products/vpn/?coupon=springsale
2. If user chooses yearly plan, we pass coupon slug. In this case - `springsale`
3. if user chooses monthly plan, we pass coupon slug with `_monthly` appended -  `springsale_monthly`
4. if user chooses 24 month plan, we pass coupon slug with `_24` appended - `springsale_24`


I have asked the team to be absolutely certain that this is a stripe limitation for coupon codes. If this is the approach we take, the VPN team would be responsible for creating all of the necessary coupon codes whenever we generate a coupon.

I asked the question about the whitelist and will come back with an answer.

**Comment by alexgibson** [comment]
This makes sense, thanks. I think we could easily enough add some logic in bedrock that adds a suffix to each coupon, as long as we can align on a predetermined format. It's also possible that subplat could add such a prefix themselves, since they already know the plan via the `plan` query param we already pass. But either way could work. I guess we'd need to make sure they can fail gracefully if a coupon is unknown at the very least.

Whichever route we go for, I don't think this is a huge amount of work on our side. Happy to help move this forward whenever we're ready 👍

**Comment by slightlyoffbeat** [comment]
Update:

VPN team met with Stripe, and clarified a few things. Stripe actually can use a single coupon code to meet our needs. This means we can go with a simpler solution of just passing a single coupon code to every pricing plan.

- User lands on https://www.mozilla.org/en-US/products/vpn/?coupon=springsale
No matter which pricing plan they select, we pass the same coupon slug. In this case - `springsale`

For a whitelist, could we use the stripe API to regularly check for and update a whitelist?

https://stripe.com/docs/api/coupons

**Comment by umitceylan** [comment]
Hey @slightlyoffbeat, thanks for summarizing the request and @alexgibson thanks for looking into that. 

I am checking about the next steps on this.

**Comment by slightlyoffbeat** [comment]
Consensus on success criteria:

- if a user lands on the VPN landing page or the VPN pricing page (looking forward a bit) with URL param `coupon=slug` then pass that URL param to checkout
- No whitelist/allow list for now. Pass any alphanumeric parameter in `coupon=`

**Comment by umitceylan** [comment]
This sounds good to me! Also, I am assuming that a user will be coming from the promo (via clicking the cta) where this will trigger the logic to add the coupon={sluig} param to the URL. Is that right, Dan?

**Comment by alexgibson** [comment]
@umitceylan When testing I notice that the coupon codes we use in production do not get automatically applied at checkout when we try and use them on the FxA staging server. I'm guessing because the coupons are only configured for the production environment?

This does not block us from getting this feature out the door where you can test things are working OK, but fixing this might be something that your QA team would find useful in the future.
