### ISSUE TITLE
L10N community - visibility enhancements

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13045]
## Description

The L10N team has asked for assistance in bringing more awareness to our community l10n efforts. After some discussion, we came up with a list of improvements that should help the l10n team:

### Requests we can assist with:

- Add a footer link. Initial idea is:  "Help Localize Mozilla.org" under the Support column. I'll ping the team to comment on wording and where to link to below.
- update `/contribute` - The Translate Content card should direct traffic to Pontoon

**Comment by slightlyoffbeat** [comment]
@peiying2 For the footer link:

In the request document, there 3 links proposed for the Mozilla footer. Can you help:

1. prioritize in order which you would most like to have added to footer. 
2. What the preferred copy + link would be for each one.


The three are:

- Add Localize Mozilla under the Support column
- Add an “Improve Mozilla localizations” link to [bugzilla.mozilla.org/home](https://bugzilla.mozilla.org/home)
- Include links toward our other localization efforts from the [SUMO localization page](https://support.mozilla.org/en-US/contribute/l10n)

**Comment by peiying2** [comment]
> @peiying2 For the footer link:
> 
> In the request document, there 3 links proposed for the Mozilla footer. Can you help:
> 
> 1. prioritize in order which you would most like to have added to footer.
> 2. What the preferred copy + link would be for each one.
> 
> The three are:
> 
> * Add Localize Mozilla under the Support column
> * Add an “Improve Mozilla localizations” link to [bugzilla.mozilla.org/home](https://bugzilla.mozilla.org/home)
> * Include links toward our other localization efforts from the [SUMO localization page](https://support.mozilla.org/en-US/contribute/l10n)

Thank you for filing the issue. I am also working with the team to decide where the link points to which generates a lot of debate both technical and user experience, etc. So to help move things forward, let's focus on these in the order of priority and ease of implementation:
- Translate Content link: points to Pontoon
- Footer: Add Localize Mozilla under the Support column
- Add an “Improve Mozilla localizations” link to [bugzilla.mozilla.org/home/Mozilla Localization](https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla+Localizations).

The team is working on the Landing page content. One agreement we reached is that we host our own landing page so we can update the content more easily without tapping into the Bedrock resource. The landing page will contain basic l10n process. The question we are debating internally is whether this is the first place to point potential contributors to or they should land on Pontoon, and Pontoon has a way to provide more info if the visitors want to find out more. We hope to reach an agreement soon, but I don't want to block you from carrying out the things that seem to be low hanging fruit.

For the Community page that focuses on product l10n, Scott D within our org will help us rewrite and polish the text. I will reach out to Konstantina to get it implemented once it's ready.

**Comment by peiying2** [comment]
@slightlyoffbeat we have decided to direct traffic to Pontoon from mozilla.org site, at least for now, so we don't block it from moving forward

**Comment by alexgibson** [comment]
I can't see the request document linked in this issue, so am trying to consolidate what needs doing here from the convo above:

1. Update the "Translate Content" card on https://www.mozilla.org/en-US/contribute/ to point directly to https://pontoon.mozilla.org/
2. Add a "Localize Mozilla" link in the site footer under "Support" that points to ? (Pontoon as well?)
3. Add an "Improve Mozilla localizations" link to ? that points to https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla+Localizations

Can you help clarify here @peiying2? Thanks

**Comment by peiying2** [comment]
> I can't see the request document linked in this issue, so am trying to consolidate what needs doing here from the convo above:

Just shared the doc with you two [here](https://docs.google.com/document/d/1Pr4AbHqvnvtlCdz4wKyFW2eke4sK8fqa-TOC0KbsBGQ/edit#heading=h.b8f25nd2c2ge).
> 
>     1. Update the "Translate Content" card on https://www.mozilla.org/en-US/contribute/ to point directly to https://pontoon.mozilla.org/

Correct.
> 
>     2. Add a "Localize Mozilla" link in the site footer under "Support" that points to ? (Pontoon as well?)
Correct.
> 
>     3. Add an "Improve Mozilla localizations" link to ? that points to https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla+Localizations
>
Correct. 

@alexgibson all your guesses are spot on. Please proceed with the recommended changes. Thank you!!

**Comment by alexgibson** [comment]
@peiying2 can you please clarify 3, what page should this link appear on?

**Comment by peiying2** [comment]
> @peiying2 can you please clarify 3, what page should this link appear on?

Initially we were thinking of footer, but there is already Bugzilla entry in the Support column. Does it sound redundant to add a localization specific one?

**Comment by alexgibson** [comment]
@peiying2 so the request is to add two links for localization to the footer?

- Localize Mozilla
- Improve Mozilla localizations

I guess my question here is from a user perspective - what does each link mean, which one should I click? It doesn't quite seem clear to me.

**Comment by peiying2** [comment]
> @peiying2 so the request is to add two links for localization to the footer?
> 
>     * Localize Mozilla
> 
>     * Improve Mozilla localizations
> 
> 
> I guess my question here is from a user perspective - what does each link mean, which one should I click? It doesn't quite seem clear to me.

Let's just use `Localize Mozilla` and drop the other one. Let me know the ETA to implement the changes. Thanks a mil!

**Comment by peiying2** [comment]
@alexgibson When you get a chance, let me know what the ETA for the issue is. Thx!

**Comment by slightlyoffbeat** [comment]
@peiying2 it is in our backlog, but is not yet assigned for work. I asked our PM to take a look at everyone's schedules and see if we can get a more firm date attached to this.

**Comment by stevejalim** [comment]
I picked this up between my backend things to return one of the many favours I owe @peiying2 😄 - it's at PR now, with Craig tagged to take a look
