### ISSUE TITLE
Remove firefox/android SMS experiment

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13040]
## Description

This experiment has been running for 10 months now. Is there a conclusion? Can we turn it off / remove?

https://www-dev.allizom.org/en-US/firefox/browsers/mobile/android/?v=2&geo=us

---

#### Success Criteria

- [ ] Experiment is concluded and deactivated / removed

**Comment by alexgibson** [comment]
@slightlyoffbeat are we OK to turn this experiment off?

**Comment by slightlyoffbeat** [comment]
yes we can turn off.
