### ISSUE TITLE
Stage CDN does not seem to be including query parameters in cache key

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13047]
## Description

Query parameters that we rely on for showing different types of content does not seem to be working correctly on stage.

### Steps to reproduce

1. Open https://www.allizom.org/en-US/firefox/browsers/mobile/
2. Open https://www.allizom.org/en-US/firefox/browsers/mobile/?xv=legacy

### Expected result

The second step should show a different template, like it does here in prod https://www.mozilla.org/en-US/firefox/browsers/mobile/?xv=legacy

### Actual result

The cached response from the first step is shown instead.

### Environment

N/A

**Comment by bkochendorfer** [comment]
Should be resolved now, thank you

**Comment by alexgibson** [comment]
Thanks @bkochendorfer !
