### ISSUE TITLE
Add message to email preference center on timing of unsubscribes

### ISSUE THREAD

**Issue by krattliff11** [mozilla/bedrock#13050]
In the past, there have been cases of users receiving emails 24 hours after unsubscribing from a newsletter. Acoustic stores newsletters and global opt-out fields and gets the data from the user's email preference center (basket). To better communicate expectations with our email audiences, we'd like to add this language to the email preference center:

It may take 1-2 business days to process your opt-out request during which time you may still receive another email.

---

Success Criteria
- language appears on the email preference center page for all users in their preferred language

**Comment by alexgibson** [comment]
Thanks for filing this - in terms of placement, may I suggest underneath the unsubscribe all checkbox?

Hopefully here it's pretty difficult to miss when someone clicks submit:

![image](https://user-images.githubusercontent.com/400117/236168951-72ea8b5b-835e-45a0-8bf7-4ce163023e6b.png)

**Comment by alexgibson** [comment]
Does this make sense to you, @pmac? ^

**Comment by krattliff11** [comment]
Hey Alex,

That looks like it will work.

Thank you,
Tina Rattliff (she/her)
Mozilla
***@***.*** | @tinacorn on Slack

**Comment by pmac** [comment]
Looks good to me Alex. Thanks!

**Comment by krattliff11** [comment]
Thanks, Alex & Pmac
