### ISSUE TITLE
Redirects mistake short path names such as "/vpn/" as locale codes.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13073]
## Description

By default our redirect helpers are set up to match a provided pattern against both a plain URL (e.g. `/download/`) or one with a locale prefix (e.g. `/fr/download/`). This works for the most part, unless the specific pattern you want to redirect also contains something like a three letter path at the beginning (e.g. `/vpn/download/`) and we already have a redirect for just `/download/`.

One possible fix for this could be to add a list of known non-locales (such as `vpn`) to our redirect helper so it can avoid false locale matches.

Here's an example of where we have an issue like this currently:

### Steps to reproduce

Case example:

Let's say we want to add the following redirect:

```
redirect(r"^vpn/download/?$", "products.vpn.download"),
```

But we already have this redirect that comes before it:

```
redirect(r"^download/?$", "firefox.new"),
```

### Expected result

`/vpn/download/` should redirect to `/products/vpn/download/`

### Actual result

`/vpn/download/` redirects to `/vpn/firefox/new/` which is a 404.

### Environment

N/A

**Comment by pmac** [comment]
Would it be too confusing to just make sure any 3 letter prefix redirects like the VPN stuff are first? That would be the easy fix. Order matters for redirects. We may not know which `redirects.py` is first in our system, but perhaps that is a thing we could fix.

**Comment by alexgibson** [comment]
Ensuring the order of redirects is definitely the easiest fix, however it becomes a little confusing when multiple redirects are all in different places e.g:

- `redirect(r"^download/?$", "firefox.new"),` is in `firefox/redirects.py`.
- `redirect(r"^vpn/download/?$", "products.vpn.download"),` is in `products/redirects.py`

The first redirect directly effects the second, which isn't obvious especially when they are in different files amongst hundreds of other redirects.

**Comment by alexgibson** [comment]
Closing this as we went for adding `base/redirects.py`
