### ISSUE TITLE
Remove doubleclick pixel from /thanks/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13083]
## Description

The doubleclick [pixel](https://github.com/mozilla/bedrock/blob/main/media/js/base/mozilla-pixel.js) has not been enabled in production since Q4 last year (it seems like it got inadvertently wiped out in our infra migration), but it still exists in our codebase. In that time, no-one seems to have noticed it's not firing.

Is anyone in marketing today still using it? If not, can we remove it?

If it is still useful, then should it be re-enabled?

---

#### Success Criteria
- [ ] Pixel is either reinstated or removed.

**Comment by alexgibson** [comment]
@slightlyoffbeat can you please weight in here?

**Comment by alexgibson** [comment]
I haven't got any responses on this after asking around in several places, so rather than spend time and effort documenting its existence and fixing the CSP issues related to it, I think we should recommend removing it.

It'll always be there in Git history should we need to resurrect it.

**Comment by slightlyoffbeat** [comment]
as a last effort, I messaged our leads for lifecycle and activations. But Otherwise, yes I support removing it.
