### ISSUE TITLE
Temporary Pocket Updates page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13123]
## Description

We are building a new page that allows users to sign up for pocket updates. This page is not ready, and we will be building a placeholder page that can support some short-term needs of the communications team.

Details
- English only
- URL: `getpocket.com/en/pocket-updates-signup`

Design: [Figma](https://www.figma.com/file/WG0GgITA0UEIeHaqKOEC8S/Pocket-Marketing-Sign-up-LP-(Copy)?type=design&node-id=202%3A389&t=DDK5dktGjD2vp7Kj-1)

Design Note: The link text can use whatever the default link text color is. The color in the mockup may not be accurate.

Copy: Can be taken from Figma file.
![Mobile](https://github.com/mozilla/bedrock/assets/2030656/45ce63bd-35b2-43af-a657-a12c6c23f327)
![Pocket Marketing Email Sign Up - 16](https://github.com/mozilla/bedrock/assets/2030656/960b05bf-06a0-4b9b-bde2-05d67bc9dcff)

Screenshots (included)

**Comment by slightlyoffbeat** [comment]
I would like to get this on a demo server live, but please do not merge until i've given a thumbs up.

**Comment by slightlyoffbeat** [comment]
Looks good to me. Here are the changes we should implement:

1. Update URL to `getpocket.com/en/pocket-updates-signup/pilot`
2. Forward any traffic from root `/pocket-updates-signup/` to the above URL


This is because we will eventually have a system in place where the slug (in this case "pilot") can be passed to the email signup. That system is not in place right now, but I want to make sure we are using a URL that can still be useful after the new system is in place. We can also just forward all other traffic just in case until we have something at that root page.

**Comment by reemhamz** [comment]
Mock-up of the email sign up page for when it's ready:

![Screenshot 2023-05-17 at 8 03 48 PM](https://github.com/mozilla/bedrock/assets/42309026/73b46d91-a7b7-4920-8c13-65dedbbda241)

**Comment by alexgibson** [comment]
Looks like this one was done
