### ISSUE TITLE
Prefer addEventListener('change') over addListener for media queries

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13129]
## Description

We still have several occurrences of `addListener` in the code base when handling media queries in JS. This method is deprecated and may no longer be supported by browsers in the future. We should switch to `addEventListener` for browsers that support it, falling back to the old method like we do here:

 https://github.com/mozilla/bedrock/blob/main/media/js/pocket/mobile-nav.es6.js#L101-L115

**Comment by amishk783** [comment]
hey @alexgibson, I would like to work on this issue.

**Comment by yashkhandelwal123** [comment]
hi, I would like to work on it.

**Comment by alexgibson** [comment]
Rather than let this sit unfixed I'm going to knock it out. Thanks for showing interest though
