### ISSUE TITLE
Dev Edition release notes page doesn't mention Dev Edition

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13142]
## Description

Both Firefox Beta and Dev Edition share the same release channel, so their release notes are the same.

When opening the release notes page from Dev Edition (About -> What's New) it's confusing however, since the page only mentions Firefox Beta: https://www.mozilla.org/en-US/firefox/114.0beta/releasenotes/

We should update the page title to read "Firefox Beta and Developer Edition Release Notes" so it's clearer that it's the right page for both browsers.

**Comment by sharmatanikesh** [comment]
Hey, Can I work on this issue?

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/14022
