### ISSUE TITLE
Inter font within box on /firefox/privacy/products doesn't load when not installed locally

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla/bedrock#13187]
## Description

The Inter font within the box on /firefox/privacy/products gets replaced with a serif font like Times New Roman when not locally installed. 

### When Inter font is NOT installed on local system
<img width="1451" alt="Screenshot 2023-05-25 at 2 27 55 AM" src="https://github.com/mozilla/bedrock/assets/17863082/04409a6f-9ed3-413e-916a-688e906e6a37">

### When Inter font IS installed locally
<img width="1451" alt="Screenshot 2023-05-25 at 2 31 47 AM" src="https://github.com/mozilla/bedrock/assets/17863082/64891ba4-99c0-4fc3-aa9f-6898e0f6c221">

What browser and operating system are you using?
Windows 11, Firefox Nightly v115 (2023-05-24)

**Comment by stephaniehobson** [comment]
Fixed in https://github.com/mozilla/bedrock/issues/14248
