### ISSUE TITLE
Remove Sidebar Menu JS from /all

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13236]
## Description

In the recent Protocol upgrade the JavaScript to support the side bar menu component was added to /all. That makes sense, there's a side bar. However, it's only displayed to visitors who do not meet modern browser requirements and the JavaScript itself only takes effect on mobile browsers (because this sidebar menu does not have any nested menu items). 

I believe collapsing the menu on mobile makes the page harder to navigate, since if the user misses the menu (because it is collapsed) they have to scroll through all the language options for desktop browsers before getting to the mobile download links.

The better user experience for everyone is to remove the javascript IMHO.

---

#### Success Criteria
- [ ] Sidebar menu JS is removed from all-downloads-unified-init.es6.js

**Comment by stephaniehobson** [comment]
@alexgibson Wondering if you have thoughts on this since you built the original page and added the menu js in the recent update.

**Comment by alexgibson** [comment]
Happy to remove if we think it makes for a better UX 👍
