### ISSUE TITLE
Find a Replacement for Meinheld WSGI Server

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#13247]
## Description

Currently, our project relies on the [Meinheld](https://github.com/mopemope/meinheld) WSGI server as the underlying server technology, along with gunicorn, for serving our application. However, this project has not been updated, maintained, or seen a release in over 3 years. It also does not compile on Python versions > 3.9. 

This GitHub issue aims to discuss and identify a suitable replacement for Meinheld.

**Comment by stevejalim** [comment]
@robhudson I think you might have already spotted this, but as well as Python 3.10/3.11 being issues, it looks like pip is going to enforce a related limit soon too

```
# DEPRECATION: meinheld is being installed using the legacy 'setup.py install' method, 
# because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. 
# pip 23.1 will enforce this behaviour change. 
# A possible replacement is to enable the '--use-pep517' option. Discussion can be found 
# at https://github.com/pypa/pip/issues/8559
 ```

**Comment by robhudson** [comment]
We tested uWSGI on bedrock-dev today and saw very slow start times which caused our Kubernetes health checks to "flap" resulting in a lot of pod churn. We tested decreasing the number of workers to reduce memory and CPU consumption which helped some. We also tested both `lazy-apps` as set to true and false and both showed slow start up times. We reverted the commit on main for further testing.

**Comment by robhudson** [comment]
Commit 4f8fb977 migrated to using gunicorn+gevent and all is running well. Closing.
