### ISSUE TITLE
New page for advertising

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13256]
## Description

We need to quickly stand up a page for Mozilla advertising. This is a WIP, but if should get this started as soon as possible.

Page URL: `/advertising`
Language: English only

[Copy doc (WIP)](https://docs.google.com/document/d/10QeYPUYdkIoNuL5yAaODY45fV5O_Gl4UAEn4SOD_JgY/edit?usp=sharing)

[Design](https://drive.google.com/file/d/14uSjmsNSeT7HjclxbfB-IIJ0ZLnwUPCD/view?usp=sharing) - a combination of callout components for the top and bottom section, and picto components for the middle section.

Stakeholders - Anne Goodrich (questions on content)
Elise - For layout, and recommendations of creative for picto
Dan Brown - for everything else

**Comment by slightlyoffbeat** [comment]
The URL for the top and bottom CTA is:

`https://mozilla.formstack.com/forms/advertising`

**Comment by alexgibson** [comment]
This seems to be live, closing
