### ISSUE TITLE
Ensure that Firefox can continue to refer to https://www.mozilla.org/%LOCALE%/firefox/set-as-default/thanks/

### ISSUE THREAD

**Issue by ncalexan** [mozilla/bedrock#13253]
## Description

As part of https://bugzilla.mozilla.org/show_bug.cgi?id=1835352, Firefox started referring to https://www.mozilla.org/%LOCALE%/firefox/set-as-default/thanks/: see https://searchfox.org/mozilla-central/rev/b91e9bef5a6d6f7b549fbc9cba70cb4665ed3866/browser/app/profile/firefox.js#285.

This ticket tracks adding a comment or an automated test that ensures that Firefox can continue to refer to this endpoint.  (I should have done this when the change was made but I did not think of it at the time.)

**Comment by stevejalim** [comment]
For the paper trail, at some point in early July 2025, www.mozilla.org/firefox/set-as-default/thanks/ will redirect to https://www.firefox.com/landing/set-as-default/thanks/ which has the same content as www.mozilla.org - see #16355

**Comment by stevejalim** [comment]
@ncalexan Will the redirect to www.firefox.com break any behaviour in FF itself? As long as it's simply opening the www.m.o URL then the redirect will handle it from there fine

**Comment by ncalexan** [comment]
> [@ncalexan](https://github.com/ncalexan) Will the redirect to [www.firefox.com](http://www.firefox.com) break any behaviour in FF itself? As long as it's simply opening the [www.m.o](http://www.m.o) URL then the redirect will handle it from there fine

Sorry for letting this sit for so long.  AFAICT, there will be *no problem*:
1.  The relevant link in Firefox is no longer present; the prefs that referenced `/thanks` have been removed.
2. After [Bug 1942328](https://bugzilla.mozilla.org/show_bug.cgi?id=1942328), the `UITour` components will work when hosted on firefox.com.  That's not directly related, but it's the use case that came to mind.
