### ISSUE TITLE
Duplicate Security & Privacy newsletter landing page

### ISSUE THREAD

**Issue by krattliff11** [mozilla/bedrock#13258]
## Description
Before the monitor premium product launch, we want to gauge interest and gather a waitlist by utilizing the privacy and security newsletter and a dedicated entry point.

Lifecycle marketing is requesting a copy of the privacy and security newsletter signup page. (https://www.mozilla.org/en-US/newsletter/security-and-privacy/). 

What's different?

- copy change - Join the Mozilla Security & Privacy Newsletter and sign up for the Monitor Premium waitlist! (vetting in progress)
- URL needs to be unique so that lifecycle marketing can segment the waitlist signups and announce monitor premium when it is available. suggestion to use -> https://www.mozilla.org/en-US/newsletter/security-and-privacy/monitor-waitlist
- slug = security-privacy-news

Product: Monitor Premium
Language: EN

---

#### Success Criteria
1) A new sign-up page is available for the privacy and security newsletter
2) the copy mentions Montior premium waitlist
3) the URL is unique so that lifecycle marketing can tag new sign-ups and send announcement emails later this year

**Comment by alexgibson** [comment]
@krattliff11 not sure if this is an old / outdated request but just checking - is this still needed?

**Comment by alexgibson** [comment]
Oh never mind, looks like this was done at https://www.mozilla.org/en-US/newsletter/monitor-waitlist/
