### ISSUE TITLE
VPN download link on stage points to incorrect domain

### ISSUE THREAD

**Issue by jswinarton** [mozilla/bedrock#13312]
## Description

As part of the FPN sunset initiative we have cleaned up the domains that the VPN project uses. Previously, the VPN used `stage-vpn.guardian.nonprod.cloudops.mozgcp.net`, but it now uses `stage.guardian.nonprod.cloudops.mozgcp.net` (i.e. without the `-vpn`). This is now breaking download links on stage bedrock pages.

### Steps to reproduce

1. Visit https://www-dev.allizom.org/en-US/products/vpn/download/
2. Click the "Get Mozilla VPN" link under "Based on your current device"

### Expected result

The link should direct to the new domain.

### Actual result

The link directs to the old domain. (This still works at the moment but will stop working soon. We plan to take this down on June 27.)

### Environment

Firefox/Ubuntu

**Comment by jswinarton** [comment]
Hi @craigcook, thank you for making this change! I just went to verify that this is live, but the links on https://www-dev.allizom.org/en-US/products/vpn/download/ still point to the old domain. I checked on the What's Deployed status to verify that this commit is live and it seems to be -- maybe I am missing something?

**Comment by alexgibson** [comment]
@jswinarton hi thanks for the update. It looks like there might be some download links that we're missed initially. I'll take a look

**Comment by alexgibson** [comment]
Hmm, code looks ok - which leads me to wonder if there's an environment variable that needs updating

**Comment by alexgibson** [comment]
Tried removing the variables here: https://github.com/mozmeao/www-config/pull/525

If this doesn't work I'll ping Brett (our SRE) to take a look tomorrow

**Comment by alexgibson** [comment]
Looks like this got fixed by our SRE follks, closing
