### ISSUE TITLE
Serve ESR to users on old desktop operating systems

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#13317]
In [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1840562) the request is for bouncer to handle redirecting users requesting desktop firefox from Windows 7, 8, and 8.1, and MacOS 10.12 to 10.14 from release Firefox 115 and later to ESR 115. Due to the current state of our bouncer service, this may not be able to be accomplished before Firefox 116 is released and so they've asked us if it is possible for us to handle this change on the website. We'd need to change the download bouncer URL `product` from stub or full installer to ESR-115 for users on these operating systems. We'd also need to make sure that users who'd have normally received stub get the proper 32 or 64bit full installer since stub installer is the thing that makes sure that is correct normally, but there is no stub installer for ESR.

**Comment by alexgibson** [comment]
OK, breaking this down a little:

- This needs to launch some time after 115 ships, but before 116 (July 4th - August 1st).
- If the visitor is on  <= Windows 8.1, or on <= macOS 10.14 then:
  - Replace Firefox release/beta/dev/nightly links with ESR-115.
  - Replace links for both stub and full installers.
  - Try to detect 32/64bit readiness, since ESR has no stub installer.

Does that sound right?

**Comment by alexgibson** [comment]
Another question: do we need to redirect people to ESR-115 explicitly, or would `firefox-esr-latest-ssl` be sufficient?

If we need to send them to 115, what would the bouncer URL be?

**Comment by pmac** [comment]
> Does that sound right?

Sounds right to me

> Another question: do we need to redirect people to ESR-115 explicitly, or would `firefox-esr-latest-ssl` be sufficient?

I think that should be sufficient, but it may need to be the `-next` variant as that's what 115 will be for a few weeks.

**Comment by pmac** [comment]
> Possible UI treatments for a quick fix for Beta / Dev Edition / Nightly:

I like this. The only down side is that l10n won't be ready in time, but it's better than getting people the wrong build.
