### ISSUE TITLE
Newsletter subscriptions page creates broken URL when left open for a period of time

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#13324]
## Description

With the page open over a lunch break, then editing the form and submitting, I see 2 requests in my network panel...

1. `OPTIONS https://<basket-url>/news/user//`
2. `POST https://<basket-url>/news/user//`

Looks like the token expired since I opened the page and when I submitted the form.

### Steps to reproduce

1. Open `https://www.mozilla.org/en-US/newsletter/existing/<token>/`
2. Wait about an hour
3. Submit the form

**Comment by alexgibson** [comment]
Yeah, looks like the cookie we et lasts for 1 hour. I'm not sure if we need to extend the duration (?), but we should probably fail more gracefully and redirect back to `/recovery/` when it expires.
