### ISSUE TITLE
Mozilla mailing address change

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#13352]
Please change the Mozilla mailing address on the pages below to the following:

**149 New Montgomery Street, 4th floor
San Francisco, CA 94105**

The pages where this will be required are below:

- https://www.mozilla.org/en-US/contact/spaces/san-francisco/

They would like this new mailing address to go live on **August 1, 2023**. 

Please let Emma know if you have any questions. Thank you :)

**Comment by NitinRana01125532553** [comment]
Hey, Do you also want the map images changed for new address ?

**Comment by enavajas** [comment]
> Hey, Do you also want the map images changed for new address ?

Yes please!

**Comment by stevejalim** [comment]
@NitinRana01125532553 When you make your pull request, please add the Do Not Merge label to it and note the 1 August go-live date in the description. Thanks so much!

**Comment by stevejalim** [comment]
@NitinRana01125532553 Hi - yes, of course, please feel free to contact me if you still have questions, or please just comment here

**Comment by stevejalim** [comment]
@craigcook @reemhamz Either of you recall how to best get the two map images out of OpenStreetMap, please? I just tried to do it to help Nitin, but they're too busy

**Comment by craigcook** [comment]
I also get errors searching on OpenStreetMap but it works about half the time. I can get screenshots.

**Comment by NitinRana01125532553** [comment]
I took the screenshots but what will be the proper way of using them? 
should I delete the previous images from Media>img>contact and add new images with same names ?

**Comment by stevejalim** [comment]
Yeah @NitinRana01125532553 I think that'd work fine. Thanks for checking

**Comment by NitinRana01125532553** [comment]
are these images right? shall i commit ?

![image](https://github.com/mozilla/bedrock/assets/63962929/6abe3957-9c5f-414a-b4b9-0a18c929624d)

![image](https://github.com/mozilla/bedrock/assets/63962929/3b5d3e4b-4a67-4e5f-9b6e-a7a75b0d2c53)

**Comment by stevejalim** [comment]
@craigcook do the new maps look right to you?
