### ISSUE TITLE
Faulty link in 115.0.2 releasenotes

### ISSUE THREAD

**Issue by D4n2021** [mozilla/bedrock#13380]
## Description

"(bug 1840746)" on the [115.0.2 releasenotes page ](https://www.mozilla.org/en-US/firefox/115.0.2/releasenotes/) doesn't link to the bugzilla entry, instead it links to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternTransform
instead of to
https://bugzilla.mozilla.org/show_bug.cgi?id=1840746

### Steps to reproduce

1. visit https://www.mozilla.org/en-US/firefox/115.0.2/releasenotes/
2. click on "(bug 1840746)"

### Expected result

should be linking to https://bugzilla.mozilla.org/show_bug.cgi?id=1840746

### Actual result

links to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternTransform

### Environment

115.0.2, Win 10 22H2

**Comment by stevejalim** [comment]
One for you @pascalchevrel ? I can move it to BZ if you need it there

**Comment by pascalchevrel** [comment]
This is fixed, thanks for the ping @stevejalim
