### ISSUE TITLE
Remove 2 names from senior leadership page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#13392]
Hi! For the senior leadership page, we would like to remove the following two people:

- Matt Koidin
- Mardi Douglass 

The link to access the page is: [https://www.mozilla.org/en-US/about/leadership/senior-leadership/](url)

Please let me know if you have any questions. Thank you!!

**Comment by craigcook** [comment]
Fixed in https://github.com/mozilla/bedrock/commit/869f11f1b19df668c187a312d9a8a4dedd23e3a6

**Comment by enavajas** [comment]
thanks so much @nathan-barrett and @craigcook
