### ISSUE TITLE
Investigate odd pause during npm install during bedrock container build

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#13413]
I saw this with timing during the demos Cloud Build, but I've experienced it locally, too

<img width="919" alt="Screenshot 2023-07-17 at 20 09 39" src="https://github.com/mozilla/bedrock/assets/101457/eb951b09-22a3-4715-b4ee-fafe346f2147">

It _looks_ like it's `browserlist` chewing something, but I've also had the pause without seeing that message when just doing a `make clean build` locally

**Comment by alexgibson** [comment]
I added a commit to update caniuse-lite in https://github.com/mozilla/bedrock/pull/13396

**Comment by alexgibson** [comment]
I added a commit to update caniuse-lite in https://github.com/mozilla/bedrock/pull/13396
