### ISSUE TITLE
Redirect /firefox/mobile/get-app/ to /firefox/browsers/mobile/get-app/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13469]
## Description

The [get-app page](https://www.mozilla.org/en-US/firefox/mobile/get-app/) should live under the same IA as the rest of the Firefox mobile pages.

We should move it to https://www.mozilla.org/en-US/firefox/browsers/mobile/get-app/ and redirect the old URL.

---

#### Success Criteria
- [ ] Page now lives at new URL
- [ ] Redirect is in place for old URL

**Comment by Soumya0803** [comment]
Hi @alexgibson
I would like to work on this.

**Comment by alexgibson** [comment]
Completed in https://github.com/mozilla/bedrock/pull/13819
