### ISSUE TITLE
Update /firefox/browsers/compare/brave/ utility section

### ISSUE THREAD

**Issue by chrismore** [mozilla/bedrock#13471]
👋 Hi friends! 

Small update to a www.mozilla.org page.

### Steps to reproduce

1. Visit: https://www.mozilla.org/en-US/firefox/browsers/compare/brave/
2. Review `Utility` section

### Expected result

`In-browser screenshot tool` should be checked
![image](https://github.com/mozilla/bedrock/assets/751491/d0954d80-6e9c-40ad-8599-a94ac5f829b4)

### Actual result

`In-browser screenshot tool` not checked
![image](https://github.com/mozilla/bedrock/assets/751491/37a1ee98-be4d-4611-a840-0b8ac52b979f)

Brave shipped a [screenshot tool in April 2023](https://twitter.com/brave/status/1646614006767968257?lang=en)

❤️

**Comment by alexgibson** [comment]
Thanks @chrismore 👋

**Comment by chrismore** [comment]
@alexgibson I was counting the minutes until I heard from you or @craigcook. 😉 Hope you two are doing well.

**Comment by alexgibson** [comment]
Same to you @chrismore, hope everything is well!
