### ISSUE TITLE
VPN Prices should be formatted for the locale of the page

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#13476]
We're currently getting this almost right, but in some cases the format of the number and symbol (e.g. `4.99 €` vs `€4,99`) vary quite a bit for different locales. As part of this we should move to letting Fluent handle this kind of formatting. 

`FluentNumber` is a [class in the Fluent system](https://projectfluent.org/python-fluent/fluent.runtime/stable/usage.html#numbers) that can format number input for a particular locale and currency. It would be nice if we could build in handling for currency formatting into the `ftl()` helper in bedrock for use in templates.

**Comment by alexgibson** [comment]
I opened a PR linked above for the short term fix that updates Euro formatting for en locales.

Looking in bedrock, we're already using babel's `format_currency` helper in some places for the newer Relay code. We could use that for VPN also, however if we want to add currency formatting to the `ftl()` helper like you suggest, I'll leave that for a back-end dev to take a look at.
