### ISSUE TITLE
Incorrect term in Fx 116.0 changelog

### ISSUE THREAD

**Issue by D4n2021** [mozilla/bedrock#13486]
## Description

In the 116.0 release changelog, it says "**command** + shift + t".

### Steps to reproduce

Visit this page and read the "Changed" section entry: https://www.mozilla.org/en-US/firefox/116.0/releasenotes/

### Expected result

Should say "**Ctrl** + shift +t" (Windows keybinding) or "Ctrl+shift+t or Command+shift+t" if this change is also directed at devices that have a "Command" key instead of "Ctrl" key.

### Actual result

Says "**command** + shift + t".

### Environment

What browser and operating system are you using?

Fx 116.0, Win 10 22H2

**Comment by alexgibson** [comment]
@pascalchevrel is this something you could take a look at? thanks

**Comment by pascalchevrel** [comment]
I am on PTO, @dsmithpadilla could you make the change please? Thanks!

**Comment by dsmithpadilla** [comment]
Thank you, this has been corrected! Since Release Management usually handle release changelogs/release notes, you can tag that team here or file a bugzilla for a quicker response. Either way, we will be monitoring this closely moving forward.

**Comment by dsmithpadilla** [comment]
yeah, @ mozilla/release-management
