### ISSUE TITLE
Update Glean.js to 2.0.0

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13493]
## Description

https://github.com/mozilla/glean.js/releases/tag/v2.0.0

**Comment by stevejalim** [comment]
Heya - do we also need to update glean-parser in lock-step with this? I just happened to see this comment in the prod.in dependencies file:

https://github.com/mozilla/bedrock/blob/ec7a9d5746b61f0e9b3456f5294c84fdad4fa801/requirements/prod.in#L30

**Comment by alexgibson** [comment]
> Heya - do we also need to update glean-parser in lock-step with this? I just happened to see this comment in the prod.in dependencies file:

Already taken care of in the PR, but thanks for the call out!
