### ISSUE TITLE
In the "You've already got the browser" popup, the "Just download the browser" text is unreadable when focused

### ISSUE THREAD

**Issue by dholbert** [mozilla/bedrock#13585]
## Description
If you use Firefox to visit https://www.mozilla.org/en-US/firefox/new/ and click "download firefox", there's an in-content popup that appears, with a "Just download firefox" button.

At that point, if you use your keyboard to focus the "Just download the browser" button, then its text becomes unreadable

### Steps to reproduce
1. Visit https://www.mozilla.org/en-US/firefox/new/
2. Click "Download Firefox"
3. Press your Tab key 3 times (to give focus to the "Just Download the Browser" button).  Do not hover the button with your mouse.

### Expected result
The text should remain readable, with whatever focus styling the page decides to apply.

### Actual result

The text fades away and becomes unreadable. (I think we chose this color with an expectation that it would be drawn over a dark background -- which is what happens if you click or hover the button, but not if you simply focus it with your tab key.)  Here's a screenshot of how it looks:
![image](https://github.com/mozilla/bedrock/assets/426803/e43d66ec-8642-4e8e-aef1-b22ed1dbc1a0)

### Environment
Firefox 116.0.2 (64-bit)
Ubuntu 22.04

**Comment by alexgibson** [comment]
Thanks for the report!

**Comment by stephaniehobson** [comment]
Thank you for the report! A fix for this was just merged but it could be a day or two until it deploys to production.
