### ISSUE TITLE
Remove IE from browser comparison pages

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#13600]
## Description

Our desktop browser comparison pages include Internet Explorer among our competitors. IE has been officially deceased for some time and is simply no longer relevant in comparisons of recent browsers. We should remove mentions of IE from these pages and remove the IE standalone comparison page.

https://www.mozilla.org/firefox/browsers/compare/
https://www.mozilla.org/firefox/browsers/compare/ie/

**Comment by janbrasna** [comment]
Resolved in #14142 with #14167
