### ISSUE TITLE
WNP 118 EU (translate)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13619]
## Description

Copy doc: https://docs.google.com/document/d/1mCJtM_yeiZt5Wdo09eICOdRXhRgScvmiQxLy2io-LYU/edit?usp=sharing
Figma file: https://www.figma.com/file/8fVLbzzAd40lSSLuOwCfnl/EU_Firefox_WNP_21-23?type=design&node-id=3396-26&mode=design&t=XrOWgiBLD1lqoR8r-0

Note:

The page has two CTAs based on FF being default or not:

- "Set Firefox as your default browser"
- "Try it now" (which will link to the homepage in a different language)

---

#### Success Criteria
- [ ] Live before Sept 26

**Comment by marinee-b** [comment]
Hi @stephaniehobson, can we lowercase "Firefox Translations" to "Firefox translations" for all versions, please? 
(GTM/product ask on how we talk about the feature)

**Comment by stephaniehobson** [comment]
Updated :)
