### ISSUE TITLE
"VPN for X" SEO Pages (Batch 2 and 3)

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#13632]
Hi! We are replacing the content and metadata on the "VPN for X" pages at:

- /products/vpn/features/servers/
- /products/vpn/features/fast/
- /products/vpn/features/no-logging/
- /products/vpn/features/private/
- /products/vpn/features/secure/
- /products/vpn/features/open-source/
- /products/vpn/features/gaming/
- /products/vpn/features/work/
- /products/vpn/features/home/
- /products/vpn/resource-center/hide-ip/
- /products/vpn/resource-center/anonymous/
- /products/vpn/resource-center/risks-free-vpn/
- /products/vpn/resource-center/vpn-does/

Currently, these pages are duplicates, with a single sentence to distinguish them. The new pages are unique, and now contain potentially useful information.

The links with the updated copy are below:

- [VPN servers (no. of…)](https://docs.google.com/document/d/1GPkeCzC7o0JaU18X1GDnyH5rQWRMIEjUGRs429aGtjo/edit?usp=sharing)
- [Fast](https://docs.google.com/document/d/1QjsK3hAginK2xBkEEn7Xy6nBHTX_mCrsNN6vKV93Q5Q/edit?usp=sharing)
- [No logging](https://docs.google.com/document/d/1iOoAdsTzply-Y5TNqnDg-LwA5YDjqqTPrLBg2Ft1gvw/edit)
- [Private](https://docs.google.com/document/d/1Zn7y8g5Krd4Q-1tj50mDNfMSNZPS3gNx7W5Z_qk2qvI/edit?usp=sharing)
- [Secure](https://docs.google.com/document/d/1f6W8tTWW-D_dlHJgNuK6Np1wkIH0wISOqQZzEfa7UBU/edit?usp=sharing)
- [Open Source](https://docs.google.com/document/d/17AiRGDNNROml8D4uVxG1YiaoqOGPTI0TtTQVQYkODTY/edit?usp=sharing)
- [Gaming VPN](https://docs.google.com/document/d/123WFEyCRVpFCpTaxM732wj-rLhthiUWDWoXBxs3e0lY/edit?usp=sharing)
- [Work VPN](https://docs.google.com/document/d/1ndvJUkwP4kuQAu27yeorAiLhTrpCJ1RuV25r5mIgT-o/edit?usp=sharing)
- [Home VPN](https://docs.google.com/document/d/1jybr18n8zEQN9nzdgc2D7xrwmfdkHNwE2cppRAkR1qQ/edit?usp=sharing)
- [How to hide your IP address](https://docs.google.com/document/d/1xqmivwZxWl22n3CF4P_UUyTmEjg1Xw-2JTfGrRZT0yI/edit?usp=sharing)
- [How to browse anonymously](https://docs.google.com/document/d/1bs4v7EMf4iVQNClqYb7Ou8HOyHFUYF9ZlXaSQSx4DMc/edit?usp=sharing)
- [Risks of using free VPN](https://docs.google.com/document/d/1cKPZj4RszxDrjfd88efERWP9u3-rBAXehGSKvcthQkM/edit?usp=sharing)
- [What does a VPN do](https://docs.google.com/document/d/1jM3su6z0ZfRcYn8LWMo7e_i951WXQLgSZAXtpWqptYc/edit?usp=sharing)

Please let me know if you have any questions!

**Comment by nathan-barrett** [comment]
Closing this as Dan added these pages to the resource center
