### ISSUE TITLE
 Senior Leadership Page Update

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#13674]
Hi! We got a request to make an addition to the senior leadership page by 9/18 (if possible):

- Add Masayo Nobe [headshot](https://drive.google.com/file/d/14QjUKQ_JWX-Trhv0lcq1Kgs6XtnBo3QL/view?usp=drive_link) and [bio](https://docs.google.com/document/d/1OPJywxhfzFvL6aMttbGeFLmW5NFyclIDcKcqCez_EoQ/edit) to the [senior leadership section](https://www.mozilla.org/en-US/about/leadership/). 

Please let me know if you have any questions. Thank you!

**Comment by PradeepG-07** [comment]
Please Assign it to me.

**Comment by PradeepG-07** [comment]
And i have requested access for headshot and bio files please check it. Accessing mail(pradeepindia503@gmail.com)

**Comment by craigcook** [comment]
> Please Assign it to me.

Thanks very much for your interest, but these updates are usually handled internally by Mozilla staff until it can be made public. There may be some other issues you can work on. Sorry!

**Comment by PradeepG-07** [comment]
Could you help me where i can work on?
