### ISSUE TITLE
Poor JPEG images received at monitor.firefox.com when visitng with WebP accept header stripped

### ISSUE THREAD

**Issue by FOSSPCM** [mozilla/bedrock#13681]
## Description

When visiting https://monitor.firefox.com/ with the browser set to asking the server not to send WebP images, instead causes the server to send very poor JPEG images to replace them, so bad that even the very logo for Firefox Monitor just shows a black rectangle with the Monitor graphic very noisy.

### Steps to reproduce

One way this can be reproduced:
1. In Firefox, open "about:config."
2. Set image.http.accept to */*
3. Open **a new tab or window** and visit https://monitor.firefox.com/

Other ways include setting image.webp.enabled to false, or installing an addon like "Don't "Accept" image/webp" by jscher2000 and setting it to Strip image/webp.

**Refreshing the tab/window will not cause the server to reflect your header changes. Close the tab/window, open a new one, and visit the site again.**

### Expected result

This is the original with WebP images served.
![firefox_d7Bc2FWbpX](https://github.com/mozilla/bedrock/assets/103983060/b0b554ea-effa-4180-9dc7-b389a1908ed3)
URL: https://monitor.firefox.com/

### Actual result

Notice the faulty JPEG images when WebP is removed from the image accept header.
![firefox_KAF3dqTlLk](https://github.com/mozilla/bedrock/assets/103983060/090fdeb4-0ae1-4cff-8eb6-c3702d44870e)
URL: https://monitor.firefox.com/

### Environment

Tested in Firefox 117.0.1 on both Windows 10 and Window 11.
I normally have the image.http.accept header is set to */* for myself.

For the record, the reason why I have Firefox set up to do this is because I like to save images I like or otherwise want or need in their original form, rather than be served a WebP file. This becomes problematic as WebP is not suitable format that works in most software, and sometimes servers will compress a JPEG as a WebP, and converting it back to JPEG adds additional quality loss. WebP may have also degraded the quality in what would otherwise be PNG files as well. Simply converting WebP images to something else is not a viable option for me. However, I do not have a problem with WebP if the original file was a WebP. I only have a problem when the original file is re-compressed into WebP. Now you know.

### Possible solutions

A. Use PNG as a fallback image format to serve instead of JPEG.
B. Exclusively serve WebP. Even with the methods used to ask the server not to serve WebP, if WebP was the only option, or is the original image, a WebP file may be served anyway.

**Comment by alexgibson** [comment]
Thanks for filing this. But I believe you need this repo: https://github.com/mozilla/blurts-server

I don't have permissions to transfer this existing issue, so I'm afraid you'll need to open a new one over there.

**Comment by FOSSPCM** [comment]
@alexgibson Okay, I just made a report at the Blurts-server repo. Thanks for letting me know!

Love the work you guys are doing, by the way.
