### ISSUE TITLE
Clean up obsolete/outdated strings

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13714]
When we keep an old strings around as a fallback for a new string we should remove the old/obsolete string after some time has passed to avoid giving our translation community more work.

> A lot of volunteers don't necessarily check the comment area unless they see two similar strings. The best practice is to remove these strings on a regular basis. 

I don't think we've done this... ever? So we should do it. 

We should also try to find a way to do it every-other month.

**Comment by reemhamz** [comment]
I can cover this after https://github.com/mozilla/bedrock/pull/13715 gets merged to avoid fixing a big number of rebase conflicts

**Comment by stephaniehobson** [comment]
Fixed in #13886
