### ISSUE TITLE
Update bedrock helpers and docs to reference Mozilla accounts

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13724]
## Description

We have a whole set of helpers and documentation around Firefox Accounts. I guess we should update the naming to reflect Mozilla accounts going forward: https://bedrock.readthedocs.io/en/latest/firefox-accounts.html

---

#### Success Criteria
- [ ] Documentation and helpers are updated to reference new naming

**Comment by nox1134** [comment]
Hi! I would like to work on this issue.

**Comment by alexgibson** [comment]
@nox1134 thanks for the interest in this issue, but I'm afraid it's not necessarily as simple as a find and replace, so someone on our dev team will likely take this on.

**Comment by alexgibson** [comment]
Note for posterity - I asked internally if people are referring to `FxA` as `MzA` as an abbreviation (in code for example), and it seems like the guidance for now is to stick to using `fxa` in internal code.

The reason is that the branding changes are so far superficial, and for now the github repo, domain name and everything else is still `fxa`.  When that changes further down the road we can start to think about renaming things, but for now we should probably also stick to using `FxA` in code.
