### ISSUE TITLE
October VPN Moments page has incorrect UTM params

### ISSUE THREAD

**Issue by dmose** [mozilla/bedrock#13799]
## Description

October VPN Moments page has incorrect UTM params

### Steps to reproduce

Go to https://www.mozilla.org/en-US/firefox/welcome/16

Once the Moments page is shown, click the "Get Mozilla VPN" button and then select a subscription plan.

### Expected result

According to the [experiment brief](https://docs.google.com/document/d/1OvWvJ6azwOoSmMqAKqDj1mn8_UsoZa_M53_PNROb0-c/edit#bookmark=id.k2jr8cbqf1jp) and Slack, the URL should contain these UTM params:

```
utm_medium=firefox-desktop
utm_source=moments
utm_campaign=cybersecurity-month-23
utm_content=moments-oct23-global
```

### Actual result

The URL contains these UTM params:

```
utm_source=www.mozilla.org-welcome
utm_medium=referral
utm_campaign=welcome-page16
```

### Environment

MacOS Ventura 13.6, Firefox 120 Nightly

CC @aminomancer @nathan-barrett

**Comment by alexgibson** [comment]
@dmose hi!

The way our moments pages work, we can’t really override the standardised set of utm params (the actual result) without causing issues in our own GA set up (attaching utm params to the actual vpn landing page will conflate the number of sessions we see).

My suggestion would be to update your configuration to use the standardised format for utm params that you see in the actual results. This is the same format we’ve used for all previous VPN moment pages.

**Comment by alexgibson** [comment]
Note @nathan-barrett has updated the `utm_campaign` value to `cybersecurity-month-23`  in https://github.com/mozilla/bedrock/pull/13801 so that it's a little more in line with what you laid out:

```
utm_source=www.mozilla.org-welcome
utm_medium=referral
utm_campaign=cybersecurity-month-23
```

**Comment by dmose** [comment]
@nathan @alexgibson Currently, I'm seeing `utm_source=www.mozilla.org`, and the other two look the same as you mentioned (and no `utm_contents`).

> The way our moments pages work, we can’t really override the standardized set of utm params (the actual result), without causing some issues in our own Goggle Analytics set up (attaching hard coded utm params to the actual vpn page CTA link will conflate the number of sessions we see).

@alexgibson Should I be concerned that these most recent changes will have confused the Google analytics?

I think we want other folks from product and marketing in this discussion, so before we go forward, I'd like to chat some more in Slack...

**Comment by dmose** [comment]
After discussion in Slack, Brad, Venetia, Alex, and maltman agreed to revert this change in favor of the conventions that we've used in the past to reduce risk.

**Comment by alexgibson** [comment]
Discussed on slack and folks are aligned with the standard values we use:

```
utm_source=www.mozilla.org-welcome
utm_medium=referral
utm_campaign=welcome-page16
```
