### ISSUE TITLE
Incorrect analysis - Annual Consumer Creep-O-Meter

### ISSUE THREAD

**Issue by Cupprum** [mozilla/bedrock#13808]
## Description

When i do the quiz about the products i use, it gives me wrong recommendations.

### Steps to reproduce

1. Go to the [Creep-O-Meter](https://foundation.mozilla.org/en/privacynotincluded/articles/annual-creep-o-meter/?utm_source=mofo&utm_campaign=2023-Creep-o-meter-A&utm_medium=email&utm_term=en&utm_content=button_Creep-o-meter) 
2. Start the quiz.
3. Choose the following options - [Signal, WeChat]
4. Press see results

![IMG_2292](https://github.com/mozilla/bedrock/assets/25938209/73654949-6ead-4756-b321-3c825dca2efd)
![IMG_2293](https://github.com/mozilla/bedrock/assets/25938209/dba65cde-d6d1-46e4-9437-6d2c709f5de8)
![IMG_2294](https://github.com/mozilla/bedrock/assets/25938209/8d2bd3d7-63ae-4602-86a2-fe87c266523f)
![IMG_2295](https://github.com/mozilla/bedrock/assets/25938209/8c9be799-b87f-403a-8be0-bb9fc9fbf8af)

### Expected result

I should receive warning for using WeChat, just like only when i choose WeChat.

![IMG_2296](https://github.com/mozilla/bedrock/assets/25938209/ce60d511-183e-419f-89a2-7ee2a8731bd7)
![IMG_2297](https://github.com/mozilla/bedrock/assets/25938209/e6f8a73b-45a4-4f08-9531-fa57c7257818)
![IMG_2298](https://github.com/mozilla/bedrock/assets/25938209/dd11130f-f3ff-4756-be1e-1f3e526a518a)

### Actual result

I am notified that i do everything correctly.

### Environment

Iphone 13 Pro
iOS 17.0.3
Safari browser

**Comment by alexgibson** [comment]
Hi! I believe you want this GitHub repository: https://github.com/MozillaFoundation/foundation.mozilla.org

Sorry I am not able to transfer the issue as it's in another org, so you will have to re-open it over there.

**Comment by Cupprum** [comment]
Thank you for pointing me to correct direction :), the mozilla website forwarded me to this repository, sorry.
