### ISSUE TITLE
Add link to newsletter recovery page to fxa error page

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#13828]
## Description

The [FxA error page](https://www.mozilla.org/en-US/newsletter/fxa-error/) is redirected to if part of the flow from FxA's link titled "Email Communications" in the FxA account settings page fails. This seems to happen frequently enough and is a current issue trying to be resolved. But in the meantime I suggest adding a link on this page to the newsletter recovery page where the user could enter their email to get a link to the newsletter management page so landing on this page isn't a dead-end.

**Comment by alexgibson** [comment]
Looks like this one was fixed in https://github.com/mozilla/bedrock/pull/13831
