### ISSUE TITLE
RSS/Atom error in /firefox/nightly/notes/feed/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13830]
## Description

https://github.com/mozmeao/www-site-checker/actions/runs/6648592312

```
Checking https://***/firefox/nightly/notes/feed/
Invalid feed detected:
https://***/firefox/nightly/notes/feed/ mismatched tag @ L:27
Error: Process completed with exit code 128.
```

Looks like it might be due to an `<img>` element which isn't closed correctly for XHTML

```
<img alt="UI setting for GPC" src="https://www.mozilla.org/media/img/firefox/releasenotes/note-images/120_relnote_GCP.png">
```

**Comment by Ansh101112** [comment]
Hello, 
Yes, it can be because of XHTML's wrongly written syntax. I will try to fix it.

**Comment by alexgibson** [comment]
Note that we could fix this in the release notes itself as a quick fix, but it would be good to try and ensure we escape things like this in the view that processes the feed perhaps.

**Comment by stevejalim** [comment]
@alexgibson Thanks for picking this up while I was OOO. I thought the same as you: we could fix this at the source, but better to make the feed generation more robust

**Comment by stevejalim** [comment]
OK - this has been bugging me and I have a fix for it. Will raise a PR tomorrow for this
