### ISSUE TITLE
[GTM review] changes to expose GA4 client and session ID in GTM

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13895]
## Description

With GA4 the client and session ID are not available to us by default, we need to expose them by tweaking something in GTM. This issue tracks the review of those GTM changes.

I have followed the steps outlined here: https://www.simoahava.com/gtmtips/write-client-id-other-gtag-fields-datalayer/

There was some concern because the template is in ES6 but I ran the GTM js files through a compatibility checker and there were not glaring problems for older browsers, like `let` statements or something.

I also pushed the changes live in our GTM demo account and then pointed a demo server there. Browser stack did not report any new JS errors in older browsers.

---

Please review and publish the "ga4 stub" workspace.

---

See also: https://github.com/mozilla/bedrock/issues/12801

**Comment by alexgibson** [comment]
I've approved the changes in GTM but have left them unpublished, as I'm not sure if you want to time releasing this when you're around or not. Feel free to publish when ready.

I don't see how the custom JS is going to run in IE browsers as it contain's things like arrow functions that are definitely not supported. However the code is also using commonJS `require()` statements to load some other things, so perhaps this is pre-compiled? I'm not too sure as I haven't been able to inspect what GTM outputs after this is built.

**Comment by alexgibson** [comment]
Searching a bit it sounds like this sandboxed JS uses a simplified subset of the JS language: https://developers.google.com/tag-platform/tag-manager/templates/sandboxed-javascript

It doesn't really mention browser support at all, but it sounds like it's isolated in some way.

**Comment by alexgibson** [comment]
I tried to do a bit more debugging to try and find where the compiled code is output, but I wasn't able to really find anything unfortunately. It's pretty tricky trying to search through the minified GTM scripts. 

I guess all we can do is publish and then keep an eye out for any errors.

**Comment by stephaniehobson** [comment]
Published this morning.
