### ISSUE TITLE
GTM changes to send current stub session ID to GA4

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13904]
## Description

While we're working out a way to get the client and session IDs from GA4 there's no reason not to send the UA derived stub session ID to GA4. 

Bedrock changes https://github.com/mozilla/bedrock/pull/13903 and [demo4](https://www-demo4.allizom.org/en-US/firefox/).

---

Please review the `stub_session_set` workspace in GTM.

**Comment by alexgibson** [comment]
Approved and published r+
