### ISSUE TITLE
[GTM Review] changes to support default_browser_set and dimension_set

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13919]
## Description

- watch for `default_browser_set` and `dimension_set` events
- send correct value for dimension_st

---

Please review and publish the `default browser set` workspace in GTM.
http://localhost:8000/en-GB/firefox/118.0/whatsnew/  is a good page to test from, it triggers `dimension_set` and then you can click through to set the browser as default and `default_browser_set` is triggered if appropriate.

---

See also: 
https://github.com/mozilla/bedrock/issues/12801
https://github.com/mozilla/bedrock/pull/13913

**Comment by alexgibson** [comment]
Testes, approved and published, r+
