### ISSUE TITLE
Hard-coded "Get Mozilla VPN" banner in VPN landing page

### ISSUE THREAD

**Issue by flodolo** [mozilla/bedrock#13934]
https://www-dev.allizom.org/it/products/vpn/

In the middle of the page I have content in English.

<img width="1308" alt="Schermata 2023-11-26 alle 15 35 02" src="https://github.com/mozilla/bedrock/assets/3644868/49af3508-986e-4466-a96f-288b9f0e63d3">

I have at least [3 strings](https://transvision.flod.org/?recherche=30-day+money-back+guarantee&repo=all_projects&sourcelocale=en-US&locale=it&search_type=strings_entities&entire_string=entire_string) in Pontoon with the `30-day money-back guarantee` text.

I don't understand much of the Bedrock's code these days, but [this looks hard-coded](https://github.com/mozilla/bedrock/blob/50d26be1993206f3c899ba9a5ff655908bb2f1a7/bedrock/products/templates/products/vpn/includes/macros.html#L121-L125)?

**Comment by alexgibson** [comment]
Thanks for the spot @flodolo, will get these fixed

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/13936
