### ISSUE TITLE
Hard-coded section title in VPN features page

### ISSUE THREAD

**Issue by flodolo** [mozilla/bedrock#13935]
https://www-dev.allizom.org/it/products/vpn/features/

<img width="1220" alt="Schermata 2023-11-26 alle 15 53 55" src="https://github.com/mozilla/bedrock/assets/3644868/8c7b5b13-9a73-454a-a221-7c1435c8bcf5">

`We never log, track or share your network data` appears hard-coded.

https://github.com/mozilla/bedrock/blob/50d26be1993206f3c899ba9a5ff655908bb2f1a7/bedrock/products/templates/products/vpn/features.html#L330

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/13936
