### ISSUE TITLE
Remove marketing banner from Pocket German landing page

### ISSUE THREAD

**Issue by anthony-liddle** [mozilla/bedrock#13941]
## Description

There is a request from Marine Boussat to remove the blue banner at the top of the Pocket German landing page.

The url of the page is `https://getpocket.com/de/`. 

Attached is a screenshot of the page and banner.
![image](https://github.com/mozilla/bedrock/assets/1273879/a756719b-60e8-4e3e-a262-b666a6bca8b5)

---

#### Success Criteria
- [x] The banner has been removed

**Comment by stephaniehobson** [comment]
Fixed in https://github.com/mozmeao/www-config/pull/540
