### ISSUE TITLE
[GTM Review] Add support for experiment_view

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13943]
## Description

- watch for `experiment_view` event
- send `experiment_view` event to GA4 with corresponding attributes (id, variant)

---

Please review and publish the `experiment_view` workspace in GTM.

Not all experiments are being tracked in GA4 yet. A good page to test on is: https://www.allizom.org/en-GB/firefox/119.0/whatsnew/

---

See also: 
#13238 
#13914

**Comment by alexgibson** [comment]
Tested, approved and published r+ 🍎
