### ISSUE TITLE
[GTM Review] Tweak cta_click event in GA4

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13948]
## Description

- trigger the event if data-cta-text, data-cta-type, or data-cta-position are present 
- filter "type" to fit new GA4 purpose ([see docs](https://github.com/mozilla/bedrock/pull/13947)) 
- update event to log the filtered value for type

## Testing

- https://www.allizom.org/en-US/ 
  - product links
- https://www.allizom.org/en-US/firefox/products/
  - "Check for breaches"
  - "Learn more about Firefox Relay"
  - "Continue" (the form button, make sure I didn't break form stuff since the changes are focused on links)
- https://www.allizom.org/en-US/products/vpn/
  - "Get annual subscription"
- https://www.allizom.org/en-US/firefox/accounts/
  - "Continue" (form button)

---

Please review and publish the `cta_click` workspace in GTM.

---

See also: 
#13238 
#13947

**Comment by alexgibson** [comment]
I've approved these changes but left them unsubmitted in case you wanted to change anything (nothing here is blocking)

- On the VPN page, if I click "Get annual subscription" I get both a cta_click event and a begin_checkout event. Do we need both?
- I'm not a huge fan of using custom JS that's hidden in GTM:

```javascript
function () {
  var element = {{Click Element}}.closest('a, button')
  var type = element.dataset.ctaType;
  
  // throw away the old values that UA used that we don't want anymore
  if(type == 'link') { type = ''; }
  if(type == 'button') { type = ''; }

  // try to add new values we do want, as long as we're not over-writing something
  if(element.tagName.toLowerCase() == 'a' && type == '') {
      if(element.href.indexOf('https://relay.firefox.com') == 0 ) { type = 'relay'; }
      if(element.href.indexOf('https://monitor.firefox.com') == 0 ) { type = 'monitor'; }
      if(element.href.indexOf('https://getpocket.com') == 0 ) { type = 'pocket'; }
      if(element.href.indexOf('https://accounts.firefox.com') == 0 ) { type = 'account'; }
      if(element.href.indexOf('https://accounts.mozilla.org') == 0 ) { type = 'account'; }
  }

  return type;
}
```

I'm not opposed to keeping this, but it feels hidden enough that it could be a possible source of confusion in the future perhaps? We don't have to change it now necessarily as what you have works, but I'd perhaps favor more of this logic living in bedrock (where it can have tests) longer term?

Feel free to publish as-is for now, but I'm curious on your perspective here too.

**Comment by stephaniehobson** [comment]
Yeah, I don't like it either and it's not intended to be permanent. (Did I document this? no 🤦‍♀️ )

Options are:
1) change the current values of `data-cta-type` in bedrock to reflect the new usage
2) leave the JS in GTM until July 2024 and then do #1.

Maybe I am trying too hard not to change the UA data and should just change the values now? What do you think?
