### ISSUE TITLE
Update copy on developer edition page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13970]
## Description

The experimental features listed on this page are no longer exclusive to Developer edition. I recommend we update copy to:

`All the latest developer tools in beta, in addition to features like the Multi-line Console Editor and WebSocket Inspector.`

![image](https://github.com/mozilla/bedrock/assets/2030656/7fd81d21-99a0-485f-88f6-5c93c22e9243)

**Comment by Soumya0803** [comment]
Hi @slightlyoffbeat I would like to work on this.

**Comment by souvikjs01** [comment]
Can I work on this issue if it is open? Then please assign it to me.

**Comment by reemhamz** [comment]
Re-opening as it's not fully completed just yet. I have to do a couple of extra things from my end

**Comment by reemhamz** [comment]
Closing as https://github.com/mozilla/bedrock/pull/14049 has been merged
