### ISSUE TITLE
About page update

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#13971]
Hi there! We would like the following image and copy changes made to the IRL tile of the https://www.mozilla.org/en-US/about/ page. 

Cover image: please change to [this](https://drive.google.com/file/d/1fA4SwbjOF4Vu3a6A8KV28Y0nueP-_4yN/view). 

Title: please change to: _Talking Tech Issues IRL_

Blurb: please change to: _In Mozilla’s multi-award winning podcast, host Bridget Todd talks to the people shaping the future of the internet and AI._

<img width="1728" alt="Screenshot 2023-12-01 at 12 50 46 PM" src="https://github.com/mozilla/bedrock/assets/134577516/0e4c3477-861d-49ef-adff-96b652383108">

**Comment by nathan-barrett** [comment]
Hey @enavajas - we will need a differently sized image for this - we need something with a 3:2 aspect ratio. If they can provide a 1200 x 800 sized image, that would be best

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/13983
