### ISSUE TITLE
Update Twitter to X

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13980]
## Description

References to "Twitter" should be renamed to "X (formerly Twitter)", or just "X" where it makes sense.

Areas to update:

- Twitter icon/link in site footer
- Share button on https://www.mozilla.org/en-US/about/manifesto/
- Hero image on https://www.mozilla.org/en-US/firefox/new/ (plus another image half way down) (Done in https://github.com/mozilla/bedrock/pull/14010)
- Share link on https://www.mozilla.org/en-US/firefox/switch/
- Twitter link on https://www.mozilla.org/en-US/firefox/privacy/book/
- Twitter link on https://www.mozilla.org/en-US/contact/
- Share icon on https://www.mozilla.org/en-US/newsletter/opt-out-confirmation/

There may also be a few random references to Twitter in the text of various other pages that might need updating (requires a more thorough search)

---

#### Success Criteria
- [ ] X brand name is updated across the website

**Comment by draunger** [comment]
Assign me

**Comment by reemhamz** [comment]
Do you think it's also worth updating `data-link-name` attributes on older files to say X instead of Twitter?
