### ISSUE TITLE
Update twitter to X on firefox /new product images

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#13987]
## Description

Firefox new tab now displays 'X' instead of 'Twitter', and we need to update the product screenshots to reflect that on the Firefox /new page.

- There are 3 screenshots that I can find, but we should check code to see if there are any more.
- Jessica M has already created the new screenshots. I'll include them below, but developer should reach out to make sure they get the latest version and they are optimized and web ready.
- Confirm text should say "twitter' and not "X"

![screen-mr1-dark_cropped](https://github.com/mozilla/bedrock/assets/2030656/2f41772b-bc68-46ff-98b6-b1666cc28f7e)
![screen-mr1-dark](https://github.com/mozilla/bedrock/assets/2030656/6213c61b-6a57-4860-8d8f-bb5dc0a9964e)
![screen-mr1](https://github.com/mozilla/bedrock/assets/2030656/0d8f0609-0e91-4b9b-b17b-9d000b36392e)

**Comment by slightlyoffbeat** [comment]
When I look at new tab in my own Firefox, it shows the new icon, but the old name: 'twitter'.

We should confirm that is product behavior and do the same.

**Comment by alexgibson** [comment]
Gonna grab this and pop them up on a demo server for review. Will wait on confirmation for the "twitter" name before moving forward.

**Comment by draunger** [comment]
Assign me plz I will do this
