### ISSUE TITLE
[Feb 6] Monitor name switch flip

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14019]
## Description

SWITCH_MOZILLA_MONITOR_BRAND_NAME=on

---

#### Success Criteria
- [x] Switch is flipped on for Feb 6 2024

**Comment by enavajas** [comment]
Hi @alexgibson, I wanted to confirm a couple of things for this work stream:

1. The requested time for these changes to be live is **_2:30 AM PST / 10:30 AM GMT on Tuesday, February 5th, 2024._** 
3. There are a couple of associated tickets that should also be pushed live at the same time as this one. These include:
- [Pencil banner + mid-page banner](https://github.com/mozilla/bedrock/issues/14115)
- [Updated copy ](https://github.com/mozilla/bedrock/issues/14047)

Please let me know if you have any questions. Thank you so much!
