### ISSUE TITLE
Remove pocket banners & promo on homepage [January 31st]

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/bedrock#14046]
## Description
Remove the Best of 2023 pocket promo's and banner

---

#### Success Criteria
- [ ] Bo

**Comment by janbrasna** [comment]
Now with the switch off (https://github.com/mozmeao/www-config/pull/549/commits/81a897caeb023d41211438b5e6457c9f272a08d8) I believe it's just a matter of reverting #14004 and #14045 — would you like the code completely removed?

**Comment by alexgibson** [comment]
@janbrasna yes I believe we can completely remove the code, thank you!
