### ISSUE TITLE
Wrong link on https://www.mozilla.org/en-US/about/leadership/

### ISSUE THREAD

**Issue by topotropic** [mozilla/bedrock#14059]
### Description / Steps to reproduce

1. Go to https://www.mozilla.org/en-US/about/leadership/
2. Click on Mitchell's profile
3. Click on 'Mozillians profile' on the profile page

### Expected result

No link should be there since Mitchell's profile isn't public

### Actual result

Link open `(https://mozillians.org/u/mitchell/)` -- which is very misleading

**Comment by stevejalim** [comment]
When someone picks up this ticket, please note [this thread](https://mozilla.slack.com/archives/G7ACJHJCB/p1704796109676439)

**Comment by stevejalim** [comment]
It looks like Mitchell's real Mozillians profile is https://people.mozilla.org/p/mitchellbaker, which is acccessible if one is logged in with a Mozillian / people.m.o account but is not visible if one is not logged in.

At the least we should fix the link to the correct profile. Will make a PR now

**Comment by stevejalim** [comment]
Chatting with @alexgibson I think we'll just zap the Mozillians links from Leadership in general, because they now redirect to people.mozilla.org which requires auth
