### ISSUE TITLE
[GTM Review] Record link_click in GA4

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14056]
---

Please review and publish the `link_click` workspace in GTM.

---

## Description

It will help the review to read https://github.com/mozilla/bedrock/issues/14053 for some background.

These changes will begin recording the `link_click` event in GA4. Some data transformation is necessary to log the data in the final format that we want the data to take. There are also some changes to the UA setup which will allow us to begin the HTML changes from name to text without disrupting UA data collection.

- Added a Tag for recording `link_click` event in GA4
- Added a Variable for `data-link-text`
- Added Triggers for `data-link-name` and `data-link-text`
   - We can remove the data-link-name one once the bedrock HTML edits have been made
- Created a Custom JS variable which will return the value of `data-link-text` or fallback to `data-link-name`
  - This is just to help with the transition eventually we can make bedrock edits and convert this to a plain variable
- Created a Custom JS variable which will combine the value of `data-link-position` and `data-link-group`
   - This is just to help with the transition once UA goes away we can make bedrock edits and convert this to a plain variable
- Renamed the Trigger for data-link-type to clarify what it does
- Renamed the Variable for data-link-group to match existing naming conventions

The Custom JS variables can be removed once UA goes away. Issues have been filed:

- https://github.com/mozilla/bedrock/issues/14054
- https://github.com/mozilla/bedrock/issues/14055

## Issue / Bugzilla link

https://github.com/mozilla/bedrock/issues/13238
https://github.com/mozilla/bedrock/issues/14053

## Testing

Some different combinations of attributes can be found here:

- type, name, position & group: header nav links
- type, name, & group (no position): [firefox more cards](https://www.allizom.org/en-US/firefox/more/)
- type & name (no position or group): [feature page cards](https://www.allizom.org/en-US/firefox/features/)
- I couldn't find anything with a type but no name (except type="download" which uses `data-display-name` instead of `data-link-name` but that's not covered by this work)

### Test against **staging**:

**UA (make sure I didn't break anything)**

| label | value | example |
|--------|--------|--------|
| action | {{type}} click | nav click |
| label | data-link-name | Firefox for iOS |
| index 14 | data-link-position | topnav |
| index 13 | data-link-group | firefox |

- [x] Compare the data collected in the default workspace with what's in the link_click workspace
- [x] Clicking a link with `data-link-type` with a value that is not "download" triggers `GA Event - Link Clicks - Data Attribute`
- [x] `data-link-name` is recorded as the action's `label`
- [x] `data-link-position` is recorded as CD 14
- [x] `data-link-group` is recorded as CD 13

**GA4 (make sure we're recording what we want and when)**

| label | value | example |
|--------|--------|--------|
| event | link_click |  |
| text | data-link-name | Firefox for iOS |
| position | data-link-position - data-link-group | topnav - firefox |

- [x] Clicking a link with data-link-name triggers `GA4 Event - link_click`
- [x] Clicking a link without `data-link-name` does not trigger (see sticky promo)
- [x] `data-link-name` is recorded as the `text` parameter
- [x] `data-link-position` with no group is recorded as `position` 
- [ ] `data-link-group` with no position is recorded as `group` 
- [x] `data-link-position` and `data-link-group` are combined as `position`

### Test against **demo9**:

https://github.com/mozilla/bedrock/pull/14057 is on demo9 and it changes all `data-link-name` attributes to `data-link-text` it also includes a [test page](https://www-demo9.allizom.org/en-US/analytics-tests/ga4-links/)

- [x] Clicking a link with `data-link-text triggers` a GA4 `link_click`
- [x] `data-link-text` is recorded as the `text` parameter in GA4
- [x] `data-link-text` is recorded as the action `label` in UA

**Comment by alexgibson** [comment]
I've tested the steps above (thanks for the instructions!) and things seem to work as expected for me. I approved the changes in GTM, but I'll leave you to publish in case there's anything else you want to test manually.

r+
