### ISSUE TITLE
[Developer Edition 18.5.0.0] Add-ons not available, no menu had shown.

### ISSUE THREAD

**Issue by ocsxxi** [mozilla/bedrock#14073]
## Description

The add-ons can't be able to work, and the add-ons button in the toolbar doesn't work. 

### Steps to reproduce

1. Install the Developer Edition.
2. Save & add some add-ons to the browser,
3. When clicking on the addons button in the toolbar, the addons menu doesn't show.

### Expected result

The add-ons menu should be shown.  Like the regular version does.

### Actual result

The add-ons menu doesn't show. Clicking on the button would automatically jump into the add-ons `about:addons`.

### Environment

Firefox Develop Edition 18.5.0.0 + Windows 10.

**Comment by ocsxxi** [comment]
Wait... My regular version of Firefox can't be able to open the add-ons menu either...  
As for my initial thought, maybe is because of some of my browser's privacy settings, but which one?
Let me figure it out.

**Comment by ocsxxi** [comment]
Finally, I have found out where the problem occurs.
The reason the panel had not shown is that I had enabled the overall privacy mode, which is in `privacy and secure`-`history`-`always allow...`.
This very setting makes the normal mode a global privacy mode, add-ons requiring privacy mode allowance to work.

**Comment by ocsxxi** [comment]
Finally, I have found out where the problem occurs.
The reason the panel had not shown is that I had enabled the overall privacy mode, which is in `privacy and secure`-`history`-`always allow...`.
This very setting makes the normal mode a global privacy mode, add-ons requiring privacy mode allowance to work.

**Comment by alexgibson** [comment]
@ocsxxi I'm glad you figured out your problem! This is actually the place to report bugs for the website www.mozilla.org. If you have an issue with Firefox, you can use Bugzilla: https://bugzilla.mozilla.org/enter_bug.cgi

**Comment by ocsxxi** [comment]
> @ocsxxi I'm glad you figured out your problem! This is actually the place to report bugs for the website [www.mozilla.org](http://www.mozilla.org). If you have an issue with Firefox, you can use Bugzilla: https://bugzilla.mozilla.org/enter_bug.cgi
xiexie
@alexgibson Thank you Alex. My fault. I had wondered why the main language is html😂. I got Bugzilla now, thank you again!
And if you think this issue is no need to be here anymore, just delete it, or tell me and I'll do it.
