### ISSUE TITLE
careers.mozilla.org "See yourself on one of our teams?" section is awkwardly laid out on mobile

### ISSUE THREAD

**Issue by dholbert** [mozilla/bedrock#14078]
## Description

The "See yourself on one of our teams?" text is smooshed against the left side of the screen (no margin at all) and isn't centered like the other similarly-sized header-looking text.

### Steps to reproduce

1. Visit 
Visit https://www.mozilla.org/en-US/careers/ in a mobile browser on a phone, or using Firefox on Desktop with responsive design mode and e.g. "Galaxy Note Android 20" as the selected emulated device.

2. Scroll down to the "See yourself on one of our teams? [Find your role]" section

### Expected result

The text should have some margin from the edge of the screen, and the text should be centered like the other similar-looking sections (e.g. like "Feel good about your work" at the top and "We'll meet you where you are" further down).

### Actual result

- The text is smooshed against the left edge of the screen, with no margin, and neither of the two lines are centered. It looks very out-of-place from the rest of the page's design.

### Environment

Firefox Nightly 123 on Android (Pixel 8) and Windows 10 (in RDM mode as described above).  Also reproduces in Chrome on Windows 10 with a similarly-small window size.

Screenshot -- left is "good" for reference for how the rest of the site has this sort of text nicely centered with margin; right is "bad":
![image](https://github.com/mozilla/bedrock/assets/426803/2ffc9fb1-b902-4b7c-9048-6b4af140df93)

**Comment by alexgibson** [comment]
Thanks for the report!

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/14113
