### ISSUE TITLE
Broken images on VPN resource center

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14074]
## Description

Images (from Contentful) all seem to be broken on https://www.mozilla.org/en-US/products/vpn/resource-center/

**Comment by stevejalim** [comment]
Looks like a CSP-related regression. This line needs to to back in 

https://github.com/mozilla/bedrock/pull/14044/files#diff-eaca14ba79bd8caf620f2740e240a03b6e2d192e1df89dc259ec63894da1f62dL184
