### ISSUE TITLE
Rendering issues on the nightly release notes page

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/bedrock#14097]
![Screenshot 2024-01-17 at 17-15-56 Firefox Nightly 123 0a1 See All New Features Updates and Fixes](https://github.com/mozilla/nucleus/assets/454375/7c873136-0063-444e-b1f8-8744e7fe6f17)

There are weird indentation issues on https://www.mozilla.org/en-US/firefox/123.0a1/releasenotes/
See screenshot

**Comment by stevejalim** [comment]
Thanks @reemhamz. PR landing very soon!

**Comment by stevejalim** [comment]
@pascalchevrel Fixed on Dev https://www-dev.allizom.org/en-US/firefox/122.0a1/releasenotes/ -- will be shipped to prod soon

**Comment by stevejalim** [comment]
@pascalchevrel This fix just shipped to production
