### ISSUE TITLE
[GTM Review] Add custom dimension for if user is signed in to Firefox Account

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14107]
## One line summary

Please review and publish the **Default Workspace** in GTM. (Sorry for working on default 🤦‍♀️ )

## Description

- add support for `firefox_is_signed_in` custom dimension on `dimension_set` event.

## Issue / Bugzilla link

This is supporting WNP 122. Bedrock changes are in #14106

**Comment by alexgibson** [comment]
Approved in GTM - I'll leave it to you to publish
