### ISSUE TITLE
[GTM Review] Split product_download into product specific events

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14108]
## One-line summary

Review and publish "product_download events" workspace. 

## Significant changes and points to review

This change is to send both the existing event `product_download` and separate events for each product.

- triggers added for: 
  - `firefox_download`
  - `firefox_mobile_download`
  - `focus_download`
  - `klar_download`
  - `pocket_download`
  - `vpn_download`
- Any of the new triggers and the old `product_download` trigger should trigger the `GA4 Event - product_download` tag
- The tag has been updated to insert the name of the event dynamically based on the event name.

The supporting bedrock changes are in #14083 and published on demo9. The workspace and bedrock changes can go live in any order.

## Issue / Bugzilla link

#14072 

## Testing

#14083 Is on demo9 for testing purposes.

At the top of the tag manager, click the **G-YBFC8BJZW8** tag to see the hits sent. You can also watch the events coming in with the GA debugger (Admin > Property Settings > Data display > DebugView) on the **www_mozilla_org - GA4 Testing** property.

Both `product_download` and a product specific download event should fire.

- `firefox_download`: https://www-demo9.allizom.org/en-US/firefox/all/
- `firefox_mobile_download`: https://www-demo9.allizom.org/en-US/firefox/browsers/mobile/android/
- `focus_download`: https://www-demo9.allizom.org/en-US//firefox/browsers/mobile/focus/
- `klar_download`: https://www-demo9.allizom.org/de/firefox/browsers/mobile/focus/
- `pocket_download`: https://www-demo9.allizom.org/en-US/firefox/
- `vpn_download`: not yet implemented in bedrock

**Comment by alexgibson** [comment]
I tested the changes above and everything looks to be as expected

I did notice there are not Pocket download events firing though - is there maybe something missing from your PR for Pocket?

**Comment by stephaniehobson** [comment]
The GTM side isn't missing anything, I'll check the PR.

**Comment by stephaniehobson** [comment]
The Pocket download links are missing the class they need, I'll file a separate issue.
