### ISSUE TITLE
[GTM Review] Require data-cta-text to trigger cta_click

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14102]
## Description

Change to reflect making `data-cta-text` required - only record `cta_click` event when `data-cta-text`  is present on the link.

## Issue / Bugzilla link

Missing `data-cta-text` values were added in https://github.com/mozilla/bedrock/pull/14071 so this should not impact data collection.

Documentation was updated in https://github.com/mozilla/bedrock/issues/14056

## Testing

You can find a link with data-cta-* attributes and edit it with the dev tools to remove the "text" attribute.

**Comment by alexgibson** [comment]
I've approved the workspac echange called `cta_click` (assuming that's the right one by looking at the changes). I'll leave it to you to publish.
