### ISSUE TITLE
Welcome/Whatsnew pages - Google Play Store badge links to Apple App Store

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14111]
## Description

When clicking the "Get it on Google Play" badge, the user is instead directed to the Apple App Store.

### Steps to reproduce

1. Using Firefox open https://www.mozilla.org/en-US/firefox/welcome/17b/
2. Click the "Get it on Google Play" badge

### Expected result

I am taken to the Google Play Store to view the Firefox app

### Actual result

I am instead taken to the Apple App Store listing.

### Environment

Firefox
macOS

**Comment by alexgibson** [comment]
The same also happens on this WNP: https://www.mozilla.org/en-US/firefox/114.0/whatsnew/

**Comment by craigcook** [comment]
This seems to be what Adjust does in desktop browsers. We could/should update those badges to be direct links instead of Adjust.

**Comment by janbrasna** [comment]
I've also run into adjust links not working etc. in the past, so love to see them finally being phased out…

Is this issue fixed since #14125 or are there any more occurrences left? #11698 seems complete, sans the QR code images here and there…

**Comment by alexgibson** [comment]
Oh yes this issue can be closed as fixed. Adjust links are no more, and QR codes will be removed next. Thanks for the reminder!
