### ISSUE TITLE
VPN LP - Heading/Subheading test

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14131]
Hello. The PXI team would like to conduct a 3-way split on the following headings and sub-headings for the [VPN landing page:](https://www.mozilla.org/en-US/products/vpn/?entrypoint_experiment=vpn-pricing-position&entrypoint_variation=2)

**Option 1** (control/current variant)
_H1:_ Powerful privacy for peace of mind

**Option 2**
_H1:_ Powerful privacy for peace of mind `_(keep as is)_`
_H2:_ Switch on complete web activity and location protection from hackers and trackers.

**Option 3**
_H1:_ Mozilla VPN
_H2:_ Protect your digital activity and physical location with just one click.

There currently does not exist a subheading on the page. For **Option 2 **and** Option 3,** we will need to determine the best placing for the subheading. This is at the developer's discretion. 

There is no set timeline for this, but it would be nice to have it done when we have a bit of time to cross it off our list. 

Please let me know if you have any questions. Thank you!

**Comment by enavajas** [comment]
Hi @craigcook, i received the l10n strings for the headings. You can find them [here](https://drive.google.com/drive/folders/1dy3e-bBs72lt5AXVdSa4NPH7oJIw_1G1). Please let me know if you need anything else!

**Comment by enavajas** [comment]
Hi @craigcook, [here](https://github.com/mozilla/bedrock/issues/14176) is the other ticket to incorporate the winning variant from the VPN pricing section experiment that should take place just before this one.

**Comment by enavajas** [comment]
Also, for this heading/subheading experiment, I just wanted to confirm that we will be running it in the US, DE, and FR (using the translations referenced above).

**Comment by craigcook** [comment]
> Also, for this heading/subheading experiment, I just wanted to confirm that we will be running it in the US, DE, and FR (using the translations referenced above).

Confirmed, and also in en-GB and en-CA.

**Comment by enavajas** [comment]
This experiment can now be turned off. We can revert back to the control for now until we decide what to do with VPN. Thank you.
