### ISSUE TITLE
Redirect firefox/IE comparison page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14142]
This page is out of date and not a significant source of conversions. It can be removed and redirect to the Edge comparison.

- [x] Remove /firefox/browsers/compare/ie/ and associated assets
- [ ] Remove links to it from around the site (compare subnav, look for others)
- [ ] Redirect /firefox/browsers/compare/ie/ to /firefox/browsers/compare/edge/

**Comment by reemhamz** [comment]
We're probably going to also need a new graphic for the hero image so it removes IE:

https://www.mozilla.org/en-US/firefox/browsers/compare/
<kbd>![Screenshot 2024-02-01 at 11 48 12 AM](https://github.com/mozilla/bedrock/assets/42309026/fc8d0010-2fb9-4541-bab2-962958397378)</kbd>

**Comment by stephaniehobson** [comment]
@reemhamz I'll note that in the [Asana ticket for the page re-design](https://app.asana.com/0/1204604936721242/1206460414872557/f). It's not a blocker for this Issue :) 

Also, if you would like to fix to the image that's okay too.
