### ISSUE TITLE
Redirect mobile comparison page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14141]
This page is out of date and not a significant source of conversions. Rather than devoting resources to updating it, it's a better use of our resources to remove it and redirect people to pages that do a better job selling our mobile browsers.

- [x] Remove /firefox/browsers/mobile/compare/ and associated assets
- [x] Find links to it from around the site (footer, browsers/mobile, banner on compare landing page)
- [x] Remove links to it from around the site
- [x] Redirect the URL to /firefox/browsers/mobile/

**Comment by reemhamz** [comment]
In the [mobile compare page](https://www.mozilla.org/en-US/firefox/browsers/mobile/compare/), there's also a link in the subnav that leads to a Chromebook info page, which isn't a mobile device per se. Are you ok with me removing the link from the subnav?

**Comment by stephaniehobson** [comment]
Yup, please remove it.
