### ISSUE TITLE
Port Challenge the Default landing page to French

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#14169]
## Description
The CTD landing page was created in German but the campaign is being expanded, starting with French but then to a few more languages.

New translations will reside at /firefox/challenge-the-default/ but the German page remains at /firefox/ (at least for now).

More info and resources (Mozilla-only):
Asana task: https://app.asana.com/0/1204604936721242/1206302680261436/f
Copy: https://docs.google.com/spreadsheets/d/1KF9hfxONY7Dccep7InJEECLPJkFgDZzddJmSXsA7Gj8/
Design: https://www.figma.com/file/7QLwJIytyYUIL4NDkZS16e/Firefox_DMA?type=design&node-id=140%3A15490&mode=design&t=NzB90m8ATfCvyRhG-1

**Comment by enavajas** [comment]
Hi there, per legal's direction, we need to update one word in the four CTD FR pages. We need to remove the word "monopolisation" from a paragraph under the FAQ section on all four pages. 

The links to the four affected pages are:
1. https://www.mozilla.org/fr/firefox/challenge-the-default/
2. https://www.mozilla.org/fr/firefox/challenge-the-default/?v=2
3. https://www.mozilla.org/fr/firefox/challenge-the-default/?v=4
4. https://www.mozilla.org/fr/firefox/challenge-the-default/?v=5

I am adding a screenshot to indicate the section + word in question. 

<img width="1728" alt="Screenshot 2024-02-13 at 12 59 34 PM" src="https://github.com/mozilla/bedrock/assets/134577516/731f1103-1a32-4a57-b300-159f952ae436">

Please let me know if you have any questions! Thank you
