### ISSUE TITLE
Move /firefox/browsers to /firefox

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14222]
- [x] move /firefox/browsers to /firefox
- [x] update associated links
- [x] add a redirect from the old to the new
- [x] remove the split component at the top of the page and replace it with a heading and subheading like the ones on /products
- [x] update the heading text to: 

**Firefox Browsers**
Get the browser that puts your privacy first — and always has

---

# Blocked by https://github.com/mozilla/bedrock/issues/14266

**Comment by stephaniehobson** [comment]
We need a plan for moving the German CTD page off /firefox before this happens.

**Comment by stephaniehobson** [comment]
https://github.com/mozilla/bedrock/issues/14266 should be resolved Monday 🤞 so dev work can start on this now.

**Comment by alexgibson** [comment]
Screenshot of new header:

![image](https://github.com/mozilla/bedrock/assets/400117/99025703-f31e-4982-a123-1e3a66891521)
