### ISSUE TITLE
Move firefox/accounts to /account

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14230]
Firefox accounts has re-branded to Mozilla account

- [x] move firefox/accounts page to /account
- [x] remove subnav
- [x] add the heading "Mozilla account"
- [x] change the theme to Mozilla (that might happen automatically with the move 🤞)
- [x] redirect firefox/accounts to /account
- [x] update links
- [x] update any pre-existing redirects that point to firefox/accounts to /account

**Comment by alexgibson** [comment]
Just to double check here, do you mean the new URL should be mozilla.org/mozilla/accounts, or mozilla.org/accounts?

**Comment by stephaniehobson** [comment]
mozilla.org/account

Thanks for checking.

**Comment by stephaniehobson** [comment]
Oh, I just found out there was a request to make it mozilla.org/accounts (plural).  Unfortunately the request came from someone no longer here. I will try to get a final word on this from someone else.

**Comment by alexgibson** [comment]
we can always add a redirect for account -> accounts too (or vice versa)

**Comment by stephaniehobson** [comment]
Fixed in #14265
