### ISSUE TITLE
Move from django_jinja to core Django Jinja2 support

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14238]
## Description

As part of prepping the ground for Wagtail, we need to move to using Django's built-in Jinja2 support, rather than `django-jinja`

---

#### Success Criteria
- [ ] Django-jinja is not used to render pages
- [ ] Site content/resulting HTML is 100% identical to before the internal changes

**Comment by janbrasna** [comment]
The Epic currently looks like it was decided against built-in Jinja2:
> "Decision: stick with django-jinja, because its feature set is better"

Is this still relevant then?

**Comment by stevejalim** [comment]
Closing - this is not a workable route as Django's core Jinja2 support isn't broad enough for our needs
