### ISSUE TITLE
Reduce /firefox/privacy section

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14248]
The [Firefox privacy section](https://www.mozilla.org/en-US/firefox/privacy/) doesn't fit with our strategy going forward. We'd love to have a privacy section of the site but whatever form that takes will be different from this.

**Simplify the landing page:**

- [x] remove copy and links to this page where you can (use your best judgment, avoid creating new strings for translation)

If not all the links can be quickly removed re-factor the page to:

- [x] remove subnav
- [x] remove the privacy promise from the global navigation menu
- [x] update content to look something like the image below (use the firefox theme, [privacy promise heart logo](https://github.com/mozilla/bedrock/blob/main/media/img/firefox/privacy/icon-privacy-promise.svg), and existing icon colours, use your best judgment) (Components: section heading, narrow content container with 3 articles, content container with picto component)

![Screenshot 2024-02-23 at 11 50 46](https://github.com/mozilla/bedrock/assets/854701/bf8640ea-0af3-477e-9223-26798ef7d0df)

**Remove the sub pages:**

- [x] Remove firefox/privacy/products and redirect to /products
- [x] Remove firefox/privacy/book
- [x] Remove firefox/privacy/safe-passwords and redirect to /firefox/features/password-manager/
- [x] Remove associated links

**Comment by janbrasna** [comment]
For starters I'll try to find new link destinations for existing hrefs to pages that should be removed, without any l10n impact, as a first step. I'll split this into more PRs as some will need design decisions or bigger layout/content updates than just a new location:
- Point links away from `firefox.privacy.products` (+remove menu item from Products subnav)
- Point links away from firefox/privacy/book
- Point links away from firefox/privacy/safe-passwords

**Comment by janbrasna** [comment]
In case the reduced "Privacy Promise" page is kept, I have one additional suggestion: changing the _family_ favicon to the _browser_ one like elsewhere, for consistency:

![Screen Shot 2024-06-12 at 15 56 18](https://github.com/mozilla/bedrock/assets/1784648/1fbac061-26b2-4204-a5a1-8d7d2878226d)
