### ISSUE TITLE
Simplify dev edition whatnew page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14243]
Make the whatsnew page very simple, link to the release notes.

**Comment by reemhamz** [comment]
Link for reference: https://www.mozilla.org/en-US/firefox/120.0a2/whatsnew/

**Comment by reemhamz** [comment]
Do we need a designer for this, or do we have an idea in mind for how we'd like to simplify it?

**Comment by craigcook** [comment]
The current page is essentially a pitch for MDN Plus. If we want to significantly change the content we do probably need to engage a writer and designer for input.

**Comment by stephaniehobson** [comment]
I was thinking something very simple that informs them their version of Dev Edition updated successfully and links to the release notes (which are English only so the link needs to either only show up in English or contain a warning it is in English).

I was going to throw something together.

**Comment by stephaniehobson** [comment]
We should go back to using parts of the old one with the out of date / redundant info removed.

![Screenshot 2024-03-06 at 12-38-07 Firefox Developer Edition](https://github.com/mozilla/bedrock/assets/854701/bffa2e49-75b6-4bdd-b3b9-c21f8b9a2101)

**Comment by stephaniehobson** [comment]
These components should be returned to base protocol in https://github.com/mozilla/bedrock/issues/14244

**Comment by stephaniehobson** [comment]
We could add this after the update notification:

![Screenshot 2024-03-06 at 13 08 15](https://github.com/mozilla/bedrock/assets/854701/1ff492b5-8c2b-416e-92d8-b03b5c35d22b)

Linking to:
https://developer.mozilla.org/en-US/curriculum/
https://developer.mozilla.org/en-US/docs/Web
https://developer.mozilla.org/en-US/plus
