### ISSUE TITLE
Combine remaining Mozilla Spaces on one page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14245]
- [x] Remove the individual pages under [/contact/spaces/](https://www.mozilla.org/en-US/contact/spaces/)
- [x] On the landing page include the office name and address in a four column default-aligned [picto component](https://protocol.mozilla.org/components/detail/picto--default) (use the space stickers as the images)
- [x] Remove Twitter, Facebook, and space operations guide links

**Office logos:**

- /media/img/careers/locations/mozilla-toronto.png
- /media/img/careers/locations/mozilla-berlin.png
- [you will have to make one for sf, here is the vector file](https://github.com/mozilla/bedrock/assets/854701/0f96ab6e-2ade-44a2-95a9-f085c252d011)
- [you will have to make one for Beijing, here is the vector file](https://github.com/mozilla/bedrock/assets/854701/4395944a-96e8-4830-80c8-87cbfff300b5)

**Comment by reemhamz** [comment]
Just to confirm, would the only information within a location's picto container be the address of the office?

**Comment by stephaniehobson** [comment]
Yes 👍

**Comment by janbrasna** [comment]
@stephaniehobson The Beijing sticker is SVG (OK), but the SF image link leads to a huge raster PNG that's hard to edit (needs the borders, background and logo removed) — while not impossible it would be more clean to work with SVG, maybe you could try to find a real vector of the SFO illustration?

**Comment by stephaniehobson** [comment]
@janbrasna I updated the description with an SVG for SF, thanks for keen observation!

**Comment by stephaniehobson** [comment]
Yeah, the new one is good to use. I couldn't find an SVG of the first one and the second one had a "2" in the filename so I think it is probably more recent. But there's nothing official about these images so using the "wrong" one is low risk.

**Comment by janbrasna** [comment]
I think they're all awesome;) We'll see how busy they look in small sizes, IIRC they're used at ¼ size at 150px.
