### ISSUE TITLE
Remove light footer from Firefox pages

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14251]
A long time ago in a galaxy far far away we had a separate look and feel for the Firefox part of the website compared to the Mozilla parts. We're moving away from that kind of separation and in the name of simplifying code maintenance we should retire the light version of the footer that appears on the Firefox pages.

(no changes to the light footer on the whatsnew pages).

- [ ] Replace all appearances of the light footer with the standard dark footer
- [ ] Remove the light footer and associated code

**Comment by reemhamz** [comment]
The [`/download/thanks`](https://www.mozilla.org/en-US/firefox/download/thanks/) page has a bottom section with a background that matches the light-theme footer, and there might be some other pages with the same. Do we also want to change its background color or shall we just keep it as it is?

![Screenshot 2024-03-12 at 12 02 21 PM](https://github.com/mozilla/bedrock/assets/42309026/2cc31f2a-cf8f-4950-81c5-5fd9b2df8247)

**Comment by reemhamz** [comment]
Question: why keep the light-theme for WNP if we're removing it for Firefox pages?

**Comment by stephaniehobson** [comment]
@reemhamz I think we can leave the background colour as-is for any place where there is a strip at the bottom. We certainly can in the screenshot you shared. 

I thought the WNP footer was different code but poking around at is now I see that it is not. I think we should retire it from there too but it's worth discussing with the WNP stakeholders.

So... we can either wait until we have an answer for what to do with the WNP to do any work or we can do the rest of the site first and address the WNP in a separate PR. Thoughts?

**Comment by stephaniehobson** [comment]
Oh, LOL you already have a PR without the WNPs! 🏃‍♀️

**Comment by reemhamz** [comment]
Luckily it's all the exact same code on every page, and just being imported :) the main difference in the Firefox/WNP is that there is a CSS class applied to them that gives them the light theme. In the PR I have open, all I did was remove the `theme_class` macro from a base template that gets imported, and instead made the lighter footer appear only on WNPs -- pretty simple stuff!

Also, it's almost just as easy to entirely remove the light theme from code, it's just removing some CSS, a macro, and a CSS conditional 👍🏼

**Comment by stephaniehobson** [comment]
From Slack: We'll use the dark footer starting on WNP 125 and when 125 releases (April 16) we will change the older pages to have the black on as well, and can pull out the rest of the code then.

**Comment by reemhamz** [comment]
Let's keep this issue open until we also remove the light footer from WNP come v125

**Comment by janbrasna** [comment]
@reemhamz 👋 Just a kind reminder that WNP 125 is ready #14394 and to go live tomorrow, so this is no longer blocked to get changed completely now.
