### ISSUE TITLE
Remove settings.FACEBOOK_LIKE_LOCALES and all related code

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14260]
I noticed that we have `settings.FACEBOOK_LIKE_LOCALES` in the codebase, and a util which uses it to set a value in the context via a context processor, but that the value is no longer used, because we don't have FB Like buttons in the site any more

We should clean that up

---

#### Success Criteria
- [ ] Codebase no longer has support for FB Like button

**Comment by stevejalim** [comment]
@alexgibson Am I right that we no longer use the FB like button/widget anywhere in Bedrock these days?

**Comment by alexgibson** [comment]
> @alexgibson Am I right that we no longer use the FB like button/widget anywhere in Bedrock these days?

That's correct yeah, we can remove this 👍
