### ISSUE TITLE
Update to the reimagine site to indicate event has passed

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14295]
Hello,

We need to update this site (https://reimagine.mozilla.org/en) to indicate that the event has passed. We have flexibility to do this as we think is best, since we no longer have a contract with them. 

Please let me know if you have any questions! Thank you :)

**Comment by janbrasna** [comment]
@enavajas Hi, the event is not served by mozorg website, the correct repo is [@mozilla/reimagine](https://github.com/mozilla/reimagine) 🔖

**Comment by alexgibson** [comment]
@enavajas can this issue be closed out?

**Comment by enavajas** [comment]
> @enavajas can this issue be closed out?

yes :)
