### ISSUE TITLE
Add Fakespot to /products/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14290]
## Description

Fakespot is currently missing from https://www.mozilla.org/en-US/products/

---

#### Success Criteria
- [ ] Fakespot is present as a product

**Comment by reemhamz** [comment]
We'll need the logo, image of it being used on a phone (matching the rest of the page) and a blurb of what to write for its section in the Nav as well. 

The blurb can be something like `Use AI to detect fake reviews and scams on e-commerce sites`

**Comment by reemhamz** [comment]
@enavajas can we get someone from studio to help design an image we could use that matches the rest of the page? :)

**Comment by enavajas** [comment]
> @enavajas can we get someone from studio to help design an image we could use that matches the rest of the page? :)

Yeah, totally. I will reach out to them.

**Comment by enavajas** [comment]
@reemhamz is there anything in here that we could use? https://www.figma.com/file/xlK86j9MkZCkRpRMqKLtex/Fakespot-Brand-Guidelines?type=design&node-id=1-3&mode=design&t=mPImgp3YzEUBLCYA-0

**Comment by stephaniehobson** [comment]
I'm working on converting this page to use logos instead of product images.

**Comment by enavajas** [comment]
Aw man, they already did it for us. Ok, I have it if you need it

**Comment by stephaniehobson** [comment]
Well, if you want to chase down one for Thunderbird and MDN Plus we can keep the existing design.

**Comment by enavajas** [comment]
Nah, I’m sure they’d rather not have to also make those (unless necessary)
since they are swamped. And anyway looking ahead, a logo may just be the
easiest and less complicated approach anyway. Up to you however!

**Comment by enavajas** [comment]
> I am still working on this :)

i am so sorry, i got mixed up with another issue i had open that i was meaning to close 😑
