### ISSUE TITLE
Updates to Mozilla Legal Pages

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14299]
Hello. We received a request to make a couple of updates to legal pages. 

### **_Request No. 1:_**

1. Create two new pages to display new legal documents (similar in formatting and style to the other existing legal pages).

2. Host the document text from the two new pages in the Legal Github repository so that it can be updated from there in the future.
3. Add the links to the two new pages to the [Mozilla Legal ](https://www.mozilla.org/en-US/about/legal/)page.

[- Content for **New Page 1**](https://docs.google.com/document/d/1CjiKXzYBA9VOn9xOAeXWUGqqOQB5uW5gceUCcoAiUDw/edit#heading=h.4wqy1gf0chjj)
[- Content for **New Page 2**](https://docs.google.com/document/d/1LlzppFALQdkluE6Vy2cggksWZaYRzA0saZWuIkHZgOA/edit)

### **_Request No. 2:_** 
_Note: this should be completed after Request No. 1._

1. Create a central landing page for users to access the relevant TOS, Privacy Notice, and content policies for **AMO**, as well as **content moderation policies** (i.e. both of the new pages created with Request No. 1). 

**_Notes:_**
- This can be the same format as other legal landing pages, such as [the one for privacy](https://www.mozilla.org/en-US/privacy/)
- A link to this LP does _not_ need to be displayed on the main [Mozilla Legal page](https://www.mozilla.org/en-US/about/legal/), but they will need a URL so they can link to it directly from AMO-hosted pages.

**Comment by reemhamz** [comment]
For **Request No. 1** I'm not exactly sure where the 2 new legal pages would fit in the Mozilla Legal page since they don't fall under Terms, Privacy & Trademarks, or Downloadable software notices :/

**Comment by reemhamz** [comment]
Spoke to legal, they currently don't want these 2 files to have their own landing pages from this ticket. This will be something they'll be scoping out when their intern joins in June. For now, they just want us to have these pages available on our website and for us to share the links with them
