### ISSUE TITLE
double-escaped page title for German version of Firefox for iOS page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/bedrock#14291]
### Steps to reproduce

1. Open https://www.mozilla.org/de/firefox/browsers/mobile/ios/
2. look at the page title in the tab

or

1. use a search engine to search for Firefox for iOS

### Expected result

`Firefox Browser iOS (iPhone & iPad) - Mozilla` as page title

### Actual result

`Firefox Browser iOS (iPhone &amp;amp; iPad) - Mozilla` as page title

Mozilla website:

![Bildschirmfoto 2024-03-05 um 15 58 34](https://github.com/mozilla/bedrock/assets/1100614/e72750f1-4db2-46d4-8a2d-34b7d45b6087)

Google:

<img width="642" alt="Bildschirmfoto 2024-03-05 um 15 58 45" src="https://github.com/mozilla/bedrock/assets/1100614/f68a0a53-337c-402d-9246-5f15ea242362">

Similar to #12129.

**Comment by janbrasna** [comment]
This happens in all languages that don't translate _'and'_ to "un" "et" "y" etc. and use '&' ampersand instead. Some more examples:

- NL: https://www.mozilla.org/nl/firefox/browsers/mobile/ios/
- SE: https://www.mozilla.org/sv-SE/firefox/browsers/mobile/ios/
- FI: https://www.mozilla.org/fi/firefox/browsers/mobile/ios/
- VN: https://www.mozilla.org/vi/firefox/browsers/mobile/ios/

**Comment by alexgibson** [comment]
Thanks for the report. It looks like localized title strings are being escaped twice here, once in [bleach ](https://github.com/mozilla/bedrock/blob/main/lib/l10n_utils/templatetags/fluent.py#L61)and then again in the [jinja template](https://github.com/mozilla/bedrock/blob/main/bedrock/base/templates/base-protocol.html#L27).

We'll need to double check, but I think we should be OK to remove the (older) Jinja escape here.
