### ISSUE TITLE
Newly published legal documents need to be properly linked on mozilla.org

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#14346]
## Description

[A few new documents](https://github.com/mozilla/legal-docs/pull/2027/files) were created and merged in this repo. They need to be properly linked on mozilla.org page

Please coordinate with @aroybalreid

CC @pmac

**Comment by reemhamz** [comment]
Closed for https://github.com/mozilla/bedrock/issues/14299

**Comment by flodolo** [comment]
Are you sure that's a duplicate? That seems to be mostly about AMO, this has 1 page about AMO (policies), but also 3 about Formulaic.

**Comment by aroybalreid** [comment]
The main thing I need with the Formulaic ones is a URL that the product can link to. If they are also hosted on the Legal page with the various other terms, that's fine, but the most critical thing is having a URL that people signing up for or using the product (hosted on Formulaic.app), can click on to see the policies

**Comment by peiying2** [comment]
@reemhamz https://github.com/mozilla/bedrock/issues/14299 covers only AMO, we have three more new documents to be added. I will open a new ticket.

**Comment by reemhamz** [comment]
Ah sorry folks, my Ramadan brain fog 🌁  closed this issue just quickly assuming it was the legal pages I was discussing with Ashley, I should have done a double take before deciding to close the issue. I'll re-open now and tackle it when I have time next week.

**Comment by reemhamz** [comment]
Okay, spoke with the team and I'll be closing this PR as:
- The Formulaic team already has these legal pages live on their website (check the footer): https://formulaic.app/
- The AMO policy page has already been taken care of in another PR (https://github.com/mozilla/bedrock/issues/14299)
- Thunderbird privacy policy page was automatically updated
