### ISSUE TITLE
`…see-how-firefox-for-desktop-stacks` wrong number of compared browsers

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14354]
## Description

At the bottom of the mobile browsers page, there is a box that tells people they can read more about firefox compared to other browsers. The text in the box says:

https://github.com/mozilla/bedrock/blob/1d3d23fdb4fa7c6b5da0709adf3c65c30de44791/l10n/en/firefox/browsers/mobile/index.ftl#L26

> ![Firefox mobile browsers](https://user-images.githubusercontent.com/30198386/181856370-f6d244d5-84d5-4311-a7c2-9a10b8eea60f.jpg)

> "… stacks up to seven other browsers."

The target page lists six browsers total, i. e. five other browsers.

### Steps to reproduce

1. go to https://www.mozilla.org/en-US/firefox/browsers/mobile/
2. scroll to the bottom and observe

### Expected result

`browsers-mobile-see-how-firefox-for-desktop-stacks` string and localizations contain the correct number of compared UAs.

### Actual result

The string (in EN and localizations alike) contains "**seven** other browsers", while in reality the comparison page shows six browsers total, i. e. it's only **five** other browsers.

**Comment by janbrasna** [comment]
Ah I see it now, the number of browsers changed most recently for #14142 in #14167 so this string would also need some updating anyways.

What is the best way? Keep the current string as fallback and add a `-v2` new saying "five others"? Or to make it easier to maintain try to re-use some of the recently updated strings for comparison? Or maybe separating out the number as a variable and use a number not word for futureproofing? Or maybe omitting the number entirely from the string, leaving it as "see how fx stacks up to other browsers" and be done?

**Comment by craigcook** [comment]
I'm updating this string along with other comparison page updates in #14336.

I've gone for your third option, to just omit the number so we won't need to worry about it again.
