### ISSUE TITLE
Foundation redirect

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14351]
Hi there. [www.mozilla.org/research](http://www.mozilla.org/research) and [www.mozilla.org/research/cc](http://www.mozilla.org/research/cc) need to redirect to [foundation.mozilla.org/research](http://foundation.mozilla.org/research)

*There will be a follow up request at some point to redirect that second URL to a specific section on the foundation site, but for now both should redirect to the foundation page listed above.

**Comment by craigcook** [comment]
We now have the URL for the second redirect: `https://foundation.mozilla.org/en/research/library/?topics=187`

**Comment by janbrasna** [comment]
This was completed in a457e9e
