### ISSUE TITLE
Remove format option from newsletter preference center

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14362]
## Description

![image](https://github.com/mozilla/bedrock/assets/400117/c2ea9190-461b-47cb-9d04-11f283941535)

The email marketing team have asked to remove this option in the newsletter preference center, as text based email are not supported by Braze (our new vendor).

See also https://github.com/mozilla/protocol/issues/926 for removing the same option from newsletter forms.

---

#### Success Criteria
- [x] Format option is removed both from newsletter forms and the preference center.

**Comment by reemhamz** [comment]
Note that @pmac mentioned that they're getting rid of this option entirely, so we're also going to be removing it from the newsletter macro in Bedrock so it's removed from all newsletter signups
