### ISSUE TITLE
Don't redirect to dead labs site

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14364]
## Description

Historically `/technology` URL used to be part of top-level navigation menu item, and subsequently ripped off as a part of somewhat "unified Protocol masthead" copied over to downstream projects.

After changes in #6824 and #8642 the removed page redirects to https://labs.mozilla.org which is unfortunately abandoned now (returns empty 404 page with no sunset info and no redirection anywhere), but the `/technology` URL is still being used in various templates and leads people from blogs' main navigation to dead sites:/

I know it sounds weird maintaining dead links, but in this case it might be worth it, as up until last month this URL was part of [WordPress theme header `nav-global.php#L15`](https://github.com/craigcook/frontierline-theme/blob/f03ad06034fc9b6c8c71e7d46c96591e7ee56048/themes/frontierline/includes/nav-global.php#L15).

Refs: https://github.com/mozilla/One-Mozilla-blog/issues/74

### Steps to reproduce

Go to https://www.mozilla.org.tr/ and click "Teknoloji" in main menu.

_(this is just an example blog, but reproduces for any community using `frontierline` before https://github.com/craigcook/frontierline-theme/pull/64 that added customizable menu, or using the defaults, or not using own child theme to override the masthead…)_

### Expected result

Take the users anywhere useful instead of the removed page, e.g. future.mozilla.org (or /products, or /firefox/developer etc.)

### Actual result

`/technology` is redirected to labs.mozilla.org which is a 404 dead link.

```http
HEAD /technology/?utm_source=www.mozilla.org.tr HTTP/1.1
Host: www.mozilla.org

HTTP/1.1 301 Moved Permanently
Location: https://labs.mozilla.org/?utm_source=www.mozilla.org.tr

HEAD /?utm_source=www.mozilla.org.tr HTTP/1.1
Host: labs.mozilla.org

HTTP/1.1 404 Not Found
```

I know it's an ancient URL and old redirect, but please consider updating it so that the decade-old links hardcoded somewhere don't bring people to 404s today.

**Comment by alexgibson** [comment]
@janbrasna thanks for pointing this out, I agree it makes sense to update seeing as labs is now 404 👍
