### ISSUE TITLE
Nested list fails to render on about/governance/policies/security-group/certs/policy

### ISSUE THREAD

**Issue by gliu20** [mozilla/bedrock#14374]
## Description

Cross-reporting from: https://bugzilla.mozilla.org/show_bug.cgi?id=1888740
Solves webcompat issue: https://github.com/webcompat/web-bugs/issues/135300

### Steps to reproduce

Visit  https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#84-externally-operated-subordinate-cas

Notice that the nested list fails to render

## Actual results:
Nested lists fail to render as a sublist

![image](https://github.com/mozilla/bedrock/assets/24921711/8f41a96c-d4d2-4cad-8752-a9d41ff451b2)

## Expected results:

The correct indentation in https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md

## Relevant Source code: 
https://github.com/mozilla/bedrock/blob/main/bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html#L905

## Core Issue:
Running the markdown generator as specified in the comment at the top of the file does fail to create the nested ul. Looking further, it seems the core issue is python-markdown requires tab_length=2 to be set as a configuration option per https://github.com/Python-Markdown/markdown/issues/3

I do not see a way to configure that via the command-line but creating a quick python script fixes the issue:

```python
import markdown

with open("policy.md", "r", encoding="utf-8") as f:
    text = f.read()
    
html = markdown.markdown(text, tab_length=2, extensions=['markdown.extensions.toc'])

with open("policy.html", "w", encoding="utf-8", errors="xmlcharrefreplace") as output_file:
    output_file.write(html)
```

Alternatively, we should make sure to use a tab spacing of 4 in all *.md if python-markdown is used as the generator. I wonder if there is a linter or something to catch errors like these so we can avoid regressions.

**Comment by stevejalim** [comment]
Thanks for the report and the investigation @gliu20! 

Initially I wondered about 'fixing' the data upstream to use four-space indents, but I'm not sure if that'd cause problems/surprises elsewhere, particularly for editors working on that content who are used to two-space indents.

I'm thinking that maybe the most effective, and stably repeatable solution here is to take your script and extend it a little, leaning on `BeautifulSoup` (or similar) to add relevant classes, build the TOC, and splice that into a skeleton of the page -- and to update the comment in the template to tell users how to run that script. 

I'll take a swing at that now, as I have some headspace free and can't resist automating things 😆

**Comment by gliu20** [comment]
Not sure how I missed this but I just noticed that `tab_length=2` breaks the list in Section 1.1. 

Maybe commonmark would be better since I believe that's how most markdown editors parse md rather than John Gruber’s Markdown spec with python-markdown. It seems it works as expected (at least at a cursory glance), but then we'd need to find a replacement for making the anchor tags for the headings. 

It is a pretty interesting rabbit hole seeing how different implementations have subtly different parsing behavior 😅

**Comment by stevejalim** [comment]
Ah that's interesting @gliu20 - thanks for the re-check.

I'll try out commonmark as an experiment, and I'll also check in with someone on the policy source repo about whether the indentation for  1.1 is worth fixing.

What's evident from your comments is that we should definitel add some good tests around any automation. If you want to suggest some test cases to include, feel free, but no pressure.
