### ISSUE TITLE
MDN icon in nav not the actual logo

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14370]
## Description

In #12722 it was hinted the menu item icon for MDN Web Docs might need refreshing.

It is a metaphor resembling the current logo, but it's not the actual MDN logo.

### Steps to reproduce

Hover the "Innovation" main menu.

### Expected result

MDN icon being probably closer to the actual MDN logo.

### Actual result

![Screen Shot 2024-03-28 at 19 05 17](https://github.com/mozilla/bedrock/assets/1784648/c1bafa9e-8be1-4738-ba90-cb3523fd5601)

The icon representing MDN Web Docs is actually quite a good metaphor without using the real MDN logo, but as this submenu got all colourful and filled with logos, the B&W icon is probably not needed anymore and more "real" representation of the site could be used.

**Comment by janbrasna** [comment]
The full logo would be too oblong to use:
![Screen Shot 2024-03-28 at 18 57 46](https://github.com/mozilla/bedrock/assets/1784648/dff34e9b-4850-40c6-b450-0e1acfe4d790)
but there's also a shorter version being used:
![Screen Shot 2024-03-28 at 18 58 07](https://github.com/mozilla/bedrock/assets/1784648/e4df5477-d416-4e4d-9701-4a65d68eca73)
but that seems too plain:/

From exploring the identity being used around the site in creative ways like:
![Screen Shot 2024-03-28 at 18 57 43](https://github.com/mozilla/bedrock/assets/1784648/369c138d-9bf2-4142-9bd7-c8f02e0316cf)
using the elements of the logo freely as anchoring points to show relation to MDN brand, I guess that we could maybe create own representation of the menu item icon representing MDN just using the shapes?

Something like this?

![Screen Shot 2024-03-28 at 18 57 20](https://github.com/mozilla/bedrock/assets/1784648/a8353a5d-a76b-462c-b7dd-fc87adf82503)

**Comment by stephaniehobson** [comment]
I like the M_ in the second example :)
