### ISSUE TITLE
Internal AI Newsletter Signup Page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14393]
Hi there. We have a request to create a signup page for an internal newsletter.

This page can be simple, and modeled off of previous newsletter sign up pages, like [this](https://www.mozilla.org/en-US/newsletter/) one or [this](https://getpocket.com/explore/pocket-hits-signup) one. 

The copy for the page should be:
_"This week in AI" is a newsletter that keeps you posted on the most relevant AI news to Mozilla. The ai360 team scours the Internet and our Slack channels to bring you the latest and greatest AI developments across Mozilla, open source, policy, startups, industry, research, and trustworthy AI. Subscribe below!_

The data collection fields should be:
1.  Your email address
2. Select country or region (not sure what the best option is here – maybe we have a drop down of a few common ones, or they fill it in?)

The image above the copy should be: 
![image (14)](https://github.com/mozilla/bedrock/assets/134577516/9675e587-29eb-4569-bfee-3507362d3572)

**_Note: Since this is internal, it will need to be behind SSO._**

**Comment by robhudson** [comment]
Since we're getting rid of the email format in #14362 we wouldn't need it here as well.

The form will also need a hidden field with the newsletter ID whenever we have that available and added to basket.

**Comment by reemhamz** [comment]
I can pick this up, however I'm not entirely sure how to make this SSO friendly...? Since we make things on a public website and not on an internal-company site, would we be the right team for this?
cc: @alexgibson @slightlyoffbeat

**Comment by enavajas** [comment]
I feel like Steve may have ideas since we’ve done SSO stuff before with
birdbox…..?

**Comment by reemhamz** [comment]
Yeah, I'm looking through Bedrock's codebase and there are no references to SSO/single sign-on, unless we're using a different term for it. I'll cc @stevejalim here as well to see if this was indeed done on Birdbox before?

**Comment by reemhamz** [comment]
Discussed it with the team, and my thoughts were correct, we've never done or will do any SSO-related content on our website since it is 100% public facing and for a wider audience. Closing this issue
