### ISSUE TITLE
Remove CPU architecture type detection from site.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14404]
## Description

I need to double check first, but I think since https://github.com/mozilla/bedrock/pull/14096 was completed we no longer need to keep the `archType` UA checks that are still in site.js.

---

#### Success Criteria
- [ ] Verify that there's nothing left that relies on detecting CPU type (e.g. ARM).
- [ ] Remove `archType` functions and code from `site.js`.

**Comment by janbrasna** [comment]
There's an open issue for Chromebooks: #8006 that refers (=is caused by?) this sniffing. Can't tell if removal of the arch detection makes the Chromebook results better or worse, just wanted to mention it.

**Comment by alexgibson** [comment]
@janbrasna if removing this code helps fix one of those false positives then it's another reason to remove this code 👍

**Comment by janbrasna** [comment]
Additionally I think the `.arm` body class added to the /thanks page has no effect today — it [used to](https://github.com/mozilla/bedrock/blob/16322320b37096116fb32d3166808d580376fcf6/media/css/firefox/new/common/thanks-messaging.scss#L64-L72) show a link to sumo, but that's long gone, and today even the linux-arm explainer [is removed](https://github.com/mozilla/bedrock/pull/14096/files#diff-4b21adb47c34cf1547384758f5fcb7fea4878508e99860171aede9b7b7757bd1L69-L71) in favour of generic instructions. Windows ARM64 detection is removed too #9768, so this seems OK.

The ARMv8-A are still tested via `getArchSize("aarch64")` if needed so this all looks like just an old, unused code. :shipit: 🚢
