### ISSUE TITLE
Remove mozilla connect banner on /contribute

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14400]
## Description

The Mozilla Connect banner at the top of /contribute has been active for a long time now and can be removed: 

https://www-dev.allizom.org/en-US/contribute/

**Comment by janbrasna** [comment]
Is there any other place the Connect Community is linked from?

It used to be linked somewhere from /stories but that has been already removed.

I can imagine being it part of the regular content of /contribute somewhere down there, but right now the four cards align nicely, don't see how a fifth could fit well:(

**Comment by janbrasna** [comment]
Well if the topics somehow align within "Our Mission" content, it can be two items to keep the grid — a good copy could probably fit not only "Connect", but also Discourse in some form (but with so many categories there I'm struggling to come up with a decent tagline, but it can easily revolve around community, participation, openness etc.) — with two new items it could work maybe?
