### ISSUE TITLE
Remove UA client ID from stub attribution

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14406]
** ⚠️ Wait for July 2024 ⚠️ **

The UA/GA3 code will stop working at the end of June. At that time we will not have a UA stub attribution ID to log anymore and should remove the code that captures and sends it.

Let @willdurand know when this is complete so he can remove the corresponding code from stub attribution.

**Comment by alexgibson** [comment]
@stephaniehobson if the UA/GA3 code will stop working at the end of June, shouldn't we remove the check before that happens as opposed to after? Or is there a reason why we should wait?

**Comment by stephaniehobson** [comment]
There's some people who are still relying on custom reports in the GA3 interface. I wanted to leave it as long as possible. Still, mid-June should be okay. I'll confirm in the migration channel and assign an earlier start date if I can.

**Comment by alexgibson** [comment]
> There's some people who are still relying on custom reports in the GA3 interface.

My main concern would be if something in our attribution code blows up, should the GA3 code stop working. If we can set a date to remove this code before the end of June, that would ease the risk I think.

**Comment by stephaniehobson** [comment]
I've asked in #ga4-migtation-2024 on Slack if we can start mid-June. The main concerns seems to be with YoY comparison for the KBR - but if the Big Query sync stops before June we don't have it anyway.

Not to mention the other costs with running the code in parallel. Hopefully we can solve this with planning and math 🤞

**Comment by alexgibson** [comment]
Now that UA is turned off in production, this is imposing a ~2second delay to stub attribution calls, so we should remove the `getUAClientID()` that now returns `null`.

**Comment by alexgibson** [comment]
Opened a PR to remove `client_id` cc @willdurand ^
