### ISSUE TITLE
Expose Desktop Nightly for Linux/ARM64 www.mozilla.org for downloads

### ISSUE THREAD

**Issue by gabrielBusta** [mozilla/bedrock#14414]
## Description

I am working on patches to publish an ARM64 Nightly build to the Mozilla FTP archive.
I'd like to direct people that prefer our traditional .tar archives to https://www.mozilla.org/en-US/firefox/all/#product-desktop-nightly
Under select you preferred installer - people should be able to select "Linux ARM64/AArch64" to get the files from https://download.mozilla.org/

I also filed a Bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1889793)

cc @JohanLorenzo

**Comment by alexgibson** [comment]
Thanks @gabrielBusta - let us know when this is ready and we'll take a look at adding this

**Comment by gabrielBusta** [comment]
Hi @alexgibson! We're nearly there, with just [a few patches left to land](https://lando.services.mozilla.com/D205501/) and the task of [adding the builds to download.m.o](https://bugzilla.mozilla.org/show_bug.cgi?id=1889782) :)

It would be great to have these builds available early on the 127 Nightly starting on April 15. That would be the week after next. Does this seem doable? I'm open to suggestions.

**Comment by alexgibson** [comment]
@gabrielBusta I'm gonna take a look at what needs doing here (been a while since I've had to add a new option here). I'll let you know if I have any Qs.

**Comment by alexgibson** [comment]
OK, I think I have a handle on what needs doing here. Let me know once the builds are available in bouncer @gabrielBusta and I'll follow up here with adding them to /all 👍

**Comment by gabrielBusta** [comment]
@alexgibson the builds are now available in bouncer

**Comment by alexgibson** [comment]
@gabrielBusta thanks - I'll try and push this up to a demo for you to test.

**Comment by alexgibson** [comment]
@gabrielBusta I pushed this for a demo environment for you to test. Please let me know if this looks OK to you? https://www-demo3.allizom.org/en-US/firefox/all/#product-desktop-nightly

Thanks again

**Comment by alexgibson** [comment]
Oh, it looks like the builds are all 404 since the demo is pointed at https://dev.bouncer.nonprod.webservices.mozgcp.net/. Prod seems fine though. Is that something you could perhaps get someone to take a look at fixing @gabrielBusta ?

**Comment by gabrielBusta** [comment]
OK. Good to know. I don't have access to the bouncer DBs but [I requested we add the builds to the dev and staging bouncer.](https://bugzilla.mozilla.org/show_bug.cgi?id=1889782#c18) The production environment should be fine, we added all the locations to that one.

**Comment by gabrielBusta** [comment]
@alexgibson the builds were added to the stage and dev instances of bouncer :)

**Comment by gabrielBusta** [comment]
> @gabrielBusta I pushed this for a demo environment for you to test. Please let me know if this looks OK to you? https://www-demo3.allizom.org/en-US/firefox/all/#product-desktop-nightly
> 
> Thanks again

Looks good to me!
