### ISSUE TITLE
Add CTA to Fx Features Private Page in DE and FR

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14428]
Hello.

We received a request to add a button with the CTA "Download Firefox" on [this]((https://www.mozilla.org/en-US/firefox/features/private/)) page directly below the headline of _**"What information does Firefox collect?"**_

This button should only be in DE and FR. The page already exists in DE and FR copy so we don't need l10n for the page copy. For the "download Firefox", we can use the copy from past pages with l10n. Do we have this, or would you like me to find it?

This will be part of a 50/50 traffic split experiment being done by a separate agency.

**Comment by reemhamz** [comment]
This is sort of an odd request. Having a CTA show up right under a header when there's a body related to the header?
Wouldn't it make more sense to just add it to the bottom of the page (which is after that header/body section)?

**Comment by reemhamz** [comment]
And I'm assuming we'd be the ones covering the 50/50 split right? I don't see how the agency will be able to conduct that experiment themselves on our website?

**Comment by janbrasna** [comment]
FYI the page already displays download CTA in non-FF browsers. See how the whole page compares for FF vs. non-FF:

![Screenshot 2024-04-10 at 18 40 48](https://github.com/mozilla/bedrock/assets/1784648/c103b7ec-78ac-408e-9435-6ac9c9bc4d7d)

**Comment by reemhamz** [comment]
yup correct! i've just been confirming a few things with the team requesting this. They mainly wanted a CTA above the fold but never specified if they want it only for non-fx browsers or not
