### ISSUE TITLE
Bring back WNP118 for Fx beta 126

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14435]
Hello, we received a request to stand back up WNP 118 on translations for the fx team to push out a Beta that opens a WNP to ensure that the new Nimbus integration works. This should go to production w/ WNP 125 that goes live on April 16th. 

They would like to match the same translations that were previously available for this page (en-US and en-CAN, and EU translations are most important)

for reference: link to wnp118 demo: https://www-demo4.allizom.org/en-US/firefox/118.0/whatsnew/?v=1

**Comment by craigcook** [comment]
We'll apply the same template for 127beta as well.
