### ISSUE TITLE
Updates to PDF Editor Page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14445]
Hello. We have received a request to update [this page](https://www.mozilla.org/firefox/features/pdf-editor/).

They would like to add a few 2-3 sentence blurbs (similar to the existing sections detailing "add text" and "add drawings"), and a visual/screenshot to go with it. 

For reference, 

- [Here](https://docs.google.com/document/d/1YuOSJD16evC2XImFyyrXwmSeSCdlKVFeD3nqega6Ljw/edit?usp=sharing) is the copy doc (it has been approved). 
- [Here](https://www.figma.com/file/elSBKpUxHCZe6yTqoohUu9/PDF.js-Designs?type=design&node-id=3547-82665&mode=design&t=FnsNaWKUz7J9hESO-4) is a Figma outlining how to add an image.
- [Here](https://www.figma.com/file/elSBKpUxHCZe6yTqoohUu9/PDF.js-Designs?type=design&node-id=3547-83550&mode=design&t=FnsNaWKUz7J9hESO-4) is the Figma showing how you’d add alt text to set image.
- [Here](https://www.figma.com/file/elSBKpUxHCZe6yTqoohUu9/PDF.js-Designs?type=design&node-id=4669%3A34201&mode=design&t=aR8CKrJc89zdy7se-1) is the Figma showing the PDF highlight.

**_**Timing**: they are releasing PDF editor on April 17th, and would like to include the latest feature updates to the existing page._**

**Comment by reemhamz** [comment]
Happy to take this on once content is delivered

**Comment by enavajas** [comment]
Thank you! I’ll let you know once I get it. Should be Monday

**Comment by enavajas** [comment]
@reemhamz this has been updated and is ready to start dev 🙂
