### ISSUE TITLE
"Learn more about Mozilla" (account) string in CTA/forms

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14460]
## Description

The signin/about "already have an account?" sentence in CTA/form for Mozilla account sounds like it's missing the "account" last word:

![Screenshot 2024-04-16 at 2 01 22](https://github.com/mozilla/bedrock/assets/1784648/46f207ce-ce2d-40e2-bf08-2d0a4e8d4113)

### Steps to reproduce

https://www-demo3.allizom.org/en-US/firefox/browsers/mobile/ (bottom: form)
https://www-demo3.allizom.org/en-US/firefox/ (bottom: cta)

https://github.com/mozilla/bedrock/blob/69baed8399e9258ea15020d729c3cda404da1aab/l10n/en/mozilla-account-promo.ftl#L12-L13

### Expected result

"Already have an account? [Sign in](https://accounts.stage.mozaws.net/signin?entrypoint=mozilla.org-products&form_type=button&utm_source=mozilla.org-products&utm_medium=referral) or [learn more](https://www-demo9.allizom.org/en-US/account/) about Mozilla **Account**"

### Actual result

> Already have an account? [Sign in](https://accounts.stage.mozaws.net/signin?entrypoint=mozilla.org-products&form_type=button&utm_source=mozilla.org-products&utm_medium=referral) or [learn more](https://www-demo9.allizom.org/en-US/account/) about Mozilla

**Comment by reemhamz** [comment]
Hello!
I've checked the documents we've referred to when working on this form section, and they all just mention "learn more about Mozilla" instead of "learn more about Mozilla account" (the "account", by brand, is supposed to be lowercase, as its more of a generic word than branded). I think it was left intentionally (as It's also been reviewed by copywriters when working on this update), especially considering the "account" word isn't supposed to be a branded word. I'll close this as a wontfix. Thanks for your keen eye though wow!

**Comment by janbrasna** [comment]
Noticed another occurrence, where it makes more sense: 

![Screen Shot 2024-06-11 at 19 12 53](https://github.com/mozilla/bedrock/assets/1784648/d4b2490f-e316-43e6-ac9e-80f23f8b698e)

The copy is pretty much the same, but reads "learn more about **joining** Mozilla" which feels like the reported one was also supposed to be this.

**Comment by reemhamz** [comment]
Oh, I think you might be right here, that's a good find. I'm all for making this clearer to our users, so if you'd like to open a PR that adds the word `joining` to the main promo, then I grant you the green light! 🚥

**Comment by janbrasna** [comment]
👌 Sweet! I didn't want to propose any superfluous changes at first, but seeing that the original call-to-action has been like this for many years, it will hopefully be prepopulated from Pontoon translation memory as a suggestion. (More importantly I wanted to do this before the og string gets removed with privacy pages reduction, so it's not lost completely…)

I also checked some "slower" languages, and they mostly don't have `moz-account-already-have` from last year translated yet, so no harm done there. Hopefully it won't be an issue for more active locales, those get stuff like this translated usually in matter of days. So I believe the timing for this fix is just about right, having the same content as a pre-existing string may actually get more languages to have this call-to-action now translated, repurposing the current copy from older location (that is usually localised even in these "slower" languages).
