### ISSUE TITLE
[l10n] Remove files in [en] in the www-l10n repo 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#14477]
## Description

The compare browser files have been removed in Bedrock according to [this PR](https://github.com/mozilla/bedrock/commit/b8b1bb42321eaba134616ed55ecd6e903d2593ff). The [en] files need to be removed in www-l10n repo too so the localized files no longer appear in Pontoon. Otherwise, some communities may spend time on pages no longer used.
  @craigcook

**Comment by craigcook** [comment]
There are other active still files in `/firefox/browsers/` so I don't think we need to change anything in `pontoon.toml`, unless we want to make the paths more specific.

**Comment by janbrasna** [comment]
This can be closed now, the pages are back fwiw.
