### ISSUE TITLE
Remove non-essential attribution fields from RTAMO flow

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14482]
## Description

As part of the data privacy / consent epic (see https://github.com/mozilla/bedrock/issues/14213), we want to remove non-necessary attribution fields (such as GA client_id and session_id) from the RTAMO flow. Only required fields that are necessary for the feature to function should be passed:

- `utm_source`
- `utm_medium`
- `utm_campaign`
- `utm_content`
- `referrer`

The following should not be set

- `ua`
- `experiment`
- `variation`
- `client_id`
- `client_id_ga4`
- `session_id`

---

#### Success Criteria
- [x] RTAMO only includes required attribution fields

**Comment by stephaniehobson** [comment]
The docs say `Specifically, the RTAMO feature looks for a utm_content parameter that starts with rta:, followed by an ID specific to an extension. ` 

Should we consider `utm_source`, `utm_medium`, and `utm_campaign` non-necessary?

**Comment by stephaniehobson** [comment]
Also, in the long run, is there any chance we could start using a rtamo specific query parameter and stub attribution field for this? (not now, I know now this is urgent).

**Comment by alexgibson** [comment]
@stephaniehobson both legal and product have discussed what’s norm-necessary and signed off keeping what we have here. I’ll share the decision brief with you privately.

**Comment by alexgibson** [comment]
> Also, in the long run, is there any chance we could start using a rtamo specific query parameter and stub attribution field for this? (not now, I know now this is urgent).

Possibly, but I think we need to first discuss what the problems are and what we’d gain by switching, and then weigh the effort. But this is outside of the scope of this change.
