### ISSUE TITLE
Chromebook dropdown cut off

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14491]
## Description

Trying to select a platform in CrOS dropdown hides the options behind some kind of overflow or z-index thingy from the rest of the page.

### Steps to reproduce

https://www.mozilla.org/firefox/browsers/chromebook/
- try to select the second value from the arch dropdown
- the page section starts to scroll, if you're able to get to the second item at all

### Expected result

Dropdown being on top, page not having scrolling bits.

### Actual result

recording:

https://github.com/mozilla/bedrock/assets/1784648/c994d95e-be1a-4e26-bc06-1d8f6d98a7d8

### Environment

reproduced in random selection of geckos and webkits

**Comment by janbrasna** [comment]
Ah, it's some bad interaction between relative positioning and grid boundaries — the bespoke dropdown is on the bottom edge of the grid container — so when unfolded, it stretches its parent and shifts stuff around, making the selection seem cut off and/or triggering some puzzling overflow scrolling.

**Comment by reemhamz** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/14653
