### ISSUE TITLE
H2 2023 Transparency Report

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14508]
Hello. We have received a request to update the transparency report content to reflect the information from H2 2023. 

The main landing page where this content lives is https://www.mozilla.org/en-US/about/policy/transparency/

I have outlined the requested changes below:

- [x] Change the text in this button to `July-December 2023 Report`
<img width="1483" alt="Screenshot 2024-04-29 at 10 24 45 PM" src="https://github.com/mozilla/bedrock/assets/134577516/9408740b-92f3-4170-b074-c62df481c8f9">

- [x] Add the current report (living [here](https://www.mozilla.org/en-US/about/policy/transparency/jan-jun-2023/)) to the list of Previous Reports, and title it `January-June 2023` 
- [x] Create a new page with the URL `https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2023/`. The page should match the template of the previous one, but will have updated information. 

**In the new page,**
- [x] The subheading should be updated to`Reporting Period: July 1, 2023 to December 31, 2023`
- [x] The numbers for the _Government Demands for User Data_ section are updated as follows:
<img width="496" alt="Screenshot 2024-04-29 at 10 33 47 PM" src="https://github.com/mozilla/bedrock/assets/134577516/ca59f8ec-5b49-4300-9b56-fe7aedcde263">

- [x] The _Government Demands for Content Removal_ section has the following copy updates:
<img width="488" alt="Screenshot 2024-04-29 at 10 36 42 PM" src="https://github.com/mozilla/bedrock/assets/134577516/3a55d214-0563-4d4d-98be-982a2eb1083c">

- [x] For the existing _Copyright_ and _Trademark_ sections, a title should be added before them of `Copyright and Trademark Requests`. Then, the copy and data of those sections should be updated as follows:
<img width="684" alt="Screenshot 2024-04-29 at 10 38 19 PM" src="https://github.com/mozilla/bedrock/assets/134577516/09bc521a-516c-4046-8a21-435d9d43b89d">

- [x] For the current _Other Takedown Requests By Companies or Individuals_ section, the title should be changed to `Legal Removal Requests By Companies or Individuals` and the body copy should be changed to `In the Reporting Period, we received 0 private legal removal requests invoking laws other than copyright or trademark (note that takedown notices can target more than one item). Where takedown requests are made pursuant to national laws removal might be limited to the relevant jurisdiction.`

- [x] The _Personal Data Requests_ section has the following copy and data updates:
<img width="696" alt="Screenshot 2024-04-29 at 10 41 54 PM" src="https://github.com/mozilla/bedrock/assets/134577516/ce1b2fb2-7f32-43d9-b58e-c528cf67987e">

- [x] Under the _Targeted Advertising Disclosures_ section, the copy should be changed as follows:
<img width="670" alt="Screenshot 2024-04-29 at 10 50 22 PM" src="https://github.com/mozilla/bedrock/assets/134577516/799c39b4-7468-43f1-9905-ee0341cc74cd">

- The pdfs to be linked in the new _Mozilla Corporation_ section can be found [HERE](https://drive.google.com/drive/folders/1u2oaRhJ5_XdZxdDqPL6-OiclPLHa0eSh). The titles of the pdfs match those in the list. 
- The pdfs to be linked in the _Mozilla Foundation Ads_ section can be found [HERE](https://drive.google.com/drive/folders/1EiycUbPg3h8h_lwyMRx9uWUaPRqeu8bf). The titles of the pdfs match those in the list. 

_Note: the **Firefox** section will be absent this time._ 

- [x] Under the _EU Monthly Active Users_ section, the copy and data should be updated as follows (note the removal of two of them):
<img width="674" alt="Screenshot 2024-04-29 at 10 43 54 PM" src="https://github.com/mozilla/bedrock/assets/134577516/eb879560-231d-4c9b-bc99-64409a85db99">

- [x] The current section titled _Supplement_ should be changed to `Policy Supplement` and the body copy can be updated to:

> During the course of this reporting period, Mozilla continued to protect the privacy and security of our users through public policy interventions. In the European Union, we refocused our efforts on the eIDAS legislation as the law entered its final stages in the legislative process. Article 45 in the law threatened encryption and web security by limiting standards for web certificates and taking away the independence of browser root store programs. Our efforts in H2 2023 focused on amplifying our policy focused [campaign](https://securityriskahead.eu/) to drive awareness of the risks in Brussels, [organising](https://last-chance-for-eidas.org/) the cybersecurity community to highlight technical concerns, convening an industry [open letter](https://blog.mozilla.org/netpolicy/files/2023/11/eIDAS-Industry-Letter.pdf), conducting meetings with members of the European Council, Parliament and Commission, and engaging with civil society [allies](https://nce.mpi-sp.org/index.php/s/cG88cptFdaDNyRr). Through these efforts, we were able to help persuade the European Parliament to introduce a cybersecurity clarification to Article 45 as part of its adopted public [position](https://www.europarl.europa.eu/doceo/document/A-9-2023-0038-AM-007-007_EN.pdf) on the legislation which will largely mitigate the security and privacy risks.  We also reiterated our [concerns](https://blog.mozilla.org/netpolicy/2023/07/13/european-parliaments-version-of-the-cra-threatens-cybersecurity-and-open-source-development/) on the Cyber Resilience Act (CRA) and engaged in conversations to protect the interests of the open source community. We also were quoted in [media](https://netzpolitik.org/2023/gefaehrlicher-praezedenzfall-neues-gesetz-in-frankreich-will-browser-zur-zensur-verpflichten/) about browser support for global privacy control in Germany and ran a [campaign](https://foundation.mozilla.org/en/campaigns/sign-our-petition-to-stop-france-from-forcing-browsers-like-mozillas-firefox-to-censor-websites/) on France’s efforts to make browsers the [vectors](https://thenextweb.com/news/french-law-threatens-free-internet-warns-mozilla) of website blocking. 
> 
> In the United States, we called for [reform](https://blog.mozilla.org/netpolicy/2023/07/27/mozilla-calls-on-congress-to-reform-fisa/) of Section 702 of the Foreign Intelligence Surveillance Act (FISA) and organised a builders [letter](https://blog.mozilla.org/netpolicy/2023/12/08/mozilla-and-allies-say-no-to-surveillance-blank-check-in-ndaa-yes-to-strong-surveillance-protections/) in line with our long-standing [advocacy](https://wiki.mozilla.org/Netpolicy/actions#Surveillance) on the issue. We also submitted [comments](https://blog.mozilla.org/netpolicy/2023/08/11/mozilla-supports-updates-to-the-health-breach-notification-rule/) on the FTC’s Notice of Proposed Rulemaking for the Health Breach Notification Rule (HBNR) and [applauded](https://blog.mozilla.org/netpolicy/2023/08/18/mozilla-applauds-cfpb-for-taking-on-the-data-broker-ecosystem/) the Consumer Financial Protection Bureau (CFPB) for taking on the data broker ecosystem. Finally, we also weighed in with our [thoughts](https://blog.mozilla.org/netpolicy/2024/01/11/mozilla-weighs-in-on-state-comprehensive-privacy-proposals/) on the state privacy proposals in Massachusetts and Maine. 
> 
> Globally, we wrote about the [efforts](https://www.techpolicy.press/five-eyes-campaign-against-encryption-threatens-democracy/) of the Five Eyes against encryption and the threats it poses to democracy and also gave a [talk](https://media.ccc.de/v/37c3-12004-please_identify_yourself) at the Chaos Communications Congress on the privacy connotations of digital identity systems around the world.

- [x] For the _Voluntary Threat Indicators & Data Disclosures_ section, the current table should be removed and the information should be replaced with the following on 2 lines:
```
0 Cybersecurity Threat Indicator Disclosures
0 Other Specific User Data Disclosures
```

**_I know this is a lot of little things, so please don't hesitate to let me know if you have any questions. Thank you!_**

**Comment by alexgibson** [comment]
@reemhamz Emma asked me to put this up on a demo server so I pushed it to demo6 (just FYI)

https://www-demo6.allizom.org/en-US/about/policy/transparency/jul-dec-2023/

**Comment by enavajas** [comment]
Hi @reemhamz! I think there may be an inadvertent period at the end of the PDF link for the TikTok Reporter Campaign under the Ads section 👀 (screenshot attached). 
![IMG_2381](https://github.com/mozilla/bedrock/assets/134577516/0b0ce07f-be6c-4236-aec0-b5a3eac5a917)


It seems to break on my end when I click it, but the same link without the period at the end seems to work (https://assets.mozilla.net/pdf/transparency-report/h2-2023/tiktok-reporter-campaign.pdf). Would you mind taking a look to see if that’s what is going on?

Please let me know if we need to request something else from legal to fix it. Thank youuuuuu!

**Comment by reemhamz** [comment]
Ah thanks for the heads up @enavajas!! I just fixed it now
