### ISSUE TITLE
Legal text to be revised in en/privacy/cookie-settings.ftl 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#14505]
## Description

The string in this paragraph needs to be revised for better translation:

Issue: `... different types of Cookies and similar technologies (such as pixel tags, web beacons, clear GIFs, JavaScript, and local storage) (“Cookies”)...`. The way this sentence is structured makes it difficult to translate. 

### Steps to reproduce

File name: en/privacy/cookie-settings.ftl 
String ID: [cookie-settings-page-intro](https://github.com/mozilla-l10n/www-l10n/blob/c51dba778a49d095a3d9bb5709d5bab205155587/en/privacy/cookie-settings.ftl#L11) 
Text: `This page describes the different types of Cookies and similar technologies (such as pixel tags, web beacons, clear GIFs, JavaScript, and local storage) (“Cookies”) that { -brand-name-mozilla } may use, and gives you control over which types of data you agree to { -brand-name-mozilla } collecting.`

### Expected result

Per @Feldman from legal, remove the text in the first parentheses, `(such as pixel tags, web beacons, clear GIFs, JavaScript, and local storage)`

### Actual result

Updated text reads `This page describes the different types of Cookies and similar technologies (hereafter, “Cookies”)`

**Comment by alexgibson** [comment]
Thanks for passing it by legal already. I’ll update. Do you require a new string ID @peiying2?

**Comment by flodolo** [comment]
Looks like wired got crossed somewhere.

Per conversation with Feldman: the original suggestion was to drop the first parentheses (not the content), we then agreed to make it explicit that `("Cookies")` refers to all the items leading to it by adding "hereafte".

```
This page describes the different types of Cookies and similar technologies such as pixel tags, web beacons, clear GIFs, JavaScript, and local storage (hereafter, “Cookies”) that Mozilla may use, and gives you control over which types of data you agree to Mozilla collecting.
```

**Comment by nlpinc** [comment]
Suspense.



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by flodolo** [comment]
> Do you require a new string ID @peiying2?

Yes, it requires a new ID as this has been translated already.
