### ISSUE TITLE
[l10n] { -brand-name-mozilla } -> { -brand-name-mozilla-account }

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#14538]
## Description

Mozilla account should be coded as `{ -brand-name-mozilla-account }`: [... such as logging in using your { -brand-name-mozilla } account ...](https://github.com/mozilla/bedrock/blob/75cab111a37834d71ed02f2aa7e692380b9eda4a/l10n/en/privacy/cookie-settings.ftl#L29) 

### Expected result

Change from `your { -brand-name-mozilla } account` to `your { -brand-name-mozilla account }`

**Comment by flodolo** [comment]
This is fixed by https://github.com/mozilla/bedrock/pull/14545 (don't have permissions to close it).

Note that it's replacing the old string, not keeping it around as obsolete, since the page is not in prod yet.
