### ISSUE TITLE
Update donate links on footer and contribute page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14537]
Hello, we have received a request from MoFo to update a couple of links on moz.org:

- [ ] On the footer for the site, change the `donate` link to: https://foundation.mozilla.org/?form=moco-donate-footer
- [ ] On the [contribute page](https://www.mozilla.org/en-US/contribute/), change the `donate` link to: https://foundation.mozilla.org/?form=contribute

Thank you!

**Comment by craigcook** [comment]
While we're updating the footer, I'm also going to update the "Press Center" link to point to a more active source, and change "Corporate Blog" to "Mozilla Blog"
