### ISSUE TITLE
Home page updates for june 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14543]
Hello. We are going to make the following changes to the [www.mozilla.org](https://www.mozilla.org/en-US/) homepage.

**[HERE](https://www.figma.com/file/gGW6xUpetI6wjsnccWWXvV/mozilla.org-refresh?type=design&node-id=2158-1511&mode=design&t=R5voHsAipBwpedvj-0)** is the figma file containing the changes.  (Mozilla only)

The design + copy in the figma file is final _except_ for the copy in the Trustworthy AI section. That will be shared with us shortly, and I will comment once we have it. 

Please put this on a demo server once ready so I can share w/ the team.

**Comment by reemhamz** [comment]
Can we have the team verify what URLs we should use for some of the updates too? For example, which URL should I use for Fakespot? Should we be using the AMO URL or the Fakespot landing page?

**Comment by enavajas** [comment]
> Can we have the team verify what URLs we should use for some of the updates too? For example, which URL should I use for Fakespot? Should we be using the AMO URL or the Fakespot landing page?

Yes – I will get all of those confirmed for you.

**Comment by stephaniehobson** [comment]
This came in via email:

> ... one thing to add for the Mozilla.org homepage - our fundraising team would like to use '?form=featured-section' to track donations coming from the [mozilla.org](http://mozilla.org/) homepage (so the url I believe should be https://mozilla.org/?form=featured-section).

**Comment by slightlyoffbeat** [comment]
I'm going to consolidate a few things into here a checklist:

Ready:

- [ ] Pocket logo always looks optically larger than the other logos. Lets make the pocket logo 44x44px with 3px padding in the image (that way we do a 1:1 swap)
- [ ] Change the 'trustworth AI' section into a split component with an image on the right side. Copy and Image TBD.
- [ ] Can we change the font-size for the 3x2 picto section to have text be 16px? Will make everything line up.
- [ ] Change Monitor text to "Reclaim your private info" to shorten
- [ ] Fakespot link should link to https://www.fakespot.com/ with campaign tags similar to what is used for relay and monitor link
- [ ] 

Not ready:

- [ ] final image for Trustworthy AI section
- [ ] Final copy, link, and CTA text for Trustworthy AI section
- [ ] Links for moco/ventures/ai section

**Comment by reemhamz** [comment]
@slightlyoffbeat if we're changing the picto font-size in the products section, do you want to do the same to the moco/ventures/ai picto or shall we keep that the way it is?

**Comment by reemhamz** [comment]
Also, I believe it's about time we also add Fakespot to the Products nav

**Comment by slightlyoffbeat** [comment]
@reemhamz yes! we should add fakespot to nav.

Here's the next set of updates. A few changes, but mostly minor. Refer to [this](https://docs.google.com/document/d/1V_NMoWCFs_dCIhqHx5HAKdzaPQ0u1Ef5zB2UtGqdGeU/edit?usp=sharing) doc when referring to "doc" 

- [ ] remove the three icon section with Mozilla AI, Mozilla VC, and moco
- [ ] Update "is Mozilla a Corporation" copy section (see doc, section 1) 
- [ ] Update Trustworthy AI copy section (see doc, section 2)
- [ ] Update Trustworthy AI copy section to use attached image
- [ ] Make sure all external links on homepage (excluding nav/footer) use campaign params `?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage`
- [ ] external nav link for fakespot should use `?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=products`


![ai-1](https://github.com/mozilla/bedrock/assets/2030656/1e80c0ee-4971-4006-ba17-71b716212c27)

**Comment by reemhamz** [comment]
@slightlyoffbeat Thanks! I'll work on these changes shortly.
Curious, are we still going to be linking the Moz Ventures and Moz AI pages in our nav? I'm still waiting on the URLs + description of those.

**Comment by reemhamz** [comment]
Couple more questions:
- Aside from the MoFo donate mid-page banner, do we want any top banner live?
- For Monitor, we currently have 2 copies showing for `en-US` vs global:
  - `en-US`: Reclaim your private info
  - Global: Private & secure browsing

Is the new Monitor copy (`Protect your private info from data brokers`) meant to be for all locales?

**Comment by slightlyoffbeat** [comment]
Final stretch!

- [ ] Lets change order to hide the mismatched line heights a bit. Move Relay to bottom left. Fakespot to top right. VPN to bottom middle
- [ ] We will not be linking to ventures and mozilla AI in nav for now. Only nav changes should be adding fakespot
- [ ] There's a typo. Space missing: `MZLA, Mozilla Venturesand Mozilla AI`
- [ ] We will be linking to Mozilla Ventures and Mozilla AI in the paragraph text for the "So, what is Mozilla" section. URL is https://www.mozilla.ai/ and https://mozilla.vc/
- [ ] Please use standard UTM params for the paragraph text links: `?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage`
- [ ] Lets have `Protect your private info from data broke` be for all locales.

**Comment by slightlyoffbeat** [comment]
Reviewed everything on demo, and it looks good to me. Thumbs up from me as long as review, etc is good.
