### ISSUE TITLE
Update localized press links

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#14550]
## Description

A few years ago we created a number of international press blogs for different languages ([German](https://blog.mozilla.org/press-de/), [Spanish](https://blog.mozilla.org/press-de/), [Italian](https://blog.mozilla.org/press-de/), et al), and different local press teams published content on them. We then created a [helper function](https://github.com/mozilla/bedrock/blob/main/bedrock/mozorg/templatetags/misc.py#L333-L365) in bedrock that outputs the appropriate blog link for the current locale.

Those press blogs have since fallen out of use and aren't being updated. Some haven't posted anything since 2018. We're still linking to those very outdated blogs for those locales, and should instead update any existing press links to point to the current site where most of our press is published, https://blog.mozilla.org/category/mozilla/news/.

This also raises the question of what to do with those outdated press blogs, but that's not a bedrock issue.

**Comment by janbrasna** [comment]
1. the links have been all pointing to EN press blog since #14561
2. now just the `press_blog_url()` helper serves no purpose and can be eventually cleaned up.
3. (what to do with the localised press content is probably a task for the respective owners;)
