### ISSUE TITLE
Fix broken form on legal page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14556]
Hello. We were notified by legal that the form _Report of Misuse of Mozilla Trademarks_ ([here](https://www.mozilla.org/en-US/about/legal/defend-mozilla-trademarks/)) seems to be broken. 

They haven't been seeing submissions for over a week, which piqued their curiosity, and when they did a test submission (it routes to trademarks@mozilla.com), it did not come through. 

Are we able to determine what could be wrong and try to find a fix for it? Thank you!!

_**I have been notified that this is fairly urgent.**_

**Comment by alexgibson** [comment]
@stevejalim @robhudson when I test the form things seem to work OK here, and it says things were sent successfully when I fill out a test submission.

Could one of you take a look to see if there's a back-end issue here perhaps? Thanks

**Comment by stevejalim** [comment]
Shelling into a production pod, I can see we still have email-sending credentials enabled. 

I tried to send an email to myself to confirm that it's working:
```
>>> send_mail(subject="testing email is sent", message="testing", recipient_list=["stevejalim+test1@mozilla.com"], from_email="noreply@mozilla.com")
1
```

However, several minutes later, the message from the server hasn't landed in my inbox. I tried emailing the same address from a different account, to check that it's receiving ok, and that message got through.

I'll look and see if there are any obvious errors/messages in the console for the SMTP provider, but I think we're into SRE zone here. @bkochendorfer can I tag you in here, please?

**Comment by stevejalim** [comment]
Update: I can't see flatlining in the SMTP sender's metrics - email sending _appears_ to be working but I'd welcome a double-check, because clearly I didn't get the (two) test emails I send from a production pod.

Thought: maybe the credentials are stale/expired, but surely that would result in a failed attempt to send the email in the first place, as it's done directly via SMTP in the current process, and not deferred to a queue to send later

**Comment by enavajas** [comment]
Confirmed April 30th was the last submission to the form @stevejalim

**Comment by alexgibson** [comment]
@stevejalim was this one fixed, can we close it?

**Comment by stevejalim** [comment]
Yep, closing as fixed. We also now have a Dead Man's Snitch check in place that confirms every 6 hours that email sending from Bedrock is working
