### ISSUE TITLE
L10N-cleanup reminder action is closing more than the intended PR

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14571]
This morning this issue was auto-closed by a GH action https://github.com/mozilla/bedrock/issues/13357

Turns out it was this piece of automation which makes a [handy reminder task to clean up L10N strings](https://github.com/mozilla/bedrock/issues/14570)
https://github.com/mozilla/bedrock/actions/runs/9076625014/workflow

However, that action auto-closes issues with a particular label - in this case `L10N` which was validly used on a separate issue, the one mentioned at the top.

Should be an easy fix: we could/should make a dedicated label - eg `L10N-cleanup-reminder` or similar that won't be used on any other Issue and adjust the action to use that. That should avoid any clash.

**Comment by janbrasna** [comment]
You probably don't need a designated tag just for filtering the created issues, the cli has more flags https://cli.github.com/manual/gh_issue_list to pinpoint the intended issue#, if you don't want to search by the exact title, I guess filtering also by the author of `github-actions` (either as `--author` or maybe rather `--app` in this case) used to create the issues from GHA should suffice.

If you're planning improvements to the workflow, I have also two things to consider:
- adding `[cron]` or `[bot]` or something to the subject to distinguish the autogenerated issue from others at a first glance?
- linking to ["obsolete" ftl search results](https://github.com/search?q=repo%3Amozilla%2Fbedrock+obsolete+language%3AFluent&type=code&l=Fluent) from the issue body for convenience? (I know it's not perfect, but at least gives an idea…)

**Comment by stevejalim** [comment]
Thanks @janbrasna - those make good sense. (If you want to pick it up and PR a change, please feel free -- we'd certainly appreciate it)

**Comment by janbrasna** [comment]
I'm looking into this, but either I need to do a bit more escaping, or the cli can't cope with bot values — so if I fail to make it work this way I'll try converting the args into a query (basically passing a string similar to using search/filters in web UI, where [the `author:app/github-actions` token](https://github.com/mozilla/bedrock/issues/created_by/app/github-actions) works) and that should work.
