### ISSUE TITLE
Support pre-generating renditions

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14578]
## Context

Wagtail can generate versions of images automatically, in particular sizes that are specified via the template tag that includes the image. These are called renditions. [Explainer docs here](https://docs.wagtail.org/en/stable/topics/images.html). 

Normally, Wagtail will generate a rendition "just in time", while rendering out the HTML template that features the given image. (This approach is favoured because template markup (and therfore image specs) might change between release etc - and without parsing templates all the time, Wagtail won't know in advance what size images are needed.)

**Here's our problem:** generating revisions requires write access to both the cloud storage bucket (to save the new rendition) _and_ the database (to tell Wagtail that the rendition exists and where to find it). In our planned architecture, Bedrock's web pods will have read-only DB access and no write access to the storage buckets. Therefore we need to avoid a situation where a rendition needs to be created at page-render time.

We also need to support multiple-size renditions of an image, so that we can have reliable srcsets for `<img>` tags. This means we can't just expect to just use a single `original` rendition version. 

## The Plan

If we know what spec renditions we'll need, _and we stick to them_ when we write our image tags, we _can_ pre-generate renditions. 

Then we can reference them explicitly in the template markup, whether we're including an image with a single `src` attr or a `srcset`. Because they already exist, no new rendition-generation will be triggered. 

Because we're pre-making a range of them, there should be be incremental sizes available for all uses - eg a hero might want 1400px and 800px while a callout might want 1200px, 800px and 600px. 

The algo for determining rendition sizes (suggested in [this conversation](https://mozilla.slack.com/archives/CD6RG3N3H/p1715939530703159)) is

1. Pick a starting width. This will either be a max size of 2400px or the width of the image, whichever is the smaller.  
2. Generate series of renditions, getting smaller by 200px each step. 
4. Ensure (via documentation, team norms and code review) that whenever an image is used in a template:
   a. the requested fill-rule that fits that spec - eg `width-1000px` but not `width-950px` (See wagtail docs on [renditions](https://docs.wagtail.org/en/stable/topics/images.html) for the fill-rule syntax)
   b. the srcset features a fallback fill-rule of `original`, so we can - worst case - show something, rather than a missing image

Note that we can't upscale using Wagtail, so doubling the size of the image for a hires version isn't viable - we'll just have to encourage uploading hires images.

## To do

- [x] Team Frontend: Confirm the rendition-size algorithm above is sensible, workable and clear, and/or suggest improvements.
- [x] Team Wagtail: add a post-save hook to the image saving that pre-generates the renditions from an Editing Pod, which has appropriate DB and storage write access. This should be done AFTER setting up our custom image model, ideally.

#### Success Criteria
- [x] We use have various size images, based on CMS-uploaded images, in our templates
- [x] This all works without triggering the generation of new renditions at render time
- [x] We have a unit test which catches use of image tags that aren't on-spec, to avoid hard failure in production
- [x] We have documentation about the srcset/size options available

**Comment by stevejalim** [comment]
@alexgibson How's this sound? Feel free to comment or edit as you see fit. Thanks for bouncing this around!

**Comment by alexgibson** [comment]
I'm not sure I fully understand renditions in practice, but the proposal for pre-cutting variation sizes for responsive images at upload time sounds like a sensible enough plan to me 👍

**Comment by stevejalim** [comment]
@stephaniehobson This is the ticket re images that I just mentioned in our call.
