### ISSUE TITLE
Epic: Remove Pocket mode

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14596]
## Description

Now that we're no longer serving content for getpocket.com, we can remove the Pocket mode implementation and related pages. This will likely be split into a number of tasks, which can be defined below later when we're ready.

---

#### Issues
- [ ] #15124
- [ ] Front-end pocket mode removal

**Comment by janbrasna** [comment]
It also means that the following issues can be closed as `wontfix`?
- https://github.com/mozilla/bedrock/issues/14139
- https://github.com/mozilla/bedrock/issues/13177
- https://github.com/mozilla/bedrock/issues/12290
- https://github.com/mozilla/bedrock/issues/12324
- https://github.com/mozilla/bedrock/issues/12925
- https://github.com/mozilla/bedrock/issues/12965
- https://github.com/mozilla/bedrock/issues/12289
- https://github.com/mozilla/bedrock/issues/12291
- https://github.com/mozilla/bedrock/issues/11544
- https://github.com/mozilla/bedrock/issues/10756
- https://github.com/mozilla/bedrock/issues/10761

**Comment by alexgibson** [comment]
@janbrasna thank you for this housekeeping ♻️

**Comment by robhudson** [comment]
https://github.com/mozilla/bedrock/pull/15182/files
