### ISSUE TITLE
Firefox Developer Edition Page Duplicate String Usage

### ISSUE THREAD

**Issue by turnipjs** [mozilla/bedrock#14609]
## Description

The Firefox Developer Edition page uses the same string for two different features: Inspector and Console. This seems unintentional, and in my opinion looks unprofessional even if it is intentional.

### Steps to reproduce

[Link to live page](https://www.mozilla.org/en-US/firefox/developer/)
[Link to source file in this repo](https://github.com/mozilla/bedrock/blob/main/bedrock/firefox/templates/firefox/developer/includes/features.html)
[Link to strings file (english)](https://github.com/mozilla/bedrock/blob/main/l10n/en/firefox/developer.ftl)

### Expected result

Different text for different sections.

### Actual result

Same text.

### Environment
N/A

**Comment by janbrasna** [comment]
This is now resolved in production https://www.mozilla.org/firefox/developer/ — thanks for the heads up @turnipjs!
