### ISSUE TITLE
Dead Link for the 7zSD.sfx

### ISSUE THREAD

**Issue by Parkautomat1337** [mozilla/bedrock#14605]
## Description

When working on creating my own Firefox Installation I followed the german guide given in the mozilla support knowledgebase.

The hyperlink for downloading the 7zSD.sfx is responding with an error, no download is happening. 

### Steps to reproduce

Guide:
https://support.mozilla.org/de/kb/anpassen-des-firefox-windows-installers

7zSD.sfx: 
https://hg.mozilla.org/mozilla-central/raw-file/tip/other-licenses/7zstub/firefox/7zSD.sfx

![Screenshot 2024-05-28 at 14-11-23 https __hg mozilla org](https://github.com/mozilla/bedrock/assets/171035494/980c939b-0b67-4ba2-8dc5-bd6fbf2597ef)

### Expected result

Starting the download for the 7zSD.sfx - File.

### Actual result

error: other-licenses/7zstub/firefox/7zSD.sfx@046da0f065e90bcf67ec9fd58aa8f84c1a8f80be: not found in manifest

### Environment

Firefox 126.0 (64-Bit)
Windows 10

**Comment by janbrasna** [comment]
_(Not a `mozilla/bedrock` issue, you'd probably want to raise this in community discussions for your language group.)_

This is unfortunately outdated in more locales.

If you check the [en-US original](https://support.mozilla.org/en-US/kb/repackaging-windows-installer) article, the linked file is actually [7zSD.**Win32**.sfx](https://hg.mozilla.org/mozilla-central/raw-file/tip/other-licenses/7zstub/firefox/7zSD.Win32.sfx) — you can propose a fix for the knowledge base article in your language right on the support site to help improve this content for others.

**Comment by alexgibson** [comment]
Sorry, this is the wrong repository. Please open an issue for this over at https://github.com/mozilla/kitsune for support.mozilla.org issues.
