### ISSUE TITLE
Remove Hubs Privacy Notice Page + Link

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14647]
Hello. We received a request from legal to delete the Hubs privacy notice now that it has been sunset. The steps are below:

- [x] Delete this page: https://www.mozilla.org/en-US/privacy/hubs/
- [x] Remove the link to the page in the sidebar (see photo attached). 
![Screenshot 2024-06-05 at 4 49 02 PM](https://github.com/mozilla/bedrock/assets/134577516/0653ae18-e311-427e-84c3-7271a7ccdeb9)

**Comment by alexgibson** [comment]
Some open questions:

1. Should we also remove https://www.mozilla.org/en-US/about/legal/terms/hubs/ ?
2. Should these legal pages be archive to https://www.mozilla.org/en-US/privacy/archive/, or is the request to let them 404?

Imho, we should probably only let them 404 if we're confident that users are not going to find links to these pages in the wild. If they might still, we should probably archive them.

**Comment by enavajas** [comment]
@alexgibson yes, let's please archive both pages. thank you!
