### ISSUE TITLE
Update Copy in Mozilla’s Data Privacy FAQ

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14652]
Hello, we need to make some changes to the Mozilla’s Data Privacy FAQ page (https://www.mozilla.org/en-US/privacy/faq/)

The changes are outlined in this doc: https://docs.google.com/document/d/1cVfzhYC4US7yzkn2pxoPhUYwSf5B1Qeo2HhffGgquTY/edit

Thank you!

**Comment by reemhamz** [comment]
requesting access to the doc
