### ISSUE TITLE
FX Download Page Experiment

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14676]
Hello. Please see the project brief **[here](https://docs.google.com/document/d/1n0aMNYDnyjs_GU6ZnOd5-PJVn65-LbDMEmkQEzVgR3g/edit?usp=sharing)** (Mozilla only). Thank you.

**Comment by alexgibson** [comment]
Some new information on MS store technicalities:

1. The MS Store is not supported in every country. There are a list of around ~240 supported countries. David Rubino has access to the list of countries.
2. Windows 11 SE (the education SKU) does not have access to the MS Store. Windows 11 (and also the SE) version, are impossible to detect by User Agent.
3. IT admins can also restrict access to the MS store on Windows 10/11.

As such, we should be careful to:

1. Only show the MS store badge as the primary CTA in countries where the store is supported.
2. Always offer a secondary CTA (a regular installer link), should a user not have access to the store for reasons 2 or 3.

cc @enavajas

**Comment by alexgibson** [comment]
Removed previous comment as this is the wrong issue, apologies
