### ISSUE TITLE
Add Microsoft Store as installer option on firefox/all

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14673]
## Description

Add links to the Microsoft Store versions of Firefox on /firefox/all.

- [x] Add links to the Microsoft Store in the list of installers for Release and Beta
- [x] Auto fill the language as "multiple languages" like we do for iOS and Android
- [x] Display a link to the Microsoft store in step 4 instead of a download button 

Firefox: https://www.microsoft.com/store/apps/9NZVDKPMR9RD
Firefox Beta: https://www.microsoft.com/store/apps/9NZW26FRNDLN
Firefox Nightly: coming soon.

- [x] Add this text to the installer help modal:

> Microsoft Store
> This option will open a Firefox product page in the Microsoft Store web portal. If you are running Windows 10 or Windows 11, you will have the option to open the Microsoft Store from this page and install Firefox. If you install from the Microsoft Store, updates to Firefox will also be handled by the Microsoft Store. There are minor differences in Firefox behaviors and capabilities when installed from the Microsoft Store, but for most users these differences are not noticeable.
> 

- [x]  Make sure strings are FTL'd

**Comment by stephaniehobson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9845

**Comment by janbrasna** [comment]
The MS Store badges have guidelines https://learn.microsoft.com/en-us/windows/apps/publish/app-marketing-guidelines and also a link to generate a JS badge w/ campaigns and behav options etc.; TL;DR it currently looks like this:

> ![Screenshot 2024-06-19 at 23 01 25](https://github.com/mozilla/bedrock/assets/1784648/f69645d4-6086-4753-80c1-dd0f6a0441ac)

**Comment by stephaniehobson** [comment]
@janbrasna This is fantastic, thank you! My searches had failed to turn this up and I was on the verge of trying to make something myself.

**Comment by stephaniehobson** [comment]
@alexgibson yes, that makes sense and is what I was planning to do.

**Comment by drubino-mozilla** [comment]
Hello... I have no expectations at all for what it should be, but it would be useful to have an ETA for reporting purposes. Thanks!

**Comment by stephaniehobson** [comment]
Hi @drubino-mozilla it's wrapped up in the much more complicated https://github.com/mozilla/bedrock/issues/9845 but since that's almost ready to go I'm thinking before the end of July.

**Comment by alexgibson** [comment]
@stephaniehobson should we perhaps split out adding the badge into a separate issue? We'll likely need it before the end of July for the /new experiment.

**Comment by alexgibson** [comment]
Filed https://github.com/mozilla/bedrock/issues/14738

**Comment by stephaniehobson** [comment]
@drubino-mozilla It's been added on our demo server, can you please have a quick look and tell me if it's okay? 

[Relase](https://www-demo2.allizom.org/en-US/firefox/all/desktop-release/ ) 
[Beta](https://www-demo2.allizom.org/en-US/firefox/all/desktop-release/ )

**Comment by apsociallife** [comment]
Looks good to me! Thanks! I love the new design too. I assume we have QA on the page and I'm not playing that role today.

**Comment by stephaniehobson** [comment]
Code is merged. It'll push today.
