### ISSUE TITLE
Update macOS and iOS version in Downloads page for Mozilla VPN to macOS 11 and iOS 14

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#14727]
Jira ticket: https://mozilla-hub.atlassian.net/browse/VPN-6337

## Description

Given our adoption of QT 6.6, in Mozilla VPN 2.23 (ETA Late June) we are going to be begin requiring iOS 14 as the minimum iOS version. This is a bump from the current requirement of iOS 13.

Given our adoption of QT 6.6, in Mozilla VPN 2.24 (ETA Mid/Late July) we are going to be begin requiring macOS 11 as the minimum macOS version. This is a bump from the current requirement of macOS 11.5

For the sake of efficiency, we are OK making a change on our Website immediately and in one go.

Request

We should update the Downloads page in the Website: /products/vpn/download/, to reflect this.

**Comment by alexgibson** [comment]
PR to bump versions: https://github.com/mozilla/bedrock/pull/14780
