### ISSUE TITLE
Remove VPN headline experiment code

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14721]
## Description
The experiment that was added in https://github.com/mozilla/bedrock/issues/14131 has been deactivated in prod for several months, so we should be able to remove the experiment code.

Was there a winner / outcome of this experiment that should be implemented? /cc @enavajas

---

#### Success Criteria
- [ ] VPN experiment code is removed and a winner is chosen.

**Comment by enavajas** [comment]
not that i know of @alexgibson - i will investigate
