### ISSUE TITLE
[GTM Review] Review workspace "UA removal"

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14750]
## One-line summary

Review and publish GTM workspace "UA removal"

## Significant changes and points to review

- the biggest change is the removal of the `GA Pageview - Core Tracking` tag, this will stop loading any UA files and sending data to GA3.
- I also removed Tags, Triggers, and Variables used only by GA3. I am confident in these changes because the Tags were clearly labelled as GA or GA4 and GTM will not delete triggers or variables that are still in use.

## Issue

Issue: #14749

## Testing

- no javascript errors
- GA4 events are still sending

**Comment by alexgibson** [comment]
I've approved the changes in the workspace. I'll leave it to you to decide when to publish

I did notice some other possibly unused variables and bits and pieces left over, but for a first pass this LGTM. r+
