### ISSUE TITLE
Add a scheduled task to sync Smartling translations

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14776]
## Description

See https://github.com/mozilla/wagtail-localize-smartling/tree/main?tab=readme-ov-file#synchronization

We need a new k8s CronJob that runs every 10 mins on the editing deployment to pull translations into the primary DB

---

#### Success Criteria
- [x] CronJob added with appropriate credentials
- [x] DMS monitoring the CronJob (for Dev, Stage and Prod)
- [ ] CronJob working in Dev

**Comment by sarveshtiku** [comment]
Hey @stevejalim, can you assign this task to me.
