### ISSUE TITLE
New cookie settings page active elements hover/pointer

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14781]
## Description

Collapsible headings/sections and the close buttons don't change cursor on hover from text selection pointer to hand or any other interaction version, to provide a feedback the element has some function upon clicking.

Worse, the same is true for preference inputs, as both cookie-control-label and cookie-radio-preference also don't change pointer to signal interactivity.

### Steps to reproduce

Open https://www.mozilla.org/privacy/websites/cookie-settings/ and click around expanding and collapsing the detailed sections as _"How does Mozilla use this data?"_ and flipping the _"Preference"_ between _"I Agree"_ and _"I Do Not Agree"_ e.g.

### Expected result

To have mouse pointers demonstrate the affordance of being an active UI element instead of default cursor for just passive text selection.
(Compare to the same style of components on https://www.mozilla.org/privacy/subscription-services/ that show hand pointer on hover.)

### Actual result

Headings for expanding the text, close buttons for collapsing, and form elements for changing the preference all don't provide "active" pointer for interaction.

### Environment

macOS Catalina
FXDE 128b8, Chromium 127r1313161

**Comment by alexgibson** [comment]
@janbrasna these are stock form controls / protocol components. There’s a fine balance between overuse of the cursor for a pointer mechanism imho, but can I suggest you file a Protcol issue for this?

**Comment by alexgibson** [comment]
I think we could definitely add a pointer hover style to the details component here in the meantime, but I’m not entirely sure that controls should have this styling. I think that should have some further discussion in Protocol.

**Comment by janbrasna** [comment]
🤦 You're right, I was probably just too used to having frameworks' resets and/or defaults have the details and labels decorated with pointers before, not realising their (basic browser) defaults are actually plaintext carets. 🤯 🤡  

I haven't looked into the styling / base protocol deeper, I get it's just the base components, but wanted to raise this before looking into it further, if there's a need for that at least for the sake of consistency. But now see the difference:

- https://protocol.mozilla.org/components/detail/details-component--default has the pointer (=component)
- https://protocol.mozilla.org/components/detail/details has the system defaults (caret) because it's just the element
_(which makes sense, only was a bit unexpected)_

**Comment by alexgibson** [comment]
Yeah, it quickly gets a bit murky here. I think using `cursor: pointer;` is fine for any interactive element that's not obviously interactive without it on hover. As such, I think adding it to `<details>` probably makes sense here.

But adding it to basic form controls feels a little heavy handed perhaps. Native applications don't do this, and as long as we're styling our form controls sensibly, it should already be obvious they are interactive without it.

**Comment by alexgibson** [comment]
I think we can add it to `<summary>` on the cookie settings page as an interim fix.

Opening an upstream issue to add it to the Protocol base styling makes sense to me.
