### ISSUE TITLE
Dependabot PR grouping

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14809]
## Description

Motivated by `psycopg*` that can't be updated by individual PRs now, would it be helpful if scheduled updates are grouped? Either for just `psycopg*` or maybe whole pip `*` for minor bumps (not security, they still trigger individually regardless of schedule).

Dependabot grouping makes sense for minor+patch. Major shouldn't be intertwined with these.

_(I see the only issue in Selenium minor version updates being avoided constantly for some compatibility reasons. Once Selenium gets phased out, this won't be a problem anymore.)_

Having regular updates in one PR/checkout also makes it easier to test, instead of individual packages' PRs (that can often fail to resolve one by one too, as with wagtail being picky about willow etc.), so current dependabot scheduled bumps are merely a reminder to redo it manually on the side and supersede it by own PR.

---

#### Success Criteria
- [ ] Being able to update `psycopg[binary]` and `psycopg-binary` that have to be bumped in one go (to the same version) via PRs and with proper CI runs.
- [x] Regular dep updates are grouped so that build+tests run for the whole changeset, and it could also be checked out locally to testdrive in one go.
- [x] Less noise, and dep update PRs ready to test and merge instead of updating manually just to close out the individual dependabot PRs by superseding them with own PRs.

**Comment by alexgibson** [comment]
> Less noise, and dep update PRs ready to test and merge instead of updating manually just to close out the individual dependabot PRs by superseding them with own PRs.

This is something I'd very much like to do yeah. If we can group dependabot PRs in a more manageable way, then I'd also love to enable them for NPM dependencies too.

**Comment by janbrasna** [comment]
@alexgibson I've iterated over the various settings and grouping configs to get a bit meaningful results, you can [check the current yml](https://github.com/janbrasna/gha-dependabot-test/blob/main/.github/dependabot.yml) I'm [somewhat](https://github.com/janbrasna/gha-dependabot-test/issues/22) comfortable with that produces [these updates](https://github.com/janbrasna/gha-dependabot-test/pulls) — there are still a few [letdowns](https://github.com/janbrasna/gha-dependabot-test/issues/24) I'm jotting down. RIght now I'm not happy with updates to python lockfiles so I'll elaborate on that if I find a good setting…

**Comment by alexgibson** [comment]
@janbrasna thanks for taking a look at this! I think this may be something we want / need to test out iteratively to see what works best.

**Comment by janbrasna** [comment]
I will write up the path I took, why I did some tuning of the configs etc. so you can then swipe the bits that look applicable (or you can just follow my changes through the few commits and see the resulting PRs there). TL;DR the frontend groups look alright to me if you feel like browsing around, it's the backend groups that are somewhat underwhelming in how the versions are pinned:/

**Comment by alexgibson** [comment]
Thanks, this will be super useful!

**Comment by janbrasna** [comment]
Also one bit to point out when grouping, if there are PRs open immediately for security bumps, when time comes for the scheduled group these would also get included in the group, and the original individual security updates get superseded and closed. That kinda makes it less visible that it was an actual security advisory-triggered bump in the first place.
