### ISSUE TITLE
1-click subscribe for the Knowledge is Power (KIP) newsletter

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14823]
Hello 👋 We have received a request from the NA LCM team to help them continue to engage their deprecated S&P newsletter audience by offering them the option to subscribe to their KIP newsletter instead. 

After discussion with our engineering team + the LCM team, the following user flow was agreed upon:

1. The user clicks the `subscribe` link in the email the LCM team will send letting subscribers know that the S&P newsletter will soon be replaced by the KIP one. 
2. The user is taken to a page on [mozilla.org](http://mozilla.org/) with text saying "Confirm your subscription" and a button that says `subscribe`. There is no set design for this page – it can be very simple, much like [this](https://www.mozilla.org/en-US/newsletter/security-and-privacy/) one, but with the revised language. 
3. The user clicks the `subscribe` button on that page.
4. The KiP newsletter subscription is then set to `true` in the basket slug in Braze email. 
5. The user is then sent to a page with a confirmation message stating "Thank you for subscribing". They can then see their subscriptions on the page. 

The requested completion date for this task is any time prior to our code freeze on July 26th, 2024. 

Thank you 🙂

**Comment by alexgibson** [comment]
>  it can be very simple, much like one, but with the revised language

@enavajas is the "much like one" bit here missing "this", that was supposed to be a link to an example layout?

**Comment by enavajas** [comment]
> > it can be very simple, much like one, but with the revised language
> 
> @enavajas is the "much like one" bit here missing "this", that was supposed to be a link to an example layout?

Hi @alexgibson – yes, my bad 😑 the link didn't stick for some reason. I was pointing to this page: https://www.mozilla.org/en-US/newsletter/security-and-privacy/

**Comment by alexgibson** [comment]
@enavajas is this OK for the "very simple" page?

![image](https://github.com/user-attachments/assets/47860868-a8dd-444d-94b9-f5e035f2074d)

**Comment by alexgibson** [comment]
> The user is then sent to the Email Preferences page with a confirmation message stating "Thank you for subscribing". They can then see their subscriptions on the page.

Also, would it not be simpler just to display a "Thank you for subscribing" message, rather than forward the visitor to the newsletter preferences page? 

I'm not sure that the preferences page really has an option to display a "thank you" message.

**Comment by enavajas** [comment]
In terms of simplicity of design, yes, that aligns with the request. 

In terms of the pref center, I confirmed with the requestor that we do not need to send users there – ending the user journey at the "thank you" page works. 

Thank you @alexgibson

**Comment by alexgibson** [comment]
@enavajas this page is now in production and can be accessed at `https://www.mozilla.org/en-US/newsletter/knowledge-is-power/confirm/{INSERT_NEWSLETTER_TOKEN_HERE}`.

Can you please let whoever asked for this know, and also ask them to please test the flow to make sure things are working as expected before sending people to it for real? Thanks!

**Comment by alexgibson** [comment]
@enavajas I'm going to re-open this issue as I think I've just discovered a possible bug in the flow (language gets set back to English when confirming the subscription if I had a different language specified previously).

I'm not sure what's expected here, but I'll check with pmac/rob on how to handle this if it is an issue.

**Comment by alexgibson** [comment]
@enavajas OK the issue as I see things here:

- This confirmation page is English only. Are they going to send the email in English only, and only to subscribers who have English set as their preference? If that's the case, then I think we're OK.
- However if not, then I think we need to get this page translated in French / German too (which seem to be the only other languages KiP is available in). We could then pass the page language along with the subscription.

Apologies I did not catch this earlier. I didn't realize the newsletter was available in anything other than English.

**Comment by enavajas** [comment]
Hi @alexgibson - I met with Brad L. who has taken over the page now that Juliana has departed.

The email is only sent in EN, so we are good to leave as is 🙂 Thank you!

**Comment by enavajas** [comment]
Thank you! We may receive a request in a few weeks (post code freeze thawing) to do a similar thing with Firefox News, but they are still aligning and deciding on that. I will let you know if/when that comes up.

Thank you again!!
