### ISSUE TITLE
Refresh: New header navigation

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14827]
[Details are in this Figma file.](https://www.figma.com/design/mYHdNFy9RyswvKRWzEK6wH/%F0%9F%9A%A7-MVP-mozilla.org-updates?node-id=0-1&t=ntGdhSogMey0VErw-0)

Build behind a switch prefixed with `M24-`.

**Comment by stephaniehobson** [comment]
Update: please use the full wordmark on the mobile menu (see the Figma file for details)

**Comment by stephaniehobson** [comment]
Update: we are going to use white drop down menus in light mode. Just noting the decision for future posterity. Wen is already on it 🏃‍♀️

**Comment by alexgibson** [comment]
Depends on:

- https://github.com/mozilla/bedrock/issues/15154
- https://github.com/mozilla/bedrock/issues/15155
- https://github.com/mozilla/bedrock/issues/15156
