### ISSUE TITLE
Refresh: New footer navigation

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14830]
[Details are in this Figma file.](https://www.figma.com/design/mYHdNFy9RyswvKRWzEK6wH/%F0%9F%9A%A7-MVP-mozilla.org-updates?node-id=0-1&t=ntGdhSogMey0VErw-0)

Build behind a switch prefixed with `M24-`.

**Comment by stephaniehobson** [comment]
Update to the social media section. We should keep the same icons and accounts we use currently:

![Screenshot 2024-09-05 at 16 03 47](https://github.com/user-attachments/assets/f4abb096-66d5-47d8-8f1e-adbd590b09ad)

**Comment by wen-2018** [comment]
> Update to the social media section. We should keep the same icons and accounts we use currently:
> 

We are good here 👍   I have used the same social media links we currently have

**Comment by stephaniehobson** [comment]
Now that I am seeing the Figma design in a browser there are a few accessibility concerns with the design we should address:

- [ ] newsletter form input focus states are not visible
- [ ] links should have a hit area a minimum of 44px 
- [ ] tab order should match visual display order
- [ ] text in the `moz24-footer-secondary` element is too small

**Comment by stephaniehobson** [comment]
Calling this done and moving follow up work to #15427
