### ISSUE TITLE
Migrate VPN Resource Center to Wagtail

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14860]
## Description

Same as https://github.com/mozilla/bedrock/issues/14801 but for the [VPN Resource Center](https://www.mozilla.org/en-US/products/vpn/resource-center/). Localized content can hopefully be reused from Smartling.

---

#### Success Criteria
- [x] VPN Resource Center pages are migrated from Contentful to Wagtail CMS.

**Comment by stevejalim** [comment]
This one's gonna be interesting, as we already have the content. We could use it as an example of a data migration to load at least the `en-US` into the page tree, then trigger Smartling to show the workflow there

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/15350

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/15520

**Comment by alexgibson** [comment]
Last dependency has been resolved, closing as completed
