### ISSUE TITLE
Spin.js dependency throws `style-src-elem inline` CSP warning

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14873]
## Description

It looks like an old dependency we have, [spin.js](https://github.com/mozilla/bedrock/blob/main/media/js/libs/spin.min.js), violates `style-src-elem inline` CSP.

https://mozilla.sentry.io/share/issue/731d31b3e0a8411088056e46031c3906/

It looks like it's used in two places:

- https://github.com/mozilla/bedrock/blob/main/media/js/base/send-to-device.es6.js
- https://github.com/mozilla/bedrock/blob/main/media/js/newsletter/management.es6.js

I think we could remove it as a dependency, and create a simpler loading indicator of sorts.

---

#### Success Criteria
- [ ] spin.js is removed as a dependency

**Comment by janbrasna** [comment]
It should be CSP-compliant (or at least have an option to):
- https://github.com/fgnass/spin.js/pull/343

**Comment by janbrasna** [comment]
Removed `hwaccel` and `trail` options that would need describing otherwise. Besides that the API is the same. _(Will also need looking into the CSS animation definition that we may have to add somewhere.)_

But the upgrade sounds completely doable. Slowly looking into it…

**Comment by janbrasna** [comment]
But yea it's probably too overkill when you can just show/hide an SVG with all the keyframes already defined eg:

![spin](https://github.com/user-attachments/assets/cffc5afa-e58a-4d13-9f6e-4f5c33327493)

```svg
<svg viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg">
    <style>
    @keyframes spin {
      to {
        transform: rotate(360deg);
      }
    }
    @keyframes spin2 {
      0% {
        stroke-dasharray: 1, 800;
        stroke-dashoffset: 0;
      }
      50% {
        stroke-dasharray: 400, 400;
        stroke-dashoffset: -200px;
      }
      100% {
        stroke-dasharray: 800, 1;
        stroke-dashoffset: -800px;
      }
    }
    .spin2 {
      transform-origin: center;
      animation: spin2 1.5s ease-in-out infinite,
        spin 2s linear infinite;
      animation-direction: alternate;
    }
    </style>
    <circle class="spin2" cx="400" cy="400" fill="none"
      r="200" stroke-width="50" stroke="#E387FF"
      stroke-dasharray="700 1400"
      stroke-linecap="round" />
</svg>
```

**Comment by janbrasna** [comment]
FYI: The `spinner_color` passed around all the included `email_newsletter_form` instances is a no-op it seems — looking through the form includes, I can't seem to find the container for the spinner there. So unless I'm missing something, it's not even displayed while the form submits. The only place is really the newsletter management page.

**Comment by janbrasna** [comment]
For now I went with the smallest change surface keeping the original markup (as it is also used in tests etc.) and chose SVG+CSS via background in #14880

I will open the more meta `spinner_color` issue (more related to all `email_newsletter_form` instances than this) and will resolve that accordingly, here it is made a no-op as well, just using the setting always used for these forms.

**Comment by alexgibson** [comment]
> I will open the more meta spinner_color issue (more related to all email_newsletter_form instances than this) separately later, and will resolve that accordingly. Here it is made a no-op as well for now, just using the setting always used for these forms.

@janbrasna there's no need to open an issue for this I think. The spinner is no longer used in email forms, it was removed quite a long time ago. If there's any left-over code related to it then that can just be removed. Thanks

**Comment by janbrasna** [comment]
@alexgibson Alright, if it's not coming back it should just be removed from [all the macros and docs](https://github.com/search?q=repo%3Amozilla%2Fbedrock%20spinner_color&type=code) and the param completely removed from the helper. I'll comb through it at some point to wipe the leftovers 👍
