### ISSUE TITLE
CSP img error on /foundation/licensing/website-content/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14889]
## Description

The Creative Commons badge on the /foundation/licensing/website-content/ page does not load due to a CSP violation.

### Steps to reproduce

1. https://www.mozilla.org/en-US/foundation/licensing/website-content/

### Expected result

The Creative Commons [badge](https://mirrors.creativecommons.org/images/public/somerights20.gif) should be displayed.

### Actual result

The image is blocked due to a CSP violation. It looks like the image URL now forwards to `mirrors.creativecommons.org`.

We can probably just load this image directly from `/media`, rather than need to make a CSP exception for a third party domain for just a single image.

```
content-Security-Policy: The page’s settings blocked the loading of a resource (img-src) at https://mirrors.creativecommons.org/images/public/somerights20.gif because it violates the following directive: “img-src https://www.google-analytics.com/ https://www.googletagmanager.com/ https://images.ctfassets.net/ https://*.mozilla.org data: https://*.mozilla.com https://*.mozilla.net 'self' https://creativecommons.org/ https://mozilla.org/”
```

### Environment

Firefox Nightly
macOS

**Comment by janbrasna** [comment]
I understand you don't want to add a too lax wildcard `*.creativecommons.org` (as just `creativecommons.org` is already in the policy anyways), so it may be a candidate for removal entirely if its only goal was including the badge…

Regarding the badge, the old  ![cc](https://github.com/user-attachments/assets/029b96ba-bb24-4765-a9c1-4070c29cee6d) is somewhat too vague, there's maybe a better one with the actual license in it:

![ccbysa](https://github.com/user-attachments/assets/fc5bb40e-466d-463b-a1be-07d6275982fe)

or, if you ask me, I'd go for some of the newer style icons:

![cc](https://github.com/user-attachments/assets/f9d563ca-c728-478e-a7b0-35fb215a6bb4) ![by](https://github.com/user-attachments/assets/821d97cf-df48-4614-bc8d-aa7489dbaa22) ![sa](https://github.com/user-attachments/assets/6949869f-2288-4f78-b345-a2ab0a378aa6)

_(I will have to investigate their trademark/assets policies first though.)_

If this is the only occurrence, an inline SVG can be probably more effective than sending the hostname in all CSP headers for all the pages to begin with;)

(A quick fix for now would be adding the wildcard subdomain to the image policy.)
