### ISSUE TITLE
Update Email Service Provider in /privacy/websites

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#14894]
## Description

Acoustic has been replaced by Braze. I just noted that Acoustic is referenced in the "Things you should know" section on this page:

https://www.mozilla.org/en-US/privacy/websites/

**Comment by janbrasna** [comment]
This comes from [`@mozilla/legal-docs`](https://github.com/mozilla/legal-docs) — feel free to add this change to the list: https://github.com/mozilla/legal-docs/issues/1987

**Comment by alexgibson** [comment]
I don't seem to have powers to transfer this issue to legal-docs, but I'll do it manually 👍

**Comment by alexgibson** [comment]
Closing in favor of https://github.com/mozilla/legal-docs/issues/2124
