### ISSUE TITLE
Tools 404

### ISSUE THREAD

**Issue by foxtrotsc** [mozilla/bedrock#14908]
https://firefox-source-docs.mozilla.org/devtools-user/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=footer&utm_content=developers

**Comment by janbrasna** [comment]
@foxtrotsc Please watch https://bugzilla.mozilla.org/show_bug.cgi?id=1910530 for updates, nothing can be done about this here unfortunately.
