### ISSUE TITLE
Home for outdated locales interacts badly with donate banner

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14941]
## Description

Home "old" (for "slower" languages not having the home-new translated) shows the "Donate" banner under the footer, with close button non-functional.

### Steps to reproduce

https://www.mozilla.org/sco/

### Expected result

The Donate banner positioned somewhere with the content.

Also closing it ("Sneck") would work.

### Actual result

![Screenshot 2024-07-31 at 21 35 53](https://github.com/user-attachments/assets/a87a5dbc-6565-4031-b258-4c3ff3b2ca0c)

(these are supposed to be hidden on home-old, or should be made to work somehow? or this fidelity is expected and ok?)

**Comment by craigcook** [comment]
The include is repeated outside the switch: https://github.com/mozilla/bedrock/blob/main/bedrock/mozorg/templates/mozorg/home/home-old.html#L36
