### ISSUE TITLE
[GTM Review] Review GTM space "data-link-name"

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14940]
## One-line summary

Review and publish GTM workspace "data-link-name"

## Significant changes and points to review

All instances of `data-link-name` were removed from the code base in https://github.com/mozilla/bedrock/issues/14055. This GTM edit removes the trigger and Custom JavaScript variable that were helping smooth the transition from data-link-name to data-link-text.

## Issue

Issue: #14055
Supporting bedrock changes: #14057

## Testing

- find an element with `data-link-text`
- click it
- make sure `link_click` still fires (hint: all the navigation menu items should have that attribute)

**Comment by alexgibson** [comment]
Approved in GTM (I'll leave it to you to publish).
