### ISSUE TITLE
FXDE in-product pages include navbar

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#14949]
When compared to **release/beta**:
https://www-dev.allizom.org/en-CA/firefox/127.0/whatsnew/
https://www-dev.allizom.org/en-CA/firefox/126.0beta/whatsnew/
and **nightly**:
https://www-dev.allizom.org/en-US/firefox/80.0a1/whatsnew/

the WNPs and firstrun for **aurora/developer** currently start with the common layout masthead:
https://www-dev.allizom.org/en-US/firefox/102.0a2/whatsnew/
https://www-dev.allizom.org/en-US/firefox/92.0a2/whatsnew/
https://www-dev.allizom.org/en-US/firefox/83.0a2/firstrun/

(comparison aurora–beta:)
![Screenshot 2024-08-01 at 15 07 34](https://github.com/user-attachments/assets/fc702596-d03f-4670-b40d-40535ca20e32)
(whatsnew aurora × nightly:)
![Screenshot 2024-08-01 at 14 54 17](https://github.com/user-attachments/assets/1a524bf4-bc2f-4866-92b9-d6cee4e44a7f)
(firstrun aurora × nightly:)
![Screenshot 2024-08-01 at 15 07 34](https://github.com/user-attachments/assets/3c4d53f4-ca4b-4690-97e2-c0c051f93cfb)

Is it intentional, or for consistency with other in-product pages this should also skip the masthead?

**Comment by janbrasna** [comment]
Why I'm raising this is that in #14936 this is being evened out for all channels in simplification, so the FXDX WNPs would also be header-less — therefore I've added the same treatment to its firstrun for consistency.

Unless the navigation is intentional, and I'll have to find a way to make the aurora in-product pages behave differently.

**Comment by stephaniehobson** [comment]
I don't think it was intentional, so we're good to make them all the same.
