### ISSUE TITLE
[GTM Review] Review and publish GTM workspace GA3 deletions

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14963]
## One-line summary

Review and publish GTM workspace GA3 deletions

## Significant changes and points to review

This version removes more variables, and one trigger only used by our GA3 setup. The GTM interface assures me none of these are in current use.

## Issue

Issue: #14749

**Comment by alexgibson** [comment]
Approved in GTM (I'll leave it to you to publish)
