### ISSUE TITLE
Add new campaign IDs to app store redirector

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15027]
## Description

- mzaonboardingemail-de
- mzaonboardingemail-fr
- mzaonboardingemail-es
- mzaonboardingemail-it
- mzaonboardingemail-nl
- mzaonboardingemail-pl

---

#### Success Criteria
- [x] URLs that auto redirect to app / play store using the campaign values above.

**Comment by alexgibson** [comment]
Prod URLS:

- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-de
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-fr
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-es
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-it
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-nl
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-pl

**Comment by alexgibson** [comment]
Prod URLS:

- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-de
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-fr
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-es
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-it
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-nl
- https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=mzaonboardingemail-pl

**Comment by enavajas** [comment]
**[Doc](https://docs.google.com/document/d/11Aa8JCyEXgVQum4I9ELmaiNE4sunTGk5VI8iURi4Z-Y/edit)** w/ corresponding QR codes for Marine.
