### ISSUE TITLE
Language selector on CMS pages is showing too many languages

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15037]
As we'll see when #14801 lands, there's currently a niggle where a page that intended for just one locale has all the other CMS-supported langages available in the language picker in the footer.

This may be a bug in the integration of the lang picker or it may just be that Wagtail is creating aliases of a the en-US page in all the other available locales and we don't want that.

Need investigation and is a blocker for turning on the CMS-backed leadership page in prod, so P2

**Comment by stevejalim** [comment]
cc @alexgibson for awareness

**Comment by janbrasna** [comment]
it's drawn from `translations` context that's being defined here on the render() for CMS pages:
https://github.com/mozilla/bedrock/blob/3e8f11ba370e70a08a38a476bf4801d52d9a1f3d/lib/l10n_utils/__init__.py#L160-L161

so it's patched as: https://github.com/mozilla/bedrock/blob/3e8f11ba370e70a08a38a476bf4801d52d9a1f3d/bedrock/cms/models/base.py#L46-L49

to get the translations from `get_translations()` — they must be coming wrong from it already.

**Comment by stevejalim** [comment]
yeah, poking around lightly i can see that my local build has other locale versions of the test page i intended to be in en-US only, but saved as draft.  So, two things there:

1) I didn't expect (or want) wagtail-loalize to auto-create versions of my test page in other locales - i would expect that only to happen if i hit 'translate this page', so that needs exploring - one that I will raise in the Wagtail Slack if I can't find docs about it

2) Looks like `get_translations` doesn't take into consideration whether a page is live or not:

https://github.com/wagtail/wagtail/blob/4af8ab528bc4439a3deb50b30d61324eb18871ed/wagtail/models/i18n.py#L287-L298

so we might be able to change this:
```diff
-      request._locales_available_via_cms = [self.locale.language_code] + [x.locale.language_code for x in self.get_translations()] 
+      request._locales_available_via_cms = [self.locale.language_code] + [x.locale.language_code for x in self.get_translations().live()]
```

**Comment by stevejalim** [comment]
@alexgibson I'd hold off merging (or at least trying to set up) #14801 till this is done in case we need to replumb anything

**Comment by stevejalim** [comment]
Moving the auto-creation of alias pages to a separate ticket
