### ISSUE TITLE
Download tests are failing after refactor of /all/

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15041]
See https://github.com/mozilla/bedrock/actions/runs/10634008214/job/29480387534

**Comment by robhudson** [comment]
The issue:

The download tests scan the HTML of the /firefox/all page looking for download URLs, which it then does a HEAD check against to verify that we're not providing any dead links to download Firefox.

But after the refactor, the /firefox/all/ page does not have any download URLs, only URLs to drill down to select the type of download the user wants based on product, platform, and language. So the test finds no download URLs and fails.

These need to be re-written to fetch the download URLs from the various edge pages, possibly traversing all variations provided in the HTML. And then ensuring that the download URLs are valid.
