### ISSUE TITLE
Make Firefox ESR 115 available on the /firefox/all page alongside the latest (and sometimes next) ESR release 

### ISSUE THREAD

**Issue by drubino-mozilla** [mozilla/bedrock#15083]
To continue to offer supported updates for Windows 7-8.1 and macOS 10.12-14 users, we are extending support for ESR 115 for 6 months, and this support could be extended again indefinitely. This means we need to offer, for now, a means of downloading ESR 115 even as ESR 128 becomes the latest ESR channel, and beyond that when ESR 140 becomes the next ESR channel for a 3 month transition period next year. 

I am open to any UX for this offering, but one suggestion is to modify the offering on the /firefox/all/desktop-esr pages. (For example, https://www.mozilla.org/en-US/firefox/all/desktop-esr/win64/en-US/). 

Currently these pages have two versions... for 9 months out of the year, when esr-latest and esr-next are the same, they offer a single ESR download, and for 3 months out of the year during transition, when esr-latest and esr-next are not the same, they offer both ESR downloads. The copy accompanying each version explains the current situation. 

The modification would be to offer the esr115-latest on both versions of this page, and make appropriate updates to the copy to explain both situations. This would mean that 9 months out of the year we're offering two ESR channels, and 3 months out of the year we're offering three ESR channels. 

The above is just an implementation suggestion. There certainly are other sensible approaches.

**Comment by alexgibson** [comment]
Note that for the regular Firefox download flow (e.g. /firefox/new/) we will be pinning ESR 115 for unsupported OS users in https://github.com/mozilla/bedrock/issues/13753

**Comment by alexgibson** [comment]
@drubino-mozilla do you have a suggested piece of copy you would like to use for this?

Would this work perhaps?

`Note: If you are using Windows 7, Windows 8, Windows 8.1, or macOS 10.12, 10.13 or 10.14, then please download ESR 115 in order to use Firefox.`

**Comment by alexgibson** [comment]
Proposed UI:

![image](https://github.com/user-attachments/assets/1d2d6462-483f-4f96-95b6-588c47971002)

**Comment by drubino-mozilla** [comment]
Sorry for the delay. That looks great. Is this future-proof for if we get to the time where we offer 128 and 140, but 115 is still around? And it will show this way for each of the applicable desktop-esr paths (/win64, /win64-msi, /win, /win-msi, /osx) and not the non-applicable paths (win64-aarch64, linux64, /linux)?

-David

**Comment by alexgibson** [comment]
@drubino-mozilla hi, yes that's correct the ESR 115 copy and button will stick around until we decide to remove it, and will show up for relevant paths. I'll get this code reviewed next - thanks for taking a look!
