### ISSUE TITLE
DB exporter script fails when workflows are configured

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15084]
The DB export script excludes some models because they may contain sensitive info/PII and there is no need for that data to be in the sqlite export for local use.

One such model is `wagtail.TaskState`. However, once workflows are being used, the DB table for this is populated but not exported - and this breaks the export process when filling up the export DB, because another table (`wagtail.WorkflowState`) references `TaskState`, which has no data so the foreign key to that table causes and `IntegrityError`.

Sentry: https://mozilla.sentry.io/issues/5805387252

----

Possible fixes
1.  Include `wagtail.TaskState` but purge the `comment` column which may contain sensitive info

or

2. Just don't include `wagtail.WorkflowState` either -- this would mean local builds don't get a copy of the state a page was in, but that's generally going to be fine, I think

**Comment by pmac** [comment]
I'm cool with either of these directions. Go with whichever you prefer. Thanks!
