### ISSUE TITLE
1 click subscribe LP for Firefox News 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15142]
Hi. This is similar to a request we received a few months ago (https://github.com/mozilla/bedrock/issues/14823).

This time, they would like the same flow with a new landing page that allows prior subscribers of the _Security and Privacy (S&P)_ newsletter to join the _Firefox News_ newsletter in one-click. 

They are requesting this to be in FR and DE.

The design and layout can be the same as the one in the previous ticket referenced. 

The timeline is flexible. 

The copy docs with localized strings are below: 
[- DE ](https://docs.google.com/spreadsheets/d/1mM1H65Ph6dFAQCkQsv-LhWAsHgvnOv50vUPiaF4P0To/edit?gid=2048776457#gid=2048776457)
[- FR](https://docs.google.com/spreadsheets/d/1__IbP_pPrGgGa-Ac7ETj0NmAzRwiCqRLv0X250R047M/edit?gid=844373989#gid=844373989)

Thank you. Please let me know if there are any questions or concerns.

**Comment by alexgibson** [comment]
@enavajas the copy docs you linked to look like they are for the emails, and not the landing page itself. Do they have any specific copy in mind for the page?

**Comment by enavajas** [comment]
Hi @alexgibson – Using the image below from a prior newsletter LP as a guide, please  see the copy below for the landing page itself: 

- Headline: Stay connected with Mozilla, courtesy of our Firefox News newsletter 
- Sub-Headline: By subscribing, you’ll receive the latest product updates, expert tips, and important news from Mozilla—ensuring you stay safe and informed online. 
- Form: All stays the same, except the copy under the button should read Firefox instead of Mozilla, as follows:  `We will only send you Firefox-related information. You can unsubscribe at any time. `

<img width="988" alt="Screenshot 2024-09-23 at 9 10 25 AM" src="https://github.com/user-attachments/assets/bd0117a9-5c6a-4676-a206-cf329359e378">

**Comment by alexgibson** [comment]
@enavajas the page features only a single "one click to subscribe" buttton, not a full email form like shown above. This is what I have based in the copy so far. Does this work OK? We'll need German and French translations for this as well if we are to handle DR/FR.

![image](https://github.com/user-attachments/assets/d514a65a-e661-4737-836f-7edccf6ea494)

After clicking subscribe:

![image](https://github.com/user-attachments/assets/5bf8754d-0971-4df3-adf9-e9e2d115c05d)

**Comment by alexgibson** [comment]
@enavajas Hi, I've cobbled together the following copy. Can you please get someone to verify this reads OK, especially for French and German?

English:

Headline: "Stay connected with Mozilla, courtesy of our Firefox News newsletter"
Tagline: "By subscribing, you’ll receive the latest product updates, expert tips, and important news from Mozilla—ensuring you stay safe and informed online."
CTA: "Subscribe"
Thanks message: "Thanks for Subscribing! Your newsletter subscription has been confirmed."

German:

Headline: "Bleib mit Mozilla über unseren Firefox News-Newsletter auf dem Laufenden"
Tagline: "Wenn du abonnierst, erhältst du aktuelle Produkt-Updates, Expert*innentipps und wichtige News von Mozilla."
CTA: "Abonnieren"
Thanks message: "Danke, dass Sie den Newsletter abonniert haben! Ihr Newsletter-Abonnement wurde bestätigt."

French:

Headline: "Restez en lien avec Mozilla grâce à la newsletter Firefox News"
Tagline: "En vous abonnant, vous recevrez les dernières mises à jour de nos produits, des conseils d’experts et des actualités importantes concernant Mozilla."
CTA: "Abonnement"
Thanks message: "Merci pour votre inscription ! Votre inscription à la lettre d’information est maintenant confirmée."

**Comment by enavajas** [comment]
Hi Alex,

Below is the confirmed final copy for FR and DE. Please let me know if you
have any questions. Thank you.

FR:

- Headline: "Restez en lien avec Mozilla grâce à la newsletter Firefox News"

- Tagline: "En vous abonnant, vous recevrez les dernières mises à jour de
nos produits, des conseils d’experts et des actualités importantes
concernant Mozilla."

- CTA: “Je m'abonne"

- Thanks message: "Merci pour votre inscription ! Votre abonnement à la
newsletter Firefox News est maintenant confirmé."

DE:

- Headline: "Bleib mit Mozilla über unseren Firefox News-Newsletter auf dem
Laufenden"

- Tagline: "Wenn du abonnierst, erhältst du aktuelle Produkt-Updates,
Expert*innentipps und wichtige News von Mozilla."

- CTA: "Abonnieren"

- Thanks message: "Danke, dass Sie den Newsletter abonniert haben! Ihr
Newsletter-Abonnement wurde bestätigt."

**Comment by enavajas** [comment]
Hi @alexgibson  – There is one minor update we received from the EU LCM team that we should make prior to launch:

In the DE version, the following should be changed in the "Tagline" section:

- [ ] "Expert*innentipps" should be replaced with "Expert:innentipps"

The change is simply switching out the asterisk (*) with a colon (:). 

Once this update is made, this is good to go live. Thanks so much!
