### ISSUE TITLE
New MVP footer has `<hr>` element adding extra space

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#15152]
## Description
The new MVP footer's pixelated design is only available on the `home` and `about` pages. However, on other pages that don't have it, there's an extra space from a leftover `<hr>` element

### Steps to reproduce
- Go to a random page that isn't the `home` or `about` page (i.e. http://localhost:8000/en-US/advertising/)
- Scroll all the way to the bottom of the page
- Notice a grey horizontal line (`<hr>`) that's floating above the black footer with extra spacing above and below it.

### Expected result

No `<hr>` element or space around it:

<kbd>![Screenshot 2024-09-16 at 4 19 03 PM](https://github.com/user-attachments/assets/9fb75afa-7546-4e2a-be3b-9e28db5e2607)</kbd>

### Actual result

An `<hr>` element with space around it:
<kbd>![Screenshot 2024-09-16 at 4 15 27 PM](https://github.com/user-attachments/assets/6eb8ec11-5695-48c7-8b39-09ca474d496e)</kbd>

What happened.

### Environment
MacOS Sonoma 14.6.1, Firefox 130.0

**Comment by stephaniehobson** [comment]
I think the right thing to do here is to add the styles that transform the hr into the pixelated line. I think that means adding them to the footer's CSS files.

**Comment by janbrasna** [comment]
I have tried adding the transition divider styling everywhere in #15194, but… some pages that end with colour shapes don't work well with that, like:

> ![Screenshot 2024-09-22 at 19 10 59](https://github.com/user-attachments/assets/d9957171-d6d5-4fd6-a09a-020fa2f9fbc0)

> ![Screenshot 2024-09-22 at 17 45 17](https://github.com/user-attachments/assets/cec31b20-b6d3-45d2-b690-316a9024b3a1)

> ![Screenshot 2024-09-22 at 19 24 32](https://github.com/user-attachments/assets/fa55c1de-cd74-4166-8678-c90b673e1849)

Hiding the hr for now with low specificity `.m24-c-transition * { display: none; }` _(that's only effective until the proper declaration is loaded)_ looks perhaps better — but that doesn't solve the issue once 2024 styles are turned on site-wide — when that divider gets styled globally and places with somewhat rectangular blocks ending the pages will display like this anyway…
