### ISSUE TITLE
[refresh] Navigation close button is half way off screen when focus is received

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15156]
## Description

On desktop, when trying to use the new navigation using keyboard, the menu close button is not displayed correctly.

### Steps to reproduce

1. On desktop open https://www-dev.allizom.org/en-US/.
2. Using keyboard, tab through to "Firefox Browsers" in the navigation menu and press enter.
3. Press tab again.

### Expected result

Focus should move to the menu close button, which should be clearly presented.

### Actual result

The close button is floated half way off screen.

<img width="688" alt="image" src="https://github.com/user-attachments/assets/297f4a34-3adf-4962-8b58-4b235f7c0a05">

It should be placed within the menu where it is clearly visible. Having it displayed always would also be beneficial for visitors on touch devices. 

### Environment

Firefox
macOS

**Comment by stephaniehobson** [comment]
Design suggestion:

![Image](https://github.com/user-attachments/assets/6ffc1601-952e-43e5-822f-b9981521a3ad)
