### ISSUE TITLE
[M24] Submenu hidden under nav on mobile

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#15169]
## Description

In mobile layouts (portrait and landscape), pages with submenu have the subnav component hidden under the new masthead:

![Screen Shot 2024-09-17 at 18 09 47](https://github.com/user-attachments/assets/20fad57b-237f-4949-9b3a-865656f9aa4c)

### Steps to reproduce

Open https://www-dev.allizom.org/en-US/firefox/new/ in mobile viewports.

(Reproduces in desktop Responsive Design Mode too.)

### Expected result

Submenu reachable, placed after the main nav.

### Actual result

Submenu hidden under the nav:

https://github.com/user-attachments/assets/10b5aaa4-bebe-4633-83f6-8c997241236e

### Environment

Mobile Safari 15–17, FxiOS (+Focus iOS)

**Comment by alexgibson** [comment]
Possible duplicate issue: https://github.com/mozilla/bedrock/issues/15214

**Comment by wen-2018** [comment]
This has been fixed by https://github.com/mozilla/bedrock/pull/15215
