### ISSUE TITLE
Moments Page - Root Certificate Expiration - 1 of 6 | Oct 2024 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15162]
Hello. We need to make a series of three moments pages to alert users of a root certificate expiration.

The first of three moments pages will launch on **Oct 9th.** The dates of the other two are still being decided, along with the final copy and designs for those as well. Let's just focus on the first one for now. 

This needs to be in xx different locales. We are waiting for the translated strings. I will share those as soon as I have them, which should be in a couple of days. 

The final figma file is [here](https://www.figma.com/design/qxwVpxJJTpc8OsylbN7S95/Root-Certificate-Succession?node-id=7-1627&node-type=frame&t=ANKFJ2PsycOVrs8z-0). The translated strings are located [here](https://docs.google.com/document/d/1tm0w48iubriqiPzFUeM9IBtDfdorV4GRMMtZRa-r3tQ/edit). 

Please let me know if you have any questions. Thank you.

**Comment by enavajas** [comment]
@reemhamz the copy doc has been updated w/ all translated strings, so it is ready whenever you are :) thank you!

**Comment by reemhamz** [comment]
I need a bit more clarification -- the Figma file shows 6 different moments pages to be created, and they're separated in to 2 sections: one for v101 and lower, and v102 and higher. 

Should I be developing the October 9th moments page for users with Firefox v101 and lower? Or do all the moments pages that we're going to be releasing cater to all Firefox versions currently released?

**Comment by cpeterso** [comment]
> Should I be developing the October 9th moments page for users with Firefox v101 and lower? Or do all the moments pages that we're going to be releasing cater to all Firefox versions currently released?

@reemhamz - We'd like to build all six versions of the moments page now, so we can publish the pages all at once. When the future release dates arrive, we'll just need to update Remote Settings to point to the existing pages. We don't want to pester you with the overhead of six separate requests.

**Comment by reemhamz** [comment]
@cpeterso from my understanding, copy and design aren't finalized for the rest just yet (based on the PR info above)? Even if design is ready, are we also hard-coding the rest of the moments pages in 15 languages? I won't be able to finish developing them until everything is finalized, however I can keep them all in draft PRs for now while the final touches are coming in.

Also, regarding my question above, will I need to show different pages for folks with different Firefox versions?

Also cc @enavajas can you confirm we should be building all 6 pages and not 3?

**Comment by enavajas** [comment]
Hi @reemhamz – I spoke with @cpeterso just now to clarify and confirm. The TL;DR is:

- Since our team only received the request for the three moments pages (Oct 9, Dec 16, Jan 10), that is what we will be going with this first one on October 9th. Nothing else is changing for this one. For the design, please refer to the first design on the top left titled _"Moments Page MA1 Shown Oct 9, 2024"._ 
- I confirmed that we are just building the pages – they will take care of the Firefox version targeting in their Remote Settings configuration. They just need all the pages to have unique URLs.
- Lastly, I was able to get an updated SVG file of the `lighting fast` icon exported (a bit modified, but that is ok, it will be replaced in the figma to match. I have attached it below. 
![image (15)](https://github.com/user-attachments/assets/6b167702-ba87-4f20-aa49-d873b565b3a5)

Please let me know if you have any questions. 
________________________
### FOR FUTURE PAGES BEYOND OCTOBER 9TH

Due to the importance of this event, we will be increasing the scope of this work to include three more pages, for a total of six Moments pages. The updated release schedule is below:

- x2 pages on Dec 10, 2024 _(for different fx versions)_
- x1 page on Jan 9, 2025
- x1 page Feb 5, 2025
- x1 March 11, 2025

However, this is simply a note for future reference. Additional issues will be made for these other pages with the corresponding assets.

**Comment by reemhamz** [comment]
This clarification totally helped, thank you both!
P.S. that new SVG did the track 🎉

**Comment by enavajas** [comment]
Hi @reemhamz – Can you please put this on a demo server for their review? Thank you

**Comment by reemhamz** [comment]
@enavajas here's the demo server link w/ a list of locales:

- [ ] https://www-demo6.allizom.org/en-US/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/de/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/fr/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/es-ES/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/et/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/el/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/pl/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/cs/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/zh-CN/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/pt-BR/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/ar/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/ru/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/ja/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/id/firefox/welcome/19/
- [ ] https://www-demo6.allizom.org/hu/firefox/welcome/19/

**Comment by enavajas** [comment]
Awesome, thank you

**Comment by reemhamz** [comment]
@enavajas let me know if the team has any updates or requests they'd like me to work on. Otherwise, Craig's approved the PR so it should be good for launch 👍🏼

**Comment by cpeterso** [comment]
@reemhamz Thanks! I'll ask our designer to review these pages.

**Comment by enavajas** [comment]
Confirmed that we are good to launch these on Oct 9. Thanks all.

**Comment by enavajas** [comment]
Hello. We have a late-breaking update that was just requested regarding the CTA links for this page:

- [ ] For ESR builds, the CTA should link to `https://www.mozilla.org/en-US/firefox/enterprise/#download`
- [ ] For Release builds, the CTA should link to `https://www.mozilla.org/en-US/firefox/download/thanks/`

Thank you.

**Comment by cpeterso** [comment]
Note that the URLs should NOT include a locale (like `en-US` in the example URLs above). We want the website to automatically redirect to a translated page that is appropriate for the visitor's locale:

* For ESR builds, the CTA should link to `https://www.mozilla.org/firefox/enterprise/#download`
* For Release builds, the CTA should link to `https://www.mozilla.org/firefox/download/thanks/`

**Comment by reemhamz** [comment]
Howdy -- the demo has been updated to reflect the latest changes! 
https://www-demo6.allizom.org/en-US/firefox/welcome/19/

❗  When testing in an ESR browser, make sure UITour is enabled. Follow the steps here: **https://bedrock.readthedocs.io/en/latest/uitour.html#local-development**

**Comment by reemhamz** [comment]
Re-opening as we have 5 more pages to add for this to be 100% completed
