### ISSUE TITLE
[M24] Navigation hidden behind app-store-banner

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#15172]
## Description

When app store banner is displayed, it covers the new masthead and/or subnav:

> ![IMG_0992](https://github.com/user-attachments/assets/a5cc28da-8b40-4efc-9719-4fc7dca59840)

### Steps to reproduce

Open https://www-dev.allizom.org/en in browsers matching `isMobile && !isFirefox`, e.g. Mobile Safari.

### Expected result

Banner doesn't cover header nav.

### Actual result

https://github.com/user-attachments/assets/99096189-9bb5-42ea-b1bc-964aded83de4

### Environment

Safari iOS 17.6.1

**Comment by wen-2018** [comment]
This should have been fixed by: https://github.com/mozilla/bedrock/pull/15215

**Comment by wen-2018** [comment]
This should have been fixed by: https://github.com/mozilla/bedrock/pull/15215
