### ISSUE TITLE
Nightly update message should refer to Firefox Labs instead of Nightly Experiments

### ISSUE THREAD

**Issue by gijsk** [mozilla/bedrock#15187]
## Description

The [message](https://github.com/mozilla/bedrock/blob/bb03d1779b885d8e56e3ff51e6ea95473e1c7c08/l10n/en/firefox/nightly/whatsnew.ftl#L27) right now is:

```
nightly-whatsnew-want-to-know-which-v2 = Want to know which platform features you could test on { -brand-name-nightly } and can’t see yet on other { -brand-name-firefox } channels? Then have a look at the <a { $attrs }>Nightly Experiments</a> preferences page.
```

We renamed Nightly Experiments to Firefox Labs in 130. The whats new page should use the new name.

**Comment by gijsk** [comment]
(We may also wish to alter the wording as different items are available on different channels but the page as a whole is available on release.)

**Comment by janbrasna** [comment]
@gijsk Do you have any other wording updates you'd like to include?

Any change to this string will go to the l10n community triggering new translations, so if you'd like to see any other tweaks to the string, it's sensible to push them all in one changeset.

**Comment by janbrasna** [comment]
This is live now: https://www.mozilla.org/en/firefox/111.1a1/whatsnew/ and translations (esp. when pre-translation machinery/memory kicks in) are already being added, too:
- https://www.mozilla.org/no/firefox/111.1a1/whatsnew/
- https://www.mozilla.org/it/firefox/111.1a1/whatsnew/
- https://www.mozilla.org/cs/firefox/111.1a1/whatsnew/
- https://www.mozilla.org/pt/firefox/111.1a1/whatsnew/

**Comment by janbrasna** [comment]
This has been updated in most of the active locales, and those who are not exactly active seem to be getting this paragraph in default English anyways /and the actual fallback string is already expired so it's marked for deletion in the next wave/ so all variants should only refer to "Firefox Labs" now — @gijsk @pascalchevrel feel free to close as completed if you're happy with the current output.
