### ISSUE TITLE
Nightly update message should remove mentions of Mastodon

### ISSUE THREAD

**Issue by grahamalama** [mozilla/bedrock#15188]
## Description

The [message](https://github.com/mozilla/bedrock/blob/bb03d1779b885d8e56e3ff51e6ea95473e1c7c08/l10n/en/firefox/nightly/whatsnew.ftl#L23) right now is:

```
nightly-whatsnew-if-you-want-to-v3 = If you want to know what’s happening around { -brand-name-nightly } and its community, reading our <a { $blog }>blog</a> and following us on <a { $mastodon }>Mastodon</a> or <a { $twitter }>X</a> are good starting points!
```

Since Mozilla is [winding down mozilla.social](https://mozilla.social/@mozilla/113153943609185249), unless we have another presence on Mastodon, we should remove mention of it here.

**Comment by janbrasna** [comment]
The instance is shutting down, but I believe all the accounts will be migrated elsewhere, perhaps back to mastodon.social where some of the og handles still are?

So once https://mozilla.social/@FirefoxNightly has a new home, it would be easy to update the WNP link. _(It's easier to update the URL than to change the string given it triggers new translations from the l10n community.)_

Actually all the mozilla.social URLs around the site will need to be updated once their new fediverse location is decided. 🤷

**Comment by pascalchevrel** [comment]
Jan's analysis is correct, we have no intention to abandon our presence on Mastodon, we are just closing our own Mastodon instance. We will migrate our firefoxnightly account probably early December and will just update the url on the pages where it is mentioned.

**Comment by reemhamz** [comment]
Based on the discussion above, I'll close this issue. We can create a new issue to update the Mastodon URLs across the website once the instance shuts down in December. The current link to the instance we have has context for why we're shutting it down if a new user chooses to look up Moz Social.
