### ISSUE TITLE
[M24] New base bundle doesn't include rebrand logic for old footer

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#15206]
## Description

Even after switching to the 2024 base stylesheet, the old nav & footer is still being used (basically because it's an independent switch, but even that shows it only for default locale or progressively only to locales based on its ftl activation threshold / translation completion), so to avoid unexpected changes between various switch combinations being flipped, even the new base stylesheet should support both old and new brand based on its switch/class.

### Steps to reproduce

With all refresh switches flipped, visit some non-en page, e.g. http://localhost:8000/cy/ or http://localhost:8000/sco/?xv=legacy — these will display the og elements that will continue to be served for parts of the site.

### Expected result

New logo in both old nav & footer.

### Actual result

> ![Screenshot 2024-09-22 at 18 53 32](https://github.com/user-attachments/assets/0e367cfb-1298-4439-b258-b1a434c8c3ef)

Header links proper img based on the switch. Footer only adds class based on the switch, so the declaration for .m24-logo needs to set the correct asset explicitly.

### Environment

All the switches enabled.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/15120

**Comment by janbrasna** [comment]
@alexgibson I **_think_** this was actually started with #15144 (base-protocol-2024.scss) — so this only follows up (monkey-patching the same temp overrides supporting the m24-logo switch in all the bundle variants:/…) — feel free to supersede it once there's a better fix.
