### ISSUE TITLE
Add new app store button links for EU Built for You campaign pages 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15203]
We received a request to do the following for the DE and FR campaign [Built for You. ](https://www.mozilla.org/de/firefox/built-for-you/)

Please add the following links to the app store buttons to mobile:

- [ ] [iOS DE campaign store](https://apps.apple.com/app/firefox-private-safe-browser/id989804926?ppid=721e328c-8a9e-4a2f-9785-febc1563f4e1)
- [ ] [iOS FR campaign store](https://apps.apple.com/app/firefox-private-safe-browser/id989804926?ppid=4a5a3315-553e-4bbd-ac61-2f1e001c0fdc)
- [ ] [PlayStore DE](https://play.google.com/store/apps/details?id=org.mozilla.firefox&listing=built-for-you-de)
- [ ] [PlayStore FR](https://play.google.com/store/apps/details?id=org.mozilla.firefox&listing=built-for-you-fr)

Also,

- [ ] Please confirm that the `built-for-you` campaign tag is visible for this campaign on both Andorid and iOs. 

Thank you!

**Comment by alexgibson** [comment]
@enavajas pushed this to a demo. Please can we get them to test the new links, and make sure they can see the data they expect? Thanks

- https://www-demo1.allizom.org/de/firefox/built-for-you/
- https://www-demo1.allizom.org/fr/firefox/built-for-you/
