### ISSUE TITLE
Release Mozilla Sans and Mozilla Semi Slab on their own?

### ISSUE THREAD

**Issue by nclm** [mozilla/bedrock#15217]
Hi :)

Mostly a question, cannot find where else to ask.

Do you plan to release Mozilla Sans and Mozilla Semi Slab on their own?

I see you have them in https://github.com/mozilla/bedrock/tree/main/media/fonts/m24 but shouldn’t they have their own repo like https://github.com/mozilla/zilla-slab and https://github.com/mozilla/Fira have?

Another question is what license do they have? This repository is MPL, but I’m guessing the fonts themselves might be OFL maybe? This isn’t clear in the current state.

Thanks!

**Comment by alexgibson** [comment]
Hi @nclm,

Thanks for filing this issue! Yes we will be releasing the fonts in their own respective GitHub repository soon, once they are final. When that happens they will use an OFL. The files in bedrock right now are still only for testing purposes, so are not quite ready to use more widely just yet.

Thank you for asking!

**Comment by nclm** [comment]
Thanks looking forward, they look like nice typefaces!

**Comment by stephaniehobson** [comment]
The beta versions of the fonts have been released in their own repo. https://github.com/mozilla/mozilla-type-family/releases

Original source files aren't there right now but should be added with the 1.0 release.
