### ISSUE TITLE
[nothing personal] Add newsletter form

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15218]
## Description

- Ask is to add a newsletter form to the bottom of this page: https://www.mozilla.org/en-US/firefox/nothing-personal/
- Include a page anchor link that will enable linking directly to the newsletter section.
- The sign-up form should have two check boxes – one for the Fx newsletter, another for opting in to receive college related news.

See the [brief here](https://docs.google.com/document/d/13xZqrLeQ2sKKlHzEjctmecDYS3aA9NEm565Y2NMw67M/edit?usp=sharing) for more details.

---

#### Success Criteria
- [ ] Landing page has signup form for Fx News / college related news.

**Comment by enavajas** [comment]
Hi Alex,

I checked with them, and they were wondering if we could remove the
language and region selectors since the landing page and campaign are for
EN US only. What do you think?

Also, the slug for the new newsletter in braze is:
nothing-personal-college-interest

Everything else is gucci. Thank you!!

**Comment by alexgibson** [comment]
@enavajas yes we can do that, updated here thanks:

![image](https://github.com/user-attachments/assets/54a15dbc-c96f-4259-839e-997c16b90413)

**Comment by alexgibson** [comment]
@enavajas I also pushed this up to a demo server if they wanted to test the signup flow: https://www-demo1.allizom.org/en-US/firefox/nothing-personal/

Let me know if they need anything else

**Comment by enavajas** [comment]
Hi @alexgibson – Legal has advised that an additional checkbox be added to the bottom of the form with the words:

`I am at least 18 years of age or older`

Is this something we can do?

**Comment by alexgibson** [comment]
@enavajas adding an extra checkbox might actually be a bit of work to do. Would it be possible to update the terms and conditions checkbox copy to accommodate this instead?
