### ISSUE TITLE
Leadership Page Update (w/ CMS) 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15238]
Hi. We have been asked to update [the leadership page](https://www.mozilla.org/en-US/about/leadership/) to add the following individual: 

- Girish Rao
- SVP of Infrastructure
- [Bio](https://docs.google.com/document/d/1HkTnr_pD3V3rFAZRgQJxBxw0Iv1A9Aujs60sx0wJ3hQ/edit?usp=sharing)
- [Headshot](https://drive.google.com/file/d/1Y0bRZAp7oVZD25DlZ6zGthpLAAHdL_9B/view?usp=sharing)

I will be taking care of this task in the CMS. This GH issue is for tracking and visibility purposes. 

cc @alexgibson @stevejalim

**Comment by craigcook** [comment]
This was done on 2 October 2024, ~1:30pm PT... not sure if we can reference a specific revision in Wagtail somehow? But it's live now.
