### ISSUE TITLE
H1 2024 Transparency Report

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15239]
Hello. It's that time of year again... Transparency Report Time!!! 

The main landing page where this content lives is https://www.mozilla.org/en-US/about/policy/transparency/

I have outlined the requested changes below:

- [x]  Change the text in this button to `January 1, 2024 to June 30, 2024`
<img width="1512" alt="Screenshot 2024-10-02 at 10 48 19 AM" src="https://github.com/user-attachments/assets/b1d9b948-15b8-4a30-9fb7-08c5a4502553">

- [x] Add the current report (living [here](https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2023/)) to the list of `Previous Reports`, and title it `July-Dec 2023`
- [x] Create a new page with the URL https://www.mozilla.org/en-US/about/policy/transparency/jan-june-2024/. The page should match the template of the previous one, but will have updated information.

**In the new page,**

- [x]  The subheading should be updated to` Reporting Period: January 1, 2024 to June 30, 2024`
<img width="804" alt="Screenshot 2024-10-02 at 11 03 49 AM" src="https://github.com/user-attachments/assets/19eb2a9e-5482-4950-9a1f-4a933500d1af">

- [x] Update the numbers in the _Government Demands for User Data_ section as follows (changes are highlighted in yellow): 
<img width="484" alt="Screenshot 2024-10-02 at 11 05 05 AM" src="https://github.com/user-attachments/assets/f2a877be-f222-4780-9216-789cb64ab312">

- [x] Update the numbers in the _Government Demands for Content Removal_ section as follows (changes are highlighted in yellow):
<img width="445" alt="Screenshot 2024-10-02 at 11 07 41 AM" src="https://github.com/user-attachments/assets/9a00e28d-9a3c-44b7-9780-94a5077069d1">

- [x] For the _Copyright and Trademark Requests_ section, add a section title of `Copyright and Trademark Requests.` 
- - [x] Then, update the section as follows (changes are highlighted in yellow):
<img width="716" alt="Screenshot 2024-10-02 at 11 08 40 AM" src="https://github.com/user-attachments/assets/e1179b3d-04b2-481f-9556-ac94dbe04bdd">

- [x] Update the _Legal Removal Requests By Companies or Individuals_ section as follows (changes are highlighted in yellow):
<img width="679" alt="Screenshot 2024-10-02 at 11 10 40 AM" src="https://github.com/user-attachments/assets/e6144a46-bf8a-4602-895a-c17bed888ac2">

- [x] Update the _Personal Data Requests_ section as follows (changes are highlighted in yellow):
<img width="691" alt="Screenshot 2024-10-02 at 11 11 32 AM" src="https://github.com/user-attachments/assets/10e5a57d-ec78-4fad-94bf-c4b9a932f145">

- [x] Update the _Targeted Advertising Disclosures_ section as follows (changes are highlighted in yellow):
<img width="688" alt="Screenshot 2024-10-02 at 11 12 08 AM" src="https://github.com/user-attachments/assets/69b035fe-4023-4482-9d50-127c640c9a4a">

- - [x] Then, for the two links, please create PDFs at an [assets.mozilla.net](https://www.google.com/url?q=http://assets.mozilla.net&sa=D&source=docs&ust=1727192347799095&usg=AOvVaw0HTPqFzf8JuQlpRH7HwuQk) location, and link to them as we have for prior ad disclosures in Transparency Reports. 

- [x] Update the _EU Monthly Active Users_ section as follows (changes are highlighted in yellow):
<img width="687" alt="Screenshot 2024-10-02 at 11 14 22 AM" src="https://github.com/user-attachments/assets/6159a140-bdb2-41fb-b0b6-83974a2db2cf">

- [x] Update the Policy Supplement section with the following new copy: 

> During the course of this reporting period, Mozilla continued its efforts to protect the security and privacy of our users through public policy. 

> In Europe, we published our[ policy recommendations for the new EU mandate](https://blog.mozilla.org/netpolicy/2024/07/17/mozillas-policy-vision-for-the-new-eu-mandate-advancing-openness-privacy-fair-competition-and-choice-for-all/) outlining our position on ensuring greater openness, privacy, fair competition, and meaningful choice online. We also[ contributed](https://blog.mozilla.org/netpolicy/2024/03/27/pathways-to-a-fairer-digital-world-shaping-eu-rules-to-increase-consumer-protection-and-choice-online/) to the EU’s process of evaluating consumer protection rules and emphasized that such rules should unequivocally incentivise the use and uptake of privacy-enhancing technologies to balance personalization and respect for privacy online. At the Computers, Privacy and Data Protection (CPDP) conference, we utilized the conference’s strong focus on privacy to organize a panel on[ accountability in AI](https://www.cpdpconferences.org/cpdp-panels/lifting-the-hood-on-big-ai-the-future-of-transparency-and-accountability-in-ai), highlighting the importance of transparency and responsibility in AI development.

> Building on our work in 2023, we continued to engage in a dialogue with the European Commission on the eIDAS legislation published in the official journal. We continued to monitor the implementation of  Article 45 to ensure encryption and web security are not weakened by restricting the independence of browser root store programs to apply strict cybersecurity requirements for website authentication.

> In the United States, we engaged in discussions on comprehensive federal privacy proposals, including the[ American Privacy Protection Act (APRA)](https://blog.mozilla.org/netpolicy/2024/04/26/work-gets-underway-on-a-new-federal-privacy-proposal/). We[ testified before Congress](https://blog.mozilla.org/en/mozilla/internet-policy/mozilla-urges-federal-privacy-law-for-ai-development/) on the need for a comprehensive federal privacy law to ensure the responsible development of AI. We also supported state privacy proposals modeled after the[ American Data Privacy Protection Act (ADPPA)](https://blog.mozilla.org/netpolicy/2024/01/11/mozilla-weighs-in-on-state-comprehensive-privacy-proposals/) to ensure individuals’ security and privacy on the Internet are fundamental and are not treated as optional. Additionally, we co-signed an[ amicus brief in the Nevada vs. Meta case](https://blog.mozilla.org/netpolicy/2024/03/12/nevada-e2ee-amicus/), defending end-to-end encryption to affirm our collective commitment to safeguarding encryption, digital privacy and security as fundamental rights. Through our efforts to protect[ net neutrality](https://www.fcc.gov/ecfs/document/1011790221057/1), we highlighted the privacy implications of weakening net neutrality[ in January's reply comments](https://www.fcc.gov/ecfs/document/1011790221057/1) to the FCC. 

> Globally, through the Global Encryption Coalition Steering Committee, we continue to collectively advocate for the protection of encryption against regulatory efforts that aim to weaken or undermine it. As a part of our collaborative efforts with GEC SC, we contributed to the following activities: We joined allies in signing a[ joint statement](https://www.globalencryption.org/2024/06/joint-statement-urging-australia-to-protect-end-to-end-encryption-in-the-online-safety-act-review/) urging Australia to protect end-to-end encryption in the Online Safety Act review. We also signed onto a letter outlining GEC’s[ concerns](https://www.globalencryption.org/2024/04/global-encryption-coalition-gec-sc-contribution-to-the-ongoing-discussions-at-the-uns-global-digital-compact/) about the Belgian Presidency's advocacy to use scanning technologies for encrypted messaging services to prevent CSAM, without addressing the security and fundamental rights concerns raised by experts. This statement was a follow-up of earlier GEC SC [comments ](https://www.globalencryption.org/2024/04/statement-of-the-global-encryption-coalitions-steering-committee-on-the-belgian-presidencys-compromise-proposal-on-eu-csam/)on the Belgian Presidency’s compromise proposal on EU CSAM. We supported a statement delivered as a part of the open consultations on the zero draft of the Global Digital Compact,[ articulating](https://www.globalencryption.org/wp-content/uploads/2024/04/Final_GEC-statement-on-the-GDC-Draft-Zero.pdf) the expert insights on protecting and extending the use of strong encryption to protect human rights. We also joined GEC SC in[ supporting](https://www.globalencryption.org/2024/05/global-encryption-coalition-steering-committee-statement-in-support-of-the-inclusion-of-encryption-as-a-right-for-every-person-in-chile/) the Chilean government’s inclusion of encryption as a right for every person in Chile through its[ Cybersecurity Law](https://www.bcn.cl/leychile/navegar?idNorma=1202434). In the UK, GEC SC [recommended](https://www.globalencryption.org/2024/02/comments-of-the-global-encryption-coalition-steering-committee-on-ofcoms/) that Ofcom removes E2EE as a risk factor within risk assessments and that the Ofcom guidance be revised. GEC SC also outlined [concerns](https://www.globalencryption.org/2024/02/global-encryption-coalition-steering-committee-statement-on-proposed-revisions-to-the-uks-investigatory-powers-act/) on proposed revisions to the UK’s Investigatory Powers Act where the Amendment Bill proposed changes that would interfere with the ability of providers to offer strong encryption in their products, which in turn would harm the security of users not just in the UK, but around the world. 

> The policy team played a strong role in supporting product teams to ensure privacy continues to be ingrained in our product offerings.  We supported our product teams in testing[ Privacy-Preserving Attribution (PPA)](https://blog.mozilla.org/netpolicy/2024/08/22/ppa-update/) designed to measure digital ad effectiveness without compromising user privacy. By using advanced cryptographic methods, PPA aggregates data to assess ad impact without tracking individual users, aligning with privacy regulations like GDPR. During the course of this reporting period, Mozilla continued its efforts to protect the security and privacy of our users through public policy.

- [x] Update the _Voluntary Threat Indicators & Data Disclosures_ section as follows (changes are highlighted in yellow):
<img width="464" alt="Screenshot 2024-10-02 at 11 16 18 AM" src="https://github.com/user-attachments/assets/407b782e-7b69-4ce5-9e32-6d1377ee1d0f">

Thank you!

**Comment by reemhamz** [comment]
Can I please get the 2 links mentioned in the Targeted Advertising Disclosures sectioned so I can upload them to assets.mozilla.net?

**Comment by reemhamz** [comment]
Also, in the following sentence under the Policy Supplement (paragraph #4):

> Through our efforts to protect[ net neutrality](https://www.fcc.gov/ecfs/document/1011790221057/1), we highlighted the privacy implications of weakening net neutrality[ in January's reply comments](https://www.fcc.gov/ecfs/document/1011790221057/1) to the FCC.

It seems both those hyperlinks are the same. Just want to double-check if this is intentional?

**Comment by enavajas** [comment]
Hi @reemhamz, please see below:

**Targeted Advertising Disclosures section links:**
- [Firefox EU Campaign](https://drive.google.com/file/d/1TAUNo4FBfbm8zd_zZgHFLX-TOok1zHru/view?usp=drive_link)
[FIrefox North America Campaign](https://drive.google.com/file/d/1FAfi7g8iBeQkkovYPoFWMW2IEsZ8Z9a_/view?usp=drive_link)

**Comment by reemhamz** [comment]
Here is the demo link: https://www-demo7.allizom.org/en-US/about/policy/transparency/jan-jun-2024/

**Comment by enavajas** [comment]
Thank you. For the section with the repeated same links, could we please
change the first time it shows up to the following one instead:
https://blog.mozilla.org/netpolicy/2024/04/26/net-neutrality-is-back/

Then I’ll send off the demo link. Thank you!

**Comment by reemhamz** [comment]
I updated the link and it's now reflected on the demo 👍🏼

**Comment by enavajas** [comment]
@reemhamz Confirmed that we are good to go live with this now. Thanks!
