### ISSUE TITLE
Decommission old VPN platform templates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15245]
## Description

We have a series of VPN platform-related articles that have both old and new versions. The latest versions were added over a year ago, and at this point the old templates are mostly just accruing technical debt, since they now serve only a very small number of languages. I also don't think the VPN product is available in countries where these languages are most common.

Need to check with Adria first to make sure we're OK to remove these, since they seem to be mostly SEO focused pages.

- https://www.mozilla.org/en-US/products/vpn/mobile/android/
    * Latest template total languages: 37
    * Old template total languages: 40
    * Languages that would be dropped: be,es-MX,sr 
      * Example: https://www.mozilla.org/es-MX/products/vpn/mobile/android/
* https://www.mozilla.org/en-US/products/vpn/desktop/
    * Latest template total languages: 37
    * Old template total languages: 39
    * Languages that would be dropped: es-MX,gn,lo,sr
      * Example: https://www.mozilla.org/es-MX/products/vpn/desktop/
* https://www.mozilla.org/en-US/products/vpn/mobile/ios/ 
    * Latest template total languages: 34
    * Old template total languages: 40
    * Languages that would be dropped: be,es-MX,fi,gn,lo,sr
      * Example: https://www.mozilla.org/es-MX/products/vpn/mobile/ios/
* https://www.mozilla.org/en-US/products/vpn/desktop/linux/ 
    * Latest template total languages: 36
    * Old template total languages: 39
    * Languages that would be dropped: es-MX,gn,lo,sr
      * Example: https://www.mozilla.org/es-MX/products/vpn/desktop/linux/ 
* https://www.mozilla.org/en-US/products/vpn/desktop/mac/ 
    * Latest template total languages: 34
    * Old template total languages: 39
    * Languages that would be dropped: es-MX,fi,gn,lo,rm,sr
      * Example: https://www.mozilla.org/es-MX/products/vpn/desktop/mac/ 
* https://www.mozilla.org/en-US/products/vpn/mobile/ 
    * Latest template total languages: 36
    * Old template total languages: 39
    * Languages that would be dropped: es-MX,lo,rm,sr
      * Example: https://www.mozilla.org/es-MX/products/vpn/mobile/ 
* https://www.mozilla.org/en-US/products/vpn/desktop/windows/ 
    * Latest template total languages: 34
    * Old template total languages: 41
    * Languages that would be dropped: be,es-MX,gn,lo,rm,sr,tr
      * Example: https://www.mozilla.org/es-MX/products/vpn/desktop/windows/ 

---

#### Success Criteria
- [ ] Old templates are removed from the codebase.

**Comment by alexgibson** [comment]
Issue where newer pages were added for reference: https://github.com/mozilla/bedrock/issues/13205

**Comment by a-kyne** [comment]
Conferred with @stephaniehobson and we should delete the old templates.
