### ISSUE TITLE
[Refresh] OG/social image logo poster needs refreshing

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#15248]
## Description

Currently only a small 256×256px JPG is being used as a social preview image: [`mozilla-256.jpg`](https://github.com/mozilla/bedrock/blob/cbf53a292f2b640ce3f5d58855c96dc2f5099b23/media/img/mozorg/mozilla-256.jpg)

![Screen Shot 2024-10-06 at 18 48 59](https://github.com/user-attachments/assets/5499c9fc-b5e8-4566-bead-c027532e79b9)

not exactly matching the usual dimensions or resolution expectations.

Once the refresh switch for logo is flipped, it will create a disparity between the preview and branding on the actual site.

---

#### Success Criteria
- [ ] Create a new poster image (preferably 1.91:1 1200×630px PNG?)
- [ ] Add that to base-protocol template behind m24-logo switch

**Comment by stephaniehobson** [comment]
Here's the asset for the new image. It needs to be behind a switch like everything else.

![og](https://github.com/user-attachments/assets/7c605bda-b91f-4fcd-b05a-56601506a68d)
