### ISSUE TITLE
[GTM Review] Review "Remove CJS" workspace 

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15259]
## One-line summary

Review and publish GTM workspace "Remove CJS"

## Significant changes and points to review

- remove 2 custom JS filters in favour of directly using attribute values

## Issue

Fix https://github.com/mozilla/bedrock/issues/13951
Fix https://github.com/mozilla/bedrock/issues/14054
See also https://github.com/mozilla/bedrock/issues/14749

Supporting bedrock changes:

https://github.com/mozilla/bedrock/pull/14910

## Testing

Shouldn't be much to do, GTM prevents deletion of stuff that's still in use. I suppose you could search that `data-link-group` is gone from the bedrock code? But Reem did a pretty through review of #14910

**Comment by alexgibson** [comment]
Approved and published
