### ISSUE TITLE
Experiment: Share Fx Mobile with a Friend

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15296]
Hello. We have received a request to run a multi-variant experiment with the aim of ascertaining which variant drives the most downloads and DAU. 

The two items required from our team are: 

- [ ] Add four campaign IDs `share1, share2, share3, share4 `to the allow list. 
- [x] Provide shortened versions of the following four links:

```
-https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=fxshare1
-https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=fxshare2
-https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=fxshare3
-https://www.mozilla.org/firefox/browsers/mobile/app/?product=firefox&campaign=fxshare4
```

I can provide the shortened URLs.

**Comment by enavajas** [comment]
The shortened links are below: 

1. fxshare1 = `https://mzl.la/3Nq9vqp`
2. fxshare2 = `https://mzl.la/4gYyZJb`
3. fxshare3 = `https://mzl.la/3Y3fQwV`
4. fxshare4 = `https://mzl.la/3Y3Eldf`

**Comment by pmac** [comment]
We've added `fxshare5`. Now we're adding `fxshare6` and `fxshare7`.
