### ISSUE TITLE
Refresh: Home - donate section tweaks

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15303]
Update component to match [the updated Figma](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1-4721&t=VaL6cYyET7hTTRRo-1).

The link should take you right to the component but if not it's under _Desktop Prototypes > Homepage V3_

**Comment by Ayushsunny** [comment]
Hi @stephaniehobson ,

I hope you’re doing well! I wanted to ask if I could take on the issue regarding the tweaks to the donate section. Please let me know if that’s okay!

Thank you!
