### ISSUE TITLE
Refresh: Home - update hero

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15309]
Update hero to match "[Homepage - Updated MVP](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1-4721&t=VaL6cYyET7hTTRRo-1).

Talk to Tess to get the details on the animated flag and if you need design guidance on the media controls.

**Comment by craigcook** [comment]
Actually this issue was relating to a previous design, there's a newer issue for the latest layout changes (https://github.com/mozilla/bedrock/issues/15482) so we can call this one done.
