### ISSUE TITLE
[VPN] Apple App Store CTA shown on iOS while in country where app store is not available

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15328]
## Description

When visiting the VPN landing page on an iOS mobile device, in a country where Apple App Store subscriptions are **not** available, the "Download the app" CTA is shown that still tries to link to the Apple App Store.

### Steps to reproduce

1. On an iOS device, visit https://www-dev.allizom.org/en-US/products/vpn/?geo=br
2. Scroll down to the "One subscription for all your devices" section.

### Expected result

If VPN is available in this country, but not the Apple App Store, then we should try and clearly explain that they need to sign up on an Android device.

### Actual result

A "Download the app" CTA is displayed that links to the Apple App Store.

<img src="https://private-user-images.githubusercontent.com/400117/377844947-2a2ea209-d321-4ee3-8c6b-566f14c7ee92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTAzMjQsIm5iZiI6MTcyOTI1MDAyNCwicGF0aCI6Ii80MDAxMTcvMzc3ODQ0OTQ3LTJhMmVhMjA5LWQzMjEtNGVlMy04YzZiLTU2NmYxNGM3ZWU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxMTEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWFkOWJhYWFiODVhYjVhNjgyN2NiMjlkNTRlODgyNjUyNzA1MTEyNzMyNjg1ZmQ1Y2I3ZWRmYzIxZTA2MmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zW6DG0Rqrjft7du8oFf5Ey_kPWG_SFu9kfyHJFILzik" alt="image" width="300" style="max-width: 100%;">

### Environment

iOS Safari

**Comment by albionx** [comment]
One thing that is a bit confusing in this bug filing (title + 'actual result') is that it says we link to the Apple App Store, but in fact we don't, as we link to the Google Play Store.

Though I agree that the fix here is that we should change the text "Sign up for a Mozilla VPN subscription on your mobile device" for "Sign up for a Mozilla VPN subscription on your Android device"

**Comment by alexgibson** [comment]
> One thing that is a bit confusing in this bug filing (title + 'actual result') is that it says we link to the Apple App Store, but in fact we don't, as we link to the Google Play Store.

Right now it links to Apple App Store on iOS, so we'll need to change that too.

**Comment by alexgibson** [comment]
Re-opening this issue, as the ask is to not show the blue "Download the app" button at all if the user is on iOS in a country where Apple subscriptions are not enabled. The copy will simply state they need to use an Android device.

**Comment by ValentinaPC** [comment]
Verified this as fixed for Brazil, Morocco and Bangladesh while on iOS 17.5.1, and there is no Download app button and the description only lists Android. 
![ImportedPhoto_1729663083164](https://github.com/user-attachments/assets/b2761753-ace7-4e3a-9d73-08e5cb495742)

@albionx we were not able to verify this for Senegal, as we don't have a VPN to localized ourselves there.
