### ISSUE TITLE
URLs that use prefer_cms should merge active_locales data

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15349]
## Description

When viewing a page published using Wagtail, the languages listed in the footer's language picker map only to the published languages that Wagtail knows about in the CMS. If the page uses the `prefer_cms` decorator, then the fallback Django / Fluent languages are not listed in the picker. The same is true in reverse. When viewing a Django / Fluent translated page, the language picker will not include languages that are published in Wagtail.

We should combine this data when rendering a template, so that the language picker lists all available translations for a given URL, regardless to where the source data is published from.

**Comment by stevejalim** [comment]
Completed via https://github.com/mozilla/bedrock/pull/15475
