### ISSUE TITLE
Refresh: 'Mozilla' missing from 'Mozilla VPN' and 'Mozilla Monitor' on stage Products menu

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/bedrock#15351]
## Description

'Mozilla' is missing from 'Mozilla VPN' and 'Mozilla Monitor' in the Products menu on Stage

<img width="1279" alt="Screenshot 2024-10-21 at 1 26 23 PM" src="https://github.com/user-attachments/assets/8363148f-3372-495b-8f6f-dd31cd95f42b">

**Comment by craigcook** [comment]
I believe "Monitor" should also be "Mozilla Monitor"

**Comment by stephaniehobson** [comment]
This was the official direction given to the devs to build out so I will check with Dan

**Comment by lesleyjanenorton** [comment]
Gotcha, thanks.

**Comment by lesleyjanenorton** [comment]
> I believe "Monitor" should also be "Mozilla Monitor"

Thanks, updated the ticket to reflect this.

**Comment by ashannonjones** [comment]
Hi folks, 
Confirming both VPN and Monitor should have Mozilla in front of them as per the brand teams guidelines. 
Holler with any follow up questions!

**Comment by lesleyjanenorton** [comment]
thanks @ashannonjones!

**Comment by stephaniehobson** [comment]
This should be updated on the products list on the homepage as well, please.
