### ISSUE TITLE
Update the Title Tag and Meta Description of the Nothing Personal Campaign Page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15355]
Request from: Louise Morgan

## Description

Please update the Title Tag and Meta Description to these copy below. 
(https://www.mozilla.org/en-US/firefox/nothing-personal/)

Title Tag: Firefox - Nothing Personal. Just Browsing.

Meta Description: Firefox browser is fast, reliable and private. We really don't need your personal data to help you get where you need to go online.

---

#### Success Criteria
- [ ] Reviewed by Adria

**Comment by clarapenn** [comment]
@stevejalim I'd like to work on this if possible?
