### ISSUE TITLE
[Refresh] Pencil banner should have a close / dismiss button

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15374]
## Description

The pencil banner should have a close (X) button on the right hand side that can be used to dismiss the banner.

When closed, we should set a preference cookie, in the same way we do for our older (pre-redesign) banners.

---

#### Success Criteria
- [ ] Pencil banner is dismiss-able

**Comment by stephaniehobson** [comment]
Duplicate of https://github.com/mozilla/bedrock/issues/15331
