### ISSUE TITLE
Update the video thumbnail and play icon for visibility and a11y.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15419]
## Description

The play icon over the video thumbnail on the latest WNP was hard to see.

The combination of a darker thumbnail + updated icon brings the contrast to 3:1. This helps with visibility and contrast is now a contrast of 3:1 for a11y.

Before:
![image](https://github.com/user-attachments/assets/3b89dc8d-8e59-45a7-a5a4-f029e9e1dea5)

After:
![image](https://github.com/user-attachments/assets/1d3c3456-97d9-492f-9f1a-9f09d1cebc0f)

---

### Assets:
![background](https://github.com/user-attachments/assets/0fe048f1-167d-4b9d-aded-5644d5985d52)
![play-icon](https://github.com/user-attachments/assets/9ee22e54-859a-40fd-99eb-20cb06b36298)

**Comment by slightlyoffbeat** [comment]
@wen-2018 lets use these same background/play button assets for the fx20 landing page video thumbnail as well.

**Comment by wen-2018** [comment]
@slightlyoffbeat Is there a high res version of the new thumbnail (1600 * 900) available?

**Comment by slightlyoffbeat** [comment]
An optimized 1600x900 below.

![Video-Thumbnail_1600x900](https://github.com/user-attachments/assets/fb9b1717-36da-400c-ab9e-44d17d525bec)
