### ISSUE TITLE
Refresh: Nav - hide keyboard navigation close button except on :focus

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15434]
The close button in the header navigation should only appear when a user puts keyboard focus on it (this will match the behaviour of the current navigation menu).

![Image](https://github.com/user-attachments/assets/9cd2306f-0f6c-4660-9d50-25d1e142cca1)

**Comment by alexgibson** [comment]
> Do we want to keep visible so that it is obvious how to close the menu for tablet and horizontal mobile users?

Good point, this could be especially useful for smaller tablet devices perhaps, where it becomes difficult to tap outside the menu area.

**Comment by alexgibson** [comment]
I've given this some testing on a couple of devices, and I think we should leave it as-is. Without it, the menu becomes hard to close and you can become locked in the navigation.

**Comment by stephaniehobson** [comment]
I'll ask Tess to add it to the designs.
