### ISSUE TITLE
Refresh: Move Thunderbird to second in product list

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15430]
Move Thunderbird to second in the product list. It's our second most popular product!

**Comment by janbrasna** [comment]
Would it make sense to have the product list on home and menu dropdown actually render the products in the same order?

**Comment by alexgibson** [comment]
@stephaniehobson looks like Thunderbird is already the second in the product list on the home page.

As to @janbrasna's suggestion I think it's worth considering still. This is the current order of (non-Firefox) products in the nav. Anything here that we could / should update to be more consistent?

![Image](https://github.com/user-attachments/assets/8be879de-aa5c-489a-82fd-c28b78a89633)

**Comment by stephaniehobson** [comment]
Fixed in #15410
