### ISSUE TITLE
Remove leftover experiment code for donate nav CTA

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15446]
## Description

There's still some leftover code in the current home page for a donation nav CTA experiment. I can't seem to get the variation to trigger when I test, so I can only assume it's leftover code from an old experiment. Looks like it's been running since July.

---

#### Success Criteria
- [x] Leftover experiment code is removed.

**Comment by alexgibson** [comment]
@slightlyoffbeat can you confirm we're OK to remove the experiment added in https://github.com/mozilla/bedrock/issues/14748? The switch seems to be active, but I can no longer seem to trigger the variant, but wanted to confirm it's OK to remove? Thanks

**Comment by slightlyoffbeat** [comment]
It can be ended/removed
