### ISSUE TITLE
Apply `word-break: keep-all;` for Korean text

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#15450]
## Description

When Korean text reflows automatically it can cause some words to split and be confused as separate words when the characters  should be combined to form a single word. We should use the CSS `word-break: keep-all;` globally for Korean to preserve strings as entered.

VPN page without `word-break: keep-all`:
![image](https://github.com/user-attachments/assets/7c562e1b-6582-45d1-b468-00ed4bb899e7)

VPN page with `word-break: keep-all`:
![image](https://github.com/user-attachments/assets/21ccd16b-eb4e-487c-b739-948fb7598011)

Only Korean has been flagged so far; we should consult with the l10n team to see if there are any other languages that may benefit from this setting.

**Comment by janbrasna** [comment]
Interestingly, I thought UA styles would apply these in CJK correctly based on lang (while in reality it's done based on unicode range) as `normal` is defined to do what's appropriate for every CJK script, and also revert that for any "western" words intertwined with the native lang, but it seems any actual word breaking or phrase breaking was never really the case and is rather a modern preference (along with boundary support):

- https://github.com/w3c/csswg-drafts/issues/4285 (habits changing in hangul vs. hanja)
- https://github.com/w3c/csswg-drafts/issues/8920 (breaking at phrases)

TIL. So yea, this request seems to be "ahead of" what the auto value provides, that is deemed perhaps old fashioned today, and such a manual addition is a welcome improvement in modern day? `css-text-4` calls it a "[typesetting preference](https://www.w3.org/TR/css-text-4/#example-f0d22488)".
