### ISSUE TITLE
Add pricing info to VPN mobile subscription CTA

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#15463]
## Description

We've been asked to add pricing information to the VPN mobile subscription offer that was added in https://github.com/mozilla/bedrock/issues/15262, so that potential subscribers have more info up-front before they download the app.

Option A from this Figma: https://www.figma.com/design/nm2nApv3ghovOu4w49ckk8/VPN-Landing-Page-(2023)?node-id=2390-5257&m=dev&t=8Yeh2fPQcyitTDwg-1

---

#### Success Criteria
- [x] Mobile subscription section features pricing info.

**Comment by slightlyoffbeat** [comment]
[Simplified sheet ](https://docs.google.com/spreadsheets/d/1mQ6QjKRdF6DgJ6FvzUKR5-K-C-8TQNVgucKJV0keJ9Y/edit?gid=1231306582#gid=1231306582)with countries, currencies, and amounts.
