### ISSUE TITLE
Link doesn't work anymore

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#15484]
## Description
[The link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink) in this string no longer works: `{ -brand-name-netscape } created and released JavaScript, which gave websites powerful computing capabilities they never had before. (They also made the infamous <a href="{ $blink }">&lt;blink&gt; tag</a>.) { -brand-name-microsoft } countered with Cascading Style Sheets (CSS), which became the standard for web page design.` 

- File name: en/firefox/browsers/history/browser-history.ftl
- ID: browser-history-netscape-created

### Steps to reproduce

The link points to a `Page Not Found` page on MDN.

### Expected result

Fix the link or update the string and remove link

**Comment by janbrasna** [comment]
Ah, nostalgia:/ It got removed in https://github.com/mdn/content/pull/26904

**Comment by janbrasna** [comment]
I think the least disruptive change would be to link https://developer.mozilla.org/en-US/docs/Glossary/blink_element instead, to keep the MDN reference? (It also has some fun stories from the early days;)…)
