### ISSUE TITLE
WNP - 133 (Version 2 & Version 3)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15487]
### Description

Version 2 and Version 3 refer to two variations of a WNP that has a donation message for the Mozilla Foundation. **The only difference between these two versions is the headline**.

### Audience

**Language:** EN-US, EN-UK, EN-CA, FR, DE, PL, IT, SP
Breakdown: 
EN-*, DE, FR : 10% of total market to V2 and 10% of total market to V3
PL, IT, SP: 50% of total market to V2, and 50% of total market to V3

### Assets

**Brief:** [EU](https://docs.google.com/document/d/1SwBQX0TD8kGpvghE4ZDDmo6ekwuuD_nb-MyOgF8OTl0/edit?usp=sharing) [NA](https://docs.google.com/document/d/1KL1gSb09-929HhbiQiaafbANnBylb60Pp5BLsdNRuIU/edit?usp=sharing) (refer to version 2 and version 3)
**Copy:** [EU](https://docs.google.com/document/d/1SwBQX0TD8kGpvghE4ZDDmo6ekwuuD_nb-MyOgF8OTl0/edit?usp=sharing) [NA](https://docs.google.com/document/d/1KL1gSb09-929HhbiQiaafbANnBylb60Pp5BLsdNRuIU/edit?usp=sharing) (refer to version 2 and version 3)
**Design:** [Link](https://www.figma.com/design/CZvzHgU9NQMQUm34lomIl5/Firefox-WNP?node-id=9386-356&t=pWRDtoB8ZlOzlXzy-1) (refer to Mozilla Foundations section)

**Comment by slightlyoffbeat** [comment]
For reference:
[WNP EU V1a (Newsletter Subscription)](https://github.com/mozilla/bedrock/issues/15485)
[WNP NA V1b (Fakespot)](https://github.com/mozilla/bedrock/issues/15486)
[WNP V2 & V3 (Mofo Donation)](https://github.com/mozilla/bedrock/issues/15487)
[WNP V4 (VPN)](https://github.com/mozilla/bedrock/issues/15488)

**Comment by slightlyoffbeat** [comment]
After discussion, we determined that we will need to use traffic cop for directing traffic. Nimbus will not work.

[Here](https://docs.google.com/document/d/1ffApBCQox0qzYyfiJYCYsfCRTgvSl_1sncP3uxSqwHE/edit?usp=sharing) is a document that outlines traffic priority for how this can be handled.

**Comment by alexgibson** [comment]
Traffic Cop config for NA/EU/Donation WNPs:

EU:
 - If country is [GB, FR, DE] and locale is [en-US, en-GB, fr, de]:
    - 80% see WNP EU design
    - 10% see WNP donation version 2
    - 10% see WNP donation version 3
NA:
  - Else if country is [US, CA] and locale is [en-US, en-CA]:
    - 80% see WNP NA design
    - 10% see WNP donation version 2
    - 10% see WNP donation version 3
Donation:
  - Else if locale is [fr, de, pl, it, es-ES]:
    - 50% see WNP donation Version 2
    - 50% see WNP donation Version 3
