### ISSUE TITLE
Refresh: Gallery updates

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15481]
We're calling the black section about AI on the homepage and the white news section on the about page a "gallery" component.

The homepage gallery needs to be updated with the most recent copy, images, and design.

Both instances of the component need to have the design for their their mobile display updated. For now please use the [mobile version of the component shown on the about page](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1-92938&m=dev). This swaps to a 3:2 ratio image and vertically stacks. (The mobile carousel for the AI section will be addressed in a separate issue).

**Comment by alexgibson** [comment]
@stephaniehobson do we have a link to the most recent design/copy/images for both of these components (on both desktop and mobile)? I'm a bit lost in all the multiple versions in Figma, which makes it not so clear to figure out what needs doing here. Thanks

**Comment by stephaniehobson** [comment]
[AI Gallery (Homepage, desktop))](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=949-141700&m=dev).  [AI Gallery (Homepage, mobile)](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=226-430479&m=dev). 

[News Gallery (About, desktop)](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1-28519&m=dev). [News Gallery (About, mobile)](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1-92938&m=dev).

You'll see the carousel design in the mobile version of the AI Gallery but that's a stretch goal. You can take it on as part of this issue or not, up to you. My thinking was that we would have all gallery have the stacking behaviour on mobile and then use the carousel as an optional progressive enhancement. But, once you're into code do what makes the most sense.
