### ISSUE TITLE
WNP (Version 4)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15488]
## Description

VPN has expanded to more regions. We will be advertising to the regions that we are expanding to. These regions are not a part of the target audience for the other WNP and should be safe to geo target.

### Audience
**Countries:** India, Indonesia, Brazil, Mexico, Türkiye, South Africa, Vietnam, Saudi Arabia, Thailand, Uganda, Senegal, Australia, Bangladesh, Ukraine, Egypt, Greece, Nigeria, Morocco, Colombia, Kenya, Chile, South Korea, Taiwan, and Norway.

**Languages available:** English, Portuguese, Chinese, Spanish , French, Ukrainian, Greek, Vietnamese, Turkish, Indonesian, and South Korean.

**Languages Codes:** EN-*, zh-TW, vi-VN, uk-UA, tr-TR, pt-BR, ko-KR, id-ID, fr-FR, es-LA, el-GR

**Breakdown:** 100%

Design: [Link](https://www.figma.com/design/CZvzHgU9NQMQUm34lomIl5/Firefox-WNP?node-id=9285-17328&node-type=canvas&t=a7h7YzxB6P7ubZPv-0) (Dark mode optional, not necessary)
Copy: [Link](https://drive.google.com/drive/folders/1uCQHsd7noa897JIKusfbV2KFMkuxlG5o)

#### Notes: 
- Needs to be Geo-targeted. We need to confirm how this works with Nimbus
- This is based on a previous WNP design. Possible to reuse older code.

**Comment by slightlyoffbeat** [comment]
For reference:
[WNP EU V1a (Newsletter Subscription)](https://github.com/mozilla/bedrock/issues/15485)
[WNP NA V1b (Fakespot)](https://github.com/mozilla/bedrock/issues/15486)
[WNP V2 & V3 (Mofo Donation)](https://github.com/mozilla/bedrock/issues/15487)
[WNP V4 (VPN)](https://github.com/mozilla/bedrock/issues/15488)

**Comment by alexgibson** [comment]
Adding a note here that bedrock does not support this exact list of language codes:

> Languages Codes: EN-*, zh-TW, vi-VN, uk-UA, tr-TR, pt-BR, ko-KR, id-ID, fr-FR, es-LA, el-GR

The closest match we have (I think) would be this:

```
    wnp_133_vpn_langs = [
        "el",
        "en-CA",
        "en-GB",
        "en-US",
        "es-ES",
        "es-MX",
        "fr",
        "id",
        "ko",
        "pt-BR",
        "tr",
        "uk",
        "vi",
        "zh-TW",
    ]
```

I'll double check expectations with Santiago

**Comment by alexgibson** [comment]
Demo links for reference:

- https://www-demo1.allizom.org/en-US/firefox/133.0/whatsnew/?geo=AU (en-US)
- https://www-demo1.allizom.org/en-CA/firefox/133.0/whatsnew/?geo=AU (en-CA)
- https://www-demo1.allizom.org/en-GB/firefox/133.0/whatsnew/?geo=AU (en-GB)
- https://www-demo1.allizom.org/el/firefox/133.0/whatsnew/?geo=AU (el)
- https://www-demo1.allizom.org/es-ES/firefox/133.0/whatsnew/?geo=AU (es-ES)
- https://www-demo1.allizom.org/es-MX/firefox/133.0/whatsnew/?geo=AU (es-MX)
- https://www-demo1.allizom.org/fr/firefox/133.0/whatsnew/?geo=AU (fr)
- https://www-demo1.allizom.org/id/firefox/133.0/whatsnew/?geo=AU (id)
- https://www-demo1.allizom.org/ko/firefox/133.0/whatsnew/?geo=AU (ko)
- https://www-demo1.allizom.org/pt-BR/firefox/133.0/whatsnew/?geo=AU (pt-BR)
- https://www-demo1.allizom.org/tr/firefox/133.0/whatsnew/?geo=AU (tr)
- https://www-demo1.allizom.org/uk/firefox/133.0/whatsnew/?geo=AU (uk)
- https://www-demo1.allizom.org/vi/firefox/133.0/whatsnew/?geo=AU (vi)
- https://www-demo1.allizom.org/zh-TW/firefox/133.0/whatsnew/?geo=AU

**Comment by slightlyoffbeat** [comment]
After discussion, we determined that we will need to use traffic cop for directing traffic. Nimbus will not work.

[Here](https://docs.google.com/document/d/1ffApBCQox0qzYyfiJYCYsfCRTgvSl_1sncP3uxSqwHE/edit?usp=sharing) is a document that outlines traffic priority for how this can be handled.

**Comment by janbrasna** [comment]
@alexgibson FYI "es-LA" as in `es-419` would map to "es-AR", "es-CL", "es-MX" from the prod locales here.
