### ISSUE TITLE
Strikethrough is not supported in Smartling 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15498]
When rich text containing a strikethrough is sent to Smartling, it is not editable/translateable

This may be wagtail-localize or it might be Smartling, but either way we should disable the option in Wagtail's rich-text editor - we don't use it at the moment, so there won't be any loss

@alexgibson - sound OK to you?

**Comment by alexgibson** [comment]
@stevejalim this sounds sensible to me yeah. I can't imagine many use-cases for needing it in CMS content.
