### ISSUE TITLE
Refresh: Homepage - animate flag

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15515]
We're moving forward with a SVG/CSS animation for the flag on the homepage. You can [use this Slack thread as a starting point](https://mozilla.slack.com/archives/G7ACJHJCB/p1731596316508239).

Respect the user's `prefers-reduced-motion` settings and there's design direction for a [pause animation button](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=1274-146173&m=dev) in the Figma. 

Tess is the best person to go to if you have questions.

**Comment by maureenlholland** [comment]
Codepen implementation: https://codepen.io/oleaceae/pen/GRVzVdE?editors=1100

**Comment by ehot** [comment]
Codepen Alt Animation: https://codepen.io/oleaceae/pen/vYoPdOJ (Blinking + Bouncing)

**Comment by slightlyoffbeat** [comment]
I'd like to string these together, as long as performance allows.

Waving for a period of time. Back to static. Blink. Bounce. Blink. Static. Repeat. Something like that.

**Comment by ehot** [comment]
https://codepen.io/oleaceae/pen/VwoJzYG @slightlyoffbeat here's a variant that switches between static, to wave, to static, to bounce/blink

**Comment by ehot** [comment]
https://codepen.io/oleaceae/pen/wvVLrOm <- another variant where it waves for 20s, then winks and bounces for 10s, then stays stationary for 10s, then loops.

**Comment by stephaniehobson** [comment]
Most recent codepens: 
https://codepen.io/slightlyoffbeat/pen/LYwwpgj
https://codepen.io/slightlyoffbeat/pen/XWvvXpg
