### ISSUE TITLE
Giving Tuesday MoFo Donation Banners

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15527]
## Description

Giving Tuesday Banner

### Timing

Go-Live: End of Day PST on December 2nd.
Take-Down: Either morning UK or when we switch to new design on December 3rd. 

### Assets

Design: [Figma](https://www.figma.com/design/2TK8tXeDIiLC67TMdbMIcO/Fundraising?node-id=2673-1822&t=BBeBZbvAla8micac-1)
Copy: [Link](https://docs.google.com/document/d/1v6TndAHF9XdD2H4sWCocb1BZUPjtecgQ0c_iHxkYjns/edit?usp=sharing) (refer to phase one: giving tuesday)
Assets: [Link](https://drive.google.com/file/d/15_Lk-yRV5wWLUae6Mc3lmYn5P_834CBN/view)

### Details

Surface: homepage
Languages: EN, FR, DE (translations needed)
Split Test: 3 way (33/33/33)

### Split Test

A 3 way split test (33/33/33) will be implemented.

The variations of the CTA text will be tested. The three CTAs are in the copy document, along with the three CTA links.

If there is enough data to determine a winner, the winning CTA text will be used for the end-of-year donation banner.

### Notes

A switch should be used for quickly putting up and taking down
Another banner will be used at the end of december with slightly different copy and design/

**Comment by alexgibson** [comment]
Demo links for English:

- https://www-demo1.allizom.org/en-US/?v=a
- https://www-demo1.allizom.org/en-US/?v=b
- https://www-demo1.allizom.org/en-US/?v=c

**Comment by alexgibson** [comment]
There has been a late request to add some more languages for this banner, so I'm re-opening this issue to track adding them.
