### ISSUE TITLE
Refresh: reduce size of IRL images

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#15522]
## Description

Pink IRL image is small but green & orange are about 60kb high res. This is a simple rounded box with text and icon, so it might be easier to export as SVG and do color manipulations through CSS custom properties.

https://github.com/mozilla/bedrock/pull/15448#discussion_r1848531923

---

#### Success Criteria
- [ ] Replace existing large PNGs with SVG or smaller PNGs (similar to pink PNG sizes)

**Comment by stephaniehobson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/15599
