### ISSUE TITLE
Refresh: nav tweaks

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15564]
- On wide screens the menus end up far away from other content - restrict the width of the drop down to grid(8) on $mq-lg
- Remove underline on links and only display it when they are hovered
  - Underline should stay visible on menu item when its menu is open
- Add a transition to the arrow on the "all products" link like the one on on the launchpad arrows

**Comment by craigcook** [comment]
* Update "close" button styling. Not sure we got a design for it, but maybe we can just match what's in the pencil banner.

**Comment by craigcook** [comment]
![image](https://github.com/user-attachments/assets/b4d1563d-2b9d-4ee9-93e0-652c2f18f4b1)

The title spacing/positioning is wonky on mobile, and we should use the filled arrow.
