### ISSUE TITLE
[M24] Language picker doesn't stretch to fit content

### ISSUE THREAD

**Issue by janbrasna** [mozilla/bedrock#15609]
## Description

Current language (besides _en-US_, _ar_, and a few more) mostly doesn't fit inside the locale selector in [m24] footer.

### Steps to reproduce

(M24:) Change language from English to anything else, i.e. "English (Canadian)" or almost any other locale, and observe the component now.

### Expected result

The chosen locale should fit within the selector.

### Actual result

Locale is cropped (WebKit):

<img width="182" alt="Screenshot 2024-11-28 at 22 40 06" src="https://github.com/user-attachments/assets/7b82f1e4-6a2e-4051-b51f-21301074b520">
<img width="179" alt="Screenshot 2024-11-28 at 22 40 19" src="https://github.com/user-attachments/assets/49675d9e-2f0c-4667-aa81-d7aed5caf342">
<img width="169" alt="Screenshot 2024-11-28 at 22 40 56" src="https://github.com/user-attachments/assets/b996afd7-5b79-4354-ba39-d24e09e2a99b">
<img width="162" alt="Screenshot 2024-11-28 at 22 41 45" src="https://github.com/user-attachments/assets/4f7b689d-480b-4423-ada8-005e50b5855e">

Or in case of Gecko the ellipsis eats up even more space (Aurora):

<img width="173" alt="Screenshot 2024-11-29 at 22 12 38" src="https://github.com/user-attachments/assets/911d2c17-1b3b-48ba-bd19-99dde8f1b115">

- - - -

_Originally posted by `@stephaniehobson` in https://github.com/mozilla/bedrock/issues/15620#issuecomment-2515575065_:

> Most languages should display without being cut off.
> 
> Possible solutions:
> - make it expand to match the width of the selected language
> - make it the same width as our current language selector

**Comment by maureenlholland** [comment]
This also cuts off dramatically with large font setting on chrome
<img width="199" alt="chrome-lang-switcher" src="https://github.com/user-attachments/assets/49018248-00fe-4cb3-a2c5-c810a4dceb4a">

**Comment by janbrasna** [comment]
There is JS hooked up to that component anyways, so I'll also check if it would be feasible to "measure" the necessary width based on the current content, and set the select size with some math in a script.
