### ISSUE TITLE
Update Link & copy for builders section on new homepage

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15613]
## Description

Builders has a new website that is launching just about the same time as the homepage.

In the AI section on the homepage, the requested updates are:

- change link from `future.mozilla.org/builders` to: `builders.mozilla.org`
- change copy to `Builders helps independent developers create transformative open-source AI projects through bespoke collaborations, programming, and community.`

It will soft launch on Dec 3, which is the day before the new homepage goes live.

We also confirmed that this subdomain will forward to the current home at future.mozilla.org until the new home is live.

**Comment by janbrasna** [comment]
I've also updated the existing https://www.mozilla.org/builders/ redirect with it in #15614

However the https://builders.mozilla.org host seems still unconfigured, so this is not ready to merge yet.

**Comment by janbrasna** [comment]
@stephaniehobson Leaving the FTL change to you — not sure if you want to keep the current string as a fallback or to replace it unconditionally etc.…

**Comment by stephaniehobson** [comment]
Fixed in #15614 and #15624.
