### ISSUE TITLE
Gap between Navigation & Navigation Drawer (Desktop)

### ISSUE THREAD

**Issue by tesseheinricks** [mozilla/bedrock#15636]
## Description

There is a gap between the top navigation and the dropdown menu

### Steps to reproduce

<img width="1864" alt="Screenshot 2024-12-03 at 1 19 02 PM" src="https://github.com/user-attachments/assets/a5105d86-ebd7-4299-a188-4e6639b6f1a9">

### Expected result

No Gap between these items

What should happen?

No Gap between these items

What happened.

There is a gap 

What browser and operating system are you using?

Macbook Pro, Sonoma

**Comment by maureenlholland** [comment]
should be fixed with https://github.com/mozilla/bedrock/pull/15631
will confirm when latest update is on demo

**Comment by stephaniehobson** [comment]
+1 should be fixed 🤞

**Comment by janbrasna** [comment]
@tesseheinricks This is now deployed to demo4 (along with other recent fixes) to validate it is indeed resolved.
