### ISSUE TITLE
Firefox Enterprise Purple Box

### ISSUE THREAD

**Issue by ehot** [mozilla/bedrock#15643]
![IMG_0021](https://github.com/user-attachments/assets/edf24fbb-af9a-489a-823d-65584d40c741)

Viewed on 8th Gen IPad, 15.6.1, Portrait Mode

There is a purple box around the download / privacy notice.

**Comment by stephaniehobson** [comment]
Might be fixed in #15654. We should check when it merges.

**Comment by janbrasna** [comment]
Yup these fit now even in the languages that run the headlines a bit longer:
- https://www-dev.allizom.org/en/firefox/enterprise/
- https://www-dev.allizom.org/de/firefox/enterprise/
- https://www-dev.allizom.org/pt/firefox/enterprise/
- https://www-dev.allizom.org/ru/firefox/enterprise/
- https://www-dev.allizom.org/nl/firefox/enterprise/
etc.
