### ISSUE TITLE
Padding around Flag on Ipad

### ISSUE THREAD

**Issue by ehot** [mozilla/bedrock#15640]
![IMG_0019](https://github.com/user-attachments/assets/ac346e18-9b65-4f87-99ad-17f938d7a7e7)

Viewed on 8th Gen IPad, 15.6.1, Portrait Mode

There should be more padding around the flag when the split component goes switches from a 2 to a 1 column layout.

**Comment by maureenlholland** [comment]
issue with support for [media range syntax](https://caniuse.com/?search=media%20range%20query), will revert to better supported syntax

**Comment by stephaniehobson** [comment]
Fixed in #15525
