### ISSUE TITLE
Heading Text Width on Product Pages

### ISSUE THREAD

**Issue by ehot** [mozilla/bedrock#15648]
![IMG_0028](https://github.com/user-attachments/assets/de142b7b-e6b2-4e51-a910-214bd0b7f7f3)
![IMG_0025](https://github.com/user-attachments/assets/4d72a082-150a-4ce7-a922-0cd1fa0ac44b)
<img width="1238" alt="Screenshot 2024-12-03 at 4 04 51 PM" src="https://github.com/user-attachments/assets/26d03e82-6ad8-4cff-99db-184987e28050">

On my desktop, there is the input box that lets you send a download link to your phone. On my ipad, however, this input box is not there, but the layout is still two columns, which squishes the text to the left. You can find this happening on the IOS, Android, and Focus pages.

**Comment by stephaniehobson** [comment]
Might be fixed in #15654. We should check when it merges.
