### ISSUE TITLE
Brand Standards Link in Footer

### ISSUE THREAD

**Issue by ehot** [mozilla/bedrock#15647]
In the footer, under Resources, the link for "Brand Standards" goes to the old mozilla brand standards website.

**Comment by janbrasna** [comment]
I believe there's no public alternative with any newer brand guidelines — the https://brand.mozilla.com/ is behind a login for now.

**Comment by slightlyoffbeat** [comment]
After discussion with the brand team, the preference is to remove the link completely for now.
