### ISSUE TITLE
Change pencil banner text and link in updated design.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15649]
## Description

Text should change to: `Donate to Mozilla by Dec 31 — `
CTA text should change to: `Donate ♥`
Link should change to: `https://foundation.mozilla.org/?form=eoy-pencil-aa`

![image](https://github.com/user-attachments/assets/acbd8906-4f67-4315-b836-f59dde64db59)

**Comment by stephaniehobson** [comment]
@slightlyoffbeat should we keep "Support ethical AI and internet privacy — donate today!" around to use again or should it be removed from the code base?
