### ISSUE TITLE
Donate button and langauge switcher are not aligned

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15658]
The donate button and language switcher look like they should be level with each other but they're not quite. It's most obvious at tablet sizes:

![Screenshot 2024-12-03 at 21 21 22](https://github.com/user-attachments/assets/0e9b6f5b-894a-4e6f-ad3e-0897e23584f3)

**Comment by wen-2018** [comment]
This has been fixed in https://github.com/mozilla/bedrock/pull/15654
