### ISSUE TITLE
Adjust body type scale, avoid text being too small on mobile

### ISSUE THREAD

**Issue by tesseheinricks** [mozilla/bedrock#15667]
## Description

The body copy is appearing too small on mobile

### Steps to reproduce

<img width="355" alt="Screenshot 2024-12-04 at 10 38 30 AM" src="https://github.com/user-attachments/assets/53efe7ae-0bc3-4b0c-aa2f-93cec7d68995">

### Expected result

The body copy would be Mobile - Medium body (16)

### Actual result

The copy is appearing at 12pt 

### Environment

iPhone X

**Comment by alexgibson** [comment]
The gallery image descriptions are 14px on mobile, and the small CTA test is also 12px 

![image](https://github.com/user-attachments/assets/3ba4814d-65ed-40a6-b595-99569e1d79d7)

**Comment by craigcook** [comment]
The nav text is also quite small on mobile, which has a side effect of also reducing the hit area for tapping.

![image](https://github.com/user-attachments/assets/e5cf0806-9941-4784-8322-b8464f4ee71e)
