### ISSUE TITLE
Left align the picto icons on the about page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15679]
<img width="324" alt="Screenshot 2024-12-03 at 10 52 00 AM - Jodie Gatlin" src="https://github.com/user-attachments/assets/a953dce8-a0b7-4da1-82da-3ffe820b6cdf">

This is going to be a PITA. I'm not sure there's a "right" way to do it that isn't a hack.

**Comment by stephaniehobson** [comment]
@ehot we talked a bit about this already. Is there a "right" way to handle this? A set of icons with no padding?

**Comment by wen-2018** [comment]
I have talked with Tess and she has created a set of special icons with reduced padding on left and right, but reserved padding on top and bottom. This allows the icons to have the same height and preserves the proportions to each other
