### ISSUE TITLE
Add firefox ticktock to Follow @Firefox section of footer

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15692]
Firefox now has a TickTock. We should add it to the Follow @Firefox section of the footer:

https://www.tiktok.com/@firefox

**Comment by janbrasna** [comment]
This ordering would work?

<img width="169" alt="Screenshot 2024-12-06 at 15 32 58" src="https://github.com/user-attachments/assets/ca363a9d-5ec2-4417-95bd-7a1cedef6dc4">
