### ISSUE TITLE
Refresh: footer donate button visited color on Firefox pages

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#15701]
## Description

![image](https://github.com/user-attachments/assets/cb45f5ee-9a0d-4a9c-b639-56699003af35)

Donate button is getting the :visited link color on the pages that kept Firefox branding (whatsnew, welcome, and campaign pages). Likely just a specificity glitch.

### Steps to reproduce

https://www.mozilla.org/en-US/firefox/133.0/whatsnew/
https://www.mozilla.org/en-US/firefox/welcome/10/
https://www.mozilla.org/en-US/firefox/nothing-personal/

Click the Donate button in the footer so it's marked as visited.

### Expected result

On returning to the page, the donate button text should still be white.

### Actual result

It's purple (the color for visited links).

### Environment

What browser and operating system are you using?

Firefox on macOS but I would expect other browsers to do the same.

**Comment by janbrasna** [comment]
So the actual class only sets the color on anchor, not :link — and in m24 base styles the :link generally defines white color — something not present in fx styles, hence the visited purple applied on the CTA.

In #15722 I'm just moving the CTA color from anchor to :link/:visited as the easiest fix.
