### ISSUE TITLE
Change section CTAs to use large theme

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15707]
Change the default size of `.m24-c-cta` to match the large theme. Right now they're xl, make xl accessible through a theme class.

**Comment by janbrasna** [comment]
Is the ask to literally only change `.m24-c-section-cta > .m24-c-cta` (that targets _"Explore our products"_ and _"Watch the award show"_ — but not e.g. _"Donate"_) or it should be understood more generally changing all `.m24-c-cta` sizing for consistency, incl. _"Donate"_ or _"Learn about us"_ (which is already overridden to `lg` btw), no matter if it's an actual section-cta, donate-cta, or flag-cta in the end?

**Comment by stephaniehobson** [comment]
More generally for consistency please!
