### ISSUE TITLE
Add State of Mozilla to home page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#15727]
## Description
The 2024 State of Mozilla is coming soon and we'll be updating the home page showcase currently showing Rise25 to promote State of Mozilla instead.

[Figma here for design and copy](https://www.figma.com/design/umfT9uNYJwAjIwgz360BdB/MVP-3.0-Mozilla.org?node-id=2171-190749&t=3oFbXgmxHftuuTJS-1) (mozilla access only)

Since SoM is English-only we were thinking we'd only show it on the home page for English and other locales would continue to show Rise25.

This depends on #15726 and shouldn't go live until SoM goes live as well (obviously).

**Comment by janbrasna** [comment]
FYI, both Rise25 site and the awards video linked from the CTA are both EN only, too. (That said, if the target content is EN anyways in both cases, I believe the SoM could be interesting for all the language communities, even if the target content is EN-only.)

**Comment by craigcook** [comment]
> FYI, both Rise25 site and the awards video linked from the CTA are both EN only, too. (That said, if the target content is EN anyways in both cases, I believe the SoM could be interesting for all the language communities, even if the target content is EN-only.)

You're right. I also expect this section of the page will stay in place for a while so I see no reason not to have it localized.
