### ISSUE TITLE
SOM: Image Updates:

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#15749]
## Description

There are Image updates for 7.2 and 7.4, and 1.3

Images Links:
- [Desktop](https://drive.google.com/drive/folders/113QBBn52g_gd0OxoU_ZoCz5FjzTocNPm)
- [Article](https://drive.google.com/drive/folders/141MpaHlSkVWf5YMENpzGIh07Vi2qM0o3)
- [Mobile](https://drive.google.com/drive/folders/11CWjukvUfJ1x-MXIX-DAQFERIsEN5dvv)

Note: These folders contain images for more than just 7.2 and 7.4. It is only 7.2 and 7.4 that need to be udpated.

The images for 1.3 were also slightly broken (there were lines between some of the pixels. These have been fixed. Here are the new exports:

Desktop: [(1x)](https://drive.google.com/open?id=16_PBVtD3kV1K3tsqD7dDdoJIpgDIm3wj&usp=drive_fs) [(3x)](https://drive.google.com/open?id=16_oEDDwlFXvLFxniwMp-feyAeDpC4kXP&usp=drive_fs)
Mobile: [(1x) ](https://drive.google.com/open?id=1qER73bFuaIIrIEngQp691fXker-ly-lI&usp=drive_fs)[(3x)](https://drive.google.com/open?id=1qMegrsDgPh7lAYlr9WKaDKIeo52J-AFK&usp=drive_fs)
Article: [(1x)](https://drive.google.com/open?id=14aV2EXlZqWRnV7DEAHQbnOZmRIQNxWbh&usp=drive_fs) [(3x)](https://drive.google.com/file/d/14ZYWf_fu2Hr5sGv-f3Jmt2NCQbBLoPNk/view?usp=drive_link)

**Comment by alexgibson** [comment]
Note that the case studies (7.1 -> 7.4) do not have article images unlike the other sections (this was requested by design agency), so we only need to update the desktop / mobile landing page images for 7.4 and 7.2.
