### ISSUE TITLE
Tabzilla does not have high density mozilla image

### ISSUE THREAD

**Issue by vtsatskin** [mozilla/bedrock#1849]
When browsing bedrock websites on a high density display (such as a retina MacBook) Tabzilla does not have a high density Mozilla logo. See screenshot below.

![](https://cloud.githubusercontent.com/assets/1301625/2581872/8a5f8494-b9bd-11e3-9671-43e83c7c7a2c.png)

Perhaps an SVG can be used for this resource to prevent having to maintain different display density images.

**Comment by alexgibson** [comment]
This was fixed in #2775 thanks to @kyoshino
