### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/bedrock#3055]
This is mostly for my notes and TODOs as I encounter them for [bug 1156344](https://bugzilla.mozilla.org/show_bug.cgi?id=1156344).

**Comment by GurpreetSK95** [comment]
HI.
Has this issue been fixed?

**Comment by pmac** [comment]
It has indeed. Forgot this was here. Thanks.

**Comment by GurpreetSK95** [comment]
Just so you know, there are some other issues dating back to 2012 also 🍡 
Regards.

**Comment by pmac** [comment]
Yeah. We mostly use [Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=product%3Awww.mozilla.org) for this project, but some issues were created a while back and apparently forgotten about. I'll see if I can clean them up. Thanks!
