### ISSUE TITLE
Incomplete button in ios page

### ISSUE THREAD

**Issue by pochy-ja** [mozilla/bedrock#3555]
Have a button with a property over, see there

![bug](https://cloud.githubusercontent.com/assets/7938214/11125435/e8dd616c-8937-11e5-8e00-e29a9d739541.png)

I delete the property margin-top of the rule {.fxfamilynav-cta-wrapper .send-to} and this works, you need a pull-request or anyone can handle this.

**Comment by pochy-ja** [comment]
I go to check this in another language and in en-US this feel good, but in some languages like es-ES this happens, the line [L742](https://github.com/mozilla/bedrock/blob/master/media/css/firefox/ios.less#L742) is the responsible.

**Comment by alexgibson** [comment]
Thanks for the report @pochy-ja - I filed a bugzilla bug for reference to track this: https://bugzilla.mozilla.org/show_bug.cgi?id=1231732

**Comment by alexgibson** [comment]
This was fixed in #3736 and should be in production soon. Thanks, @pochy-ja!
