### ISSUE TITLE
Add functional tests to improve coverage

### ISSUE THREAD

**Issue by davehunt** [mozilla/bedrock#3629]
The following functional tests/checks have been identified as desirable to improve test coverage:

- [ ] Viewing [Mozilla Spaces](https://www.mozilla.org/en-US/contact/spaces/) on a mobile viewport
- [ ] Viewing [Mozilla Communities](https://www.mozilla.org/en-US/contact/communities) on a mobile viewport
- [ ] Checking page footer is displayed on at least one page
- [x] Checking 404 page components are displayed
- [x] Thunderbird download pages
- [x] Firefox Desktop pages
- [x] Firefox for iOS page
- [x] Firefox channel page
- [x] Firefox installer help page
- [x] SmartOn pages
- [x] Android page sent-to-device form test (blocked by #3534)
- [ ] Firefox Products page conditional messaging for Android, iOS, out-of-date Firefox.
- [ ] Plugincheck page tests for both none and one (or more) plugins using Firefox.
- [ ] Sync page conditional messaging for Android, iOS, out-of-date Firefox.
- [ ] Firefox family navigation scroll tests, plus mobile viewport test.
- [x] Firefox OS 2.5 page news feed is displayed test (pending #3709)
- [x] Add test for partnerships form (see: https://github.com/mozilla/mcom-tests/blob/master/tests/test_partnerships.py#L33)

**Comment by alexgibson** [comment]
I'm going to close this issue for now. There are still a few areas not covered in this initial list, but I think we have good enough coverage for most things now. Can always revisit in the future when we have some more bandwidth.
