### ISSUE TITLE
LinkChecker is failing on pages with downlevel-revealed conditional comments

### ISSUE THREAD

**Issue by davehunt** [mozilla/bedrock#3692]
Commit https://github.com/mozilla/bedrock/commit/a01513050a2d399548ad3ddeb7335358dc99da13 introduced a downlevel-revealed conditional comment, which has caused a problem with our LinkChecker. I have raised this against LinkChecker (https://github.com/wummel/linkchecker/issues/630), however @alexgibson suggests that we may be able to revert this change.

**Comment by alexgibson** [comment]
@jpetto, @jgmize - do we still need this conditional comment for IE6 after yesterday? (was it in fact a red herring). If we do still need to keep it, I suggest we switch back to using piece of JS to detect the user agent (which is what jon even wrte originally :weary:)

**Comment by alexgibson** [comment]
This should now have been fixed by #3702. Closing, thanks all!
