### ISSUE TITLE
Miswording in Windows 10 welcome page

### ISSUE THREAD

**Issue by darchons** [mozilla/bedrock#3723]
Item 1 in the Windows 10 welcome page [1] says "Click the button below", but the button is actually above the text.

[1] https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/win10-welcome.html#L54

**Comment by alexgibson** [comment]
Thanks for the report! It looks like the position of the button was swapped recently after an A/B test but the string was not updated. We'll get this fixed asap.

**Comment by dhanushuUzumaki** [comment]
I would like to work on it

**Comment by alexgibson** [comment]
> I would like to work on it.

Thanks @dhanushuUzumaki - we already have PR #3724 open for this issue, but the code changes are incomplete. I'm waiting to hear back from the contributor, but if they don't update I can assign the bug over to you.

**Comment by dhanushuUzumaki** [comment]
Thanks for the info :)

**Comment by alexgibson** [comment]
This was fixed in #3759, thanks all!
