### ISSUE TITLE
Update Selenium to v2.50 in Jenkins & Docker

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#3789]
As per https://github.com/mozilla/bedrock/pull/3772 we are now using Selenium client v2.49.0 for running tests locally in bedrock.

Quoting @davehunt:

To update the server versions used in the pipeline, we must change the value of SELENIUM_VERSION in the global configuration in Jenkins. Note that this will affect both Sauce Labs and Docker jobs, and it appears that 2.49 is not yet available in [docker-selenium](https://github.com/SeleniumHQ/docker-selenium). To keep Docker pinned, we can set the SELENIUM_VERSION environment variable within the job configuration that uses Docker.

For what it's worth, the 2.49 client should be fully compatible with the 2.48.2 server, so there's no need to block merging this. If for some reason there is an incompatibility, we can simply revert this commit.

**Comment by alexgibson** [comment]
There's a pull request to update docker-selenium to the latest version here: https://github.com/SeleniumHQ/docker-selenium/pull/146

**Comment by alexgibson** [comment]
cc @jgmize and @glogiotatidis

**Comment by davehunt** [comment]
I've seen a few issues and mentions of timeouts when using Selenium Grid 2.49, so we should use caution when upgrading. I'll update here if I see any concrete evidence of issues in this release.

**Comment by alexgibson** [comment]
Note: Selenium 2.49.2 has been released with a minor regression fix https://github.com/mozilla/bedrock/pull/3791

**Comment by davehunt** [comment]
It's confusing, but 2.49.2 refers to the Python client. The latest Java server version is still 2.49.0.

**Comment by davehunt** [comment]
A new server, 2.50 is now out.

**Comment by davehunt** [comment]
It should be safe to set SELENIUM_VERSION to 2.52.0 in https://ci.us-west.moz.works/configure

**Comment by jgmize** [comment]
> It should be safe to set SELENIUM_VERSION to 2.52.0 in https://ci.us-west.moz.works/configure

Done, thanks.

**Comment by alexgibson** [comment]
Thanks @jgmize!
