### ISSUE TITLE
update android system requirements on download button

### ISSUE THREAD

**Issue by lizzard** [mozilla/bedrock#3821]
In   https://github.com/mozilla/bedrock/blob/e3f844ae8bb58aed6971db7316f2b2fd6e6b02c8/bedrock/firefox/firefox_details.py we say,

# Android Honeycomb (3.x) was supported on Firefox 45 and below
        if int(self.latest_version(channel).split('.', 1)[0]) < 46:
            platforms['android'] = _('Modern devices\n(Android 3.0+)')

I just posted in release notes for 46 aurora that we don't support Honeycomb, but the download button still says "For Android Honeycomb+".

**Comment by kyoshino** [comment]
This was reported in [Bug 1245839](https://bugzilla.mozilla.org/show_bug.cgi?id=1245839) and fixed in  #3833. Can someone close the issue?

**Comment by alexgibson** [comment]
Closing, thanks @kyoshino!

**Comment by kyoshino** [comment]
:smiley_cat:
