### ISSUE TITLE
New root certificate to add to /certs/

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/bedrock#3844]
https://wiki.mozilla.org/MozillaRootCertificate references the file https://www.mozilla.org/certs/mozilla-root.crt for the current internal SHA-1 CA.

I would like to add two new files alongside it for the new internal SHA-2 CA, titled:

```
mozilla-root-sha2.crt
mozilla-root-sha2.crt.sha256sum
```

I'll email the files to @jgmize as it's not clear where I would put them in a pull request.

**Comment by floatingatoll** [comment]
Emailed.

```
746eb47c02524cf15dea7e947be4b47cf6fb96ce1a41fe87d8ffc2ce64ba134d  ca_sha2.crt
```

**Comment by jgmize** [comment]
Added in #3847, which I plan to push to production tomorrow morning.

**Comment by jgmize** [comment]
> I would like to add two new files alongside it for the new internal SHA-2 CA, titled:
> mozilla-root-sha2.crt
> mozilla-root-sha2.crt.sha256sum

@floatingatoll I just noticed that the filenames you used when you reported this issue are different than those in your signed email attachment, which are what I used in #3847. Would like them renamed to match those above, or do you prefer them as they are?

**Comment by floatingatoll** [comment]
Please rename them to match this request - thanks for checking!
