### ISSUE TITLE
Remove Cloud9, Vagrant and legacy PHP site from documentation?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#3944]
- [ ] http://bedrock.readthedocs.org/en/latest/quickstart.html
- [ ] http://bedrock.readthedocs.org/en/latest/vagrant.html
- [ ] http://bedrock.readthedocs.org/en/latest/php.html

Can any/all of these now be removed from our documentation?

**Comment by alexgibson** [comment]
Thoughts @jgmize or @pmclanahan? I'd be happy to lend a hand cleaning up some things if we no longer use/support them.

**Comment by pmclanahan** [comment]
I think all of this can go, yes.
