### ISSUE TITLE
Inconsistent instructions on referring to bugs on changes to Bedrock

### ISSUE THREAD

**Issue by amuntner** [mozilla/bedrock#4112]
This page reads, "All commit messages must include a bug number. You can put the bug number on any line, not only the first one."

The Guidelines displayed on Github when one makes a pull request read: "All commit messages should be well written, and reference a Bugzilla bug number where applicable."

Not sure what the correct lang should be, posting here for discussion instead of filing a bug.

**Comment by alexgibson** [comment]
We recently simplified our GitHub pull request template in #4115, and it no longer references the line of copy highlighted above. For now, we are back to a single source of instruction here: http://bedrock.readthedocs.io/en/latest/contribute.html#git-commit-messages
