### ISSUE TITLE
Enable l10n auto-updates in prod

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#4399]
Auto updating of .lang files happens in the dev instances via a supervisord process running in the docker container which in turn runs a gunicorn process for the website, and a separate python process for updating the files every 10 minutes or so. We'd like to try this in production. We'll be starting by trying this in staging in our US-based cluster, then to prod. We'll monitor performance metrics and logs for errors and issues for several days before doing the same in the much more heavily-trafficked European cluster.
## Turning on Supervisor

``` bash
$ deis-usw config:set -a bedrock-stage RUN_SUPERVISOR=true L10N_CRON=true
```
## Order of Operations
- [x] Verify things are working properly on dev by inspecting running processes in the `web` and `clock` containers
- [x] Turn on supervisor for staging in us-west
- [x] ssh into web containers to verify running processes are as expected (supervisor, gunicorn, cron.py l10n)
- [x] watch performance metrics on New Relic and logs on papertrail
- [x] repeat the above steps for prod in us-west
- [ ] repeat the above steps for stage, then prod in eu-west

cc @jgmize

**Comment by pmac** [comment]
Verified dev, turned on stage, verified stage. Just for the record, verification looks like:

```bash
core@xxx.us-west-2.compute.internal:~$ fleetctl list-units | grep bedrock-stage
bedrock-stage_v1152.clock.1.service                     a99809ba.../10.0.6.246  active          running
bedrock-stage_v1152.web.1.service                       80320da7.../10.0.4.211  active          running
bedrock-stage_v1152.web.2.service                       60ad69e8.../10.0.2.174  active          running
bedrock-stage_v1152.web.3.service                       a99809ba.../10.0.6.246  active          running
core@xxx.us-west-2.compute.internal:~$ deisctl dock bedrock-stage_v1152.clock.1.service
Executing 'docker exec -it bedrock-stage_v1152.clock.1 sh' on XX.XX.XX.XX
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
webdev       1  0.6  0.1  54840 21596 ?        Ss   16:56   0:00 python ./bin/cron.py db
webdev      10  1.5  0.0   4508   756 ?        Ss   16:57   0:00 sh
webdev      15  0.0  0.0  36128  3148 ?        R+   16:57   0:00 ps aux
$ core@xxx.us-west-2.compute.internal:~$ deisctl dock bedrock-stage_v1152.web.1.service
Executing 'docker exec -it bedrock-stage_v1152.web.1 sh' on XX.XX.XX.XX
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
webdev       1  0.4  0.1  57064 18956 ?        Ss   16:56   0:00 /usr/bin/python /usr/local/bin/supervisord -c etc/supervisord.conf
webdev      19  0.5  0.1  54824 21404 ?        S    16:56   0:00 python /app/bin/cron.py l10n
webdev      20  0.0  0.0  19788  3072 ?        S    16:56   0:00 /bin/bash -xe /app/docker/run-prod.sh
webdev      21  0.3  0.1  47596 17988 ?        S    16:56   0:00 /usr/bin/python /usr/local/bin/gunicorn wsgi.app:application -b 0.0.0.0:8000 -w 2 --error-logfile - --access
webdev      28  6.4  0.6 444300 111708 ?       Sl   16:56   0:04 /usr/bin/python /usr/local/bin/gunicorn wsgi.app:application -b 0.0.0.0:8000 -w 2 --error-logfile - --access
webdev      29  7.0  0.6 444520 111868 ?       Sl   16:56   0:04 /usr/bin/python /usr/local/bin/gunicorn wsgi.app:application -b 0.0.0.0:8000 -w 2 --error-logfile - --access
```

**Comment by flodolo** [comment]
This would be great. 

On a side note, it's worth noting that bedrock-l10n has a lot less activity than the repo used for production (avg 1 commit a day).

bedrock-l10n (prod): https://github.com/mozilla-l10n/www.mozilla.org/graphs/commit-activity
www.mozilla.org (dev): https://github.com/mozilla-l10n/www.mozilla.org/graphs/commit-activity

**Comment by pmac** [comment]
Thanks @flodolo. Perhaps I'll reduce the update frequency on prod. It's at 10min everywhere at present, though that doesn't seem to have added any stress to the system, so maybe it's fine.

**Comment by pmac** [comment]
This is now running in prod in us-west. I'll be turning it off later however as I'd like to be more comfortable before leaving it running over the weekend. Will start the real prod test on Monday.

**Comment by pmac** [comment]
I've turned it back off in prod in us-west for the weekend. I'll flip it back on Monday for a full test. So far so good though.

**Comment by pmac** [comment]
This is back on in us-west as of 9:22 am eastern time.

**Comment by pmac** [comment]
This was done a while back but I forgot to close this. Thanks all!
