### ISSUE TITLE
Make winning variants for /new and /firstrun the defaults (FC100)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#4966]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380137

Acceptance criteria :

Pages live w. winning page variants from funnelcake experiment

- /new - set default to content here -  mozilla.org/en-US/firefox/new/?f=100
- /firstrun - set default to content here - mozilla.org/en-US/firefox/51.0/firstrun/?f=99

[Reference experiment data](https://docs.google.com/presentation/d/10Bmnjwtast0kTuiedtMpqZGzywAVJ6Hy9OHI-xtg0QY/edit#slide=id.g21ba0fcb09_0_9)

**Comment by alexgibson** [comment]
@ejregithub - should we begin localization of these new templates? Both feature new strings, so would require translation for all locales Firefox supports. Can those strings be considered final at this stage?

**Comment by alexgibson** [comment]
I should probably also note, the experiment data seems to suggest that /firefox/new/?f=100 performed worse than the current default?

Funnelcake 98 (control) - 3.36% drop-off
Funnelcake 100 - 6.53% drop-off
