### ISSUE TITLE
When Firefox Quits The Browser Turns Black

### ISSUE THREAD

**Issue by valerietrudell** [mozilla/bedrock#4982]
I am an avid user of Firefox Developer Edition, and I have noticed in the last month that when I close Firefox, whether with command + Q or right-clicking the icon in my task bar and clicking Quit, that 
the screen goes black and is completely black shortly before it is completely exited. It doesn't do this when I exist via the quit button within the browser - I think that's because the browser hasn't fully shut down all the way. If it matters, my operating system is macOS Sierra 10.12.5.

I thought I would just let you know.

**Comment by alexgibson** [comment]
Hi, This repository is for the website www.mozilla.org. If you wish to file a bug for Firefox itself, you can do so by following this link:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

Thanks
