### ISSUE TITLE
Auckland space information is out of date

### ISSUE THREAD

**Issue by heycam** [mozilla/bedrock#4993]
The Auckland office recently moved to a co-working space, so the details of the Auckland space at https://www.mozilla.org/en-US/contact/spaces/auckland/ should either be updated or removed.

**Comment by heycam** [comment]
@kentuckyfriedtakahe How should these details be updated?

**Comment by timdream** [comment]
@heycam Submit a pull request :)

**Comment by heycam** [comment]
I would but I'm not sure if the entry should be updated or removed...

**Comment by ajomadlabs** [comment]
Can I take up this issue ? I would love to solve this as I'm a first timer

**Comment by jpetto** [comment]
> Can I take up this issue ? I would love to solve this as I'm a first timer

I think we're still waiting on direction - to remove or update the entry. What do you think @heycam?

**Comment by fmarier** [comment]
The office has closed permanently and has been removed from Mana.

**Comment by alexgibson** [comment]
This was updated in #5116, closing.
