### ISSUE TITLE
Update Berlin space info

### ISSUE THREAD

**Issue by wagnerand** [mozilla/bedrock#5014]
The Berlin office moved! The new address is:

GSG-Hof Schlesische Straße
Gebäude 3, 4. Obergeschoss
Schlesische Straße 27
10997 Berlin

See also: http://www.openstreetmap.org/node/4996803917#map=19/52.49947/13.44914

**Comment by craigcook** [comment]
Resolved in https://github.com/mozilla/bedrock/commit/408808ad2c4296a7bf2505d078b536fc41cb2118. Thanks!
