### ISSUE TITLE
Upgrade Django to latest 1.11

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5080]
1.11 is the next LTS release and we should move to it. This covers upgrading Django and all other libs required to be updated to support it.

**Comment by click4code** [comment]
Hi

I am interested in this issue. Please tell me how to proceed?

**Comment by pmac** [comment]
This is going to be a lot of work I'm afraid. If you're an experienced Django developer then feel free to give it a shot, but I expect it to be a rather large project as some 3rd party library updates will potentially require major changes.

**Comment by NdagiStanley** [comment]
Hi @pmac 
What's the progress of this issue?

**Comment by Hasan-Ahmad** [comment]
I think we should upgrade to 2.0, it makes life a lot easier with its new syntax

**Comment by NdagiStanley** [comment]
True. It's best we upgrade to version 2.0

**Comment by NdagiStanley** [comment]
@pmac could we create a branch for this upgrade to `Django 2` so that we can collaboratively make this upgrade?
cc @Hasan-Ahmad @click4abhishek 

I'll shift the base of the PR I have raised to that branch.

Cheers.

**Comment by angelpongo** [comment]
Thanks

**Comment by StephenOrJames** [comment]
I would advise against Django 2 for now, especially since it drops support for Python 3 (this repository is still using Python 2). Everything needs to be made Python 3-compatible first, which is, itself, a large challenge (e.g. some packages need to be updated (e.g. some of the current packages are Python 2-only, but have later versions that support Python 3), imports fixed (explicit relative imports, `urllib`/`urlparse` to `urllib.request`/`urllib.parse`), `cStringIO.StringIO`/`StringIO.StringIO` to `io.BytesIO`/`io.StringIO` (as appropriate), etc.

**Comment by angelpongo** [comment]
Thanks for the heads up

**Comment by pmac** [comment]
We do want to get to Django 2 eventually, but for now the best path forward is 1.11. @StephenOrJames is right that it will be quite a lot of work to get to Python 3. I think it's going to be a good bit of work to get to 1.11 even.

**Comment by BojanKogoj** [comment]
As a reminder, Django 1.8 LTS has ended a few days ago (1 April 2018) according to https://www.djangoproject.com/download/#supported-versions

If I understand correctly the plan is:
-  Django 1.11 with Python 2.7
-  Django 1.11 with Python 3+
-  Django 2+

**Comment by NdagiStanley** [comment]
I guess @BojanKogoj. @pmac, right?

**Comment by pmac** [comment]
Looks like you are right. We'll be accellerating the move to 1.11 this quarter. Thanks for the reminder.

**Comment by NdagiStanley** [comment]
@pmac I'm curious. How did this go?

**Comment by pmac** [comment]
Still not done :( We're going to do [kitsune](https://github.com/mozilla/kitsune/) first and then bedrock.

**Comment by NdagiStanley** [comment]
On this issue? https://github.com/mozilla/kitsune/issues/3177

**Comment by pmac** [comment]
We have finally completed this! It went live earlier this week. It was done in #7135

**Comment by metadave** [comment]
cc @SmileyChris 1.1 is in prod
