### ISSUE TITLE
Create a more elegant solution to serving different /new templates

### ISSUE THREAD

**Issue by jpetto** [mozilla/bedrock#5094]
Our current ["system" for determining which template to serve for all the `/new` variations](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L501) has some serious code smell.

We need to figure out a more scalable, readable, and sane method of determining which template to serve.

Initial high-level branstorm:

- Create a dictionary mapping experience names (e.g. `youdoyou` and `fast`) to another dictionary containing template base directory (e.g. `firefox/new/sem/secure/`) and *another* dictionary of variants to locales.
- Create a method that takes a scene, and experience, a locale, and a variation that iterates over the above dictionary (probably calling `lang_file_is_active` for each) and returns the appropriate template.

This would let us modify available templates just by editing the top-level dictionary.

Something like:

```
new_choices = {
    'youdoyou': {
        'template_root': 'firefox/new/fx-lifestyle/you-do-you/'
    },
    'batmprivate': {
        'lang_file': 'firefox/new/batm',
        'template_root': 'firefox/new/batm/',
        'variations': {
            'b': {
                'locales': ['en-US'],
                'scenes': [1],
                'template_root': 'firefox/new/batm/machine/'
            }
        }
    }
}

def choose_a_new(scene, experience, locale, variation):
    # default to canonical template
    template = 'firefox/new/scene{}.html'.format(scene)

    for key, choice in new_choices.iterItems():
        if choice.get['variations']:
            # do some semi-nasty logic to figure out if we serve a variation
        else:
            if choice.get['lang_file', None]:
                if lang_file_is_active('firefox/new/batm', locale) and key == experience:
                    template = choice.get['template_root'] + 'scene' + scene + '.html' # pseudo code!
            elif locale == 'en-US' and key == experience:
                    template = choice.get['template_root'] + 'scene' + scene + '.html' # pseudo code!
                
    return template
```

This would require some restructuring/standardization of the file system to make sure all templates are named either `scene1.html` or `scene2.html`.

Happy to hear other suggestions!

**Comment by jpetto** [comment]
Would love @pmac's thoughts on this one.

**Comment by pmac** [comment]
I do love anything that makes this easier to maintain through naming convention. I'm all for someone putting together a PR for this and we can discuss there. Your proposal above sounds like a great start.

Notes: We have a `template_is_active` that will auto-discover the lang file(s) in use, but perhaps you don't want to use that to be more specific?

**Comment by pmac** [comment]
@alexgibson doing some ticket gardening. I think much has changed since this was filed. Do you think we still need this?
