### ISSUE TITLE
Display Page titles in the Next and Previous buttons

### ISSUE THREAD

**Issue by mish24** [mozilla/bedrock#5101]
The documentation is built using Sphinx, and I think it'll be a good update if the page titles are written instead of `Prev` and `Next`.

**Comment by sagar-kalra** [comment]
Can you please elaborate about which navigation arrows are you talking about?

**Comment by jpetto** [comment]
I'm guessing this is referring to the "Next" and "Previous" buttons at the bottom of each page of our docs, e.g. scroll to the bottom of our [Localization](http://bedrock.readthedocs.io/en/latest/l10n.html) docs.

@mish24 Are these the buttons you are referencing?

**Comment by mish24** [comment]
Yes @jpetto. I think it will be better if the page titles are shown, plus I'll make it responsive too! If it is fine I would like to add this feature.

**Comment by jpetto** [comment]
I believe the docs are already responsive. Can you elaborate on what you mean?

**Comment by alexgibson** [comment]
I believe the original requester means the "Next" and "Previous" button labels at the bottom of each docs page e.g. http://bedrock.readthedocs.io/en/latest/install.html#installation

I'm not entirely clear if this text is something you can configure using Sphinx

**Comment by gpetrioli** [comment]
Just a heads up, @alexgibson according to http://www.sphinx-doc.org/en/stable/templating.html#next it seems like it is customizable (*and since the title of the next/previous section is already set as the `title` attribute of the link it should not be that hard to move it to the actual text*).

**Comment by shikhar-scs** [comment]
@gpetrioli @jpetto 
If this issue is still up, can I please work on it?

**Comment by gpetrioli** [comment]
@shikhar-scs i am not a contributor to the project, so i cannot comment on this.

Better wait for @jpetto to answer on availability and whether this issue is wanted.

**Comment by alexgibson** [comment]
The issue here is still open, so by all means submit a pulle request :)

**Comment by shikhar-scs** [comment]
Thanx @alexgibson . I'll work on this and file a PR soon. :+1:

**Comment by shikhar-scs** [comment]
@alexgibson what I am doing is replacing the words Previous and Next (because given the arrow directions, they are a bit too obvious) with the respective titles of the page previous and next to the current page. 
Is that fine?

**Comment by alexgibson** [comment]
That sounds good, we can review your code once you open a PR. Thanks

**Comment by divyabaid16** [comment]
@shikhar-scs , are you still working on this issue or can I take it ?

**Comment by shikhar-scs** [comment]
Actually I'm a bit pre occupied , so sure go on @divyabaid16

**Comment by obviyus** [comment]
Hey @alexgibson, may I work on this?
