### ISSUE TITLE
Is it possible to start loading the FxA iFrame earlier?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/bedrock#5104]
Hey @alexgibson @jpetto,

Is it possible to start loading the FxA iFrame earlier on the first run? In our metrics we are experiencing really slow loading times for users with slow connections. We are already working on ways to speed up things on our end but looking into this problem in this repository should make a better experience for Firefox 57 users. In the screenshots below you can see that the iFrame is not loading until some other resources are loaded, such as the 2 Fira fonts. 

Firefox loading (fast internet): 

![image](https://user-images.githubusercontent.com/128755/30277866-101b48ee-96d7-11e7-9d4a-a32d775add20.png)

Chrome loading (throttled 3g connection):

![image](https://user-images.githubusercontent.com/128755/30278121-a03d1024-96d7-11e7-8d08-9e08d44b5fad.png)

cc @shane-tomlinson

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/5180

**Comment by alexgibson** [comment]
A quick search shows the iFrame is being loaded on DOM ready: https://github.com/mozilla/bedrock/blob/master/media/js/firefox/firstrun/firstrun.js#L64-L68

I'm guessing this mainly for the sunrise animation. Without actually digging in, I can't see why the iframe couldn't be initialized earlier, unless there is some unforseen jank that was worked around for example. Still, I don't see why we couldn't try and improve it by initializing as soon as the JS is excecuted. I'd be happy to file a bug for this if it helps your efforts.

Fwiw, I believe `/firstrun` is being redesigned soon for the upcoming Firefox 57 release. I don't know any details on what the page will look like, or if it will still animate in the same way.

**Comment by vladikoff** [comment]
> Fwiw, I believe /firstrun is being redesigned soon for the upcoming Firefox 57 release.

Who would have the details on this? I thought the Sunrise animation was the one for 57. cc @jpetto

**Comment by alexgibson** [comment]
> Who would have the details on this? I thought the Sunrise animation was the one for 57.

Yeah, so did we. All we know for now is it will be aligned with some of the Photon branding. It's currently with the design teams afaik.

**Comment by vladikoff** [comment]
>  with the design teams

@alexgibson is there someone we can ask on that team?

**Comment by alexgibson** [comment]
Let me try and find out who's working on it. Said bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1397532

**Comment by alexgibson** [comment]
@vladikoff design & UX:

https://phonebook.mozilla.org/?search/rwong
https://phonebook.mozilla.org/?search/cseabolt

**Comment by vladikoff** [comment]
Thanks @alexgibson !!

**Comment by vladikoff** [comment]
cc @davismtl

**Comment by davismtl** [comment]
@alexgibson The upcoming firstrun design are experiments around testing copy for subscriptions.

By no means is it a sure thing that it will perform better than the current experience. In fact, we have a few other experiments also planned around asking email first for example.

In the meantime, we should not assume that any of these experiments will win so we should optimize the iFrame loading speed. On a slow internet connection, it can take 22 seconds for the iframe to show up. This makes for a horrible experience for 57.

**Comment by alexgibson** [comment]
> The upcoming firstrun design are experiments around testing copy for subscriptions.

I'm not sure what you mean here. The page is being redesigned for 57 (not an experiment afaik).

**Comment by davismtl** [comment]
Small update:
- I've seen the new firstrun page. It is sensibly the same experience but different background and animation.
- Normally, the topic of this bug should still be relevant with that design. There is no reason for us to believe that that design will load our iFrame any faster.

**Comment by vladikoff** [comment]
> different background and animation.

👍

**Comment by alexgibson** [comment]
The `/firstrun` page moved in-product as of Firefox 63. Elsewhere, we've switched to the iframeless form, so I think we can close this issue. Please re-open if needed, thanks!
