### ISSUE TITLE
Is it possible to get an ID on the Download Firefox button(s) - particulary homepage and 

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bedrock#5124]
Is it possible to get a distinct ID on at least the "main" (body of the page) Download Firefox button?

One of my Stub Attribution automation tests broke, and it'd be great if I could rely on a unique ID to key off the Download Firefox button, in https://github.com/mozilla/stubattribution-tests/blob/9af05d2c26aa9585b99363efa14601b5aa6877f3/tests/test_stub_attribution_organic.py#L15?

My tests use the latest Chrome, on Windows 10, through Sauce Labs, so whichever view that is, is my primary use-case.

Something to ```replace fx-download-link```.  Not sure if there's a clean(er) way to do this, without impacting A/B testing?

Thanks!

**Comment by alexgibson** [comment]
@stephendonner try `(By.CSS_SELECTOR, '#download-intro .download-link')`

**Comment by stephendonner** [comment]
@alexgibson no dice: https://gist.github.com/stephendonner/2ce90a04eb82ef2dd7f4338f01937982

**Comment by alexgibson** [comment]
The button already has an ID ('download-intro')

**Comment by alexgibson** [comment]
Seems to work for me when I try locally

**Comment by stephendonner** [comment]
Thanks; I ended up fixing this in https://github.com/mozilla/stubattribution-tests/pull/56
