### ISSUE TITLE
Links to vogue.com in Firefox page should be https://

### ISSUE THREAD

**Issue by Standard8** [mozilla/bedrock#5163]
Seen on twitter: https://twitter.com/nomorehttp/status/914781391124074496

Vogue supports https:// so the vogue links on https://github.com/mozilla/bedrock/blob/7bd8404ad4aa7e3725d2cacde69c149642a8a677/bedrock/firefox/templates/firefox/hub/home.html should be updated to https://

**Comment by alexgibson** [comment]
Thanks for the report
