### ISSUE TITLE
Replace Ember reference in Developer Edition pages with Redux 

### ISSUE THREAD

**Issue by digitarald** [mozilla/bedrock#5171]
Ember somehow slipped in there because we added some features for debugging Ember - but are not using Ember in any fashion!

In several places:

```diff
-can target multiple browsers and is built in React and Ember.
+can target multiple browsers and is built in React and Redux.
```

**Comment by jeffaustin81** [comment]
I made a pull request for this "Fix reference to Ember on Developer Edition page #5174"

**Comment by alexgibson** [comment]
Looks like this was done in #5174
