### ISSUE TITLE
Ember or Redux on Developer Edition page  (PR5174)               

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#5196]
@schalkneethling, are we replace Ember with Redux or the other way round?  

https://github.com/mozilla/bedrock/pull/5174

With the current fix, there is no change for localization: https://transvision.mozfr.org/?recherche=The+new+Firefox+DevTools+are+powerful%2C&repo=mozilla_org&sourcelocale=en-US&locale=de&search_type=strings

**Comment by schalkneethling** [comment]
@peiying2 Oh dang 😿  , yeah. I totally missed that, those paragraphs needs to be switched around. The change is from "multiple browsers and is built in React and Ember" to "multiple browsers and is built in React and Redux"

I will open a PR to resolve that.

**Comment by schalkneethling** [comment]
https://github.com/mozilla/bedrock/pull/5198
