### ISSUE TITLE
[Legal docs]: Firefox Focus/Klar Privacy Notice updates

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#5261]
@pmac 
Could you help push these updates on production? We have one string update in the following two documents (4 files):

-  https://github.com/mozilla/legal-docs/tree/master/focus_privacy_notice
- https://github.com/mozilla/legal-docs/tree/master/klar_privacy_notice

Thank you,
Peiying

**Comment by pmac** [comment]
The submodule in bedrock/master is up-to-date with the legal-docs master branch. If these changes aren't in production they should be shortly as we'll be deploying today I'm sure.
