### ISSUE TITLE
Header menu Bug

### ISSUE THREAD

**Issue by sweatC** [mozilla/bedrock#5276]
Hello, everyone!
I have found that if window width in range 760-777, header menu don`t visible.
![image](https://user-images.githubusercontent.com/15202961/32743842-548715ba-c8b6-11e7-855d-4424ec855b20.png)
In other cases it looks like this: 
![image](https://user-images.githubusercontent.com/15202961/32743889-7340ac14-c8b6-11e7-85ff-e8c6b58ad39f.png)
or like dropdown
![image](https://user-images.githubusercontent.com/15202961/32743921-94571f78-c8b6-11e7-891b-bc06ea2b5a7a.png)

**Comment by georgegillams** [comment]
I can't find this problem anywhere on the site. Could you provide a URL or steps to reproduce this?

**Comment by sweatC** [comment]
@georgegillams here

![image](https://user-images.githubusercontent.com/15202961/32851950-287b792c-ca3f-11e7-9e54-7a27bb8ad166.png)

**Comment by georgegillams** [comment]
Good catch!
This seems to be specific to the mozilla.org/ru (which uses a slightly different style of menu to other versions).
Will take a look tomorrow if someone else doesn't beat me to it 👍

**Comment by alexgibson** [comment]
I believe this is bug https://bugzilla.mozilla.org/show_bug.cgi?id=1401978

**Comment by sweatC** [comment]
@alexgibson it is similar, but in this case it is range (760-777) not the one pixel

**Comment by alexgibson** [comment]
> @alexgibson it is similar, but in this case it is range (760-777) not the one pixel

I just tested this in responsive design mode on the German home page: https://www.mozilla.org/de/

Only at exactly 760px does the nav disappear. It reappears for me at 761px

**Comment by georgegillams** [comment]
@sweatC  the behaviour seems exactly the same on **de** as on **ru**. See gif below - the menu is only missing at that exact width

![ru-de](https://user-images.githubusercontent.com/30267516/32855592-0b7417da-ca3a-11e7-8192-5c927a64d4e3.gif)

**Comment by sweatC** [comment]
I agree, It is kind confusing thing because I have tested it using _google chrome browser_, so when 
I have launched it on firefox it looks like in your gif above.

**Comment by georgegillams** [comment]
All I'm trying to say is this:
The issue you've seen on mozilla.org/ru is the same one as the bug describes on mozilla.org/de

I hope the screenshots below help to clarify this:
![de_ru](https://user-images.githubusercontent.com/30267516/32857728-b8e70908-ca40-11e7-906e-0b74333298e3.png)

**Comment by sweatC** [comment]
@georgegillams  Did you try to test your website using Google Chrome?

**Comment by alexgibson** [comment]
To try and save some back and forth here, this bug will be present in the header on any page, for every non English locale.

**Comment by alexgibson** [comment]
The issue is also only evident at 760px in Google Chrome (the website uses the same breakpoints, regardless of the browser). @georgegillams is correct that this is the same bug as the one I linked to earlier.

**Comment by georgegillams** [comment]
@sweatC  yes I did

Glad we got to the bottom of this. For future issues, it's useful to include what OS / browser you are using, and the URL / steps to reproduce.

😎

**Comment by sweatC** [comment]
@georgegillams I got it 😅

**Comment by pandyamarut** [comment]
I didn't find this sort of problem on the site.
Can you just send me Url? @sweatC

**Comment by sweatC** [comment]
@pandyamarut [you are welcome
](https://www.mozilla.org/ru/)
