### ISSUE TITLE
macOS FirefoxNightly served a Windows Firefox binary with privacy.resistFingerprinting turned on

### ISSUE THREAD

**Issue by robinwhittleton** [mozilla/bedrock#5300]
(hopefully this is the right place to report it)

I went through the flow to get a copy of release Firefox using today’s FirefoxNightly on macOS 10.13.1. Getting to https://www.mozilla.org/en-GB/firefox/new/?scene=2 automatically served me a `.exe` installer, which isn’t very useful to my mac (and indeed popped up an `open in TextEdit?` box).

**Comment by alexgibson** [comment]
Thanks for filing this issue @robinwhittleton 

I can't replicate here. Can you please supply your user agent? (both `navigator.userAgent` and `navigator.platform` would be very helpful)

**Comment by robinwhittleton** [comment]
Worked it out, it’s yet another side-effect from setting `privacy.resistFingerprinting` in about:config. I’d guess in this case there’s little you can do about it if the browser isn’t going to expose data that could potentially be used for malicious purposes. Will leave this open in case it’s something you want to try and address but feel free to close it.

**Comment by alexgibson** [comment]
Ah, yes - I see the issue now. Thanks for the further investigation! 

I'll bring this to the attention of the team for discussion. There may be some extra paths we could provide to manually download a different OS/platform binary on the thank you page.

**Comment by robinwhittleton** [comment]
There wasn’t any progression path once I’d cancelled the unwanted download so that’d be a good idea at least, yep.

**Comment by alexgibson** [comment]
I filed a bug to update the wording for our link to /firefox/all/ on this page, which should help with this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1427724
