### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by lungati** [mozilla/bedrock#5325]
Hi,

Getting the error below when I try to install the base requirements. (HEAD is now at 5235b49db [fix bug 1422094] Updates to Mozilla 2016 Annual report (#5322))

(bedrock) $ pip install -r requirements/base.txt
Collecting Django==1.8.18 (from -r requirements/base.txt (line 1))
  Using cached Django-1.8.18-py2.py3-none-any.whl
Collecting django-pipeline==1.6.8 (from -r requirements/base.txt (line 4))
  Using cached django_pipeline-1.6.8-py2.py3-none-any.whl
Collecting icalendar==3.8.3 (from -r requirements/base.txt (line 7))
  Using cached icalendar-3.8.3.tar.gz
Collecting django-statsd-mozilla==0.3.14 (from -r requirements/base.txt (line 9))
  Using cached django-statsd-mozilla-0.3.14.tar.gz
Collecting statsd==3.1 (from -r requirements/base.txt (line 11))
  Using cached statsd-3.1-py2.py3-none-any.whl
Collecting PyYAML==3.11 (from -r requirements/base.txt (line 14))
  Using cached PyYAML-3.11.zip
Collecting futures==2.2.0 (from -r requirements/base.txt (line 17))
  Using cached futures-2.2.0-py2.py3-none-any.whl
Collecting ipaddr==2.1.11 (from -r requirements/base.txt (line 20))
  Using cached ipaddr-2.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jn/p78b626x0fd82t0wcjw1923r0000gp/T/pip-build-vye28l8h/ipaddr/setup.py", line 19, in <module>
        import ipaddr
      File "/private/var/folders/jn/p78b626x0fd82t0wcjw1923r0000gp/T/pip-build-vye28l8h/ipaddr/ipaddr.py", line 1450
        ip_int = 0L
                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jn/p78b626x0fd82t0wcjw1923r0000gp/T/pip-build-vye28l8h/ipaddr/

**Comment by NdagiStanley** [comment]
@lungati  I also had a `pip install` error when running `pip install -r requirements/base.txt`.

> `pip install -r requirements/test.txt` works on my Mac

The docs [here](http://bedrock.readthedocs.io/en/latest/install.html#installation) insist on running `pip install -r requirements/test.txt` which by extension installs the packages in `requirements/base.txt`. There might be an error on first run of this but a rerun does the trick.

Again ensure the `python` version in `2.7` and that you are in a virtual environment

**Comment by NdagiStanley** [comment]
@lungati if this is no longer an issue feel free to close this issue :)

**Comment by hoosteeno** [comment]
Closing this issue as we've since created a docker install process that should be preferable for most contributors. Please reopen if it continues to block.
