### ISSUE TITLE
Error installing dependancies

### ISSUE THREAD

**Issue by arjunmahishi** [mozilla/bedrock#5346]
I am getting this error while trying to installing dependancies in  base.txt

`In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    jinja2>=2.7 from https://pypi.python.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#md5=cb679acd14423aef56dfff61d6a988f8 (from puente==0.4.1->-r requirements/base.txt (line 94))`

**Comment by NdagiStanley** [comment]
@arjunmahishi I also had a `pip install` error when running `pip install -r requirements/base.txt`.

> `pip install -r requirements/test.txt` works on my Mac

The docs [here](http://bedrock.readthedocs.io/en/latest/install.html#installation) insist on running `pip install -r requirements/test.txt` which by extension installs the packages in `requirements/base.txt`. There might be an error on first run of this but a rerun does the trick.

Again ensure the `python` version in `2.7` and that you are in a virtual environment

**Comment by NdagiStanley** [comment]
@arjunmahishi feel free to close this issue.
