### ISSUE TITLE
Old OS X versions are still working with Firefox with bare minimum mods

### ISSUE THREAD

**Issue by iH85CH001** [mozilla/bedrock#5364]
I had posted this on Twitter originally and got a reply from a volunteer, @FirefoxScout. I was told to post my findings here as a bug report, even though I wouldn't necessarily consider this a bug... I have tested Firefox, and have gotten it to run on many older systems, but 99% of my testing went to 10.8.5. However, with Firefox 57 quantum, it made it even easier for me to make it work on 10.8.5. It required less work than even previous "unsupported" versions did. You literally right click on the Firefox icon, say "show package contents" and navigate to *Firefox.app/Contents/Info.plist and open this file, edit the 

"<key>LSMinimumSystemVersion</key>
	<string>10.9.0</string>"

line to just any number before that, and boom, it worked beautifully. Previously you had to play with about:config and a few things before it would work exactly right, but I'm wondering if I didn't have to do that this time because somehow it carried over from my previous work? Can't say for sure... 

Anyways, if you have problems after the program launch, specifically "this tab has crashed" issues, go to about:config and find the browser.tabs.remote.autostart & browser.tabs.remote.autostart2 and make sure both are Boolean, and set to false. Quit Firefox, reopen and test. If you still have issues, add a new Boolean value for browser.tabs.remote.force-disable and make it true. Quit, relaunch, and it will be beautifully perfect and I've been using it for a long time with no issues, less crashes than when it was officially "supported" lol. 

I don't know why this happens or why anybody thinks that Firefox only works on 10.9+, but I assume its because you're using new SDK's, specifically Xcode, that just automatically sets the value to 10.9+ because Apple is stupid, but, realistically, there's no true reason it can't function as it is currently on older systems.

I'm providing this information in the hopes it will be used for good and bring back support to people on older systems with older computers who can't afford , or want, newer things or softwares. I hope this will be used for good to let the Firefox user base grow, as people with older systems and older computers adopt Firefox as other browsers drop them also. I hope this will allow anybody reading this to learn a few things about OS X, along with Firefox. I just really hope this isn't a trap to get the "bug"/workaround from me, in the desire to use it to "harden" Firefox to purposely cut out old version support for good. Please keep your user base in mind, and please avoid becoming like other companies and alienating long time customers because of a lack of support. There are many reasons I've stayed with Firefox, and this is one of them, so please don't change that now. Thank you in advance and I wish the best of luck. 

Attached is a picture to show it working on 10.8.5.
![drm4v_wv4aabl5-](https://user-images.githubusercontent.com/34756973/34281659-1014843a-e68e-11e7-988f-cdeb48f050c0.jpg)

**Comment by flodolo** [comment]
Hi there, this repository is hosting the code that runs www.mozilla.org, so the report is not in the right place (sorry for the confusion).

I assume the [direction you got on Twitter](https://twitter.com/FirefoxScout/status/943998409521991680) was about allowing you to download Firefox from an unsupported system. 

Note that you can download Firefox from here https://www.mozilla.org/firefox/all/, independently from the system you're using (supported or not).

As for the check on the system: 10.8 is [officially unsupported](https://blog.mozilla.org/futurereleases/2016/04/29/update-on-firefox-support-for-os-x/), not covered by automated tests, so mozilla.org **needs** to stop you from downloading it. 

Changing `Firefox.app/Contents/Info.plist` will lead to unexpected results, and you won't get any help for issues, so it's not something a standard user should do.

**Comment by iH85CH001** [comment]
Sorry for posting in the wrong place, only did what I was told. However no, you're wrong. It doesn't give any "unexpected results" it works perfectly fine, as my personal usage for months has confirmed.
