### ISSUE TITLE
Update styling on https://www.mozilla.org/credits/faq/

### ISSUE THREAD

**Issue by gurumukhi** [mozilla/bedrock#5395]
The credits faq page doesn't look well styled along with current theme of the site, do we have a design available for this page as per new theme?

**Comment by harshitakalsi5** [comment]
Hello. I am new to opensource. I would love to work on this issue. How should I apply for it? Thank You

**Comment by gurumukhi** [comment]
@gerv do we have a designer/dev mentor who can help @harshitakalsi5 here?

**Comment by gerv** [comment]
I think it would just be a case of removing any custom styling and adding whatever the standard styling is. I don't think it needs a mentor specifically.

**Comment by gurumukhi** [comment]
Hey @harshitakalsi5, I checked few other pages and have few suggestion for you:
1. Minimal change - just add 40px top padding (like legal page - https://www.mozilla.org/en-US/about/legal/)
2. If you want to make it look more similar to the rest of website, you can try to make it look something like https://www.mozilla.org/en-US/internet-health/. This should need following changes -
* Change font family of the page heading & invert color and background color of the heading.
* Remove all additional backgrounds added to the page.
* May be, add the horizontal line on top of page.

You will need to bring up your own instance of the project and then try out the any of fixes mentioned above. You can also contact the developers mentioned on wiki (https://wiki.mozilla.org/Webdev/GetInvolved/mozilla.org#Contacts) or commend here if you are facing any issues.

**Comment by harshitakalsi5** [comment]
Okay Sir!! I will do it. Thank You.

**Comment by gerv** [comment]
I suspect a better technique would be simply to make sure it was using the standard markup for the header and footer all the other pages use - however that is done. Then it will have the correct styling now and in the future. Trying to style it manually seems like the wrong approach.

**Comment by alexgibson** [comment]
> I suspect a better technique would be simply to make sure it was using the standard markup for the header and footer all the other pages use - however that is done. Then it will have the correct styling now and in the future. Trying to style it manually seems like the wrong approach.

We're currently mid-way through a redesign of mozilla.org, as well as the creation of a new websites design system to aid facilitating building new pages that reflect our new branding. This page will likely come under that system and is probably relatively low on our list of priorities, but until then you could certainly craft a new page by-hand using the same conventions as other new pages. We won't have any guidelines to help facilitate this however in the interim. If a contributor does want to take this on, they are certainly welcome, but it may require some additional design review / feedback.

**Comment by gurumukhi** [comment]
Lets wait for some more time if we get a PR on this then we will close it.

**Comment by alexgibson** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1444998
