### ISSUE TITLE
Credits page not showing correct 'last updated' date

### ISSUE THREAD

**Issue by gurumukhi** [mozilla/bedrock#5396]
Credits page should show correct 'last updated' date as date of last change made to https://github.com/mozilla/community-data/blob/master/credits/names.csv file.

**Comment by pmac** [comment]
They do currently seem to match. The date displayed is the date that the website picked up the change, so it's the date that the list on the website was updated, which could well be after the date that the underlying data was updated. I think that seems appropriate. If you'd rather it be set to the git modify date of the file then we should be able to do that, but I think what we have is good enough. I'd be happy to review a PR about this however if someone feels strongly enough to make the change.

**Comment by gurumukhi** [comment]
@sagaragarwal94 wanted to work on this, awaiting his reply if he is still interested.

**Comment by hoosteeno** [comment]
Closing this WONTFIX; current solution seems adequate. Reopen if discussion needed.
