### ISSUE TITLE
Push legal updates to production

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#5403]
We have two requests:

1). https://github.com/mozilla/legal-docs/tree/master/firefox_privacy_notice
2). https://github.com/mozilla/legal-docs/tree/master/firefox-cliqz_privacy_notice

**Comment by peiying2** [comment]
@pmac when you get a chance, please help with this push. Thanks a mil.

**Comment by pmac** [comment]
@peiying2 does this need to get to prod today? It's merged to master and should be on www-dev.allizom.org shortly.
