### ISSUE TITLE
sub-nav bar

### ISSUE THREAD

**Issue by amit2rockon** [mozilla/bedrock#5418]
sub-nav of https://www.mozilla.org/en-US/technology/ do not stick with scrolling while other's sub-nav do. i would like to work on this issue if mentored.

**Comment by amit2rockon** [comment]
@marcoscaceres

**Comment by alexgibson** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1444996

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/commit/759560584d68a4d8f4979f59075ad096953d8862

Thanks for reporting!
