### ISSUE TITLE
Video on full screen shows irrelevant data and screen becomes unresponsive

### ISSUE THREAD

**Issue by DivuMarcus** [mozilla/bedrock#5503]
Hi, 
I went to https://www.mozilla.org/en-US/contribute/  and started watching a video named  "See Our Community In Action"on Google Chrome. 
The problem start when I put the video on full screen mode.
The video worked fine but the video was covered with a red tab on top of it and the data of the background of the website in the bottom of the video. Also the page became unresponsive and I was unable to pause or even turn off the full screen mode.
I have attached the screenshots of the issue for some ease.
![screenshot_20180312-195731](https://user-images.githubusercontent.com/36792228/37294741-88132b60-263c-11e8-8d27-440d925d10d2.png)
![screenshot_20180312-195712](https://user-images.githubusercontent.com/36792228/37294742-886707f8-263c-11e8-97fb-849e5f2948fa.png)

**Comment by alexgibson** [comment]
I can reproduce this in Chrome on desktop too:

<img width="1680" alt="screen shot 2018-03-12 at 18 56 00" src="https://user-images.githubusercontent.com/400117/37303691-2a6c758a-2627-11e8-827c-96242f8e63eb.png">

**Comment by alexgibson** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1444995
