### ISSUE TITLE
CompilerError

### ISSUE THREAD

**Issue by yingtaiGithub** [mozilla/bedrock#5514]
I got this error when installing and running bedrock on my local. I followed the instruction of http://bedrock.readthedocs.io/en/latest/install.html

Request Method: | GET
-- | --
http://127.0.0.1:8000/en-US/
1.8.18
CompilerError
[Errno 2] No such file or directory: '/home/zhang/work/WEBSITES-2/bedrock/static/css/pebbles/base/tmpq_g1of'
/home/zhang/.virtualenvs/bedrock/local/lib/python2.7/site-packages/pipeline/compilers/__init__.py in execute_command, line 141
/home/zhang/.virtualenvs/bedrock/bin/python
2.7.12
['/home/zhang/work/WEBSITES-2/bedrock',  '/home/zhang/.virtualenvs/bedrock/lib/python2.7',  '/home/zhang/.virtualenvs/bedrock/lib/python2.7/plat-x86_64-linux-gnu',  '/home/zhang/.virtualenvs/bedrock/lib/python2.7/lib-tk',  '/home/zhang/.virtualenvs/bedrock/lib/python2.7/lib-old',  '/home/zhang/.virtualenvs/bedrock/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/zhang/.virtualenvs/bedrock/local/lib/python2.7/site-packages']

It would be appreciate if you could help me. 

Thanks

**Comment by flodolo** [comment]
Are you following the "Make it run" section? In particular, running `gulp` in parallel with the server.

**Comment by yingtaiGithub** [comment]
The problem was resolved. I missed the instruction 'npm install'. T

Thanks for your comment, flodolo.
