### ISSUE TITLE
Change Common Voice link for Czech language

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/bedrock#5535]
Hi, we have started gathering Czech CV data on our own (https://voice.mozilla.cz). Unfortunately, all links on mozorg lead to voice.mozilla.org. Is it possible to change the URL for Czech localization, or not?

**Comment by alexgibson** [comment]
I see only 2 pages with links to voice.mozilla.org, so we should be able to accomodate this pretty easily: https://github.com/mozilla/bedrock/search?utf8=%E2%9C%93&q=%22voice.mozilla.org%22&type=

**Comment by alexgibson** [comment]
The links aren't in .lang files, they are in templates.

**Comment by MekliCZ** [comment]
And how to do that? I've never contributed to bedrock and I don't know the template system bedrock uses. :(

**Comment by alexgibson** [comment]
Here's an example of how we provide a different `href` for a German blog link: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/home.html#L120
