### ISSUE TITLE
RSS Feed for application relases?

### ISSUE THREAD

**Issue by AdrianKoshka** [mozilla/bedrock#5550]
It'd be really handy to have an RSS feed for releases of applications like Thunderbird and Firefox available from the mozilla.org website.

**Comment by kyoshino** [comment]
This is being discussed in [Bug 1449884](https://bugzilla.mozilla.org/show_bug.cgi?id=1449884).

**Comment by alexgibson** [comment]
Closing this as a duplicate of the bug linked above.
