### ISSUE TITLE
Integration test timeouts on bedrock-dev

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#5561]
Example from https://ci.us-west.moz.works/view/Bedrock/job/bedrock_multibranch_pipeline/job/master/943/testReport/junit/tests.functional.firefox/test_whatsnew/Test_bedrock_dev_oregon_b___firefox___test_send_to_device_fails_when_missing_required_fields/ 

```
tests/functional/firefox/test_whatsnew.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/site-packages/pypom/page.py:93: in open
    self.wait_for_page_to_load()
tests/pages/base.py:22: in wait_for_page_to_load
    self.wait.until(lambda s: 'loaded' in el.get_attribute('class'))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <selenium.webdriver.support.wait.WebDriverWait (session="4609e5e181c44ce49386db84f2228fa3")>
method = <function <lambda> at 0x7f5289061f50>, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       TimeoutException: Message:

end_time   = 1523035849.181287
message    = ''
method     = <function <lambda> at 0x7f5289061f50>
screen     = None
self       = <selenium.webdriver.support.wait.WebDriverWait (session="4609e5e181c44ce49386db84f2228fa3")>
stacktrace = None
value      = False

/usr/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException
```

This has been seen on bedrock-dev on multiple urls and multiple clusters. At first I thought the timeouts might be network related, but given that the failures occur with much greater frequency in the dev environment than we see in stage or prod, I now believe it's likely to be related to a difference in the deployed code. Specifically, when `DEV = True` we [source pontoon.js](https://github.com/mozilla/bedrock/blob/09fd36ef1cdb520f2a9efe393b74af6ed8b22905/bedrock/base/templates/base-pebbles.html#L186-L188) which has been known to cause performance issues in local dev environments.

**Comment by alexgibson** [comment]
While pontoon is a good thought and definitely a possible source of page load timing out, many of the test failures I see point to a different issue. For example, this test here (in the same test run) shows that the site never loads at all, and we get is a blank screen:

https://saucelabs.com/beta/tests/452c7d6ca3d84ae49cb8464e016ffab5/watch#27

Tests on dev have generally been pretty reliable (very rarely orange on us-west) until we recently introduced oregon-b. Nearly all of the oranges I can see in Jenkins are also for that cluster:

https://ci.us-west.moz.works/view/Bedrock/job/bedrock_multibranch_pipeline/job/master/

**Comment by alexgibson** [comment]
Here's another example:

https://saucelabs.com/beta/tests/f6cefd4466d548a1aa735456ae040dca/watch#27

Some of the other failures also seem to headless tests, which wouldn't need to wait to load pontoon:

https://ci.us-west.moz.works/view/Bedrock/job/bedrock_multibranch_pipeline/job/master/930/

Still, I think the suggestion of only loading pontoon on www-dev.allizom.org is maybe a good idea so we can rule it out 👍

**Comment by jgmize** [comment]
We also saw the browser test failures in the other clusters in dev, until we decided to only run the browser test in the us-west-2 region and use headless tests for the other region. The headless test timeouts from a few days ago were likely due to there only being one "dev" pod at the time. We have since scaled bedrock-dev in oregon-b to 5 pods but we were still seeing the browser test failures after that.

**Comment by alexgibson** [comment]
It may be my misunderstanding here, but as far as I understand the previous issues we had we’re with frankfurt/tokyo on stage and prod, and not dev (which was ok at the time).

**Comment by jgmize** [comment]
Thanks @alexgibson, I could be misremembering. I'll do some more research.

**Comment by jgmize** [comment]
There's a possibility that https://github.com/mozilla/bedrock/pull/5565 could help with this, although I would have expected that to affect stage as well-- both bedrock-dev and bedrock-stage point to basket.allizom.org.

**Comment by alexgibson** [comment]
Things are looking pretty green on master since we made the basket/DB changes: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/activity?branch=master

I can't say for sure if the issue is gone, but it potentially signals something that may not be directly related to `Dev=True`?

**Comment by jgmize** [comment]
I agree, this appears to have been slowness related to basket-dev rather than DEV=True on bedrock itself.
