### ISSUE TITLE
Remove links to download-sha1.allizom.org

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#5567]
Now that we have disabled SHA1 and SSLv3 on www.mozilla.org, dropping support for IE on XP SP2 and below, I believe we no longer need the solution implemented in https://github.com/mozilla/bedrock/pull/4413 for [bug 1304538](https://bugzilla.mozilla.org/show_bug.cgi?id=1304538).

According to https://www.ssllabs.com/ssltest/analyze.html?d=download.mozilla.org&s=52.206.66.214&latest download.mozilla.org as currently configured should work with XP SP3, which we still support on www.mozilla.org. Specifically, both sites still support TLS 1.0 and do not require SNI. Note that for IE6 users, TLS 1.0 must be [enabled in the browser](https://warwick.ac.uk/services/its/servicessupport/web/sign-on/help/enable-tls/).

**Comment by jgmize** [comment]
@jvehent do you agree that this should be safe?

**Comment by alexgibson** [comment]
I'll happily work on this as soon as time allows. Added to our Kanban board 👍
