### ISSUE TITLE
Move feature switch distribution to the DB

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5583]
It would be easier, faster, less disruptive, and more reliable to distribute at least the feature switches via the database. It would work like so:

1. A management command would pull/update the [www-config repo](https://github.com/mozmeao/www-config)
2. Said management command would load the config values from the `*.env` file appropriate to the app (dev, stage, or prod) into a database table
3. The switch functions in bedrock would look for a configuration by name in the environment, then database, then return the default (value of `settings.DEV`).

I'd also like to look into the possibility of distributing other settings changes in this way if possible. I know there are 3rd party django apps out there for storing general settings in the DB, but I'm not sure if any are simple enough for what we want and also support loading overrides from the environment.

**Comment by jpetto** [comment]
For my edification, why is distributing a DB faster & easier than our current `.env` file process?

Why would we still check for an `.env` file first?

**Comment by pmac** [comment]
> For my edification, why is distributing a DB faster & easier than our current .env file process?

The `.env` file is used in local dev, but not in production. The servers only pull values from the environment. In order to update the environment variables all of the servers have to be restarted. This works fine, but is a bit slow and more cumbersome and slightly more risky than updates in the database which we already do every 5 min.
 
> Why would we still check for an .env file first?

We'd still want to support local dev via the `.env` file as well as possibly other methods of using that file in docker or other situations. We wouldn't ship secrets in the database for example, so those settings still need to come from the environment.

**Comment by pmac** [comment]
Also it'd mean the config would come with the db, so you could pull a prod DB and easily inspect what's going on.

**Comment by pmac** [comment]
I've closed #5584 as I think the right direction is to separate "static" configs from "dynamic" ones. That is configs that are only updatable via an app restart, and those that can be updated while the site is running. Basically the dynamic ones are waffle switches and funnelcake settings, and static are everything else. See https://github.com/mozmeao/www-config/pull/94

**Comment by pmac** [comment]
@alexgibson @jpetto @craigcook @stephaniehobson 

The PRs for bedrock and www-config to make this happen are in (linked above). I'd love your feedback on this change. Is the distinction between "static" and "dynamic" settings to subtle? They seem straight forward to me, but I'm close to all of this code. It would mean no more having to keep a list of deleted switches around, you'd just delete the line and they'd be gone. But Alex pointed out on IRC that it would mean that the change would roll out (only for dynamic settings like switches) as soon as the merge to master happened, so you'd need 2 PRs if you wanted to do staging separately.

**Comment by jpetto** [comment]
I'm on board with this change. Even though 2 PRs would be necessary if we wanted to test staging before prod, we will also be saved from having to do the config push, so it's essentially the same number of steps (fewer if we _don't_  need to test stage first).
