### ISSUE TITLE
CVE json feed needs to reference the advisories, too

### ISSUE THREAD

**Issue by dveditz** [mozilla/bedrock#5590]
Each CVE item in the cve.json feed contains the references we list in the advisories, but those are often to closed bugs. MITRE wants a reference to where the CVE itself was published which would be a link to the advisory itself. We need to add that to each item in addition to any references we've explicitly listed in the .yaml files.

Sometimes the same CVE appears in two different .yaml files (e.g. affects both Firefox and Firefox ESR) and you've merged those into a single CVE item so hopefully it won't be too hard to add both  advisories as references.

**Comment by pmac** [comment]
That should be possible. I'll get on this soon.

**Comment by dveditz** [comment]
thanks!
