### ISSUE TITLE
Enable HTTP2 Server Push

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5603]
We can do this via Cloudflare via [Link headers in our responses](https://www.cloudflare.com/website-optimization/http2/serverpush/). All we'd need to do is to add a static asset function that wraps the current one that adds the asset URLs to a list that can be added to the response headers, much like [django-static-push](https://www.cloudflare.com/website-optimization/http2/serverpush/) does (though we may not be able to use that because it's not Jinja enabled).

**Comment by alexgibson** [comment]
@pmac this is an old issue, but I’d like to propose we close it as wontifx. HTTP/2 server push has been deprecated in Chrome, mainly through lack of adoption.

From my (limited) understanding, it’s one of those things that’s pretty difficult to get right, but too easy to get wrong.

https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1

https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

**Comment by pmac** [comment]
That sounds right to me too. Thanks for following up.
