### ISSUE TITLE
Redundency in the Acceptable Use Policy

### ISSUE THREAD

**Issue by Jayman2000** [mozilla/bedrock#5614]
The 8th sub-bullet of the final bullet of the [Acceptable Use Policy](https://www.mozilla.org/en-US/about/legal/acceptable-use/) redundantly lists religion twice.

> …encourages prejudicial action against someone or a group based on age, gender, race, ethnicity, national origin, **religion**, sexual orientation, disability, **religion**, geographic location or other protected category or constitutes hate speech

**Comment by alexgibson** [comment]
@Errolyn it looks like to fix this in bedrock we'll need to update the legal-docs git-submodule and issue a PR to bedrock. It looks like we're lacking any documentation for doing this, so I'll see if I can put something together in a PR.
