### ISSUE TITLE
iOS Adjust Flow Fix

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5629]
[Description of issue](https://docs.google.com/document/d/1Cf7860EXtW4q4BFFKYpwkEZWE4hV44CgZdIKTp19G04/edit)

**Comment by ejregithub** [comment]
Met with Aaron/Jon/Devyani to clarify what can be done.  Jon is unblocked, able to create the fallback URL that will eliminate the 'no where state' when clicking cancel and to use js to automagically forward the user to the appstore.

**Comment by alexgibson** [comment]
Closing old issue
