### ISSUE TITLE
Update /enterprise & /organizations Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5630]
- [Tracking Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1457975)
- https://github.com/mozilla/bedrock/pull/5665

**Comment by stephaniehobson** [comment]
PR #5665 

Will need a follow up PR to toggle the switch. I'll submit the PR.

It's scheduled to go live at 5:30 am PT on Wed May 9th. @jpetto has volunteered to take one for the team by pushing it.

**Comment by stephaniehobson** [comment]
The config change for tomorrow: https://github.com/mozmeao/www-config/pull/100
