### ISSUE TITLE
Firefox Accounts iFrame-Less

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5640]
- [Tracking Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1446023)

**Comment by jpetto** [comment]
The blocking FxA issue: https://github.com/mozilla/fxa-content-server/issues/5882

**Comment by ejregithub** [comment]
@jpetto - @hoosteeno just indicated that FxA issue: mozilla/fxa-content-server#5882 is now closed. Please pick this back up when ready.

**Comment by jpetto** [comment]
Blocking this for now while we decide a strategy for implementation in regards to localization.

We control `/firstrun/` until Fx 62, which is slated for 9/5. Do we want to hold off on implementing the new form on `/firstrun/` until all localizations are complete? Or do we want to put it behind and L10n tag? Probably the latter, but want confirmation before changing the PR.

**Comment by hoosteeno** [comment]
If we can launch at least one locale then we can measure the impact of this work, which may be significant. That would be a nice measure to have. That would optimally be done with a split test, but if some implementation detail makes that impossible, we can get by with a before/after analysis.

**Comment by hoosteeno** [comment]
> will this new form be displayed to non-Firefox users?

As things stand, the firstrun page's animation never runs for non-Firefox users, which means the form never appears. On firstrun we can replicate that behavior for the new form (or whatever expedient alternative produces the same result). 

Going forward, it will probably be a question we have to address for each form factor. E.g., if we put an account signup form in the header where the big green button is, then non-Fx gets the button, Firefox gets the form. If we put it in the footer, then non-Fx gets nothing, Firefox gets the form. Etc.

**Comment by ejregithub** [comment]
Per discussion with Jon, this needs a final sign-off from Vladikoff on the fxa team, but it is ready for review

**Comment by alexgibson** [comment]
This is now a thing, and it's in production at `/firefox/accounts`.
