### ISSUE TITLE
Test /firstrun Firefox Accounts With Vertical Content

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5641]
- [Mana Experiment Page](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=72786918)
- [Tracking Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1440486)

**Comment by hoosteeno** [comment]
This card is blocked (I might even say Iceboxed) by the onboarding cross functional team. https://projects.growthhackers.com/u/orgs/mozilla-corporation/projects/FUR/cards/FUR-6

**Comment by alexgibson** [comment]
Given that this page is moving in-product, I'd say we wontfix this and close the issue/bug?

**Comment by hoosteeno** [comment]
Yep. No further testing on firstrun.
