### ISSUE TITLE
Moz.org Homepage Experiment - More DL

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5647]
[demo](https://bedrock-demo-shobson.oregon-b.moz.works/en-US/?v=a)

**Comment by ejregithub** [comment]
@vincejoyiv - please provide QA, let us know if we can move to signoff from Janis.

**Comment by ejregithub** [comment]
https://bedrock-demo-shobson.oregon-b.moz.works/en-US/?v=a

**Comment by vincejoyiv** [comment]
lgtm.

**Comment by bensternthal** [comment]
Janis approved via slack. We are good to go.
