### ISSUE TITLE
Informed Consent Experience

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5648]
- [Project Board](https://github.com/mozilla/bedrock/projects/5)
- [Background Doc](https://docs.google.com/document/d/1B3rkPe8Ao28F957BMdvJVu0S0qVHPOfgK_kg2GrcI2A/edit)

**Comment by thejeffreytaylor** [comment]
Backgrounder for ideation session scheduled for Friday 18 May: https://docs.google.com/document/d/1B3rkPe8Ao28F957BMdvJVu0S0qVHPOfgK_kg2GrcI2A/edit

**Comment by alexgibson** [comment]
It looks like this may touch many different parts of the website. Should this have its own sub-project board?

**Comment by bensternthal** [comment]
Absolutely! Updated description with link.

**Comment by thejeffreytaylor** [comment]
Next meeting scheduled for 6 June, with the following agenda: 

During the last meeting we agreed that the next steps for the project are:

1. Define Scope (goals for this project and what would be the success measures)
Consumer Team is working on a brief (due today)

2. Estimate - how big and expensive this could be and what would be pushed to the back log if we would work on this

Let's meet to review both Scope and Estimate

Here is the link to the brief (signed off by Yuliya)
[](https://docs.google.com/document/d/1L7wp3FEPC-JM_EUwHO1WGvaa3aZ20hWezqC-wgrmKeA/edit?usp=sharing)

**Comment by ejregithub** [comment]
Brief review scheduled for Thursday 6/7

**Comment by thejeffreytaylor** [comment]
Flagging as blocked as there's been no word on the next meeting reschedule.
