### ISSUE TITLE
IRL Redesign

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5649]
- [Issues List](https://github.com/mozilla/irlpodcast/issues)
- [Brief](https://docs.google.com/document/d/1PkqcQVAiIsiTcxuY3LBO3Ww0D9V7XQoxJQVxuUDViLA/edit)

**Comment by mrkwvr** [comment]
Link to final IRL Sketch file https://mozilla.box.com/s/2u3vrpmpmwnxty9lwzie1dfq2drrngs2

**Comment by thejeffreytaylor** [comment]
@ejregithub

**Comment by alexgibson** [comment]
@ejregithub can this issue be closed? The sketch file linked above seems to reflect what I see in production.

**Comment by ejregithub** [comment]
@stephaniehobson - i know that Collapsing/shortening the page is still an [open item](https://github.com/mozilla/irlpodcast/issues/65) - are there any others in that irl issues list we should flag here?

**Comment by stephaniehobson** [comment]
I don't know, I wasn't involved in this at all.

**Comment by stephaniehobson** [comment]
We don't have any designs for collapsing/shortening the page but with all the cover art on the homepage the current design has only so-so performance (the players lazy-load, which is good).

We already have season specific pages (https://irlpodcast.org/season1/) so I'll work on something to address #5681 next week.
