### ISSUE TITLE
/privacy Changes & Updates

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5651]
- [Slide Deck](https://docs.google.com/presentation/d/1OjwvxSB5JiMetD2RKVB9f7-n7qjvmPDw0fGi3VhyaQY/edit#slide=id.g38befeb50f_1_6)

**Comment by ejregithub** [comment]
Next step: A developer needs to review the proposed changes for any 'gotchas'.

A separate page is in the works that will need to be linked to in the revised page here that is dependency (the 'Learn more' link in slide 2)

**Comment by ejregithub** [comment]
Splitting this into the following separate cards

#5745 
#5759
#5745
