### ISSUE TITLE
SEO Tweaks: Hreflang Fixes

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5652]
- [Brief](https://docs.google.com/document/d/1p0U9NL-SG2RJZQ562-E0ngEC03NtbREVr4oWsvwljng/edit?ts=5a969658#heading=h.yr6adbipop2y)

lang selector page is being managed in #5827

**Comment by rraue** [comment]
To do:

- [ ] XML Sitemap (include all documents) https://bugzilla.mozilla.org/show_bug.cgi?id=1441250

- [ ] Building a country/language selector page for better crawlability https://bugzilla.mozilla.org/show_bug.cgi?id=1439377

**Comment by rraue** [comment]
Depends on https://github.com/mozilla/protocol/pull/260

**Comment by rraue** [comment]
Depends on #https://github.com/mozilla/bedrock/issues/5827

**Comment by rraue** [comment]
Done
