### ISSUE TITLE
Copywriting Template

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5653]
- [Draft](https://docs.google.com/a/mozilla.com/document/d/16FooAUTz8QanYDSa_LbBLqt6C1PVlh6AH2O5cEWTeps/edit?disco=AAAAB8S1lNY&ts=5aeb9a87&usp=comment_email_document)

**Comment by thejeffreytaylor** [comment]
https://docs.google.com/document/d/16FooAUTz8QanYDSa_LbBLqt6C1PVlh6AH2O5cEWTeps/edit?usp=sharing

**Comment by bensternthal** [comment]
@thejeffreytaylor any other work planned on this phase? Or shall we call it done?

**Comment by thejeffreytaylor** [comment]
Not at this phase. Next step is moving this to a platform like [GatherContent](http://gathercontent.com), but there's a far longer runway for that.
