### ISSUE TITLE
Develop Best Practices For Localizing Images 

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5654]
- [x] 1st step: audit competitor sites to see how they handle localizing images.
- [x] Provide recommendations for moz.org based on audit

**Comment by dzingeek** [comment]
**Link to the audit I did:**
https://docs.google.com/presentation/d/106at95m4nohJcUGxOuSAqVso4YuwPUnlqlJJnSp4490/edit?usp=sharing

**Recommendations:**
- We should create some guidelines around using text in images
- Start to localize the top 3 languages for all images (assuming English, German, and Spanish)
- Involve contributors. Open source all other languages. This is a stretch goal and will take some time to figure out all the logistics. 
- Default to English when a localized image is not available.

**Comment by hoosteeno** [comment]
@dzingeek is this a priority for the brand team that should remain open? If so, can you articulate the next steps? If not, can we close?

**Comment by dzingeek** [comment]
@hoosteeno Clio and I have been in talks with l10n but we don't have a solid solution yet. Let me re-sycn with him next week and get back to you. So for now, let's keep it open.

**Comment by alexgibson** [comment]
Closing old inactive issue
