### ISSUE TITLE
[Due Sept 17] Profile per install feature - MIGRATION scenario informational page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5655]
[Background doc](https://docs.google.com/document/d/1qW4J_ons1ZlKgY1zA_taaRQ_Nk4BK5Afsynhb7gAqRQ/edit#)

Success Criteria:

- [ ] Page w. content informing users in the primary (new profile(s) created) scenario
- [ ] unique URLs for scenario (with a unique query param, etc)
- [ ] page set as no index
- [ ] Timing: pages in place Sept 17th to be seen in 64 Nightly release cycle
- [ ] Must be localized (top 10 in Nightly) for launch

**Comment by ejregithub** [comment]
@peiying2 - flagging the need for l10n with you.  We'll get final copy asap.  The request from product is to have the content in place, localized to top 10 langs, for Sept 5th

**Comment by thejeffreytaylor** [comment]
[Copy deck here](https://docs.google.com/document/d/1Ze-2tnOFJ6b4pMH2MilPC3LADM3_JWwT195JawXdIAU/edit?usp=sharing)

**Comment by thejeffreytaylor** [comment]
Copy is updated. There may be small changes to accommodate design requirements, but the feedback has been implemented.

**Comment by dzingeek** [comment]
@craigcook Use this copy doc 

**Migration Copy Only**
https://docs.google.com/document/d/1Xbqr6_qmPwXi5zWzss57lIyTpGGlI_iRWtOi4SLF3SQ/edit?usp=sharing

**Comment by dzingeek** [comment]
@craigcook **Design tweaks** 

**Header area:**
- [ ] make "An Important Change..." copy smaller and dark red. (see screenshot for reference)
- [ ] make "We detected that you..." copy larger and bold (see screenshot for reference)

**FxA area:**
- [ ] make "Enter your email to..." bold
- [ ] move "by proceeding, you agree.." copy below button (this may not be possible)

Note: can we not have the button on the same "line" as the entry filed?

![screen shot 2018-09-11 at 12 40 05 pm](https://user-images.githubusercontent.com/3740746/45383661-bb912500-b5c0-11e8-846a-503c5790bbb7.png)
![screen shot 2018-09-11 at 12 40 11 pm](https://user-images.githubusercontent.com/3740746/45383663-bb912500-b5c0-11e8-898f-b5fc6572e231.png)

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/profile-migrate/
