### ISSUE TITLE
Update CTA on FxA benefits page to account for different platforms

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5660]
https://bugzilla.mozilla.org/show_bug.cgi?id=1457004

**Comment by stephaniehobson** [comment]
PR #5665

**Comment by stephaniehobson** [comment]
The correct link is in PR #5665 but I have a post-launch task to implement[ option #2 from comment 14](https://bugzilla.mozilla.org/show_bug.cgi?id=1457004#c14).
