### ISSUE TITLE
/whatsnew page 61

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5669]
[wnp61 project board](https://github.com/mozilla/bedrock/projects/2)
[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1463821)

**Comment by ejregithub** [comment]
[Sketch file](https://mozilla.box.com/s/1kl1z375c2hu50jt6zbartzn7e9gbgkv) - @craigcook - we need this up on demo by 6/7, please.

**Comment by JennyDouglas** [comment]
Devyani and I approve the design, with 1 caveat. The LCM team is currently working to get the STDW for Focus and klar. 
What is the drop dead date for US/DE WNP changes on design implemented from the QR code to STDW?
We understand that if we do not meet what that date is, then we continue with the QR code for US and DE on focus/klar for 61.

**Comment by ejregithub** [comment]
We'll proceed as if it will be there  - since we're pretty sure it will need to be done for 62. ;)

We do need time to test (as I'm sure does the LCM team and folks working on basket), so let's consider that and the schedule, in which go live is intended for the 21st. With All Hands in the mix here I think getting the basket IDs on 6/6 would keep us in good shape. BUT, I will defer to @craigcook on this . . .

**Comment by craigcook** [comment]
Sooner is always better than later, but I'd be comfortable with setting the 18th as the very latest we can make a go/no-go decision. 

For now we'll proceed as if we'll have the widget working for Focus and can just update the link at the last minute and still have a few days to test. If we don't have it by then, we use those few days to disable the widget.

**Comment by JennyDouglas** [comment]
@craigcook great, I am going to say, that if we can't get it done and ready to hand off next week sometime, then we push it to 62.
Thanks!
