### ISSUE TITLE
Use bouncer aliases for ESR-Next

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5684]
Now that [bug 1408868](https://bugzilla.mozilla.org/show_bug.cgi?id=1408868) is complete we can use the new `firefox-esr-next-latest-ssl` alias for the ESR 60 (for now) links on /organizations/all/ much like we use `firefox-esr-latest-ssl` for the ESR 52 links now. This should be the final update to remove all version specific bouncer links on the site \o/

**Comment by alexgibson** [comment]
Looks like this was done as part of the new /all page redesign: https://www.mozilla.org/en-US/firefox/all/
