### ISSUE TITLE
Remove all of the Funnelcake experiment code from the site

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5685]
Since the release of Quantum I believe the Funnelcake program is over. This issue covers removing the code as well as checking with stakeholders to make sure that I'm right that it is indeed time to do this.

**Comment by pmac** [comment]
@chrismore do you know if this is accurate?

**Comment by jpetto** [comment]
FWIW, we are running a funnelcake currently for the Facebook container add-on, and we're about to run one for a Facebook video chat initiative.

**Comment by pmac** [comment]
Ah. Perhaps I'm wrong. I was told that post-Quantum the funnelcake builds wouldn't be possible.

**Comment by jpetto** [comment]
I was told the same, but here we are. 🤷‍♂️

**Comment by pmac** [comment]
fair enough :) closing for now then. hopefully we can do this sooner than later.

**Comment by chrismore** [comment]
I am back! (1 month of paternity leave). No, funnelcakes are not dead and they are still possible and they are still being done, but just much more rarely. I am trying to use Shield exclusively unless it is 100% not possible with Shield. Though, there are some experience use cases that a funnelcake is about the only way to test it.

**Comment by pmac** [comment]
Gotcha. Thanks Chris. I definitely heard wrong then. We'll leave this closed. Sheild++ though 👍
