### ISSUE TITLE
careers.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5694]
- [Tracking Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1460718)

### List of Issues For this Phase

- [ ] https://github.com/mozmeao/lumbergh/issues/228
- [x] https://github.com/mozmeao/lumbergh/issues/226
- [x] https://github.com/mozmeao/lumbergh/issues/272
- [x] https://github.com/mozmeao/lumbergh/issues/273

**Comment by ejregithub** [comment]
@stephaniehobson - until we receive new images, let's limit the changes here to the following:
- Update Mozilla logo to match new brand guidelines
- Remove tabzilla
- Update fonts to Zilla Slab

**Comment by stephaniehobson** [comment]
Photos were added to the bug but we need to discuss which ones go where.
