### ISSUE TITLE
Update TestFlight Page With New Logo

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5701]
https://bugzilla.mozilla.org/show_bug.cgi?id=1428365

**Comment by amychurchwell** [comment]
@alexgibson I saw you commented on the original [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1428365) recommending we remove the tabzilla wordmark. If we remove from `firefox/base-resp.html` I see that there are 17 files that use it. Is tabzilla something we are wanting to remove from the site completely?

**Comment by stephaniehobson** [comment]
Yes, it's something we want to remove.

Tabzilla used to be used to give all Mozilla sites one unifying element. It was intended to provide a way for people to navigate between all Mozilla sites. In reality it hardly ever got used. It was never updated when the new branding came in.

**Comment by amychurchwell** [comment]
@stephaniehobson do you think it could break pages if we remove it from the base? At a glance it doesn't not seem to impact layouts.

**Comment by stephaniehobson** [comment]
I'm not familiar enough with the old pages to know. Is there still a link to the mozilla.org homepage if we do that?
