### ISSUE TITLE
Update Leadership page on morning of Wednesday May 30th

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5704]
https://bugzilla.mozilla.org/show_bug.cgi?id=1459803

**Comment by alexgibson** [comment]
I'm buessing this is https://bugzilla.mozilla.org/show_bug.cgi?id=1459803

**Comment by bensternthal** [comment]
@ejregithub can you verify if this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1459803) is the scope of this work?

**Comment by ejregithub** [comment]
That is correct. I've been told of no intent to add the person filling the role as interim. That being said, I will ask again.

**Comment by ejregithub** [comment]
@alexgibson - This has now changed:  The interim leader's bio and pic should be added in place of those being removed for the role.  Lucile is updating the bug with that content.

The update should be made on the day of, not before.  If you (Alex) are going to take this on when assets are provided, please make changes locally, only, and then submit the PR on May 30th.

**Comment by alexgibson** [comment]
> @alexgibson - This has now changed: The interim leader's bio and pic should be added in place of those being removed for the role. Lucile is updating the bug with that content.

> The update should be made on the day of, not before. If you (Alex) are going to take this on when assets are provided, please make changes locally, only, and then submit the PR on May 30th.

I was just adding some missing info to the issue, I didn't volunteer to take it ;)

Please note we can also waffle changes behind switches for timed updates.

**Comment by ejregithub** [comment]
Heh, fair enough.  

The ask was to keep the changes from the public (even in the bedrock repo) til the very day.

**Comment by stephaniehobson** [comment]
This is in production with the low-res photo we were provided.

**Comment by stephaniehobson** [comment]
High res photo received as well as a few bio edits.

@craigcook is uploading the big one to assets.mozilla.net for me 👍
