### ISSUE TITLE
Update content in existing Berlin landing page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5706]
This work request is to update the page https://www.mozilla.org/de/firefox/new/?xv=berlin to feature content used in Phase 2 of the Berlin city campaign

[The new content assets (psd file) are here](https://drive.google.com/file/d/1rJXD56N538wa1KLtHaomGI6pEWaqTms_/view)

[Copy doc](https://docs.google.com/document/d/16JaAiCGBTbM1KjF5HEbiJBC-rW45vbRxVThckuAzbhM/edit)

For this content update, use the psd file name Phase2_BerlinCityCampaign_Landing Page_Desktop_1.psd (along with the layout for mobile)

**Comment by ejregithub** [comment]
@alexgibson - can you please take a look at the design files and proceed with the update if they're up to snuff?  If not, please ping Guy or Candice in this bug with requirements - https://bugzilla.mozilla.org/show_bug.cgi?id=1462076

**Comment by alexgibson** [comment]
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/new/?xv=berlin

**Comment by alexgibson** [comment]
This is blocked on GA requirements for the video interactions. I have needsinfo'd Peter in the bug linked above.

**Comment by alexgibson** [comment]
We now have both GA and final design amands, so removing the blocked label. I'll update here when we're good for final review.
