### ISSUE TITLE
Standardize legal docs naming convention

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#5707]
I hope this is not a complicated task/ask. Right now, the naming convention is inconsistent: https://github.com/mozilla/legal-docs. As a result, they are sorted in two groups. Either capitalized initials or all lower case in file names. 

@pmac

**Comment by bensternthal** [comment]
@peiying2 You should file an issue in that projects repo.  It's specific to those folders and does not touch the bedrock codebase.
