### ISSUE TITLE
Remove user survey from IRL site

### ISSUE THREAD

**Issue by jpetto** [mozilla/bedrock#5710]
Remove when we have enough user responses - (200)

**Comment by ejregithub** [comment]
@thejeffreytaylor do you know how many responses there have been to the survey (and what the mark is for shut off?)

**Comment by jpetto** [comment]
From Slack yesterday (5/29):

> Quick update on the survey: We're at 62 respondents at the moment for the survey re: subscribers. Tyler and I agreed to let this sit a while longer so we can get at least 200.

**Comment by thejeffreytaylor** [comment]
Confirmed. At this rate, I see it being up for 2 more weeks.

**Comment by thejeffreytaylor** [comment]
Survey link here: http://qsurvey.mozilla.com/r/28049_5b0d9c7bf03746.57162654

We're getting about 4 responses per day.

**Comment by craigcook** [comment]
Resolved in https://github.com/mozilla/irlpodcast/issues/74
