### ISSUE TITLE
Automated Pocket Feed On The Mozilla.org Homepage

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#5723]
- [x] - [LDAP account set up request](https://mozilla.service-now.com/sp?id=ticket&table=incident&sys_id=69d005d6dbfadb40809e17e15b961977)

This issue captures pre-reqs to delivering an automated feed of stories from [mozillaHQ](https://getpocket.com/@MozillaHQ) pocket account. It will be unblocked once we reach a decision on the homepage. 

### User Accounts
The current mozilla account is a shared login among a few mozilla employees. This should be a proper ldap account with 2 factor authentication enabled.

1. Request from IT an LDAP user mozillahqpocket@mozilla.com  with Janis and any other folks who need access assigned (they have done this before).
1. Once that is done sign up for pocket via -> `https://getpocket.com/signup/ and choose the "Sign Up with Google" option.`
1. Reach out to either Justin or Matt to migrate the existing account over. 

### Retrieving Data
Below is the note from Matt regarding the API:

> Re: the [API](https://getpocket.com/developer/docs/v3/retrieve) - the endpoint you specified will return you "saves" - basically anything that has saved to the specified account. It will not return you the recommended posts you put on https://getpocket.com/@MozillaHQ. If you want those, you will either need to use the approach Nick outlined -or- if you want to use the API, I think we could provide you access to a non-publicized endpoint that would return the recommended posts in JSON format (similar to the response you referenced).

### Pocket Contacts
* matt@getpocket.com - Can assist with all things technical.
* justin@getpocket.com - Can assist with anything account or community related.

**Comment by ejregithub** [comment]
Submitted service request today to set up LDAP account for Janis.
