### ISSUE TITLE
Microdata of SoftwareApllication and Product is missing required data

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#5725]
https://bugzilla.mozilla.org/show_bug.cgi?id=1460253

**Comment by alexgibson** [comment]
@rraue is this still an issue, or has it been fixed with recent updates?

**Comment by rraue** [comment]
This is still an issue and will be fixed once I get to /new and /firefox. Should be still in the backlock. I am blocked on this by brand, we need first a complete naming system.

**Comment by alexgibson** [comment]
@rraue can this issue be closed yet, or is there still something to do here?

**Comment by rraue** [comment]
Its closed
