### ISSUE TITLE
legal doc: update the template with an URL at the address section

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#5729]
At the end of this doc https://www.mozilla.org/en-US/privacy/, at the address section, we need to add an email address per this update: https://goo.gl/TN7Dt9 (scroll to the end).

**Comment by peiying2** [comment]
@pmac

**Comment by pmac** [comment]
@craigcook is this something that needs to be handled specially due to the "Organization" schema in the markup, or is it pretty simple?

**Comment by craigcook** [comment]
Sorry I missed this ping! It just needs `itemprop="email"` for the schema:

`<span itemprop="email">foo@example.bar</span>`

It might be a little more complicated if you want to make it a mailto link:

`<a href="mailto:foo@example.bar" itemprop="email">foo@example.bar</a>`

http://schema.org/email

**Comment by pmac** [comment]
Thanks craig! I'm happy to go either way. I'm guessing the link way is desired. Is that right @peiying2 ?

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by craigcook** [comment]
> I am new to mozilla. Can I work on this?

Thanks for your interest! Unfortunately it looks like this issue just fell through the cracks. It was later duplicated with https://github.com/mozilla/bedrock/issues/6820 and resolved in 3d256d1b22e91f169261b73f5499e3f66e358f28

If you search for open issues labeled "good first bug" we can try to find something else for you to work on.
