### ISSUE TITLE
Wireframe components for Protocol Design System

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5733]
Please add a description here.

**Comment by alexgibson** [comment]
Should this be something on the Protocol project board, or is this something specific to www?

**Comment by dzingeek** [comment]
Not sure. These components/assets will only live in a sketch file for designers to access when creating wireframes.

**Comment by dzingeek** [comment]
@vincejoyiv I have branched off of Protocol DS in abstract and uploaded a new file (Protocol Wireframe Components). If you could take a look at it and let me know what next steps are, thanks.

**Comment by michaelmccombie** [comment]
Merged!
