### ISSUE TITLE
Microdata of SoftwareApplication and Product is missing required data

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5741]
https://bugzilla.mozilla.org/show_bug.cgi?id=1460253

/cc @ejregithub

**Comment by rraue** [comment]
To test, if we can use js+ld inline I propose @type "organization" as the social media profiles in "sameAs" usually  show up in the knowledgraph box as seen at apple: https://screenshots.firefox.com/CoLyrbEUoiJ4MBtE/www.google.com in the right sidebar.

We currently have "only" twitter and facebook there. Lets see if we get added at least youtube or linkedin as well: https://screenshots.firefox.com/JIRS6iN9rGLyOFDe/www.google.com. If we know that it works, we can talk about the sense of it and which Networks there really should be.

The code for us would be on our homepage: 
<script type="application/ld+json">
	{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "Mozilla",
		"url": "https://www.mozilla.org",
		"logo": "https://www.mozilla.org/media/img/mozorg/mozilla-256.4720741d4108.jpg",
		"sameAs": [
			"https://www.wikidata.org/wiki/Q9661",
			"https://twitter.com/mozilla?lang=de",
			"https://www.facebook.com/mozilla",
			"https://github.com/mozilla",
			"https://www.instagram.com/mozilla/",
                         "https://www.youtube.com/user/Mozilla";
			"https://wikipedia.org/wiki/Mozilla",
			"https://www.linkedin.com/company/mozilla-corporation"
		]
	}
</script>

I am just not sure with the url element if it should be localized or not. For the first test I think we should go withou locale even thought its a redirect.

**Comment by rraue** [comment]
Reopening because of https://github.com/mozilla/bedrock/issues/6949

The test on the homepage was succesful, we can use js+ld instead of microdata and we should. To fix Softwareapllication on /new we need two things:

- [ ] Converting microdata to js+ld and correct all errors (currency)

- [ ] We need an aggregated rating for Firefox, else it will not be displayed in search results but most other downloadpages have this visual advantage

**Comment by rraue** [comment]
The js+ld code including breadcrump and SiteNavigationElement:

```
<script type="application/ld+json">
  [{
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [{
      "@type": "ListItem",
      "position": 1,
      "item": {
        "@id": "https://www.mozilla.org/en-US/",
        "name": "Mozilla"
      }
    },{
      "@type": "ListItem",
      "position": 2,
      "item": {
        "@id": "https://www.mozilla.org/en-US/firefox/",
        "name": "Firefox"
      }
    },{
      "@type": "ListItem",
      "position": 3,
      "item": {
        "@id": "https://www.mozilla.org/en-US/firefox/new/",
        "name": "Download Firefox"
      }
    }]
  },
  {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Firefox",
    "description": "Download Mozilla Firefox, a free Web browser. Firefox is created by a global non-profit dedicated to putting individuals in control online. Get Firefox for Windows, macOS, Linux, Android and iOS today!",
    "sameAs": [
          "https://www.wikidata.org/wiki/Q698",
          "https://twitter.com/firefox",
          "https://www.instagram.com/firefox/",
          "https://www.youtube.com/user/firefoxchannel",
          "https://en.wikipedia.org/wiki/Firefox"
      ],
    "operatingSystem": [
    "Windows",
    "MacOS",
    "Linux",
    "Android",
    "iOS" ],
    "url": "https://www.mozilla.org/en-US/firefox/new/",
    "image": "https://www.mozilla.org/media/img/logos/firefox/logo-quantum-high-res.cfd87a8f62ae.png",
    "softwareVersion": "66.0.2",
    "releaseNotes": "https://www.mozilla.org/en-US/firefox/66.0.2/releasenotes/",
    "applicationCategory": "Browser",
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.6",
      "ratingCount": "8864"
    },
    "offers": {
      "@type": "Offer",
      "price": "0.00",
      "priceCurrency": "USD"
    },
    "author": {
        "@type": "Organization",
        "name": "Mozilla",
        "url": "https://www.mozilla.org/en-US/",
        "logo": "https://www.mozilla.org/media/img/mozorg/mozilla-256.4720741d4108.jpg",
        "sameAs": [
          "https://www.wikidata.org/wiki/Q9661",
          "https://twitter.com/mozilla",
          "https://www.facebook.com/mozilla",
          "https://github.com/mozilla",
          "https://www.instagram.com/mozilla/",
          "https://www.youtube.com/user/Mozilla",
          "https://wikipedia.org/wiki/Mozilla",
          "https://www.linkedin.com/company/mozilla-corporation"
      ]
    }
    
  },
  {
    "@context": "http://schema.org",
    "@type": "SiteNavigationElement",
    "name": [
        "Firefox for Windows",
        "Firefox for Mac",
        "Firefox for Mobile",
        "Firefox Releasenotes",
        "Firefox Features",
        "Firefox Accounts"
    ],
    "url": [
        "https://www.mozilla.org/en-US/firefox/windows/",
        "https://www.mozilla.org/en-US/firefox/mac/",
        "https://www.mozilla.org/en-US/firefox/mobile/",
        "https://www.mozilla.org/en-US/firefox/66.0.2/releasenotes/",
        "https://www.mozilla.org/en-US/firefox/features/",
        "https://www.mozilla.org/en-US/firefox/accounts/"
    ]
}
  ]
  </script>
```

The locale relative urls must be different in every locale of course. I double checked the code obove with the structured data testing too of google and with visual studio code but as it got quite long it would be great if someone could review it again.

**Comment by rraue** [comment]
For the aggregated rating we need an easy solution, as we dont have reviews on our page. I think just a weekly updated aggregated rating of our iOS and Android reviews would definetely do the job. Opinions? If we wnat it a bit more sofisticated, we could crawl once in a while all the download and review pages and store their ratings, but I think thats a bit too much work for a test.

Benefit will be a listing like this ins earch results:

![image](https://user-images.githubusercontent.com/36700618/55877122-802bf880-5b99-11e9-96bc-c5d407d536c7.png)

**Comment by hoosteeno** [comment]
@rraue Reading through this card, it sounds like the original bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1460253) and the original issue have been resolved. Is that true?

Near the end, we had a sort of [separate request](https://github.com/mozilla/bedrock/issues/5741#issuecomment-481662145), which was for a subsystem to scrape an aggregated rating from app stores. Do you agree? Could we maybe close this issue and create a new issue for that subsystem?

**Comment by hoosteeno** [comment]
@raue, barring input from you, I'm closing this issue. If desired, please create a new issue for a subsystem to scrape app stores.

**Comment by raue** [comment]
folks, pls, keep an eye on the user ID you are using, because @rraue is somebody else than @raue (that's me).

thanx

**Comment by pmac** [comment]
Sorry. Yes. @rraue is the one I'm sure we meant here.
