### ISSUE TITLE
2nd Homepage Test Experiment Analysis

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5742]
In #5647 the test (with sticky download button at the top of the homepage) was put in place and started on May 18th.  We need analysis of the data once a sufficient number of sessions has been reached. 

Ref:  The original test ran fromApril 16 - 23 with 31.5k session to A and 31.2k to B.

**Comment by ejregithub** [comment]
@peterGerman - I've schedule a review of the results w. Janis et al on Thursday May 31st

**Comment by peterGerman** [comment]
Tomorrow we'll be reviewing this -> https://datastudio.google.com/open/1orTezUq_EzXktFfmUMrMdBnHDJXapQsv

**Comment by alexgibson** [comment]
Closing old issue
