### ISSUE TITLE
Data Privacy page content updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5745]
Intended go live 6/26

[Reference doc](https://docs.google.com/presentation/d/1OjwvxSB5JiMetD2RKVB9f7-n7qjvmPDw0fGi3VhyaQY/edit#slide=id.g29b8722ab_017)

DO: Slides 2-6

- [x]  - Header and copy for Our Privacy Notices
- [x]  - Product Privacy Notices
- [x]  - Get Involved
- [x]  - Add section 'Transparency' in side principles section under Get Involved

**Comment by stephaniehobson** [comment]
I have some questions about the links for the privacy notices. I posted some to the slide document and some on IRC, depending on who I thought could answer. 

Archiving the notices is more complicated than just moving a page unfortunately.

**Comment by stephaniehobson** [comment]
Blocked by answers on how to archive privacy notices.

**Comment by ejregithub** [comment]
@stephaniehobson - for the archival of the Firefox Marketplace privacy notice please:

- [ ]  Create the page https://www.mozilla.org/en-US/privacy/archive/firefox-marketplace with the privacy notice template and the content [here](https://www.google.com/url?q=https://github.com/mozilla/legal-docs/blob/master/marketplace_privacy_policy/en-US.md&sa=D&ust=1527878804076000&usg=AFQjCNGACs7QIsjGL0pMyZTlHh6vTwzVPQ) changing the date from "January 14, 2015" to "Archived, January 2015"
- [ ]  Add a section 'Firefox Marketplace' in https://www.mozilla.org/en-US/privacy/archive/
and create the line item  "January 2015", linking to the archive page created above.

**Comment by ejregithub** [comment]
For the Firefox TV privacy notice, please link to: https://www.mozilla.org/privacy/firefox-fire-tv/ 

Note that this currently redirects to the Focus privacy notice. Legal (mfeldman@mozilla.com) stated in email that they (Legal) will remove the redirect when they create the actual page/content for fire-tv.

**Comment by stephaniehobson** [comment]
I've lost access to the reference doc. I need it to complete my work. I've requested it again.

**Comment by stephaniehobson** [comment]
Oh, we've been working from a copy of that doc and I still have access to the copy.

**Comment by stephaniehobson** [comment]
Unblocked with help from Eric and pmac :)

**Comment by stephaniehobson** [comment]
Blocked on what to archive for the Cloud Services link now. I asked the question in the slide deck.

**Comment by ejregithub** [comment]
I talked to Mika, who said we can simply remove the line item for Cloud Services. There’s no need to archive since the active link goes to the current Firefox privacy policy.

**Comment by stephaniehobson** [comment]
The first to do item depends on the FAQ changes and will be handled in https://github.com/mozilla/bedrock/issues/5759

**Comment by ejregithub** [comment]
Blocked on FAQ

**Comment by thejeffreytaylor** [comment]
Unblocked after meeting with Mika clarified all issues and I proofread and updated all copy. 

1. We got clear on the on-page language within the slide deck. 

2. We agreed to let the FAQ stay in the current format until the Informed Consent experience that is in progress is more "baked".

**Comment by ejregithub** [comment]
@stephaniehobson @alexgibson - Mika indicated that yes, we do need to archive the DE version of the Cliqz privacy policy.
