### ISSUE TITLE
/channel/desktop page content update

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5746]
In https://www.mozilla.org/en-US/firefox/channel/desktop/

- Update copy on /channel/desktop for:
  - [x] Beta
  - [x] Dev Edition
  - [x] Nightly
- [x] Link new copy to https://www.mozilla.org/en-US/privacy/firefox/#pre-release

Copy as discussed in comments on the Google Slides doc: 
"Beta/Nightly is an unstable testing and development platform. By default, Nightly sends data to Mozilla — and in some cases to our partners — to help us find and fix problems. <a href="https://www.mozilla.org/en-US/privacy/firefox/#pre-release">Learn what data is shared.</a>"

(Updated June 25 by @stephaniehobson)

**Comment by alexgibson** [comment]
> Create new "pre-release" section of copy at the bottom of the main content

How should this new section look, and where exactly should it go in terms of the content order? Above the newsletter, after the Nightly section? Should it need to stand out visually in some way?

**Comment by ejregithub** [comment]
Eric to consult with Mika on this (the added copy and not linking to telemetry)

**Comment by stephaniehobson** [comment]
This is up on demo now: https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/channel/desktop/

@ejregithub Can you please check in with the client to make sure what's there is okay?

**Comment by stephaniehobson** [comment]
Also, note, that these changes cannot go live until June 26 to allow time for the community to be informed. It'd be nice to get the PR in for review before that so the strings can be localized.

**Comment by stephaniehobson** [comment]
After discussing with the client about the demo server I found out this change depends on changes to the privacy notice page itself.

In response I've changed our "Find out what data is shared" wording to a more generic "Learn more" because we don't actually know what the content of that section will be. At the moment there isn't actually any "more" to "learn".

@ejregithub Could you please check in with the client to see how the privacy notice updates are going? Do they expect to be ready on June 26 and is there a draft I could see?

**Comment by ejregithub** [comment]
Note that this now should go live with the other privacy updates on July 3rd

**Comment by thejeffreytaylor** [comment]
I've taken my final pass at the copy: https://docs.google.com/presentation/d/1sNt2IsvE2Qa_XzOi36iKxCKR_Z_Slhwb3Ml9FY3Dpjk/edit#slide=id.g379500bc1a_0_5

**Comment by ejregithub** [comment]
Updated demo server link - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/channel/desktop/

**Comment by alexgibson** [comment]
This got closed in error via a mos-referenced commit. Re opening
