### ISSUE TITLE
Adding pages to rank for “Browser”

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#5750]
**Problem:** We do not rank for the keyword “browser”

**Solution:** adding more informational and camparing content

**Proposal:** https://docs.google.com/document/d/15AZ5yXzD3St2LDMRAZgFkX5odIt7Vek918F15md1pTM/edit#

**Comment by thejeffreytaylor** [comment]
Added my updates/edits and have one suggestion for @rraue about section order. 

This is actually quite important, as the proposal for a series of articles

**Comment by thejeffreytaylor** [comment]
Also @ejregithub  — is the next step approval from David?

**Comment by thejeffreytaylor** [comment]
David - please approve or add comment. Next step would be kickoff.

**Comment by thejeffreytaylor** [comment]
@djst

**Comment by thejeffreytaylor** [comment]
Will work on moving this card over when @rraue returns from PTO.

**Comment by thejeffreytaylor** [comment]
This content was drafted by Chelsea and Dustin and is currently being reviewed.

**Comment by thejeffreytaylor** [comment]
Working with @dzingeek to see where these pages can fit in the nav/IA. @rraue can you link us to the content?

**Comment by rraue** [comment]
Here's the content for the "History of Web Browsers":
https://drive.google.com/open?id=1demvfj2kzdHZ2HhoS4GwUTNfRxFZ0s54veJ84XOwHKY

Here's the content for "What is a Web Browser":
https://docs.google.com/document/d/19msv-D3WdYS2k9ymxW2kRX6aM7obEk8qOZWUgqnC8KE/edit

and here is the Comparative Chart of Browser Features:
https://drive.google.com/open?id=1PaJzDRJJFAmyDecefBbh9K2KupDEZxPUbkeXpBNXYiI

**Comment by rraue** [comment]
Success criteria
- [ ] Content brief

- [ ] Design

- [ ] Coding

**Comment by ejregithub** [comment]
I'm marking this as done as both of these pages are live in prod:

https://www.mozilla.org/en-US/technology/browser-history/
and
https://www.mozilla.org/en-US/technology/what-is-a-browser/
