### ISSUE TITLE
Rank better for "adblock" and related keywords

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#5753]
Proposal: https://docs.google.com/document/d/1mE8wQdLKlNDp2sKqyuG2x24fDOG3S0TfR-PDlwhcr34/edit?usp=sharing

**Comment by rraue** [comment]
I need data from the search console of addons.mozilla.org and I am still blocked on getting access. cc @ejregithub

**Comment by djst** [comment]
Dupe of https://github.com/mozilla/bedrock/issues/6116? @rraue

**Comment by rraue** [comment]
@djst Yes
