### ISSUE TITLE
Firefox Privacy page hero image change

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5754]
Remove the existing pixelated eye image

**Comment by ejregithub** [comment]
@dzingeek recommends simply removing (not replacing) the gb image. Eric asked Michele in Slack on 5/30 if this approach was okay (no response yet)

**Comment by ejregithub** [comment]
@alexgibson - please simply remove the background image (pixelated eye). We don't have a replacement and won't in time for the 61 Release next Tuesday.

**Comment by ejregithub** [comment]
@dzingeek - please note your approval by checking the boxes above under Testing and adding the go ahead (or comments for edits) here.

**Comment by dzingeek** [comment]
Looks good to me, nice work Alex. Can we note somewhere that this page needs a redesign in the future?

*Designer approved!
