### ISSUE TITLE
Create new page for Privacy FAQ content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5759]
[Original request doc from Legal](https://docs.google.com/presentation/d/1OjwvxSB5JiMetD2RKVB9f7-n7qjvmPDw0fGi3VhyaQY/edit#slide=id.g38befeb50f_1_6)

Part of the update to the Privacy pages will be the addition of a new FAQ

Tasks:
- [x]  Copy (stated as final by Mika on 5/29)
- [x]  URL: /privacy/faq
- [x]  page title: Mozilla's Data Privacy FAQ
- [x]  Can precede or launch concurrent to content updates in #5745 (which will link to this page)
- [x]  Add link to FAQ from sidebar on /privacy

**Comment by stephaniehobson** [comment]
I asked Jeffrey to look at the copy because it's got a very distinct tone. I expect to hear back from him on Monday.

**Comment by thejeffreytaylor** [comment]
This FAQ copy needs overhaul-level attention, but I need more information: 

1. What is the goal of this content? Or to narrow it down, what do you want users to do once they consume this information. 

2. Do we really need an FAQ or can we consider packaging this content a different way using different content types (namely images/infographics). It's a lot to absorb, and I don't think the FAQ will alleviate user fatigue with the sheer mass of content. 

3. One possible solution is to use this content in the interim while the "Informed Consent Experience" (Issue #5648) is worked on, then we revisit this once that experience is fully baked.

**Comment by stephaniehobson** [comment]
We decided yesterday to use the FAQ until the  "Informed Consent Experience" is ready. Jeffrey is reviewing it by end of day today.

**Comment by thejeffreytaylor** [comment]
@stephaniehobson  Are you good? Let me know if you need anything here.

**Comment by stephaniehobson** [comment]
It's in review :)
