### ISSUE TITLE
Facebook container page is not RTL ready

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5766]
https://bugzilla.mozilla.org/show_bug.cgi?id=1465541

**Comment by Shivansh2407** [comment]
Can you please explain more on this issue ?

**Comment by alexgibson** [comment]
The description in the bug linked above explains what needs doing: https://bugzilla.mozilla.org/show_bug.cgi?id=1465541#c0

**Comment by Shivansh2407** [comment]
So what should I need to do in order to fix this issue?

**Comment by Shivansh2407** [comment]
I looked through this [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1465541#c0) but was not able to get a clear Idea of how to proceed. If possible please let me know.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8580
