### ISSUE TITLE
Allow testpilot to use the /country-code.json endpoint

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#5786]
https://testpilot.firefox.com/ is basically a static site. They'll be using basket to send SMS soon in much the same way we do for sending download links to mobile. They need Geolocation but they've been told they can't use [Mozilla Location Services](https://location.services.mozilla.com/api) because reasons.

Currently they also can't use our JSON country-code endpoint because we don't set CORS headers. This issue is to discuss adding such headers and whether we should add only specifically testpilot.firefox.com as allowed or just set it to `*` and change it later if it becomes an issue.

/cc @meandavejustice @jpetto @metadave @jgmize

**Comment by meandavejustice** [comment]
Here is a list of all of our environment urls:
`https://example.com/`
`https://testpilot.dev.mozaws.net/`
`https://testpilot-l10n.dev.mozaws.net/`
`https://testpilot.stage.mozaws.net/`
`https://testpilot.firefox.com/`

**Comment by jpetto** [comment]
The thought of allowing `*` makes me uneasy. Perhaps we could do `*.mozaws.net` and `*.firefox.com`?

**Comment by pmac** [comment]
> The thought of allowing * makes me uneasy. Perhaps we could do *.mozaws.net and *.firefox.com?

Agreed. We can use [django-cors-headers](https://github.com/ottoyiu/django-cors-headers) and specify those domains. Should be easy enough.

**Comment by pmac** [comment]
Feel like taking this one @jpetto or shall I knock it out?

**Comment by metadave** [comment]
> Agreed. We can use django-cors-headers and specify those domains. 
:+1:

**Comment by jpetto** [comment]
> Feel like taking this one @jpetto or shall I knock it out?

I would love to take it on, but I have some other moz.org stuff I have to get done. If you're free, go for it and I'll review.

**Comment by pmac** [comment]
@bensternthal to be clear here, do we need to discuss whether or not this is something we should do further, or should I proceed with the changes?

**Comment by bensternthal** [comment]
This architecture feels funky to me. I'm mostly concerned with this being a hard dependency between two unrelated websites and Bedrock isn't really architected to provide services to other websites (IMHO).

So I'd like to understand the impact of us going down this road and if we should do anything differently.

@jgmize opinions?

**Comment by pmac** [comment]
Update: @meandavejustice talked and they are going to be able to use [Mozilla Location Services](https://location.services.mozilla.com/api) for this after all. The hangup was that said service would return much more accurate and detailed location information than was needed (e.g. lat, long) when using an API key. But if used without an API key it simply returns country code, which is all they need. So as long as that service works for them we no longer need to do this. Should something happen to change that we can revisit this.

Thanks all!
