### ISSUE TITLE
Localize /newsletter/opt-out-confirmation/ to DE

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5788]
https://bugzilla.mozilla.org/show_bug.cgi?id=1467252

Requirement is to open the page and its additional state (success) to l10n.  

The email program leveraging this page is opened only to German for now. 
Eric will confirm with Peiying that l10n be opened to DE only until such time more locales are added on the LCM side.

**Comment by ejregithub** [comment]
@alexgibson - please inspect the page for required changes to enable l10n.

**Comment by alexgibson** [comment]
> @alexgibson - please inspect the page for required changes to enable l10n.

Strings are already wrapped, so there should be nothing further to do here other than translate the page.

**Comment by ejregithub** [comment]
I've assigned the bug to Peiying. Stephan Z has already localized the copy and will input to Pontoon when Peiying extracts the strings.

Closing this, our part is done
