### ISSUE TITLE
About Page Redesign: Propose Discovery Process and overall timeline

### ISSUE THREAD

**Issue by thejeffreytaylor** [mozilla/bedrock#5808]
Jeffrey and Jennifer would like to: 

1. Do an[ heuristic evaluation](https://www.nngroup.com/articles/ten-usability-heuristics/) of the current About page to measure current state usability and utility (i.e. use UX best practices to outline the problems we need to solve) 

Output: A presentation deck with evaluation findings, including content and design requirements. 

2. Create provisional wireframes as a starting point with our ideas for a redesign

Output: Provisional wireframes

3. Bring the evaluation and provisional wireframes to stakeholder interviews to get reaction, feedback, and business requirement guidance. 

Output: Iterated presentation deck with business requirements and round 2 wireframes for stakeholder approval. 

The next step would be to secure final approval and start production. 

The only open item that could block this discovery process is the identification of the right stakeholders and ensuring we get time with them amidst busy schedules.

**Comment by thejeffreytaylor** [comment]
@djst @dzingeek  @rraue I added this issue before all hands. Could you let me know your thoughts and feedback? 

I also set up a requirements-gathering doc. Please contribute and we can bake those requirements in evaluation findings and wireframes.

**Comment by thejeffreytaylor** [comment]
Promised @djst a fully baked proposal for him to review by Monday, if not sooner.

**Comment by rraue** [comment]
I added the Seo requirements in the doc.

**Comment by thejeffreytaylor** [comment]
We've got several user stories on the board now, so I'm closing this.
