### ISSUE TITLE
Add analytics to the language switcher

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#5810]
We're curious how many people use the language switcher in the footer to change to a language other than what we initially serve them. Having some data on this would inform a proposed redesign of our language switcher. It seems like something we could do pretty easily with GA and an event on the switcher dropdown?

**Comment by ZehCnaS34** [comment]
> ... we could do pretty easily with GA and an event on the switcher ...

To implement this, would we use [dataLayer.push()](https://github.com/mozilla/bedrock/blob/master/docs/analytics.rst#datalayer-push-example)?

**Comment by alexgibson** [comment]
It looks like we already capture this data in GA: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-utils.js#L52

**Comment by craigcook** [comment]
> It looks like we already capture this data in GA

Ah! So we do. I don't know why it didn't occur to me to check first before I assumed we didn't.
