### ISSUE TITLE
404 occurs - https://www.mozilla.org/about/logo

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5816]
Task:
- [ ] Redirect: https://www.mozilla.org/about/logo/ to https://www.mozilla.org/styleguide/

- [x] @rraue  to comment on best practice
- [x] Eric to get confirmation from Tim Murray on preferred redirect URL

**Comment by rraue** [comment]
@ejregithub I agree that styleguide would be the best destination, as it is basically the replacement. This reminds me, that I want to do a 404 analysis and mapping plan with @thejeffreytaylor together.

**Comment by LordGameleo** [comment]
Is this issue open? I would like to work for it.

**Comment by ejregithub** [comment]
@lordgameleo - yes, apologies for the delay in responding. This issue remains open and available.

If you're still interested, please submit a pull request when ready.

**Comment by Shivansh2407** [comment]
Can you please help and list out the file which we need to change in order to redirect from  https://www.mozilla.org/about/logo/ to  https://www.mozilla.org/styleguide/
