### ISSUE TITLE
Homepage needs a localization plan

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5824]
The [redesigned home page](https://www.mozilla.org/en-US/) is being shown for all English locales, however all other non-English locales, *except* DE, are still being served the [old home page design](https://www.mozilla.org/fr/), because the editorial content is aimed for English audiences and our blog content is largely not translated. The card content is also likely to change every 2 weeks, which is pretty pointless to try and translate.

We need to develop a strategy for l10n and the new home page, as currently 60% of our global audience is not seeing it. The download CTA sections and billboards are evergreen and are well suited for translation, but we need some other content to replace the card sections. We can easily serve non-English locales a slightly different variation on the content hierarchy, but the overall template design should remain consistent and use Protocol components.

**Comment by michaelmccombie** [comment]
For a temporary fix we could convert the old homepage content we have to homepage cards. It would keep the designs consistent and we wouldn't have to go through the process of translating and testing new content.

Ideally we would come back and create something brand new, but it's probably best not to go down that route until we are sure the current homepage design is performing well.

![image](https://user-images.githubusercontent.com/5924575/41606674-13065a72-7399-11e8-9fe9-33e0cbe91ecf.png)

**Comment by michaelmccombie** [comment]
We could also take the landing page templates (which we haven't started building yet) and adapt that work to create a non /en-US home page. 

![image](https://user-images.githubusercontent.com/5924575/41690798-191c3f9e-74ac-11e8-98c4-219075a49d04.png)

**Comment by michaelmccombie** [comment]
Personally, I'd lean towards the landing page look because it makes more sense for our current content (assuming we don't want to turn this into a bigger redesign project) and it would be nice to have a project in mind already when we start putting together those components.

**Comment by ejregithub** [comment]
Flagging the new to get the brand teams involved for determine evergreeen content on the page for non-Tier one locales.

**Comment by ejregithub** [comment]
I emailed Eddie Ibarra (TL for NA Brand) and then sent a meeting invite, adding Robin (TL for EU Brand) to that for June 24th

**Comment by ejregithub** [comment]
From the meeting. Robin self-assigned the task to talk to Janis about this including determining who the Accountable person should be here.

**Comment by pmac** [comment]
@alexgibson with all of the changes since this was last filed, do we still need to have this one open?

**Comment by alexgibson** [comment]
Closing in favor of https://github.com/mozilla/bedrock/issues/12282
