### ISSUE TITLE
SEO - Build a country/language selector page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5827]
Build a country/language selector page for better crawlability https://bugzilla.mozilla.org/show_bug.cgi?id=1439377
****
Sketch file: https://mozilla.app.box.com/s/qevzuvmufmag8pnjvn4hv3esfssmlv3y
URL: https://www.mozilla.org/locales/
Title: "Choose your language or locale to browse Mozilla.org
Meta description: "Select your country or region to indicate your preferred language. Learn how Mozilla puts people before profit, making products designed to keep the internet open to all."
****

- [x]  page design

- [x] Locales are hard coded for v.1

- [x]  Protocol ready (no longer new component "table" only change in footer https://github.com/mozilla/protocol/issues/259 needed)

- [x] Meta description (Clay and Raphael)

- [x] Ready to code

- [ ] Page linked in the footer as described https://github.com/mozilla/bedrock/issues/5827#issuecomment-434395964

**Comment by dzingeek** [comment]
The design is ready. Links to jpgs for reference and sketch file below. 
_**Note:** All languages might not be represented in the file. We are under the assumption that there is an existing list out there that can be leverage w/in development. We should also include the language in its original form._ 

**sketch file**
https://mozilla.box.com/s/qevzuvmufmag8pnjvn4hv3esfssmlv3y

**jpgs**
https://mozilla.box.com/s/n1jxgbbe76yowndlawigxas38vrw3lk9
https://mozilla.box.com/s/je730hyke94ad20z431ru53dkik0ydgb

**Comment by alexgibson** [comment]
I'm assuming the list of countries on this page should be auto-generated based on the currently active locales for the site. We do have a list of locales available to query, but they are not split up or arranged based on geographical area. We'd need to manipulate the data in some way to achieve this. 

While this works design-wise, it's also worth noting that geographical locations do not also necessarily map 1:1 with language. The `fr` locale is very popular in Canada for example.

**Comment by rraue** [comment]
@alexgibson This page will be not available for every document, just one page for all "root" language/country locales. So auto-generated would be good, but as we are not adding too much noch locales every week, a slow process is good enough.

**Comment by michaelmccombie** [comment]
Dependent on https://github.com/mozilla/protocol/issues/186

**Comment by rraue** [comment]
@pmac Could you please give us your opinion on how much extra work it would be to autogenerate (see @alexgibson comment above) in the given design the locales to show and map them to the continents, so I can decide if we should do the automation or just hard code it?

**Comment by pmac** [comment]
Well no one has addressed Alex's question around where locales should go on a map. Language isn't geography. It works for some locales but not for others. Also we have some locales in our production list that have only one or two pages on the whole site enabled ("tl" for example has only some privacy pages). So I guess I'm still too unclear on how we'd even do this to know how much work it will be.

**Comment by rraue** [comment]
Thank you pmac. @dzingeek we should discuss this, maybe a simple list of all locales at least having a homepage will do it and we care about design later. Sumo has a page like that: https://support.mozilla.org/en-US/locales

**Comment by pmac** [comment]
The short and easy answer I think is to just maintain a separate list of locales you want on this page grouped by whatever grouping you want (e.g. "Asia Pacific"), and I'd suggest limiting the list to those locales that have at least the home page translated so that the links on the page can all point there. If we can go that route then it won't be much extra work at all.

**Comment by rraue** [comment]
Thank you @pmac. @dzingeek we should discuss this as it is more a design decision. For Seo anything works. Maybe a simple list of all locales at least having a homepage will do it and we care about design later. Sumo has a page like that: https://support.mozilla.org/en-US/locales

**Comment by dzingeek** [comment]
After talking this over with @rraue, @vincejoyiv, and @michaelmccombie I think we have decided to move forward with the design suggested above. While we totally understand that locals are not languages I think these labels with help users find languages quicker if needed. 

The other thing we had discussed a while ago was where to link this list from. The conclusion we came up with was using the word Language (next to the drop-down list) as the link to this list.

Any concerns with this direction @alexgibson ?

![screen shot 2018-10-30 at 9 08 23 am](https://user-images.githubusercontent.com/3740746/47732561-af6e2f00-dc23-11e8-8ea7-96786b11a4a6.png)

**Comment by alexgibson** [comment]
Ok, we've settled on the following approach for the footer. It's not ideal, but gets around the a11y issue at least for now.

- We keep the “Language” label for the form input, but we hide it visually (just not from screen readers). Perhaps we could update it to be something slightly more specific, like "Page language".
- Then we can have a “Language” become a link to this new page.

**Comment by rraue** [comment]
Thank y'all. So we hard code it and see if any UX is needed. We just need to remember then to add locales, if we create the homepage for them.

**Comment by rraue** [comment]
@alex sized it as M

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/protocol/issues/259

**Comment by rraue** [comment]
@clay-chaffin added the meta description, I updated the brief: "Select your country or region to indicate your preferred language. Learn how Mozilla puts people before profit, making products designed to keep the internet open to all."

**Comment by rraue** [comment]
From my slack conversation: This page will be not localized in v1, its just one page at www.mozilla.org/locales/ and all footerlinks from all locales point to this page. 

There is only one english sentence on the page and we dont know if users will really use this page, if so, that would be a iteration for v2.

**Comment by alexgibson** [comment]
Demo URL is up for review: https://bedrock-demo-agibson.oregon-b.moz.works/locales/

@rraue @dzingeek let me know if there are any amends.

Note: I went for using localized language names which is different to the mockup, but probably more useful from a UX perspective. Because of this I chose to order languages by their locale code, since there are some different alphabets in use.

**Comment by alexgibson** [comment]
Also note: this page is not yet linked to in the footer, there's a Protocol PR for that here: https://github.com/mozilla/protocol/pull/260

This doesn't block us from reviewing / merging the language page.

**Comment by djst** [comment]
Alex, I agree that localized names is a better user experience, but the sorting feels different from standard practice, which seems to be to sort alphabetically on the localized name rather than the locale string. Given that the locale string is unknown technical jargon to most people, I would recommend we sort by localized name instead.

The page _looks_ awesome, fwiw.

**Comment by alexgibson** [comment]
> Alex, I agree that localized names is a better user experience, but the sorting feels different from standard practice, which seems to be to sort alphabetically on the localized name rather than the locale string. Given that the locale string is unknown technical jargon to most people, I would recommend we sort by localized name instead.

That's not something I think we can realistically do, given the multiple alphabets used as I mention above. Also, if we're to automate this page longer term, whatever manual sorting we do now will likely be undone.

**Comment by djst** [comment]
I assumed you could just do some universal UTF-8 sort for all localized names and that that's how google does it on e.g. the dropdown here: https://support.google.com/accounts/answer/32047

Anyway, just my 2 cents here, not very important to me. :)

**Comment by alexgibson** [comment]
> I assumed you could just do some universal UTF-8 sort for all localized names and that that's how google does it on e.g. the dropdown here: https://support.google.com/accounts/answer/32047

Hmm, I'll investigate if this is something we can do in Jinja, thanks. But right now this is a manual list. I guess I'll need to work out a manual way to sort this

**Comment by alexgibson** [comment]
After discussing this with @pmac, we're going to leave ordering as-is (by locale code). Even though there are libraries out there that will help sort unicode strings, it's not really possible to sort a mixture of latin and non-latin based alphabets correctly,  Ordering by locale code is something we already do in other parts of the site for this reason, such as the language selector in the footer.

**Comment by rraue** [comment]
When reviewed it can be merged and closed even without mozilla/protocol#260.

**Comment by craigcook** [comment]
Live in production: https://www.mozilla.org/locales/

**Comment by djst** [comment]
Looks great!

**Comment by alexgibson** [comment]
Filed https://github.com/mozilla/bedrock/issues/6455
