### ISSUE TITLE
Long page titles

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5835]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454428

**Comment by alexgibson** [comment]
@rraue is this something we still need to fix? The /about page launched some time ago so I'm guessing this is no longer blocked.

**Comment by rraue** [comment]
It was blocked by time from Jeffrey. It's still something to do, but we more important stuff. I want to work with @clay-chaffin on a complete title and description audit and this would be part of it, so I am fine to close it, as I will not forget about it.

**Comment by stephaniehobson** [comment]
Closing to let @rraue re-open with clear action items.
