### ISSUE TITLE
Refactor google_play_button macro to global jinja function

### ISSUE THREAD

**Issue by jpetto** [mozilla/bedrock#5838]
The logic in the macro has grown enough that it's getting a bit tough to reason about. Would be cleaner and clearer to perform the logic in Python and render out HTML (much like the download button).

**Comment by pmac** [comment]
@alexgibson thoughts on this one? Still something we should do?

**Comment by alexgibson** [comment]
@pmac this one is a nice-to-have I think. The macro is rarely updated though, so it's probably not a big deal if we wanted to close this. I'll leave it up to you.

**Comment by robhudson** [comment]
I took a look at this macro and it seemed minimally complex to me. Since this is old I'm going to close it. We can always re-open if it becomes a problem later.
