### ISSUE TITLE
Article in header image attributed to the wrong news source

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#5839]
On the /new page (https://www.mozilla.org/en-US/firefox/new/) the main hero image has a pocket recommendation card that attributes an article to the wrong source. The incorrect source on our website is some site called "Kottke" (which I'm unfamiliar with and doesn't have a verified twitter account) the correct source is The Verge.

This is the actual article the image references:
https://getpocket.com/explore/item/the-secret-rules-of-the-internet-1255998884

This is the image of the pocket recommendation in question
<img width="736" alt="screen shot 2018-06-21 at 11 00 44 pm" src="https://user-images.githubusercontent.com/5924575/41760147-dc8cb4ae-75a6-11e8-88cd-eb5e915b12b5.png">

**Comment by stephaniehobson** [comment]
Kottke is one guy who reads a lot and puts links to the best stuff he finds on his website. I think it's a great favicon to include even though it doesn't have a verified Twitter account.

That said, Kottke doesn't seem to have covered The Secret Rules of the Internet.

**Comment by michaelmccombie** [comment]
@stephaniehobson thanks! I was unfamiliar with him before, I didn't know it was a personal blog. I use Twitter verification as a way of assessing whether something comes from a legitimate news source, I recognize it's not a perfect way of assessing the "validity" of a source. 

We can leave the favicon, but I will update the piece of text so the article is attributed to the right source.

**Comment by alexgibson** [comment]
This issue now references the old design for the /new page. The new page features a different browser image where this no longer occurs. Closing.
