### ISSUE TITLE
Deprecate the old send-to-device widget

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#5844]
For the whatsnew page for Firefox 61 we introduced a refactored widget so we can send messages for either Firefox or Firefox Focus, and additional products in the future. The new widget avoids duplicate IDs so we can safely embed more than one widget on a page. It also follows the Protocol naming convention and is a step towards making it a proper Protocol organism (finalizing that will be another task for another repo).

The old widget is still in place on the whatsnew 60 page as well as the /firefox/mobile/ page, and possibly a few other places but those two may be it. We should update those instances to use the new widget macro, port the existing tests to new widget, update docs where necessary, and do any additional cleanup needed to get us to a more maintainable one-widget state.

**Comment by alexgibson** [comment]
We combined the features from send-yourself into send-to-device, so now there's only one library in the repo.
