### ISSUE TITLE
GA Property for Marketing website only

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#5849]
I am struggeling at a lot of points to get my numbers right because of the heavy pageviews /whatsnew and /firstrun do in the main ga property www.mozilla.org (Production). Especially with the mixed attribution model (last non-direct click) in some reports it's repetitive work to get the right numbers.

Is it possible to have a property showing just the "real" website and /whatsnew /firstrun as one incoming marketing channel, if users click on these pages, but without the traffic, time spend and all data from these pages?

Then we would have a better picture of the sections, channels and assisted conversions.

Of course the traffic on whatsnew&firstrun is a important funnel, but the traffic happening there is not really marketing website usage. It would make my life way easier to split this.

Whatsnew is responsible for 24% of all page views
Firstrun around 19%

They are a important funnel for the website, but not a direct channel and users on this two page types have a completely different behavior to the rest of the site.

When looking on our website and the way we optimize it, it should be different point of views.

Any opinions @peterGerman and @hoosteeno?

**Comment by hoosteeno** [comment]
I agree with the difficulties here.

Both pages are likely to land in the product in the next few months, which will cause pageviews on those pages to drop to practically 0. 

Meanwhile is it possible to limp along by e.g. forcing reports to use a segment comprising all visits that did not land on those pages?

**Comment by peterGerman** [comment]
Justin, can you remind me when we anticipate those changes will land in the
product?

If it is going to be soon, I would rather not do work that we are going to
throw away, especially since any changes we make are going to be forward
looking only.

**Comment by hoosteeno** [comment]
about:welcome is in 62 -- that replaces firstrun. Sounds like moving /whatsnew is not a priority at the moment, so a GA property and/or a recommended approach to solve this for @rraue is probably worthwhile.

**Comment by ejregithub** [comment]
Pinged Daniel Z in Slack about this ask.
