### ISSUE TITLE
FxA Benefits page v 1.1

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5862]
For relaunch - Update the page based on learning from qualitative testing
Post relaunch - Compare GA data of relaunched page to the winner (new baseline) of the quantitative a/b test w. short vs. long copy

- [x] Design QA - Approval (by Lauren) - [QA document](https://docs.google.com/document/d/1UlSGIyekb82vBiAAhWdU0o_xSoYF3vQdIJ859dlFNYM/edit)
- [ ] Coded page final QA - Approval (by Lauren)

- Design file (sketch)
- [v 1.1 brief](https://docs.google.com/document/d/1wubD3fE6geu4jg_f9sgiMisf9TJ1pwfHEuwAYWz7_Js/edit#heading=h.da90bld12nbq)
- [Copy doc](https://docs.google.com/document/d/1G8QkQfQLfw4sILYK7JoYcIXLfh5c1F3DyLd3BMguewo/edit)

**Comment by ejregithub** [comment]
copy and design approved - 

lniolet [8:37 AM]
approved.

**Comment by ejregithub** [comment]
@craigcook - copy and design are approved, would like to ask that you pick up coding the new rev of the page.  @mrkwvr - please provide Craig with the sketch file.  Craig, please refer to the [copy doc](https://docs.google.com/document/d/1G8QkQfQLfw4sILYK7JoYcIXLfh5c1F3DyLd3BMguewo/edit) as the source of truth for copy (not what is in the sketch file).

**Comment by craigcook** [comment]
On demo at https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/accounts/features/

**Comment by mrkwvr** [comment]
@craigcook Looking good! Just a few things I noticed that I'm sure you're still working on:

- add firefox logo to top section
- make sure buttons are correct color/shape
- can we shift Send Tabs section to the left so that text aligns to hero section text? Matches the design but after seeing it I think it needs to be moved over.

**Comment by craigcook** [comment]
> add firefox logo to top section

Doh, I knew I had forgotten something.

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/accounts/features/

Updates: added the logo, squared the buttons, aligned the boxes.

**Comment by dzingeek** [comment]
@craigcook can we tweak the buttons a bit? I know buttons am I right?
• They seem a bit too large 
• Hover states might be an accessibility issue

I've updated the abstract file to have hover states included (second artboard). Let me know if you have questions or if this change is too much work.

**Abstract file (FxA Benefits Page > Hover states for buttons)**
https://share.goabstract.com/938627a0-33c4-4661-95d5-a910df00bc57

**Comment by craigcook** [comment]
Updates: shrunken buttons, new hover states.

**Comment by bniolet1** [comment]
We've got "Synced" and "Synched." I don't know what our official spelling is (would love to know if you do). But we need one. 
![screenshot-bedrock-demo-craigcook oregon-b moz works-2018-07-12-11-55-59](https://user-images.githubusercontent.com/14222130/42644883-ae3e6848-85ca-11e8-98d5-7ba0b8b688f8.png)

**Comment by craigcook** [comment]
> We've got "Synced" and "Synched." I don't know what our official spelling is (would love to know if you do). But we need one.

Good catch! I vote for "sync/synced" as our official spelling, since the feature is/was officially named Firefox Sync (sans h). I'll update.

**Comment by thejeffreytaylor** [comment]
Yep. AP style in synced. We checked.

**Comment by ejregithub** [comment]
@craigcook - Lauren indicated final signoff/approval in Slack. If/when the code review is done, let's ship it, please.
