### ISSUE TITLE
About- P1 - As a visitor of the About Us page, I watched the video on the page and it left me feeling like I was watching a “rah rah” employee-targeted hype video from a few years back. This doesn’t feel like it’s for me, so I left the page.

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5875]
- [ref doc](https://docs.google.com/document/d/1op2sQfY_l73vkwZL1W20FtZvTDhNuuu_89aM4bhDGVQ/edit#)

Success metric: overall increase of engagement on page. If we do another video, more views and longer view time

**Comment by alexgibson** [comment]
This is a _really_ subjective user story 🙄

**Comment by djst** [comment]
Did you watch the video? It's objective. 😂 (And, thankfully, solved)
