### ISSUE TITLE
Create & test variation of default German download page (/de/firefox/new) with local campaign messaging and creative assets

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5879]
German /new page A/B test

https://bugzilla.mozilla.org/show_bug.cgi?id=1455208

**Comment by stephaniehobson** [comment]
There is already an A/B test running on this page. Has sufficient data been collected from it? Can it be disabled? Do we need to run another test based on the results for this one?

**Comment by stephaniehobson** [comment]
@ejregithub Could you please contact the team about this experiment: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=77893531 

1) Can we disable it? (If not we should not start a new one)
2) Should the winning variant be promoted to the default?
3) If the winning variant is promoted they should re-think the the current request.
