### ISSUE TITLE
Create three landing page variations based on the Berlin pixelated heart LP (https://www.mozilla.org/de/firefox/new/?xv=herz).

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5880]
Create three landing page variations based on the Berlin pixelated heart LP (https://www.mozilla.org/de/firefox/new/?xv=herz). The three additional pages have different header visuals and some copy tweaks:

1) Speed: cursor rocket visual
2) Privacy: mask visual
3) On your side: fist bump visual

https://bugzilla.mozilla.org/show_bug.cgi?id=1473357

**Comment by stephaniehobson** [comment]
Here are the 3 variations with temporary slugs:

https://bedrock-demo-shobson.oregon-b.moz.works/de/firefox/new/?xv=speed
https://bedrock-demo-shobson.oregon-b.moz.works/de/firefox/new/?xv=privacy
https://bedrock-demo-shobson.oregon-b.moz.works/de/firefox/new/?xv=oys

The image for large mobile/small tablets is not wide enough. For example, it looks funny on ipad a 768. I'm still working on that but please let me know if the text is all correct.

I am blocked on permanent slugs (or client sign off on the temporary ones).

I reached out to the client in bug but not sure that's the best way to communicate.

**Comment by ejregithub** [comment]
I'm suggesting these to Guy, in the bug and in Slack.

Speed:  /de/firefox/new/?xv=geschwindigkeit
Privacy:  /de/firefox/new/?xv=privatsphare
On your side:  /de/firefox/new/?xv=auf-deiner-seite
