### ISSUE TITLE
Update Events link to Events.m.o in new nav

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5899]
User story: As a product manager on the Open Innovation team launching the new Events.mozilla.org website, I need a suitable place in the navigation of mozilla.org so visitors can find it. 

Success metrics: Increased participation in Open Innovation events and efforts.

**Comment by dzingeek** [comment]
My initial thought was to replace the current /contribute/events with this new events.mozilla.org.
Right now /contribute/events doesn't really do anything for anyone, and we don't need two event locations. So as soon as this new events site is ready we should make the switch in the nav. 

Thoughts @rraue and @vincejoyiv

**Comment by rraue** [comment]
I agree

**Comment by djst** [comment]
Let's do it.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/6174

**Comment by stephaniehobson** [comment]
Done in https://github.com/mozilla/bedrock/pull/6220
