### ISSUE TITLE
monitor.firefox.com project

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5919]
[Master project doc](https://docs.google.com/document/d/1d9fd5LxZD4IC2JE5DfhKoAlHQYtXMkDMVBmgkhyq06I/edit#)

Project goals
- [ ] Redesign of monitor.firefox.com (which brand? Or brand neutral?) and optimize for mobile by 62 launch on 9/5. Keep the more product look and feel as users will be coming here from Fx product and from other browsers. 

- [ ] Promote newsletter signup and account sign up. a/b test to id best approach, using FxA as means to sign up vs. just email account (Timing TBD, likely post launch)

- [ ] Promote monitor.firefox.com from within mozilla.org (consider creating a tile on the homepage)

**Comment by alexgibson** [comment]
@ejregithub it seems like this was done by another team. Can this issue be closed?
