### ISSUE TITLE
Pocket - cards for homepage (above the fold)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5923]
Create content to post in a card on the homepage

**Comment by thejeffreytaylor** [comment]
Working on this with Jennifer

**Comment by thejeffreytaylor** [comment]
@ejregithub Unclear on the status of this.

**Comment by thejeffreytaylor** [comment]
@ejregithub Still unclear on the status of this.

**Comment by alexgibson** [comment]
@ejregithub do we have some idea what this is, can it be closed?

**Comment by alexgibson** [comment]
This request was never quite clear and is now pretty old. Closing.
