### ISSUE TITLE
Pocket - cards for homepage (in the Pocket feed)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5924]
Create content to post in the Pocket feed section about Pocket

**Comment by thejeffreytaylor** [comment]
Working with Jennifer on this.

**Comment by thejeffreytaylor** [comment]
@dzingeek @ejregithub I see the other card from Ben. It looks like we're automating the feed here, but have we agreed on what's going to be displayed exactly? Let me know where this is as it seems #5723 may be redundant.

**Comment by thejeffreytaylor** [comment]
Closing this, as it went live last Friday as far as I know. @jpetto-circleci please re-open if I got this wrong. Still thing we could brand this for Pocket better and provide a small amount of content and some sort of Pocket conversion CTA in that section, @ejregithub and @djst - please let me know if you'd like for me to create an issue/card.
