### ISSUE TITLE
Compile CSS in CI on pull requests

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5928]
I'm pretty sure we used to compile CSS in CI against each pull request. I'm guessing this changed as part of the django pipeline removal, but it would probably be useful to have this check still.

As an example, https://github.com/mozilla/bedrock/pull/5927 breaks the home page due to an error upstream - but this isn't picked up until someone pulls down the branch to test locally.

**Comment by pmac** [comment]
Hmm. I thought it did, but it looks like you're right. I'll try to knock this out today. Good catch!
