### ISSUE TITLE
Language switcher no longer works without JavaScript

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5931]
This may well be an intended change reading https://github.com/mozilla/bedrock/issues/5581, but I'm filing this as not 100% sure.

STR:

Using any browser with JS disabled, or a legacy browser such as IE8 (where we don't serve JS):

1.) Visit https://www.mozilla.org/en-US/
2.) Scroll down to the language switcher in the footer and choose "Francais" from the list (as an example).
3.) Hit the "Go" button to submit the form.

Expected results:

Page should redirect to https://www.mozilla.org/fr/

Actual results:

Page redirects to https://www.mozilla.org/en-US/?lang=fr (still English)

If we no longer want to support the language switcher without JavaSctipt that's OK by me, but we should probably then hide it by default, rather than leave it in a broken state.

**Comment by michaelmccombie** [comment]
Once we have the language selector page https://github.com/mozilla/bedrock/issues/5827 built out and added to the new footer https://github.com/mozilla/protocol/issues/184 we will be able to provide that same functionality to those who have javascript disabled.

**Comment by conradylx** [comment]
I think this issue is already fixed.

**Comment by robhudson** [comment]
Tested this today and it is still an issue.
