### ISSUE TITLE
Dev Newsletter page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5935]
[Details](https://docs.google.com/document/d/18iLmmM3-SfGZI2JLTB_SKXn-N0p4y6DTcGx-Bhn-G6k/edit?ts=5b50c6fd)

Success criteria:

- [x] update hero image w. asset from Brigade
- [ ] update copy as found in the [Details](https://docs.google.com/document/d/18iLmmM3-SfGZI2JLTB_SKXn-N0p4y6DTcGx-Bhn-G6k/edit?ts=5b50c6fd) doc

**Comment by ejregithub** [comment]
@amychurchwell - want another one?

**Comment by amychurchwell** [comment]
@ejregithub - definitely! I'll tackle this once I finish Trademark Webpages #5949 :)
