### ISSUE TITLE
Create Pocket Section for FxA Benefits page 

### ISSUE THREAD

**Issue by thejeffreytaylor** [mozilla/bedrock#5937]
Create a new section for the FxA Benefits page detailing sign in with FxA for Pocket:

Success Criteria:
- [x] New Pocket section is added
- [x] Page is updated with new images (sections include; send tabs, sync, and passwords )

![moz_fxa-pocket](https://user-images.githubusercontent.com/4681199/43089234-fbe80c2a-8e58-11e8-9b91-6721f8dbc1be.jpg)

**Comment by stephaniehobson** [comment]
See also https://github.com/mozilla/bedrock/issues/5862

**Comment by alexgibson** [comment]
It looks like this was done.
