### ISSUE TITLE
[Oct 1] Lean Data Practices site launch

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5938]
**Lean Data Practices Landing page + 4 supporint Pages:** 
[Project Board](https://github.com/mozilla/bedrock/projects/10)
[Master Project Doc](https://docs.google.com/document/d/1gLnXiXzR-gQJq04x0RRiOjeqsP6GCgGL34Xf6y2K1iQ/edit)
[Current Page](https://www.mozilla.org/en-US/about/policy/lean-data/)
Resources from Client
[Copy doc](https://docs.google.com/document/d/1NBKCDZt8PJjPXP1yHNOozKx7ChUMYfAMIreTNpURH0g/edit)

**Success Criteria**
- [ ] Live on October 1, 2018
(The Policy team is doing presentations in the fall and has asked for a target date for go-live of October 1)
- [x] Maintain current URL redirect from leandatapractices.com to https://www.mozilla.org/en-US/about/policy/lean-data/
- [ ] Design and Build Landing Page
- [ ] Design and Build Stay Lean Page (this should be the template for the following pages)
- [ ] Design and Build Security Page 
- [ ] Design and Build Engage Users Page 
- [ ] Design and Resources Page

**Comment by stephaniehobson** [comment]
I'm curious about the Wordpress requirement. Do they expect to be updating it frequently? From the mockups it looks like a good candidate for a static site.

**Comment by ejregithub** [comment]
I'll ask Mika.

**Comment by ejregithub** [comment]
@stephaniehobson - Mika said Legal is good with a static website. I'll change the requirement.

**Comment by ejregithub** [comment]
@rraue - Mozilla owns leandatapractices.com and it currently redirects to https://www.mozilla.org/en-US/about/policy/lean-data/   

The desire is to have the new Lean Data Practices content (nearly done) live on its own website and we're wondering, w. regard to SEO, if it is best that is live on leandatapractices.com - or - if live as a subdomain to mozilla.org (perhaps as 'leandata.mozilla.org).

Please provide your recommendation for a URL for the site.

**Comment by rraue** [comment]
But another question: what is the success metric of this page? There is in the new mockup a download button for the toolkit, but pretty much hidden in the footer and if usage of the toolkit is the success metric, I am pretty sure the current page will perform better.

**Comment by alexgibson** [comment]
@ejregithub can you please provide some context as to the reasons why this update is in the form of a microsite, and not just a series of updates to the existing pages on www. If there are some good reasons to spin up a separate site for this then that's fine, but there is a long term cost of keeping microsites up and running, as well as ongoing maintenance required (asking for our SRE's).

**Comment by craigcook** [comment]
Perhaps the horses are already out of the barn on this particular project, but this is exactly the kind of thing Protocol is supposed to solve. We could pretty quickly build this set of pages without fully polished designs from an (expensive) agency. 

I don't know that this site needs a unique brand and interface, unless it's purposely meant to stand apart from the Mozilla brand. If we need to match these designs it'll mean building from scratch, which takes longer and incurs more technical debt. Overall we should be striving for fewer microsites and more consistent design, not the opposite.

If it's not too late to rethink the requirements I'd recommend building this on mozorg using Protocol and treating the designs as a wireframe guide. If there's a compelling reason for it to be a standalone website I'd still recommend using Protocol for it if possible.

**Comment by ejregithub** [comment]
@alexgibson - I pinged Mika, who inherited the project. She's okay with this going on mozorg at /about/policy/lean-data/ with the requirement that the leandatapractices.com domain redirect there remains.

@rraue - this is an old design from The Brigade, we can largely ignore old bits, building it with our new toolkit. And the branding, while also out of date in the mockups, is intended to reflect the mozilla global brand.

Thanks all for winnowing this down. I'll update the Success Criteria

**Comment by ejregithub** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/about/policy/lean-data/
