### ISSUE TITLE
Change way of deindexing for whatsnew and firstrun

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#5940]
Currently /whatsnew and /firstrun are blocked by robots.txt but not little of the pages have external backlinks. These links do not count for the domain, as the landingpage is forbidden to crawl. 

As we do not have much of these pages and dont have to worry about crawl budget on www (small site) we should allow crawling on whatsnew and firstrun and set them then to noindex, follow. Then they will be not indexed, but the incoming backlinks count for the domain.

_Blocked by robots.txt does NOT mean pages can't be indexed, they can be and will be if detected, just all information on the page will be not indexed, as its forbidden to crawl:_
<img width="823" alt="Screenshot 2020-01-13 at 16 39 07" src="https://user-images.githubusercontent.com/36700618/72269056-3d64e880-3623-11ea-85de-680edd240094.png">

To set them on noindex we need to remove hreflang and canonical from the pages, like our general rule for noindex pages.

The backlink count for the pages is not very high, so it hasnt a priority to do this, but by this issue I want to prevent, we are doing this to more pages and if we touch whatsnew and/or firstrun anyways, it should be a small tweak to change this issue as well.

Tasks:

- [ ] Allow all whatsnew and firstrun pages in robots.txt
- [ ] Remove canonicals and hreflang
- [ ] Set them to noindex, follow

**Comment by hoosteeno** [comment]
@rraue is this issue still valid & important?

**Comment by rraue** [comment]
Yes I still would like to do this if its small effort.

**Comment by robhudson** [comment]
@a-kyne This seems like something you would be interested in and could chime in on.

**Comment by a-kyne** [comment]
It looks like these recommendations were implemented. It was unnecessary, because robots.txt does not invalidate links to a blocked page (and because the site has 1 Billion backlinks anyway). Also, you don't need to remove any HTML (for SEO reasons) if you noindex the page.
