### ISSUE TITLE
Experiment - ask for email prior to download

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5944]
[manapage w. test write up](https://mana.mozilla.org/wiki/display/FIREFOX/Ask+for+email+prior+to+download+test)

Success Criteria

- [ ] non-Firefox en-US visitors on Windows only
- [ ] Implemented on www.mozilla.org/firefox/

Prototype:
https://invis.io/SDNAAE3ZCK4

Sketch File:
https://share.goabstract.com/3473d71b-737b-480a-8dd0-658d84692668

**Comment by thejeffreytaylor** [comment]
[Copy doc](https://docs.google.com/document/d/1ijjDcATdeBGWrBdyTWmJ-4la4RIb4Tyepn3VHv7Dy1s/edit?usp=sharing) for all states (not the usual copy deck template due to the nature of this project, but I can drop the text in there anytime upon request).

**Comment by craigcook** [comment]
For further explanation, this is showing a sticky newsletter subscription form at the bottom of the Firefox product page that will appear some time after the initial page load (after scrolling a certain distance? Or after a certain amount of time? Was this decided?). 

It should only be shown when viewports are large enough to show it without obscuring too much of the page (so not shown on small screens). There should be a "close" button to dismiss the sticky form, and if closed it should still appear (non-sticky) further down the page if the user continues to scroll down to it. There's precedent for this treatment on the now-deleted SmartOn pages so some code could be resurrected from git history for reference.

The hypothesis is that making the form more noticeable will get more attention from people who are Firefox-curious but haven't yet downloaded. At present the newsletter form is near the bottom of a very long page so it's easily overlooked or ignored. Making the form more noticeable (but still unobtrusive) should increase the number of subscribers. If this proves successful it may be something we try on other pages as well.

Success criteria above says this is for Windows only. Is that accurate? Unless this is tied to some funnelcake experiment I think this can be shown to all platforms. Do we still want to target non-Firefox or should it be shown to all browsers?

**Comment by michaelmccombie** [comment]
Here are links to the Prototype and Sketch file:

Prototype:
https://invis.io/SDNAAE3ZCK4

Sketch File:
https://share.goabstract.com/3473d71b-737b-480a-8dd0-658d84692668

**Comment by alexgibson** [comment]
> Success Criteria

> non-Firefox en-US visitors on Windows only
> Implemented on www.mozilla.org/firefox/

To me these aren't success criteria, they sound more like requirements.

**Comment by alexgibson** [comment]
Demo:
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

Direct URL variants:
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a (control)
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=b (newsletter)

This is now blocked on analytics requirements & the new email privacy copy page.

**Comment by craigcook** [comment]
I'm working on the "how" page in #5943, should have a PR today. It will need to merge first so you can link to it.

**Comment by ejregithub** [comment]
Measurements: Site sessions -> installs - > retention at 3 weeks -> retention at 6 weeks

**Comment by peterGerman** [comment]
The Experiment will need to run for 2 days with each variant getting 10% or one day with each variant getting 20%. 

Full experiment design coming tomorrow.

**Comment by peterGerman** [comment]
Hey Gang, Draft experiment outline and instrumentation requirements -> https://docs.google.com/document/d/16KGkQt-owZ8l7aunA131fmNRA5LUoWP2kseILvj-z4Y/edit

**Comment by alexgibson** [comment]
@dzingeek @vincejoyiv, I think this is now ready for design QA:

Direct URL variants:

    https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a (control)
    https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=b (newsletter + headline 1)
    https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=c (newsletter + headline 2)

**Comment by alexgibson** [comment]
This is also now ready for analytics QA:

To test, use a **non-Firefox browser on Windows** with **do-not-track disabled** and visit the following URL:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

You have a 20% chance of being redirected to one of the following three variants:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a&utm_source=retention-experiment&utm_medium=email_form_first&utm_campaign=v-1-control (control)
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=b&utm_source=retention-experiment&utm_medium=email_form_first&utm_campaign=v-2-headline-a (newsletter + headline 1)
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=c&utm_source=retention-experiment&utm_medium=email_form_first&utm_campaign=v-3-headline-b (newsletter + headline 2)

Note: if you don't see one of the three variants, you may need to clear session cookies and try again.

We need to ensure that:

- dataLayer events are being tracked correctly.
- data is being passed to the stub installer via stub attribution correctly.

**Comment by hoosteeno** [comment]
> `https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a&utm_source=retention-experiment&utm_medium=email_form_first&utm_campaign=v-1-control` 

We'll need to add a `utm_content` parameter and `utm_source` should be a valid domain (refs below).

We should not clobber the original source/medium/campaign fields -- they are more valuable than the information we're overwriting them with. Let's keep them and simply add a utm_content parameter that distinguishes these clients from others.

I suggest `https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=[VARIATION]&utm_source=[ORIGINAL_SOURCE]&utm_medium=[ORIGINAL_MEDIUM]&utm_campaign=[ORIGINAL_CAMPAIGN]&utm_content=downloader_email_form_experiment_[VARIATION_SLUG]`

---
Refs:
a) utm_content is required (along with utm_source, utm_medium, utm_campaign): https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/validator.go#L15, https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/validator.go#L81

b) utm_source should be a domain on the whitelist: https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/sourcewhitelist.go#L18-L218

**Comment by hoosteeno** [comment]
I'll also just point out that same-site UTM links are a GA no-no. They will cause GA to create a new session on the /thanks page, which will inflate the overall session count and skew attribution and reporting inside of GA. A small experiment doing this may not matter too much, but any large volume of same-site UTM use will make our web analytics less meaningful in lots of ways. Ref: https://holini.com/utm-parameters/#9

**Comment by alexgibson** [comment]
> I'll also just point out that same-site UTM links are a GA no-no. They will cause GA to create a new session on the /thanks page, which will inflate the overall session count and skew attribution and reporting inside of GA. A small experiment doing this may not matter too much, but any large volume of same-site UTM use will make our web analytics less meaningful in lots of ways. Ref: https://holini.com/utm-parameters/#9

I'll defer to our analytics team on what to do here, but I'll note that the UTM params would be present on the `/firefox/` page, not `/downbload/thanks/`.

**Comment by alexgibson** [comment]
@hoosteeno this solution does pose another question however, as it assumes UTM parameters will already be present, whiisn't always the case. There are a couple of options:

- Only enter into the experiment if utm params are present. This may mean we need to run the experiment for longer however, as I'm not sure of the % of visitors who hit this URL with said params.
- If UTM params are not present, add some predefined values that we decide. What should these be?

**Comment by hoosteeno** [comment]
> If UTM params are not present, add some predefined values that we decide. What should these be?

I'm fine with the predefined option. Suggestion:

`https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=[VARIATION]&utm_source=[ORIGINAL_SOURCE or www.mozilla.org]&utm_medium=[ORIGINAL_MEDIUM or download_button]&utm_campaign=[ORIGINAL_CAMPAIGN or firefox_page]&utm_content=downloader_email_form_experiment_[VARIATION_SLUG]`

**Comment by alexgibson** [comment]
Ok, demo is now updated as per Justin's recommendation above:

https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

At this stage, I think we need Analytics Pros to weigh in and provide QA. Thanks, @hoosteeno 💯

**Comment by alexgibson** [comment]
Ok, latest testing instructions:

To test, use a **non-Firefox browser on Windows** with do-not-track disabled and visit the following URL:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

You have a 20% chance of being redirected to one of the following three variants:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a&utm_source=www.mozilla.org&utm_medium=download_button&utm_campaign=firefox_page&utm_content=downloader_email_form_experiment_va (control)
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=b&utm_source=www.mozilla.org&utm_medium=download_button&utm_campaign=firefox_page&utm_content=downloader_email_form_experiment_vb (newsletter + headline 1)
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=c&utm_source=www.mozilla.org&utm_medium=download_button&utm_campaign=firefox_page&utm_content=downloader_email_form_experiment_vc (newsletter + headline 2)

Note: if you don't see one of the three variants, you may need to clear session cookies and try again.

If landing on /firefox/ with existing UTM params, you those shjould be persisted through to the experiment with the exception of `utm_content`. For example:

https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?utm_source=www.mozilla.org&utm_medium=foo&utm_campaign=bar&utm_content=buzz

Could result in: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/?v=a&utm_source=www.mozilla.org&utm_medium=foo&utm_campaign=bar&utm_content=downloader_email_form_experiment_va

We also need to ensure that:

- dataLayer events are being tracked correctly.
- data is being passed to the stub installer via stub attribution correctly.

Reference analytics doc: https://docs.google.com/document/d/16KGkQt-owZ8l7aunA131fmNRA5LUoWP2kseILvj-z4Y/edit

**Comment by alexgibson** [comment]
Updated specs from Analytics Pros: https://docs.google.com/presentation/d/1Chmz2QE29GwCV0S_UaJ6MoTSISxGmq1TAp327nReL7I/edit?usp=sharing

**Comment by alexgibson** [comment]
Demo updated as per the latest specs: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

**Comment by ejregithub** [comment]
@alexgibson - can you indicate how this can be tested on demo?  Also, could you please upload screenshots here for stakeholders to review?
