### ISSUE TITLE
(Due 8/22) [Legal] Trademark Webpages Updates 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5949]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1JwiTM9wXDdDiNCBBWM43Zawf-70cpz4TKV8pDTDjrTw/edit?ts=5b5a0d81#gid=0)
[Slide deck](https://docs.google.com/presentation/d/1puvkxp0xq0YXYtOe8VB5l9Ie71JAiGUY-SPPwG5WPvU/edit#slide=id.g3e45100f31_0_0)

The slide deck informs on the spreadsheet, if needed.

Success criteria
- [ ] Target go live for August 22 pending final copy/QA by Legal
- [ ] Redirects and copy updates can be pushed to prod independent of updates to the honeypot

**Comment by alexgibson** [comment]
For the record via Slack:

"Don’t worry about the CAPTCHA request for now, it’s not a blocker for the other requests, but we will have to get to a better solution than what we have as Legal is wasting a lot of time filtering submissions for violations."

**Comment by ejregithub** [comment]
@amychurchwell - I chatted with Alex, who agrees this could be another good card for you to take on.  Please take a look and ping with any questions.

**Comment by amychurchwell** [comment]
Logos needed for foundation/trademarks/list/:

- Firefox Friends (white text not showing up on white bg -contrast version?)
- Pontoon
- Common Voice
- Pocket Wordmark
- Pocket logos for mac, android, iOs, "other apps."

(Slide 5 on slide deck.)

**Comment by amychurchwell** [comment]
Demo link: https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/

**Comment by ejregithub** [comment]
Logos needed for foundation/trademarks/list/:

- [ ] Firefox Friends
- [ ] Pontoon
- [ ] Common Voice
- [ ] Pocket Wordmark
- [ ] Pocket logo for mac
- [ ] Pocket logo for android
- [ ] Pocket logo for iOS
- [ ] Pocket logo for 'other apps'

**Comment by ejregithub** [comment]
@amychurchwell - the feedback is maintain the current URL /foundation/trademarks/list/ but to revert the update to the h2 you just made to the original plural to stay matching "Mozilla Trademarks List"

**Comment by amychurchwell** [comment]
@ejregithub trademarks/list/ responsive issue will be resolved in this PR.

**Comment by djst** [comment]
What's the actual due date for this work?
