### ISSUE TITLE
Code V1 - /new variation for Safari visitors

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5950]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479085

[Content assets](https://share.goabstract.com/c89ffc12-ca7b-4848-844d-04db048a5ba2)

**Comment by stephaniehobson** [comment]
Time estimates:
Code V1: L
Code V2: M
Traffic Cop: S

**Comment by stephaniehobson** [comment]
I'm going to take V2, the "comparison table" version with the goal of having it in for review before I leave EOD Wednesday.

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/new/?xv=safari&v=1

**Comment by craigcook** [comment]
There was no copy deck, only the Sketch file.

**Comment by thejeffreytaylor** [comment]
Please see Sung for all copy references. I can help on B versions if needed, but he and Kirby are the final authorities here. My involvement is I did some content design work on the tables and edited/re-wrote the copy.
