### ISSUE TITLE
2 /new variations for Edge visitors w. traffic cop

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5951]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479086

[Assets](https://share.goabstract.com/c89ffc12-ca7b-4848-844d-04db048a5ba2)

Success Criteria:
- 2 /new variations live
- Traffic is configured to route traffic according to spec in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1479086)

**Comment by ejregithub** [comment]
@dzingeek @vincejoyiv - please give the pages (v=1 and v=2) above a QA review and ping me if we are good to pass it to the New User aDAU team for the same signoff.

**Comment by dzingeek** [comment]
In general both designs look good. I, however, can't truly test these as I don't have edge. @ejregithub can you find someone who has edge to confirm that the design looks the same as it does in firefox?
