### ISSUE TITLE
2 /new variations for Chrome visitors w. traffic cop

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5952]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479087

[Design Assets](https://share.goabstract.com/c89ffc12-ca7b-4848-844d-04db048a5ba2)

Success Criteria:
- 2 /new variations live
- Traffic is configured to route traffic according to spec in the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1479087)

**Comment by ejregithub** [comment]
Assets for one of the new variations (2) are  now ready.

**Comment by alexgibson** [comment]
These pages are live, closing.
