### ISSUE TITLE
Experiment: new download button styles

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#5958]
We want to redesign our standard download button but need to do some testing to determine that proposed changes are an improvement or at the very least don't perform any worse than the current button.

The current download button has white text on a bright green background that fails general accessibility guidelines for minimum color contrast. We want to test a darker green variant that will be more readable.

We also want to test a blue download button as a step towards updating our overall color palette.

The plan is to set up a short-lived A/B test on the Firefox desktop product page with three versions of the button in the top "hero" section; the current bright green button, a darker green button, and a blue button.

cc @dzingeek

**Comment by dzingeek** [comment]
@craigcook I think that looks good. Let's talk to @ejregithub to see when we can start this test.

Oh one other thing, we would like to run this test soon before we start the email experiments on the /firefox page.

**Comment by dzingeek** [comment]
@craigcook and @ejregithub 
Since we are now just moving forward with the new blue button can we remove this experiment?

**Comment by ejregithub** [comment]
Let me ask the New User aDAU team if they're interested in this one (they being the team that requested the blue button).

**Comment by dzingeek** [comment]
@ejregithub 
So we are just moving forward with the blue button, no reason to really test it. It's already being used on the homepage and other places. I don't really want to make it seem like there is an option for another color at this point.
