### ISSUE TITLE
[Indonesian What's New Page for Firefox Rocket] Replace "Firefox Rocket" logo and copy with "Firefox Lite" 

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#5965]
The rebrand for Firefox Rocket has gone live. So we need to update the copy and the logos used to refer to this product on support.mozilla.

[Link to Play Store](https://play.google.com/store/apps/details?id=org.mozilla.rocket)

### Zip Folder with Assets
[Firefox Lite.zip](https://github.com/mozilla/bedrock/files/2254538/Firefox.Lite.zip)

**Comment by michaelmccombie** [comment]
We also have another open issue that has to do with that page.
https://github.com/mozilla/bedrock/issues/5834

**Comment by michaelmccombie** [comment]
Waiting for the thumbs-up from the Taipei team

**Comment by stephaniehobson** [comment]
See also: https://github.com/mozilla/bedrock/issues/5968

**Comment by michaelmccombie** [comment]
The Taipei team is still testing the new logo so we need to revert this merge and reopen the issue.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/6354
