### ISSUE TITLE
On Ubuntu18.04.1 LTS, pip install -r requirements/dev.txt fails

### ISSUE THREAD

**Issue by Sancus** [mozilla/bedrock#5967]
`Collecting setuptools (from icalendar==3.8.3->-r requirements/base.txt (line 11))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools from https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl#sha256=d68abee4eed409fbe8c302ac4d8429a1ffef912cd047a903b5701c024048dd49 (from icalendar==3.8.3->-r requirements/base.txt (line 11))`

The above is the error I get. This happens even if setuptools 40.0.0 is already installed via pip. This is on a clean Ubuntu18.04.1 LTS VM, with nothing installed except apt-get `python, python-pip, and git`.

**Comment by Sancus** [comment]
I'll also note that using hashin to add hashes for either setuptools==39.2.0 or 40.0.0 resolves the issue, but pinning a version of setuptools when there's really no good reason for it seems suboptimal.

**Comment by Sancus** [comment]
This issue is caused by icalendar 3.8.3 having setuptools in its requirements, which is not only redundant it is apparently harmful because [pip does not have a real dependency resolver](https://github.com/pypa/pip/issues/988).

This triggers a bug similar to https://github.com/certbot/certbot/issues/5195 where pip will try to install dependency requirements based on the order it encounters them which can be different from platform to platform or even from user to user, I suspect.

icalendar 3.11.3 removes the redundant setuptools requirement, so updating to any version past that should work. I'm only using the check_calendars.py script and it seems to work as expected with icalendar==4.0.2 so I'm updating to that on the Thunderbird website.

Bedrock may be able to remove icalendar entirely from the code since calendars don't need to be displayed or submitted on bedrock anymore?

**Comment by pmac** [comment]
Nice work @Sancus! I think we do still need icalendar since we do still ingest some ical feeds from [reps](https://reps.mozilla.org/events/), but it sounds like we should upgrade. Thanks!

**Comment by brainwane** [comment]
Hi! please [try the beta of the new pip dependency resolver in pip 20.2](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) and see whether that helps?

**Comment by pmac** [comment]
This issue is very old. I don't believe this is an issue any longer. Closing. Thanks all.
