### ISSUE TITLE
[mozilla.org/privacy/firefox-rocket] Replace "Firefox Rocket" logo and copy with "Firefox Lite" 

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#5968]
This is another page that would need an update to the logo/ copy.
https://www.mozilla.org/en-US/privacy/firefox-rocket/

![image](https://user-images.githubusercontent.com/5924575/43607721-e7a97cbe-9653-11e8-8f9d-b1a813d81726.png)

![image](https://user-images.githubusercontent.com/5924575/43608180-647fccce-9655-11e8-92c6-7ecdf75f5926.png)

**Comment by michaelmccombie** [comment]
@rraue the current URL for this page is /privacy/firefox-rocket. I'd assume that would need updating as well, not sure what that means for SEO.

**Comment by rraue** [comment]
@michaelmccombie Yes you are right, if the name change is permanent and not a test we should update all urls named -rocket to -lite and redirect the old ones 301.

**Comment by ejregithub** [comment]
Before we go too far on this page, i'm consulting with Legal. Blocking this card until we have direction from them (which may include archiving the original Rocket privacy notice).

**Comment by alexgibson** [comment]
This was fixed in https://github.com/mozilla/bedrock/pull/6297
