### ISSUE TITLE
Remove unused /firefox/new/ templates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#5982]
We have a rather large collection of download page variations which are growing unwieldly once again:

https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L607-L643

Rather than leaving this unchecked for much longer, I think it's probably time we remove any pages / URLs that are no longer in use.

The following seem to be likely candidates:

- [x] Wait Face
- [x] Reggie Watts
- [x] Portland Campaign
- [x] We also have a suprising number of Berlin campaign pages. Are all of these experiments still in use, or can we remove some of those that did not perform as well as others?

Fixing issue https://github.com/mozilla/bedrock/issues/5094 may also help us make this kind of thing more managable over time.

**Comment by alexgibson** [comment]
@ejregithub can you please try and find out if we can remove any of these? thanks

**Comment by stephaniehobson** [comment]
The /de/ landing page variation is part of an on going a/b test that should be ending soon.

The 3 Berlin campaign pages have only been around a few weeks. I don't see any evidence in the analytics that they've been part of a campaign yet. It would be nice if we had a date we could remove these by but I don't think it's passed yet.

**Comment by stephaniehobson** [comment]
Wait Face and Reggie Watts are gone in #6576

**Comment by alexgibson** [comment]
These templates have either been decomissioned or moved to /campaign.
