### ISSUE TITLE
Test - snippet-like banner w. email CTA

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5985]
The idea here is to show a sticky newsletter subscription form at the bottom of the Firefox product page that will appear some time after the initial page load (after scrolling a certain distance? Or after a certain amount of time? Was this decided?).

It should only be shown when viewports are large enough to show it without obscuring too much of the page (so not shown on small screens). There should be a "close" button to dismiss the sticky form, and if closed it should still appear (non-sticky) further down the page if the user continues to scroll down to it. There's precedent for this treatment on the now-deleted SmartOn pages so some code could be resurrected from git history for reference.

If someone dismisses the form we should set a short-lived cookie (a few days? Just a session? I think we used sessionStorage on SmartOn; I'd have to look again) so we don't show it again right away. There's also some concern over having too many email prompts if we do this experiment while one of our other experiments is also running, so we'll have to decide timing and targeting. If someone has deliberately closed this prompt and then continues to download, perhaps we should take that user action as an emphatic "no" and NOT show them another email prompt mid- or post-download. Something to think about.

The hypothesis is that making the form more noticeable will get more attention from people who are Firefox-curious but haven't yet downloaded. At present the newsletter form is near the bottom of a very long page so it's easily overlooked or ignored. Making the form more noticeable (but still unobtrusive) should increase the number of subscribers. If this proves successful it may be something we try on other pages as well.

Success criteria TBD. 

Questions:

- A/B test against the current static newsletter form, or 100% to all?
- Multivariate test with different copy or designs?
- Firefox only, non-Firefox only, or all browsers?

**Comment by dzingeek** [comment]
**Link to the deck that highlights goals and user flow**
https://docs.google.com/presentation/d/1y8z1k0-xyBNIXZ865mpa3WKV9cTjew5PQFrFtJ5Pyu4/edit?usp=sharing

**Comment by hoosteeno** [comment]
@dzingeek is this a test the brand team hopes to run in 2020? If not, can we close and reopen at some later date if it is a priority again?

**Comment by dzingeek** [comment]
@hoosteeno I think we can close this for now, thanks for checking.
