### ISSUE TITLE
[ASAP] Remove Mozilla Board member from Leadership page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6002]
Cathy Davidson has officially left the Mozilla Board, we need to remove her listing on the leadership page.

Success Criteria:
- The listing for Cathy Davidson is removed from the 'Mozilla Foundation' section in https://www.mozilla.org/en-US/about/leadership/

**Comment by kyoshino** [comment]
https://www.mozilla.org/en-US/foundation/about/ also needs to be updated.

**Comment by stephaniehobson** [comment]
Thank you @kyoshino! 

@amychurchwell Can you please remove it from the other page too?

**Comment by amychurchwell** [comment]
@stephaniehobson Done, just needs review. #6007

**Comment by ejregithub** [comment]
@amychurchwell - a(nother) late breaking addition from the requestor:

Cathy should be added into the Emeritus section of this page: https://www.mozilla.org/en-US/about/leadership/#directors

ping me with any questions, please
