### ISSUE TITLE
Code V2 - /new variation for Safari visitors

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6003]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479085

[Content assets](https://share.goabstract.com/c89ffc12-ca7b-4848-844d-04db048a5ba2)

Success Criteria:
- Version number 2 is live (not dependent on [Version 1](https://github.com/mozilla/bedrock/issues/5950) or Traffic cop)

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/new/?xv=safari&v=2
