### ISSUE TITLE
Pocket logo out of proportion on /firefox/accounts/features page

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#6012]
The logo on the /firefox/accounts/features page has been stretched beyond to be a little taller than it actually is so we just need to replace that with an in-proportion logo. Here is a link to the Pocket logo we have in the Protocol assets library: https://github.com/mozilla/protocol-assets/blob/master/logos/pocket/pocket.svg

![image](https://user-images.githubusercontent.com/5924575/44107775-50a2a9e0-9fad-11e8-90d2-6fc3345175f0.png)

**Comment by stephaniehobson** [comment]
I matched the old height of the icon so it is much wider now. 

<img width="1148" alt="screen shot 2018-08-14 at 11 34 27" src="https://user-images.githubusercontent.com/854701/44110978-065bf16c-9fb6-11e8-881a-6c7e481dca7f.png">
