### ISSUE TITLE
/firefox/accounts/features/ layout issues in RTL

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6015]
This isn't an issue in production as the page has yet to be localized, but running locally I noticed some layout issues for RTL locales. We should make sure we fix these before we open the page up to translators.

Perhaps we could update the page to use Protocol components instead (which should support RTL out of the box).

![screenshot_2018-08-15 get a firefox account - sync passwords bookmarks and tabs everywhere](https://user-images.githubusercontent.com/400117/44139335-b34a1288-a06e-11e8-92c2-21a4efd30b3a.png)

**Comment by dzingeek** [comment]
Could this also be a good time to iterate on this page? See if we can improve it and add the iframeless form now that we have it? If so let me know and I can start to look into it.

**Comment by dzingeek** [comment]
Well, I think we also need to get this page into protocol too..not sure if that affects strings or not. I can work with a dev on this to see what we can do and still achieve our goal. we can always iterate on later once we get it localized.

**Comment by ejregithub** [comment]
Oh, sure.  "Protocolizing" a page should have no bearing on l10n.

**Comment by alexgibson** [comment]
Actually, one way to fix all these RTL issues would be to port the page to Protocol (since those components already support RTL out of the box).

**Comment by dzingeek** [comment]
**Design Question:** 
Would it be possible to redesign the header and bottom blue section of the page as long as we don't touch the copy? Also, can we add the iframless form to this page? Or would that effect strings?

**Comment by alexgibson** [comment]
> Would it be possible to redesign the header and bottom blue section of the page as long as we don't touch the copy?

I think so, yes.

> Also, can we add the iframless form to this page? Or would that effect strings?

Those strings are global, so can be safely used on any page.

**Comment by alexgibson** [comment]
This page no longer exists, closing.
