### ISSUE TITLE
Internet Health page content caching problem

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#6016]
The main IH page randomizes the order of the "issues" section on the server side. This means that to the server and the CDN the page appears to change with nearly every request. If possible it would be better to do this shuffling using JS on the client side so that the payload from the server can remain constant.

Thoughts @alexgibson?

**Comment by alexgibson** [comment]
Hmm, I forgot this page does this. I seem to remember asking if doing this kind of thing was OK in jinja, and at the time there weren't any concerns  - but if that's no longer true then we can change it. This is a very old page, so I'd say even removing the shuffling altogether would likely be fine.

**Comment by pmac** [comment]
Yeah. The shuffling is neat in that it changes the primary image for that section, but it's so far down the page it's not likely to be noticed. I'm fine either way.

To be clear this is not a big deal. But in my attempts to improve the sitemap and detect when pages change so we can add "last modified" dates this is frustrating, and it does make the page less cachable since the HTML change makes the `etag` header for the page change quite often.

**Comment by alexgibson** [comment]
Then I'd say let's just remove the shuffle altogether . Thanks @pmac 👍

**Comment by pmac** [comment]
Sounds good. Thank you @alexgibson 🎉

**Comment by pmac** [comment]
@alexgibson I'll knock this out. Should be quick. Do you happen to have a preference for which one of the items should be the "featured" one with the image on the left side?

**Comment by alexgibson** [comment]
> @alexgibson I'll knock this out. Should be quick. Do you happen to have a preference for which one of the items should be the "featured" one with the image on the left side?

I'd say choose the privacy feature 👍
