### ISSUE TITLE
/About Redesign UX Design

### ISSUE THREAD

**Issue by thejeffreytaylor** [mozilla/bedrock#6019]
Create User Flow + Wireframes for redesigned /About 
[Link to epic if available](url)
[_Link to project brief here_](url)
[_Link to user flow/wireframes_](url)
[_Link to copy deck_](url)

- [x] Document User Journey

- [x] Create Wireframes

- [x] Internal Design Review (devs + managers)

- [ ] Get approval from stakeholders

**Comment by alexgibson** [comment]
@djst this is a mock project board (for the thing you asked myself and jennifer to work on). We're using it as an example for how we think our team should structure work on GitHub. Once it's ready we can discuss as a group, but for now please ignore as this is all just for example purposes.

**Comment by AllenChong** [comment]
issue
