### ISSUE TITLE
/About Redesign Due XX/XX

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6024]
**/About Redesign Deadline xx/xx**
Is off-brand, dated, has A11y issues, has usability issues, and is just not a reflection of today’s Mozilla. While overall traffic is low compared to the homepage, employing UX and SEO best practices for an /About redesign will have that ensure that the traffic we do get serves our business goals.

Link to all user stories: https://docs.google.com/document/d/1op2sQfY_l73vkwZL1W20FtZvTDhNuuu_89aM4bhDGVQ/edit?usp=sharing

[Link to Resources](url)
[Analytic Requirements](url)

**Estimated Size **
_Measure 1/2 days to full days_

- SEO Work = 1 day
- Content Work = 3 days
- Dev. Work = 4 days
- UI Work = 4 days
- UX Work = 3 days
- QA = 2 days

**Total = 17 days**

**Comment by alexgibson** [comment]
This work was completed in another issue.
