### ISSUE TITLE
/About Email Signup Experiment Due XX/XX

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6025]
Due Date xx/xx
High-level description on what the test is about.
[Link to doc](url)
[Link to mana page](url)

**Estimated Size **
_Measure 1/2 days to full days_

- SEO Work = 1 day
- Content Work = 2 days
- Dev. Work = 4 days
- UI Work = 1 day
- UX Work = 1/2 day
- QA = 1 day

**Total = 9.5 days**

**Comment by alexgibson** [comment]
I believe this was a placeholder example for a project board demo. Please re-open if incorrect.
