### ISSUE TITLE
/About Email Signup Exp. User Journey Research

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6028]
Research current user journey and find areas that could be improved in user flow.
[Link to epic if available](url)
[Link to project brief here](url)
[Link to Mana page](url)
[Link to user flow](url)

- [ ] Document Current User Journey

- [ ] Internal Design Review (devs + managers)

- [ ] Get approval from stakeholders

**Comment by alexgibson** [comment]
I believe this was a placeholder example for a project board demo. Please re-open if incorrect.
