### ISSUE TITLE
Newsletter on /download/thanks/ incorrectly sized when using IE

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6031]
I didn't pick up on this during code review (apologies), so I'm not sure if it was a last minute regression that snuck in perhaps, but in any version of IE the newsletter on `/download/thanks/` is incorrectly sized. Looks fine on Edge.

<img width="473" alt="screen shot 2018-08-16 at 10 26 20" src="https://user-images.githubusercontent.com/400117/44200661-0b560b00-a13f-11e8-970c-57a893ea1ca2.png">

**Comment by ejregithub** [comment]
@alexgibson - can you please apply an Estimate to the effort/complexity for this work?

**Comment by alexgibson** [comment]
> @alexgibson - can you please apply an Estimate to the effort/complexity for this work?

I can't find this issue on zenhub, so I'll provide an estimate here: 2

Thanks
