### ISSUE TITLE
Careers site - people image updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6032]
- [ ] update language/description in each hexagon

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/44221037-23c12800-a135-11e8-8173-2097b7ae1587.png)

**Comment by dzingeek** [comment]
@ejregithub are we getting an image from someone to replace the current image? Or is this something I need to spend time finding on my own?

**Comment by ejregithub** [comment]
@dzingeek - I'm going to ping Rainer as @djst suggested.  He's working from Europe now and then on PTO next week, hopefully I can catch him before he heads off and avoid looking ourselves.

**Comment by djst** [comment]
![image](https://user-images.githubusercontent.com/5638050/44257290-dcf23180-a20b-11e8-9e78-8fc6dd1aebf3.png)

**Comment by ejregithub** [comment]
Closing this issue, latest requirements have been moved to this card - https://github.com/mozilla/bedrock/issues/6052
