### ISSUE TITLE
[Due for 9/5] Update ESR content on www.mozilla.org corresponding to ESR 52 deprecation

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6034]
Success Criteria:

- [ ] Remove ESR 52 content in https://www.mozilla.org/en-US/firefox/organizations/ - Place behind a switch, flip switch early on 9/5:  
- [ ] Confirm with engineering that setting for ESR 52 will be removed in https://www.mozilla.org/en-US/firefox/organizations/all/ 

Note that no changes are required in https://www.mozilla.org/en-US/firefox/enterprise/

**Comment by kyoshino** [comment]
Bugzilla: [Bug 1463436](https://bugzilla.mozilla.org/show_bug.cgi?id=1463436)
