### ISSUE TITLE
Bug: Something goes here about a bug that needs to be addressed for the /about page

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6041]
What is the issue:
What needs to be fixed:

**Comment by pmac** [comment]
um... is there a bug? I don't believe we need placeholder issues for any reason. Feel free to reopen if there's a bug I guess.

**Comment by dzingeek** [comment]
This is a demo project. We are using this to mockup ideas on how we want to use github and create a better process. Please ignore anything in this project.

**Comment by pmac** [comment]
This repo is watched by 99 people and starred by nearly 700. That's a lot of false notifications. Please open a new testing repo to open testing issues.

**Comment by dzingeek** [comment]
K, will do thanks for the heads up.
