### ISSUE TITLE
[Due 10/30] Data Leeks website (formerly Breached Recipes)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6043]
[Brief](https://docs.google.com/document/d/1HPI04MmxrG_LD25sGfH3aLSy_tmfMT6qeYI-Z59uqAw/edit)

Success Criteria:
- [ ] Site is built with existing WP theme
- [ ] Site is live Oct 30th
- [ ] en-US only at launch (monitor.firefox.com will not be localized at launch)
- [ ] Developer hours NTE 3 days

Tasks:
- [ ] Vet WP theme, select winner and backup
- [ ] Set up WP instance and apply theme

**Comment by ejregithub** [comment]
@rraue - can you comment on the preferred URL for this with regard to structure?
Should it be projectfoo.mozilla.org or blog.mozilla.com/projectfoo

**Comment by ejregithub** [comment]
@craigcook - can you let us know if making this a multi-lingual site is as easy as I recall?  If so, can we open it up to that, DE specifically if that's a required setting?

**Comment by ejregithub** [comment]
per Craig: Savor is top choice for WP theme with Elara as a backup

**Comment by rraue** [comment]
@ejregithub Its not very important but blog.mozilla.org/projectfoo would be better.

**Comment by djst** [comment]
Where is this project being tracked? I don't see a separate project board, is one needed?

**Comment by craigcook** [comment]
General update on this project (based on my current understanding):

In the end there was a severe shortage of publishable recipes, which pretty much undermined the entire original concept for the site. It was decided to pivot to a more general-purpose info hub about data breaches, with articles, tips, guidelines, etc.

The intent is still to use an off-the-shelf WordPress theme and minimize the engineering effort, but the timeline for getting the site live has shifted accordingly. I'm not sure what the current deadline may be, perhaps still by the end of October or early November.

**Comment by craigcook** [comment]
Alright, minor correction... they did apparently track down enough recipe-like content to move forward with the recipes as a framing concept. Tentatively aiming for an Oct 30 launch.

**Comment by ejregithub** [comment]
This work was removed from the Websites queue with the decision to host it on SquareSpace
