### ISSUE TITLE
Missing urls in sitemap

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6048]
I was now able to test and crawl the sitemaps live and found some pages missing in the sitemap. Weirdly all locale /about/ pages aren't in the sitemap but the en-US version is. The rest are the pages always showing up when something is missing like old releasenotes and system requirements. I did a list of pages not in the sitemap but indexable and 200: https://docs.google.com/spreadsheets/d/15iRo0ospuuQqSgI6YUtBKdGvqfMUHj8Awzv8PE7ssX8/edit?usp=sharing

And /firefox/all/ is in the sitemaps for all locales, but isn't indexable, so we should remove it.

There are some old pages ending with .html, these pages do not need to be included, @dzingeek and @thejeffreytaylor we need to figure out what to do with them.

**Comment by pmac** [comment]
Addressing the /about/ page in #6047. I assume we don't want any `/firefox/*/all/` pages in the sitemap?

**Comment by pmac** [comment]
@rraue I've deployed some fixes to [my demo site](https://bedrock-demo-pmac.oregon-b.moz.works/en-US/sitemap.xml) again. It should now have the grants urls, no longer inlucde /firefox/*/all/, and fix many missing urls. I have not done anything about the system-requirements or known-vulnerabilities urls. We can discuss those.

**Comment by pmac** [comment]
@rraue and now the system-requirements urls are there. Let me know what you think and we can land these changes. I can go ahead and file the pull request.
