### ISSUE TITLE
Add analytics to Pocket product page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6050]
The page was initially built without any special tagging or events for GA. I suspect we just need to add some data attributes for the primary and secondary CTAs: the "Learn More" button at the top and the "Try Pocket NOw" button at the bottom.

Success Criteria:
- [ ] Get data and analyze for performance of interstitial page
- [ ] Get data and analyze for performance after removal of interstitial page (at getpocket.com)

**Comment by ejregithub** [comment]
@craigcook - was the page ever updated, perhaps in a separate issue, or is this still pending?

**Comment by craigcook** [comment]
I don't think we ever made any changes, but it's also possible we're already collecting all the data we need without doing anything special.

**Comment by djst** [comment]
@rraue will do the same analysis as he did last time when we compared pre and post interstitial page. The hypothesis is that bounce rate and signup rate on getpocket.com should fall somewhere in between those two extremes.

**Comment by rraue** [comment]
The page is not longer linked in the main navigation and just around for seo purpose, so this analysis is no longer needed: https://github.com/mozilla/bedrock/issues/6450
