### ISSUE TITLE
Careers site updates (short term tasks)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6052]
Success Criteria:

- [x] Each hexagon is update w. new copy reflective of current Mozilla brand
- [x] remove all 6 photos of people, and their quotes
- [x] keep only the team descriptions and CTA on each sub-page

**Comment by thejeffreytaylor** [comment]
Natalie Linden and I met with Tori Covington yesterday. She's asked us to hold for a sec so she can secure copy requirement feedback on Friday, and also to consult with Michael to ensure there's no other red flags that may cause another senior executive to come back and ask for another redesign.

**Comment by thejeffreytaylor** [comment]
Nothing from Tori as of AM of Tuesday 28 August. I've emailed her.

**Comment by thejeffreytaylor** [comment]
H[ave the feedback here.](https://docs.google.com/document/d/1XiE85gkZZVgBH2_x6fo3ld586eOPdfuK5bCQNoFLMcg/edit?usp=sharing) Working with Natalie to take this home. @ejregithub and @djst You may want to take a look at this and see if we need to manage expectations with the people team for near-term and long-term efforts.

**Comment by thejeffreytaylor** [comment]
Natalie will be providing copy on this going forward.

**Comment by ejregithub** [comment]
@stephaniehobson - Natalie is going to provide that final copy update for the pending item here.

**Comment by natalielinden** [comment]
@stephaniehobson Would the following copy work in the hexagon for "Building & Designing"? Will it fit the space? 
_Working in the open, for the greater good_

**Comment by stephaniehobson** [comment]
It fits! I will get it in there. Thank you :)

**Comment by natalielinden** [comment]
WOOOO HOOO! Sorry I inadvertently made it take three weeks for you to get it. : /

**Comment by stephaniehobson** [comment]
@ejregithub I think we should call this one closed once the wording change merges, rather than trying to do a comprehensive update.

**Comment by ejregithub** [comment]
Agreed.  A quick glance in the code looks like the first Success Criterion, the last one remaining has been met.
