### ISSUE TITLE
Dublicate title on /system-requirements/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6053]
https://www.mozilla.org/en-US/firefox/xxx/system-requirements/ and https://www.mozilla.org/en-US/firefox/android/xxx/system-requirements/ have always the same <title>. that's not good SEO, as a search engines needs different titles for differnet documents. 

Title Android now: Firefox — 61.0.1 System Requirements — Mozilla
Fixed title: Firefox Android 61.0.1 System Requirements — Mozilla

Title desktop now: Firefox — 61.0.1 System Requirements — Mozilla
Fixed title: Firefox 61.0.1 System Requirements — Mozilla

The — in the title is overly technical and not necessary even on such a technical page. Do you agree @thejeffreytaylor or have even a better suggestion for the title?

**Comment by rraue** [comment]
@stephaniehobson it's a similar task like with the releasenotes, I am not sure if the variable is available like this, but anything that solves the duplicate and talks better to users works for Seo.

**Comment by stephaniehobson** [comment]
If we add the channel in like we did with the Release Notes I think we end up with:

Firefox 61.0.1 System Requirements — Mozilla
Firefox for iOS 12.0 System Requirements — Mozilla
Firefox for Android 61.0 System Requirements — Mozilla
Firefox Beta 62.0beta System Requirements — Mozilla
Firefox Nightly 62.0a1 System Requirements — Mozilla
Firefox for Android Beta 62.0beta System Requirements — Mozilla

I'll have to check if we have the channel information available but I don't see why not.

**Comment by stephaniehobson** [comment]
Ended up not including the "channel".

These are as requested:
Firefox 61.0.1 System Requirements — Mozilla
Firefox for Android 61.0 System Requirements — Mozilla

And Nightly will show up as:
Firefox 62.0a1 System Requirements — Mozilla

I can add the channel if there's any value to that.

**Comment by rraue** [comment]
@stephaniehobson If its not much work, I would go with the most distinguished title, so with the channel. But only if it's easy to get the channel here, as these type of pages will not be search rocking pages.

**Comment by stephaniehobson** [comment]
@rraue It's not much trouble. I removed it because it made the current into "Firefox Release" which will be confusing to users. I think I can just exclude the channel when it's release.

The other thing I was wondering about was if it is okay for these page titles to be changing as the different versions get released. The 61.0.1 page will go from Nightly to Beta to Release over time.

**Comment by rraue** [comment]
@stephaniehobson That's not ideal but its okay as the title should reflect what the page is about. And if this changes that's fine.
