### ISSUE TITLE
[August] Homepage content updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6055]
Success Criteria:

- [ ] homepage updated with [new content](https://docs.google.com/spreadsheets/d/14e4UMW1FIntdB-DU6WFq_tsUO21d2MJF0jsS2hP_Gok/edit#gid=0) 

* handy mock up in [Airtable](https://airtable.com/shrVQdWrXYQus2NqT). (Be sure to click on the Next Record link at the top of the page to get to the 8/10/2018 edition)

**Comment by ishanrai05** [comment]
Hi, I would like to help with this issue.

**Comment by alexgibson** [comment]
@ejregithub please note here there's a bit more work than just content updates. The home page editorial team is moving to using YouTube for all their videos, as exporting the different formats was taking too long in terms of resourcing. That means for this update, we'll need to write some new JS that uses the [YouTube Player API](https://developers.google.com/youtube/iframe_api_reference), so we can lazy-load the videos when people click to open the modal.

I can discuss this with @amychurchwell if/when she picks this up, if that helps.

**Comment by amychurchwell** [comment]
@ejregithub we tend to avoid animations unless they are demonstrating product features. I'll create static images so we can get the changes out. If there is a need for the images to be animated on the homepage the team can discuss it further. 🙂
