### ISSUE TITLE
Bug bounty pages have duplicate titles

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6062]
All four bug bounty pages have the same title and are therefore harder to distinguish for search engines. We are currently ranking for "bug bounty" on 17 and jumping to at least the first search result page would probably get us more bug reports. The h1 is different and so should be the title.

https://www.mozilla.org/en-US/security/web-bug-bounty/
Title now: Mozilla Security Bug Bounty Program — Mozilla
Title then: Web and Services Bug Bounty Program — Mozilla

https://www.mozilla.org/en-US/security/bug-bounty/
Title now: Mozilla Security Bug Bounty Program — Mozilla
Title then: Security Bug Bounty Program — Mozilla

https://www.mozilla.org/en-US/security/client-bug-bounty/
Title now: Mozilla Security Bug Bounty Program — Mozilla
Title then: Client Bug Bounty Program  — Mozilla

https://www.mozilla.org/en-US/security/bug-bounty/faq/
Title now: Mozilla Security Bug Bounty Program — Mozilla
Title then: Bug Bounty Program FAQ  — Mozilla

**Comment by ishanrai05** [comment]
hello.. I'd like to help with issue.. I

**Comment by ishanrai05** [comment]
Is the issue still open? I'd like to help.
