### ISSUE TITLE
[Sept 4 or sooner] Updates to Developer Edition pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6081]
[Work request](https://docs.google.com/document/d/19WYyoDub7hbKbJonAJkqV-y09g0WuX3FKpJvSE1Eoew/edit)

Success Criteria:
- [x] https://www.mozilla.org/en-US/firefox/developer/ is updated with new content
- [x] https://www.mozilla.org/en-US/firefox/62.0a2/firstrun/ is update with new, duplicate content
- [ ] https://www.mozilla.org/en-US/firefox/61.0a2/whatsnew/ is update with new, duplicate content
- [ ] Updates are live in production on Sept 4th
- [x] localization is NOT required

**Comment by martinbalfanz** [comment]
There are 2 outstanding items on our task list that we may have not communicated clearly:
* add learn more links to the shape editor and font editor on the firstrun and whatsnew pages
* exchange the font editor static image with an animation

I addressed both items in PR #6122 :)
