### ISSUE TITLE
Lean Data - Analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6096]
Analytics size =  1 hour

Tasks

- [  ] vet pages for any interactions requiring tagging GA/GTM

**Comment by ejregithub** [comment]
From @rraue A subdomain I wouldnt use for this, as the volume around this keywords is too small and tehre will be not much content either. **So the url right now is good**

**Comment by dzingeek** [comment]
We need to make sure we keep track of the basic here. Time on page, links clicked...that sorta stuff. This is probably standard but I still wanted to mention it.
