### ISSUE TITLE
Lean Data - SEO 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6098]
Seo reviews and consults with:

- [ ] Urls
- [ ] title
- [ ] meta description
- [ ] copy
- [ ] internal links to the pages

**Comment by dzingeek** [comment]
@rraue now that we know this is not a separate website but will live on https://www.mozilla.org/en-US/about/policy/lean-data/ is there still no need for SEO? If so can you comment on this then move it to done?

**Comment by rraue** [comment]
@dzingeek If it is on www we should do the normal process of me reviewing title, url, meta description and copy. I will update this description.
