### ISSUE TITLE
moz.org Footer redesign for Nav/IA updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6104]
Updating the footer is required in order to launch the Nav test

[Nav Outline Copy Doc](https://docs.google.com/document/d/1g0N8oy0WSOY218LJjDIslBbVOmNaBY4Agnfo-cvp6wA/edit?usp=sharing)

**Comment by stephaniehobson** [comment]
Copy: https://docs.google.com/document/d/1g0N8oy0WSOY218LJjDIslBbVOmNaBY4Agnfo-cvp6wA/edit#heading=h.vvqh5av6uul

**Comment by stephaniehobson** [comment]
Demo is online here: https://demo1--mozilla-protocol.netlify.com/demos/footer.html

Still cleaning up the Protocol documentation.

**Comment by stephaniehobson** [comment]
Demo is updated with proper documentation: https://demo1--mozilla-protocol.netlify.com/

Initial PR is here: https://github.com/mozilla/protocol/pull/237

**Comment by stephaniehobson** [comment]
Updated the demo: https://demo1--mozilla-protocol.netlify.com/patterns/organisms/footer.html

**Comment by stephaniehobson** [comment]
Depends on https://github.com/mozilla/protocol/pull/237

**Comment by stephaniehobson** [comment]
@ejregithub I added this car to the board but it might be more appropriate to add the protocol card to the sprint. Feel free to update if you would prefer the other way.

**Comment by hoosteeno** [comment]
Current status: Needs someone to pick up and ship to Bedrock. Should probably wait until the nav is localized. Likely to be blocked by l10n; assessing it for new strings should come next. If no new strings, easier to activate. This is blocking changes to protocol until this is done.

**Comment by peiying2** [comment]
Here is the status of new navigation page l10n progress: https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=navigation.lang

**Comment by alexgibson** [comment]
@peiying2 can you please help to interpret what this dashboard recommends? I see at the bottom it says "Complete locales: 30 (26%) - 83.01% of our l10n user base. This file is not supposed to be activated". What can be considered enough coverage in terms of % to merge? Also when we do merge, what happens to any locales that haven't completed the work? Just want to make sure we understand the impact so we can assess when is a good time.

**Comment by peiying2** [comment]
@alexgibson this means 30 locales (representing 26% of the entire locales on production on mozorg) and 83.01% user base. I remember our threshold in general is 80%+ and it's good to switch over. But I will let the team decide if this is high enough.

**Comment by hoosteeno** [comment]
That's good info. What happens for visitors from locales that are not ready, if we switch over now? Do they get the new footer in en-US?

**Comment by alexgibson** [comment]
> What happens for visitors from locales that are not ready, if we switch over now?

I'd very much like to understand this too. If all those locales default to en-US pages and lose their activation status then we could wait a bit longer, and consider make a last call for translations? Thoughts @peiying2?

**Comment by peiying2** [comment]
@alexgibson I assume if the page defaults to en-US, users would most likely stuck on the US site. It may switch back at some point if user language preference setting is another locale.
I will send a reminder on this. In the past, when a home page (mozorg or fx) was defaulting to en-US, the community would ask us why their localized pages were gone, and we reminded them they fell behind.

**Comment by alexgibson** [comment]
@peiying2 thank you! That sounds great.

**Comment by peiying2** [comment]
I think they should be on the localized site, just en-US content at nav bar/layout, because unlike activated page controlled on the l10n side, this setup could make the page look partially localized (footer, the page itself and nav bar) because it is made up by several components. Anyway, I have sent out reminders.

**Comment by alexgibson** [comment]
The nav is now localized at "locales: 36 (32%) - 92.65% of our l10n user base". Given that the threshold is generally around 80%, I think we may now be in a position to merge the navigation? If locales that have not yet completed the work and will see some English strings (as opposed to lose activation status entirely), then I think this is probably ok.

Thoughts @peiying2 and @hoosteeno?

**Comment by peiying2** [comment]
I am good with merging the navigation now. Those that have not localized it will catch up as soon as they see it in English. I will send reminder in our next monthly l10n report.

**Comment by hoosteeno** [comment]
I agree: We should launch the new navigation! Thank you @peiying2 and @alexgibson .

**Comment by alexgibson** [comment]
The nav has now merged, so I think this work can be unblocked. I'm not clear if there are any new string changes associated with the new footer rolling out, but we can perhaps try and minimize those changes as much as we can.
