### ISSUE TITLE
Create macros for Protocol components

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6107]
Now that we have numerous pages on mozorg built using Protocol, we should start to think about making components built using Jinja more reusable, so updating markup due to change upstream doesn't become difficult and time consuming. We should make a new set of Jinja macros for Protcol components, which can be imported as needed by individual page templates

Looking at these three pages:

https://www.mozilla.org/en-US/
https://www.mozilla.org/en-US/about/
https://www.mozilla.org/en-US/firefox/pocket/

I can see Cards, Billboards, Feature Cards, and Hero sections, but they all have separate implementations for the markup, so when making updates we'd need to address each page separately. It could be much easier and faster just to update the markup in a single macro, which each page then pulls from.

We should try and move these pages to use shared components sooner rather than later, else the job will get bigger as time goes on and more pages are built.

**Comment by cvidal2** [comment]
simple
