### ISSUE TITLE
Ad blocker page for SEO

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6116]
Success Criteria
- [ ] page is launched using Protocol components
- [ ] page is built referencing [this Sketch file](https://share.goabstract.com/1b0f078e-1f06-4a56-b248-92e7a9bc5702) and [this copy doc](https://docs.google.com/document/d/1H-b0B87jIU3AFlh0ON9LeIiqZBcllxdcB-tnTu_q-Hw/edit#)
- [ ] page is reviewed/approved on demo by Winston B prior to merging

Tasks
- [ ] Developer - Review design file w. Sung
- [ ] Developer - code page on demo, inform PM when ready
- [ ] Design/Creative Review
- [ ] PM - manages stakeholder QA of coded page on demo (24 hour review cycle)
- [ ] Developer (other) - review PR when it is submitted

**Comment by ejregithub** [comment]
@rraue - can you please comment/recommend where (URL) this should live in the IA?

**Comment by rraue** [comment]
@ejregithub  /firefox/features/adblocker/

**Comment by dzingeek** [comment]
**Items we are suggesting to change/tweak to get this page using Protocol.** 

1. "Ad blocker is a web browser..." copy block will change to default protocol text size and color (not bold)
2. The current images won't work for the web. We suggest two options:
    - Crop image so it does not go to the edges (like a static image)
    - Or change illustration so the waves can extend to any screen size. 
3. Don't use italic on pull quote. We will switch to regular for two reasons.
    - Loading another font style slows down the page 
    - Italics can be hard to read unless they are bold or really large in size
4. Connected dots graphics. This is not something that is easily achieved and would have to be a one-off component. We suggest using numbers instead.
5. Shift laptop image down so it does not interfere w/text block above. 
6. Change bottom CTA background color from blue to white. Blue doesn' work our hover state of the blue button.

_See attached image for reference to changes/tweaks._
![ad blocker landing page 7-changes](https://user-images.githubusercontent.com/3740746/45644235-1075e500-ba72-11e8-8207-f578f61e4603.png)

**Comment by djst** [comment]
@dzingeek what is the next step here? Are you bringing those recommendations to the requesting team / Approver?

**Comment by ejregithub** [comment]
@amychurchwell @djst - I put this in front of Winston and he is good with all the suggestions.  We have a greenlight to get this out asap.

**Comment by amychurchwell** [comment]
@ejregithub There are several links in the design. Where do they link to?

**Comment by alexgibson** [comment]
Dependent on https://github.com/mozilla/bedrock/pull/6232

**Comment by ejregithub** [comment]
> @ejregithub There are several links in the design. Where do they link to?

@amychurchwell -  please check the [copy doc](https://docs.google.com/document/d/1H-b0B87jIU3AFlh0ON9LeIiqZBcllxdcB-tnTu_q-Hw/edit#) and let me know if you don't find what you need there

**Comment by dzingeek** [comment]
@amychurchwell a few design tweaks. 

**Yellow Highlight:**
- [ ] Since this is a Fx specific page the fonts should be open sans. Change all headlines/headers from zilla to open sans.

**Green Highlights:**
- [ ] Bold copy

**Red Markup:**
- [ ] Align titles to body copy (left) "A typical ad blocker" and "The Firefox ad blocker"
- [ ] Center align button with title "drive the conversation..."
- [ ] Download fx strip doesn't really stand out. Let's change that light grey for the strip area to a darker grey (hex ##d7d7db)
- [ ] Replace the image with a high-res version (I will work on getting you this now) 

![screenshot_2018-10-05 firefox adblocking feature](https://user-images.githubusercontent.com/3740746/46563057-3bef3100-c8b4-11e8-96f0-fd67011edd5c.png)

**Comment by dzingeek** [comment]
Laptop assets
[laptop images.zip](https://github.com/mozilla/bedrock/files/2452463/laptop.images.zip)

**Comment by dzingeek** [comment]
Looks good to me. Nice work @amychurchwell and thanks for making those tweaks so fast.
