### ISSUE TITLE
Add 'Download Firefox' CTA to Firefox Privacy Notice Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6121]
https://www.mozilla.org/en-US/privacy/firefox/ receives [a lot](https://docs.google.com/spreadsheets/d/1R8vY9eXltYh8r0PMtWPPrbVlAD7Lf9Qo1tyGzWQq-0g/edit#gid=2084128443) of traffic from other than the direct that can be attributed from Firefox product installs. The hypothesis from the NewUseraDAU indicates adding a Firefox downlaod CTA module in the page will increase downloads

Success Criteria
- [ ]

**Comment by stephaniehobson** [comment]
Traffic to that page is almost exclusively people already using Firefox. If I've got the analytics right only 100,000 non Firefox users visited that page last month.

**Comment by stephaniehobson** [comment]
(Compared to 16 million Firefox users)

**Comment by ejregithub** [comment]
Spoke with @hoosteeno and concluded this is not something to take on. Citing the nominal set of non-Fx users visiting the page and the fact that the download button is in the nav (the global nav was not always shown on this page, but is now)
