### ISSUE TITLE
Automate updates to homepage editorial (card) content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6124]
Opening this issue to track building automation to facilitate updates to the [homepage](https://www.mozilla.org/en-US/) editorial cards.

Rationale:

- Updating the cards monthly takes a lot of dev time and cross-team coordination.

Notes from meeting with @pmac, @djst and @ejregithub:

- Data could live in a separate GitHub repo in markdown format.
- Bedrock could pull in & parse markdown post-merge.
- Websites team could still code review pull requests initially, if required.
- Could possibly share common image processing tasks that we build for the leadership page in #6123.

Things to consider:

- Even though the editorial content is `en-US` only for now, we could expect l10n to become a requirement in the future for locales such as `de`.
- Need checks to ensure image and quality, size aspect ratio.

**Comment by alexgibson** [comment]
Some specs:

**Card order:**

- Card 1 (large)
- Card 2 (small)
- Card 3 (small)
- Card 4 (small)
- Card 5 (small)
- Card 6 (medium)
- Card 7 (medium)
- Card 8 (medium)
- Card 9 (medium)
- Card 10 (small)
- Card 11 (small)
- Card 12 (small)
- Card 13 (small)
- Card 14 (small)
- Card 15 (small)
- Card 16 (medium)
- Card 17 (medium)

Note: cards are interspersed with other static content, such as billboard components. The page would need a way to insert / reference cards by some unique identifier, based on number/size.

I think we would need to say the order above & size of cards does not change. This is the layout.

**All cards have the following properties:**

- Thumbnail image
  - One of three aspect ratios: 1:1, 3:2, 16:9
  - Large cards
    - 16:9 only
    - 1860px width high-res, 930px width low-res
  - Medium cards
    - 1200px width high-res, 600px width low-res
  - Small cards
    - 860px width high-res, 430px width low-res
- Tag e.g. "Firefox", "Privacy"
- Title
- Description
- Link
- Icon (either video or audio)
- YouTube video ID (if provided, clicking the home page card would open a modal and inject a youtube video)

**Comment by alexgibson** [comment]
@pmac @ejregithub just checking in here - is this something we need to regroup on in terms of planning work / timing? I think Eric mentioned the home page automation would be the most immediately useful thing to start work on, but I guess we need to try size this in terms of LOE and how long we think something like this may take to build.

**Comment by pmac** [comment]
I thought we'd decided that the leadership page would be the best starting place? It should be similar enough so that the work would translate well to the home page, while being less impactful should there be issues.

**Comment by alexgibson** [comment]
> We need to target rollout of the homepage automation solution in early Q1/2019

@ejregithub just checking in here as I'm probably somewhat out of the loop. We originally had this under our H2 deliverables for 2018. Have priorities shifted enough that we're pushing these automation tasks out to 2019?

**Comment by ejregithub** [comment]
@alexgibson - we need to confirm with @djst  but my sentiment is that this is indeed the case.  My take on it is that the current asks of us and the upcoming calendar blocks (holidays and All Hands) pushes this out to working on it post All Hands and delivering in Q1.

**Comment by djst** [comment]
I think it depends on the size of this work. I'd love to get some automation stuff done this year, but only if we still have time to deliver on the main marketing projects (FFFY, FxA benefits, LiveNation, etc). Do we have a clear idea of LOE here? And, reading pmac's comment above, is this where we start (vs Leadership page updates)?

**Comment by djst** [comment]
Spoke with @pmac on Slack, the aim is to get this one done this year and the other Leadership one next year. 

I should say here that the priority of doing this first is right: homepage is updated regularly/monthly, whereas leadership happen more intermittently. So I think we'll get more value out of doing this first.

Thanks @pmac!

**Comment by pmac** [comment]
Yup. Thanks David. I'm making it one of my H2 goals, so I hope to start on this soon.

**Comment by alexgibson** [comment]
Myself an @pmac met earlier today to discuss a plan for taking this forward ([notes here](https://docs.google.com/document/d/1Nguau44N5a2OlAJKj0eXqdg-YA0fRrKewzPHQHQuQCw/edit#)).

We settled on the following 2 phased approach:

**Phase 1** 

Create a new GitHub repo that will store the card metadata which bedrock will consume to populate the home page. Our team will start updating this repo as the default workflow for updating the homepage content. Doing this will help us iron out kinks and solve any kind of automation issues, so we can feel confident in the system before opening it up to other teams. The repo will use markdown as the chosen file format, and will also be structured in a way whereby we can support l10n in the future if needed. We hope to try get this phase done before the end of the year.

**Phase 2** 

Once everything is working nicely, we can begin to look at incorporating a lightweight CMS, such as [Netlify CMS](https://www.netlifycms.org/) (as one possible example) in order to help facilitate updating the cards for less technical folks. We can also incorporate things like image optimisation checks as part of this phase. This phase is where we'll likely need to involve people like MJ to get their input, and to also assist in training.

Does this sound ok, @djst @ejregithub ?

**Comment by pmac** [comment]
@alexgibson I've done a pass at data organization and an initial import of all of the homepage cards in the new repo for these things:

https://github.com/mozmeao/www-admin

Take a look at the files in there and let me know if you have thoughts. We should find some time to discuss again soon as well.

**Comment by pmac** [comment]
Hi @alexgibson ,

I've made some updates based on our last conversation about this.

1. I've updated the card generator script to extract the data directly out of the `home-en.html` template in bedrock. This should allow us to much more easily keep things up-to-date during development of this feature.
2. I added the `aspect_ratio`, `media_icon`, and `highres_image` data fields.

Let me know if you see anything else about the data file structure that needs tweaking before we move to the integration-into-bedrock phase. One last question I have is whether we decided to leave the description in the body or move it to a `desc` field in the front-matter data?

**Comment by pmac** [comment]
@alexgibson one thing I'm noticing (that I forgot) is that if you put any string through the markdown parser it comes out wrapped as a paragraph (`<p>my description</p>`). This may not be what we want here. Right?

**Comment by pmac** [comment]
I did move the description to the data instead of the markdown bit. Working well.

**Comment by pmac** [comment]
I have run into a question though. I'm guessing the `ga_title` field in the card macro is meant to always be english where the `title` can be translated. As I have it now we can't do that. Is that a feature we definitely need? I'm thinking it'd be better for the implementation anyway if every non-en-US card was really just an overlay over the en-US data so that you don't need to redefine data from the en-US card if you don't need it to change. And we could then have a `ga_title` field on the en-US card and it would carry through since we don't define it on the others. Thoughts?

**Comment by pmac** [comment]
Okay, nevermind. I've done the following:

* When requesting an `en-US` card you get the data, and if `ga_title` isn't defined in the data, it's set to be the same as `title`.
* When requesting any other locale, the `en-US` card is loaded, and the requested card's data is loaded over the `en-US` data.

So as long as the non-en-US card doesn't define `ga_title` it will be in English from the English card. The same goes for other values in the cards like `aspect_ratio` and `image` and whatnot. They can be overridden in non-en-US cards or not. LMK what you think.

**Comment by pmac** [comment]
Sounds good. I'm just putting down my thoughts here. Don't worry with it. We'll sync on Monday. Enjoy PTO!

**Comment by alexgibson** [comment]
@pmac how are you feeling about merging this now we're back? Is there anything else we need to wait on, other than some back-end review?

**Comment by pmac** [comment]
was just thinking about this. It does need a bit more review, and I need to rebase and fix up the homepage template with the changes, and maybe update the data in the admin repo with the current cards.
