### ISSUE TITLE
 2 /new variations for Opera visitors w. traffic cop 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6130]
Success Criteria:
- [ ] 2 /new variations live
- [ ] Traffic is configured to route traffic according to spec in the bug

[FINAL copy ](https://docs.google.com/document/d/1AvqbqZHiyKpTauaGClf0RzbXfcWBZGOjocwzbOAZxEc/edit)

**Comment by alexgibson** [comment]
Looks like this issue was missing a link to the details - I found the original bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1489266

**Comment by alexgibson** [comment]
This is now up on demo for approvals:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera&v=2

**Comment by ejregithub** [comment]
@alexgibson - I'm seeing the standard /new when attempting to view these pages. Was the demo site modified since?

**Comment by alexgibson** [comment]
> @alexgibson - I'm seeing the standard /new when attempting to view these pages. Was the demo site modified since?

Ah yes thanks - I'l re-deploy now 👍

**Comment by ejregithub** [comment]
@alexgibson - we've cleaned up copy per your comments and further review by Legal.  That clean and FINAL copy is [here](https://docs.google.com/document/d/1AvqbqZHiyKpTauaGClf0RzbXfcWBZGOjocwzbOAZxEc/edit)

**Comment by alexgibson** [comment]
@ejregithub - I've updated the best I can, but I noticed a grammar/spelling errors in the copy doc.

The browser comparison table in that doc also seems out of date compared to the existing LPs for chrome/edge/safari. I'm very confused about what is correct, as I've been told to work from [this doc](https://docs.google.com/spreadsheets/d/1PaJzDRJJFAmyDecefBbh9K2KupDEZxPUbkeXpBNXYiI/edit#gid=1512926430) (see 2nd tab). Can we make sure we have a single source of truth, please?

**Comment by djst** [comment]
> Note that based on the doc you link above, we're back to saying Opera doesn't have "security features", which seems like somehting legal would be very unlikely to approve.

Where do you see that in the copy doc? I'm guessing the doc was updated since then, but want to make sure I'm not missing anything.

**Comment by alexgibson** [comment]
Yeah the doc has been updated since then. Kirby has QA’d and approved all the copy.

**Comment by ejregithub** [comment]
Ship it!

**Comment by stephaniehobson** [comment]
Experiment enabled.
