### ISSUE TITLE
Localize the /firefox/features/accounts/ page 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6131]
Success Criteria:
- [ ] Strings are wrapped for localization
- [ ] Tagged for l10n

**Comment by alexgibson** [comment]
May depend on https://github.com/mozilla/bedrock/issues/6015

**Comment by ejregithub** [comment]
@amychurchwell - can you please pick up #6015 , then this card, when you're done with the /download/thanks/ and homepage work?

**Comment by alexgibson** [comment]
This page no longer exists, closing.
