### ISSUE TITLE
Feature pages - add download prompt after content

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6134]
For non-Firefox users:

- [ ] https://www.mozilla.org/en-US/firefox/features/
- [ ] https://www.mozilla.org/en-US/firefox/features/bookmarks/
- [ ] https://www.mozilla.org/en-US/firefox/features/sync/
- [ ] https://www.mozilla.org/en-US/firefox/features/send-tabs/
- [ ] https://www.mozilla.org/en-US/firefox/features/private-browsing/
- [ ] https://www.mozilla.org/en-US/firefox/features/password-manager/
- [ ] https://www.mozilla.org/en-US/firefox/features/fast/

**Comment by anshulahuja98** [comment]
From what I understood, we have to move the download button for firefox to the bottom after the content?

**Comment by anshulahuja98** [comment]
If this issue is approved, can you please assign it to me?

**Comment by stephaniehobson** [comment]
Hi @anshulahuja98 we do not have approval or design direction for this yet.

**Comment by anshulahuja98** [comment]
Okay

**Comment by alexgibson** [comment]
Closing as these pages are being redesigned today
