### ISSUE TITLE
Update Edge SEM page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6142]
Success Criteria:
- [ ] Page is updated with revised content as found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1PaJzDRJJFAmyDecefBbh9K2KupDEZxPUbkeXpBNXYiI/edit?usp=sharing)

Reference the new columns (comparisons) as done in #6141 - the layout is the same

**Comment by alexgibson** [comment]
Taking care of this in #6141, so closing as duplicate
