### ISSUE TITLE
Decommission FxA iframe

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6149]
Third party cookie blocking is preventing the FxA account iframe from showing the sign-in form.

All instances of the iframe should be replaced with the iframe-less form. Then we should remove the iframe and associated code from bedrock.

- [x] /bedrock/bedrock/firefox/templates/firefox/accounts/
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-a.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-b.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-c.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-d.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/index.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx60.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx61.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx62.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fxa.html

- [ ] remove iframe FxA code

**Comment by stephaniehobson** [comment]
The accounts team rolled out a fix on their side so this isn't urgent anymore. Still good to fix though.

**Comment by alexgibson** [comment]
Perhaps we can retire many of these pages as part of https://github.com/mozilla/bedrock/issues/6197

**Comment by alexgibson** [comment]
@hoosteeno there's a new [Firefox Accounts bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1538008) that has some level of urgency behind it, and may require us to expediate removing the iframe on the above pages.

Given the above, the easiest and fastest way to remove the iframe would be the following:

1. Remove all the effected old /whatsnew templates, and either allow them to fall back to the [default /whatsnew template](https://www.mozilla.org/en-US/firefox/whatsnew/) (send-to-device), or alternatively redirect them to /firefox/accounts/.
2. Remove the old /firstrun templates and redirect those users to either /firefox/new/ (where they will be told their browser is out-of-date), or to /firefox/accounts/.

The second option would be to:

1. Keep these old templates around,
2. Update each one to use the FxA email-first form. 

Given the urgency, and the level of effort to update old templates to use the new email-first form, I would probably advise the first option. Redirecting to /accounts/ may also help keep signups going using the new flow. This would also allow us to kill off more non-Protocol pages in the process.

/cc @shane-tomlinson @ejregithub

**Comment by alexgibson** [comment]
Current sign-in iframe numbers:

![image](https://user-images.githubusercontent.com/400117/55162228-443b7100-515f-11e9-9dac-7abe801148c4.png)

Earlier this month:

![image](https://user-images.githubusercontent.com/400117/55162240-4dc4d900-515f-11e9-96c2-173f8560ae64.png)

**Comment by alexgibson** [comment]
To quote @shane-tomlinson on Slack:

"yesterday BigQuery says 34397 folks visited with context=iframe. 5k difference to redash"

**Comment by hoosteeno** [comment]
@alexgibson, could we create a single fallback template identical to Whatsnew 66, and redirect all these old in-product urls there? We could add a version check at the top, but we could also skip it to get this out quickly. This would probably require us to duplicate lang files for that new template?

**Comment by alexgibson** [comment]
@hoosteeno anything is possible, but this may not be so simple as it depends somewhat on the locales that had whatsnew 66 translated. This content would also be frozen in time, so would need maintenance long term. /firstrun also needs to cover as many locales as possible (like /new).

**Comment by hoosteeno** [comment]
Ok, thanks. I think we should take the expedient route to mitigate the urgency. 

> Remove all the effected old /whatsnew templates, and redirect them to /firefox/accounts/.
> Remove the old /firstrun templates and redirect those users to /firefox/accounts/.

Let's send everyone to the accounts page. 
* This will hopefully avoid losing that trickle of new accounts we get from the firstrun page
* It includes navigation in case people want to find something else

**Comment by alexgibson** [comment]
I checked how many locales we have activated for each page:

- /firefox/66.0/whatsnew/ [42 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/whatsnew_66.lang)
- /firefox/accounts/ [48 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/accounts-2018.lang)

So for better coverage, /accounts/ probably wins.

**Comment by hoosteeno** [comment]
I've been thinking about this and am second guessing my earlier comment (https://github.com/mozilla/bedrock/issues/6149#issuecomment-477803259). While the accounts page seems like the best way to sustain the trickle of acquisition currently coming from firstrun, it's also not a page we treat like in-product-content, and we won't want to. It's going to change *a lot* going forward, which means its localization completion (and adequacy for this job) will vary. 

What about...
* For whatsnew, redirect impacted urls to something we should start treating as the [default fallback whatsnew template](https://www.mozilla.org/en-US/firefox/whatsnew/) (now). Make a plan to improve it later).
* For firstrun, redirect impacted urls to something we should start treating as the [the default fallback firstrun template](https://www.mozilla.org/en-US/firefox/firstrun/) (now). Remove the iframe. Add a link from "Sign in to your account" to /accounts. Make a plan to improve it (later).

Does that seem like way to triage the urgent issue and give ourselves a good way forward? What's missing?

**Comment by alexgibson** [comment]
@hoosteeno I think your logic makes sense, but I'm not clear on which templates you're proposing we keep as the new default /firestrun and /whatsnew? Adding a new string to /firstrun is also going to have l10n implications, which will block removal of the iframe.

**Comment by hoosteeno** [comment]
> @hoosteeno I think your logic makes sense, but I'm not clear on exactly which templates you're proposing we keep as the new default /firestrun and /whatsnew? 

The templates I link to above: 
* https://www.mozilla.org/en-US/firefox/whatsnew/
* https://www.mozilla.org/en-US/firefox/firstrun/

> Adding a new string to /firstrun is also going to have l10n implications

I'm not proposing adding a new string -- just a new link from an existing string. E.g. `<a href="new_link">Existing string</a>`, where the existing string in question is the words, "Sign into your account."

**Comment by alexgibson** [comment]
> I'm not proposing adding a new string -- just a new link from an existing string. E.g. <a href="new_link">Existing string</a>, where the existing string in question is the words, "Sign into your account."

The words "Sign into your account" are part of a paragraph, and cannot be altered via insertion of a link, without it breaking existing translations.

If we're choosing a new default /firstrun template, I'd be tempted to consider https://www.mozilla.org/en-US/firefox/57.0/firstrun/, which is more up-to-date in terms of design? It's worth noting that the link "Learn more about Firefox Accounts" here already points to the /firefox/accounts/ page. Perhaps we could repurpose that text in the form of a button, that's slightly more prominent? Just an idea.

**Comment by hoosteeno** [comment]
> If we're choosing a new default /firstrun template, I'd be tempted to consider https://www.mozilla.org/en-US/firefox/57.0/firstrun/, which is more up-to-date in terms of design? It's worth noting that the link "Learn more about Firefox Accounts" here already points to the /firefox/accounts/ page. Perhaps we could repurpose that text in the form of a button, that's slightly more prominent? 

Great, I support this plan. Let's use this content/template as the fallback. Can it live at the fallback URL firefox/firstrun, or does it have to live at firefox/57.0/firstrun?

**Comment by alexgibson** [comment]
> Can it live at the fallback URL firefox/firstrun, or does it have to live at firefox/57.0/firstrun?

It can live in both places 👍

**Comment by alexgibson** [comment]
Ok, gonna see if I can knock this one out.
