### ISSUE TITLE
l10n image helper is broken when running bedrock locally

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6152]
I don't see the same issue when looking at pages in production, but the following code always returns the en-US image for me when running locally (after viewing the page using another locale):

```html
<img src="{{ l10n_img('firefox/ios/btn-app-store.svg') }}">
```

I have tested both using docker and running bedrock locally.

**Comment by jpetto** [comment]
Looked at this for a few minutes. Noting findings here for when I/someone has more time.

Looks like `STATICFILES_DIRS` (in `settings/base.py`) may just need an alternate path when `DEBUG = True`?

```
STATICFILES_DIRS = (
    path('media') if DEBUG else path('static_final'),
)
```

A quick test shows the above works locally, but should test on dev/demo to be sure there are no regressions.

**Comment by pmac** [comment]
I've not looked, but what Jon said definitely looks like a plausible solution. It's almost certainly something like that.
