### ISSUE TITLE
[9/25] - URL for legal terms for Firefox Monitor

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6153]
Firefox Monitor service will launch on September 25th and they need a URL to host the legal terms.

This card will:

- Document the final URL of the Firefox Monitor privacy notice
- Track the creation of that URL in association with the pull request submitted for the content in the legal-repo

**Comment by djst** [comment]
What is the status here? Due date is today!

**Comment by alexgibson** [comment]
CLosing as a duplicate of https://github.com/mozilla/bedrock/issues/6205
