### ISSUE TITLE
Test  /firefox/features/ -  impact bounce rate

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6155]
https://mana.mozilla.org/wiki/display/EN/Features+page+header+test

Description:  see if we can impact the 95% bounce rate for Linux users to test our hypothesis that no real users see the page. It would also be interesting to see if we can impact the 78% bounce rate for non-Linux users.

**Comment by stephaniehobson** [comment]
This experiment never got activated and talking to Justin we have decided not to run it.
