### ISSUE TITLE
WNP 63 - Content DUE 09/18/18

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6159]
Final approved copy **DUE 09/18/18** to have time for L10N

**Comment by alexgibson** [comment]
Is this copy dock linked about final? There are still some outstanding comments it seems. This task should be closed as 'done' when copy is locked.

**Comment by ejregithub** [comment]
@alexgibson - content is now final, Natalie has noted this in t[he copy doc](https://docs.google.com/document/d/1JjucIsw3I1G8tRAiNg6OE1kusGyeswoI8VMkSaZoslQ/edit?ts=5ba18161).
