### ISSUE TITLE
WNP 63 - Analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6160]
Provide spec for analytics requirements for 63 WNP:

- Detail `dataLayer.push()` requirements for page states (if required)
- Custom data attributes on CTA's (if required).

**Comment by alexgibson** [comment]
@ejregithub this is now ready for analytics requirements.

See [here](https://github.com/mozilla/bedrock/issues/6161#issuecomment-425431685) for demo link and testing instructions.

**Comment by ejregithub** [comment]
@alexgibson - when, by what date, do you need the spec from AP?

**Comment by alexgibson** [comment]
@ejregithub my aim is to get this finished and in production before we're all in Portland, else we'll have a big rush to get this finished off on my return. I'd say we need specs early to mid next week?

**Comment by alexgibson** [comment]
Spec from AP: https://docs.google.com/presentation/d/152A8lyqFjKKq63B4BZfBbiHfb4Eyf7QJVxyk0VJKIQQ/edit?ts=5bcf8bc4#slide=id.g4314b67b70_5_5

**Comment by alexgibson** [comment]
Reopening just until the page has been QA'd according to the spec.

**Comment by alexgibson** [comment]
QA has been completed and signed off by AP (via Slack)
