### ISSUE TITLE
WNP 63 - Dev

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6161]
**Resources**
[approved flow diagram](https://github.com/mozilla/bedrock/issues/6157#issuecomment-420459794)

**Todos**
_please add things here that need to be done_
- [x] final strings coded in template and pushed to demo for l10n
- [x] internal review
- [ ] stakeholder review
- [ ] analytics
- [x] unit / functional tests
- [ ] code review

**Comment by alexgibson** [comment]
This is now waiting on #6158

**Comment by dzingeek** [comment]
@alexgibson Design has been approved. 
See [here](https://github.com/mozilla/bedrock/issues/6158#issuecomment-424862184) for final file, assets, and some documentation.

**Comment by alexgibson** [comment]
@dzingeek this is now up on demo for both stakeholder & design review:

https://www-demo2.allizom.org/en-US/firefox/63.0/whatsnew/

Testing notes:

To see the FxA form and enable the link to `about:preferences#privacy`, you need to whitelist the demo server for UITour:

1. Open `about:config`.
2. Create a new preference called `browser.uitour.testingOrigins` and give it a value of `https://www-demo2.allizom.org/`
3. Make sure you are signed out of Sync.

**Comment by dzingeek** [comment]
@alexgibson looks good just one thing. Is it possible to shift the illustration and copy on the "better blocking" section for smaller screens (see screenshot for reference)?

Also totally get it if it's not, as this 'page' is not something someone will see on mobile so you can tell me no or that it will take too much effort.

![screen shot 2018-10-02 at 8 47 33 am](https://user-images.githubusercontent.com/3740746/46360411-37aae580-c620-11e8-888f-c5bcad49ade2.png)

**Comment by alexgibson** [comment]
> @alexgibson looks good just one thing. Is it possible to shift the illustration and copy on the "better blocking" section for smaller screens (see screenshot for reference)?

This should be fine to do, thanks 👍

**Comment by alexgibson** [comment]
> @alexgibson looks good just one thing. Is it possible to shift the illustration and copy on the "better blocking" section for smaller screens (see screenshot for reference)?

Actually, on second thought, I think I'm going to say a polite "no" to this. This is just another page-specific deviation from a standard protocol component. If this page had mobile traffic, I'd be tempted just to do it. But seeing as this is only shown to desktop users, I don't think adding more custom code here is going to really benefit.

**Comment by alexgibson** [comment]
@ejregithub ok this is now ready for stakeholder review. We're still waiting on analytics too.

Demo instructions are here: https://github.com/mozilla/bedrock/issues/6161#issuecomment-425431685
