### ISSUE TITLE
Open section on privacy page if linked to with a fragment identifier

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/bedrock#6164]
We've been asked by legal to change our privacy link to point to https://www.mozilla.org/privacy/firefox/#addons

However, the concern we have is that users clicking that link would need to click the header to see the relevant information. 

If the correct fragment id was used could the header be expanded by default?

**Comment by ejregithub** [comment]
@muffinresearch - We'll pull this into our queue. Current Lead Time is approx 22 days

**Comment by craigcook** [comment]
This is doable but aren't we also discussing redesigning the policy pages and doing away with the collapsing sections? I'm not sure if/when that might happen but it would make this issue moot.

**Comment by willdurand** [comment]
@ejregithub would you have an update to share by chance?

**Comment by alexgibson** [comment]
We removed the accordion from the privacy policies as part of https://github.com/mozilla/bedrock/issues/6198, so I think this can be closed.
