### ISSUE TITLE
Data request  - Lead Time and Cycle time for bedrock issues

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6167]
#1 (must have, asap) - Lead Time - lead time being defined as the number of business days from when an Issue is created in github to the time the issue is Closed. We need those data and, at least, the Title, Labels and Projects associated with each issue so I can create reports. .csv  output would be fine.

#2 (must have, eventually - by mid October would be nice) - Cycle Time - the time from when the work on an issue actually starts to when it (the issue) is closed. We should talk about this in reference to  the current column configuration we have in our project tracking board/project boards so I can understand what data is available. For us, the ask would be to have data reporting how many business days occur from when an issue is moved from the Ready (column) to being Closed in our Project Tracking board.

**Comment by ejregithub** [comment]
@jgmize - following up on the discussion we're having in email (I figure filing an issue was an eventuality/probably the better place to discuss).

The moz.org team has a KR to reduce our Lead Time. Since we've moved into using github projects for our Kanban board we've lost that ability - but I was assured when doing so that we could either pull that data ourselves or use one of many other offerings. So, I'm following up on the former to put in the request for scripts/queries to retrieve those data.

**Comment by jgmize** [comment]
@ejregithub please take a look at the data on https://analytics.mozilla.community/app/kibana#/dashboard/GitHub-Issues-Timing and let me know if that is sufficient for your "Lead Time" needs. Note the ability to filter by project at the top of the page; here's a [direct link filtered to bedrock](https://analytics.mozilla.community/app/kibana#/dashboard/GitHub-Issues-Timing?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:github_issues_main_metrics_timing,panelIndex:1,row:1,size_x:6,size_y:1,title:Summary,type:visualization),(col:4,id:github_issues_repositories,panelIndex:2,row:6,size_x:6,size_y:5,title:Repositories,type:visualization),(col:7,id:github_issues_status,panelIndex:3,row:1,size_x:3,size_y:4,title:Status,type:visualization),(col:10,id:github_issues_submitter_organizations,panelIndex:4,row:1,size_x:3,size_y:4,title:'Issues%20by%20Organization',type:visualization),(col:1,id:github_issues_last_issues,panelIndex:5,row:11,size_x:9,size_y:5,title:'Last%20Issues',type:visualization),(col:1,id:github_issues_submitters,panelIndex:6,row:6,size_x:3,size_y:5,title:'Issues%20Submitters',type:visualization),(col:1,id:github_issues_oldest_issues,panelIndex:7,row:16,size_x:9,size_y:5,title:'The%20Oldest%20Issues',type:visualization),(col:1,id:github_issues_median_open_time,panelIndex:8,row:2,size_x:3,size_y:2,title:'Median%20Open%20Time%20(days)',type:visualization),(col:4,id:github_issues_80_percent_open_time,panelIndex:9,row:2,size_x:3,size_y:2,title:'80%20Percent%20Open%20Time%20(days)',type:visualization),(col:1,id:github_issues_evolutionary,panelIndex:10,row:4,size_x:3,size_y:2,title:Issues,type:visualization),(col:4,id:github_issues_evolutionary_submitters,panelIndex:11,row:4,size_x:3,size_y:2,title:Submitters,type:visualization),(col:10,id:'3317bb70-6e28-11e7-a3d7-593a556c81b1',panelIndex:12,row:5,size_x:3,size_y:6,title:Organizations,type:visualization),(col:10,id:'8527a530-6e26-11e7-a3d7-593a556c81b1',panelIndex:13,row:11,size_x:3,size_y:6,title:Projects,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:bedrock)),title:'GitHub%20Issues%20Timing',uiState:(P-1:(title:Summary),P-10:(title:Issues),P-11:(title:Submitters,vis:(legendOpen:!f)),P-12:(title:Organizations,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-13:(title:Projects,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-2:(title:Repositories,vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-3:(title:Status),P-4:(title:'Issues%20by%20Organization'),P-5:(title:'Last%20Issues',vis:(params:(sort:(columnIndex:1,direction:asc)))),P-6:(title:'Issues%20Submitters',vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-7:(title:'The%20Oldest%20Issues',vis:(params:(sort:(columnIndex:!n,direction:!n)))),P-8:(title:'Median%20Open%20Time%20(days)',vis:(legendOpen:!f)),P-9:(title:'80%20Percent%20Open%20Time%20(days)')))). As for the "Cycle Time", I believe that's going to require some custom scripting against the github [projects API](https://developer.github.com/v3/projects/) based on your description of what you want.

**Comment by ejregithub** [comment]
@jgmize - thanks for the response and links.

At first glance the reporting is interesting but a little over-manipulated for my needs.

If I can obtain raw data on a 'per issue' level in bedrock that is then informed, for each, with issue opened date, issue closed date, Submitter, etc I can then separate all the issues the moz.org team members have worked on and better manipulate the data to weed out weekends when calculating Lead Time (actual working days only).

I thought 'Oldest Issues' might be sufficient, but it doesn't allow me to back past 50 issues.

A .csv with the following info for (all, for now) bedrock issues would be ideal

                                    URL |  ID | Submitter  |  Created on |  Closed on
Issue Description

Let me know if a chat would help/if you need anymore info, please.

Thanks!

**Comment by ejregithub** [comment]
@jgmize - thanks for the response and links.

At first glance the reporting is interesting but a little over-manipulated for my needs.

If I can obtain raw data on a 'per issue' level in bedrock that is then informed, for each, with issue opened date, issue closed date, Submitter, etc I can then separate all the issues the moz.org team members have worked on and better manipulate the data to weed out weekends when calculating Lead Time (actual working days only).

I thought 'Oldest Issues' might be sufficient, but it doesn't allow me to back past 50 issues.

A .csv with the following info for (all, for now) bedrock issues would be ideal

                                    URL |  ID | Submitter  |  Created on |  Closed on
Issue Description

Let me know if a chat would help/if you need anymore info, please.

Thanks!

**Comment by ejregithub** [comment]
@jgmize - based on discussion w. Ben i need to revise the request to be one of fully automated delivery, with Lead Time fully calculated, as previously specified, in the reporting document but with weekend days removed from the duration of the Lead Time per issue. Let me know if you questions, please.  We should meet to discuss.

**Comment by jgmize** [comment]
@ejregithub - I sent you a calendar invite for the first day that works with both our schedules.

**Comment by ejregithub** [comment]
@jgmize - Per our meeting:
- Create script and automate delivery of Lead Time data on a monthly basis
- Deliver functionality by 10/31

**Comment by jgmize** [comment]
https://gist.github.com/patrickfuller/e2ea8a94badc5b6967ef3ca0a9452a43 looks like a decent start

**Comment by jgmize** [comment]
@ejregithub I've created a csv based on your request from https://github.com/mozilla/bedrock/issues/6167#issuecomment-421363018 to give you something to look at https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5#file-mozilla-bedrock-issues-csv

### Notes

- When you asked for "ID", I assumed that you didn't mean the ID returned by the github API but rather the issue number (for example, bedrock issue #1 has a github API id of 889629)
  - Is this correct? 
- the numbers are not sequential because I've [filtered out pull requests](https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5#file-github_issues-py-L53)

### Next steps
- [ ] add a "net work days" column using https://pypi.org/project/workdays/
  - please let me know if we should exclude any holidays in addition to weekends
- [ ] monthly averages based on net work days (separate csv)
- [ ] automated updates
  - [ ] decide where to upload resulting files
  - will require stored credentials

**Comment by ejregithub** [comment]
@jgmize - sorry for the delay in review/reply (training then straight into PTO).  This is looking good!  A few comments/requests:

- re: Holidays - no worries about these, I did not remove them in the previous lead time calculations and need to maintain that same method for measurement.
- With the URL including the ID number, the ID column is moot - I should have realized this sooner.
- I'd like to ask if we could add a filter based on 'is closed', as in: do not include any open issues in the report. If an issue is not closed we can't determine lead time so inclusion of those issues is also moot.

**Comment by jgmize** [comment]
I've updated the script to omit the ID column and filter for closed issues, and a new csv can be downloaded from the updated gist I linked earlier: https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5/raw/c950f1ec4ee292e9777a46a23d46a8aa6f86ab5d/mozilla-bedrock-issues.csv

**Comment by ejregithub** [comment]
@jgmize - could ask for another optimization to pull data only for issues created by the following users:
ejregithub 
alexgibson 
dzingeek
amychurchwell 
craigcook 
stephaniehobson 
amychurchwell 
clay-chaffin 
mrkwvr 
michaelmccombie 
vincejoyiv 
djst 
bensternthal 

Also, we are modifying our tracking board to be at the org level so we may include not just bedrock issues but also the following repos (for now):
https://github.com/mozilla/irlpodcast
https://github.com/mozmeao/lumbergh

Could you please add issues to the report, restricted to that set of users identified above (though only devs + Ben have perms to these other repos), for these two other repos, as well?  

Ping me with questions, I'm happy to jump on Vidyo to clarify anything!

**Comment by ejregithub** [comment]
From our meeting: 
- Notebook solution sounds good.
- Agreed on not limiting reporting to specific individuals

**Comment by jgmize** [comment]
Per our discussion on slack packaging as a jupyter notebook is unnecessary, only updated data for the 3 repositories requested. I've pushed the results of the following command as an update to [the gist](https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5):
```bash
$ ./github_issues.py mozilla/bedrock mozilla/irlpodcast mozmeao/lumbergh --auth
```
- [mozilla-bedrock-issues.csv](https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5/raw/1b5f4b0449facda4db7ce5aaef16ab3c854e3271/mozilla-bedrock-issues.csv)
- [mozilla-irlpodcast-issues.csv](https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5/raw/1b5f4b0449facda4db7ce5aaef16ab3c854e3271/mozilla-irlpodcast-issues.csv)
- [mozmeao/lumbergh](https://gist.github.com/jgmize/ff97ff509bb7c2efb38c44b07c969fe5/raw/1b5f4b0449facda4db7ce5aaef16ab3c854e3271/mozmeao-lumbergh-issues.csv)

@ejregithub let me know if you need any further updates, otherwise I'll consider this resolved.
