### ISSUE TITLE
"What is a browser page" for SEO

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6171]
This page uses the template establish in the SEO 'Ad blocker' page that @amychurchwell coded.

[The brief](https://docs.google.com/document/d/19msv-D3WdYS2k9ymxW2kRX6aM7obEk8qOZWUgqnC8KE/edit?ts=5b9bd8d8)

Success Criteria
- [ ] page is launched using Protocol components
- [ ] page is built referencing [this Sketch file]()
- [ ] page is reviewed/approved on demo by Winston B prior to merging

Tasks
- [x] Developer - code page on demo, inform PM when ready
- [ ] Design Review (internal team)
- [ ] PM - manages stakeholder QA of coded page on demo (24 hour review cycle)
- [ ] Developer (other) - review PR when it is submitted

**Comment by dzingeek** [comment]
Blocking this card as the sketch file link goes nowhere and we can't find a "final" sketch file. Will reach out to someone on the new adau team to see if we can get some clarification.

**Comment by dzingeek** [comment]
@ejregithub After talking with Yuliya it looks like the design + copy is not done. This would probably be a great project for Clay and David (new designer on new adau). But since they are both new they would need some background and a new kickoff.

**Comment by dzingeek** [comment]
Here is the link to the brief and the copy doc. David Luhman from new aDau is working on the design. Ping him with any questions.

[Brief/Copy Doc](https://docs.google.com/document/d/19msv-D3WdYS2k9ymxW2kRX6aM7obEk8qOZWUgqnC8KE/edit?ts=5bc61cc5)

Also looks like there might be some open issues in the doc for @rraue

**Comment by craigcook** [comment]
On demo: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/what-is-a-browser/

Final URL TBD, and I've made some comments/suggestions in the copy doc that we should hammer out but it's nearly there.

**Comment by chelseanovak** [comment]
I accepted most of Craig's suggestions in the copy doc and corrected some errant capitalizations. Once those changes are reflected on the page I can QA again.

**Comment by ejregithub** [comment]
@craigcook - The url will be /technology/what-is-a-browser/

**Comment by chelseanovak** [comment]
Reviewed and signed off by me!

**Comment by craigcook** [comment]
Live in production: https://www.mozilla.org/en-US/technology/what-is-a-browser/
