### ISSUE TITLE
Identify 10 S mode users

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6172]
Description: Research means to identify 10 S mode users from the mozilla.org website.

Reasoning:  

- Windows 10 in S mode prevents users from installing Firefox
- If successful we could then put this flag in a data attribute that GA would pick to then understand the set of users attempting to download Firefox
- Could provide users with messaging about 'S' mode, including instructions how to disable S mode that would enable them to install Firefox

**Comment by alexgibson** [comment]
This is a duplicate of https://github.com/mozilla/bedrock/issues/6367
