### ISSUE TITLE
Update bedrock to use Protocol navigation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6174]
Now that Protocol has the new [Navigation](https://protocol.mozilla.org/patterns/organisms/navigation.html), we can finally use it in bedrock 🎉 

The plan is to:

1. Roll out the new component across all English locales.
2. Put the new component behind a switch, toggling back to the current navigation.
3. When launched, carefully monitor click through's (Analytics requirements TBD)
4.  Only roll back to the old navigation if there is a problem.

**Comment by alexgibson** [comment]
Final copy doc: https://docs.google.com/document/d/1g0N8oy0WSOY218LJjDIslBbVOmNaBY4Agnfo-cvp6wA/edit?usp=sharing

**Comment by alexgibson** [comment]
WIP demo: https://bedrock-demo-navigation.oregon-b.moz.works/en-US/

**Comment by alexgibson** [comment]
@dzingeek can you please QA the navigation content and link above? I've tried to do this the best I can based on edits in the copy doc, but a second pair of eyes would be appreciated.

**Comment by alexgibson** [comment]
@dzingeek we may also want to think about any updates to the existing sub navigation on pages like this: https://bedrock-demo-navigation.oregon-b.moz.works/en-US/firefox/

I'm not sure I quite understand why we still need a sub nav on these pages, given the expandable panels in the new navigation. But maybe I'm not thinking through some scenarios. Thoughts?

**Comment by dzingeek** [comment]
We will need to figure out a sub nav. Some pages will have subsections that will not live in the main nav. @vincejoyiv was going to start to look into the sub nav.

**Comment by dzingeek** [comment]
@alexgibson looks good to me. Nice work!

**Comment by dzingeek** [comment]
@alexgibson do we have to solve the sub nav before pushing out the new nav? In other words, is this a blocker?

**Comment by alexgibson** [comment]
> @alexgibson do we have to solve the sub nav before pushing out the new nav? In other words, is this a blocker?

I'd rather it not be a blocker if at all possible. If we can remove some of the existing sub navs though, I'd be happy to do that as part of this change.

**Comment by ejregithub** [comment]
@alexgibson - here's [the spec](https://docs.google.com/presentation/d/1EwL65T779SyTHQ5s4BPACS3fbid5Md_QTQ2lQ829f48/edit#slide=id.g223bb6efd2_0_44) from AP

**Comment by alexgibson** [comment]
Demo is now updated as per the spec from AP, now pending verification.

**Comment by alexgibson** [comment]
Depends on #6232
