### ISSUE TITLE
[10/5] Developers for Firefox - /new variation landing page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6178]
Description: create a /new variation landing page to support the  ['Developers for Firefox' program](https://docs.google.com/document/d/1t6YWu8rvUOgzahv9uZPM_N6fxnrGWhF0m7Phedo_hKc/edit). In this mktg program, developers are encouraged to promote use of Firefox, posting images with a URL (link with UTM parameters to enable anonymous tracking). Users clicking the link are taken to this  landing page with copy inline with their 'referral journey'

Success Criteria: 
- [ ] We track the number of installs / aDAU in aggregate for the whole campaign with the single referral URL (Traffic to landing page attributed using source tags)
- [ ] aDAU attributed to traffic in Telemetry
- [ ] URL:  /firefox/this-browser-comes-highly-recommended
- [ ] Set to noindex (not be indexed by search engines)

[Copy doc](https://docs.google.com/document/d/1dR93_giMMpa77SVkanE9x-kkTTMpE1kmtXXejtdYs5I/edit)

**Comment by ejregithub** [comment]
Currently blocked on copy which is pending Legal approval. Coding can proceed with the current copy as placeholder.

**Comment by alexgibson** [comment]
Mockup https://docs.google.com/presentation/d/1DJcJlKNNyS9EOyIr-smSQMU8SvxoufLiG_14UX8XN94/edit#slide=id.g3f27b046e3_0_0

**Comment by alexgibson** [comment]
@ejregithub page is up on demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/this-browser-comes-highly-recommended/

**Comment by ejregithub** [comment]
@hoosteeno - please record the UTM params that will be used for this campaign here.

**Comment by alexgibson** [comment]
Updated as per final copy & design: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/this-browser-comes-highly-recommended/

We're going to aim to get this reviewed and shipped tomorrow (Friday)

**Comment by hoosteeno** [comment]
> @hoosteeno - please record the UTM params that will be used for this campaign here.

Let's use this: 

`https://www.mozilla.org/en-US/firefox/this-browser-comes-highly-recommended/?utm_campaign=devs-for-firefox&utm_content=[button-specific]&utm_medium=referral&utm_source=devs.for.firefox.com`

That URL implies that each badge will get its own utm_content parameter (e.g. `utm_content=fox-in-sunglasses`). That might be interesting/helpful data. If it is too much scope creep, then use a generic utm_content parameter: `utm_content=dff-badge`

---

Will `devs.for.firefox.com` pass the whitelist test? 

Yes. Here's the whitelist:
https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/sourcewhitelist.go#L26

Here's a regex proof: https://www.regexpal.com/?fam=105264
