### ISSUE TITLE
New legal docs: Firefox Reality Privacy Notice and About Rights 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#6179]
The following two docs need to be pushed to production by Sept 18.
- About Rights: https://github.com/mozilla/legal-docs/blob/master/firefox_reality_about_rights/en-US.md
- Privacy Notice: https://github.com/mozilla/legal-docs/blob/master/firefox_reality_privacy_notice/en-US.md

**Comment by pmac** [comment]
This is [bug 1491425](https://bugzilla.mozilla.org/show_bug.cgi?id=1491425)
