### ISSUE TITLE
Update copy on /firefox/accounts page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6180]
We should re-use the same copy from the current /whatsnew page:

[HEADLINE] 
Firefox Account: Simplify your online life.

[BODY]
- Send pages instantly between your devices
- Sync bookmarks, history and more
- View content offline and anytime with Pocket

Find out more (link to /firefox/accounts/features)

**Comment by stephaniehobson** [comment]
I'm going to close this since we have redesigned the page since it was opened.
