### ISSUE TITLE
Broken link in cmommunity page

### ISSUE THREAD

**Issue by ChillarAnand** [mozilla/bedrock#6181]
http://www.mozillaindia.org/ link is broken and it is referenced in https://www.mozilla.org/en-US/contact/communities/india/

**Comment by pmac** [comment]
Thanks for the report! Looks like https://mozillaindia.org/ is working, but the `www` subdomain isn't. We can change the link on the site, but that should be fixed as well. I'm checking in #india on IRC to find who might have access to fix it.
