### ISSUE TITLE
Videos loading from videos.cdn.mozilla.net are all broken

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6187]
STR:

1. Open: https://www.mozilla.org/mission/
2. Click the video thumbnail

Expected results:

The video should play

Actual results:

The video is broken, with the following error in the Firefox web console:

```
All candidate resources failed to load. Media load paused.
```

It looks like https://videos.cdn.mozilla.net/ is no more?

Looking through the repo, there are numerous pages using this server. I can only assume all are broken:

https://github.com/mozilla/bedrock/search?q=videos.cdn.mozilla.net&unscoped_q=videos.cdn.mozilla.net

**Comment by metadave** [comment]
if files can be restored from backup, we can host in our own S3/Cloudfront

**Comment by metadave** [comment]
the video now plays on this page: https://www.mozilla.org/en-US/mission/

**Comment by jgmize** [comment]
fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1489692#c19

**Comment by stephaniehobson** [comment]
So, are we hosting these ourselves now?

**Comment by metadave** [comment]
@stephaniehobson no, the current CDN has been fixed.

Shall I open a separate bug with the airmo team to recover missing viewsourceconf files?

**Comment by Pike** [comment]
The viewsource ones are airmo, right? Maybe that's partly the auth-required question that Mossop added for the internal call.

**Comment by stephaniehobson** [comment]
I'm talking to AirMo on Slack/email. I'll file a bug if someone on our team needs to do something.
