### ISSUE TITLE
CSP violation alerts from sentry

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#6191]
- https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/4719394/
  - source: https://www-dev.allizom.org/en-GB/firefox/download/thanks/
  - blocked-uri: https://adservice.google.de/
- https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/4712335/
  - source: https://www-dev.allizom.org/da/firefox/download/thanks/
  - blocked-uri: https://adservice.google.dk/
- https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/628815/
  - source: https://www-dev.allizom.org/en-CA/
  - blocked-uri: https://fonts.gstatic.com

**Comment by alexgibson** [comment]
> https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/628815/

I think we can ignore this one, there shouldn't be anything loading google fonts afaik.

I'll file a PR for the two violations on /download/thanks/ 👍
