### ISSUE TITLE
[FFYR #4] - Investigate possibility to do update for old whatsnew+firstrun pages (and rewrite in Protocol)

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6197]

**Comment by alexgibson** [comment]
In order to answer this we really need an idea of what type of content we will want to show users on these pages.

**Comment by hoosteeno** [comment]
In case helpful, I wrote a tool to do this on www content previously. It's not directly applicable, but with minor modifications could do the job, or at least show one way of doing the job. https://github.com/hoosteeno/archiver_toolkit
