### ISSUE TITLE
[9/25] FFYR - Update homepage banner

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6201]
This work supports the Fight for Your Rights campaign
 
Success Criteria:
- [ ] Banner live on 9/25

Tasks:
- [x] UI/design of Banner - Jennifer
- [x] Copy for Banner - Natalie/Tim
- [x] Team QA - Design
- [ ] Code Banner - TBD
- [ ] Team QA of Banner on demo 
- [ ] Stakeholder QA of Banner on demo

**Comment by dzingeek** [comment]
**Copy for Banner f/Tim M**
- logo lockup *Firefox* fights for you.
- headline "More power to you."
- subhead (assuming it fits) "Control your privacy. Get 2x the speed. Your rights are worth the fight."

**Comment by dzingeek** [comment]
[Sketch File Here](https://share.goabstract.com/7491c709-54f8-4dcc-8d8a-2d91bcc26cc7)
_Image is low res, waiting on high res version._

See screenshot for reference:
<img width="1264" alt="screen shot 2018-09-24 at 4 15 09 pm" src="https://user-images.githubusercontent.com/3740746/45985037-2444bc80-c019-11e8-8421-22c7698721d7.png">

**Comment by dzingeek** [comment]
One other thing to note, based on the new design we need to also update the bottom fx banner.

**Things to tweak**
- [ ] change background color to grey
- [ ] make text black
- [ ] use blue square button (matching new banner button)

**Comment by dzingeek** [comment]
@craigcook here is the [link to the high res png with a transparent background ](https://mozilla.box.com/s/dx49senhnrrjuigwncim1dz8ldozvca5). Let me know if you run into any issues.

**Comment by dzingeek** [comment]
@craigcook Looks like something is happening on some smaller screen sizes with the "skinny" verions. 
![screen shot 2018-09-25 at 11 56 54 am](https://user-images.githubusercontent.com/3740746/46036499-7689ea00-c0ba-11e8-8307-25a6392d4d12.png)
