### ISSUE TITLE
[9/25] - Update 'Evolving the Firefox Brand' card with Monitor content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6203]
Description: Swap out Card 1 (Evolving the Firefox Brand) for Firefox Monitor content on 9/24 (to drive people directly to the Monitor site)

**Comment by kellymj** [comment]
Headline: Protect yourself with Firefox Monitor

Blurb: Find out what hackers already know about you and get alerts when data breaches put you at risk.

URL: https://monitor.firefox.com/  (with UTM tags that your team adds)

**Comment by ejregithub** [comment]
![sp_fx_monitor_moz org homepage 01](https://user-images.githubusercontent.com/20547886/45849622-89ca3d80-bce7-11e8-9978-2df0ac936511.png)

**Comment by ejregithub** [comment]
@alexgibson - all assets are now here ^^

**Comment by alexgibson** [comment]
Enabled once again, closing.
