### ISSUE TITLE
Add download CTA to bottom of About page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6204]
## Description of the work:
The www.mozilla.org/about/ page could use a download CTA near the footer. After talking with the websites team, a similar one to what is found on https://www.mozilla.org/en-US/firefox/browsers/compare/ might be the best match.

## Success Criteria
- [ ] CTA has been added and is responsive
- [ ] Copy for the CTA has been added to the corresponding fluent [file](https://github.com/mozilla/bedrock/blob/main/l10n/en/mozorg/about.ftl)

**Comment by stephaniehobson** [comment]
Responding to [this question](https://github.com/mozilla/bedrock/issues/6110#issuecomment-474555149) here:

@amychurchwell This page is almost pure Protocol, you can use a compact call out for the download CTA.

**Comment by stephaniehobson** [comment]
Also, note that l10n has started so the CTA will need to be wrapped in l10n_has tags

**Comment by craigcook** [comment]
After a bit of discussion, it was pointed out that this page already includes a component calling out how using Firefox supports Mozilla and links to /new. The main nav also includes a download button (for those not using Firefox), and adding yet another CTA wouldn't really help anyone and in fact could dilute the rest of the page's value. If people want to download Firefox from the About page they have other ways to find it.

There's more we could do to improve this page, but adding another download button probably wouldn't.
