### ISSUE TITLE
Love it or leave it: FB Video Chat Funnelcake experiment.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6206]
This should be made permanent or removed depending on how successful it was:
https://bugzilla.mozilla.org/show_bug.cgi?id=1458340

**Comment by alexgibson** [comment]
@ejregithub given what we now know about funnelcakes and auto-updating, we should probably make a decision here as to whether we keep this around?

**Comment by alexgibson** [comment]
Closing this as a dupicate of #6749
