### ISSUE TITLE
/firefox/download/thanks redirects to /firefox/new/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6210]
I keep on hitting this because I bring up the URL so often in the awesomebar, but always forget to file it so here goes:

STR:

Visit: https://www.mozilla.org/firefox/download/thanks

Expected results

Should redirect to https://www.mozilla.org/firefox/download/thanks/

Actual results:

Redirects to https://www.mozilla.org/firefox/new/

**Comment by RCMainak** [comment]
I would like to work on this one.

I am debug this issue but having trouble since raven is complaining, need to find a way to enable logging.
