### ISSUE TITLE
IA - Figure out Foundation content/placement in new nav

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6225]
Following up on the discussion w/ Janis and MEM, we need an answer to how to link visitors to foundation.mozilla.org from mozilla.org. We should have an opinion about 

- what specific Foundation content we want to link to (e.g. just a jump-off to foundation.m.o. or links to specific content/stories on their website)
- whether the connections happen from the nav, from in-page content (e.g. homepage, About, etc), or a combination of both

Once we have an opinion, let's meet and discuss/align with Janis, primarily. 

Success metrics: 
- We have a proposed solution
- We have buy-in from Janis and MEM

**Comment by alexgibson** [comment]
The nav links directly to https://foundation.mozilla.org/
