### ISSUE TITLE
Events schema.org markup is invalid

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6238]
I got today warnings in the search console, that all our events on https://www.mozilla.org/contribute/events/ have invalid markup. Something is wrong with the location. 
<img width="1233" alt="screen shot 2018-09-27 at 12 27 07" src="https://user-images.githubusercontent.com/36700618/46140268-ec27be80-c250-11e8-921f-97c6435a9812.png">
But as I see in search that our events are displayed right and we will introduce a new page anyways, I think there is no priority to fix it right now, but we should do it right on the new page or if we do something on the old page anyways.
<img width="587" alt="screen shot 2018-09-27 at 12 29 21" src="https://user-images.githubusercontent.com/36700618/46140352-298c4c00-c251-11e8-919e-594fc9040e6c.png">

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/7382

**Comment by rraue** [comment]
And [test is passed](https://search.google.com/test/rich-results?id=SRrwOvvSF_0Ra2dKlL4PWA), the errors should disolve in search console.
<img width="1896" alt="Screenshot 2019-07-10 at 17 25 40" src="https://user-images.githubusercontent.com/36700618/60982144-dc88ea80-a337-11e9-9ace-82527be229af.png">
