### ISSUE TITLE
Experiment: Copy Variations on /New

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6254]
**Hypothesis:** Our current heading “The New Firefox - Fast for Good” isn’t saying anything about what Firefox is or why someone should try it. The assumption here is that we can increase performance by trying a few other options. The New aDAU team’s experiments on SEM optimized pages certainly supports the idea that copy can make a huge difference in download rate. Let’s set up a similar experiment on the organic traffic segment on the evergreen version of /new.

**Goal:** To increase Fx downloads

**Effort:** Small
- Copy variations for header
- Analytics input
     - What are we tracking
     - What % of users do we need to see this page in order so say it was a success or not
- Dev time for both setup and implementation 

Impact: +5% downloads. 
The IE SEM campaign was able to find a headline that converted 5% better than the control.

**Comment by hoosteeno** [comment]
We have an [experiment in the backlog ](https://airtable.com/tbl2BcU9Qoo8rh5hI/viwj9Jp4P8bNo4g1R/recGPDzgmGQGErEnD?blocks=hide)with lots of details that will accomplish this. Closing this one as we open that one.
