### ISSUE TITLE
Research: Learn Why users who have Fx land on /New

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6257]
In order to run the right experiments on /New for we need to better understand why users using Fx come to this page.

- Were they brought here by an ad?
- Did they type in firefox.com?
- Are they having issues with the browser and think downloading it again will fix it?
- Do they know the difference between refresh and download?
- Are they just interested in learning what’s new?

_1.5 million people came through firefox.com in August. That is a lot of potential impact.
Previous surveys suggest people with Firefox are there for lots of different reasons._

**Comment by djst** [comment]
Where are we with this research and what are the next steps, @dzingeek ?

**Comment by ejregithub** [comment]
@dzingeek -I'm going to tag this to go into the [Websites Team backlog](https://github.com/orgs/mozilla/projects/46) as it appears to not be in progress.  When you're ready to resume, tag it with the Label 'in sprint' and the Project '[Websites Durable Team Project Sprint Board](https://github.com/orgs/mozilla/projects/45)' to pull into an upcoming sprint.

**Comment by dzingeek** [comment]
Data is now in the doc. It still needs some more evaluation but I think it's at a point where we can look at it as a team and come up with some suggestions for future experiments. 

https://docs.google.com/document/d/11FfNSYUXOkDqBEgubOdtEDIH9y6nBJe6FMc-p5-Q8vY/edit?usp=sharing

**Comment by hoosteeno** [comment]
If there are follow-up bugs to file here, let's file them. This seems done!
