### ISSUE TITLE
Experiment: Add navigation to /download/thanks/

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6261]
**Hypothesis:** What is valid for /firefox/new/ is even more eminent for /download/thanks/. Users have a bounce rate of more than 70% because we are not offering much besides the main ctr, which is right now newsletter and performing poor (1% ctr). By giving them other options (nav) this could potentially increase other goals (engagement, nav clicks, newsletter, mobile downloads, social share). 

**Effort:** Small
Dev time for both setup and implementation 

**Impact:** Unknown

**Comment by alexgibson** [comment]
Nav now exists on this page
