### ISSUE TITLE
Experiment: Download Button Shape

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6262]
**Hypothesis:** A button design that looks more 3 dimensional will communicate the click affordance better to users and they will be more likely to click it.

**Effort:** Small
- Design Time
- Analytics input
- Dev time for both setup and implementation 

**Impact:** Unknown

**Comment by amychurchwell** [comment]
I'm going to close this in favor of https://github.com/mozilla/bedrock/issues/7841
We can address this in design review of that variant.
