### ISSUE TITLE
Experiment: Add Navigation to Firefox/New/

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6265]
**Hypothesis:** We have a very good ctr of 66% on /firefox/new/ but that leaves still more than 30% of users undecided and most of them directly bounce (26%). By giving users access to more information (nav) this should reduce the bounce rate without reducing downloads per session. This could increase downloads after users have a chance to inform themselves more on Fx.

**Effort:** Small
- Design Time
- Analytics input
- Dev time for both setup and implementation 

**Impact:** Unknown

**Comment by alexgibson** [comment]
Closing this as a duplicate of https://github.com/mozilla/bedrock/issues/8037
