### ISSUE TITLE
[On or B4 10/12] Update ScreenshotGo logo in Privacy Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6274]
Description: The ScreenshotGo privacy policy went live, the logo needs to be updated in that page

Page to update the logo - https://www.mozilla.org/en-US/privacy/firefox-screenshotgo/

[Assets](https://drive.google.com/drive/folders/1tHebCa2UyzTbWHmXOer7OyVjEUtBR2g9)

[Reference bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1487436)

**Comment by weslyhuang** [comment]
Hello, may I know is it feasible to update the logo by this week? Thanks.

**Comment by ooHAoo** [comment]
I would like to work on this if possible and if it's still open?
Please let me know. Thanks!

**Comment by weslyhuang** [comment]
guess we need @ejregithub to comment?

**Comment by ooHAoo** [comment]
> guess we need @ejregithub to comment?

Yup, I do not have access to the correct logo.

**Comment by ejregithub** [comment]
[Adaptive-Beta-20181012T223923Z-001.zip](https://github.com/mozilla/bedrock/files/2474760/Adaptive-Beta-20181012T223923Z-001.zip)

Apologies for the delay.  @ooHAoo - if you're able to submit a pull request by Monday the 15th, please do. One of our developers can review it then.

**Comment by weslyhuang** [comment]
thanks!
