### ISSUE TITLE
Lazy load billboard images on homepage

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6283]
We can get some performance gains buy deferring loading of the billboard images.

The audit tool I used estimated between 0.5s and 1.5s gains!

**Comment by Shivansh2407** [comment]
Can You explain more on this....Can I help you fix this issue

**Comment by joneskj55** [comment]
Hello @stephaniehobson & @hoosteeno is this still something that you would like done? I did something similar for `/firefox/privacy/book` in PR #10596 and would not mind looking into this if it is still up for grabs.

**Comment by alexgibson** [comment]
Closing in favor of https://github.com/mozilla/bedrock/issues/10669
