### ISSUE TITLE
[10/19] Kill "Powered by Mozilla" page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6287]
Description: Legal recently rediscovered the "Powered by Mozilla" page. It looks pretty defunct, and Michael F. reached out to Mike Hoye who confirmed it's defunct. The "form" on the page to ask permission for the badge no longer goes anywhere. The page needs to be removed.

- Developer Hours [  ]

Success Criteria:
- [ ] The page is removed from mozilla.org by the assigned date (10/18)

**Comment by ejregithub** [comment]
@amychurchwell - could you please this one up, letting me know how you would size it (in hours/days) for total dev time required including review/merge/push?

**Comment by amychurchwell** [comment]
@ejregithub - Work-wise, >1 hour --assuming I am correct in seeing that there are hardly any dependencies on this page. Review/merge/push depends on how busy everyone but possibly today.

**Comment by kyoshino** [comment]
Just FYI: The [linked form](https://bugzilla.mozilla.org/enter_bug.cgi?product=Marketing&format=poweredby) will also be removed from Bugzilla today or tomorrow. https://github.com/mozilla-bteam/bmo/pull/830

**Comment by amychurchwell** [comment]
@kyoshino Thanks Kohei! This should be reviewed/merged today.
