### ISSUE TITLE
[10/15 or so] Hide the download button in the top nav in the Election bundle landing page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6288]
Description:  The download button in the top nav is for the standard build, therefore competing with the main CTA and likely taking downloads away from the intended Election bundle version. We need to prevent this and hiding the button seems the least effort to do so.

Success Criteria:
- [ ] the download button in the upper right of the page is removed/hidden
- [ ] this should happen asap, the week of Oct 15th

**Comment by ejregithub** [comment]
@stephaniehobson - I flipped a 4 sided coin and you came up, but feel free to pass this off if needed.

**Comment by alexgibson** [comment]
This looks like a simple one to get out, picking this up.
