### ISSUE TITLE
[10/?] - Update the University page on careers.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6289]
Description: The University page on careers.mozilla.org needs to be updated to correspond to the intern hiring process that is starting Monday, Oct 15th.

[Copy doc](https://docs.google.com/document/d/1Hv57PnJwaHXm4-2YC8BHIa7BfJg6LUmMX14_l7eEhMo/edit)

Success Criteria:
- [x] The page is update with the new content (copy) by date xd

Tasks:

Risks:

**Comment by alexgibson** [comment]
For future ref: Issues for careers should be created here: https://github.com/mozmeao/lumbergh

For tracking on bedrock, we can just create a note on the board (shouldn't need to open a duplicate issue). Thanks

**Comment by craigcook** [comment]
Submitted PR https://github.com/mozmeao/lumbergh/pull/348

**Comment by stephaniehobson** [comment]
Done!
