### ISSUE TITLE
Determine winner of Yandex A/B test

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6300]
In #5635 we added a Yandex specific download page at `/firefox/ru/yandex/`. As part of that work, we also started an A/B test to ensure that conversions weren't too adversely effected (90% of audience currently get Yandex, 10% get the regular FF download).

As far as I'm aware, we never found out the winner of this test and it is still running. Next steps should be to chase this data up, and decide on a winner.

a. Promote 100% of audience in Russia to Yandex
b. Revert the experiment if unsuccessful to the regular download page.

**Comment by alexgibson** [comment]
Ok, it sounds like the ask here is to remove the test and make Yandex 100% regardless of what the data tells us.

**Comment by hoosteeno** [comment]
I talked with BD team. Please don't remove this yet.

**Comment by alexgibson** [comment]
Closing as a duplicate of https://github.com/mozilla/bedrock/issues/6752
