### ISSUE TITLE
Urgent legal copy changes to some web pages

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6306]

**Comment by craigcook** [comment]
I think we'll need some more guidance on these items so we can take proper action to address them.

> On the landing page for IRL, change the line “IRL is an original podcast from Mozilla” by adding “Corporation” to the end.

This seems simple enough at a glance but I wonder if it has broader implications for the brand. We generally refer to "Mozilla" as a singular entity (which I guess is the whole problem here) so if we have to start saying "The Mozilla Corporation" emphatically everywhere we would normally say "Mozilla," that's a really far-reaching change way beyond one tagline on one website.

> At https://www.mozilla.org/en-US/foundation/ there is a description of the roles of the Foundation and the Corporation. Add to the description of the corporation that it owns and is responsible for mozilla.org websites other than foundation.mozilla.org (or whatever is accurate to say, that makes clear that www.mozilla.org and blog.mozilla.org are not foundation content).

The legal team should provide us with accurate copy here, or should we just draft something for them to review? And is it correct to say that the entirety of www.mozilla.org is "not Foundation content"? We have a fair amount of what I would consider Foundation content on the site. The manifesto for example, as well as a lot of governance policies and documentation.

As for blog.mozilla.org, that subdomain houses 80+ separate and distinct blogs with many thousands of unique pages, some of which might be also considered Foundation content.

I worry this could snowball into a massive undertaking to break up mozorg into separate sites. I guess I mostly want to know what exactly distinguishes "MoCo" content from "MoFo" content. I'm not a lawyer (obviously) but might it be sufficient to say that the Mozilla Corporation owns and manages these websites on behalf of the Foundation? So even if we publish "Foundation content" that web property still falls under MoCo ownership?

> The browser certificates seem to show ownership by Mozilla Corporation for www.mozilla.org but not blog.mozilla.org—it would be good to have blog.mozilla.org also registered so the security certificates show that it is owned by Mozilla Corporation.

This may be a job for webops. I'm not sure what cert is being used for the blog subdomain or how to get the address bar to show the organization name. For what it's worth, I'm not sure any of our many subdomains display the org name in the address bar (e.g. support.mozilla.org, careers.mozilla.org, foundation.mozilla.org, developer.mozilla.org, and so on).

> Somehow label the www.mozilla.org site and the blog.mozilla.org site to say that this site is owned and maintained by Mozilla Corporation, which is responsible for the content on the site. This could also say, “For the website of Mozilla Corporation’s nonprofit parent, the Mozilla Foundation, go to http://foundation.mozilla.org.”

That seems like something best put in the footer, probably in addition to our standard copyright statement. Some precise language from legal would be good here. 

Also blog.mozilla.org is more than one blog, and they don't all have the same footer. It will be a challenge to standardize a single element across every blog. If there's some way we can make it clear in one place who owns/manages all the blogs that might give us the coverage we need, as opposed to trying to put a statement on every individual blog.

**Comment by djst** [comment]
All valid points. Clay, can you take a look and discuss with Natalie to
identify appropriate solution and language?

Den tor 18 okt. 2018 00:44Craig Cook <notifications@github.com> skrev:

**Comment by stephaniehobson** [comment]
The IRL update is on its way to production.

I would like to update it to `the Mozilla Corporation` instead of `Mozilla Corporation` if that's okay. It's more readable.

**Comment by stephaniehobson** [comment]
Also, the[ about page on IRL](https://irlpodcast.org/about/) has the word Mozilla several times.
