### ISSUE TITLE
Update URL About page card for Foundation to foundation.mozilla.org

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6315]
MEM asked why we link to Mozilla.org/foundation which is really outdated, rather than foundation.mozilla.org. I can't think of a reason other than to keep users within the same domain and navigation, but I dont think that's a strong reason for linking to an old page.

The quick fix here is to just update the link target. Not sure if that's the correct solution but it feels better than linking to /foundation.

Success criteria:
- Foundation card links to foundation.mozilla.org

**Comment by jamesgeorge007** [comment]
@djst Could you elaborate?

**Comment by alexgibson** [comment]
The `/foundation` landing page now redirects to https://foundation.mozilla.org/, so we can close this.
