### ISSUE TITLE
Remove incorrect info from Firefox webpage

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla/bedrock#6321]
Hi,

First of all I should say, I'm Firefox user.

Here: [https://www.mozilla.org/en-US/firefox/new/](https://www.mozilla.org/en-US/firefox/new/) I see this:

> Uses 30% less memory than Chrome

It's not true at all, please remove it, people makes joke about that.

Thanks.

**Comment by ejregithub** [comment]
This assertion was not without made without testing to support the claim at the time is was made. Those data can be found here - https://blog.mozilla.org/firefox/quantum-performance-test/
