### ISSUE TITLE
Global Navigation - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6333]
| Estimates |  |
| ------------- | ------------- | 
| TL | 2|
| PM | 0|
| ENG |4 |
| SEO | 0|
| ANA | 0|
| DES | 1|
| COPY | 0|

Add sub links under the "Accounts" heading on the global nav. We want a link to /accounts/features, as well as a link to signin/signup (possibly /accounts)

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Users can access login from nav link
- [ ] Users can access FxA benefits pages

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:

Risks:
- [ ] Determination of where the new page will live (the URL) 

Tasks:
- [ ] JRouse (@dzingeek) to talk Amy about this, the layout and required elements
- [ ] Code - @amychurchwell

**Comment by dzingeek** [comment]
It looks like accounts.firefox.com does not look to see if a user is signed into an account or not. So unless that can get "fixed" this, I think we should avoid adding Create Account as a sub-link in the nav under Firefox Accounts. In my opinion, it would make for a bad user experience. 

@amychurchwell did you want to add anything else?

**Comment by amychurchwell** [comment]
CC: @dzingeek in regards to conditional Create Account sublink in nav--
* Had a talk w/ @stephaniehobson in which we both agreed that we _should not_ target whether fxa users are signed in. We would need to load in an extra JavaScript library, adding approx 1/2 second wait.
* We will however show the link only if the user is using a firefox browser.

^ all of the above depending on our conversation with the fxa product team as you mentioned.

**Comment by amychurchwell** [comment]
**Temporarily blocked:** waiting to hear back from accounts.firefox.com about a logged in user being redirected to account preferences instead of sign-up form.

**Comment by amychurchwell** [comment]
**Status update for posterity:** We decided to not move forward with fxa account state in the global navigation for the time being.
