### ISSUE TITLE
Custom /download/thanks - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6334]
| Estimates |  |
| ------------- | ------------- | 
| TL |2 |
| PM |2 |
| ENG |5 |
| SEO | 0|
| ANA | 1|
| DES | 10|
| COPY | 6|

A custom /download/thanks page which encourage users to continue their journey to creating an account. Michelle identified that the email newsletter is a very good way to get them to do that and is important to her to keep. (Probably design changes and copy additions).

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Custom thanks page consistent with user journey
- [ ] Open Firefox to continue

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:

- [ ] Only opportunity to sign up for welcome journey
- [ ] FxA sign up journey is not clear

Tasks:
-  [ ] Research feasibility of custom /download/thanks/ for this journey

**Comment by ejregithub** [comment]
We need to socialize this with Michele @vincejoyiv

**Comment by ejregithub** [comment]
@amychurchwell - please provide additional comments on the tasks here, along with comments about the topic of technical debt you mentioned from a discussion w. Alex

**Comment by alexgibson** [comment]
Every new page we create comes with a cost of maintenance over time. If we’re creating custom /thanks/ pages for specific campaigns or pages, let’s make sure it’s for a good reason.

**Comment by amychurchwell** [comment]
@alexgibson @dzingeek I mentioned in our meeting earlier that we can tether this dev task with addressing some of the previous /thanks debt. I think it's worth doing for this project/not purely to match design. Feels like an evergreen change to me.
Welcome to set up a sync w/ the three of us to discuss.

**Comment by dzingeek** [comment]
Sounds good @amychurchwell please set up a quick meeting. Thanks!

**Comment by djst** [comment]
I appreciate the pragmatism of that approach. We will need to align on these changes of expectations with Michele though.
