### ISSUE TITLE
Update /Firefox Sync Section - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6335]
| Estimates |  |
| ------------- | ------------- | 
| TL | 2|
| PM | 2|
| ENG |5 |
| SEO | 0|
| ANA | 1|
| DES | 5|
| COPY |8 |

Add a link to the accounts benefits page in the "Sync your devices" section of the /firefox page

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Talk to Fx project
- [ ] If no overhaul, update Sync section

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Depends on prioritization

Tasks:
- [ ] Copy
- [ ] Create link to new page once established
- [ ] Code

**Comment by dzingeek** [comment]
This is the current sync section that we will want to update.

<img width="1122" alt="screen shot 2018-10-25 at 3 31 38 pm" src="https://user-images.githubusercontent.com/3740746/47545548-d0d8bf00-d8a1-11e8-86f5-6bb5d6c7ad82.png">

**Comment by dzingeek** [comment]
@amychurchwell Because we are not redesigning /firefox we will just be adding a link to the sync section that will take users to the benefits page.

**Comment by dzingeek** [comment]
@clay-chaffin is working on copy now and should have something by eod tomorrow (12/14/18).

**Comment by claychaffin** [comment]
For anyone looking for me, I'm now claychaffin

**Comment by ejregithub** [comment]
@claychaffin - per the[ comment above](https://github.com/mozilla/bedrock/issues/6335#issuecomment-447105314) - has the copy been delivered for this?

**Comment by claychaffin** [comment]
@ejregithub Yes, I delivered the copy to our stakeholders. We await Michele Warther's input/approval. Consensus thusfar: Option 1
