### ISSUE TITLE
Homepage Banners CTA - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6337]
| Estimates |  |
| ------------- | ------------- | 
| TL | 1|
| PM | 4|
| ENG | 10|
| SEO | 0|
| ANA | 1|
| DES | 10|
| COPY | 4|

Change Download CTA on homepage for FF users to an Accounts Benefits CTA

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Replace Fx download CTA for Fx users w. FxAccount CTA
- [ ] Analytics QA
- [ ] Inform stakeholders
- [ ] Reuse design & copy from benefits page
- [ ] Replace secondary download CTA for Fx Users
- [ ] Internal Design QA
- [ ] Stakeholder Design QA
- [ ] Internal coded component QA
- [ ] Stakeholder Design QA
- [ ] Stakeholder coded page QA

**Comment by dzingeek** [comment]
These are the two sections on the hmpg that we will want to update for users using fx.
<img width="1135" alt="screen shot 2018-10-25 at 3 31 02 pm" src="https://user-images.githubusercontent.com/3740746/47545584-fd8cd680-d8a1-11e8-8936-6c61ab95738d.png">
<img width="1129" alt="screen shot 2018-10-25 at 3 31 14 pm" src="https://user-images.githubusercontent.com/3740746/47545586-fe256d00-d8a1-11e8-8295-7e6d1891b636.png">

**Comment by dzingeek** [comment]
Latest Designs can be found here

[Desktop View](https://mozilla.box.com/s/litusssxk31i3k1wa1tmsojdcutlrqbf)
[Mobile View](https://mozilla.box.com/s/67e5c75ykzy1e6u6domweth0jok96tch)
