### ISSUE TITLE
Benefit Sub Pages (PER PAGE) - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6338]
| Estimates |  |
| ------------- | ------------- | 
| TL |5 |
| PM | 12|
| ENG | 60|
| SEO | 0|
| ANA | 6|
| DES | 60|
| COPY | 24|

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Conditional content
- [ ] Enable discovery of other features
- [ ] Decom old /firefox/features/ pages
- [ ] Teach people how to use features
- [ ] Internal Design QA
- [ ] Stakeholder Design QA
- [ ] Internal Coded page QA
- [ ] Stakeholder Coded page QA
- [ ] Analytics QA
- [ ] Legal Approval
- [ ] Uses Raphael's SEO keyword recommendations
- [ ] Link to external URLs where appropriate

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] RR Input

**Comment by stephaniehobson** [comment]
Post MVP, but we can revive it later if we want.
