### ISSUE TITLE
List of FxA Services - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6344]
| Estimates |  |
| ------------- | ------------- | 
| TL | 1|
| PM | 0|
| ENG | 1|
| SEO | 0|
| ANA | 0|
| DES | 6|
| COPY | 0|

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Need the full list of Benefits and high-level description on what they do/are.
- [x] Stakholder approved

Tasks
- [x] Eric to reach out to Celeste and Michele about these across the x named products/benefits to obtain a description of each and some detail on the key benefits
- [x] Eric to book kickoff meeting with stakeholders (Michele/Celeste/Yuliya)

**Comment by dzingeek** [comment]
After our conversation w/Celeste and Michele yesterday it was confirmed we will be talking about these 6 benefits.

1. Sync
2. Send Tabs
3. Pocket
4. Lockbox
5. Notes
6. Screenshots

**Comment by ejregithub** [comment]
@clay-chaffin @claychaffin - please post the link to the reference materials doc that Celeste provided to the team here.

**Comment by claychaffin** [comment]
FxA Firefox Accounts/ User Benefits slides: https://docs.google.com/presentation/d/1nOOz5hHHq0zMQNqSMstM69fdaUJTWHn41SWbY_cD3AI/edit#slide=id.g30ad5da84d_0_0

**Comment by claychaffin** [comment]
FxA account benefits descriptions (just the facts): https://docs.google.com/document/d/13EkOs8sq5QYJieC7JlB1h4sQrIljwLSFBvGoYo2o084/edit?usp=sharing
