### ISSUE TITLE
Information Architecture Recommendations - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6345]
| Estimates |  |
| ------------- | ------------- | 
| TL | 0|
| PM | 0|
| ENG | 1|
| SEO | 0|
| ANA | 0|
| DES | 1|
| COPY | 0|

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] we know the final url target of the main page (e.g. /firefox/benefits)
- [x] We've established the recommend links to this page, both internal on moz.org and external (podcast et al)
- [ ] What pages link to this 'page', to where does this page link (2/3)
- [ ] Context of 'page' w. rest of site? (3/3)
- [ ] We have a recommendation of how to link to/from SUMO

Tasks
- [ ] Informed by #6349, @rraue to provide recommendation for placement in IA

**Comment by dzingeek** [comment]
Final url for the benefits page should be https://www.mozilla.org/en-US/firefox/accounts/

**Comment by dzingeek** [comment]
**Links to this page from within moz.org**
- Homepage banners (top and bottom)
- Sync Sections on /firefox/
- Navigation (mega menu)

**Redirects to this page from moz.org**
- /firefox/accounts/features/
- /firefox/features/sync/
- /firefox/features/send-tabs/

**Links from this page NEED FINAL URLS**
- Pocket App Store
- Pocket Google Play Store
- Lockbox App Store
- Notes Google Play Store

_Still figuring out where else we can link to this section from outside of the moz.org_

**Comment by dzingeek** [comment]
@rraue please see above lists and let me know if I missed anything.

**Comment by rraue** [comment]
Additional:

**Links to this page from within moz.org**

- Sync Sections on /firefox/mobile/

- Sync Sections on /firefox/features/

- Account Data Section on /privacy/faq/

**Comment by dzingeek** [comment]
@amychurchwell Something like this for the /privacy/faq/ section
![screen shot 2018-11-06 at 2 57 33 pm](https://user-images.githubusercontent.com/3740746/48099428-59c1f580-e1d4-11e8-90ba-5570ea1f75dc.png)

**Comment by ejregithub** [comment]
**Links to this page from within moz.org**
- [ ] Homepage banners (top and bottom)
- [ ] Sync Sections on /firefox/
- [ ]  Navigation (mega menu)

**Redirects to this page from moz.org**
- [ ] /firefox/accounts/features/
- [ ] /firefox/features/sync/
- [ ] /firefox/features/send-tabs/

**Links to this page from within moz.org**
- [ ] Sync Sections on /firefox/mobile/
- [ ] Sync Sections on /firefox/features/
- [ ]  Account Data Section on /privacy/faq/

@dzingeek @amychurchwell - please review these for completion (I've check the ones I've confirmed myself and I know the Sync Sections on /firefox/ is WIP
