### ISSUE TITLE
Research - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6346]
| Estimates |  |
| ------------- | ------------- | 
| TL | 1|
| PM | 1|
| ENG | 2|
| SEO | 0|
| ANA | 0|
| DES | 10|
| COPY | 0|

Gather extending research and data (both quan and qual) to help us inform our decisions moving forward. And to Better understand the current page and the benefits. 

---

#### Success Criteria 💛 
- [ ] Natalie and Clay are up to speed on previous learnings of what style of messaging of features best resonate with users
- [ ] We are up to speed on past user research from Product User Research Team
- [x] We are up to speed on past user research on animation for FxA

**Comment by dzingeek** [comment]
[Here is the user research](https://mana.mozilla.org/wiki/pages/resumedraft.action?draftId=77889919&draftShareId=cbec2441-f860-46ef-a0fa-ce02fd59d298) from v.1.0 of FxA Benefits

**Comment by dzingeek** [comment]
@ejregithub where can I find past user research from product user research team as well as past user research on animation for FxA (see last two items in success criteria)

**Comment by dzingeek** [comment]
I am saying this item is blocked as I need the above information from @ejregithub and I still don't fully understand what all the fxa benefits are, so I can't do any user testing.

**Comment by ejregithub** [comment]
@dzingeek  - FxA image/animation testing 
- https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=72783034

**Comment by ejregithub** [comment]
@dzingeek - Yes! Per my Slack message: https://firefoxur.github.io/

Also, questions about this research can be posed in #userresearch

**Comment by dzingeek** [comment]
Below is some data from GA:

[Traffic to Current Pg (/firefox/accounts/features)](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a36116321w64087799p65789850/explorer-table.filter=en-US~2Ffirefox~2Faccounts~2Ffeatures~2F&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.sourceMedium&explorer-table.advFilter=%5B%5B0,%22analytics.landingPagePath%22,%22RE%22,%22en-US~2Ffirefox~2Faccounts~2Ffeatures~2F%22,0%5D%5D/)
- ~67% Direct
- ~18% Email
- ~7% support.mozilla.org

[Browsers Traffic to Current Pg (/firefox/accounts/features)](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a36116321w64087799p65789850/explorer-table.filter=en-US~2Ffirefox~2Faccounts~2Ffeatures~2F&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.landingPagePath%22,%22RE%22,%22en-US~2Ffirefox~2Faccounts~2Ffeatures~2F%22,0%5D%5D&explorer-table.secSegmentId=analytics.browser/)
- ~88% Fx 
- ~6.5% Chrome

Events on Current Pg (/firefox/accounts/features) 
- ~43% Button Click (create account or not set label)
- ~31% Firefox Download
- ~13% Nav Clicks

**Comment by djst** [comment]
I think I can live with your rationale for descoping this, but I don't agree that this is something we can't own. It's a matter of chasing some people on the Product UR team, set up a 30 minute 1:1 or 1:n to get a quick download of any important things they've researched as it relates to our proposed approach (wall them through it) to make sure we capture any important gotchas before we execute. Doesn't have to be that hard.

**Comment by dzingeek** [comment]
So while I totally get that a 30 min 1:1 with each product owner should be easy that is a total of about 3 hours. Which I am not sure is something we need to do in order to make this a successful project.  I also don't feel that it's necessary as we are not "selling" these products, we are trying to sell the idea of an account. 

We will however pass any copy to Celestes to make sure we are capturing things correctly. It's my understanding that it's her responsibility to talk to those product owners. 

@djst how does that sound?

**Comment by djst** [comment]
That sounds great @dzingeek and I was responding to the part about getting up to speed on past research from product UR team which I think is just one conversation, not six. And, I'm fine with skipping that too, especially if you don't think we need it (and I totally trust your opinion, here). Thanks!

**Comment by ejregithub** [comment]
@dzingeek - can you please review this issue, closing it if it is complete or indicating next steps if not?
