### ISSUE TITLE
Audit Existing Pages for Conversion Baseline - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6349]
| Estimates |  |
| ------------- | ------------- | 
| TL | 0|
| PM | 0|
| ENG |0 |
| SEO | 0|
| ANA |2 |
| DES | 0|
| COPY | 0|

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### Success Criteria 💛 

- [ ] Understand existing FxA conversion of account/features/ page to set success metric from that baseline
- [ ] Answers captured in github issue card

Task
- [ ] Eric to ask @rraue for any current data he has and then follow up w. AP to fill in any gaps

**Comment by dzingeek** [comment]
User flow still a wip. This is a good place to start. 
![features user flow](https://user-images.githubusercontent.com/3740746/47667465-48894100-db63-11e8-95c4-2daf0c05be1e.png)
