### ISSUE TITLE
[Jan 29th] Whatsnew 65

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6352]
[Master Project Doc](https://docs.google.com/document/d/1zYG6GBewf18Q9DOpP-PV9GS3oAA6WMvwTYoo9SYF0YM/edit#)

| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | 10 |
| ENG | 8 |
| SEO | N/A |
| ANA | |
| DES | |
| COPY | 0 |

Description: Updates to the content on the WNP for the Firefox 65 release. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Content is live the Wednesday (1/23) prior to the release date

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Late delivery of copy intended for localization
- [ ] No details on desired test (to en-US) from Alex Davis

**Comment by ejregithub** [comment]
Michele Warther indicated that the page will remain largely the same with only the removal of some content with no new strings.

**Comment by alexgibson** [comment]
Based on our meeting yesterday, this is the plan for WNP 65:

- Reuse the [/whatsnew page for 63](https://www.mozilla.org/en-US/firefox/63.0/whatsnew/) (no changes to the main page copy). We should Trigger whatsnew for the same list of locales that we used for 63.
- Users who are not logged into FxA will see the same blue sticky bar prompting to create an account.
- Users who are signed-in will see a Firefox newsletter signup in the sticky bar instead (reusing existing strings from main.lang).
- Users who are signed-in but are in a locale where the newsletter is not translated, will not get a sticky bar at all. Newsletter locales are: en, es, pt-br, fr, de, pl, ru.
- The `id` and `zh-TW` locales will get their usual locale specific templates.

**Comment by ejregithub** [comment]
@alexgibson - could you please take screenshots for each condition and attach those to this issue for stakeholder review?

**Comment by LaurenNiolet** [comment]
For EN version, the body text won't align to the CTA for versions where we are presenting the email signup. 

For those, the CTA is "Get Firefox tips, tricks, news and more" Body text says "...And sign up for a better internet all around with a free Firefox Account" 

I suspect we will just have to live with that on l10n versions, given the time crunch, is that right?

**Comment by alexgibson** [comment]
> I suspect we will just have to live with that on l10n versions, given the time crunch, is that right?

We could show something different for English pages (if you can provide an alternative), but you're correct we can't change strings that have already been translated for other locales.

**Comment by alexgibson** [comment]
Fwiw, this string was also here regardless of being signed in or out for the 63 WNP.

**Comment by LaurenNiolet** [comment]
Good point. Approved.

**Comment by ejregithub** [comment]
@alexgibson (logging the decision you already are aware of) - Per Michele Warther in Slack and the meeting we were just in we need to:  for 65 we need to omit the sentence (the single string)/ headline “Here’s What’s New” that's in the existing page WNP63.

**Comment by alexgibson** [comment]
This page is now live in production: https://www.mozilla.org/en-US/firefox/65.0/whatsnew/
