### ISSUE TITLE
Sync page redesign (placeholder card, Michele to kick off seven sheets)

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6353]

**Comment by alexgibson** [comment]
We should probably pause to understand why there is a request to redesign this page, given that we're also about to start redesigning `/firefox/accounts/features/`. Both pages could likely cover the same things. I know we discussed the possibility of retiring `/firefox/features/sync/` if it became redundant after the redesign of the benefits page - but that is still to be determined.

**Comment by alexgibson** [comment]
This page no longer exists as it was replaced by the new /firefox/accounts/ redesign. 

Closing.
