### ISSUE TITLE
Move Trademark Policies into Legal Repo

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6357]
Conversion of the existing pages/documents into markdown and addition of them to the legal-docs repo, and then conversion the pages to use the legal-docs markdown.

https://bugzilla.mozilla.org/show_bug.cgi?id=1501452

**Comment by maureenlholland** [comment]
@pmac I think this is done but don't have permissions to view the bug

**Comment by maureenlholland** [comment]
confirmed, bugzilla closed without moving policies to legal repo, needed changes were made in https://github.com/mozilla/bedrock/pull/10102

a new bug will be opened if it's decided worthwhile to move the policies
