### ISSUE TITLE
[10/29] Shield study for Private Browsing

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6361]
[Copy/idea doc](https://docs.google.com/document/d/16rDLIXSxhrnOZXTHLcSz2RR0aFg5hHii2mpCv0oos1g/edit?ts=5bcfadae)

Description

Success Criteria:
- [x] page is live and shown to shield study participants

Risks
- [ ] Timeline

Tasks
- ~~Copy~~ We're using their copy
- [x] Design
- [x] QA of creative (internal)
-  ~~QA of creative (stakeholder)~~ We're using their copy
- [x] Dev - Code page
- [x] QA of coded page (internal)
- [x] QA of coded page (stakeholder)

**Comment by stephaniehobson** [comment]
Vince and I had a short follow up. Keeping in mind that there is a tight deadline and it's an experiment we decided a few things:

- We will use the copy provided (which is from SUMO)
- We will drop the keyboard shortcut explanation

Vince will:
- [ ] make images that are:
  - same aspect ratio of current images
  - match graphic treatment of current images
  - not include keyboard shortcuts

Stephanie will:
- [ ] add the experiment to the current page
- [ ] communicate with the Fx team to set a URL variable to trigger it
- [ ] add the 2 blocks continuing the same left/right pattern
- [ ] leave one of the marketing blurbs as the first thing on the page

**Comment by vincejoyiv** [comment]
Image assets attached below.

![newprivatewindow_ 2x](https://user-images.githubusercontent.com/13005624/47530147-a3b6ed00-d85e-11e8-8942-021f3ce5e87b.jpg)
![openlinkpbm_ 2x](https://user-images.githubusercontent.com/13005624/47530148-a3b6ed00-d85e-11e8-94e5-a56577732c96.jpg)

**Comment by stephaniehobson** [comment]
The PR is in.

It is up on demo here: https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/features/private-browsing/?v=a

With the deadline I think it is important to get it merged as long as there's nothing broken. If Porfirio has feedback we can address it after it's live.

**Comment by RosanneScholl** [comment]
This is wonderful! Thank you so much for creating it on rather short notice. For the purposes of the research, is it possible to re-order the blocks so that the two instruction ones are first, and the value propositions are lower? That's the only change I think will be needed.

**Comment by RosanneScholl** [comment]
^I know this is not what you'd usually do from a communication perspective, but it makes sense in the context of how users will be arriving to the page from within the study, and their needs at that point.

**Comment by ejregithub** [comment]
@stephaniehobson - please see Rosanne's comments above ^^

**Comment by stephaniehobson** [comment]
We did it this way because Porfirio wanted to strike a balance between marketing and instructions based on there not being much info in-product about the benefits of Tracking Protection.

It's a quick, easy change though, I'll get started.

**Comment by ejregithub** [comment]
@stephaniehobson -  i think we're good here and close this issue, but please confirm there are no further asks on your plate for this.
