### ISSUE TITLE
Edge SEM pages - adjust the test

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6371]
Description: The New User aDAU team ran a test for the Edge landing pages (browser comparison). Result analysis from the testing data indicates that the test parameters should be changed.

Success Criteria:
- [x] Remove [v=1](https://www.mozilla.org/en-US/firefox/new/?xv=edge&xv=edge&v=1) from the test
- [x] Adjust the test to direct traffic, 50/50, to [v=2](https://www.mozilla.org/en-US/firefox/new/?xv=edge&xv=edge&v=2) and v=a (the default /new page).

**Comment by alexgibson** [comment]
Ok, I have some questions:

The ask here is to remove `?v=1`, but that's the same page where this experiment is set to run _from_. If I remove this template and don't adjust anything else, then the experiment won't run at all. This means we also need to adjust the URL where this experiment is triggered from. There are some possible solutions, but each has reprecussions:

- We could run the experiment from the regular `/firefox/new/` URL, but I'm not clear how this would effect reporting, it may mess things up. 
- We could make `?v=2` the new default comparison landing page for Edge, and display it at ?v=1` and run the experiment from there. Again, this could mess up reporting.
- Changing the default URL where the experiment runs from, also assumes that all the ads being used to route traffic to these pages would also need their URLs updating. I'm not clear if this can or will happen.

Adding this issue as blocked until we get clearer requirements.

**Comment by ejregithub** [comment]
@alexgibson - Xuan stated:  "For Edge, traffic is really low at 28 sessions/day. Currently DL rates for Control = 39.69%,  39.62% from V2 (-0.2% w/ control), and 37.95% from V1 (-4.4% w/ control). Although we can't say V1 is statistically significantly worse than Control, with current data we can get rid of V1, and continue test Control and V2 if needed."

Thus the request at hand (Kirby wants to continue the testing).

**Comment by alexgibson** [comment]
Thanks @stephaniehobson, I think your suggestion makes good sense. I've updated the PR to default `/firefox/new/?xv=edge` to use `scene-1-edge.html`, and the traffic cop experiment uses `?v=a` for control, and `?v=3` for what was V2.

@ejregithub please relay that the URLs are changing as above. They will need to look at the performance of `?v=3` going forward. Traffic split is now 50/50.
