### ISSUE TITLE
Remove legacy navigation from bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6377]
Once we're happy that the new Protocol navigation is here to stay, we need to remove both the switch and the code for the legacy nagivation from bedrock.

**Comment by alexgibson** [comment]
@ejregithub @djst please reply here and let me know when we're confident that the old navigation can be removed. Thanks.

**Comment by djst** [comment]
Will do. I have a hard time imagining that we'd want to keep it, but let's look more carefully at performance of the new nav before moving forward. 

Blocked on me.

**Comment by djst** [comment]
Xuan got pulled into other requests and I'm still waiting for her analysis. There are some data points I'm observing that make me somewhat concerned, so I'd rather keep the code here until she has verified it. That said, the likeliness of us pulling back is approaching zero. It's just a matter of feeling confident about the decision before going ahead. 

All this said: you have said before that "nothing is ever removed for real, you can always roll back" - if that's true here as well, I don't think I need to block this issue.

**Comment by alexgibson** [comment]
> All this said: you have said before that "nothing is ever removed for real, you can always roll back" - if that's true here as well, I don't think I need to block this issue.

That is true, but this is a large site wide change. I'd rather not have to do this multiple times, so let's be sure before we remove this code.

**Comment by djst** [comment]
Update: we can remove the old code. 

Over the first 2 weeks after the navigation change to Moz.org is consistently surpassing download performance thresholds for non-Firefox visitors based on multiple predictions.

![image](https://user-images.githubusercontent.com/5638050/48840666-9c1c3280-ed8f-11e8-95d5-a030b5e5a4b8.png)
_Figure1. DoD SUM of forecasted downloads versus actuals._

**Comment by djst** [comment]
@dzingeek, you get to keep your job. ;)

**Comment by stephaniehobson** [comment]
We get to keep @dzingeek  🎉
