### ISSUE TITLE
 Upgrade to new Sentry SDK 

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/bedrock#6378]
Sentry dropped raven package in favor of a new unified SDK.

-   New Package: https://github.com/getsentry/sentry-python
-   Docs: https://docs.sentry.io/quickstart/?platform=python

While I couldn't find a deprecation schedule, please plan to upgrade to the new SDK in the near future to avoid incompatibility issues with the server.

**Comment by jwhitlock** [comment]
One issue for kuma is ``csp_violation_capture``, borrowed from bedrock, which uses ``raven.contrib.django.models.client``, to capture data from the request (``client.captureMessage``). There doesn't appear to be an equivalent in sentry-python (clients and Django integrations are re-written, and ``sentry_sdk.capture_message`` doesn't take data).

I'm going to experiment with reporting CSP directly to Sentry, demoed here: https://blog.sentry.io/2018/09/20/content-security-policy-newegg-breach

**Comment by pmac** [comment]
Finally getting around to doing this. And on the CSP thing it seems that Sentry now has a specific URL they give you for security header reports, including CSP violation. If you're curious the URL is listed in the available client keys in the app's settings in Sentry.

**Comment by glogiotatidis** [comment]
> Finally getting around to doing this. And on the CSP thing it seems that Sentry now has a specific URL they give you for security header reports, including CSP violation. If you're curious the URL is listed in the available client keys in the app's settings in Sentry.

sweet, thanks for the heads up!
