### ISSUE TITLE
Add main navigation to `/firefox/enterprise/` and `/firefox/channel/` pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6381]
Both of the above pages we're designed without a consistent navigation component, which makes navigating to them an inconsistent experience. 

The new navigation should be easy enough to add to both pages for `en` locales, falling back to existing/legacy nav for other locales.

**Comment by rraue** [comment]
@alex Could you please always cc me when we change something on the main nav or footer links. All site wide links are very important for Seo. Thank you.

**Comment by alexgibson** [comment]
@rraue this PR isn’t changing anything on the navigation or footer. It’s adding the navigation to pages that didn’t have it before.

**Comment by rraue** [comment]
No, its very good that we are doing it, I am just running a Seo monitoring on the new nav and if we expand it to more pages, I need to adjust it. I just want to be in the loop and know so I can monitor 😉
