### ISSUE TITLE
New feature page: What is Activity Stream

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6384]
Description: Activity Stream is an important feature of Firefox. Providing users with information on what this is and the benefits it provides to them. 

[Background doc](https://wiki.mozilla.org/Firefox/Activity_Stream)
[Graduation report (from TestPilot)](https://medium.com/firefox-test-pilot/graduation-report-activity-stream-31aed429bd49)

**Comment by alexgibson** [comment]
Closing, as I don't think activity stream is marketed as a named product feature today.
