### ISSUE TITLE
Firefox Fights For You Campaign Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6387]
[MasterProjectDoc](https://docs.google.com/document/d/1l4VKr7uEeZLha1MSsF0Rb4yhYhFG6ng8daV0zbESrcs/edit#)

| Estimates |  |
| ------------- | ------------- | 
| TL | 10|
| PM | 12 |
| ENG | 14 |
| SEO | 1 |
| ANA | 4 |
| DES | 40 |
| COPY | 20 |

Description, good enough that reading the card 1 month from now, you still know what it means.
---
#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Analytics in page (GMT - data attributes) to enable proper data reporting post launch/page is tagged appropriately to ensure data is sent and record
- [x] Copy Deck reviewed and approved by MJ
- [x] Copy translated into German - due on 11/21
- [x] Launch to en-US and DE (confirmed w. Janis on 10/31)
- [x] Visuals
- [x] Build in Protocol w. new components added
- [ ] ~Protocol code/design review~
- [x] Design must be approved by the team and the Approver
- [ ] Legal has approved the copy
- [x] The Coded page must be approved by the team and the Approver
- [x] Analytics has QAed and approved tagging in the page
- [x] Page includes a section on Firefox Desktop Browser as an entry point for talking about how FFFY
- [x] Page includes sections on sub-products as proof of Firefox Fighting for You
- [x] Page is set to be indexed (@rraue feels doing so will be of benefit)
- [x] Video component
- [x] We need to understand video content so we can write copy around it
- [x] Survey link included

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Localization as a blocker to launch - ask Michele (en-US and DE required for launch)
- [x] Video component (the video) may not land on this page
- [x] Time line needs to built and shared
- [x] The creative team is out all next week (11/12->)
- [x] Design calls for a new web font we don't have a license to

**Comment by ejregithub** [comment]
Eric pinged Janis in the FFFY-page Slack channel "for the page being produced here - is DE required for launch (is it tied to campaigns/messaging on/after the specified launch date) ?"

**Comment by ejregithub** [comment]
Janis confirmed that the page must be localized to DE for launch. "we will have DE media driving as well.  It will also start 11/27"  So, I'm clearing the flag in Success Criteria and nothing EN and DE as Success Criteria

**Comment by stephaniehobson** [comment]
We can't rely on the volunteers to turn this around quickly enough so we will need to get a German translation somehow. David suggests the German marketing team can do it. Adding a task to get the transaltion.

**Comment by ejregithub** [comment]
Eric to work w. JBalaco on getting Legal review of copy

**Comment by ejregithub** [comment]
Final DE localized copy required to be in Stephanie's hands on the 21st

**Comment by ejregithub** [comment]
@rraue , @stephaniehobson
please provide your opinions on what the URL for this page should be. 

/firefox/fights-for-you/  ?

**Comment by stephaniehobson** [comment]
I like /firefox/fights-for-you/ 😃

**Comment by stephaniehobson** [comment]
Adding a new risk: "Design calls for a new web font we don't have a license to".

Vince said there's a meeting about it on Thursday and they'll have more information then.

**Comment by rraue** [comment]
Me too, good one @ejregithub 😎

As long we do not have an explicit structure for the campaign pages, we should just care that the url is representing the campaign in the best way possible and here this is /firefox/fights-for-you/

**Comment by stephaniehobson** [comment]
We've been asked to include a survey on this page.

Survey link: https://www.surveygizmo.com/s3/4693873/FFFY-Heartbeat-Survey
Old code that might be re-used for this: https://github.com/mozilla/bedrock/pull/5082

**Comment by vincejoyiv** [comment]
@stephaniehobson attaching images here, with the caveat that they might turn into stock photography. 


![fffy-privacy-illustration 2x](https://user-images.githubusercontent.com/13005624/48800169-e208c600-ecbd-11e8-8205-89c299e50229.png)
![fffy-focus-illustration 2x](https://user-images.githubusercontent.com/13005624/48800170-e208c600-ecbd-11e8-832b-08d2d04cfb07.png)
![fffy-monitor-illustration 2x](https://user-images.githubusercontent.com/13005624/48800172-e208c600-ecbd-11e8-97b4-ecd2979238b0.png)

**Comment by ejregithub** [comment]
Survey: Tyler recommends a 50% sample size, which assumes a 1% CTR (which is probably a bit high) will give us right around 1000 responses.

**Comment by stephaniehobson** [comment]
English and German pages are both on the demo server now:
https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/fights-for-you/
https://bedrock-demo-shobson.oregon-b.moz.works/de/firefox/fights-for-you/

**Comment by stephaniehobson** [comment]
Update on the web font.

We purchased the license yesterday and I received a copy of the files today.

SREs say we need to be able to include them in the bedrock repo in order to get them onto the site. I have asked Michael in legal if we can license a sub directory of the repo under a different license and if the contract would allow us to put the file onto GitHub. He's off for Thanksgiving today.

**Comment by vincejoyiv** [comment]
@stephaniehobson This is looking great in both languages. Just a couple QA things. 

1. I got your email re: the hero text width change from (50% - 48px) to 50%. LGTM.
2. I'm seeing a slight horizontal scroll on mobile, specifically my iPhone SE in Safari and Firefox for iOS.
3. I'd like to change the background color of the Survey link to something a little less colorful. Thinking light gray, like #ededf0.

Neither of those block the page launch.

**Comment by vincejoyiv** [comment]
ah, interesting. I'm in the old-fashioned minority with a 320 sized screen :) 

I wonder if it's part of the nav update?

**Comment by ejregithub** [comment]
Noting these in the issue:

Klar Adjust Link: https://app.adjust.com/rtnpf1x
Focus Adjust Link: https://app.adjust.com/oh460vy

**Comment by stephaniehobson** [comment]
YouTube links:

- https://www.youtube.com/watch?v=3NG6dZl9kpA
- https://www.youtube.com/watch?v=rZAQ6vgt8nE
