### ISSUE TITLE
Tie download from this page to aDAU telemetry

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6389]
| Estimates |  |
| ------------- | ------------- | 
| TL |1 |
| PM | 2|
| ENG |1.5|
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] We can follow a user from download on this page over time through to some amount of daily active use

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We don't know if this is possible

**Comment by djst** [comment]
This is candidate for out of scope given other November priorities.

**Comment by ejregithub** [comment]
@djst - thanks for the note - I've removed the In Sprint label (meaning that it won't be pulled into our board to be worked on)
