### ISSUE TITLE
Analytics report - FFFY campaign page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6390]
| Estimates |  |
| ------------- | ------------- | 
| TL |2 |
| PM | 2|
| ENG |0.5|
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Some kind of summary of page performance and conversion rate

**Comment by djst** [comment]
This is candidate for out of scope given other priorities in November.

**Comment by agv123** [comment]
谢谢

**Comment by ejregithub** [comment]
[Analytics dashboard](https://datastudio.google.com/u/0/reporting/1mbFaOsQ2P4WTmy-JuvPP_SMR2mYVQTt3/page/6oCd)
