### ISSUE TITLE
Document trackertest.org dependency

### ISSUE THREAD

**Issue by englehardt** [mozilla/bedrock#6398]
In [Bug 1495671](https://bugzilla.mozilla.org/show_bug.cgi?id=1495671), the tracking protection UI tour page added a specific test page from `trackertest.org`. We should document these dependencies on [that repo](https://github.com/mozilla/trackertest), so we know what might break if we decide to change a test page down the road. I also filed https://github.com/mozilla/trackertest/issues/16.

Note that I'm not the maintainer of `trackertest.org`, so perhaps @fmarier is aware and already has a process for this. Filing this in just in case.

**Comment by alexgibson** [comment]
Thanks for filing this. I was under the impresion that the trackertest repo was set up specifically for the Tracking Protection tour. At least, that was the initial use case. If it is being used for more widely today then yes, it should probably document those clients.

**Comment by alexgibson** [comment]
The content blocking tour was removed in https://github.com/mozilla/bedrock/issues/7424, so mozilla.org is no longer a dependency on this project.
