### ISSUE TITLE
Update newsletter CTA on /technology/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6400]
MVP: 
- make the newsletter sign up field on https://www.mozilla.org/en-US/technology/ point to the email list value 'mozilla-technology'
- replace copy in the newsletter module 
from:
Get the Mozilla newsletter for our latest tech news and more.
to:
Get the Mozilla Labs newsletter for updates on our latest tech and product innovations
------------------
post-MVP:
- replace image the newsletter module with design similar [to this](https://drive.google.com/drive/folders/17__1UBXPcfApV1hurWh9fwMx0IXrRUL0?usp=sharing) that reflects the other creative in the page

**Comment by alexgibson** [comment]
This seems to be the related bugzilla bug for this request: https://bugzilla.mozilla.org/show_bug.cgi?id=1503021

**Comment by alexgibson** [comment]
PR is do not merge until we get an answer to this question here: https://bugzilla.mozilla.org/show_bug.cgi?id=1503021#c4
