### ISSUE TITLE
[Due 11/6] Homepage content updates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6401]
**Due: Tuesday 6th Nov**

Content: https://docs.google.com/spreadsheets/d/1v78ZTvEvIDGcz1xTvNiYBJJShMOg4UESEyAk-g6zAtA/edit#gid=0

Mockup: https://airtable.com/shrVQdWrXYQus2NqT/tblgNmPLbDjXxeViI/viwYLv28cjNOdZMm0?date=2018-11-02&mode=month

**Comment by kellymj** [comment]
**Card 2:**
**New image** [Note, it is 1:1 square so it should take up some of the whitespace]: https://dl.airtable.com/OsJccjR7TVYQCOkACIPv_cheddar_square.png 
**New link [Created an owned-channel blog post for the article]:** https://blog.mozilla.org/internetcitizen/2018/11/05/cheddar-firefox-enhanced-tracking-protection/

**Card 9:** 
**New image:** https://dl.airtable.com/d0HOMxLNTP2CRGaxqFgt_cs-challenge-moz.org.png

**Card 11:** Content change, dropping Spokes
Tag stays the same: Emerging Technologies
**New headline:** Firefox Reality gets recline mode
**New blurb:** Now available for download in the Viveport, Oculus, and Daydream app stores.
**New asset:** Embed YouTube video: https://youtu.be/BcHiFM3m50A
**Fallback image:** https://dl.airtable.com/tpsMSLe6T9ar8IUqFhlo_firefox-reality-recline_16x9.png
