### ISSUE TITLE
Adding a main navigation to /firefox/releases/ and /releasenotes/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6403]
The release overview page has currently no Download button but especially organic search traffic indicates at least interest in Firefox and mostly the latest/current version.
<img width="1779" alt="screen shot 2018-11-05 at 15 32 51" src="https://user-images.githubusercontent.com/36700618/48003916-18681200-e110-11e8-9464-87b15bd6b19b.png">
Right now the page has a conversion rate of 20% and with a download button, this should increase significantly. 

It's interesting, that non-fx and fx user have nearly the same download rate on this page. 

**Key facts**
Sessions per Year: 220k
Downloads per Year: 50k
Downloads per Year non-fx-users: 28k
Downloads per Year fx-users: 22k
75% of users coming from search

**Opportunity**
With a download button or adding the main navigation to this page, download rate should increase at least by 50% to 30%. This would be 20k more downloads per year and a better UX for users coming by search to this page. In a best case scenario we should double the downloads on this page.

**Decition to make**

- [ ] Adding a download button
or
- [ ] Adding the main navigation to /firefox/releases/

**Comment by alexgibson** [comment]
Talked with @rraue on Slack, and we're going to add the new Protocol navigation to both `/firefox/releases/` and `/releasenotes/`
