### ISSUE TITLE
careers.mozilla.org - 'people page' copy revisions to 'How we take care of our people' section

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6445]
Description: The copy in the 'How we take care of our people' section on careers.mozilla.org is out of date and needs to be align with the current verbiage in use.

**Comment by metadave** [comment]
this might be better as an issue in https://github.com/mozmeao/lumbergh

**Comment by ejregithub** [comment]
Agreed, thanks for the correction!
