### ISSUE TITLE
Remove link to interstitial Pocket page in navigation

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6450]
Now that the new nav provides the necessary context to visitors, the interstitial Pocket page is no longer needed.

Success Criteria:
- [ ] Nav link links directly to https://getpocket.com/firefox_learnmore
~- [ ] The template and related assets are removed~
- [ ] The bounce rate on getpocket.com from this traffic source falls somewhere between pre and post interstitial page

**Comment by alexgibson** [comment]
After some discussion on Slack, @rraue would like to keep the page around for a little while to assess it's SEO impact, even though not linked to from the navigation. We may decide to remove it in the future.

**Comment by agv123** [comment]
谢谢
