### ISSUE TITLE
Archive Marketplace Privacy Policy

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6452]
Fix [Bug 1496300](https://bugzilla.mozilla.org/show_bug.cgi?id=1496300)

- [X] Remove link to marketplace from[ about/legal](https://www.mozilla.org/en-US/about/legal/)
- [x] Add link to [archived marketplace terms](https://www.mozilla.org/en-US/privacy/archive/firefox-marketplace/2015-01/) to [archives](https://www.mozilla.org/en-US/privacy/archive/)

**Comment by LordGameleo** [comment]
Is it open? I would like to work on this issue.

**Comment by amychurchwell** [comment]
@LordGameleo No one is assigned so feel free to submit a PR, if you'd like. 😄

**Comment by ejregithub** [comment]
Sorry, this issue is done, just closed in the corresponding Legal bug, but not here. Closing now.
