### ISSUE TITLE
Re-launch pre-download experiment

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6456]
This probably means reverting #6224 so we can run experiment #5944 once again. 

Aim is to launch experiment early next week with a new cohort size and duration that xluo is going to provide details about. 

Success Criteria:
- [ ] page is made available to x% (test parameters TBD) DE locale with [this localized content](https://docs.google.com/document/d/1jcytuc-QMV-onPuE6zpxbU_v2BBmt15cWGC5oRnnHGM/edit#)
- [ ] page is made available to x% (test parameters TBD) FR locale with [this localized content](https://docs.google.com/document/d/1RCWsZLFQzVFVcEXba6SU13CQDn5Q3ucolQaC02dcqRs/edit?ts=5bedee6b)

**Comment by djst** [comment]
Blocked until we know exact duration and size of cohort of A/B/C variants.

**Comment by djst** [comment]
@alexgibson what's an appropriate size for something like this?

**Comment by alexgibson** [comment]
I already plucked this out of git history in a branch ready. Assuming there are no extra changes to the UX or design this time around, i’d say size XS.

**Comment by ejregithub** [comment]
> Blocked until we know exact duration and size of cohort of A/B/C variants.

@djst @alexgibson - Michele indicate that Jascha signed off on 100% EN and 25% in DE & FR.

We can proceed w. EN but need to open the strings to l10n, if you would please @alexgibson 
- DE - the email is localized and ready to go so whenever the strings are ready we can set it live.
- FR - the email is with l10n now. I'll confirm when that's ready so we can proceed here.

**Comment by djst** [comment]
Still blocked on size of cohorts (A/B/C variant allocations). I've asked Daniel and Xuan, will know later today.

**Comment by alexgibson** [comment]
Increasing the size of this task to S (a full days work), given the l10n ask.

**Comment by djst** [comment]
Let's figure out who can do the actual l10n task here - wondering if we can handle that internally with paid staff given the nature of the experiment. @ejregithub do you know who we typically pull in for tasks like that?

**Comment by alexgibson** [comment]
Ok, I did some testing and locale specific-templates work with our multivariant testing helper, so I think hard-coded templates for German and French should work fine here. I'll put together a doc today with the strings we need translating and share here.

**Comment by alexgibson** [comment]
We also need to open up the following privacy page for translation through our regular l10n process: https://www.mozilla.org/en-US/privacy/email/

Currently, the page is available in english only.

**Comment by alexgibson** [comment]
@djst @ejregithub I put the strings required for translation in this google doc:

https://docs.google.com/document/d/1jcytuc-QMV-onPuE6zpxbU_v2BBmt15cWGC5oRnnHGM/edit?usp=sharing

We'll need translation of the copy here, in addition to the page I linked in https://github.com/mozilla/bedrock/issues/6456#issuecomment-438969205 (this page can be done through our regular l10n process).

**Comment by djst** [comment]
Update - this is the info we need to re-launch the en-US experiment right away (more info on de/fr later): 

EN-US expansion
To confirm our preliminary results we'll be upping the a priori confidence requirements from 90%ish to 99%. This will mean that each variant is required to create at least 15,152 clients (~24,000 downloads). To build this sample in short order we recommend splitting Moz.org traffic across the three versions at a ratio of 0.33/0.33/0.33. We estimate that this volume of traffic should take approximately 1 week to accumulate.

**Comment by ejregithub** [comment]
@alexgibson - please find the links to the DE and FR localized content for this page in the description, above.

@peiying2 @flodolo - in order to move forward with the test in DE and FR we need this page localized, please: https://www.mozilla.org/en-US/privacy/email/

**Comment by alexgibson** [comment]
Ok, https://github.com/mozilla/bedrock/pull/6457 is now updated with the following conditions:

- Test expands to all `en` locales.
- Three cohort sizes increase to `33%` each.

We can tackle adding in `de` and `fr` once the `en` experiment gets back out the door.

**Comment by alexgibson** [comment]
Reopening this as we still need to tackle `de` and `fr`.

**Comment by alexgibson** [comment]
PR #6496 adds the same experiment for German and French locales at ~25% of traffic (8% per cohort).

German demo links:

- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/?v=a
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/?v=b
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/?v=c

French demo links:

- https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/?v=a
- https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/?v=b
- https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/?v=c

This work is now blocked on localization of the `/privacy/email/` page.

**Comment by djst** [comment]
@ejregithub let's figure out a plan B for l10n if this keeps blocking us this week.

**Comment by djst** [comment]
@alexgibson are we using the same UTM parameters for this re-run?

**Comment by alexgibson** [comment]
> @alexgibson are we using the same UTM parameters for this re-run?

Yes, everything is identical

**Comment by alexgibson** [comment]
@ejregithub any update here on the l10n status? I'm on PTO on Friday, so if we're to do this before all-hands I would like to get this merged and started today if possible.

**Comment by alexgibson** [comment]
We now have a solution for translating the /privacy/email/ page, this is now unblocked.
