### ISSUE TITLE
/firefox internal linking

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6458]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

/firefox/ currently is not as informative as it could and should be. This is a proposal to use the page in a better way as a internal linkhub to reduce orphaned pages, especially feature pages no user can reach via our navigation. I expect these pages to have afterwards a better chance to rank in search engines for important keywords around our browser.

- What’s new? -> /firefox/releases/
- Switch from Chrome to Firefox in just a few minutes -> /firefox/switch/
- Private Browsing -> /firefox/features/private-browsing/
- Firefox Quantum features -> /firefox/features/
- Screenshots -> screenshots.firefox.com
- Pocket -> /firefox/pocket/
- Gaming -> https://games.mozilla.org
- VR -> https://mixedreality.mozilla.org
- Extensions -> https://addons.mozilla.org/firefox/extensions/
- Themes -> https://addons.mozilla.org/firefox/themes/
- Toolbar -> https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars
- Sync your devices -> /firefox/accounts/
- Browse for good -> /about/
- The new Firefox -> /firefox/new/

I want to link the page https://www.mozilla.org/en-US/technology/what-is-a-browser from /firefox/ as well, but right now "browser" is only used once as a linktext on the page. But thats something for a copy update. Firefox is a browser, we should use the keyword browser to describe it.
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] the page is updated to be an internal linkhub to reduce orphaned pages, especially feature pages no user can reach via our navigation. 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Needs to be monitored to not lower conversion rate on /firefox/

Tasks
- [ ] Obtain UX approval for proposed links
- [ ] Design for linked headlines on /firefox/

**Comment by ejregithub** [comment]
@rraue - please note that this has been pulled into the Websites Durable Team Backlog for consideration to be included in an upcoming sprint after @djst has prioritized it (this will happen over time as a we populate the backlog).

**Comment by hoosteeno** [comment]
@stephaniehobson would you consider this in scope for NA-Brand? Maybe you want it on your board?

**Comment by rraue** [comment]
I think, if this is not much dev-work, we should consider doing this even on the existing page, as it could be month of work to find a completely new strategy for /firefox/.

**Comment by stephaniehobson** [comment]
It's not much dev work to add links.

What do we think of adding as an A/B test initially so we can do before/after analysis. Or am I making it more complicated than it needs to be?

**Comment by rraue** [comment]
@stephaniehobson I would just test on bouncerate and pages/session metrics for the page as a landing page to see if anything shifts. I do not expect that, but I do expect crawlers to understand our site architecture better, what doesnt directly increases traffic/conversions but enables us to do such experiments like on /all/.
