### ISSUE TITLE
Bad ranking for "Mozilla" in some countries

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6462]
### Problem:
In Venezuela and some other Spanish speaking countries we are ranking for "Mozilla" and "Descargar Mozilla" behind some download pages on No. 3 and therefore we are losing firefox downloads to the darkfunnel. And we definitely should rank for our main brands, especially because in some parts of the world "Mozilla" is a bigger or equally big brand than "Firefox".
<img width="1779" alt="screen shot 2018-11-12 at 15 08 37" src="https://user-images.githubusercontent.com/36700618/48352380-da796980-e68c-11e8-8246-a8913a3ba886.png">

### Opportunity:
In Venezuela alone the keyword volume for "mozilla" is 60k monthly. www is getting around 10k clicks in Venezuela with a in serp ctr of 25%, normal would be around 70% ctr. So alone for "mozilla" there is a opportunity of 20-40k more clicks a month. "Descargar Mozilla" is even more specific and has a keyword volume of 25k and us getting just 2k clicks per month. 

Opportunity for monthly more dektop Downloads: **30-60k**

### Risk
Changing anything on /new is always a risk, so we need to monitor closely ctr, rankings and clicks from Search for all locales.

But Google is adding the intended solution (adding " — Mozilla" as suffix) by itself, so I do not expect any other change than the positiv expected in Venezuela and other Spanish speaking countries.
<img width="804" alt="screen shot 2018-11-12 at 15 48 58" src="https://user-images.githubusercontent.com/36700618/48354662-870a1a00-e692-11e8-9c29-5ccfeae2d5ac.png">

### Solution:

Adding " — Mozilla" as suffix to /new

**Comment by alexgibson** [comment]
Reopening until we can confirm the implementation works

**Comment by rraue** [comment]
We can close this as I checked now after 28 days and the change did no harm. Didn't help in the way I hoped either but helped a bit, ctr and rankings got better in Venezuela, just not as I have hoped. I need to analyse deeper, why we lost rankings. 

We should keep the suffix, as it helped a bit and didn't cause any decline.
