### ISSUE TITLE
SEM landing pages - IE - 4 vars

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6466]
https://bugzilla.mozilla.org/show_bug.cgi?id=1506301

Description:  Requesting 4 new pages, using the existing templates from the other SEM competitor landing pages (Safari, Opera, Chrome . . .)

For Traffic Cop:
v=a is the control, a copy of the canonical /firefox/new page

/?xv=internetexplorer&v=a

v=1 and v=2 use this layout template: /firefox/new/?xv=opera&v=1

/?xv=internetexplorer&v=1 
/?xv=internetexplorer&v=2

v=3 and v=4 use this layout template: /firefox/new/?xv=opera&v=2

/?xv=internetexplorer&v=3
/?xv=internetexplorer&v=4

Follow previous form and create a fork of /new (as with the other competitor landing page tests) so Kirby can have Fetch redirect our Internet Explorer ads in EN to http://mozilla.org/firefox/new/?xv=internetexplorer.

The copy and the information for the comparison chart are in [this document](https://docs.google.com/document/d/10jKPXbHmh7PUkId9xt4jT5QxpuPD71hCRj7HKD21dG0/edit?usp=sharing), all of which is final and has been approved by Legal.

**Comment by ejregithub** [comment]
@alexgibson - please review this in your day tomorrow and respond with any questions. It's probably best to do so in [the bug and set a needinfo](https://bugzilla.mozilla.org/show_bug.cgi?id=1506301) for Kirby as she's not in this project on github (yet!) to flag here.

**Comment by agv123** [comment]
谢谢
