### ISSUE TITLE
Redirects for /foundation

### ISSUE THREAD

**Issue by cadecairos** [mozilla/bedrock#6467]
We're ready to redirect traffic away from `/foundation` to the new foundation.mozilla.org site.

Currently we've got approvals for the following redirects (as per [this spreadsheet shared](https://docs.google.com/spreadsheets/d/1VFha8fSY0gMqwO9KLT8nWRhVwQqm4ehPJfoHTGnTQ_U/) with me)

https://www.mozilla.org/foundation/ -> https://foundation.mozilla.org/
https://www.mozilla.org/foundation/about/ -> https://foundation.mozilla.org/about/
https://www.mozilla.org/foundation/documents/ -> https://foundation.mozilla.org/about/public-records/
https://www.mozilla.org/foundation/issues/ -> https://foundation.mozilla.org/initiatives/
https://www.mozilla.org/foundation/leadership-network/ -> https://foundation.mozilla.org/
https://www.mozilla.org/foundation/advocacy/ -> https://foundation.mozilla.org/

We do not yet have a go-ahead for this redirect.
https://www.mozilla.org/foundation/licensing/

**Comment by cadecairos** [comment]
Hi @ejregithub, thanks for sharing that info, I'll take it back to the rest of the team and get back to you here on when we'd like to proceed.

**Comment by alanmoo** [comment]
@ejregithub Are you talking about the horizontal scrolling that we had (which has since been fixed- content issue) and the image crop?

**Comment by alexgibson** [comment]
Re-opening until we clean up the old templates.

**Comment by jessevondoom** [comment]
Just popping in to note that the image cropping issues were fixed with a content change. We should be ready on the foundation.moz.org side now.

**Comment by cadecairos** [comment]
I'll open a PR to clean up those templates. I might need some direction as to where exactly I should be removing content.

**Comment by cadecairos** [comment]
Oh, @alexgibson have you started on this already?

**Comment by alexgibson** [comment]
> Oh, @alexgibson have you started on this already?

Yep, already taken care of, thanks for the offer still 👋

**Comment by cadecairos** [comment]
great, thank you very much!

**Comment by stephaniehobson** [comment]
Fixed by #6493
