### ISSUE TITLE
Indonesian What's New Page for Firefox Lite -update content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6472]
https://bugzilla.mozilla.org/show_bug.cgi?id=1504954

Description: 
Update content in the Indonesian What's New Page (for Firefox Lite), adding the send-to-device widget using the new bucket ID  'download-firefox-rocket'. See [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1495393) for questions about the basket ID

[Page creative assets](https://drive.google.com/drive/folders/1laQfg5diCIQZgEVmzxEqIZDSvTeLVCW2?usp=sharing )

**Comment by ejregithub** [comment]
@alexgibson - could you please take a look and apply size estimations for this request?  @djst - could you please also assess for priority, indicating if Alex can take this on next or if other work in the [backlog](https://github.com/orgs/mozilla/projects/45) takes precedence?

**Comment by djst** [comment]
Not sure I have enough info to assess priority of this one. Is there a deadline? Also, the current backlog is messy with some things tagged In Sprint and other things not tagged. Can we go through this together to make sure we're on the same page?

**Comment by alexgibson** [comment]
> @alexgibson - could you please take a look and apply size estimations for this request?

The coding work here would probably be a `Size: S` (a day's work), but seeing as this is a new basket ID that needs testing and QA, I'd add an extra 1/2 day, so `Size: M`.

**Comment by ejregithub** [comment]
@djst - there's no deadline but it's important that it get done as the send-to-device widget is proven to perform better than QR codes.

**Comment by djst** [comment]
So it's just one of multiple download options that's broken for a small market? Sounds like it's low priority then. No need to squeeze into this sprint.
