### ISSUE TITLE
Redirect /pocket to getpocket.com

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#6475]
/pocket currently redirects to firefox/pocket/. The pocket navigation link was recently updated to getpocket.com and firefox/pocket/ is no longer active.

**Comment by ejregithub** [comment]
@amychurchwell  - was this frame as P1 or P2?

**Comment by stephaniehobson** [comment]
@rraue do you have thoughts on changing the redirect? I know you wanted to keep /firefox/pocket/ around for a while.

**Comment by amychurchwell** [comment]
@ejregithub I was thinking lower priority, P2

**Comment by rraue** [comment]
As long we keep the page around, we need this redirect not changed as well.
