### ISSUE TITLE
[Go live 11/27] State of Mozilla 2017

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6478]
| Estimates |  |
| ------------- | ------------- | 
| TL | 0 |
| PM | 2 |
| ENG | 8 |
| SEO | 0 |
| ANA | 0 |
| DES | |
| COPY | 0 |

Description: Create new State of Mozilla page for 2017 following format of previous years (URL structure and content layout). 

Deliverables for requestor (Erica):

Content for:
- https://www.mozilla.org/en-US/foundation/annualreport/2017/

Additional content items:
- 2017 Audited financial statement (PDF)
- 2017 Form 990 (PDF)
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Code is in the bedrock private repo prior to launch 
- [ ] Content is final, approved and provided to ENG by EOD 21st Nov. 
- [ ] Must be stakeholder approved (QA of coded page)
- [ ] Is live on, not before, 11/27

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

**Comment by djst** [comment]
Requests for updates on copy/layout: https://docs.google.com/document/d/1mOHvS5Ydrq4XP4sHW98tqt2zJNu5Ea9hbRSbRUDDAGc/edit
