### ISSUE TITLE
[On 12/27/2018] 2018 H1 Transparency Report

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6479]
Description: Add 2018/H1 Transparency report to mozilla.org with [this content](https://docs.google.com/document/d/1inLs0TpZHt2kfmaU3ODlhRWCybLl4_HhrARel5xv5W4/edit)

Success Criteria:
- [ ] Go live on 12/27/18 - put it behind a switch to facilitate this.

**Comment by ejregithub** [comment]
Today I pinged Mika with the link to the demo in email asking for stakeholder review

**Comment by stephaniehobson** [comment]
Blocked by sign off from legal team.

**Comment by ejregithub** [comment]
@amychurchwell - please note updates from the stakeholder.  Also, note that this needs to go live in the last week of the year and not before.

**Comment by ejregithub** [comment]
Mika has approved the latest updates, this is now stakeholder QA approved.

@amychurchwell @craigcook - Go live is now 12/27 - let's target flipping the switch at 9 am so it's live before noon.  ;)
