### ISSUE TITLE
Automate image compression as part of asset pipeline.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6480]
Image compression is a time consuming but easily automatable step in the development process.

Tinypng has a developer API and can do both PNG and JPEGs.
SVGO is available as a npm package.

**Comment by amychurchwell** [comment]
[@alexgibson @craigcook @stephaniehobson]
 
The Tinypng developer API has a price associated per image: https://tinypng.com/developers but there are potential other options if that is a blocker.

[SVGO ](https://github.com/svg/svgo) has quite a few formats, including [gulp](https://github.com/sindresorhus/grunt-svgmin). We could potentially write a gulp task for this & watch img directory for changes. Thoughts?

**Comment by alexgibson** [comment]
I think SVGO is a great tool to handle svg files, and a gulp task makes the most sense 👍 

Tinypng is probably my favorite lossy image compression tool (in terms of results). For non-lossy compression there's also ImageOptim (which also has a [gulp plugin](https://github.com/allbitsnbytes/gulp-imageoptim)).

If we're to invest in automation this year, I think it's likely there will be some costs associated with that investment, so perhaps this is something to talk to Justin about? Personally I don't find ImageOptim on its own to be enough, so it would be nice to have something like TinyPng if we're to really streamline our workflow.

**Comment by alexgibson** [comment]
There's a new `Imagemin` lib out that may be worth investigating here? https://web.dev/fast/use-imagemin-to-compress-images

It looks like it handles, jpg/png compression, svg optimization and also webp. There's a gulp plugin available too.

**Comment by amychurchwell** [comment]
@alexgibson It is looking like imagemin has it's own plugins for png/svg/etc. For both `imagemin-pngquant` and `imagemin-mozjpeg` have a quality field to determine compression level.
(EX: `[pngquant({quality: [0.5, 0.5]})]`, this example forces compression to be at 50%)
Do you know if there a way to best determine what this range should be?

**Comment by alexgibson** [comment]
Done in https://github.com/mozilla/bedrock/pull/7243
