### ISSUE TITLE
Additional icon partly displaying on https://www.mozilla.org/en-US/firefox/mobile/#focus-privacy

### ISSUE THREAD

**Issue by scheinercc** [mozilla/bedrock#6484]
- URL: https://www.mozilla.org/en-US/firefox/mobile/#focus-privacy
- Firefox 65.0a1 (2018-11-16) on macOS
- Checked that no zooming had occurred

---
Within the icon's frame next to " Automatically blocks ads that have sneaky hidden trackers that collect data. " the icon above from the icon spritesheet is showing - the little blue arrow above the "blocking" icon.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/817856/48669412-3d20a880-eb58-11e8-9a72-d5ba443fc7ee.png">

Here a screen of the CSS rule and selector(s), the sprite-sheet and the CSS file in question:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/817856/48669425-8d980600-eb58-11e8-8c74-01fa4f9cadb5.png">

**Comment by Shivansh2407** [comment]
This is a Issue in the image file /media/img/firefox/mobile/icon-sprite.e7269a8abcf8.svg mentioned in the code.The image file contains the blue arrow.
Change the image file to fix the issue.

**Comment by scheinercc** [comment]
@Shivansh2407 that could be correct. It needs someone to make and push the change and also know about the implications about where the blue arrow might be used as well, to adjust any background positioning etc. accordingly. 
Alternatively it might be better to change 
```
li.feature-block::before {
  background-position: left top -4px;
}
```
to

```
li.feature-block::before {
  background-position: left top -10px;
}
```
but again, this might change other elements as well and maybe breaks something.

Go ahead and give it a crack ;)

**Comment by Shivansh2407** [comment]
Please assign this issue to me and also let me know which file has this issue because I have been browsing various files and did not find this li.feature-block....Thanks in advance

**Comment by scheinercc** [comment]
Hey @Shivansh2407, I am not part of the project, but I don't think you need to be assigned. You just fork the project, make a change and submit a pull request where you set a link to this issue within the commit message (you should be able to find out how to do that by search for "Github link issue in commit message" or something).
I quickly had a look at the files and found this:
https://github.com/mozilla/bedrock/blob/20c9f5afb70c134c9455d72472826e7a0f4e87f2/media/css/firefox/mobile.scss#L717-L719
The selector from this code would be `.feature li.feature-block:before`, so not quite the same, but it might still be it!? Hope that helps you to get started.
Maybe @alexgibson can help you out more.

**Comment by Shivansh2407** [comment]
I have created a pull request regarding the issue . Please review it and let me know .
