### ISSUE TITLE
[11/29] New www.mozilla.org homepage banner to support FFFY

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6490]
Description: FMB is requesting a new banner (‘the’ homepage banner)

Success Criteria:
- [ ] James Dybvig has produce the file and provided it to us no later than EOD 11/26
- [ ] the provided file is a still image (not animation)
- [ ] Must be live before All Hands (target 11/29, 11/30 would be acceptable)

Risks:
- [ ] meh

**Comment by kellymj** [comment]
New copy for the banner:
**Your live is your business. Not ours.**
Firefox fights for you.

Dreadful mockup here, just to show you possible placement:  https://dl.airtable.com/p6QxSg1DRnOO4aRwwx7G_full_ffy-mock.jpg

James is creating the design and will deliver the color specs.

**Comment by stephaniehobson** [comment]
`Your *life` according to the mockup, which makes more grammatical sense and is probably what was intended.

**Comment by kellymj** [comment]
Yes, quite right. Thanks for catching that @stephaniehobson .

**Comment by stephaniehobson** [comment]
Here's the image for the banner:

![homepage image-11 27-2](https://user-images.githubusercontent.com/854701/49115418-9c18a880-f24f-11e8-8aaf-1f56ff643081.jpg)
