### ISSUE TITLE
[11/29] New www.mozilla.org homepage editorial content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6491]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | |
| ENG | 8 |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: new homepage editorial content updates for Dec/18 (regular monthly cadence)
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New content is provided by MJ on 11/20
- [ ] New content is live on 11/29 (11/30 would be okay, but preference is to stick with the 'no Friday pushes' best practice).

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The usual

Tasks:
- [ ] code
- [ ] internal team QA
- [ ] manage stakeholder QA
- [ ] review code

**Comment by kellymj** [comment]
Here is the content: https://docs.google.com/spreadsheets/d/1a6K6nLnnQLHw93KSB_WwE4DYaqnubLsL6xOcyVs7CWk/edit#gid=637696574

Some caveats:
1. FFY video will go into the card 1 position once it is on YouTube.
2. We are in limbo on the Live Nation content in card 2. If we get an artist booked by our go-live date, we'll have a visual to place there. If we do not, I will provide back up content.
3. Looks like the wordmark is not used correctly in the "privacy not included" visual for card 4. Waiting to hear if that will be updated.

I'm on PTO, returning next Wednesday. I will check in from time to time on London time (waves). Chelsea Novak is my backup if you have questions. She's Canadian, so she's not on holiday. She's also a nice person. I'm not sure if she has a github account.

**Comment by kellymj** [comment]
@alexgibson See above.

**Comment by chelseanovak** [comment]
> I'm on PTO, returning next Wednesday. I will check in from time to time on London time (waves). Chelsea Novak is my backup if you have questions. She's Canadian, so she's not on holiday. She's also a nice person. I'm not sure if she has a github account.

I do! So I'm here to get what you need Alex.

**Comment by alexgibson** [comment]
@chelseanovak @kellymj WIP demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/

Any further amends just let me know.

Please note: for the FFYR video we'll still need a placeholder graphic for before people click to open the modal / play the video.

**Comment by chelseanovak** [comment]
Here is the URL for card 9: https://blog.mozilla.org/firefox/6-tips-for-safe-online-shopping/

Do you need me to fetch the UTM parameters for it as well? Let me know if you need it added anywhere else. 

The rest of it looks to match what's in air table. The only thing I noticed was that the background on the Download Firefox space at the bottom of the page is grey instead of blue. Not sure if that's important, but just noting it. 

Hopefully we'll have the FFY video, placeholder graphic and the Live Nation graphic/URL on Monday. If Live Nation doesn't come together in time, I will provide a link to a high performing press hit as a replacement. 

Thanks!

**Comment by alexgibson** [comment]
> Here is the URL for card 9: https://blog.mozilla.org/firefox/6-tips-for-safe-online-shopping/

Perfect, thanks!

> Do you need me to fetch the UTM parameters for it as well? Let me know if you need it added anywhere else.

Not to worry, I can add these to match what we use for other card links.

> The rest of it looks to match what's in air table. The only thing I noticed was that the background on the Download Firefox space at the bottom of the page is grey instead of blue. Not sure if that's important, but just noting it.

I think the airtable mockup is based on a slightly older version of the page, so it's a little out of date compared to how that section looks today.

> Hopefully we'll have the FFY video, placeholder graphic and the Live Nation graphic/URL on Monday. If Live Nation doesn't come together in time, I will provide a link to a high performing press hit as a replacement.

Got it, thanks!

**Comment by chelseanovak** [comment]
Hey Alex, here is the YouTube Video for the home page: https://www.youtube.com/watch?v=rZAQ6vgt8nE&feature=youtu.be

and the embed code: 
<iframe width="560" height="315" src="https://www.youtube.com/embed/rZAQ6vgt8nE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Do you need a still pulled for it?

**Comment by alexgibson** [comment]
Thanks @chelseanovak - I'll update the homepage card to open the video.

I think the two things we're missing are:

- A video placeholder image for the FFY video (card 1)
- Final content for card 2 (currently the Firefox concerts promo).

Aside from these two things, I think we're pretty much complete.

**Comment by chelseanovak** [comment]
Yes! I am waiting for a video placeholder image from James and comms is getting clearance for a press hit that we will be using as the concert promo isn't ready to launch yes. Crossing fingers and toes we get them today. Thanks!

**Comment by kellymj** [comment]
@alexgibson @ejregithub 

We will have a concert promo by Friday. Can we hold off on going live until we have that? Alternatively, I can supply something to you on Thursday, but we'll have to update the card when we have the artist image.

**Comment by kellymj** [comment]
@alexgibson Let's mock this up for Card 2:
[IMAGE] https://drive.google.com/open?id=19nyqcS4n3CR2_Yi694-udvmiEdz15WRj
[TAG] Firefox Concert Series
[HEADLINE] Here's to you. Here's to the internet.
[BODY] Here's to watching it for free, from all kinds of artists, right from Firefox. Sign up and rock out!
[LINK] https://www.mozilla.org/firefox/concerts/?utm_source=mozilla.org&utm_campaign=livenation-promotion&utm_medium=referral&utm_content=homepage

**Comment by alexgibson** [comment]
> [LINK] https://www.mozilla.org/firefox/concerts/?utm_source=mozilla.org&utm_campaign=livenation-promotion&utm_medium=referral&utm_content=homepage

Note: I'm not going to include the UTM params for an internal link. Adding utm params to internal links creates a new session in Google Analytics, which skews our data. We can already track where a person navigates from within our own site without these.

**Comment by alexgibson** [comment]
> [IMAGE] https://drive.google.com/open?id=19nyqcS4n3CR2_Yi694-udvmiEdz15WRj

@kellymj this image is too small. I need at minimum 450 x 450 px.

**Comment by alexgibson** [comment]
> We will have a concert promo by Friday. Can we hold off on going live until we have that? Alternatively, I can supply something to you on Thursday, but we'll have to update the card when we have the artist image.

We can hold off and merge this together with the concerts page on Friday, but that's the last possible cut off date until after all-hands.

**Comment by kellymj** [comment]
> > [LINK] https://www.mozilla.org/firefox/concerts/?utm_source=mozilla.org&utm_campaign=livenation-promotion&utm_medium=referral&utm_content=homepage
> 
> Note: I'm not going to include the UTM params for an internal link. Adding utm params to internal links creates a new session in Google Analytics, which skews our data. We can already track where a person navigates from within our own site without these.

I'm using a link builder that @hoosteeno set up specifically for the concert series: https://docs.google.com/spreadsheets/d/1VzSbNN7nt4tKuTAW0EwP1YMOJsItjuyATeECnwNP76Q/edit#gid=0. Is the issue that it's internal links? Curious how that skews data.

**Comment by hoosteeno** [comment]
> I'm using a link builder that @hoosteeno set up specifically for the concert series: https://docs.google.com/spreadsheets/d/1VzSbNN7nt4tKuTAW0EwP1YMOJsItjuyATeECnwNP76Q/edit#gid=0. Is the issue that it's internal links? Curious how that skews data.

@kellymj When a page request has utm parameters in the URL, Google Analytics starts a new session. If a same-site link has utm parameters in it, the session clicking the link won't be the same session getting the page at that URL. It can really confound measurement and with a few exceptions (stub attribution) it's not necessary. Sorry for any confusion, and thanks for catching it @alexgibson.

**Comment by kellymj** [comment]
@alexgibson Lots of activity today, and with that came some updates. 

New image of the artist: https://dl.airtable.com/yYnnU5zDQwKJRIWAd0mG_full_Square_fossy.png

Revised copy: 
[TAG] Firefox Concert Series | Phosphorescent
[SAME HEADLINE] Here’s to you. Here’s to the internet.
[BODY] Here’s to watching it free, from all kinds of artists, right from Firefox. Rock out with Phosphorescent, LIVE on Dec. 11.

Note: We are sending this to the artist for approval tomorrow along with all the assets. We can't push this or the concert page until we have the green light.
