### ISSUE TITLE
We should not tell ESR users their browser is out of date

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6495]
Our "Your browser is out of date" banner pops up in Firefox 60, which is ESR.

Discovered because someone in my office has `privacy.resistFingerprinting` enabled and Firefox self identifies as ESR in that case as well.

**Comment by alexgibson** [comment]
I downloaded ESR 60 and I didn't see the out-of-date notification when visiting mozorg. Looking at the code, we do seem to check that the visitor is on release channel: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-notification-banner-init.js#L47

Was this person using ESR, or we're they on release channel with `privacy.resistFingerprinting` set to `true`? If it was the latter, I would expect the notification to display as that setting alters the userAgent string. This then becomes a bug about UA sniffing reliability in general :)

**Comment by stephaniehobson** [comment]
> were they on release channel with `privacy.resistFingerprinting` set to `true`

That was the case. I think I will just close the issue because I'm not sure it's actionable if ESR is being notified correctly.
