### ISSUE TITLE
Localize new navigation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6498]
Once we remove the legacy global nav from bedrock, we should be ready to start localizing the new navigation so we can roll out to all locales.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/6377

**Comment by alexgibson** [comment]
Probably also depends on https://github.com/mozilla/bedrock/issues/6471

**Comment by djst** [comment]
Would love to see this prioritized. Candidate for next sprint.

**Comment by hoosteeno** [comment]
Is this ready for review? Is someone reviewing it?

**Comment by alexgibson** [comment]
> Is this ready for review? Is someone reviewing it?

This has been ready for review for a while now, but we can't merge it yet as we have to wait on l10n. @craigcook is assigned for review, but I don't know how far he is with it yet. It's a very large review.
