### ISSUE TITLE
[Nov 28 - EOD] Update to Community Participation Guidelines

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6500]
https://bugzilla.mozilla.org/show_bug.cgi?id=1506402

Description:  Updates are required to the Community Participation Guidelines on mozilla.org

Tasks:
- [x] [Copy updates](https://docs.google.com/document/d/1bTXt5tArulXw0DZjE0bqJ2s-U23bEjx7cg3Bk3UzxUo/edit#)
- [x] Add a new page 'How to Report'
- [x] update internal staff harassment policy link to: https://mana.mozilla.org/wiki/display/PR/Open+Door+Policy

**Comment by peiying2** [comment]
This page has been localized in a few languages. When the PR is ready, please add an L10n label.

**Comment by craigcook** [comment]
This is live in production

https://www.mozilla.org/about/governance/policies/participation/
https://www.mozilla.org/about/governance/policies/participation/reporting/
