### ISSUE TITLE
Download button doesn't say download on Android or iOS

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6509]
The download button macro produces buttons that say "Firefox for Android" and "Firefox for iOS" without any verb. 

The buttons should include a verb. "Download Firefox for Android" or "Install Firefox for Android" not sure which is better.

**Comment by aman-earthian** [comment]
hey @stephaniehobson , so should the macros be changed or a dialogue box be added which shows up when someone hover on the macros.

**Comment by stephaniehobson** [comment]
This issue probably needs a UX designer to weigh in so I don't think it's ready to be worked on.

**Comment by robhudson** [comment]
The buttons currently say "Get it on Google Play" or "Download it on the App Store" which both include the verb. Closing.
