### ISSUE TITLE
Create functional tests for new navigation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6517]
Now that we've removed the legacy navigation from bedrock we should create new functional tests to make sure the Protocol navigation continues to work as expected.

**Comment by alexgibson** [comment]
This is being handled in https://github.com/mozilla/bedrock/pull/6642

**Comment by ejregithub** [comment]
@alexgibson - this is in the Review column.  Shall we tag it with 'Needs Review' and find another dev to take it on when they complete current tasks?

**Comment by alexgibson** [comment]
@ejregithub as per https://github.com/mozilla/bedrock/issues/6517#issuecomment-451892389, this is being reviewed as part of the navigation l10n PR. Craig is already assigned.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/issues/6498
