### ISSUE TITLE
Update Navigation card under About to something more relevant

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6518]
The current nav card on the About megamenu shows a blurb about the Mozilla Festival, which is a month old now. Let's update this to something relevant - may I propose the EOY fundraising campaign?

![image](https://user-images.githubusercontent.com/5638050/49082618-805ed380-f24a-11e8-83de-301a0413cc4b.png)

**Comment by alexgibson** [comment]
I think this is a duplicate of https://github.com/mozilla/bedrock/issues/6471
