### ISSUE TITLE
Firefox has auto play blocking now

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6536]
It is on by default in Release.

We should update the SEM comparison pages with its newly supported status.

**Tasks**
- [ ]  Update the table row for 'Autoplay blocking' to have a lovely green check mark under the Firefox column on https://www.mozilla.org/en-US/firefox/new/?xv=edge
- [ ]  Update the table row for 'Autoplay blocking' to have a lovely green check mark under the Firefox column on https://www.mozilla.org/en-US/firefox/new/?xv=safari

**Comment by stephaniehobson** [comment]
@ejregithub Do you know who we can consult about this? I think all our SEM pages are out of date.

**Comment by stephaniehobson** [comment]
Okay now I'm SURE the SEM pages are out of date. @ejregithub can you get this on the board?

I think these are the two relevant pages:
https://www.mozilla.org/en-US/firefox/new/?xv=edge
https://www.mozilla.org/en-US/firefox/new/?xv=safari

**Comment by ejregithub** [comment]
Tagged in the new sprint milestone starting on Monday.
