### ISSUE TITLE
Remove content from www.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6552]
These pages should no longer be shown, the content and URLs retired/made inaccessible via the web.

https://www.mozilla.org/de/firefox/new/?xv=reggiewatts
https://www.mozilla.org/en-US/firefox/new/?xv=reggiewatts

https://www.mozilla.org/de/firefox/new/?xv=waitface
https://www.mozilla.org/en-US/firefox/new/?xv=waitface

**Comment by stephaniehobson** [comment]
Closed by #6576
