### ISSUE TITLE
[aDAU Experiment] Download/sign-up interstitial

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6562]
We would like to test how the download prompt interacts with the download experience:

4 proposed variations:
- current modal "experiment" acts as control
- modal on /firefox that automatically starts download
- mimic the design of the modal on the /thanks page with download starting automatically
- mimic the design of the modal on the /thanks page and hold download until form is filled out/declined

**Comment by djst** [comment]
(Note: we may decide to move this out to a dedicated Download Rate Optimization furrable team board.)

**Comment by alexgibson** [comment]
This has been superseded by https://github.com/mozilla/bedrock/issues/6950
