### ISSUE TITLE
Update copy in home page fundraising banner

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6580]
[Requested in a comment on the original issue](https://github.com/mozilla/bedrock/pull/6501#issuecomment-446193737) but filing a new issue for ease of tracking.

The new blurb:

> The future of the internet is at stake, with new threats to our online privacy and security virtually every day. The not-for-profit Mozilla Foundation fights to save a healthy internet, with projects like our *Privacy Not Included buyer's guide. Your donations make this work possible, so please chip in today.

This will be for English only, using a conditional to avoid breaking strings for other locales.

**Comment by claychaffin** [comment]
I'm working with Craig on new body copy for this
