### ISSUE TITLE
Change nav of /channel/x

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6581]
All /channel/ locale pages have a custom navigation. The English versions already have the new navigation. As the custom nav on locales currently has no download button, we should kill this custom build and give all locales the standard fallback navigation of the new nav, as this includes a download button.

Why should we do it: in mostly less translated and smaler locales especially the /channel/desktop/ is a landingpage for search traffic not just with the intend to download beta, nightly or dev-build, so it would help these users to get the normal firefox and will most likely not distract users searching especially for beta, nightly and dev-build, as the numbers on en-US with the new nav and not the custom build indicate.

Only worth doing it if feasable. The most important locale right now is /vi/ where it's currently the main download page as we do not have /new/ in this locale (will be fixed). So will these rather small locales get the new nav or will they get the fallback?

Applying this now would get us especially in Vietnam directly less confused users and more downloads (better ctr).

**Comment by rraue** [comment]
Interested in your thoughts @craigcook and @alexgibson. Applying the new nav to this pageset not just on en-US would have to be done anyways when we localize the new nav, right? If we do it now, we would directly see an improvement, as the fallback nav is already an improvement to the custom build right now. And once the new nav is set for the locales, the fallback is not needed anymore and the new one will show up, is that correct?

**Comment by stephaniehobson** [comment]
The download button on these pages is complicated. What would someone on the Firefox for Android page expect the download button to download? What about the desktop page that lists Beta, DevEd, and Nightly?

In both cases it will download Release Firefox Desktop. On other similar pages (https://www.mozilla.org/en-US/firefox/mobile/) we have removed the download button to solve this confusion.

**Comment by rraue** [comment]
@stephaniehobson I completely get your objection, so I looked into GA to find out if this is a real harm.

In my understanding, there is no download button on mobile anyways and on desktop above the screen is enough information to not confuse this. We have a download button on /en-US/firefox/channel/android/ as well, as it has the new nav and only 1.5% of conversions on this page are desktop-downloads, so it seems users get it.

Seems like an exception, we can remove.

**Comment by alexgibson** [comment]
My gut here says we should be spending time localizing the new navigation, as opposed to adding already deprecated HTML & CSS to this page. If we did this then by the time search engines pick up the change, we may nearly be ready with the new localized navigation anyway.

I think @stephaniehobson does also have a good point here re: the UX of the button in the nav. It may not get many clicks, but GA doesn't really tell us what product people are expecting when they click it. At least the pre-release sections make it very clear what someone is getting when they read it.

**Comment by alexgibson** [comment]
Closing this as wontfix, since we're now underway with translating the new nav.
