### ISSUE TITLE
FFFY - French version

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6584]
This is a request to create the French version of [the FFFY page](https://www.mozilla.org/en-US/firefox/fights-for-you/). 

- Design will be identical to en-US version
- MJ or Liz is the contact person for this. 
- French localization will be handled internally of Marketing most likely (i.e. no need to engage with l10n team)

Needs from Websites team are: SEO (?) keywords and coding. 

Tasks:
- [ ] Hard code template for FR using [this copy](https://docs.google.com/document/d/1Q466LlBu4Tvch3CzJdjLE_pag5usvpPXpVlv3J_Tvyw/edit)

**Comment by rraue** [comment]
I don't understand what kind of Seo and keywords is needed? If its a translation meta title, description, content and Seo will be the same.

**Comment by djst** [comment]
Hence the (?) - was just flagging that your input is probably needed here one way or the other. :)

**Comment by rraue** [comment]
Then I finished my job here I guess 😄

**Comment by ejregithub** [comment]
@craigcook / @amychurchwell - when you're done tasks currently in progress, please pick this up as the highest priority task - it's up for grabs to the first person free.

**Comment by ejregithub** [comment]
@craigcook @amychurchwell - this is good to go when r+ed - Lucile reviewed the page on demo and signed off.
