### ISSUE TITLE
Win 10 funnelcake test on /new

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6586]
Alex has understanding here and we still Daniel Z’s final input on traffic cop allocations

 - an important request from product

**Comment by djst** [comment]
Given that @alexgibson is on PTO, I think this one is blocked at least until @ejregithub is back.

**Comment by alexgibson** [comment]
The only context I have on this request is what’s in the bug, so I don’t have any additional background. If it’s urgent, I wouldn’t call myself a blocker here until I return.

**Comment by djst** [comment]
Thanks @alexgibson. Unassigning you so someone else on the team can pick this up.

**Comment by craigcook** [comment]
I'll see what I can do on this, if I can parse the info in the bug.

**Comment by craigcook** [comment]
(This info is also in the bug, just noting it again here for posterity):

> Context: We're investigating the impact that placing a Firefox shortcut on the Windows 10 taskbar would have on engagement and retention. The hypothesis being that users find it more convenient to open Firefox from the taskbar in a context where pinning shortcuts to the taskbar is not something most users know how to do.

There are two Funnelcake builds; 138 is the control and 139 has the taskbar pinning. This is targeting only users on Windows 10 and only in the en-US locale. Since there are only two builds and one is already set up as a control, it will be a simple 50/50 split in Traffic Cop.

**Comment by craigcook** [comment]
Update: based on expected download rates the sample will be a 9%/9% split between the two funnelcakes and the remaining 82% getting the normal build.

We'll run the test for two weeks so as to avoid needing to turn it off during the holiday break, starting on 20 December (Thursday) and ending on 3 January (two Thursdays hence).

The code merged in https://github.com/mozilla/bedrock/commit/2ecc2a883d0456acd4ea468df6339e0c6520c0d6
