### ISSUE TITLE
[aDAU Experiment] Improved pre-download experience test

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6588]
Pending a full prioritization of all aDAU-related experiments, this is the one experiment we discussed last week that the team would like to run. It's about creating a multivariate test with the winner of the current en-US pre-download experiment as control. 

@stephaniehobson: please fill in the info that you wrote down last week.

**Comment by stephaniehobson** [comment]
This one? https://github.com/mozilla/bedrock/issues/6562
