### ISSUE TITLE
Documentation for send_yourself macro

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#6603]
I noticed in macros.html the comment:
`{# send_to_device macro is being deprecated in favor of the send_yourself macro below. #}`
when searching for `send_yourself` in readthedocs.io there are no results. Perhaps we should write about transitioning from `send_to_device` to `send_yourself`

**Comment by craigcook** [comment]
💯 that new `send_yourself` macro was made in haste and not really documented, and we have yet to follow up on deprecating the older macro on the pages that still use it. The new macro could/should also be refactored and backported into Protocol, but that also hasn't happened.

**Comment by alexgibson** [comment]
The new macro is also lacking any unit tests (which the old one does have) 😕

**Comment by alexgibson** [comment]
Closing as wontfix as per: https://github.com/mozilla/bedrock/issues/7614
