### ISSUE TITLE
SEO page for Firefox for Windows

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6604]
Description: create page intended to boost SERP ranking for Firefox for Windows

[Brief w. Copy](https://docs.google.com/document/d/1crlAjayxVea16mwozC93IUvGS_Yd7Wmka3CIDpng4ME/edit)

[Design in Abstract](https://share.goabstract.com/8b81c0d1-952d-4cd3-ba7d-f812913037fa)

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/49976673-c331d400-fef7-11e8-9a42-f7f16f9bf4be.png)

**Comment by amychurchwell** [comment]
@ejregithub I am a little confused by the ask-- this is an alternate /new page for Windows users? So we would be offering alternative pages to Windows? Has @rraue weighed in?

**Comment by amychurchwell** [comment]
@rraue & @claychaffin would you be able to provide meta title and description?

**Comment by ejregithub** [comment]
@rraue - Chelsea quoted you as saying "They are supposed to be exactly as the firefox/new page just different in the headline, title, and the three bullet points below the cta."

Can you confirm that meta title and description should be the same as /new or should be throw in some operating specific (Windows in this case) flair?

From /new:
<meta property="og:title" content="Download the fastest Firefox ever">
    <meta property="og:description" content="Faster page loading, less memory usage and packed with features, the new Firefox is here.">

**Comment by rraue** [comment]
The title of new is currently "Download Firefox — Free Web Browser — Mozilla" and should be adjusted on this page:

title for /firefox/windows/: Download Mozilla Firefox for Windows — Free Web Browser

Same for the description: Download Mozilla Firefox for Windows, a free Web browser. Firefox is created by a global non-profit dedicated to putting individuals in control online. Get Firefox for Windows today!

@claychaffin please review my suggestion.

og-tags are not really my piece of cake but should as well be changed:
 meta property="og:title" content="Download the fastest Firefox for Windows ever"
meta property="og:description" content="Faster page loading, less memory usage and packed with features, the new Firefox for Windows is here."

**Comment by amychurchwell** [comment]
@ejregithub Demo link for stakeholder review: https://bedrock-demo-seo-windows.oregon-b.moz.works/en-US/firefox/windows/
