### ISSUE TITLE
SEO pages for Firefox for Linux

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6605]
Description: create page intended to boost SERP ranking for Firefox for Linux

[Brief w. copy](https://docs.google.com/document/d/1D7ktsLfaEL_3mNVVgNJlW_c7jMMcBbz5FsSBApFVJwM/edit)

[Design in Abstract](https://share.goabstract.com/8b81c0d1-952d-4cd3-ba7d-f812913037fa)

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/49976770-34718700-fef8-11e8-996a-c336b6b8e55d.png)

**Comment by ejregithub** [comment]
title for /firefox/windows/: Download Mozilla Firefox for Windows — Free Web Browser
@amychurchwell - regarding meta data, we'll adapt this page from @rraue 's comments for the Windows page

meta title for /firefox/linux/: Download Mozilla Firefox for Linux — Free Web Browser
meta description: Download Mozilla Firefox for Linux, a free Web browser. Firefox is created by a global non-profit dedicated to putting individuals in control online. Get Firefox for Linux today!

og-tags should as well be changed:
meta property="og:title" content="Download the fastest Firefox for Linux ever"
meta property="og:description" content="Faster page loading, less memory usage and packed with features, the new Firefox for Linux is here."

**Comment by amychurchwell** [comment]
@ejregithub Demo link: https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/linux/
