### ISSUE TITLE
"Investigation" hard-coded in English on CPG reporting

### ISSUE THREAD

**Issue by Pike** [mozilla/bedrock#6609]
https://github.com/mozilla/bedrock/blob/ff44d0331ef581030df6193045435263376cc1cd/bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html#L152 has a hard-coded English string, "Investigation".

CC @peiying2

Thanks to @petercpg for reporting.

**Comment by peiying2** [comment]
@craigcook

**Comment by craigcook** [comment]
D'oh, sorry I missed that one. I'll have a fix shortly.
