### ISSUE TITLE
SEO pages for Firefox for Mac

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6615]
Description: create page intended to boost SERP ranking for Firefox for Mac

[Brief w. copy](https://docs.google.com/document/d/1uogCdrTNhmY-krJ7m3afhBCh-mWOjg7RqPwMhZEMLkQ/edit)

[Design in Abstract](https://share.goabstract.com/8b81c0d1-952d-4cd3-ba7d-f812913037fa)

**Comment by ejregithub** [comment]
@amychurchwell - regarding meta data, we'll adapt this page from @rraue 's comments for the Windows page

meta title for /firefox/mac/: Download Mozilla Firefox for Mac — Free Web Browser
meta description: Download Mozilla Firefox for Mac, a free Web browser. Firefox is created by a global non-profit dedicated to putting individuals in control online. Get Firefox for Mac today!

og-tags should as well be changed:
meta property="og:title" content="Download the fastest Firefox for Mac ever"
meta property="og:description" content="Faster page loading, less memory usage and packed with features, the new Firefox for Mac is here."

**Comment by amychurchwell** [comment]
@ejregithub Demo link: https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/mac/
