### ISSUE TITLE
New Firefox Accounts l10n page missed a few strings 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#6619]
L10n string extraction missed a few strings and string updates between PR #6503 commits. 

Refer to bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1514343

Some of the strings were hard coded in this commit: https://github.com/mozilla/bedrock/pull/6503/commits/00dbad57ace2d0ed0ff0b7742422a218bc28b8dc 

11 days later, they were tagged correctly for l10n and two strings were revised too: https://github.com/mozilla/bedrock/pull/6503/commits/e7f7dbf7a21199a6f31f0ca923dabbca71cf1f1d. 

Somehow, when I extracted the strings (see the conversations and timeline), I got the copy from the old version with the new file name. How can we fix this? 

@craigcook @amychurchwell

**Comment by craigcook** [comment]
Sorry, that whole pull request got a bit messy. I'm not sure how best to clean it up at this point. Can we just re-extract strings from the final template? Would that undo all the previous l10n work?

**Comment by peiying2** [comment]
> Sorry, that whole pull request got a bit messy. I'm not sure how best to clean it up at this point. Can we just re-extract strings from the final template? Would that undo all the previous l10n work?

I extracted the file today to confirm what the bug listed is correct. For the "hard coded" strings, adding the new strings make no difference (they are  exposed in English now already). For the updated strings, if we replace them with new strings (Scan...), which means more English strings on the site until the communities with activated pages catch up again.

**Comment by craigcook** [comment]
For those strings that changed between commits (the "Scan..." ones), we can at least wrap them in a tag with the old form as the fallback. I'll do that.

**Comment by craigcook** [comment]
We added the tag `accounts_2018_qrcodes` in #6620 for the two strings that changed but alas there's nothing we can do for the ones that were hardcoded in the original extraction. Sorry for the headaches.
