### ISSUE TITLE
Deleting or moving static assets doesn't delete them in local dev

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6628]
I ran into a problem where images were resolving for me locally but no on the server. I had moved the files into a new directory and not updated the image source. 

Restarting the docker image didn't fix the problem. Deleting the static directory on my local machine didn't fix the problem. Deleting the docker image did. 

It would be nice if images that 404 on the server also 404 locally.

**Comment by alexgibson** [comment]
Closing outdated issue, feel free to reopen if still relevant
