### ISSUE TITLE
Differing trademarks email addresses used

### ISSUE THREAD

**Issue by gene1wood** [mozilla/bedrock#6651]
PR #6059 uses differing email addresses for trademark-permissions. I suspect one of these is correct and the others should be fixed but I'm not sure which one is right.

* [licensing.html uses `trademark-permissions@mozilla.org`](https://github.com/mozilla/bedrock/blob/b13e0f962ee4e131daf94e8ce4a43ff27e538fc5/bedrock/foundation/templates/foundation/licensing.html#L48-L49)
* [distribution-policy.html uses `trademark-permissions@mozilla.com`](https://github.com/mozilla/bedrock/blob/b13e0f962ee4e131daf94e8ce4a43ff27e538fc5/bedrock/foundation/templates/foundation/trademarks/distribution-policy.html#L97-L98)

The variable used for the email link was also wrong, I've put up #6650 to fix that. (cc @amychurchwell )

**Comment by gene1wood** [comment]
@amychurchwell Actually #6059 doesn't fix this issue as this issue speaks to the differing email addresses used, not the incorrect `mailto:` link (that #6059 fixes). You probably want to re-open this issue.

**Comment by amychurchwell** [comment]
@gene1wood Thank you. Must still be sleepy from holidays. 🙂
I am also not entirely sure which one is correct, but I will try and track down an answer.

**Comment by gene1wood** [comment]
@amychurchwell actually I just happened upon the answer (I needed to email that trademark email address which is what started this odyssey in the first place). When emailing the .org I get back

> Your message wasn't delivered to trademark-permissions@mozilla.org because the address couldn't be found, or is unable to receive mail. 

So I think that means the .com is the right address

**Comment by gene1wood** [comment]
Which means [`licensing.html`](https://github.com/mozilla/bedrock/blob/b13e0f962ee4e131daf94e8ce4a43ff27e538fc5/bedrock/foundation/templates/foundation/licensing.html#L48-L49) is the file that needs to be fixed.

**Comment by amychurchwell** [comment]
@gene1wood Will have a PR up shortly. Thanks for the catch!
