### ISSUE TITLE
Disable and remove /new FxA experiement for existing Firefox Users

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6689]
The experiment was only coded to target current release, which at the time was 62. Very few people should be seeing the experiment now.

https://github.com/mozilla/bedrock/pull/6173

**Comment by hoosteeno** [comment]
@alexgibson and @stephaniehobson, can we hold this? Turns out my analysis was flawed.

**Comment by alexgibson** [comment]
@hoosteeno I've added a DNM lable to it for now. Note that keeping the code around is only really useful if we want to rerun the experiment. Rolling this out to production as a new default would be a considerable refactor of the default /new page.
