### ISSUE TITLE
Fundraising banner for February/Valentine campaign

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6693]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

MoFo is planning a mid-February fundraising campaign and wants to bring back the home page banner for a brief time, with design and messaging relating to Valentine's Day. It will be English-only. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Launch on Friday Feb 8th
- [ ] Switch

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] 

#### Tasks
- [ ] Code it
- [ ] Code switch
- [ ]

**Comment by WillatMozFdn** [comment]
^^ that'll be the design ticket , just FYI.  We'll work out copy and implementation here, I think?  Thanks Craig!

**Comment by kristinashu** [comment]
Hi @craigcook, here's how designs are coming along. Please let me know if you have any feedback/concerns and then I'll share all the files with you. Only updates from the EOY banner are the background image and the copy.

Also, @WillatMozFdn is inquiring if it's possible to run an A/B test on the copy? I've included the two variations but let us know if it won't be possible.

**Variant A on desktop:**
![moz org v-day copy 2 2x](https://user-images.githubusercontent.com/1068783/51209732-ca1c7f80-18c5-11e9-95b5-8c2cb6082b49.jpg)

**Variant A on mobile:**
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/51209877-2aabbc80-18c6-11e9-9552-70a169f0a813.png">

**Variant B on desktop:**
![moz org v-day copy 3 2x](https://user-images.githubusercontent.com/1068783/51209755-d6a0d800-18c5-11e9-95da-e71388a18d87.jpg)

**Comment by craigcook** [comment]
Yes, we can do an A/B test. Should I assume a 50/50 split between the two versions?

Also, we should set a new `utm_campaign` value for GA. What should it be? (The EOY banner was `2018wk1`)

**Comment by kristinashu** [comment]
@WillatMozFdn I've updated the comp but that copy is looking a little long. Any chance you could shorten it a little?

@craigcook here's the Sketch file, jpg of the background, and psd for it https://drive.google.com/drive/folders/1OeKSE0wM8CQXiMjV4r9wFaBWfIg6RF0h?usp=sharing. I can also update the file once Will has the updated copy.

**Comment by WillatMozFdn** [comment]
@kristinashu ...

1. try this copy out for variant B?  (Condensed it a bit, but finding it hard to make it shorter without dropping one of the three concepts, which I don't want to do)  "Big corporations try to restrict how we access the web. Misinformation makes it harder for us to find the truth. Web-connected devices go to market without basic security standards. The non-profit Mozilla Foundation fights for a healthier internet, **will you donate today?**  (Note the bolding on the last part, the call to action.)

2. for the copy in variant A, please add "the non-profit" before "Mozilla Foundation," so it reads "A few times a year, the non-profit Mozilla Foundation asks for donations..."   and also, bold the first part of the CTA and add the word "Please," so it reads "**Please chip in** to help us keep the web healthy, wonderful..."

Now, a note -- MoCo style is "non-for-profit" and MoFo's is "non-profit" ... I'm going with the latter on these, b/c a) it's shorter and b) this is on Mozilla.org (not Firefox.com) so it seems like the style rules for the nonprofit organization should apply.  However, I've willing to be overruled if others feel strongly -- I don't think it makes a big difference at all.

**Comment by WillatMozFdn** [comment]
@craigcook ....

1. Correct ... let's do a 50-50 split.  Timing-wise, I'd like to start the test evening of the 11th or morning of the 12th ... see what results we get on the 12th and/or 13th ... and then roll all the traffic to the winner no later than the morning of the 14th. Then take-down end of day on the 15th or morning of the 16th. Is that do-able?

2. To accurately track the contributions coming from these two variants, we need to put different UTM parameters on the links in each version -- then I can watch results in real-time using GA.  (It's not perfect due to some privacy-oriented blockers, but still -- with enough traffic, we can almost always get a good read on what's winning.)  So ... for variant A, we should have these parameters on the URLs:

?utm_source=mozilla.org&utm_medium=referral&utm_campaign=feb2019banner&utm_term=variantA

... and for variant B ...

?utm_source=mozilla.org&utm_medium=referral&utm_campaign=feb2019banner&utm_term=variantB

Does that make sense?  Let me know, thanks!

**Comment by kristinashu** [comment]
### Here are the final files!

- [Comps](https://redpen.io/p/zofc918b58da625a20)
- [Working files](https://drive.google.com/drive/folders/1OeKSE0wM8CQXiMjV4r9wFaBWfIg6RF0h?usp=sharing)
- Background banner JPG
![v-day-banner](https://user-images.githubusercontent.com/1068783/51338182-0672eb80-1a3e-11e9-9a71-b15429ad551c.jpg)

### Copy for Variant A
Title: We all love the web.  Join Mozilla in defending it.

Body: Let’s protect the world’s largest public resource for future generations.  A few times a year, the non-profit Mozilla Foundation asks for donations. **Please chip in** to help us keep the web healthy, wonderful and welcoming to all.

### Copy for Variant B
Title: We all love the web.  Join Mozilla in defending it.

Body: Big corporations try to restrict how we access the web. Misinformation makes it harder for us to find the truth. Web-connected devices go to market without basic security standards. The non-profit Mozilla Foundation fights for a healthier internet, will you donate today?

### Comp for Variant A

![moz org v1 2x](https://user-images.githubusercontent.com/1068783/51337928-4c7b7f80-1a3d-11e9-828f-099b93776162.png)
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/51338114-d62b4d00-1a3d-11e9-9f81-d6f3dbf6372f.png">

### Comp for Variant B

![moz org v2 2x](https://user-images.githubusercontent.com/1068783/51337929-4d141600-1a3d-11e9-8bf8-c56622636211.png)

<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/51338147-efcc9480-1a3d-11e9-9bcf-0f50cc5ff22b.png">

**Comment by hoosteeno** [comment]
The a/b variations here are slight -- in paragraph text, only. After running lots and lots of a/b tests, my gut tells me that we would need a large sample to be confident in any minor difference coming from these variations. We're unlikely to get that sample in 5 days, and _very_ unlikely to have time to respond to anything we might learn from the experiment. Adding an experiment to this doesn't seem like a good investment. Can we just run with our favorite copy on this?

**Comment by WillatMozFdn** [comment]
Hey Justin (@hoosteeno ), I've run lots of tests of fundraising copy in the snippet channel, and you'd actually be surprised at the significant results I've seen from testing even small variants in the copy (and even after less than one day of data).  Point taken, however -- I'll re-work the copy some tomorrow morning so that we have a bigger difference.  We do however absolutely need to stick to running an A/B test on this project; this is now our second-biggest fundraising channel, and the donations increase we can see from optimization via an A/B test is likely to result in increased revenue to the tune of tens of thousands of dollars.

**Comment by hoosteeno** [comment]
I believe you re: snippets. One thing that snippets have going for them is massive volume. In this case we don't have the same volume, not by a long shot. 

The numbers on the banner channel don't seem to justify the engineering and management effort for a 5 day experiment. [Have a look](https://docs.google.com/document/d/1IClAqjRNPGPwnU4D-56n_gyuNCCFp5q1y7Y9Y0-dKRM/edit) and let me know if you disagree?

If you still think the experiment is worthwhile, do you have a monitoring plan? My napkin math suggests the only way we'll capture any incremental benefit from this experiment is if we promote the winner the very moment we become confident it has won.

**Comment by WillatMozFdn** [comment]
Hey Justin (@hoosteeno ), I'll accept your logic on this one.  (And thanks for the numbers, I previously did not have any idea the scale of the traffic we're talking about here.)  Let's go with variant A -- I think it's more consistent with a valentine's day theme.  Follow-up question ... what changes to the banner (in general, not just for V-day) do you think we could make that would make a big difference and get us a clear result in a few days' testing -- ??

**Comment by craigcook** [comment]
This is up on a demo server at https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/

We're aiming to go live this Friday the 8th and run until early on the 15th.

There's a small issue with the background image at mobile sizes where it's not quite tall enough to fill the space and the edges become visible. I can do some CSS trickery to stretch it, but thought it might also be just as easy to ask for a taller version, if possible @kristinashu ? Maybe just without the top and bottom edges cropped? We can still center it so it will usually be clipped by the box but it would be nice to have a bit more room to expand and reveal more of the background when it's tall and skinny.

![image](https://user-images.githubusercontent.com/205591/52383019-7c121c00-2a2c-11e9-8046-bd59c7e1a5de.png)

**Comment by kristinashu** [comment]
Everything looks great but the banner background seems really zoomed in at wide browsers widths. Could it be related to the banner getting cut off at narrow widths? I think the background image would like nicer if it's size were set to `cover` on all screen sizes?

Here's a comparison of the background image:

![v-day-banner](https://user-images.githubusercontent.com/1068783/52384848-0742e000-2a34-11e9-9b1d-3577da417bac.png)

I can definitely get you a taller image tho, just let me know how much tall it should be.

**Comment by craigcook** [comment]
> Everything looks great but the banner background seems really zoomed in at wide browsers widths. Could it be related to the banner getting cut off at narrow widths? I think the background image would like nicer if it's size were set to `cover` on all screen sizes?

Yeah, sorry, that was a CSS bug. I've since fixed it but needed to push the fix to the demo server (it should be updated momentarily). Also I think I've solved the tall-and-skinny issue at the same time but still wouldn't turn down a larger version of the image if it's no trouble.

**Comment by kristinashu** [comment]
It's looking great!

Here's a taller image 700px instead of 555px. Is that what you meant by larger? 
![v-day-banner-h700px](https://user-images.githubusercontent.com/1068783/52431659-83cdd100-2abd-11e9-915e-aefc66ba3198.jpg)
