### ISSUE TITLE
Primary CTA is missing when visiting /firefox/accounts/ on Firefox mobile.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6694]
When I visit the `/firefox/accounts/` page using Firefox for iOS, I don't see a primary CTA button displayed at the top of the page. Only when I scroll right to the bottom of the page to the secondary CTA section there's a "Set up Sync for iOS" button, that takes me to SUMO.

Not entirely sure if this is intentional or not, but it seemed odd that the only CTA was at the bottom of the page. I can assume the same is also true for Android, as I don't see any mobile links in the markup for the hero section.

We should be able to replicate that same CTA button at the top of the page pretty easily.

**Comment by dzingeek** [comment]
I don't think that was intentional. I would call that a bug, nice catch @alexgibson

**Comment by datavizard** [comment]
@alexgibson, I would like to work on this. Can you provide me with a bit clearer steps to reproduce this issue first? Then we can discuss the approach to fix this.

**Comment by ejregithub** [comment]
@alexgibson - can you please apply an Estimate to the effort/complexity for this work?

**Comment by alexgibson** [comment]
> @alexgibson - can you please apply an Estimate to the effort/complexity for this work?

Done, thanks
