### ISSUE TITLE
Mozilla.org localization audit

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6697]
The localization team has [highlighted a number of problems](https://docs.google.com/document/d/1V-27Dvs2uv4jHebyJ9OLwakK-QY9bCKcxPRU9nR_JdY/) with our current localization infrastructure and workflow on mozilla.org. In a nutshell:

1. Marketing pages need to ship quickly and change frequently, which rarely allows time for community l10n.
2. Using outside vendors for translation is difficult because bedrock uses a unique infrastructure that isn't compatible with industry-standard tools.

We want to solve these problems so we can begin to use vendors for translation of key marketing pages, taking much of the burden of the volunteer community. And yet using vendors alone would greatly limit the number of languages we can support, while also eliminating l10n as a volunteer opportunity.

So as we begin the work to solve all the things and make everyone happy, we want to assess the current state of the site and identify which pages or section are considered "marketing content" (fast-shipping, often-changing) that will be translated by paid vendors and which pages are considered "core content" (slow-shipping, evergreen) that would be translated by the l10n community.

**Comment by peiying2** [comment]
Thanks @craigcook for getting this started. I want to share this list of .lang files. The names and number of files don't necessarily correspond to the template names on bedrock, but it does shed light on what pages are fully localized in what languages: https://l10n.mozilla-community.org/langchecker/?action=listpages. It also highlights the pages that are activated at some point but still have outstanding untranslated (tagged) strings. It's a good indicator how active a community is at the moment. I think the info here helps us carve out what's covered by the communities and what by vendors. And it may lead us to think what a simple vs. full mozorg site looks like.

**Comment by craigcook** [comment]
Very rough, very much WIP spreadsheet: https://docs.google.com/spreadsheets/d/1ViVvQyH0IWYBDYaY8N-TKXeBsuYCgsFVUGyIz3WPg-g/
