### ISSUE TITLE
Launch new SEO page "'The history of web browsers"

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6709]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: using the template established for SEO pages from the NA Desktop team, create the new page 'The history of web browsers'

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Get QA signoff from @rraue prior to go live
- [ ] Get QA signoff from Accountable (Winston) prior to go live

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] None identified

Tasks
- [ ] Assign the URL /technology/browser-history/
- [ ] Use the copy in [this document ](https://docs.google.com/document/d/1demvfj2kzdHZ2HhoS4GwUTNfRxFZ0s54veJ84XOwHKY/edit?usp=sharing)to create the page

The native Sketch file lives [here](https://share.goabstract.com/75a5ee3e-51e2-415f-8950-3ae3e70200ef) and within the Sketch file, it's the History Landing Page layer.

**Comment by ejregithub** [comment]
Blocked on meta data and URL

**Comment by ejregithub** [comment]
@alexgibson - the copy is now final, here, so I've removed the blocker -https://docs.google.com/document/d/1demvfj2kzdHZ2HhoS4GwUTNfRxFZ0s54veJ84XOwHKY/edit?usp=sharing

The meta data is at the bottom of the doc.

**Comment by alexgibson** [comment]
This is up on demo for stakeholder review https://bedrock-demo-agibson.oregon-b.moz.works/en-US/technology/browser-history/

**Comment by ejregithub** [comment]
I have this in front of the desktop team for QA

**Comment by alexgibson** [comment]
@ejregithub I thought this was already approved by stakeholders. Does this mean the copy has now changed and needs updating again? I can't easily spot what's changed :(

**Comment by ejregithub** [comment]
@alexgibson - Copy is unchanged. Apologies if I presented any confusion.  This is good to go.
