### ISSUE TITLE
Launch new SEO page "Update browser"

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6710]
| Estimates |  |
| ------------- | ------------- |
| PM | 2 |
| ENG | 2 |
| SEO | .5 |

Description: using the template established for SEO pages from the NA Desktop team, create the new page 'Update browser'

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live before end of January 2019

#### Tasks
- [ ] Assign the URL /technology/update-your-browser/

Native Sketch file can be found [here](https://share.goabstract.com/75a5ee3e-51e2-415f-8950-3ae3e70200ef) (in Abstract)

Look for the `Update Landing Page" layer.

[Copy (with meta data at the bottom of the page) 
](https://docs.google.com/document/d/1P30d7rLGNF-F4Hea0OAwV3JQSWCu5Hw1Anz8wpC8HFQ/edit#)

**Comment by ejregithub** [comment]
Blocked on meta data and URL

**Comment by ejregithub** [comment]
Sorry @amychurchwell - I asked for it, was told it was done, but don’t see it in the original copy doc.  I’ve asked for that.

https://docs.google.com/document/d/1P30d7rLGNF-F4Hea0OAwV3JQSWCu5Hw1Anz8wpC8HFQ/edit#

**Comment by ejregithub** [comment]
@amychurchwell - please find that in [this doc](https://docs.google.com/document/d/1P30d7rLGNF-F4Hea0OAwV3JQSWCu5Hw1Anz8wpC8HFQ/edit#) at the bottom.

**Comment by amychurchwell** [comment]
@ejregithub demo link -- https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/technology/update-your-browser/

**Comment by ejregithub** [comment]
@amychurchwell - the copywriter noted an error in the original copy doc, sorry!
Please make all mentions of 'internet' all lowercase (unless it leads off a sentence, of course).

**Comment by amychurchwell** [comment]
@ejregithub demo reflects typo fix 👍
