### ISSUE TITLE
Update video placeholders on /firefox

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6716]
The current video place holders don't give users an idea of what they will see demoed in the videos. Let's update them to use a still that communicates the video content.

**Comment by alexgibson** [comment]
This ws completed in https://github.com/mozilla/bedrock/pull/6717

**Comment by stephaniehobson** [comment]
Mixed results with the updated placeholders:

<img width="516" alt="screen shot 2019-02-05 at 3 38 42 pm" src="https://user-images.githubusercontent.com/854701/52312130-4e5ea180-295e-11e9-9e99-0160ae58a139.png">

I will revert the Pocket and comparison video ones and try a different still from the bookmarking one.

The new screenshot placeholder is doing quite well though :)
