### ISSUE TITLE
Improve or deprecate the Firefox out-of-date notification banner

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6726]
In 2017 we implemented a site wide notification banner that is shown to out of date Firefox users (2 major verions out of date or more). Clicking the "Update Firefox" button takes people to `/download/thanks/`. You can see a screenshot of the banner below:

![screenshot_2019-01-18 the new fast browser for mac pc and linux firefox](https://user-images.githubusercontent.com/400117/51383599-c715cf00-1b11-11e9-9367-dabb41d09095.png)

This was implemented in a relatively short sprint cycle, and was to meet a Q3 goal to increase the volume of users updating old versions of Firefox from 500k weekly to 750k. The notification met that goal (in terms of the number of clicks the button got), but the banner has a number of flaws that we never addressed. I think we should evaluate how effective this banner is, and either fix those flaws, or else consider removing it from the site.

Issues:

- If a user has an update waiting, all they really need to do is restart their browser. They have already downloaded the update, and to make them re-download the entire product again is sub-optimal.
- If someone downloads Firefox using Firefox and then attempts to run the installer, they are presented with an error because Firefox is already running (a frustrating UX).
- We have no idea if people who clicked on the "Update Firefox" button actually updated their browser or not, all we know is if they click the button.
- The banner is also shown on outdated `/firstrun` and `/whatsnew` pages. Telling someone their browser is out of date when they literally just updated it, is a also frustrating UX.
- Visually the banner is unlike anything on any page, it's a snowflake in terms of design, and it is perhaps overly obtrusive. If someone really doesn't want to update their browser, it is likely quite annoying (it's possible to dismiss, but the cookie only lasts a week or so).
- The banner is quite JS heavy, and increases the bundle size of all our pages even though it's only applicable to a single browser, and only on outdated versions.
- The banner has never been ported to Protocol, and so only exists on legacy Pebbles and Sandstone pages.
- The banner was never localized, and only exists for en-US audiences.

I can think of ways to try and improve some of these issues, but first I think we should take a look at the existig data for how well it is performing (do we know how many clicks turn into re-installs, for instance?).

Relevant bugs/issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=1381776
https://github.com/mozilla/bedrock/pull/5001

**Comment by alexgibson** [comment]
@hoosteeno given the reasons outlined above, I'd like to propose that we remove this feature from bedrock. We have newer, more easily reusable [notification components](https://protocol.mozilla.org/patterns/molecules/notification-bar.html) available in designs today that aren't as intrusive, should we ever want to revisit this type of feature.

Thoughts?

**Comment by hoosteeno** [comment]
Yes, let's remove it. Thanks.

See also: https://github.com/mozilla/bedrock/issues/8147
