### ISSUE TITLE
/new/ title isnt translated anymore on locales

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6728]
It looks like the end of December/ beginning of January something went wrong and all locales for /new/ got the English title. That causes a massive drop in ctr and therefore traffic/downloads and we need to fix this fast. 

As an example the French version:
<img width="1336" alt="screen shot 2019-01-21 at 11 51 33" src="https://user-images.githubusercontent.com/36700618/51470097-33dbd400-1d73-11e9-83ec-7cf15edbbd4e.png">

**Comment by rraue** [comment]
The og:title tag still contains the translated title, so I assume its not because of a change in l10n, but something in our code. Maybe a change on the win/mac/linux pages caused this? That would be around that time when it caused the drop.

**Comment by alexgibson** [comment]
Looks like this is a regression from https://github.com/mozilla/bedrock/commit/52ebe66e537fb45ece909309fa1a88057f569bc2#diff-0f99a4dfbf94512a350aa10237d0bc35
