### ISSUE TITLE
Update copy on Edge SEM pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6735]
Description: Copy updates in the two versions of the Edge SEM pages

#### Tasks
- [ ] Update copy highlighted in RED in this [document](https://docs.google.com/document/d/1XI2HYanpq2sWXMkbLOSlbf0Zw2sicudfeGU-TjJ4RMI/edit)

https://www.mozilla.org/en-US/firefox/new/?xv=edge&xv=edge&v=1
https://www.mozilla.org/en-US/firefox/new/?xv=edge&xv=edge&v=2

**Comment by alexgibson** [comment]
Note there is only 1 version of the Edge SEM page to update. The other version was removed in https://github.com/mozilla/bedrock/issues/6371

**Comment by alexgibson** [comment]
@ejregithub I've been through the spreadsheet and added comments. All of the changes to the browser features tables are already reflected in the web page live in production? I'm not sure what that team used as reference for these changes, but they seem old and outdated.

The only new string change I can see is:

```
Edge came with your PC, but Firefox doesn’t hog your data. Edge runs on Google’s Chromium where data means profits. Firefox beats Edge when it comes to privacy, portability and utility.
```

I think we should make sure this is Ok with legal, as the line that says "Edge runs on Google’s Chromium where data means profits" seems a little contentious to me. It may not be true yet also, as I believe they have still to switch engines in their release main version?

**Comment by alexgibson** [comment]
I've talked to Kirby on IRC and most of this copy doc is old, dating back to last September.

The only line of copy we need to change here is:

"Edge came with your PC, but Firefox doesn’t hog your data. Edge runs on Google’s Chromium where data means profits. Firefox beats Edge when it comes to privacy, portability and utility."

**Comment by alexgibson** [comment]
@ejregithub any word from legal on this string change?

**Comment by ejregithub** [comment]
@alexgibson - Michael responded but the team has not yet picked up copy changes based on that feedback. I'm going to leave this blocked and move it into our backlog.

**Comment by ejregithub** [comment]
@alexgibson - and . . . we're there. There is no longer a request to change the copy in the remaining en-US version of the page being shown. However, Guy indicated that the EU team is localizing the copy to DE. I would very much like that to run through Pontoon and be open to further localization and will see if I can work that out. In the meantime, let's plan on a hard coded template for DE to get it out of the door, should that copy come quickly.

**Comment by alexgibson** [comment]
@ejregithub I think it's probably better to open a new issue for the l10n request, as it's largely unrelated to the original request here. Closing this issue if these changes are no longer needed.
