### ISSUE TITLE
[2019-03-19] WNP 66

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6736]
[Master project doc](https://docs.google.com/document/d/121RNIt_W8RSjubBHugQgCXKH8F8solk2hXP0ziunXsQ/edit)

| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | 1/2 day |
| ENG | 4 |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: the What's New page for Firefox 66, promoting Firefox Accounts

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live a week before the release date to allow for QA (external)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] String changes 

#### Tasks:
- [ ] Code the page with creative assets provided by the Accounts team

- Schedule
Deadline for [final copy](https://docs.google.com/document/d/1vuNn8ct1ub0DAwz2YivEmNIDwP2yR4NtAmo8FSR6LnA/edit?usp=sharing) - 2/8
Submit PR w. strings - 2/13
Deadline for final design - 2/19
Coded page on demo for stakeholder QA review - 3/5
RC week - 3/11
WNP 66 go live - on or before - 3/12
Release date - 3/19

**Comment by hoosteeno** [comment]
@amychurchwell can you update here with relevant links & status?

**Comment by amychurchwell** [comment]
Final design a la mham.
<img width="1035" alt="screen shot 2019-02-19 at 1 05 43 pm" src="https://user-images.githubusercontent.com/30483988/53116076-9ce27300-34fc-11e9-82fa-93fcae065cef.png">
https://share.goabstract.com/e11de043-482a-436d-a88b-6223c841bd4e

**Comment by amychurchwell** [comment]
Does Firefox Send have an adjust link? I am not seeing it as an app store product, only finding https://send.firefox.com/
If we are linking directly do we have utm param requirements? Also the design will change from a button to a link for that section as it would not have a QR code.

**Comment by amychurchwell** [comment]
@ejregithub demo link -- https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/66.0/whatsnew/
will also post in slack channel.

**Comment by ejregithub** [comment]
Closing, this is live in prod -
