### ISSUE TITLE
Remove Yandex test, make 90% cohort the 100% default

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6752]
Description:  Close the Yandex experiment and drive 90% cohort to 100% of RU geo-located audience

**Comment by ejregithub** [comment]
@hoosteeno - please prioritize this, pulling into the https://github.com/orgs/mozilla/projects/45 sprint backlog column when it's ready.

**Comment by hoosteeno** [comment]
@alexgibson can you estimate effort on this? If trivial, please pull it into sprint board any time before next sprint begins.

**Comment by alexgibson** [comment]
I think I can get this done today, added to the sprint board 👍
