### ISSUE TITLE
Travis integration no longer working

### ISSUE THREAD

**Issue by gene1wood** [mozilla/bedrock#6783]
With [GitHub services being turned off yesterday](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) the Travis integration has stopped working and travis builds won't be triggered. [You should migrate](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/) to the Travic CI GitHub app

**Comment by alexgibson** [comment]
I don't believe we use Travis integration in bedrock, so I think we're ok to close this.

**Comment by gene1wood** [comment]
@alexgibson It looks like it is enabled on the repo using @pmclanahan 's account.

![Selection_071](https://user-images.githubusercontent.com/1134034/60446285-ec852980-9bd5-11e9-9a59-7f63cab86ac0.png)

**Comment by alexgibson** [comment]
@pmac can you take a look if there's anything we need to do here? ^

**Comment by pmac** [comment]
Huh. Yeah. I'll take a look. We definitely don't use Travis anymore.

**Comment by pmac** [comment]
Okay. Removed Travis and IRC from that list.
