### ISSUE TITLE
Homepage content card update (en locales)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6785]
| Estimates |  |
| ------------- | ------------- |

| ENG | 16 |

Description: Monthly content refresh on the www.mozilla.org homepage (en-US version)

---
#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of success criteria. Use a checklist!
- [ ] This is an example of success criteria.

#### Tasks
- [ ]

Here is the content refresh for the EN-US homepage: https://docs.google.com/spreadsheets/d/1RmJsZierLpeSu5X-98Py8Pe8L2NFS5YN8BdGp5NiI7M/edit#gid=637696574

Airtable mockup is here. Click Next record to 1/30/2019: https://airtable.com/shrVQdWrXYQus2NqT/tblgNmPLbDjXxeViI/viwYLv28cjNOdZMm0

~Content for the last 2 cards are still being discussed, they may be dropped from the layout.~

Card 1 contains a video with fallback image. I've requested a higher quality fallback image, and should have that on Monday.

**Comment by ejregithub** [comment]
@alexgibson - when you can, please ballpark the ENG time required for this work.

**Comment by alexgibson** [comment]
Proposed new layout:

1. Banner
2. 5-card
3. More power to you.
4. 2-card
5. 4-card Pocket feed
6. 2-card
7. Support a healthy internet.
8. 2-card
9. Open source. Open minds.
10. 2-card
11. Love the web?
12. Footer

**Comment by alexgibson** [comment]
> @alexgibson - when you can, please ballpark the ENG time required for this work.

I'd normally ballpark this as a days work (8 hours), but seeing as they want to tweak the layout that's going to involve some extra work in bedrock. I'm going to up this to 2 days work.

**Comment by alexgibson** [comment]
Initial PR to the admin repo to update the card content: https://github.com/mozmeao/www-admin/pull/2

**Comment by ejregithub** [comment]
@amychurchwell - ready for your code review, please.

**Comment by ejregithub** [comment]
@alexgibson - is this estimate for ENG in hours or days?  Let's stop at 2 hours when estimating time, then estimate in 1/2 increments.  16 hours would equate to 3 days or so. If you agree on duration of effort (code review included), I'll change this to 3 days.

**Comment by alexgibson** [comment]
> @alexgibson - is this estimate for ENG in hours or days? Let's stop at 2 hours when estimating time, then estimate in 1/2 increments. 16 hours would equate to 3 days or so. If you agree on duration of effort (code review included), I'll change this to 3 days.

I'm never quite sure what unit value the template should use? Maybe baking in some more info would help others to work it out. Also explaining what all the abbreviations mean could be helpful too.

**Comment by ejregithub** [comment]
Yes, totally agree on adding guiding documenation @alexgibson.  I'll take that task and have it ready shortly.
