### ISSUE TITLE
"Safe Browser" SEO Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6793]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | 2 hours |
| ENG | |
| SEO | |

Description: using the template established for SEO pages from the NA Desktop team, create the new page 'Safe Browser'

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Get QA signoff from @rraue prior to go live
- [ ] Get QA signoff from Accountable (Winston) prior to go live

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] None identified

Tasks
- [ ] Have @rraue assign the URL 
- [ ] Use the copy in [this document ](https://docs.google.com/document/d/1C1n0x6YUXgkub07_EJiSB86u1PRQQU0mi_DzgRnT7zY/edit)to create the page
- [ ] Use the Sketch file located [here](https://share.goabstract.com/36637586-5c96-459f-968c-ec0e566c734a) - The layer name/artboard is: Revised Design > Safe Browser Landing Page

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/52289298-9c55b400-2922-11e9-998e-97668a790558.png)

**Comment by stephaniehobson** [comment]
Note that we do not yet have a license to use Sharp Sans on any pages other than FFFY.

**Comment by craigcook** [comment]
Page in progress on demo: https://www-demo5.allizom.org/firefox/features/safebrowser/
