### ISSUE TITLE
Reducing complexity for /firefox/mac/, /windows/ and /linux/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6798]
Right now /firefox/mac/, /windows/ and /linux/ are build as variations of /new/ and after analysing the traffic and user behaviour on this pages, we found out that it is not necessary to have all complexity of /new/ on this pages. Basically, all visitors (98%) are non-firefox. So the update banner is not necessary and various other functions not as well. 

It is enough to have a "dump" protocol page with a download button to serve the SEO-needs on these pages.

Moving the pages to a normal protocol template reduces complexity on /new/ and will prevent therefore mistakes and traffic loss on /new/.

The three pages should have a design like https://www.mozilla.org/en-US/firefox/this-browser-comes-highly-recommended/ but with the standard navigation and the messaging/wording like on /firefox/mac/, /windows/ an /linux/.

The urls, title, metadata should stay the same.

**Comment by stephaniehobson** [comment]
It would be nice if the windows and linux ones did not have a macbook as the hero image.

**Comment by hoosteeno** [comment]
@alexgibson , looking at this bug, I wonder what the best way is to have 4+ different pages (/mac, /linux/, /windows, and /this-browser-comes-highly-recommended) that are identical except for copy. I'm wondering if there is a template solution here that...
* reduces replication of the layout code
* enables independent copy evolution
* enables easy removal or addition of individual url/copy combinations (like if we wanted to add a new page just like these at a new URL)

I don't think the system necessarily has to include a content management interface yet. 

Do we already have that system? Should we be talking about building or using that system to apply to this case, and other similar cases like moments pages, campaign pages, etc?

**Comment by stephaniehobson** [comment]
There is absolutely a template solution for this :) I'm curious if it was not used for historical reasons?

**Comment by alexgibson** [comment]
When this issue was filed, these pages were extending the /firefox/new/ template, together with all of its more complex features, in order to add some new strings at a different URL. This impacted things like making changes to, and running experiments on the /new page, as we always had to be careful not to break or introduce errors here on these other pages.

Today, the /new page is no longer quite as complex, but I still don't feel great about this level of template inheritance a sane way of working, despite seeming like a quick and easy win at the time. The longer I've worked on bedrock the more I'm convinced that systems of complex inheritance for templates are not necessarily the most sensible thing, especially for high traffic pages like this. Others may disagree (which is totally fine), but it's my opinion that these pages should probably be stand-alone, like we did for [/firefox/campaign/](https://www.mozilla.org/en-US/firefox/campaign/), if they need to exist. Make things easy to update, and make things easy to rip out.

Something else I think we shoiuld stop to consider is why we need these pages at all to begin with, seeing as they are 99% identical in markup to the original /firefox/new/ page. If that page isn't ranking as highly for these keywords, then I'd like to see us try and fix that issue, rather than create multiple clones of the same page here. If memory serves me correctly, this wes the original intent, that these pages should only be temporary. But here we are today struggling to work out how to keep them updated.

**Comment by alexgibson** [comment]
> Do we already have that system? Should we be talking about building or using that system to apply to this case, and other similar cases like moments pages, campaign pages, etc?

To try and answer your question more directly, I honestly don't think we need to build a complex system for these pages. If they need to exist, then keep them simple, using stock Protocol components and layouts (e.g. like /this-browser-comes-highly-recommended). Sticking to this requires very little maintenance, and allows us to keep concerns more easily separated.

**Comment by rraue** [comment]
> Something else I think we shoiuld stop to consider is why we need these pages at all to begin with, seeing as they are 99% identical in markup to the original /firefox/new/ page. If that page isn't ranking as highly for these keywords, then I'd like to see us try and fix that issue, rather than create multiple clones of the same page here. If memory serves me correctly, this was the original intent, that these pages should only be temporary.

Some context here: I still intend /new to be improved so we dont need the three subpages anymore, but the improvement of /new got delayed several times because of priorities and until /new isn't ranking for what the subpages are ranking for, we need them. They increased desktop downloads on www by 2% and still growing.

**Comment by alexgibson** [comment]
If we still need these URLs, and the page design can't change for whatever reason, then I'm not opposed to keep on extending it for now. Either that, or extend from /firefox/campaign/. But my first preference would be to make these page designs as low maintenance as possible (e.g. stock Protocol components).

**Comment by rraue** [comment]
For SEO the page design can be whatever is best to maintain, it can change for sure, lets just keep an eye on the ctr and test changes.

**Comment by stephaniehobson** [comment]
I don't think it's appropriate to move these into the campaign section because these are indexed pages (everything in campaign lists /new as it's canonical URL). 

@alexgibson let me know if my logic is off.

**Comment by stephaniehobson** [comment]
@rraue Do we need to keep these links?

<img width="317" alt="Screen Shot 2020-02-07 at 15 12 33" src="https://user-images.githubusercontent.com/854701/74072652-4e074500-49bc-11ea-9281-58db7c84dc64.png">

**Comment by rraue** [comment]
@stephaniehobson Not for SEO necessarily but I think we should keep them or replace with possible better UX to give everyone the solution they might need, same like on /new.

**Comment by alexgibson** [comment]
> Not for SEO necessarily but I think we should keep them or replace with possible better UX to give everyone the solution they might need, same like on /new.

The original intent behind this issue was to reduce complexity for these pages, but if we want to keep all these features then perhaps we should close this issue as wontfix, and commit to keeping / maintaining the pages as they are currently, and simply update the branding.

**Comment by rraue** [comment]
That was just my opinion and as its not important for SEO I think @cgonz0 and/or @dzingeek should decide rather than me.

**Comment by stephaniehobson** [comment]
I talked to @dzingeek about getting a non-mac image for the simplified pages and she asked if we could just use the /new design for these pages since that has a hardware agnostic image already. So I'm going to update the scene1.html to use Protocol as a first step to cleaning up these pages.

**Comment by hoosteeno** [comment]
@stephaniehobson are you self-assigning this issue?

**Comment by stephaniehobson** [comment]
I guess so?

I have a WIP of updating the pages to Protocol here: https://github.com/mozilla/bedrock/pull/8532

However, it does not change the template as the issue suggests since we'd need different assets for the other template.

**Comment by alexgibson** [comment]
I think we should probably close this issue as wontfix (?), as we seem committed to maintaining these for now as full-fat download pages.

**Comment by alexgibson** [comment]
Feel free to re-open if we want to revisit.
