### ISSUE TITLE
Global FxA CTA Experiment - Invalid utm_content value

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6809]
The `utm_content` value `Get a Firefox Account` used in the [global FxA CTA experiment](https://github.com/mozilla/bedrock/blob/a22d4a2c787df8ce5fedc90643a2d41465b71b34/bedrock/base/templates/includes/protocol/navigation/index.html#L27) fails validation in the FxA team's backend service, meaning the data never makes it to Amplitude or Redash. 

Next steps:
~1. Pause the current experiment.~
2. Update the value to [something that works](https://mozilla.github.io/application-services/docs/accounts/metrics.html#descriptions-of-metrics-related-query-parameters).
3. Notify analytics people / stakeholders.
4. Relaunch the experiment

Related FxA issue: https://github.com/mozilla/fxa-content-server/issues/6954

**Comment by alexgibson** [comment]
Experiment paused via https://github.com/mozmeao/www-config/commit/d3331c1f3108fe9475cbe011a5ad681e9c729a67

**Comment by alexgibson** [comment]
Experiment reenabled in https://github.com/mozmeao/www-config/commit/8f59abd52fa0d83c075bbd2e8628ad8664a7a9bb

@hoosteeno @sghoseWI - wheh we come to evaluate data at the end of this experiment, we probably want to ignore any data prior to 12 Feb due to the issue above.

**Comment by sghoseWI** [comment]
Thanks @alexgibson -- that makes sense. Would you or @hoosteeno be able to point me to a list of all the working UTM parameters for this experiment (control vs. experimental groups)?  I'm hoping to use our BigQuery datasets to get more fine-grained data than what we can get just from Amplitude.

**Comment by sghoseWI** [comment]
Thanks @alexgibson -- that makes sense. Would you or @hoosteeno be able to point me to a list of all the working UTM parameters for this experiment (control vs. experimental groups)?  I'm hoping to use our BigQuery datasets to get more fine-grained data than what we can get just from Amplitude.

**Comment by sghoseWI** [comment]
That makes sense @alexgibson  -- I will make sure to do that in my analysis report.
