### ISSUE TITLE
New links added to /firefox/ have accessibility issues

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6814]
## Description

Several links added to `/firefox/` in https://github.com/mozilla/bedrock/issues/6458 have accessibility issues.

### Steps to reproduce

1.) Visit https://www-dev.allizom.org/en-US/firefox/
2.) Scroll down to the "Seriously Private Browsing" section.
3.) Read the content.

### Expected result

It should be easy to identify that the first two sub-titles, "Private Browsing" and "Tracking Protection" are clickable links in some way, either before or at least after hover.

In the "Customization Features" section further down, it should also be easy to identify that "Extensions", "Themes" and "Toolbar" are interactive in some way. It would also be nice if the icons we're also clickable maybe?

### Actual result

There's no way to visually identify that these elements are links. Hovering over the links produces no clear interactive state, making them pretty hard for users to discover.

### Environment

Can reproduce using any browser.

**Comment by rraue** [comment]
I agree with you @alexgibson, links on that page are underlined, if we choose to link headlines, they should be as well, even if that means, some headlines are underlined, some not, but I doubt that this is a conversion issue.

**Comment by dzingeek** [comment]
I also agree but I am not sure how I feel about underlining headlines. I think there is a better way. However, we are in the middle of revamping this page which will include the following. 

1. qual test this pg (this will be the control)
2. "re-skin" the page with updated graphics that are on brand
3. qual test again
4. updated content
5. qual test again
6. updated ux based on our finding 

I think we should address this issue in phase 4 and then again in phase 6. Does that work for everyone?

**Comment by alexgibson** [comment]
I don't really mind how / when we fix this, just as long as it's on our radar and doesn't end up being like this for a long time. I'm all for improving our internal linking, but I don't feel great about doing it as the expense of basic usability like this. Some of these things can likely be fixed without waiting for the user testing, but I agree the headings are more tricky. 😕

**Comment by rraue** [comment]
That works for me, I just can't imagine any qual test outcome explicitly ruling out underlined headline links, it just hurts "everything looks the same" what it should, as some are links, some arent.

**Comment by dzingeek** [comment]
Sorry, I forgot to update my previous comment. We are putting a few things in one phase, so this update will happen by end of this quarter. But if we want it to happen sooner we can do that too, just keep in mind it will change again..."soon"

**Comment by alexgibson** [comment]
This page has since been redesigned, so the issue no longer exists.
