### ISSUE TITLE
Small spelling mistake on https://www.mozilla.org (en-GB and en-US)

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/bedrock#6819]
## Description

Get the latest features, fast performance and the development tools you need to build for the open web with Firefox Develop Edition.

Should be:

Get the latest features, fast performance and the development tools you need to build for the open web with Firefox Developer Edition.

**Comment by pmac** [comment]
Ah. `s/Firefox Develop Edition/Firefox Developer Edition/`. Took me a min to see it. Thanks for the report!

**Comment by pmac** [comment]
Rolling out to prod now. Should be fixed in the next 15 min or so. Thanks again!

**Comment by SeburoSUMO** [comment]
Wow, thank you.  I know it is not a massive thing, but for this contributor, it is still cool to a) help fix mozilla.org b) to see this happen across time zones and c) to see it go live so quickly.

@pmac Keep being awesome.

**Comment by pmac** [comment]
You too @SeburoSUMO! Great catch!
