### ISSUE TITLE
Update "contact" section of Mozilla Privacy Policy

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6820]
## Description

Update the copy in https://www.mozilla.org/en-US/privacy/ with the copy and links in [this doc](https://docs.google.com/document/d/19EA0GrF4p0QHqaznkNnuNzm8DyJ18PxBKHgKlewJLf8/edit?usp=sharing)

**Comment by peiying2** [comment]
Do we know how many languages we need, though German is P1?

**Comment by ejregithub** [comment]
@peiying2 - Mika conveyed that: "it should align with all languages that we have localized the privacy policy to"  I would think, if prioritization beyond DE is needed that addressing other EU locales first would be prudent.

**Comment by peiying2** [comment]
@ejregithub Which live page is this so I can check the other locales?

The thing is on legal github: https://github.com/mozilla/legal-docs, some have the address in the files themselves (different format and different versions). I am wondering what this PR covers. Let me reply in the email.
