### ISSUE TITLE
Determine the fate of the /technology page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6824]
The [technology page](https://www.mozilla.org/en-US/technology/) hasn't been updated in a long time. We no longer link to it from the global navigation, and we're now replacing links to it from the home page pointing to https://labs.mozilla.org/ instead.

Unless we plan on updating this content, I think we need to consider what to do with this page long term, especially as we are now using https://labs.mozilla.org as the hub to talk about these types of projects.

Options are:

1. We keep the page as-is and let it grow stale. There may be some SEO benefits here, but I'm not sure if it really does Mozilla any huge favors if the content is outdated and no longer reflects how we are focusing this type of work. The page is also not using Protocol, so keeping it around is not debt-free.
2. We decommission the page and redirect it to https://labs.mozilla.org/.
3. We re-purpose the page as an index for all the recently added SEO pages (porting it to Protocol):
    - https://www.mozilla.org/en-US/technology/what-is-a-browser/
    - https://www.mozilla.org/en-US/technology/update-your-browser/
    - https://www.mozilla.org/en-US/technology/incognito-browser/
    - https://www.mozilla.org/en-US/technology/browser-history/
    - (and soon to be more)
4. We keep the current purpose of the page, redesign it and update the content (porting it to Protocol).

My preference would probably be 3, as creating all these orphaned pages probably isn't great for SEO anyways.

Interested in @rraue's thoughts here.

**Comment by alexgibson** [comment]
One key point to consider here: https://labs.mozilla.org/ is only in English.

**Comment by craigcook** [comment]
The technology landing page is prominently linked from the main nav on the blog theme but we can update that easily, depending on what we decide to do here.

**Comment by hoosteeno** [comment]
Proposal:

- [ ] Redirect the root technology page, https://www.mozilla.org/technology/, to labs.mozilla.org.
- [ ] Move the sub-pages of the technology page, what-is-a-browser/, update-your-browser/, incognito-browser/ and browser-history/ to www.mozilla.org/firefox/browsers/, and redirect each page to its new home.

**Comment by rraue** [comment]
I like that. We need to think about how to link these pages but I think
that’s the best solution.
-- 
______
Send via mobile

Raphael Raue
Global Head of Seo
www.mozilla.org

twitter.com/raue

**Comment by alexgibson** [comment]
I think then we can split this out into two issues.

1. Retire /technology/ and redirect to labs.
2. Move sub pages to live under /browsers/

I'll file a new issue for 2, and then work on removing the landing page here.
