### ISSUE TITLE
Mozilla legal contact update missing variable in localizable string

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#6826]
## Description
PR 6821 update missing variable in localizable string

Describe the issue that you're seeing.
See comment in the https://github.com/mozilla/bedrock/pull/6821/files#r256880657

### Expected result
Need variable in the localizable string to reference back to the URL

@amychurchwell; @craigcook

**Comment by amychurchwell** [comment]
Will submit PR shortly.

**Comment by craigcook** [comment]
I don't think this is correct. This is the code, with added indentation for clarity:

```
{% if l10n_has_tag('privacy_email_2019') %}
  <p>
    <a href="https://app.onetrust.com/app/#/webform/4ba08202-2ede-4934-a89e-f0b0870f95f0">
      {{ _('See here for Data Subject Access Requests.') }}
    </a>
  </p>
 {% endif %}
 ```
The entire string is contained inside the link, the link is not part of the string itself. There was an earlier version where it was but we changed that in a later commit. What actually got merged is above.

**Comment by peiying2** [comment]
@craigcook You are right. I should have not included the link when I copied the string. Having said that, this is what's in the email thread: 

See [here](link) for Data Subject Access Requests. 

If I just copy the above {{ _('...., the variable or link won't be in the string.

**Comment by peiying2** [comment]
Correct the issue subject/description.

**Comment by craigcook** [comment]
> @craigcook You are right. I should have not included the link when I copied the string. Having said that, this is what's in the email thread:
> 
> See [here](https://app.onetrust.com/app/#/webform/4ba08202-2ede-4934-a89e-f0b0870f95f0) for Data Subject Access Requests.
> 
> If I just copy the above {{ _('...., the variable or link won't be in the string.

That was the original request, but we deviated from it because "here" is terrible link text. It doesn't describe the link destination and is a much smaller target, making it bad for accessibility and user experience. So we made the entire thing one link because it's better than what they originally asked for.

We can still certainly structure it with a variable but it should still be one complete string enclosed in a link:

```
{% trans onetrust='https://app.onetrust.com/app/#/webform/4ba08202-2ede-4934-a89e-f0b0870f95f0' %}
  <a href="{{ onetrust }}">See here for Data Subject Access Requests.</a>
{% endtrans %}
```

**Comment by craigcook** [comment]
Alright, we sorted out the confusion. The code we ultimately committed didn't exactly match what was requested, but I think we improved on that request and still accomplish the goal. So we're all good to go, no further changes required. Sorry!
