### ISSUE TITLE
TemplateDoesNotExist: firefox/new/compare/scene1-ie-1.htm

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#6833]
## Description

We are seeing the error message in the issue description in production: https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/5220570/

The template in question was removed in https://github.com/mozilla/bedrock/pull/6755 but is still referred to in one branch of the view: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L743

**Comment by jgmize** [comment]
In the ~5.5 hours this has been in production, we have seen 93 instances of this error so far, so fortunately this is a relatively rare branch.

**Comment by stephaniehobson** [comment]
Merged, I'll leave it up to you if you want to push tonight.
