### ISSUE TITLE
Firefox Concert page does not send `entrypoint` and `form_type` when calling /metrics-flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/bedrock#6839]
## Description

When calling FxA's `/metrics-flow` endpoint, neither `form_type` nor `entrypoint` are specified, these are both used to track top of funnel metrics. Without `form_type=email`, we won't log a `screen.enter-email` event within Amplitude.

### Steps to reproduce

1. Open https://www.mozilla.org/en-US/firefox/concerts/
2. Look at the `params` tab in the network console for https://accounts.firefox.com/metrics-flow

<img width="523" alt="screenshot 2019-02-19 at 11 08 37" src="https://user-images.githubusercontent.com/848085/53010865-d81a6e80-3436-11e9-9c33-a0b6fd1d1def.png">

### Expected result

`params` should include both `entrypoint` and `form_type`. `form_type` should be the string `email`, `entrypoint` a short descriptor that validates according to the rules in https://mozilla.github.io/application-services/docs/accounts/metrics.html#descriptions-of-metrics-related-query-parameters.

### Actual result

They aren't sent.

### Environment

Firefox 65.0.1 on OSX

**Comment by alexgibson** [comment]
Thanks for reporting @shane-tomlinson, I'll see if I can issue a fix for this today.
