### ISSUE TITLE
The font used in the home page is not full internationalized

### ISSUE THREAD

**Issue by pierreneter** [mozilla/bedrock#6844]
## Description

Texts include diacritics looks rather bad in intro section. You can see:

![2019-02-22 2](https://user-images.githubusercontent.com/12815768/53190172-94dd1d00-363b-11e9-8009-7230c8bb7fab.png)
I think this font don't (`Zilla Slab`) support or not include path support for Vietnamese. 

### Steps to reproduce

Right at homepage: https://www.mozilla.org/vi/

### Expected result

The words and punctuation marks are displayed normally.

### Actual result

The texts is broken.

### Environment

What browser and operating system are you using?

Chrome, Windows 10

**Comment by craigcook** [comment]
We should specify an alternative locale-specific font for Vietnamese that can supersede Zilla Slab (we do this for [several other locales already](https://github.com/mozilla/bedrock/tree/master/media/css/l10n)). Is there a preferred system font? Or is there an open webfont with the right character set that might have a similar "feel" to Zilla Slab?

**Comment by pierreneter** [comment]
Ok. right, i will find a font look like Zilla Slab and use it instead of Zilla Slab

**Comment by craigcook** [comment]
[Roboto Slab](https://www.fontsquirrel.com/fonts/roboto-slab) doesn't look bad and supports Vietnamese. We can also fall back to Open Sans, which also supports Vietnamese and we already use it elsewhere.

**Comment by pierreneter** [comment]
Roboto Slab doesn't support mix of 2 style like: `RegularItalic`, `BoldItalic`, etc... which are being used in in `Zilla Slab`, i'm finding another `Slab`

**Comment by pierreneter** [comment]
ps: https://github.com/mozilla/bedrock/blob/master/media/css/pebbles/includes/fonts/_zilla-slab.scss#L29

**Comment by pierreneter** [comment]
[Rokkitt](https://www.fontsquirrel.com/fonts/rokkitt) It look like `Zilla Slab`, I think I will choice it

**Comment by pierreneter** [comment]
![2019-02-23](https://user-images.githubusercontent.com/12815768/53258906-58272980-3700-11e9-8a61-81cdde0723e0.png)

I tried it and felt it was hard to read, I think going back to `Open Sans` is the best choice.
