### ISSUE TITLE
D&I 2019 - images Mozilla Foundation

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6847]
## Description

Update images used for MoFo D&I with new data

### Estimates

| Estimates |  |
| ------------- | ------------- |
| PM | 1 hour |
| ENG | 2 hours |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] It's done

#### Tasks
- [x] Update images used for MoFo D&I with new data

**Comment by craigcook** [comment]
Already done and uploaded to https://drive.google.com/drive/u/1/folders/16qUpTXiIaY3AOc8pFykLPOwhRSLoU7g6

I've pinged Michael Aukland to review them for accuracy and to let me know if he needs any tweaks. We can keep this issue open for the moment until we get final signoff but the initial work is complete at the time of this comment.

**Comment by ejregithub** [comment]
Excellent @craigcook -  I see you put in two hours for Eng time, thank you!

**Comment by ejregithub** [comment]
Done on 2/22
