### ISSUE TITLE
`js/base/object-assign-polyfill.js` in common bundle is 404

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6848]
## Description

In the process of working on upgrading Gulp it has revealed a 404 JS file in our base bundle:

https://github.com/mozilla/bedrock/blob/master/media/static-bundles.json#L1605

It looks like the file exists, but the filename is misspelt:

https://github.com/mozilla/bedrock/blob/master/media/js/base/ojbect-assing-polyfill.js

### Steps to reproduce

Our current gulp task paves over this error silently (this will be fixed in v4), so it's hard to notice. But I'm guessing as this polyfill is missing, there will be some impact on older browsers that need it?

### Expected result

The polyfill should be present in the base bundle.

### Actual result

The polyfill is omitted silently. I'm not clear on the effects this might be having - any clues @jpetto?

### Environment

Should be reproducible on any local bedrock installation.

**Comment by jpetto** [comment]
Wow, two typos in one file name. Nice job by me.

The IE family (but not Edge) are the only browsers without native support for `Object.assign`, which would have had zero impact in our case, as we are only using this ES6 feature in `stub-attribution-macos.js`, which does [platform detection to restrict to macOS users](https://github.com/mozilla/bedrock/blob/master/media/js/base/stub-attribution-macos.js#L110).

Which begs the question - do we need the polyfill at all? It was originally implemented before we knew the macOS platform restriction. I think the answer is no, we do not need this polyfill. Will file a PR.

**Comment by alexgibson** [comment]
Ah, that makes sense. I was trying to workout why we needed it in the base bundle and couldn’t quite piece it together. I think your suggestion of removing it makes sense, thanks @jpetto
