### ISSUE TITLE
Pre/post test - Design test on Blog: Solid d/l button

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6856]
## Description

Make the download button solid. We believe that making this change to the download button would make it easier to see and increase downloads on the blog. The button becomes solid when the user mouses over it. We would like to test whether or not it performs better as solid and it if impacts the article completion rate.

[manapage experiment write up](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90739196)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1/2 hour |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Button is solid blue, no mouse over

#### Tasks
- [x] Make the download button a solid blue

**Comment by craigcook** [comment]
The button has been made solid.

**Comment by ejregithub** [comment]
done, live, closing

**Comment by hoosteeno** [comment]
Can someone point me at the measurements for this?
