### ISSUE TITLE
Debug contact section on Mozilla privacy policy

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6863]
The German privacy policy has English copy at the bottom of the contact section. It does not appear to be a missing localization; it appears to be a problem in the template. It may be happening in more locales, not just German.

Please debug, fix ASAP.

**Comment by hoosteeno** [comment]
https://www.mozilla.org/de/privacy/ is the page. Here is the problem: 

![screen shot 2019-02-27 at 4 10 05 pm](https://user-images.githubusercontent.com/94519/53529553-31734500-3aaa-11e9-87d9-c66aaa5f0b39.png)

**Comment by craigcook** [comment]
Fix is live in production: https://www.mozilla.org/de/privacy/

![image](https://user-images.githubusercontent.com/205591/53596124-ea418e80-3b53-11e9-8ef4-92a4486461cc.png)
