### ISSUE TITLE
Update /firefox with new branding

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6865]
Update the Firefox Desktop landing page at `https://www.mozilla.org/en-US/firefox/` with a temporary English only page that reflects the new brand.

**Comment by mrkwvr** [comment]
here are the design assets
[FX-Quantum-assets.zip](https://github.com/mozilla/bedrock/files/2920868/FX-Quantum-assets.zip)

**Comment by stephaniehobson** [comment]
Up on [demo/shobson](https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/) for design review.

**Comment by dzingeek** [comment]
@stephaniehobson and @mrkwvr just a few things. 

**Desktop View Specific**
- [ ] - Firefox privacy notice is too far to the right on Chrome. [Image for reference](https://user-images.githubusercontent.com/3740746/54571545-6fc09d80-49a0-11e9-9474-3eb9c51cdfda.png)
- [ ] - hero image needs to be updated @mrkwvr please supply Stephanie updated image when available 

**Mobile (phone) View Specific**
- [ ] - Can we left align the copy on mobile (body copy should be default moving forward)? We can keep the hero section centered if needed @mrkwvr it's your call please advise.

**Mobile (tablet 1024) View Specific**
- [ ] - Can we "fix" how quantum is butted right up to the purple blob? (this happens at 1024 breaking point) [Image for reference ](https://user-images.githubusercontent.com/3740746/54571535-5c153700-49a0-11e9-92f3-aa2a08577727.png)
- [ ] - The image is really tight to the copy. [Image for refernece](https://user-images.githubusercontent.com/3740746/54571541-633c4500-49a0-11e9-8191-9f4d35e73d9c.png)
- [ ] - Can we move button to be below the headline? Assuming 1024 is a standard breaking point. [Image for refernece](https://user-images.githubusercontent.com/3740746/54571517-46077680-49a0-11e9-8369-a8bbc1a2454c.png)

**Comment by stephaniehobson** [comment]
> Can we move button to be below the headline? Assuming 1024 is a standard breaking point. 

The break points are: 320, 480, 768, 1056, 1312. I'd rather not make custom layout modifications for this. Would making the text smaller help?

**Comment by dzingeek** [comment]
oh, my mistake didn't realize that 1056 was the breakpoint and not 1024...nope don't make a custom layout mod. making the text smaller might help yes, is this a custom thing though? trying to avoid too many custom elements if possible.

**Comment by stephaniehobson** [comment]
It's already got a larger than usual font on it so tweaking the font is no trouble :)

**Comment by dzingeek** [comment]
@stephaniehobson here is the updated headline for the [FxA section](https://user-images.githubusercontent.com/3740746/54842893-62e9c580-4c90-11e9-912d-37969bb16f96.png):

"Opt in to a Firefox account"

**Comment by stephaniehobson** [comment]
After the test I need to make a few small changes. I missed adding links to the customization section and the submenu. Natalie has requested a few copy updates too.

**Comment by stephaniehobson** [comment]
The test results showed a drop in downloads and so we would like to run another round of tests as outlined here: https://docs.google.com/document/d/1b17PXV5rZa7dEHN9u1_gJa7ZlLHXgkTrQh-Ztp8y_Ck/edit#

**Comment by stephaniehobson** [comment]
@hoosteeno given that I'm back on the websites team I think it's now up to you to prioritize the experiment for getting this work published.

There were 5 factors that the team identified to test:
1) Remove "Quantum" from the branding.
2) Add the word browser in the hero.
3) Communicate "new" in the hero.
4) Add a product image in the hero.
5) Review the copy with an eye for understand-ability, especially from a non-native English speaking perspective.

I think #5 is not possible anymore with the copy writers busy on trailhead. You have expressed disinterest in running headline experiments before and that's what 1-3 are essentially. 

Rather than running and a-e test one option would be to make all the changes to the same version and run a second a-b test.

**Comment by hoosteeno** [comment]
@stephaniehobson is there any reason to think the designs here will land on the website? Why wouldn't we land designs like Trailhead's, instead?

**Comment by stephaniehobson** [comment]
@hoosteeno I have not heard any mention of including /firefox in the trailhead work. If we shelve this work I don't expect an update before July.

**Comment by stephaniehobson** [comment]
Also, if the follow up experiment isn't going to happen we should pull the experiment code out of bedrock.

**Comment by dzingeek** [comment]
[Sketch file](https://share.goabstract.com/31ef3279-7899-43e6-9cc4-d3f905056529) with an updated hero image that includes the browser
[png](https://user-images.githubusercontent.com/3740746/57032847-28186d00-6c00-11e9-858d-7132064bcb09.png) for reference
[location](https://user-images.githubusercontent.com/3740746/57032824-19ca5100-6c00-11e9-986a-0ffcf1a2b760.png) of page within the sketch file

**Comment by stephaniehobson** [comment]
Done in https://github.com/mozilla/bedrock/pull/7776
