### ISSUE TITLE
Gulp doesn't copy over newly added files to /media once already running.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6874]
## Description

When running bedrock locally, Gulp doesn't copy over new files that get added to `/media/` once already running. In order to pick up newly added files, you must currently stop and start Gulp again.

### Steps to reproduce

1. Start bedrock using `make run` and wait for the gulp task to initialise.
2. Add a new image file to `/media/`
3. Try and load that image file in a page.

### Expected result

The image should load correctly.

### Actual result

The image is 404.

It looks like we need to add another event handler to the [`assetsWatch()`](https://github.com/mozilla/bedrock/blob/master/gulpfile.js#L163-L184) task. Currently we only listen for the `change` event, which works only on existing files. I think we also need an `add` event listener.

Docs: https://gulpjs.com/docs/en/api/watch#chokidar-instance

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
