### ISSUE TITLE
new welcome page experience for AArch64

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6876]
## Description

Firefox is going to be the default, pre-installed browser on certain Windows machines. We need to welcome and provide information to users when the first open Firefox in this scenario.

Target market entry is June

[Master project doc
](https://docs.google.com/document/d/1ud0V548_8vSqwkoUU-ZsXbC5SCEFMOtd9086xwJtUE8/edit#)
### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
@ejregithub is this issue still relevant, can it be closed?

**Comment by ejregithub** [comment]
Yes, this languished - we've had no follow up from Romain on this.
