### ISSUE TITLE
Update /firefox/installer-help/

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#6882]
## Description

Redesign and update https://mozilla.org/firefox/installer-help/

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by amychurchwell** [comment]
Current design of page:
<img width="1066" alt="screen shot 2019-03-04 at 12 01 58 pm" src="https://user-images.githubusercontent.com/30483988/53759529-60583500-3e75-11e9-9508-05ab21d0f961.png">

**Comment by amychurchwell** [comment]
Design of page from release channel
<img width="1064" alt="screen shot 2019-03-04 at 2 49 29 pm" src="https://user-images.githubusercontent.com/30483988/53768134-c43a2800-3e8c-11e9-9201-4f546f07949c.png">

**Comment by alexgibson** [comment]
This page is still using Sandstone, so I'm adding this to the roadmap. If there are no plans to redesign it, then we'll port it instead.
