### ISSUE TITLE
Fork /new for Softonic in Tier 1 locales

### ISSUE THREAD

**Issue by Kiiirby** [mozilla/bedrock#6893]
## Description

Hi! Requesting that the current version of the /new pages in our Tier 1 locales (US, CA, DE, FR, UK) be forked for Softonic. Providing a custom URL to Softonic will bring their traffic into the visible funnel, and give us control over the user flow through install and onboarding.

For the custom URLs, any generic modifier that doesn't explicitly say "Softonic" is great. Maybe something like this (this is an example for en-US)

https://www.mozilla.org/en-US/firefox/new/stc

Thank you!

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
I think we need to disuss the best possible solution for this. Forking our most complex download page doesn't come without technical debt, just like the SEM download page.

**Comment by Kiiirby** [comment]
Hi Alex, Can you please help me understand the risks? By technical debt, do you mean upkeep? Do any better solutions jump out at you?

**Comment by alexgibson** [comment]
I think we first need to understand The requirements a bit better here. It’s not quite  clear to me from the description why you need to fork the main download page. If we can understand the context better, the website team can help you find the most appropriate solution.

**Comment by Kiiirby** [comment]
10-4. I'm double-checking that on my side now and I'll get back to you. Thanks Alex!

**Comment by Kiiirby** [comment]
Hey Alex,

I think all we need is a separate landing page for Softonic. (One we envision looking exactly like the current /new page, which is why we thought of "forking".) This is our intent:

Separate reporting and analysis for Softonic traffic
Custom messaging and experimentation for Softonic traffic

**Comment by Kiiirby** [comment]
What's the least complicated way to achieve or intent?

**Comment by alexgibson** [comment]
If all you need is a URL by which you can gather GA data for Softonic, you don't need an entirely spearate landing page, you can just use a unique URL parameter e.g.

https://www.mozilla.org/firefox/campaign/?xv=stc

If you ever want to do a customised landing page / message based on this `?xv=stc` parameter, we can do that for you too at the time when you need it.

**Comment by alexgibson** [comment]
Also worth considering, we now have a (non-indexed) landing page specifically for campaigns and SEM traffic. You may want to consider pointing to this over /new

https://www.mozilla.org/firefox/campaign/?xv=stc

**Comment by Kiiirby** [comment]
Thanks Alex! Very helpful, I'll take this back to the team. Thanks again.

**Comment by Kiiirby** [comment]
These are the URLs + UTM params Softonic will use:

In US:

https://www.mozilla.org/en-US/firefox/campaign/?xv=stc&utm_medium=affiliate&
utm_source=stc&utm_campaign=stc_[mm]_[yy]&utm_content=[assigned by softonic for each ad placement]

In CA:

https://www.mozilla.org/en-CA/firefox/campaign/?xv=stc&utm_medium=affiliate&
utm_source=stc&utm_campaign=stc_[mm]_[yy]&utm_content=[assigned by softonic for each ad placement]

In DE:

https://www.mozilla.org/de/firefox/campaign/?xv=stc&utm_medium=affiliate&
utm_source=stc&utm_campaign=stc_[mm]_[yy]&utm_content=[assigned by softonic for each ad placement]

In FR:

https://www.mozilla.org/fr/firefox/campaign/?xv=stc&utm_medium=affiliate&
utm_source=stc&utm_campaign=stc_[mm]_[yy]&utm_content=[assigned by softonic for each ad placement]

In UK:

https://www.mozilla.org/en-GB/firefox/campaign/?xv=stc&utm_medium=affiliate&
utm_source=stc&utm_campaign=stc_[mm]_[yy]&utm_content=[assigned by softonic for each ad placement]
