### ISSUE TITLE
Mozilla.Client.getFxaDetails() returns incorrect data if called multiple times in quick succession

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6904]
## Description

There is a race condition bug in `Mozilla.Client.getFxaDetails()` that returns incorrect data.

### Steps to reproduce

Call the function twice in quick succession and you can often see different results:

### Expected result

The data returned should always be accurate and consistent.

### Actual result

The results are often different:

```
Object { firefox: true, legacy: false, mobile: false, setup: false, desktopDevices: false, mobileDevices: false }
```

```
Object { firefox: true, legacy: false, mobile: false, setup: true, desktopDevices: 1, mobileDevices: 1 }
```

The code short-circuits itself, since it creates a reference to `Mozilla.FxADetails` too early, before the first callback returns:

https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-client.js#L352-L367

### Environment

Bug can be encountered using any Firefox desktop channel.

**Comment by stephaniehobson** [comment]
I think you probably have a direction for a solution on this but I wanted to note that since UI Tour only works in FX 29 and above you can use Promises or other new APIs that might help with this.
