### ISSUE TITLE
The /firefox/accounts/ page gives no clear indication that I'm signed-in.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6907]
## Description

If I'm already signed-in to a Firefox Account, the `/firefox/accounts/` page gives no clear indication of this.

### Steps to reproduce

In Firefox for desktop, make sure you're signed into a Firefox Account and then visit: https://www.mozilla.org/en-US/firefox/accounts/

### Expected result

The page should give some clear indication that I'm already signed into my Firefox Account, and then describe what I can do next to make the most of the benefits.

Perhaps somethign like: "Congrats! You're already signed-in to your Firefox Account. Now go get the Firefox mobile app so you can enjoy all the benefits".

### Actual result

All the the main CTA says is "Download Firefox App" and nothing else, which feels a little too brief to be clear (especially seeing as I'm already using Firefox). A little added context to go along with this button could make things a lot clearer?

### Environment

Any Firefox desktop browser that is signed-in to an account.

**Comment by amychurchwell** [comment]
Totally agree. Also, if we are evaluating the design and a dev is picking this up --could we also consider  #6789 while doing this? Semantically, I don't think links were the best choice for this page because they trigger a modal and do not navigate off the page.

**Comment by alexgibson** [comment]
@amychurchwell I think that's a great suggestion too 👍

**Comment by alexgibson** [comment]
WIP copy deck https://docs.google.com/document/d/1nyg_trea3ew3dBMA_GP_kW2Bw5W7T4rAWCzQUH-DvZg/edit?usp=sharing

**Comment by wboucherfischer** [comment]
Here are designs. 
![accounts button 480](https://user-images.githubusercontent.com/50332473/59376210-8b6be380-8d04-11e9-8715-c9fa720b4425.png)
![accounts button 768](https://user-images.githubusercontent.com/50332473/59376211-8c047a00-8d04-11e9-968f-034805124514.png)
![accounts-logged-in-button-1312](https://user-images.githubusercontent.com/50332473/59376212-8c047a00-8d04-11e9-8401-4d8df4411e88.png)
![accounts button v1 1056](https://user-images.githubusercontent.com/50332473/59376213-8c047a00-8d04-11e9-80ce-4846f6e19f41.png)

[Link to file](https://share.goabstract.com/2ce05234-ab46-4865-8334-242d37ba8a66https://share.goabstract.com/2ce05234-ab46-4865-8334-242d37ba8a66)

**Comment by alexgibson** [comment]
This is now up on demo for review: https://www-demo5.allizom.org/en-US/firefox/accounts/

To test signed-in state, set the following options:

1. Type `about:config` in the address bar and hit return.
2. In the about:config page, search for the preference `browser.uitour.testingOrigins`.
3. If the preference exists already, click "Edit". If not, click "Add" (set type to "String").
4. Give the preference a value of `https://www-demo5.allizom.org/`.
5. Visit https://www-demo5.allizom.org/en-US/firefox/accounts/ and if you are signed into your Firefox Account, you should then see the signed-in state.

**Comment by alexgibson** [comment]
@wboucherfischer @claychaffin ^

**Comment by claychaffin** [comment]
Copy question for @hoosteeno @alexgibson @wboucherfischer @craigcook 

Currently our subhead is "See if you’ve been part of another company’s data breach." 
Would this be better or worse? "See if you’ve been involved in an online data breach."
My concern is that "another company's data breach" implies its opposite: that sometimes its our company that suffers the data breach. 
Sort of akin to the "Nixon problem." 
President Richard Nixon infamously said "I am not a crook" and this only introduced/reinforced the idea that he was, in fact, a crook. What do you all think?

**Comment by alexgibson** [comment]
I'll let others weigh in, but your new suggestion for the subhead and its reasoning make sense to me.

**Comment by wboucherfischer** [comment]
it makes sense to me.

**Comment by alexgibson** [comment]
Ok, copy is final.

Screenshot of signed-in state:

![image](https://user-images.githubusercontent.com/400117/59448001-2f848600-8dfc-11e9-9c84-e11f5b429569.png)

Screenshot of signed-out state:

![image](https://user-images.githubusercontent.com/400117/59448062-4f1bae80-8dfc-11e9-8ea6-0012a3d86e47.png)

**Comment by ejregithub** [comment]
Noting we have stakeholder review completed with the final approval to move forward as is.

**Comment by amychurchwell** [comment]
Pull request has been code reviewed & approved! We can merge after all-hands. 😄

**Comment by wboucherfischer** [comment]
![accounts button 480](https://user-images.githubusercontent.com/50332473/59459208-1adec880-8dd1-11e9-9f2a-b6bcb0666644.png)
![accounts button 768](https://user-images.githubusercontent.com/50332473/59459210-1adec880-8dd1-11e9-94b7-350c11f466d9.png)
![accounts-logged-in-button-1312](https://user-images.githubusercontent.com/50332473/59459211-1adec880-8dd1-11e9-9f48-c01d44d251f6.png)
![accounts button v1 1056](https://user-images.githubusercontent.com/50332473/59459212-1b775f00-8dd1-11e9-9c66-376195cebc9c.png)

**Comment by alexgibson** [comment]
This has been reviewed and r+'d, but we're not merging until after all-hands.
