### ISSUE TITLE
Questions on copies for localization

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#6922]
Refer to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1534671 for the pages discussed below. 

1) bedrock/firefox/templates/firefox/features/adblocker.html
The punctuation used on this page are inconsistent with the style defined here: https://design.firefox.com/photon/copy/punctuation.html
a). wrong use of dash: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/features/adblocker.html#L29, #L46
b). Q/A style headings, only this one has a question mark while the rest doesn't. Not consistent.  https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/features/adblocker.html#L65

2). a few technical issues
a). /bedrock/mozorg/templates/mozorg/browser-history.html - the URL shows the path as after .../technology/. https://www.mozilla.org/en-US/technology/browser-history/. Please confirm the correct path for this page.
b). https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/browser-history.html#L8 - missing a template name for l10n: add_lang_files

3). /bedrock/mozorg/templates/mozorg/what-is-a-browser.html - the URL shows the path as after .../technology/. https://www.mozilla.org/en-US/technology/what-is-a-browser/. Please confirm the correct path for this page.  The string extraction script puts this page after mozorg/technology/ while browser-history.lang is under mozorg/.

4). /bedrock/mozorg/templates/mozorg/what-is-a-browser.html - The writing style of this page doesn't comply to the style defined here: https://design.firefox.com/photon/copy/punctuation.html
a). Incorrect grammar: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/what-is-a-browser.html#L30: "... `Depending on how it’s used it bridges nations, ` There should be a `,` (comma): `...it's used, it bridges nations,`
b). Too many to list, not using serial commas (also called Oxford commas).
c). wrong use of dash:  https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/what-is-a-browser.html#L81, #L87, #L94

**Comment by peiying2** [comment]
@craigcook, @alexgibson

**Comment by craigcook** [comment]
I can comment on a few of these. Paging @claychaffin for the rest.

>        a). wrong use of dash: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/features/adblocker.html#L29, #L46

These dashes definitely stand out and it's not a style we've used elsewhere. I would defer to Clay on if this is OK or if we should revise. If we do go ahead with dashes it should be an en dash (–) or em dash (—), not two hyphens.

>        b). Q/A style headings, only this one has a question mark while the rest doesn't. Not consistent.  https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/features/adblocker.html#L65

I think this is correct. The one highlighted is the only heading that is a question; the others are all declarative statements even though they begin with words like "how" and "where".

> 2). a few technical issues
> a). /bedrock/mozorg/templates/mozorg/browser-history.html - the URL shows the path as after .../technology/. https://www.mozilla.org/en-US/technology/browser-history/. Please confirm the correct path for this page.

That's the correct URL. However, now that we have several pages under that directory we should consider grouping these templates into a `technology` folder.

> b). Too many to list, not using serial commas (also called Oxford commas).

We don't use serial commas. I know, I prefer them too, but it's not in our house style. If there's a sentence where the lack of a serial comma makes it ambiguous the usual solution is to rephrase the sentence.

> c). wrong use of dash: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/what-is-a-browser.html#L81, #L87, #L94

These aren't completely incorrect, but the dash is a stylistic choice where a comma or no punctuation might do just as well. I think it's probably fine but we should confirm with Clay.

**Comment by ejregithub** [comment]
@claychaffin - can you please see Peiying's comments above and comment back here?

**Comment by ejregithub** [comment]
@djst - adding you here to keep you informed.

**Comment by claychaffin** [comment]
@ejregithub @hoosteeno 

Per Peiying's request in 1(a) above,  please update the hero section subhead on https://www.mozilla.org/en-US/firefox/features/adblocker/ 

Code: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/features/adblocker.html#L29

Copy deck: https://docs.google.com/document/d/1X8mc2GAEN9OKks3NZnRmfk44gUXrC6APpYpJrS1WSrg/edit?usp=sharing

**Comment by peiying2** [comment]
@claychaffin grammar related:
https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/what-is-a-browser.html#L36 `...everyone have`, should be `everyone has`.

https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/what-is-a-browser.html#L30: `... Depending on how it’s used it bridges nations,`  There should be a , (comma): `...it's used, it bridges nations,`

**Comment by claychaffin** [comment]
Hi Peiying, I've filed https://github.com/mozilla/bedrock/issues/7032
to address the issues you shared here. Thank you.
