### ISSUE TITLE
Updated Mozilla footer to include Firefox Instagram account

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6923]
## Description

[https://bugzilla.mozilla.org/show_bug.cgi?id=1495745](https://bugzilla.mozilla.org/show_bug.cgi?id=1495745)
Updated Mozilla footer to include Firefox Instagram account

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by stephaniehobson** [comment]
Just to note that it was an intentional architectural decision to only link to the Mozilla social accounts in the footer. It's not a quick change to add a second instagram account* and @dzingeek should be consulted before it's done.

* Well, it is quick to add a second logo but two instargram logos is confusing so how do users tell them apart?

**Comment by dzingeek** [comment]
Curious on the ask? The reason behind only having moz stuff in the footer is to help with confusion on what is moz and what is fx...if I know more about this ask I might have a better suggestion or at least a more informed one.

**Comment by ejregithub** [comment]
I originally thought the request came in because there was no Instagram link at all.  Clearly we need to stick with what we've got. If the Firefox Instagram can be provided in the Firefox site /firefox/*, other than in the footer, great. But we won't solve that here, so I'm closing this and the bug.
