### ISSUE TITLE
Experiment: Newsletter page pre-download on /new

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#6939]
## Description

This proposal suggest adding an interstitial page after a user clicks "download" on the /firefox/new page and the start of their download. This page would prompt users to pick between downloading Firefox or simultaneously downloading Firefox and signing up for an email newsletter.

**Newsletter page**
![image](https://user-images.githubusercontent.com/5924575/54638897-57588d80-4a49-11e9-92f6-07d20548d1dc.png)

**/thanks (if a user selects the "newsletter" option**
![image](https://user-images.githubusercontent.com/5924575/54637916-06479a00-4a47-11e9-8c7e-7e59bcf1ef87.png)

**/thanks (if a user selects the "continue with download" option)**
![image](https://user-images.githubusercontent.com/5924575/54637934-0f386b80-4a47-11e9-8374-8914058cc6f4.png)

### Note
This is the third in a series of experiments. See also:
#6935 - Experiment: Accessibility improvements on /thanks
#6938 - Experiment: Newsletter modal on /new

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
@michaelmccombie one suggestion that may add a bit less complexity here could be to avoid a new interstitial page (i.e. from /new -> /newsletter -> /thanks).

It could be simpler to go from /new -> /thanks like it does currently, but where the newsletter is now displayed. We could then show some new content (e.g. "thanks your download will now begin") once the visitor interacts with the form, if that makes sense?

**Comment by alexgibson** [comment]
This user flow is now up on demo:

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=d

Page load:
![image](https://user-images.githubusercontent.com/400117/55238059-7dd9ae00-522b-11e9-9656-3e423a7fe7fd.png)

Click download:
https://www-demo1.allizom.org/en-US/firefox/download/thanks/?xv=pre-dl&v=d
![image](https://user-images.githubusercontent.com/400117/55238238-e2950880-522b-11e9-9685-8a35a045d014.png)

Newsletter success (initiates download):
![image](https://user-images.githubusercontent.com/400117/55238140-ab265c00-522b-11e9-9816-54a33292bc90.png)

Newsletter no thanks (initiates download):
![image](https://user-images.githubusercontent.com/400117/55238186-c729fd80-522b-11e9-974d-c073f9378305.png)

**Comment by rraue** [comment]
I don't see any SEO concerns the way its implemented on allizom right now

**Comment by alexgibson** [comment]
This experiment is in the wild and will be finishing shortly. Closing this issue out.
