### ISSUE TITLE
Add subhead to hero section on Mozilla.org for en-US homepage

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#6942]
## Description
Add subhead to hero section on Mozilla.org

The Mozilla.org hero section headline "Live your life. Own your life." is a high-level, aspirational message and by itself may not be enough for visitors to understand what is being offered--a Firefox Account-- and why they might want to click "Learn More".  

LINK TO THE COPY DECK:
https://docs.google.com/document/d/1G3N2o886KrB5kA06OE7ESUKGLW9LwXQBNd8OQxVqJ6A/edit?usp=sharing

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ]  Subhead is added

#### Tasks
- [ ] Add the new copy found here - https://docs.google.com/document/d/1G3N2o886KrB5kA06OE7ESUKGLW9LwXQBNd8OQxVqJ6A/edit?usp=sharing

**Comment by ejregithub** [comment]
@hoosteeno - this likes a very quick dev task. Could we consider this to be done during the remainder of Sprint 2?

**Comment by hoosteeno** [comment]
@amychurchwell , could you take a look at this one? Are there any l10n ramifications that we need to program around?

**Comment by hoosteeno** [comment]
@amychurchwell can you also check the instrumentation on the "Learn More" button? I want to be sure we're measuring well there.

**Comment by alexgibson** [comment]
Note that this CTA also features on the German home page, and shares much of the same code. If we're updating things, we should probably do the same there too? 

It may require finding a translated string?

**Comment by ejregithub** [comment]
@amychurchwell - We can do en-US and DE separately, they are not dependent on one another.
