### ISSUE TITLE
Untranslated string on `/66.0/whatsnew/` page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6947]
## Description

The "Congrats! You’re using the latest version of Firefox." string is untranslated on `/firefox/66.0/whatsnew/`

### Steps to reproduce

1. Visit https://www.mozilla.org/de/firefox/66.0/whatsnew/ (or any other non-English locale)

### Expected result

The string should be translated e.g. "Perfekt! Du hast die neueste Version von Firefox am Start."

### Actual result

The string is shown in English for all locales.

### Environment

Any Firefox browser.

**Comment by peiying2** [comment]
Looks like this is resolved. Thanks @amychurchwell for verifying! We can close the issue now.
