### ISSUE TITLE
Dry-market only sending traffic to v=1 and v=c

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6958]
## Description

The dry market test we set up should be splitting a small number of users between 6 experimental treatments and a control. [Right now it looks like it's only splitting users between the control and 1 variation (v=c)](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a36116321w64087799p65789850/_u.date00=20190313&_u.date01=20190319&_.sectionId=&_.useg=&_.goalOption=2&explorer-table.advFilter=%5B%5B0,%22analytics.landingPagePath%22,%22RE%22,%22en-US~2Ffirefox~2Fnew~2F%5C%5C%3Fxv=priv-dmt%5C%5C%2526v=%5B1abcdef%5D$%22,0%5D%5D&explorer-table.plotKeys=%5B%5D). (I verified this in unsampled reporting.)

Is this experiment working properly?

**Comment by hoosteeno** [comment]
@alexgibson can you check analytics in the a.m. and, if they still only include 2 variations, take a look for problems?

**Comment by alexgibson** [comment]
I can see data starting to show up for `v=1`, `v=c`, `v=a` and `v=e`. There's only a 0.6% chance of someone seeing variations a-f. It may just take a little while for this data to start showing up in GA.

From what I can see, I can't see any misconfiguration in the experiment.

![image](https://user-images.githubusercontent.com/400117/54741162-71af7a00-4bb5-11e9-800a-3e474a4d6f30.png)

**Comment by alexgibson** [comment]
It sounds like we [have enougn data](https://github.com/mozilla/bedrock/issues/6985) for this experiment, so I'm going to close this issue.

**Comment by hoosteeno** [comment]
We believe there is a bug in TrafficCop. This experiment had 6 variations that should have received 0.6% of traffic each, but [only 3 did](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a36116321w64087799p65789850/_u.date00=20190317&_u.date01=20190327&_.sectionId=&_.useg=&_.goalOption=2&explorer-table.advFilter=%5B%5B0,%22analytics.landingPagePath%22,%22RE%22,%22en-US~2Ffirefox~2Fnew~2F%5C%5C%3Fxv=priv-dmt%5C%5C%2526v=%5B1abcdef%5D$%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/): v=a, v=c, v=e. The spacing of these (even-numbered variations b, d and f were excluded) suggest a bug in a loop, perhaps related to TC's 1% floor. We should fix this bug, but it is not so urgent that we need to drop everything to fix it.

**Comment by alexgibson** [comment]
Do we have a resolution here? What are the next steps?

**Comment by hoosteeno** [comment]
> Do we have a resolution here? What are the next steps?
https://github.com/mozilla/trafficcop/issues/11
