### ISSUE TITLE
High Res img helper gives big images to mobile

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6962]
## Description

We use srcset to provide high res versions of images. On small high res screens when the images are scaled down to half their size or more the low res version of the image could serve this purpose.

We can probably address this with the sizes attribute.

### Steps to reproduce

Load site on mobile screen.

### Expected result

Smallest possible images served.

### Actual result

Largest possible images served.

### Environment

Tested in Firefox on desktop with responsive design mode. That's how srcset works though so I would expect it to behave the same on all supporting browsers.

**Comment by alexgibson** [comment]
Closing this issue in favour of https://github.com/mozilla/bedrock/issues/11833
