### ISSUE TITLE
 Add subhead to hero section on Mozilla.org for DE homepage

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6980]
Description: Add a subhead to the hero section in the DE homepage

**Tasks**
- [x] Get DE localized string (@ejregithub)
- [x] Add the new string to the subhead in the DE homepage hero section

**Comment by alexgibson** [comment]
Copy is "Nimm Lesezeichen und Privatsphäre-Features mit auf jedes Gerät – mit deinem Firefox-Konto."
