### ISSUE TITLE
L10n comment is truncated when running `./manage.py l10n_extract`

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6990]
## Description

I'm trying to extract a lang file for a new l10n comment that was added to the `/firefox/new/scene1.html` template in https://github.com/mozilla/bedrock/pull/6977, but the comment is not extracted correctly.

### Steps to reproduce

Run `./manage.py l10n_extract bedrock/firefox/templates/firefox/new/scene1.html`

### Expected result

The l10n comment should be extracted fully.

### Actual result

The l10n comment is truncated to `# Firefox account, which unlocks access to all our new products and services.`

### Environment

N/A

**Comment by pmac** [comment]
Thanks Alex. I'll see what I can find.

**Comment by alexgibson** [comment]
@peiying2 is this anything you have prior knowledge of? It seems like a bug to me.

**Comment by pmac** [comment]
When I do the extraction I see in the `django.pot` file the following:

```pot
#. The phrase “Now get everything else Firefox” is in specific reference to a
#. Firefox account, which unlocks access to all our new products and services.
#: bedrock/firefox/templates/firefox/new/scene1.html:157
msgid "You’ve already got the Firefox browser. Now get everything else Firefox."
msgstr ""
```

So something in the .pot -> .lang process is missing the fact that this is a multi-line comment. I'm not sure yet why it's a multi-line comment either, but that appears to be the deal.

**Comment by pmac** [comment]
PR filed. The .pot -> .lang processor just didn't expect more than one line of comment and I guess at some point those started being a thing 🤷‍♂️
