### ISSUE TITLE
Bug 1535640 - Download button on nightly release notes page has blue text instead of white

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7002]
## Description

[Bug 1535640](https://bugzilla.mozilla.org/show_bug.cgi?id=1535640)
Download button on nightly release notes page has bluen text instead of white

### Steps to reproduce

In the bug

### Expected result

Text in the download button should be blue. https://www.mozilla.org/en-US/firefox/68.0a1/releasenotes/

### Actual result

What happened.

### Environment

What browser and operating system are you using?

**Comment by stephaniehobson** [comment]
Will be fixed by #6986.

**Comment by alexgibson** [comment]
This is fixed.
