### ISSUE TITLE
Fix CircleCI integration for PRs

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#7013]
CircleCI is not currently triggering on PRs. We're seeing errors like the following:

![image](https://user-images.githubusercontent.com/161718/55340452-545a9580-546a-11e9-93d1-4e63bbd0bad9.png)

**Comment by jgmize** [comment]
https://github.com/mozilla/bedrock/pull/7012 triggered a CircleCI run, but then other branches started building at the same time, so it's unclear if this was a coincidence.

**Comment by alexgibson** [comment]
Is this something that still needs fixing?

**Comment by jgmize** [comment]
No, this appears to have been a temporary issue on the CircleCI side.
