### ISSUE TITLE
Download tests are hanging

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#7015]
## Description

The download tests are repeatedly hanging. 

- https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1587/pipeline
- https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1588/pipeline
- https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/402/pipeline

Running them in isolation, they passed: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/276/pipeline

**Comment by alexgibson** [comment]
I believe this issue resolved itself, closing,
