### ISSUE TITLE
Epic: Redesign FxA Funnel

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7021]
We need our Firefox Accounts funnel on www.mozilla.org to evolve with our Firefox Accounts suite. In the past several months, we've seen some great improvements and changes that our funnel needs to consider:

* an FxA now has real value to a non-Firefox user. This means our FxA benefits page, which switches the CTA depending on UA, is no longer an optimal landing page for non-Fx users.
* FxA services now include some potential search categories such as "password manager", "[free] file sharing", and perhaps something related to the service provided by monitor. This means we could increase organic sessions on our website by focusing pages on this kind of content.
* Our marketing (in e.g. snippets and email, and probably elsewhere) is aimed at these specific FxA benefits. Conversion rates are far better when upstream marketing and conversion points have very similar CTAs.
* FxA itself requires someone creating an account to be attached to a service; by default, this has been Sync, but that is no longer an appropriate default. This means we'll want to use different defaults specific to the marketing CTA that a new user responded to.

This epic tracks work to redesign this UX to support these new funnels.

**Comment by hoosteeno** [comment]
@dzingeek is this on the brand team's radar at all for 2020? Should we leave this issue open or will a better issue likely emerge from IA reimagining?

**Comment by alexgibson** [comment]
Closing on inactive issue
