### ISSUE TITLE
Change the CTA on the Yandex page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7034]
## Description

Yandex CTA - Change the download button text to make it more clear what the user can expect to get when downloading either the Yandex or vanilla version of Firefox

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Primary and secondary download button CTA copy is replaced with new copy in RU

#### Tasks
- [ ] Update the primary CTA with new copy in RU: ("Download Firefox for Yandex") 
"Скачать Firefox с Яндексом"
-[ ]  Update the 2nd CTA "" with the new copy in RU: ("Download Firefox without Yandex") 
"Скачать Firefox без яндекса"

**Comment by ejregithub** [comment]
I reached to Chris Arnold for copy variations as follows:

1 - "Download Now" - replace with either

"Get Firefox for Yandex"
or
"Download Firefox for Yandex"

2 - "Download Firefox" - replace with either:

"Get Firefox without customizations"
or
"Download Firefox without customizations"

**Comment by alexgibson** [comment]
@ejregithub we need a decision on the copy here, and for those strings to be provided in Russian. Adding a blocked label to this.

**Comment by ejregithub** [comment]
@alexgibson - We can move forward with replacing the primary CTA "Download Now" with:

"Download Firefox for Yandex" = Скачать Firefox с Яндексом

We've not received better copy for the 2nd, so let's leave that out and open a new issue if that comes in.

**Comment by ejregithub** [comment]
Blocker placed back. We're close to the copy for the 2nd CTA so let's do that with the primary copy change.  I'll update this when I have it and remove the blocker at that time.

**Comment by ejregithub** [comment]
And this in now good to go and noted in the Description above:

2nd CTA - Download Firefox without Yandex - Скачать Firefox без яндекса
