### ISSUE TITLE
Update /new and /thanks with new branding, rolling out with an experiment 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7038]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
Moved this to icebox; uncertain how it relates to redesign of these pages for Project Trailhead.

**Comment by alexgibson** [comment]
Closing this issue as the design was superceded by trailhead.
