### ISSUE TITLE
A/B test new brand on /new and /thanks

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7039]
## Description

A/B test new brand on /new and /thanks

Hypothesis: If we put the new branded pages in place of the old ones, the conversion rate will remain steady or improve because the functionality and content is identical, only the colors and fonts are changing.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
Dupe: https://github.com/mozilla/bedrock/issues/7039
