### ISSUE TITLE
Enable WNP in DevEdition channel using WNP 66 content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7043]
## Description

Enable WNP in DevEdition channel using WNP 66 content - https://bugzilla.mozilla.org/show_bug.cgi?id=1540911

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
See also: https://github.com/mozilla/bedrock/issues/7044

**Comment by alexgibson** [comment]
Live in prod:

- https://www.mozilla.org/en-US/firefox/68.0beta/whatsnew/
- https://www.mozilla.org/en-US/firefox/68.0a2/whatsnew/
