### ISSUE TITLE
Remove old references on /firefox/new/

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7046]
## Description

Remove old page references from `/firefox/new/`

https://github.com/mozilla/bedrock/issues/6894#issuecomment-478505182

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] @guyfitzpatrick repoints ads to the following campaign URLs:
  https://www.mozilla.org/en-US/firefox/campaign/?xv=betterbrowser
  https://www.mozilla.org/en-US/firefox/campaign/?xv=safari
  https://www.mozilla.org/en-US/firefox/campaign/?xv=edge
  https://www.mozilla.org/de/firefox/campaign/?xv=berlin
   https://www.mozilla.org/de/firefox/campaign/?xv=aus-gruenden
   https://www.mozilla.org/de/firefox/campaign/?xv=herz
   https://www.mozilla.org/de/firefox/campaign/?xv=geschwindigkeit
   https://www.mozilla.org/de/firefox/campaign/?xv=privatsphare
   https://www.mozilla.org/de/firefox/campaign/?xv=auf-deiner-seite

- [ ] Old references are removed from `/firefox/new/`
    https://www.mozilla.org/en-US/firefox/new/?xv=betterbrowser
    https://www.mozilla.org/en-US/firefox/new/?xv=safari
    https://www.mozilla.org/en-US/firefox/new/?xv=edge
    https://www.mozilla.org/de/firefox/new/?xv=berlin
    https://www.mozilla.org/de/firefox/new/?xv=aus-gruenden
    https://www.mozilla.org/de/firefox/new/?xv=herz
    https://www.mozilla.org/de/firefox/new/?xv=geschwindigkeit
    https://www.mozilla.org/de/firefox/new/?xv=privatsphare
    https://www.mozilla.org/de/firefox/new/?xv=auf-deiner-seite

**Comment by amychurchwell** [comment]
Adding blocked label as development is blocked until confirmation that ads have been repointed to new campaign URLs.

**Comment by alexgibson** [comment]
@guyfitzpatrick can you please provide an estimate for when removing these URLs will become unblocked? Thanks

**Comment by guyfitzpatrick** [comment]
@alexgibson the campaign URLs have now been updated. Please can you confirm that if the old pages get traffic from other sources that they will redirect to the new URL? i.e. https://www.mozilla.org/de/firefox/new/?xv=auf-deiner-seite will redirect to https://www.mozilla.org/de/firefox/campaign/?xv=auf-deiner-seite ?

**Comment by alexgibson** [comment]
@guyfitzpatrick thanks for the update. Our aim is to remove complexity surrounding /new to make our core download page less risk prone, so we don’t plan to maintain legacy redirects to these landing pages once the references are removed. I’d urge you to update wherever possible. 

Note: If a URL does not update, it will default to the regular /new landing page so we won’t risk losing conversions from legacy links.

**Comment by guyfitzpatrick** [comment]
@alexgibson thank you! I just wanted to make sure users don't get a 404, the /new landing page is fine for those updates outside of our control

**Comment by alexgibson** [comment]
Great, thanks again!
