### ISSUE TITLE
Direct support requesters to support forums

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7052]
## Description

1. The [press blog](https://blog.mozilla.org/press/) includes an email address for the support team (Click "Explore"), but we don't provide email support. Please remove the content about emailing support. The revised content should be, "Need help? For any support requests, please [visit our forums](https://support.mozilla.org/)."
2. The [privacy page](https://www.mozilla.org/en-US/privacy/) has a "Contact" section at the bottom which includes an email for "compliance@mozilla.org". This email gets lots and lots of support emails. We should add the support blurb from the press blog to the Contact section to help people find the support forums. **The new Contact section should include the text, "For product support requests, please [visit our forums](https://support.mozilla.org/)."**

**Comment by craigcook** [comment]
I've updated the press blog.

**Comment by ejregithub** [comment]
I pinged Mika to confirm on the privacy page update

**Comment by ejregithub** [comment]
Per Mika, we simply need to add the following copy and link below the contact section, as so:

![image](https://user-images.githubusercontent.com/20547886/77208217-9b48fd00-6ab8-11ea-9c61-563a6f2756be.png)

For product support requests, please [visit our forums](https://support.mozilla.org/).
