### ISSUE TITLE
Extract strings to Pontoon for https://www.mozilla.org/en-US/technology/what-is-a-browser/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7059]

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/7032

**Comment by alexgibson** [comment]
Here are the three pull requests that enable translation:

- https://github.com/mozilla/bedrock/pull/7120
- https://github.com/mozilla-l10n/www.mozilla.org/pull/295
- https://github.com/mozilla-l10n/langchecker/pull/878

**Comment by alexgibson** [comment]
This is now complete and strings have been exposed in Pontoon.
