### ISSUE TITLE
Extract strings to Pontoon for https://www.mozilla.org/en-US/technology/browser-history/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7060]

**Comment by alexgibson** [comment]
@ejregithub are there any priority locales this should be considered for?

**Comment by ejregithub** [comment]
German & French.  (Plus all EN).  Anika is queued to hit Pontoon as soon as the strings are there.

**Comment by peiying2** [comment]
@alexgibson depending on the long term interest in the page, you can use these two examples:

1). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L228  - we only make the page available in these locales.
2). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L297 - we make it available for all locales, but we list the required locales for now. Other communities can ask for their locales at a later time. I will take care of these requests. 
3). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L209 - for all Firefox locales, this is optional. Then you specify the supported locales in the first go around (now). Other communities can ask for it later and I will take care of those.

**Comment by alexgibson** [comment]
The lang files for this page have been extracted and pushed our for translation.
