### ISSUE TITLE
Standardize parameters and values in FxA referrals

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7061]
## Description

When we send traffic to FxA signups, we need to send uniform parameters so measurement is straightforward. 

1. For the `entrypoint` url parameter that we generate and send to FxA servers, please use the following standard format: `domain-point_of_CTA`. Examples from our existing site: 

```
entrypoint=mozilla.org-globalnav, 
entrypoint=mozilla.org-fxa_benefits, 
entrypoint=mozilla.org-firefox_new_modal,
```

We may add other entrypoints later.

2. For datalayer values in FxA links, please use the following standard format ([ref](https://bedrock.readthedocs.io/en/latest/analytics.html?highlight=data-link-type)): `FxA-ServiceName`. Examples from our existing site:

```
data-link-type="FxA-Sync"
```

We may add other data link types later.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Parameters are standardized and code is live

#### Tasks
- [ ] Insert the parameters

**Comment by alexgibson** [comment]
@ejregithub I'm confused what this issue is for. Can you add some more information? Thanks

**Comment by ejregithub** [comment]
This the task to complete the work by adding the new parameters. The parameters are named so we can land this code: mozilla/fxa#693 (comment)

**Comment by hoosteeno** [comment]
I added two comments to the closed card mentioned above. Can we discuss here?

1: @amychurchwell , do you think it would be possible to add to this code a uniform event category for FxA links? Right now, our event instrumentation of referrals depends on labels (e.g. "Get a Firefox Account"), which makes them brittle. If we used a category (e.g. "FxA Referral" or similar) we would not be dependent on a CTA string.

2: The parameters are named, so there is no further reason to delay landing this code: mozilla/fxa#693 (comment)

Note that these parameters imply usage. We can use them when we have variations on a CTA on the same entrypoint, as part of an experiment.

In cases where we don't, we can leave them blank.

All of this suggests that what we send in entrypoint should be uniform and verbose. I'd like to suggest the following uniform examples for the entrypoint parameter, and encourage your feedback:

```
entrypoint=site-page-element
entrypoint=mozilla.org-globalnav
entrypoint=mozilla.org-fxa.features-send.tabs
entrypoint=mozilla.org-wnp66-topbar
entrypoint=mozilla.org-firstrun-footer
```

Then when we have experimental variations, we can use the two new parameters

**Comment by hoosteeno** [comment]
@amychurchwell I updated the description of this issue.

**Comment by hoosteeno** [comment]
This is good to launch.
