### ISSUE TITLE
Excessive whitespace in release notes page

### ISSUE THREAD

**Issue by yoasif** [mozilla/bedrock#7070]
## Description

Saw reports of excessive whitespace: https://www.reddit.com/r/firefox/comments/bcolsf/is_there_a_reason_theres_so_much_whiteempty_space/ on the release notes page. 

It definitely feels like there is too much vertical whitespace between one line release descriptions.

Describe the issue that you're seeing.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/66.0.3/releasenotes/

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

Something more similar to previous design seen in https://web.archive.org/web/20190319160029/https://www.mozilla.org/en-US/firefox/66.0/releasenotes/

### Actual result
Too much vertical whitespace between feature updates in the release notes page. 

### Environment

What browser and operating system are you using?

Firefox nightly on Linux.

**Comment by CuriousGeorgeGTS** [comment]
Same results on Chrome (Windows)
