### ISSUE TITLE
Look different between chrome and firefox.

### ISSUE THREAD

**Issue by junngo** [mozilla/bedrock#7071]
## Description
I use both browser firefox and chrome. I checked, look different between chrome and firefox.
I can see download button on chrome. But I can't see button on firefox.

### Steps to reproduce
- Check on firefox.
- Check on chrome.
URL : https://www.mozilla.org/en-US/firefox/68.0a1/releasenotes/

### Expected result
On chrome
![1_chrome](https://user-images.githubusercontent.com/29684524/56094397-e654aa80-5f0e-11e9-8174-38756508a258.png)

### Actual result
On firefox
![2_firefox](https://user-images.githubusercontent.com/29684524/56094456-99bd9f00-5f0f-11e9-90ef-b440808f78cb.png)

### Environment
Firefox Version 65.0.1 (64-bit)
Chrome Version 73.0.3683.75 (64-bit)

**Comment by alexgibson** [comment]
This is expected behaviour. We don’t Show the download button to Firefox users since they are already using Firefox.

**Comment by alexgibson** [comment]
Oh wait, I’m this case you’re highlighting that we hide the Nightly download button to regular FF users. I’m going to reopen and double check what the intended behaviour should be here. Thanks

**Comment by alexgibson** [comment]
@stephaniehobson @dzingeek can you please advise on what the correct behavior should be here?

**Comment by stephaniehobson** [comment]
I preserved the behaviour that existed before the update, which was to hide the top download button from existing Firefox users. So it is behaving as expected.
