### ISSUE TITLE
Investigate alternate / 1st party analytics

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7083]
## Description

With the rise of adblockers and tracking protection, we should investigate a 1st party, self-hosted, analytics solution. This will become especially useful for user agents that default to privacy always on.

Example: Firefox Nightly with a new profile visiting Mozorg:

<img width="1680" alt="Screenshot 2019-04-16 at 18 10 14" src="https://user-images.githubusercontent.com/400117/56231374-339f5c00-6076-11e9-96b9-f4399c4402e5.png">

**Comment by hoosteeno** [comment]
The code landing in a future version of Firefox will block cookies from certain third party providers identified by Disconnect.me. GA's basic analytics cookies (including GA and GTM) will not be blocked. 

[Analysis here.](https://docs.google.com/document/d/1zekLgbJcH_Qz8g9ZD71o3zlSlGpaoe2UeqwPynOAzAk/edit#)

**Comment by pmac** [comment]
Doh! You're right. I was seeing googletagmanager.com being blocked because I have a local DNS tracking blocker. It works as you describe when I turn that off. My apologies for the churn.

**Comment by alexgibson** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1576673

For posterity, it's bugs like this (^) that drive forward the affirmation to me that we should be investigating other solutions for our analytics. The page mentioned in that bug was a valulable source of measurement for website performance, since it was seen by so many people. Firefox traffic provides a large and diverse audience both in terms of geography and connectivity, and being able to measure and optimize for those users on our website remains an important feature.

Whilst this may not impact our measurement for Skyline, it is something we need to keep prioritized and on the roadmap for bedrock imho.

**Comment by alexgibson** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1578872

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/8482

**Comment by alexgibson** [comment]
Further reading: https://blog.convert.com/analytics-ab-testing-cookies-after-consent-in-europe.html

**Comment by alexgibson** [comment]
I'd like to keep this issue in our minds, so I'm sharing a couple of recent new products that aim to provide privacy-preserving analytics as an alternative to GA:

- https://plausible.io/
- https://www.goatcounter.com/

**Comment by pmac** [comment]
I also found https://usefathom.com/ via https://switching.software/replace/google-analytics/

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9028

**Comment by alexgibson** [comment]
Relevant: there are reports that Safari on the next version of macOS (Big Sur) may block GA by default (even with anonymised IP):

https://appleinsider.com/articles/20/06/22/safari-now-blocks-google-analytics-on-sites-new-privacy-report-feature-shows

**Comment by maureenlholland** [comment]
I believe this was completed in Asana task (Mozilla only): https://app.asana.com/0/1203970207351421/1203970207635769/f
