### ISSUE TITLE
Set up mozilla-org-fr-content-hub-homepage

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7085]
## Description

As with the en-US and DE versions of the homepage, this issue is for setting up the same for FR mozilla-org-fr-content-hub-homepage 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New FR homepage is ready for content by end of the sprint (5/24)

#### Tasks
- [ ] Code FR homepage template with the same card functionality available in en-US and DE versions

**Comment by alexgibson** [comment]
This is live in production: https://www.mozilla.org/fr/
