### ISSUE TITLE
win10sUser not showing up in GA

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7093]
I haven't been able to get win10sUsers to show up in GA. The configuration looks right from GTM/GA side, but there are 0 such users right now. It seems unlikely (but not impossible!) that we simply get 0 visits from 10s users right now.

Since [I can't find docs explaining how to test 10s without buying hardware](https://superuser.com/questions/1427203/is-there-a-way-to-install-windows-10s-in-a-virtual-environment) right now, @alexgibson can you check to see that the dataLayer looks correct in prod?

If you want to check GA yourself, [here's a segment definition](https://analytics.google.com/analytics/web/template?uid=v0mwy82VT7i3-61kqbDWqA) that you can use to import a 10s segment to apply to any report.

**Comment by alexgibson** [comment]
@hoosteeno the only way to test this is on Windows 10 S hardware right now, AFAIK. I'm happy to look into this when I return on Tuesday, but here are some hints in the meantime:

You can see the code in question here: https://github.com/mozilla/bedrock/blob/master/media/js/base/core-datalayer.js#L61-L79

The value returned right now is a boolean `true` or `false`, so GA should be looking for that. When I tested on demo via the GTM link you provided, I could see that value in the dataLayer as `true` on my test device.

I did notice one discrepency - all the other GA functions in this file seem to return `'true'` and `'false'` (as strings, not boolean values weirdly). Perhaps is this something that GA needs?

**Comment by alexgibson** [comment]
@hoosteeno it looks like you may have figured this out, can we close this issue?
