### ISSUE TITLE
Can bedrock/base/templates/includes/lang_switcher.html be removed?

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7101]
## Description

`bedrock/base/templates/includes/lang_switcher.html` doesn't seem to be included anywhere anymore.

**Comment by alexgibson** [comment]
It looks like the footer for both english and non english locales import `/bedrock/base/templates/includes/protocol/lang-switcher.html`, so the answer points to yes. This is likely a stray file that never got cleaned up in the latest footer overhaul.
