### ISSUE TITLE
Write copy for new /all page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7109]
We need to write copy for /all. The product team is building [a positioning crib sheet](https://docs.google.com/spreadsheets/d/1-eRoBpWwYUT5nwn7aPdiOEEa-c6pHvs3vlvwewWNJ1A/edit#gid=0) to contextualize this copy. The page is designed and in code.

**Comment by claychaffin** [comment]
Copy-deck-in-progress. Thanks for the reminder to share this here, @hoosteeno 
https://docs.google.com/document/d/1phOeJaAiy5WlNSLiWKmlcMQiK5K22m1Fel8Uco3-7TE/edit?usp=sharing

**Comment by ejregithub** [comment]
Closing per @claychaffin - the final copy is here - https://docs.google.com/document/d/1phOeJaAiy5WlNSLiWKmlcMQiK5K22m1Fel8Uco3-7TE/edit?usp=sharing
