### ISSUE TITLE
Add switch, and switch to "off", on /firefox pre-download CTA

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7111]
## Description

The pre-download newsletter CTA on /firefox did its most important work during March. We can anticipate a full redesign of the /firefox page in coming months, and we should turn off the CTA while that work is underway. Could we put the /firefox CTA behind a switch, and then switch to off?

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
This feature is already behind a switch, I'll turn it off.

**Comment by alexgibson** [comment]
Disabled in https://github.com/mozmeao/www-config/commit/99f1ae17a642dbd06d861c6553622a2dfada903b
