### ISSUE TITLE
Extract strings for firefox/features/adblocker

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7112]
## Description

Copy updates to firefox/features/adblocker have been merged in https://github.com/mozilla/bedrock/pull/7092
The websites team is beginning to take over string extraction, so there are still some action items on this issue (#6879):

- [ ] Strings are extracted to Pontoon and tagged as optional for localizers
- [ ] Anika on the EU team is notified so she can add strings for the DE version in Pontoon

**Comment by amychurchwell** [comment]
Assigning task to myself since I was the developer on the updates.

**Comment by ejregithub** [comment]
@amychurchwell - can you please close this out, extract the strings now that they've been updated?  
We have our internal DE and FR folks ready to localize it.
This could be a good tutorial or sorts with @Errolyn  ?
