### ISSUE TITLE
Trailhead - Qualitative user tests on designs to increase confidence in its ability to do its job.

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7138]
Estimate: 2

**Comment by wboucherfischer** [comment]
Here are links to usability reports:

[WNP Logged Out State](https://docs.google.com/presentation/d/15IfYiePdr1F_zUwTtR0W74SyAGnoXbZxnlyw-0vIEs8/edit?usp=sharing)
WNP Logged In State [](https://docs.google.com/presentation/d/1oFSrSE6Sc-kesypexqYJMfHblvLfzT-vPV3X9QsUm5A/edit?usp=sharing)
/accounts [](https://docs.google.com/presentation/d/1xct5X9NdSHt00aZIEDcahsJwQRRRJSe9CcKroH_pH3k/edit?usp=sharing)

**Comment by ejregithub** [comment]
Testing complete, reports have been delivered, closing.
