### ISSUE TITLE
A/B Test /new and /thanks designs:

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7140]
Description: test the current versions of the page against the redesigned /new and /thanks

* download + install measures
* build "production ready" in case it's good
* test for non-negative drop
* Traffic cop for routing
* Stub attribution for measuring installs
* A/B test to finish 5/28

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7168
