### ISSUE TITLE
Shut off Fundraising banner to follow Internet Health Report Release on 5/3

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7144]
## Description

Shut off the Fundraising banner that followed Internet Health Report Release in #7047

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] The banner is shut off, no longer shown to users.

#### Tasks
- [x] Flip the switch

**Comment by craigcook** [comment]
Switch flipped in https://github.com/mozmeao/www-config/commit/563e8c7b2133dd286e12bbb0bff5002469816dcf

Will have a PR momentarily to remove the code from bedrock.

**Comment by ejregithub** [comment]
Closing this as the banner has been turned off.
