### ISSUE TITLE
FxA validation on fxa_email_form macro

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7154]
## Description

Work in #7110 (media/js/base/fxa-utm-referral.js) validates parameters through the new `fxa_cta_link` button macro. 
`fxa_email_form` utilizes input fields for parameters:
`<input type="hidden" name="utm_source" value={{ utm_source }} id="fxa-email-form-utm-source" />` which requires additional/different functionality.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Closing in favour of https://github.com/mozilla/bedrock/issues/7585
