### ISSUE TITLE
Review designs for protocol

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7157]
## Description

Let's review designs incoming with an eye to Protocol. Specific questions:
* Are designs using Protocol components where possible? Slight adjustment to designs if necessary seems worthwhile if it takes advantage of existing components.
* Are designs implying things that should be a part of Protocol going forward? If so, let's file issues on the Protocol repo with clear and complete specifications to add them. Include any relevant specs for wide/narrow screens, behavior (e.g. hover states, scroll, click states, etc.).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] WNP 67.0.05 reviewed
- [x] /accounts reviewed
- [x] /new reviewed
- [x] /thanks reviewed

**Comment by hoosteeno** [comment]
I've clarified in the description above that scrutinizing designs for Protocol fit is best for a developer. Devs, please flag designs that could/should use existing protocol. Filing new issues is work best suited to designers. Designers, please file new github issues for reusable components (note: [specs for such issues are forthcoming](https://github.com/mozilla/bedrock/issues/7158)).

**Comment by alexgibson** [comment]
Some notes from the /new and /thanks designs:

- The download button color has changed, and needs updating. I filed https://github.com/mozilla/protocol/issues/380 for this.
- Both the /new and /thanks pages feature [Picto cards](https://protocol.mozilla.org/patterns/molecules/picto-card.html), but they deviate from the spec slightly:
  - On /new there are 3 picto cards, but they all have arbitrary icon sizes (the component only supports a 56x56px icon currently, without manual overrides).
  - On /thanks there are 4 picto cards, again with arbitrary icon sizes. The component doesn't currently support a 4 column layout (three is maximum). The cards on /thanks also don't have individual titles, which the component expects. Only longer descriptions are shown.

I can do manual/custom overrides for all the above items, but we should update Protocol to better fit these needs. Updating the button color is easy, but for the picto cards I'd suggest the following:

- Make it configurable using both a small and large predefined icon size.
- Make it support a 4 column layout.

**Comment by alexgibson** [comment]
The /thanks page also features a new notification bar design:

<img width="653" alt="Screenshot 2019-05-07 at 13 19 11" src="https://user-images.githubusercontent.com/400117/57298717-cad25f00-70ca-11e9-8522-183f7415e25e.png">

This does not currently exist as a component, and also uses a background color that does not yet exist in our token pallet.

**Comment by stephaniehobson** [comment]
This floating box could be added to Protocol too. It's on the WNP and in IRL.

<img width="720" alt="Screen Shot 2019-05-23 at 1 08 50 PM" src="https://user-images.githubusercontent.com/854701/58283075-4afbf400-7d5c-11e9-9776-c30e7c088710.png">

**Comment by stephaniehobson** [comment]
Designs reviewed.

Here are the related issues:
mozilla/protocol#380
mozilla/protocol#358 
mozilla/protocol#357
mozilla/protocol#383
mozilla/protocol#382
mozilla/protocol#385
mozilla/protocol-tokens#53
mozilla/protocol-tokens#51
