### ISSUE TITLE
Update leadership page: Camp

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7162]
## Description

Please replace Dave Camp's bio on the leadership page with the copy in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1549841).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Bio is updated and launched

**Comment by alexgibson** [comment]
It looks like this was done in https://github.com/mozilla/bedrock/pull/7165
