### ISSUE TITLE
FxA utm validation: tests & remaining touchpoints

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7169]
## Description

Close-out of the work in https://github.com/mozilla/bedrock/pull/7110

---

#### Tasks
- [x] Global navigation fxa cta button
- [x] Sign-in links
- [x] Write tests

**Comment by stephaniehobson** [comment]
@amychurchwell Have you started this or is it okay for me to pick it up?

**Comment by amychurchwell** [comment]
@stephaniehobson I haven't yet, feel free 🙂 thank you!

**Comment by stephaniehobson** [comment]
This is taking longer than I expected because (as is inevitable) writing the tests had turned up bugs.

**Comment by amychurchwell** [comment]
@stephaniehobson yeah, it's a bit of a can of worms. 😅

**Comment by stephaniehobson** [comment]
The Sign into Monitor button on the WN 67.0.5 page should be considered when the email forms are updated.

**Comment by ejregithub** [comment]
@amy - can you please apply an Estimate to this card?

**Comment by ejregithub** [comment]
Noting that these tasks were pulled out and complete in #7417 
- [ ] Email-first form
- [ ] Monitor sign-in button

Closing this issue.
