### ISSUE TITLE
Pages referencing missing image are 500

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7175]
## Description

Two pages are currently 500 in production due to a missing image:

- https://www.mozilla.org/en-US/firefox/features/private-browsing/&v=a
- https://www.mozilla.org/en-US/firefox/62.0/firstrun/?xv=firefox-election

`ValueError: Missing staticfiles manifest entry for 'img/firefox/election/icon-menu.svg'`

### Steps to reproduce

Open either of the above URLs.

### Expected result

Pages should display correctly.

### Actual result

The 500 error page is shown.

### Environment

Any browser

**Comment by alexgibson** [comment]
Note: 

- The firefox-election firstrun page can likely be removed entirely.
- The experiment on the features page can also likely be removed.

**Comment by hoosteeno** [comment]
Experiment can be removed. https://github.com/mozilla/bedrock/issues/7176

**Comment by amychurchwell** [comment]
Can firefox/election also be removed?

**Comment by stephaniehobson** [comment]
@amychurchwell No it's been updated with new different content that doesn't reference the old page.
