### ISSUE TITLE
/new &  /thanks - Extract strings to Pontoon for localization

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7177]
## Description

We need to extract strings for /new and /thanks to Pontoon

-  initially just to DE to Anika can localize those - Not sure what needs to be done (Peiying can provide assistance) to limit the file just to DE . . .
- then when DE is done we'll open to the broader community

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Bedrock PR to enable translation: https://github.com/mozilla/bedrock/pull/7187
String extraction PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/296
Langchecker PR: https://github.com/mozilla-l10n/langchecker/pull/881

**Comment by alexgibson** [comment]
Strings are extracted and pushed to production, so closing this as for now this work is complete.

**Comment by ejregithub** [comment]
@alexgibson - please provide your Estimate (or in retrospective, the actual) for this work

**Comment by alexgibson** [comment]
I'd say a 2
