### ISSUE TITLE
String Extraction - email preferences center

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7178]
## Description

Changes are specified in [this document](https://docs.google.com/presentation/d/1lYEG-a30ram5L6pubUXMNyB7A0CNNIbLvFEK0HKBnh0/edit#slide=id.g573fb7b135_0_118).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Strings extracted by 5/21 - in PR [Update mozilla/newsletters.lang](https://github.com/mozilla-l10n/www.mozilla.org/pull/299)

Page launched by 6/3

**Comment by hoosteeno** [comment]
Seealso #7164

**Comment by hoosteeno** [comment]
See light (and optional) UI refresh here https://github.com/mozilla/bedrock/issues/7164#issuecomment-491425124

**Comment by alexgibson** [comment]
@ejregithub can you please provide the final list of locales for translation? The slide deck states:

`N, DE, FR, ES, ID, pt-BR, RU, PL, zh-TW + TBD`

Is that right? And if so, are there any TBDs?

**Comment by ejregithub** [comment]
EN, DE, FR, ES, ID, pt-BR, RU, PL, zh-TW + BG, CS, HU, IT, HU, NL
@alexgibson 
The latter have localized the current version, would like them to be able to update the new strings as well, opt-in.  Localization to 100% is not required. EN will be shown until a string is localized, as it now works in the file.

**Comment by pmac** [comment]
I believe the referenced PR (#7198) is ready for l10n.

**Comment by alexgibson** [comment]
I've extracted strings and opened a PR here: https://github.com/mozilla-l10n/www.mozilla.org/pull/299

Extraction was more complicated than usual, so it could do with some careful review.

**Comment by ejregithub** [comment]
Given that the PR - https://github.com/mozilla-l10n/www.mozilla.org/pull/299 has been merged, I'm closing this issue.
