### ISSUE TITLE
Make fundraising banner a more permanent feature

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7185]
## Description

We have a now semi-annual fundarising banner that gets requested to be shown on the home page (see https://github.com/mozilla/bedrock/issues/7047). It used to be an annual one-off thing, but we're now re-coding and re-reviewing the same banner more regularly, which gets added each time and then removed from the repo once it's finished.

Given the increase in the frequency, It may now make sense to make this fundraising banner a more permanent feature which can:

- Be quickly and easily toggled on / off via a switch.
- Support different copy.
- Support different backgrounds.
- Contain some evergreen (localized) content.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The Foundation banner can be launched without re-coding and re-reviewing; it's a permanent part of the application that can be switched on/off.
- [ ] The system that displays a banner, with a close toggle, a headline, a subhead, and a CTA button, is easy to repurpose for some other banner without rebuilding the entire system for a different purpose.

#### Approvals
- [ ] @alexgibson 
- [ ] Team Lead

**Comment by hoosteeno** [comment]
We should have a reusable capability to deliver a large-format promotion at the top of an arbitrary page. Would repurposing this issue for that be fair? The first use case is clearly the fundraising banner.

**Comment by alexgibson** [comment]
> We should have a reusable capability to deliver a large-format promotion at the top of an arbitrary page. Would repurposing this issue for that be fair? The first use case is clearly the fundraising banner.

I think making a system for this sounds sensible, as we'd not want more than one large promo on any page at a given time. I do still think we need to keep the fundraising banner around in the codebase however, even when it's not active. It's too bespoke and has a lot of functionality around currencies, and is now also used multiple times per year. We've been resurrecting and re-coding / reviewing it each time, but that no longer seems like an efficient way.

**Comment by hoosteeno** [comment]
OK, that makes sense. 

Can we layer the fundraiser's specific capabilities on a more abstract subsystem that provides the basic promotional banner? I think the abstract banner's basic features are something like:
* 100% width
* optionally close-able, with close link instrumented with an event
* default background, text, link, button styles
* default responsive layout (e.g. [wide](https://user-images.githubusercontent.com/1068783/51209732-ca1c7f80-18c5-11e9-95b5-8c2cb6082b49.jpg), [narrow](https://user-images.githubusercontent.com/1068783/51338114-d62b4d00-1a3d-11e9-9f81-d6f3dbf6372f.png))
* at a URL
* toggled by a switch (maybe one day scheduled more automatically)
* some logic to ensure only one per page

And the fundraising banner's specific features are something like:
* Seasonal background and headline with defaults set to the [EOY 2019 campaign](https://github.com/mozilla/bedrock/issues/8195)
* Frequency and amount selectors
* Configurable amounts in preset list
* Donate button 
* On the homepage
* staff/vendor localized

Does this seem accurate/complete?

**Comment by alexgibson** [comment]
I think something like this makes sense. This is similar in the way to how we currently handle modal content. What's shown inside the banner could be custom, but the outer appearance and basic functionality could be inherited.

**Comment by alexgibson** [comment]
I think @hoosteeno's list of suggestions above sound sensible. Moving this to ready.
