### ISSUE TITLE
Brainstorm new treatment experiments for Trailhead-branded pages

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#7189]
Produce a[ list of experiment ideas](https://docs.google.com/document/d/1a3JurLUurz0wr7q8cKBoDT6mnIMmTxzk_pKdfhNSJj4/edit) for Trailhead-branded pages:

* /new and /thanks
* /accounts
* whatsnew 67.0.1
* email preferences center

Suggestions:
* Lead a brainstorming session inviting a small or large group. Treat it like a brainstorming session. (Only add ideas, don't critique; capture as many as possible for later curation)
* Review user onboarding emails for ideas not tested, and talk with FxA marketing team about what's working, if anything
* Review usertesting conducted by Wendy and by Firefox user research teams on Trailhead messaging
* Talk to Raphael
* Share output and encourage additional ideas

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] A list of experiment ideas is ready for pruning

**Comment by ejregithub** [comment]
Team consensus says: we're good.  Closing.
