### ISSUE TITLE
Rewrite global CTA ("Get a Firefox Account") 

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#7190]
## Description

 Rewrite global CTA ("Get a Firefox Account")  aka Reword Global CTA for FxA Trailhead

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by ejregithub** [comment]
Comments from @hoosteeno in Slack:

```
right now, users not signed in to an account click "get an account" and go to accounts.firefox.com.

the question asks: when we put an account sign up form at the top of /accounts, wouldn't it be better to send those same users to /accounts?
```

**Comment by claychaffin** [comment]
@hoosteeno, I think our global FxA CTA should be "Sign Up/In" — at least until "Account" has a new name.

**Comment by claychaffin** [comment]
Copy Deck https://docs.google.com/document/d/1ArIy0zN9cJ06h0IwG96hkTrIpzTcHdMmBMXKyYKAywc/edit?usp=sharing

**Comment by hoosteeno** [comment]
I don't think we can have an unvarnished "Sign Up/Sign In" button at the top of all marketing pages, especially when this promotional button leads to the /accounts page. I forget why we can't say "Join Firefox"?

What do you think about "Get More From Firefox" ?

<img width="1285" alt="Screen Shot 2019-06-06 at 3 44 25 PM" src="https://user-images.githubusercontent.com/94519/59068666-fe430d80-8871-11e9-8919-e2d59d90c9c2.png">

**Comment by claychaffin** [comment]
@hoosteeno In answer to your question: For Mozilla.org and other pages, we think "Join Firefox" would be unclear as a (global) CTA— as a user, what am I “joining”? Whereas "Sign Up/Sign In" clearly *_signals_* an account relationship without saying “account.” It’s what users expect from experience with other sites. To be clear, itt doesn't communicate what the value might be -- that will be conveyed elsewhere -- but it does signal that there is more value to be had.

**Comment by claychaffin** [comment]
@wboucherfischer please take a look at the MVB (minimum viable brief) in the copy doc and fill in what you can -- I took it as far as I could. Thanks.
https://docs.google.com/document/d/1k0yUn4iBdMlXUryiNexenkKHTjb2mJWzYF9Jf6GyHog/edit?usp=sharing

**Comment by wboucherfischer** [comment]
Commented.

**Comment by claychaffin** [comment]
I cleaned up the copy doc, and added one question for @ejregithub and one for @wboucherfischer  Thanks.
https://docs.google.com/document/d/1k0yUn4iBdMlXUryiNexenkKHTjb2mJWzYF9Jf6GyHog/edit?usp=sharing

**Comment by alexgibson** [comment]
Some comments on the proposed copy:

- Whilst "Sign Up/Sign In" is common place for many websites, the typical action those types of link perform is to authenticate with a website (e.g. login). But that's not really what this button is responsible for. It signs people up for a Firefox Account (not a website account for www.mozilla.org). Without any additional context, how would visitors know what the button does?
- With our focus now on "Joining Firefox", and it being more than just about an account, but rather a whole suite of products & services - is "Sign Up/Sign In" now too closely coupled with the concept of an account? On /firefox/new/ for example, we now use the term "Get More From Firefox" (which links to /firefox/accounts/).
