### ISSUE TITLE
Create copy options for pre-download modal on /new/thanks for the June 4 sprint

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#7191]
Let's come up with new headline/subhead combos to test and optimize against the modal copy used in the last experiment:
"You've got the Firefox browser. Now get everything else Firefox." 

Consider improving the sign up form as well, though (per Justin) there is less room for improvement there

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### Tasks
- [ ] Write copy
- [ ] Update design when copy is final
- [ ] QA by Team
- [ ] Stakeholder review

**Comment by claychaffin** [comment]
@mrkwvr design pre-copy. Thanks Mark! @wboucherfischer Hi Wendy, do you have a POV about introducing  "Join Firefox" as our button CTA (replacing Get a Firefox Account") and something like "Already a member? Sign in" as our copy below the button? Thanks.
![Screen Shot 2019-05-21 at 11 36 04 AM](https://user-images.githubusercontent.com/45859665/58122534-b5772d80-7bbe-11e9-820a-913fdf6e6968.png)

**Comment by claychaffin** [comment]
_Pages for reference_ 

After clicking  the "Download Firefox" CTA button on this page
https://www-demo1.allizom.org/en-US/firefox/new/?xv=th&v=b

If users click "

If users instead click "download anyway" they get:
https://www-demo1.allizom.org/en-US/firefox/download/thanks/?xv=th&v=b

**Comment by claychaffin** [comment]
Copy deck - work in progress: https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing

**Comment by claychaffin** [comment]
Hi @hoosteeno, here’s improved copy and design for the modal on /New. Credit @mrkwv 's smart questions and good judgment and @dzingeek 's wisdom for guiding us to a better solution.
Please let us know if it’s good to go. Thank you.
![Screen Shot 2019-06-05 at 2 02 08 PM](https://user-images.githubusercontent.com/45859665/58979523-1851f280-8783-11e9-8e96-d7147c3ee27b.png)

**Comment by claychaffin** [comment]
@ejregithub Okay to close this Issue, which was focused only on the copy? The copy and design are both addressed in the other Issue

**Comment by claychaffin** [comment]
copy deck
https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing

**Comment by claychaffin** [comment]
Copy deck 
https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing

**Comment by ejregithub** [comment]
Closing this as Clay is logging the work for it in #7201
