### ISSUE TITLE
Remove games section from /technology

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7194]
## Description

games.mozilla.org is no more and we should remove and replace this section.

![Screen Shot 2019-05-15 at 3 47 51 PM](https://user-images.githubusercontent.com/30483988/57814574-eb349600-7728-11e9-8ceb-bb8645c2c9f4.png)

**Comment by imskr** [comment]
Is this open to work?  @amychurchwell

**Comment by hoosteeno** [comment]
When I visit games.mozilla.org, I get a website. Has that changed since this bug was filed?

**Comment by amychurchwell** [comment]
@hoosteeno no longer appears to be a bug. Closing issue.
