### ISSUE TITLE
Design: Trailhead-ify Pre-download FxA CTA for Fx Users

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7201]
## Description

Pre-Trailhead, we showed a pre-download modal (below) pitching FxA to people clicking the Download button on /new. We showed the modal only to Firefox users not logged in to sync. The modal was an effective FxA acquisition tool ([ref](https://analytics.amplitude.com/mozilla-corp/chart/q3klfgi)).

New designs for /new in Trailhead omit the modal. It needs to be updated to express our new FxA positioning with our new brand system. We should revise the copy and design of the earlier modal to fit with our new direction.

*Messaging direction:* These are Firefox users who are not signed in to sync, downloading Firefox again. Our message to them is, in much better copy, "You already have Firefox, but you're not taking advantage of the family of Firefox services we've built to help you own your online experience. Maybe you want to sign up for that, instead of downloading again what you already have downloaded?" It should...
[ ] incorporate learnings from the /accounts page user testing @wboucherfischer is conducting
[ ] incorporate new positioning

*UI direction:* The modal should include...
[ ] an email-first form with a signup button
[ ] a "Learn more"-type link (to /accounts)
[ ] links for the Terms and Privacy Notice
[ ] an option to sign in instead
[ ] a "Skip"-type button for circumventing the form and downloading anyway
[ ] new brand -- via protocol, wherever possible 

![Screen Shot 2019-05-15 at 1.38.12 PM.png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/918e1c02-ca6e-47d7-a5cc-362c56b04b84)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New designs ready and approved by dev team by end of present sprint

**Comment by dzingeek** [comment]
@hoosteeno I have a few UX questions around this experience. 

- Having a user click a button to initiate a download and then get interrupted by a modal is not ideal is there a better way to expose current fx user to an account offer..maybe without the modal/interrupting step?
- If a user clicks "Download Anyway" will they be taking through the onboarding experience? If so they will see an offer to "Join Fx"...this could lead to a very frustrating experience as they just saw that sort of offer.

**Comment by alexgibson** [comment]
> If a user clicks "Download Anyway" will they be taking through the onboarding experience? If so they will see an offer to "Join Fx"...this could lead to a very frustrating experience as they just saw that sort of offer.

I can add some extra info here: users should only see about:welcome if they launch Firefox using a new profile. If a visitor downloads Firefox using Firefox, and then installs the new version, it should get treated as a _pave over_ installation. This means Firefox will use their existing profile, and they won't get treated as a new user.

Caveat: this is how things used to work for /firstrun. Things may have changed ^

**Comment by hoosteeno** [comment]
>     * Having a user click a button to initiate a download and then get interrupted by a modal is not ideal is there a better way to expose current fx user to an account offer..maybe without the modal/interrupting step?

We await results on [our modal test in the funnel](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108). It may suggest a better place for this kind of prompt. 

I encourage creative ideas for making this better, if they are based on more knowledge than we have now. Our current understanding of this flow is inadequate to say what Firefox users downloading Firefox expect. When presented with an explanation and a choice in [an experiment](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=81691802#AddFxAto/newpageforexistingusers-Results:), more chose to exit the download flow than continue.

>     * If a user clicks "Download Anyway" will they be taking through the onboarding experience? If so they will see an offer to "Join Fx"...this could lead to a very frustrating experience as they just saw that sort of offer.

The pave-over experience [isn't changing](https://mozilla.slack.com/archives/GHU1GJ1T7/p1558377168142200), functionally, but it will get a visual refresh.

**Comment by dzingeek** [comment]
Thanks, @hoosteeno I will think about this more and chat with @wboucherfischer and a few others to see if we can come up with some other alternatives for future experiments.

**Comment by claychaffin** [comment]
Hi @hoosteeno ,here are the three copy options chosen by me and Natalie.

Thoughts:

Subheads - yes or no?
Whatever option we pick, should we omit the subhead for a shorter read or should we keep the subhead to more fully set landing page expectations? Do the subheads do more harm than good — or the opposite? 


Headline options -which direction to go?
Options 1 and 2 are similar - it's nuance. 
Option 3 is the only one here that sets landing page expectations (more) clearly by speaking to "protection" -- the top message of the landing page. But it's longer headline, and a narrower net, even if spot on.

Button copy
It's generic and the same for each 

https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing

**Comment by claychaffin** [comment]
@wboucherfischer @ejregithub

**Comment by wboucherfischer** [comment]
I'm leaning towards Option 3. I'm still not sure about the "spot hackers
with firefox monitor" because that implies virus scanning software or a
firewall. I feel like we should go away from that. Thoughts?

**Comment by claychaffin** [comment]
@wboucherfischer sounds like it's between options 2 and 3 for you, and you lean towards 3.
If 3, should we omit he subhead? If we keep it I can tweak it to address "Spot hackers..." if that does not align with what the product delivers.

**Comment by dzingeek** [comment]
I am confused by the CTA..are we still using the fxa form (user inputs email address)? if so learn more makes no sense to me.

**Comment by claychaffin** [comment]
@dzingeek great question. no, we are not now using the fxa form for this. We are taking users that click "Learn More" straight to the Trailhead-ified accts-membership page, on which its a Join Firefox CTA.

**Comment by claychaffin** [comment]
Hi @hoosteeno, here’s improved copy and design for the modal on /New. Credit @mrkwvr 's smart questions and good judgment and @dzingeek 's wisdom for guiding us to a better solution.
Please let us know if it’s good to go. Thank you.
![Screen Shot 2019-06-05 at 2 02 08 PM](https://user-images.githubusercontent.com/45859665/58989053-f7e06300-8797-11e9-8331-fbe119a6d0e7.png)

**Comment by claychaffin** [comment]
copy deck
https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing

**Comment by stephaniehobson** [comment]
FWIW "Get more Firefox" does not make sense to me. How do I get more browser?

**Comment by claychaffin** [comment]
@stephaniehobson Thanks for your honest feedback. I might think the same viewing that phrase in isolation; do you feel this way about "Get More Firefox"even after reading the headline, which (re)defines the relationship between "browser" and "FIrefox", and then below, when you view the button messages together? @ejregithub

**Comment by hoosteeno** [comment]
Thanks Clay! I added comments to the doc.

**Comment by stephaniehobson** [comment]
The headline does not redefine the relationship for me. "You've already got the browser, now get more browser." I'm not sure it makes sense to me even with a brand I identify with several products. "You've already got the browser, now get more Google."

**Comment by claychaffin** [comment]
@hoosteeno please review and weigh in on two new copy options. My comments are in the doc. Thanks.
https://docs.google.com/document/d/1vfMqegM57OvFkAjFIZ03B_3zS9KAFHW_fM0WShHY5pA/edit?usp=sharing @stephaniehobson @ejregithub

**Comment by ejregithub** [comment]
Changing Estimate to be a 13 as Clay is wrapping is copy work into this this issue and closing the original issue for copy  #7191

**Comment by hoosteeno** [comment]
Reviewed.

**Comment by mrkwvr** [comment]
here's the sketch file with the modal design and final copy [FxA-modal-:new.sketch.zip](https://github.com/mozilla/bedrock/files/3278364/FxA-modal-.new.sketch.zip)

**Comment by ejregithub** [comment]
I see final copy and design here, posted 16 days ago. Closing this, the 'design' card.
