### ISSUE TITLE
l10n_extract only extracts strings from HTML templates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7204]
## Description

See https://github.com/mozilla-l10n/www.mozilla.org/pull/299 for context.

### Steps to reproduce

Run `./manage.py l10n_extract bedrock/newsletter/templates/newsletter/existing.html`

### Expected result

It should generate a `newsletters.lang` file in `./locale/templates/mozorg/`, containing both the strings defined in the HTML template *and* the strings defined in `bedrock/newsletter/views.py`.

### Actual result

The `newsletters.lang` file is generated, but contains only the strings from the HTML file.

### Environment

N/A

**Comment by pmac** [comment]
Oh... well you ran it against a specific file. I expect if you ran it listing the template and the view file it would have worked. The extract script will only look at the files you tell it to if you list any, or all files of types it knows about if you don't pass it any files. It has no understanding of templates and views and how they connect.

**Comment by pmac** [comment]
In other words I believe the following command would have done what you wanted:

```bash
$ ./manage.py l10n_extract bedrock/newsletter/templates/newsletter/existing.html bedrock/newsletter/views.py
```

**Comment by alexgibson** [comment]
Oh, I had no idea you needed to run it directly on the Python file as well. The way I read the docs, it made it sound like it would extract all the needed localizations.

What then if the `views.py` file contains views for multiple templates, would they al end up in the same file?

**Comment by alexgibson** [comment]
Well, yup - in this case it does seem to do the right thing, and everything ends up in the right place. Let me run this again properly, and I'll update the lang file again in the preferences PR.

**Comment by pmac** [comment]
When a python file has strings in it (which isn't that common really) you can specify the lang file with a constant variable in the file: `LANG_FILES`. You can see it at the top of `newsletters/views.py`. That determines the lookup of the strings in the same way as templates, and where strings should extract to. It's obviously not perfect as you point out, but it's what we've got for now.
