### ISSUE TITLE
Adjust links on 67.0 /whatsnew page redirect to the wrong destination

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7207]
## Description

More than one of the app store badges on the 67.0 whatsnew page redirect clicks to the wrong destination: https://www.mozilla.org/en-US/firefox/67.0/whatsnew/

### Steps to reproduce

1. Load the above URL
2. Click "Get the Lockbox App"
3. Click the "Get it on Google Play" store badge.

### Expected result

I should get redirected to the Play Store.

### Actual result

I get redirected to https://itunes.apple.com/app/id1314000270?mt=8

The same also happens with the Pocket app link. We should either link directly to the appropriate stores (removing the adjust links), or alternatively remove the links altogether and leave only the badges.

### Environment

Any desktop Firefox Browser

**Comment by hoosteeno** [comment]
Great issue, thanks. The solutioning for this will be tracked over in #7214, so we'll close this as a dupe.
