### ISSUE TITLE
Add MSI installers to redesigned /all page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7209]
In the new /all page (#7076) we allow visitors to choose a version of Firefox to download using a set of dropdowns. The following user story applies to this interface:

* As a user, I want to download Firefox MSI installers from the /all page

The following functional requirements support this user story:

1. MSI installers should be included in the list of products available via the dropdowns
2. When MSI installers are selected in the dropdowns, the dynamic elements on the page and in the URL bar change to reflect the MSI installer is selected

The following task would improve the value of this feature:

* The SUMO page linking directly to MSI downloads (https://support.mozilla.org/en-US/kb/deploy-firefox-msi-installers?redirectlocale=en-US&redirectslug=firefox-customization-msi-installers) instead links to the new /all page with a deep link for the MSI installer.

**Comment by alexgibson** [comment]
Note: this may be somewhat tricky to do as long as we're still supporting the old page (which can't be removed until enough new locales have the new template translated), since the same product details data powers both templates.

**Comment by hoosteeno** [comment]
The [design card](https://github.com/mozilla/bedrock/issues/7265) has proceeded far enough along to start coding this card. We will put MSI installers in the OS dropdown. We will add an info modal to the OS dropdown, as with products. We will have some new copy for the modal and for the dropdown label.

**Comment by alexgibson** [comment]
I'm gonna see if I can figure out the plumbing here.

**Comment by alexgibson** [comment]
I figured out the backend work, which is now up on demo: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/

This is now blocked on final copy / design.

**Comment by ejregithub** [comment]
Design spec for color of question mark icon  - @mrkwvr 

Copy - adding to 'platform' drop down - blocked on Tyler - 64 bit copy strings here, too.

**Comment by alexgibson** [comment]
We received some copy suggestions in the [design issue](https://github.com/mozilla/bedrock/issues/7265#issuecomment-505127182), although they are only suggestions and not final, usable copy.

I've pushed what I have to demo:

https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/all/

This is still blocked on nailing down final copy. We need to work with @claychaffin to firm up what's still needed.

**Comment by alexgibson** [comment]
We have final copy, removing the blocker.
