### ISSUE TITLE
App store badges don't work as expected on desktop

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7214]
## Description

Adjust links such as the ones on WNP67 (click "Get Lockbox" and then on an app store badge) are designed to redirect mobile user agents to their appropriate app store. On desktop, these links redirect to the Apple App Store, even when clicking on the Google Play Store button. With more interest in our non-browser products and more marketing of them, this problem will continue to confound users (see bug reports linked below).

We should fix it. Ideas:

* ~Eliminate app store badges for desktop users.~
* ~Eliminate Adjust from the mix for desktop users.~
* ~Configure an Adjust fallback link for desktop users https://docs.adjust.com/en/tracker-generation/#redirecting-users-to-landing-pages-or-in-app-locations~
* **Create Adjust links for each badge individually, that redirect to the store that corresponds with the badge selected https://docs.adjust.com/en/tracker-generation/#cross-platform-trackers-for-multiple-app-stores**

##### For Pocket:
Android: https://app.adjust.com/1ek4zlx?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.ideashower.readitlater.pro
iOS: https://app.adjust.com/438mmzr?redirect=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Fpocket-save-read-grow%2Fid309601447

##### For Lockwise:
Android: https://app.adjust.com/gi0ycmr?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dmozilla.lockbox
iOS: https://app.adjust.com/qywno6t?redirect=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fid1314000270%3Fmt%3D8

##### For Notes:
No changes needed, it's already a direct link to Play Store.

----

Reported in webcompat: https://github.com/webcompat/web-bugs/issues/31572
Reported on HackerNews: https://news.ycombinator.com/item?id=19969818

----

### Steps to reproduce

Visit https://www.mozilla.org/en-US/firefox/67.0/whatsnew/ on a desktop machine. Click "Get The Lockbox App". Click the Google Play Store badge.

### Expected result

Go to Google Play Store listing.

### Actual result

Go to Apple App Store listing

### Environment

Desktop browser.

**Comment by hoosteeno** [comment]
@lwa-moz will generate new Adjust links and put them in this issue for us when ready.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/7103

**Comment by lwa-moz** [comment]
This link will resolve Google Play page regardless of the device used to open it: https://app.adjust.com/utf1y0q?redirect=https%3A%2F%2Fplay.google.com/store/apps/details?id=mozilla.lockbox

**Comment by hoosteeno** [comment]
This issue is happening in reverse on https://www.mozilla.org/en-US/firefox/68.0beta/whatsnew/. 

@lwa-moz , can you specify exactly what needs to be done to fix the issue? e.g...

```
1. Replace apple app store links with _____.
2. Replace google play store links with ____.
```

**Comment by lwa-moz** [comment]
Good call out:
LockWise WNP 68.0 Adjust Links
Android: https://app.adjust.com/gi0ycmr?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dmozilla.lockbox
iOS:  https://app.adjust.com/qywno6t?redirect=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fid1314000270%3Fmt%3D8

Please let me know if you're referring to something different from platform specific LockWise install links. Happy to provide whatever links make for the best user flow.

**Comment by hoosteeno** [comment]
Thanks @lwa-moz ! Can you do the same for Pocket and Notes?

**Comment by lwa-moz** [comment]
**For Pocket:**
Android: https://app.adjust.com/1ek4zlx?redirect=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.ideashower.readitlater.pro 
iOS: https://app.adjust.com/438mmzr?redirect=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Fpocket-save-read-grow%2Fid309601447 

The Adjust integration for Notes is not live, so we'll be unable to provide redirect links with Adjust tracking embedded. I'd recommend using direct store links (utm parameters work in Google Play, if not Appstore, fwiw).

**Comment by hoosteeno** [comment]
Thanks!

**Implementers:** I captured the badge specific links for all apps in the overall description of this bug.

**Comment by alexgibson** [comment]
@lwa-moz - can we please also have a set of standardized links for Firefox Focus? (both Focus and Klar). Thanks

**Comment by alexgibson** [comment]
For completeness sake (and to avoid needing them in the future), a set for Firefox on Android and iOS would be good to have too.

**Comment by alexgibson** [comment]
This is blocked on answers to this question: https://app.zenhub.com/workspaces/websites-team-59bd527821e82e515786ca73/issues/mozilla/bedrock/7257#issuecomment-497374308

**Comment by alexgibson** [comment]
@hoosteeno @lwa-moz I put together a test page to help verify that the links are correct:

https://www-demo1.allizom.org/en-US/adjust-test/

I still have some tests to finish writing, but in the meantime feel free to take a look. Thanks

**Comment by lwa-moz** [comment]
Thanks @alexgibson! Looks like they all are working as expected on my end.

**Comment by hoosteeno** [comment]
@alexgibson working for me, too. 

Note, we now have a link for Klar: https://docs.google.com/spreadsheets/d/1KXiB4Dp0Bar5cdwIjFjYPhzLXYpMS53s-DPKOPH5hp8/edit#gid=462416323

**Comment by alexgibson** [comment]
This is now ready for code review.

**Comment by hoosteeno** [comment]
@alexgibson can you put an estimate on this for all work done, and work to come in review? Round up for work from Loren & me.

**Comment by alexgibson** [comment]
@hoosteeno done, thanks
