### ISSUE TITLE
Trailhead - /accounts page 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7220]

**Comment by claychaffin** [comment]
Copy doc for _non-signed in_ users:
https://docs.google.com/document/d/1nyg_trea3ew3dBMA_GP_kW2Bw5W7T4rAWCzQUH-DvZg/edit?usp=sharing

**Comment by claychaffin** [comment]
@ejregithub is the correct Issue for non-signed in FxA copy?
