### ISSUE TITLE
Trailhead - WNP 67.0.5 - Code Review

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7223]
## Description

Trailhead - WNP 67.0.5 - perform Code Review of the Pull Request
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Looks like this is in production: https://www.mozilla.org/en-US/firefox/67.0.5/whatsnew/
