### ISSUE TITLE
pre-download FxA CTA for Firefox users modal - Extract Strings

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7236]
## Description

Extract strings for localization when copy is final/approved

---

**Comment by alexgibson** [comment]
Design, dev & code review is now complete. This will go out later today, so I'll start work on string extraction.

**Comment by alexgibson** [comment]
L10n PR to update langfiles: https://github.com/mozilla-l10n/www.mozilla.org/pull/322

**Comment by alexgibson** [comment]
Strings extracted and pushed to production
