### ISSUE TITLE
Set up demo of Convert

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7237]
We previously set up a demo of Google Optimize. Can we replace that demo with a demo of convert.com? This will require removing Google Optimize tags from HTML, and adding convert.com tags to HTML *on a specific page e.g. /new*. Here's an example of the convert tag (actual code to be provided when URL of demo server is known).

```
<html>
<head>
...
</title>
<!-- begin Convert Experiences code--><script type="text/javascript" src="//cdn-3.convertexperiments.com/js/10039-100310.js"></script><!-- end Convert Experiences code -->
...
</head>
```

cc: @jpetto @metadave

**Comment by hoosteeno** [comment]
After thinking this through, I realize there is no reason we have to couple this demo with the previous demo of Optimize. We simply need a demo of convert. Setting it up requires changes to templates as described above, and probably changes to CSP.

**Comment by hoosteeno** [comment]
Here are docs:
https://support.convert.com/hc/en-us/articles/205151015-How-to-Install-the-Main-Tag-Code-Javascript

We'll use demo 3. 

Here's the code:

Here are its brief instructions:
> Add the following project code in the <head> section, just after </title>, on all your experiences and goal pages
```
<!-- begin Convert Experiences code--><script type="text/javascript" src="//cdn-3.convertexperiments.com/js/10039-100317.js"></script><!-- end Convert Experiences code -->
```

**Comment by jpetto** [comment]
Currently up on [demo3](https://www-demo3.allizom.org).

**Comment by alexgibson** [comment]
When trying to preview the site inside the editor, I see the following CSP error:

```
Refused to load the script 'https://app.convert.com/sys/v4.11.2-1776-g95f8522/js/neweditor/bundle-editor-iframe.js' because it violates the following Content Security Policy directive: "script-src 'self' *.mozilla.net *.mozilla.org *.mozilla.com *.allizom.org 'unsafe-inline' 'unsafe-eval' www.googletagmanager.com www.google-analytics.com tagmanager.google.com www.youtube.com s.ytimg.com cdn-3.convertexperiments.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

I'll take a look at adding `app.convert.com` to the CSP exception list.

**Comment by alexgibson** [comment]
@hoosteeno @jpetto OK, I've managed to get the editor working against our demo's CSP. I also restricted Convert to a single page / URL (which is a requirement above).

For now, the tag should only appear on https://www-demo3.allizom.org/en-US/firefox/campaign/

Some brief observations:

- This will no doubt need a formal security review.
- We'd need to make loading of the convert script honor DNT (like we did for Optimizely).
- Convert seems to [integrate directly with GA](https://support.convert.com/hc/en-us/articles/205160075-Integrate-Convert-Experiments-with-Google-Analytics), which could be really useful.

**Comment by alexgibson** [comment]
In Sentry I noticed a load more CSP violations for:

```
CSP Violation: https://100317.track.convertexperiments.com/track/?c=10039&p=100317&v=1&sh=1559166461310-0.621968577365468&e=100323-1003197-&ea=1&g=&ga=0&_rnd=1559166461317
```

I'll take a look today and see if I can correct this.

**Comment by alexgibson** [comment]
Added `100317.track.convertexperiments.com` to `CSP_SCRIPT_SRC` and pushed to demo.

**Comment by alexgibson** [comment]
@hoosteeno it seems like everything is pretty much complete on the demo for folks to test. Shall we close this card out?
