### ISSUE TITLE
Trailhead - WNP 67.0.1 - Design Review/Feedback

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#7244]
@amychurchwell Just a few small tweaks.

- [ ] Button color should be #0060DF 
- [x] It's missing the "Congrats! You're using the latest..." bar in the nav area
- [ ] The text below the box should go from edge to edge of the 'shadow box' above _(See image below for reference (left = live site right = how it should look)_
- [ ] The text does not appear to be Firefox Sharp Sans or Inter (sharp sans for headlines and inter for body copy) 

![Screen Shot 2019-05-24 at 3 37 37 PM](https://user-images.githubusercontent.com/3740746/58359998-127f1780-7e3b-11e9-9626-fa4fd176ae76.png)

**Comment by stephaniehobson** [comment]
The button colour and font face updates are coming in https://github.com/mozilla/bedrock/pull/7227 which is waiting on design and code review.
