### ISSUE TITLE
Show Trailhead WNP to beta users launch

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7248]
## Description

Show Trailhead WNP content to beta users at launch

https://bugzilla.mozilla.org/show_bug.cgi?id=1549889

PR in which this was done to show WNP 66 content to DevEdition users - https://github.com/mozilla/bedrock/pull/7073

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by ejregithub** [comment]
@alexgibson - I want to ask if you can take this on, citing the fact that you did in the last request to show a WNP to beta users.

**Comment by alexgibson** [comment]
@ejregithub what version number are we targeting here? People are also asking the same question in bugzilla.

**Comment by alexgibson** [comment]
@ejregithub I've made a PR to show this page at `/firefox/68.0beta/whatsnew/` for en, de and fr.

If this is not correct, let me know ASAP.

**Comment by ejregithub** [comment]
@alexgibson  - Please size the work done here in the Estimate menu

**Comment by alexgibson** [comment]
Done, thanks
