### ISSUE TITLE
Show Trailhead WNP to DevEdition users at launch

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7249]
## Description

Show Trailhead WNP content to DevEdition users at launch

https://bugzilla.mozilla.org/show_bug.cgi?id=1549891

PR in which this was done to show WNP 66 content to DevEdition users - https://github.com/mozilla/bedrock/pull/7073

**Comment by ejregithub** [comment]
@alexgibson - I want to ask if you can take this on, citing the fact that you did in the last request to show a WNP to DevEdition users.

**Comment by alexgibson** [comment]
@ejregithub what version number are we targeting here? People are also asking the same question in bugzilla.

**Comment by alexgibson** [comment]
@ejregithub I've made a PR to show this page at `/firefox/68.0a2/whatsnew/` for en, de and fr.

If this is not correct, let me know ASAP.

**Comment by ejregithub** [comment]
Looks right to me.

**Comment by ejregithub** [comment]
@alexgibson - can you please provide story points for this in 'Estimate'

**Comment by alexgibson** [comment]
Done, thanks
