### ISSUE TITLE
Use standardized FxA Referrals GA config in fxa_email_form

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7252]
## Description

In #7061 it was decided that when we send someone to FxA we would like to record it in GA with an Event Action that includes FxA. FxA-ServiceName was decided on with FxA-Sync being the only service currently passed to FxA from moz.org.

With the work on #7197 I realized the button in the fxa_email_form was not updated at that time.

An [example of this form](https://www.mozilla.org/en-US/firefox/accounts/) can be found on the accounts page.

**Comment by stephaniehobson** [comment]
@hoosteeno FYI the work we did in #7061 has not been applied to the sign in/up form.

**Comment by alexgibson** [comment]
@stephaniehobson there's an existing issue here that details the remaining issues that didn't make it into the original PR https://github.com/mozilla/bedrock/issues/7169

**Comment by stephaniehobson** [comment]
@alexgibson That issue seems to be more about updating the parameters we send to FxA not the ones we trigger on our site for GA?

**Comment by alexgibson** [comment]
@stephaniehobson that work was kinda muddied together yeah. But my hope was just to convey that yes these links did not get covered originally.
