### ISSUE TITLE
/firefox pre-download newsletter cleanup

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7254]
There are still some fragments of the pre-download newsletter floating around.

bedrock/firefox/templates/firefox/home/index.html still has the `show_newsletter` switch
bedrock/firefox/templates/firefox/home/index.de.html
bedrock/firefox/templates/firefox/home/index.fr.html
media/css/firefox/home/pre-download-newsletter.scss
media/js/firefox/home/pre-download-newsletter.js
(and associated listings in static_bundles.json)
and some tests which should be cleaned up in #7203.

There's a `show_newsletter` switch on scene2 and WNP templates as well, are those separate or part of the same effort? 

See https://github.com/mozilla/bedrock/issues/7121#issuecomment-488254113

**Comment by stephaniehobson** [comment]
@alexgibson Does this look right to you?

**Comment by alexgibson** [comment]
Yes, although I think the `show_newsletter` variable is used by more than just this pre-download modal.

I’ll defer to @hoosteeno if we are ok to remove this functionality.

**Comment by hoosteeno** [comment]
Let's not remove this now. Too many moving pieces prevent an accurate assessment of its ongoing value. I'm setting a reminder for a week from now.

**Comment by stephaniehobson** [comment]
Okay, removed test clean up from #7203.

**Comment by hoosteeno** [comment]
We are greenlit to remove pre-download newsletter modals from anywhere they exist in download funnels.
