### ISSUE TITLE
Trailhead /whatsnew page does not display the "Congrats! You’re using the latest version of Firefox." message.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7256]
## Description

When loading the page there is a white banner at the top where the up-to-date message should be displayed. The strings are in the template, but we're not showing them.

### Steps to reproduce

Visit: https://www.mozilla.org/en-US/firefox/67.0.1/whatsnew/ (using a Firefox browser)

### Expected result

There should be a message at the top saying you're up-to-date:

![image](https://user-images.githubusercontent.com/400117/58625601-b436b680-82ca-11e9-96cb-2a87691a9522.png)

### Actual result

The bar is empty:

![image](https://user-images.githubusercontent.com/400117/58625544-95382480-82ca-11e9-93a9-fb6cbea9fd34.png)

### Environment

Tested in both Firefox 68 and Firefox Nightly.

**Comment by alexgibson** [comment]
I'm not sure that's correct. On the regular 67.0 page, I see the message in both Nightly and Release: https://www.mozilla.org/en-US/firefox/67.0/whatsnew/

The code that checks that is here: https://github.com/mozilla/bedrock/blob/master/media/js/firefox/whatsnew/whatsnew-67.js#L32-L41

**Comment by stephaniehobson** [comment]
Huh, okay, I'm seeing it now too. I've always had to switch to Release to check it during code reviews though. Perhaps I am just in the habit of running Nightly without updating it 🤷‍♀

**Comment by alexgibson** [comment]
The logic says if you're on anything equal or above the latest release version, then you're up to date. It does rely on UITour, so perhaps you need to enable that locally in your Nightly profile.
