### ISSUE TITLE
Show default content for trailhead /whatsnew page

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7260]
## Description

A bit of an edge case, but if a user who happens to be on mobile or is in a non-firefox browser loads this page they see an empty page.

![image](https://user-images.githubusercontent.com/30483988/58666914-7a28dd00-82e9-11e9-9afe-08f259f17513.png)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Show the blurb section as default for mobile and non-firefox users.

**Comment by ejregithub** [comment]
@amychurchwell - I believe this was resolved in another issue (I can readily view the WNP in Chrome on Desktop as well as in Chrome and Firefox on mobile).  

Please confirm and I'll close this issue.

**Comment by amychurchwell** [comment]
Yes, this issue should be closed. What's new pages aren't shown to non-firefox browsers or mobile users.
