### ISSUE TITLE
Signups via /accounts do not work in Internet Explorer 11

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7270]
## Description

Signups via /accounts is broken using IE browsers.

### Steps to reproduce

1. Using Internet Explorer visit https://www.mozilla.org/en-US/firefox/accounts/.
2. Enter an email address and click "Continue"

### Expected result

I should be forwarded to accounts.firefox.com where I can then continue entering my details. Alternatively, if Internet Explorer 11 is not supported then we should display a message to install Firefox instead.

### Actual result

I'm forwarded to accounts.firefox.com as expected, but all I see is a loading spinner and a broken layout.

<img width="1675" alt="Screenshot 2019-06-03 at 13 32 53" src="https://user-images.githubusercontent.com/400117/58802085-275e6680-8604-11e9-817e-cee46e877545.png">

Things to note:

- The accounts.firefox.com layout is clearly broken in legacy browsers.
- We're passing `?action=email&context=fx_desktop_v3` in the URL. This is probably a bug on mozilla.org's side. Looking at our code, we seem to [return early](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-form.js#L20-L22) if a browser does not support `fetch`. This probably means signups don't surrently work in any legacy browsers.
- `flow_id` and `flow_begin_time` are empty (see https://github.com/mozilla/bedrock/issues/7269).

### Environment

Internet Explorer 11 on Windows 7.

**Comment by craigcook** [comment]
>     * We're passing `?action=email&context=fx_desktop_v3` in the URL. 

The context field should be omitted for anything that isn't Firefox, I'm not sure why it's not being removed.

**Comment by craigcook** [comment]
> > ```
> > * We're passing `?action=email&context=fx_desktop_v3` in the URL. 
> > ```
> 
> The context field should be omitted for anything that isn't Firefox, I'm not sure why it's not being removed.

Error in IE10: `Object doesn't support property or method 'remove'` so that explains that.

**Comment by hoosteeno** [comment]
@alexgibson we recently did some work on this part of our site. Is this still an issue?

**Comment by alexgibson** [comment]
@hoosteeno I just checked using IE11 and this is still an issue.

**Comment by hoosteeno** [comment]
Adding this to backlog. Let me know if we need a conversation with FxA/metrics team to identify a solution.

**Comment by alexgibson** [comment]
> Let me know if we need a conversation with FxA/metrics team to identify a solution.

I'm assuming the FxA team do not plan on supporting IE browsers. We should verify that, and if correct, then we need to come up with some alternate call to action for users on legacy IE browsers (perhaps a download firefox button?)

**Comment by alexgibson** [comment]
An different course of action (rather than mozorg patching these holes from multiple entry points), could be for the FxA team to have some kind of fallback message at accounts.firefox.com for unsupported browsers. This could be a more robust and scalable solution, but I guess it depends on if this is a priority for that team.

**Comment by craigcook** [comment]
Related: https://github.com/mozilla/fxa/issues/1368

**Comment by hoosteeno** [comment]
I agree that downstream is the place to handle this issue, and think we should close this card in favor of that one.

**Comment by ejregithub** [comment]
Closing per @hoosteeno's last comment
