### ISSUE TITLE
Hide the accounts signin/signup form from unsupported browsers

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7274]
## Description

FxA only works properly in modern browsers. Rather than checking for Sync support, we need a more browser-agnostic test for minimum support level to determine whether to show or hide the form.

> base level is ES5, so at a minimum we need Function.prototype.bind and a bunch of Array methods. Array.prototype.filter comes to mind as commonly used.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Closing as a duplicate of #7270
