### ISSUE TITLE
Update design and copy for bottom banner on www.mozilla.org EN homepage

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#7293]
## Description

As part of Trailhead, we are 1) moving away from the term "Accounts" (and "accounts") and the product positioning "Firefox Accounts" to support a new membership model ("Join Firefox") and 2) updating mozilla.org everywhere with a new brand design.
_To that end, we need to update design and copy for the bottom banner on the 
www.mozilla.org homepage (existing copy: "The account that protects you rather than profits off you") with Trailhead messaging, including eliminating the reference to "account."_

<img width="959" alt="Screen Shot 2019-06-06 at 3 36 45 PM" src="https://user-images.githubusercontent.com/94519/59068272-fafb5200-8870-11e9-817d-756e0a28db86.png">

In a separate Issue -- #7190 -- we are creating new copy to replace the existing FxA global CTA copy (existing: "Get A Firefox Account").
When we publish/push this new FxA global CTA live, we should simultaneously (or as soon as practicable) also publish/push the content created under this Issue https://github.com/mozilla/bedrock/issues/7293

Tasks
- [ ] update design (with new logo too?)
- [ ] write headline
- [ ] write subhead, if needed
- [ ] what is best, button or link?
- [ ] write button or link copy

**Comment by stephaniehobson** [comment]
Closing in favour of #7684.

**Comment by stephaniehobson** [comment]
Drat. Re-opening as this is the only banner we're not updating in #7684.

**Comment by stephaniehobson** [comment]
I will updated to the master brand logo though.
