### ISSUE TITLE
Update or remove fxa_create_account_button macro

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7294]
The `fxa_create_account_button` macro was designed to create a "Create Firefox Account" Call to Action for Firefox Desktop users, fall back to "Download Firefox" for non Fx users or link to SUMO documentation for Fx Mobile users.

With the trailhead re-focus this macro is no longer used. Can we remove it?

Was there an associated JS file that can also be removed?

**Comment by alexgibson** [comment]
I’ve tried to use this macro on a couple of pages in the past, but ended up using a simple button instead as there was a bit too much behaviour baked-in that I didn’t need. Also agree that given the shift in how we promote accounts, this macro is likely less aligned with what we need today. +1 for removing.
