### ISSUE TITLE
Safari on iOS 13 download issues due to dynamic UA string behavior?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7299]
## Description

I haven't tested this as I do not yet have the beta of iOS 13 available, but current reports indicate that Safari on iOS 13 will start dynamically changing it's UA string for iPad, depending on the size of the browser window (and a few other heuristics). For larger iPad devices, it now pretends to be macOS.

Source: https://twitter.com/firt/status/1136652739432390661

UA for desktop mode:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
```

`navigator.platform` = `MacIntel`

UA for mobile mode:

```
Mozilla/5.0 (iPad; CPU OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1
```

`navigator.platform` = `iPad`

Related Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=198672

### Steps to reproduce

1.) Using iPad Safari on iOS 13, visit: https://www.mozilla.org/en-US/firefox/new/.
2.) Click "Download Now"

### Expected result

Users should always be redirected to the App store, irrespective of browser window size.

### Actual result

When in "desktop mode", the user might get a macOS download (to be confirmed still).

### Environment

iPad running iOS 13 beta.

**Comment by alexgibson** [comment]
@hoosteeno filing this early, just as a heads up ^

**Comment by alexgibson** [comment]
So, iOS 13 was released yesterday, so according to [this article](https://medium.com/@firt/iphone-11-ipados-and-ios-13-for-pwas-and-web-development-5d5d9071cc49), the bug above is now in the wild.

I don't yet have an iPad device running iOS 13 to test, or use to develop a fix for. We should be able to use a simulator in XCode for this vs a real device. But it looks like those updated simulators aren't out yet :/

**Comment by alexgibson** [comment]
The article above seems to suggest using `‘standalone’ in navigator` in combination with iOS/macOS user agent string, to detect iPad OS.

**Comment by pmac** [comment]
I have an iPad Pro I could upgrade to the iPadOS beta if that would help.

**Comment by alexgibson** [comment]
I think iOS 13 is out now for iPad Pro, so you may not need to switch to beta. Not to worry if you’re not ready to upgrade yet though, hopefully XCode will be updated shortly 👍

**Comment by pmac** [comment]
iOS 13 is out, but iPadOS comes out on the 24th apparently. I don't currently show any available update on mine.

**Comment by alexgibson** [comment]
I can now confirm this bug

![ipad-bug](https://user-images.githubusercontent.com/400117/65694185-56925b00-e06d-11e9-9044-3fffe474bf30.png)
