### ISSUE TITLE
Replace Firefox Quantum w. Firefox Desktop Browser in global nav

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7303]
## Description

We're  moving off of mentioning the browser as Firefox Quantum and using, instead, Firefox Desktop Browser with this (B)rowser as title case.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Firefox Desktop Browser is in place as new copy in the global navigation

#### Tasks
- [ ] Update string

**Comment by rraue** [comment]
On which pages will we replace this? All pages?

**Comment by ejregithub** [comment]
@rraue - for now, for this task, it is only in the global navigation (i updated description accordingly). I will create another card (epic) to further discuss this, identifying the locations it (Quantum) is in use on the site and to create a plan for implementing the change further.

**Comment by rraue** [comment]
Great, we will need one page, where we still mention it and have it in the title, so not only the blog is ranking for it but besides that I am fine with removing it everywhere. I could get us a crawl with all pages mentioning Quantum on www, if thats needed.
