### ISSUE TITLE
'Get Firefox Account' CTA in nav turns to 'Download Firefox' on /firefox

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7306]
## Description

Users visiting /firefox on firefox see the "Get a Firefox Account" CTA in the nav, then when scrolling down the page the CTA turns into the "Download Firefox" CTA. These should match each other.

**Comment by amychurchwell** [comment]
<img width="290" alt="Screen Shot 2019-07-09 at 11 33 56 AM" src="https://user-images.githubusercontent.com/30483988/60914064-97808d80-a23d-11e9-9e1e-27adbda53518.png">
<img width="240" alt="Screen Shot 2019-07-09 at 11 33 51 AM" src="https://user-images.githubusercontent.com/30483988/60914065-97808d80-a23d-11e9-9fd1-2e7ccf3ca38f.png">

Something I also noticed is that these two CTA's have different shades of green.

**Comment by alexgibson** [comment]
This sub nav no longer exist, closing
