### ISSUE TITLE
Add 'Download Firefox' cta to nav on /firefox/accounts/  for non-firefox browsers.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7320]
## Description

On non-firefox browsers we should include a cta in the nav for 'Download Firefox' on /firefox/accounts/
Currently there is no cta for any browser.

![Screen Shot 2019-06-13 at 10 14 47 AM](https://user-images.githubusercontent.com/30483988/59454518-1d3c2500-8dc7-11e9-89cb-39e57863dbea.png)

**Comment by alexgibson** [comment]
@hoosteeno A contributor has issued a fix for the above. Just want to double-check that this is ok to show to non-Firefoxes, along with the primary Join Firfox CTA? Thanks

**Comment by amychurchwell** [comment]
--for a little context, this was mentioned as a bug in slack.

**Comment by hoosteeno** [comment]
@wboucherfischer how do you feel about adding this CTA to the global nav for non-Firefox users? The CTA is already present almost everywhere on the site. I believe it is not a deliberate omission with Trailhead work, but an accidental one missed because it's an edge case.

**Comment by dzingeek** [comment]
I have some thoughts on this. As we move to "Firefox is more than a browser" then a Download Firefox button will no longer make sense. One way to address this is to have a Sign In/Up button for all users (fx users and non-fx users) in the nav. 

That said I am not sure we are ready for this just yet as we have to build out more pages around telling this new brand story. So I think for now, sure go ahead and add "Download Firefox" button, knowing that it's very likely to change "soon"

**Comment by alexgibson** [comment]
> So I think for now, sure go ahead and add "Download Firefox" button, knowing that it's very likely to change "soon"

Works for me, thanks 👍

**Comment by wboucherfischer** [comment]
I'd agree with Jennifer. However, I think we should consider adding
'download Firefox browser' into the footer at some point. It feels like the
footer could make better use of the items that are down there and should
also reflect what is in the header navigation. I know @Jennifer Rouse
<jrouse@mozilla.com>  has done some exploration on this.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7361
