### ISSUE TITLE
If passing through UTMs to FxA, do not fall back to our default values

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7321]
After the work on #6854 if a user arrives on mozilla.org with UTM parameters we pass those along to FxA if they continue on to there.

The current code works like this:
1) put our own UTMs on
2) if there are UTMs in the URL replace ours with theirs
If the URL has 3/4 possible UTMs we leave the 4th value unchanged.

In https://github.com/mozilla/bedrock/issues/6854#issuecomment-500951475 Justin clarified that we should remove our own when adding others.

> If utm_* are present, let's not add any of our own. We do add missing ones on desktop downloads because all 4 (source/campaign/medium/content) are required by stub attribution, but there is no such requirement in FxA, and adding them just muddies the water.

Tasks
- [x] update the JS to remove our UTMs if other UTMs are present
- [x] update the tests
- [x] update the docs

**Comment by alexgibson** [comment]
According to our [documentation](https://bedrock.readthedocs.io/en/latest/firefox-accounts.html) things like `utm_campaign` are considered required, and our macros often bake-in defaults, such as `utm_campaign=fxa-embedded-form`.

Given the above, what are the rules we should follow here if it means we can potentially drop certain params?

Should we only replace UTMs on links if there is a minimum of valid params on the URL? (e.g. both `utm_source` and `utm_campaign` must exist and be valid, else we do nothing?)

Thoughts @hoosteeno?
