### ISSUE TITLE
Consider adding "Release Notes" links in global navigation / footer.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7323]
## Description
Now that [release notes](https://www.mozilla.org/firefox/releasenotes/) have been updated and ported to Protocol, we should consider adding more easily discoverable links in the main nagivation.

### Steps to reproduce

1.) Visit https://www.mozilla.org.
2.) Hover over the "Firefox" link in the main navigation.

### Expected result

There should be a link to "Release Notes" under "Firefox Desktop Browser", and also a "Release Notes" link under "Firefox Mobile Browsers".

### Actual result

It's impossible to find release notes.

### Environment

Any browser

**Comment by alexgibson** [comment]
Alternatively, if we think the global navigation is not the best place for this, adding a "Release Notes" link somewhere in the main footer would be another option.

**Comment by ShivanshRakesh** [comment]
Adding a link to 'Release Notes' in the footer menu would work I guess. Should the link be added in Primary Footer (`<nav class="mzp-c-footer-primary">`) or Secondary Footer (`<nav class="mzp-c-footer-secondary">`) ?

**Comment by RCMainak** [comment]
If this issue is up for grab then I would love to work on it.

**Comment by ShivanshRakesh** [comment]
@RCMainak I too am on it. Waiting for confirmation from @alexgibson.

**Comment by alexgibson** [comment]
We need to decide where this is ooing before we can take action on it.

**Comment by ShivanshRakesh** [comment]
> Adding a link to 'Release Notes' in the footer menu would work I guess. Should the link be added in Primary Footer (`<nav class="mzp-c-footer-primary">`) or Secondary Footer (`<nav class="mzp-c-footer-secondary">`) ?

Won't this work as a solution to the issue?

**Comment by alexgibson** [comment]
> Won't this work as a solution to the issue?

Yes, but what I mean is we don't know if that's the solution we want just yet. This bug isn't quite ready to work on.

**Comment by alexgibson** [comment]
Since opening this issue release notes have been added as a link to the firefox navigation, closing.
