### ISSUE TITLE
Updating newsletter preferences could use some UX improvements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7324]
## Description

After updating my newsletter preferences, the ["thank you" page](https://www.mozilla.org/en-US/newsletter/updated/) could use some UX improvements.

### Steps to reproduce

1. From https://accounts.firefox.com/settings, I clicked "Email preferences", which took me to the /newsletter/existing/ page on mozorg.
2. I subscribed to a couple of newsletters and clicked "Save Preferences".

### Expected result

After clicking save, I should be returned to some kind of nicely designed and informative web page.

### Actual result

The page looks kinda broken. There's a tiny bit of misaligned text thanking me for updating my preferences. The cross-promotion of other products is also pretty minimal, showing text-only links. We could offer something more up-to-date and visually appealing.

![image](https://user-images.githubusercontent.com/400117/59516577-8ac87e00-8eb9-11e9-8abd-3637e6ffef59.png)

**Comment by hoosteeno** [comment]
We'll need to break this into design, copy and code cards. Needs specification.

**Comment by cgonz0** [comment]
Updating with new image of what's currently up after protocol porting

![Screenshot_2020-01-10 Newsletter Subscriptions(3).png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/747cf28d-d6d7-4b8a-9596-12c9621bb9f6)

**Comment by hoosteeno** [comment]
@cgonz0 can you update with status? Is this still in progress?

**Comment by cgonz0** [comment]
@hoosteeno this is in progress - we did initial copy/design, but still needs brand review. would be good to have separate copy and design cards
