### ISSUE TITLE
Update l10n bedrock docs

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7344]
## Description

* Noticed that https://bedrock.readthedocs.io/en/latest/l10n.html is missing the `$ source venv/bin/activate` step.

Suggestion: move the link to https://mozilla-l10n.github.io/documentation/products/mozilla_org/working_bedrock.html#extracting-strings-from-a-template to the top of the page? I skimmed past it at first.

* **String Extraction documentation**: https://docs.google.com/document/d/e/2PACX-1vRKrVSuY7WSj_xvEDaU7T8Tu4bwAIPPOh8caPdLP0pmJh332ki81W8f-ficYmNApbuZ5IRG1eAaRqq-/pub

**Comment by Parikshit-Hooda** [comment]
Can I fix this issue?

**Comment by amychurchwell** [comment]
@Parikshit-Hooda feel free! no one has picked this up yet. 😄 Feel free to ping if you have any questions.

**Comment by amychurchwell** [comment]
[I wrote a "quick start" google doc for our newest dev](https://docs.google.com/document/d/1plFw0Yi6QEC6FWR5RgHuqW-mZFSwaca1xquweg-9z3c/edit?usp=sharing), that we can use for the official docs. (Unfortunately, I believe this is only viewable by folks with a mozilla email)

**Comment by ejregithub** [comment]
Can this live on bedrock docs?

**Comment by amychurchwell** [comment]
@ejregithub yes! I was posting it as content for this docs update, planning on adding to docs when I have a free moment.

**Comment by Shivansh2407** [comment]
Can you explain more about this issue as I would like to fix this issue.

**Comment by amychurchwell** [comment]
@Shivansh2407 Hello, thank you for the interest! We would like to add the string extraction guidelines in [this document](https://docs.google.com/document/d/e/2PACX-1vRKrVSuY7WSj_xvEDaU7T8Tu4bwAIPPOh8caPdLP0pmJh332ki81W8f-ficYmNApbuZ5IRG1eAaRqq-/pub) to [bedrock's localization documentation](https://bedrock.readthedocs.io/en/latest/l10n.html).

The documentation files live in `.rst` files in this part of the repository: https://github.com/mozilla/bedrock/tree/master/docs

This addition would update the `l10n.rst` file - https://github.com/mozilla/bedrock/blob/master/docs/l10n.rst

**Comment by Shivansh2407** [comment]
I have added the content of the document from[this document](https://docs.google.com/document/d/e/2PACX-1vRKrVSuY7WSj_xvEDaU7T8Tu4bwAIPPOh8caPdLP0pmJh332ki81W8f-ficYmNApbuZ5IRG1eAaRqq-/pub) to https://github.com/mozilla/bedrock/blob/master/docs/l10n.rst
Please review the pull  request

**Comment by aniruddha2000** [comment]
Hey @amychurchwell I would like to work on this issue.

**Comment by aniruddha2000** [comment]
https://github.com/aniruddha2000/bedrock/commit/8801446036844d699f7c1abdc14f63445729e4ad I have added some changes in my fork. If the format seems ok then can i complete the rest documentation and open a PR for that? @amychurchwell

**Comment by aniruddha2000** [comment]
@amychurchwell have a look https://github.com/aniruddha2000/bedrock/blob/issue-7344/docs/l10n.rst#development :)

**Comment by amychurchwell** [comment]
This issue is being closed as a WONTFIX because this legacy system will be frozen in the near future. Thank you for the interest in helping us improve bedrock and apologies for any confusion. 🙂
