### ISSUE TITLE
Update jQuery library version

### ISSUE THREAD

**Issue by pdehaan** [mozilla/bedrock#7351]
## Description

I ran a Lighthouse audit in Google Chrome for https://www.mozilla.org/en-US/firefox/accounts/ and saw that it identified **jquery@3.2.1** as a questionable version.

**Snyk results:**

- https://snyk.io/test/npm/jquery/3.2.1
- https://snyk.io/vuln/npm:jquery?lh=3.2.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

### Steps to reproduce

1. Open Google Chrome
2. Go to https://www.mozilla.org/en-US/firefox/accounts/
3. Open DevTools > Audits
4. Click [Run audits] button.
5. Scroll down to "Best Practices" section in results after scan is done.

![Get_a_Firefox_Account_–_Keep_your_data_private__safe_and_synced](https://user-images.githubusercontent.com/557895/60299338-5bfece80-98e1-11e9-8d37-c2da123630f1.png)

### Expected result

No errors or warnings.

### Actual result

![Get_a_Firefox_Account_–_Keep_your_data_private__safe_and_synced](https://user-images.githubusercontent.com/557895/60299448-98cac580-98e1-11e9-87cf-782aa3ae14a8.png)

### Environment

macOS w/ latest Google Chrome.

**Comment by alexgibson** [comment]
Thanks for filing this, @pdehaan 👍

**Comment by ejregithub** [comment]
@alexgibson - please apply an Estimate (just your work, not Peter's) in this card

**Comment by alexgibson** [comment]
Done, thanks
