### ISSUE TITLE
Update firstrun page with Trailhead branding

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7354]
## Description

Update [firstrun page](www.mozilla.org/firefox/firstrun) with Trailhead branding

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Trailhead branding is on the default firstrun page at www.mozilla.org/firefox/firstrun
- [ ] Strings are not modified

#### Tasks
- [x] Design
- [x] Code
- [x] Code Review
- [ ] Launch

**Comment by mrkwvr** [comment]
updated design and animation![:firstrun.png](https://images.zenhubusercontent.com/5caf3c03b1a2d93c3b8e816d/77ac0748-7d57-4668-a7a3-d38d549e3362)
https://files.slack.com/files-pri/T027LFU12-FLBFYB8S0/sync_animation_1.gif

**Comment by hoosteeno** [comment]
Thanks @mrkwvr !

Do you think our revised value propositions fit well into this design? I'm thinking particularly about the Firstrun experience that most browsers get after Trailhead:

<img width="954" alt="Screen Shot 2019-07-16 at 9 24 42 AM" src="https://user-images.githubusercontent.com/94519/61307550-6525e180-a7a3-11e9-970d-7540ca4fe734.png">

We should aim to express the entirety of our brand pivot here, and I think what we have now is just the visual parts of that. Do you agree?

**Comment by mrkwvr** [comment]
@hoosteeno yes I agree that what was updated was around visuals such as typography, color, design patterns, etc. my understanding was that copy and content would not change on this page because of localization, but I may have gotten that wrong.

**Comment by hoosteeno** [comment]
Oh, interesting, I see that "Strings are not modified" in the success criteria. I don't recall the conversation around that. 

@ejregithub can you fill in the gaps here? Did we decide to go forward without new strings for the sake of speed?

**Comment by ejregithub** [comment]
@hoosteeno - that indeed was the case, to not modify strings (which would impact l10n) and simply get the visual refresh out to bring it on brand. Can we launch with this, as is, then iterate further with copy/design in a subsequent and as priority allows?

**Comment by hoosteeno** [comment]
Re: strings, yes.

@craigcook, can we build this with Protocol?

**Comment by hoosteeno** [comment]
r+ wc (Approved, with comments: I want @craigcook to confirm this is a protocol-ready design before we commit. If it is, we can move to code.)

**Comment by craigcook** [comment]
It looks Protocol-ready to me!

**Comment by mrkwvr** [comment]
awesome. I'll clean up the file and will post it later today

**Comment by ejregithub** [comment]
@Errolyn - when @mrkwvr posts the file, this one is yours.

**Comment by Errolyn** [comment]
Awesome I will keep an eye out for it.

**Comment by mrkwvr** [comment]
@Errolyn here's the final design sketch file. the animation is posted above in this issue. Let me know if you have any questions. 
[FX-firstrun.sketch.zip](https://github.com/mozilla/bedrock/files/3407946/FX-firstrun.sketch.zip)

**Comment by Errolyn** [comment]
Thanks! Will do!

**Comment by Errolyn** [comment]
I'm close to being done with the initial coding, I have a draft PR up and am going to get some feedback. I need the device gif (from above) without the background but that is in the works.
<img width="1436" alt="Screen Shot 2019-07-26 at 4 47 25 PM" src="https://user-images.githubusercontent.com/1214589/61986650-879ad480-afc5-11e9-8dde-3685207324af.png">

**Comment by Errolyn** [comment]
The gif without a background is in now and the PR is marked ready for review.

**Comment by Errolyn** [comment]
@mrkwvr @hoosteeno  Here is a demo link to view the changes: https://bedrock-demo-errolyn.oregon-b.moz.works/en-US/firefox/firstrun/

**Comment by hoosteeno** [comment]
Great, thank you.

I'd like to take this opportunity to bring the instrumentation on this page up to our new standards. 

1. Change utm_source to `mozilla.org-firstrun` in the metrics-flow request and in the URL on the button submit
2. Change the dataLayer parameters on the CTA button (this is a brand new standard). Eliminate `data-link-type` and `data-link-name`, and replace with:

```
  data-cta-type="FxA-Sync"
  data-cta-text="Register" 
  data-cta-position="Primary"
```

**Comment by amychurchwell** [comment]
@hoosteeno my understanding is both the `data-mozillaonline-link` and `data-mozillaonline-action` found on `fxa_email_form` and `fxa_link_fragment` reference a config value to provide conditional functionality based on distribution (China re-pack)
```
FXA_ENDPOINT_MOZILLAONLINE = config('FXA_ENDPOINT_MOZILLAONLINE',
                                    default='https://accounts.firefox.com.cn/')
```
Alex is in the process of writing documentation & will be updating: https://bedrock.readthedocs.io/en/latest/firefox-accounts.html 👏
