### ISSUE TITLE
Convert /privacy section to Protocol

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7358]
These pages are on a very out of date template. The brand team would like to update the section to better reflect our commitment to privacy. We've talked to legal and they would also like that.

With #7141 we have a template that can be used for most of the pages in the section. 

Legal has also requested that we update https://www.mozilla.org/en-US/about/legal/terms/mozilla/ as part of this work.

**Comment by alexgibson** [comment]
This was done
