### ISSUE TITLE
Remove Nick from leadership page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7374]
## Description

Remove Nick Nguyen from https://www.mozilla.org/en-US/about/leadership/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Nick no longer appears in the leadership page

#### Tasks
- [ ] Remove Nick Nguyen from https://www.mozilla.org/en-US/about/leadership/

**Comment by RCMainak** [comment]
I would like to work on this issue

**Comment by amychurchwell** [comment]
@RCMainak thank you so much for offering to contribute! Unfortunately, we needed to get a fix in right away. Thank you again and feel free to keep an eye out for any future issues that capture your interest! 😄
