### ISSUE TITLE
Minor string changes to new /enterprise page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7375]
## Description

Tyler (@skrelnick23) has asked for some minor changes to the /firefox/enterprise page. This page is in en-US only, so we can make string changes with abandon. 

Specs:

- [x] Strike two parts of the headline and subhead
- [x] Add an MSI installer line to the list of installer links
- [x] Make all installer links point at the new /firefox/all/ page

Mockup with specs:

![Screenshot_2019-07-03 Firefox Quantum for Enterprise Web Browser Firefox.png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/c6eaf9d1-6df7-44ea-a14a-db88b06a24fc)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] List of changes is coded & launched

**Comment by stephaniehobson** [comment]
I think it is a really bad user experience that all 3 links with different labels go to exactly the same page with no difference :(

**Comment by amychurchwell** [comment]
@stephaniehobson I would have to agree with you. I wonder if we could pass a parameter to the /all page to adjust what installer is selected when the user lands on that page?

**Comment by hoosteeno** [comment]
> @stephaniehobson I would have to agree with you. I wonder if we could pass a parameter to the /all page to adjust what installer is selected when the user lands on that page?

See also https://github.com/mozilla/bedrock/issues/7208
