### ISSUE TITLE
Standardize video GA events across mozorg

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7378]
## Description
Ensure key actions are being tracked in the same way across all videos.

---

#### Tasks
- [ ] Create a reusable video macro to ensure GA consistency.
- [ ] Video macro supports YouTube API & self-hosted video.
_Nice to have_: optional milestone tracking on video.

Data layer push from YouTube videos on homepage:
https://github.com/mozilla/bedrock/blob/df77b2e6c66b6f235060cbdc656f813b6802d1c2/media/js/mozorg/home/home.js#L79

**Comment by alexgibson** [comment]
Closing this out as most of the videos we host today are on youtube, and our scripts contain GA events.
