### ISSUE TITLE
Create an about-base.html that uses Protocol

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7386]
## Description

Currently, 26 templates extend `mozorg/about-base.html` which uses our older Pebbles design. We should create a Protocol version so we can gradually begin porting over this section of pages.

**Comment by alexgibson** [comment]
This might already be covered in https://github.com/mozilla/bedrock/issues/6822

**Comment by stephaniehobson** [comment]
This is covered in https://github.com/mozilla/bedrock/pull/7141/ :)

**Comment by amychurchwell** [comment]
@alexgibson @stephaniehobson awesome! :D I will close this as a dupe.
