### ISSUE TITLE
UTM values for FxA referrals are inconsistent across /whatsnew pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7387]
## Description

Whilst working on https://github.com/mozilla/bedrock/pull/7369 it became clear that our /whatsnew page templates lack a consistent format for passing UTM values on FxA referrals.

### Steps to reproduce

Examples:

- [Firefox 68 trailhead template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html#L13-L15)
- [Firefox 68 standard template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html#L13-L14)
- [Firefox 67 trailhead template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html#L41-L43)
- [Firefox 67 standard template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html#L20-L24)
- Firefox 66 template uses two conflicting sets of values:
  - [These seem unused](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html#L19-L23)
  - [Are these ones correct?](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html#L52)
- [Firefox 65 template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html#L36)

### Expected result

There should be a standardized set of parameters, and these should be documented somewhere.

### Actual result

I have no real idea which format is correct.

### Environment

N/A

**Comment by hoosteeno** [comment]
See also: https://github.com/mozilla/bedrock/pull/7113

**Comment by amychurchwell** [comment]
Format:
```
utm_source='whatsnew-#',
utm_params={'
    campaign': 'fxa-embedded-form', // [urlsafe category of CTA, ex: globalnav]
   'content': 'get-firefox-account', // [urlsafe content of CTA, ex: get-firefox-account]
   'medium': 'referral'}) // [medium should always be referral.]
```

`content` should no longer be vague 'whatsnew' because we already get this information from source. I wonder if the `fxa_email_form` even needs the `content` value because knowing `campaign: 'fxa-embedded-form'` we know what the CTA is? @stephaniehobson

**Comment by stephaniehobson** [comment]
Content is an optional parameter so we would be safe dropping it. In this case I agree it isn't useful.
