### ISSUE TITLE
Improve universal stylesheet served to old IE browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7390]
## Description

The universal stylesheet we serve to IE8 and below could benefit from some minor tweaks to make it a bit more readable:

<img width="1659" alt="Screenshot 2019-07-08 at 14 11 07" src="https://user-images.githubusercontent.com/400117/60812848-57140780-a18a-11e9-860f-23c1207ba796.png">
 
1. The navigation contains many links, which pushes the main page content down a long way. We could provide a really basic layout for this so that it doesn't take up so much height.
2. Hide the useless `<button>` elements (e.g. "Menu", "Close Firefox Menu"), that don't do anything without the JS.
3. Improve readability by placing all content within a centered container in the page and a set max-width.
4. Hide content that is only really meant for Firefox users.
5. Anything else?

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Browsing the no-frills site is a slightly more pleasant experience.

#### Tasks
- [x] Update legacy IE stylesheets.

**Comment by hoosteeno** [comment]
@alexgibson do we know enough about this to estimate the effort of it?

**Comment by alexgibson** [comment]
@hoosteeno probably a days work, possibly a 3.

**Comment by alexgibson** [comment]
This is now up on demo at: https://bedrock-demo-agibson.oregon-b.moz.works/

Screenshots for those without VMs:

**Homepage before & after:**

![homepage-ie](https://user-images.githubusercontent.com/400117/62202638-8d0b6c80-b381-11e9-97c9-83de8d7b5c22.png)

**/firefox before & after**

![firefox-ie](https://user-images.githubusercontent.com/400117/62202657-97c60180-b381-11e9-8bf1-df18a418b455.png)

**/accounts before & after**

![accounts-ie](https://user-images.githubusercontent.com/400117/62202684-a6acb400-b381-11e9-9ccf-3be5a12d484c.png)

**/channel before & after**

![channel-ie](https://user-images.githubusercontent.com/400117/62202709-b3c9a300-b381-11e9-82cd-cb3fdc09627b.png)
