### ISSUE TITLE
Remove instances where both data-link-type and data-button-name attributes are used.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7392]
## Description

We should not use `data-link-type` and `data-button-name` attributes together or the event will be captured twice by GA.

I have found two places in bedrock this occurs: 
- In the mission CTA in the `about-2019.html` template.
https://github.com/mozilla/bedrock/blob/f6b1b88b778b3096da45bfe2b4322147e9eeb71d/bedrock/mozorg/templates/mozorg/about-2019.html#L40

- The `fxa_banner` macro in `macros.html`
https://github.com/mozilla/bedrock/blob/f6b1b88b778b3096da45bfe2b4322147e9eeb71d/bedrock/mozorg/templates/mozorg/home/includes/macros.html#L62

**Comment by amychurchwell** [comment]
Instead of `data-link-type="button"` we should add `role='button'` to these links.

**Comment by stephaniehobson** [comment]
I don't think there's any value to adding `role="button"` to the links. That will signal to screen readers that these are buttons when they are actually links. (links go places buttons do things). We can remove the analytics code without impacting the screen reader experience.

**Comment by amychurchwell** [comment]
@stephaniehobson totally agree with the links = navigation & buttons = action comment. I included that comment because, at a glance, I was under the impression the links were meant to be perceived as buttons due to the `mzp-c-button` class.

**Comment by alexgibson** [comment]
I was reading our docs on this to try and understand what we should / shouldn't be using. Currently we have this:

```
For all nav, footer, and CTA/button link elements, add these data attributes:

+--------------------------+--------------------------------+
|    Data Attribute        |        Expected Value          |
+==========================+================================+
|    data-link-type        | 'nav', 'footer', or 'button'   |
+--------------------------+--------------------------------+
|    data-link-name        | name or text of the link       |
+--------------------------+--------------------------------+

For all button elements, add this data attribute:

+--------------------------+--------------------------------+
|    Data Attribute        |        Expected Value          |
+==========================+================================+
|   data-button-name       | name or text of the link       |
+--------------------------+--------------------------------+
```

This to me says:

- If it's a `<button>` element, use `data-button-name`.
- If it's a <a href="#" class="mzp-c-button"></a>`, use `data-link-type="button"` and `data-link-name`.

Have I interpreted that correctly? If so, the [Monitor button macro](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros.html#L259) may also need some attention.

**Comment by amychurchwell** [comment]
@alexgibson that is my impression as well.

@Errolyn so for this issue we should: 
1. Remove `data-button-name` on any element that is not a button and add `data-link-name` for what we want the event label to be- so the text of the cta.

2. For the monitor button macro that Alex mentioned, we want to remove `data-button-name="Continue"` and replace it with `data-link-name="Continue"` and add `data-link-type="button"`

**Comment by Errolyn** [comment]
Ok that makes sense, I will make those changes.

Thanks for all the input!
