### ISSUE TITLE
Fix italic addresses on /contribute/events/

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7398]
## Description
On [/contribute/events](https://www.mozilla.org/contribute/events/) we recently added the `<address>` element to event addresses to make the markup more semantic. Unfortunately, the address element has the default style of italics.

## Tasks

We will need to override the `<address>` default styling in the contribute .less file under `.events-table` with `font-style: normal`:
https://github.com/mozilla/bedrock/blob/f56fb567a61d1ef43ca3222c122a2c1dd52feec0/media/css/mozorg/contribute/contribute-base.less#L1006

**Comment by amychurchwell** [comment]
**Note:** This template uses a _very old_ design system (sandstone) and at some point needs to be redesigned in [protocol](https://protocol.mozilla.org/). --that aside, I thought I would file this as a easy first bug for anyone interested.

**Comment by Errolyn** [comment]
I have added myself to keep an eye out if tanuja3 has any questions on this :)
