### ISSUE TITLE
The newest ESR version should be the default on the firefox/all/ page

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#7408]
When you select ESR on the new [/firefox/all/](https://www.mozilla.org/firefox/all/) page during the time when we have two versions on offer the newest version should be the default one selected. This is the way the current [/firefox/organizations/all/](https://www.mozilla.org/firefox/organizations/all/) page works during this time.

**Comment by devinreams** [comment]
Related and perhaps worth fixing separately (or at the same time), is that the "old"-ish organizations page shows a hard-coded value for the ESR version (60 currently, but should be 68):

https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/organizations/organizations.html#L37

**Comment by pmac** [comment]
From an external conversation it sounds like I have this backward. The desire from the Enterprise team is that the older ESR should remain the default offered for download until it is retired. So for now I think both the new /all/ page and the current /organizations/ page are correct. Do you agree @devinreams ?

**Comment by devinreams** [comment]
That's my understanding too, thanks @pmac. To summarize:

- https://www.mozilla.org/en-US/firefox/all/ defaults to 60.8 ESR as expected ✅ 
  - but when selecting 68 does not offer the new MSI 🔗 #7410
- https://www.mozilla.org/en-US/firefox/organizations/ says the current ESR (60) as expected ✅ 
- https://www.mozilla.org/en-US/firefox/organizations/all/ but this view defaults to 68 (which is the link from `/organizations`) which is not the ESR, should be 60 ❌

**Comment by pmac** [comment]
So since the /organizations/all/ page is slated for decommission is it okay if we just allow that to happen naturally, close this issue, and fix #7410? Or do we need to fix the /organizations/all/ page in the interim?

**Comment by devinreams** [comment]
>So since the /organizations/all/ page is slated for decommission is it okay if we just allow that to happen naturally, close this issue

Oh yes, absolutely. I missed the decommission/localization stuff in-flight. Assuming the URL redirects cleanly then this seems to A-OK as-is. Thanks very much👌

**Comment by pmac** [comment]
Great! Thanks for the help Devin!
