### ISSUE TITLE
Selecting ESR on /all should let me download an MSI installer

### ISSUE THREAD

**Issue by rtestard** [mozilla/bedrock#7410]
## Description
ESR versions 68+ have MSI installers built for them. These should be exposed on https://www.mozilla.org/en-US/firefox/all/

### Steps to reproduce
On https://www.mozilla.org/en-US/firefox/all/ select "Firefox Extended Support release" and then "68.0ESR" 
Selecting your preferred installer should offer the MSI installer options for 32 and 64 bit.
Note that 60.X ESR versions don't have MSI installers.

### Expected result
32 and 64 bit MSI installers appear on the "Select your preferred installer" drop down if "68.0ESR"  is selected.

### Actual result
32 and 64 bit MSI installers do not appear currently

### Environment

Windows 10 with Firefox Nightly 69

**Comment by alexgibson** [comment]
Thanks for the report, I can take a look at this.
