### ISSUE TITLE
Add /.well-known/change-password route?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/bedrock#7420]
## Description

Had this discussion in https://github.com/mozilla/blurts-server/issues/1112 and not sure if it fits here as well.

Luke mentioned a https://wicg.github.io/change-password-url/index.html doc which outlines an endpoint for changing passwords.

https://news.ycombinator.com/item?id=18618193

### Steps to reproduce

1. Go to https://www.mozilla.org/.well-known/change-password

### Expected result

Redirect to a page where I can change my mozilla.org password?

### Actual result

Redirected to https://www.mozilla.org/en-US/.well-known/change-password which seems to be a 404 page.

Or maybe this is a non-bug since I'm not sure you can log in to mozilla.org proper, and maybe this needs to be filed specifically against BMO and AMO.

- https://bugzilla.mozilla.org/.well-known/change-password simply 404s.
- https://addons.mozilla.org/.well-known/change-password/ (redirects to https://addons.mozilla.org/en-US/firefox/.well-known/change-password/ which 404s). Not sure if it should redirect to https://accounts.firefox.com/.well-known/change-password.

### Environment

Firefox macOS (both latest versions).

**Comment by pmac** [comment]
Which mozilla.org password would this be? www.mozilla.org has no authentication at all, and FxA isn’t at a mozilla.org domain. I know there are services at mozilla.org subdomains that have passwords, but most of them use our SSO and it wouldn’t be clear to me which we would point to.

> Or maybe this is a non-bug since I'm not sure you can log in to mozilla.org proper, and maybe this needs to be filed specifically against BMO and AMO.

I think that’s right.

**Comment by pdehaan** [comment]
Great! Thanks for the clarification. I'll close this and file against AMO and BMO separately.
