### ISSUE TITLE
Push Transparency Reports on 8/8

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7422]
Both Transparency Reports need to go live on 8/8 (edited). Per Mika and discussion with Alex, we can take these live in the wee hours of the day, Pacific Time so they're available for press/comms when they get to work.

https://github.com/mozilla/bedrock/issues/7356
https://github.com/mozilla/bedrock/issues/7036

**Comment by ejregithub** [comment]
Per email from Mika earlier - the go live date is pushed out to the following Tuesday, August 6th. I'm updating the rest of this issue accordingly.

**Comment by alexgibson** [comment]
@ejregithub I'm on PTO on this 6th, so we'll have to find someone else to do this.

**Comment by ejregithub** [comment]
@Errolyn - how do you feel about an early start on August 6th to push this out?

**Comment by Errolyn** [comment]
That is doable as long as it is possible to do at my house. I will also need to learn how to deploy the site before then :) what time are we thinking, 6-7am, earlier?

**Comment by ejregithub** [comment]
> That is doable as long as it is possible to do at my house. 
@Errolyn - i'm certain you can do this remotely, yes.

> I will also need to learn how to deploy the site before then :) 
Yes! Please reach out to a fellow dev, probably @alexgibson, for that tutelage. 

>what time are we thinking, 6-7am, earlier?
That's perfect, pushing in that time frame.

**Comment by ejregithub** [comment]
@Errolyn - Mika requested one more update to the 2018 H2 report. The change requested can be seen in the bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1564532

We're now moving the go live date to Thursday August 8th, still between 6 - 7 am (I've updated this issue accordingly).

**Comment by Errolyn** [comment]
This is done!
