### ISSUE TITLE
Defer loading YouTube API on homepage

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7423]
### Steps to reproduce

1. Using an up-to-date Firefox Nightly, visit: https://www.mozilla.org/en-US/
2. Observe the purple tracking protection shield in the address bar.
3. Clicking the purple shield icon shows that Firefox blocked a tracking cookie from youtube.com.

<img width="1679" alt="Screenshot 2019-07-12 at 08 56 06" src="https://user-images.githubusercontent.com/400117/61112258-5974ab00-a483-11e9-88d3-7b8bd70e379a.png">

### Expected result

There should be no tracker from youtube.com

### Actual result

A tracking cookie was blocked.

### Environment

Firefox Nightly 70.0a1 (2019-07-10) (64-bit)

**Comment by alexgibson** [comment]
The tracker is detected when the YouTube iframe API is loaded: https://github.com/mozilla/bedrock/blob/master/media/js/mozorg/home/home.js#L18-L19

The API is used mainly to track interaction events with the YouTube video: https://github.com/mozilla/bedrock/blob/master/media/js/mozorg/home/home.js#L64-L86

Options as I see it:

1. We could defer loading the script until after a user initiates the modal via a click. This would prevent the tracker being detected on page load, but it does not change the fact that we're using it.
2. We could remove the API entirely, and simply load the video inside an iframe hosted from https://www.youtube-nocookie.com. This means we would lose the API events linked above, but we would still get regular GA data on how many people click the card to open the modal. Users would also have to initiate the video manually by clicking play.
3. We could host the videos ourselves via the CDN. This means we could retain video interaction via native HTML Video events, but it would add a lot more process steps to get videos onto the homepage.

Given the above, my personal preference would be 2.

**Comment by alexgibson** [comment]
Thoughts @hoosteeno? ^

**Comment by alexgibson** [comment]
There are also other pages on the site using this same API: https://github.com/mozilla/bedrock/search?q=https%3A%2F%2Fwww.youtube.com%2Fiframe_api&unscoped_q=https%3A%2F%2Fwww.youtube.com%2Fiframe_api

**Comment by amychurchwell** [comment]
Note: decision here will affect work in #7378

**Comment by amychurchwell** [comment]
We heard in a meeting about GA & video with adswerve about an open source tool called videojs. 
https://docs.videojs.com/
Might be worth researching other custom player options for the long-term.

**Comment by alexgibson** [comment]
> https://docs.videojs.com/

This looks like to be a nice wrapper around the native video API, but I don't see anywhere in the docs around supporting videos loaded from YouTube.

**Comment by alexgibson** [comment]
There does seem to be an additional plugin to add youtube support here: https://github.com/videojs/videojs-youtube

**Comment by hoosteeno** [comment]
> Thoughts @hoosteeno? ^

For now I think we should defer loading the API until a user engages with the modal (option 1). Play/Finish are valuable data for video on the web.

**Comment by alexgibson** [comment]
Taking this on the premise that we're just going to defer loading the API until the user interacts with the card, and we can work on removing the dependency on this API later.
