### ISSUE TITLE
Update link in card on homepages for IHR 2019

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7429]
## Description

The card for the Internet Health Page 2019 on www.mozilla.org currently links to the https://internethealthreport.org/

It should link to the 2019 report itself https://internethealthreport.org/2019/ and be made specific to the language for each, EN, DE & FR homepages

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New link to the 2019 IHR is in place

#### Tasks
- [ ] Update link on each homepage, EN, DE & FR with appropriate language for DE & FR in each
- https://internethealthreport.org/2019/?lang=fr
- https://internethealthreport.org/2019/?lang=de

**Comment by Errolyn** [comment]
@ejregithub It looks like https://www.mozilla.org/de/ does not have a internet health report card, and https://www.mozilla.org/fr/ 's card is already using a the language appropriate link. Do we need to add an internet health report card for  https://www.mozilla.org/de/ ?

**Comment by Errolyn** [comment]
Once the issue above is merged, then I can update master with the changes assuming we don't need to add anything else.

**Comment by ejregithub** [comment]
@Errolyn - right you are. If there's not a card for IHR on the www homepage, we don't need to create one.  

Just to confirm, as reading back I don't know if I made it explicit in the tasks:

- The link on the en-US homepage for the IHR card will be changed to go directly to the 2019 report - https://internethealthreport.org/2019/
- The link on the FR homepage for the IHR card will be changed to go directly to the 2019 report - https://internethealthreport.org/2019/?lang=fr

**Comment by Errolyn** [comment]
That seems right, are we leaving the source info in the link `utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage-de&utm_content=card` or should I remove all that? @ejregithub if it doesn't need to be removed then fr is already good to go and it is one the English version of the site that need an update.

**Comment by ejregithub** [comment]
Yes @Errolyn - let's update the base URL only while leaving all the UTM goodness as it is now, please.

**Comment by Errolyn** [comment]
Awesome we should be set when link update gets approved.
