### ISSUE TITLE
Global nav CTA changes color and size.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7430]
## Description
On the homepage the global nav CTA is blue and larger than the others. This is true for both 'Get a Firefox Account' and 'Download Firefox'

We should make these consistent, the larger blue version is more legible.

<img width="249" alt="Screen Shot 2019-07-12 at 12 38 58 PM" src="https://user-images.githubusercontent.com/30483988/61154159-39a0af80-a4a2-11e9-97a1-9259609fde7e.png">
<img width="252" alt="Screen Shot 2019-07-12 at 12 38 51 PM" src="https://user-images.githubusercontent.com/30483988/61154160-39a0af80-a4a2-11e9-97b6-70fd0cb854e5.png">

**Comment by amychurchwell** [comment]
See also:  #7306

**Comment by amychurchwell** [comment]
This looks to be left over code from the global fxa cta experiment: https://github.com/mozilla/bedrock/pull/6695/
https://github.com/mozilla/bedrock/blob/d83bd3934b6014886e986a7073303b0e75b83292/media/css/pebbles/components/_protocol-nav.scss#L83

It looks like this was an intentional design decision (https://github.com/mozilla/bedrock/issues/6629)

> For Pebbles and Sandstone pages, the FxA button uses the older green outline secondary button, to remain consistent with those pages

I disagree that the FxA button being green creates consistency. A CTA in the nav should not change appearance from page to page in this way.

Example: Navigating from mozilla.org to /firefox via the navigation.
![globalnav-cta](https://user-images.githubusercontent.com/30483988/61156041-52f82a80-a4a7-11e9-842c-073dbc1a7669.gif)

**Comment by craigcook** [comment]
It's consistent on a single given page, at least. The button changing color in the nav was deemed less objectionable than having a page where two download buttons were two different colors. Neither option is good, I think this was chosen as the lesser evil.

The real solution is ending the green button once and for all and making it blue everywhere.
