### ISSUE TITLE
Port Legal pages to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7441]
## Description

The main `/legal/` pages are still built on Sandstone / Less. They can probably be ported pretty easily using the basic article template style.

https://www.mozilla.org/en-US/about/legal/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Legal pages are updated in production using Protocol.

#### Tasks
- [ ] Update templates.
- [ ] Remove old assets.

**Comment by stephaniehobson** [comment]
On it :)

**Comment by alexgibson** [comment]
@stephaniehobson are you actively working on this? The legal team have expressed wishes for these pages to be updated, and the websites team may have capacity to take this on next sprint. I'm going to add it to our suggested queue.

**Comment by stephaniehobson** [comment]
Yeah, I'm not working on it right now. I thought it would get done when we redid the privacy section but stuff happened.
