### ISSUE TITLE
WNP 69 - Extract strings for L10n on July 23rd

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7455]
Extract strings for localization in Pontoon.

**Comment by ejregithub** [comment]
@peiying2  - we need Anika and Malcom to localize this in Pontoon, not sure what you do to convey that to the community localizers that they should have first stasbe.  Craig is going to update the ask to put this out to all locales since we have final strings within the required (6 weeks) timeframe to request from the community.

**Comment by craigcook** [comment]
Strings extracted and merged in https://github.com/mozilla-l10n/www.mozilla.org/pull/326 and pushed to production in https://github.com/mozilla-l10n/bedrock-l10n/commit/b74406dfbfc193bdd0cb2d7912997bf9a883d736
