### ISSUE TITLE
Replace existing enterprise sign up form 

### ISSUE THREAD

**Issue by skrelnick23** [mozilla/bedrock#7469]
## Description

The current sign up form on the [/enterprise page](https://www.mozilla.org/en-US/firefox/enterprise/) is too long and too vague. The form has been updated and is now ready to have it "show up" on this [page](https://www.mozilla.org/en-US/firefox/enterprise/signup/). 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This form is able to be distributed to various stakeholders 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Timely completion will allow the enterprise team to close a sale by H2. 
[lead_form_final.html.zip](https://github.com/mozilla/bedrock/files/3403610/lead_form_final.html.zip)

**Comment by devinreams** [comment]
I created this pull request for the HTML field swap out: #7472
