### ISSUE TITLE
Remove the MoFo fundraising banner on 9/14

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7478]
## Description

This is the card/task to remove the MoFo fundraising banner made live on the site on 9/3

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The banner is removed from mozilla.org on 9/14

#### Tasks
- [ ] Remove the banner on 9/14

**Comment by alexgibson** [comment]
9/14 was a Saturday, so we're a little late in taking this down.

Rather than keeping in the cycle of removing this from the code-base and then re-coding it all over again next time, I think it's probably better just to toggle it off via a switch.

**Comment by alexgibson** [comment]
Disabled in https://github.com/mozmeao/www-config/compare/c43ca05d0e9c...2bc340cc82ed
