### ISSUE TITLE
iOS Firefox app: firefox/accounts shows disabled fxa_email_form

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7483]
## Description

When viewing firefox/accounts on ios (IRL phone) `fxa_email_form` shows disabled form button. 
We need to investigate functionality and possibly create a mobile-specific `fxa_email_form`.

![image](https://user-images.githubusercontent.com/30483988/61721615-99f2e500-ad1d-11e9-875d-fd36d18a7ba3.png)

**Comment by amychurchwell** [comment]
Note: this behavior does not occur when "faking" mobile in browser.

**Comment by amychurchwell** [comment]
Note: this behavior does not occur when "faking" mobile in browser.

**Comment by amychurchwell** [comment]
This bug seems to occur in the iOS Firefox app.

- Safari for iOS works as expected.
- Firefox Preview on Android and Chrome on Android work as expected.

**Comment by amychurchwell** [comment]
**Update:**
Fetch API not supported in Firefox iOS.*
`fxaSubmitButton.disabled = true;` remains disabled until `fetchTokens()` is called. If not supports fetch, button remains disabled. Which is the behavior here.

https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-form.js#L42-L45

This JS needs to be refactored a bit. Adding this comment to issue description.

_*can't find evidence to the contrary_

**Comment by amychurchwell** [comment]
**Update:**

When opening `fetch` [codepen test](https://codepen.io/anon/pen/VoeRrL ) on Firefox iOS event fires as expected. 😕

**Comment by alexgibson** [comment]
I couldn't find any documented way to debug Firefox for iOS locally (ugh 😕), so I wrote a quick custom `onerror` function to alert any JS errors in the page:

```javascript
window.onerror = function(error) {
    alert(error);
    return false;
};
```

When visiting the URL the result is:

`TypeError: null is not an object (evaluating 'userVer.match(/^(\d+(?:\.\d+){1,2})/)[1]')`

That looks to be inside this function: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-client.js#L195

Which is called here: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-client.js#L286

We don't seem to have any logic in place to reason about whether Firefox for iOS is up to date or not. I'm not 100% sure if we have that readily available in product details yet, at least not something we can query in bedrock pages.

For now, we may need to add some custom logic here to return `true` is the user agent is Firefox for iOS (i.e. assume it's up to date).
