### ISSUE TITLE
Firefox logo warped on DevEd What's New Page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7484]
## Description

The Firefox logo on https://www.mozilla.org/en-US/firefox/68.0a2/whatsnew/ is the wrong dimensions in Dev Edition.

### Steps to reproduce

1) Open Dev Edition
2) Visit: https://www.mozilla.org/en-US/firefox/68.0a2/whatsnew/
3) See problem

### Expected result

<img width="447" alt="Screen Shot 2019-07-23 at 4 23 26 PM" src="https://user-images.githubusercontent.com/854701/61753990-3d67e800-ad66-11e9-95ad-e5252460c55e.png">

Or maybe the Dev Edition logo?

### Actual result

<img width="581" alt="Screen Shot 2019-07-23 at 4 22 02 PM" src="https://user-images.githubusercontent.com/854701/61753972-2aedae80-ad66-11e9-82c9-7775b8259fc0.png">

### Environment

Dev Edition, MacOS.

**Comment by craigcook** [comment]
The same on https://www.mozilla.org/firefox/67.0.1/whatsnew/ and https://www.mozilla.org/firefox/68.0/whatsnew/ (they're all the same page).

The image is set to `width="147"` but should be `width="159"`

**Comment by craigcook** [comment]
We're currently showing the same template to release, beta, and dev edition, but I think we should show the correct logo for each channel. That's a little more work than just fixing the width right now, but we could do that as part of building the new modular page.
