### ISSUE TITLE
Add Emphasis box to the need help section on /firefox/unsupported-systems/

### ISSUE THREAD

**Issue by Errolyn** [mozilla/bedrock#7497]
## Description

Add Emphasis box to the "need help" section on [/firefox/unsupported-systems/](https://www.mozilla.org/en-US/firefox/unsupported-systems/) once the emphasis box is available in protocol [mozilla/protocol/issues/385] as discussed in https://github.com/mozilla/bedrock/pull/7470.  

Should look something like this:

<img width="1358" alt="Screen Shot 2019-07-30 at 1 00 14 PM" src="https://user-images.githubusercontent.com/1214589/62160965-0cd60000-b2ca-11e9-8453-c11553a65e05.png">

## 🐬  Success Criteria 🐬 
- [ ] Page has an emphasis box around the get help content

**Comment by jhasaurabh312** [comment]
@Errolyn can i open a pr regarding this issue?

**Comment by Errolyn** [comment]
@jhasaurabh312 The emphasis box should be ready soon. I'll update this issue as soon as it has landed in protocol. Then you will be more then welcome to work on it :D Thanks for your interest!

**Comment by Errolyn** [comment]
The emphasis box will show up here when it has landed: https://protocol.mozilla.org/patterns/molecules/emphasis-box.html

I hope to have it added by next week.

**Comment by jhasaurabh312** [comment]
Ok!! thanks for your approval.

**Comment by sarathsomana** [comment]
@Errolyn https://protocol.mozilla.org/patterns/molecules/emphasis-box.html is leading to 404. I see that the emphasis box implementation was merged in #441. Is there an issue to track the documentation for the same ?

**Comment by Errolyn** [comment]
@sarathsomana It will be in our next release of protocol. I'll talk to the team to find out when that is going to happen.

**Comment by sarathsomana** [comment]
@Errolyn Sure, Thanks. I'm planning to work on this once I get an update.

**Comment by Errolyn** [comment]
@sarathsomana The emphasis box is available for use now if you want to go ahead and work on this issue, let me know if you have any questions! You can find the usage here: https://protocol.mozilla.org/patterns/molecules/emphasis-box.html

**Comment by Shivansh2407** [comment]
Can I work on this issue....Please guide me how to proceed .... Thanks

**Comment by aditya-hari** [comment]
@Errolyn Would changing the class of the section to "mzp-c-box-emphasis" be enough?
