### ISSUE TITLE
GA Instrumentation of VPN Premium Services Site

### ISSUE THREAD

**Issue by sghoseWI** [mozilla/bedrock#7499]
Need: to measure users and people clicking the primary CTA on the website

Further details on custom event requirements will be coming in a document, similar to this from last year: https://docs.google.com/document/d/1ZMhI1GzVmQFEJnAs5r9YB3btk2JycQ42GKLvgjep8SI/edit#heading=h.nclzritcivwg, from Chris More.

**Comment by ejregithub** [comment]
@sghoseWI - since this page/site https://premium.firefox.com/vpn/ is not hosted on bedrock (www.mozilla.org), we shouldn't be tracking in the bedrock repo. We can, however, track in the Websites Sprint Roadmap Trello board, to which I've just invited you - (and I'll mull on a better solution)

**Comment by sghoseWI** [comment]
@ejregithub thanks for helping out on this -- I received the invite to the Trello board!
