### ISSUE TITLE
GA Instrumentation of private-network.firefox.com Site

### ISSUE THREAD

**Issue by sghoseWI** [mozilla/bedrock#7500]
Requirements will be determined at a meeting with the stakeholders on 8/1

**Comment by ejregithub** [comment]
@sghoseWI - since this site private-network.firefox.com is not hosted on bedrock (www.mozilla.org), we shouldn't be tracking in the bedrock repo. We can, however, track in the Websites Sprint Roadmap Trello board, to which I've just invited you - (and I'll mull on a better solution)
