### ISSUE TITLE
CRO Sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7504]
## Description

Build a CRO (conversion rate optimization) sandbox in Bedrock and port 2 pages into it.

---

**Comment by hoosteeno** [comment]
@alexgibson I just want to call your attention to this epic, which was added to the board late, but which we intended to work on this sprint. You and I previously articulated the work needed, which are the cards included in this epic. 

This work is somewhat dependent on our CRO solution, but as we've discussed in other forums, the sandbox is a convenient segmentation tool regardless of how we build/distribute experiments, so I think the preliminary work (https://github.com/mozilla/bedrock/issues/7505)is a good investment.

**Comment by alexgibson** [comment]
All dependencies are closed here, and we're now running the second CRO experiment. Closing this epic!
