### ISSUE TITLE
CRO Sandbox - Determine technical approach for sandboxing

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7505]
## Description

We should design a sandbox that we can segment some www.mozilla.org audience to, for some www.mozilla.org content. Some technical requirements/details we've agreed on:

- Only javascript-enabled browsers
- Common segmentation characteristics possible (user agents, locales, OS)
- Single-page experiences only (to start)
- URL can be different if helpful (e.g. /exp/firefox/new/)
- URL parameters passed through

---

#### :yellow_heart: Success Criteria :yellow_heart:
- Approach is defined well enough to build (it could be in a comment below or in a document)

**Comment by alexgibson** [comment]
WIP technical proposal: https://docs.google.com/document/d/1RXzBVUk3LSbyBeJOesPrKcekvA5bOUBiUIiQy7frHgQ/edit?usp=sharing

@hoosteeno feel free to review / comment ^

Once you've taken a look here and given feedback, I'd like to get some of the other engineers to review this. Thanks

**Comment by alexgibson** [comment]
@stephaniehobson @craigcook @amychurchwell @Errolyn please see the above proposal for how we might implement the experiment sandbox. ^

Any feedback or suggestions, please comment in the doc. Thanks
