### ISSUE TITLE
Build a sandbox for CRO

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7508]
## Description

Implement the sandbox defined in #7505: https://docs.google.com/document/d/1RXzBVUk3LSbyBeJOesPrKcekvA5bOUBiUIiQy7frHgQ/edit?usp=sharing

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Sandbox is built and a) ready to port content to b) ready to send audience to

**Comment by alexgibson** [comment]
The initial pages in the sandbox will be:

- `/en-US/exp/firefox/new/`
- `/de/exp/firefox/new/`

For now we'll be hardcoding the strings for `de`, rather than exposing the strings through pontoon.

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/7700

**Comment by alexgibson** [comment]
@hoosteeno I've implemented convert in the PR referenced above, and pushed it to demo here:

https://www-demo3.allizom.org/en-US/exp/firefox/new/

In the convert dashboard I've set up a simple A/B test (in the staging project) that changes the headline. It seems to be working ok and tracking as expected. Please take a look.

Things to note:

- I've implemented loading their script dynamically (async). This means that if the script is slow to load, or unresponsive, our visitors won't be left looking at a blank screen & loading spinner. This can mean that swapping out varation content may be visible during page load, but as long as their CDN is fast I don't think the experience is too jarring. This is a better (imho) alternative to blocking on a third-party resource.
