### ISSUE TITLE
Port Speaker Request and Press Inquiry forms to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7512]
## Description

Port the following pages to Protocol.

- https://www.mozilla.org/en-US/press/speakerrequest/
- https://www.mozilla.org/en-US/press/press-inquiry/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are in production using Protocol.

#### Tasks
- [ ] Update templates.
- [ ] Remove legacy assets.

**Comment by amychurchwell** [comment]
Noticed that that "Media Library" link `https://blog.mozilla.org/press/media-library/` 404s under "Resources." Should we remove or replace with a different link? (Not sure what media library is.)

**Comment by alexgibson** [comment]
@amychurchwell I'm not sure on the answer to that question, but I wouldn't worry too much about it blocking porting of the page. We can always file a separate issue to find out if that should be updated or removed.
