### ISSUE TITLE
L10n example page throws a 500 error

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7519]
## Description

We have an (old) L10n example page that is throwing an error in production.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/l10n_example/

### Expected result

The page should shown an l10n example.

### Actual result

The page throws a 500 error. Running locally, the error says `TemplateDoesNotExist l10n_example/example.html`

### Environment

Any browser.

**Comment by alexgibson** [comment]
@pmac this page has likely not been working for a long time. Is there any reason why we might want to revive it (for the new system perhaps?). Else I think we can just delete it.

**Comment by pmac** [comment]
Looking at what's in that `l10n_example` app I can't imagine why we'd need to keep it around. I vote for removal.
