### ISSUE TITLE
Noindex urls in sitemaps

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#7521]
## Description
**I found some urls being noindex but included in the sitemaps:**

/firefox/content-blocking/start/
/firefox/this-browser-comes-highly-recommended/
/firefox/dedicated-profiles/
/newsletter/fxa-error/
/firefox/installer-help/
/newsletter/country/success/
/newsletter/opt-out-confirmation/
/firefox/enterprise/signup/

### Steps to reproduce

<img width="1531" alt="Screenshot 2019-08-05 at 13 53 47" src="https://user-images.githubusercontent.com/36700618/62462762-7ea9c000-b788-11e9-97da-1a7f254ecba5.png">

### Expected result

Urls with noindex must not be included in sitemaps

**Comment by pmac** [comment]
It's a simple matter of updating the `NOINDEX_URLS` setting in `bedrock/settings/base.py`. We should make sure to update this whenever a noindex is added to a template. I'll have a PR in shortly for these.
