### ISSUE TITLE
Remove jQuery as a dependency from stub-attribution.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7524]
## Description

There are a few areas in [stub-attribution.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/stub-attribution.js) that rely on jQuery. We should replace these function calls with vanilla JS equivalents.

It's worth noting that stub-attribution is currently served to [even old IE browsers](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-pebbles.html#L121-L125). Before making this change, we need to consider if this level of support is still necessary, or if we can move this bundle to 1st class supported browsers only.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Code is running in production using vanilla JS.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Dropping support for a legacy browser may see a drop in attribution data.

#### Tasks
- [ ] Refactor code.

**Comment by rbrishabh** [comment]
Hey! Can I take this up? :)

**Comment by alexgibson** [comment]
This is not yet ready to work on

**Comment by alexgibson** [comment]
I did a little poking at this today, and I think we can still make this work as far down as IE8 as long as we use `onreadystatechange` instead of `onload` for the XHR request. 

We only get a very small fraction of visitors on still IE6/7, which is probably a not very significant amount of attribution data. With that in mind, I think proposing we drop those browsers is OK.
