### ISSUE TITLE
Add Data Privacy Promise page to mozilla.org

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7525]
The Data Privacy Promise was initially published on the Firefox blog because it was tied to the Trailhead release and there wasn't adequate time to create a page and get it localized (it was still being written). Since then we've referenced it in a few places and it might be good to give it a permanent home in bedrock, which would also allow us to translate it in more languages.

https://blog.mozilla.org/firefox/firefox-data-privacy-promise/

**Comment by Patil2099** [comment]
@craigcook Can I work on this?

**Comment by alexgibson** [comment]
Since this issue was opened this page has been rolled up into https://github.com/mozilla/bedrock/issues/7766, so we don't need this particular issue any longer. Thanks for showing interest though 👍
