### ISSUE TITLE
Stop double-requesting Flow IDs on WNP69+

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7532]
## Description

On WNP 67.0.1 and 68, we double-request Flow IDs. We do it once for the form shown to signed-out users (https://github.com/mozilla/bedrock/blob/1608cf38e0b530769c50bdfaa6db22dbcccf9829/media/js/base/mozilla-monitor-button.js) and once for the form shown to signed-in users (https://github.com/mozilla/bedrock/blob/432985279224bc492d2a0b591f25c272b2c7f456/media/js/base/mozilla-fxa-form.js).

Here's what that looks like in the network request panel:
![Screen Shot 2019-08-05 at 5 15 49 PM](https://user-images.githubusercontent.com/94519/62500672-da824200-b7a4-11e9-8ab8-9d82f3284a9f.png)

**We should not request Flow IDs when we don't show the UI for the flow they relate to.** Doing so inaccurately increments the number of views of that UI element. Specifically, in this case, when a signed-in user sees the Monitor button, Amplitude still increments the number of visitors to the FxA email-first sign-in form, even though a signed-in user could not interact with that form. 

We should only request one Flow ID per pageload. We should make this change to WNP69+, but not to WNP68* and below.

**Comment by amychurchwell** [comment]
@alexgibson I recommended on the WNP69 issue that we keep `js/base/mozilla-fxa-form.js` and `js/base/mozilla-monitor-button.js` in separate JS blocks separated by some logic (if user is signed in = `mozilla-monitor-button.js`, if signed out = `mozilla-fxa-form.js`) to avoid the double request.

Do you know of a way that we can detect if the fetch request to fxa has been made already that we could include in the JS itself? (or perhaps Python?) 
It would be nice if there was a way to say: if server value `settings.FXA_ENDPOINT` has had a `fetch` request in this session, do not make a second request. Could we test for this?

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7588
