### ISSUE TITLE
Retrieve deviceID from metrics-flow requests and add to downstream referrals

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7533]
## Description

We make requests to the FxA servers "metrics-flow" endpoint in several places on Bedrock:

https://github.com/mozilla/bedrock/search?q=metrics-flow&unscoped_q=metrics-flow

The response to these requests should (now) include a deviceId:

https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js#L122

We need to add this deviceId to any downstream referrals we make:

https://github.com/mozilla/bedrock/search?q=flow_id&unscoped_q=flow_id

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Device ID is retrieved and added to downstream referral links

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7588
