### ISSUE TITLE
Document current analytics instrumentation standards

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7535]
## Description

We have undertaken several analytics standardization efforts, particularly in the FxA CTA space. We need to refresh our analytics documentation (https://bedrock.readthedocs.io/en/latest/analytics.html) to incorporate information about new standards, requirements, and macros.

Refs:
https://github.com/mozilla/bedrock/issues/7417
https://github.com/mozilla/bedrock/issues/7533
https://github.com/mozilla/bedrock/issues/7532
https://github.com/mozilla/bedrock/issues/7531
https://github.com/mozilla/bedrock/pull/7257
https://github.com/mozilla/bedrock/pull/7489
https://github.com/mozilla/bedrock/issues/7387

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Documentation is updated and updates are live
- [ ] Developers have reviewed and approved updates (complete? understandable?)

**Comment by hoosteeno** [comment]
For docs:

When we have an experiment that requires us to measure some outcome in a system we're referring to (e.g. sending traffic to Monitor), we can change the utm_content parameters. But we should never change entrypoint or utm_source parameters as part of an experiment. They are always the same!

Ref: https://github.com/mozilla/bedrock/commit/52cafd1b598575e05ff696e724c49dae92e8ac37#diff-09da908a0665017a7cb549ab96ea8a2bR18-R23

**Comment by alexgibson** [comment]
I'm updating the Firefox Accounts documentation as part of https://github.com/mozilla/bedrock/issues/7417

**Comment by alexgibson** [comment]
@hoosteeno both of the above PRs have now been merged, so the documentation as-is should be good for review.
