### ISSUE TITLE
Stop double-requesting flow IDs on /accounts page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7539]
## Description

On /firefox/accounts, we double-request Flow IDs. We do it once for the form shown to signed-out users (https://github.com/mozilla/bedrock/blob/1608cf38e0b530769c50bdfaa6db22dbcccf9829/media/js/base/mozilla-monitor-button.js) and once for the form shown to signed-in users (https://github.com/mozilla/bedrock/blob/432985279224bc492d2a0b591f25c272b2c7f456/media/js/base/mozilla-fxa-form.js).

Here's what that looks like in the network request panel:
![Screen Shot 2019-08-05 at 5 15 49 PM](https://user-images.githubusercontent.com/94519/62500672-da824200-b7a4-11e9-8ab8-9d82f3284a9f.png)

**We should not request Flow IDs when we don't show the UI for the flow they relate to.** Doing so inaccurately increments the number of views of that UI element. Specifically, in this case, when a signed-in user sees the Monitor button, Amplitude still increments the number of visitors to the FxA email-first sign-in form, even though a signed-in user could not interact with that form. 

We should only request one Flow ID per pageload.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7588
