### ISSUE TITLE
Monitor button form_type value dependency on fxa/issues/963

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7551]
## Description

**Awaiting outcome from https://github.com/mozilla/fxa/issues/963 to determine the value of the `monitor_button`'s `form_type` value.** 

Currently `monitor_button` has `form_type=email` in which conflicts with the `fxa_email_form`.

https://github.com/mozilla/bedrock/blob/2ff934c938ca23ba380999655ec8ad2165132b18/bedrock/base/templates/macros.html#L259

- https://github.com/mozilla/fxa/issues/963#issuecomment-518434376

**Comment by alexgibson** [comment]
Looks like the macro now defaults to `form-type='button'`, so I think somewhere along the road this got fixed: https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros.html#L203
