### ISSUE TITLE
Update language + increase visibility of /contribute survey 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/bedrock#7553]
## Description

The current survey has a low 0.03% conversion rate. There is a similar CTA on support.mozilla.org where the banner is at the top and the wording was proposed by the research team, and they have a conversion rate of 1.5%. 

Suggestions: 

* Update Wording - "We would love to get your opinion on your experience with our site with a short survey [Take Survey]"
* Move Banner - So it appears at the top of the page. 

Any other ideas? 

cc @johngian

**Comment by alexgibson** [comment]
@LucyeoH @johngian happy to make this more prominent on the page either by placing it at the top of the viewport and/or styling it differently 👍

**Comment by LucyeoH** [comment]
@alexgibson thank you, that would be great!
