### ISSUE TITLE
Migrate homepage editorial content to Nucleus

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7560]
## Description

Epic to track migration of homepage [card content publishing](https://github.com/mozmeao/www-admin) to a [Nucleus](https://github.com/mozilla/nucleus) powered workflow.

Architecture proposal doc: https://docs.google.com/document/d/1B9lJ78u_8n1SunS0ggmDfqlk2PmMrslkzXmtTb8qcwM/edit#heading=h.8rbejd6o6w9f

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Homepage card content can be edited and updated in production via a Nucleus.

**Comment by alexgibson** [comment]
@pmac I know you're also busy with the L10n system, but thought I should check in here. Do you still think porting the homepage cards to Nucleus is within scope for end of Q3 2019, or do you think this needs to move further out on the roadmap?

**Comment by pmac** [comment]
Oh. I missed that this was a Q3 goal. I have it for EOY mostly because l10n is going to take a good chunk of my Q3. I'd like to move it out if we can.

**Comment by alexgibson** [comment]
@hoosteeno @pmac is there still an appetite for this work? It's been pushed back on the technical roadmap a few times, which gives me the impression it's no longer as importent compared to when we first filed this issue. 

Should we keep this open, and try to commit a time to doing it, or should we close it?

**Comment by pmac** [comment]
It's on my map for H1. It was pushed last year due to subhub work, but should now be cleared for takeoff.

**Comment by alexgibson** [comment]
@pmac is this still something that's being worked on currently, or have other priorities come along? Just asking so I can update the roadmap for H2. Thanks

**Comment by pmac** [comment]
It is still being worked on. I’m trying to get a v1 shipped this month.

**Comment by alexgibson** [comment]
Going to close this and we can file a new issue for the realigned CMS work.
