### ISSUE TITLE
THe [About] page layout has text truncation issue (bug 1573244)

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#7566]
## Description
The text in the **Our Mission in Action** section on the [About](https://www.mozilla.org/en-US/about/) page are truncated. It appears that the box of text allows only a number of characters, so they depending on the language, the truncation takes place at random spot, not just the end of the line.

Describe the issue that you're seeing.
Not only English has this issue, the localized content has the same issue. The paragraph is cut short at random places, which means the truncated text could end up with different meaning. 

### Steps to reproduce
https://www.mozilla.org/en-US/about/
https://www.mozilla.org/es-ES/about/
https://www.mozilla.org/ru/about/
https://www.mozilla.org/id/about/
https://www.mozilla.org/ka/about/
https://www.mozilla.org/el/about/

### Expected result
Expand the text allowed in the field in words and characters. 

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

**Comment by devbihari** [comment]
If you don't mind can I fix this issue?

**Comment by alexgibson** [comment]
This has been fixed
