### ISSUE TITLE
/firefox/firstrun/ page throws a JavaScript error

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7581]
## Description

The [/firefox/firstrun/](https://www.mozilla.org/en-US/firefox/firstrun/) page throws a JavaScript error on page load. I'm not certain if this is causing an issue (it may be related to old code perhaps), but we should take a look and fix it.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/firstrun/
2. Open the Web Console.

### Expected result

There should be no errors.

### Actual result

```
TypeError: document.getElementById(...) is null2 firefox_firstrun_quantum.3b5c4e34d494.js:1:1215
    onreadystatechange https://www-demo5.allizom.org/media/js/BUNDLES/firefox_firstrun_quantum.3b5c4e34d494.js:1
```

### Environment

Firefox Nightly.

**Comment by craigcook** [comment]
Oops, looks like this is a regression from a64a4be72b0e41748c050ff1d0afdca8b95b8aa3

I missed this in code review, sorry. The JS is expecting an element that doesn't exist in the new template.

https://github.com/mozilla/bedrock/blob/master/media/js/firefox/firstrun/firstrun_quantum.js#L9

But I'm not even sure what that was meant to do in the first place... maybe we don't need that at all and can just delete the whole file?
