### ISSUE TITLE
Lockwise - Build analytics plan and implement analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7583]
## Description

We need an analytics instrumentation plan for Lockwise when it lands at www.mozilla.org. We should evaluate the current state of Lockwise analytics on lockwise.firefox.com, and design an ideal analytics setup, and specify the instrumentation so we can build it.

Notes
* If there are existing analytics we should prioritize continuity.
* There are 3 CTAs: Download on play store, download on app store, and install extension. The extension CTA will disappear later.
* We might be able to use our new [Generic CTA](https://github.com/mozilla/bedrock/issues/7491#issuecomment-520981154) tooling for this, in which case we simply need to specify the values of the CTA datalayer attributes.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Analytics plan is specified adequately for a developer to implement

**Comment by ejregithub** [comment]
@sghoseWI - please review tasks here and consult w. @Errolyn who is coding this page.

**Comment by sghoseWI** [comment]
UPDATES: 

Tags
On App Store download buttons:
data-cta-type=“lockwise-app-store”
data-cta-text=“apple-app-store|google-play-store” // there are 2 of these buttons; use only one text option depending on the platform
data-cta-position=“primary”

On ‘Install for Firefox’ button:
data-cta-type=“lockwise-install”
data-cta-position=“primary”

On ‘Get Firefox’ button:
data-cta-type=“lockwise-download-fx”
data-cta-position=“primary”

On ‘Open in Firefox’ button:
data-cta-type=“lockwise-open-in-fx”
data-cta-position=“primary”

On Offsite links only (not on any onsite links):
utm_source=www.mozilla.org-lockwise
utm_campaign=lockwise
utm_medium=referral
entrypoint = “mozilla.org-lockwise”

**Comment by sghoseWI** [comment]
One caveat (from Justin): All of our download buttons are very finely tuned. If we change the data params on them, we break download goal counting. We should use a default download button for "Get Firefox".  @Errolyn
