### ISSUE TITLE
Lifecycle page - Survey visitors to initial release to learn more about how to refine the channel.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7586]
https://bugzilla.mozilla.org/show_bug.cgi?id=1574304 - this a private bug, for now

**Comment by hoosteeno** [comment]
@wboucherfischer would you be up for reviewing this? https://docs.google.com/document/d/1JpHLrpQjUbs2K5lb_7jdUN2n3Fn-aFwX1UfWhbBHMAQ/edit#heading=h.g1ycqgsaf2tp

**Comment by wboucherfischer** [comment]
@hoosteeno  I have reviewed and thought we should put something in about what people thought about the page.

**Comment by hoosteeno** [comment]
@wboucherfischer something additional to "3. How did you feel when you saw that page?" How would you express it? Feel free to comment in doc.
