### ISSUE TITLE
Test faq structured data on https://www.mozilla.org/en-US/MPL/2.0/FAQ/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#7596]
We would like to test how ctr in search and impressions in search react on [faq structured data](https://developers.google.com/search/docs/data-types/faqpage). https://www.mozilla.org/en-US/MPL/2.0/FAQ/ is a good candidate to test on, as the page has some but not much traffic from search and a very clear faq structur.

**Comment by rraue** [comment]
The test was succesful. The code is valid and already showing up in search, including the link in the markup:
<img width="669" alt="Screenshot 2019-09-02 at 11 15 49" src="https://user-images.githubusercontent.com/36700618/64103748-2bb92d80-cd73-11e9-98a0-568450c8b402.png">
<img width="777" alt="Screenshot 2019-09-02 at 11 15 58" src="https://user-images.githubusercontent.com/36700618/64103749-2bb92d80-cd73-11e9-9a0e-6465e39aad62.png">

**Comment by stephaniehobson** [comment]
That is pretty slick.
