### ISSUE TITLE
Roughly scope an experiment on /firefox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7600]
## Description

We want to land new content on /firefox that talks about the master brand by Oct. 22. We need to understand the magnitude of change (desktop acquisition volume DOWN, non-desktop conversion volume UP) to expect. This will require an experiment, and we need to know how much we can learn in that experiment based on the anticipated data gathering time required.

Please roughly estimate the amount of time we would need to run an experiment with these characteristics:

* on /firefox/
* for en-US visitors only
* for visitors landing on this page (starting session here)
* for all browsers
* comparing 7 variations including control
* comparing 3 different segments based on source (organic, direct, and owned-media referrals)
* measuring session->click for any/all CTAs on the page

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Rough idea of experiment duration is delivered
- [ ] BONUS success criteria: Which factors above we could eliminate to have the most impact on experiment duration, if we need to trim scope

**Comment by ejregithub** [comment]
@sghoseWI - is this issue still in review and if so who needs to complete review of it?

**Comment by sghoseWI** [comment]
@ejregithub This issue is done and I've marked it as such.  Thanks for heads up.

**Comment by sghoseWI** [comment]
Downloads loss threshold estimate:

- So far in Q3 2019, we are seeing an average of 31,913 desktop downloads in en-us per day (across all segments).  

- The standard deviation of the dataset is ~7,794 desktop downloads. 

- Using an outlier detection methodology of 2.5 standard deviations below the mean (~19,486 downloads), we should terminate the experiment if average daily download completions drops below (31,913 - 19,486 = 12,427 downloads).  

- Note: If traffic distribution to the experiment is less than 100% (as it likely will be), the experiment termination threshold for download volume loss will be lower -- though at the same ratio relative to the mean.  I will make sure to monitor and communicate to the team if this occurs.
