### ISSUE TITLE
Add new docs to production: Hubs Privacy Notice and ToS

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7612]
## Description

Add the new docs to production.

https://github.com/mozilla/legal-docs/tree/master/Mozilla_Hubs_Privacy_Notice
https://github.com/mozilla/legal-docs/tree/master/Mozilla_Hubs_ToS

https://bugzilla.mozilla.org/show_bug.cgi?id=1568885

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Both pages are live in production

#### Tasks
- [ ] Add the new legal docs (web pages) to the production website

**Comment by Errolyn** [comment]
@ejregithub do we already have URL's for these, or am I creating new routes?

**Comment by ejregithub** [comment]
Per discussion, closing. the files are in the submodules on bedrock
