### ISSUE TITLE
Determine the fate of SendToDevice/SendYourself widgets

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7614]
## Description

Currently we have two widgets in bedrock that do the same thing. Only one should survive.

- [send-to-device.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/send-to-device.js)
- [send-yourself.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/send-yourself.js)

### Send-Yourself Widget

Pros:

- Is newer than send-to-device.js.
- Can handle multiple forms on one page.

Cons:

- [No documentation](https://github.com/mozilla/bedrock/issues/6603).
- [No unit tests](https://github.com/mozilla/bedrock/issues/6608)
- [Not part of Protocol](https://github.com/mozilla/bedrock/issues/6698)
- Uses jQuery.

This widget is currently in use on a [single web page](https://github.com/mozilla/bedrock/blob/master/media/static-bundles.json#L1467-L1475) (but note that page isn't using multiple forms).

### Send-to-Device Widget

Pros:

- [Has documentation](https://bedrock.readthedocs.io/en/latest/send-to-device.html)
- [Has unit tests](https://github.com/mozilla/bedrock/blob/master/tests/unit/spec/base/send-to-device.js)
- [Has soon to be added protocol-based styles](https://github.com/mozilla/bedrock/pull/7458)

Cons:

- Can only be used on a single form instance per page.
- Not part of Protocol.
- Uses jQuery.

This widget is currently is use on two web pages (`/firefox/mobile/` and `/firefox/whatsnew/`).

What to do?
------------

We need to decide what to do with these widgets. The upcoming evergreen `/whatsnew` page likely isn't going to need either, but `/firefox/mobile/` may still do. I imagine we'll still need to maintain one version either way.

There hasn't been movement on deprecating the old send-to-device widget since the new one was introduced. Given the low usage of both today, we could potentially keep either. It may be less work to keep the old version (which already has documentation and tests).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Developers agree on which version to keep moving forward.

#### Tasks
- [ ] Bikeshed it 🚲

**Comment by alexgibson** [comment]
Any thoughts / preferences @craigcook @stephaniehobson @amychurchwell @Errolyn ?

**Comment by stephaniehobson** [comment]
Send-to-Device seems like the lowest effort.

**Comment by craigcook** [comment]
Send-yourself was created to support multiple products, which send-to-device can't do, and I honestly don't recall why at the time it seemed better to create a second widget than to refactor the original. But the plan had always been to deprecate the old one, that work just never happened.

If we decide we no longer need multi-product functionality (Firefox for Android/iOS is hard-coded in the send-to-device widget so it can't be used for Focus, Lite, or anything else) then we can just delete send-yourself at the same time we replace the legacy whatsnew page. That's certainly the least amount of effort, but we'd be losing some functionality that could be valuable again down the road. We might be setting ourselves up for more work later if someone ever wants to use this widget for another product.

If we want to keep the extended capabilities of send-yourself, then we should do the work of deprecating send-to-device. That entails swapping the widgets on those other two pages, updating the tests and docs, and probably still some refactoring to improve the widget overall.

**Comment by alexgibson** [comment]
It looks like both macros support the `message_set` parameter, so (I think) either should be configurable.

**Comment by craigcook** [comment]
Hmm yeah, it looks like send-to-device does handle different products, but still only one per page since it still has a hardcoded ID. Send-yourself is about a 95% clone of send-to-device, with just a few more options to avoid duplicate IDs so there can be more than one widget on a page. I thought message_set was hardcoded as well, and maybe it was at the time.

So if we just delete send-yourself we can only have one widget per page and maybe that's fine.

**Comment by alexgibson** [comment]
Ok, so the only functionality the send-to-device widget is missing is instantiation for multiple instances. I think adding that functionality is probably going to be less work than rewriting tests, documentation, and deprecating the old widget. It’s also non-blocking, as we don’t have any pages where multiple instances are being used.

**Comment by alexgibson** [comment]
That said, the existing documentation does need some updates still (to mention `message_set‘ etc).

**Comment by alexgibson** [comment]
Opened a new issue to update send-to-device: https://github.com/mozilla/bedrock/issues/7632
