### ISSUE TITLE
/enterprise switch for 9/18 go live 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7629]
Set up switch for /enterprise page

Flip switch for go live ≤ 6 am PT on Wednesday Sept 18

**Comment by alexgibson** [comment]
@ejregithub it’s going to be a lot less work just to push the page live on the above date, rather than retroactively apply a switch to the page.

**Comment by alexgibson** [comment]
We have the confimration via Slack that we can ship this just as soon as it's been code reviewed.
