### ISSUE TITLE
(firefox/privacy/products) Protection Report Landing Page (Epic) 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7643]
For Skyline we will launch a new landing page for the Firefox protection report (about:protections). This page should handle incoming traffic from e.g. social and maybe paid. It should introduce/explain the report and should link visitors to the most appropriate next step if they wish to try the report:
* on 70 and above, use UITour to link into report
* on <70, update instructions on SUMO
* on non-Fx, get Firefox

[Master Project Doc](https://docs.google.com/document/d/1avYBLNeDbzgR9K58gTz29Qam-emBT5OSfoOjnqXLp8U/edit) (links to all the things)

***Tasks***
- [x] Contexting session
- [ ] Roadmapping session 
- [x] Project board - > github issues subordinate to this epic

**Comment by alexgibson** [comment]
@ejregithub is there an analytics card for this work? I can't seem to find an issue for it.

**Comment by alexgibson** [comment]
Oh, nevermind I found it, it just wasn't linked in the epic.
