### ISSUE TITLE
Wrong string on /enterprise

### ISSUE THREAD

**Issue by rtestard** [mozilla/bedrock#7647]
## Description
On https://www.mozilla.org/en-US/firefox/enterprise/ a title states "Your data stays your business" whereas it should be "Your data stays in your business"

### Steps to reproduce

Browse to https://www.mozilla.org/en-US/firefox/enterprise/
### Expected result

What should happen?

### Actual result

Read "Your data stays your business"

### Environment

Chrome and Firefox
![Screenshot_2019-09-04 Get Firefox for your enterprise — ESR, RR and premium support](https://user-images.githubusercontent.com/866979/64251093-f863d380-cf17-11e9-99ba-c13d8c995879.png)

**Comment by alexgibson** [comment]
The string in production is correct according to the [copy doc](https://docs.google.com/document/d/1nbSDIpMxmkLcy9Uts54IMB9LVZiTFGpwHRrC-_AFmD8/edit?usp=sharing).

/cc @claychaffin to weigh in here, as the change being proposed means the title takes a slightly different meaning/connotation.

**Comment by rtestard** [comment]
Dreams clarified that this is not wrong wording in english, my bad understanding of the language!
Closing now
