### ISSUE TITLE
Privacy notices are missing meta descriptions

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7666]
## Description

Not sure if this is a recent regression, but whilst working on a new policy I noticed that the meta descriptions for all current privacy policies are blank:

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/privacy/firefox/ or any other policy.
2. Open the web console and inspect the `<head>`.

### Expected result

`<meta name="description" content="INSERT MEANINGFUL DESC OF PAGE HERE">`

### Actual result

`<meta name="description" content="">`

### Environment

Any browser.

**Comment by Shivansh2407** [comment]
Can I help you in fixing this issue?

**Comment by Patil2099** [comment]
@alexgibson Can I work on this issue?

**Comment by alexgibson** [comment]
Pull requests are always welcome 👍

**Comment by ManthanKeim** [comment]
@alexgibson sir, as I saw the privacy contents are dynamically loaded, can you please help me locate the file locally so that I can add the meta content to them.

**Comment by alexgibson** [comment]
@ManthanKeim the template in question can be found here: https://github.com/mozilla/bedrock/blob/master/bedrock/privacy/templates/privacy/notices/base-notice.html

**Comment by shivanik6z** [comment]
Is this issue solved? If not I would like to work.
