### ISSUE TITLE
Update Enterprise Platform link in SLA *Urgent*

### ISSUE THREAD

**Issue by flekkowich** [mozilla/bedrock#7667]
Update Enterprise Platform link in [SLA](https://www.mozilla.org/en-US/firefox/enterprise/sla/) 

Under *Contact Information*
Remove: https://mozilla.force.com/enterprise/s/
Replace with: https://enterprise-help.mozilla.com/hc/en-us

Under *Procedure to file a ticket*
Remove: https://mozilla.force.com/enterprise/s/
Replace with: https://enterprise-help.mozilla.com/hc/en-us
Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

*What should happen?*
All contact links should link to 
https://enterprise-help.mozilla.com/hc/en-us

### Actual result
Current contact links link to 
https://mozilla.force.com/enterprise/s/

NOTE:
We are releasing a blog post by end of this week (Friday 6th) and we will be sending people to the new website which links to the SLA and we need this updated.

**Comment by hoosteeno** [comment]
@flekkowich Is the en-US string at the end required? We generally try to drop locale strings when a locale-sensitive request handler is present, which appears to be the case here:

https://enterprise-help.mozilla.com/hc/

**Comment by craigcook** [comment]
I'm also not sure if the '/hc/' bit is required. If I go to https://enterprise-help.mozilla.com it then redirects to /hc/en-us/, so maybe we should just link to the top-level domain.

**Comment by craigcook** [comment]
Confirmed via Slack that we can link to `https://enterprise-help.mozilla.com` without the additional URL segments (they're automatic redirects).
