### ISSUE TITLE
Detect UITour failure / non-response on what's new page

### ISSUE THREAD

**Issue by Mardak** [mozilla/bedrock#7671]
We're trying to evaluate how widespread is https://bugzilla.mozilla.org/show_bug.cgi?id=1557153 where UITour default permission gets lost, so UITour does not respond to events. E.g., Mozilla.UITour.ping(cb) should call back pretty immediately except it never happens with the lost permission.

**Comment by alexgibson** [comment]
After some discussion on Slack, we've decided a 1 second timeout *should* be enough, at least to give us a general idea on the scope of the issue. We're also going to track the response times, so we can get a good idea of the median for people hitting /whatsnew in general.
