### ISSUE TITLE
Remove jQuery dependency for send-to-device.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7673]
## Description

The send-to-device widget is still being used in modern templates, but relies on jQuery. We should replace those function calls with native equivalents.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] send-to-device.js no longer relies on jQuery.

#### Tasks
- [x] Remove dependency.
- [x] Update tests where applicable.

**Comment by Patil2099** [comment]
@alexgibson Can I work on this issue?

**Comment by vinay-deshmukh** [comment]
@alexgibson I have submitted a PR for this issue.
