### ISSUE TITLE
WNP 70 copy

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7674]
## Description

Copy for WNP 70 (Skyline)

[Copy Doc](https://docs.google.com/document/d/1CTHULbVZ8JekZ1efwaa-ksNvx8nVXxGT-cTJR5zmsz0/edit#heading=h.oo63piaiuqi8)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Copy is final/approved Friday Sept 13th

#### Tasks
- [x] write copy, get it reviewed and approved (Rob)

**Comment by hoosteeno** [comment]
We're pivoting WNP70 content.

1) We've decided to keep the Monitor CTA for all visitors (signed in and signed out).
2) We'll change the secondary CTAs accordingly.

The new copy has been approved. It is presented in the below PDF, along with states. *Please note*, these are not graphic/ui designs, these are copy designs. Graphics may change independently.
[WNP 70 Copy Designs.pdf](https://github.com/mozilla/bedrock/files/3654867/WNP.70.Copy.Designs.pdf)

The source for that PDF can be accessed by account holders at https://miro.com/app/board/o9J_kw7odMs=/.
