### ISSUE TITLE
WNP 70 string extraction

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7675]
Extract strings to Pontoon for localizers

***Tasks***
 - Flag DE and FR w. Peiying for Mozilla Staff localizers
- Opt in for all others
- @ejregithub to coordinate with Staff for DE and FR

**Comment by amychurchwell** [comment]
langchecker: https://github.com/mozilla-l10n/langchecker/pull/919
ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/332
