### ISSUE TITLE
WNP 70 Design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7676]
We need to apply design to the WNP 70. It is using the modular system and will feature content for existing products

**Comment by cgonz0** [comment]
![WNP-70_design.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/76b7d2df-2bb8-4fa2-94be-76efc61a00c4)

**Comment by ejregithub** [comment]
@cgonz0 - looks good! Is this 'final'?  If so, do you have a sketch file you can provide to @amychurchwell ?

**Comment by cgonz0** [comment]
@ejregithub yes and yes - synced with amy yesterday and everything has been handed off.

**Comment by ejregithub** [comment]
Noting the decision to maintain the copy and link to Release Notes in 70 as they were in 69, not 68 (as in the original mock-up above)
