### ISSUE TITLE
Non-English locales still show old footer content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7682]
## Description

The main page footer on bedrock shows different content for English / non-English locales. They should be the same.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/
2. Look at the footer content:

![image](https://user-images.githubusercontent.com/400117/64520667-86600580-d2ee-11e9-861e-04424aa56656.png)

3. Visit https://www.mozilla.org/de/
4. Look at the footer content:

![image](https://user-images.githubusercontent.com/400117/64520717-a0014d00-d2ee-11e9-92d0-431a535d2b68.png)

### Expected result

All locales should have the same footer content.

### Actual result

Only English locales get the latest footer content. It looks like we have a hard-coded conditional here:

https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/includes/site-footer.html

I can't see the strings in the new footer in the L10n repo, so it looks like they were never exposed?

### Environment

Any browser

**Comment by Shivansh2407** [comment]
The site-footer.html Must extend the index.html file so as to continue changing according to the dynamic data otherwise it will feel like the data is hard-coded.

**Comment by Patil2099** [comment]
@alexgibson  Can I work on this issue?

**Comment by alexgibson** [comment]
This is now fixed
