### ISSUE TITLE
Character limit on homepage cards is clipping text in funny places

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7690]
## Description

This line of text was one character too long:

<img width="702" alt="Screen Shot 2019-09-10 at 10 14 13 AM" src="https://user-images.githubusercontent.com/854701/64635119-cdfc9500-d3b3-11e9-9dc1-2dbc20ca082f.png">

It's not like we were short on space.

**Comment by stephaniehobson** [comment]
I recommend we remove the character limit from the homepage cards. The content team has been pretty good about using this space sensibly.

**Comment by alexgibson** [comment]
Fwiw, this was originally a "feature" that the design team asked for, in order to keep line lengths for each card fairly uniform across the page. I have no strong feelings on changing this though.

**Comment by stephaniehobson** [comment]
I don't think it's doing the thing they want it to do right now. :/

<img width="1060" alt="Screen Shot 2019-09-10 at 10 37 53 AM" src="https://user-images.githubusercontent.com/854701/64636694-14072800-d3b7-11e9-8ed3-6a2f27bfceef.png">

**Comment by alexgibson** [comment]
It was more to impose a limit to avoid really long card titles. I agree it’s not really very useful though, seeing as content creators are already imposing soft-limits.
