### ISSUE TITLE
Publish remote preferences 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7694]
## Description

When the lifecycle page #1 is ready, we need to file a bug for a remote preferences change. 

The bug should block this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1574982

It should look kind of like this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1570372

We can use this issue to talk about the criteria.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Remote prefs are published
- [x] Remote prefs are identified

**Comment by hoosteeno** [comment]
Here's a first pass at the remote rules we want for this message.

Targeting:

* In locales we have localized
* Firefox profile create date >= 4
* Firefox profile create date < 15
* CFR opt-out != true

Trigger: 

* Browser Restart

URL: 

{{ the lifecycle page url }}

**Comment by hoosteeno** [comment]
Bug filed. https://bugzilla.mozilla.org/show_bug.cgi?id=1583586

**Comment by craigcook** [comment]
Question: should we allow for a few days of buffer between pages?

I'm imagining a scenario where a user restarts Firefox on day 14 and sees page 1, then restarts again on day 15 (the next day) and sees page 2. Might that be annoying for those users? Or do we think that number might be very small? If it's worth worrying about, we could show page 1 from day 5-14 and show page 2 starting on day 18, just to avoid the potential for some number of people getting marketing pages two days in a row.
