### ISSUE TITLE
Create automation for checking and processing FTL files

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#7705]
This automation will do a number of things:

- [x] pull changes in from the l10n team's fluent file repository
- [x] check those changed files for errors
- [x] copy the files without errors to [mozmeao/www-l10n](https://github.com/mozmeao/www-l10n/) repo
- [x] check the changed files that aren't yet active to decide if they should be activated
- [x] write the activitation state of each file to a JSON file of the same name (e.g. for a FTL file `de/mozorg/home.ftl` write a `metadata/mozorg/home.json` file to contain metadata)
- [ ] push the updates to the [mozmeao/www-l10n](https://github.com/mozmeao/www-l10n/) repo

This will make it as easy as possible for bedrock to know the things it needs to for page activation.

This automation will live in bedrock and should get a GitLab CI job that will be triggered by a webhook on commit in the l10n team's repo.

TODO:

- [ ] hook up the automation to do all of the above on commits to the l10n team's repo

**Comment by hoosteeno** [comment]
This issue can be almost completely resolved; but closing it out will require the l10n team's repository to be built. Meanwhile we can build a temporary version of that somewhere.

**Comment by alexgibson** [comment]
A script that pulls in updates and processes activation metadata was added in https://github.com/mozilla/bedrock/pull/8523

The remaining steps involve running this script via automation.

**Comment by pmac** [comment]
Also need to improve said script from #8523 to include updating the configs in addition to the .ftl files.
