### ISSUE TITLE
UI/Design -  (firefox/privacy/products) Protection Report Landing Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7707]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Link to abstract/sketch file: https://share.goabstract.com/fe0f1dad-c2e8-49c2-b140-e8b59d3889af?sha=2270b6bff22174da6248d64d013c25c0a79025db

**Comment by dzingeek** [comment]
@alexgibson wanted to give you an update on where we are at and an updated link to the sketch file. 

**Design:** 
- general design direction is good, mark has some work to do on images and james is doing some spot illustration for us but he is OOO until tuesday. 

**Sketch File:** 
- [link to the latest file](https://share.goabstract.com/36cde4df-0cb7-432b-8d70-eee3e613a198?sha=bda284235640424fb34dda1008d6666b8a8be776)
- artboards can be found on **/firefox/privacy/products** under pages
- please open sketch file, mark has started to spec things out which live outside of the artboard (see attached img for reference)
- mark has also started early design for breakpoints

**other notes:**
- Mark will continue on design tweaks/images on monday
- As soon as we have assets we will package them up and add them to this issue
- @mrkwvr please reach out to alex and walk him through the design/sketch file on monday

![Screen Shot 2019-09-20 at 3 43 27 PM](https://user-images.githubusercontent.com/3740746/65363425-b5b12500-dbc0-11e9-855e-69730bcaabae.png)

**Comment by dzingeek** [comment]
@alexgibson [sketch file](https://share.goabstract.com/27ed31d2-c719-48c2-bb35-9a2792eb38df?sha=2faced350a4a5114e7b428b490b4c7f53618aa3c) has been updated to reflect more specs + all breakpoints. Also, attaching images/assets... some images are still being worked on. 

**assets (images)** [privacy-etp-imgs.zip](https://github.com/mozilla/bedrock/files/3649662/privacy-etp-imgs.zip)

"final" logo files can be [found here](https://drive.google.com/drive/folders/1Oe8hM9afrtwRlr9oVNu_rN8PpE3deQqm)

_attaching latest png for reference_
![fx-privacy-products-1312](https://user-images.githubusercontent.com/3740746/65553744-64fd3d00-dedc-11e9-8510-85a68e35fb76.jpg)

**Comment by hoosteeno** [comment]
Blocked awaiting final design assets from @dzingeek .

**Comment by alexgibson** [comment]
I think we have all the final assets here now, unblocking and closing this issue.
