### ISSUE TITLE
Identify a list of widgets that live in separate fluent files from template content.

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7718]
We need to call out the widgets on our existing website that deserve their own fluent files on day 1.

**Comment by alexgibson** [comment]
I took a look through our existing macros and these seem like the most common widgets/includes of high importance:

- Navigation.
- Footer.
- Firefox Accounts email form.
- Newsletter.
- Send to Device widget.

**Comment by alexgibson** [comment]
In the current system we also have [`main.lang`](
https://github.com/mozilla-l10n/www.mozilla.org/blob/master/en-US/main.lang) for miscellaneous strings. I think we should try and avoid a large, monolith file like this in the new system. However I could see a case where we need system wide strings that don't fit into the notion of a widget. For example:

- Common UI strings such as "Open", "Close", "Play", "Menu", "Next", "Previous".
- Default, global strings that may live in a base template (page titles, meta data).
- Localized date/month strings.

**Comment by alexgibson** [comment]
Another thing to consider is a list of languages and their translations, such as what we see in the site footer:

<img width="184" alt="Screenshot 2019-09-13 at 09 37 36" src="https://user-images.githubusercontent.com/400117/64849020-63916200-d60a-11e9-9359-16002bad65ba.png">

I don't believe these strings come from a .lang file however (but I could be wrong). They seem to be part of the translation system. 

Is that right, @pmac?

**Comment by pmac** [comment]
> Localized date/month strings.

Fluent has some [built in ways of handling localized datetime](https://projectfluent.org/fluent/guide/functions.html#datetime) data.

**Comment by pmac** [comment]
> Another thing to consider is a list of languages and their translations, such as what we see in the site footer

The [translated language names](https://product-details.mozilla.org/1.0/languages.json) come from product-details.

**Comment by pmac** [comment]
They are part of the system in that that list is populated based on the active locales for that specific page, but it's also not because those strings are not in the system that is translated by our l10n team.

**Comment by alexgibson** [comment]
## Final list

### Global elements
- Navigation
- Footer
- Download Button
- Misc

### Page-specific elements
- Firefox Accounts email form.
- Newsletter.
- Send to Device widget.

**Comment by pmac** [comment]
So you would like a separate .ftl file for each of these elements, with the global ones being loaded by default for every page, right?

**Comment by alexgibson** [comment]
> So you would like a separate .ftl file for each of these elements, with the global ones being loaded by default for every page, right?

I believe that should cover our most frequent use cases, yes.
