### ISSUE TITLE
Automate l10n activities

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7723]
### from bedrock

- [x] Lint fluent files for validity post-commit on Bedrock: fluent is valid, and fluent files included in templates actually exist (if not, CI fails)
- [x] Copy new fluent files in bedrock over to l10n team's fluent repositories in a branch
- [x] Config files -- which are authoritative in Bedrock's l10n repo -- are copied to l10n team's repository at this time
- [x] Open a PR with these changes against the https://github.com/mozilla-l10n/www-l10n repo

---

### to bedrock

- [x] Retrieve fluent files from l10n team's fluent repositories on some schedule or as a result of some event
- [x] Lint fluent files when retrieved from fluent repositiories: fluent is valid (if not, don't import)
- [x] Evaluate every fluent file imported for activation status & manage activation lists
- [x] Ensure a developer can override the site-wide default activation % for a particular fluent file
- [x] Push into [mozmeao/www-l10n](https://github.com/mozmeao/www-l10n) repository

**Comment by pmac** [comment]
@Pike for the "from bedrock" part, we want to push a branch to the mozilla-l10n repo and open a PR during that automation right?

**Comment by pmac** [comment]
Much of the "to bedrock" part was done in #8523. #7705 indicates what's left to do.

**Comment by Pike** [comment]
> @Pike for the "from bedrock" part, we want to push a branch to the mozilla-l10n repo and open a PR during that automation right?

Yep.

**Comment by pmac** [comment]
>  and fluent files included in templates actually exist

I'm not sure this part is necessary. It would be pretty obvious if the ftl file wasn't right during development and review since no strings would show up on the page and would only have the string IDs in the HTML. We could look at including this in tests, but it seems like overkill to me, at least for now.

**Comment by pmac** [comment]
I think we're done here! Please reopen if we discover we need something more.
