### ISSUE TITLE
Establish site default activation criteria

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7724]
Write code or build configuration structures to activate a URL in a locale based on our initial set of defaults (80% strings + all required strings).

### Success Criteria

- [ ] In production, content meeting the minimum threshold will be activated automatically
- [ ] In production, content *not* meeting the minimum threshold will *not* be activated
- [ ] Staging acts like production
- [ ] In dev the thresholds do not apply

**Comment by alexgibson** [comment]
I think we can close this one out. The `process_ftl.py` command uses a global default of 80%, which is [defined here](https://github.com/mozilla/bedrock/blob/4d161e90f21a43446bd93ba84530b44d9af8c41f/bedrock/settings/base.py#L245).

Individual Fluent files can set their own [activation threshold](https://bedrock.readthedocs.io/en/latest/l10n.html#fluent-file-activation), based on [metadata](https://github.com/mozmeao/www-l10n/tree/master/metadata).

@pmac Is there anything else tha needs to be done, before we can close this one out?

**Comment by pmac** [comment]
If we're happy with 80% then I think we're done here.
