### ISSUE TITLE
Identify first target page for conversion

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7731]
Description:  Identify first target page for conversion to be 100% on Fluent

***Success Criteria***
- [ ] By the end of Sept we should have 100% localized a page that meets the selection criteria below

***Selection Criteria***
- [ ] Exercises a few of our developer use cases
- [ ] Has expected continue longevity (won’t be deprecated soon)
- [ ] Is translated in > 1 language
- [ ] A page with a global element (e.g. nav or footer using lang file)
- [ ] Not about to be redesigned for Skyline.

**Comment by alexgibson** [comment]
A few possible candidates (I tried to pick Protocol based pages with semi-recent branding).

Updated infrequently, have high community appeal, and have at least one global element:

- https://www.mozilla.org/en-US/about/manifesto/
- https://www.mozilla.org/en-US/about/

More product focused, are not (afaik) being redesigned for Skyline, and have at least one global element:

- https://www.mozilla.org/en-US/firefox/all/
- https://www.mozilla.org/en-US/firefox/nightly/firstrun/

I'll update this list as I think of more.

**Comment by alexgibson** [comment]
@pmac @hoosteeno feel free to add any thoughts / opinions / suggestions to this list of candidates ^

**Comment by alexgibson** [comment]
If we're looking at Firefox pages, I'd be tempted to suggest /firstrun:

https://www.mozilla.org/en-US/firefox/firstrun/

The page has the global footer, has a widget (FxA email form), and has some existing L10n conditional tags in the template. It's also widely translated.

I'm not sure if that's perhaps too complicated for what we'll be able to accomplish for the end of September, but technically it could be a good candidate.

**Comment by pmac** [comment]
https://www.mozilla.org/en-US/mission/ came up in our meeting and it seems like a good candidate

**Comment by hoosteeno** [comment]
/mission also has a widget, a global footer, [some locale conditionals](https://github.com/mozilla/bedrock/blob/5d74216f302d50e63acdd80bc9a81b35b14bdb7e/bedrock/mozorg/templates/mozorg/mission.html#L69), and is localized into 90 locales. Also, it's not part of a funnel.

+1 for /mission

**Comment by alexgibson** [comment]
I gave /mission some thought after our meeting, but I think something like /about/ or /manifesto/ are more recent (both are protocol). That said, I think /mission could still be a good candidate. It's farily short & simple.

**Comment by alexgibson** [comment]
Chosen page is https://www.mozilla.org/en-US/mission/

**Comment by pmac** [comment]
Thanks Alex 👍
