### ISSUE TITLE
WNP 70 Instrumentation Plan - Analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7742]
***Tasks***
- [ ] Create instrumentation plan
- [ ] Work with dev for including instrumentation, tags in the coded page, in #7677

**Comment by sghoseWI** [comment]
WNP 70 Analytics Instrumentation:
On ‘Sign Up for Monitor’ button:
data-cta-type=“whatsnew70-Monitor”
data-cta-position="Primary"

On SUMO/Lockwise/Release Notes links
utm_source=www.mozilla.org-whatsnew70
utm_campaign=whatsnew70
utm_medium=referral

**Comment by sghoseWI** [comment]
Conventions
-----------

When choosing URL parameter values, the following conventions help support uniformity in code and predictability in retroactive analysis.

* Use lower case characters in parameter values.
* Separate words in parameter values with hyphens.
* Follow parameter naming patterns established in previous iterations of a page.

**Comment by hoosteeno** [comment]
@sghoseWI can you update with the latest here?

**Comment by sghoseWI** [comment]
@hoosteeno Done (edited previous comment above to avoid confusion) - thanks!
