### ISSUE TITLE
WNP 69 analysis 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7743]
## Description

Produce a lightweight analysis of the /whatsnew 69 page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Differences in session-to-login and session-to-registration between 69 and 68 (or previous mean) are clear (within constraints imposed by data quality)
- [ ] Differences in 7-day retention is clear

**Comment by Shivansh2407** [comment]
What is this issue about?

**Comment by ejregithub** [comment]
> What is this issue about?

@Shivansh2407 - apologies for not providing greater detailing when filing this. This is task for out internal data scientist to compare the performance of the 69 and 68 /whatsnew pages (shown to users when they update there Firefox browser corresponding to those releases)

**Comment by Shivansh2407** [comment]
Ok Thanks .

**Comment by sghoseWI** [comment]
https://docs.google.com/document/d/1F4LfAyme_h8AVG-1is_sIzncBEHc8dkuVeM8dt22mFo/edit#heading=h.6bs8agnufvbm

Edward Cho did the above analysis -- I believe it answers the research questions relating to this analysis.
