### ISSUE TITLE
Design task completion survey widget

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7745]
## Description

We should build a widget that can be enabled on any page of the website to measure task completion/satisfaction on that page. This issue is about researching, specifying and designing that widget.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] The widget should follow best practices in task completion/site satisfaction surveys.
- [ ] The widget should be integrated with one of our survey OR analytics tools (e.g. SurveyGizmo, SurveyMonkey, or GA)
- [x] The widget should include a minimum of questions and cause the least possible interruption to maximize the likelihood of engagement

**Comment by hoosteeno** [comment]
@wboucherfischer can you update the status of this with progress to date? Thanks!

**Comment by wboucherfischer** [comment]
Here is a link to the competitive analysis and suggested approach. 
https://docs.google.com/presentation/d/1K-rM_h82VEEsDcF19LaOIAzlASWZImmATftHR0CZ1-E/edit?usp=sharing

**Comment by ejregithub** [comment]
@wboucherfischer - the research and analysis was great; thorough and interesting, thank you!

Closing this as done
