### ISSUE TITLE
Fix eslint 'no-useless-escape' errors.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7747]
## Description

When running `make run` to start bedrock you may notice some errors in your console such as: 
```
assets_1      | /app/media/js/base/mozilla-client.js
assets_1      |   99:55  warning  Unnecessary escape character: \ .  no-useless-escape`
```

The [no-useless-escape](https://eslint.org/docs/rules/no-useless-escape) rule lints for unnecessary characters in regular expressions, .etc. The above error is saying: on line 99 in `/app/media/js/base/mozilla-client.js` there is an extra `\` character.

We should go through and make the recommended eslint fixes to fix these errors.

**Comment by Shivansh2407** [comment]
I have removed the no-useless-escape rule lints for unnecessary characters in regular expressions, .etc.
Please review it and let me know soon.

**Comment by alexgibson** [comment]
Once this is fixed let’s be sure to remove the rule for it: https://github.com/mozilla/bedrock/blob/master/.eslintrc.js#L8

**Comment by amychurchwell** [comment]
@alexgibson shouldn't we keep the rule for future regex?

**Comment by alexgibson** [comment]
> shouldn't we keep the rule for future regex?

The rule is in there as an exception, so it triggers a warning instead of an error. If we remove the rule after this work is done, then it will fall back to the default.

**Comment by Shivansh2407** [comment]
So what should I basically do , should I remove those extra escape char or just remove the rule as suggested by @alexgibson .Please let me know soon @amychurchwell .

**Comment by amychurchwell** [comment]
Both would be ideal. Thank you, @Shivansh2407

**Comment by Shivansh2407** [comment]
Can you please tell how to fix this snippet :
var regex = RegExp(param + '=([^\#\&\?]+).*$');

Here it is showing:
  33:49  warning  Unnecessary escape character: \#  no-useless-escape
  33:51  warning  Unnecessary escape character: \&  no-useless-escape
  33:53  warning  Unnecessary escape character: \?  no-useless-escape
Please let me know soon so that I can complete fixing the issue and create a PR for this.

**Comment by amychurchwell** [comment]
in the error:
```
/app/media/js/firefox/concerts.js
  33:49  warning  Unnecessary escape character: \#  no-useless-escape
  33:51  warning  Unnecessary escape character: \&  no-useless-escape
  33:53  warning  Unnecessary escape character: \?  no-useless-escape
```

in `/app/media/js/firefox/concerts.js` on line 33:
`var regex = RegExp(param + '=([^\#\&\?]+).*$');`

The errors should stop once the `\` characters are removed:
`var regex = RegExp(param + '=([^#&?]+).*$');`

and running `make lint` in your console should show that file has been fixed.

**Comment by Shivansh2407** [comment]
I am fixing this issue by creating PRs for changing various files. Please review and merge them accordingly.

**Comment by amychurchwell** [comment]
Hi @Shivansh2407! we don't need to open a separate PR for every file, they can be added to your original PR.
