### ISSUE TITLE
Code Lifecycle #2

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7748]
## Description

Code the lifecycle page #2 (see [epic](https://github.com/mozilla/bedrock/issues/7698) for related cards).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Lifecycle page is coded and pushed to production
- [x] It includes the features in the UI design
- [ ] It includes the instrumentation in the instrumentation plan

**Comment by ejregithub** [comment]
- needs title for the page 
- button logic

**Comment by rantley** [comment]
@craigcook 

Page title:  Firefox Pocket - Save news, videos, stories and more

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/welcome/2/

**Comment by hoosteeno** [comment]
Sorry, I think I wasn't clear on the button behavior we need.

1. The button on the page should *behave like the button on the firefox_learnmore page*. It should not link to the firefox_learnmore page. That means it should link into an FxA registration or confirmation flow, just like the button on firefox_learnmore.
2. The url on the button needs to have device_id, flow_id, and flow_begin_time parameters, which we get by pinging FxA servers on pageload, as on other FxA-initiating pages like welcome/1. 

Thanks!

**Comment by craigcook** [comment]
> Page title: Firefox Pocket - Save news, videos, stories and more

From a brand angle, I don't think we use the term "Firefox Pocket." Unlike the rest of the Firefox products, Pocket is its own thing and is a standalone brand. So we might want to change this to just "Pocket" or maybe "Firefox _and_ Pocket"? Should we check with Natalie?

**Comment by ejregithub** [comment]
@craigcook - please apply a size estimate for this work.

**Comment by hoosteeno** [comment]
I am working with the Pocket team to get parameter pass-through working. The params I told them we'd send (values TBD by @sghoseWI and by OAuth init) are...

https://getpocket.com/ff_signup?s=ffwelcome2&entrypoint={{something}}&utm_content={{something}}&utm_source={{something}}&utm_campaign={{something}}&utm_medium={{something}}&flowId={{something}}&deviceId={{something}}&flowBeginTime={{something}}&form_type=button

**Comment by sghoseWI** [comment]
@hoosteeno FYI https://github.com/mozilla/bedrock/pull/7869

**Comment by cgonz0** [comment]
gonna sign off on the demo design. looks good to me.
