### ISSUE TITLE
UI Design Lifecycle #2

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7750]
## Description

Build a minimal UI design for Lifecycle page #2 (see [epic](https://github.com/mozilla/bedrock/issues/7698) for related cards).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The page is minimally designed to include critical features
- [ ] Designs include copy provided by copywriters
- [ ] Designs are reviewed by functional teams
- [ ] Designs are reviewed by RASCI including developers

**Comment by hoosteeno** [comment]
@alexgibson and I met with Tawanda, the PM for Pocket Discovery, to talk through our options for Pocket content on this page. Coming out of that meeting we have a clearer idea of how we can feasibly deliver this experience in the next couple weeks. We should have enough information for a visual design. 

Roughly speaking, the design...
* Should follow the layout and copy patterns set by Welcome 1
* Should include Pocket content items similar to those shown on the newtab
* Should include a title above the Pocket content, and link above the Pocket content

A rough wireframe of that is [here](https://miro.com/welcomeonboard/f8gPENCqxj3ZtwQFXxKUNkZMs8ZdVLnd7eGDg1w8Umsfp9MuE4OiI6Zv3z6oA2C7). For those without access, that wireframe looks like this.

**Comment by cgonz0** [comment]
final design with [copy](https://docs.google.com/document/d/1lD5cxydNwSZ4ut_5e86z166i2vebxrGbYUf5PFu_CaU/edit#) from folks @ pocket. (subheader text could possibly change...)
![Lifecycle v2.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/7917c635-ed9e-4a63-9788-e8046fee6169)

**Comment by cgonz0** [comment]
![Save_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/0756746b-8480-436f-a11e-ea5569e8473e)
![Discover_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/216686fc-58ba-4bd8-b152-f4f1d45cdea5)

**Comment by cgonz0** [comment]
@craigcook - dropping the assets here ![lifecycle_v2_illustration.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/3da3f9be-eb56-460e-8f35-5688a13a9c2c)
