### ISSUE TITLE
Analytics plan Lifecycle #2

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7751]
## Description

Build an analytics and instrumentation plan for Lifecycle page #2 (see [epic](https://github.com/mozilla/bedrock/issues/7698) for related cards).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The core instrumentation plan is included in a comment on this issue
- [ ] Any detailed background is linked from this issue to a doc

**Comment by sghoseWI** [comment]
Worked with @craigcook to get the proper params instrumented -- details below:

https://github.com/mozilla/bedrock/pull/7869

**Comment by sghoseWI** [comment]
Lifecycle Page 2

entrypoint='mozilla.org-firefox-welcome-2',
utm_campaign='welcome-2-pocket'
utm_source=mozilla.org-firefox-welcome-2
utm_medium='referral'
entrypoint=mozilla.org-firefox-welcome-2'

**Comment by ejregithub** [comment]
@sghoseWI - just wanted to check in and query if the 2 success criteria for this issue have been fulfilled and if we can close this card?

**Comment by sghoseWI** [comment]
@ejregithub yes, we can close this card. Thanks for checking in.
