### ISSUE TITLE
WNP 70: replace header background

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7778]
## Description

As part of the WNP 70 work we'll replace the header background. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Background is delivered to devs in a format they need for implementation

**Comment by cgonz0** [comment]
New header/bg + updated copy
![WNP70](https://user-images.githubusercontent.com/29640968/65649061-dfe85580-dfb9-11e9-9f09-c45a3b2eda7f.png)

**Comment by cgonz0** [comment]
![Noodle_background_WNP_lineargradient.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/f6012e1a-c3dc-4a2a-846e-0710fb082172)

**Comment by ejregithub** [comment]
@cgonz0 - what action needs to be taken here? (who needs to review this)

**Comment by cgonz0** [comment]
naturally moved this into review, but should probably be in the done column. I already handed over the asset to amy - no other action is needed
