### ISSUE TITLE
Add new UITour target to documentation.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7779]
## Description

Add Logins and Passwords UITour target `logins` to bedrock documentation: https://bedrock.readthedocs.io/en/latest/uitour.html#javascript-api

- Add `logins` to the "Target types:" list.

## Bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1582768

**Comment by yatri1609** [comment]
Hey can I work on this issue?

**Comment by amychurchwell** [comment]
Hi @yatri1609! Feel free, please let us know if you have any questions.

**Comment by imskr** [comment]
@amychurchwell Please review the PR! I have added it.
