### ISSUE TITLE
Blank space in enterprise menu in mobile

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7780]
## Description

The global navigation looks like it is missing an item when it's opened on the firefox/enterprise pages.

### Steps to reproduce

On a screen 767px or smaller visit https://www.mozilla.org/en-US/firefox/enterprise/ and expand the global navigation menu.

### Expected result

Not sure, probably needs design direction. Even putting the two lines very close together would be an improvement, I think.

### Actual result

A blank space appears between the last navigation item and the sub nav that looks like the right size to have a navigation item in it.

![Screen Shot 2019-09-24 at 17 17 18](https://user-images.githubusercontent.com/854701/65559481-a3e8be00-deef-11e9-8776-bd7627367e36.png)

### Environment

MacOS with Nightly.

**Comment by alexgibson** [comment]
The styling of the sub nav is changing enough for the privacy hub pages where I think this will no longer be an issue:

![sub-nav](https://user-images.githubusercontent.com/400117/65581992-6a0dcb00-df74-11e9-9a93-035fc8016239.png)

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7768
