### ISSUE TITLE
Improve FTL file linting 

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#7785]
As a follow up to #7679 we'd like to potentially improve Fluent file linting using some of the tools written by the l10n team. @Pike has recommended [compare-locales](https://pypi.org/project/compare-locales/) and using the `moz-l10n-lint` script or some of the internals directly.

**Comment by alexgibson** [comment]
I see compare-locales was used in https://github.com/mozilla/bedrock/pull/8087. Can this issue be closed?

**Comment by alexgibson** [comment]
Closing this, but feel free to re-open if there's still some more work to be done.
