### ISSUE TITLE
Leadership page updates - in n out

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7794]
## Description

Update the leadership page according to the[ spec in the bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1583389)

---

**Comment by amychurchwell** [comment]
awaiting a final bio in bug.

**Comment by craigcook** [comment]
Doh, I shouldn't have tagged the commit with "fix".

**Comment by amychurchwell** [comment]
@craigcook I forgot to remove it 😅 oh well

**Comment by craigcook** [comment]
I think this is finally complete! (until the next update)
