### ISSUE TITLE
Add lifecycle page 1 to CRO Sandbox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7802]
## Description

The CRO sandbox is a segmented part of the site where we do Conversion Rate Optimization. 

We have to add pages to the sandbox that we intend to experiment on. 

Let's add the new lifecycle page 1 (/firefox/welcome/1). 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] en-US lifecycle 1 is in the sandbox

**Comment by olsenme** [comment]
Hi. My name is Meagan, and I am a CS grad and pretty new to contributing to open source. I didn't see a forum for this page,  but I was wondering if I could help out somewhere? Alot of the "Good first bugs" seemed to be getting picked up really quickly.

**Comment by hoosteeno** [comment]
@olsenme This issue may be kind of esoteric to start with. If you want to take the one below on, comment on the issue and someone will help. Thanks for reaching out!

https://github.com/mozilla/protocol/issues/460

**Comment by olsenme** [comment]
@hoosteeno  Thanks so much for the input. I commented on that issue you suggested

**Comment by alexgibson** [comment]
Blocked on https://github.com/mozilla/bedrock/pull/7954
