### ISSUE TITLE
Outdated google support article linked

### ISSUE THREAD

**Issue by Fiesian** [mozilla/bedrock#7809]
On https://www.mozilla.org/en-US/internet-health/privacy-security/, section _What you can do about user control | Control your apps_, there is a link to https://support.google.com/googleplay/answer/6014972. The linked support article applies to the outdated Android version 5.9 (or older), https://support.google.com/googleplay/answer/6270602 is the article for Android 6.0 and newer.

**Comment by mokshchaudhary** [comment]
Can I have this ?

**Comment by mokshchaudhary** [comment]
#7814

**Comment by Shivansh2407** [comment]
Done Sir Please Check

**Comment by sanskarseth** [comment]
I  want to contribute in the bug .. This is my first request. So can u guide me on this
