### ISSUE TITLE
Footer on /firefox/enterprise/ is not full width in IE

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7819]
## Description

The page footer on /firefox/enterprise/ is not full width in IE11

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/400117/66032088-a5704280-e4fc-11e9-84fa-0ce1012b2c69.png">

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/enterprise/ in IE (I used IE 11)
2. Scroll down to the bottom of the page.

### Expected result

The footer should be full width of the viewport.

### Actual result

The footer is centered in the page.

It looks like there may be a stray / missing closing tag in the HTML source. When I do view source I see:

```
End tag </main> seen but there were open elements.
```

### Environment

IE 11, windows 10.

**Comment by rajk1121** [comment]
@alexgibson Hey. I would like to work on this issue. Is it up for grabs?

**Comment by alexgibson** [comment]
@rajk1121 pull requests are always welcome

**Comment by rajk1121** [comment]
All right @alexgibson . Will get back to you as soon as I set it up locally on my laptop.
