### ISSUE TITLE
Align mission.ftl with template, fix comments

### ISSUE THREAD

**Issue by Pike** [mozilla/bedrock#7821]
`mission.ftl` as landing in PR #7679 has a few issues left over from its `.lang` ancestry.

* Ordering of strings is seemingly random, and should follow file-order from the template.
* URL should be a file-level comment, and not include `%LOCALE%`.

I'm not sure if the comment about the l12y of the video in https://github.com/mozilla-l10n/bedrock-l10n/blob/69a45a89b541a101c218f93d8fb7d9970505437d/en-US/mozorg/mission.lang#L2 should be kept. It's been 4 years "for now", maybe we just settle the case?

CC @pmac @peiying2 @hoosteeno

**Comment by pmac** [comment]
I think I can tackle the ordering by looking at the order in the template and then enforcing that order in the resulting ported files. What I'm not sure about is the comment issues. I'm guessing these are going to be problematic in a number of files, and will probably be inconsistent in the translations. Can we just rely on the developer to tweak the comments in the `en` file and then I can ignore the comments in all of the translation `.lang` files and use the ones in the `en` `.ftl` file for all of the translated `.ftl` files?
