### ISSUE TITLE
Add 'Sign Up' state to monitor button macro.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7823]
## Description

In the `monitor_button` macro our default button text is `Sign In to Monitor`, we should make the default button text conditional depending if someone is signed into a firefox account or not: 
`show-fxa-supported-signed-out` = `Sign In to Monitor`
`show-fxa-supported-signed-in` = `Sign Up for Monitor`

**Comment by imskr** [comment]
I would like to work on it

**Comment by amychurchwell** [comment]
@craigcook I forgot what the resolution of our convo was the other day when we were discussing the l10n task for this. Do you remember?

**Comment by alexgibson** [comment]
I'm not sure it makes sense to do this. The macro currently has the string `Sign In to Monitor` baked in directly, but that string doesn't belong to any specific .lang file (it's not in main.lang). This makes it easy to assume that the string is global and widely translated, but this isn't the case. Adding another string in the same fashion will have the same issue.

This macro is also being removed in https://github.com/mozilla/bedrock/pull/8311, in favor of the python helper.
