### ISSUE TITLE
/firefox/welcome/ pages are listed in sitemap

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7833]
## Description

The /firefox/welcome/ pages are noindex, but still appear listed in the sitemap.

### Steps to reproduce

1. Open https://www.mozilla.org/sitemap.json
2. Hit `cmd + f` and search for /firefox/welcome/

### Expected result

The URL `/firefox/welcome/1/` should not be listed.

### Actual result

The URL is listed.

Adding `r'^firefox/welcome/',` to the list of no-inex URLs here should fix this issue: https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L267

### Environment

N/A

**Comment by craigcook** [comment]
I'll fix this when I add the second welcome page

**Comment by Shivansh2407** [comment]
Can I help ?

**Comment by craigcook** [comment]
> Can I help ?

Go for it. Since I won't have the second welcome page ready for a few more days, this seems like a simple fix we can get in before then.

**Comment by Shivansh2407** [comment]
I have added r'^firefox/welcome/' to the list of urls ..Please Check and let me know

**Comment by Shivansh2407** [comment]
Check #7836
