### ISSUE TITLE
Redirect /enterprise to /firefox/enterprise

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7842]
## Description

We should [add a redirect](https://bedrock.readthedocs.io/en/latest/redirects.html) to point **/enterprise** to **[/firefox/enterprise](https://www.mozilla.org/firefox/enterprise/)**.

**Comment by Shivansh2407** [comment]
Can I work on this issue . Also explain a little more about it.

**Comment by Shivansh2407** [comment]
REDIRECTS FIXED PLEASE CHECK ...

**Comment by alexgibson** [comment]
@Shivansh2407 if you look at the activity above, someone has already submitted a PR for this issue. As a courtesy on a first-come, first-served basis I have closed your PR and we will review the first one opened.
