### ISSUE TITLE
Browser Comparison Hub Page Design Assets

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7853]
The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Original brief](https://docs.google.com/document/d/1TRJO1g9ZT6CBR94iApXOfkAcq_54G8aoLu_PYxC2tX4/edit#)

[FINAL EN COPY](https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit?usp=sharing)

***Tasks***
- [x] Complete design assets originating from JKropp
- [ ] Specify Protocol 
- [ ] Team & Stakeholder review in Miro

**Comment by hoosteeno** [comment]
Copy is done and legal approved per @ejregithub

**Comment by cgonz0** [comment]
Final design for comparison hub.
![BCH_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/ec87ccbd-b048-401b-b0d5-60515fa869a9)

**Comment by cgonz0** [comment]
Updated table data from [source of truth](https://docs.google.com/spreadsheets/d/1jlttswF282a9oOQAY7fDCQd44EDCwfxnqVlsht3FRXg/edit#gid=1512926430).

![BCH_mockup_updatedtables.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/26988a96-3e7e-4255-bfae-b43abf963005)
