### ISSUE TITLE
High-res image helper doesn't work with images from Protocol NPM package

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7863]
## Description

See https://github.com/mozilla/bedrock/pull/7848 for context, where we had to revert a change because the high_res_img helper doesn't play quite right with images that are in `/protocol/`, rather than `/media/img/`.

To make it more fiddly, the helper seems to work as expected when running locally, but not when deployed to demo.

### Steps to reproduce

I'm actually not quite sure how to reproduce this locally (what are the best steps for emulating the same environment?), but adding the following to a template and pushing to demo should reproduce the bug:

```
{{ high_res_img('/protocol/img/logos/firefox/monitor/logo-word-hor-stack-md.png') }}
```

### Expected result

The page should give a 200 response.

### Actual result

The page throws a 500 error.

### Environment

N/A

**Comment by alexgibson** [comment]
@pmac not super urgent as we reverted the change, but could you take a look at this one when time allows?

**Comment by pmac** [comment]
@alexgibson one of the reasons the helpers don't include the `img/` prefix is that the `l10n_img` helper relies on other directories, so it's easiest if they have just the path information after the `img` dir. Is it okay if the `l10n_img` helper won't support protocol images? I doubt protocol would include images with text.

**Comment by alexgibson** [comment]
@pmac I don't thnk there's a current need for the `l10n_img` helper in regard to protocol sourced images. Most assets are logos and wordmarks, which aren't translated. 

One wrinkle might be that `high_res_img` also supports an `l10n` parameter though?

**Comment by pmac** [comment]
> One wrinkle might be that `high_res_img` also supports an `l10n` parameter though?

Right, but I think we may just have to document that this option doesn't work with images outside of the `media/img/` folder e.g. protocol assets.
