### ISSUE TITLE
(10/21) Push /firefox/privacy/ and /firefox/privacy/products/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7876]
## Description

Push  /firefox/privacy/ and /firefox/privacy/products/ on 10/21 so they are live for the 10/22 Skyline launch

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are live on 10/21

#### Tasks
- [ ] Push the merged pages on 10/21

**Comment by alexgibson** [comment]
Fixed https://www.mozilla.org/en-US/firefox/privacy/
