### ISSUE TITLE
Alternative way of handling data-attributes

### ISSUE THREAD

**Issue by icaaq** [mozilla/bedrock#788]
Instead of `<div id="strings" data-foo="bar"></div>` you could do something like this:

```
{% block js %}
    {{ js('home') | {
        'close': {{_('Close')}},
        'share': {{_('Share')}}
      }
  }}
{% endblock %}
```

that generates something like this
`<script id="home-js" data-close="Close" data-share="Share" src="//mozorg.cdn.mozilla.net/media/js/home-min.js?build=f446ab8"></script>`

**Comment by alexgibson** [comment]
Closing out old issues
