### ISSUE TITLE
Firefox nav logo is truncated on legacy IE browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7885]
## Description

The Firefox master brand logo is truncated when viewing the universal stylesheet served to legacy browsers:

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/400117/66636113-6fbc0f80-ec08-11e9-9988-e8f8fe4bf3fc.png">

Whilst we don't provide 1st class CSS support for these browsers, I think we could at least try and ensure the nav logo displays correctly.

### Steps to reproduce

Visit https://www.mozilla.org/en-US/firefox/ or any firefox related page where the nav is displayed.

### Expected result

The FIrefox master brand logo should be identifiable.

### Actual result

The logo is truncated.

### Environment

IE9

**Comment by Shivansh2407** [comment]
how can i help fixing this?

**Comment by stephaniehobson** [comment]
Fixed in #8083
