### ISSUE TITLE
Picto cards on 68.0 /whatsnew page missing styles

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7897]
## Description

I have no idea if this experiment is still active, or if people are still seeing it somehow, but the picto cards on the 68/0 /whatsnew page seem to be missing some styling:

![image](https://user-images.githubusercontent.com/400117/66745360-a39c6c80-ee76-11e9-8d86-ecacd0c4037c.png)

It's only visible if you're signed-out of Sync.

### Steps to reproduce

1. Make sure you're suing a profile that is signed out of Sync.
2. visit https://www.mozilla.org/en-US/firefox/68.0/whatsnew/all/?v=c

### Expected result

The three list items below the main CTA should be centered in the same narrow column, and have smaller headings.

### Actual result

The items span the full width of the page container and have default heading sizes.

### Environment

Firefox Nightly.

**Comment by craigcook** [comment]
That experiment is not active, though the page is still live. It needs to be deleted. I'll work on finishing up https://github.com/mozilla/bedrock/pull/7665 today.

**Comment by Shivansh2407** [comment]
@craigcook Can I work on this? Please explain me a bit about what to do? Thanks

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7665
