### ISSUE TITLE
Legal doc update: production push needed

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#7901]
## Description

A few legal docs have been updated and need a production push:
- Firefox Privacy Notice (lockwise link change, localization update)
- Firefox Cloud Services Privacy Notice (lockwise link change, localization update)

Deadline: October 17 (the lockwise update need to be pushed for the October launch).

**Comment by peiying2** [comment]
@pmac @Errolyn

**Comment by alexgibson** [comment]
Please double-check but I think this has already been taken care of in https://github.com/mozilla/bedrock/pull/7891

**Comment by peiying2** [comment]
> Please double-check but I think this has already been taken care of in #7891

Thank you!!
