### ISSUE TITLE
'Go to Lockwise' link is incorrect on Fx70 whatsnew page

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/bedrock#7910]
## Description

The fallback URL for the 'Go to Lockwise' link is incorrect as it links to a tracking protection page, instead of a Lockwise desktop page.

### Steps to reproduce

1. Load https://www.mozilla.org/firefox/70.0/whatsnew/
2. Right-click on "Go to Lockwise" and Open Link in New Tab (or ctrl-click the link)

### Expected result

A SUMO article should explain about the Lockwise on desktop

### Actual result

I'm taken to the irrelevant "Enhanced Tracking Protection in Firefox for desktop" SUMO article. The incorrect URL is at https://github.com/mozilla/bedrock/blob/0218a6fbc5da55bf60a0120fd76d37e2b97560a0/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70.html#L89

### Environment

Firefox 70

**Comment by ejregithub** [comment]
@amychurchwell - please check this one (I can confirm the reported issue)

**Comment by ejregithub** [comment]
@mnoorenberghe - thank you for reporting this!
