### ISSUE TITLE
Mozilla menu "Firefox Desktop" link goes to Firefox master brand page.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7917]
It should go to firefox/new since that's where we market the Desktop browser now.

@hoosteeno @rraue @sghoseWI This will have the effect of dropping traffic to /firefox and increasing traffic to /firefox/new/

**Comment by Shivansh2407** [comment]
Is this still open ?

**Comment by stephaniehobson** [comment]
Yes.

**Comment by hoosteeno** [comment]
@rraue, I support this change, but I'd like you to weigh in on it before we commit to it. Do you have any concerns that removing this link will negatively impact how we show up in search?

**Comment by rraue** [comment]
We should do it!

**Comment by stephaniehobson** [comment]
Closed by #7925
