### ISSUE TITLE
Design - Browser Comparison SEO Edge page: Compare Firefox vs Microsoft Edge

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7931]
Design task for Firefox vs. Edge browser comparison page.

[Copy - en-US](https://docs.google.com/document/d/1QSX6lr2VSpLA8gb-Sbotiwb0AySntNCadBVXKly7UJY/edit)

**Comment by cgonz0** [comment]
![BC_firefoxVsEdge_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/791ee0fc-c563-4603-a6e6-4256b7ae5972)
