### ISSUE TITLE
Design - Browser Comparison SEO Internet Explorer page: Compare Firefox vs Internet Explorer

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7932]
Design task for Firefox vs. IE browser comparison page.

Brief

[Copy - en-US](https://docs.google.com/document/d/1tMtr1tU5c7kDvmRcnEUgjnAsNDrWYaM7yiTdQkZR5hw/edit#)

**Comment by cgonz0** [comment]
![BC_firefoxVsIE_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/1fa483c9-3c4f-431f-9f48-c54317a92191)
