### ISSUE TITLE
Design - Browser Comparison SEO Safari page: Compare Firefox vs Safari

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7933]
Design task for Firefox vs. Safari browser comparison page.

[Copy](https://docs.google.com/document/d/1KpxsHVtge3bk5l8BYHz4E_UpWI4PR6sYcx5ZdTAifrI/edit#heading=h.oo63piaiuqi8)

**Comment by cgonz0** [comment]
![BC_firefoxVsSafari_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/3e9568b5-3555-44ba-ac49-acb6c70b219f)
