### ISSUE TITLE
Design - Browser Comparison SEO Opera page: Compare Firefox vs Opera

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7934]
Design task for Firefox vs. Opera browser comparison page.

[Copy - en-US](https://docs.google.com/document/d/1zSMcQwsHJkrrxJ4X9x7jZmwbWCpdG6Cq66FcvZI0Dsk/edit)

**Comment by cgonz0** [comment]
![BC_firefoxVsOpera_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/2565f223-aa31-48b1-949c-9399f79721da)
