### ISSUE TITLE
Double counting events on lockwise page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7941]
## Description

In https://github.com/mozilla/bedrock/blob/d09bd3bdce9a778c951fce74fe9d58866629fa81/bedrock/firefox/templates/firefox/lockwise/lockwise.html#L55, we see the following:

```
 <a href="{{ lockwise_adjust_url('ios', 'lockwise-page') }}" data-link-type="download" data-download-os="iOS" class="ios-button"  data-cta-text="apple-app-store" data-cta-type="lockwise-app-store" data-cta-position="primary">
```

I believe `data-link-type` causes an event to fire, for an iOS (browser) download. And `data-cta-type` causes an event to fire. We should not fire both events.

We should use the spec here for the data attributes on links on this page:

https://github.com/mozilla/bedrock/issues/7583#issuecomment-536762745

Specifically:

* remove data-link-type and data-download-os from the lockwise app store links

**Comment by Shivansh2407** [comment]
I have removed data-link-type and data-download-os from the lockwise app store links. Please check the PR #7944 .

**Comment by alexgibson** [comment]
@hoosteeno it looks like fixing this here on one page is easy, but the Google play store badge uses a macro that is shared on many pages across the site. Removing `data-link-type="download" data-download-os="Android"` from the macro will therefore effect download counts on many more pages.

The suggested values `data-cta-type=“lockwise-app-store” data-cta-text=“google-play-store”` only work assuming the macro is used for Lockwise. If we we're to make the macro have a default value (say data-cta-type=“firefox-app-store”`) that we could then override, would that work?

**Comment by hoosteeno** [comment]
I'm not sure I understand: Are we using the same macro to build app store buttons for every kind of app in the app store? And that means we have to count all clicks on app store buttons as a download click on a mobile browser's download button?

**Comment by alexgibson** [comment]
> Are we using the same macro to build app store buttons for every kind of app in the app store? And that means we have to count all clicks on app store buttons as a download click on a mobile browser's download button?

Yes. 99% of these are just for Firefox Android, but a few are for Focus. I don't know the history for why it's configured this way, but removing the default dtat-attributes will havce knock on offects on buttons for other pages.

**Comment by hoosteeno** [comment]
Since Lockwise is not a browser download, we shouldn't count it as one. It sounds like the solution is more complicated than removing a parameter; in fact, we need to replace the macro on non-browser download buttons. It could be a different macro; or a more flexible macro; or bespoke code on this one page. 

@Shivansh2407 thank you for your PR, and I'm sorry the complexity here is bigger than I originally thought.

**Comment by ejregithub** [comment]
@alexgibson - can you please apply a size estimate for this card?
