### ISSUE TITLE
(10/22) /mobile page - device w. Firefox logo image update for Skyline

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7951]
Description:  we need to make an image update for Skyline on the /mobile page, replacing the current device image w. Firefox logo in it to correspond to the new branding.

***Success Criteria***
- [ ] Updated image is live on 10/22 and not before, targeting go live at 8:30 am PT (pushing early to meet that is okay, putting it behind a switch would be ideal).

**Comment by ejregithub** [comment]
![fx-device-2](https://user-images.githubusercontent.com/20547886/67029799-da66c280-f0c2-11e9-97e0-8b15a1bbce97.png)

**Comment by Errolyn** [comment]
This has been reviewed and is waiting for its merge date.
