### ISSUE TITLE
Images on /firefox could use some further optimization

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7964]
## Description

The new [/firefox](https://www.mozilla.org/en-US/firefox/) page weighs in at over 3MB high-res screens, which is more than twice as resource heavy as the previous design.

There may be further optimizations we could do, but looking at the waterfall chart there are a couple of images that jump out; both of which could likely be optimized further.

- https://www.mozilla.org/media/img/firefox/home/master/respect-high-res.png (1.4MB)
- https://www.mozilla.org/media/img/firefox/home/master/pocket-high-res.png (615KB)

**Comment by stephaniehobson** [comment]
These will be replaced by much smaller SVGs in https://github.com/mozilla/bedrock/pull/7962
