### ISSUE TITLE
en-US homepage - update Lockwise video w. new URL

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7977]
## Description

the Lockwise video on the homepage, en-US, needs to be update to this URL:
 https://youtu.be/ltRDl6FJKck  (the current one talks about the add-on)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is updated and live 10/22

#### Tasks
- [ ] Update the Lockwise video with the newer video link - https://youtu.be/ltRDl6FJKck

**Comment by alexgibson** [comment]
Fixed on stage: https://www.allizom.org/en-US/

**Comment by alexgibson** [comment]
Fixed on prod: https://www.mozilla.org/en-US/
