### ISSUE TITLE
(10/25) Review/Merge/Push Fx Lite legal doc updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7978]
## Description

Updates and new pages are being added in the legal-repo for Fx Lite. They'll need to be reviewed and merged/pushed on or about 10/25

https://bugzilla.mozilla.org/show_bug.cgi?id=1589298

---

**Comment by alexgibson** [comment]
Note that there are 2 new pages required here, so it's more than just a Git sub-module update.

**Comment by chianger** [comment]
FWIW. You may find there's one link  (https://qsurvey.mozilla.com/s3/Firefox-Lite-Reward-Help) not really functioning in the Terms of Use for reward ( https://github.com/mozilla/legal-docs/blob/master/firefox_lite_contentservices_reward/en-US.md ).  We'll make that survey link work on Oct-24.

**Comment by alexgibson** [comment]
I have a draft PR here to update the content: https://github.com/mozilla/bedrock/pull/7994

Please let me know when all the localizations are ready in the L10n repo and I'll update here and mark it ready for review. Thanks.

**Comment by ejregithub** [comment]
@alexgibson - @peiying2 is telling me know (Thursday at 3:34 pm PT) that the legal docs are coming in tonight and that she'll merge them shortly after.

@peiying2 - please flag Alex here when that's ready/he can push on bedrock

**Comment by peiying2** [comment]
@alexgibson the three sets of Firefox Lite legal docs are merged to the master repo. Please help with the production push.

**Comment by alexgibson** [comment]
These pages are now in production:

- https://www.mozilla.org/en-US/privacy/firefox-lite/
- https://www.mozilla.org/en-US/about/legal/terms/firefox-lite/
- https://www.mozilla.org/en-US/about/legal/terms/firefox-lite/reward/
