### ISSUE TITLE
Download links on /firefox should point to locale neutral /thanks URL

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7982]
## Description

The download links for desktop on [/firefox](https://www.mozilla.org//firefox/) include the page locale in the destination URL, which means people can only download Firefox in the same language as the page is translated in. We should remove the locale from the link, so that language detection can serve the most apropriate build.

### Steps to reproduce

1. With an en-US browser, visit https://www.mozilla.org/de/firefox/
2. Click "Browser downloaden"
3. Click "Desktop"

### Expected result

I should land on https://www.mozilla.org/firefox/download/thanks/ and then be redirected to https://www.mozilla.org/en-US/firefox/download/thanks/, as en-US is my preffered language.

### Actual result

I land directly on https://www.mozilla.org/de/firefox/download/thanks/, and get the German build.

The above is just a simple to reproduce example, but It can be worse for other languages; as unless the page language matches, it makes it difficult to download the right build of the browser.

### Environment

Any browser

**Comment by craigcook** [comment]
It's linking to `{{ url('firefox.download.thanks') }}` ... should that be just `/firefox/download/thanks/` without using the url helper?

**Comment by stephaniehobson** [comment]
As a user I'm not sure I'd expect to get the English version when downloading from the German page.

**Comment by alexgibson** [comment]
> As a user I'm not sure I'd expect to get the English version when downloading from the German page.

With the exception of /firefox/new/, this is something we do across the site, as we can't be sure every page on the website is translated in the user's preferred language. The /firefox page has pretty good coverage, but unless it's as exhaustive as /new I think we should consider this a valid issue.

**Comment by alexgibson** [comment]
Currently /new has 43 locales active, whereas /firefox has 28.

So for example, right now it's really hard for someone to get the build in their preffered langage, if they are part of that delta.

**Comment by amychurchwell** [comment]
I agree that I think it would be confusing as a user to be downloading the english version of the browser when navigating the site on `de`. 
could we do a check for: if the page is not localized in their preferred language, we send them to /all, so they can make the call? 

I think we should do our best to avoid the potentially frustrating experience of downloading the browser in a language you do not expect.

**Comment by alexgibson** [comment]
All download buttons on the site work this way today (give a locale neutral link for the reasons above). I’m not opposed to thinking about different solutions, but I think we should probably do that a site wide level.

Users being unable to get access to builds in their preferred language is a real problem, and I think a bigger one than someone landing on a page not in their language, and getting a build they can still use.

Linking to /firefox/all/ is an idea, but one that could likely impact conversions.

**Comment by alexgibson** [comment]
I filed an issue to add a link to /firefox/all/ on the thanks page: https://github.com/mozilla/bedrock/issues/8116
