### ISSUE TITLE
Redirect `/privacy/products/` to `/firefox/privacy/products/`

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7983]
## Description

We should [add a redirect](https://bedrock.readthedocs.io/en/latest/redirects.html) to point **/privacy/products/** to **[/firefox/privacy/products/](https://www.mozilla.org/firefox/privacy/products/)**.

**Comment by Shivansh2407** [comment]
I want to take up this issue ... Please let me the file to fix

**Comment by Patil2099** [comment]
@amychurchwell Is this issue still open?
