### ISSUE TITLE
Responsive styles bug on product list in bottom /firefox CTA.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8007]
## Description
Styles for list items in `.c-showcase-list .t-small` are broken on mobile screen sizes.
https://github.com/mozilla/bedrock/blob/master/media/css/firefox/home/master.scss#L196-L205

<img width="395" alt="Screen Shot 2019-10-24 at 1 01 50 PM" src="https://user-images.githubusercontent.com/30483988/67520838-7c0b8800-f65e-11e9-8ed4-dc9f973bbd1d.png">

**Comment by imskr** [comment]
I would like to work on this!

**Comment by amychurchwell** [comment]
@imskr sounds good! I will assign you to this issue. Let us know if you have any questions. 🙂

**Comment by imskr** [comment]
@amychurchwell  It can be like this if i change `<div class="c-showcase t-small">` to `<div class="c-showcase">`  Should i make like this or make changes in scss file?

![ss](https://doc-08-0o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ssn109r2qknfi5cetubf4mkplbck1l12/1572336000000/01128862856494067037/*/1Qd_YaAFJuyvlEtVopJp9jpvWX8G5l3Ej)

**Comment by amychurchwell** [comment]
@stephaniehobson cc'ing for your opinion because I believe you were the dev on the /firefox redesign? ⬆️

**Comment by stephaniehobson** [comment]
The link isn't working for me :(

Here is what it should look like:

<img width="477" alt="Screen Shot 2019-10-29 at 09 07 10" src="https://user-images.githubusercontent.com/854701/67786110-8eedd600-fa2b-11e9-9b73-7f6ce1297f59.png">

I think you will need to fix the flex problem (maybe by setting `flex-basis:auto`) and decrease the borders just on `.t-small .c-showcase-list li`.

**Comment by imskr** [comment]
@stephaniehobson I've updated my comment above.

**Comment by stephaniehobson** [comment]
The image I posted is the original spec for this page. A good fix for this issue would be for it to match that design and you will need to edit the CSS to solve it.
