### ISSUE TITLE
WNP70 test - specify the experiment

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8031]
## Description

[Write the specification](https://docs.google.com/document/d/1cFYYXLam6ic27tEsd2pplFPsvu-AyaA1rDsA8L1qR6g/edit#) for experimenting on WNP70

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
@sghoseWI has provided this document: https://docs.google.com/document/d/1cFYYXLam6ic27tEsd2pplFPsvu-AyaA1rDsA8L1qR6g/edit#

**Comment by hoosteeno** [comment]
Experiment instrumentation specifications are at the bottom of this document: https://docs.google.com/document/d/1cFYYXLam6ic27tEsd2pplFPsvu-AyaA1rDsA8L1qR6g/edit#heading=h.6bvhfucrz4hk

**Comment by hoosteeno** [comment]
Each variation in the experiment (including variation 0, the control) should get 5% of traffic to WNP70, in en-US only.

**Comment by ejregithub** [comment]
@hoosteeno @sghoseWI - could you please collectively size this work and apply that in the Estimate?
