### ISSUE TITLE
Specify /firefox page buttons experiment

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8036]
## Description

Specify an experiment to test buttons on the /firefox/ page - generated by the EU Growth Team

https://trello.com/c/YGuH0oz9/288-cro-test-on-firefox-download-buttons-instead-of-dropdowns

The updated /firefox page uses a dropdown link for browser downloads. This requires two clicks. This is a simple test to replace the dropdown with the three options (Desktop, Android, iOS) shown directly on the page instead, reducing the clicks to just one.

Hypothesis:

A more direct presentation of download links that reduces friction to the visitor will increase download conversion rate for all three browsers.

***Tasks***

Test control against a couple of alternative designs. This experiment requires some lightweight design. A few options:

- Use the same link styles as shown in the dropdown
- Use more traditional download buttons for each product (w/ GPlay and App store icons for mobile)

***Notes***
- Little or no copy work is needed. Initial test can probably reuse existing copy
- It doesn't matter which locale(s) we test this on. en-US, DE or multiple

**Comment by hoosteeno** [comment]
@stephaniehobson is this experiment important enough to keep this issue open?

**Comment by stephaniehobson** [comment]
@hoosteeno yes

**Comment by ejregithub** [comment]
The CRO team has this in their board @stephaniehobson

**Comment by hoosteeno** [comment]
This is being worked in https://trello.com/c/9onBmpFI/30-buttons-vs-dropdowns.
