### ISSUE TITLE
Firefox Account links in the nav/footer are broken in non-Firefox browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8044]
## Description

The "Sign Up" and "Sign In" links in the footer of the firefox pages don't work as expected.

![image](https://user-images.githubusercontent.com/400117/67787272-2ec95500-fa68-11e9-8983-a4490ad53b30.png)

### Steps to reproduce

1. In Chrome, visit https://www.mozilla.org/en-US/firefox/
2. Scroll down to the footer.
3. Click "Sign Up"

### Expected result

The link should take me to https://accounts.firefox.com/signup, where I should be able to sign up for a Firefox Account

### Actual result

The link takes me to https://accounts.firefox.com/signin, which isn't the right pathway. The form itself also breaks in non-Firefox browsers, spinning forever:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/400117/67787511-a13a3500-fa68-11e9-9162-eddfcaf0bbde.png">

I believe this is because the links contain `?service=sync` and possibly `context=fx_desktop_v3`

### Environment

Any non-Firefox browser.

**Comment by stephaniehobson** [comment]
I submitted a PR for the sign-up link. I think changing the sign-in link will require editing our macros to remove the service param?
