### ISSUE TITLE
Running bedrock using Docker drains battery quickly

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8056]
## Description

Since https://github.com/mozilla/bedrock/pull/7679 merged I've noticed my MBP's fans are spinning almost constantly when running bedrock locally (using Docker), and the battery seems to be draining quicker too.

I'm not 100% certain, but I think this is due to https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L237

I've overridden this value in my `.env` to use a longer timeout

```
L10N_CACHE_TIMEOUT=60
```

My laptop seems quieter, but I'll continue to monitor. I'd be interested if others are seeing the same thing, and if changing this value helps?

**Comment by pmac** [comment]
Interesting. I'll do some testing and see what I can see.

**Comment by alexgibson** [comment]
An update here: I'm still having issues running Docker, but I'm no longer certain `L10N_CACHE_TIMEOUT` is the cause (I'm still seeing high energy usage even after changing it). I've tried resetting Docker from scratch, clearing caches, pruning images, but so far nothing has worked.

I've resorted to running bedrock locally for now, which is less taxing on my machine. I'll try and set some time aside to test again soon.

**Comment by pmac** [comment]
well that is unfortunate. I was sure that would be the fix since that is the one change that would most affect your local environment when working on non-Fluent pages. What I could do is to split that timeout into separate ones for LANG and Fluent so that we can keep fluent very short for dev and leave LANG very long since it's not needed for dev. Sound good?

**Comment by pmac** [comment]
you could try it with the timeout set for 600 (like it was) and see if that brings it back into a more normal range.

**Comment by alexgibson** [comment]
> you could try it with the timeout set for 600 (like it was) and see if that brings it back into a more normal range.

I'll give this a test tomorrow and see how long my battery lasts for 👍

**Comment by alexgibson** [comment]
I've been working again using Docker this morning, and using a timeout of 600 has made a huge improvement, both in terms of CPU and battery (I'm on 45% battery by lunch as opposed to < 20%). I'm not sure what the best solution is here, but I would say the current default makes (for me at least) using Docker unworkable :(

Is there any way we could optimize what's happening in the background, to either be more efficient, or needs to happen with less frequency?

**Comment by pmac** [comment]
Great! that's fantastic info. I'll get a PR together that gets us back to the 600s (or longer) timeout for the langfile translations. Thanks!
