### ISSUE TITLE
Analyze results from experiment run /new using Convert #7857

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8058]
Target Experiment was #7851, implemented in #7857

We should test new strings/icons on en-US/firefox/new using Convert. 

This card is for the task to analyze and report on the results

***Tasks***
- [ ] Analyze the experiment

**Comment by alexgibson** [comment]
Initial resulas are here: https://github.com/mozilla/bedrock/issues/8070#issuecomment-554925744

The Convert report can be seen here: https://app.convert.com/#/projects/1003343/experiments_report/10031827

@hoosteeno please make sure to archive the experiment once the analysis is closed out. Thanks

**Comment by sghoseWI** [comment]
Experiment Report: https://docs.google.com/document/d/10l6_Vye2U4VB8lnb5oRftkFbdLqEeE_MbP_-loeb5z8/edit#

**Comment by alexgibson** [comment]
Analysis is done here, closing
