### ISSUE TITLE
Update the hero section headline copy on the welcome 1 page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8060]
## Description

https://www.mozilla.org/firefox/welcome/1/

We need to update the headline copy on the welcome 1 page with something that we believe will perform better than the current copy based on testing in another location (mobile).

The new string for the hero headline replacing the current "You’re on track to stay protected" is:

"Stay ahead of hackers. Check for data breaches with Firefox Monitor."

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New string is live in en-US

#### Tasks
- [ ] Update headline copy in en-US and submit PR

**Comment by ejregithub** [comment]
@peiying2 

When we get this merged, can you please update for en-CA and en-GB, de and FR in Pontoon?

https://pontoon.mozilla.org/translate/de/mozillaorg/firefox/welcome/page1.lang/

en:
Stay ahead of hackers. Check for data breaches with Firefox Monitor.

de:
Sei Hackern einen Schritt voraus. Checke Datenleaks mit Firefox Monitor.

fr:
Vérifiez si vous avez été victime d’une fuite de données avec Firefox Monitor.

**Comment by craigcook** [comment]
> @peiying2
> 
> When we get this merged, can you please update for en-CA and en-GB, de and FR in Pontoon?

I'll have a separate PR to add the new string.
