### ISSUE TITLE
Only update DB when there is a change to the relevant env file in www-config

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#8062]
## Description

Currently, "./manage.py [update_www_config](https://github.com/mozilla/bedrock/blob/master/bedrock/base/management/commands/update_www_config.py)" (called by [bin/run-db-update.sh](https://github.com/mozilla/bedrock/blob/5c7518d/bin/run-db-update.sh#L30) via [bin/cron.py](https://github.com/mozilla/bedrock/blob/a5c85b5/bin/cron.py#L103)) will update the DB whenever there is any commit to the master branch of www-config. We'd like to change this to only update the DB when there is a change to the relevant env file in [waffle_configs](https://github.com/mozmeao/www-config/blob/master/waffle_configs/).

**Comment by alexgibson** [comment]
@pmac is this something still important / relevant today? If not can we close this out?
