### ISSUE TITLE
Release and monitor experiment run /new using Convert #7857

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8070]
Target Experiment was #7851, implemented in #7857

[The experiment in Convert](https://app.convert.com/#/projects/1003350/experiments_report/10031777)

We should test new strings/icons on en-US/firefox/new using Convert. 

This card is for the tasks to set the experiment live and monitor it for performance and shut off

***Tasks***
- [x] Start experiment run
- [x] Monitor results
- [x] Shut off

**Comment by alexgibson** [comment]
This experiment is now enabled in production and dat is coming into the Convert dashboard.

**Comment by alexgibson** [comment]
This experiment is now turned off as requested by @hoosteeno:

Date range
-----------

Nov 4th - Nov 18th

Conversion rate:
----------------
a. Original variation: 67.04% 
b. Skyline branding: 66.49% (confidence 85.78%)
c. A/A: 66.86% (confidence 63.78%)
