### ISSUE TITLE
Add localized images on /firefox/ and /firefox/privacy/products/ pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8074]
## Description

Update /firefox/ and /firefox/privacy/products/ pages with localized images.

Assets are linked below

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] `en`, `de`, and `fr` locales are updated.

#### Tasks
- [ ] Update templates to use localized images.
- [ ] Optimize images.

**Comment by carolynjaeger** [comment]
Hey @alexgibson here are the images for the /firefox page that need updating. I am unable to upload SVGs to Github so will send you the SVG files via Slack for the /fireox/privacy/products page.

**EN Files**
![img-browser-EN](https://user-images.githubusercontent.com/57360215/68129832-89f0c100-ff1a-11e9-83e3-3dfd61d0f360.jpg)
![img-browser-EN@2x](https://user-images.githubusercontent.com/57360215/68129833-8a895780-ff1a-11e9-9b3f-ee27b918f393.jpg)


**FR Files**
![img-browser-FR](https://user-images.githubusercontent.com/57360215/68129866-9e34be00-ff1a-11e9-9043-0de3cac15117.jpg)
![img-browser-FR@2x](https://user-images.githubusercontent.com/57360215/68129867-9e34be00-ff1a-11e9-8ac7-e2fe3713e722.jpg)


**DE Files**
![img-browser-DE](https://user-images.githubusercontent.com/57360215/68129755-66c61180-ff1a-11e9-95b1-c84b9ea5caa6.jpg)
![img-browser-DE@2x](https://user-images.githubusercontent.com/57360215/68129757-66c61180-ff1a-11e9-931e-ad3e1ed20d9a.jpg)

**Comment by alexgibson** [comment]
Zip file of all images:

[FINALS.zip](https://github.com/mozilla/bedrock/files/3804590/FINALS.zip)

**Comment by alexgibson** [comment]
@ejregithub fyi - for prioritization ^
