### ISSUE TITLE
Default whatsnew page top banner is solid white

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8108]
## Description

The banner on the top of the default whatsnew page, `firefox/whatsnew/index.html` is solid white and should be changed to `$color-off-black` to match the background.

<img width="1207" alt="Screen Shot 2019-11-08 at 9 12 49 AM" src="https://user-images.githubusercontent.com/30483988/68496949-4ba01e00-0208-11ea-8e37-377bea54bdd1.png">

<img width="1209" alt="Screen Shot 2019-11-08 at 9 13 04 AM" src="https://user-images.githubusercontent.com/30483988/68496970-55298600-0208-11ea-8390-acf0df01e82f.png">

**Comment by imskr** [comment]
I would like to work on this!

**Comment by Shivansh2407** [comment]
Please check this out

**Comment by imskr** [comment]
@Shivansh2407 I'm already working on this

**Comment by amychurchwell** [comment]
@imskr I assigned you to this bug. The file to change is [`media/css/firefox/whatsnew/whatsnew.scss`](https://github.com/mozilla/bedrock/blob/master/media/css/firefox/whatsnew/whatsnew.scss#L63-L65)

Let's remove the background properties from `.main-content` and add a new rule for `.content-wrapper`

```
.content-wrapper {
    background: $color-off-black url('/media/img/firefox/whatsnew/whatsnew_background.svg') no-repeat;
    @include background-size(100%);
}
```

**Comment by imskr** [comment]
Thanks @amychurchwell I will do it!
