### ISSUE TITLE
Not getting data on variations for WNP70 experiment

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8111]
## Description

We're looking for data coming in from the experiment on WNP70:

https://analytics.amplitude.com/mozilla-corp/chart/new/h7w2u50

Only seeing it from v3 and v4 -- the email-first variations. 0,1,2,5,7 are not sending data. They are all button variations. #8110 addresses one found bug. We should see data coming in from those variations as soon as it lands, or we should urgently debug.

https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=0
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=1
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=2
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=3
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=4
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=5
https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=7

**Comment by craigcook** [comment]
#8110 has been deployed to production, the data should be flowing as of this posting. If not, we need to figure out what else might be wrong.

**Comment by hoosteeno** [comment]
Data is coming in. #8110 was the fix. 😌
