### ISSUE TITLE
Subscriber Feedback: "Email preferences don't make sense"

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/bedrock#8112]
> Hello friends,
> I dunno if this is corretc place to repurt bug, but I am confusion of the email preferences.
> Is it yes to subscibe, no to unsubscribe? Please help me lol.
>
> ![screenshot](https://user-images.githubusercontent.com/34972102/66964542-f62b8380-f044-11e9-95d5-0e5017718b7e.png)

Original issue filed here: https://github.com/mozilla/foundation.mozilla.org/issues/3792

**Comment by alexgibson** [comment]
We're looking at redesigning this page currently, but given the confusing nature of the current state, I think it makes sense to make a quick fix for this.
