### ISSUE TITLE
Add a link to choose a different language on /firefox/download/thanks/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8116]
## Description

There used to be a "Download in another language" link on /firefox/download/thanks/, but it looks like it was removed in a recent redesign. We should reinstate it to make selecting a different language easier.

### Steps to reproduce

1. Visit https://www.mozilla.org/firefox/ and click download.
2. Once https://www.mozilla.org/firefox/download/thanks/ loads try and select a different language to the one that was auto-downloaded.

### Expected result

There should be a "Download in another language" link on the page that links to /firefox/all/.

### Actual result

There is no link. The only way to get another language is to change the dropdown in the page footer, which is not easy to find.

### Environment

N/A

**Comment by Shivansh2407** [comment]
Where can it be found ? Would like to help in this issue...
