### ISSUE TITLE
Remove duplicate logo on /firefox/accounts

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8118]
## Description

There is a logo duplicate on /firefox/accounts, we should remove the one above the headline.
![image](https://user-images.githubusercontent.com/30483988/68611777-c5861080-046f-11ea-9e25-69686e3ee369.png)

We should remove the logo background property on `.c-accounts-hero-title` in [`firefox/accounts-2019.scss`](https://github.com/mozilla/bedrock/blob/master/media/css/firefox/accounts-2019.scss#L28-L29)

**Comment by imskr** [comment]
I would like to take this issue!

**Comment by amychurchwell** [comment]
@imskr okay, I will assign you this bug.
