### ISSUE TITLE
Moments page - welcome/4/ - Analytics plan/validation

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8132]
Noting campaign value set to:  welcome-4-mobile

**Comment by sghoseWI** [comment]
<button class="js-modal-link mzp-c-button mzp-t-product" data-cta-position="primary" data-cta-type="button" data-cta-text="Get the Firefox App">

<a href="https://support.mozilla.org/kb/firefox-browser-welcome-pages/?utm_source=mozilla.org-firefox-welcome-4&amp;utm_medium=referral&amp;utm_campaign=welcome-4-mobile&amp;entrypoint=mozilla.org-firefox-welcome-4">Why am I seeing this?</a>
