### ISSUE TITLE
Mobile CTA - Moments page - welcome/4/ - CODE

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8134]
**Epic:** #8127

[Master project doc](https://docs.google.com/document/d/1kDxf9ATASBwh5oMGT-I4iV7VDHmttyZRSIN7CU6VNYQ/)

- [x] [Design](https://github.com/mozilla/bedrock/issues/8133#issuecomment-554043869)
- [x] [Analytics ](https://github.com/mozilla/bedrock/issues/8132)
- [x] [Final Copy](https://docs.google.com/document/d/1yZPqkElk3ZqLBqQsSbdjw0mvw17s5kzmvs4MLuMRfS8/edit#)

**Comment by amychurchwell** [comment]
QR Code as fallback for locales `send_to_device` is not available in:
https://github.com/mozilla/bedrock/issues/8040#issuecomment-547530892

**Comment by ejregithub** [comment]
@amychurchwell - can you please apply a size estimate to your work here?
