### ISSUE TITLE
/privacy should use the Metropolis font for headlines 

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#8135]
[/privacy](https://www.mozilla.org/en-US/firefox/privacy/) should use the Metropolis font for headlines 

![Screenshot_2019-11-12 Firefox Privacy Promise](https://user-images.githubusercontent.com/3740746/68723278-fa2bc200-056c-11ea-9fa3-28b989bbf8ee.png)

**Comment by craigcook** [comment]
This was meant to be fixed in #7965 but it looks like we need a space on [this line](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/privacy/index.html#L20). Without that space the output is `mzp-t-firefoxprivacy-promise` so the theme font isn't applying.

**Comment by dzingeek** [comment]
ah thanks, @craigcook I still have a hard time searching for things properly in github. Since this is a duplicat I am going to close this one.

**Comment by craigcook** [comment]
It's a valid bug report. The previous fix didn't fix it, but now there's a new fix to hopefully fix it good and proper 😺
