### ISSUE TITLE
Lockwise page contains hard coded string for l10n

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#8142]
## Description
https://www.mozilla.org/firefox/lockwise/ - change the locale page to de, fr, or it, you will notice the `Open in Firefox` is hard coded. 

Describe the issue that you're seeing.

CTA button `Open in Firefox` is not extracted for localization.
 
### Expected result

Make CTA button `Open in Firefox` localizable

**Comment by peiying2** [comment]
@Errolyn this is the page you prepared for l10n. Not sure if the content was changed later but not followed up with l10n. This needs to be fixed.

**Comment by alexgibson** [comment]
I think this may be a duplicate of https://github.com/mozilla/bedrock/issues/8097

**Comment by peiying2** [comment]
Thanks for point it out. Close this issue.
