### ISSUE TITLE
Create generic FxA product button python helper

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8143]
## Description

`Mozilla.FxaProductButton` is used with the `monitor_button` macro. As we create more product buttons (monitor, pocket, .etc.) that use FxA metrics flow requests, it no longer makes sense for these buttons to be macros.

We should create a python helper that has product link generation functionality (`monitor.firefox.com`, `getpocket.com`, .etc.) with accompanying unit tests.

**Comment by alexgibson** [comment]
I'm already working on this in https://github.com/mozilla/bedrock/issues/8059

**Comment by amychurchwell** [comment]
@alexgibson okay, sounds good. It's not clear by that issue's title that this specific work would happen, feel free to close this if redundant. 🙂

**Comment by alexgibson** [comment]
I think we can chalk up part of making this button code work across products like Pocket and Monitor is some refactoring work. I’ll add making it a Python helper as a task in the other issue. Thanks!
