### ISSUE TITLE
Link to gitlab pipeline in #www-notify on Mozilla slack at beginning

### ISSUE THREAD

**Issue by jgmize** [mozilla/bedrock#8144]
## Description

We currently get notified (for [example](https://mozilla.slack.com/archives/CBX0KH5GA/p1573673454011200)) at the end of a pipeline, but would like to get a notification when the pipeline starts (potentially at each stage of the pipeline) similar to the existing Jenkins pipelines.

**Comment by maureenlholland** [comment]
closing as we're moving away from GitLab: https://github.com/mozilla/bedrock/issues/12820
