### ISSUE TITLE
/firefox/election page does not redirect trailing slash

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8160]
## Description

The /firefox/election/ page is available at 2 URLs:

https://www.mozilla.org/en-US/firefox/election
https://www.mozilla.org/en-US/firefox/election/

### Steps to reproduce

Visit https://www.mozilla.org/en-US/firefox/election

### Expected result

It should redirect to https://www.mozilla.org/en-US/firefox/election/

### Actual result

The page is rendered without the trailing slash, instead of redirecting.

### Environment

N/A

**Comment by Shivansh2407** [comment]
Working on it
