### ISSUE TITLE
URL params to Monitor seem to come in double-encoded?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/bedrock#8163]
## Description

URL params to Monitor seem to come in double-encoded?

### Steps to reproduce

Look at Monitor's GA report for traffic sources.

### Expected result

In GA, should see the traffic as `Referral` medium with Source of `firefox-home`.

### Actual result

<img width="696" alt="image" src="https://user-images.githubusercontent.com/71928/68958923-b1ede900-0792-11ea-8928-578acb8d9cbc.png">

### Environment

What browser and operating system are you using?

**Comment by alexgibson** [comment]
Thanks for the report, Luke!

Looks like this may be the cause: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/home/index-master.html#L39

**Comment by Shivansh2407** [comment]
Can I fix this file @alexgibson Sir?

**Comment by alexgibson** [comment]
@Shivansh2407 please go ahead, thanks!

**Comment by alexgibson** [comment]
Picking this up so we can get it fixed.
