### ISSUE TITLE
Convert Monitor buttons to new FxA product button Python helper.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8167]
## Description

The work done in #8154 added a dedicated [Python helper for creating FxA product buttons.](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templatetags/misc.py#L723-L742) 

We should convert the Monitor buttons to use the new helper.

Same task for Sync buttons: #8185

---
#### Tasks
- [x] Convert Monitor buttons (`monitor_button`) to the new Python helper.
- [x] Write tests.

**Comment by alexgibson** [comment]
Note: I think we should probably do this as two separate pull requests to help keep scope & review small.

**Comment by amychurchwell** [comment]
@alexgibson Agreed! I broke up the work into two issues. (https://github.com/mozilla/bedrock/issues/8185)
