### ISSUE TITLE
`mobile-protocol.scss` to use protocol color tokens.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8170]
## Description

`mobile-protocol.scss` has defined it's own [color variables](https://github.com/mozilla/bedrock/blob/master/media/css/firefox/mobile-protocol.scss#L18-L22):
```
$fx-body: #42425A;
$fx-blue: #0A84FF;
$fx-pink: #FF2889;
$fx-purple: #20123A;
$fx-yellow: #FFE55B;
```
we should replace these with [protocol colors](https://protocol.mozilla.org/fundamentals/color.html). 

- `$fx-body` is a dupe of `$color-gray-80`
- `$fx-purple` is a dupe of `$color-off-black`

**Comment by Shivansh2407** [comment]
So basically We should write like $color-gray-80 instead of $fx-body: #42425A; or anything else?

**Comment by amychurchwell** [comment]
@Shivansh2407 yes, we should delete these custom variables and replace them with the protocol tokens. The other colors aren't the exact value but very close to what we already have.

`$fx-pink: #FF2889;` could be replaced with `$color-pink-50`, for example.

[protocol color docs](https://protocol.mozilla.org/fundamentals/color.html)

Want me to assign you this bug?

**Comment by Shivansh2407** [comment]
Yes assign it to me.

**Comment by amychurchwell** [comment]
@Shivansh2407 a PR for this issue has been opened, going to unassign you from this issue. Thanks again for your continued interest in bedrock!

**Comment by tikhsuP** [comment]
@amychurchwell, I found this issue interesting so I gave it a try, please review.
Do tell me if any changes are needed.
Thankyou.
