### ISSUE TITLE
Redirect /desktop to /new

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8174]
## Description

Currently /firefox/desktop/ is redirected to /firefox/ but with the change of this page the better destination is /new as this page is all about the desktop browser and /firefox isnt anymore. Several of our subdomains and external pages are still linking to /desktop/

If I see this right in https://github.com/mozilla/bedrock/issues/4963 there have been some subpages, which should be redirected as well to /new

**Comment by PrachiSarda** [comment]
If no one is working on it, can I take this up?

**Comment by vansh37** [comment]
Hi @rraue , to be clear /firefox/desktop should be redirected to /firefox/new right ?
