### ISSUE TITLE
Experiment: "Download" in de

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8188]
## Description

We want to test whether "Download" works as well or better for German audiences. We can use Convert to create this experiment.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment plan built
- [x] Experiment built 
- [x] Experiment reviewed and deployed on prod
- [x] Traffic going to experiment 
- [x] Experiment report complete

**Comment by hoosteeno** [comment]
Experiment plan here: https://docs.google.com/document/d/1OjLWbTfsK8scIDochAnBsU_kwwC4yF1S-u1CyotL1RM/edit

**Comment by hoosteeno** [comment]
Experiment built here: https://app.convert.com/#/projects/1003343/summary/10032269

**Comment by hoosteeno** [comment]
@rraue can you review?

@alexgibson can you review?

**Comment by alexgibson** [comment]
> @alexgibson can you review?

I tested the experiment on staging and it works as expected. I've approved it to run in production (adding the prod URL). One open question: does this experiment need an A/A variation? This seemed to be something you wanted in the previous test.

Finally, I'll need to enable a redirect for /de/firefox/new/. What % of traffic would you like this to be?

Thanks

**Comment by hoosteeno** [comment]
> > @alexgibson can you review?
> 
> One open question: does this experiment need an A/A variation? This seemed to be something you wanted in the previous test.

After watching the A/A on the prior test (our first), I don't think it's a strict requirement. Thanks for asking. 

> 
> Finally, I'll need to enable a redirect for /de/firefox/new/. What % of traffic would you like this to be?

I've asked @sghoseWI to fill that out in the plan. I suspect the number is roughly 3% per variation, which would mean 6% overall.

**Comment by rraue** [comment]
> @rraue can you review?

Anika and I reviewed and it looks like intended

**Comment by hoosteeno** [comment]
@alexgibson from the plan:

> As a result, we estimate that each of the 2 groups (including the control) will need 7% of total traffic.

**Comment by alexgibson** [comment]
Pull request to redirect 7% of traffic from /de/firefox/new/

https://github.com/mozmeao/www-workers/pull/5

**Comment by alexgibson** [comment]
I have the redirector running on stage https://www.allizom.org/de/exp/firefox/new/

I'll wait for a review from Josh before turning it on in prod later today.

**Comment by hoosteeno** [comment]
@alexgibson Since both variations need 7%, we should redirect 14%.

**Comment by alexgibson** [comment]
This experiment is now running in production

**Comment by alexgibson** [comment]
I've ended this experiment in Convert. Preliminary results:

- Original Page: conversion rate 78.48% ± 0.60%
- "Download" variation: conversion rate 78.43% ± 0.60%

**Comment by sghoseWI** [comment]
Experiment Report: https://docs.google.com/document/d/1mZU0KDdCBwGx6V61--zCi9n_Co_CX6y5zuAtF5Gm7fE/edit#
