### ISSUE TITLE
[12/5] Remove EOY Fundraising banner

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8191]
## Description

Take en, fr and de copy from MoFo; integrate into fundraising banner; switch on for DE , EN, FR on the homepage only during 2 periods:

Nov. 27- Dec. 4 for Giving Tuesday
Dec. 24 - Jan 1 for EOY

May need integration with other banners we may build at the same time.

[Copy](https://docs.google.com/document/d/1VQwpJKfBBFZnNzYtme4XxxuSX1CbMp4mDQ4BOvrSEhM/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Banner is removed on 12/5

#### Tasks
- [x] Turn off switch on 12/5

**Comment by craigcook** [comment]
Done in https://github.com/mozmeao/www-config/pull/253
