### ISSUE TITLE
EOY fundraising banner on homepage

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8194]
## Description

Take en, fr and de copy from MoFo; integrate into fundraising banner; switch on for DE , EN, FR on the homepage only during 2 periods:

Nov. 27- Dec. 4 for Giving Tuesday
Dec. 24 - Jan 1 for EOY

May need integration with other banners we may build at the same time.

[Copy](https://docs.google.com/document/d/1VQwpJKfBBFZnNzYtme4XxxuSX1CbMp4mDQ4BOvrSEhM/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live during listing dates

#### Tasks
- [ ] Add FR and DE copy for banners shown to those locales

**Comment by hoosteeno** [comment]
@ejregithub is this done?
