### ISSUE TITLE
(12/3 - 5:15am PT) FPN - Update Term and Privacy pages - take live

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8197]
## Description

This issue is for the work required to take the updated FPN 'terms' and 'privacy' pages live on the launch date. The content updates were done in #7850 and the PR in the private repo is https://github.com/mozilla/bedrock-private/pull/81

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are live around 5:15am PT on Tuesday, December 3rd

#### Tasks
- [x] Import content from private repo to bedrock, merge and push

**Comment by ejregithub** [comment]
@alexgibson -here's the card to take the updated terms and privacy page for FPN live on the appointed date of 12/3

**Comment by alexgibson** [comment]
I've deployed this sucessfully to stage and all looks good. Will update once it's time to go to prod.

**Comment by alexgibson** [comment]
Pages are live:

https://www.mozilla.org/en-US/privacy/firefox-private-network/
https://www.mozilla.org/en-US/about/legal/terms/firefox-private-network/
