### ISSUE TITLE
Build a sync-optional FxA signup flow

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8198]
## Description

Versions of Firefox >=71 can use a sync-optional signup flow. The sync-optional flow allows people to choose whether to sign in their current browser to sync when they sign in/up for FxA. 

We should make sure our macros are ready for this flow. 

The flow is enabled by removing `service=sync` from the parameters on FxA links, but that will only work on Fx71+, so it has to be conditional.

Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1595829 for context.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] A Fx Sync sign in flow (whether email first or button first) can send users on Fx 71+ into a sync-optional flow.

**Comment by hoosteeno** [comment]
When this code lands we should integrate with wnp71.

**Comment by amychurchwell** [comment]
PR #8219 makes the `service_type` parameter on `fxa_link_fragment`/`fxa_cta_link` optional and updates wnp71 accordingly. We should leave this issue open to coordinate site-wide changes, including addressing the email-first form.

**Comment by hoosteeno** [comment]
A dupe of https://github.com/mozilla/bedrock/issues/8201
