### ISSUE TITLE
Update UITour to take advantage of new capabilities

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8200]
## Description

The UITour API in Firefox has been improved ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1548404)). Implementers can now learn what FxA services a particular client has authorized. This will be helpful for marketing segmentation. We should update our UITour library to use these new features.

Important: These new capabilities will be present in Firefox 72+. Our work on the UITour library should anticipate that
* older versions of the browser will continue requesting pages our website that implement UITour
* newer versions of the browser can be segmented more finely

Considering these factors, we should implement these changes so they don't break -- and so that implementing webpages can understand and continue to show valid content -- in the event that the API is not present in a particular requester's UA.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] UITour library uses the new features
- [ ] A demo of them in use is available
- [x] Bedrock documentation is updated to describe them

**Comment by alexgibson** [comment]
Note that documentation is already being updated here: https://github.com/mozilla/bedrock/pull/8158

**Comment by alexgibson** [comment]
Adding a blocker on the outcome of https://bugzilla.mozilla.org/show_bug.cgi?id=1601662

**Comment by alexgibson** [comment]
This is now unblocked in Nightly
