### ISSUE TITLE
Build analytics plan & validate analytics implementation: /new SEO update

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8203]
We will rebuild for SEO reasons /new. Top part of the page will stay the same, but below the fold we will add more content including links to other products. We need to specify how we'll measure it and then test the implementation to be sure it is sending the right data.

Brief: https://docs.google.com/document/d/1pFdPpjwalN74B0_HD5zem2P_51AvFlu4SJiOwS-v5u4/edit?ts=5dd56592

- [ ] Risk plan (when do we roll back)
- [ ]  Analytics needs for links and secondary ctas
- [ ] Three month measurment plan against forecast 
- [ ] Keyword monitoring plan

**Comment by sghoseWI** [comment]
https://docs.google.com/document/d/1cKw1Z7TddHYglhN6lr1CpQwa5BXF9krCaLRbrfeLAYs/edit

**Comment by rraue** [comment]
Done, the new /new page is a great success.
