### ISSUE TITLE
COPY - Browser Comparison SEO Overview page: Compare Web Browsers

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8205]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Original brief](https://docs.google.com/document/d/1TRJO1g9ZT6CBR94iApXOfkAcq_54G8aoLu_PYxC2tX4/edit#)

[Updated, SEO specific brief](https://docs.google.com/document/d/1BkZL_29Qx9rhf1_foCYMD8kju4bHdaGhpv2PcXvPImo/edit)

[EN COPY]()

***Tasks***
- [ ] Write [en copy for the page](https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit?usp=sharing)
- [x] Get Legal signoff on copy

**Comment by rantley** [comment]
@rraue    Revised version of the backtranslated version, keeping length, revisions to help readability and usability. 

https://docs.google.com/document/d/1TuoOyRT0CSV83Dog5zqQ39rIcfMSQxtQpA5im2aZmF8/edit?usp=sharing

**Comment by rraue** [comment]
Reviewed

**Comment by rantley** [comment]
@ejregithub This has been reviewed by Raph, Guy and Natalie. We're good to move forward.

https://docs.google.com/document/d/1TuoOyRT0CSV83Dog5zqQ39rIcfMSQxtQpA5im2aZmF8/edit?usp=sharing

**Comment by ejregithub** [comment]
@sgarrity - while @cgonz0 is working to float the copy into design, I've given you access to the copy doc in the comment above, which is final barring and concerns Cristina may raise over layout.

**Comment by ejregithub** [comment]
Copy is final, closing this issue
