### ISSUE TITLE
Research: pulling "what's new" snippet into websites

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8209]
## Description

For future developement I would like to know if its possible and what would be the scope to pull in data like these snippets form releasenotes and/or the in-product snippet into /new or WNP or /firefox:

Releasenotes
<img width="1255" alt="Screenshot 2019-06-06 at 16 59 51" src="https://user-images.githubusercontent.com/36700618/69433081-357f7b00-0d3b-11ea-87ad-5dd3e54c22b3.png">

Whatsnew in the browser:
![whatsnew](https://user-images.githubusercontent.com/36700618/69433266-95762180-0d3b-11ea-9f73-3125947f0970.png)

I would like to determine:

- [ ] Is it possible

- [ ] Is it possible in a way that especially /new is absolutly safe

- [ ] Is it possible to expose the parsed strings for translation into l10n

**Comment by alexgibson** [comment]
As discussed, I'm sure it would be possible to pull in a snippet from the latest releasenotes, but we might not have something that can do this readily available. Maybe @pmac can help advise here?

As for the whatsnew panel that's in-product, we'd need to do some reasearch and possibly contact the product team about where that data comes from. An initial search suggests those strings are baked [in-product using their Fluent l10n system](https://searchfox.org/mozilla-central/source/browser/components/newtab/locales-src/asrouter.ftl#96), so it may not be data currently available via an API. We'd need to confirm here.

As for translating such strings, as far as the releasenotes go they are in English only. Given how frequently they change, I don't think this makes sense to put into pontoon. We could do a special release notes 'snippet' for the top tier languages perhaps, but someone in marketing would probably need to be responsible for translating the content.

**Comment by k88hudson** [comment]
Hey friends, what's new panel works with the Standard Message Format under the Firefox Messaging System, and definitions for these messages are shipped to the browser via Remote Settings. The messages are pretty much just raw JSON. Here's an example in local test provider: https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/PanelTestProvider.jsm#103

Feel free to reach out to me or the team in #fx-messaging-system on slack if you need to know more!

**Comment by k88hudson** [comment]
(sorry for the drive-by)

**Comment by alexgibson** [comment]
Thanks @k88hudson - this is really useful info 👍

**Comment by pmac** [comment]
If those messages are publically available as JSON somewhere we could definitely pull in that data and use it. Release notes data comes in the form of data files in the [release notes repo](https://github.com/mozilla/release-notes/), which is populated from data entered into nucleus.mozilla.org.

The exact line you highlighted from the 67.0.1 release is here:

https://github.com/mozilla/release-notes/blob/14b1c2c37a7516a9fff710e0bcf301c9326bfeec/releases/firefox-67.0.1-release.json#L54

These data are already in the database and could be used on the WNP, but are only available in English.

**Comment by alexgibson** [comment]
I'm going to close this issue, since (afaik), the content outlined above is no longer needed for this page in question. Feel free to reopen if that's not the case though.
