### ISSUE TITLE
Dev Edition website: add a new Inactive CSS section, remove Shapes section

### ISSUE THREAD

**Issue by violasong** [mozilla/bedrock#8211]
## Description

In [this issue](https://github.com/mdn/kuma/issues/6059), we've created a new DevEdition banner on MDN which will feature Inactive CSS. For continuity, we'd like to update the DevEdition website to also feature Inactive CSS.

I think we should remove the "Shapes Editor" section for this, and then add the Inactive CSS section as the new top-left feature.

The banner on MDN will go live on Tuesday. It's okay (and totally understandable) if this can't go live that soon, but soon-ish would be great! Please let me know if you have any questions.

## Mockup

<img width="569" alt="image" src="https://user-images.githubusercontent.com/55994/69468852-b8580400-0d42-11ea-9943-3ac1951af5d0.png">

## Copy

> New DevTools
> Inactive CSS
> 
> Firefox DevTools now grays out CSS declarations that don’t have an effect on the page. When you hover over the info icon, you’ll see a useful message about why the CSS is not being applied, including a hint about how to fix the problem.
> 
> Learn more

Learn more link should point to:  https://hacks.mozilla.org/2019/10/firefox-70-a-bountiful-release-for-all/#developertools

## Assets
[inactivecssscreenshot.png.zip](https://github.com/mozilla/bedrock/files/3881935/inactivecssscreenshot.png.zip)

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Inactive CSS section added
- [x] Shapes section removed

**Comment by violasong** [comment]
Additional info:

> How does this work relate to Mozilla’s success this year? 
It will directly grow Firefox Desktop MAU (Firefox Developer Edition).

> How will you measure the success of this work? 
My team will use numbers from Google Analytics.

**Comment by alexgibson** [comment]
L10n PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/355

**Comment by violasong** [comment]
Looks great :) thanks so much!
