### ISSUE TITLE
Update leadership page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8216]
Specifically, Mitchell's bio. There are no hyperlinks in the new content.

Replace this content:

She has written for the Atlantic, Quartz, CNN.com and Les Annales Des Mines and appeared on NBC’s “Meet the Press”, BBC’s “HardTalk”, CNN’s “Global Office”, NBC’s “Weekend Today”, France 24, the UK’s Channel 4 and NPR’s “Morning Edition". She has spoken at high-level events like Tech for Good, VivaTech, Wired NextFest, World Economic Forum, Mobile World Congress, Web Summit, Collision and Singularity University.

With this content:

She has written for Scientific American, the Atlantic, Quartz, CNN.com and Les Annales Des Mines and appeared on NBC’s “Meet the Press”, BBC’s “HardTalk” and "CEO Secrets", CNN’s “Global Office”, NBC’s “Weekend Today”, CNBC's "Squawk Box", Cheddar TV, France 24, the UK’s Channel 4 and NPR’s “Morning Edition". She has spoken at high-level events like Tech for Good, VivaTech, Wired NextFest, World Economic Forum, Mobile World Congress, Web Summit, Collision, AI@Oxford, Bloomberg's "Sooner Than You Think", SXSW Edu, EL PAÍS Retina, RSA and Singularity University.

**Comment by Shivansh2407** [comment]
Please Check this @ejregithub

**Comment by ejregithub** [comment]
Thanks @ Shivansh2407 - I've asked Errolyn to review your pull request.
