### ISSUE TITLE
Success message displayed above page headline on newsletter/recovery/

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8217]
## Description

After submitting an email address for email subscription management on [newsletter/recovery/](https://www.mozilla.org/newsletter/recovery/), the page headline appears underneath the success message.

We should either remove the page headline after a successful submission or keep it placed above.

![Screenshot_2019-11-25 Newsletter email recovery](https://user-images.githubusercontent.com/30483988/69581894-3b1fcf80-0f8c-11ea-85cb-ee05f1770fbd.png)

**Comment by YuriyCherniy** [comment]
I have done some changes in this PR #8235 and it seems work properly.
