### ISSUE TITLE
Links to 2017 and 2018 public records (990, audited financial statements) missing

### ISSUE THREAD

**Issue by tbm** [mozilla/bedrock#8233]
https://foundation.mozilla.org/en/about/public-records/ is missing links to the 2017 and 2018 public records:

2017:

* Annual report: https://www.mozilla.org/en-US/foundation/annualreport/2017/
* 990:  https://assets.mozilla.net/annualreport/2017/mozilla-2017-form-990.pdf
* Audited financial statements: https://assets.mozilla.net/annualreport/2017/mozilla-fdn-2017-fs-short-form-final-0927.pdf

2018:

* Annual report: https://www.mozilla.org/en-US/foundation/annualreport/2018/
* 990: https://assets.mozilla.net/annualreport/2018/mozilla-2018-form-990.pdf
* Audited financial statements: https://assets.mozilla.net/annualreport/2018/mozilla-fdn-2018-short-form-final-0926.pdf

**Comment by alexgibson** [comment]
@tbm I think this issue may belong to https://github.com/mozilla/foundation.mozilla.org

**Comment by tbm** [comment]
I think you're right given this:

commit d2fb9525b8806edf00635adbc90cfe8ba97e7091
Author: Alex Gibson <alexgibson@users.noreply.github.com>
Date:   Tue Nov 20 09:29:30 2018 +0000

    Remove old /foundation page templates (#6467)

I don't actually see the code in https://github.com/mozilla/foundation.mozilla.org though, but I guess I should report it there.
