### ISSUE TITLE
Fix Learn more link for Next-Gen CSS Engine section

### ISSUE THREAD

**Issue by swarnava** [mozilla/bedrock#8241]
### Steps to reproduce

Visit https://www.mozilla.org/en-US/firefox/72.0a2/whatsnew/india/?oldversion=71.0

Click on **Learn More** under **Next-Gen CSS Engine section**

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/1162991/70065539-4ec4d900-1611-11ea-9984-9906c5f284c7.png">

### Expected result

It should navigate like this https://www.mozilla.org/en-US/firefox/72.0a2/whatsnew/india/?oldversion=71.0#for-devs

### Actual result

It's going to https://www.mozilla.org/en-US/firefox/72.0a2/whatsnew/india/?oldversion=71.0#nextgen which isn't navigating anywhere.

**Comment by alexgibson** [comment]
Thanks for the report!
