### ISSUE TITLE
mobile page CTA update - button

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8250]
## Description

We need to remove the copy CTA "Get Firefox Mobile" and phone image, replacing that copy in a big blue button and putting that button above the badges - see the attached image for reference.

**Comment by ejregithub** [comment]
![Screen Shot 2019-12-04 at 7 57 57 AM](https://user-images.githubusercontent.com/20547886/70166408-8b2c1f80-1679-11ea-84a2-2971435bfa7c.png)

**Comment by alexgibson** [comment]
@hoosteeno @sghoseWI please note I'm standardizing the data attributes we use here, as per [our docs](https://bedrock.readthedocs.io/en/latest/analytics.html):

```
data-cta-type="button" 
data-cta-text="Get Firefox Mobile" 
data-position="primary|secondary"
```
