### ISSUE TITLE
For signed in, 0-mobile-device users, replace global nav CTA

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8251]
## Description

We should modify the global nav CTA to pitch Firefox Mobile to Firefox users who are signed in, but don't have any mobile devices set up. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Firefox users signed in with 0 mobile devices see a new CTA
- [ ] Clicking the CTA links to the mobile page
- [ ] The link is instrumented to count click events

**Comment by maureenlholland** [comment]
Closing as outdated. The Global nav CTA is now for VPN
