### ISSUE TITLE
Code - Lockwise CTA - Moments page - Welcome/5/ 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8263]
See epic - https://github.com/mozilla/bedrock/issues/8157

Note the slug for the send-to-device widget is "lockwise-welcome-download"

**Comment by craigcook** [comment]
On demo: https://www-demo4.allizom.org/firefox/welcome/5/

**Comment by ejregithub** [comment]
@craigcook - can you please add the word 'of' in Then use Firefox Lockwise to safely access your passwords across all your apps, on **of** all your devices. In the hero subhead.

**Comment by craigcook** [comment]
> @craigcook - can you please add the word 'of' in Then use Firefox Lockwise to safely access your passwords across all your apps, on **of** all your devices. In the hero subhead.

That's not what appears in the copy deck, which was signed off as final. We've just pushed the strings to Pontoon. We can make this change if it's **_really_** important, but this is a copy change after copy was said to be final. I think it still reads fine without it.

**Comment by ejregithub** [comment]
@craigcook - Yeah, Lindsey just saw it and asked for it . . .  Pretty please.

**Comment by craigcook** [comment]
The of has been added.
