### ISSUE TITLE
Design - Lockwise CTA - Moments page - Welcome/5/ 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8264]

**Comment by cgonz0** [comment]
![Momentsv5_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/742fbbcd-2f6e-4df0-a17f-d7129f80c170)

**Comment by ejregithub** [comment]
Nice, @cgonz0. Is this considered ready for stakeholder review?

**Comment by cgonz0** [comment]
@ejregithub yes, this approved on the design side.

**Comment by cgonz0** [comment]
@craigcook 
Updated mock w/ final copy
___
![Momentsv5_mockup_finalcopy.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/a04e18b7-2f7a-4adb-a793-935cddbc2412)


Assets
___
![momentsv5_icon1.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/19b080aa-c79f-4d32-a718-154ffc10369d)
![momentsv5_icon2.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/9e28a730-3a5e-4549-a56e-c861592ca346)
![momentsv5_icon3.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/6387362c-8899-458c-a46f-7a8fa8fbaa64)
