### ISSUE TITLE
Analytics/Measurements - Lockwise CTA - Moments page - Welcome/5/ 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8265]

**Comment by ejregithub** [comment]
Adjust links

Network | Campaign | Ad Group | Creative |  
-- | -- | -- | -- | --
Product Marketing | S2D | Email |   | https://bhqf.adj.st/?adjust_t=mclvdo7&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise
Product Marketing | S2D | SMS |   | https://bhqf.adj.st/?adjust_t=plpx8dk&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise
Product Marketing | S2D | QR |   | https://bhqf.adj.st/?adjust_t=n7gkx2p&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise

**Comment by hoosteeno** [comment]
@ejregithub can you add more detail to this card to explain what needs done? This is coming up quickly.

**Comment by alexgibson** [comment]
This page is in production https://www.mozilla.org/en-US/firefox/welcome/5/
