### ISSUE TITLE
Build a landing page for SMS referrals

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8266]
## Description

We should build a bare-bones SMS interface, identical to the SMS modal, that we can direct users to. It would resemble the (sync-signed-in) page at https://accounts.firefox.com/sms.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Interface is up at a URL such as www.mozilla.org/firefox/mobile/get-app/
- [x] Interface is localized in en-US only
- [x] Interface works exactly as the modal works, except with no opening and no closing
- [ ] **Interface is launched, online, tested by 2019-12-13**

**Comment by stephaniehobson** [comment]
+1, I was just thinking it would be great to have a page like this to fall back to if the user has JS disabled.

**Comment by stephaniehobson** [comment]
Oh, but I guess it still needs an email fallback state if the user is outside of a SMS area.

**Comment by ejregithub** [comment]
@alexgibson - do you think you could take this one on - noting the success criterion of "launched, online, tested by 2019-12-13" - @stephaniehobson - could I ask you to allocate time to do the code review for this?

**Comment by alexgibson** [comment]
I have some questions:

1.) SMS is only available in certain countries, else the form falls back to email only. Are we sure we want to call the page mobile/sms?
2.) There is no proposed design or copy in the issue. Is the ask just to make something up?
3.) For locales who don’t have these newsletters/messages localized, what is the proposed fallback, QR Code?

**Comment by alexgibson** [comment]
To be clear:

I'm happy just to run with the above and work things out. I just want to make sure I'm not missing anything here (like designs or copy, or more detail), to save confusion.

**Comment by hoosteeno** [comment]
> I have some questions:
> 
> 1.) SMS is only available in certain countries, else the form falls back to email only. Are we sure we want to call the page mobile/sms?

How about `mobile/get-mobile/` ? 

> 2.) There is no proposed design or copy in the issue. Is the ask just to make something up?

We can copy the widget from /mobile entirely, and put in the center of the page on a white background:

![Screen Shot 2019-12-09 at 11 12 03 AM](https://user-images.githubusercontent.com/94519/70461801-b5654f00-1a76-11ea-898f-57e437ae5996.png)


> 3.) For locales who don’t have these newsletters/messages localized, what is the proposed fallback, QR Code?

Yes. Do we need to put together designs/copy/funnels for this?

**Comment by alexgibson** [comment]
> Yes. Do we need to put together designs/copy/funnels for this?

I'd say for now I can just put something together on demo. We'll get some light design feedback, and iterate from there.

Thanks for the extra info!

**Comment by alexgibson** [comment]
@hoosteeno this is now up on demo. I went for `/mobile/get-app/` which seems like another useful keyword (as opposed to repeating mobile again):

https://www-demo3.allizom.org/en-US/firefox/mobile/get-app/

Let me know if this looks OK or if we need any changes. Thanks

**Comment by ejregithub** [comment]
@amychurchwell - there's a very tight due date on this work (go live Friday, but QA needs to test sooner than that).  Can you please start code review, familiarizing yourself with the PR?
