### ISSUE TITLE
/new experiment - long content - Build spec/test plan

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8283]
***Tasks***
- [x] Create the spec/test plan for this a/b test of long from content in the /new page - @sghoseWI

**Comment by sghoseWI** [comment]
Test plan: https://docs.google.com/document/d/1cKw1Z7TddHYglhN6lr1CpQwa5BXF9krCaLRbrfeLAYs/edit

**Comment by ejregithub** [comment]
@rraue approved

**Comment by hoosteeno** [comment]
Approved.
