### ISSUE TITLE
/new test - long form content - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8285]
David Tenser's team is going to provide the required elements to launch a test on /new involving 'long content'

This card is for the coding (and code review) tasks for this experiment

***Tasks***
- [ ] code the content
- [ ] configure the experiment (Convert or TrafficCop)
- [ ] code review
- [ ] merge, push

**Comment by hoosteeno** [comment]
@alexgibson since you've been watching the nav on /new experiment, would you mind pitching your preferred approach to experiment segmentation here? I think Convert saves substantial time when it comes to connecting variations to measurements, but you were concerned about using it for redirects as we are on /nav. How do you think we should build this experiment?

**Comment by alexgibson** [comment]
@hoosteeno do we have an idea of what this new content looks like? That may help in deciding the best approach here.

**Comment by hoosteeno** [comment]
[Here is a work in progress](https://user-images.githubusercontent.com/94519/70657686-82a78c00-1c19-11ea-90fb-b5871562d005.jpg). It's not done; it's not ready for a lot of feedback. Included here only for estimation purposes.

**Comment by alexgibson** [comment]
Assuming ony the below the fold content is changing, i see three main options:

1. A developer codes this page (template available via a URL param), and then we do a redirect experiment in Convert (do-able, but makes review & QA fiddly as we have seen).
2. A developer codes this page, and then we do a traditional traffic cop A/B test (analysis config and reporting more complex).
3. A developer codes this page. We then take the HTML/CSS, and put that into a Convert variation (more dev effort, but the experiment setup becomes simpler).

Number 3 is something we haven't tried before, so it's a little hard to say how fiddly it may be. Saying that, it may be worth trying to find out (assuming we decide traffic cop isn't the way forward).

**Comment by hoosteeno** [comment]
Closing WONTFIX for now. Reopen if needed.
