### ISSUE TITLE
Firefox logo truncated on /mobile for some RTL languages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8293]
## Description

The Firefox logo on /firefox/mobile/ is truncated at medium screen widths for some RTL locales. This may be more prevalent for locales such as Arabic, which have larger line-heights by default.

### Steps to reproduce

1. Visit https://www-dev.allizom.org/ar/firefox/mobile/
2. Resize the browser window to around 960px.

### Expected result

The logo should not be truncated.

### Actual result

The logo is truncated. The wordmark is also blown up larger than the source file dimensions, so it appears a pixelated. This may be contributing to the truncation.

![image](https://user-images.githubusercontent.com/400117/70545481-8d084e00-1b65-11ea-9ca3-ef88f1502535.png)

### Environment

Any browser

**Comment by imrishabh18** [comment]
@alexgibson Hey, I want to work on this issue. Can you tell me how to get to that page of different language in my local machine ?

**Comment by alexgibson** [comment]
@imrishabh18 there's a link above where you can reproduct the issue.

When running locally, you may have to pull in localizations to get to the locale itself: https://bedrock.readthedocs.io/en/latest/l10n.html

**Comment by ForgottenProgramme** [comment]
Hey, @alexgibson ! Can I please try working on this issue if @imrishabh18  has dropped it?

**Comment by alexgibson** [comment]
@ForgottenProgramme feel free, pull requests are welcome. Thanks!

**Comment by ForgottenProgramme** [comment]
@alexgibson , please help me setting up the environment. 
I have windows 10 on my system. 
Tried installing WSL2, but failed because my system version doesn't meet the minimum requirements for WSL2.

**Comment by ForgottenProgramme** [comment]
@alexgibson 
Okay,  I tried setting up the environment myself. 
I followed the instructions given here:   https://bedrock.readthedocs.io/en/latest/install.html#make-it-run

But I am getting stuck here; 
![bedrock](https://user-images.githubusercontent.com/65779580/83058508-165cff80-a076-11ea-9f56-90f8df308e7d.png)

**Comment by mdieske** [comment]
Hi @alexgibson,
I would like to work on this issue if there is still help needed. I'm a Github newbie and this seems to be a good first bug for me.
