### ISSUE TITLE
Add "Other" to the email pref language drop down

### ISSUE THREAD

**Issue by brynneh** [mozilla/bedrock#8297]
We'd like to add "other" to the email preference page language drop down. This should *only* display for people who have "other" set as their language in SFDC and *not* as an option for people who already have one of the supported 9 languages chosen (i.e. we don't want someone switching from "DE" to "Other").

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by robhudson** [comment]
Since we are no longer using SFDC I'm closing this. If it's still a request feel free to re-open with a new spec.
