### ISSUE TITLE
(Code Review) Update design in WNP template for India (content in EN)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8300]
## Description

Originally done in #7552 - we need to maintain the same functionality while updating the content in the page. 

New content is [here](https://drive.google.com/drive/folders/1zJbfgledNRHT5pGCfAP9TvWfVouWUeDE?usp=sharing) - use the ' india final' .psd file 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live

#### Tasks
- [ ] Code Review
- [ ] Ensure functionality to show users in India this page w. EN content - from #6084

**Comment by hoosteeno** [comment]
We will work with a vendor on this code.

**Comment by ejregithub** [comment]
Technically this card, which is for code review, is blocked til the code in written, pr submitted

**Comment by hoosteeno** [comment]
Stella reviewed and approved this for launch (in my email).
