### ISSUE TITLE
(Code review) Update design in WNP template for Indonesia

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8302]
## Description

Update the content in the Indonesian WNP for 72, featuring Firefox Lite

New content is [here](https://drive.google.com/drive/folders/1zJbfgledNRHT5pGCfAP9TvWfVouWUeDE?usp=sharing) - use the ' indonesia final' .psd file 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live on 12/27

#### Tasks
- [ ] Update the content

**Comment by hoosteeno** [comment]
We plan to work with a vendor on this code.

**Comment by ejregithub** [comment]
Technically this card, which is for code review, is blocked til the code in written, pr submitted

**Comment by alexgibson** [comment]
Adding a blocker to this as I don't know who still needs to approve the page.

**Comment by hoosteeno** [comment]
Stella reviewed and approved this for launch (in my email).
