### ISSUE TITLE
Move the WNP notification contents into their own language file

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8305]
## Description

We may want to use WNP-style notification messages on different templates, but we can't now because they share the same language file as the main body of the page. 

We should create a language file for these that can standalone and be imported into other pages if needed.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Language file contents are moved into their own file
- [ ] Existing WNPs import that language file

**Comment by hoosteeno** [comment]
@Errolyn Thanks for the great suggestion. Feel free to pick this up in an upcoming sprint if you can.

**Comment by alexgibson** [comment]
We may want to consider that we're on the cusp of transitioning to a new L10n system at the end of the year. This would be a great thing to do as we start afresh with /whatsnew. I've split out the common strings into a separate Fluent file in this PR: https://github.com/mozilla/bedrock/pull/8213

**Comment by alexgibson** [comment]
The above is not to say we shouldn't also do this with .lang, but hopefully before too long we'll not be doing WNP using the old system ^

**Comment by hoosteeno** [comment]
We should block this issue on fluent pipeline completion, which is delayed. Adding blocked flag.

**Comment by alexgibson** [comment]
Fluent is now live, and this is done in https://github.com/mozilla/bedrock/blob/master/l10n/en/firefox/whatsnew/whatsnew.ftl
