### ISSUE TITLE
/new experiment with long-form content: Design

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8307]
## Description

We're designing an experiment for the /new page which includes a visual refresh (epic: https://github.com/mozilla/bedrock/issues/8035). This card is about the design work. @justinkropp, this is all yours.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Brand and Growth approved designs included here
- [ ] Developer reviewed/approved
- [ ] Product reviewed/approved

**Comment by justinkropp** [comment]
This experiment has been put on hold for 2019.

**Comment by hoosteeno** [comment]
Closing WONTFIX for now. Reopen if needed.
