### ISSUE TITLE
Remove adjust.com links

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8309]
Is it possible to avoid using adjust.com to link to our mobile products? It's on our [list of known trackers](https://github.com/disconnectme/disconnect-tracking-protection) used in Firefox tracking protection. I block that list on my network, and so none of the links work for me.

**Comment by alexgibson** [comment]
I think this is something we should give some serious consideration. Even though navigating to adjust links via mozorg still works like normal in the majority of cases (things like TP or ublock won't directly prevent navigation to a website), adjust is still classified as a known tracker. It can also, on some platforms, provide a pretty [surprising UX](https://bugzilla.mozilla.org/show_bug.cgi?id=1448153).

There was also talk recently of removing adjust on /mobile in favor of linking directly to the respective app stores, as this is (from what I understand) better for SEO.

Ultimately, this probably comes down to a joint decision from product/marketing. I believe the reason we use it is to measure attribution for installs of the mobile products. But as we see, it's not without some downsides.

I'd be interested in @hoosteeno's thoughts here.

**Comment by hoosteeno** [comment]
The adjust SDK is built into our mobile products[[1](https://firefox-source-docs.mozilla.org/mobile/android/adjust.html)]. Presently it is the only way we can know whether a marketing investment in mobile campaigns (e.g. building a new page on the website) turns into mobile installs. Interestingly, those docs say 

> Mozilla is using a third party framework in order to answer this question for the Firefox for Android 38.0.5 release. We hope to remove the framework from Fennec in the future.

I'll talk to adjust stakeholders.

**Comment by alexgibson** [comment]
From recent discussions on Slack it sounds like Adjust has been removed from both Firefox and Focus on iOS, due to recent changes in iOS14. For now, we're continuing to use it on Android.

With that in mind, and the [surprising UX](https://bugzilla.mozilla.org/show_bug.cgi?id=1448153) Adjust links can give to website visitors, we could now consider removing Adjust links from mozorg that target the iOS app store.

Searching the codebase, I can see at least 21 occurences of `firefox_adjust_url('ios'`: https://github.com/mozilla/bedrock/search?q=firefox_adjust_url&type=code

/cc @slightlyoffbeat @pmac

**Comment by kbrosnan** [comment]
[Adjust is back in Firefox-iOS](https://github.com/mozilla-mobile/firefox-ios/pull/9768) due to the need to understand impact of  install campaigns

**Comment by alexgibson** [comment]
When testing an upcoming /whatsnew page the EU team observed that uBlock Origin also attempts to block Adjust links:

![image](https://user-images.githubusercontent.com/400117/155504139-b590e0bd-a53b-43b8-a746-bc440a24e865.png)

**Comment by JohnVeness** [comment]
Hi, I came here to report a similar thing. The page https://www.mozilla.org/en-US/firefox/browsers/chromebook/ has a "Get it on Google Play" badge that, when clicked, shows that adjust.com is blocked by uBlock Origin. I seriously worried that mozilla.org had been hijacked at first!

**Comment by alexgibson** [comment]
Adjust links have now been removed in https://github.com/mozilla/bedrock/issues/11698

https://github.com/mozilla/bedrock/issues/14172 will follow up to remove them from QR Codes
