### ISSUE TITLE
Firefox Nightly logo is blurry on first run and what's new pages

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/bedrock#8310]
## Description

The Firefox Nightly icon used is an upscaled 128x128 png. It looks bad on the Firstrun and Whatsnew pages:

https://www.mozilla.org/fr/firefox/73.0a1/whatsnew/all/
https://www.mozilla.org/en-US/firefox/nightly/firstrun/

I would like that we use an SVG icon on these pages

Here is the current png:
![image](https://user-images.githubusercontent.com/454375/70720892-f8345a80-1cf4-11ea-8d2f-814e2466727b.png)

With an svg:
![image](https://user-images.githubusercontent.com/454375/70721009-30d43400-1cf5-11ea-94b4-e9559ba5da9f.png)

If people are busy, I would be happy to make the css + image patch, just tell me in which folder to store the image.

Thanks

**Comment by pascalchevrel** [comment]
@craigcook what do you think? ^

**Comment by alexgibson** [comment]
I don't think we need to add new assets to the repo for this as they are now sourced from Protocol directly. A more appropriately sized PNG may also be smaller than an SVG.

**Comment by alexgibson** [comment]
The two options are:

- Change `logo-lg-high-res.png` to `logo-xl-high-res.png`
- change `logo-lg-high-res.png` to `logo.svg`

Looking at the file size comparison, the SVG looks like it may be slightly smaller than a PNG at this size.

**Comment by imrishabh18** [comment]
Hey @alexgibson , should i take up this issue ?

**Comment by aman-earthian** [comment]
hey @pascalchevrel @alexgibson, can i work on the issue.

**Comment by wigzen** [comment]
@pascalchevrel sir i can fix this bug please  assign me this bug this is my first contribution

**Comment by wigzen** [comment]
my idea is replace logo  i already have logo with SVG format with high Quality resolution 300dpi

**Comment by alexgibson** [comment]
Contributions are always welcome. As per the comments above, there's no need to source or add a new logo here as we already have assets as a dependency in the repo. Changing the filenames to one of the options in [this comment](https://github.com/mozilla/bedrock/issues/8310#issuecomment-565974764) should work ok.

**Comment by alexgibson** [comment]
Actually, since this issue was filed it looks like both pages have since been redesigned / ported to Protocol. The logos don't look blurry when testing here, but feel free to re-open this issue if someone can still reproduce. Thanks
