### ISSUE TITLE
Extract strings for SEO browser comparison pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8319]
The browser comparison pages are ready for string extraction. There are 5. This card is about extracting strings for all of them.

### Success criteria

Strings are extracted for the following comparison pages..
- [x] Safari
- [x] Opera
- [x] Edge
- [x] IE
- [x] Chrome

**Comment by ejregithub** [comment]
Noting the go ahead (Raphael approved) to add new copy & links between each section and a download button at the bottom of the page.

**Comment by hoosteeno** [comment]
> Noting the go ahead (Raphael approved) to add new copy & links between each section and a download button at the bottom of the page.

@ejregithub is this another success criteria or change that needs a separate card?

**Comment by craigcook** [comment]
Strings PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/371
