### ISSUE TITLE
Design: new 404 and 500 pages

### ISSUE THREAD

**Issue by peterbe** [mozilla/bedrock#8329]
## Description

We should rewrite and redesign the 404 and 500 error pages on www.mozilla.org, then rebuild using our current coding standards. 

### Success Criteria 

- [ ] New designs and copy for 404 and 500 pages
- [ ] Copy and design are on brand
- [ ] Copy is clearer (see original report, below) about the page's purpose and the visitor's options: The title is descriptive, and the page includes a handful of links to help people get to common use cases.
- [ ] Built with Protocol components
- [ ] Community localized in Fluent (no vendors)

### Link ideas:

* Download the Firefox browser for your mobile device or desktop
* Explore the entire suite of Firefox products, which are fast 'n safe
* Learn about Mozilla, the non-profit behind Firefox
* Go to the home page

### Reviews:
- [x] Brand (copy and design)
- [x] Dev QA
- [x] Team Lead

------

## Original Report

I ended up on https://www.mozilla.org/en-US/firefox/xr/ ([from clicking a link like this](https://bugzilla.mozilla.org/show_bug.cgi?id=1604853))

<img width="1248" alt="Screen Shot 2019-12-18 at 12 48 33 PM" src="https://user-images.githubusercontent.com/26739/71110150-bf80ff00-2194-11ea-8c32-bd0735c717c5.png">

My impression was that this was some sort of marketing campaign. But it was cryptic. What's a "Whoops!"? Also, the attempt to be funny with "Did you make a left at that last URL instead of a right?" is funny but it's not working. It could work if I've immediately understood that it's a page-not-found page. 

Also the bullet point list is unfocussed in that I have no idea what those bullet points are trying to communicate (I know it's about getting you away from the not found page to the right page, but that's not clear and takes time to understand)

### Steps to reproduce

Go to https://www.mozilla.org/en-US/firefox/xr/ and imagine you don't know what a www.mozilla.org's page-not-found pages look like. 

### Expected result

A title like "Page not found". Or a sub-title like "The URL could not be found". 
Perhaps some graphic that gets the impression that something went wrong. 

### Actual result

See description.

**Comment by pmac** [comment]
I agree that this error could be better. I think this text is quite old and probably made more sense before the redesign. You have thoughts @alexgibson ?

**Comment by alexgibson** [comment]
Yeah, some of this copy is probably ~10 years old. Making a more informative 404 page would be nice and likely low effort, although I'm not sure where this fits in terms of current priorities.

/cc @hoosteeno

**Comment by hoosteeno** [comment]
Yeah, good call @peterbe. We can do this in Q1.

**Comment by hoosteeno** [comment]
I rewrote the description with some success criteria. I'm attaching a screenshot of the 500 page for reference.

 ![image (5).png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/f32b0b91-fd87-428a-8182-87f237edafbf)

**Comment by cgonz0** [comment]
notes:

- 2 copy versions for 404, plus 505 page

- specs in sketch link https://share.goabstract.com/a52afa2d-5257-4dee-931a-b3d19f2a324a?sha=a4ff41c3b1ebe805142bf4b3b731afecbcc6d578

- will update with assets

- optional: randomized link to "weird" content on the web  - a tie in to some firefox brand stuff that's being worked on (weird sh*t on the internet emails). this would need extra work to curate content and build - not expecting this to be part of this particular version. 



![404_505_mockups.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/08bc1a84-245e-4d71-8556-1aecb8978c5c)

**Comment by hoosteeno** [comment]
Thank you!

* The first 404 headline, "can't find", is better
* The second 404 body, "broken URLs happen", seems "truer" and is easier to localize.
* Let's leave out "Take me to a random" for now.

**Comment by amychurchwell** [comment]
Note to dev: the new joint logo asset should land in https://github.com/mozilla/protocol-assets/

![firefox_moz_co-brand_sm-high-res](https://user-images.githubusercontent.com/30483988/72104080-73326600-32df-11ea-832a-bba3da82ddba.png)
![firefox_moz_co-brand_sm](https://user-images.githubusercontent.com/30483988/72104085-74fc2980-32df-11ea-8967-2a26ea1613a7.png)

**Comment by amychurchwell** [comment]
Designs look great from dev perspective. (Cristina & I had a conversation this morning)
Only feedback is that the "download" link should link to /new. Does not trigger download.

**Comment by hoosteeno** [comment]
@cgonz0 can you turn [this comment](https://github.com/mozilla/bedrock/issues/8329#issuecomment-572656836) into a final draft for 404?

**Comment by cgonz0** [comment]
@hoosteeno done
Final Mocks 404/505 below


![404_update_mockups](https://user-images.githubusercontent.com/29640968/72108280-15eee280-32e8-11ea-9b5e-7e9127b3cbbe.png)

**Comment by hoosteeno** [comment]
Closing, follow #8407 for code.
