### ISSUE TITLE
The /firefox/accounts/ page doesn't mention Sync as a browser feature

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8334]
## Description

There are pathways from product sites that point to the /firefox/accounts/ page as a destination to learn more about Sync, however the page no longer mentions Sync as a benefit.

### Steps to reproduce

1. In a **non-signed-in, non-Firefox browser**, visit: https://accounts.firefox.com/
2. Click "Looking for Firefox Sync? **Get started here**"
3. Get redirected to https://www.mozilla.org/en-US/firefox/accounts/?utm_campaign=fx-signup&utm_content=fx-sync-get-started&utm_medium=fx-accounts&utm_source=fx-website

### Expected result

The /firefox/accounts/ page should explain what Sync is, and how to get started using it.

### Actual result

The page doesn't mention Sync at all.

### Environment

Non-Firefox browser.

**Comment by dzingeek** [comment]
Thanks @alexgibson I know there is talk of updating this page once we figure more out about "memberships" or what an account really means. I wonder though if sending users to this page makes sense in the future or should we think about other possible user journies? 

ie. browsers features page? or a section on the browsers page that talks about sync?

**Comment by alexgibson** [comment]
Yeah, we could get product to update their links to point to a more suitable target. I'm not sure if anything exists today though. the Sync section on https://www.mozilla.org/en-US/firefox/features/ also points to /accounts/.

**Comment by rraue** [comment]
I want to endorse this issue, as all traffic from Search around sync is landing on sumo but should go to the accounts page first. So we need to figure out how to get sync as a feature on this page, its the one thing users care most about, at least in search.

**Comment by dzingeek** [comment]
Let me talk to my team and see if we can get this on our roadmap..probably won't be until Q2. But I agree, this page needs an updated...not just to mention sync but also there isn't much there other than duplicated stuff that is on /firefox.
