### ISSUE TITLE
Cookies link in footer goes to closed accordion

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8354]
## Description

https://www.mozilla.org/en-US/privacy/websites/#cookies which is linked to from the site footer does not take the user to the cookie section of the privacy policy.

### Steps to reproduce

Go to mozilla.org and click on "cookies".

### Expected result

Link to the cookie portion of the websites privacy notice.

### Actual result

View of the footer on the privacy notice.

**Comment by Shivansh2407** [comment]
Can I please work on this issue ?

**Comment by Shivansh2407** [comment]
Can You please tell me which file I need to look for?

**Comment by mdieske** [comment]
Hi @stephaniehobson,
I would like to work on this issue. 
Just to make sure we talk about the same section of the website: It's the one with the heading "Things you should know", isn't it?
