### ISSUE TITLE
Legal section should use Mozilla theme

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8355]
## Description

The legal section is Mozilla legal stuff and should use the Mozilla theme.

### Steps to reproduce

https://www.mozilla.org/en-US/about/legal/

### Expected result

Headings should be in Zilla.

### Actual result

Headings in Inter.

**Comment by amychurchwell** [comment]
**TO-DO**

1. Add `{% block body_class %}{{ body_class }}{% endblock %}` to `bedrock/base/templates/base-article.html`

2. Add `{% block body_class %}mzp-t-mozilla{% endblock %}` to:
- `bedrock/legal/templates/legal/index.html`
-  `bedrock/legal/templates/legal/docs-base.html`
- `bedrock/legal/templates/legal/fraud-report.html`

**Comment by harshil1712** [comment]
Hey :wave: 
I would like to work on this issue.

**Comment by amychurchwell** [comment]
Hello @harshil1712 👋 
I will assign this issue to you.
