### ISSUE TITLE
Newsletter on firefox/channel/ pages should be inside emphasis box.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8357]
## Description

The newsletter on the [firefox/channel pages](https://www.mozilla.org/firefox/channel/) should be inside an [emphasis box.](https://protocol.mozilla.org/patterns/molecules/emphasis-box.html), similar to the design on [firefox/developer](https://www.mozilla.org/firefox/developer/).

![Screen Shot 2019-12-30 at 3 09 17 PM](https://user-images.githubusercontent.com/30483988/71604394-817dc680-2b16-11ea-9961-ff86a2db2920.png)

![Screen Shot 2019-12-30 at 3 09 52 PM](https://user-images.githubusercontent.com/30483988/71604405-8e9ab580-2b16-11ea-8b06-6f51ab2c6fa0.png)

**Comment by creative-fool** [comment]
**Hey there!** I am new to open source community and willing to contribute for this issue as a beginner.

**Comment by amychurchwell** [comment]
@creative-fool hello and welcome! Thanks for dropping by. There is currently already a pull request open for this issue (#8361). (See link above your comment with the icon "open")

Feel free to browse our other issues. We try our best to keep things labeled, but you are welcome to comment if you have a question.
- [mozilla.org](https://github.com/mozilla/bedrock/issues)
- [protocol design system](https://github.com/mozilla/protocol/issues)
