### ISSUE TITLE
Experiment: animations on load content/scroll

### ISSUE THREAD

**Issue by cgonz0** [mozilla/bedrock#8358]
## Description

Placeholder ~ needs more detail.

What:
Create a series of types of motion that can be applied on loading content when user is scrolling through page
Protoype: https://codepen.io/cgonza/full/OJPbxdq

Why:
Add life to page / Engage and encourage user to scroll through page

To be tested on /firefox and measure success vs current static page
If successful: Set of animations should be added into protocol, used on /firefox, and available for use on any other pages

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by amychurchwell** [comment]
See also: https://github.com/mozilla/protocol/issues/251

**Comment by alexgibson** [comment]
When we tackle this we should consider how we deal with legacy browsers, as many older mobile devices for example, do not support scroll events in the same way as desktop. We should look to avoid delivering janky or broken experiences to users who may not be on modern devices, whilst serving more modern users an enhanced experience.

**Comment by amychurchwell** [comment]
@alexgibson Agreed. I'm of the opinion that motion should only be served to [browsers who support the `prefers-reduced-motion` accessibility feature.](https://caniuse.com/#search=prefers-reduced-motion)

**Comment by amychurchwell** [comment]
^ scrolling transition motion, that is. I think motion such as notification effects are of a different category.

**Comment by alexgibson** [comment]
> @alexgibson Agreed. I'm of the opinion that motion should only be served to browsers who support the prefers-reduced-motion accessibility feature.

That's a great suggestion. I _think_ this should be accessible in JS too, via `window.matchMedia()`;

**Comment by hoosteeno** [comment]
@cgonz0 is this experiment ready for specifying? If so, we can create a card for @sghoseWI and get on it.

**Comment by cgonz0** [comment]
@hoosteeno almost. having another meeting this thursday regarding creating an experiment. will have a clearer idea post-meeting.

**Comment by sghoseWI** [comment]
@hoosteeno Amy invited me to that meeting -- I'll attend and put together the test plan once I get some more details Thursday.

**Comment by alexgibson** [comment]
Closing old / stale issues. Feel free to re-open if still relevant
