### ISSUE TITLE
Default homepage needs conditional CTA for firefox users.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8359]
## Description

Currently, the [default homepage](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home.html) shown to users not in EN, FR, or DE shows a "Download Firefox" CTA and related hero copy to users **already** using the Firefox browser.

We should write alternative hero copy and show a different CTA (Assuming Firefox Accounts?) for these users.

**Comment by alexgibson** [comment]
Closing this an unplanned as the page is being redesigned currently
