### ISSUE TITLE
Remove jQuery code from Facebook Container page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8370]
## Description

The `/firefox/facebookcontainer/` page is the only remaining page still using the legacy `mozilla-video-poster.js` library. Removing the jQuery code from this page means we can also remove the library from bedrock (or we could decide to keep/migrate it if useful).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Library is removed from the page.
- [x] Video is still functional.

**Comment by imskr** [comment]
Can I take this issue?

**Comment by alexgibson** [comment]
@imskr sorry I had already started work on this

**Comment by imskr** [comment]
@alexgibson no problem :)

**Comment by imskr** [comment]
Is there any current issue I can work on @alexgibson
