### ISSUE TITLE
Determine the fate of /plugincheck

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8374]
## Description

The [/plugincheck](https://www.mozilla.org/en-US/plugincheck/) page has not been linked to from in-product since 2016. When it was a functioning page, it used to get around ~700,000 page views daily (which was huge!), but since then we've seen a gradual declining long-tail in traffic.

![image](https://user-images.githubusercontent.com/400117/71727662-eb59e100-2e32-11ea-8117-385b0af6e552.png)

Even still, today the page gets around ~15,000 pave views per day. Mostly from legacy Firefox users. Those users just get a prompt to update their browser:

![image](https://user-images.githubusercontent.com/400117/71727746-2b20c880-2e33-11ea-8b29-59b61834226e.png)

This page is now pretty outdated in terms of branding, so we should decide what to do with it. It could either be updated, or redirected to /firefox/new/.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is either updated, or redirected in production.

**Comment by amychurchwell** [comment]
Can we port this to protocol in the meantime?

**Comment by alexgibson** [comment]
@amychurchwell right now pages like this are dependent on the audit in https://github.com/mozilla/bedrock/issues/8421.

I’m not sure it’s worth the effort of porting pages we can potentially retire soon. Let’s wait until the audit is complete?

**Comment by amychurchwell** [comment]
@alexgibson sounds good! 👍

**Comment by hoosteeno** [comment]
@alexgibson can you paste a screenshot of this page in Fx version 12.0?

Thank you.

**Comment by hoosteeno** [comment]
Note: There is no logic on this page for old versions that checks plugins anymore. It just tells them to upgrade.

**Comment by alexgibson** [comment]
@hoosteeno here's a screenshot of what firefox 12 users see when visiting the page

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/400117/75904917-f41f6100-5e3b-11ea-99ee-8c0a226788a5.png">

As discussed, this is likely a dead-end as people on windows 2000 likely can't upgrade any further.

**Comment by hoosteeno** [comment]
I have submitted an article update to the NPAPI article on SUMO which includes the copy on the page above:

https://support.mozilla.org/en-US/kb/npapi-plugins/compare?locale=en-US&to=196090&from=195162

If/when that revision (or similar) is live, let's redirect this traffic there.

**Comment by alexgibson** [comment]
@hoosteeno looks like the SUMO revision here isn't updated just yet. Any way to get visibility on that process, or find out when it might be completed?

**Comment by hoosteeno** [comment]
The SUMO page launched with the copy we wanted there.
