### ISSUE TITLE
Remove jQuery code from mozilla.smoothscroll.js and mozilla.lazy-load.js libs

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8381]
## Description

Both `mozilla.smoothscroll.js` and `mozilla.lazy-load.js` libs have portions of jQuery code that can either be removed or converted to native functions.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Both libraries are updated to use native code only.

**Comment by vinay-deshmukh** [comment]
I'd like to solve this issue.

Are there any particular webpages which use these libraries, so I can observe the changes I am making? (on a local server i.e. through `npm start`)
