### ISSUE TITLE
Remove jQuery code from contact-spaces.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8383]
## Description

The code for the /contact/ pages is still written using jQuery, and can be converted to use native functions.

Note we may want to either replace or remove the "magnificent popup" plugin being used for the community photos.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page JS is updated to use native code.

**Comment by Shivansh2407** [comment]
Can I help with this issue Sir? The only thing that needs to be done here is removing jquery code?

**Comment by Shubhrmcf07** [comment]
Can I help on this?

**Comment by alexgibson** [comment]
This will be fixed in https://github.com/mozilla/bedrock/pull/8514
