### ISSUE TITLE
Automate legal-docs updates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8385]
## Description

It would be nice if legal-docs could be updated automatically, without the need for a manual git submodule update.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Privacy / legal page content can be updated independently to bedrock.

**Comment by pmac** [comment]
We do have some issues filed for this: #5721, #5818. We could consider those prerequisites.

**Comment by pmac** [comment]
Also, for even more context, I've had a conversation with Michael Feldman in legal and he's interested in possibly moving the management of the docs to a more user-friendly system like we have for release notes. So maybe it will move to Nucleus eventually as well. No solid plans for this to be clear, but that could be a thing this year.
