### ISSUE TITLE
Experiment: Design experiment for Mac vs. Windows install rates

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8389]
## Description

Design a download-to-install rate experiment to answer these questions:

Is it possible to know whether Mac or Windows users have a higher overall download-to-install rate? We want to run three variations + the control (four page variations total). The target pages are /en-US/firefox/thanks and /en-CA/firefox/thanks.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is designed and approved by stakeholder (kfowle) and team lead
- [ ] Follow up issues are filed and linked here

**Comment by hoosteeno** [comment]
@sghoseWI this is in the "specify" column with a "ready" label, which is the new 2020 way of saying it's ready for work. Do you need any more information to start?

**Comment by hoosteeno** [comment]
Depends on https://github.com/mozilla/bedrock/issues/7474

**Comment by alexgibson** [comment]
One thing to consider here is that MacOS has an [entirely separate mechanism](https://github.com/mozilla/bedrock/blob/master/media/js/base/stub-attribution-macos.js) for attribution. We may have to do some extra work to make those parameters available like we do for Windows.

**Comment by hoosteeno** [comment]
Thanks, Alex. In fact, Mac attribution doesn't work at all. I think that's our new 2020 way of saying this is not ready. I'll figure out whether it can be made ready.

**Comment by hoosteeno** [comment]
Closing this as impossible for now. Reopen as needed.
