### ISSUE TITLE
Extract Strings for new webpage on mozilla.org for the community participation hotline content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8396]
## Description

Extract the strings created in  #8393 for https://www.mozilla.org/about/governance/policies/participation/reporting/community-hotline

L10n - This is NOT a Marketing page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Strings are extracted and made available to localizers

#### Tasks
- [ ] Extract strings
- [ ] Notify Peiying of extraction

**Comment by alexgibson** [comment]
This was done in https://github.com/mozilla-l10n/www.mozilla.org/pull/362
