### ISSUE TITLE
Splash Page for Recommended Extensions Program

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8398]
## Description

Webpage on www.mozilla.org for Recommended Extensions Program (maybe could also be used as a Moments Page)

Better surfacing of Recommended Extensions in a 'splash' page (vs. how they are badged on AMO) with the hypothesis that it would lead to more addons usage and thus better retainement of users (Firefox Desktop Retention). CPark noted that addon users are "known to retain 2x better than non-users."

---

#### :Success Criteria:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :Approver:
- [ ] PMM

**Comment by ejregithub** [comment]
@hoosteeno que pasa aqui?

**Comment by hoosteeno** [comment]
Closing until we have clearer input from PMM team.
