### ISSUE TITLE
Set up an experiment for UA attribution with coarse user agent detection

### ISSUE THREAD

**Issue by Mardak** [mozilla/bedrock#8405]
## Description

Probably using #8363 to complete [Bug 1406005 - Run onboarding experiment passing UA string variation to attribution service](https://bugzilla.mozilla.org/show_bug.cgi?id=1406005)

The high level intent is to correctly attribute the top 5 desktop browsers and pass that data to Firefox via stubattribution. Other browsers (or modified UAs) that have strings that look like one of the top default user agent strings will just be treated as false positives. Also noting that we don't need to capture the browser version.

Here's some example code from https://bugzilla.mozilla.org/show_bug.cgi?id=1406005#c47:
```js
function deriveVariation(ua) {
  if (ua.includes("Trident")) return "ie";
  if (ua.includes("Edg"))     return "edge";
  if (ua.includes("Version")) return "safari";
  if (ua.includes("Firefox")) return "firefox";
  if (ua.includes("Chrome"))  return "chrome";
  return "other";
}
```

**Comment by hoosteeno** [comment]
I'll channel @alexgibson here (and encourage him to follow up with other great questions): Since attribution is impossible in MacOS, do we need to do this for Safari?

**Comment by Mardak** [comment]
Ah good point about no windows safari. I suppose we could add Opera/OPR as a 5th or just exclude as the other named ones probably cover 95% of windows desktop already.

**Comment by alexgibson** [comment]
The main question I have here is how should this experiment be configured? What kind of parameter values should we conform to, and how long should this experiment need to be running until we have enough data to satisfy the purpose?

If we have `experiment` and `variation` parameters available. We could do something like the following:

```javascript
experiment: 'ua-attribution'
variation: StubAttribution.getUserAgent()
```

Obviously, this would override any other experiment until we have enough data. As far as the UA detection pseudo-code in the description goes, this seems OK to me, but may be a little more complex in reality. I'd also like to call out that we may want to consider something such as `chrome-like` instead of just `chrome`, since many browsers are now starting to use Chrome's default UA string (Brave, Vivalid, Edge in some instances). I expect more brosers could start to follow this pattern in the future.

**Comment by Mardak** [comment]
We had a meeting with @hoosteeno where we decided to get stubattribution updated to support `ua` https://github.com/mozilla-services/stubattribution/pull/95

So there should be no concern about needing to overload `experiment` and `variation` anymore (which sounds like we'll want to run an experiment soon separate from this UA work).

I suppose to get meaningful numbers, we want to set `ua` attribution as wide as possible for firefox desktop downloads, but perhaps to start / experiment, attribute the primary download flow? @hoosteeno do you have suggestions on if doing it on the main download point needs to be throttled?

**Comment by hoosteeno** [comment]
Yes, https://github.com/mozilla-services/stubattribution/pull/95/commits adds ua to the stub attribution service, and it's already present in Fx73, so we just have to start sending it from download buttons. 

@alexgibson what are the constraints on sending this parameter with every download?

**Comment by alexgibson** [comment]
> @alexgibson what are the constraints on sending this parameter with every download?

We're already hitting the stub auth service for every download on Windows, so adding in a new parameter here for bedrock should be fine I think.

Does that sound right, @pmac?

**Comment by pmac** [comment]
> We're already hitting the stub auth service for every download on Windows, so adding in a new parameter here for bedrock should be fine I think.

Are we? I thought we were only hitting it when we had some UTM param data and/or a referrer. I assumed that wasn't everyone. Though I don't think it'll be a burden to turn it on for all stub downloads if we're not already.

**Comment by alexgibson** [comment]
https://github.com/mozilla/bedrock/pull/5609 seems to be the change that introduced adding data for every request

**Comment by alexgibson** [comment]
@hoosteeno given the above, I'm not sure if there's anything preventing us adding the `ua` parameter to all stub attribution requests, at least on the bedrock side of things.
