### ISSUE TITLE
Code: new 404 and 500 pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8407]
## Description

The card is for the tasks required to code the newly design 404 and 500 error pages on www.mozilla.org, using our current coding standards. 

The new designs for this page are here: https://github.com/mozilla/bedrock/issues/8329#issuecomment-572775691

### Success Criteria 
- [ ] The page is built with Protocol components
- [ ] Strings are extracted, made available in Pontoon to be localized in Fluent by the Community

### Reviews:
- [ ] Brand (copy and design)
- [ ] Team QA
- [ ] Team Lead

------

## Original Report

I ended up on https://www.mozilla.org/en-US/firefox/xr/ ([from clicking a link like this](https://bugzilla.mozilla.org/show_bug.cgi?id=1604853))

<img width="1248" alt="Screen Shot 2019-12-18 at 12 48 33 PM" src="https://user-images.githubusercontent.com/26739/71110150-bf80ff00-2194-11ea-8c32-bd0735c717c5.png">

My impression was that this was some sort of marketing campaign. But it was cryptic. What's a "Whoops!"? Also, the attempt to be funny with "Did you make a left at that last URL instead of a right?" is funny but it's not working. It could work if I've immediately understood that it's a page-not-found page. 

Also the bullet point list is unfocussed in that I have no idea what those bullet points are trying to communicate (I know it's about getting you away from the not found page to the right page, but that's not clear and takes time to understand)

### Steps to reproduce

Go to https://www.mozilla.org/en-US/firefox/xr/ and imagine you don't know what a www.mozilla.org's page-not-found pages look like. 

### Expected result

A title like "Page not found". Or a sub-title like "The URL could not be found". 
Perhaps some graphic that gets the impression that something went wrong. 

### Actual result

See description.

**Comment by Errolyn** [comment]
@ejregithub I'm not seeing a source for the copy? I'm just using what I see in the design but to go any further I need access to the copy doc. Thanks :D 

@cgonz0 what famicon should we use for the 404 & 500 pages? And to double check there should not be a footer on this page?

**Comment by cgonz0** [comment]
@Errolyn 
correct, no nav or footer. let me get back to you on the favicon:)
the (m)ozilla and desktop icons are used in the nav - although not exactly sure where they live in the directory.
i don't think the firefox logomark icon exists on any webpage just yet, so will send that to you.

> @cgonz0 what famicon should we use for the 404 & 500 pages? And to double check there should not be a footer on this page?
> 
>     * I will also need a resource for the icons used in the list, ( I could be missing them if they are already in protocol but I'm not seeing them)

**Comment by hoosteeno** [comment]
@Errolyn Can you update with status on these pages?

**Comment by Errolyn** [comment]
Is mostly done, I have been having a transient issue with the styles in the 500 page not showing up, and also the page itself having an error. I plan to get everything up on demo today for review.

**Comment by cgonz0** [comment]
hi @Errolyn, looking good - some design feedback below
___________________________________

Just a few tweaks from the screenshots you sent - i can get a little more specific once I see the demo

**404 page**
-can we add a little more space under go back link?
-and some more space b/w list items below


**mobile**
-we should reduce the header logos a bit (for 500 page as well)
-and header text down to 40px (same for 500)
-position list text so it wraps around underneath the text (not underneath the icon - should just be hanging on the left side)

**Comment by cgonz0** [comment]
hey @Errolyn, a few more changes after reviewing demo

___________________________________

**404 page**

-Header logo - Can we use the high res version? Looks a bit blurry. Please set to 290px width (to match logo size on other pages).
-Can we also mimic the responsive sizing from our other pages - where screen is <1056px, logo should reduce a bit (to 220px).

-Header font-size - please bring down to 48px
-@ <768px increase size from 32px to 40px. at this screen size we can leave rest of the text at 18px (increase from 14px).
-Increase the padding above header - add about 32px

-Can we add a space between arrow and “Go Back”?

-Let's make the icons a bit bigger - please increase the width to about 30px

-Can we decrease the max-width of list-content so it doesn't wrap around at small screen size?


**500 page**
Same text sizing applies here

Thanks!
