### ISSUE TITLE
Build experimentation plan for content scroll animation.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8408]
## Description

Refining experiment details around introducing motion on scroll events on mozorg.
Protoype: https://codepen.io/cgonza/full/OJPbxdq

Epic: #8358

**Comment by sghoseWI** [comment]
Test plan: https://docs.google.com/document/d/1L1HRec2DUAkZIs2Ylqb7ktvzShsEvuBACVMY4iocHUc/edit

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
