### ISSUE TITLE
Add a .well-known URL to support the Mozilla Matrix service

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla/bedrock#8410]
## Description

The messaging platform that we will be using (Matrix / Riot), needs a well-known URL, https://mozilla.org/.well-known/matrix/server to verify delegation of the matrix service to an offsite service.

The contents of that URL are likely static-forever:
`{
  "m.server": "mozilla.modular.im:443"
}`

A comparable example from another customer of theirs is at https://kde.org/.well-known/matrix/server

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Visiting https://mozilla.org/.well-known/matrix/server returns the above json blurb

**Comment by pmac** [comment]
bedrock only serves URLs at www.mozilla.org. If the URL at the apex domain redirected to one at www.m.o would it still work?

**Comment by ara4n** [comment]
yes, if https://mozilla.org/.well-known/matrix/server 302s to https://www.mozilla.org/.well-known/matrix/server it will still work.

N.B. the contents needs to be `{ "m.server": "mozilla.modular.im:443" }`

**Comment by pmac** [comment]
Cool. That redirect already works. We can host the file. I'll get a PR together.

**Comment by jgmize** [comment]
@pmac's PR is now in production:

> $ curl -is https://mozilla.org/.well-known/matrix/server | egrep '(HTTP|location)'
> HTTP/2 302
> location: https://www.mozilla.org/.well-known/matrix/server
> $ curl https://www.mozilla.org/.well-known/matrix/server
> { "m.server": "mozilla.modular.im:443" }
