### ISSUE TITLE
Leadership page update requests

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8412]
## Description

There are several update requests for the leadership page:

- [ ] Those listed in this [document](https://docs.google.com/document/d/1-TKTB7FtLeN8wU8kCCELuYui5Mxhgs_fIbfP8yiewAw/edit)
- [ ] Replacing the current image for Alan Davidson with the one attached in comment
- [ ] The tasks described [here](https://github.com/mozilla/foundation.mozilla.org/issues/3765), to add the new VP - Bob Alotta, his pic and bio, to the leadership page.

Due 1/31 (well within our current average Lead Time of 14.3 days)

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/72117206-ad146400-3301-11ea-92cf-ecdf9aa3d333.png)

**Comment by Shivansh2407** [comment]
The link you posted is not accessible . Please let me know what to do. Would like to help you fix this issue.

**Comment by ejregithub** [comment]
@hoosteeno - please assess for inclusion to the backlog. This should be good to move to the ready column. Please note the requested date for go live, on or before 1/31 (so 1/23, realistically).

**Comment by ejregithub** [comment]
Hi @Shivansh2407 - apologies, I don't own the brief that was submitted and can't open it externally. I will see about posting the required content from it here. Thank you for your interest in working on the issue.

**Comment by ejregithub** [comment]
Piling on here - new requirement is do the tasks described here - https://github.com/mozilla/foundation.mozilla.org/issues/3765

**Comment by kristinashu** [comment]
Can I please add an additional request to this ticket? Please remove `Ronald Lemos` from the board. He has resigned and needs to be moved to emeritus ASAP. Thank you and please let me know if you have any questions!

**Comment by ejregithub** [comment]
@craigcook please see the request above to more Ronald Lemos to the 'former board member' section.
