### ISSUE TITLE
Determine the fate of /styleguide/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8418]
## Description

The current [/styleguide/ ](https://www.mozilla.org/en-US/styleguide/)page is placeholder from when a lot of outdated content was removed. We should decide if it's worth keeping, or alternatively redirect to https://mozilla.design/.

The /styleguide/ page currently gets < 100 page views per day.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is either kept or removed & redirected in production.

**Comment by hoosteeno** [comment]
Let's redirect this page to https://mozilla.design/.
