### ISSUE TITLE
Determine the fate of /this-browser-comes-highly-recommended/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8419]
## Description

This page is a developer-focused campaign [landing page](https://www.mozilla.org/en-US/firefox/this-browser-comes-highly-recommended/). It receives next to no traffic (sometimes ~3 page views per day), and has had ~1000 page views in the last year.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is either kept or removed & redirected in production.

**Comment by hoosteeno** [comment]
Let's remove this content and redirect to developer edition download page.
