### ISSUE TITLE
Determine the fate of /firefox/dedicated-profiles/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8420]
## Description

If memory serves me correctly, [this page](https://www.mozilla.org/en-US/firefox/dedicated-profiles/) was shown only to Nightly users for a limited period of time. That period seems to be 15/16 Jan 2019, and since then the page recieves pretty much zero traffic.

We could redirect this page to https://support.mozilla.org/kb/dedicated-profiles-firefox-installation

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is removed & redirected in production.

**Comment by hoosteeno** [comment]
Let's redirect this page to https://support.mozilla.org/kb/dedicated-profiles-firefox-installation and remove from our code repo.
