### ISSUE TITLE
Audit of legacy content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8421]
## Description

Below are a few open issues to get started:

- /internet-health/ https://github.com/mozilla/bedrock/issues/8375
- /plugincheck/ https://github.com/mozilla/bedrock/issues/8374
- /technology/ https://github.com/mozilla/bedrock/issues/6824
- ~/firefox/concerts/ https://github.com/mozilla/bedrock/issues/8416~
- /styleguide/ https://github.com/mozilla/bedrock/issues/8418 ✔️ 
- /recommended/ https://github.com/mozilla/bedrock/issues/8419
- /dedicated-profiles/ https://github.com/mozilla/bedrock/issues/8420 ✔️
- /campaign/ landing pages https://github.com/mozilla/bedrock/issues/8427
- /firefox/features/ pages https://github.com/mozilla/bedrock/issues/8461 ✔️
- /etc/firefox/retention/ pages https://github.com/mozilla/bedrock/issues/8536

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Produce a list of pages that should either be kept or decommissioned.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Some pages may have content owners, others may have no clear owner.

**Comment by alexgibson** [comment]
Audit doc of other existing pages here: https://docs.google.com/spreadsheets/d/1RMYNxsFvZAx2DGwHINiEbf5oUYzOvEOp2RPrIH1LtF0/edit?usp=sharing

**Comment by hoosteeno** [comment]
In terms of replacing Pebbles with Protocol, the items in this list that we need to address are...

* Internet health
* plugincheck
* campaign
* feature
* retention
* technology

These are all equal priority from a dev perspective. We can prioritize them by other factors.

**Comment by hoosteeno** [comment]
Priorities and dispositions for this content are established here: https://docs.google.com/spreadsheets/d/1RMYNxsFvZAx2DGwHINiEbf5oUYzOvEOp2RPrIH1LtF0/edit#gid=1434861645
