### ISSUE TITLE
Find a better hosting solution for /enterprise package downloads

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8424]
## Description

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1608659

TL:DR: box.com does not work in legacy browsers.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Box.com links are replaced by a self-hosted solution.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The /enterprise team need to be able to update the URL autonomously.

**Comment by devinreams** [comment]
We don't want to manually create/maintain these anymore, so will need to do the following...

- [ ] remove Download buttons and terms link from https://www.mozilla.org/firefox/enterprise/#download
- [ ] add "Deployment Guide" to a hosted location (GDrive, bedrock?) and link to it
- [ ] link "Policy documentation" to the GitHub default branch view for that markdown file?

## Windows 64

- [ ] link to "Firefox browser" (can we link directly to this OS/release config?)

## Mac

- [ ] link to "Firefox browser" (can we link directly to this OS/release config?)
- [ ] add link to "sample plist" (where?)
- [ ] add link to "PKG installer" to this article https://support.mozilla.org/kb/deploying-firefox-macos-using-pkg-and-jamf
  - [ ] change article to describe "step 1" as browsing to the release "mac" directory to download the PKG file

## Windows 32

- [ ] link to "Firefox browser" (can we link directly to this OS/release config?)
- [ ] add same links as Windows 64

**Comment by devinreams** [comment]
@ejregithub I just created a pull request to remove the downloads entirely and replace them with links in the content.

Is this something you can help us get reviewed and deployed ASAP as the files are currently outdated and removed from box.com: https://github.com/mozilla/bedrock/pull/8489

**Comment by devinreams** [comment]
Whoop, I believe @ejregithub is out right now...

Sorry to bug you directly @hoosteeno or @alexgibson, but is this something you all can help take a look at? #8489

**Comment by craigcook** [comment]
Updates are live: https://www.mozilla.org/firefox/enterprise/
