### ISSUE TITLE
Default Browser Campaign: Rough design CTA

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8425]
## Description

We need to figure out how the default browser campaign CTA will work. This card is about putting together a clickable prototype that will help us identify the right way forward.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Rough prototype is ready for coding

#### Reviews
- [ ] UX
- [ ] Dev
- [ ] Analytics

**Comment by hoosteeno** [comment]
If you are in Firefox and have *not* set Firefox to be the default, [here is a CTA experience that might work for you](https://invis.io/EZVJ028V2D8).

If you are in Firefox and have *already* set Firefox to be the default, [here is a CTA experience that might work for you](https://invis.io/5WVJ03HYR6E).

**Comment by dzingeek** [comment]
@hoosteeno I spent a bit more time thinking this through and would love your thoughts on my new proposed ux direction. 

If you are in Firefox and have already set Firefox to be the default, [here is a CTA experience that might work for you.](https://mozilla.invisionapp.com/share/JVVJ32TKUWS#/400509754_400487682)

If you are in Firefox and have not set Firefox to be the default, [here is a CTA experience that might work for you.](https://mozilla.invisionapp.com/share/28VJ30GKFEG#/400509509_400487684)

**Comment by hoosteeno** [comment]
Thanks @dzingeek ! In conversation with @amychurchwell , we started thinking it would be a neater abstraction of all the "hard parts" of this if we were able to put the mechanism on a single page, and did not try to cram it into a modal. What do you think of this flow? https://miro.com/app/board/o9J_kv0J57s=/

**Comment by hoosteeno** [comment]
In meeting, the project team agreed that this flow is acceptable. We'll move on to copy and design.
