### ISSUE TITLE
Determine fate of legacy campaign pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8427]
## Description

The following campaign pages are all several years old, and still using the legacy Pebbles framework. If they are no longer in use, we should decommission them. If they are still neded, we need to migrate them.

- https://www.mozilla.org/en-US/firefox/campaign/?xv=betterbrowser
- https://www.mozilla.org/en-US/firefox/campaign/?xv=safari
- https://www.mozilla.org/en-US/firefox/campaign/?xv=edge
- https://www.mozilla.org/de/firefox/campaign/?xv=berlin
- https://www.mozilla.org/de/firefox/campaign/?xv=aus-gruenden
- https://www.mozilla.org/de/firefox/campaign/?xv=herz
- https://www.mozilla.org/de/firefox/campaign/?xv=geschwindigkeit
- https://www.mozilla.org/de/firefox/campaign/?xv=privatsphare
- https://www.mozilla.org/de/firefox/campaign/?xv=auf-deiner-seite

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are either ported or decommissioned in production.

**Comment by alexgibson** [comment]
@guyfitzpatrick hi - unless you have any reason why we need to keep these pages around, I'm going to propose we end-of-life the above campaign landing page designs. 

All the above URLs have next to zero traffic in GA, and the templates themselves are built on a legacy framework which is being decommissioned. If any of this content is still needed, it would need to be ported to use our current design system. Given the low traffic however, I'm not sure this is a worthwhile investment.

If you have any objections, please let me know. Thanks!

**Comment by hoosteeno** [comment]
Let's remove this content (yes all of it) and redirect to /new. \o/
