### ISSUE TITLE
Default Browser Campaign: Design landing page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8429]
## Description

In #8428 we'll build several campaign pages. This card is about designing the landing page for the campaign. The landing page will accept traffic from numerous upstream sources such as press, email, possibly in-product, etc. It should have one CTA: Set Firefox as Default. The CTA will link to a thanks page.

[Copy for Landing Page](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/

This work requires close collaboration with copy team.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Design is ready for coding and attached in final form to this card
- [ ] All approvals complete

#### Approvals
- [ ] Brand
- [ ] Copy
- [ ] RASCI A
- [ ] Dev
- [ ] PM

**Comment by cgonz0** [comment]
First Draft of landing page:

![default browser_set-as-default - landing page](https://user-images.githubusercontent.com/29640968/72397514-fcd59f80-36f4-11ea-91cb-174d645242ab.png)

**Comment by cgonz0** [comment]
Updated Copy - icons not finalized

![default browser_set-as-default - landing page_update](https://user-images.githubusercontent.com/29640968/72544641-98255c80-383c-11ea-92e2-3d57147cc32c.png)

**Comment by cgonz0** [comment]
@Errolyn 

![browserdefault_privacy_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/b26e4071-1648-411a-afeb-f91de6185e53)

![browserdefault_freedom_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/6412a7e2-07ba-4916-8dfd-39f706795d5d)

![browserdefault_independence_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/71c9ea42-66d1-4b38-95ca-4aeb2a37793b)

![Screen Shot 2020-01-16 at 4.04.54 PM.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/d9257e2e-902d-48e3-9062-ece878fda045)
