### ISSUE TITLE
Default Browser Campaign: Copy for landing page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8430]
## Description

In #8428 we'll build several campaign pages. This card is about writing copy for the landing page for the campaign. The landing page will accept traffic from numerous upstream sources such as press, email, possibly in-product, etc. It should have one CTA: Set Firefox as Default. The CTA will link to a thanks page.

[Copy for Landing Page](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/

This work requires close collaboration with design team.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Copy is attached in final form in this card
- [ ] All approvals complete

#### Approvals
- [x] Brand
- [x] RASCI A
- [ ] Dev
- [x] PM

**Comment by rantley** [comment]
https://docs.google.com/document/d/1EQZP6CleTmrFoa1xNCqFe8UmaYupqTwXGsT9h6GNeyw/edit?usp=sharing

First draft of copy here

**Comment by rantley** [comment]
@ejregithub  Landing page copy 
https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing

**Comment by ejregithub** [comment]
As copy is final/approved, I'm closing this issue.
