### ISSUE TITLE
Default Browser Campaign: Code landing page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8431]
## Description

In #8428 we'll build several campaign pages. This card is about coding the landing page for the campaign. The landing page will accept traffic from numerous upstream sources such as press, email, possibly in-product, etc. It should have one CTA: Set Firefox as Default. The CTA will link to a thanks page.

The copy doc for this page is [here.](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/

See #8429 for design.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is launched in production by 2020/01/22 or sooner
- [ ] All approvals complete
- [ ] Ready for staff localization in Tier 1
- [ ] Strings extracted for community localization

#### Approvals
- [ ] RASCI A
- [ ] PM

**Comment by ejregithub** [comment]
@Errolyn - flagging here that the copy is final/approved by Shep and the [copy doc](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit#heading=h.oo63piaiuqi8) is the source of truth.
