### ISSUE TITLE
Default Browser Campaign: Design Thanks Page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8432]
## Description

In #8428 we'll build several campaign pages. This card is about coding the thanks page for the campaign. The thanks page will manage state-based transactions on behalf of users who have clicked "Set Firefox as Default" somewhere upstream. The diagram of conditions is here: https://miro.com/app/board/o9J_kv0J57s=/

[Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/thanks/

This work requires close collaboration with copy team. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is launched in production 2020/01/22 or sooner
- [ ] All approvals complete

#### Approvals
- [ ] Brand
- [ ] Copy
- [ ] Dev
- [ ] RASCI A
- [ ] PM

**Comment by cgonz0** [comment]
First Draft of thank you pages (firefox not desktop browser, not set to default (system dialog), set to default success)

![default browser_ser-as-default-thanks - thankyou page](https://user-images.githubusercontent.com/29640968/72397635-58a02880-36f5-11ea-9ad0-3f462b495f36.png)

@alexgibson  initial mocks here - should be enough to get a head start. icons included in one version - tbd on that.

**Comment by alexgibson** [comment]
@cgonz0

I updated the demo server with the design feedback you gave me yesterday over Slack, thanks.

I also updated the "Not set -> system dialog" state to not display the bottom section of links, as you suggested (screenshot below). As you can see, if someone has difficulty setting their browser to default, there is now nothing to help them since the SUMO links are no longer there. 

My preference would be to not hide these links at all, or alternatively move the "Having trouble?" copy up underneath the "almost done copy". This does make things more busy though. Do you have any suggestions here for what you think might be best?

![image](https://user-images.githubusercontent.com/400117/72514994-1ab31980-3847-11ea-9c0e-2a17b07ffaf6.png)

**Comment by cgonz0** [comment]
@alexgibson 
yes, i think adding a help link underneath is helpful without being too distracting. we could either use the full text of that bucket with both links to desktop and android, or have a more condensed link - maybe just linking to the more general desktop link? although it would probably make more sense to include both links. here's a screenshot of an example of both - possibly copy can weigh in if we decide to go this route. what do you think?

<img width="1239" alt="Screen Shot 2020-01-16 at 6 55 01 AM" src="https://user-images.githubusercontent.com/29640968/72535317-33163a80-382d-11ea-972f-bbd3f8956cbd.png">

**Comment by alexgibson** [comment]
@cgonz0 thanks, I think adding the full blurb with both links is probably best, since Android users could also visit this page, and their only option is to follow the SUMO instructions. I'll see to updating the page, thanks.

**Comment by cgonz0** [comment]
thanks @alexgibson, text set at 16px

**Comment by alexgibson** [comment]
@cgonz0 updated thanks

**Comment by alexgibson** [comment]
@cgonz0 can you please provide the icons in these mockups? thanks

**Comment by alexgibson** [comment]
@cgonz0 @hoosteeno based on suggestions in https://github.com/mozilla/bedrock/issues/8434#issuecomment-575402884, I've made the following changes to state two, depending on if you're using Firefox for desktop/android/ios:

Desktop
--------
![image](https://user-images.githubusercontent.com/400117/72604856-9e3a3c80-3913-11ea-9153-8340d07134de.png)

Android
--------
![image](https://user-images.githubusercontent.com/400117/72604922-bb6f0b00-3913-11ea-820b-33c48691c769.png)

iOS
----
![image](https://user-images.githubusercontent.com/400117/72604970-d2156200-3913-11ea-8a23-a72f9531f8c5.png)

Note: the iOS link goes to [this SUMO article](https://support.mozilla.org/en-US/kb/unable-set-firefox-default-browser-ios), which explains you can't set it as default, but does show how to perform other useful actions such as sending pages from other apps.

**Comment by alexgibson** [comment]
@hoosteeno @cgonz0 please note that before we extract strings for this page, I'd like someone to officially approve the copy that's on demo: https://www-demo2.allizom.org/en-US/firefox/set-as-default/thanks/

**Comment by cgonz0** [comment]
@alexgibson the above changes look good to me. apologies about the icons - i pulled them from the website so thought you'd have access to them.
i just changed the help icon though. slacking to you now - not letting me attach them here.

**Comment by alexgibson** [comment]
Icons are now in place https://www-demo2.allizom.org/en-US/firefox/set-as-default/thanks/

**Comment by cgonz0** [comment]
> Icons are now in place https://www-demo2.allizom.org/en-US/firefox/set-as-default/thanks/

thanks @alexgibson. could we bring down the help icon just a bit? (background-size: 29px 29px;) it visually feels a bit larger than the ff icon.
