### ISSUE TITLE
Default Browser Campaign: Write copy for thanks page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8433]
## Description

In #8428 we'll build several campaign pages. This card is about writing copy for the thanks page for the campaign. The thanks page will manage state-based transactions on behalf of users who have clicked "Set Firefox as Default" somewhere upstream. The diagram of conditions is here: https://miro.com/app/board/o9J_kv0J57s=/

[Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/thanks/

This work requires close collaboration with design team. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Copy is attached in final form to this issue
- [ ] All approvals complete

#### Approvals
- [x] Brand
- [ ] Dev
- [x] RASCI A
- [x] PM

**Comment by hoosteeno** [comment]
Copy for the thanks page drafted here (cc @rantley ) https://docs.google.com/document/d/1EQZP6CleTmrFoa1xNCqFe8UmaYupqTwXGsT9h6GNeyw/edit

**Comment by rantley** [comment]
@ejregithub Updated version of copy here

https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing

**Comment by ejregithub** [comment]
As copy is final/approved, I'm closing this issue.
