### ISSUE TITLE
Default Browser Campaign: Code thanks page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8434]
## Description

In #8428 we'll build several campaign pages. This card is about coding the thanks page for the campaign. The thanks page will manage state-based transactions on behalf of users who have clicked "Set Firefox as Default" somewhere upstream. The diagram of conditions is here: https://miro.com/app/board/o9J_kv0J57s=/

[Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)

Proposed URL: /firefox/set-as-default/thanks/

See https://github.com/mozilla/bedrock/issues/8432 for designs.

In the event that a default browser setting is changed after a session appears on this page, we should send an event to Google Analytics. 

Refer to https://github.com/mozilla/bedrock/blob/e9fc1b5ce4dc16e02d8352f8d80ada2ab9e6e82c/media/js/firefox/win10-welcome.js to see previous implementations of this system.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is launched in production 2020/01/22 or sooner
- [ ] All approvals complete
- [ ] Ready for staff localization in Tier 1
- [ ] Strings extracted for community localization

#### Approvals
- [ ] RASCI A
- [ ] PM

**Comment by alexgibson** [comment]
WIP version of this page is now up on demo: https://www-demo2.allizom.org/en-US/firefox/set-as-default/thanks/

Testing notes:
- Be sure to [enable UITour](https://bedrock.readthedocs.io/en/latest/uitour.html#local-development) on demo by creating a pref called`browser.uitour.testingOrigins` with a value of `https://www-demo2.allizom.org`.
- To test the user flow, make sure Firefox is not already the default browser.

Things still missing:
- [ ] Final design / approved copy.
- [ ] Analytics parameters / events.
- [ ] Tests

**Comment by alexgibson** [comment]
One minor concern I have with the UX on this page:

Unless the visitor is referred from a page what sets the context (e.g. /whatsnew or /set-default/browser/ landing page), the UX of seeing a system prompt trigger on page load could be pretty suprising and/or confusing. This isn't something that web pages can typically do, so people will not expect it. We should be careful not to share this /thanks/ page directly, just like we don't encourage people to link directly to /firefox/download/thanks/.

**Comment by alexgibson** [comment]
Design tweaks from Slack: firefox logo 60px, headline 56px, description 24px, bucket headline 24px

**Comment by hoosteeno** [comment]
>  Analytics parameters / events.

@alexgibson I have set up a goal around Firefox being set as a default. I think if we use the [Generic CTA](https://bedrock.readthedocs.io/en/latest/analytics.html#gtm-listeners-data-attributes), we can track this as a goal. If you can set it up soon, we can click a few dozen times and see if data appears.

If I've configured this correctly (a wide open question TBH), we need to add 'data-cta-type': 'fx-default'` to the datalayer attributes for an event that is sent when the default is changed to Firefox (but not if the default was already Firefox). 

Does this make sense & seem reasonable?

**Comment by alexgibson** [comment]
> I think if we use the Generic CTA, we can track this as a goal. If you can set it up soon, we can click a few dozen times and see if data appears.

I'm not sure I follow here. There is no CTA on this page, and hence nothing to click. Unless I'm misunderstanding what you mean (which is quite possible), I think we'll need a `dataLayer.push()` event or two to track interaction.

> If I've configured this correctly (a wide open question TBH), we need to add 'data-cta-type': 'fx-default' to the datalayer attributes for an event that is sent when the default is changed to Firefox (but not if the default was already Firefox).

Is `cta-type` appropriate, seeing as we have no direct CTA on the page? I was thinking this should probably be `'event': 'in-page-interaction',` or similar?

**Comment by hoosteeno** [comment]
We could go either way. But as you earlier implied: Nobody should get here without clicking a CTA. But, as with many of our CTAs (e.g. download), the actual completion happens on a different URL.

What pattern do we use on /download/thanks? We should probably do the same here. I can set up a goal around it.

**Comment by alexgibson** [comment]
> What pattern do we use on /download/thanks? We should probably do the same here. I can set up a goal around it.

We don't fire any kind of event on /download/thanks/ specifically. I believe we have something configured in GA/GTM for this?

It's a little different here, as we may want to measure:

- People who land on the page who already have Firefox as default.
- People who land on the page who don't have a default set.
- People who are in the category above, who then go on to sucessfully switch their default.

I'd suggest a `dataLayer.push()` event for each item.

**Comment by hoosteeno** [comment]
OK, so let's do a `dataLayer.push()` with the following:

### already-set-to-default
```
'eAction': 'visited'
'eLabel': 'firefox-default'
```

### some-other-browser-set-to-default
```
'eAction': 'visited'
'eLabel': 'non-firefox-default'
```

### just-now-set-to-default
```
'eAction': 'default-changed'
'eLabel': 'success'
```

**Comment by alexgibson** [comment]
@hoosteeno events should now be firing on demo

**Comment by hoosteeno** [comment]
I was finally able to see events on demo. 

I made one code comment for a change to a datalayer tag. 

I modified the goal on prod to handle the "success" tag. 
![Screen Shot 2020-01-16 at 12 15 25 PM](https://user-images.githubusercontent.com/94519/72555513-ee54c880-3859-11ea-9372-69ed8210340f.png)

**Comment by ejregithub** [comment]
@alexgibson - flagging here that the copy is final/approved by Shep and [the copy doc](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit#) is the source of truth.

**Comment by hoosteeno** [comment]
It looks like the default experience for Firefox users on this page is to show the "you're almost done" message.

This breaks on Fennec. Do you think we need a 4th state for Firefox not desktop?

**Comment by alexgibson** [comment]
> some-other-browser-set-to-default

> 'eAction': 'visited'
> 'eLabel': 'non-firefox-default'

@hoosteeno note i think this is somewhat confusing. If someone is using a non-Firefox browser, we have no idea if it's their default or not, but also we don't need to track non-Firefox visits in this way, as that's done for free in GA anyway via regular page views.

I suggest we change this to:

firefox-browser-not-set-to-default

'eAction': 'visited'
'eLabel': 'firefox-not-default'

This seems clearer to me, as we know if someone is using Firefox but it's not their default browser.

**Comment by hoosteeno** [comment]
Wfm. Thanks.
