### ISSUE TITLE
staticfiles ValueError when DEBUG is set to false

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8435]
## Description

Bedrock encounters a staticfiles `ValueError` when DEBUG is set to false in .env.
I believe this is a bug related to `STATICFILES_STORAGE` being flipped to `ManifestStaticFilesStorage` in settings when DEBUG is false.

https://github.com/mozilla/bedrock/blob/4d9db1d8ed9e11e9e1fe1f259fd2303bf2d96489/bedrock/settings/base.py#L358-L359

**Comment by amychurchwell** [comment]
@Errolyn encountered this bug while working on the 404 page locally.

@pmac when debugging the issue I ran `collectstatic` per [django docs](https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#manifeststaticfilesstorage) & also `make clean build` & still received the staticfiles error. Any ideas on what the issue might be?

**Comment by pmac** [comment]
Yes. `ManifestStaticFilesStorage` requires all of the referenced files to exist. If you run `collectstatic` with `DEBUG=False` then it should collect them all and you can run the server in that mode.

**Comment by amychurchwell** [comment]
@pmac unfortunatelly, `collectstatic` doesn't resolve the server error. :(
It seems to be receiving multiple errors of: 
- `ValueError: Missing staticfiles manifest entry for 'js/BUNDLES/site.js'`
- `ValueError("Missing staticfiles manifest entry for '%s'" % clean_name`

The "site" js bundle is referenced in templates and declared in `static-bundles`, so I'm not sure what is happening there. The `'%s'" % clean_name` error makes me feel like that value is being accidentally passed to `static`?

**Comment by pmac** [comment]
Oh! right. you also have to run the gulp stuff with `gulp build`. So the procedure should be:

1. `gulp build --production`
2. `./manage.py collectstatic`
3. Profit

I think that should do it at least...

**Comment by amychurchwell** [comment]
unfortunately, no dice. I think there is a wrong value happening somewhere, something that is not able to be referenced?

**Comment by amychurchwell** [comment]
this issue will be addressed in the work in #8392
