### ISSUE TITLE
WNP73: Code

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8436]
## Description

In #8428 we'll build several campaign pages. This card is about coding WNP73, which will be a primary entry point for the campaign. 

* WNP73 will take the copy from the campaign landing page
* It will have 3 content items below the main CTA area; [WNP70 experiment v5](﻿﻿https://docs.google.com/presentation/d/1PlWlpWK3L27W2zmZ2Jp1VVhbDwUGMPohHCOEIQRl-wM/edit#slide=id.g7c4f53cf2e_0_1222) is an approach that could work. 
* it will have a state-based CTA with two states. IF Firefox is the default, the CTA will be the mobile send-to-device widget. If Firefox is not the default, the CTA will encourage users to set Firefox as the default browser. The set-default CTA will link to the campaign's thanks page.

Designs for the campaign landing page (https://github.com/mozilla/bedrock/issues/8429) will be very helpful in building the WNP73. 

[Copy doc for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit#)

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1609993)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] WNP73 is launched in production by 2020/01/23
- [ ] All approvals complete
- [ ] Ready for staff localization in Tier 1
- [ ] Strings extracted for community localization

#### Approvals
- [ ] RASCI A
- [ ] PM

**Comment by cgonz0** [comment]
@amychurchwell First Draft of wnp73 - icons forthcoming

![wnp73.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/e344003c-f25f-4dfe-8de2-c183c7d974a8)

**Comment by ejregithub** [comment]
@amychurchwell - flagging here that the copy is final/approved by Shep and the [copy doc](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit#) is the source of truth.
