### ISSUE TITLE
Add test for modal on /technology

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8437]
## Description

The modal on /technology was updated to use [Protocol](https://github.com/mozilla/protocol) in #8423. We should add a modal test to `tests/pages/technology.py` by importing `tests/pages/regions/modal.py`

**Comment by imskr** [comment]
Can I work on this? @amychurchwell

**Comment by imskr** [comment]
@amychurchwell Should I start working on this?

**Comment by amychurchwell** [comment]
Hi @imskr, you can work on this issue. Thanks for the interest.
Expect slower responses this week and next from the team due to work. 👍

**Comment by imskr** [comment]
Its ok @amychurchwell no problem :)

**Comment by imskr** [comment]
Do I only have to import `tests/pages/regions/modal.py`? @amychurchwell

**Comment by amychurchwell** [comment]
@imskr apologies for the delayed response. Unfortunately, we are unable to mentor this bug but I'd recommend looking at other tests using `from pages.regions.modal import ModalProtocol`.
For now I'm going to close the open PR. :+1:

**Comment by alexgibson** [comment]
The /technology page no longer exists, closing.
