### ISSUE TITLE
Copy for WNP 73

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8441]
The WNP 73 page intended for release with the Firefox rapid release 73 on February 11th will feature content supporting the Firefox as Default Browser campaign.

[Copy doc for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing)

#### Success Criteria
- [x] Copy is attached in final form to this issue
- [x] All approvals complete

#### Approvals
- [x] Brand
- [x] Dev
- [x] RASCI A
- [x] PM

**Comment by rantley** [comment]
@ejregithub Copy for WNP 73
https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing

**Comment by ejregithub** [comment]
Flagging here that the copy is final/approved by Shep and the copy doc is the source of truth.

**Comment by ejregithub** [comment]
As copy is final/approved, I'm closing this issue.
