### ISSUE TITLE
Design for WNP 73

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8442]
The WNP 73 page intended for release with the Firefox rapid release 73 on February 11th will feature content supporting the Firefox as Default Browser campaign.

[Copy doc for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing)

#### Success Criteria
- [ ] Design is attached in final form to this issue
- [ ] All approvals complete

#### Approvals
- [x] Brand
- [ ] Dev
- [x] RASCI A
- [x] PM

**Comment by cgonz0** [comment]
@amychurchwell First Draft of wnp73 - icons forthcoming

![wnp73.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/ef33e1ea-167d-426b-a6e7-761133d263ac)

**Comment by cgonz0** [comment]
Updated Copy - (icons not finalized)
![wnp73_update](https://user-images.githubusercontent.com/29640968/72544585-817f0580-383c-11ea-8110-03edbf5de09b.png)

**Comment by cgonz0** [comment]
@amychurchwell


![browserdefault_privacy_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/b26e4071-1648-411a-afeb-f91de6185e53)

![browserdefault_freedom_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/6412a7e2-07ba-4916-8dfd-39f706795d5d)

![browserdefault_independence_icon.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/71c9ea42-66d1-4b38-95ca-4aeb2a37793b)

![Screen Shot 2020-01-16 at 4.01.31 PM.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/facd0153-6cb5-4694-ba36-29fffbc413ed)

**Comment by amychurchwell** [comment]
@cgonz0 demo URL for design review: https://www-demo5.allizom.org/en-US/firefox/73.0/whatsnew/all/

**Comment by ejregithub** [comment]
@amychurchwell - I'm seeing double CTAs. Which one do I pick?!  ;)

![Screen Shot 2020-01-16 at 8 43 43 PM](https://user-images.githubusercontent.com/20547886/72584946-ea986480-38a0-11ea-9755-c4caf0c5ba57.png)

**Comment by cgonz0** [comment]
> @cgonz0 demo URL for design review: https://www-demo5.allizom.org/en-US/firefox/73.0/whatsnew/all/

@amychurchwell looks great to me!

**Comment by amychurchwell** [comment]
@ejregithub I warned you in slack that a push was happening for the conditional code at that hour! lol 😄 should be correct now.
