### ISSUE TITLE
Extract strings for WNP73, Landing & Thanks pages - default browser campaign

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8446]
Depending on when copy hits as final for each page, separate PRs may be required to extract the strings for each file.

- [Copy doc for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing)
- [Copy for Landing Page](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing) 
- [Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)

**Comment by ejregithub** [comment]
@amychurchwell - all copy is final/approved

- [Copy doc for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing)
- [Copy for Landing Page](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing) 
- [Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)

**Comment by alexgibson** [comment]
I've opened PRs to extract strings for the /thanks/ page here:

https://github.com/mozilla-l10n/langchecker/pull/954
https://github.com/mozilla-l10n/www.mozilla.org/pull/363

**Comment by alexgibson** [comment]
Strings for the /thanks/ page shouldnow be in Pontoon.

**Comment by amychurchwell** [comment]
PRs to extract strings for wnp73 (also covers landing page):

https://github.com/mozilla-l10n/www.mozilla.org/pull/364
https://github.com/mozilla-l10n/langchecker/pull/956
