### ISSUE TITLE
Simplify site.js platform detection logic

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8454]
## Description

We have a global script called [site.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js) that sits in the `<head>` of every web page. This script is used for platform detection, and acts as a hook for displaying the correct link in our download buttons.

Much of the logic in here is from old, legacy code. Some stretching back to the old PHP site. We're likely in a position whereby we can now remove and simplify some of what's here. For example:

- Can we remove the detection for [very old versions of Windows](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L14-L36)? Does the TLS certificate for www.mozilla.org today even support these old clients? how much traffic do we see from them?
- Can we remove [Firefox OS detection](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L68-L70)? This isn't used as a hook anywhere on the site any more, so the answer is likely yes.
- Can we remove detection for [old MacOS versions](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L47-L52)? Also [here](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L62-L67)?.
- Do we still need [64bit detection for Windows](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L164-L167)? This code has never been enabled, since we know it's not always acurate, and the stub installer handles serving 32/64bit binaries much more accurately.

Tidying up some of this old code may help us move toward migrating to [Client Hints](https://github.com/mozilla/bedrock/issues/8440) more easily. Making this script smaller also has performance benefits since it is a blocking request.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Legacy code is removed from site.js

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Results in download buttons being shown to really old clients, even if they may not be able to install / run Firefox.

**Comment by alexgibson** [comment]
Currently clients classed as 'oldwin' and 'oldmac' see a message saying "Your system doesn't meet the requirements to run Firefox." They are prevented from downloading the product entirely.

![image](https://user-images.githubusercontent.com/400117/72620143-a061c280-3936-11ea-8e6d-48c64ef5615f.png)

Removing these checks would mean they fall through to 'other', or unknown status. This results in the message "Your system may not meet the requirements for Firefox, but you can try one of these versions", together with a choice of download buttons.

![image](https://user-images.githubusercontent.com/400117/72620104-9049e300-3936-11ea-9db4-289cae46622f.png)

It can be argued that giving users the choice to try may be a better experience, but it comes at the cost of a potentially wasted download. Still, if we only see a very small amount of traffic from these clients, it may not justify keeping this code around.

**Comment by l-hedgehog** [comment]
>     * Do we still need [64bit detection for Windows](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L164-L167)? This code has never been enabled, since we know it's not always acurate, and the stub installer handles serving 32/64bit binaries much more accurately.

Somewhat related: https://bugzilla.mozilla.org/1564333

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by alexgibson** [comment]
@pmac I'd be interested in your thoughts here, especially around removing the hard-stop "Your system doesn't meet requirements" message.

It looks like refactoring this logic is going to be required in the future (for https://github.com/mozilla/bedrock/issues/8440), so simplifying our use of UA strings ahead of that work may help ease the transition. This may also make creating a simplified download button easier.

**Comment by pmac** [comment]
I'm very much in favor of avoiding the hard-stop and going with the "other" mode where they get the choice. I think it's always possible for that script to get it wrong no matter how good we make it.

**Comment by alexgibson** [comment]
I'm going to make a first-pass at this 👍

**Comment by alexgibson** [comment]
@l-hedgehog I think https://bugzilla.mozilla.org/1564333 could be fixed by the stub installer passing a query param to bedrock to suggest the installer type. Given the brittleness of trying to do that type of detection using UA strings, I think that probably makes the most sense.

**Comment by l-hedgehog** [comment]
> @l-hedgehog I think https://bugzilla.mozilla.org/1564333 could be fixed by the stub installer passing a query param to bedrock to suggest the installer type. Given the brittleness of trying to do that type of detection using UA strings, I think that probably makes the most sense.

@alexgibson Yes, I agree a query param from the stub installer is the right solution there.

**Comment by alexgibson** [comment]
@hoosteeno before making these changes, I'd like to run them past you first. These are useful first steps to simplifying our download buttons.

I'm proposing we tidy up our [site.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js) platform detection logic, specifically:

- Remove the `"Your system doesn't meet the requirements to run Firefox"` message from our download buttons entirely. Instead, unknown platforms will see the message `"Your system may not meet the requirements for Firefox, but you can try one of these versions:"` (see https://github.com/mozilla/bedrock/issues/8454#issuecomment-575653264 for screenshots). The benefit here is that we no longer put a hard stop on anyone trying to download the product, but they still get a warning. This reduces the risk of false positives in our UA detection.
- Remove detection for [ancient Windows versions](https://github.com/mozilla/bedrock/blob/master/media/js/base/site.js#L17-L34). I took a look in GA and these systems combined accounted for 0.03% of our Windows traffic over the last year. I think all this code is doing is increasing the chances of bugs.
- Remove detection for Firefox OS (not used anywhere)
- Remove logic for displaying 64-bit download links on Windows (this code has never been enabled since it's handled better by the stub installer, which is universal).
- Remove logic for detecting Android CPU architecture (this is no longer used anywhere, as we link to the Play Store from download buttons instead).

If you would like to talk about any of these points further, let me know. Thanks!

**Comment by hoosteeno** [comment]
> @hoosteeno before making these changes, I'd like to run them past you first. These are useful first steps to simplifying our download buttons.
> <snip>
> If you would like to talk about any of these points further, let me know. Thanks!

Just following up to say I agree with the recommended changes. Thank you.
