### ISSUE TITLE
Firefox on Facebook

### ISSUE THREAD

**Issue by Casimodo72** [mozilla/bedrock#8457]
Guys, please move your brain around the usual ways of posting bugs in this case if you are interested in fixing firefox stuff.
You have a serious issue with Facebook.
1) I can't find a place to post firefox issues. That's why I post this here. It was the last entry on the first page of Mozilla's projects. So feel free to move this to the appropriate Firefox hub that I couldn't find :-/
2) Firefox on facebook does not really work with untouched settings.
I'm getting blackouts (UI becomes unresponsive), menu entries not being visible, clicking on stuff leading to completely unrelated stuff. E.g. clicking on post does sometimes nothing, sometimes it leads me to completely unrelated stuff, sometimes it works. It sees the UI is off somehow - sometimes. How can this happen? Why are the results of UI actions that random per page refresh?

Sorry for playing the nooby here, but it seems to be a PITA globally and didn't find any panic/reactions yet to fix this. If I could date this: this started all with the announcement of MS to go Chrome. I had no issues before that. What's going on guys, and what's wrong especially with Facebook?

**Comment by alexgibson** [comment]
@Casimodo72 Sorry to hear you're having issues using Facebook. I can't replicate the issues you're describing, and if this was a wide-spread problem I'm pretty sure people would already be working hard to fix it.

This GitHub repository is for bugs relating to the www.mozilla.org website, so I'm going to close this issue. I'd suggest filing a new issue for firefox here: https://bugzilla.mozilla.org/enter_bug.cgi

There are also some useful guidelines for writing bugs [here](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines), which may be useful. The more detailed information you can provide, the greater the chance that someone can work out what's causing your problem.

Best of luck, and sorry you're having a difficulties.

**Comment by Casimodo72** [comment]
@alexgibson : I shouldn't have written my comment :-) I was home, had some wine and really annoyed. As a workaround I'll just switch to an other browser for FB. Thanks for your response though!
