### ISSUE TITLE
Determine the fate of /firefox/features/ pages.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8461]
## Description

The [/firefox/features/](https://www.mozilla.org/en-US/firefox/features/) pages are now old and outdated. They we're also all designed primarily as download/conversion pages, rather than being instructional or informative for existing Firefox users. It's debatable how useful they are in their current state.

We need to decide what to do with them. Either we should decommission them, or commit to updating / maintaining them (porting them to Protocol).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are either decommissioned or ported to Protocol.

**Comment by hoosteeno** [comment]
@stephaniehobson Is the brand team going to update the Features pages? What's the timeline for that?

**Comment by stephaniehobson** [comment]
It's on our wishlist but I wouldn't expect any movement on it before June.

**Comment by hoosteeno** [comment]
In https://github.com/mozilla/bedrock/issues/8581 we will produce some light design enabling this to move to Protocol (without a major content refactor) in Q2.

**Comment by hoosteeno** [comment]
Design and code work for this are captured in the epic card at https://github.com/mozilla/bedrock/issues/8686. Closing this.
