### ISSUE TITLE
Eliminate /concerts 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8465]
## Description

There is no indication that the series will continue. We should eliminate the content at https://www.mozilla.org/firefox/concerts/, including any templates, template-specific helpers, template-specific javascript, template-specific CSS.

@rraue , please specify whether this should be a redirect (and to what?) or a 404.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Concerts content is no longer served by www.mozilla.org.
- [ ] Requests get appropriate response (look for @rraue guidance)

**Comment by craigcook** [comment]
hmm... in addition to the page itself, there was also a bunch of back-end logic to handle signing into bedrock via FxA. We may want to preserve that capability in some form, though it would need some refactoring to make it generic and not so concert-specific. Or we could just rip all that out and if we need to use FxA auth again in the future we can add it back.

**Comment by rraue** [comment]
Thats a 404, we do not even have a far fetched equivalent page so a redirect wouldnt benefit any user.

**Comment by craigcook** [comment]
@pmac Any thoughts on trying to preserve the FxA Oauth stuff in some form? The more I look at it, it seems like it's mostly concert-specific (e.g., [lots of stuff for the basket RSVP mixed in](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/views.py#L192)) so I'm thinking rather than refactor it might be simpler to remove it all and re-implement it cleanly if/when we need Oauth again in the future.

**Comment by hoosteeno** [comment]
I am in favor of removing and reimplementing if needed. First, because FxA infrastructure has evolved since this was written. Second, because the reason to remove this content now is to avoid augmenting the FxA integration with a handler for Delete User events (which is newly required in 2020).

**Comment by craigcook** [comment]
> I am in favor of removing and reimplementing if needed. First, because FxA infrastructure has evolved since this was written. Second, because the reason to remove this content now is to avoid augmenting the FxA integration with a handler for Delete User events (which is newly required in 2020).

Good point. In that light, it's much better to remove it all now rather than put any effort into updating something we don't even need.

**Comment by pmac** [comment]
I'm also +1 for removal. 💥
