### ISSUE TITLE
Code - Update Icons in modules on the 'default browser' campaign pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8468]
## Description

Design updates, image files, are being created for the modules in the lower sections of the pages supporting the 'default browser' campaign.

These are
- The WNP73
- https://www.mozilla.org/firefox/set-as-default/

---

#### Success Criteria 
- [ ] Icons are updated and live

#### Approvals
- [ ] Brand
- [ ] Team Lead

**Comment by hoosteeno** [comment]
Blocked by design: https://github.com/mozilla/bedrock/issues/8469

**Comment by cgonz0** [comment]
this is ready - see design issue [8768](https://github.com/mozilla/bedrock/issues/8768)
in addition to whats new page icons, includes default browser campaign icons.

**Comment by Errolyn** [comment]
This is blocked until assets are added to protocol.

**Comment by maureenlholland** [comment]
The icons on the referenced page are coming through Protocol, so I'm assuming this is completed

<img width="409" alt="Screenshot 2023-03-29 at 5 12 49 PM" src="https://user-images.githubusercontent.com/19650432/228601545-96b5ad04-5683-4edf-b2db-aded4a120c35.png">
