### ISSUE TITLE
Design - Update Icons in modules on the 'default browser' campaign pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8469]
## Description

Design updates, image files, are being created for the modules in the lower sections of the pages supporting the 'default browser' campaign.

These are
- The WNP73
- https://www.mozilla.org/firefox/set-as-default/

---

#### Success Criteria 
- [x] Icons are provided to developer for coding

#### Approvals
- [ ] Brand
- [ ] Team Lead

**Comment by cgonz0** [comment]
[browserdefault_landing.zip](https://github.com/mozilla/bedrock/files/4105988/browserdefault_landing.zip)

![default browser_set-as-default - landing page_update - new icons](https://user-images.githubusercontent.com/29640968/73031367-bcf77200-3df0-11ea-929e-e63ebcd170a0.png)



[wnp73.zip](https://github.com/mozilla/bedrock/files/4105994/wnp73.zip)

![wnp73_update_new icon](https://user-images.githubusercontent.com/29640968/73031481-1a8bbe80-3df1-11ea-81d8-95c65ec03043.png)

**Comment by hoosteeno** [comment]
@cgonz0 is this design task done? If so, do you mind creating a coding issue in the "ready" column with clear specs for a coder?

**Comment by cgonz0** [comment]
@hoosteno this is currently on hold as brand is exploring icon work. should this go into the backlog in the meantime?

**Comment by ejregithub** [comment]
@cgonz0 - can you indicate progress on the Brand side for these icons and if direction for changing them now exists or will soon?

**Comment by cgonz0** [comment]
@ejregithub we are almost done with brand icon work. i can predict sometime next week we can start replacing these, however - the update isn't isolated to the pages mentioned in this issue. they will include previous whats new pages plus previous moments pages. so, should we scrap this one and create a more comprehensive issue instead?

**Comment by cgonz0** [comment]
icons above are now out of date - see new issue [8768](https://app.zenhub.com/workspaces/wmo-scrumban-59bd527821e82e515786ca73/issues/mozilla/bedrock/8768)

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by maureenlholland** [comment]
closing as this was ultimately moved to a protocol issue: https://github.com/mozilla/protocol/issues/575
