### ISSUE TITLE
Remove ContributorActivity model and contributor-data/ URL

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8471]
Along with the `update_tableau_data` management command. These things are no longer used. They updated data for a JSON endpoint like https://www.mozilla.org/contributor-data/github.json, but all of those URLs return empty JSON objects now.

@alexgibson do you agree, or is there some plan to revive this?

**Comment by alexgibson** [comment]
Huh, I had no idea this was a thing. Was this used for the old mozilla logo prototype that was never used? If that's the case, then yeah let's remove it 👍

**Comment by pmac** [comment]
It was that plus some numbers on an old home page and the main old contributor page IIRC. Sounds good. Adding it to the PR of removal :) 💥

**Comment by alexgibson** [comment]
We still have contributor number here, but I'm not sure where that comes from: https://www.mozilla.org/en-US/contribute/
