### ISSUE TITLE
WNP73 - string changes, legal requirement

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8475]
## Description

3 strings need to be updated in the WNP 73.0 webpage. These strings must be changed - so if we can wrap them to show en-US copy in all locales until the other locale strings can be updated that would be best.

String One:

The current copy reads:

"The internet keeps finding new ways to poach your personal data. Firefox is the only browser with a mission of finding new ways to protect you."

The new copy needs to be:

"Companies keep finding new ways to poach your personal data. Firefox is the browser with a mission of finding new ways to protect you."

---

String Two:

The current copy reads:

"Firefox is fast and safe on Windows, iOS, Android, Linux...and across them all. We have no interest in locking you in or resetting your preferences."

The new copy needs to be:

"Firefox is fast and safe on Windows, iOS, Android, Linux...and across them all. You deserve choices in browsers and devices, instead of decisions made for you."

---

String Three:

The current copy reads:

"Firefox is the only major independent browser. Chrome, Edge and Brave are all built with code from Google, the world’s largest ad network."

The new copy needs to be:

"Firefox is the only major independent browser. Chrome, Edge and Brave are all built on Google code, which means giving Google even more control of the internet."

**Comment by alexgibson** [comment]
L10n PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/365
