### ISSUE TITLE
Add a link tile to /features for the browser comparison hub

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8485]
## Description

We need to add a link tile on the features page to link to /firefox/browsers/compare/ so this pages aren't orphaned and has better chances for SEO. The feature page isn't very up to date but the link will count right now until we get a chance to redo the whole feature page.

![Screenshot 2020-02-05 at 16 13 00](https://user-images.githubusercontent.com/36700618/73854447-de198300-4832-11ea-89f1-1dac4dc22e98.png)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The update is online

#### Tasks
- [x] An icon
- [x] Link copy
- [ ] Add tile and link it on all locales to /firefox/browsers/compare/

**Comment by hoosteeno** [comment]
This is a way to create an SEO outcome, which means the style and location and usability of the link are not very important. True? So a hasty addition for now would be adequate?

**Comment by rraue** [comment]
Exactly, I suggest nonetheless that we integrate it as its own tile like the other tiles.

**Comment by hoosteeno** [comment]
Design for this link will appear in https://github.com/mozilla/bedrock/issues/8581.

**Comment by cgonz0** [comment]
@rraue  as discussed, we can add this link tile & icon while we're awaiting /features to be ported into protocol with a new design. (please note, this "new" icon is off-brand and only to be used in the interim).

![browser_icon_offbrand.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/41ff32d1-88d0-41ad-88bd-167b04bcdfc9)

![features_linktile2.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/bf2c2829-63d8-4382-adbf-b48c5290503f)
