### ISSUE TITLE
Fennec Nightly download links are 404

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8486]
## Description

Download links on mozorg for Fennec Nightly are 404.

### Steps to reproduce

1. Navigate to https://www.mozilla.org/en-US/firefox/all/#product-android-nightly
2. Click "Download Now"

### Expected result

A file download

### Actual result

404:
- https://download.mozilla.org/?product=fennec-nightly-latest&os=android&lang=multi
- https://download.mozilla.org/?product=fennec-nightly-latest&os=android-x86&lang=multi

### Environment

N/A

**Comment by jbuck** [comment]
For now, we've decided to restore the objects

**Comment by alexgibson** [comment]
@jbuck thanks - I'll close this issue, but we'll open a new issue to discuss how / when we can switch over from Fennec to Fenix.
