### ISSUE TITLE
Newsletter preferences Thank You page update - DESIGN

### ISSUE THREAD

**Issue by cgonz0** [mozilla/bedrock#8499]
## Description

Refer to [#7324](https://github.com/mozilla/bedrock/issues/7324)

---

#### Approvals
- [x] Brand
- [x] Team Lead

**Comment by cgonz0** [comment]
![newsletter_thank you_cards_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/8399fa9e-2f94-4822-b9da-df6ab8bb2e23)

**Comment by ejregithub** [comment]
@cgonz0 - please flag @hoosteeno when the design updates are ready for TL review

**Comment by cgonz0** [comment]
@hoosteeno brand review done- your turn, please.

**Comment by hoosteeno** [comment]
This is a big improvement over [the current copy and design](https://www.mozilla.org/newsletter/updated/)! Nice work.

One change I suggest: The Mobile CTA should mention the app it refers to, and should not say "Download". It is probably simplest to keep the link text from the current Mobile CTA: "Get Firefox for mobile".

**Comment by cgonz0** [comment]
[newsletter_thankyou_assets.zip](https://app.zenhub.com/files/1616665/b82fd28a-90b3-4c77-9986-a5b157160f51/download)

[Sketch file](https://share.goabstract.com/c14c351e-0d8e-44ac-9604-b1b6501eaf69?sha=720adce9ae4c11791560f51d9943225950415f54l)


![1312 - FINAL Design.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/3fe014a7-0701-458b-924c-2deb620c66ae)

![480 - FINAL Design.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/7b0f5f71-c646-40a2-8ffd-ef67a0e16775)
