### ISSUE TITLE
Dot on channel page only in Chrome

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8501]
## Description

There's a weird lonely dot hanging out on the channel page.

### Steps to reproduce

Open: https://www.mozilla.org/en-US/firefox/channel/desktop/ in Chrome

Scroll down:
<img width="581" alt="Screen Shot 2020-02-10 at 15 58 43" src="https://user-images.githubusercontent.com/854701/74201336-4fd04300-4c1e-11ea-8cd9-01a1e01429bb.png">

### Expected result

No dot.

<img width="618" alt="Screen Shot 2020-02-10 at 15 59 58" src="https://user-images.githubusercontent.com/854701/74201383-6e363e80-4c1e-11ea-8ef5-20a1e6b1fadb.png">

### Actual result

Dot.

### Environment

Mac OS and Chrome.

**Comment by craigcook** [comment]
It's a stray list marker. The picto card macro defaults to `li` as the base element but in this case it doesn't have a `ul` parent so it's not getting the global `list-style: none;` styling. Chrome evidently adds bullets to `li` elements when it doesn't know how else to treat them (Firefox seems to treat them as nothing; `li` isn't valid HTML without a parent `ul` or `ol`). 

Switching the macro call to a `div` or `section` should fix the bug and also be valid and more semantically correct.

**Comment by ishantd** [comment]
Hi sorry for making a pull request before mentioning it here.
If it's okay, please review it. Thanks.
