### ISSUE TITLE
Update hreflang x-default

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8513]
## Description

We right now set the x-default in our hreflang-setup to the en-US url. We should change this so crawlers can "understand" our language based redirects and crawl all possible locales to the non locale url.

So mozilla.org/en-US/ and mozilla.org/fr/ and all other locales will have x-default set to mozilla.org/ and mozilla.org/en-US/firefox/lockwise/ and mozilla.org/pl/ and all other locales will have x-default set to mozilla.org/firefox/lockwise/.

We should do this for all our urls even the ones without any other locale then /en-US/ to stay consistent.

- Remove locale from meta data

**Comment by alexgibson** [comment]
@rraue does this look correct to you? https://www-demo5.allizom.org/en-US/

**Comment by rraue** [comment]
Yes it does exactly what it should 👍
