### ISSUE TITLE
Default homepage picto card responsive styles bug.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8515]
## Description

![Screen Shot 2020-02-12 at 9 01 57 AM](https://user-images.githubusercontent.com/30483988/74358589-8f11a780-4d76-11ea-9d19-9766516ad77a.png)

Picto card list items break formation at certain screen widths.
example: https://www.mozilla.org/hi-IN/

**Comment by alexgibson** [comment]
On closer inspection this seems to be a float clearing issue with the content above, rather than an issue with the picto card styles themselves. Giving the section directly above a class name like `impact-innovations` and then clearing the floated content in that section should force the picto cards to wrap onto the next line:

```css
.impact-innovations {
    @include clearfix;
}
```

**Comment by mitchell-frost** [comment]
Hey! I am new to mozilla. Can I work on this?

**Comment by codebreakeragr8** [comment]
@amychurchwell @alexgibson Hey! If this issue is still open then i would like to work on it.

**Comment by alexgibson** [comment]
@codebreakeragr8 @mitchell-frost thanks for showing interest in this bug. Pull requests are always welcome, and contributing docs are here: https://github.com/mozilla/bedrock/blob/master/.github/CONTRIBUTING.md

**Comment by Rudresh22** [comment]
Hello sir, I want to work on this issue. It would be great if you could guide me through this.

**Comment by craigcook** [comment]
Sorry, this is already being worked on (I hadn't seen this issue when I opened the PR). It'll be fixed with https://github.com/mozilla/bedrock/pull/9089

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/9089
