### ISSUE TITLE
Firefox Lite promotional hero for Indonesian users on the homepage.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8516]
## Description

Implement a Firefox Lite promotional hero for Indonesian users on the homepage.
https://www.mozilla.org/id/

---

#### Tasks
- [ ] Collaborate with Firefox Lite team on design and assets.
- [ ] Get localized copy.
- [ ] Code page.

**Comment by Aayushap1** [comment]
I want to work on this issue plz assign this issue to me

**Comment by alexgibson** [comment]
Lite is being EOL'd, closing.
