### ISSUE TITLE
Determine fate of /etc/firefox/retention/ pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8536]
## Description

The following legacy pages are built using Pebbles. We should decide if we want to keep them around or not.

- https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-a/
- https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-b/
- https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-referral/

Looking in GA I see some traffic, but it's pretty sporadic. My guess is from snippets.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are either decommissioned or updated to use Protocol as a base.

**Comment by alexgibson** [comment]
@hoosteeno can you update here with the proposal for these pages? Thanks

**Comment by hoosteeno** [comment]
Let's keep thank-you-a and redirect both of the others to that one. We should get thank-you-a onto protocol. Does that require new designs? If so, we can file a design and code epic for thank-you-a.

**Comment by alexgibson** [comment]
The page is already a snowflake, and receives relatively little traffic. I don't think it's worth creating an epic for this with a redesign.
