### ISSUE TITLE
WNP 74 - Design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8544]
Create designs for the WNP 74 page within the constraints of available templates/components

2020-03-10 is the release date for WNP 74 We need the page live for QA on 2020-03-02

###Success Criteria
- [ ] Design is complete in time for 2020-03-02 page launch
- [ ] FB container is the main content for the WNP 74

###Approvals
- [x] Brand (Clio)
- [ ] Team Lead (Hoosteeno)
- [ ] Approver/Accountable (MWarther)

**Comment by cgonz0** [comment]
![WNP 74 - EN DE.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/f61d42c4-8cf2-42fc-af44-87bdacec1ce2)![WNP 74 - FR.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/1778bbb3-484e-4776-b1a3-c86cfe99a4f1)![WNP 74 - RoW.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/5e221c35-746f-481c-ba32-a3aa912b18dc)
