### ISSUE TITLE
(02-26-2020) WNP 74 - Copy

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8545]
Write copy for the WNP 74 page in cooperation with design #8544

Use this [Copy Doc](https://docs.google.com/document/d/14kMX3dSG10xS0UseMPjkYZPUJCB8BDVsJPBJdeYQemo/edit)

2020-03-10 is the release date for WNP 74. We need the page live for QA on 2020-03-02

###Success Criteria
- [x] Copy is final/approved on 2020-02-26
- [x] MVB/Copy is shared with Staff for DE & FR

###Approvals
- [x] Brand (Natalie)
- [x] Team Lead (Hoosteeno)
- [x] Approver/Accountable (MWarther)

**Comment by rantley** [comment]
RND 1 copy https://docs.google.com/document/d/14vJmsevrc6fac8IMZMRzPruhEcSZtMDlPyGNSzP3Mwg/edit#

RND 2 WIP 
https://docs.google.com/document/d/14kMX3dSG10xS0UseMPjkYZPUJCB8BDVsJPBJdeYQemo/edit?usp=sharing
