### ISSUE TITLE
(3-2-2020) - WNP 74 - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8546]
## Description

Code the WNP for the 74 product release on 3/10/20

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live on 2/28

#### Approvals
- [ ] Brand
- [ ] PMM (TBD)
- [ ] Team Lead
- [ ] Accountable stakeholder
- [ ] Legal

**Comment by craigcook** [comment]
Demo: https://www-demo3.allizom.org/firefox/74.0/whatsnew/all/

**Comment by hoosteeno** [comment]
We need...

* icons (@cgonz0 ?)
* final copy in en (@rantley ?)
* final copy de/fr (@ejregithub ?)
* an analytics review (@hoosteeno )
