### ISSUE TITLE
Port Facebook Container page to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8554]
## Description

The page at `/firefox/facebookcontainer/` is built using Pebbles and needs porting to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production to use Protocol.

#### Tasks
- [ ] Update template & scss.
- [ ] Update tests?

**Comment by hoosteeno** [comment]
This page is not beautiful now.

**Comment by hoosteeno** [comment]
See also: https://github.com/mozilla/bedrock/issues/5766
