### ISSUE TITLE
(3-13-2020) Estimate effort of building firefox.com

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8561]
## Description

Top of mind awareness goal [+X% YOY] in T1 [Shared] | By 2020-03-13, present likely engineering effort of building www.firefox.com to inform the pitch provided by NA Brand/Content.
-- | --

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Current pitch for firefox.com contains sections summarizing likely effort, and describing preferred technical approach

**Comment by hoosteeno** [comment]
This is underway in [a (Mozilla confidential) document](https://docs.google.com/document/d/1LfhppxqF_qkKx-znHBMlsTzVclHgzskUa41XDwWODXA/edit#).
