### ISSUE TITLE
(2020-03-24) WNP 75 Copy

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8562]
2020-04-07 is the release date for WNP 75. We need the page live for QA on 2020-03-30

###Success Criteria
- [ ] Copy is final/approved on 2020-03-24
- [ ] MVB is shared with Staff for DE & FR

###Approvals
- [ ] Brand (Natalie)
- [ ] Team Lead (Hoosteeno)
- [ ] Approver/Accountable (MWarther)

**Comment by hoosteeno** [comment]
We need copy and design for 3 journeys:

1. User is not logged into Firefox or Sync: User is shown a "mobile-forward Sync pitch" that takes them through accounts setup flow and ends at FxA's SMS form (https://accounts.firefox.com/sms/). Subcontent ideas: Lockwise + Sync, Send Tabs, Browsing History. CTA ideas: "Start Syncing" or something better. 

2. User is logged in to Firefox or Sync but has 0 mobile device synced: User is shown a "mobile-forward Sync pitch" that takes them to FxA's SMS form (https://accounts.firefox.com/sms/). Subcontent ideas: Lockwise + Sync, Send Tabs, Browsing History. CTA ideas: "Start Syncing" or something better.

3 - ser is logged in to Firefox or Sync and has >0 mobile device synced: User is shown a Monitor CTA. Prior copy OK here; new details about “Resolve your own breaches” would be good to add. Subcontent ideas halfway down on https://monitor.firefox.com/. CTA idea "Check your breach report" as on https://www.mozilla.org/en-US/firefox/welcome/1/.

Sync journeys should get some minimal art in the CTA area depicting “synchronizing” -- see https://accounts.firefox.com/sms for reference. Doesn’t need to have motion.
Monitor journey can get art too, if we can find it.

**Comment by rantley** [comment]
Draft copy here https://docs.google.com/document/d/1FHXQA89Rqawig0se7J0RFANHmTeK2XGYAVJ0GJa3Imo/edit#
