### ISSUE TITLE
WNP75 Design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8563]
Theme is TBD for this page

2020-04-07 is the release date for WNP 75. We need the page live for QA on 2020-03-30

###Success Criteria
- [x] Design is complete in time for 2020-03-30 page launch

###Approvals
- [x] Brand (Clio)
- [x] Team Lead (Hoosteeno)
- [x] Approver/Accountable (MWarther)

**Comment by hoosteeno** [comment]
We need copy and design for 3 journeys:

1. User is not logged into Firefox or Sync: User is shown a "mobile-forward Sync pitch" that takes them through accounts setup flow and ends at FxA's SMS form (https://accounts.firefox.com/sms/). Subcontent ideas: Lockwise + Sync, Send Tabs, Browsing History. CTA ideas: "Start Syncing" or something better. 

2. User is logged in to Firefox or Sync but has 0 mobile device synced: User is shown a "mobile-forward Sync pitch" that takes them to FxA's SMS form (https://accounts.firefox.com/sms/). Subcontent ideas: Lockwise + Sync, Send Tabs, Browsing History. CTA ideas: "Start Syncing" or something better.

3. User is logged in to Firefox or Sync and has >0 mobile device synced: User is shown a Monitor CTA. Prior copy OK here; new details about “Resolve your own breaches” would be good to add. Subcontent ideas halfway down on https://monitor.firefox.com/. CTA idea "Check your breach report" as on https://www.mozilla.org/en-US/firefox/welcome/1/.

Sync journeys should get some minimal art in the CTA area depicting “synchronizing” -- see https://accounts.firefox.com/sms for reference. Doesn’t need to have motion.
Monitor journey can get art too, if we can find it.

**Comment by cgonz0** [comment]
![WNP75_mockup_reg.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/e73886e8-bc69-42e2-bf7d-df9aa7af79e8)
