### ISSUE TITLE
Moments 6 page - Default Browser - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8569]
This Moment page is to built from the content in WNP 73 that features information about selecting Firefox as one's default browser. 

https://www.mozilla.org/firefox/73.0/whatsnew/all/

**Comment by ejregithub** [comment]
@Errolyn - can you investigate how l10n will need to be handled here?  Tier One are required, Tier Two are 'should have' depending where this lands with the new l10n system (community or agency localizing) and the remaining are at the kindness of the communities.

We have all the required content in /mozillaorg/firefox/whatsnew_73.lang/ but will need to include the strings standard to the Moments pages including 'Join Firefox' in the top nav and 'Why am I seeing this page?' at the bottom of the page.

**Comment by Errolyn** [comment]
I will look into when I get in, in the morning. When do we need this done by?

**Comment by Errolyn** [comment]
I think we have a couple of options:

1. Write a small script to copy all of the locals already active to new lang files then do the normal string extraction process we would do to add new strings. This would keep our lang files separate.

2. Use the same .lang file for both pages and add the new strings we need.

3. From my understanding fluent has a way to handle this already? but I'm not 100% sure if the system is ready for us to make use of it yet. @alexgibson would have more info on that I think.
