### ISSUE TITLE
Moments 6 page - Default Browser

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8571]
This Moment page is to built from the content in WNP 73 that features information about selecting Firefox as one's default browser. The content from that page will be inserted into the Moments page template

https://www.mozilla.org/firefox/73.0/whatsnew/all/

**Comment by ejregithub** [comment]
This content in the Moments page template layout has been approved.

@cgonz0 - The item missing here is the Firefox logo in the hero section

![Screen Shot 2020-03-02 at 5 25 04 PM](https://user-images.githubusercontent.com/20547886/75736367-e047f380-5cb1-11ea-893c-46540bf05196.png)

**Comment by alexgibson** [comment]
https://www.mozilla.org/en-US/firefox/welcome/6/
