### ISSUE TITLE
Design for Enterprise funnel

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8577]
The page at www.mozilla.org/firefox/enterprise serves a variety of download intents with a lot of links. Several of those links need to be improved. This issue describes a list of problems to solve. We can solve these with quick fixes to links, but before doing so, let's have a designer review the page for more elegant (but still efficient) improvements.

This page must:

* Attract and handle organic traffic looking for variations on "esr", "enterprise" and (sometimes) "msi"
* Help people download Firefox Desktop (any platform), Firefox ESR (any platform), Firefox MSI (windows platform), and Firefox PKG (mac platform) installers
* Make those downloads *measurable* if possible
* Link people to lots of platform-specific install instructions

We need to accomplish the following:

Design:
* A light design for [the "Download" section](https://www.mozilla.org/en-US/firefox/enterprise/#download) that distinguishes download _actions_ from content link clicks
* Note: MSI, PKG, and ESR downloads are actually links to e.g. /firefox/all page. Should they be buttons here, or links? 

Reviews
- [ ] Team Lead
- [ ] Dev TBD

**Comment by ejregithub** [comment]
@justinkropp - can you please apply an Estimate for your work in this card?  LMK if you need some guidance to doing so.

**Comment by justinkropp** [comment]
@ejregithub Yes, I need some guidance. I don't know how to apply estimates in github and I don't know where this card lives?

**Comment by justinkropp** [comment]
![fx-enterprise-1312 update.png](https://images.zenhubusercontent.com/5e3b061054691a8602dab50b/a09ff11d-6c3f-44d5-9a40-8ecadd22b606)

I've updated the design of the Enterprise page. The biggest change on the page is the treatment of the downloads section, which now consists of the following:

- a drop-down button that will allow the user to trigger a download of whatever configuration/installer they're after.
- a "Support" section under each platform that has the same links that currently exist on the page
- 2 additional links under this "Support" section: a _Release notes_ link and a _Enterprise support_ link

Including these 2 additional inks allows us to get rid of the big "Enterprise resources" section that currently exists on the page.

Some additional changes I would like to see on this page, if possible, are the following:

- update the Firefox browser logo in the hero section to the Firefox enterprise browser logo
- get rid of the sub-navigation jump link menu
- update the copy in the main hero section cta to be more explicit

**Comment by hoosteeno** [comment]
@justinkropp I like this direction as a fix. Great work.

I have asked in Slack for a dev review.

**Comment by hoosteeno** [comment]
@justinkropp Are the dropdowns in this design part of Protocol? If not, can you file the necessary issues to make them part of Protocol, and bring that conversation into the next Protocol meeting?

**Comment by hoosteeno** [comment]
@craigcook can you mark this complete when you are satisfied that it depicts a feasible solution?

**Comment by craigcook** [comment]
I think it's feasible right now. We'll settle on the specific styling of the menu list in Protocol, so the final look of the dropdowns may differ from this mockup.
