### ISSUE TITLE
Code for Enterprise page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8578]
Development:
* Implementation of designs provided above
* Links to things that can be downloaded from our site should go to the place on our site where you can download them (e.g. all MSI links, ESR links should go to /all)
* Links to actual downloads should be instrumented to be measurable -- this may mean simply using the standard download button macros on release download links.
* UTM parameters on all referrals other *.mozilla.org sites (e.g. SUMO, ftp) which appear all over the page: `utm_source=mozilla.org-enterprise&utm_medium=referral&utm_campaign=enterprise`
* .lang strings extracted (or, possibly, Fluent configuration) so this page is localizable by community
* Food for thought: Should we augment [/all page logic to allow pre-population of MSI downloads from links on /enterprise](https://github.com/mozilla/bedrock/blob/9a309cacbc5bf9494003313b5845aca3663f8db0/bedrock/firefox/templatetags/helpers.py#L258-L269)?

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Enterprise page distinguishes between actions and links in the download section
- [ ] Enterprise page includes appropriate links to downloads, on www wherever possible
- [ ] Enterprise page links to owned external sites include UTM parameters
- [ ] All actual downloads occurring on Enterprise page are measured
- [ ] Strings are localizable

**Comment by hoosteeno** [comment]
Design is nearly complete in https://github.com/mozilla/bedrock/issues/8577. Moving this to "ready".
