### ISSUE TITLE
Only show nightly down if ?channel=nightly on firefox/installer-help/ 

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8579]
## Description

Users arriving on firefox/installer-help/ from the nightly channel should be shown the Firefox nightly download button instead of all of the download buttons. Like we do for the other channels.

[beta](
https://www.mozilla.org/en-US/firefox/installer-help/?channel=beta&installer_lang=en-US)
![Screen Shot 2020-02-21 at 2 47 47 PM](https://user-images.githubusercontent.com/30483988/75077985-38fcdc80-54b9-11ea-9bac-5ef866bfb378.png)

[nightly](
https://www.mozilla.org/en-US/firefox/installer-help/?channel=nightly&installer_lang=en-US)
![Screen Shot 2020-02-21 at 2 47 36 PM](https://user-images.githubusercontent.com/30483988/75077988-39957300-54b9-11ea-87cc-da7588483e2d.png)

**Comment by alexgibson** [comment]
Related code: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L46

Incidentally, looking in GA I also see `?channel=aurora`, which I'm guessing (?) is for dev edition.

**Comment by imskr** [comment]
Would like to fix this issue 🔧

**Comment by amychurchwell** [comment]
@alexgibson it looks like `?channel=alpha` currently shows dev edition. While the [aurora channel no longer exists](https://wiki.mozilla.org/Firefox/Aurora), I confirmed with the installer team that `aurora` is a name still used for dev edition, so I will update that. Not sure what alpha is.

**Comment by amychurchwell** [comment]
@imskr thank you for the offer, but I am going to pick up this issue! 🙂
