### ISSUE TITLE
Design: Produce comps for migrating /features to Protocol (deadline: 2020-03-20)

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8581]
## Description

We want to migrate the /features section to Protocol. We need a light design process that specifies the right way to deliver a Protocol version of the index and item pages. 

This is a Q1 KR; we committed to complete it by 2020-03-20.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] This issue is resolved by 03/20/20
- [ ] Design comps for index and item pages are reviewed and approved by devs
- [x] Comps are attached to this issue
- [x] Code issue is filed

**Comment by alexgibson** [comment]
One thing to consider here is our goal for removing Pebbles. If we do v2, which adds new strings, then we'll need to keep the old page around until locales all have the new page translated.

This means we'll be stuck with the old page for some time, unless we commit to porting the legacy page to Protocol as well - but this then doubles the work.

**Comment by alexgibson** [comment]
This is supposed to be completed by tomorrow (according to our Q1 KR at least).

Which versionare we choosing, and is both design and copy final?

**Comment by hoosteeno** [comment]
Thanks Alex.

@dzingeek we are blocked proceeding here on a decision about whether the brand team will undertake a more comprehensive redesign of this page in 2020. 

* If yes, we should make the v1 (no copy) update here
* If no, we should make the v2 (yes copy) update here

@cgonz0, are these designs approved and ready to go? If not, can we get them through that today?

**Comment by dzingeek** [comment]
@hoosteeno Just talked with Clio and the answer is _No_, this will **not** be a priority for us so please move forward with v2. 

Also I will talk with @cgonz0 today about the design feedback.

**Comment by cgonz0** [comment]
@hoosteeno - the layout is pretty much set and approved. the only forthcoming changes will be with assets and copy. if we can start getting the page laid out with some placeholders - i will work on getting the icons and hero img finalized while @rantley works on copy.

**Comment by hoosteeno** [comment]
@cgonz0 can you explain what you mean by "get the page laid out" ? 

Right now we need approved designs for /features and a /features sub-page, following along with the v2 above.

**Comment by hoosteeno** [comment]
@cgonz0 do you think we could close this issue with the final design? https://github.com/mozilla/bedrock/issues/6134

**Comment by cgonz0** [comment]
> @cgonz0 can you explain what you mean by "get the page laid out" ?
> 
> Right now we need approved designs for /features and a /features sub-page, following along with the v2 above.

sorry if i wasn't clear - i meant laid out on the dev side with placeholder copy/images and such.
v2 design is approved, but new assets will be created next week to replace some of the icons shown here and hero image. we need copy as well.

**Comment by cgonz0** [comment]
[**Sketch file**](https://share.goabstract.com/60a8b54f-546d-4965-90c4-200ce17a0206?sha=78e983fb9b575e6ea69904b7457febf169e2a14f)
/Features page and subpage layout - responsive & specs included

[**assets**](https://app.zenhub.com/files/1616665/3d9415db-52b5-4e2b-a06f-841cc63abc52/download)
hero img and icons

[**copy doc**](https://docs.google.com/document/d/1vt8q2TH3TYz2NHVZ_8WqvBnZjw0SIT3vPTx2tXOUJvA/edit?ts=5e836795)

-----------


![fx-features-1312 FINAL.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/8cd72612-8c8d-4bdb-b2b5-76ff7fd424ec)

![fx-features-item page FINAL.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/5c2287eb-197f-4cc9-8d8e-ff1315b7ebd7)

**Comment by rraue** [comment]
One small tweak on the copy would benefit SEO: The last link says "Compare Firefox" but it would be better go with "Browser Comparison".
