### ISSUE TITLE
Messaging when updating dev edition directed at new users instead of existing.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8592]
## Description

The copy when updating developer edition is talking to new users, not existing users.
![image](https://user-images.githubusercontent.com/30483988/75294216-ad4abf00-57dc-11ea-844c-380deb8385ca.png)

example: https://www.mozilla.org/en-US/firefox/73.0a2/whatsnew/all/?oldversion=72.0

[Separating this issue from #7488]

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by alexgibson** [comment]
Looks like this was fixed: 

![image](https://user-images.githubusercontent.com/400117/123423521-8e6a6180-d5b7-11eb-8b6f-ae35114c61fa.png)
