### ISSUE TITLE
Port firefox/switch page to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8595]
## Description

The L10n team would like to run a second test for the vendor pipeline, so we've settled on porting the [firefox/switch](https://www.mozilla.org/en-US/firefox/switch/) page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production to use Fluent for translation.

#### Tasks
- [ ] Migrate .lang files to .ftl
- [ ] Migrate template.
- [ ] Expose strings.

**Comment by Pike** [comment]
First step, create recipe ;-)

**Comment by alexgibson** [comment]
note to self: https://bedrock.readthedocs.io/en/latest/fluent-conversion.html

**Comment by alexgibson** [comment]
@peiying2 has asked if we can re-run this migration using placeholders for brand names. Re-opening.
