### ISSUE TITLE
Experiment: sticky navigation on /firefox

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8600]
## Description
Hypothesis: If we make the global navigation a sticky navigation, CTA clicks in global nav CTA will increase.

## Test Plan
https://docs.google.com/document/d/1eja21ZlEJQfi-9jjWUhxx1zD6Gnm5EeaGMR8BZBIOP8/edit?usp=sharing

#### Tasks
- [x] Put proposed nav on demo for design review.
- [x] Code experiment for final review.

#### Demo
https://www-demo-demo-nav-sdavucfmzlyu.herokuapp.com/en-US/exp/firefox/

**Comment by amychurchwell** [comment]
@stephaniehobson or @alexgibson would either of you be able to review the draft of this experiment on convert? (ID 10034124)

**Comment by alexgibson** [comment]
Link to experiment summary for posterity: https://app.convert.com/#/projects/1003343/summary/10034124

**Comment by alexgibson** [comment]
Some initial review feedback:

- Is there a test plan for this experiment, I can't seem to find one linked here?
- I think I managed to fix the preview links by changing the editor URL to point to stage (I had to manually copy over the CSS code as I initially clicked the wrong thing (sorry), hope I did that ok?)
- Traffic distribution for the experiment is set to 24%. Should this be 100%? I'm guessing we need to redirect 24% of traffic from /firefox/ to /exp/firefox/?
- Should we add bounce rate as a secondary goal perhaps? (I'm guessing more people might end up navigating to a different page?)
- Would it be worth adding a vertical media query, to stop the nav taking over on smaller desktop screens?
- The goal for "Click: Download button in navigation on /firefox" is set as "Site Wide". Should it be specific to /firefox?
- The same goal is set to track clicks on `#protocol-nav-download-firefox`, but the actual download link is a child of that element. Should it be something more specific? e.g. `DIV#protocol-nav-download-firefox .download-list > li > a.download-link`?

**Comment by alexgibson** [comment]
Another thing that may be worth exploring:

- Do we need to consider the effect this may have on the page's primary goals (which aren't neessarily to download Firefox or navigate)? Do we need to measure if an increase in clicks in the nav leads to a decrease in click throughs for other products?

**Comment by amychurchwell** [comment]
@alexgibson I updated the issue to include a link to the experiment plan, sorry about that: https://docs.google.com/document/d/1eja21ZlEJQfi-9jjWUhxx1zD6Gnm5EeaGMR8BZBIOP8/edit?usp=sharing
The trello board should also be visible: https://trello.com/b/M2XzdRvy/conversion-rate-optimization.

I will work through answering all your feedback shortly.

**Comment by amychurchwell** [comment]
@alexgibson 

> Traffic distribution for the experiment is set to 24%. Should this be 100%? I'm guessing we need to redirect 24% of traffic from /firefox/ to /exp/firefox/?

✅ Yes, I made a mistake because the 24% is controlled by cloudflare. Updated.  

> Should we add "Decrease bounce rate" as a secondary goal perhaps? (I'm guessing more people might end up navigating to a different page?)

✅ That makes sense to me, good idea! I confirmed with Saptarshi & Hoosteeno. Updated.

> Would it be worth adding a vertical media query, to stop the nav taking over on smaller desktop screens?

I brought this up to Kropp in design review & I thought we landed on it being okay, but [re-reading the comment](https://github.com/mozilla/bedrock/pull/8601#issuecomment-594551402) makes me realize it was mobile-specific. I will tweak today, but I don't know if I'd consider it a blocker?

> The goal for "Click: Download button in navigation on /firefox" is set as "Site Wide". Should it be specific to /firefox?

✅ Yes! Thank you. Updated to the regex `^https:\/\/www.(allizom|mozilla).org\/.+?\/firefox`  

> The same goal is set to track clicks on #protocol-nav-download-firefox, but the actual download link is a child of that element. Should it be something more specific? e.g. DIV#protocol-nav-download-firefox .download-list > li > a.download-link?

I originally had it as the parent > child, but was asked to change it to ID in case those relationships change & felt it was 6 one way half dozen another. If it is better to have the more explicit specificity, more than happen to update. Thank you! 👍

> Do we need to consider the effect this may have on the page's primary goals (which aren't neessarily to download Firefox or navigate)? Do we need to measure if an increase in clicks in the nav leads to a decrease in click throughs for other products?

Hmm, an interesting point. I think this would be more straight-forward to measure on a page that has one primary CTA. imo, /firefox feels trickier because it is marketing the entire family of products. Maybe we can do a more focused test if this one seems promising. I wanted to iterate on the UX of this nav behavior if this initial experiment seemed promising anyway.

**Comment by amychurchwell** [comment]
As always, thanks for the super thorough/thoughtful review, Alex! 👏 appreciate it.

**Comment by alexgibson** [comment]
I enabled the experiment on stage, and verified that I recieved the sticky nav variation OK. Clicking on the download button in the nav registered a primary goal conversion. Everything looks good! 👍

**Comment by alexgibson** [comment]
This experiment is now running in production for 24% of traffic to /en-US/firefox/

**Comment by alexgibson** [comment]
Can this issue now be closed out?

**Comment by amychurchwell** [comment]
@alexgibson yes, thanks again!
