### ISSUE TITLE
Experiment: installer-help redesign

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8602]
## Description
Design & copy for /firefox/installer-help/

## Test Plan
https://docs.google.com/document/d/1nI6GlQjZ3mH7_J_Dsdgpd2Ia7hke0lDxgwT7BrvvJwU/edit?usp=sharing

#### Tasks
- [x] Copy.
- [x] Design mockups.
- [x] Demo for design review.
- [x] Code experiment for final review.

#### Demo
N/A

**Comment by l-hedgehog** [comment]
Hi, while working on a redesign, would you please take https://bugzil.la/1564333 into consideration? Thanks.

**Comment by amychurchwell** [comment]
Hello! Thanks for mentioning this bug, @l-hedgehog. I've created an issue to track this work here: #8635

**Comment by amychurchwell** [comment]
@justinkropp 
Hi Justin! Here are demo links for design review. If you have feedback, feel free to post on this issue and I can update the pull request accordingly. 

Demo:
- https://www-demo5.allizom.org/en-US/firefox/installer-help/?v=b
- https://www-demo5.allizom.org/en-US/firefox/installer-help/?v=b&channel=release

**Comment by justinkropp** [comment]
@amychurchwell I reviewed both demos and they both look good to me. No edits. 👍

**Comment by amychurchwell** [comment]
This is now live - https://github.com/mozilla/bedrock/pull/8791
