### ISSUE TITLE
Copy - Browser comparison for Brave

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8614]
Research Brave browser to write comparison copy

[Copy doc](https://docs.google.com/document/d/1Hy8BHIyCEmyyhJ6V71Y-vyh1_V0vWCkR13-7_5Hbd4s/edit?usp=sharing)

Approvers:
- [ ] Accountable -Eddie I
- [x] PMM - Tyler Ahn
- [x] SEO @rraue 
- [x] Brand - Clio/Natalie
- [x] Legal

**Comment by hoosteeno** [comment]
@rantley let's stop working on this for the time being. Please link assets here. I'm moving back to New Issues until its future is clearer.

**Comment by rantley** [comment]
https://docs.google.com/document/d/1Hy8BHIyCEmyyhJ6V71Y-vyh1_V0vWCkR13-7_5Hbd4s/edit?usp=sharing

DRAFT
