### ISSUE TITLE
Design - Browser comparison for Brave

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8615]
- Create assets to insert in templated page

Approvers
- [x] Brand - Clio
- [ ] TL - Hoosteeno
- [ ] Approver - Eddie

**Comment by hoosteeno** [comment]
I'm moving this back to New Issues; I don't think we should invest any more in this work until its future is clearer.

**Comment by cgonz0** [comment]
**assets (intro img / animated svg)**
[firefox_vs_brave_assets.zip](https://app.zenhub.com/files/1616665/7536b4e5-4aae-42dd-b67d-83d1b87d38a7/download)


**mockup -- (copy not final)**
![BC_firefoxVsBrave_mockup.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/40df9d69-6ba1-42ba-93dd-9e20ee2986b7)

**Comment by cgonz0** [comment]
@ejregithub done - edited above.
