### ISSUE TITLE
New WNP Template

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8618]
## Description

Stakeholder request is to build out another template for the WNP.

The initial ask is for a layout similar to that of /new, with a prominent 'hero image' section at the top of the page

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Have the template ready for use prior to the end of Q1/2020

#### Approvers
- [ ] Brand (design)
- [ ] Team Lead
- [ ] Accountable (MWarther)

**Comment by hoosteeno** [comment]
This is not happening. Let's reopen if it is a priority someday.
