### ISSUE TITLE
Remove screenshotgo pages from www

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8619]
## Description

The legal team says we can remove https://www.mozilla.org/about/legal/terms/firefox-screenshotgo/ and https://www.mozilla.org/en-US/privacy/firefox-screenshotgo/ from the website.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] 2 screenshotgo pages are no longer displayed on the website.
- [x] These will be left to the 404 page (no redirect is put in place)

**Comment by alexgibson** [comment]
@hoosteeno for older privacy policies we usually archive them: https://www.mozilla.org/en-US/privacy/archive/

Should that not be the case here?

**Comment by hoosteeno** [comment]
We can EOL this content. It can be a 404.
