### ISSUE TITLE
Make the zh-CN WNP 74 page show the WNP 73 (or the default / fall back WNP)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8629]
Facebook is not available in China, therefore the FB content in the WNP 74 page is irrelevant to users there.

We can use geo-location, as we do with India to show the en content template, but need to understand the time and effort required to do so.

**Comment by ejregithub** [comment]
@alexgibson -

The stated request was to show the WNP 73 to zh-TW as Facebook is not available in China. Yet making that change for that reason doesn't look appropriate, though certainly easier.

If we wholesale show WNP 73 to zh-TW, the locale, then that's all users with that setting (I have no information at hand on how many users outside of China have zh-TW selected as their preferred language in Firefox). 

If we geo-locate users in China to then show them the WNP-73, while showing the WNP 74 to users not in China with zh-TW as their preferred lang in Fx, what kind of effort would that require, for curiosity's sake?

That being said, I think going with WNP 73 to all zh-TW is the lowest barrier, best option . . .

**Comment by craigcook** [comment]
Is this for zh-TW (Taiwan, traditional Chinese characters) or zh-CN (Mainland China, simplified Chinese characters)? Or both?

Or, if we're talking geolocation anyway, is it for all users physically located in China regardless of language?
