### ISSUE TITLE
Privacy-related images on /firefox/mobile/ are missing alt attributes

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8634]
## Description

Two images on the `/firefox/mobile/` page are missing `alt` attributes. Whilst the images are purely decorative, they should still have an empty `alt=""` attribute value, to prevent screen readers from reading our the image filename.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/mobile/
2. Scroll down to the "Block online trackers and invasive ads" section.

### Expected result

The two phone images should have an empty `alt=""` attribute.

### Actual result

Neither image has an `alt` attribute:

```html
<img src="https://www.mozilla.org/media/img/firefox/mobile/protocol/screen-private.15a3437f9013.svg" height="331" width="163">
```

```html
<img src="https://www.mozilla.org/media/img/firefox/mobile/protocol/screen-tracking.390ad080cea1.svg" height="331" width="163">
```

### Environment

N/A

**Comment by obviyus** [comment]
Can I take up this issue @alexgibson?

**Comment by alexgibson** [comment]
> Can I take up this issue @alexgibson?

Pull requests are welcome!
