### ISSUE TITLE
Experiment: Banner on /new for mobile users.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8637]
## Description
https://trello.com/c/Ea2O0GZX

Add banner on /new for both ios and android users with app store CTA.

## Test Plan
https://docs.google.com/document/d/1-GwH3-XtQUf-PU8N6n6-dbe1VJeUdw4KkP7vG5ZEoXA/edit?usp=sharing

#### Tasks
- [x] Copy.
- [x] Design mockup.
- [x] Demo for design review.
- [x] Code experiment for final review.

#### Demo
N/A

**Comment by cgonz0** [comment]
![new_mobilebanner.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/a030605a-b0ae-4619-9a99-184ee18216a9)

**Comment by amychurchwell** [comment]
@alexgibson 
This experiment is ready for review in convert, it includes some JS to show/hide the CTA based on `window.site.platform` being android or ios.

**Comment by alexgibson** [comment]
Some feedback on the experiment setup:

- The primary goals are "app store clicks on the /new mobile banner", but we don't seem to be tracking clicks on the regular download button. I'm not entirely sure if this is needed or not, but I'm unclear how we'd know if say, downloads are going up overall, or if people are just clicking one button instead of the other?

JS feedback:

```javascript
if (window.site.platform = 'ios') {}
```

I think this needs to be `==` for the conditional to work? Same for the Android conditional. Right now it's treating it like an assignment. I was trying to get the preview URL to work on iOS unsuccessfully, and I _think_ this might be why.

```javascript  
close.addEventListener('click', function() {
  banner.parentNode.removeChild(banner);
});
```

Suggest adding `false` as the default last param to `addEventListener`:

```javascript  
close.addEventListener('click', function() {
  banner.parentNode.removeChild(banner);
}, false);
```

Let me know when the above changes are made, and I'll have another go to see if I can get the preview URL working.

**Comment by alexgibson** [comment]
Also, not to impede this experiment as I still think it's worthwhile, but has the CRO team considered trying [native app banners](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html)? These are just a single line of code, and may provide users with a more familiar UX. They are also native, so have potential to be more performant (faster loading).

**Comment by amychurchwell** [comment]
@alexgibson Thank you for the feedback, really appreciate it.
I made the above JS changes, and I agree that we should also probably track download button clicks as well.

Thank you for bringing up native app banners! 👏 I think it would be worth running the same test with the native app banner also. I am going to mention this to the team.

**Comment by alexgibson** [comment]
@amychurchwell I noticed the targeting URL is incorrect, as well as the URLs in the visual editor (so the preview links aren't working). I think those need updating in order to test the experiment.

**Comment by amychurchwell** [comment]
@alexgibson URLs have been updated to exp pages. `https://www.allizom.org/en-US/exp/firefox/new/`

**Comment by amychurchwell** [comment]
@alexgibson we are going to do a 3rd variant with a native app banner, so we are delaying launch until we tweak experiment plan and I get the code ready for that. Going to work on that today.

**Comment by amychurchwell** [comment]
@alexgibson this is ready for final review, I think we should move native app banners into a separate experiment.

from slack:
>I think we should move the native app banners variant into a separate experiment for now:
Android native banners require: a user engagement heuristic (currently, the user has interacted with the domain for at least 30 seconds) that may not work for this?

> Also requires adding a manifest to bedrock, and I would feel more comfortable having more time for overall research. Convert might not be the tool for this.

> There is an open issue of measuring clicks/installs for both (would like to discuss with ios/android developers) and I have been debugging the iOS native banner functionality today that is not yet resolved. I don’t think it should block us launching the designed banner experiment.

**Comment by alexgibson** [comment]
@amychurchwell when I visit the preview URL on iOS Safari, I see the banner and app store badge a-ok, but when I try and click on the app store badge, nothing happens?

Clicking the regular download button redirects to the app store as expected, but the banner uses an adjust link. Could there be a problem with this link? Other adjust links on the site, such as on /firefox/mobile/ seem to work ok.

The clicks don't seem to be registering as goals in convert either, but that may just be becasue of the issue above. Can you replicate any of this when you try?

**Comment by amychurchwell** [comment]
@alexgibson It has given me the correct behavior before, but I am also experiencing something similar. Convert seems to open a separate window that you need to click-through?
I collaborated with Loren on the links for these, so they should be correct. I'll double check.

![image](https://user-images.githubusercontent.com/30483988/77669672-5f8fb680-6f42-11ea-8864-13aa5deb10ba.png)

**Comment by alexgibson** [comment]
I can only seem to get the link to open by holding instead of tapping and then telling it to open in a new tab?

**Comment by amychurchwell** [comment]
For posterity: `rel="external noopener noreferrer"` on adjust links breaks them in convert. Investigating.

**Comment by alexgibson** [comment]
@amychurchwell I tested the preview link on my iOS device and it now functions as expected.

I took a second look at review and things look good to me. Once question though: the original variation (control) doesn't have any goals set up to track conversions. How are we hoping to work out if the mobile buttons outperform the control?

**Comment by alexgibson** [comment]
Ok, this experiment is now running in production for 12% of traffic going to /en-US/firefox/new/

**Comment by alexgibson** [comment]
Lowered to 9%, as per Slack
