### ISSUE TITLE
Move the /technology sub-pages to live underneath /browsers/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8641]
## Description

As part of retiring the /technology/ section in #6824, we'd like to move and redirect the following sub pages pages:

- https://www.mozilla.org/en-US/technology/what-is-a-browser/
- https://www.mozilla.org/en-US/technology/update-your-browser/
- https://www.mozilla.org/en-US/technology/incognito-browser/
- https://www.mozilla.org/en-US/technology/browser-history/
- https://www.mozilla.org/en-US/firefox/best-browser/
- https://www.mozilla.org/en-US/firefox/windows-64-bit/

to these URLs:

- https://www.mozilla.org/en-US/firefox/browsers/what-is-a-browser/
- https://www.mozilla.org/en-US/firefox/browsers/update-your-browser/
- https://www.mozilla.org/en-US/firefox/browsers/incognito-browser/
- https://www.mozilla.org/en-US/firefox/browsers/browser-history/
- https://www.mozilla.org/en-US/firefox/browsers/best-browser/
- https://www.mozilla.org/en-US/firefox/browsers/windows-64-bit/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] URLs are updated and redirected in production.

**Comment by alexgibson** [comment]
@rraue would it also make sense to move these pages over to live under /firefox/browsers/?

- https://www.mozilla.org/en-US/firefox/best-browser/
- https://www.mozilla.org/en-US/firefox/windows-64-bit/
- https://www.mozilla.org/en-US/firefox/features/safebrowser/

**Comment by rraue** [comment]
The first two for sure. /features/ and whats in this folder should for now stay there until we move it completely in /browsers/. What do you think @dzingeek?

**Comment by alexgibson** [comment]
Fwiw, /features/safebrowser/ is related by URL only. It isn't linked from the /features/ landing page, and does not share the same design / UX as the other /features pages.

**Comment by dzingeek** [comment]
Yeah I agree with @rraue , but i am not sure what to do with that last one tbh.

**Comment by alexgibson** [comment]
Seeing as we don't have a clear recommendation here I'm going to leave /safebrowser/ as an orphan. We'll probably still need to decide what to do with it when /features/ is redesigned though.
