### ISSUE TITLE
Update nightly whatsnew page language on non-en-US as we update more frequently now

### ISSUE THREAD

**Issue by gijsk** [mozilla/bedrock#8643]
## Description

The text on https://www.mozilla.org/en-GB/firefox/76.0a1/whatsnew/all/ suggests we update every 6-8 weeks, and that's now ~4 weeks.

### Steps to reproduce

1. update to 76.

### Expected result

The "what's new" page should be informative and accurate.

### Actual result

See above.

### Environment

macOS, nightly 76 updated from 75.

**Comment by jens1o** [comment]
`en-US` has already been updated.

**Comment by gijsk** [comment]
Looks like #8253 fixed en-US but not other languages.

**Comment by flodolo** [comment]
Someone needs to expose the new string and tag for localization
https://github.com/mozilla-l10n/www.mozilla.org/commits/master/en-US/firefox/nightly_whatsnew.lang

cc @peiying2

**Comment by alexgibson** [comment]
Yep, looks like this was merged but the string was never extracted. I'll see if I can do this today 👍

**Comment by alexgibson** [comment]
PR for string extraction: https://github.com/mozilla-l10n/www.mozilla.org/pull/378

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla-l10n/bedrock-l10n/commit/92a8373a810d956d8d83e175bed7864cb02bad3f
