### ISSUE TITLE
Add a redirect for /builders

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8644]
A request has come in via email for this:

mozilla.org/builders -> 301 -> https://builders.mozilla.community/

**Comment by vmunix** [comment]
Hey @pmac could we get the 301 updated with some UTM magic:

`301 from www.mozilla.org/builders to https://builders.mozilla.community/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=builders-redirect`

Will clean up the GA on the builders GA. Thx!!
