### ISSUE TITLE
Remove "autofill" from switch page.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8651]
## Description

We should cut "autofill" from the switch page copy as it is not data we import through the switching process. Here's the [supporting documentation](https://wiki.mozilla.org/QA/Firefox_migrators#Supported_data_types).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New page is launched with improved copy.

**Comment by alexgibson** [comment]
Note that this is likely blocked on activation of Fluent in Pontoon

**Comment by alexgibson** [comment]
This is unblocked and seems like a good-first-fluent type issue for a dev. Moving to the ready column.

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
