### ISSUE TITLE
Email preferences page shows a "Get a Firefox account" button while the user is already logged in

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/bedrock#8664]
Moved from https://github.com/mozmeao/basket/issues/504#issuecomment-598735441

STR:
1. With an already created Firefox Account I went into settings and clicked the "Email preferences"  at the bottom of the page which redirects to the newsletter page https://www.mozilla.org/en-US/newsletter/
2. Observe the blue button on the top right
3. Click the button

Actual result:
It redirects to https://www.mozilla.org/en-US/firefox/accounts/  

Expected result:
The button should have another name since the user is already created. Instead of "Get a Firefox Account" maybe "Go to Firefox accounts". 

Notes:
I tested on 75.0b3(Win10). 

![button not good](https://user-images.githubusercontent.com/33448286/76625080-33863580-653f-11ea-9f33-e0f1d627f86e.gif)

**Comment by alexgibson** [comment]
Another alternative button for this state could be https://github.com/mozilla/bedrock/issues/8251

**Comment by maureenlholland** [comment]
Closing as outdated, the blue button on top right (desktop screen size) is now for VPN
