### ISSUE TITLE
Remove legacy /firefox/campaign/ main template

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8667]
## Description

The trailhead template for the /firefox/campaign/ page is now [active for 50 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/campaign-trailhead.lang), which makes up 96% of our L10n user base.

Seeing as this isn't our main download page we should be relatively safe to remove the legacy Pebbles template.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Old template is removed from the codebase.

**Comment by obviyus** [comment]
Is this the file to be removed? 
https://github.com/mozilla/bedrock/blob/246b331bbc81529dbd435387b4fb1f891493595a/bedrock/firefox/templates/firefox/campaign/index.html#L1
