### ISSUE TITLE
Redirect /contact/communities/ to community.mozilla.org/groups

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8668]
## Description

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1622345

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Outdated community contact pages are removed and redirected.

**Comment by alexgibson** [comment]
@hoosteeno this seems like a good opportunity to clean up a bunch of legacy URLs that haven't been updated in some years. Any objections to redirecting these pages to https://community.mozilla.org/groups/ ?

**Comment by hoosteeno** [comment]
Let's make that redirect happen. 

Do we need a separate issue for eliminating that content from Bedrock?

**Comment by alexgibson** [comment]
I don't think we need a separate issue for removing the content. We can tackle that here too.
