### ISSUE TITLE
Update bedrock's cookie helper lib

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8670]
## Description

Bedrock's [cookie helper](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-cookie-helper.js) is a small custom library, [copied from MDN](https://developer.mozilla.org/en-US/docs/Web/API/document/cookie), which was originally based on the source code of this github repo: https://github.com/madmurphy/cookies.js

The version in bedrock, whilst altered for some custom functionality, is now quite out of date. It does not support setting the `sameSite` property, for example: https://web.dev/samesite-cookies-explained/

We should consider updating our helper, so that we can be more explicit when it comes to setting cookie values relating to 1st / 3rd party contexts. We could either update our existing helper to add support, or alternatively deprecate it in favor of using the cookies.js open source library directly.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Cookie helper is updated.
- [ ] Cookies set using JS explicitly set the `sameSite` attribute (`lax` should be fine for front end needs where cookies are used to control display of content?).

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by alexgibson** [comment]
Changes to SameSite cookie behavior are rolling out in Chrome and soon also in Firefox. https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/

From what I can tell, I don't think  any cookies in use on mozorg are effected directly by this change, but it may still be worthwhile updating this lib, so that we can set the `SameSite` attribute explicitly, instead of relay on the new implied default.
