### ISSUE TITLE
Sticky Navigation: Code

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8675]
The epic at https://github.com/mozilla/bedrock/issues/8676 talks about implementing sticky navigation to replace global navigation bars on all pages that have global navigation. This card is about the coding.

Success Criteria:
- [ ] Sticky navigation code is live in production

Tasks:
- [x] Build it in Protocol

**Comment by alexgibson** [comment]
Sticky nav is now ready for code review over in Protocol: https://github.com/mozilla/protocol/pull/561

**Comment by alexgibson** [comment]
Adding a blocker to this until it's in Protocol.

**Comment by alexgibson** [comment]
https://github.com/mozilla/protocol/pull/561 has been merged, so the next step is now to publish a new NPM release and then update bedrock to use it.

**Comment by hoosteeno** [comment]
@craigcook is publishing a new NPM release something you can do?

**Comment by craigcook** [comment]
> @craigcook is publishing a new NPM release something you can do?

Yup, I'm on it.

**Comment by hoosteeno** [comment]
This is dependent on https://github.com/mozilla/bedrock/pull/8796
