### ISSUE TITLE
Experiment: Test WNP template in Moments channel, Moments template in WNP channel

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8683]
## Description

We should aim to learn whether the difference between WNP and Moments page templates is meaningful. 

Questions:
* Does either of these templates outperform the other, in the other's channel? If so, we should choose the best performing one.
* Do they work the same? If so, we should pick one and unify.

---

#### Test Plan

[rough drafts]
- [WNP template on moments page.](https://docs.google.com/document/d/1rbKi37ZDxSxrYet4lnOfcx5mJ5xA8Ej8h1sfRiPllbI/edit?usp=sharing)
- [moments template on WNP](https://docs.google.com/document/d/1tAdN48r7BRjosHBXdZTyLl1gwNdkSJC-GNHRBQOHngg/edit?usp=sharing)

**Comment by hoosteeno** [comment]
@amychurchwell This one is up for grabs...

**Comment by mitchell-frost** [comment]
Can I work on this as I am new to mozilla?

**Comment by amychurchwell** [comment]
@mitchell-frost I am assigned to and am working on this issue. Thanks for the interest!

**Comment by amychurchwell** [comment]
Moments template on the WNP channel A/B test will be targeted at the [Firefox 78 release (6/30)](https://wiki.mozilla.org/Release_Management/Calendar)

WNP template on the moments channel TBD, test plan is more of a challenge for that channel because of lack of historical traffic data.

**Comment by hoosteeno** [comment]
@amychurchwell is this in progress, then?

**Comment by amychurchwell** [comment]
@hoosteeno yes, this is in progress. :) will have a PR early this week.

**Comment by ejregithub** [comment]
@amychurchwell - can you please provide status here?

**Comment by amychurchwell** [comment]
@ejregithub hi Eric! We ran the moments template on wnp77. Unfortunately there was a JS bug that was missed that prevented the datalayer push for analysis. We attempted to compare the URLs directly in GA
`https://www.mozilla.org/en-US/firefox/77.0.0/whatsnew/all/?v=2` vs `https://www.mozilla.org/en-US/firefox/77.0.0/whatsnew/all/` but we were unable to find anything. Unsure why, perhaps we can take another look.

I heard something in passing that the whatsnew pages were getting a redesign? Perhaps we can revisit this experiment after that work is completed?

**Comment by hoosteeno** [comment]
Here is an analysis of thee Moments in WNP channel that I put together: https://docs.google.com/spreadsheets/d/1K7JlRVkn1KiLe-GNME1tyYhssJV_dbaCFMJE5FiW234/edit#gid=509894921.

I've asked @sghoseWI to review the methodology and determine if it's adequate.

**Comment by alexgibson** [comment]
Based on the last comment above it sounds like this experiment was considered done.
