### ISSUE TITLE
Copy - Migrate /features to Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8684]
In https://github.com/mozilla/bedrock/issues/8686 we are redesigning the /firefox/features/ page so we can implement it using existing Protocol features. We need copy on that page for each feature.

Tasks:
* Write new copy for the /features overview page, for each feature listed on current page
* Write new copy for a new feature to be listed that links to browser comparison pages

Success criteria:
* New copy is approved and incorporated into designs

**Comment by rantley** [comment]
@cgonz0 

Here's a draft version, this is in queue to be reviewed by brand. 
https://docs.google.com/document/d/1vt8q2TH3TYz2NHVZ_8WqvBnZjw0SIT3vPTx2tXOUJvA/edit?usp=sharing

**Comment by ejregithub** [comment]
Brand has approved

**Comment by ejregithub** [comment]
@hoosteeno to talk to Porfirio about this for PMM perspective

**Comment by hoosteeno** [comment]
I pinged Porfirio and asked for his reply within the week.

**Comment by hoosteeno** [comment]
@rantley is this card complete? If so can you drag to the "done" column?
