### ISSUE TITLE
Invite the Nightly users to the Nightly community on chat.mozilla.org

### ISSUE THREAD

**Issue by jens1o** [mozilla/bedrock#8688]
## Description

On the `nightly_whatsnew.html` page there was a former reference to the IRC server (`irc.mozilla.org`) which was removed as the IRC server was shut down as Mozilla moved to Matrix.
However, the Matrix method isn't (yet) mentioned on that page.

Came up at https://github.com/mozilla/bedrock/pull/8253/files/f7ff829b47ea99a80fdceddd912a085e43367171#diff-abf2619d0c5c977a82010883746b8b23

### Steps to reproduce

n/t

### Expected result

There should be a reference that the Nightly users may connect on Matrix.

### Actual result

No mention of the existing Nightly community on Matrix.

### Environment

Firefox Nightly

/cc @pascalchevrel

**Comment by alexgibson** [comment]
Looks like this was fixed
