### ISSUE TITLE
Newsletter form on /channel page is broken

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8690]
## Description
The newsletter signup on the /firefox/channel/ page isn't working quite right. It looks like the JS that handles the form request is missing.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/firefox/channel/desktop/
2. Fill out the newsletter signup form and click "Sign Up Now"

### Expected result

Upon successful signup, you should see a "thank you" message.

### Actual result

The URL changes to https://www.mozilla.org/en-US/newsletter/, and you get a blank page:

![image](https://user-images.githubusercontent.com/400117/77325482-4c95a000-6d10-11ea-9b60-a5587e5c9fbb.png)

### Environment
Firefox Nightly

**Comment by imrishabh18** [comment]
I would like to work on this issue.
