### ISSUE TITLE
Change title of /new (en-US only)

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8697]
## Description

We should test if a easier to read title tag with more value prepositions gets a better ctr in search results. To test this I will measure trends on en-US vs en-CA & en-GB

Current title: "Download Firefox — Free Web Browser — Mozilla"

New title meta tag on en-US only: "_Download Firefox Browser — Fast, Private & Free — from Mozilla_"

---

#### Test Plan

SEO testing, so it needs to be hard coded on /en-US/firefox/new/

Test for 2 Weeks, comparing these two weeks to previous weeks and the change in ctr to the change on en-GB & en-CA to measure any influence.

#### Tasks
- [x] @rantley needs to check grammar and spelling
- [ ] Hard code the title tag for en-US only and not expose it to pontoon

**Comment by rantley** [comment]
@rraue looks fine to me. Another way to consider phrasing it below:

  _"Download Firefox Browser — Fast, Private & Free — from Mozilla"_

**Comment by rraue** [comment]
@rantley Will change, thank you. I copied this from the Firefox page but your version is even cleaner with the same massage 🙌

**Comment by rraue** [comment]
Old issue, closing as we change it with the redesign of /new
