### ISSUE TITLE
Test Pilot - "marketing website home"

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8698]
## Description

Test Pilot - Give it a real marketing website home

Why: It will directly grow FxA acquisition, Firefox Desktop MAU, or non-Desktop MAU., It enhances our brand.

Requester: Tyler Ahn

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] It's 7 sheeted
- [ ] The cost/benefit equation is done to determine if it should be done

####Approvers
- [ ] Approver/Accountable - Tyler Ahn
- [ ] SEO - Raphael
- [ ] Team Lead - Hoosteeno
- [ ] Brand - Clio / Natalie

**Comment by alexgibson** [comment]
Test Pilot is no more afaik, closing.
