### ISSUE TITLE
Design - WNP 76

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8702]
Provide design assets for the WNP for 76 in the wnp template. In this case it will be the hero section and 3 subsections as detailed below:

Privacy and Security theme content leaning towards Skyline content

Hero section: Enhanced Tracking Protection

- 1st subhead: Monitor
- 2nd subhead: Send
- 3rd Subhead: FB Container, shown to all locales except zh-TW

[Copy doc](https://docs.google.com/document/d/1q45AUQPnzCkQdAc1hELW8kYN8pC7xWbFqgs3Xl3iBrA/edit#)

Approvals:
- [x] Approver/Accountable MWarther
- [x] TL - @hoosteeno 
- [x] Brand - Design - Clio
- [x] Brand - Copy - NLinden

**Comment by ejregithub** [comment]
@cgonz0 - when requirements are clear to you, please apply an estimate (time/complexity) for your work that is required to close this card.

**Comment by ejregithub** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/20547886/78845190-be324700-79bc-11ea-9b45-8c5b8b1e60f1.png">

**Comment by cgonz0** [comment]
All locales ~

![wnp76 - Final - all locales.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/0a4b7bfd-8ff3-48e4-b6d6-b665a808beea)


zh_TW ~

![wnp76 - FInal - zh-TW.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/7f645e9c-5562-45c9-9333-edb4919ef638)

![hero_etp.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/e033e685-999f-41c2-84b2-66359c6c8ca8)
