### ISSUE TITLE
Possibly error in footer links?

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/bedrock#8707]
## Description

I noticed today that there's two links in the footer that don't have hrefs:
```
<div class="mzp-c-footer-license">
          
          
          <p>
          Visit <a moco_link="">Mozilla Corporation’s</a> not-for-profit parent, the <a mofo_link="">Mozilla Foundation</a>.
          </p>
          <p>
          Portions of this content are ©1998–2020 by individual mozilla.org contributors. Content available under a <a rel="license" href="/en-US/foundation/licensing/website-content/">Creative Commons license</a>.
          </p>
        </div>
```

And indeed, if I visit a page such as https://www.mozilla.org/en-US/firefox/75.0beta/releasenotes/, the " Visit Mozilla Corporation’s not-for-profit parent, the Mozilla Foundation. " text has no clickable links.

Possibly caused by https://github.com/mozilla/bedrock/commit/4d161e90f21a43446bd93ba84530b44d9af8c41f ?

**Comment by alexgibson** [comment]
Thank you, nice catch!
