### ISSUE TITLE
Implement to bedrock

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8710]
Get this this live on the website using the Protocol component

- [ ] Determine the pages on which it should appear
- [ ] Testing to ensure proper behavior and no breakage

**Comment by alexgibson** [comment]
@ejregithub can you add a little more information here, so that this issue makes sense out of context of the discussion yesterday? I already can't remember what this one is about :)

**Comment by hoosteeno** [comment]
Duplicate #8675
