### ISSUE TITLE
Header logos on 404 and 500 pages should be links

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#8716]
## Description

The Mozilla and Firefox logos at the top of the error pages should link to the home page and /firefox, respectively.

![image](https://user-images.githubusercontent.com/205591/77805981-9e0b9b00-7040-11ea-8f0f-7fb89db89d70.png)

**Comment by imrishabh18** [comment]
Hey, i want to work on this.

**Comment by imrishabh18** [comment]
Filed a PR for this check it - https://github.com/mozilla/bedrock/pull/8741

**Comment by Rudresh22** [comment]
Hello, I want to work on this issue, please guide me through this.
