### ISSUE TITLE
"Our Mission" buttons remain 1 column up to 1024px wide [New Contribute Page]

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8719]
Going from mobile to desktop, the four buttons under the "Our Mission" heading remain in a  single column until the screen reaches 1024px wide.

<img width="958" alt="Screenshot 2020-03-30 at 15 19 24" src="https://user-images.githubusercontent.com/42435754/77923127-e5409880-7299-11ea-9b10-1f93af21b7b2.png">

Upon reaching 1024px the buttons switch to a 2x2 grid matching the desktop design.

For people using the side without a maximised window this may use up a lot of space, can we switch to 2x2 as soon as it's "comfortable", can we try something like 768px ?

Thanks!

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
