### ISSUE TITLE
"Get Help" and "Webcompat" blocks should be smaller [New Contribute Page]

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8720]
On desktop, the "Get Help" and "Webcompat" blocks above the footer of the page should not stretch beyond the width of the footer content area. 

<img width="365" alt="Screenshot 2020-03-30 at 15 31 41" src="https://user-images.githubusercontent.com/42435754/77924533-aad7fb00-729b-11ea-97a8-fa3e8b328d44.png">

Looking at the footer, this would mean that these two blocks should go no wider than 1228px

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
