### ISSUE TITLE
Height of hero area a little too big [New Contribute Page]

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8721]
Admittedly very much a nitpick (sorry)!
Though I typically don't value an above-the-fold mentality, the height of the hero area in this instance was purposeful in order to get the "How you can contribute…" header from the section below within a typical screen view.

Looking between the designs and the staging area, we only need to remove 50px in order to match what is on Figma.

| Figma  (602px)      | Staging  (654px)      | 
| ------------- |:-------------:| 
| <img alt="Screenshot 2020-03-30 at 16 41 12" src="https://user-images.githubusercontent.com/42435754/77932327-49b52500-72a5-11ea-82c6-97a92adf74ca.png">     | <img alt="Screenshot 2020-03-30 at 16 32 12" src="https://user-images.githubusercontent.com/42435754/77932197-1ffbfe00-72a5-11ea-8ad0-bf90fb6b614c.png">| 

That might also help match our triangle cut-off point from the designs:

<img width="485" alt="Screenshot 2020-03-30 at 16 43 06" src="https://user-images.githubusercontent.com/42435754/77932580-a4e71780-72a5-11ea-8bf3-e9948bc62029.png">

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
