### ISSUE TITLE
Webcompat lightbulb placement [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8723]
In between mobile and desktop states, the Webcompat lightbulb can interact with the text within the block:

<img width="355" alt="Screenshot 2020-03-30 at 17 58 45" src="https://user-images.githubusercontent.com/42435754/77940147-293e9800-72b0-11ea-9139-f2d880b7561f.png">

I'm not fussed about placing it perfectly anywhere so long as the bulb doesn't appear underneath other content elements. 
Nudging a little up and to the left in these scenarios is perfect.
The mobile and desktop positions are fine as-is.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
