### ISSUE TITLE
Prevent button text from appearing on two lines [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8724]
Can we prevent the buttons within the "Get Help" and "Webcompat" blocks from appearing on two lines:

<img width="255" alt="Screenshot 2020-03-30 at 18 04 34" src="https://user-images.githubusercontent.com/42435754/77940685-f648d400-72b0-11ea-8953-d20393ccf418.png">

The buttons should always appear within a single line.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
