### ISSUE TITLE
Increase distance between footer and Webcompat block [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8725]
On desktop sizes, the gap between the Webcompat block and the footer should be larger than that of the gap between the Webcompat and Get Help blocks:

<img width="668" alt="Screenshot 2020-03-30 at 18 08 29" src="https://user-images.githubusercontent.com/42435754/77941105-8b4bcd00-72b1-11ea-91e7-c498130193db.png">

Let's go with 140px 👍 

The gap distance on mobile is fine.

**Comment by drewminns** [comment]
@mcroud I've made the change (pending deployment to the environment) but I wanted to flag that the spacing is not using a design token defined within the Protocol design system. Is this alright?

**Comment by mcroud** [comment]
I see! You know I actually wasn't aware that we had tokens for specific measures.
Let's go with `$layout-xl`
Thanks for the heads up!

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
