### ISSUE TITLE
Reduce max width of Our Mission area on Desktop [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8726]
On staging the body copy area of Our Mission can expand to over 1000px.
This might be more than what's comfortable to read on a single line (though admittedly it is only a single line!)

<img alt="Screenshot 2020-03-30 at 18 15 43" src="https://user-images.githubusercontent.com/42435754/77942183-2ee9ad00-72b3-11ea-8d33-7bc928f6beae.png">

Can we reduce this width to something close to the designs so we end up with three lines:

<img alt="Screenshot 2020-03-30 at 18 20 19" src="https://user-images.githubusercontent.com/42435754/77942391-7112ee80-72b3-11ea-9fa7-175d51aba71a.png">

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
