### ISSUE TITLE
Align card heights [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8727]
When the contribution cards become a 2x2 formation the height of the cards are not synced with their neighbour:

<img alt="Screenshot 2020-03-30 at 18 19 38" src="https://user-images.githubusercontent.com/42435754/77942720-f4ccdb00-72b3-11ea-9ce3-f2010eed9ed6.png">

Can we have the cards match the height of the tallest card. I acknowledge that this will create extra white space along the bottom of the shortest card.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
