### ISSUE TITLE
MOSS-Covid: Design

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8729]
## Description

In https://github.com/mozilla/bedrock/issues/8728 we are building a new banner for the MOSS pages. The copy and specs are in that issue. This issue is about putting together a light design for the banner.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Banner is approved by devs and attached to this issue.

**Comment by cgonz0** [comment]
[Sketch file w/ specs & bg img - MOSS-Covid_banner.zip](https://github.com/mozilla/bedrock/files/4447529/MOSS-Covid_banner.zip)

-------------


![1312 - final](https://user-images.githubusercontent.com/29640968/78730382-7d213080-78f1-11ea-90f9-592162761731.png)

------------

![768 - final](https://user-images.githubusercontent.com/29640968/78730384-7e525d80-78f1-11ea-8daf-1a6e732d522a.png)

------------

![480 - final](https://user-images.githubusercontent.com/29640968/78730388-801c2100-78f1-11ea-8807-43abaa172bcf.png)
