### ISSUE TITLE
Broken link on /privacy/firefox/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8736]
## Description

On /privacy/firefox/ the link to the privacy terms of adjust.com is 404. It needs to link to https://www.adjust.com/terms/privacy-policy/ instead of https://www.adjust.com/privacy-policy/.

**Comment by ejregithub** [comment]
@rraue - I pinged MFeldman (on Wed) but have not heard back.  Given the 404 circumstance and that we're simply replacing a link, I see no reason not to move forward and implement the update.
