### ISSUE TITLE
Research & implement the use of data-nosnippet

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8739]
## Description
Google and other search engines are displaying more and more feature snippets in search results. This is in general good for us, as they usually are the first result answering short questions with a link to our websites.

We saw from time to time weird feature snippets including wording from forms, buttons, nav or footer. One of the latest examples is from Germany. We won back the first rank for "browser" but because of the download button it says "Your system does not meet the requirements for Firefox” what isn't very encouraging to click on the result :confused:

![Screenshot 2020-04-01 at 12 17 33](https://user-images.githubusercontent.com/36700618/78161731-355c5e00-7446-11ea-8312-616ae549f72a.png)

There is a HTML attribute **data-nosnippet** we could use to prevent search engines from using non-content content for snippets (it will still be indexed and used for ranking and "understanding" the page): https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr

We should discuss how we can use this all across mozilla.org and combine it with protocol. There are obvious parts of every url like the nav, subnavs, the footer, buttons and forms that should not be part of a snippet and could be standardized with data-nosnippet but maybe I miss some and maybe it's even easier to mark the content as not having a data-nosnippet attribute and everything has?

There is no way to figure out how often we have "wrong" snippets on all our keywords, locales and search engines, so if we find a way to use this as a standard, we reduce the risk of faulty snippets by far for now and the future (as feature snippets are expected to grow in results) and this is important for voice search as well as snippets are used for answers there by Siri (bing) and Google Assistant.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] We have a plan how to use data-nosnipped across mozilla.org to prevent faulty snippets (no need for perfection, we rather get 90% safe for 30% work load)
- [ ] Estimade the workload this would need to implement

**Comment by rraue** [comment]
@alexgibson  and I reviewed our pages and decided to only put the data-nosnippet in two places. The rationale behind is, that search engines are pretty good in figuring out what's a navigation and a footer and html mistakes especially in the nav can cause all content to be ruled out of snippets. So we decided to add the data-nosnippet only to the parts that can cause very mixed or wrong messaging on all pages: 

- Download button
- Donation banner (and all future variations)


To reduce risk (not closing div which will apply the data-nosnippet attribute to all following content) in the download button the following parts need to have a data-nosnippet:

- <div class="unrecognized-download">
- <p class="unsupported-download-osx">
- <p class="unsupported-download-osx">
- <p class="linux-arm-download">

The three <p> must be transferred to <div> as data-nosnippet can only apply to div, span or section. So it would look like:

Important! Add a comment in the code, that it is extremely important to close every div in these divs or everything following will be excluded for snippets.

**Comment by ejregithub** [comment]
@alexgibson if #8860 is a duplicate to the code card #8798 (originally created under the epic #8797) can you please close the appropriate dupe?

**Comment by alexgibson** [comment]
Thanks Eric, I think we can just use this issue to track what needs doing. Closed #8798

**Comment by alexgibson** [comment]
Ok, I'm going to pick this up seeing as it's a high priority and seems ready to me.

**Comment by alexgibson** [comment]
@rraue can you please help review on demo? Thanks!

- https://www-demo5.allizom.org/en-US/
- https://www-demo5.allizom.org/en-US/firefox/new/
