### ISSUE TITLE
"People like you image" should be flush right [New Contribute Page] 

### ISSUE THREAD

**Issue by mcroud** [mozilla/bedrock#8740]
On desktop, the image associated with the **Made by passionate people like you** section seems to have come away from the right hand edge.

There's now a gap between the image and the edge, and the image appears closer to the body copy.

<img width="1525" alt="Screenshot 2020-04-02 at 13 49 05" src="https://user-images.githubusercontent.com/42435754/78256491-81fc7380-74f0-11ea-8758-16279e09fac8.png">

Reverting this back to where it was would be awesome.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8896
