### ISSUE TITLE
Switch to native lazy loading for images

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8752]
## Description

Firefox 75 is out, which supports the [`loading="lazy"` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading). This means native image lazy loading now has pretty broad browser support, with the notable exception of Safari.

We should investigate switching to native lazy loading of images, instead of using our current Intersection Observer solution that relies on JS. Or possibly falling back on a JS based solution if native support does not exist.

**Comment by maureenlholland** [comment]
Let's do this!

Success Criteria:

- [ ] remove `lazy_img` helper and related CSS/JS
- [ ] include `loading` param on macros, default to "Lazy" (? - feels like that's the one we'd need more, open to discussion)
- [ ] ensure existing `lazy_img` elements have `loading="lazy"` when the helper is removed

**Comment by alexgibson** [comment]
> (? - feels like that's the one we'd need more, open to discussion

I'm not 100% sure what is best here also. I would add that defaulting to `loading="lazy"` could result in over use, as it's an anti-pattern to use on image that appear inside the visual viewport on page load.

**Comment by maureenlholland** [comment]
Fair point re:anti-pattern. I think we'd be fairly vigilant about that but it's definitely a point in favour of default Eager (or nothing, as eager is the browser default already)

**Comment by alexgibson** [comment]
Yeah, up to you here - whatever you think makes the most sense 👍
