### ISSUE TITLE
Resources link on firefox/enterprise goes nowhere.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8761]
## Description

On the [firefox/enterprise](https://www.mozilla.org/en-US/firefox/enterprise/) there is a link to resources (`#resources`) that currently goes nowhere. There does not seem to be a resources section on this page, should this link be pointing somewhere else?

**Comment by craigcook** [comment]
The resources section was removed in https://github.com/mozilla/bedrock/pull/8722 and I just totally missed the link the subnav. We should remove it.
