### ISSUE TITLE
Design - Update Icons in modules on previous What's New & Moments pages

### ISSUE THREAD

**Issue by cgonz0** [mozilla/bedrock#8768]
Original issue: [8469](https://github.com/mozilla/bedrock/issues/8469)

## Description

We need to update icons used in the lower section modules of previous What's New and Moments pages (+ 404 pg) in accordance with our updated icon system.

Specifically:
/welcome/1
/welcome/4
/welcome/5
/welcome/6

70.0/whatsnew
73.0/whatsnew / https://www.mozilla.org/firefox/set-as-default/
74.0/whatsnew 
75.0/whatsnew

404 page

---

#### Success Criteria 
- [x] Icons are provided to developer for coding

#### Approvals
- [x] Brand
- [ ] Team Lead

**Comment by cgonz0** [comment]
all assets located here: 
[/icon_replacement](https://drive.google.com/drive/folders/1U9yffk8KBoFKf2TRrPF4Tu3YExCqeOV6?usp=sharing)

--
^folder on google drive contains mockup & new icons for each page:

**./404:**
404.png
mozilla-icon.svg

**./moments_pages:**
/welcome/1
/welcome/4
/welcome/5
/welcome/6

./moments_pages/welcome/1:
/welcome/1.png
breach_pink.svg
private-browsing_violet.svg

./moments_pages/welcome/4:
/welcome/4.png
cookies_pink.svg
sync_orange.svg
tracking-protection_violet.svg

./moments_pages/welcome/5:
/welcome/5.png
breach_orange.svg
login_violet.svg
password_pink.svg

./moments_pages/welcome/6:
/welcome/6.png
devices_pink.svg
mountain_orange.svg
privacy_violet.svg

**./what's_new_pages:**
70.0
73.0
74.0
75.0

./what's_new_pages/70.0:
tracking-protection_violet.svg
whatsnew70.png

./what's_new_pages/73.0:
devices_pink.svg
mountain_orange.svg
privacy_violet.svg
set-as-default
whatsnew73.png

./what's_new_pages/73.0/set-as-default:
devices_pink.svg
mountain_orange.svg
privacy_violet.svg
set-as-default - landing.png

./what's_new_pages/74.0:
audio_pink.svg
blog_pink.svg
polaroid_orange.svg
whatsnew74_en_de.png
whatsnew74_fr.png

./what's_new_pages/75.0:
breach_blue.svg
history_pink.svg
login_orange.svg
mail_pink.svg
send-tabs_violet.svg
tracking-protection_violet.svg
whatsnew75_monitor.png
whatsnew75_sync.png

**Comment by hoosteeno** [comment]
Let's not update Whatsnew pages older than 75. The pages will fall off the internet along with their icons.

**Comment by hoosteeno** [comment]
@cgonz0 Have you named these images the same as their current names? If not, is there a reason to name them differently? It's far easier to swap images than it is to swap and rename images in code.

**Comment by cgonz0** [comment]
@hoosteeno good call on the what's new pages. 

looking more into into it - it looks like the file names will have to be different in all cases here due to 1) a lot are being replaced with different icons where the names don't match (eraser.svg / cookies_pink.svg) and the ones we're updating also need name updates (arrows.svg = sync_orange.svg).

as you can see, our updated icon system also has color coded names since we have several sets of the same icons. i think this will help us manage the icons better - and they should become part of our web system eventually.
