### ISSUE TITLE
Update https://www.mozilla.org/firefox/features/independent/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8771]
## Description

We need to update copy on the page https://www.mozilla.org/firefox/features/independent/

Current copy:
We champion your right to privacy with tools like Private Browsing with Tracking Protection, which go beyond what Google Chrome and Microsoft Edge offer.

New copy:
We champion your right to privacy with tools like Private Browsing with Tracking Protection.

Success Criteria:
- [ ] Page is updated in en-US
- [ ] String update is made available for all other locales

**Comment by craigcook** [comment]
New string added in https://github.com/mozilla-l10n/www.mozilla.org/commit/2ff04dc28ea43c763c65ca5c538606a7c51caccc
