### ISSUE TITLE
Experiment: re-run /nav on /new

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8773]
## Description

The Brand team would very much like to include the global navigation on the download page to:
- keep users arriving on this page who don't want to download on our site
- enforce the master brand narrative that Firefox is more than a browser

We believe it is worth running again because:
- installs were not measured last time
- load times were not compared last time
- changes to /firefox mean that traffic arriving here from search engines may include different segments than before those changes were picked up by search engines

What are we wanting to do? What are we hoping to affect?
- decrease bounce rate
- improve download:install ratio
- no decrease in installs

---

#### Test Plan

https://docs.google.com/document/d/13lxBKBI5pv8WMUnaHWGSweXYJfLIABRyztEZYSYqHqo/edit

#### Tasks
- [ ] Update /new template to show nav with a variable
- [ ] Add a variation which includes the nav HTML and JS but does not show it

**Comment by stephaniehobson** [comment]
This experiment is ready for review: https://app.convert.com/#/projects/1003343/experiments_report/10035273

**Comment by stephaniehobson** [comment]
@alexgibson can you review please ^?

**Comment by stephaniehobson** [comment]
@alexgibson Oh it was the stub attribution Amy and I wanted to ask about. Can you please make sure that's working as intended as part of the review 🙏

**Comment by alexgibson** [comment]
I tested this on Windows and everything seems ok with stub attribution. I see the convert experiment Id and variation passing along automatically 👍 

I do wonder if the targeting URL is incorrect however. It's currently set to `https://www.allizom.org/en-US/exp/firefox/new/?v=a`, so how is traffic going to get to `?v=a`? Seems like this query parameter might be redundant?

Once I do hit the target URL, I get redirected to a variation correctly. Clicking the download button registers as a goal as expected.

One other thing I did notice was a new CSP error in the console:

```
convert.eb14ea70d301.js:1 Refused to connect to 'https://1003343.metrics.convertexperiments.com/log-rep/' because it violates the following Content Security Policy directive: "connect-src 'self' *.mozilla.net *.mozilla.org *.mozilla.com *.allizom.org www.googletagmanager.com www.google-analytics.com logs.convertexperiments.com https://accounts.stage.mozaws.net/ https://accounts.firefox.com.cn/".
```

This doesn't seem to impede the experiment as far as I can tell, but I'll open a pull request to add an exception for it nonetheless 👍

**Comment by stephaniehobson** [comment]
@alexgibson can't we set the cloudflare redirect to include the v=a?  I could also switch to using no query variables for the control and just test against the b and c ones. The CRO team wants to run an experiment on /new as well though so I thought we could avoid a conflict by having two different pages to redirect to in cloud flare (but maybe cloud flare doesn't work that way?)

**Comment by alexgibson** [comment]
The Cloudflare redirector works by matching targets as opposed to destinations, so we would need to route the combined % of traffic needed for both experiments, and then you can manage distribution in Convert. How you configure that you’ll need to discuss.

Another issue with redirecting in Cloudflare to v=a is that group wouldn’t incur the same redirect that the other variations see, so it may not be a level playing field for comparison.

**Comment by stephaniehobson** [comment]
@alexgibson Okay I set the experiment to run on /new without any variables and added v=a as a variation which I have labeled control. I'll explain to the data scientist to use v=a as the control and not include /new in the analysis.

**Comment by amychurchwell** [comment]
This is now live! 🚀
