### ISSUE TITLE
Bad example breach for Monitor on /firefox/privacy/products

### ISSUE THREAD

**Issue by groovecoder** [mozilla/bedrock#8775]
## Description

Mastercard breach is displayed on https://www.mozilla.org/firefox/privacy/products/ but it's not a great example of Monitor's value-proposition. (Small breach, country-specific, no passwords or even card numbers included.)

### Steps to reproduce

Go to https://www.mozilla.org/firefox/privacy/products/

### Expected result

Some other breach is a better example breach.
Alternatives here: https://monitor.firefox.com/breaches (prefer a breach that is not country-specific and included passwords)

### Actual result

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/71928/79240867-ee07a180-7e37-11ea-8a73-2b8fc3e999b5.png">
(MC doesn't include passwords or card numbers or other data that people might assume is included.)

### Environment

What browser and operating system are you using?

Firefox on Mac

**Comment by slightlyoffbeat** [comment]
One idea: change this to facebook. Its accurate, global, and timely.

**Comment by alexgibson** [comment]
Need a replacement image for this on

**Comment by janbrasna** [comment]
1. This image will be removed from [/products](https://www.mozilla.org/products) after #14220
2. This image will be removed from [/firefox/privacy/products](https://www.mozilla.org/firefox/privacy/products) after #14248

I'll try to find all occurrences to make sure it will be gone completely.

**Comment by stephaniehobson** [comment]
Fixed in https://github.com/mozilla/bedrock/issues/14248
