### ISSUE TITLE
Code - Update Icons in modules on previous What's New & Moments pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8800]
## Description

We need to update icons used in the lower section modules of previous What's New and Moments pages (+ 404 pg) in accordance with our updated icon system.

See - #8768 for the asset attachments
See - https://github.com/mozilla/protocol/issues/575 for work to add the icons to Protocol

Specifically:
- [ ] /welcome/1
- [ ] /welcome/4
- [ ] /welcome/5
- [ ] //welcome/6

- [ ] /75.0/whatsnew

- [ ] /404 page

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Approvals
- [ ] Team Lead (Brand has already approved the new images)

**Comment by ejregithub** [comment]
- Note: Need to add new icons in Protocol, Eric to create a card there for that. this remains the card for the corresponding work on /bedrock

**Comment by ejregithub** [comment]
Blocked on consensus for sizing, etc. - @craigcook to unblock

**Comment by alexgibson** [comment]
Closing this as outdated
