### ISSUE TITLE
Copy - Update Edge comparison page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8805]
Write new copy for the Edge browser comparison page corresponding to the latest releases/feature updates

[Copy doc](https://docs.google.com/document/d/1waoo2Uh7Ap90YzFq36qHs7pAdf-uLS8_JPO3CVAGoF4/edit?usp=sharing)

###Approvals
- [x] SEO (@rraue)
- [x] Brand - Natalie
- [x] TL - @hoosteeno 
- [x] Accountable - Eduardo Ibarra

**Comment by rantley** [comment]
https://docs.google.com/document/d/1waoo2Uh7Ap90YzFq36qHs7pAdf-uLS8_JPO3CVAGoF4/edit?usp=sharing
