### ISSUE TITLE
Review IE comparison page for updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8814]
Review the page for updates in content (copy & comparison tables), then make changes as required.

###Success Criteria
- [ ] Copy is updated with latest release information
- [ ] Comparison tables reflect latest release information

###Approvals
- [x] Brand - Natalie
- [ ] Brand - Clio
- [ ] SEO - Raphael
- [ ] Team Lead - Hoosteeno
- [ ] Accountable - Eddie

**Comment by rantley** [comment]
https://docs.google.com/document/d/1usQPe_GgGcHfvL74UrtwB9de3qTw497Bj873Q6oga9Y/edit
