### ISSUE TITLE
Review Opera comparison page for updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8815]
Review the page for updates in content (copy & comparison tables), then make changes as required.

###Success Criteria
- [ ] Copy is updated with latest release information
- [ ] Comparison tables reflect latest release information

###Approvals
- [x] Brand - Natalie
- [ ] Brand - Clio
- [ ] SEO - Raphael
- [ ] Team Lead - Hoosteeno
- [ ] Accountable - Eddie

**Comment by rantley** [comment]
https://docs.google.com/document/d/1bS5DkZCSnpCIR7l04eJdjJUYzUQ0k6WM6pDOyW0oB8Y/edit
