### ISSUE TITLE
Design: Mobile banner takeover

### ISSUE THREAD

**Issue by cgonz0** [mozilla/bedrock#8823]
## Description

Update/refresh experiment design according to updated /new design

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Design is ready for coding and attached to this card
- [ ] All approvals complete

#### Approvals
- [x] Brand
- [ ] Team Lead

**Comment by cgonz0** [comment]
this design is moving over to NA Brand team -- it will be implemented within the new /new page redesign.

**Comment by hoosteeno** [comment]
@cgonz0 @dzingeek Can we find a near-term solution to this that enables us to start capturing some of the benefits of this CRO optimization while the overall /new redesign is underway?

**Comment by cgonz0** [comment]
back on the websites team - i'll tackle the interim design.

**Comment by cgonz0** [comment]
[sketch file (specs)](https://share.goabstract.com/edea5927-fae8-4725-85ab-0beccc1fae5b?sha=031380631052797b26cf22bfc1f1b8ae87b93649)

background:
[NoodleBg.svg](https://app.zenhub.com/files/1616665/85f5ea2f-0a04-4b6c-a79b-04fe4808c69d/download)

![Slice.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/4aeb800e-1697-4322-833f-79c9b73cbabc)
