### ISSUE TITLE
Design: Global nav CTA should match page CTA on certain pages

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8827]
## Description

On some pages (e.g. [the Mobile page](https://www.mozilla.org/en-US/firefox/mobile/)), we hide the global navigation CTA because it competes with the primary on-page CTA.

On other pages (e.g. [the Lockwise page](https://www.mozilla.org/en-US/firefox/lockwise/)), we don't.

With the release of Sticky Navigation, neither of those seems optimal. What we really want is the page CTA to be in the global navigation, on certain pages. 

The list of pages -- and whether/how we can algorithmically identify them -- is TBD. This card is for design team to figure out which pages and what commonalities they have.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
@kropp would you mind working on the list of pages where this behavior should occur? Our least-best option (but still feasible) will be to do this on a manually maintained list. Our most-best option will be to find some existing characteristic of pages where this behavior should occur that can be used sitewide to trigger this behavior.

**Comment by kropp** [comment]
I would love to help, but I don't get what are you talking about, sorry.

**Comment by hoosteeno** [comment]
Oh, I'm very sorry. I meant @justinkropp. Please forgive the random ping!

**Comment by justinkropp** [comment]
@hoosteeno Happy to look into this. Agreed that with the sticky nav now giving us the option to show a primary CTA at all times during a user scrolling down a page, rethinking the above relationship on key pages is idea. I'll try to put together a starter list of pages where we need to focus on mitigating the competition between page CTAs (primarily those in the nav and hero section).

**Comment by alexgibson** [comment]
A note that whilst we can do the design / UX work here, the coding part is likely blocked by activating Fluent, as it will imply adding new strings to `navigation.ftl`.

**Comment by hoosteeno** [comment]
@justinkropp  can you update us on this?

**Comment by justinkropp** [comment]
@hoosteeno I've been using [this spreadsheet](https://docs.google.com/spreadsheets/d/1h85nJEfg6qWn6WcLgSqjj8zC7IZiYVreyappa3pBo2o/edit?usp=sharing) to document pages where the CTAs in the primary navigation and hero sections are in opposition. It's rough. I am hoping to wrap up next week.

**Comment by hoosteeno** [comment]
This has been brand reviewed. Next steps
* @hoosteeno to review
* create new feature card

**Comment by hoosteeno** [comment]
@justinkropp Thanks, it looks good. I think we need to capture the non-Fx experience in this spreadsheet, too. And I think we should add a column to capture the changes we recommend. What do you think?

**Comment by justinkropp** [comment]
@hoosteeno Sounds good. I'll start looking at non-Fx pages.

**Comment by hoosteeno** [comment]
> @hoosteeno Sounds good. I'll start looking at non-Fx pages.

I mean we need to look at the CTAs for non-Fx visitors to pages that you've highlighted.

**Comment by justinkropp** [comment]
@hoosteeno That's what I thought you meant. Sorry is my reply was confusing.

**Comment by alexgibson** [comment]
Closing old / stale issues. Feel free to re-open if still relevant
