### ISSUE TITLE
Design - WNP77

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8835]
Design for WNP77 about the Picture in Picture feature

[The (winning) copy](https://docs.google.com/document/d/1qsOpXefbBfkzWHn1G4p59wCGfXf_aNoRMnZ8oczWp1Y/edit?usp=sharing)

###Approvers
- [x] Brand - Clio
- [x] Team Lead - Hoosteeno
- [x] Accountable - MWarther

**Comment by cgonz0** [comment]
[wnp77-PiP_assets.zip](https://app.zenhub.com/files/1616665/f6930add-6fec-468a-b350-3e2053e16ba8/download)

![wnp77 PiP.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/74beb789-d237-4444-ae22-bc4225c2351f)

**Comment by ejregithub** [comment]
@craigcook - see assets above ^
