### ISSUE TITLE
Code - WNP77

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8836]

**Comment by craigcook** [comment]
On demo: https://www-demo3.allizom.org/firefox/77.0/whatsnew/all/

**Comment by cgonz0** [comment]
thanks @craigcook 

can we reduce the video size to 500px width?

also noticed a little issue with the middle icon - something going on with the leaf rendering...
i exported a modified version that will hopefully be a fix. 

and i changed some of the colors of the other icons - so here's a new set:
[wnp-PiP_assets_update.zip](https://github.com/mozilla/bedrock/files/4625028/wnp-PiP_assets_update.zip)

let's leave the left-aligned content for mobile, i think it's fine here

thanks!
