### ISSUE TITLE
Moments/Browser Welcome page (# 8)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8840]
## Description

The next Moments/Browser Welcome page (# 8)

We will take the content from WNP 76, insert all 4 areas into the welcome page template and will need to take a new intro/headline approach

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] It's live

#### Approvals
- [x] A - MWarther
- [x] TL - Hoosteeno
- [x] Brand/Design - Clio
- [x] Brand/Copy - Natalie

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
