### ISSUE TITLE
[Epic] Make a simplified version of the download button

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8860]
## Description

The current download button helper is versatile in the way that it supports multiple products (release, beta, nightly etc) and can also have the option to download directly (vs link to `/download/thanks/`). A large proporation of use-cases on the website exist to just serve the main Firefox release verson however, and all link directly to the `/download/thanks/` page.

For those use-cases, the HTML could probably be simplified to just the following:

```html
<div class="mzp-c-button-download-container">
  <a href="/%LOCALE%/firefox/download/thanks/" class="mzp-c-button mzp-t-product" data-direct-link="https://download.mozilla.org/?product=firefox-stub&amp;os=win&amp;lang=%LOCALE%">
    Download Firefox
  </a>
  <small class="mzp-c-button-download-privacy-link">
    <a href="/%LOCALE%/privacy/firefox/">Firefox Privacy Notice</a>
  </small>
</div>
```

Note that the `data-direct-link` attribute would still need to exist, but only to serve Windows builds to legacy IE users (IE9 and below).

The other thing that's omitted here is all the conditional markup for [unsupported messaging]( https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/includes/download-button.html#L42-L59), such as:

```html
<p class="unsupported-download">
  Your system doesn't meet the <a href="/firefox/system-requirements/">requirements</a> to run Firefox.
</p>
 ```

Having all this content in every download button, often 2 or 3 times per page, adds a lot of hidden content that's often not needed to the user. This can add to page weight, make our content harder to understand for crawlers, and can also surface as confusing messages in search results (see https://github.com/mozilla/bedrock/issues/8739).

Instead of having this content in every page of the website, we could move it to `/download/thanks/`. This page could then serve as the main place for such conditional messaging, allowing us to use a simplified download button helper for most of the site.

**Comment by pmac** [comment]
Love it. Concentrating the complexity on the `/thanks/` page makes a lot of things easier to reason about, and potentially offer a better UX.

**Comment by mitchell-frost** [comment]
Can I work on this?

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9102

**Comment by alexgibson** [comment]
Depends on #8454

**Comment by alexgibson** [comment]
Depends on #9137

**Comment by alexgibson** [comment]
@hoosteeno the simplified button is now up on demo: https://www-demo2.allizom.org/en-US/firefox/new/

One thing I may need some help with here is to verify that GA events for the downloads are still working as expected.

I've put the simple button on the following pages/areas:

- Download button in the global navigation (view in non Firefox browser).
- Download buttons on https://www-demo2.allizom.org/en-US/firefox/new/
- Download buttons on home pages (view in non Firefox browser):
        - https://www-demo2.allizom.org/en-US/
        - https://www-demo2.allizom.org/de/
        - https://www-demo2.allizom.org/fr/
        - https://www-demo2.allizom.org/es-ES/

Can you spare some time to help sanity check? Thanks

**Comment by alexgibson** [comment]
@hoosteeno I think this is code ready, but is pending some GA verification. Is that something you can help with?

**Comment by hoosteeno** [comment]
Thanks. A couple notes here.

1. In en-US, I clicked the main download button on /firefox/new/, the secondary download button on the homepage, and the download button in the nav on /firefox/, and in all cases the datalayer event on click had a different payload. On the demo instance, the platform is not populated: `el: "Firefox for unavailable",`
![Screen Shot 2020-09-15 at 8 34 35 AM](https://user-images.githubusercontent.com/94519/93224483-60094d00-f72e-11ea-8699-edee47b7fb74.png)
    * notably, the de/fr instance of demo is NOT missing the platform anywhere -- not on homepage, in download page, or in nav

    The `el` attribute in the payload is the event label. We can see this new event label in GA events for the demo instance:

![Screen Shot 2020-09-15 at 9 19 40 AM](https://user-images.githubusercontent.com/94519/93230363-d4df8580-f734-11ea-92ae-19827532725b.png)

  The event label is a part of the goal setup. When an event labeled `Firefox for Desktop` occurs, a goal counter called `Firefox Download - Desktop` increments. Here's the goal setup:

![Screen Shot 2020-09-15 at 9 20 24 AM](https://user-images.githubusercontent.com/94519/93230585-0fe1b900-f735-11ea-9ea1-f48e282249bd.png)
In summary, fixing the event label will ensure that we continue counting these downloads with our desktop download goal.


2. The current nav download button has an id, `protocol-nav-download-firefox-osx", which is missing on the demo nav button. I'm not sure if this is a functional change so I'm unsure if it needs attention. Similarly,
    * the current homepage button has an id `download-secondary-osx`, missing on demo
    * the current button on /new has an id `download-button-desktop-release-osx`, missing on demo

3. On both current and demo instances, locales behave differently on the download page than elsewhere. If I (an en-US browser user) start on the fr/de/es homepage, and download, I get the en-US /thanks page. But if I start on the fr/de/es download page, I get the /thanks page in my starting locale. This seems like a difference that we may want to understand, at least, and standardize if possible; but I'm not sure if the fix fits in scope of this bug.

4. On both current and demo instances, I made a request with the parameter `?testing-dl` at the end of the URL. This makes it possible to identify an individual session in GA's realtime dashboard (by filtering on that URL) for both [current](https://analytics.google.com/analytics/web/#/realtime/rt-event/a36116321w64087799p65789850/metric.type=5&filter.list=10~~=testing-dl;/) and [demo](https://analytics.google.com/analytics/web/#/realtime/rt-event/a36116321w64087799p66842818/metric.type=5&filter.list=10~~=testing-dl;). On both current and demo instances, I saw the same event appear for homepage, nav, and download page downloads:

![Screen Shot 2020-09-15 at 9 16 30 AM](https://user-images.githubusercontent.com/94519/93229796-381ce800-f734-11ea-8be9-b65b47b60c95.png)

This gives me confidence that the event is still coming through the way we expect. 

Great work!

**Comment by alexgibson** [comment]
> In en-US, I clicked the main download button on /firefox/new/, the secondary download button on the homepage, and the download button in the nav on /firefox/, and in all cases the datalayer event on click had a different payload. On the demo instance, the platform is not populated: el: "Firefox for unavailable",

This should be fixed and is currently deploying to demo.

> The current nav download button has an id, protocol-nav-download-firefox-osx, which is missing on the demo nav button. I'm not sure if this is a functional change so I'm unsure if it needs attention...

Not required for the simple button

> On both current and demo instances, locales behave differently on the download page than elsewhere. If I (an en-US browser user) start on the fr/de/es homepage, and download, I get the en-US /thanks page. But if I start on the fr/de/es download page, I get the /thanks page in my starting locale. This seems like a difference that we may want to understand, at least, and standardize if possible; but I'm not sure if the fix fits in scope of this bug.

This is intentional (not a bug) and unrelated to this PR. Happy to discuss in another channel if you're curious why this is.

I saw you emailed adswerve to take a look at this als (thank you!). Let's wait to se if they have any further comments.

**Comment by hoosteeno** [comment]
Adswerve ran a round of QA and determined that the demo site is working as expected from a measurement perspective. :shipit: 

<img width="1204" alt="Screen Shot 2020-09-18 at 8 10 10 AM" src="https://user-images.githubusercontent.com/94519/93607366-77427780-f986-11ea-886b-6ab860dcf4d8.png">

**Comment by hoosteeno** [comment]
@stephaniehobson @alexgibson  Let's merge either on 9/21 or 10/5. When this lands in prod, we need to notify @rraue @hoosteeno to do spot checks before/after.
