### ISSUE TITLE
Duplicate IDs on /firefox/mobile/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8867]
## Description

Picked up on our daily [Lighthouse report](https://www.webpagetest.org/lighthouse.php?test=200430_P5_a13fd226d5d0f508a9005a30438fd226): there are multiple elements on the /firefox/mobile/ page that share the same ID, which can be an issue for a11y and also introduce potential bugs in functionality.

### Steps to reproduce

1.) Visit https://www.mozilla.org/en-US/firefox/mobile/ and https://www.mozilla.org/en-US/exp/firefox/mobile/ 

### Expected result

Page element IDs should all be unique

### Actual result

Multiple elements share the following Id:

```
<ul class="mobile-download-buttons firefox" id="mobile-download-buttons-firefox">
```

### Environment

N/A

**Comment by shadowoflight** [comment]
Hi, How can i start working in this project

**Comment by amychurchwell** [comment]
Hi @shadowoflight, you are welcome to start working on this issue.

Here is a link to our docs on how to get started developing on bedrock: https://bedrock.readthedocs.io/en/latest/install.html

I'm not sure what your experience level is, but here are some github docs about pull requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ishantd** [comment]
Greetings.
Can I start working on it?

**Comment by wigzen** [comment]
sir how can i communicate with i am new in git this is my first fork
