### ISSUE TITLE
Add H2 2019 Transparency Report

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8870]
Update the Transparency report for H2/2019

#### Success Criteria
- [x] The new report page for "July-December 2019 Report" is created with [this content](https://docs.google.com/document/d/1v7BYEA0A8N0qNlDGgm4mkscztHPf67iF7KGsWFhlmyQ/edit?usp=sharing) and assigned to:  https://www.mozilla.org/about/policy/transparency/jul-dec-2019/
- [x] The link to the new report is updated on the main landing page
- [x] The link to the January-June 2019 Report is added to the main landing page

#### Approvers
- [ ] Team Lead (Hoosteeno)
- [ ] Legal (DNazer)

**Comment by alexgibson** [comment]
Pull request opened against the private repo here: https://github.com/mozilla/bedrock-private/pull/85

**Comment by alexgibson** [comment]
This is now up on demo for stakeholder review: https://www-demo2.allizom.org/en-US/about/policy/transparency/jul-dec-2019/

**Comment by alexgibson** [comment]
@ejregithub just a heads up we're still waiting on some kind of content review here, or are we ok to move forward and get this reviewed / shipped?
