### ISSUE TITLE
Ensure Firefox release notes are discoverable easily for India and potentially other countries

### ISSUE THREAD

**Issue by swarnava** [mozilla/bedrock#8886]
As a Firefox Beta user, I would like to know more about the upcoming changes that are coming in beta release. However, since I am from India, I am getting this link https://www.mozilla.org/en-US/firefox/77.0a2/whatsnew/india/ and there is no way to find out the release notes.

![image](https://user-images.githubusercontent.com/1162991/81080096-fd957a00-8f0d-11ea-9e72-de2111e935a8.png)

### Expected result

It should have a navbar or something where I can navigate to [regular URL](https://www.mozilla.org/en-US/firefox/77.0a2/whatsnew/all/?oldversion=76.0) or release notes.

### Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0

**Comment by alexgibson** [comment]
This page no longer exists, and all regular /whatsnew pages contain a release notes link. Closing
