### ISSUE TITLE
Remove /country-code.json and use MLS for our geo needs

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8895]
The Mozilla Location Services (MLS) team will get us an API key to use. This was originally implemented in #3819, and then replaced with `/country-code.json` in #4915.

**Comment by pmac** [comment]
Actually, with #8976 because we need to be able to get country codes server side, we should just use this for our `/country-code.json` endpoint and keep the front-end code the same. I think I may close this one in favor of just doing that as part of the other issue, which is already done in the PR actually.

Any thoughts here @alexgibson ?

**Comment by alexgibson** [comment]
> I think I may close this one in favor of just doing that as part of the other issue, which is already done in the PR actually.

Makes sens to me, thanks @pmac 👍
