### ISSUE TITLE
Newsletter form fields appear higher in z-space than sticky nav

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8905]
## Description

The form fields for newsletter signups appear on top of sticky navigation, while the rest of page body content appears behind sticky navigation:

![Screen Shot 2020-05-11 at 2 31 39 PM](https://user-images.githubusercontent.com/94519/81608934-4462f400-9394-11ea-9d38-59d76dc585f4.png)

### Steps to reproduce

Visit https://www.mozilla.org/en-US/newsletter/. Scroll all the way down. Scroll a tiny bit up. Look at the form field.

### Expected result

The form field should be hidden by the navigation when they overlap.

### Actual result

The form field hides the navigation when they overlap.

**Comment by alexgibson** [comment]
@hoosteeno i think this may be caused by your add-on, see https://github.com/mozilla/fx-private-relay/issues/245

**Comment by hoosteeno** [comment]
Yep! Thanks. INVALID.
