### ISSUE TITLE
WNP77: Extract strings for l10n

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8909]
Strings are final, we can extract the strings.

**Comment by craigcook** [comment]
Strings PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/394

**Comment by craigcook** [comment]
Done in https://github.com/mozilla-l10n/www.mozilla.org/commit/16956a2ad2d14bd6ec688517670b2a8ff56f0d11
