### ISSUE TITLE
Add Table of Contents to Mozilla Root Store Policy

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [mozilla/bedrock#8911]
It would be really helpful for navigating if there were a table of contents at the top of the Mozilla Root Store Policy page - https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/ .  There are already anchors for all of the sections, so hopefully it won't be too much trouble.
Thanks.

**Comment by grininja** [comment]
I want to work on this issue
