### ISSUE TITLE
[cro] Implement a way for functional tests to be excluded from experiments

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8917]
## Description

I'm not sure what a solution looks like right now, but filing this issue as it's been in the back of my head for too long. When we implement traffic cop experiments, such as in https://github.com/mozilla/bedrock/pull/8901, we often have to skip functional tests for a page because the experiment alters the expected functionality. This is more work for the developer, and also loses us test coverage whilst experiments are running.

We should develop a mechanism by which functional tests are excluded from TC experiments. One possible solution could be for tests to use an `automation=true` URL parameter which traffic cop can look for and exclude. There may well be other options worth exploring too.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Functional tests are excluded from experiments.
- [x] Functionality is documented in A/B testing docs.

**Comment by pmac** [comment]
Or can we disable TC during a test run by having the test run use a URL param that TC can look for and disable itself? e.g. `?tc=ignore`

**Comment by pmac** [comment]
Oh. I think I just said the same thing you did. I misread the first time :) Sounds good. 👍
