### ISSUE TITLE
Remove the x-robots-tag header

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8919]
Bedrock currently sends the following header with responses: `x-robots-tag: noodp`. This header is still supported, but the `noodp` value is mostly not it seems. [Google's docs](https://developers.google.com/search/reference/robots_meta_tag) don't mention it at all, and this page [suggests that no other engines really support it](https://yoast.com/robots-meta-tags/) either.

**Comment by pmac** [comment]
Do you have thoughts on this @rraue ?

**Comment by rraue** [comment]
Lets remove it, odp is dead since 2017.

**Comment by pmac** [comment]
Will do. Thanks!
