### ISSUE TITLE
Update "leadership" image on the /about page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#8923]
The main "about" page has a picture of Chris Beard, who is no longer at Mozilla. We should replace that with a picture of Mitchell (or maybe even something else). I expect we'll need to work with comms for an approved image.

**Comment by grininja** [comment]
I want to Work on this issue.

**Comment by ejregithub** [comment]
@craigcook @cgonz0 - the original file appears to be 3000 x 2000, the same 3/2 ratio as the recommended size of 1200 x  800. Can we use this without cropping, to replace to photo w. Beard?  https://drive.google.com/file/d/15JU8sv0so6HQXdIE7BSrS4YG7WY78Er_/view?usp=sharing

**Comment by justinokelly** [comment]
HI there, 

Could we actually crop it so it shows only what we see below? We don't need to see the back of Sean.

Justin

<img width="770" alt="Screen Shot 2020-06-08 at 1 59 45 PM" src="https://user-images.githubusercontent.com/59577857/84079999-55e9ec80-a990-11ea-8937-8b960ab31660.png">

**Comment by cgonz0** [comment]
this crop should be about the right dimensions and image should still be large enough.

![Berlin All Hands Jan 2020 Mitchell Baker Dave Camp Sean White Amy Keating_crop](https://user-images.githubusercontent.com/29640968/84080905-d3622c80-a991-11ea-8592-42b24b3df704.jpg)

**Comment by hoosteeno** [comment]
@hoosteeno to talk to Justin O about this one.

**Comment by hoosteeno** [comment]
Could we use the one that's on the front page right now?

![Screen Shot 2020-07-17 at 3 31 13 PM](https://user-images.githubusercontent.com/94519/87832200-ac293580-c842-11ea-9b0a-88f75fea900c.png)

**Comment by ejregithub** [comment]
Noting that we are unblocked and using the image above from the homepage.
