### ISSUE TITLE
rheet doesn't play in the browser

### ISSUE THREAD

**Issue by Pike** [mozilla/bedrock#8934]
## Description

https://www.mozilla.org/en-US/about/governance/policies/commit/ links to `rheet.wav`, but you can't listen to it in the browser.

### Steps to reproduce

Clicking on "Need to hear a rheeet?"

### Expected result

A "rheet" should play

### Actual result

A download dialog

### Environment

Firefox release on macos.

**Comment by miketaylr** [comment]
Alternate proposal: it should be removed (why is this even here?)

**Comment by alexgibson** [comment]
This was removed in https://github.com/mozilla/bedrock/pull/9066
