### ISSUE TITLE
Add link to Firefox Support in Firefox footer

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8935]
In the Firefox column of the footer we should add a link to Sumo.

**Comment by stephaniehobson** [comment]
@alexgibson the footer is in fluent now, is it okay if I make this change or should I hold off until the switch over?

**Comment by alexgibson** [comment]
> @alexgibson the footer is in fluent now, is it okay if I make this change or should I hold off until the switch over?

yes please wait for Fluent to be live in Pontoon before pushing any new changes through (switchover is happening on Friday).

**Comment by alexgibson** [comment]
@stephaniehobson this is now unblocked if you want to make the change.
