### ISSUE TITLE
Add Firefox for iOS and Android to the /firefox/all/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8938]
## Description

Firefox for iOS is noticably absent from the /firefox/all/ page. The technical reason for this is because Apple only allows users to download from the App Store, but from a user perspective I'd still expect to find Firefox for iOS mentioned somewhere on this page as an option:

https://www.mozilla.org/en-US/firefox/all/

We should find a simple way to add iOS as a download option, even if it just links to the App Store.

For Android, now that [Fenix](https://github.com/mozilla-mobile/fenix) is Firefox for Android, we don't have a good way to link to the .apk files ([see bug 1663735](https://bugzilla.mozilla.org/show_bug.cgi?id=1663735)): the releases section of the GitHub repo isn't automatically updated and the builds aren't being uploaded so that bouncer can redirect to them.

The proposal is that we remove Android from the download selection form on /firefox/all/ and we add the App Store and Play Store buttons to the bottom of the left-hand column on the page so that people still have options for downloading our mobile apps.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Firefox for iOS is presented as an option for download on /all
- [x] Firefox for Android (Fenix) is presented as an option for download on /all

**Comment by alexgibson** [comment]
> The proposal is that we remove Android from the download selection form on /firefox/all/ and we add the App Store and Play Store buttons to the bottom of the left-hand column on the page so that people still have options for downloading our mobile apps.

I've been thinking about the UX here and even though it may be easier to remove Android from the product menu technically, I'm not sure that makes for the right user experience. Keeping all products in one menu feels clearer to me (including adding iOS ion there). We could point the download button to the relevant store and keep the UI consistent, or alternatively we could replace the button with a store badge.

**Comment by hoosteeno** [comment]
Needs some UX work before it's ready for code -- @justinkropp this is one to pick up when you have bandwidth.

**Comment by justinkropp** [comment]
I've though about both approaches as outline above, and I'm more in alignment with Alex's suggestion that we keep Android in the product menu, add in iOS, and point the download button to the appropriate location. 

As an alternative addition, could we also include the App Store and Google Play buttons on the page (but separate from the product menu) where appropriate?

**Comment by hoosteeno** [comment]
> As an alternative addition, could we also include the App Store and Google Play buttons on the page (but separate from the product menu) where appropriate?

I think we will have to rework the page a bit anyway to accommodate these new products:

![Screen Shot 2020-09-23 at 2 24 45 PM](https://user-images.githubusercontent.com/94519/94065577-95eea700-fda8-11ea-9d7d-5d5e293599c8.png)

For example, after this change, iOS and Android will not be downloads, and they will not have architecture-specific options, so the confirmation area will need to behave differently in those two cases. Since we have to make it more complicated anyway, I think swapping the button for an app-store button would be a nice touch. Roughly:

![Screen Shot 2020-09-23 at 2 28 17 PM](https://user-images.githubusercontent.com/94519/94065961-0b5a7780-fda9-11ea-8f92-05ebe9af91ce.png)

**Comment by justinkropp** [comment]
> Since we have to make it more complicated anyway, I think swapping the button for an app-store button would be a nice touch.

💯 on board with this approach. I was unsure if we could switch out the buttons on the fly as a result of the user's selection, but if we can this will help keep this experience as simple as it can be.

**Comment by justinkropp** [comment]
I took a quick stab at cleaning up this ux a bit (based on the above thread).

**Changes**:

I thought that the content that provides a summary of what you're about to download could feel a bit more like it was a part of the drop-down menus above. 

- "You are about to download:" down become a label.
- added visual space between the details show below this label (platform > Firefox)
- added 1px border between these details 
- if possible, I'd like to move the download button and app store badges to be aligned at the bottom right of the form
----
<img width="1312" alt="all" src="https://user-images.githubusercontent.com/1461798/94465220-92cf2e80-018d-11eb-9c22-466e1ed82258.png">
----
<img width="1312" alt="all-1" src="https://user-images.githubusercontent.com/1461798/94465238-98c50f80-018d-11eb-8d4a-d95bc2bda133.png">

**Comment by justinkropp** [comment]
@alexgibson Did the above design approach makes sense to you? Do you need anything else design-wise on this issue?

**Comment by alexgibson** [comment]
@justinkropp i think this makes sense. I’ll see if I have time to get to this this week. Thanks

**Comment by justinkropp** [comment]
You're welcome. Just wanted to follow up. :)

**Comment by stephaniehobson** [comment]
Picking this up. Sorry to open the UI question again but... 

I would expect our users to be thinking about their OS not their "installer" and I would not expect someone who wants Firefox for Android to know they need to pick a different "Firefox" out of the "Which browser would you like to download?" list.

Is it possible to switch the fields to be:

Platform: [Android | iOS | MacOS | Windows 32 | Window 64]
Version: [Firefox | Firefox Beta | Firefox Nightly]
Language: [English | etc]

Maybe this isn't possible with the way the data is currently catagorized? Was it considered when the page was created initially?
