### ISSUE TITLE
Pocket image on homepage is blurry

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8946]
## Description

The pocket image on www.mozilla.org is blurry. Can we replace with a higher resolution version?

Existing version: https://www.mozilla.org/media/contentcards/img/home-2019/card_1/reads.9b22d39e5588.jpg

High res version attached in jpg. [Link to folder containing svg.](https://www.dropbox.com/sh/peewt8girv2ynp7/AADcjfqAbn5HnAtRC9uRcwICa?dl=0)

![Vector-reader](https://user-images.githubusercontent.com/94519/83047097-24bf0300-a005-11ea-9d42-842a90a34f69.jpg)

**Comment by stephaniehobson** [comment]
On it. Thank you, I hardly ever get large enough images for the top spot and have just stopped asking. :(
