### ISSUE TITLE
Redirect "/donate" to Mozilla donation site

### ISSUE THREAD

**Issue by cadecairos** [mozilla/bedrock#8949]
## Description

The team here at MoFo were wondering if it'd be alright to submit a PR to have `https://www.mozilla.org/donate` redirect requests to `https://donate.mozilla.org` (ideally preserving locale, but our donate site has logic to load the browser's preferred language)

I'm not sure how often that url is even hit by people looking to donate to Mozilla - if we have data on that maybe it'll inform whether it's worth doing thos

### Steps to reproduce

Navigate to https://www.mozilla.org/donate

### Expected result

Redirect to https://donate.mozilla.org/

### Actual result

404 not found error

**Comment by alexgibson** [comment]
Sure thing - would you like any type of utm parameters added to the redirect, so you know where the traffic is coming from?

**Comment by alexgibson** [comment]
Fwiw, looking in GA I see zero traffic for /donate, so I don't think it is linked to from anywhere historically.

**Comment by cadecairos** [comment]
Thanks for checking in GA, I'll bring it up with my director to see if he want's to bother, and I'll update here.

**Comment by cadecairos** [comment]
Yeah we're still interested in adding a redirect. I think if we add `utm_source=mozilla.org` as a query param we'll be in good shape.

**Comment by cadecairos** [comment]
@alexgibson is this a change that needs to be made via code, or a change that must be made in django as an admin?

Happy to open the PR if it's the latter.

**Comment by alexgibson** [comment]
@cadecairos happy to help here, this should do it: https://github.com/mozilla/bedrock/pull/8977

**Comment by cadecairos** [comment]
Thank you! 🎉
