### ISSUE TITLE
Turn CTA links into buttons on /firefox and /browsers

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8950]
## Description

The CRO Team ran an experiment that identified an optimization opportunity in our links on /firefox and /browsers. Specifically, styling CTAs as buttons improved their click rate. The experiment report is here: https://docs.google.com/document/d/11XSa1FSWeHXQ0-dSBU21KmN06NkXCW04owquGyZFfKI/edit#heading=h.i4bqf6o9zs3g. 

We should PR a change (to Protocol?) that changes the CTA links on Firefox to combo buttons. 

Here is a CTA link:
<img width="280" alt="Screen Shot 2020-05-27 at 4 05 39 PM" src="https://user-images.githubusercontent.com/94519/83077082-f7d61480-a033-11ea-9293-c1f4b8e31136.png">

Here is a combo button:
<img width="362" alt="Screen Shot 2020-05-27 at 4 05 46 PM" src="https://user-images.githubusercontent.com/94519/83077135-0ae8e480-a034-11ea-8b77-266d1adec8a6.png">

There are 2 locations to make this change on https://www.mozilla.org/en-US/firefox/browsers/ -- in the Desktop and Mobile sections.

There are 3 locations to make this change on https://www.mozilla.org/en-US/firefox/ -- in the Browser, Lockwise and Pocket sections.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Change is made (in Protocol?)
- [x] Change is deployed to www.mozilla.org
  - 2 locations in /browsers
  - 3 locations in /firefox

**Comment by hoosteeno** [comment]
@justinkropp  can you add any files or specifications to help make this work ready for development?

**Comment by justinkropp** [comment]
@hoosteeno We should use the combo-button that currently exists on [/enterprise](https://www.mozilla.org/en-US/firefox/enterprise/).

**Comment by alexgibson** [comment]
Seeing as this code is already in bedrock, I think we can re-purpose it for other pages until it exists more formally in Protocol. I can pick this one up 👍

**Comment by justinkropp** [comment]
Thanks @alexgibson
