### ISSUE TITLE
[6/1/20] Leadership page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8951]
## Description

Leadership page updates

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Removed: 'Steering Committee' under Mary Ellen Muckerman and Sean White's names in the Management Teams section.
- [ ] Removed: 'Chair' under Mitchell's name in the Board of Directors - Moco.
- [ ] Live by EOD on Monday June 1st

**Comment by craigcook** [comment]
This is live: https://www.mozilla.org/about/leadership/
