### ISSUE TITLE
HTML escaping issue on releasenotes content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8957]
## Description

[Tests are failing](https://gitlab.com/mozmeao/www-config/pipelines/150816732/failures) on the Firefox 77.0beta releasenotes page.

### Steps to reproduce

1.) Open https://bedrock-test.moz.works/en-US/firefox/77.0beta/releasenotes/
2.) Scroll down to the bottom of the page.

### Expected result

There should be a bottom section with a download button, like on [this page](https://bedrock-test.moz.works/en-US/firefox/76.0beta/releasenotes/):

![image](https://user-images.githubusercontent.com/400117/83243856-69c66f00-a196-11ea-9e4f-4e3b68b64b08.png)

### Actual result

The bottom of the page is missing, due to an HTML escaping issue with a rendered `textarea` in the release notes content. It looks like the rest of the page's HTML is rendered as a string inside the textarea.

![image](https://user-images.githubusercontent.com/400117/83243974-9b3f3a80-a196-11ea-8ccd-282318620abc.png)

### Environment

Any browser

**Comment by pmac** [comment]
It's tough because there is a lot of legit HTML in the notes. I'll do some analysis to see if we can limit the tags though. I'm sure we could at least escape form elements like this since they should definitely not be in there.
