### ISSUE TITLE
Remove lang file l10n commands and docs

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8962]
We are now in read-only mode for lang files. We will not be extracting any more strings using the old commands. We should therefore remove these commands and the docs for them from the project. 

The commands are:

* `l10n_check`
* `l10n_extract`
* `l10n_merge`

**Comment by Patil2099** [comment]
Hi @pmac, I would love to help you in fixing this issue. Can I get some instructions to fix this issue?

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/10660
