### ISSUE TITLE
Add installer type to stub attribution

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8963]
## Description

The stub attribution service [will have a new field, "installer_type"](https://github.com/mozilla-services/stubattribution/pull/98/files), which needs an integer to specify the installer type. We need to add this as a parameter to stub attribution referral links and send the correct integer to specify which kind of installer is being downloaded.

The specs for this field are attached to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1598111), which links to [this spreadsheet](https://docs.google.com/spreadsheets/d/1z9IOWZrjI6fZ_vfMqErh-dzJBAz6YNz3D-oDI4vfsPE/edit#gid=0). TLDR:

```
installer_type=

0: neither Mozilla stub nor Mozilla full installer
1: Mozilla stub installer
2: Mozilla full installer
```

This bug blocks https://github.com/mozilla/bedrock/issues/8910.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] installer_type field added to stub attribution referrals as a parameter, with a value corresponding to the installer type as described in the spec

**Comment by alexgibson** [comment]
This might be a little tricky on bedrock as when someone lands on a webpage, and the stub attribution request happens, we don't yet know what someone will ultimately click on (it could be a stub installer, a full installer, on the same page, or a different page).

I'll give this some thought as to how best we might handle this. Perhaps the request could deliver encoded strings for both installer types.

Also, I'm assuming `0` just means a default value, or "we don't know"?

**Comment by alexgibson** [comment]
> Perhaps the request could deliver encoded strings for both installer types ahead of time.

@pmac does this sound like a reasonable approach? I think I can take a pop at this one, unless there's a better way to go that you can suggest.

**Comment by pmac** [comment]
I'm wondering why this is necessary at all. Stub installer and full installer are different requests to bouncer already. It's a different product name.

**Comment by pmac** [comment]
Just adding attribution attributes to the request for either stub or full should be all that's needed.

**Comment by hoosteeno** [comment]
I'll dig into that with PMs. Thanks.

**Comment by tublitzed** [comment]
the [spreadsheet](https://docs.google.com/spreadsheets/d/1z9IOWZrjI6fZ_vfMqErh-dzJBAz6YNz3D-oDI4vfsPE/edit#gid=0) actually lists incorrect values...for whomever picks this up. We should match what's the product now, see details [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1598111#c1).

**Comment by hoosteeno** [comment]
Let's hold on this. I agree that the download button should not be authoritative about the installer type; the installer should.

**Comment by tublitzed** [comment]
So, IIUC the full installer is already sending installer_type over [here](https://searchfox.org/mozilla-central/source/browser/installer/windows/nsis/installer.nsi#1052). So...

I don't think there's anything else to do here (ie, if it's full we have a value, if it's stub nothing is sent). 

cc @mhowell-mozilla

**Comment by hoosteeno** [comment]
Excellent! WONTFIX.
