### ISSUE TITLE
WNP 78 Design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8970]
Create design assets for the build and launch the Whatsnew page for the Firefox 78 release.

Content: Mobile

#### Approvals
- [x] Accountable - LNiolet
- [x] Mobile PMM - LAustin
- [ ] Brand (Design) - Clio
- [ ] Team Lead - Hoosteeno

**Comment by hoosteeno** [comment]
@cgonz0 can you attach mockups and mark as "done"?

**Comment by cgonz0** [comment]
![wnp78 - AFFINITY.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/2605e7f3-15a5-470e-84c7-c73cbf8248db)![wnp78 - FALLBACK.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/87679e56-dd60-4ca0-a069-6f498d3a15f0)![wnp78- PRIVACY.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/a3d0bbcb-e3fe-48a8-a030-38427a546a66)![wnp78- SPEED.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/a980cdfd-b0f2-47e9-8c6d-51d84c6f2e70)![wnp78- TASK COMPLETION.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/f0cafd23-1df9-4dd0-8939-31b9f9b571ac)

**Comment by ejregithub** [comment]
@cgonz0 - I'm going to make the not so wild assumption that these are 'Clio approved'. Nonetheless, could you please note that in reply here and apply the 'tick' to the Approvals line item for "Brand (Design) - Clio: in the original description at the top of this issue?  Many, many thanks.
