### ISSUE TITLE
WNP 78 Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8971]
Code and launch the Whatsnew page for the Firefox 78 release.

Content: Mobile

[Copy - DE, EN and FR](https://docs.google.com/document/d/1XGljKf8hl88z56zHaqcerEy3gQlNH1C-PB-uhKqj08o/edit) for use in the test

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1644222)

---

####  Success Criteria 
- [ ] Is fully approved and live in production on or before June 26th

#### Approvals
- [x] Accountable - LNiolet
- [x] Mobile PMM - LAustin
- [x] Brand (Design) - Clio
- [x] Brand (Copy) - Natalie
- [x] Team Lead - Hoosteeno

**Comment by Errolyn** [comment]
@ejregithub Can you add the due date for this so I have it here?

**Comment by ejregithub** [comment]
@Errolyn - done - the very last day (we should strive to have the content, all templates with copy test variations, live in prod sooner) for go live is June 26th.
