### ISSUE TITLE
WNP 78 - QA test guide and JIRA issue

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8973]
## Description

Quality Assurance testing of the Whatsnew page for the Firefox 78 release.

---

####  Success Criteria 
- [x] [QA test guide](https://docs.google.com/document/d/1wOhhesza_9emtH9ZOE_T9ZE1orlMyv7Q3W4sYHNhf-g/edit) is complete by June 26th
- [x] QA [test request is filed in JIRA](https://jira.mozilla.com/browse/PI-679) by June 15th  (on June 22nd)

#### Approvals
- [ ] Errolyn (Dev for the page)

**Comment by hoosteeno** [comment]
@ejregithub any update on this?

**Comment by ejregithub** [comment]
@hoosteeno - yes, I'm submitting the jira issue today (I chatted w. Tania about that being on my todos for today, early). I was hoping for links to demo to include the test doc, but I can easily insert copy and take screen shots w. the inspector tool.

**Comment by ejregithub** [comment]
@hoosteeno - QA test request if filed in Jira - https://jira.mozilla.com/browse/PI-679

The test doc is [here](https://docs.google.com/document/d/1wOhhesza_9emtH9ZOE_T9ZE1orlMyv7Q3W4sYHNhf-g/edit), pending only URL updates for each test variation and screenshots
