### ISSUE TITLE
Remove COVID Fund banner

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8984]
## Description

In #8728 we added a COVID fund banner to certain pages of the site. This program is closing on 2020-06-08, so we can remove the banner on/around that date.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Banner is removed from all pages where it appears

**Comment by craigcook** [comment]
The banner is [controlled by a switch](https://github.com/mozmeao/www-config/blob/master/waffle_configs/bedrock-prod.env#L34) so we can turn it off without a production push. Obviously we should delete the code as well but that cleanup task can be a lower priority and not tied to a date.
