### ISSUE TITLE
404 link on /manifesto page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8991]
## Description

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1643881 for STR.

**Comment by NdagiStanley** [comment]
Hi @alexgibson can I take this up?

What would you have me do?

**Comment by alexgibson** [comment]
@NdagiStanley pull requests are welcome. I'd suggest starting by getting bedrock up and running locally: https://bedrock.readthedocs.io/en/latest/install.html
