### ISSUE TITLE
Import data from Wordpress blog

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#8994]
We import some data from some blogs now, but for this we'll need to import it all. Possibly use an existing library like https://github.com/observermedia/django-wordpress-rest

**Comment by NdagiStanley** [comment]
@pmac I would very much like to participate in this [milestone](https://github.com/mozilla/bedrock/milestone/25). I've had the opportunity of just contributing once to the project and I'm still going through the code and supporting docs.

Let me know when this starts, where discussions are going on (if not here) and where I can plug in. I double up as a technical copywriter so I could help in that too.

**Comment by NdagiStanley** [comment]
@pmac
Does this mean the [milestone](https://github.com/mozilla/bedrock/milestone/25) has been discontinued?

**Comment by pmac** [comment]
Hi! Yes. Sorry I failed to notice your message from before. We're not sure at the moment what this integration will look like after some changes in other plans. We'll probably add some new issues later once we formulate a new plan.
