### ISSUE TITLE
WNP 78 Experiment Plan

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8999]
WNP78 will launch with 4 copy variations ([copy doc](https://docs.google.com/document/d/12EXuSwoNijGVEFoRWmEv7R1vhWWBZu7jsW4UcWp752U/edit)). We want to test these against each other to see which variation achieves the best session-send rate on the Send-To-Device widget. We need an experiment plan for that.

## Success Criteria 

- [x] Experiment plan is written and attached to this document
- [x] Plan calls out any specific instrumentation requirements needed for measurement

## Reviews

- [x] Engineer has reviewed plan

**Comment by hoosteeno** [comment]
@sghoseWI Can you help us build an experiment plan for WNP78?

**Comment by sghoseWI** [comment]
@hoosteeno Sure thing!

**Comment by sghoseWI** [comment]
Draft of test plan: https://docs.google.com/document/d/1Il1sVwNfhuXF7ZK3uUdaq0swXVj3JovOUIuGQ5jnlgs/edit#

**Comment by LaurenNiolet** [comment]
^approved
