### ISSUE TITLE
Animate global nav CTA

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9009]
## Description

The CRO team ran an experiment to determine whether a small, short animation in the global navigation's CTA would increase overall engagement with the CTA. [One variant did so](https://docs.google.com/document/d/1twN7fh3E3GPmuN9EJFb7PwomeK2NPbsNExrLApG2geE/edit#heading=h.jcj1m5tuuur8), which we called the "Initial Bounce". The variant also did not harm install rates, which UX review identified as a risk. 

Let's add an initial bounce to our global nav CTA and, if appropriate, include in Protocol. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Initial bounce animation designs attached to this 
- [x] Initial bounce added to global navigation CTA
- [ ] Any changes required in Protocol PR'd to Protocol repository

**Comment by ejregithub** [comment]
@cgonz0 - when you're back can you please provide an update here?

**Comment by cgonz0** [comment]
@ejregithub WIP at the moment - will get feedback today/tomorrow and finalize by EOW

**Comment by cgonz0** [comment]
some specs for the bounce animation:

`@keyframes bounce {
  10%, 25%, 40%, 49% {
    animation-timing-function: cubic-bezier(.39,.58,.57,1);
    transform: translate3d(0, 0, 0);
  }
  20%, 22% {
       animation-timing-function: ease-in-out;
    transform: translate3d(0, -8px, 0);
  }
  35% {
    animation-timing-function: ease-in-out;
    transform: translate3d(0, -5px, 0);
  }
  45% {
     animation-timing-function: ease-in-out;
     transform: translate3d(0, -1.5px, 0);  
  } 
}`

`.btn {
  animation: bounce 2s;
  transform-origin: center bottom;
}`

visual example:
https://codepen.io/cgonza/full/MWKjpzY

**Comment by alexgibson** [comment]
Thanks @cgonz0 - I'll see if I can get this up on demo and then we can discuss the best timing for when the bounce should occur.

**Comment by alexgibson** [comment]
@cgonz0 this is now up on demo3 for review:

https://www-demo3.allizom.org/en-US/

Note: I added an initial 1 second delay after page load before the bounce animation begins, but am happy to tweak this however you see fit. Thanks

**Comment by cgonz0** [comment]
> @cgonz0 this is now up on demo3 for review:
> 
> https://www-demo3.allizom.org/en-US/
> 
> Note: I added an initial 1 second delay after page load before the bounce animation begins, but am happy to tweak this however you see fit. Thanks

@alexgibson awesome, thanks! looking good -  i think we could reduce the 1s delay a bit... could we start by trying .5s and see how that feels? thank you

**Comment by alexgibson** [comment]
>  i think we could reduce the 1s delay a bit... could we start by trying .5s and see how that feels? thank you

Thanks, changed to .5s delay

**Comment by cgonz0** [comment]
@alexgibson  this feels a lot better to me, although the delay could possibly be even shorter. would you mind changing it to .25s? then i'll feel comfortable deciding the best timing b/w the two. thanks!

**Comment by alexgibson** [comment]
> would you mind changing it to .25s?

Done, thanks

**Comment by cgonz0** [comment]
> > would you mind changing it to .25s?
> 
> Done, thanks

thanks for trying this speed- i think we should revert back to the .5s second timing. looks good to me overall. thanks
