### ISSUE TITLE
Make adding new brand names to brands.ftl easier

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9010]
## Description

Currently adding a new brand name to brands.ftl involves a set of very laborious steps:

1. Add a new brand name to en/brands.ftl in bedrock.
2. Take that brand name and add it to every locale in the l10n-team repo.
3. Once that is merged in the l10n-team repo, pull it back into bedrock via l10n_update.

This is required because brand name placables do not fall back to English like a regular string if they do not exist for a locale.

The above takes a front end developer several hours of laborious copy / paste for every new brand name added.

We should make this easier to automate, or alternatively change the default behaviour to fall back to English.

**Comment by pmac** [comment]
With #9048 merged I'm going to mark this as closed. I don't think we need this automation if english fallbacks work on the site. Please reopen if you disagree.
