### ISSUE TITLE
Update product screens for lockwise page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9011]
## Description

Update product screens for lockwise page  - https://www.mozilla.org/firefox/lockwise/

The lockwise website is showing product screens with fakertester written all over them. 

New art is here: https://drive.google.com/open?id=1pR-uXCaHSHsY2QuR1QFanisaFjfc2P_f

---

#### Success Criteria
- [ ] The page is live with the new product images in place

#### Approvers
- [ ] Tyler Ahn
- [ ] Brand - Clio

**Comment by alexgibson** [comment]
I can take this as part of #9016

**Comment by alexgibson** [comment]
@ejregithub it looks like we have localized image for this page, we we'll need updated images for the following locales:

- https://github.com/mozilla/bedrock/blob/master/media/img/firefox/lockwise/de.png
- https://github.com/mozilla/bedrock/blob/master/media/img/firefox/lockwise/en.png
- https://github.com/mozilla/bedrock/blob/master/media/img/firefox/lockwise/es.png
- https://github.com/mozilla/bedrock/blob/master/media/img/firefox/lockwise/fr.png
- https://github.com/mozilla/bedrock/blob/master/media/img/firefox/lockwise/it.png

**Comment by alexgibson** [comment]
Marking this as blocked and uncoupling from the work in #9016

**Comment by ejregithub** [comment]
Eric to ping Tyler for localized product images.

**Comment by skrelnick23** [comment]
![Devices](https://user-images.githubusercontent.com/19312393/87577397-b18e5080-c687-11ea-8185-8bfd0e93b2e4.png)
![Android](https://user-images.githubusercontent.com/19312393/87577422-bc48e580-c687-11ea-9ffd-605c40b47dfa.png)
![iOS](https://user-images.githubusercontent.com/19312393/87577461-c834a780-c687-11ea-9323-982d994ed99b.png)

**Comment by ejregithub** [comment]
@cgonz0 - we have existing localized images, as Alex points to in [the comment ](https://github.com/mozilla/bedrock/issues/9011#issuecomment-643255805) above and Tyler has provide png files in the comment right above.

What we need to do here is update the localized screenshots with list of accounts names in [this screenshot](https://user-images.githubusercontent.com/19312393/87577422-bc48e580-c687-11ea-9ffd-605c40b47dfa.png).  The question here is if you can do so with the assets at hand - or do you need the original vector files to produce high (enough) quality images?  (FYI - Tyler is tracking those down w. Ryan)

**Comment by cgonz0** [comment]
@ejregithub the localized images provided above seem to already be minimized/compressed. i wouldn't use those as a source to update the text. i could use the higher quality images that Tyler provided, but that would mean the "start" screen would also need to be localized -- which i wouldn't recommend doing, on account of it adding a lot more complexity. having the original files would be the best option here.

**Comment by ejregithub** [comment]
Understood, thanks @cgonz0.  @skrelnick23 - please provide those/links to the original files when you're able to retrieve them and let me know if you want help in doing so.

**Comment by ejregithub** [comment]
@cgonz0 - sketch file is [here](https://drive.google.com/file/d/1haw53kDcB0mu7cn-jAf9ZHsRt3k9lfVy/view?usp=sharing)

**Comment by ejregithub** [comment]
Blocked again on assets to update localized images

**Comment by skrelnick23** [comment]
Could @Ryan Gaddis <rgaddis@mozilla.com> or @Matthew Noorenberghe
<MattN@mozilla.com> help out here? Please and thank you.

**Comment by alexgibson** [comment]
Closing due to recent Lockwise changes
