### ISSUE TITLE
Copy - Moments_4_Mobile-CTA-EXP01

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9012]
Goal: Learn which point in a desktop user's lifecycle is most effective to cross-sell mobile to inform where we should automate an evergreen Moments Page.

Approach: Distribute Welcome page 4 to users across different profile ages, i.e. multiple cohorts at once to see, for instance, if users in week 2 (still new to the browser and likely downloaded for a reason) are more or less interested in our mobile app than users in week 8 (who've maybe had more time to "fall in love" with the desktop experience and want it on all devices)... or perhaps the ideal cross-sell moment is somewhere in-between.

Details: Welcome page 4 will need two minor copy updates; the headline & last bullet. We’ve come to realize, especially in times like these, that people don’t necessarily “take mobile on the go”, they’re just as likely to use it at home from their couch.

#### Success Criteria
- [ ] [New copy](https://docs.google.com/document/d/1sNcLHvK2d0E9OOjQYsJTsNWp3NBVw3csgEs1rjFKNGs/edit#) is written
- [ ] EN copy is passed to EU team for [l10n of DE and FR](https://docs.google.com/document/d/1YWuF8smAbmaCh1dsjq2_RjAKdBoo1aYwwj1a49dM2Jg/edit)

#### Approvals
- [ ] The Accountable - MWarther
- [ ] Brand - copy Natalie
- [x] Team Lead - Hoosteeno
- [ ] Lisa W as the original requestor and drafter of the experiment

**Comment by rantley** [comment]
https://docs.google.com/document/d/1sNcLHvK2d0E9OOjQYsJTsNWp3NBVw3csgEs1rjFKNGs/edit?usp=sharing

copy is done and approved

**Comment by ejregithub** [comment]
Noting that Hoosteeno, Lisa W, MWarther (Accountable) and Legal (Emily) provided signoff today, closing this issue

**Comment by ejregithub** [comment]
Reopening with copy updates requested by  Lisa and Michele

**Comment by hoosteeno** [comment]
The canonical copy doc is here: https://docs.google.com/document/d/1GrdzXS0n6h9-YYxwQiRskCuFasplIx5EDvHouo5fF2w/edit

**Comment by ldwright** [comment]
Copy updates are ready per the canonical doc linked above. Natalie has green lit.

Changes include: a new hero headline, hero sub-header, CTA button text & last bullet point headline and sub-header (replacing "Take it all with you" section). Please note: the icon for the last bullet point should also be updated given the new copy.

**Comment by hoosteeno** [comment]
#9013 #9014 #9299
