### ISSUE TITLE
Code: Moments 4 Refresh

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9013]
Update Welcome 4 copy and images to market new mobile browsers. Code should be ready for pontoon no later than EOD Friday 8/28. 

#### Success Criteria
- [ ] [New copy](https://docs.google.com/document/d/1sNcLHvK2d0E9OOjQYsJTsNWp3NBVw3csgEs1rjFKNGs/edit#) is coded and live in EN, DE and FR
- [ ] Instrumentation is built to track mobile installs originating from this tactic
- [ ] new images are in place 

#### Approvals
- [ ] hoosteeno
- [ ] lwright

**Comment by ejregithub** [comment]
Blocked on the fact that we don't yet see that the page will be shown to users via FMS

**Comment by ejregithub** [comment]
On 7-22 Lisa W indicate more updates to the page will be requested as part of a plan to launch a new 'moment' with the revised page.

**Comment by amychurchwell** [comment]
This is blocked until design is final

**Comment by amychurchwell** [comment]
Time frame from lwright in slack:

> Ideal time is still to launch the week of 9/8 (knowing it may need to be later in the week) if it’s possible since we try to run Moments for 7 days (again, if possible), and would want to try to allow some cushion between it and the What’s New Page that launches on 9/22 for the Fx81 release.

> If it ends up being early the week of 9/14 based on realistic timelines though we’ll do what we need to do. It’s possible we’ll need to wait until 9/14 (and maybe run it for a shorter period) anyway to ensure the iOS 14 release has rolled out.
