### ISSUE TITLE
Epic: Moments 4 revision for Daylight

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9014]
## Description

Update Welcome 4 copy and images to market new mobile browsers. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Copy, images approved and attached to cards in this epic
- [ ] Code merged
- [ ] Instrumentation validated

**Comment by hoosteeno** [comment]
Epic issues:

#9013 #9012 #9299

**Comment by alexgibson** [comment]
Seems like all the dependencies here were done.
