### ISSUE TITLE
Migrate /firefox/lockwise to Fluent

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9016]
## Description

The lockwise landing page /firefox/lockwise/ is currently only available in 'en-US', 'de', 'en-CA', 'en-GB', 'es-ES', 'fr' and 'it' (https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L283). We should open it to be translated in all our locales to let users worldwide get the product in their language, increase sessions and SEO. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
The .lang project is now inactive, so this really means migrate the /lockwise page to Fluent (where it will be available to all of Pontoon locales again)

**Comment by rraue** [comment]
I thought so, do we have priorities on which pages need to be migrated first?

**Comment by alexgibson** [comment]
Yes we have a spreadsheet here: https://docs.google.com/spreadsheets/d/1RMYNxsFvZAx2DGwHINiEbf5oUYzOvEOp2RPrIH1LtF0/edit?usp=sharing

The lockwise page is currently down as a P2

**Comment by rraue** [comment]
Should we add a comment in the spreadsheet that it should be translatable to all locales and close this issue here then?

**Comment by alexgibson** [comment]
> Should we add a comment in the spreadsheet that it should be translatable to all locales and close this issue here then?

No I think keeping this issue open to track that it gets done is fine, thanks.
