### ISSUE TITLE
Market desktop browser on /new.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9019]
With the changes to /firefox last year /new now needs to focus on marketing the desktop browser. By refocusing the page to market browser features we believe we can improve conversion and SEO ranking for this page.

Special attention should be paid to:
- perceived performance of page load
- this page had enhanced styling support for older browsers
- still providing download options for mobile users
- a sustainable l10n friendly way to update frequently changing content (release notes are en-only and browser comparison chart needs regular updates)

Design:
![new-1312-v3](https://user-images.githubusercontent.com/854701/84329539-c6803d00-ab39-11ea-9965-d12a053e319a.jpg)

Copy:
https://docs.google.com/document/d/1sLVwUJniDuxJYntJ7Wd49_vA3tPOf4VPXS7FqudAwpc/edit

Images:
https://drive.google.com/drive/folders/1kvURxRbwtcD0Wzee06GgdL8LXa88lT2Z

**Comment by shashankcoc** [comment]
Hey @stephaniehobson ,
According to you the download button should be removed from small screen size or mobile view.
So can I solve this issue.

**Comment by stephaniehobson** [comment]
@shashankcoc Sorry, I should have assigned myself. I'm working on it :)

**Comment by shashankcoc** [comment]
@stephaniehobson that's pretty cool, happy coding ☺
