### ISSUE TITLE
Fluent L10n automation has stopped working?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9023]
## Description

The last automated PR from changes in bedrock was [21 days ago](https://github.com/mozilla-l10n/www-l10n/pull/34).

Since then, at least 2 more string changes have been merged in bedrock, neither of which seem to have made it to the L10n repo:

- https://github.com/mozilla/bedrock/pull/8953
- https://github.com/mozilla/bedrock/pull/8952

**Comment by alexgibson** [comment]
Any ideas here, @pmac - might this be since we changed the webhook?

**Comment by pmac** [comment]
The webhook was for the other direction. For changes coming from L10n repo to ours. I'm taking a look now.

**Comment by pmac** [comment]
`CommandError: Git push authentication not configured` from https://gitlab.com/mozmeao/bedrock/-/jobs/586196123

**Comment by pmac** [comment]
@duallain @glogiotatidis the new runners don't seem to have git auth setup properly for the integration account.

**Comment by pmac** [comment]
So it's not the runners. It expects a `FLUENT_REPO_AUTH` environment variable in CI and it's no longer there for some reason.

**Comment by pmac** [comment]
I added the variable back in the GitLab UI and reran the most recent failure and it worked:

https://github.com/mozilla-l10n/www-l10n/pull/43

Still trying to figure out when and why the variable went away.

**Comment by alexgibson** [comment]
Seems to be working again now https://github.com/mozilla-l10n/www-l10n/pull/44

I'll leave it to you as to when you wan to close this issue. Thanks all!
