### ISSUE TITLE
Conduct usefathom evaluation

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9028]
## Description

https://usefathom.com/ has been approved for use at Mozilla. We should build it into our analytics instrumentation on a few of our more important pages of www.mozilla.org to learn if we can replace GA with it.

---

#### Success Criteria
- [ ] Evaluation plan is written
- [ ] Pages are identified
- [ ] Server side config is set up
- [ ] Client side config is set up

#### Approvals
- [ ] Analytics
- [ ] Dev
- [ ] Team Lead
- [ ] MEAO

**Comment by maureenlholland** [comment]
closed with https://app.asana.com/0/1203970207351421/1203970207635769/f
