### ISSUE TITLE
[July 17] WNP 79 - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9061]
## Description

Code the page supporting the marketing theme selected for the WNP shown to users upgrading to Firefox 79 (release on 7/28)

[Principal project doc](https://docs.google.com/document/d/1DW2-pohjlRxmtSf7l4vhsVUCkhLQuXh6VdkOyopWPDk/edit)

---

#### Success Criteria
- [ ] Page is live in prod on or before July 17

#### Approvals
- [ ] The Accountable - MWarther
- [ ] Brand - Clio
- [ ] Brand - Natalie
- [ ] Team Lead - Hoosteeno
- [ ] Others?

**Comment by craigcook** [comment]
Merged in https://github.com/mozilla/bedrock/commit/f771dc08768835577e7873a89e193e4158f2bcfb
