### ISSUE TITLE
Link missing from accounts signin form

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9073]
## Description

The sign in and learn more links in the accounts signup form on the browsers page should be links.

### Steps to reproduce

https://www.mozilla.org/en-US/firefox/browsers/

<img width="628" alt="Screen Shot 2020-06-26 at 10 47 44" src="https://user-images.githubusercontent.com/854701/85886370-cff4e080-b79a-11ea-949c-0c97451697cf.png">

### Expected result

Like the products page, these should be links.

### Actual result

Not links.

### Environment

macOS

**Comment by stephaniehobson** [comment]
I think this is an artifact of #8988.

**Comment by alexgibson** [comment]
Looks like the string is missing the params, should be an easy fix https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/browsers/index.html#L123
