### ISSUE TITLE
Preconnect to accounts.firefox.com on pages that require metrics

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9081]
## Description

Our [lighthouse reports](https://www.webpagetest.org/lighthouse.php?test=200628_GM_de105c10183fc08fcfc6ab25d453eb07) suggest that we could save an estimated 550ms on slower connections by preconnecting to account.firefox.com on pages that require metrics flow params, such as /firefox/accounts/.

This can be done using a `<link rel=preconnect>` tag in the `<head>` of the page.

https://web.dev/uses-rel-preconnect/?utm_source=lighthouse&utm_medium=wpt

**Comment by UnejucatedGuy** [comment]
If this issue is still relevant, could you provide some guidance on how I can get started?
Alternatively, if this issue has been resolved or is no longer being pursued, could you suggest another beginner-friendly issue that I could tackle? I'm eager to learn and contribute to the project. Any suggestions or guidance would be greatly appreciated.

**Comment by stevejalim** [comment]
Hi @UnejucatedGuy - thanks for the offer. 

I don't know what your level of experience is with HTML, but if you're asking about how to get the project up an running, please see the docs at https://bedrock.readthedocs.io/en/latest/ and let us know how that goes

**Comment by akashkgit** [comment]
Hi!
I am really excited about this good first issue and would love to work on it.  is it still open ?

**Comment by alexgibson** [comment]
This is an old issue and a lot has changed with regard to the number of pages where this might be applicable today. I'm going to close this one for now as not planned, and if we do want to try and optimize these calls in the future we should probably do a bit more research about what makes sense.
