### ISSUE TITLE
last-modified in sitemaps

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9086]
## Description

I am coming back to an old topic we had: last-modified in sitemaps. I think with the /compare/ pages I have a good case to rethink if we might somehow get them in the sitemaps. The pages got taken down two month ago and we redirected them back to /firefox/. Last Friday they were launched again, with a new page in the set. The new page /brave/ is indexed right away and is already sending sessions via organic search but I looked up all other pages today in Search Console and they are still not recrawled and back in the index. 

I submitted all these pages now for reindexing and hope Google will pick these up fast but a redirect for two month is pretty “permanent” for a crawler, so it might take a while. Thats exactly the use case for last-modified in sitemaps. Things change and can prevent misunderstandings between site and crawler by having a source of “truth” witch is fast and easy readable.

While its not a disaster that the compare pages need some days longer to get back indexed, I can imagine a whole lot of scenarios where a day or two is crucial for our business (anything happening with /new or /firefox) where we don’t want to wait a couple of days to get the newest version indexed. Google has with the Search Console a tool to point their crawler to such changes (if I know about them and arent on pto) but a lot of search engines do not have such tools.

So I think we should have another fresh look on the sitemaps and maybe there is an easy way of checking for changes on the site once a day and updating the last-modified in the sitemap? It could prevent quite some chaos in the future.

Last modified doesn't have to be super precise. Maybe even a system for the website team flagging changing pages would be good enough, as not every bit in css or js needs to be recrawled but changes on content, links, nav/footer, images or if the code changes al lot (migrating a page to protocol for example).

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "the new design is done and approved, live on the page"

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by rraue** [comment]
cc @pmac

**Comment by pmac** [comment]
This is the code from the last time I attempted this: https://github.com/pmac/www-sitemap-generator

I think it could work. We could run it daily via CI, upload the resulting sitemaps to s3 or commit them to git, then have bedrock pull in the changes once a day as well.

**Comment by pmac** [comment]
I just updated some things with my scripts and ran everything and committed the results. It's looking good to me. Take a look at the [sitemaps in the repo](https://github.com/mozmeao/www-sitemap-generator/tree/master/sitemaps) @rraue and let me know what you think.

**Comment by rraue** [comment]
That looks great. Will the repo update if pages get updated? Right now all pages have the same timestamp, right?

**Comment by pmac** [comment]
The idea is that this will be run on a schedule (every day, or every few hours or something like that) and that the files will be synced out to bedrock servers so they can be updated. I think most URLs have the same timestamp at the moment because most have changed since last time I ran this. When it's run on a schedule it will do a better job of tracking actual modified dates.

**Comment by rraue** [comment]
I think every day is enough, we are now five days in and only three of the 60 compare pages are back in the index, so having something pointing crawlers to the right pages will be way better than nothing. 

Should we ship the sitemap and see in production how the schedule works or test it further in the repo?

**Comment by pmac** [comment]
It's still a bit fragile actually. I'm working on trying to make it run more reliably and make sure it's catching actual changes. There is either a lot more change than I expected or it's getting some false positives.
