### ISSUE TITLE
Remove `id` from the monthly WNP# template

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9100]
## Description

WNP # page (not the default) that ties to a particular Fx Desktop release is not available in `id` like the other locales on production. The `id` template is hard coded with content from the Emerging Market's marketing team. Let's remove it from the page configuration so it doesn't show up in Pontoon for the community..

### Expected result

When WNP # page is pushed to Pontoon, `id` is excluded.

**Comment by alexgibson** [comment]
Reading: https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html#paths

What's the recommended way to exclude a given locale from a configuration path? Specifying every other locale would work, but it seems like a long winded way to do things.

Any pointers here, @peiying2 or @Pike?

**Comment by Pike** [comment]
Add id to the special-templates config, https://github.com/mozilla/bedrock/blob/master/l10n/configs/special-templates.toml.

Happy to review a patch. Does it propagate from there, or do we need to patch `www-l10n` independently?

**Comment by alexgibson** [comment]
Thanks! I think once we merge to berdock the changes should be picked on in www-l10n
