### ISSUE TITLE
Move download specific messaging to the /thanks/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9102]
## Description

As a dependency to making a simplified version of the download button in https://github.com/mozilla/bedrock/issues/8860, we need to first find an alternate solution for the various pieces of [conditional messaging](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/includes/download-button.html#L46) contained in the full download button helper.

After some discussion we have agreed that the best place for this messaging to live is in the /download/thanks/ page.

This issue to to track migration of that messaging.

---

#### Success Criteria
- [x] Conditional messaging contained in the download button is shown on /thanks, instead of on the page where the download click originates from.

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by alexgibson** [comment]
I'm going to make a start on the logic for this whilst final designs are being ironed out

**Comment by alexgibson** [comment]
@justinkropp WIP screnshots below. Happy to chat in person if it helps about anytihng below, please let me know.

Unknown system
-----------------

![unknown-system.png](https://images.zenhubusercontent.com/5c927d6baa8dca0a81399557/ada372ce-7316-4b32-bc84-f857d08808da)

Windows XP / Vista
--------------------

![xp-vista.png](https://images.zenhubusercontent.com/5c927d6baa8dca0a81399557/bc870c5f-b050-4713-8a1f-be0d77356c31)

Linux ARM
-----------

![linux-arm.png](https://images.zenhubusercontent.com/5c927d6baa8dca0a81399557/5be5abba-1005-47ad-b10a-f34a05ffe372)

**Comment by alexgibson** [comment]
Codewise I think this is nearly ready for review / testing. 

The one thing we're missing is some final copy for the "Attention! Something Happened" message, which we felt could do with some better wordsmithing.

**Comment by ejregithub** [comment]
@justinkropp - can you please provide status on the remaining copy here?

**Comment by justinkropp** [comment]
@ejregithub Yes, I need to sync up with @rantley to revise this copy.

**Comment by alexgibson** [comment]
@justinkropp @rantley I know many things are hectic at the minute, so iI'm going to propose moving forward with a simple solution so this doesn't eat up your time:

Instead of using "Attention! Something Happened" (where "Something" is a bit too ambiguous), I'm going to propose we just use "Attention!" on its own. Combined with the message underneath the title, that should be enough to give context.

**Comment by justinkropp** [comment]
@alexgibson Thanks for the proposal. Let's move forward with that for now. We can revise that copy once we get a bit more breathing room. 👍

**Comment by rantley** [comment]
@alexgibson @justinkropp I put a few options here. Let me know if this works. Thanks.  
https://docs.google.com/document/d/10BNLW4NHw52jI4mprr4g69KxFPNQpPKA7aiWwDjkO5I/edit?usp=sharing

**Comment by alexgibson** [comment]
Thanks for these options @rantley 💯
