### ISSUE TITLE
RTL styling issues on /firefox/browsers/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9110]
## Description

The Firefox Accounts form on the /firefox/browsers/ page is inaccessible on RTL locales due to styling issues.

### Steps to reproduce

https://www-dev.allizom.org/ar/firefox/browsers/

### Expected result

Form should be accessible.

### Actual result

![image](https://user-images.githubusercontent.com/400117/86476111-cab90800-bd3d-11ea-9336-f503a5d74bea.png)

### Environment

Firefox.

**Comment by Abhirup-99** [comment]
is this issue still up? Would like to contribute.

**Comment by alexgibson** [comment]
@Abhirup-99 please see our contributing guide to get started, thanks https://github.com/mozilla/bedrock#contributing

**Comment by berliners1** [comment]
Hello, I just made a pull request with a potential fix for this issue.
