### ISSUE TITLE
Enable download buttons for Windows ARM64 builds.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9117]
## Description

Firefox builds for ARM64 / AArch64 were added to /firefox/all/ in https://github.com/mozilla/bedrock/issues/8929.

When someone tries to download Firefox directly via /new however, they still get the following message:

![image](https://user-images.githubusercontent.com/400117/86610185-e40fbd80-bfa4-11ea-9da1-742c068178ce.png)

This issue is to investigate enabling the download button for those users.

One thing I'm not sure about is whether we need to worry about 32bit (seeing as the ARM builds are 64bit only). I don't think our UA detection is fool proof here. That said, anything may be better than the current experience.

---

#### Success Criteria
- [ ] ARM64 builds are served in production via the regular download button.

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by saschanaz** [comment]
>whether we need to worry about 32bit

There is no 32bit ARM Windows, so no.

**Comment by alexgibson** [comment]
I've deployed this change to demo for testing:

- https://www-demo2.allizom.org/en-US/firefox/new/
- https://www-demo2.allizom.org/en-US/firefox/channel/desktop/

@saschanaz do you by any chance have a Windows ARM64 device, and would be willing to help us verify that things are working as expected?

**Comment by saschanaz** [comment]
I don't have a right device now, sorry 😔

**Comment by alexgibson** [comment]
Added a blocker to this issue until we can get some help with QA.

**Comment by ejregithub** [comment]
@alexgibson - noting that I pinged the QA coordination Slack channel querying about the possibility for assistance in testing. I'll follow up once I get direction, probably formalizing the request in a Jira request.

**Comment by ejregithub** [comment]
@alexgibson   - VBalducci confirmed QA has Lenovo Yoga w. Windows on ARM 64.  I filed this issue w. QA for testing -  https://jira.mozilla.com/browse/PI-679

**Comment by ejregithub** [comment]
@alexgibson - Testing appears to finalize this issue, please confirm and close if you concur:

QA tested and [commented ](https://jira.mozilla.com/browse/PI-679?focusedCommentId=98747&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-98747) with the following:

_As per https://github.com/mozilla/bedrock/issues/9117 I tested the download links :

    https://www-demo2.allizom.org/en-US/firefox/new/
    https://www-demo2.allizom.org/en-US/firefox/channel/desktop/

They are both showing the download button correctly on ARM64, I'm able to successfully install through the firefox installer exe , and launch without issues as well._
