### ISSUE TITLE
Experiment plan: Test upstream CTR

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9118]
## Description

Build an experiment plan for a download URL test described in https://github.com/mozilla/bedrock/issues/8843. 

---

#### Success Criteria
- [ ] Experiment plan includes 
* variations
* traffic segmentation plan
* measurement plan
* any unique instrumentation requirements
- [ ] Experiment plan reviewed by list below
- [ ] Experiment plan attached to this issue

#### Approvals
- [ ] SEO
- [ ] Team Lead
- [ ] Dev

**Comment by rraue** [comment]
WIP doc test plan: https://docs.google.com/document/d/1iJamO5X68nVvDGiXlHk7kGK-rjmGNTm1EMnYM1eJFOM/edit

**Comment by maureenlholland** [comment]
closing in accordance with https://github.com/mozilla/bedrock/issues/8843#issuecomment-815929706
can re-open if needed
