### ISSUE TITLE
[7/17] WNPs - Indonesia, India, African countries

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9119]
## Description

New content is available to update the existing WNPs, the hard coded templates, currently shown to Indonesia and India (in EN).

Additionally, the EN page shown to India is also to be shown to the following countries in Africa: Nigeria, South Africa, Kenya, Ghana, Uganda, Tanzania, Zimbabwe, Zambia. 

[Indonesia page assets](https://drive.google.com/drive/folders/1K9UcgFJrIJcj5PWv1ytbaWb3gJrnhMT3?usp=sharing)

[EN page assets](https://drive.google.com/drive/folders/1L9yaqZhdgiEk-R9_stQBwb2v6YaZ28uI?usp=sharing) shown to India, Nigeria, South Africa, Kenya, Ghana, Uganda, Tanzania, Zimbabwe and Zambia

---

#### Success Criteria
- [x] New content is live in the hard coded WNP template, shown to Indonesia via geo-location (whatever method we're using at the moment)
- [x] New content is live in the hard coded WNP template, shown to India, Nigeria, South Africa, Kenya, Ghana, Uganda, Tanzania, Zimbabwe and Zambia via geo-location (whatever method we're using at the moment)

#### Approvals
- [ ] The Accountable - Stella
- [ ] Brand design - Tim (has already approved designs)
- [ ] Brand copy - Time (has already approved copy)
- [ ] Team Lead

**Comment by ejregithub** [comment]
@cgonz0 - could you please review the assets, link to above, and indicate if any improvements/adjustments should be made.

**Comment by cgonz0** [comment]
@ejregithub design looks good- although the elements look a bit large to me. if we're going off the existing india/indonesia wnpages we have now, which work - i'd just suggest matching text sizes & qr code size. also wondering if we're going to hide the image for smaller sized screens as we're doing for other pages now

**Comment by alexgibson** [comment]
@ejregithub can you please ask whomever authored the design files to provide an export of the background as separate layers? Currently it's a single static image, which doesn't play well in the context of a responsive web page:

![background](https://user-images.githubusercontent.com/400117/86792218-2ba84f00-c062-11ea-8b86-40e8555e93ee.jpg)

Ideally, it would be great to get the circle shapes as separate layers. The gradient background can be done in CSS. 

Thanks

**Comment by alexgibson** [comment]
> design looks good- although the elements look a bit large to me. if we're going off the existing india/indonesia wnpages we have now, which work - i'd just suggest matching text sizes & qr code size. also wondering if we're going to hide the image for smaller sized screens as we're doing for other pages now

Agreed, I don't think the mockup is to scale of our standard web page templates. I'll get something up on demo and then we can make tweaks when it's easier to see things in situ. Thanks

**Comment by ejregithub** [comment]
@alexgibson @cgonz0 - request for design files has sent.

**Comment by alexgibson** [comment]
@ejregithub @cgonz0 

This is now up on demo for initial design / stakeholder review:

- https://www-demo3.allizom.org/id/firefox/78.0/whatsnew/all/
- https://www-demo3.allizom.org/en-US/firefox/78.0/whatsnew/india/
- https://www-demo3.allizom.org/en-US/firefox/78.0/whatsnew/africa/

Note: we're still waiting on the background texture, so this is missing currently. 

Any other tweaks please let me know - thanks.

**Comment by ejregithub** [comment]
![0001_New-Firefox-Lite-2 5-WNP_BG_India](https://user-images.githubusercontent.com/20547886/86939048-f51c1400-c0f5-11ea-8213-e0c64a2628a3.png)

**Comment by ejregithub** [comment]
The comment above includes an image, the 'circle shape' as a separate layer. Click to view it.

**Comment by cgonz0** [comment]
> @ejregithub @cgonz0
> 
> This is now up on demo for initial design / stakeholder review:
> 
>     * https://www-demo3.allizom.org/id/firefox/78.0/whatsnew/all/
> 
>     * https://www-demo3.allizom.org/en-US/firefox/78.0/whatsnew/india/
> 
>     * https://www-demo3.allizom.org/en-US/firefox/78.0/whatsnew/africa/
> 
> 
> Note: we're still waiting on the background texture, so this is missing currently.
> 
> Any other tweaks please let me know - thanks.


@alexgibson let's align the styles to the previous india whats new page, the suggestions below should help 

header title - 56px and metropolis
tagline - 32px
qr code width - 250px

**Comment by alexgibson** [comment]
@cgonz0 @ejregithub thanks this is now updated with regard to design feedback, as well as including the background images.

Given that this has a fixed date, and should aim to be in production by next Friday (17th), I think this is now in good enough shape to get final stakeholder review/approvals. Can you help get that rolling @ejregithub?

Thanks again.

**Comment by ejregithub** [comment]
Thanks @alexgibson - I solicited that review from Stella (and Cynthia) via email.

**Comment by alexgibson** [comment]
What's on demo has been approved from Stella via email.

**Comment by ejregithub** [comment]
@Errolyn - please review this one
