### ISSUE TITLE
Push FPN Terms and Privacy Notice to go live July 7th

### ISSUE THREAD

**Issue by litkaemily** [mozilla/bedrock#9120]
Hi @pmac and @alexgibson (@peiying2 and @mafeld)

I'd like to request that the following go live tomorrow, July 7th.

Privacy notice: https://github.com/litkaemily/legal-docs/blob/master/Firefox_Private_Network_Beta/en-US.md
Terms of service: https://github.com/litkaemily/legal-docs/blob/master/Firefox_Private_Network_ToS/en-US.md

Privacy notice URL: https://www.mozilla.org/en-US/privacy/firefox-private-network/
Terms of service URL: https://www.mozilla.org/en-US/about/legal/terms/firefox-private-network/

Please let me know if you need further information!

Thanks, 
Emily

**Comment by alexgibson** [comment]
Thanks @litkaemily - this is a pretty short turn around but let's see if we can get this done today 👍

**Comment by alexgibson** [comment]
Ok, pull request should be good for review. We'll try and get it pushed to production asap -thanks

**Comment by litkaemily** [comment]
Hi all - huge thanks. I'm sorry for the quick turn. Still leaning and will work to better understand processes and timing for next time!

**Comment by alexgibson** [comment]
> Still leaning and will work to better understand processes and timing for next time!

No problem and happy to help! Ideally more than 24 hours notice for changes like this would be the ideal (just in case we've also got other priorities to work out that day). Luckily this was just a small change, so we can get it done easily enough. We're just pushing this to stage now, and I'll update here when it hits production. Thanks again

**Comment by alexgibson** [comment]
Updates are now live:

https://www.mozilla.org/en-US/privacy/firefox-private-network/
https://www.mozilla.org/en-US/about/legal/terms/firefox-private-network/
