### ISSUE TITLE
Update descriptions from /features/password-manager

### ISSUE THREAD

**Issue by Errolyn** [mozilla/bedrock#9121]
## Description
https://www.mozilla.org/en-US/firefox/features/password-manager/ has some dated and appropriated language to describe our password manager. Specifically "Password ninja" which is something the tech industry appropriated from Asian culture. Using it in this fashion removes the original meaning from it, and uses the appropriated meaning "fast".

Also we are using "Password master", we should use a different descriptor here that might be more appropriate to get our point across and to be respectful of the baggage that term carries. In the description of this block we refer to black belt, which I assume the Password master line is commenting, maybe we can steer clear of martial arts references in general. To obtain a black belt or "mastery" of a martial art it takes many years of dedicated learning and practice, for a lot of people it is a major part of their lives and identities. We wouldn't say "Earn your second security degree with Firefox’s vast array of password manager add-ons." because of the schooling and learning that goes into getting a degree. The same goes for getting a black belt.

**Comment by craigcook** [comment]
This was fixed in https://github.com/mozilla/bedrock/pull/9105

"Password ninja" is now "Password magician"
"Password master" is now "Password champion" and refers to earning a "gold medal" rather than a "black belt."
