### ISSUE TITLE
Update English Homepage Layout

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9135]
MJ has requested an update to our homepage layout. It makes some card bigger, moves some of the section separators around, and changes the banner to be privacy focused.

<img width="251" alt="Screen Shot 2020-07-10 at 16 40 01" src="https://user-images.githubusercontent.com/854701/87211022-8e9d1e80-c2cc-11ea-9864-561ab5476909.png"> <img width="247" alt="Screen Shot 2020-07-10 at 16 40 27" src="https://user-images.githubusercontent.com/854701/87211026-91980f00-c2cc-11ea-9f09-d270885ad477.png">

**Comment by alexgibson** [comment]
This looks like it was done, closing
