### ISSUE TITLE
Remove legacy FxA sync flows

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9144]
## Description

As of https://github.com/mozilla/bedrock/pull/8914, FxA Sync authentication is now handled via a new UI-Tour flow, supported in Firefox 80 and above. Older clients (FF 79 and below) still fallback to the old flow for the time being.

Maintaining both of these flows is not without cost and complexity, and certainly not without risk of introducing regressions that are hard to debug. With that in mind, @vladikoff suggests that we should look to remove the old Sync flows sometime after the next 1-2 major ESR releases (current ESR is 68). Once the old flows are removed, legacy Firefox clients would simply log into the accounts.firefox.com website, in the same way non-Firefox browsers do.

---

#### Success Criteria
- [x] Sync flow for legacy FF clients is removed, enabling simple log-in to FxA website only.

**Comment by alexgibson** [comment]
More detail on what we could remove:

- Custom logic for handling China Repack (as the new UITour flow handles this automatically): https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-link.js#L103-L114
- Manually setting Sync params based on user agent: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-link.js#L23-L42
- At that point it may also be worth refactoring `mozilla-fxa-link.js` and `fxa-utm-referral.js` into a single script, as their responsibilities are beginning to overlap in some respects.

**Comment by vladikoff** [comment]
Excellent I am excited for this future clean up!  Even though we have to wait a bit , it's good to have this documented

**Comment by alexgibson** [comment]
The current ESR at https://www.mozilla.org/en-US/firefox/enterprise/ is v78, so I think once ESR v91 is released we can remove the old code here.

**Comment by alexgibson** [comment]
Oh, it looks like ESR v91 is already available (both versions are currently showing at https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr), so I think we can likely do this in Q1 2022.

**Comment by alexgibson** [comment]
/cc @l-hedgehog 

I'm planning on picking this up and working on it over the holidays. The change would mean we'd only handle the China Repack logic for Sync users on FF v80 and above (via the `UITour.showFirefoxAccounts()` API call). Older FF versions would simply link to accounts.firefox.com (the same as non-Firefox browsers already do).

If this is a problem for users in China (I have no idea how many are still on older FF versions?), we could still maintain some of the old logic that updates links to to accounts.firefox.com.cn. But we would only allow users to login (i.e. not Sync automatically). I'd like to propose we try and drop as much legacy code as we can though, as it gets pretty complex in places.

Any thoughts / concerns, Hector?

**Comment by l-hedgehog** [comment]
Hi @alexgibson,

Thank for looping me in.

I asked our Ops @xjc2694 to check the traffic from bedrock to https://accounts.firefox.com.cn/, and it looks like the majority are from recent whatsnew pages.

I think it should be okay to remove logic for early enough Fx versions.

**Comment by alexgibson** [comment]
> I think it should be okay to remove logic for early enough Fx versions.

Great, thank you!
