### ISSUE TITLE
Convert safebrowser and adblocker pages to Fluent

### ISSUE THREAD

**Issue by Errolyn** [mozilla/bedrock#9146]
## Description

All the feature pages have been converted to fluent besides Safebrowser and adblocker pages.

---

#### Success Criteria
- [ ] Safe browser page is using fluent
- [ ] adblocker page is using fluent

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by alexgibson** [comment]
It looks like the safebrowser page has never been translated, and the adblocker page was completed in https://github.com/mozilla/bedrock/pull/9439
