### ISSUE TITLE
/firefox/mobile-promo/ page shows mixed content in other languages.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9147]
## Description

It looks like this page is only for an experiment in which case it may not be much of a big deal, but the URL is currently marked as active for a large number of locales, and shows mixed English copy that has never been opened up to L10n:

https://www.mozilla.org/de/firefox/mobile-promo/

I'm guessing it probably shouldn't be using `firefox/welcome/page4.lang`: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/messaging-experiment/control.html#L8

### Steps to reproduce

1.) Visit https://www.mozilla.org/de/firefox/mobile-promo/

### Expected result

The page should either be in German, or if not available it should redirect to en-US.

### Actual result

The page shows a mixture of German and English copy.

### Environment

N/A

**Comment by alexgibson** [comment]
I think fixing this should be as straightforward as removing this line: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/messaging-experiment/control.html#L8

Marking as a good-first bug.

**Comment by nileshdas** [comment]
Can I work on this issue? @alexgibson

**Comment by mdieske** [comment]
I would also like to work on this issue. I'm new to Github and this would be my first bug. Looks like a good one to get my feet wet. 😉

**Comment by alexgibson** [comment]
fixed: https://www.mozilla.org/en-US/firefox/mobile-promo/
