### ISSUE TITLE
Decommission /firefox/campaign/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9148]
## Description

The [firefox campaign](https://www.mozilla.org/en-US/firefox/campaign/) page no longer has any real owner in marketing, and it's now just a replica of [/new](https://www.mozilla.org/en-US/firefox/new/), so we should decommission the page and redirect it (vs migrate to Fluent).

---

#### Success Criteria
- [ ] Page is removed from bedrock and URL is redirected to /new.

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [x] Team Lead
- [ ] Others?

**Comment by alexgibson** [comment]
@hoosteeno please confirm here if / when we can make this change, thanks.

**Comment by hoosteeno** [comment]
Let's remove this page and redirect to /new for all locales. Thanks!
