### ISSUE TITLE
[8-10] WNP80 - Design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9156]
## Description

The WNP for Firefox 80 release on 2020-08-25, promoting content as part of the Sept campaign.

This card is for the creation, review and approval of the designs to be used in the page.

[Principal project doc ](https://docs.google.com/document/d/1_pWp3lZJe3qFf5bCgsg_Lck6LaoB3RiFm1kRiPyz2As/edit)

---

#### Success Criteria
- [ ] Design assets are approved and provided to dev on or before 2020-08-10

#### Approvals
- [ ] The Accountable- MWarther
- [x] Brand design - Clio
- [ ] Team Lead - Hoosteeno
- [ ] PMM - TBD

**Comment by cgonz0** [comment]
[wnp80_assets.zip](https://app.zenhub.com/files/1616665/d7fb8b76-57dd-4013-85dd-b7bbb8509177/download)

----
![wnp80.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/830a5fc3-c832-431f-8157-66419d12b225)
