### ISSUE TITLE
Prune unused assets from bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9170]
## Description

Images are one of the largest asset types and contribute significantly to the overall footprint of bedrock. Looking through the `/media/img/` directory, I think there is likely scope for a good cleanup of unused images that have been orphaned over the years. Pruning unused images will help reduce the number of bytes we push / pull around the internet, and may also help with memory consumption when running bedrock locally and watching files.

It may also be worth looking in `/media/fonts/` as these are also heavy weight files.

---

#### Success Criteria
- [ ] Unused images are pruned from the repository.

**Comment by chuckthemole** [comment]
Hi, would this be a good project for a first time contributor? If so I'd like to take it on. Thanks!

**Comment by alexgibson** [comment]
Pull requests are welcome, thanks!

**Comment by sumagnadas** [comment]
Can this be a good issue for first time contributor? If yes, then i would like to try fixing it.

Thanks.
