### ISSUE TITLE
/fraud-report/ - Success notification appears at the bottom of the page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9177]
## Description

Upon sucessfully submitting a fraud-report, the success notification appears right at the bottom of the page, providing no clear indication that the report was sent.

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/about/legal/fraud-report/
2. Submit the required information.

(you can also visit https://www.mozilla.org/en-US/about/legal/fraud-report/?submitted=True directly)

### Expected result

Upon submission, there should be a notification visible in the viewport confirming that the report was sent.

### Actual result

The notification is shown right at the bottom of the page, which is not visible for most screen sizes. It should probably appear at the top of the page.

![image](https://user-images.githubusercontent.com/400117/87915855-9433fa80-ca6a-11ea-86be-f759b6c5d604.png)

### Environment

N/A

**Comment by berliners1** [comment]
I just submitted a pull request for a potential fix to this issue, also accounting for the red Error notification that can occur there.
