### ISSUE TITLE
Migrate Nightly /whatsnew page to Fluent

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9184]
## Description

[Firefox Nightly Whatsnew](https://www.mozilla.org/en-US/firefox/52.0a1/whatsnew/all/) - this page should show the nightly update is everyone 4-5 weeks, but the [Japanese version](
https://www.mozilla.org/ja/firefox/52.0a1/whatsnew/all/) - didn't translate the updated string so it resorts to the obsolete string which states 6-8 weeks. This is incorrect and needs to be updated.

### Steps to reproduce

en-US: https://www.mozilla.org/en-US/firefox/52.0a1/whatsnew/all/

ja: https://www.mozilla.org/ja/firefox/52.0a1/whatsnew/all/

### Expected result

Correct the information on release frequency

### Do we have a shortcut to make changes?

What is the roadmap to migrate firefox/nightly_whatsnew? If not immediately, can we still make changes in .lang to correct information that is wrong by using shortcut somewhere.

**Comment by peiying2** [comment]
I made the change in .lang file. If there is a way to manually push the file to production. If this is not possible because of current configuration, do we have a timeline to convert firefox/nightly_whatsnew.lang. Thanks!

**Comment by alexgibson** [comment]
@peiying2 let's get this page ported to Fluent so we can get this fixed

**Comment by alexgibson** [comment]
Ok, I opened a PR for migration. If you can review the .ftl files I'll see if we can get the bedrock part reviewed asap.
