### ISSUE TITLE
The instructions for opting out of Firefox Welcome Page point instead to Contextual Feature Recommender documentation 

### ISSUE THREAD

**Issue by dholbert** [mozilla/bedrock#9203]
## Description

Today (or recently), we started showing a "Firefox Welcome Page". Towards the bottom of the Welcome page, there's a "why am I seeing this" link (I forget the exact text), which points to https://support.mozilla.org/en-US/kb/firefox-browser-welcome-pages

This support page is generally helpful, but it doesn't have any "how do I opt out" steps.  Instead, it has reference to another page for instructions on that -- and unfortunately, that other page seems to be about a completely different feature.

### Steps to reproduce

Visit https://support.mozilla.org/en-US/kb/firefox-browser-welcome-pages#w_how-do-i-hide-all-firefox-browser-welcome-pages , try to find instructions to opt out of seeing the Firefox Welcome Page.

### Expected result

I should be able to find clear instructions about how to opt out.

### Actual result

There's a link "more information about opting out" which points to https://support.mozilla.org/en-US/kb/recommendations-firefox#w_how-do-i-opt-out-of-recommendations-in-firefox which is a page about a different sort of notification feature.  This page makes zero mention of the Firefox Welcome Page, and it points to checkboxes for "Recommend features/extensions as you browse".  It's not clear whether or not those checkboxes are related to the Firefox Welcome Page (maybe they are? If so, we should explicitly say so).

### Environment

Firefox Nightly 80 on Linux

**Comment by dholbert** [comment]
To be clear, I don't actually know if the linked opt-out instructions (for Contextual Feature Recommender) are in fact completely unrelated to the Welcome page and are just linked via a copypasta-mistake, or if they are actually the correct way of opting out of the Welcome page & they just need clarification to explain that.

To whoever ends up addressing this: I think that is the first question to be answered.

**Comment by pmac** [comment]
Is the new Welcome Page hosted on www.mozilla.org (WMO)? If not then this issue may need to go over to the [SUMO team](https://github.com/mozilla/kitsune/). Typically when an in-product link to SUMO is added it goes through a redirector they maintain, so the link should be able to be directed to a better page, or that team could update the current page to better explain the opt out procedure. If it is hosted on WMO then this is the repo where we could point it to a better link if one exists.

**Comment by alexgibson** [comment]
I believe this is one of the welcome pagesin question: https://www.mozilla.org/en-US/firefox/welcome/1/

@hoosteeno is the SUMO article accurate, in that this is the right way to opt-out of these pages? If so, perhaps the SUMO team could make their wording a little clearer. If not, then we need to fix the opt-out mechanism.

**Comment by dholbert** [comment]
Yeah, thanks -- that's the welcome page that I was thinking of (I had lost the URL).  There are different versions, `/1/` through `/8/`, and they all have a "Why am I seeing this?" link at the bottom, which points to the SUMO page that I linked in comment 0.

**Comment by ejregithub** [comment]
I walked through this user journey and verified some information about the requirements to 'turn off welcome pages'. I will update the first landing page with that information. There's no need for two clicks.

**Comment by ejregithub** [comment]
I updated the first page with the instructions on how to turn off welcome pages. It's pending approval by folks at SUMO.

On https://support.mozilla.org/en-US/kb/firefox-browser-welcome-pages/ the proposed updates look like this:

![Screen Shot 2020-07-22 at 3 21 58 PM](https://user-images.githubusercontent.com/20547886/88235269-5b914e00-cc2f-11ea-9294-1732fd8b28bb.png)

**Comment by alexgibson** [comment]
Looks like the content above is now featured in the SUMO article, so closing this. Thanks for reporting!
