### ISSUE TITLE
Add VPN link in main nav and footer

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9206]
## Description

We are working on a longer-term navigation refactor that clarifies the relationship between our products and brands. Meanwhile, let's put a big, bright link to VPN in both global navigations.

In the Firefox nav, replace the "Connected and Protected" promo under the Products nav item:
![Screen Shot 2020-08-05 at 3 47 32 PM](https://user-images.githubusercontent.com/94519/89467550-04ad6d80-d733-11ea-980a-cf029f818889.png)

In the Mozilla nav, replace the Add-Ons promo under the Firefox nav item:
![Screen Shot 2020-08-05 at 3 47 28 PM](https://user-images.githubusercontent.com/94519/89467561-0bd47b80-d733-11ea-94df-7e47236a3c47.png)

In both cases we can use the same image, copy -- to be provided in a comment on this bug. In both cases, the url can be: 

`https://vpn.mozilla.org/?utm_source=www.mozilla.org-globalnav&utm_medium=referral&utm_campaign=globalnav`

Let's also link to it from the Products section in the Firefox footer. The URL in the footer can be:

`https://vpn.mozilla.org/?utm_source=www.mozilla.org-footer&utm_medium=referral&utm_campaign=footer`

---

#### Success Criteria
- [x] Designs and copy for nav treatment are attached to this issue
- [ ] Both global navs updated in production
- [ ] Footer updated in production

#### Approvals
- [x] Websites Designer
- [x] Websites Dev
- [x] @chrismore
- [x] @hoosteeno

**Comment by rraue** [comment]
Any thoughts @dzingeek?

**Comment by hoosteeno** [comment]
Great bug. We'll want to parameterize the link for attribution.

**Comment by rraue** [comment]
This issue is still open and confusing the overall accessibility between both brand worlds: https://github.com/mozilla/bedrock/issues/8937. We have not so much products that we should completely separate them from each other. And the Mozilla part of teh website has great SEO power by external links as well. We should give the new product all SEO help we can do and a main nav link will be very valuable.

**Comment by stephaniehobson** [comment]
Should we add it as a product on https://www.mozilla.org/en-US/firefox/products/ as well? There's an open space.

**Comment by dzingeek** [comment]
Ugh..yeah this is a mess. IMO having a Mozilla branded thing live under firefox nav is very confusing. My suggestion would be to have this live in the moz footer and nav but NOT in the firefox one. 

If we are thinking of them as two separate sites (even though they are not) and treating them that way (separate navs and footers) then you would not expect to see Mozilla product in the nav of (let's say) firefox.com

**Comment by rraue** [comment]
Mentioning @chrismore here as well, so he is aware

**Comment by hoosteeno** [comment]
We are working on a longer-term navigation refactor that clarifies the relationship between our products and brands. Meanwhile, let's put a big, bright link to VPN in both global navigations.

In the Firefox nav, replace the "Connected and Protected" promo under the Products nav item:
![Screen Shot 2020-08-05 at 3 47 32 PM](https://user-images.githubusercontent.com/94519/89467550-04ad6d80-d733-11ea-980a-cf029f818889.png)

In the Mozilla nav, replace the Add-Ons promo under the Firefox nav item:
![Screen Shot 2020-08-05 at 3 47 28 PM](https://user-images.githubusercontent.com/94519/89467561-0bd47b80-d733-11ea-94df-7e47236a3c47.png)

In both cases we can use the same image, copy -- to be provided in a comment on this bug.

**Comment by hoosteeno** [comment]
@chrismore Please review the above as a stop-gap until we have the bigger nav overhaul done. Look OK?

**Comment by chrismore** [comment]
@hoosteeno works for me! Just let me know what the UTM parameters are going to be, which will likely be fine as you all do a great job with the nomenclature.

**Comment by hoosteeno** [comment]
I updated the issue description with these specs.

**Comment by ejregithub** [comment]
@rantley - can you please take a look at the screenshots in https://github.com/mozilla/bedrock/issues/9206#issuecomment-669534973 and provide some copy/copy options appropriate for Mozilla VPN in that available space?

@cgonz0 - can you please take a look at the screenshots in https://github.com/mozilla/bedrock/issues/9206#issuecomment-669534973 an image/image options for promoting Mozilla VPN?

**Comment by chrismore** [comment]
Thanks everyone! What's the estimated time on when this could be available on the website?

**Comment by ejregithub** [comment]
@chrismore @hoosteeno - I think by this time next Thursday is probably reasonable.

@rantley - I started a [copy doc](https://docs.google.com/document/d/1lRSbYy-kjQL3eXjoaS7Ctn1eBrOpNO9znC8_7-r_7DI/edit) that blatantly pilfers copy from https://vpn.mozilla.org/ and from the (brand) [copy options you wrote](https://docs.google.com/document/d/1zdAV6bvMaGkJnJQyoOyKlGnZw4XkspHdg-qkb3GtSso/edit) for the mobile in app and push notification content.

**Comment by cgonz0** [comment]
would recommend using this image (one of mozilla vpn's initiatives is to drive more mobile downloads so it could be a good idea to showcase mobile here)
![VPN-nav_mock](https://user-images.githubusercontent.com/29640968/89672584-bf578000-d899-11ea-9ab5-1e947538f389.png)

**assets**
high res
![VPN-nav_high-res](https://user-images.githubusercontent.com/29640968/89672921-54f30f80-d89a-11ea-8414-306c5b3ee8cb.png)
![VPN-nav](https://user-images.githubusercontent.com/29640968/89672922-56243c80-d89a-11ea-9003-2717ea914a4e.png)

**copy**
NEW Mozilla VPN
Get a Mozilla VPN subscription and get next-level security and privacy on any network.

**Comment by alexgibson** [comment]
Is this ready for coding, or is the copy here still being worked on?

**Comment by cgonz0** [comment]
@alexgibson copy/image needs to be approved, @hoosteeno

**Comment by ejregithub** [comment]
@chrismore - Hoosteeno is going to reach out to you about approvals for the copy and design proposals here.

**Comment by hoosteeno** [comment]
I'm good with this -- thanks! I'll ask @chrismore for a final nod on https://github.com/mozilla/bedrock/issues/9206#issuecomment-670631886.

**Comment by chrismore** [comment]
@hoosteeno @cgonz0 the visuals and placement look good to me, but I want to talk about the copy. 

2 questions:

1. The messaging framework we are using for the Mozilla VPN is “A faster, safer, and simpler VPN that protects your privacy from a name you can trust.”. This is the framework that we used for the copy on the VPN website, the owned media channel content, and the upcoming UAC content. The content for the www.mozilla.org navigation doesn't seem as aligned as it could be.

With the copy above: "Get a Mozilla VPN subscription and get next-level security and privacy on any network."

What is "next-level security" and what does "privacy on any network" mean? I wanted to hear the answers on the copy and the understanding potential customers should get from it.

2. For the "NEW Mozilla VPN" heading could we put "New: Mozilla VPN"? We could also try not having "NEW" as part of the link. I am not sure if I like the word "NEW" being part of the link as that may not be relevant to search engines, but maybe that's actually good. I guess maybe adding a ":" between the two makes it more clear what is new.

Thanks!

**Comment by alexgibson** [comment]
From a localization point of view `NEW Mozilla VPN` isn't going to age well, and will likely be around for some locales long after the VPN is no longer considered new.

**Comment by chrismore** [comment]
> From a localization point of view `NEW Mozilla VPN` isn't going to age well, and will likely be around for some locales long after the VPN is no longer considered new.

Yeah, I am fine with not having "NEW". It has been available to purchase (in the US) since Dec 2019 and it won't be new much longer as we roll it out in more countries.

**Comment by chrismore** [comment]
Here's some copy I wrote based on the current value props and target audience:

<h2>Mozilla VPN: Fast. Simple. Private.</h2>
<p>Protect your entire device and all applications. Mask your real location and connect up to 5 devices. Subscribe now.</p>

**Comment by cgonz0** [comment]
> @hoosteeno @cgonz0 the visuals and placement look good to me, but I want to talk about the copy.
> 
> 2 questions:
> 
>     1. The messaging framework we are using for the Mozilla VPN is “A faster, safer, and simpler VPN that protects your privacy from a name you can trust.”. This is the framework that we used for the copy on the VPN website, the owned media channel content, and the upcoming UAC content. The content for the [www.mozilla.org](http://www.mozilla.org) navigation doesn't seem as aligned as it could be.
> 
> 
> With the copy above: "Get a Mozilla VPN subscription and get next-level security and privacy on any network."
> 
> What is "next-level security" and what does "privacy on any network" mean? I wanted to hear the answers on the copy and the understanding potential customers should get from it.
> 
>     1. For the "NEW Mozilla VPN" heading could we put "New: Mozilla VPN"? We could also try not having "NEW" as part of the link. I am not sure if I like the word "NEW" being part of the link as that may not be relevant to search engines, but maybe that's actually good. I guess maybe adding a ":" between the two makes it more clear what is new.
> 
> 
> Thanks!

pinging copywriter @rantley to weigh in here

**Comment by rantley** [comment]
@cgonz0 @chrismore the below suggestion from Chris looks great to me. 

Mozilla VPN: Fast. Simple. Private.

Protect your entire device and all applications. Mask your real location and connect up to 5 devices. Subscribe now.

**Comment by chrismore** [comment]
> @cgonz0 @chrismore the below suggestion from Chris looks great to me.
> 
> Mozilla VPN: Fast. Simple. Private.
> 
> Protect your entire device and all applications. Mask your real location and connect up to 5 devices. Subscribe now.

Thanks, Rob!

@cgonz0 @alexgibson if you could make this copy change, I can r+ the update. Thank you!

**Comment by cgonz0** [comment]
@chrismore here's an updated mock with new copy
![VPN-nav_mock](https://user-images.githubusercontent.com/29640968/89828643-2b421e80-db0e-11ea-82cb-b37aa61cb801.png)

**Comment by chrismore** [comment]
r+

Thanks all.

**Comment by alexgibson** [comment]
@cgonz0 @chrismore I pushed this to a demo with the changes above:

- https://www-demo2.allizom.org/en-US/
- https://www-demo2.allizom.org/en-US/firefox/

The respective UTM params are as follows:

- https://vpn.mozilla.org/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=firefox
- https://vpn.mozilla.org/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=products

**Comment by chrismore** [comment]
@alexgibson looks good and I confirmed the UTM parameters. Also, just to confirm that the VPN promo is removed on smaller viewport sizes.

**Comment by alexgibson** [comment]
> Also, just to confirm that the VPN promo is removed on smaller viewport sizes.

Yes that's correct - and a good callout. This is something that has previously be oriented to desktop user primarily. This is some thing we should reconsider when working on https://github.com/mozilla/bedrock/issues/9286

/cc @hoosteeno

**Comment by rraue** [comment]
I wanted to mention the same, good for promoting it quickly and getting it into the nav, but most likely as search engines crawl mobile first these days, the link won't count for Pagerank.

**Comment by chrismore** [comment]
> I wanted to mention the same, good for promoting it quickly and getting it into the nav, but most likely as search engines crawl mobile first these days, the link won't count for Pagerank.

Yeah, it would be nice to at least have a link to the Mozilla VPN page on smaller viewport sizes for that reason. As Alex mentioned, probably something for #9286

**Comment by alexgibson** [comment]
@chrismore fyi this is now in prod: https://www.mozilla.org/en-US/
