### ISSUE TITLE
[7/28] Enable Switch for Firefox Lite /whatsnew page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9214]
## Description

The page is already in prod, but toggled off [behind a switch](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L488).

Dev: https://www-dev.allizom.org/en-US/firefox/79.0/whatsnew/africa/
Prod: https://www.mozilla.org/en-US/firefox/79.0/whatsnew/africa/

This issue to to track flipping the switch on, date is now on 7/28, before EOD Pacific Time

---

#### Success Criteria
- [ ] Firefox Lite /whatsnew page is enabled in prod.

**Comment by ejregithub** [comment]
@craigcook - could you please handle this one tomorrow (7/28)?
