### ISSUE TITLE
WNP Brand Refresh: Design

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9216]
The Brand Team is refreshing the WNP. This is the design card for that Epic.

Success Criteria:
- [ ] Added more Protocol components
- [ ] Brought it on brand wrt design

Reviews: 
- [ ] Channel owner
- [ ] Dev
- [x] Brand

**Comment by ejregithub** [comment]
Eric to book review meeting on Thursday w. Craig

**Comment by cgonz0** [comment]
[wnp_template_mocks.zip](https://app.zenhub.com/files/1616665/6122ad78-4e68-4d14-a232-cd8ffbca268c/download)

[google doc](https://docs.google.com/presentation/d/1KuaVxK_w5ob5mJXs0DpBKRXb6mgE8Rkd8iN1bm6zPCk/edit#slide=id.g8667d36c34_0_0)

overview
![wnp_template_overview.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/cf2b1402-27d7-4309-b917-ae0701b8600a)
