### ISSUE TITLE
WNP Brand Refresh: Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9218]
The Brand Team is refreshing the WNP. This is the code card for that Epic.

- [ ] Page is approved
- [ ] Page is live in prod in TBD WNP version BETWEEN release, not for a specific release at launch

**Comment by hoosteeno** [comment]
Let's stub out an 82 template and apply this there.

**Comment by hoosteeno** [comment]
This needs review. We've stubbed out a WNP 82 page with this code on it.
