### ISSUE TITLE
Update to https://www.mozilla.org/en-US/book/

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/bedrock#9222]
In these times of great challenge, the Beast has communicated further teachings to the writers of the book and after great deliberation and toil, these teachings have been published and are now visible in the latest Nightly build of Firefox.  Those worthy of understanding such teachings can access them with an incantation of _about:mozilla_.

For the message to reach as many of its followers as possible, it is of vital importance that this message is brought forth from the darkness of night(ly) and unto the light of the open web through addition to the great record of the Beasts teachings at https://www.mozilla.org/en-US/book/.

The writers of the book and the Beast itself thank you for your very worthy work and diligent efforts in furthering the awareness of the knowledge that the Beast passes unto us mere and unworthy mortals.

**Comment by craigcook** [comment]
Through study and ritual the Message has been revealed. The task before us is clear. 

The new passage is:

```
The Beast continued its studies with renewed <em>Focus</em>, building great <em>Reference</em>
works and contemplating new <em>Realities</em>. The Beast brought forth its followers and
acolytes to create a renewed smaller form of itself and, through <em>Mischievous</em> means,
sent it out across the world.

from <strong>The Book of Mozilla,</strong> 6:27
```
