### ISSUE TITLE
wrong fenix nightly link in docs

### ISSUE THREAD

**Issue by s-ankur** [mozilla/bedrock#9225]
## Description
Steps to reproduce
Go to
https://www.mozilla.org/en-US/firefox/channel/android/?utm_source=support.mozilla.org&utm_campaign=footer&utm_medium=referral#nightly
Click on the nightly icon

### Expected result

It should open the current nightly

### Actual result

It opens "no item" in play store

### Environment

What browser and operating system are you using?
Android, Fenix Nightly

**Comment by nileshdas** [comment]
Taking up this issue
