### ISSUE TITLE
Protection Report CTA is unmeasurable

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9237]
In https://github.com/mozilla/bedrock/blob/f771dc08768835577e7873a89e193e4158f2bcfb/media/js/firefox/whatsnew/whatsnew-79.js#L20 and in https://github.com/mozilla/bedrock/blob/7931f4e3c06568afc8c96bc8716c77c5ecd7fab7/media/js/firefox/privacy/products.js#L14 and in https://github.com/mozilla/bedrock/blob/f95c4ed85781d85e679c5216b7455a970e62424e/media/js/firefox/new/desktop/download.js#L188 we open the protection report before modifying the dataLayer. This means events related to protection report CTA clicks will almost never appear in GA. 

These likely to be reversed, as in https://github.com/mozilla/bedrock/pull/9232/files.

**Comment by craigcook** [comment]
There are a few other pages in the same situation and we can fix them all at once, but welcome 8 will go first for urgency. I can put a PR together for all the others.
