### ISSUE TITLE
Push Private Relay ToS to https://www.mozilla.org/about/legal/terms/firefox-relay/

### ISSUE THREAD

**Issue by litkaemily** [mozilla/bedrock#9240]
cc: @mafeld

Hi @pmac and @alexgibson, 

I'm writing to see if you could push the Firefox Relay Terms of Service to the following url: **https://www.mozilla.org/about/legal/terms/firefox-relay/**

The ToS are here: **https://github.com/mozilla/legal-docs/blob/master/firefox_relay_ToS/en-US.md**

As soon as possible would be good, but August 24th at the latest. @groovecoder let me know if I've got this date wrong.

Many thanks!
Emily

**Comment by alexgibson** [comment]
Thanks, will let you know as soon as this is in production.

**Comment by alexgibson** [comment]
@litkaemily this is now in production, thank you https://www.mozilla.org/en-US/about/legal/terms/firefox-relay/
