### ISSUE TITLE
Remove whatsnew 78 experiment code

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9247]
## Description

Now that the experiment has ended, we should remove the experiment-specific code that landed in #9033

**Comment by amychurchwell** [comment]
howdy @Errolyn - it looks like you made the original PR for this experiment. Wanted to draw your attention to this issue since that experiment has concluded.

**Comment by Errolyn** [comment]
Thanks! I should have some time this week to remove it.
