### ISSUE TITLE
Older versions of translated pages not linked to newer ones

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9251]
The /new page was recently redesigned. That means there are now three versions of this page. V1 has been migrated to fluent and has wide translation support. V2 remains in lang files. V3 is our shiny new one. 

The language selector in the footer of the English page only includes the locales which have translated V3 and it should be possible to access all translations from the drop down.

**Comment by rraue** [comment]
Additional issue is, that hreflang is as well only included for the locales in the language switcher, so its down to a few right now. That will confuse our language search setup a bit and might lead to wrong locales ranking in not yet translated pages.

**Comment by pmac** [comment]
The list of languages comes from the activation of the first Fluent file in the list. So you could just put the other template's fluent file first in the list and it will use the old languages list. That should work fine unless there are locales for the new page that aren't there for the old one.

**Comment by alexgibson** [comment]
I can see situations where a locale translates the newer template instead of doing the older one. Also, how does this play into situations where one older template is using .lang?

**Comment by pmac** [comment]
I'll have to look more into it. I remember discussing these issues, but it's been a while.

**Comment by pmac** [comment]
> Also, how does this play into situations where one older template is using .lang?

After looking at it some more I think the best course is to port the existing page to Fluent before doing a redesign. We'll have to figure out a way to indicate multiple Fluent files to combine for the full active locales list, but that will be considerably easier and less cumbersome than indicating which old template the old page uses during rendering. It's possible we could solve it, but I think it will be difficult and only really useful during the transition, whereas dealing with a redesign from Fluent -> Fluent will continue to happen.

**Comment by alexgibson** [comment]
I'm about to decommission the old .lang template in https://github.com/mozilla/bedrock/issues/8372, which will move us back to 2 versions (both in Fluent).
