### ISSUE TITLE
Download test failures are hard to read

### ISSUE THREAD

**Issue by duallain** [mozilla/bedrock#9252]
## Description

When a test fails, the current error message doesn't provide additional information.

Example of current error:
```
_____________________________ ERROR collecting gw2 _____________________________
Different tests were collected between gw1 and gw2. The difference is:
--- gw1

+++ gw2
```

### Steps to reproduce

1. Have a test from the `tests/functional/test_download.py` suite fail. (Probably fairly easy to introduce, add a bad url to test suite)
1. See that the error message is a little ambiguous

### Expected result

The link to the url that failed should be visible to the end user.

### Actual result

The thread/process names are instead reported.

### Environment

N/A. (This was first identified on a failed job 'test-download')

**Comment by duallain** [comment]
@pmac Adding a bug to track, but no rush.  Could use your help to make sure this bug report makes sense.

**Comment by pmac** [comment]
That failure isn't actually a test failure, it's a failure during test collection. It means that the collected set of URLs to test didn't work properly for some reason. I think each of the processes collects all of the URLs to test by scraping the test pages. If one of the requests to the test pages fails then it all fails. If a download test fails it should be much more descriptive. We could test all of that though.

**Comment by alexgibson** [comment]
Closing as per comment above
