### ISSUE TITLE
Set up 301 redirect from /grants to /moss

### ISSUE THREAD

**Issue by chriswryly** [mozilla/bedrock#9254]
## Description

DO:  Set up 301 redirect for /grants and all pages under /grants - https://www.mozilla.org/grants/*  - to https://www.mozilla.org/moss

---

Original report:

The URL (which I've been told is in bedrock) https://www.mozilla.org/en-US/grants/ delivers a vastly out of date web page, including contact information for Rowe Hoffer. While it doesn't appear to be linked anywhere, it's indexed and comes up in some search queries. I would like for this webpage to be taken down, or redirected to https://www.mozilla.org/en-US/moss/

### Steps to reproduce

As noted, the URL is https://www.mozilla.org/en-US/grants/

### Expected result

A current website would be delivered, such as https://www.mozilla.org/en-US/moss/

### Actual result

The original, outdated website is displayed, including Rowe's email address.

### Environment

N/A [for the record, Firefox Nightly on up-to-date Mac OS]

**Comment by ejregithub** [comment]
@chriswryly - we'll set up a 301 (permanent) redirect from /grants to /moss

**Comment by chriswryly** [comment]
Terrific, thanks!

**Comment by ejregithub** [comment]
@chriswryly - there's a substantial subset of pages (those describing past grantees - https://www.mozilla.org/en-US/grants/w3c-validator.html).

I just want to confirm that we have carte blanche to redirect all pages under /grants, https://www.mozilla.org/en-US/grants/* to /moss

**Comment by chriswryly** [comment]
Hi Eric,

Can we save the raw HTML offline somewhere? I do want to redirect every
page, but I think it'd be worthwhile to have an archive in case there are
later questions, even though this is all at least 8 years old.

Thanks!

**Comment by ejregithub** [comment]
@chriswryly - it will remain in github history - https://github.com/mozilla/bedrock/commits/master/bedrock/grants

**Comment by chriswryly** [comment]
Perfect, thanks!
