### ISSUE TITLE
Add tests for the download modal in Firefox on /new

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#9258]
## Description

When using the current release version of Firefox, clicking a download button on the redesigned /new page opens a modal telling you you're already on the latest Firefox and suggesting creating an account, with another option to continue to download. We should add automated tests for this condition.

In the current release version of Firefox:
- [x] Clicking a main download button opens the modal.
- [ ] Clicking the "create account" button within the modal navigates to /firefox/accounts/.
- [ ] Clicking the "download anyway" button within the modal navigates to /download/thanks/.

---

#### Success Criteria
- [ ] Tests are added

**Comment by Ingi-Hong** [comment]
I started to work on this but noticed the "skip if firefox" decorator on the download button test - 

![image](https://github.com/mozilla/bedrock/assets/73002018/f43bab1b-ec36-49c1-9301-b0ac941a6fae)

but the modal only displays on most recent firefox versions. So is the modal download button untestable atm?

**Comment by stephaniehobson** [comment]
This modal has been removed.
