### ISSUE TITLE
Evaluate Convert integration in bedrock

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9259]
## Description

Now that we've been using [Convert](https://www.convert.com/) to facilitate experiments for the best part of a year, it's probably a good time to evaluate how we have it set up in bedrock, and to see if there's anything we could change to help improve / simplify the workflow the CRO team are using.

Some possible questions to discuss:

- Are there any aspects of Convert that aren't working right? (things we could file support tickets for / improve somehow in bedrock).
- Are the /exp/ templates working out ok? The original idea was to use separate templates so both the CRO and websites teams could work independently (i.e. not having to delay one team's work to wait on the other team). If that's not so much of an issue in hindsight, there may be other options we could look to explore (e.g. using a query param & switch to load Convert conditionally).
- Is the [Cloudflare Worker](https://github.com/mozmeao/www-workers) doing the things the team needs in a sensible fashion? Would another redirection mechanism (e.g. traffic cop in bedrock), be simpler or more cost effective.

Any other questions?

**Comment by amychurchwell** [comment]
@alexgibson off the cuff thoughts:

> Are the /exp/ templates working out ok? 

I'm doing the work this week to update the /new exp template to reflect the redesign. I wonder if there can be a relationship with `{% block content %}` between exp templates and their counterparts? Currently, it relies on someone being aware of changes that have happened on the corresponding pages and making the manual update.

Exp being true reflections of what is in prod is important for the integrity of the experiment, I could foresee a situation where a template is updated and it goes unnoticed and potentially nullifies the results of an experiment. Especially considering that different teams may own the content on different pages and tweak as needed.

> Is the Cloudflare Worker doing the things the team needs in a sensible fashion?

It would be nice if it wasn't such a manual process. Submitting a PR each time to update the redirect feels a little heavy to me. I also wonder if it would be beneficial to have a mechanism to automatically turn off redirects?

**Comment by alexgibson** [comment]
> I'm doing the work this week to update the /new exp template to reflect the redesign. I wonder if there can be a relationship with {% block content %} between exp templates and their counterparts? Currently, it relies on someone being aware of changes that have happened on the corresponding pages and making the manual update.

> Exp being true reflections of what is in prod is important for the integrity of the experiment, I could foresee a situation where a template is updated and it goes unnoticed and potentially nullifies the results of an experiment. Especially considering that different teams may own the content on different pages and tweak as needed.

That's something we could potentially do yeah - the only real downside is folks on both teams need to communicate carefully when making changes to prod pages, else it could interfere with CRO team experiments. And running experiments could delay rolling out changes to prod pages.

**Comment by alexgibson** [comment]
> It would be nice if it wasn't such a manual process. Submitting a PR each time to update the redirect feels a little heavy to me. I also wonder if it would be beneficial to have a mechanism to automatically turn off redirects?

My initial thought here is that building a dashboard system, together with things like automation and authentication, seems like potentially a lot of work for making what often amounts to a very small code change. If you had a different idea as to how this could materialize, I'd be interested to talk more about it though.

**Comment by alexgibson** [comment]
@hoosteeno @amychurchwell since things have changed since this issue was filed, and the website and CRO teams are now merged (so to speak), I wonder if it makes sense to simplify how we have things set up a bit?

We could for example, now make the /exp/ pages extend the core templates, instead of duplicating them. This could be less effort for the website team to maintain - and seeing as now we don't have seperate teams working on experiments independently, that might be easier to manage.

Thoughts?

**Comment by alexgibson** [comment]
I chatted with Justin breifly about this yesterday and what I'd like to propose is the following:

- We stop duplicating /exp/ template HTML/CSS/JS.
- We switch to a system of /exp/ templates extending the original templates (less code duplication).

I think there's less risk of breakage if we do this now that CRO is no longer a separate team. We're more integrated, so have a better understanding of eachother's work in-flight.

Doing the above changes will save us some manual work, and may also make experimentation easier to facilitate on pages in the future. I'm happy to close this issue and file a new one for the template changes, but I'm also interested in @amychurchwell's thoughts on this from a dev perspective?

**Comment by amychurchwell** [comment]
@alexgibson totally agree. The manual updating of exp templates is not sustainable and all future convert experiments will be launched from the websites team.

**Comment by alexgibson** [comment]
Filed https://github.com/mozilla/bedrock/issues/9369 to follow up making the above changes.
