### ISSUE TITLE
S2D widget: Replace modal with inline form

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9260]
## Description

In https://github.com/mozilla/bedrock/pull/8901 we ran an experiment that tested the S2D widget vs. an inline form. The inline form performed 69% better than the modal. We should replace the modal with a form on /mobile and we should explore replacing it in other S2D widget locations. 

![image](https://user-images.githubusercontent.com/94519/89207401-e64f4280-d577-11ea-8148-5f914afed4a5.png)

On WNP78, we tested different CTAs to accompany the S2D form. The most performant of these was slightly more than 1% better than the control. We should replace the CTA on the new inline modal with the copy from the winning variant:

"HL: Get more done. Use Firefox for mobile.
Copy: Send a download link to your phone."

This copy outperformed the control in en-US, fr, and de. We should use it for now. 

---

#### Success Criteria
- [x] Design specs are attached to this issue
- [x] Widget is replaced with form on /mobile

#### Approvals
- [x] Design
- [x] Dev
- [x] Channel owner (PMM?)

**Comment by hoosteeno** [comment]
@cgonz0 Can you review the proposal above, produce a mockup of your suggested layout (including any tweaks to suggested copy), and attach? If you don't have any suggested changes, can you just give the above a glance and nod? Thanks!

**Comment by alexgibson** [comment]
This is blocked by https://github.com/mozilla/bedrock/issues/9161 as it introduces new copy

**Comment by amychurchwell** [comment]
Looks like the fluent migration has been merged, so this work can be triaged.

**Comment by cgonz0** [comment]
@hoosteeno lgtm
