### ISSUE TITLE
Platform and Yandex download pages are out of date

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9266]
## Description

The following download pages are now on an outdated design:

- https://www.mozilla.org/ru/firefox/new/
- https://www.mozilla.org/en-US/firefox/windows/
- https://www.mozilla.org/en-US/firefox/mac/
- https://www.mozilla.org/en-US/firefox/linux/

I'm not entirely sure what the best course of action is for these pages, as we repeat updating them every 6 months or so after the main download page gets redesigned.

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "the new design is done and approved, live on the page"

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by alexgibson** [comment]
@hoosteeno any thoughts here - is this something we could perhaps work into https://github.com/mozilla/bedrock/issues/9224 ?

**Comment by stephaniehobson** [comment]
Looking at this as part of #9224

At the moment these pages have the download button on them that swaps out for android, ios, etc if the user is on mobile. I'm going to change that to be just the desktop download link, unless anyone objects.

I'd also suggest adding /ios and /android versions of the platform templates. These can display at /mobile/ios and /mobile/android and serve as evergreen fallbacks for whatever we end up building out there eventually. @rraue Thoughts on adding these pages?

**Comment by stephaniehobson** [comment]
I'm going to investigate the yandex page as part of https://github.com/mozilla/bedrock/issues/9883

**Comment by stephaniehobson** [comment]
Looking at this as part of #9224

At the moment these pages have the download button on them that swaps out for android, ios, etc if the user is on mobile. I'm going to change that to be just the desktop download link, unless anyone objects.

I'd also suggest adding /ios and /android versions of the platform templates. These can display at /mobile/ios and /mobile/android and serve as evergreen fallbacks for whatever we end up building out there eventually. @rraue Thoughts on adding these pages?

**Comment by stephaniehobson** [comment]
Suggested title, description, and page heading for the new platform pages: https://docs.google.com/document/d/125FFxytmY_FUlAxiyLHp1-FqR0Jy0KCls_8kl9KEb38/edit (Mozilla only link)

@rraue I'd like your take on this before I talk to Tyler and legal.

**Comment by stephaniehobson** [comment]
Looking at this with fresh eyes I'm not sure I need to change the language on the platform pages. I think they can continue with their current ftl files.

**Comment by rraue** [comment]
That would give us the landing pages and we can iterate on them for Tier 1 and have directly a fallback. That would be great. We have the mobile banner and we should add it to the pages, as I agree the button on that page should be desktop only but that way there is a path to get them on mobile as well.

I need access to the title doc, as the descriptions are a bit too long and I have a suggestion

**Comment by alexgibson** [comment]
I think this was covered in https://github.com/mozilla/bedrock/issues/9224
