### ISSUE TITLE
Get new TrafficCop into Bedrock

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9290]
## Description

TrafficCop has an important bug fix (the ability to distribute fractionally) but hasn't been pulled into Bedrock since that capability was merged. We should bring the latest version in.

---

#### Success Criteria
- [ ] Latest TrafficCop is included in Bedrock

**Comment by alexgibson** [comment]
There’s already an issue and pull request for this. Closing as a duplicate of https://github.com/mozilla/bedrock/issues/9209
