### ISSUE TITLE
Design - Moments 4 page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9299]
Update the moments 4 page for Daylight promotion.

#### Success Criteria
- update hero img background colors to reflect current fenix color direction
- include new ios and android devices and screenshots, focused on privacy
- update icon for 3rd bucket
- copy changes

#### Approvals

- [ ] Team Lead - Hoosteeno
- [ ] Lisa W as the original requestor and drafter of the experiment

**Comment by hoosteeno** [comment]
The copy doc for this is here: https://docs.google.com/document/d/1sNcLHvK2d0E9OOjQYsJTsNWp3NBVw3csgEs1rjFKNGs/edit

@cgonz0 can you update on status for images?

**Comment by cgonz0** [comment]
here's an initial mock for the updates ~
-updated the hero img background colors to reflect current fenix color direction
-includes both ios and android devices and screenshots, focused on privacy
-updated icon for 3rd bucket
-copy changes are also reflected here

![welcome 4.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/948c82dd-3350-4df5-9ec0-84bbbbd7f70c)

**Comment by hoosteeno** [comment]
These are not final -- awaiting approval by studio team. @cgonz0 please update here when that's done.

**Comment by amychurchwell** [comment]
@cgonz0 @hoosteeno are these assets final? 8/28 is the deadline for code.

**Comment by cgonz0** [comment]
@amychurchwell these are the final assets

**Comment by hoosteeno** [comment]
@cgonz0 @amychurchwell We've been asked to bring these designs to Marketing standup Thursday for final review. It's possible we will get some feedback there that will change direction. So let's hold off, and assume the date on the code card will change.

**Comment by cgonz0** [comment]
@amychurchwell 
updated assets [assets_welcome4.zip](https://app.zenhub.com/files/1616665/e5ec07a4-d838-4508-8eb4-555ab41f0fe8/download)
gradient: `background-image: radial-gradient(circle at 60% 100%, #FFA437 5%, #E74549 94%);`

![welcome 4 v2.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/03d07b5d-049b-4037-887c-bd2671662ce2)
