### ISSUE TITLE
Thunderbird privacy notice template update

### ISSUE THREAD

**Issue by litkaemily** [mozilla/bedrock#9300]
Hi, 

I'm working on publishing an update to the Thunderbird privacy notice. It hasn't been updated since 2011. Can I request for the template to be updated to be consistent with our other privacy notices?

For reference, here's the Thunderbird notice (https://www.mozilla.org/en-US/privacy/thunderbird/) and here's the Firefox notice (https://www.mozilla.org/en-US/privacy/firefox/).

Thanks, 
Emily

**Comment by alexgibson** [comment]
Looks like this was done
