### ISSUE TITLE
ESR 78 releases not showing up on https://www.mozilla.org/en-US/firefox/releases/

### ISSUE THREAD

**Issue by mkaply** [mozilla/bedrock#9318]
On the page https://www.mozilla.org/en-US/firefox/releases/

If you look at 68, it lists all the ESRs

If you look at 78, it's missing 78.1.

**Comment by pmac** [comment]
Sorry I missed this. I'm looking into it now. It seems to be due to how the site tries to figure out which releases are ESR for history purposes.

**Comment by pmac** [comment]
Ah! It's because of this:

https://github.com/mozilla/bedrock/blob/9546aabcbcbf046f2fe52d00c447f723a414240e/bedrock/releasenotes/views.py#L160-L164

The site is trying to find an ESR release every 8 releases since Fx 60 and it seems that's no longer the cadence.

**Comment by pmac** [comment]
Not sure why we have to do that since every ESR and dot release is in https://product-details.mozilla.org/1.0/firefox_history_stability_releases.json

**Comment by mkaply** [comment]
We actually had similar code in Firefox that had to be worked around as well...

**Comment by pmac** [comment]
The fix has been deployed to our [dev server](https://www-dev.allizom.org/en-US/firefox/releases/) and it's looking good. Let me know if you see any more issues and I'll fix them in a follow up.

**Comment by pmac** [comment]
This is now in prod and looks good to me. Thanks again for the nudge, and for your patience. https://www.mozilla.org/en-US/firefox/releases/

**Comment by mkaply** [comment]
Thank you!
