### ISSUE TITLE
JS error on /contact/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9322]
## Description

```
Uncaught TypeError: can't access property "setAttribute", e is null
    <anonymous> https://www.mozilla.org/media/js/BUNDLES/contact-spaces.8c743e70c527.js:1
    <anonymous> https://www.mozilla.org/media/js/BUNDLES/contact-spaces.8c743e70c527.js:1
```

### Steps to reproduce

1. Visit https://www.mozilla.org/en-US/contact/
2. Open the web console.

### Expected result

No error reported

### Actual result

It looks like the error is being thrown by `protocol-sidemenu.js`, which is used on the sub pages but not the landing page. Removing the bundle from the landing page may be all that's needed:

https://github.com/mozilla/bedrock/blob/master/media/static-bundles.json#L1092-L1097

### Environment

Firefox Nightly

**Comment by fazer1929** [comment]
I will like to work on this issue.

**Comment by imskr** [comment]
I am taking this issue!
