### ISSUE TITLE
Sign in/sign up links in footer have malformed styling on some pages

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#9327]
## Description
The "sign in" and "sign up" links in the footer are getting some added styling from the FxA form on any page where that form appears. This seems due to the reocurring class name `fxa-signin` in the footer, but the same name styles the "already have an account?" link in the form to set the small font size. The /firefox/products/ page also adds a top margin.

![image](https://user-images.githubusercontent.com/205591/91232634-5454d880-e6e4-11ea-8858-c8100f1ec543.png)

The simplest fix is probably to change the class in either the FxA form or in the footer to something more unique.

**Comment by stephaniehobson** [comment]
Careful that some JS is not relying on those classes too.

**Comment by soulhunter10737** [comment]
How it should look like?
