### ISSUE TITLE
Update leadership page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9332]
## Description

We need to update Leslie Gray's entry on the leadership page. 

Bio: https://docs.google.com/document/d/1wdaWXeL6WSikjedAozvl4GOBxt4BROBpyEWG3gI49tQ/edit

New photo: 
![leslie_gray_mozilla_](https://user-images.githubusercontent.com/94519/91321864-510d2b80-e77c-11ea-8178-0e051f8e9a9d.jpg)

---

#### Success Criteria
- [ ] Changes described above are merged and live

**Comment by craigcook** [comment]
The link to the photo isn't working. Can you attach it here?

**Comment by hoosteeno** [comment]
> The link to the photo isn't working. Can you attach it here?

Attached. Will that work?

**Comment by craigcook** [comment]
That works. That's also the current photo so I think this is just some minor edits to the bio.

**Comment by hoosteeno** [comment]
It's not the current photo because it's been cropped differently.

**Comment by craigcook** [comment]
ah, got it
