### ISSUE TITLE
Epic: Multi-variant convert test on homepage Firefox Daylight promo banner

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9339]
## Description

We should test different variations of the recent promo banner to advertise the Firefox Daylight mobile browser.

![image](https://user-images.githubusercontent.com/30483988/91476055-4f616780-e851-11ea-9d0c-52139d1126e7.png)

[Promo banner issue](https://github.com/mozilla/bedrock/issues/9302)

---

#### Issues
- [ ] [Design](https://github.com/mozilla/bedrock/issues/9340)
- [ ] Code: #9341

**Comment by amychurchwell** [comment]
Since we no longer have a dedicated data science resource, I would suggest borrowing segmentation from previous en-US homepage tests and make a decision based on what convert determines is a winning variation.

**Comment by alexgibson** [comment]
I don't believe this is still being worked on, but feel free to reopen.
