### ISSUE TITLE
Epic: Launch WNP81 by 9/2

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9342]
## Description

We will want to market Daylight on WNP81. This is an epic that will include the tasks associated with launching WNP81. We need to anticipate a long weekend from 2020-09-03 to 2020-09-7: So we should try to launch by EOD 9/2.

Epic issues to come.

---

#### Issues
- [x] #9343
- [x] #9344

**Comment by hoosteeno** [comment]
Release bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1661585

**Comment by craigcook** [comment]
The page went live on 9/2: https://www.mozilla.org/firefox/81.0/whatsnew/all/
