### ISSUE TITLE
Remove macOS download attribution script?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9346]
## Description

We have a macOS download attribution script that was added some 2 years ago here: https://github.com/mozilla/bedrock/blob/master/media/js/base/stub-attribution-macos.js

As far as i know, attribution for macOS downloads has never worked fully - and I don't know of any plans to get that working. I don't think it serves us any favors to keep on maintaining and shipping dead code. If this is not being used, there's always Git history to recover things later.

---

#### Success Criteria
- [ ] macOS attribution script is removed from the repo.

**Comment by alexgibson** [comment]
It looks like the script is behind a switch: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/new/desktop/download.html#L507-L509

Which seems to have never been enabled: https://github.com/mozmeao/www-config/blob/master/waffle_configs/bedrock-prod.env

**Comment by alexgibson** [comment]
@hoosteeno any objections to removing this?

**Comment by hoosteeno** [comment]
I've asked mkaply to weigh in on this.

**Comment by rtestard** [comment]
@tublitzed Can you please weigh in there?

**Comment by tublitzed** [comment]
@alexgibson actually, can you hold off here? @ncalexan is actively working on getting macOS attribution working now. See [1619353](https://bugzilla.mozilla.org/show_bug.cgi?id=1619353) for details.

**Comment by alexgibson** [comment]
@tublitzed if this is being worked on then great. Please keep us updated, and let us know if you need anything on our side. 

The script I linked above has never been enabled in production, so if you still plan on utilizing it (?) then we'll likely need to test things on stage first.

**Comment by tublitzed** [comment]
Sounds good! I'll loop back in here when we're ready to test (see [PI-781](https://jira.mozilla.com/browse/PI-781)) and we can determine at that time if we need/want to keep this or not, and if so we can plan on testing it then.

**Comment by alexgibson** [comment]
@tublitzed it's been a while since we looped back on this. Is the script here in question still needed?

**Comment by tublitzed** [comment]
@alexgibson - go ahead and remove. Thanks for flagging!
