### ISSUE TITLE
Stub attribution is not being applied in old IE browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9350]
## Description

The stub attribution script is running in older Ie browsers, however the signed attribution code is not being applied to the download URL, due to the way old IE browsers have a different triggering mechanism for the download:

https://github.com/mozilla/bedrock/blob/master/media/js/ie/mozilla-utils-ie.js#L27-L37

### Steps to reproduce

1.) On IE 9 or below, visit https://www.mozilla.org/firefox/new/
2.) Click download Firefox

### Expected result

Stub attribution params should be attached to the file download URL

### Actual result

No params are attached.

### Environment

Windows 7, IE9

**Comment by alexgibson** [comment]
@hoosteeno is this something we care about re: dark funnel? Supporting these old browsers is non trivial for things like stub attribution long term, but it's possible to fix this without too much work (short term).

Happy to take whichever direction you think makes sense here.

**Comment by hoosteeno** [comment]
IE <= 9 is appx. .62% of visits, but almost 6% of desktop downloads. I think we should fix it.
