### ISSUE TITLE
Copy change: Daylight banner

### ISSUE THREAD

**Issue by kellymj** [mozilla/bedrock#9351]
## Description

Change headline copy on the orange Firefox for Android banner:

OLD: Introducing our latest release of Firefox for Android — Firefox Daylight.
NEW: Introducing the NEW Firefox for Android — Firefox Daylight

Note, there is no period at the end of the line

---

#### Success Criteria
- [ ] Copy is updated
 
![image](https://user-images.githubusercontent.com/16907385/91618581-99c11200-e93f-11ea-9bd6-bb59bf61ead3.png)

**Comment by DeekshithSuresh** [comment]
can i resolve this one sir.
