### ISSUE TITLE
Firefox Channel Page: Firefox for Android titles being used in Firefox Desktop page

### ISSUE THREAD

**Issue by petercpg** [mozilla/bedrock#9352]
## Description
In Firefox Channel Page, page `<title>` and `og:title` for Firefox for Android is being used in Desktop page. Not sure if this is intended but only mentioning Android is a bit of ambiguous when I was actually Googling up for Nightly Desktop download.

I do also notice there is a fallback string in https://github.com/mozilla/bedrock/blob/a7c63bde02a71d54cd980a4322f47319b6f7c4e6/l10n/en/firefox/channel.ftl#L16

Maybe we could use this line for a general title?

### Steps to reproduce
1. Open [Firefox Channel Page](https://www.mozilla.org/en-US/firefox/channel/desktop/)
2. Check rendered page source code for title and og:title

### Screenshots
Desktop
![圖片](https://user-images.githubusercontent.com/205738/91684817-23b0eb00-eb8b-11ea-9765-b3b5aef8b23a.png)
Android
![圖片](https://user-images.githubusercontent.com/205738/91684872-493df480-eb8b-11ea-8b6d-21e27f10598e.png)
iOS
![圖片](https://user-images.githubusercontent.com/205738/91684920-64a8ff80-eb8b-11ea-9437-8639aab72f0f.png)

### Expected result

1. For each platform (Desktop, Android, iOS), the page should use its own `<title>` and `<meta>` contents, and being extracted to strings respectively

### Actual result

1. The Firefox for Android variant of `<title>` and `<meta> og:title` are being used in Firefox Desktop page.
2. Correct Firefox Desktop variant `<meta>` description and og:description are being used.
3. Android and iOS page have correct contents in all `<title>`, `<meta> description`, `og:title`, and `og:description`.

### Environment

Firefox 82/Windows 10. This impacts all environments.

**Comment by alexgibson** [comment]
Thanks for reporting 👍
