### ISSUE TITLE
Deploy latest Protocol to Bedrock

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9357]
## Description

The latest version of Protocol includes some features (e.g. the sticky card) that we want to use on Bedrock. We should put the latest version of Protocol on Bedrock.

---

#### Success Criteria
- [ ] The latest version of Protocol is merged into Bedrock and deployed on live production site.

**Comment by maxxcrawford** [comment]
The [new version](https://www.npmjs.com/package/@mozilla-protocol/core/v/12.1.0) has been deployed to NPM. (S/O to @stephaniehobson! 👋 )
