### ISSUE TITLE
Comparison table on /new includes inaccurate info

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9359]
## Description

The comparison table on our download page says Chrome blocks 3rd party cookies:

![Screen Shot 2020-09-01 at 3 33 35 PM](https://user-images.githubusercontent.com/94519/91908299-90e67e00-ec68-11ea-816d-a7865de87e81.png)

This is only true under certain circumstances -- i.e. in incognito mode. We should be clearer about this comparison. We should add the words "by default" to the end of the comparison, and change the checkmark under Chrome to the "false" symbol:

![Screen Shot 2020-09-01 at 3 35 58 PM](https://user-images.githubusercontent.com/94519/91908487-defb8180-ec68-11ea-8897-63ce394f7e06.png)

**Comment by craigcook** [comment]
If we're changing it to be explicitly "by default" we may need to check against all the other browsers as well, since we state they all block third-party tracking cookies but I don't think they all do so by default. And we should make the same updates to the comparison pages under https://www.mozilla.org/firefox/browsers/compare/

**Comment by arthuredelstein** [comment]
> If we're changing it to be explicitly "by default" we may need to check against all the other browsers as well, since we state they all block third-party tracking cookies but I don't think they all do so by default. And we should make the same updates to the comparison pages under https://www.mozilla.org/firefox/browsers/compare/

Great point! Safari and Edge do block third-party tracking cookies by default.

**Comment by TanviHacks** [comment]
I don't think adding "by default" is necessary.  You could simply uncheck the box for Chrome on https://www.mozilla.org/en-US/firefox/new/ and on https://www.mozilla.org/en-US/firefox/browsers/compare/.  

On https://www.mozilla.org/en-US/firefox/browsers/compare/, you can also doublecheck Opera and IE to see what the default is.  If they don't block third party tracking cookies by default, you can uncheck them too.

**Comment by skrelnick23** [comment]
It's behind a pref in Chrome and is available for GA users, so fine to uncheck but we should indicate in fine print somewhere that the comparison is for on-by-default features.

**Comment by hoosteeno** [comment]
Rather than add new qualifying copy in fine print, perhaps we should just add "by default" to the factor.
