### ISSUE TITLE
Inconsistent Terminology: 'Master Password' vs 'Primary Password'

### ISSUE THREAD

**Issue by ViralTaco** [mozilla/bedrock#9368]
## Description

Inconsistent terminology between: 

1. mozilla.org/en-US/firefox/new/#compare-table
2. Privacy Preferences (Firefox 80) `about:preferences#privacy` in the Logins and Password section. 

The expression "Master Password" is used in the former, "Primary Password" in the latter. 

I believe [this line](https://github.com/mozilla/bedrock/blob/f6773149072b7e5bd72f6db93f84fcc6bc89a235/l10n/en/firefox/browsers/compare/shared.ftl#L30) is responsible for that, however I'm not familiar with the tooling used… 
So, unless someone can guide me through the steps, I'll be unable to make a pull request. 

### Steps to reproduce

Visit [the Browsers page](https://www.mozilla.org/en-US/firefox/new/#compare-table).

### Expected result

A consistent one.

### Actual result
![Browsers Page](https://i.ibb.co/NN9qfGh/image.png)
![Preferences](https://i.ibb.co/CnkFLyj/image.png)

### Environment

N/A

PS: Not quite sure how to add the "help wanted 👋" label 😕

**Comment by alexgibson** [comment]
It looks like this has since been fixed. Thank you for filing

![image](https://user-images.githubusercontent.com/400117/104164069-4a134c80-53ef-11eb-910d-b3f89568dab6.png)
