### ISSUE TITLE
Update compare hub and tables

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9378]
## Description

Tyler will provide copy and comparison page changes which will be attached to this bug.

---

#### Success Criteria
- [ ] Changes are specified in a doc attached to this issue, reviewed by The Studio
- [ ] Changes are made in live pages (compare pages + download page)

**Comment by hoosteeno** [comment]
Change doc here: https://docs.google.com/document/d/1Wc-DqtF2tDgPeYliYTDKITIeXiThRZ8k6373oxjwJsY/edit

Compare table changes: https://docs.google.com/spreadsheets/d/1dyxx-M27jpit4RKStXxR54kkBN1sa9Tbca2a8MionKc/edit#gid=1512926430

**Comment by skrelnick23** [comment]
Give me 1 more day with the documents above. Need fresh Monday brain for additional review and my afternoon cleared up!

**Comment by skrelnick23** [comment]
We are good to go. Thank you
