### ISSUE TITLE
Epic: Build a moments page for Election 2020 (OCT)

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9386]
## Description

We want to land a moments page that will alert audiences to a collection of non-partisan election information that we will curate on Pocket. This epic will contain the work associated with that.

Notes:
* It will target US geography, and can be en-US only
* It could live at a different URL than the Welcome pages, if there are no objections to opening a moment page at a different URL (e.g. https://www.mozilla.org/en-US/election2020/). But this is not a requirement.
* As with all moments pages, it will not be indexed or linked in upstream channels
* It should use the default Moments template. 

---

#### Issues
- [ ] #issue-number
- [ ] #issue-number

**Comment by alexgibson** [comment]
Outdated issue
