### ISSUE TITLE
Update "Contact Mozilla" on https://www.mozilla.org/en-US/privacy/

### ISSUE THREAD

**Issue by litkaemily** [mozilla/bedrock#9388]
I recently tried to update the [Mozilla Privacy Policy](https://www.mozilla.org/en-US/privacy/) through Github and noticed that the "Contact Mozilla" section at the bottom of the page (screenshot attached) wasn't part of the document in Github.

I'd like to add the following after the sentence "See here for Data Subject Access Requests." "If you are under 13, we don't want your personal information, and you must not provide it to us. If you are a parent and believe that your child who is under 13 has provided us with personal information, please contact us to have your child's information removed."

So, the whole thing reads as:

"[See here for Data Subject Access Requests.](https://app.onetrust.com/app/#/webform/4ba08202-2ede-4934-a89e-f0b0870f95f0) If you are under 13, we don't want your personal information, and you must not provide it to us. If you are a parent and believe that your child who is under 13 has provided us with personal information, please [contact us](https://www.mozilla.org/privacy/#contact) to have your child's information removed."

cc @alexgibson

**Comment by litkaemily** [comment]
@mafeld for visibility

**Comment by litkaemily** [comment]
Hi, I'm following up on this. Is there any additional steps that I should take. 

Thanks, 
Emily

**Comment by craigcook** [comment]
Sorry, I think we just overlooked this issue. Thanks for the ping to remind us! We'll get it done ASAP.

**Comment by litkaemily** [comment]
No worries! Thank you!

**Comment by litkaemily** [comment]
Hi is there any update to this? I also need to make an additional update to this section now. It should read:
------

If you want to make a correction to your information, or you have any questions about our privacy policies, please get in touch with: 

Mozilla Corporation
Attn: Mozilla – Privacy
2 Harrison St # 175,
San Francisco, CA 94105
USA
compliance at mozilla dot com 

[See here for Data Subject Access Requests](https://app.onetrust.com/app/#/webform/4ba08202-2ede-4934-a89e-f0b0870f95f0). If you are under 13, we don't want your personal information, and you must not provide it to us. If you are a parent and believe that your child who is under 13 has provided us with personal information, please contact us to have your child's information removed.

For product support requests, please [visit our forums](https://support.mozilla.org/).

**Comment by craigcook** [comment]
@litkaemily Sorry this took so long! It's finally complete and will go live in our next deployment on Monday 8 February. Meanwhile you can see the changes at https://www-dev.allizom.org/privacy/
