### ISSUE TITLE
Update strings in welcome/4 ASAP

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9394]
## Description

A mix up caused the wrong strings to go into the welcome/4 page. We need to get the correct strings in that page as soon as possible so l10n can reset. A creative team member will attach new strings to this issue.

---

#### Success Criteria
- [x] A single canonical source of strings is attached to this issue -- and allows for no confusion about what should happen
- [ ] New strings are in code & merged
- [ ] l10n is notified

**Comment by craigcook** [comment]
Updated canonical copy: https://docs.google.com/document/d/1GrdzXS0n6h9-YYxwQiRskCuFasplIx5EDvHouo5fF2w/edit

[new hero headline] 
Now get privacy on every screen

[new hero subhead]
Your privacy is on by default with the new Firefox for Android — and now you can make Firefox your default browser on iOS 14.

[new CTA text for both buttons]
Get Firefox Mobile

[new headline for last bullet - focused on task completion: replaces “Take it all with you” section]
Go faster. Do more.

[new subhead for last bullet - focused on task completion: replaces “Take it all with you” section]
Get more done in your day with lightning-fast page loads and smart search suggestions.

**Comment by maxxcrawford** [comment]
> [new CTA text for both buttons]

Does that mean:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2692333/92962628-d5c39f00-f436-11ea-91e0-ecc23fffc02d.png">

<img width="332" alt="image" src="https://user-images.githubusercontent.com/2692333/92962630-d65c3580-f436-11ea-9282-569d74350cc1.png">
