### ISSUE TITLE
Research/Implement Smartling Connections

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9403]
## Description

The l10n team has a partnership with Smartling for orchestration, and on the Bedrock side we may have some small work to do integrating with Smartling. This issue has 3 deliverables:

---

#### Success Criteria
- [ ] research/identify the proper implementations of integration; comment or attach
- [ ] implement/integrate
- [ ] identify questions/issues requiring subsequent work

**Comment by amychurchwell** [comment]
RRA is currently being revised for bedrock staging environment by operations security engineering.

**Comment by amychurchwell** [comment]
Smartling has passed security review. Moving forward the l10n team is going to leverage the existing Smartling Chrome extension, so there is currently no bedrock dev tasks for us.
