### ISSUE TITLE
Epic: Update /thanks page for Win10 users

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9407]
## Description

We want to notify Win10 users that they may encounter a hostile interruptive advertisement from their operating system, attempting to dissuade them from installing Firefox. We will try to help them navigate that interruption. In the near term, the /thanks page is the best place for this messaging. The tactic is briefly described in [this deck.](https://docs.google.com/presentation/d/1CtngldldZ4ZDNx5YzxLtvDyx2906DYwVj5k3p6AFDMo/edit#slide=id.g967f3f3deb_0_12)

---

#### Issues
- [ ] #9409
- [x] #9410
- [ ] #9411

**Comment by hoosteeno** [comment]
Here is the dialog that users will see after downloading, when they try to run the installer:

![image (7)](https://user-images.githubusercontent.com/94519/93396709-5585ab00-f835-11ea-86b7-012b0833fca4.png)

If they choose to "Change my app recommendation settings >" they will get a dialog like this:

![image (9)](https://user-images.githubusercontent.com/94519/93396796-78b05a80-f835-11ea-8942-8ae34f301548.png)

This is all part of an overall attempt to prevent people finding & choosing our browser -- e.g, if you search in Bing for Firefox, there's a banner on the search results like this:

![Screen Shot 2020-09-16 at 3 51 09 PM](https://user-images.githubusercontent.com/94519/93396860-a09fbe00-f835-11ea-95c4-12b2fdcadac1.png)

**Comment by hoosteeno** [comment]
We're not the only ones: 
* [Zoom](https://support.zoom.us/hc/en-us/articles/115004123963-Installing-Zoom-on-Windows-10-Creators-Update). 
* [Brother](https://help.brother-usa.com/app/answers/detail/a_id/149171/~/your-pc-settings-only-let-you-install-verified-apps-from-the-store-when)
* [Taxact](https://www.taxact.com/support/25504/2019/simplified-installation-procedure)

**Comment by justinkropp** [comment]
From Dan Brown:

> curious what you think is the best approach here:
> - Lay most of the steps (including screenshots) out on the /thanks page (and include link to SUMO for more details)
> - raise the issue on the /thanks page but send users to SUMO page for steps/walkthrough/screenshots

**Comment by justinkropp** [comment]
I’m leaning towards your the approach. That feels like the least disruptive/overwhelming for the user; but I could see some value in giving a bit more instruction on the /thanks page before presenting the user with a link for SUMO

**Comment by vtay29** [comment]
I would like to see the difference between what would show up on /thanks vs SUMO. Ideally, I would rather not send them out to SUMO coz we might lose them in the process. If we can have a summarized set on instructions, that would be the ideal.

**Comment by hoosteeno** [comment]
SUMO can contain great detail about how to change the global setting to avoid these dialogs permanently. It can talk about the anticompetitive context. And it will reach people searching for this issue -- many will do so, but the /thanks page is not indexed. So SUMO must have this content, and we can help people who are seriously confused by sending them there. 

The [design/copy issue](https://github.com/mozilla/bedrock/issues/9410) will start to have ideas in it. I put one idea in there to prime the pump.

**Comment by alexgibson** [comment]
Open question: are we planning to measure the effectiveness of this messaging? Do we need to be confident that we're a) improving the install rate for those who do need to change the setting, and b) not hurting the install rate for those who don't need it by showing irrelevant messaging? Or is this change considered small and non-distracting enough that we're confident in rolling it out as is?

I have no strong opinions here, just want to make sure we're thinking about the questions.
