### ISSUE TITLE
Win10 downloaders on /thanks: Get a SUMO article to link to

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9409]
## Description

This issue is part of the #9407 epic.

We should find or help get a page written on SUMO with detailed install instructions for people on Windows 10, similar to Zoom, Brother and Taxact (see #9407). 

---

#### Success Criteria
- [ ] Link to SUMO is below and added to the /thanks experience for Win10 users

**Comment by slightlyoffbeat** [comment]
I started on a doc that has a first pass at an article, along with fresh screenshots. 

@justinkropp this could use some very slight edits to the photos to highlight actions. Take a look at the doc and let me know what you think: 

https://docs.google.com/document/d/1x_oAWAf6SifJzdX5dHIm1x9CkpCcD5dmdPtizbP38NM/edit?usp=sharing

**Comment by slightlyoffbeat** [comment]
@hoosteeno for your review: https://docs.google.com/document/d/1x_oAWAf6SifJzdX5dHIm1x9CkpCcD5dmdPtizbP38NM/edit?usp=sharing

**Comment by justinkropp** [comment]
@slightlyoffbeat Can you send me the screenshots? I'll update the images accordingly and can either add here or send directly.

**Comment by slightlyoffbeat** [comment]
@hoosteeno screens to use: https://drive.google.com/drive/folders/1xWUbmJjzqSr9CPtQqK_6h4kglVKXzQeE?usp=sharing

**Comment by slightlyoffbeat** [comment]
@hoosteeno has submitted copy to legal for review

I also submitted the SUMO article for review by the SUMO team.

**Comment by slightlyoffbeat** [comment]
@hoosteeno @craigcook SUMO article has been approved and is live:

https://support.mozilla.org/en-US/kb/windows-10-warns-me-use-microsoft-verified-app
