### ISSUE TITLE
Win10 downloaders: Design and copy for a new /thanks experience

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9410]
## Description

This issue is part of the #9407 epic.

We need copy and design for a new /thanks experience for Win10 users. 

---

#### Success Criteria
- [x] Copy and designs attached to this issue.

**Comment by amychurchwell** [comment]
(x-post from slack)
Install experience for an Edge user on Windows 10:

1. Visitor lands on /firefox/new/
2. Clicks download Firefox
3. Page navigates to /download/thanks/
4. File download begins
5. File download ends
6. Visitor double clicks .exe to open installer
7. Verified app message / warning is displayed

**Comment by amychurchwell** [comment]
Considering that the pop-up occurs when a user clicks .exe, perhaps we could explore a instructional pop-up of our own after clicking download. Similar to how some software prompts users to allow permissions before the OS asks.

**Comment by alexgibson** [comment]
One thing that may be worth some careful consideration  here, is that we have no real idea who on Win10 has the recommended app setting enabled. Say for example, if 20% of Win 10 users have it enabled, then we want to avoid showing a distracting and potentially confusing message to the other 80%. Unless we have data that demonstrates a high proportion of users have the setting enabled, striking a fine balance could be really important here. We don’t want to improve the install rate for one audience whilst harming it for the other at the same time.

If a pop up may be too distracting, an in page message / link to SUMO, similar to the existing “Need help installing?” message may be another option.

**Comment by slightlyoffbeat** [comment]
Bringing a slack conversation with @justinkropp here:

me: What you think is the best approach here:
Lay most of the steps (including screenshots) out on the /thanks page (and include link to SUMO for more details)
raise the issue on the /thanks page but send users to SUMO page for steps/walkthrough/screenshots

@justinkropp : I’m leaning towards your second approach. That feels like the least disruptive/overwhelming for the user; but I could see some value in giving a bit more instruction on the /thanks page before presenting the user with a link for SUMO

**Comment by slightlyoffbeat** [comment]
My understanding is that the recommended app setting is on by default for Windows 10. Can anyone confirm? If this is the case, we should assume that the majority of users have it enabled.

With that said, we can test down the road to learn about what helps increase (and certainly not decrease) install rate. I think we can have just a few visual elements and a good balance of copy and push the rest to the SUMO article. But I also recommend that we test a variation in the future is a bit more heavy handed with the copy and images.

**Comment by hoosteeno** [comment]
Here's a [McDonald's Idea](https://medium.com/@jonbell/mcdonalds-theory-9216e1c9da7d):

<img width="1107" alt="Screen Shot 2020-09-17 at 10 37 36 AM" src="https://user-images.githubusercontent.com/94519/93501284-76e8a480-f8d2-11ea-9af8-0f535ffb9513.png">

**Comment by alexgibson** [comment]
> My understanding is that the recommended app setting is on by default for Windows 10. Can anyone confirm? If this is the case, we should assume that the majority of users have it enabled.

I believe it depends on the version of Win 10 you're using. I think home edition and "s mode" might be the key here. It doesn't happen on my Win 10 pro mahcine.

**Comment by craigcook** [comment]
If we can only consistently detect Win10 but not specific versions or modes thereof we should probably just show it to all Win10 users and cover our bases with enough "if"s and "mights"s in the copy.

**Comment by justinkropp** [comment]
@slightlyoffbeat and I spoke about this just now and have an idea for a path forward. 

I think a copy treatment would be the least obtrusive. I am going to work on a light-touch design treatment for a box and block of copy (similar to what @hoosteeno proposed above). It'll be designed to draw the users's attention to it.

I'd like to show this message to **all** WIN10 users.

One question: Can we hide the Confirmation/alert message box at the top of the page for these same WIN10 users?

**Comment by alexgibson** [comment]
> One question: Can we hide the Confirmation/alert message box at the top of the page for these same WIN10 users?

Not quite sure I understand why we’d want to do that? The users in question here do get a download (which the notification is there to support), but they may/may not get the MS message after trying to open the download.

**Comment by slightlyoffbeat** [comment]
There are a lot of things asking for the users attention, including a large green box at the top of the page. That could be a problem if we need to present users with another piece of information that may be necessary to complete installation.

I think the question here is if more Win10 users will be affected by not being able to install because of these default settings vs a failed download. I don't have data, but my guess is the former.

**Comment by justinkropp** [comment]
Here are a couple quick options that we could explore as a solution. Again, pretty minimal design lift, but just enough to hopefully get the users attention (and read):

![thanks WIN10@2x-1](https://user-images.githubusercontent.com/1461798/93507461-bc659b80-f8eb-11ea-8f64-7c6dc4423364.jpg)

----

![thanks WIN10@2x](https://user-images.githubusercontent.com/1461798/93507467-bf608c00-f8eb-11ea-8fa2-f7c67eb91ef3.jpg)

**Comment by alexgibson** [comment]
> There are a lot of things asking for the users attention, including a large green box at the top of the page. That could be a problem if we need to present users with another piece of information that may be necessary to complete installation.

If the problem is the bar is too big and too green, then we should preserve the link somewhere else or present it differently. It’s the last lifeline to getting a download should something go wrong, so arguably one of the most important things on the page imho.

**Comment by slightlyoffbeat** [comment]
@justinkropp Looks good. My vote is for the second one, but perhaps then we can get rid of the "WIN10 Users:" part. I'm going through the process right now on my virtual machine, so I can help with copy adjustments in a bit.

**Comment by justinkropp** [comment]
> but perhaps then we can get rid of the "WIN10 Users:" part

👍

**Comment by hoosteeno** [comment]
Let's go with the 2nd one. Agree we can drop the "Win10 Users" from the copy, if we keep it in the icon. Looks great! Thanks.

**Comment by hoosteeno** [comment]
We need to anticipate some users will not have "Install anyway". Suggested modification:

----

~Win10 Users:~ If you see a prompt stating the app you're trying to install isn't a Microsoft-verified app, click "**Install anyway**" or [change system settings](#).

[Visit Support for More Details](#)

----

The inline link would be the same link as the SUMO link below. 

@justinkropp can you make this modification to spec so we can get to coding? Or, share source docs so I can do it?

**Comment by justinkropp** [comment]
@hoosteeno Here's the an updated visual spec to reflect the above:


![thanks WIN10 FINAL@2x](https://user-images.githubusercontent.com/1461798/93617103-897ede80-f9a3-11ea-863e-7aae1d850de7.jpg)

**Comment by hoosteeno** [comment]
I'm going to run past legal for final review.
