### ISSUE TITLE
Update banner on mozilla.org website

### ISSUE THREAD

**Issue by kellymj** [mozilla/bedrock#9412]
## Description
With Firefox for iOS daylight coming out on 9/22/20, we want to update the Daylight banner to include iOS in copy and imagery.

I'll deliver copy and assets. The button functionality is fine as it supports mobile users on both platforms.

Banner to replace: ![image](https://user-images.githubusercontent.com/16907385/93398211-06894700-f830-11ea-8c0b-d64967d081c9.png)

---

#### Success Criteria
- [ ] New copy is shipped
- [ ] New visuals are shipped

**Comment by amychurchwell** [comment]
Blocked until we have copy and assets.

**Comment by designerham** [comment]
![fx_hero_daylight-ios_phones](https://user-images.githubusercontent.com/16651498/93650555-ae834980-f9c3-11ea-9f6d-a39df61fc6c9.png)

**Comment by hoosteeno** [comment]
@kellymj Is copy underway? 

Seems like, as a sane fallback, we could just remove "for Android" from the existing string.

**Comment by kellymj** [comment]
> @kellymj Is copy underway?
> 
> Seems like, as a sane fallback, we could just remove "for Android" from the existing string.

I will post it here later today.

**Comment by kellymj** [comment]
New headline copy: 
Meet Firefox Daylight — the latest for Android and iOS

We want to drop the copy between the headline and the button, so it runs with just the headline, button and phone graphic. Thanks!

**Comment by kellymj** [comment]
Hold on changes please. More info coming in. @amychurchwell @hoosteeno

**Comment by craigcook** [comment]
@kellymj Any updates?

**Comment by designerham** [comment]
![image](https://user-images.githubusercontent.com/16651498/94168995-1530b900-fe43-11ea-8e68-8c32980fa1be.png)

**Comment by designerham** [comment]
@craigcook RE: New Firefox for Android and iOS banner

**Comment by kellymj** [comment]
Once updated, this smaller banner can go live with iOS v29, which is scheduled for Oct. 8. I will verify that the release is a solid go when we are closer to that date.

**Comment by kellymj** [comment]
> Is the copy in the above screenshot final and approved? If so we can get strings out for l10n ahead of Oct 8 and get wider coverage, but only if we're confident it won't change again at the last minute.

This is not final copy. I like the thinking about getting the strings out for l10n.

**Comment by meg-trowbridge** [comment]
Here is the latest approved copy: "The NEW Firefox for Android and iOS is here"
