### ISSUE TITLE
Leadership Page Changes

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9414]
## Description

**For Leslie Gray**
Title changes to:
Head of Diversity & Inclusion and Chief of Staff, Office of the CEO

First paragraph changes to:
Leslie is Head of Diversity and Inclusion and Chief of Staff to the CEO of Mozilla Corporation. As Head of Diversity and Inclusion, Leslie is responsible for Mozilla’s global inclusion strategy and programs across our own culture, as shown in our products, and in how we build community beyond Mozilla. Leslie is also responsible for managing business operations for the Office of the CEO and supporting strategic projects on behalf of the Office of the CEO. 

**For Dave Camp**
Title changes to:
Chief, Firefox Products

First paragraph changes to:
As Chief, Firefox Products, Dave Camp is responsible for all product management, engineering, technology and operations in support of Firefox products, services and web platform.

**For Dana Bennett**
Title changes to:
SVP, People Team

First paragraph changes to:
As SVP, People Team, Dana is responsible for all aspects of Human Resources including Talent Acquisition, Learning and Development and Organizational Development.

**Comment by maxxcrawford** [comment]
@hoosteeno For Dave's bio, the second paragraph is: 
> Dave was previously VP of Engineering, Firefox, leading the global team of engineers that build, test, and ship the Firefox family of products and services.

Should this include his now previous role as _SVP, Firefox_

**Comment by hoosteeno** [comment]
@maxxcrawford 

> Should this include his now previous role as SVP, Firefox

No.
