### ISSUE TITLE
Improve performance on the home page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9419]
## Description

The home page is currently getting a score of 55-60% in [Lighthouse](https://www.webpagetest.org/lighthouse.php?test=200917_7M_394578c068377acffcf8220e65965edd), which isn't great. Part of this is due to the way lighthouse scores have recently changed to focus on some new criteria.

There are likely several relatively small things we could do to try and improve the score:

- Improve time to largest contentful paint
  - Try switching to native lazy image loading vs our current JS based solution.
- Reduce cumulative layout shift
  - The banner is really hurting us here as it pops in after JS loads, causing the whole page to jump.
- Optimize image sizes
  - Several are called out as being too large. Could also try some webp?

**Comment by ishantd** [comment]
Hey @alexgibson , I'd like to start working on this issue, since it'll be one of my very first open-source contributions, I may need some guidance.

**Comment by maureenlholland** [comment]
Closing as outdated, we have switched to native lazy loading solution and testing EN/DE/FR/ES homepages with mobile lighthouse audit gives scores from 85-99

That said, the CLS concern on banners is worth another look, tracking in https://github.com/mozilla/bedrock/issues/9824

**Comment by cklim4405** [comment]
> ## Description
> 
> The home page is currently getting a score of 55-60% in [Lighthouse](https://www.webpagetest.org/lighthouse.php?test=200917_7M_394578c068377acffcf8220e65965edd), which isn't great. Part of this is due to the way lighthouse scores have recently changed to focus on some new criteria.
> 
> There are likely several relatively small things we could do to try and improve the score:
> 
> - Improve time to largest contentful paint
>   - Try switching to native lazy image loading vs our current JS based solution.
> - Reduce cumulative layout shift
>   - The banner is really hurting us here as it pops in after JS loads, causing the whole page to jump.
> - Optimize image sizes
>   - Several are called out as being too large. Could also try some webp?
>
