### ISSUE TITLE
French content for Sept landing page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9424]
## Description

Same as https://github.com/mozilla/bedrock/issues/9361 but for French. Fucntionally will be similar to the German page, but with some locale specific messaging.

---

#### Success Criteria
- [ ] French landing page is approved and in production.

**Comment by alexgibson** [comment]
Copy deck (Mozilla only) https://docs.google.com/document/d/1hOTXbLboxRResRGU4CW_nskoQqEobRptRTiCKA_jPaE/edit?usp=sharing

**Comment by alexgibson** [comment]
Git alt text (Mozilla only) https://docs.google.com/document/d/1FHmoeSKRbl1QqH6hpqJD0kmZQP6XE3YgZnJ56TzeRdM/edit?usp=sharing

**Comment by hoosteeno** [comment]
@stephaniehobson to review
