### ISSUE TITLE
Exclude GA from /privacy/thunderbird/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9426]
## Description

https://www.mozilla.org/en-US/privacy/thunderbird/

It looks like this page is being opened in-product by Thunderbird, which creates a lot of noise in GA, and also decreases overall conversion rate for the site as a whole. We already exclude GA from /privacy/firefox/, so perhaps we should consider the same here as well?

---

#### Success Criteria
- [ ] GA is excluded from /privacy/thunderbird/

**Comment by alexgibson** [comment]
Thoughts @hoosteeno @rraue ?

**Comment by hoosteeno** [comment]
Yes, this is a good idea. Not a major priority, but worthwhile.
