### ISSUE TITLE
Launch CRO experiment for native Android banners on /mobile

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9434]
This experiment is already built and has gone through QA in convert. The iOS experiment had a good amount of success, and mobile team is interested in seeing the results of the iOS test.

Steps:
- QA again (its been a while)
- Check that convert is still turned on for mozilla.org
- drive traffic for experiment

**Comment by hoosteeno** [comment]
@amychurchwell to review, turn on traffic.

**Comment by slightlyoffbeat** [comment]
This has been reviewed and is ready to go.

We need a way to funnel EN_US/Android traffic to this site.

**Comment by hoosteeno** [comment]
We need to figure out the best way to launch this. 
* Create server-side experimental features that vary template based on some segment?
* Send all traffic and segment?
* Send a portion of all traffic and segment?
* Client-side redirect via TrafficCop to Convert
* Rebuild in TrafficCop?
* Other?

@alexgibson @slightlyoffbeat @amychurchwell can you huddle and discuss?

**Comment by alexgibson** [comment]
Given that we don't have a good solution right now server-side, I'd wager that @amychurchwell's suggestion of rebuilding this experiment in Traffic Cop might be the path of least resistance to getting this experiment running. The downside of that is we would lose Convert's built in reporting, and instead need to lean on data science for reporting.

**Comment by amychurchwell** [comment]
@slightlyoffbeat @alexgibson considering I am blocked on the CPG migrations, should I pick up porting this experiment over to traffic cop? is requiring data science's support to analyze the results a blocker?

**Comment by slightlyoffbeat** [comment]
I don't think its a blocker. I can check in with data science. Is everything just tracked with events in GA? If so, I think we'll be fine. I'm good to move forward with traffic cop if everyone else is.

**Comment by slightlyoffbeat** [comment]
@amychurchwell do you still have any bandwidth this week for this? Also tagging @hoosteeno for visibility and his thoughts on resourcing.

**Comment by amychurchwell** [comment]
@slightlyoffbeat yes, I can pick this up.

**Comment by hoosteeno** [comment]
This is 80% done, and we should get it out the door.

**Comment by alexgibson** [comment]
@slightlyoffbeat hi, can you please provide some info as to what each test variation should be showing for this experiment? There doesn't seem to be much direction in the test plan in terms of visuals or what each variation should define. Do we have a design doc anywhere?

Also: how should the existing mobile banner factor into this experiment?

![image](https://user-images.githubusercontent.com/400117/102205713-78227100-3ec3-11eb-87dd-77518818122c.png)

Some options:
1. We don't show the existing banner on any variation, nor the control.
2. We show the existing banner everywhere including all variations and control.
3. We only show the existing banner on the control, and don't show it on the variations.

**Comment by alexgibson** [comment]
Ok, managed to find these in Convert:

Mozilla banner:

![image](https://user-images.githubusercontent.com/400117/102220025-2801d980-3ed8-11eb-95f4-8f09726d485f.png)

Native modern banner (no stars):

![image](https://user-images.githubusercontent.com/400117/102220170-5b446880-3ed8-11eb-9c60-d14414078591.png)

Native modern banner (stars):

![image](https://user-images.githubusercontent.com/400117/102220246-7911cd80-3ed8-11eb-957a-432afd235328.png)

Native old banner (stars):

![image](https://user-images.githubusercontent.com/400117/102220346-95156f00-3ed8-11eb-8396-fb384aa3f790.png)

Native old banner (no stars):

![image](https://user-images.githubusercontent.com/400117/102220410-acecf300-3ed8-11eb-9ce5-34dffaf6d19f.png)

**Comment by alexgibson** [comment]
@slightlyoffbeat I'm still tidying things up, but here's a demo of the variations for review:

- https://www-demo1.allizom.org/en-US/firefox/?v=1 (control)
- https://www-demo1.allizom.org/en-US/firefox/?v=2 (mozilla banner)
- https://www-demo1.allizom.org/en-US/firefox/?v=3 (native modern no stars)
- https://www-demo1.allizom.org/en-US/firefox/?v=4 (native modern stars)
- https://www-demo1.allizom.org/en-US/firefox/?v=5 (native dark stars)
- https://www-demo1.allizom.org/en-US/firefox/?v=6 (native dark no stars)

Please let me know if this looks correct? Thanks

**Comment by slightlyoffbeat** [comment]
@alexgibson I checked all the links and they look correct to me. I would hide any additional banners for this test (such as daylight banners, etc). I'd vote to hide it on control as well.

**Comment by alexgibson** [comment]
Will get this moved along to ready for code review today, thanks.

**Comment by alexgibson** [comment]
This is ready for code review.

**Comment by alexgibson** [comment]
This experiment is now running in production
