### ISSUE TITLE
Build a downloads monitoring program

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9442]
Recently on www our download conversion rate dropped by 15% and we didn't noticed. Downloads have been stable as it was just noisy traffic to /privacy/thunderbird/ causing this. Nonetheless, we need a stable monitoring/alarm system that cuts through the noise, giving us a clear picture of how the website www is performing and alarm us if there is any problem.

**Comment by rraue** [comment]
I am looking into some solutions how we could monitor. In general I think to reduce noise we should focus on the following KPIs:
____________________

Filters: 
- non-fx (Exclude Browser = Firefox|Mozilla)
- Exclude direct traffic from /whatsnew/, /firstrun/, /moments/ & /privacy/* (not exclude /firefox/privacy/)
- Exclude all paid traffic 

____________________

Display:

- Yesterday vs average same weekday (avg last 13 month increasing weight on the last 4 weekdays)
- Last 7 days vs average 7 days (avg last 13 month increasing weight on the last 4 weeks)
- Last 28 days vs average 28 days (avg last 13 month increasing weight on the previous 28 days)
- This year to date vs same period last year
-- One view with and one without paid traffic

____________________

Metrics:
- Sessions
- CVR (Goal2)
- Downloads (Goal2)

____________________

Views:
- Tier 1 
- Tier 1 NA & Tier 1 EU
- ROW

**Comment by alexgibson** [comment]
In addition to this I think we should also strongly considering monitoring downloads before it even gets to GA. Case example: [this bug](https://github.com/mozilla/bedrock/issues/9615) was in the wild for 3 months, and lost us many downloads. Yet in GA everything looked fine.

See https://github.com/mozilla/bedrock/issues/9854 for ideas on solutions.

**Comment by rraue** [comment]
Closing this as its no bedrock related work and the pitch wasn't successful.
