### ISSUE TITLE
Update H* Headers on VPN to use Zilla Slab instead of the Metropolis font-family.

### ISSUE THREAD

**Issue by justinkropp** [mozilla/bedrock#9445]
## Description

https://vpn.mozilla.org/ is currently using Metropolis for its headers. Given that VPN is now a Mozilla product, the page should use **Zilla Slab** for all headers on the page. Zilla Slab is the `font-family` used by Mozilla. Metropolis is the font-family used by Firefox. 

---

#### Success Criteria
- [ ] Update all headers on the VPN landing page to use Zilla Slab
- [ ] Design approval from a designer on the websites team

**Comment by alexgibson** [comment]
@justinkropp might this be an issue better suited for the VPN website repo?

**Comment by justinkropp** [comment]
@alexgibson Ah, I thought the vpn website was on bedrock. I searched for the vpn repo and results didn't return anything. Where does that repo live?

**Comment by pmac** [comment]
I believe it's this one https://github.com/mozilla-services/guardian-website

**Comment by justinkropp** [comment]
Doesn't look like that repo exists. I found this one, https://github.com/mozilla-services/guardian-vpn-windows, but that doesn't feel right...

**Comment by craigcook** [comment]
I think it's private.

**Comment by pmac** [comment]
oh. so it is :( We can ask the team where to put issues.

**Comment by justinkropp** [comment]
@pmac We got it sorted out 👍
