### ISSUE TITLE
Implement local Selenium Grid for testing

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/bedrock#9453]
Success Criteria
 - [x] A successful test run of our selenium tests in multiple browsers on local Selenium Grid
 - [x] Easy access to failed test logs
 - [x] Recordings for tests - Opted for having the ability to easily run tests on Saucelabs to get video recordings. For screenshots are available through Gitlab's UI as artifacts.

**Comment by glogiotatidis** [comment]
Note to self:

@pmac had a good idea to send failed tests to Saucelabs to get a second try and video recordings.

**Comment by glogiotatidis** [comment]
My work here is done. We will upgrade the runners for speed on Monday, see https://github.com/mozmeao/infra/issues/1359.

@alexgibson good to close? do you need anything else?

**Comment by alexgibson** [comment]
Good to close, thanks @glogiotatidis 💯
