### ISSUE TITLE
Figure out how to schedule content

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9467]
* test content scheduling in contentful admin
* build any admin or engineering cards that result
* talk through engineering with pmac

**Comment by slightlyoffbeat** [comment]
https://www.contentful.com/developers/docs/tutorials/general/scheduled-publishing/

**Comment by slightlyoffbeat** [comment]
https://www.contentful.com/blog/2020/06/02/tasks-and-comments-supercharge-your-content-approval-workflow/

Somewhat related to the discussion. If we use the built in scheduling feature (which will have something be "published" or possibly "unpublished" at a specific schedule, then the problem shifts a bit:

- we assume that published content is approved, QA'ed, and ready to go live. We can trust that if something is scheduled, then it is ready to go live.
- we instead solve for user permissions. Who can schedule? Who can publish? What's that process? A card has been created for this.

**Comment by hoosteeno** [comment]
Q: If you schedule content in Contentful, does it imply anything about sync engineering?
A: No, when something goes live, it can be pulled from the API, full stop.

**Comment by maureenlholland** [comment]
Scheduled content is available in Contentful and should be responsibility of content creators via publish permissions. Once it is published, it will be treated like any other published content in bedrock's Contentful sync.
