### ISSUE TITLE
Enable rapid demo of pre-publication content

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9468]
When an editor clicks the "preview" button in Contentful, they see a preview of the draft content they were just looking at, in the right place in a live version of the website

* build this capability

**Comment by hoosteeno** [comment]
@pmac will research.

**Comment by pmac** [comment]
My current best proposal for how this should work:

www-dev.allizom.org (dev) will use the preview API to fetch new data that has not yet been "published". This will provide a preview of the proposed home page that can be showed to any stakeholders. 

For instant previewing during development we'll have a different URL (e.g. something like `/en-US/hompage-preview/<content-id>/` or even just `/en-US/?content-id=<content-id>`). This will load the same homepage template but will fetch the content ID (which is passed through by Contentful in the preview button). We can then use the same data processing functions the site uses when loading data updates to load into the db and thus the template will get the same data that it expects normally just the most recent version. 

* This would only be enabled in dev
* This would mean that the only object with previews enabled would be pages
	* If we want to enable previews of layouts or cards we could develop preview URLs specifically for those as well.
