### ISSUE TITLE
Research: Document how to deploy content model changes

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9470]
Answer these:

* How would we make a content model change in Contentful? Can/should we do it in github?
* How would we get that content model change into Bedrock's db? What does that require or imply about Bedrock's content model? 

This requires admin/engineer collaboration.

**Comment by slightlyoffbeat** [comment]
Contentful provides an import and export tool. I recommend we at least use the export tool on a regular basis to back up everything into git:

https://github.com/contentful/contentful-export/

https://github.com/contentful/contentful-import/

Also:

Environments (understanding them, and how we use them) may also be relevant to this discussion. They should be a part of the workflow that is used when creating content model changes.

You can have environments, and environment aliases. An environment can be cloned from any existing environment. 

An environment alias (for example, master) can point to any environment. You can easily change which environment an alias is pointing to. You can also have an alias for staging, QA, dev, etc.

If we want to make a content model change, we could create a new environment, mess around with changes, and then change the master environment alias to point to the new environment once we are confident with the changes.

A few notes from my tests:
- If using just the contentful website, it seems that while all content is identical at the time of cloning an environment it is separate from both content model and entities after that. So if you create a new card in one environment AFTER cloning, it will not appear in the other. 

Contentful mentions migration scripts that can/should be used. This is beyond my understanding, but @pmac perhaps you can look into it? We either can have a migration script that handles everything...or we have a policy that will keep people from creating content while a content model change is in progress. 

Here is a link to read more, as well as a screenshot of the recommended process.

https://www.contentful.com/faq/environments/

<img width="751" alt="image" src="https://user-images.githubusercontent.com/2030656/94600832-5d871700-0247-11eb-808b-41dadfec3b63.png">

**Comment by slightlyoffbeat** [comment]
Although I'm sure that additional best practices will come out during our quick start, we were able to learn about and utilize a few best practices regarding content model changes during the evaluation period.

Closing.
