### ISSUE TITLE
Build content model for homepage

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9471]
* cards
* sections
* reusable chunks of cards (e.g. links or images)
* locales? 

Principle: Optimize editor experience.

**Comment by slightlyoffbeat** [comment]
Content model has been updated. 

Changes include:

- It is now much simpler. One content type: card. This is the type used for all cards of all sizes. 
- All cards must include an image that is, at minimum, 1200 pixels wide and 800 pixels high.
- removed the inline cta option. I was told it is never used.
- there is an image override option for 1:1, 3:2, and 16:9 for small cards. 


Notes from me:
- I ended up not adding an Image XL field. There should just be an agreement that if the card will be used as the large card in the hero, then a large image should be uploaded. At the very least, the minimum image size requirements will at least make sure that the smaller image size is provided.
- the image override options ask for specific image sizes that are listed for 1:1, 3:2, & 16:9 small cards under the high res image sizes. This may not be ideal.
- It isn't always easy to find a 1200x800 minimum image. There was at least one image that I could not find an equivalent...but I think this is for the best and just becomes a part of the process.

**Comment by slightlyoffbeat** [comment]
![image](https://user-images.githubusercontent.com/2030656/94624405-3f331280-026b-11eb-8729-f8c3e4411e65.png)

**Comment by hoosteeno** [comment]
@slightlyoffbeat considering the plan in https://github.com/mozilla/bedrock/issues/9459#issuecomment-701029883, do we need the locale field on _cards_ or on _card groups_? I think it's card groups, or maybe both.

**Comment by slightlyoffbeat** [comment]
@hoosteeno it needs to be on cards. This way when a content editor creates a new group, they can filter to view cards by language.

We could also include a language field for card groups for the same reason, though it probably wouldn't be as useful (although now that I think about it...we might as well)
