### ISSUE TITLE
JS error on /about/leadership/ in IE11

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9478]
## Description

```
TypeError: Object doesn't support property or method 'remove'
```

https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/9686316/?query=is%3Aunresolved

### Steps to reproduce

1.) In IE11 visit https://www.mozilla.org/en-US/about/leadership/
2.) Click on a bio to open a modal
3.) Close the modal by clicking (x)

### Expected result

Modal content should be removed from the DOM on close.

### Actual result

The content is not removed, and an error is thrown instead.

### Environment

IE11, Windows 10

**Comment by craigcook** [comment]
D'oh, `childNode.remove()` isn't supported in IE, but there is a polyfill, or else we can change to the older `parentNode.removeChild()`

https://developer.mozilla.org/docs/Web/API/ChildNode/remove
