### ISSUE TITLE
FAQ Page Content

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9492]
## Description

In https://github.com/mozilla/bedrock/issues/9491 we are building a faq page. This task is for the content.

---

#### Success Criteria
- [x] Final copy attached
- [x] Chad approved

**Comment by rraue** [comment]
Final Copy: https://docs.google.com/document/d/1LAdUXUovciI1N4xNN1lNGmWv-6kdXVunvM7arrGyK-E/edit?ts=5f74df55

**Comment by stephaniehobson** [comment]
Final copy is approved according to the doc
