### ISSUE TITLE
Epic: WNP82

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9494]
Fx82 lands 2020-10-20.

We'll build a WNP for en-only visitors upgrading to Fx82. The WNP will promote VPN. All other locales/versions will get the evergreen fallback or the baseline fallback.

Blueprint: https://docs.google.com/document/d/1gFbkj3Kgb4h7zBDrO99pgXEwriWgMjgO1UkhyhFPY5w/edit#

### Epic Issues
- [ ] Copy
- [x] Design
- [ ] Merged Code

**Comment by hoosteeno** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1668938

**Comment by justinkropp** [comment]
Below is WIP design work.
----

### Default Version
![Light](https://user-images.githubusercontent.com/1461798/95095927-aa606700-06f9-11eb-9991-8ce5c7bd572f.png)

----

### Dark Mode
![Dark](https://user-images.githubusercontent.com/1461798/95095950-b0564800-06f9-11eb-97ba-d4816c1e2f7c.png)

**Comment by justinkropp** [comment]
Updated design for WNP 82. Final.

----

<img width="1312" alt="Light" src="https://user-images.githubusercontent.com/1461798/95213599-fc1df580-07bc-11eb-8a28-100973002d9f.png">

----

<img width="1312" alt="Dark" src="https://user-images.githubusercontent.com/1461798/95213625-03450380-07bd-11eb-903f-73b72a5086f8.png">

**Comment by craigcook** [comment]
Demo URL: https://www-demo4.allizom.org/en-US/firefox/82.0/whatsnew/all/

**Comment by hoosteeno** [comment]
@craigcook to build the geolocation to redirect Chinese visitors to fallback, add tests, and get review.
