### ISSUE TITLE
FAQ page design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9497]
## Description

in #9491 we build a faq page, this issue is the track the design.

---

#### Success Criteria
- [x] Mockup is attached
- [x] Wireframe
- [ ] Chad approved
- [x] Dev knows what to do

**Comment by rraue** [comment]
Mockup: 
![faq design wireframe](https://user-images.githubusercontent.com/36700618/94921639-fcff1080-04b8-11eb-998c-902a1783f5ce.png)

- Above the fold same like /new
- Single Questions wrapped in emphasis boxes (https://protocol.mozilla.org/patterns/molecules/emphasis-box.html)

**Comment by rraue** [comment]
Download button at the end

**Comment by markteater** [comment]
@rraue here's the Desktop version of the FAQ page. I'm including and opened version and a closed version. I wrapped all the questions together in one Emphasis box, but happy to separate them into individual boxes if you'd prefer.
![FAQ Page - Screen XL - 1312 - CLOSED](https://user-images.githubusercontent.com/1934450/95388374-30c6a580-08c0-11eb-8d26-7093da535fd5.png)
![FAQ Page - Screen XL - 1312 - OPEN](https://user-images.githubusercontent.com/1934450/95388355-2ad0c480-08c0-11eb-87b9-bed288ccf599.png)

**Comment by rraue** [comment]
I love it but for the purpose of SEO they need to be open when the page is visited by a user or crawler. @craigcook is this component possible to be open at load?

**Comment by justinkropp** [comment]
@rraue @markteater If I could add a suggestion: If it's better for SEO that all these FAQs be initially open, it might make more sense to just list them as a simple list of FAQs and remove the open/close toggle. I would imagine that a user would be less likely to interact with the FAQ if it's already open.

**Comment by markteater** [comment]
@rraue @justinkropp Here's a simplified FAQ page with the toggles removed. I also added in the "Related questions" to each question if it was in the doc.

![FAQ Page - Screen XL - 1312](https://user-images.githubusercontent.com/1934450/95613950-b9b21e00-0a33-11eb-88b1-f585adc95b71.png)

**Comment by justinkropp** [comment]
@markteater My only feedback for the above is this: 

For the large FAQ question header, decrease the margin below that header and the answer text and increase the margin above that same header and the "related questions" text above. 

Currently that spacing looks equidistant both above and below, which makes it harder to distinguish between which text is associated with what. Does that make sense?
