### ISSUE TITLE
Quantum Page Design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9501]
## Description

in #9499 we build a faq page, this issue is the track the design.

---

#### Success Criteria
- [x] Mockup is attached
- [x] Design is attached
- [ ] Chad approved
- [ ] Dev knows what to do

**Comment by rraue** [comment]
Mockup: 
![quantum design idea](https://user-images.githubusercontent.com/36700618/94924451-d5f70d80-04bd-11eb-963c-7b0847bfe90c.png)

- Design from /new
- Feature box without headline
- icons if available

**Comment by markteater** [comment]
@rraue here's the desktop version based on the current available copy:

![Quantum Page - Screen XL - 1312](https://user-images.githubusercontent.com/1934450/95355051-1f1ad900-0893-11eb-8da5-600a25f92b43.png)
