### ISSUE TITLE
Quantum Page Coding

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9502]
## Description

In https://github.com/mozilla/bedrock/issues/9499 we build a quantum page. This issue tracks coding.

- Url: /firefox/browsers/quantum/
- Open for translation

---

#### Success Criteria
- [x] Page is coded
- [ ] /firefox/quantum/ redirects to /firefox/browsers/quantum/

**Comment by hoosteeno** [comment]
Closed in #9499
