### ISSUE TITLE
Pillar Page Design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9505]
## Description

in #9503 we build a pillar page, this issue is the track the design.

---

#### Success Criteria
- [x] Mockup is attached
- [x] Design is attached
- [ ] Chad approved
- [ ] Dev knows what to do

**Comment by rraue** [comment]
Design like the homepage. No extra assets between the cards.

Order of cards:
4 cards:
/en-US/firefox/browsers/browser-history/
/en-US/firefox/features/independent/
/en-US/firefox/browsers/what-is-a-browser/
/en-US/firefox/browsers/update-your-browser/
break

4 cards
/en-US/firefox/products/
/en-US/firefox/browsers/
/en-US/firefox/lockwise/
/en-US/firefox/all/
break

4 cards:
/en-US/firefox/mac/
/en-US/firefox/linux/
/en-US/firefox/windows/ 
/en-US/firefox/browsers/windows-64-bit/
break

3 cards:
/en-US/firefox/browsers/compare/
/en-US/firefox/browsers/compare/chrome/
/en-US/firefox/browsers/compare/brave/
break

4 cards:
/en-US/firefox/browsers/compare/edge/
/en-US/firefox/browsers/compare/ie/
/en-US/firefox/browsers/compare/opera/
/en-US/firefox/browsers/compare/safari/
break

4cards:
/en-US/firefox/features/adblocker/
/en-US/firefox/features/private-browsing/
/en-US/firefox/browsers/incognito-browser/
/en-US/firefox/features/safebrowser/
end

**Comment by rraue** [comment]
Blocking: We need illustrations/images for all pages. Should be existing ones that fit.

**Comment by markteater** [comment]
@rraue here are low fidelity mockups (no images and a missing SM footer) for this page.

![Screen XL - 1312](https://user-images.githubusercontent.com/1934450/95261426-61dba300-07f8-11eb-8301-0d3fa8a0dea7.png)
![Screen LG - Below 1024](https://user-images.githubusercontent.com/1934450/95261432-630cd000-07f8-11eb-837e-6b618735be52.png)
![Screen SM - Below 480](https://user-images.githubusercontent.com/1934450/95261434-630cd000-07f8-11eb-9070-639122ae4ef7.png)

**Comment by rraue** [comment]
I made a choice of images for the cards. Could you please review @justinkropp:

Order of cards: 4 cards: /en-US/firefox/browsers/browser-history/
https://www.mozilla.org/media/img/firefox/browsers/browser-history/browser-history-b.fc9471e80e20.png

 /en-US/firefox/features/independent/
https://www.mozilla.org/media/img/firefox/features/thumbnails/independent/mission.e73c1c774338.jpg

 /en-US/firefox/browsers/what-is-a-browser/
https://www.mozilla.org/media/img/firefox/browsers/what-is-a-browser/illo-browser.b70096fd5f78.png

 /en-US/firefox/browsers/update-your-browser/
https://www.mozilla.org/media/img/firefox/browsers/update-browser/fast.e08e37809b25.png
 
4 cards /en-US/firefox/products/
https://blog.mozilla.org/firefox/files/2019/05/join-firefox-five-reasons_revised.jpg

 /en-US/firefox/browsers/
https://www.mozilla.org/media/img/l10n/en-US/firefox/home/browser.0513d7098d2e.jpg

 /en-US/firefox/lockwise/
Just the lockwise logo

 /en-US/firefox/all/
https://blog.mozilla.org/firefox/files/2018/11/Transation.png

 break
4 cards: /en-US/firefox/mac/
https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2020-02-04-03-15-35-ee0dc6.png

 /en-US/firefox/linux/
https://www.mozilla.org/media/img/firefox/features/index/features-hero.fa915c770ed0.png

 /en-US/firefox/windows/
https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/firefox/files/2020/03/fx_blog_switch-edge-firefox_v02.gif

 /en-US/firefox/browsers/windows-64-bit/
https://blog.mozilla.org/firefox/files/2017/08/Blog_64_Bit_Revised.jpg

 break
3 cards: /en-US/firefox/browsers/compare/
https://www.mozilla.org/media/img/firefox/compare/compare-browser-windows.3c11dd6787cd.png

 /en-US/firefox/browsers/compare/chrome/
Screenshot page

 /en-US/firefox/browsers/compare/brave/
Screenshot page

 break
4 cards: /en-US/firefox/browsers/compare/edge/
Screenshot page

 /en-US/firefox/browsers/compare/ie/
Screenshot page

 /en-US/firefox/browsers/compare/opera/
Screenshot page

 /en-US/firefox/browsers/compare/safari/
Screenshot page

 break
4cards: /en-US/firefox/features/adblocker/
https://blog.mozilla.org/firefox/files/2020/04/fx_blog_privacy-features_v03.jpg

 /en-US/firefox/features/private-browsing/
https://blog.mozilla.org/firefox/files/2019/05/private_browsing_2.png

 /en-US/firefox/browsers/incognito-browser/
https://blog.mozilla.org/firefox/files/2018/04/FF-Focus-Hub-Page_Feature-Images-01.png

 /en-US/firefox/features/safebrowser/
https://blog.mozilla.org/firefox/files/2018/09/SP_FX_Monitor_blogheader-04.png
