### ISSUE TITLE
Possibly incomplete heading

### ISSUE THREAD

**Issue by gujjwal00** [mozilla/bedrock#9509]
## Description

Heading on one section/card seems to be incomplete.

### Steps to reproduce

Go to https://www.mozilla.org/en-US/firefox/enterprise/

Screenshot:

![image](https://user-images.githubusercontent.com/27951674/94985395-eff32780-0573-11eb-9ffb-10adba81b336.png)

### Expected

 "Your data stays **with** your business"

**Comment by yogeshsingh101200** [comment]
Can you assign it to me? I want to work on this one. It need editing line 68 of this [file](https://github.com/mozilla/bedrock/blob/5a4d4cd1866034620fac7ccfefdcbf9e4bc2924d/bedrock/firefox/templates/firefox/enterprise/index.html).

**Comment by alexgibson** [comment]
Thanks for filing this. In the case of this heading the word "business" is used in relation to an individual's privacy, and not necessarily data belonging to a literal business or organization.
