### ISSUE TITLE
Chromebook Page Design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9514]
## Description

in https://github.com/mozilla/bedrock/issues/9512 we build a Chromebook page, this issue is the track the design.

---

#### Success Criteria
- [ ] Design is attached
- [ ] @justinkropp approved
- [ ] Chad approved
- [ ] Dev knows what to do

**Comment by rraue** [comment]
Mockup:
![Screenshot 2020-10-06 at 15 59 19](https://user-images.githubusercontent.com/36700618/95211512-f8a26280-07ec-11eb-8f67-920e188c8de0.png)

The download button on top should be like the dropdown on /firefox or /enterprise to give the two options for android and linux:

![Screenshot 2020-10-06 at 16 00 53](https://user-images.githubusercontent.com/36700618/95211673-28ea0100-07ed-11eb-9032-a8b52fbd55ec.png)

The cta in the bottom will be a android play store button and for linux a link to sumo.

**Comment by markteater** [comment]
@rraue here's the low fidelity mock-up for the desktop Chromebook page: 
![Chromebook - Screen XL - 1312](https://user-images.githubusercontent.com/1934450/95610893-0c3d0b80-0a2f-11eb-9a23-e7917bba781b.png)

**Comment by rraue** [comment]
First image on the page: https://drive.google.com/drive/folders/1Jyx-7DxftRWiF5xb7rBJ15R2t5zTXy-Z

Picture down left: https://www.mozilla.org/media/img/firefox/compare/compare-browser-chrome.1562906128bf.png

Picture down right: https://drive.google.com/drive/folders/1Jyx-7DxftRWiF5xb7rBJ15R2t5zTXy-Z

**Comment by amychurchwell** [comment]
Link to first image is the entire folder for me @rraue

**Comment by rraue** [comment]
Sorry @amychurchwell here again:

First image: https://drive.google.com/file/d/1KKuKKEbIXhApBPDwf7okoMmHQBEvD0uh/view?usp=sharing
Picture down left: https://drive.google.com/file/d/1KIHKb2brh9VRV7hn-9Gr7TfPhAKLf90S/view?usp=sharing
Picture down right: https://drive.google.com/file/d/1KVsSaT6IV18HYGOj4DCKRJKvdFySPNZt/view?usp=sharing

**Comment by amychurchwell** [comment]
The page will reflect the "button" style of drop-down menu because that performed the best in CRO tests. There is an issue to back port to protocol, just need to find the time.
