### ISSUE TITLE
Firefox Sync Design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9518]
## Description

in https://github.com/mozilla/bedrock/issues/9516 we build a Sync page, this issue is the track the design.

---

#### Success Criteria
- [x] Design is attached
- [ ] Chad approved
- [ ] Dev knows what to do

**Comment by rraue** [comment]
Mockup:
![sync](https://user-images.githubusercontent.com/36700618/95226444-3b6c3680-07fd-11eb-88d7-ba49503ce55a.jpg)

Head from /accounts/
Second part with the features (no headline) from /new and the lower part again from /accounts.

**Comment by markteater** [comment]
@rraue here's the low fidelity mockup for the desktop Sync page: 
![Sync Page - Screen XL - 1312](https://user-images.githubusercontent.com/1934450/95610733-c08a6200-0a2e-11eb-95e2-5b15cf464068.png)

**Comment by rraue** [comment]
Missing picture on top: https://www.mozilla.org/media/img/firefox/accounts/trailhead/value-knowledge.194ccb6b5af9.jpg
