### ISSUE TITLE
Little Book of privacy Design

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9522]
## Description

in https://github.com/mozilla/bedrock/issues/9520 we build a little book of privacy page, this issue is the track the design.

---

#### Success Criteria
- [x] Design is attached
- [x] @justinkropp approved
- [x] Chad approved
- [ ] Dev knows what to do

**Comment by rraue** [comment]
Design Mockup:
![little book design idea](https://user-images.githubusercontent.com/36700618/95090601-bf52ef80-0725-11eb-9b6d-ca349a437b69.png)

- should be included in the /firefox/privacy/ subnav
- Has 2 cta - download firefox & download pdf in en & de - in all other locales only download as cta
- easy right - left design
- illustrations we take from the pdf or from the .ai file in the gdrive: https://drive.google.com/drive/folders/1EPL0Z_AlRpK6Teq5SQQk5kgEIpD0nFbU and in caronlyns folder: https://drive.google.com/drive/folders/1xvGsE_4YNPsKi5eNONwc4Ldy-B54chqo

**Comment by markteater** [comment]
@rraue here's my initial pass at a basic conversion of The Little Book of Privacy:
![Screenshot_2020-10-15 Little Book of Privacy - Protocol Design System](https://user-images.githubusercontent.com/1934450/96271684-2cbf1580-0f9b-11eb-9046-b43b74eed5af.jpg)

**Comment by rraue** [comment]
One of the things missing in this Design (sorry I didnt catch this earlier) is the subnav of https://www.mozilla.org/en-US/firefox/privacy/ that should include the little book of privacy and should be included on top of this page here as well.
