### ISSUE TITLE
Add the software licenses for our VPN product.

### ISSUE THREAD

**Issue by mhoye** [mozilla/bedrock#9524]
## Description

We'd like to add the software licensing for our VPN product to our website somewhere sensible - Maybe legal-docs - and public, so that we can put a link to it in the product but maintain the canonical information elsewhere. I've attached a copy of the text of the LICENSE.md file in the repository, and believe that we can include the same thing on the website.

In  a perfect world, we'd pull the markdown file directly from the repository so that we could process it and add it to the website, but for now let's ship.

---

#### Success Criteria
- [ ] The licensing information (see below) is visible on the Mozilla website, and 
- [ ] A link to that page is provided to Baku for inclusion in the product.

Text of licensing.md

Mozilla VPN Software Licenses
=============================

Unless otherwise specified below, all files in the Mozilla VPN project are licensed under the
Mozilla Public License version 2.0 (*MPL2*), with copyright belonging to the Mozilla Foundation.
The full text of the MPL is [available on Mozilla's website.] (https://www.mozilla.org/en-US/MPL/2.0/) 

This project relies on [QT Quick] (https://doc.qt.io/qt-5/qtquick-index.html), provided
by [the QT Company] (http://www.qt.io/about-us/) and used unmodified under the terms of
the Lesser GNU Public License 3.0 (*LGPL-3.0*). The full text of the LGPL3 is 
[available here.](https://opensource.org/licenses/lgpl-3.0)

On MacOS and iOS, this project depends on several files provided by the [WireGuard project] 
(https://github.com/WireGuard/wireguard-apple/) under the terms of the MIT Public License (*MIT*),
a copy of which is [available here.](https://opensource.org/licenses/MIT)

The Linux release of this project also relies on several files from the [WireGuard Tools] 
(https://github.com/WireGuard/wireguard-tools/) repository, as well as the FreeDesktop 
project's [polkit library](https://gitlab.freedesktop.org/polkit/polkit/), all of which
are provided under the terms of the Lesser GNU Public License 2.0 (*LGPL-2.0*). A copy of the
LGPL-2.0 is [available here.](https://opensource.org/licenses/LGPL-2.0)

Finally, this project uses an EC25519 library from NSS, available under the terms of the 
MIT Public License (*MIT*) and copyright (c) 2016-2020 INRIA, CMU and Microsoft Corporation.

**Comment by alexgibson** [comment]
@mhoye looks like this one went under our radar. Is it still needed today?

**Comment by mhoye** [comment]
We definitely still need licensing information in the product, but we need to verify that the above claims about what's in the product are still correct first.

**Comment by danielnazer** [comment]
This can be closed - the in-product notices are good.

**Comment by alexgibson** [comment]
Thanks, closing
