### ISSUE TITLE
Homepage (EN): Pocket Hero Copy Edit

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#9558]
## Description

Update Pocket Hero section title from "Welcome to the sunny side of the web." to "Welcome to the web, sunny side up"

---

#### Success Criteria
- [ ] Update copy

**Comment by kellymj** [comment]
Blurb change:

Millions of people rely on Pocket to save and discover the best articles, stories and videos on the web. As part of the Firefox family, Pocket has the same dedication to privacy.
