### ISSUE TITLE
Update Android screenshot in mobile banner on /new

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9562]
Image in the banner needs updating:

![image](https://user-images.githubusercontent.com/400117/91414921-25a24380-e845-11ea-8750-13fc3c06e417.png)

_Originally posted by @alexgibson in https://github.com/mozilla/bedrock/issues/9337#issuecomment-681750664

**Comment by RotonEvan** [comment]
Shall I work on this issue?

**Comment by maxxcrawford** [comment]
I used the original screenshot to create this mockup. 

Before: 
![image](https://user-images.githubusercontent.com/2692333/109054657-bf876380-76a3-11eb-9a16-794cd795fff2.png)

Revised: 
![image](https://user-images.githubusercontent.com/2692333/109054685-c4e4ae00-76a3-11eb-94c5-13a1bda8551a.png)

**Comment by maureenlholland** [comment]
closing as outdated
