### ISSUE TITLE
Design new theme for blog refresh

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9568]
## Description

The current theme for the blog refresh is a Firefox specific theme. It needs to be updated to reflect Mozilla as the parent brand.

---

#### Success Criteria
- [x] Theme reflects Mozilla as the parent brand.
- [ ] Approved designs attached to issue.

**Comment by slightlyoffbeat** [comment]
https://www.figma.com/file/hRaITcz2Cnwyd2gBFZPD0i/Firefox-Content-Hub-Copy?node-id=2149%3A10

@justinkropp delivered a set of updated components. Linked above.

**Comment by alexgibson** [comment]
@slightlyoffbeat is this one all done?

**Comment by slightlyoffbeat** [comment]
Yup
