### ISSUE TITLE
Ensure version specific behavior works as expected for Firefox 100.0

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9575]
## Description

Examples:

- https://www.mozilla.org/en-US/firefox/100.0a1/whatsnew/all/ should show the Nightly /whatsnew page
- https://www.mozilla.org/en-US/firefox/100.0a2/whatsnew/all/ should show the Dev Edition /whatsnew page

It's likely there may be other areas of unexpected behavior, such as

- Release notes URLs
- Detection for Firefox being up to date (via JS?)
- Anything else?

**Comment by alexgibson** [comment]
This needs to be done before Q1 2022, which is when Nightly will hit v100

**Comment by alexgibson** [comment]
Some useful checks here: https://www.otsukare.info/2021/04/20/ua-three-digits-get-ready

**Comment by stevejalim** [comment]
Am working on the whatsnew Dev / Nightly page niggle mentioned in the description

**Comment by alexgibson** [comment]
Looks like there's a pref being added to Nightly to flip the UA string version number to 100 to help with testing: https://bugzilla.mozilla.org/show_bug.cgi?id=1748798

**Comment by alexgibson** [comment]
I took a look at our front-end code, and the only place we seem to do UA browser version checks is in the `Mozilla.Client` library. I opened a PR that adds the Firefox v100 UA string to the file's existing unit tests, and things look OK: https://github.com/mozilla/bedrock/pull/11098

**Comment by alexgibson** [comment]
Found another bug (STR):

1. Open https://www.mozilla.org/en-US/firefox/100.0/whatsnew/?signed-in=false
2. Inspect the "Sign In" link `href`.

Expected result:

- `entrypoint=mozilla.org-whatsnew100`
- `utm_source=mozilla.org-whatsnew100`
- `utm_campaign=whatsnew100`

Actual result:

- `entrypoint=mozilla.org-whatsnew10`
- `utm_source=mozilla.org-whatsnew10`
- `utm_campaign=whatsnew10`

**Comment by alexgibson** [comment]
Lol

![image](https://user-images.githubusercontent.com/400117/148556059-a2b0e6e8-63ab-4ded-8454-68df00a85fc4.png)

**Comment by alexgibson** [comment]
PR to fix /whatsnew page version logic: https://github.com/mozilla/bedrock/pull/11099

**Comment by alexgibson** [comment]
I'm pretty sure there mnight be a [bug here](https://github.com/mozilla/bedrock/blob/master/bedrock/releasenotes/views.py#L62) in the ststem requirement pages, but I'm not sure how best to check there, since related pages don't exist for FF 100 yet. It may require some extended backend testing.

@stevejalim maybe you could take a look over the `releasenotes` app?

**Comment by stevejalim** [comment]
@alexgibson Thanks for the pointer - making a PR for that now.

I grepped for `{1,2}` and saw it in some JS that might also need a tweak.

https://github.com/mozilla/bedrock/blob/4175943789d1d5123f2a005c033a94b6373e01c9/media/js/base/mozilla-client.js#L142:L147

**Comment by stevejalim** [comment]
@alexgibson @pmac Micro PR for the Android releasenotes niggle mentioned by Alex above - https://github.com/mozilla/bedrock/pull/11102

**Comment by alexgibson** [comment]
I've spent some more time searching through the codebase today, and I can't spot any other obvious areas where we're only checking for a specific number of digits in either UA strings or page URLs. The areas where we do now seem to have adequate enough tests.

@stevejalim I did wonder if it might be worth adding any additional backend tests for either [releasenotes](https://github.com/mozilla/bedrock/blob/master/bedrock/releasenotes/views.py) or [firefox_details](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/firefox_details.py)? I'll leave this up to (happy to review fi helpful), but these are the only two remaining areas I can spot where it might be useful to add a sanity check or two.

**Comment by stevejalim** [comment]
@alexgibson Will give them a look over now, sure thing

**Comment by stevejalim** [comment]
Looked over the backend code for `releasenotes` and:

* [ ] The `releasenotes` app imports from `django-product-details` which does itself need a bit of a poke to make it cope with three-digit releases. 

* [ ] We should check in with MDN (@schalkneethling ?) about whether https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases is ready for three-digit FF too, given we link to it from `releasenotes`

* [ ] I can't see any areas in releasenotes that are version-specific, but I could just backfill tests based on gaps in coverage - opinons? 
   Expand tests for:
   - [ ] `releasenotes.views.releases_index`

(Will update this code after eyeballing `firefox_details`)

**Comment by schalkneethling** [comment]
> * We should check in with MDN (@schalkneethling ?) about whether https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases is ready for three-digit FF too, given we link to it from `releasenotes`

I am asking around to make sure but I reckon we should be all good.

**Comment by robhudson** [comment]
Sharing this here as work done towards this cause: https://github.com/mozilla/django-product-details/pull/79

**Comment by stevejalim** [comment]
@alexgibson Shall we count this as 'done' as far as possible for now? Once Nightly hits 100, that should validate that we've caught everything (if we do a good test drive around), yeah?

**Comment by alexgibson** [comment]
@stevejalim sounds good, thank for all your efforts here! Closing

**Comment by stevejalim** [comment]
@alexgibson Go team! ⭐ 🌟
