### ISSUE TITLE
Implement an A/B testing redirect solution for www pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9576]
## Description

When we migrate to the new CDN, we'll no longer have the ability to run [edge workers](https://github.com/mozmeao/www-workers) for A/B testing redirects.

We're going to need to come up with an alternate solution. Some possibilities include:

1.) A server side redirect mechanism for A/B testing in bedrock.
2.) A lambda solution using Cloudfront.
3.) A client side solution using JS in bedrock.

I think our preference would likely be 1 or 2, since a client side solution would be least performant.

**Comment by alexgibson** [comment]
Minimum requirements:

- Can redirect a set % of visits to a URL, e.g. /en-US/firefox/new/ -> /en-US/exp/firefox/new/
- Redirect can be toggled on / off via a switch
- % can be updated independently of a production push.

**Comment by pmac** [comment]
A meeting would be good probably. My first thought is that implementing something in bedrock for a specific test first would be good, and then we can extract the reusable bits from that into a more general purpose solution that can evolve over time. I could see a view base class that could be used for this kind of thing, or even just some helper functions.

**Comment by alexgibson** [comment]
Sent a meeting invite for Wednesday - feel free to arrange a different time if that doesn't work?

**Comment by pmac** [comment]
We also decided that it should never get the experiment redirect if an `automation=true` parameter is in the URL, as discussed in #8917.
