### ISSUE TITLE
Newsletter preferences page lists "Mozilla Festival" twicee

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#9578]
## Description

When I inspect the elements though one of them is really for the `mozilla-festival` newsletter, but the other is for `internet-health-report-group`. I'm guessing this must be something that was introduced in #8659.

**Comment by AlexandraMoga** [comment]
@pmac I can also see Mozilla Labs twice in the list. One of the entries should actually be the Add-on Developers Newsletter:

![image](https://user-images.githubusercontent.com/31961530/96877279-1ecd3100-1482-11eb-929d-4c0a52d47fe0.png)
