### ISSUE TITLE
Need to edit three pages on CPG reporting in Mozilla.org

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/bedrock#9579]
Hello @hoosteeno,  I need to make a few minor edits on the following pages. The edits are currently under review, but they should be ready by the end of the week (I will confirm here when they are done) Changes should be carried out by EOD 29/10/2020. (would the change in the English version be reflected on the other languages?) 

https://www.mozilla.org/en-US/about/governance/policies/participation/reporting/community-hotline/
https://www.mozilla.org/en-US/about/governance/policies/participation/
https://www.mozilla.org/en-US/about/governance/policies/participation/reporting/

Here is a list of changes:

https://docs.google.com/document/d/1OdUdI59s6ZUx_h_xg_xArkehXfs_eRh_F5vXy9VIwtE/edit

Thank you very much, and let me know if I need to add more details.

**Comment by hoosteeno** [comment]
@Francescaminelli please ping when the copy is done. Our ability to hit any deadline will depend on that. 

Meanwhile, can you share a bit more about what's driving the deadline?

**Comment by Francescaminelli** [comment]
Hi, thank you for this. I will ping here when I have the copy, The deadline is probably going to be a bit longer than I thought (possibly 2-3 weeks after the copy is ready)

**Comment by Francescaminelli** [comment]
Hi @hoosteeno changes have been approved, and we can go ahead with them. All the links are in [this document ](https://docs.google.com/document/d/1OdUdI59s6ZUx_h_xg_xArkehXfs_eRh_F5vXy9VIwtE/edit). The changes are underlined with track changes. Please let me know if you need any more information, or if something is not clear.

**Comment by slightlyoffbeat** [comment]
@Francescaminelli Hello. I can work on this. Can you add dbrown@mozilla.com to the tracked changes docs? The links are read-only, so I cannot see the changes.

**Comment by Francescaminelli** [comment]
Done! thank you very much :)

**Comment by hoosteeno** [comment]
@Francescaminelli I neglected to consider the technical debt that this issue will require us to pay down. We implemented a new localization system since this page was last changed, so whenever we next change this page's text, we'll have to migrate it (a significant effort we'll have to find time for, not immediately). 

Alternatives:
1. We hold this issue until we can do the migration work
2. We adjust the specifications so they don't change any content, only links. For example, we do change what happens when people click the "Report" button, but we don't change the text, `Reports go directly to Mozilla’s Employment Counsel and HR People Partners and are triaged by the Community Participation Guidelines Response Lead.`.

Which of those is preferable?

**Comment by Francescaminelli** [comment]
Hi, @hoosteeno thank you for letting me know. What would be the timeframe for the migration work?

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9666

**Comment by Francescaminelli** [comment]
Hi, could I know if the changes could still happen in time? Thank you very much!

**Comment by hoosteeno** [comment]
@amychurchwell are we on track for finishing #9666 this week so we can release CPG changes before EOM?

**Comment by amychurchwell** [comment]
@hoosteeno yes 👍

**Comment by Francescaminelli** [comment]
Great, thanks!

**Comment by hoosteeno** [comment]
Hi @Francescaminelli , the localization team [found a string that needs clarification](https://github.com/mozilla-l10n/www-l10n/pull/133#discussion_r526512922) in the "how to report" doc.

> If the reporter wants to make an anonymous report, please inform them that this contact information we may not be able to update the initial reporter if appropriate. 

Can you please respond here with a clearer sentence for us to use in place of that one?

**Comment by Francescaminelli** [comment]
Hi, thank you for letting me know. I am confirming the changes needed to that sentence and I hope that I can back at you in a few hours. 
Unfortunately, I did not check the whole document, but only added the changes needed due to the changes in reporting system. Can you confirm that the three pages will not be changed at all (from the original published page) apart from the changes I underlined with track changes (and the correction to the sentence you underlined)?

**Comment by amychurchwell** [comment]
@Francescaminelli no worries at all! 

Part of the localization process is adjusting grammar/phrasing for the most clarity for translation. These preexisting issues came up as we move these pages over to the Fluent system. There are a couple outstanding issues on [/policies/participation](https://github.com/mozilla-l10n/www-l10n/pull/138) and [/governance/policies/reporting](https://github.com/mozilla-l10n/www-l10n/pull/133).

Perhaps you and @peiying2 can work directly to resolve so we can port these pages and get your updates in as quickly as possible? Thanks for your patience.

**Comment by hoosteeno** [comment]
@Francescaminelli we are blocked on this until we hear from you about the strings that @peiying2 highlighted. Do you need anything from us on this?

**Comment by Francescaminelli** [comment]
Hi, I clarified the one unclear sentence. Regarding the other issues, I am waiting to hear back. Thank you for this.

**Comment by amychurchwell** [comment]
@Francescaminelli thank you for your help! Unfortunately, we are also blocked on a technical issue in Pontoon. We are working with Peiying and Matjaz from l10n to resolve, thank you for your patience. Due to time zone differences, we expect an update tomorrow. Once it is resolved we will be able to move forward quickly and get the updates out.

**Comment by alexgibson** [comment]
It looks like this was fixed in https://github.com/mozilla/bedrock/pull/9743
