### ISSUE TITLE
Daylight banner is missing CSS styles on rest-of-world home page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9582]
![image](https://user-images.githubusercontent.com/400117/96886964-ff330a00-147b-11eb-9d82-462eb56d90d5.png)

I also don't see the banner at all on the french home page:

![image](https://user-images.githubusercontent.com/400117/96887050-170a8e00-147c-11eb-8a39-a555df7aa069.png)

**Comment by craigcook** [comment]
Looks like it hasn't been localized in French yet.
