### ISSUE TITLE
Remove WNP 80 Files

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#9589]
## Description

Remove all instances (files, tests, bundles) of Fx79 WNP assets. 

🚨 This issue is blocked by https://github.com/mozilla/bedrock/issues/9573 🚨 
---

#### Success Criteria
- [ ] All WNP 79 assets are removed
- [ ] All tests pass without issue

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/10258
