### ISSUE TITLE
run-integration-tests branch is not working

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9598]
## Description

Looks like this is broken because it relied on the now defunked oregon-b cluster. We should move it to GCP.

**Comment by alexgibson** [comment]
@pmac think we might be able to get this one fixed soon? It would come in handy for a few things we've got coming up, such as https://github.com/mozilla/bedrock/issues/9466 and https://github.com/mozilla/bedrock/issues/8917

**Comment by pmac** [comment]
Yes. I'll see what I can do about it today.

**Comment by pmac** [comment]
it works! https://gitlab.com/mozmeao/www-config/-/pipelines/210817144
