### ISSUE TITLE
coding blog refresh.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9600]
## Description

Front end work to finish creating this new blog theme

---

#### Success Criteria
This will be tracked on the projects github page:
https://github.com/slightlyoffbeat/foxtail/

**Comment by hoosteeno** [comment]
@slightlyoffbeat can you link to the other repo of issues/code for this here? Even just a single link.

**Comment by slightlyoffbeat** [comment]
https://github.com/slightlyoffbeat/foxtail/ (I'll work to get this moved to a mozilla owned repo)

**Comment by hoosteeno** [comment]
@slightlyoffbeat can you update?
