### ISSUE TITLE
New name for blog refresh.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9601]
## Description

This blog needs a name. Lets work with creative to come up with a name for the blog

---

#### Success Criteria
- [ ] Minimum Viable Brief
- [ ] Shortlist of names
- [ ] Name that is approved by leadership

**Comment by hoosteeno** [comment]
@slightlyoffbeat to build a brief by Tuesday.

**Comment by hoosteeno** [comment]
The brief has been handed to Editorial/Brand teams. Rsmith reviewing.

**Comment by alexgibson** [comment]
I believe this is done, but feel free to reopen if anything is still outstanding here.
