### ISSUE TITLE
Add link to pillar page on /releasenotes

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9610]
## Description

In https://github.com/mozilla/bedrock/issues/9503 we have build a pillar page for our evergreen content and in order to reduce orphaned pages (we will add more card-links to the pillar page) we need to link the pillar page. Currently our nav system is still evolving and in order to get the page and therefor the linked pages crawled and indexed, we need to set a link to /firefox/more/.

We will set a link on all /releasenotes pages in the footer

**Comment by alexgibson** [comment]
Suggest we use some link text that’s slightly more helpful than “More”?

**Comment by rraue** [comment]
Haha, yes! Any suggestion? Its a wild mix of pages we havent figured out the right information architecture for. I need it indexed and can't find a better link text. Maybe "More about Firefox"? Not super precise but at the end the page provides a lot of links to knowledge around browsers and all builds of firefox.

**Comment by alexgibson** [comment]
Honestly I'm a little confused why we'd add this to /all from a user perspective. I understand we want it indexed, but we should favor users over robots.

Would a page like https://www.mozilla.org/en-US/firefox/more/ not be a good source of additional reading to people landing at https://www.mozilla.org/en-US/firefox/ ?

**Comment by rraue** [comment]
I agree completely. We shouldn't have links for robots only (/locale/ might be the only exception) and I don't think the pages is without value (like a category page in a blog isn't without value and still not heavily used). And /firefox/ was my first page to go to as well, but I don't see currently any Text where it makes sense to link to /more (/faq should be linked from /firefox as well and I cant find a place right now). I thought as wlel about the footer, but isnt our footer global for the whole site?

The reason I choose /all is that its sort of the last resort and since the last update with a super clear UX. So the links in the right are the eternal-last resort if you really cant find on the page what you are looking for. /more will eventually guide you then.

But I am fine with any useful link to the page.

**Comment by alexgibson** [comment]
Ultimately I'm ok with putting this on /all if there's really nowhere else. But it feels like we're just adding links for crawlers now in places where users may not find it useful. Imho the focus of the /all page should be helping people get the build they want / need. Pages like /firefox seem to be more for helping people to make up their mind, where evergreen articles like these may be more helpful. This is just my 2 pence though so feel free to ignore 😅

**Comment by rraue** [comment]
Then lets do it and I have hope with more and more evergreen content to come (even on the unfck landing page) we will figure out a system that is build for both crawlers and users. Thats the ultimate goal but right now we are too brand and too little information focused on a lot of important pages. /new is a great example of both and I think this is how we will move forward. But in the mean time we need compromise. And at the end the pages on the pillar page help especially users from search to understand us better and get the browser they want: Firefox. 

So I share, as you know, your concerns but don't know a quick and good solution right away. The good thing is, with the pillar page I have then a system to add quickly pages, get them crawled and indexed and find the right solution on our important pages later. We will not need a second system. Even if we might get a better one with Dans work on the blogs to include evergreen and knowledge content better with our other content.

**Comment by rraue** [comment]
@alexgibson Another thought on this, what if I sort the pages on more in a different way to reflect better the purpose here. All firefox builds landing pages go to the top, the header links to the faq instead of privacy (with a new title of course, need to think better about it) and after the specific landing pages the compare page and the stuff form the old internet health goes to the bottom?

I need to iterate on the /more page anyways to add the new pages.

**Comment by alexgibson** [comment]
Some form of content hierarchy on that page could be helpful yeah. Right now it feels like a little like a random collection of links where the only common thread is Firefox. Sorting could help, but what might work better are visual groupings with sub headings.

**Comment by rraue** [comment]
Will work on it this week ( its on my plate anyways to add all the pages that went and will go live this week).

**Comment by rraue** [comment]
Merge only if @justinkropp & @hoosteeno approve

**Comment by justinkropp** [comment]
> Some form of content hierarchy on that page could be helpful yeah. Right now it feels like a little like a random collection of links where the only common thread is Firefox. Sorting could help, but what might work better are visual groupings with sub headings.

I agree with @alexgibson's observation and suggestion. A little visual hierarchy on the page would go a long way in helping users scan the page more effectively and target what content they are trying to find.

I'm okay with merging this as long as we can revisit once we have the system more fleshed out and can find a more appropriate spot to put `more`.

**Comment by hoosteeno** [comment]
I agree we should figure out a better way, long term, to make our entire content catalog discoverable. "Doing it for search robots" is misleading; the need here is more accurately stated as "Doing it for users who use search as their primary navigation tool". And who among us is innocent of that?

Near term, the /all page is OK for this, but we've spent a good amount of time recently making it work better. I would rather put this link into the grab-bag of links at the bottom of every release notes page, as in the attached image. @alexgibson , @justinkropp , thoughts about this?

![Screen Shot 2020-10-27 at 8 14 22 AM](https://user-images.githubusercontent.com/94519/97314045-e8e6ce80-182c-11eb-82ca-500c1930212b.png)

**Comment by alexgibson** [comment]
> "Doing it for search robots" is misleading; the need here is more accurately stated as "Doing it for users who use search as their primary navigation tool". And who among us is innocent of that?

I think we all understand the importance of how our pages turn up in search results, but I think we also all understand that UX also plays a big part here in the pages we design, and how users navigate them. If a link serves no clear purpose on a page other than to serve crawlers, then that's a problem with our site hierarchy. We should invest time in thinking how to solve that, vs add lots of little UX papercuts. I'm glad that we're thinking a bit more about this kind of thing 👍
