### ISSUE TITLE
Implement a prototype using Client Hints API for replacing bedrock's UA detection

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9628]
## Description

Implement a prototype on demo using Client Hints API to provide UA detection required for serving downloads, falling back to User Agent string if not available / for other browsers.

Depends on #9555

---

#### Success Criteria
- [x] Prototype is on demo and available for testing.

**Comment by hoosteeno** [comment]
Let's pitch this here: https://trello.com/c/u6t9j76x/129-prototype-ua-string-replacement

**Comment by alexgibson** [comment]
Some notes based on testing the prototype linked above:

On my 64bit Windows10 laptop, I have the following client hints available to me:

```
Sec-CH-UA-Arch: "x86"
Sec-CH-UA-Model:
Sec-CH-UA-Platform: "Windows"
Sec-CH-UA-Platform-Version: "10.0"
Sec-CH-UA: : "Chromium";v="88", "Google Chrome";v="88", ";Not\\A\"Brand";v="99"
Sec-CH-UA-Full-Version: "88.0.4316.2"
Sec-CH-UA-Mobile: ?0
```

What's interesting is there's nothing in the `Sec-CH-UA-Arch` field to signal that I'm on a 64bit machine. For Windows this likely won't be a problem, since we rely on the stub installer to detect 64bit machines. For Linux users, this may be a problem however and would require further testing. If we we're unable to detect 64bit on Linux, we may have to default to it, and give people the option to download the 32bit version if that's what they need.

**Comment by alexgibson** [comment]
So far I can confirm the following:

- MacOS is being detected sucessfully, and the correct binaries are served on download.
- Windows is being detected successfully and served the right files too.
- Windows version 10 is being detected successfully on /thanks (installer help message is visible)

**Comment by alexgibson** [comment]
I also have no way of telling what informartion is given for ARM64 on Windows.

[This article](https://web.dev/user-agent-client-hints/) suggests we may need to check for `ARM64` in the `Sec-CH-UA-Arch` field, but we'd need to be able to verify it somehow. Obtaining a device for testing will probably be the easiest method here.

**Comment by alexgibson** [comment]
Demo branch is here: https://github.com/mozilla/bedrock/pull/9669

I'm going to close this as done, and write up some notes / recommendations in https://github.com/mozilla/bedrock/issues/8440
