### ISSUE TITLE
lint fluent ID names in pull requests.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9631]
## Description

In pull requests that add new `.ftl` files we should do a check that these strings begin with the same prefix per the recommended syntax:
```
example-page-title = The Page Title
example-page-desc = This page is a test.
```

[Localization docs](https://bedrock.readthedocs.io/en/latest/l10n.html#ftl-files)

[We can not change fluent ID's retroactively](https://github.com/mozilla-l10n/www-l10n/pull/125#issuecomment-718936526) without breaking translations and it is important that we maintain consistency in bedrock to avoid duplicate ID's.

**Comment by alexgibson** [comment]
This is more of a recommendation than something that needs to be codified. We do have some exceptions to the rule where one (often shared) FTL file has more than one prefix. 

We do add some additional linting for other things in https://github.com/mozilla/bedrock/issues/12209
