### ISSUE TITLE
WNP 83: Remove FTL file and create second de-* template

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#9636]
## Description

Remove FTL file and create German l10n HTML file. Add routes to filter by locale. 

Add a comment to the line, _"[space to save the magic](https://github.com/mozilla/bedrock/blob/master/l10n/en/firefox/whatsnew/whatsnew-fx83.ftl#L13)"_ with `save the good things you find`

**Comment by alexgibson** [comment]
If this saves some work, it's entirely possible to specify a config for an .ftl file, so that once it goes to Pontoon it will only be exposed for de. An example of such a config can be seen here: https://github.com/mozilla/bedrock/blob/master/l10n/configs/pontoon.toml#L118-L134
