### ISSUE TITLE
404 page throws an error if locale relies on old strings

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9642]
## Description

https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874884/?query=is%3Aunresolved

### Steps to reproduce

1. ) Visit the 404 page for a locale that still relies on the older strings / messaging contained in the template, such as https://www.mozilla.org/el/404

### Expected result

There should be no error in the console.

### Actual result

```
Uncaught TypeError: can't access property "classList", document.getElementById(...) is null
```

### Environment

N/A

**Comment by amychurchwell** [comment]
Fixed in #9654
