### ISSUE TITLE
Type error on /firefox/new/ in older Edge browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9644]
## Description

Some older versions of Edge (e.g. v15) seem to hit an error on /firefox/new/

```
Object doesn't support property or method 'forEach'
```

https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874825/events/

https://github.com/mozilla/bedrock/blob/master/media/js/firefox/new/desktop/download.js#L160

Suprisingly it seems to support `IntersectionObserver`, but not `forEach` on Node Lists.

**Comment by dougmellon** [comment]
Do you mind if I take a shot at this?

**Comment by dougmellon** [comment]
Currently working on this.
