### ISSUE TITLE
Path being dropped when forwarding to www

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9653]
## Description

mozilla.org URLs entered without the www are dropping the path when forwarding to www.

### Steps to reproduce

Click: https://mozilla.org/en-US/firefox/unfck

### Expected result

Go here https://www.mozilla.org/en-US/firefox/unfck

### Actual result

Goes here https://www.mozilla.org/en-US/

### Environment

Firefox Nightly for iOS

**Comment by stephaniehobson** [comment]
@pmac is this related at all to the problem we had with firefox.com?

**Comment by pmac** [comment]
probably so. the mozilla.org redirector was just moved to the same system, but this should still work. I'll open an issue with them.

**Comment by pmac** [comment]
The it team deployed a fix and it looks good to me. Thanks for the quick fix Alan and Scott!
