### ISSUE TITLE
JS error on MPL pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9655]
## Description

https://www.mozilla.org/en-US/MPL/

```
Uncaught TypeError: can't access property "setAttribute", e is null
    <anonymous> https://www.mozilla.org/media/js/BUNDLES/basic-article.5c696d9ca60d.js:1
    <anonymous> https://www.mozilla.org/media/js/BUNDLES/basic-article.5c696d9ca60d.js:1
```

https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874887/events/

**Comment by stephaniehobson** [comment]
Going to solve this one in Protocol: https://github.com/mozilla/protocol/issues/643

**Comment by alexgibson** [comment]
Fixed in latest Protocol update 🎉
