### ISSUE TITLE
unfck page non FX A/B test

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9660]
## Description

**Page**
https://www.mozilla.org/firefox/unfck/

**Audience**
EN non FX

**Test Plan**
https://docs.google.com/document/d/1uS-FqEjbW8fI_OG0cuF5V3uKcvcXa56LSh95QuEFi9U/edit?usp=sharing

**Goal**
Better understand user behavior on this page when we remove additional CTAs. We will measure FX downloads.

**Comment by slightlyoffbeat** [comment]
Ready for review: https://app.convert.com/#/projects/1003343/summary/100310891

**Comment by slightlyoffbeat** [comment]
QA checklist:

- [ ] double check audience and distribution settings against test plan
- [ ] check that goals are coming through on live report
- [ ] check code. V2 is more changes than the usual test, and requires extra attention
- [ ] make sure FX gets normal page and nonFX gets modified page
- [ ] test on mobile

**Comment by stephaniehobson** [comment]
- All the right goals are being tracked. The primary goal is related to share links and I think the primary goal of this experiment is downloads. 
- The code for V1 is working but could be simplified to `.mzp-c-hero ~ * {display: none;}` (if there's a benefit to simplifying, there's also a benifit to not messing with something that's working fine.)
- V2 App Store button not being logged when I trigger on my iPhone (and it's sluggish but prod is sluggish too, so it's not this experiment).

Logging off for Trivia, more in the morning but at first glance V2 looks great even though it's complicated.

**Comment by slightlyoffbeat** [comment]
Thanks.

I'm always for simplification, so I went ahead and used your suggestion.

V2 app store button is responsive, redirecting correctly and is triggering a goal or me on my android phone (chrome) and my ipad pro (safari). I have a few more people with iphones to help test tomorrow.

**Comment by stephaniehobson** [comment]
Had a more through look at the V2 code complicated as it is it's working well 🔥 

Dan and I are talking about the the mobile goals showing up on the live report in Slack.

**Comment by stephaniehobson** [comment]
After more testing: the mobile goal reporting is working properly, observed hiccups were because returning visitors and duplicate goal achievements are not logged.

So R+ 🧪

**Comment by alexgibson** [comment]
This experiment was done, closing out.
