### ISSUE TITLE
vpn.mozilla.org A/B test: adding price to CTA

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9661]
## Description

**Page**
vpn.mozilla.org

**Audience**
EN

**Test Plan**
https://docs.google.com/document/d/15PCMG4qatsMvrZKkjcqo8pV71-b0li3I8tfEJKQliso/edit?usp=sharing

**Goal**
Test if being more up front with pricing will result in more completed purchases

**Comment by slightlyoffbeat** [comment]
Test is created: https://app.convert.com/#/projects/10031066/summary/100310808

**Comment by slightlyoffbeat** [comment]
Test has approval from legal.

There is one CSP issue because test images are served from mozilla.org. Working with product team to resolve. Otherwise, this is good to test.

**Comment by slightlyoffbeat** [comment]
QA checklist:

- [ ] "Try" is changed to "Get" in CTAs
- [ ] all links to /r/vpn/subscribe has correct UTM parameters added
- [ ] V1 has price added to primary CTA in hero. Also has refund disclaimer under the main CTA
- [ ] V2 has refund disclaimer under the main CTA
- [ ] Primary goal is triggered (clicking on one of the get CTAs)
- [ ] Audience is set up correctly
- [ ] FAQ items expand correctly (something Kropp reported, but I can't duplicate)
- [ ] image is displaying correctly in Firefox & Chrome (after CSP issue is resolved)

**Comment by stephaniehobson** [comment]
Review feedback:

-There's a console.log statement in the JS for both experiments
-For V1 I'm not seeing the refund disclaimer under the main CTA:

![Screen Shot 2020-11-05 at 14 10 08](https://user-images.githubusercontent.com/854701/98303395-e09c3b00-1f72-11eb-9f00-a5b20edf8c44.png)

Other thoughts:

- The audience is set up correctly according to the experiment doc but I don't see Australia on the supported list, what happens if a user in an unsupported EN locale visits?
- You could add a height & width to the checkmark icon to avoid content shifting before/after it loads.

**Comment by slightlyoffbeat** [comment]
Thank you @stephaniehobson 

If an unsupported locale visits, they will simply get the regular page without any convert page injected. I believe for australia, they will receive a notice to join a waitlist to be notified when it will be available for them.

We discussed on slack, but to keep a record here: It was decided to add the disclaimer to V1 as well. This isn't currently reflected on the test doc.

also:
- console.log removed (oops)
- height and width added to checkmark icon

**Comment by slightlyoffbeat** [comment]
Pull request is in to fix CSP issue with test images:

https://github.com/mozilla-services/guardian-website/pull/971

**Comment by stephaniehobson** [comment]
This is looking good. Launch at will once the CSP issue is fixed. R+ 💵

**Comment by hoosteeno** [comment]
@slightlyoffbeat can you update with present blocker?

**Comment by slightlyoffbeat** [comment]
blocked because of issues with URL parameters and attribution: https://github.com/mozilla/fxa/issues/6925#issuecomment-738869774

cc: @hoosteeno

**Comment by hoosteeno** [comment]
@slightlyoffbeat can you follow up and see if the measurement issues are resolved? That puts us in a position to run this test when VPN lands on bedrock.

**Comment by slightlyoffbeat** [comment]
Thank Alex. I agree that we should close this and re-open with an approach that is specific to its new design and home.
