### ISSUE TITLE
Migrate CPG pages to Fluent (by end of Nov.)

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9666]
## Description

In #9614 we are changing strings on CPG pages. We need those pages to be migrated to Fluent. We need it all done in November.

---

#### Success Criteria
- [ ] Pages touched by #9614 are migrated to Fluent and those changes are merged/live.

**Comment by amychurchwell** [comment]
Blocked until limited locale config issue is resolved in Pontoon. Peiying is working with Matjaz.
Apparently a fix was put out, but still investigating.  https://bugzilla.mozilla.org/show_bug.cgi?id=1602896
