### ISSUE TITLE
Prototype vary on template A/B test helper

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9682]
## Description

In https://github.com/mozilla/bedrock/issues/9576 we prototyped a server-side solution that performs A/B test URL redirects for a % of traffic to the /firefox/new/ page. Whilst it seems to work pretty well, one of the problems we hit with that solution is that we needed to remove the CDN caching on certain locales (whilst an experiment is running), in order to maintain query parameters in the redirects. Whilst this hasn't caused any major performance issues, it's not ideal and could still struggle for some other higher traffic URLs (e.g. /whatsnew pages).

To mitigate this, we could try varying on _template_ instead of performing a redirect. This could be simpler overall, and would also mean we can likely retain some better caching of the pages via the CDN. Another benefit here is that performing 302 redirects for a large % of traffic has potential to confuse crawlers, so varying on template might be less confusing (at least for smaller experiments that only alter pages in minimal ways).

Possible feature set:

- Vary on template for a % of traffic, per locale.
- Configurable on any URL / View via a helper.
- Maintain same query params (should come for free?)
- Ability to force a variation to show for testing / QA purposes (e.g. via an `?exp=[template-name]` param?
- Configurable via a switch (turn on / off, set locales & percentages).

**Comment by alexgibson** [comment]
/cc @pmac (we probably don't want to try this until the current experiment has ended)

Also cc @rraue for visibility / input

**Comment by alexgibson** [comment]
The A/B test in https://github.com/mozilla/bedrock/issues/9637 has ended, so this is unblocked.

I've added another suggestion that we should make this a helper that's easy to use on any URL, as I'm not yet sure on which page the next experiment will be.

**Comment by pmac** [comment]
Will this need to support more than one variation template at a time for a locale?

**Comment by alexgibson** [comment]
> Will this need to support more than one variation template at a time for a locale?

I think it's possible that we would want to test more than one variation at a time yes

**Comment by stevejalim** [comment]
Yeah, happy to chat about this. While spelunking the codebase, I came across [VariationMixin](https://github.com/mozilla/bedrock/blob/master/bedrock/utils/views.py#L8) which, in parts, might combine well with the waffle work done in https://github.com/mozilla/bedrock/pull/9622/

**Comment by alexgibson** [comment]
Closing as unplanned
