### ISSUE TITLE
JS error on /new in Firefox < 6.0

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9688]
```
o is undefined
```

https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874754/

**Comment by stephaniehobson** [comment]
I traced this to `document.querySelector('.join-firefox-content');` in join-modal.js

I suspect the problem is related to support for `querySelector` though, docs say it should be supported after Firefox 3.5.

**Comment by stephaniehobson** [comment]
@alexgibson Should we update the `createModal()` code in Protocol to handle this case gracefully? We can check if `content` exists before proceeding with the function but I'm not sure what to do if it's not found. Halt execution? Throw a custom error message? Proceed to the callback? (probably not?)

**Comment by alexgibson** [comment]
@stephaniehobson yeah, I'm undecided if it's worth updating Protocol for this. But if it was to do anything, I'd perhaps side with throwing an error? For bedrock (which has some feature detection helpers for older browsers), I think we can probably run this "join firefox" modal as a form of progressive enhancement, and older Firefox browsers can just get a download (which seems like the thing they need most here).
