### ISSUE TITLE
Add download buttons for non-fx user

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9712]
## Description

We added a download button for non-fx users on the detail compare pages and it increased the download rate by 17% (2p.p). We should do this for the following pages as well, just directly after the headline:

- https://www.mozilla.org/firefox/browsers/update-your-browser/
- https://www.mozilla.org/firefox/browsers/what-is-a-browser/
- https://www.mozilla.org/firefox/browsers/incognito-browser/
- https://www.mozilla.org/firefox/features/adblocker/
- https://www.mozilla.org/firefox/browsers/browser-history/

**Comment by alexgibson** [comment]
@rraue I noticed https://www.mozilla.org/firefox/features/adblocker/ already has both a primary / secondary download button in the page. It feels a little heavy to add another one there to me. Any suggestions, or should be leave the feature page out of this update?

**Comment by alexgibson** [comment]
Up on demo:

- https://www-demo1.allizom.org/en-US/firefox/browsers/update-your-browser/
- https://www-demo1.allizom.org/en-US/firefox/browsers/what-is-a-browser/
- https://www-demo1.allizom.org/en-US/firefox/browsers/incognito-browser/
- https://www-demo1.allizom.org/en-US/firefox/browsers/browser-history/
