### ISSUE TITLE
Send traffic to new convert.com test on /firefox

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9716]
This test is approved, reviewed, and ready to have traffic sent to it.

Audience: Mobile only, Android only, en-us
Traffic (given audience above): 72%

Full Test Plan:
https://docs.google.com/document/d/16W-gpAmN4ZE7WIYiUh3ux1-GisF_0VYrH-qqkVr4RZI/edit?usp=sharing

Test Link:
https://app.convert.com/#/projects/1003343/summary/10037932

**Comment by slightlyoffbeat** [comment]
@pmac @alexgibson Hello! Do either of you have the bandwidth to help with this?

Let me know if/when this happens and I'll turn the test on.

**Comment by pmac** [comment]
This sounds like we'd need to do it in Traffic Cop. Sound right @alexgibson?

**Comment by pmac** [comment]
Note: this is for the `/en-US/firefox/` URL.

**Comment by alexgibson** [comment]
> This sounds like we'd need to do it in Traffic Cop. Sound right @alexgibson?

Doing these types of redirects client side are probably my least preferred option, but I'm not sure if we have any other methods available right now? What's the status with the CDN, can we still use cloudflare workers?

**Comment by pmac** [comment]
We can do them server side but I don't know that we have the tools ready to go to send only mobile android traffic. If we do we could do basically the same thing we did with the recent `/firefox/new/` experiment. The CDN issue is still not fully resolved AFAIK.

**Comment by alexgibson** [comment]
When we we're redirecting using cloudflare we always just redirected a set % of traffic. Redirecting based on user agent was a feature we had not yet implemented. In order to do something like the criteria above we'd need to write something custom, so maybe TC is the easiest bet for now - but it's really going to hurt performance doing a client side redirect and then also loading Convert 😫

**Comment by alexgibson** [comment]
Ended up recoding this in Traffic Cop, which was done in https://github.com/mozilla/bedrock/pull/9789
