### ISSUE TITLE
Replace data attribute on sticky promo box

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9721]
## Description

The download button on the new sticky promo box has a download location of `other`:

https://github.com/mozilla/bedrock/commit/2cebfd9a092aacd1abf504b1e82f77425e8eac25#diff-bc737588539f2f59d1b6f56974cdd847c6cee9d49f676d95bb06958532c46bd4R11

We should make this `sticky-promo-box`. 

---

#### Success Criteria
- [ ] Improved data attributes live in production

**Comment by craigcook** [comment]
Merged in https://github.com/mozilla/bedrock/commit/c3540ca21fd719b99b69e68a05dbca0271c02afe
