### ISSUE TITLE
Sticky promo product logos should have explicit width and height attributes

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9728]
## Description

Picked up in Lighthouse report for https://www.mozilla.org/en-US/firefox/new/

We should add explicit `width` and `height` attributes to help improve CLS scores.

https://www.webpagetest.org/lighthouse.php?test=201126_DiWB_0815e50aded186da78817b56de3b2a5f

**Comment by craigcook** [comment]
Merged in https://github.com/mozilla/bedrock/commit/c3540ca21fd719b99b69e68a05dbca0271c02afe
