### ISSUE TITLE
assets.mozilla.net 404 page could be improved

### ISSUE THREAD

**Issue by duallain** [mozilla/bedrock#9729]
## Description

The 404 page for assets.mozilla.net is not very user friendly.

### Steps to reproduce

1. Go to a page that doesn't exist (for example: https://assets.mozilla.net/annualreport/2019/notrealdoc)
1. see the ugly, no error.html page exists

### Expected result

We should return a custom error page that we like. (Could be as simple as `<h1>404</h1>`, but something we're reasonably happy with).

### Actual result

The aws cloudfront 404 error page is returned instead.

### Environment

Mac OS Catalina 10.15.7, Firefox 82.0.3 (64-bit)

**Comment by Ayushsunny** [comment]
I would like to fix this issue.
