### ISSUE TITLE
primary password vs master password 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9738]
## Description

The expression has changed from **master** password to **primary** password since Fx79. There are a few pages containing the outdated expression. 

## Describe the issue that you're seeing.

They exist in these files:
- en/firefox/browsers/compare/shared.ftl/
- en/firefox/features/password-manager.ftl
- en/firefox/privacy/book.ftl

## Expected result

Change from **master** password to **primary** password to reflect what the product says, and be consistent throughout mozorg site.

**Comment by alexgibson** [comment]
We should fix this, thank you
