### ISSUE TITLE
Update comparison pages (late 2020/early 2021)

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9750]
## Description

In late December, we'll meet to talk about ongoing maintenance of comparison pages. That work will certainly produce some change requests, which we can add to this issue. 

Meanwhile there's a bug on the Edge page, which we can batch up with this work.

Here's a list of changes (to grow before this bug is ready to work on)

- [x]  https://bugzilla.mozilla.org/show_bug.cgi?id=1680487

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by alexgibson** [comment]
Looks like this was done
