### ISSUE TITLE
Edge Browser page: book icon description not clear

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9752]
## Description
The sentence of`In Edge you just tap on the small book icon and browser to get a clean easy-to-read UI.` can be found [here](https://pontoon.mozilla.org/he/mozillaorg/en/firefox/browsers/compare/edge.ftl/?string=212885) in Pontoon or on [this page](https://www-dev.allizom.org/en-US/firefox/browsers/compare/edge/).

here is the whole paragraph: `Firefox and Edge both offer excellent reading modes. With Firefox, you just tap on the small icon in the search bar and the browser strips down all unnecessary elements and presents you a clean looking article. In Edge you just tap on the small book icon and browser to get a clean easy-to-read UI.`

### Expected result

Rewrite the last sentence so it is understandable. Is it about the easy to read UI or about easy to read article?

**Comment by craigcook** [comment]
This seems like another copyediting goof.

I suggest "In Edge you can click on the small book icon to get a clean, easy-to-read page."

**Comment by peiying2** [comment]
Add a "comma" after `In Edge, ...`.
