### ISSUE TITLE
Remove ARM processor UA detection for Windows

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9753]
## Description

I managed to get hold of an ARM64 Windows device for testing downloads and found the following:

- Our ARM64 UA detection on mozorg does not work, at least on my device. The user agent string does not provide any kind of hint to reveal that it has an ARM64 processor. As a result, the regular Windows stub installer is served when visitng /thanks, instead of the ARM64 build.
- The stub installer already has (much more reliable) built in logic for figuring out the currect build, and downloads the ARM64 version of Firefox correctly.

Given the above, I think we can simply remove our existing (bad) logic for ARM64 detection via UA strings.

---

#### Success Criteria
- [ ] ARM UA detection for Windows is removed from the website.

**Comment by alexgibson** [comment]
Looks like we still use ARM UA detection for Linux, so some of the logic will have to stay until we can unfurl that also. For now, we can remove the Windows detection.

**Comment by hoosteeno** [comment]
@amychurchwell to review
