### ISSUE TITLE
Sync page incorrect UI reference: "Sign in to Firefox", not "Sign in to Sync"

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9755]
## Description

This [string](https://pontoon.mozilla.org/sl/mozillaorg/en/firefox/sync.ftl/?string=216016) states: `Open the menu in the top right of { -brand-name-firefox } and select <strong>“Sign in to { -brand-name-sync }”</strong>.` This is incorrect. It should be `Sign in to Firefox` according to the UI.

### Steps to reproduce

Make sure you log out of your account
- Go to https://www.mozilla.org/en-US/ - 
- Follow the instruction according to the string above.
- On the top of the drop down menu, it says `Sign in to Firefox`.

### Expected result

Change from `Sign in to Sync` to `Sign in to Firefox.`

**Comment by 123mansha** [comment]
@peiying2 can i take this up??

**Comment by peiying2** [comment]
This one was fixed: https://pontoon.mozilla.org/projects/mozillaorg/en/firefox/sync.ftl/?string=216016
