### ISSUE TITLE
Add link to /firefox in site navigation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9757]
## Description

There's no easy way to get to the /firefox home page in our site navigation. It still sees a lot of traffic and is an important page for both sessions/conversions and SEO. We should find a way to add a link to it that makes sense. Either in the main nav or the sub nav.

---

#### Success Criteria
- [ ] The /firefox page is no longer orphaned in our navigation.

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by alexgibson** [comment]
This is still an issue today - needs IA / UX / SEO input

**Comment by janbrasna** [comment]
This has been fixed with #14222 — the "Firefox Browsers" › "View all Firefox Browsers" link is `/firefox` now.
