### ISSUE TITLE
Migrate translate blog post to www

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9759]
## Description

Migrate translate blog post https://blog.mozilla.org/firefox/translate-the-web/ to www with updated copy.

Design Template: same as https://www.mozilla.org/en-US/firefox/browsers/windows-64-bit/

Copy: https://docs.google.com/document/d/1IjNb9oGR4G4ljKUXppWc0N6GlJkHuBd3QqT9wleFB-c/edit

Url: /firefox/features/translate/

Subnav like all /features/ pages

---

#### Success Criteria
- [x] Page is coded
- [ ] Blog article is redirected 301 to the new url on www
- [x] Add page to /more
- [x] Add page to /features

**Comment by stephaniehobson** [comment]
Demo of the page: https://www-demo-pr-9771.herokuapp.com/en-US/firefox/features/translate/

Still to code: the language list at the bottom.

**Comment by hoosteeno** [comment]
@stephaniehobson In the attached screenshot, the big orange translation illustration is cut off and becomes really hard to understand. Is this the desired effect?

![image](https://user-images.githubusercontent.com/94519/102113293-1942f600-3df6-11eb-9d3a-693a54e32c14.png)

I see the cut-off at appx. 768px - 1365px wide in Firefox.

**Comment by stephaniehobson** [comment]
@hoosteeno  This is the current functionality of the Protocol component and I don't think it's worth custom coding something different for this page until we see substantial traffic to it.
