### ISSUE TITLE
Migrate Password blogpost to www

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9760]
## Description

Migrate password blog post https://blog.mozilla.org/internetcitizen/2017/01/25/better-password-security/ to www with updated copy.

Design Template: same as https://www.mozilla.org/en-US/firefox/browsers/windows-64-bit/

Copy: https://docs.google.com/document/d/1cKki_xH0AeZEcBOD7sqw_O0XpKazYRkUA70i-L0v2C4/edit#

Url: /firefox/privacy/safe-passwords/

Subnav like all /firefox/privacy/ pages, this page added to the subnav

---

#### Success Criteria
- [x] Page is coded
- [ ] Blog article is redirected 301 to the new url on www
- [x] Add page to /more
- [x] Link page in subnav of firefox/privacy/

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by stephaniehobson** [comment]
Sorry @Ayushsunny it's already been assigned.

**Comment by Ayushsunny** [comment]
> Sorry @Ayushsunny it's already been assigned.

Ohh! I'm really sorry Stephanie. and yeah if there is any issue related to Web platform please assign me
