### ISSUE TITLE
Migrate fingerprinting blog post to www

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9761]
## Description

Migrate password blog post https://blog.mozilla.org/firefox/how-to-block-fingerprinting-with-firefox/ to www with updated copy.

Design Template: same as https://www.mozilla.org/en-US/firefox/browsers/windows-64-bit/

Copy: https://docs.google.com/document/d/19pCoqieDwUeT2BQ7YLRnp2VweKPgr8jjy787F0Ygi58/edit

Url: /firefox/features/block-fingerprinting/

Subnav like all /features/ pages

---

#### Success Criteria
- [x] Page is coded
- [ ] Blog article is redirected 301 to the new url on www
- [x] Add page to /more
- [x] Add page to /features
- [x] Link this page from /new (Block Protect you Privacy - Linktext "Fingerprinter Blocking")

**Comment by stephaniehobson** [comment]
Demo of page: https://www-demo-pr-9771.herokuapp.com/en-US/firefox/features/fingerprinting/
