### ISSUE TITLE
Edits to description of MoFo on mozilla.org homepage

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/bedrock#9766]
## Description

About 50% of the way down the Mozilla.org homepage, a banner-style graphic links over to the Mozilla Foundation under a headline of "Support a Healthy Internet."  The text under that headline reads ... "The not-for-profit Mozilla Foundation supports open-source apps, web literacy curriculum, gender equality in tech and more." 

... and while MoFo does support those concepts in principle, they're no longer active program areas and do not accurately represent the work that the Foundation does, and should be updated.  (The headline and graphic image are fine as is.)

New text should read ... "The non-profit Mozilla Foundation supports online privacy & security, trustworthy artificial intelligence (AI), accountability for big tech corporations, and more."

Thanks!

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

**Comment by Ayushsunny** [comment]
I wanna fix this issue
