### ISSUE TITLE
Add sticky promo box for downloads

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9767]
From this [pitch](https://docs.google.com/presentation/d/1zvJ-02NoXdmqCgw77TnP8GVdONYyUWITmyWfAd-3UP8/edit#slide=id.ga2fdac9f2d_0_0) and tracked in this [Trello card](https://trello.com/c/N6FbWQln/168-add-floating-promo-box-for-downloads-to-20-pages) (both Mozilla only links, sorry.)

Add a sticky promo box which:
- displays only to desktop users
- display only to non-Firefox users
- promotes the desktop download

To the following pages:

- [ ] /firefox/releasenotes
- [ ] /firefox/features/adblocker/  
- [ ] /firefox/features/bookmarks
- [ ] /firefox/features/fast
- [ ] /firefox/features/independant
- [ ] /firefox/features/memory
- [ ] /firefox/features/password manager
- [ ] /firefox/features/private browsing
- [ ] /firefox/features/safe browser
- [ ] /firefox/browsers/best-browser
- [ ] /firefox/browsers/browser-history
- [ ] /firefox/browsers/incognito-browser
- [ ] /firefox/browsers/what is a browser
- [ ] /firefox/browsers/win 64
- [ ] /firefox/browsers/Brave
- [ ] /firefox/browsers/Opera
- [ ] /firefox/browsers/Chrome
- [ ] /firefox/browsers/IE
- [ ] /firefox/browsers/Edge
- [ ] /firefox/browsers/Safari

To facilitate this work these pages can be switched from the Mozilla theme to the Firefox theme (got the okay for this from @rraue who commissioned the pages)

- [ ] /firefox/browsers/what-is-a-browser/
- [ ] /firefox/browsers/incognito-browser/
- [ ] /firefox/browsers/browser-history/
- [ ] /firefox/browsers/update-your-browser/ (not getting a promo but should be updated as well)

**Comment by maxxcrawford** [comment]
@stephaniehobson Thanks for whipping this card into shape. I'll get started directly.

**Comment by hoosteeno** [comment]
@stephaniehobson to review today, @maxxcrawford to complete this week.

**Comment by hoosteeno** [comment]
@maxxcrawford to complete this week -- 1/26 complete.
