### ISSUE TITLE
Enable evergreen WNPs even for for locales with no content

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9769]
## Description

As part of our WNP process refactor [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1680091), we're changing how the releng/relman teams configure WNP moments. We've asked them to open a WNP for every locale Firefox includes. 

In a handful of locales, WNP is not activated. That means they get redirected to the en-US version ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1681266)), which is a VPN pitch in WNP84, and that's definitely not the intent. Instead, those locales should see an en-US version of the evergreen page. 

Can we change how locale redirects work in WNPs, or change the activation status of WNPs, so that every Firefox locale can see a WNP?

* If a version-specific WNP exists for the preferred locale, show it
* If no version-specific WNP exists for the preferred locale, show the evergreen WNP

---

#### Success Criteria
- [ ] The above is true in production
- [ ] The [bug is closed](https://bugzilla.mozilla.org/show_bug.cgi?id=1681266)

**Comment by alexgibson** [comment]
PR to set the activation threshold for these pages to 0: https://github.com/mozmeao/www-l10n/pull/9

**Comment by pmac** [comment]
VPN availability is only certain countries, so perhaps we detect and redirect users in those countries and locales to a VPN page, and everyone else gets an evergreen page?

**Comment by alexgibson** [comment]
> VPN availability is only certain countries, so perhaps we detect and redirect users in those countries and locales to a VPN page, and everyone else gets an evergreen page?

If we're mostly wanting to solve this for the immediate use case (VPN), then it's certainly another option. It would likely require a different issue though (refactoring our /whatsnew geo-redirector to be opt-in for VPN, rather than opt-out, which is what we do for China)

**Comment by pmac** [comment]
> It would likely require a different issue though (refactoring our /whatsnew geo-redirector to be opt-in for VPN, rather than opt-out, which is what we do for China)

Yeah. That is a bit more work. If it's only a handful of locales then I like your strategy in the above PR.

**Comment by alexgibson** [comment]
I'll defer to Justin here, but (iiuc) this request also encompasses some simplification for how we handle /whatsnew pages in general (i.e. relieving releng from needing to maintain a manual list of locales to open).

Thoughts here, @hoosteeno ?

**Comment by hoosteeno** [comment]
Unless doing so is problematic, let's pick the solution that's better at supporting the [WNP process refactor effort](https://bugzilla.mozilla.org/show_bug.cgi?id=1680091).

**Comment by alexgibson** [comment]
https://github.com/mozmeao/www-l10n/pull/9 has merged, but I don't yet see the active locale list in an updated state. Is there anything additional we need to do?

**Comment by pmac** [comment]
Oh! 🤦‍♂️ We should have manually added those locales to the list. The list is only updated when changes are made.

**Comment by alexgibson** [comment]
PR to activate the full prod locale list https://github.com/mozmeao/www-l10n/pull/10

**Comment by alexgibson** [comment]
Looks like this is fixed:

- https://www.mozilla.org/fa/firefox/84.0/whatsnew/all/
- https://www.mozilla.org/bs/firefox/84.0/whatsnew/all/
- https://www.mozilla.org/af/firefox/84.0/whatsnew/all/
