### ISSUE TITLE
Epic: Stand up a holding page for input.mozilla.org

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9770]
## Description

input.mozilla.org currently redirects to a 3rd party-hosted site. We want to stand up a page that is on-brand and is hosted at ideas.mozilla.org. input.mozilla.org should redirect there.  

We need...

* approved content for the page (approved by content owner, brand)
* a design for that page (approved by content owner, brand, dev)
* a hosting plan for the page (approved by dev, websites lead)
* a coded page launched at ideas.mozilla.org 
* a redirect from input.mozilla.org -> ideas.mozilla.org

This is an epic and related issues will be linked below. 

The work is part of a larger effort to relaunch input.mozilla.org. [Mozilla-staff-confidential brief for that here](https://docs.google.com/document/d/1avrQWbiWg8Ibi_NK2s6ONsz1c2dsFaOr7qcL5VdlXfE/edit#). 

This work is a greenlit pitch [described here](https://trello.com/c/aMnYBmwZ/149-ideasmo-coming-soon-placeholder-page).

---

#### Issues
- [ ] #issue-number
- [ ] #issue-number

**Comment by hoosteeno** [comment]
Discussion about hosting in this slack thread: https://mozilla.slack.com/archives/G7ACJHJCB/p1607396906231200

**Comment by hoosteeno** [comment]
I moved this back into "not ready" as it appears to have made the same move in Trello.

**Comment by stephaniehobson** [comment]
They're going to have the real site in the next week or two so there's no need for a placeholder anymore.
