### ISSUE TITLE
Standardize GA data-attributes for download buttons

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9774]
## Description

From some [discussion](https://github.com/mozilla/bedrock/pull/9754#discussion_r538671894) in previous PRs it seems like our app store download badges are missing some of the common GA data attributes that our regular download buttons contain.

Example:

Play Store badges have: `data-link-type="download" data-download-os="Android"`.
App Store badges have: `data-link-type="download" data-download-os="iOS"`.
Download buttons have: `data-link-type="download" data-download-os="Desktop" data-display-name="macOS" data-download-version="osx"` (macOS example)

Should both desktop and mobile buttons be the same, or are some attributes optional? If some are optional, then we should document the reasons why it appears in some places and not in others. 

It's not easy to tell, based on [our docs](https://bedrock.readthedocs.io/en/latest/analytics.html) that seem to suggest something entirely different:

Data Attribute | Expected Value
-- | --
data-link-type | ‘Desktop’, ‘Android’, or ‘iOS’
data-download-os | name or text of the link
data-download-version | ‘standard’, ‘developer’, ‘beta’

I'm guessing our docs are incorrect? What should the rules be?

#### Success Criteria
- [ ] Data attributes are standardized for both mobile and desktop.
- [ ] Documentation is up to date.

**Comment by amychurchwell** [comment]
My guess is that the docs are incorrect.

I don't know enough about how these attributes are used in GA to make a call. Maybe it is worth huddling up with data science to get some clarity on what requirements should be?

I will say, it seems like we can safely say that `data-download-os` should be the os and not "name or text of the link"

(An issue that is tangentially relevant (https://github.com/mozilla/bedrock/issues/7392) about the GA conflict in using both `data-link-type` and `data-button-name` that.)

**Comment by hoosteeno** [comment]
Here is how the data attributes from desktop download buttons presently** pass into GA through GTM:

```
event category = pageId + "Interactions"
event action = "Firefox Download"
event label = "Firefox for " + data-download-os
custom dimension 27 = data-download-version
custom dimension 28 = data-download-language
custom dimension 15 = data-download-location
```

The event values are used far more than the custom dimensions, because they end up powering goals. Looks like only data-download-os is required for them. The custom dimensions come in handy now and then, and I think there is no harm in including them on HTML elements if doing so helps to standardize our helpers somehow -- but probably not worth special effort to include on mobile links now.

** We are trying to simplify events and make them more powerful via a new events architecture in https://github.com/mozilla/bedrock/issues/9196. It's not ready to roll out yet.

**Comment by alexgibson** [comment]
> My guess is that the docs are incorrect.

Yeah, it looks like `data-link-type` should be `download` as you point out. Also I notice the expacted values for `data-download-version` seem incorrect.

> The event values are used far more than the custom dimensions, because they end up powering goals. Looks like only data-download-os is required for them, and it's essential because that's how our goals around downloads are counted.

I think we should document which attributes are required and which are optional, so we can avoid amiguity or guessing in code reviews.

Let's leave this issue open for when we can prioritise standardizing these values throughout the code base, but for now let's at least make sure our docs reflect reality.

Thanks both!

**Comment by alexgibson** [comment]
Closing this as fixed as https://github.com/mozilla/bedrock/pull/13093 added tracking in GA4
