### ISSUE TITLE
Nightly /whatsnew page should get dark themed footer

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9783]
## Description

The Nightly /whatsnew page has a dark theme color but currently ets the light themed footer:

![image](https://user-images.githubusercontent.com/400117/101894087-8d369180-3b9d-11eb-92b0-049a235ccf95.png)

### Steps to reproduce

Visit: https://www.mozilla.org/en-US/firefox/84.0a1/whatsnew/all/

### Expected result

Footer should use dark theme.

### Actual result

Footer uses the light theme.

### Environment

N/A

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by diabitbol** [comment]
you may have an other add-on activated that prevent you to change the theme

**Comment by SnehVachhani** [comment]
i am working on it.
