### ISSUE TITLE
Missing database table while running the project

### ISSUE THREAD

**Issue by nizz009** [mozilla/bedrock#9787]
## Description

When the project is setup locally on desktop by following the instructions for [Local Installation](https://bedrock.readthedocs.io/en/latest/install.html#local-installation) in the [Bedrock Documentation](https://bedrock.readthedocs.io/en/latest/install.html), an error is generated while running the application using the `npm start` command which indicates a missing  _product_details_productdetailsfile_ table.

### Steps to reproduce
 
1. Clone the repository.
2. Create a virtual environment inside the project directory as stated in the [documentation](https://bedrock.readthedocs.io/en/latest/install.html#local-installation).
3. Install the required dependencies and the modules for the project.
4. [Run the tests](https://bedrock.readthedocs.io/en/latest/install.html#local)
5. [Run the application](https://bedrock.readthedocs.io/en/latest/install.html#id2) with `npm start` command.

### Expected result

The project should start running.

### Actual result

An error message is displayed in the CLI with:
> django.db.utils.OperationalError: no such table: product_details_productdetailsfile

 and a new tab opens up with localhost:8000 but nothing shows up.
The entire error is mentioned in the following attachment:

[bedrock_issue.txt](https://github.com/mozilla/bedrock/files/5697431/bedrock_issue.txt)

### Environment

_Operating System:_ Windows 7 Ultimate (64-bit)

**Comment by pmac** [comment]
I'm not sure the Django side of things will run on Windows. I believe we've had people successfully run it in the subsystem for Linux on Windows 10, but other than that Docker is going to be your best bet for successfully running the site locally.

**Comment by nizz009** [comment]
Hello! Apologies for the delayed reply. 
I tried installing Docker toolbox (since I am using Windows 7) but I am having some troubles in installation of Docker so I thought of trying local installation.

**Comment by alexgibson** [comment]
Closing this as wontfix. I'm not sure the site is very easy to run on Windows, but if you're still trying feel free to reopen.
