### ISSUE TITLE
Decom or Keep https://www.mozilla.org/en-US/firefox/enterprise/signup/

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#9788]
## Description
As part of researching all things SalesForce I came across ye olde enterpise signup form. This submits to:

https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8"

I think Lauren needs to make the call if we still need this form. If so, we will need a new endpoint come February. If not we can decom this page.

---

#### Success Criteria
- [x] A decision on keep or decom is made. 
- [ ] Based on the above we keep and change the form endpoint or we decom.

**Comment by alexgibson** [comment]
If this helps to inform any decisions, this sign up form has been orphaned for some time, and is no longer linked from https://www.mozilla.org/en-US/firefox/enterprise/. It hasn't seen any significant traffic in the past year.

**Comment by LaurenNiolet** [comment]
Helpful @alexgibson 

yes, we can decommission it.
