### ISSUE TITLE
en/firefox/privacy/passwords.ftl  didn't come through on www-l10n repo

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9795]
## Description
[This PR](https://github.com/mozilla-l10n/www-l10n/pull/154/files) including the passwords.ftl file didn't come through to the www-l10n repo/Pontoon. 

### Expected result

Check code and recommit the file through a new PR. 

### Actual result

Land the file in the www-l10n repo and Pontoon.

**Comment by peiying2** [comment]
@craigcook

**Comment by peiying2** [comment]
Looks like the file is under firefox/privacy/... path, and the config contains info for .../privacy/book.ftl https://github.com/mozilla-l10n/www-l10n/blob/f2dde659c6cae44c6f5ac79a71ae3071d8bb6488/configs/pontoon.toml#L139. Does it block the release of passwords.ftl from coming through? Notice that it is not available for any languages in Pontoon.

**Comment by craigcook** [comment]
Hm yeah, not sure what's wrong. The file is there but clearly something about that rule in the config is making it invisible to Pontoon. ccing @pmac as well.

**Comment by alexgibson** [comment]
Looks like there was no config specified for /privacy in general, so I think we just need to add something that covers this file
