### ISSUE TITLE
[l10n] some string IDs show up in localizable content

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9802]
## Description
1). The [Fingerprint file](en/firefox/features/fingerprinting.ftl) in Pontoon contains string ID in the localizable content:

- features-fingerprinting-the-practice-of 
- features-fingerprinting-the-latest-firefox
- features-fingerprinting-and-its-not 
- features-fingerprinting-you-probably-wouldnt

2). This one with HTML tagging issue
https://pontoon.mozilla.org/nl/mozillaorg/en/firefox/features/translate.ftl/?string=217946 - extra space in `<a { $attrs } >`

3). https://pontoon.mozilla.org/it/mozillaorg/en/firefox/features/translate.ftl/?string=217952 
`The { -brand-name-google } Translate extension for ...`, missing `To` in `To Google Translate`.

### Expected result

- Localizable string doesn't contain string ID.
- Clean HTML tag (not sure if this can cause problem in .ftl file format).

@craigcook

**Comment by peiying2** [comment]
@craigcook Adding more findings in the Description area. I will make numbered items so it is easy to track.

**Comment by craigcook** [comment]
Sorry, can you explain what you mean by "contains string ID in the localizable content"?

There were several variables surrounded by double-braces `{{ ... }}` instead of single braces `{ ... }` and I've fixed those but it doesn't seem to cause any problems, just a formatting inconsistency.

**Comment by peiying2** [comment]
https://pontoon.mozilla.org/cy/mozillaorg/en/firefox/features/fingerprinting.ftl/?string=217968 - click on this link, and see the string in the middle panel: 
`features-fingerprinting-the-practice-of = The practice of fingerprinting allows you to be <a {{ $url_tracked }}>tracked for months</a>, even when you clear your browser storage or use private browsing mode — disregarding clear indications from you that you don’t want to be tracked. Despite a near complete agreement between <a {{ $url_standards }}>standards</a> <a {{ $url_bodies }}>bodies</a> and <a {{ $url_browser }}>browser</a> <a {{ $url_vendors }}>vendors</a> that fingerprinting is <a {{ $url_harmful }}>harmful</a>, its use on the web <a {{ $url_has }}>has</a> <a {{ $url_steadily }}>steadily</a> <a {{ $url_increased }}>increased</a> over the past decade.`

**Comment by peiying2** [comment]
> Sorry, can you explain what you mean by "contains string ID in the localizable content"?

`features-fingerprinting-the-practice-of = ` should not show up on the Pontoon dashboard. Localizers should see only the string to localize, not the string ID.

**Comment by craigcook** [comment]
Ah! Now I follow. That does indeed some to be some side effect of the double braces, so hopefully that will be fixed soon.
