### ISSUE TITLE
Font is incorrect on "Firefox products are designed to protect your privacy" text at smaller screen sizes

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla/bedrock#9803]
## Description

When a window or screen size is small enough, the font on the "Firefox products are designed to protect your privacy" text is in Zilla Slab, not Metropolis.

### Steps to reproduce

1. Open mozilla.org with a small, phone sized window, or just open it on your phone.
2. Observe the font.
3. Optionally, make the window bigger to see the expected result.

### Expected result

The font for the "Firefox products are designed to protect your privacy" text should be Metropolis, not Zilla Slab.

### Actual result

At small screen/window sizes, the font for "Firefox products are designed to protect your privacy" text is Zilla Slab, not Metropolis.

![Small window size](https://user-images.githubusercontent.com/17863082/102681453-7987be00-418f-11eb-976a-18a1a8845892.png)

![Large window size](https://user-images.githubusercontent.com/17863082/102681459-89070700-418f-11eb-9dd2-32c28deaefbc.png)

### Environment

Firefox 84 on Windows 10. Also observable on Firefox/Safari on iOS 14.3.

**Comment by alexgibson** [comment]
Thanks for the report!

**Comment by lolrepeatlol** [comment]
Hmm, I'm still seeing the issue. Is the fix just not live yet?
