### ISSUE TITLE
Migrate /legal/ pages to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9808]
## Description

https://www.mozilla.org/en-US/about/legal/

---

#### Success Criteria
- [ ]  Page is using Fluent in production along with existing migrations

**Comment by Aayushap1** [comment]
Hello @alexgibson , I would like to work on this issue please assign it to me.

**Comment by Aayushap1** [comment]
I am new to the Mozilla organization please let me fix this issue.
And help me to make my 1st contribution to Mozilla.
