### ISSUE TITLE
Remove .lang machinery

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9810]
## Description

Once the last mozorg pages have been migrated to Fluent, we can remove the .lang machinery and documentation supporting the old L10n system.

---

#### Success Criteria
- [ ] Legacy .lang code is removed from the website.
- [ ] L10n documentation updated.

**Comment by Patil2099** [comment]
Hi, @alexgibson I would love to help to solve this issue.

**Comment by alexgibson** [comment]
I think we can close this one out, fixed in https://github.com/mozilla/bedrock/pull/10660

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/10660
