### ISSUE TITLE
Approve "wontfix" Fluent migrations

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9812]
## Description

As part of retiring .lang support in bedrock, there is a small collection of pages for which I'm going to propose we mark as "wontfix" for porting their translations:

- https://www.mozilla.org/en-US/foundation/annualreport/2011/ (content is old and copy intensive, annual reports have not been localized post-2012)
- https://www.mozilla.org/en-US/foundation/annualreport/2012/
- https://www.mozilla.org/en-US/foundation/trademarks/policy/ (ja locale only and translations broken)
- https://www.mozilla.org/en-US/foundation/trademarks/list/ (ja locale only and translations broken)
- https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/ (ja locale only and translations broken)
- https://www.mozilla.org/en-US/foundation/feed-icon-guidelines/ (ja locale only)
- https://www.mozilla.org/en-US/foundation/feed-icon-guidelines/faq/ (ja locale only)

---

#### Success Criteria
- [x] Content is approved as wontfix for migrations (or is not content is migrated)

**Comment by hoosteeno** [comment]
R+, this is very sensible

**Comment by alexgibson** [comment]
/cc @peiying2 ^

We're not going to migrate the above pages to Fluent.
