### ISSUE TITLE
Add a warning/notice that Nightly will be updated once/twice a day

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9832]
## Description

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1685971

---

#### Success Criteria
- [ ] Nightly page has some info relating to update frequency.

**Comment by nox1134** [comment]
Hi @alexgibson! If no one is working on this issue, I'd like to take up this issue and work on it. How do I get started?

**Comment by Fkabir0** [comment]
HI can I work on this ?

**Comment by alexgibson** [comment]
It looks like this was fixed in https://github.com/mozilla/bedrock/pull/14068
