### ISSUE TITLE
Copy WNP84 template for WNP85

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9840]
## Description

WNP85 will be distributed starting 1/26. We should have final content in template launched on a page by 1/19, to give EU time to work with it.   

We may want to change something about this page -- copy, for example, to mention the recent VPN launch on new platforms. But let's start by duplicating the template from WNP84 to serve WNP85. 

---

#### Success Criteria
- [ ] WNP85 looks just like WNP84, and is ready for changes.

**Comment by alexgibson** [comment]
I spoke to Caro on the EU team and she asks if we can please make sure VPN gets shown for en-GB as well.

It's unclear if we'll do anything for de and fr given other competing priorities / resources in the short time frame we have. I'l update here if that changes, but for now de and fr can show the default /whatsnew page.

**Comment by alexgibson** [comment]
Small update here: the EU team are going to do something to promote Firefox Mobile for WNP 85. It will be hard-coded and something that's a small lift, so no dependency on the work happening here. 

I'll file a separate issue for it.
