### ISSUE TITLE
Monitor external links from www.mozilla.org

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9842]
## Description

Problem: We have long worried that some attack could replace a valid download link with a malicious one. 

Conceptual solution: We could build/buy/configure a monitoring service that alerts when a new external link appears on www.mozilla.org. This could run on a schedule. 

Imagine that such a monitoring service simply compares the prior list of external URLs to the current list, and notifies a distribution list about diffs. Would this make a devastating attack less likely? What other ways could we accomplish it?

---

#### Success Criteria
- [ ] This idea, or a better idea, are discussed/designed in comments on this issue

**Comment by alexgibson** [comment]
I've been thinking a bit about this, and I wonder if we could also leverage some existing alerting tools to help monitor the types of things we may want to cover (in addition to a link crawler perhaps).

As an example, we have JS error reporting in place now, so we can now start to validate things such as download links and surface anomalies as errors in Sentry? See https://github.com/mozilla/bedrock/issues/9854 and https://github.com/mozilla/bedrock/pull/9853 as an examples. This could potentially catch issues created by client side manipulation (e.g. malicioud extensions), which a crawler may not be able to detect.
