### ISSUE TITLE
Migrate Mozilla VPN landing page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9855]
## Description

We have the go-ahead to create a Mozilla VPN landing page on www.mozilla.org. This landing page will be updated and localized ahead of the VPN product being launched in Germany and France in Q1. The first step toward that effort will be to migrate the current landing page at https://vpn.mozilla.org/ to https://www.mozilla.org/products/vpn/.

Implementation requirements are forthcoming, pending a kickoff meeting next week.

- Pitch doc (Mozilla confidential): https://docs.google.com/document/d/1XrYp23LozHsSTmq-Ljau8pz8p3vb1xyThtCdDn4vcW0/edit?usp=sharing
- Analytics doc: https://docs.google.com/document/d/1uXeiVno6xUGttsjqfN_9YXzIdV66I9F2iFiQ8_XHKIg/edit?usp=sharing
- QA doc: https://docs.google.com/document/d/1-vkImox_A3a5xpX6B1Jt6F9EasivU8NsRXozPuwJ1MI/edit?usp=sharing

---

#### Success Criteria
- [x] Existing VPN landing page design is migrated to bedrock.
- [x] VPN waitlist invite page is migrated.
- [ ] Page is live in production for en-US only.

**Comment by alexgibson** [comment]
This is now up on demo:

https://www-demo1.allizom.org/en-US/products/vpn/
https://www-demo1.allizom.org/en-US/products/vpn/invite/

**Comment by hoosteeno** [comment]
@alexgibson fixing FxA params.

**Comment by Adityachaturvedi2906** [comment]
Hi, can I contribute to this? please guide me further.

**Comment by alexgibson** [comment]
Analytics doc: https://docs.google.com/document/d/1uXeiVno6xUGttsjqfN_9YXzIdV66I9F2iFiQ8_XHKIg/edit?usp=sharing
QA doc: https://docs.google.com/document/d/1-vkImox_A3a5xpX6B1Jt6F9EasivU8NsRXozPuwJ1MI/edit?usp=sharing

**Comment by alexgibson** [comment]
This is now ready for code review.

**Comment by alexgibson** [comment]
We have the all-clear from data science to launch this. Will aim to merge / push on Monday 🎉
