### ISSUE TITLE
Miss matched brand fonts on firefox/privacy/products

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9865]
Both headlines should be in the Firefox theme:

<img width="1191" alt="Screen Shot 2021-01-21 at 15 58 10" src="https://user-images.githubusercontent.com/854701/105539291-6a71bf80-5ca9-11eb-8e98-dbfe88107a9a.png">

**Comment by Sayantani-sunshine** [comment]
Hello. I am interested to  contribute here.I am a first timer.Can you help me out a little bit?

**Comment by craigcook** [comment]
This was fixed with https://github.com/mozilla/bedrock/pull/10163
