### ISSUE TITLE
Odd hover state on join modal for firefox/new

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#9866]
The blue button should have white text before hovering. When I hover it flashes cyan before going back to the light purple. (Might be related to visited state). Note the modal only appears for existing Firefox users.

<img width="571" alt="Screen Shot 2021-01-22 at 12 01 25" src="https://user-images.githubusercontent.com/854701/105539464-a2790280-5ca9-11eb-8057-19d18cbb98e7.png">

**Comment by craigcook** [comment]
Seems related to https://github.com/mozilla/protocol/issues/655 which I'm working on now.

**Comment by alexgibson** [comment]
I still see this even after the protocol update, seems to be related to some possible (?) custom visited link styles:

```css
.c-modal-overlay-contents a:visited {
    color: #d9bfff;
}
```

**Comment by Soumya0803** [comment]
Hi @alexgibson. I would like to work on this issue.

**Comment by alexgibson** [comment]
Thanks @Soumya0803!

Please take some time to read our [contributing guidelines](https://github.com/mozilla/bedrock/blob/master/.github/CONTRIBUTING.md) which contain some usefuly information to help get started. Once you have bedrock running locally, pull requests are welcome.

**Comment by mdaquib171** [comment]
I am a beginner at open source, please let me know if the issue is open.
And please suggest to me how to proceed further.
Thanks

**Comment by mdaquib171** [comment]
> The blue button should have white text before hovering. When I hover it flashes cyan before going back to the light purple. (Might be related to visited state). Note the modal only appears for existing Firefox users.
> 
> <img alt="Screen Shot 2021-01-22 at 12 01 25" width="571" src="https://user-images.githubusercontent.com/854701/105539464-a2790280-5ca9-11eb-8057-19d18cbb98e7.png">

I am a beginner at open source, please let me know if the issue is open.
And please suggest to me how to proceed further.
Thanks

**Comment by Soumya0803** [comment]
Hi @mdaquib171 I am working on this issue and will be raising a PR soon.
Thanks

**Comment by shouryam-kumar** [comment]
Hi, is the issue still open?

**Comment by shouryam-kumar** [comment]
Hi, is the issue still open? I would like to work on it if its open.

**Comment by alexgibson** [comment]
This bug has been sitting round for nearly a year. Despite some interest it's still not fixed, so I'm going to get this one done.

**Comment by alexgibson** [comment]
It seems that this is because the Protocol styles assume the modal content will contain light colored links: https://github.com/mozilla/protocol/blob/main/src/assets/sass/protocol/components/_modal.scss#L105

I've added an override in bedrock for now.
