### ISSUE TITLE
Send to device submissions fail on www.allizom.org

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9870]
## Description

Pages that use the send to device widget don't function as expected on www.allizom.org

### Steps to reproduce

1. Visit https://www.allizom.org/en-US/firefox/mobile/
2. Enter `success@example.com` in the "Get Firefox for Mobile" form.
3. Click "Send".

### Expected result

The form should submit successfully.

### Actual result

The form shows an error: "An error occurred in our system. Please try again later.".

In devTools, the XHR request shows a "403 Forbidden" response.

### Environment

Firefox Nightly

**Comment by stephaniehobson** [comment]
Probably not worth fixing in light of #9864 ?

**Comment by stephaniehobson** [comment]
Oh it's failing with an email, never mind, that's worth fixing.

**Comment by Ayushsunny** [comment]
I would like to work on this issue

**Comment by alexgibson** [comment]
Looks like this was fixed
