### ISSUE TITLE
/firefox/features/translate/: language list is hard coded, punctuation incorrect for some languages

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9872]
## Description
The hardcoded list of languages ends with an Oxford comma is not the correct punctuation in some languages. 

https://www-dev.allizom.org/zh-TW/firefox/features/translate/ 

### Steps to reproduce

Go to the above URL and scroll to the bottom of the page, review the language list and see the difference in punctuation in this section compared to zh-TW. Unfortunately, this page is not localized in some of the languages using different scripts. However, you can check the landing page of RTL languages, zh-CN, and more.

### Expected result

Display punctuation that is native to  the target language.

**Comment by stephaniehobson** [comment]
I looked for some way to generate a list and didn't find it. (I would have liked to have a localized "and" before the last item where appropriate.)

The only solution I can think of would be to open the entire string to localization. It would be 100% okay to have those languages localized. It just seem like a long list of languages people would not be familiar with. We could keep the list as the fallback if people don't want to translate that string though.

Does that sound like a good option to you? I don't want to overwhelm our translators.

**Comment by peiying2** [comment]
Actually the RTL part works, sorry about it. Let me update the comment/summary. 

On the language list, I am with you on not translating the languages. Those who read it  will know what it is, and ignore those they don't recognize. Let me check with other l10n drivers on their take of this.

**Comment by peiying2** [comment]
@stephaniehobson after checking with the l10n drivers, this list presents issues even for Latin based scripts. In some languages, the language name initial needs to be capitalized. Of course, what do you do with languages not in your script. The suggestion is to do away with the list here. Or can we make it not shown in the localized pages? The link to Google Translate page is sufficient. Thank you!

**Comment by stephaniehobson** [comment]
@rraue Is it okay to remove the list of locales that To Google Translate supports from the non-English pages?

**Comment by rraue** [comment]
Actually this is one of the main traffic drivers for this page and as I agree that the link gives these information to users somehow, search engines do not do this connection and even most user will not click, so I think this information is not crucial but a very big extra for users landing on the page and search engines to display the page as a solution for problems users search for. 

So I hope we will find a solution here. If punctuation is the problem, cant we set the list then for the locales where punctuation is different the way its different, or are there too many rules of punctuation?

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by stephaniehobson** [comment]
@Ayushsunny please look for issues with the [good first bug](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22) or [help wanted](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted+%F0%9F%91%8B%22) labels. Other issues are not ready for contributor work. Other information in our [Contributor Docs](https://github.com/mozilla/bedrock/blob/master/.github/CONTRIBUTING.md) may be helpful to you as well.

**Comment by stephaniehobson** [comment]
@peiying2 what do you think of changing it to a bulleted list?

<img width="823" alt="Screen Shot 2021-02-01 at 09 27 31" src="https://user-images.githubusercontent.com/854701/106494802-bbcf3b00-646f-11eb-9b30-e03e10436cb8.png">

**Comment by Ayushsunny** [comment]
> @Ayushsunny please look for issues with the [good first bug](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22) or [help wanted](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted+%F0%9F%91%8B%22) labels. Other issues are not ready for contributor work. Other information in our [Contributor Docs](https://github.com/mozilla/bedrock/blob/master/.github/CONTRIBUTING.md) may be helpful to you as well.

Thanks a lot Ma'am

**Comment by alexgibson** [comment]
@craigcook is this issue still relevant today in the overhauled feature pages?

**Comment by craigcook** [comment]
> @craigcook is this issue still relevant today in the overhauled feature pages?

Yes, the page is being ported to the new template with a few revisions but still includes the list of languages. I agree a bulleted list seems like the better option. I'll make it so.

**Comment by janbrasna** [comment]
This got revised in #14133 (adapting to own Translate feature instead of external service) and further improved in #14261 for non-EN locales iterating through the languages in their local name programatically (so smart, Blinky!) to avoid the need to expose them to l10ns. I think this could be closed now.

@peiying2 Is the current layout with the bulleted list and language names generated outside of FTL good enough even for locales you felt were most incompatible with the content now with the recent changes?

**Comment by craigcook** [comment]
I agree, I think we can consider this resolved both with the new page content and converting to a bulleted list. I'm also trying to find up-to-date info on supported languages so we can try to keep that page accurate.
