### ISSUE TITLE
Leadership page updates 2021-01-29

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9873]
## Description

We backed out one change from the PR at https://github.com/mozilla/bedrock-private/pull/88#issuecomment-765573290. We need to launch that change on Friday 2021-01-29.

---

#### Success Criteria
- [ ] The final change specified is PR'd in private repo and staged, or PR'd on the day of in public repo
- [ ] The change is merged and pushed on 2021-01-29

**Comment by maxxcrawford** [comment]
Thanks to @craigcook and @stephaniehobson for closing this out last Friday.
