### ISSUE TITLE
Epic: Rename Git Repo Branches To 'main'

### ISSUE THREAD

**Issue by duallain** [mozilla/bedrock#9894]
## Description

Using the new name of 'main' for the primary branch in our repos. Work includes doing the rename, locking down the old branch name, and ensuring the pipeline(s) continue to work after the rename.

Related jira story:
https://jira.mozilla.com/browse/SE-1401

Github information:
https://github.com/github/renaming

---

#### Issues
- [ ] bedrock
- [ ] www-config
- [ ] (Fill in this list)

**Comment by slightlyoffbeat** [comment]
note: We will need to look forward and find the right window of time to work on this.
