### ISSUE TITLE
Incorrect grammar in en/firefox/browsers/compare/shared.ftl

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9899]
## Description

The string has a grammatical mistake. https://pontoon.mozilla.org/sl/mozillaorg/en/firefox/browsers/compare/shared.ftl/?string=212668

It reads `This page updated semi-quarterly to reflect latest versioning and may not always reflect latest updates.`

### Expected result

Correction: This page *is* updated semi-quarterly to reflect latest versioning and may not always reflect latest updates.

**Comment by Bhavik-Ardeshna** [comment]
working on this issue

**Comment by Bhavik-Ardeshna** [comment]
Made PR please review it

**Comment by Bhavik-Ardeshna** [comment]
@peiying2
