### ISSUE TITLE
en/privacy/index.ftl - Mozilla not coded as a brand 

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9900]
## Description

I thought I called this out but I didn't verify that it was fixed: https://pontoon.mozilla.org/it/mozillaorg/en/privacy/index.ftl/?string=220089. 

Note Mozilla in `Mozilla Websites, Communications &amp; Cookies` is not coded as a brand in the string.

### Expected result

Update the string so it includes *Mozilla* as a brand in the string. 

@craigcook

**Comment by craigcook** [comment]
D'oh! I did change it but it got reverted back at some point. I'll fix.

**Comment by alexgibson** [comment]
Looks like this got fixed, closing
