### ISSUE TITLE
RRA recommendation: Establish peer review of content publication.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9901]
A recommendation in the [RRA for Contentful](https://docs.google.com/document/d/1_eAmy8iK4cMfEPVKSuUG0xPxeufV3fmUbKpSWdBMlGY/edit#heading=h.t1vwvhh7e6x9) suggests establishing peer review for content changes. This suggests a governance structure. 

Right now this governance is divided across all the different publication flows we have. Legal teams govern their content. Release notes teams govern their content. Engineers govern content that goes through engineering processes. Editorial teams publishing to blog posts govern their content.

Can we establish and enforce peer review in Contentful to avoid the worst-case scenario (malicious content published via the platform)? For example, can we require that two accounts click the "publish" button before content will go live? If we cannot, what other governance can we establish that addresses this concern?

**Comment by maureenlholland** [comment]
still relevant, we need to establish safeguards around publishing, [Workflows app](https://www.contentful.com/help/workflows-overview/) has potential to enforce this

**Comment by stevejalim** [comment]
FWIW this is somethig that's on the radar in a newer Wagtail-shaped form, as part of https://github.com/mozilla/bedrock/issues/14795
