### ISSUE TITLE
RRA recommendation: Automatically detect/alert on new 3rd party links

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9902]
A recommendation in the [RRA for Contentful](https://docs.google.com/document/d/1_eAmy8iK4cMfEPVKSuUG0xPxeufV3fmUbKpSWdBMlGY/edit#heading=h.t1vwvhh7e6x9) suggests monitoring content published on www.mozilla.org for new 3rd-party links. This could help avoid the worst-case scenario (malicious content serves malicious links to 3rd-party software). 

Can we establish this at the point of integration (e.g. as we pull content from Contentful APIs)? Or would it be more powerful to establish a site-wide crawl that monitors 3rd-party links (this would provide coverage for other publishing inputs, e.g. Convert.com or Nucleus or Legal Docs or GitHub)?

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/9842

Imho, we may probably need multiple levels of checks. A site wide crawl will help to detect server generated content (via contentful), but may not capture content that gets created via client side manipulation. Some form of real-time reporting may help here.

**Comment by alexgibson** [comment]
Might this also be a good opportunity to see if we can tighten up some of our CSP rules relating to CSS/JS, to reduce the possible surface for risks?

**Comment by alexgibson** [comment]
covered in https://github.com/mozmeao/www-site-checker
