### ISSUE TITLE
Should use gender neutral term in en/firefox/privacy/safe-passwords

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9909]
## Description

In https://pontoon.mozilla.org/en-CA/mozillaorg/en/firefox/privacy/passwords.ftl/?string=218027, `... If an attacker can get your password, he can access your account and do anything you could do with that account. ...`

### Expected result

Instead of `he`, suggest to use `they`, so the sentence needs to be rewritten: If *attackers* can get your password, *they* can...

**Comment by Sayantani-sunshine** [comment]
Hello.Is the issue open?Can I work on this?
