### ISSUE TITLE
Back to top button for quick navigate to top

### ISSUE THREAD

**Issue by Raunaksingh100** [mozilla/bedrock#9910]
## Description

we can add Back to top button for quick navigate to top and this button help to quick navigate to top especially in desktop. You can add here the Back to top button see in the screenshot for the better understanding.

### screenshot-
![now](https://user-images.githubusercontent.com/65535360/107140763-5a650b80-694a-11eb-872d-8f030ad908d5.PNG)

**Comment by Soundug** [comment]
@Raunaksingh100 Hey! I am just starting to contribute to open source. I would like to work on this issue.

**Comment by Soumya0803** [comment]
Hi @alexgibson @pmac , I would like to work on this issue. I have got the project locally installed. Can you please assign this issue to me if it is available?

**Comment by Amotul-raheem** [comment]
Hi @maureenlholland, Is there a mock-up for the button?

**Comment by maureenlholland** [comment]
Hi folks! After some discussion, we've decided to move this into a Protocol issue to create a "Back to top" button component: https://github.com/mozilla/protocol/issues/825

It's not ready for work just yet, but please feel free to join the discussion as we figure out the details. Thanks!
