### ISSUE TITLE
Added Contributers name in the README.md

### ISSUE THREAD

**Issue by Ayush7614** [mozilla/bedrock#9920]
## Description

Add Contributers name in the README.md
---

#### Success Criteria

![screenshot-github com-2021 02 07-22_11_43](https://user-images.githubusercontent.com/67006255/107153115-d6cf0d00-6991-11eb-8bf5-aa0d555dff2c.png)

**Comment by Ayush7614** [comment]
Like this

**Comment by alexgibson** [comment]
Thanks for the suggestion, but I think we should try and keep the main readme focused on getting started with bedrock whilst being relatively short. GitHub already provides a section for contributor insights here: https://github.com/mozilla/bedrock/graphs/contributors
