### ISSUE TITLE
Pass experiment ID and variation data through to vpn.mozilla.org referrals

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9922]
## Description

As soon as https://github.com/mozilla/bedrock/issues/9855 is resolved, we'll have a new Mozilla VPN product landing page on www.mozilla.org at /products/vpn/ 🎉 

Once the landing page is live, we'll also be able to start facilitating A/B tests in bedrock to drive conversion rate optimisations. If we started running those right away, we'd only have visibility on data related to top of funnel conversions (i.e. clicking "Try Mozilla VPN"). In order to see what happens right down the funnel (from button click, to Firefox Account signup, to final payment/subscription), we need to establish a system whereby we can pass a specific set of query parameters related to the experiment right down the stack of sub-systems. 

This is an issue to piece together:

1. What has already been done that works toward unlocking this functionality.
2. What is remaining, and who's help we might need to do it.
3. What the final spec should be for www.mozilla.org to implement once ready.

---

#### Success Criteria
- [x] Implement a testing referral attribution flow for Mozilla VPN signups.

**Comment by alexgibson** [comment]
Possible pieces to this puzzle: on the FxA side

- https://github.com/mozilla/fxa/issues/6925
- https://github.com/mozilla/fxa/pull/7216

**Comment by alexgibson** [comment]
@hoosteeno @chrismore @slightlyoffbeat aside from the issue linked in the comment above, are you aware of any other issues related to unblocking this? Do these values need to be passed down to the subscription/payment level also?

**Comment by chrismore** [comment]
> @hoosteeno @chrismore @slightlyoffbeat aside from the issue linked in the comment above, are you aware of any other issues related to unblocking this? Do these values need to be passed down to the subscription/payment level also?

Not off the top of my head. Let's get feedback from @davismtl

**Comment by slightlyoffbeat** [comment]
It looks like we can now use `entrypoint_experiment` and `entrypoint_variation`. If that's the case, the only step would be to test and confirm.

I reached out to data science to see if someone can help with this. We can do a quick test on staging and confirm we are good to go.

**Comment by alexgibson** [comment]
Looking through our commit history it looks like we already have support for passing these parameters through in our FxA referral logic (I’d totally forgot we did this already, yikes).

https://github.com/mozilla/bedrock/issues/7589

If all is well, I’ll provide a URL and we can test this flow via the demo page.

Let’s wait to hear if there are any other pieces of the puzzle still missing though.

**Comment by hoosteeno** [comment]
I suspect, but I do not know for sure, that these parameters only get our experiment data into FxA metrics. How do parameters get through FxA servers to subscription platform metrics? Needs some digging to figure out.

**Comment by alexgibson** [comment]
I've opened a pull request here for bedrock to automatically pass through `entrypoint_experiment` and `entrypoint_variation` params to FxA product buttons (such as the VPN links): https://github.com/mozilla/bedrock/pull/9941

This is only the top of funnel however. We still need to pass this data all the way down to the subscription platform.

**Comment by alexgibson** [comment]
George is conducting some attribution tests on staging for these parameters, results are being added to this doc: https://docs.google.com/spreadsheets/d/170ZGZU-SNmkc_X2eRrxXQPh55NqLQKeuuu7hYnCszKs/edit?usp=sharing

**Comment by alexgibson** [comment]
Now that the mozorg VPN landing page is live, George is going to test the experiment params and try and find the referral data in the production database: https://www.mozilla.org/en-US/products/vpn/?entrypoint_experiment=test&entrypoint_variation=test

**Comment by alexgibson** [comment]
George has done a successful test using the entrypoint parameters from www -> subscription data. He still has some work to do in terms of how to leverage this data in reporting, but I think we can close this issue as referrals are now working as expected 🎉
