### ISSUE TITLE
Request - add new board member to leadership page

### ISSUE THREAD

**Issue by anilkanji** [mozilla/bedrock#9931]
Hi there - can we please add a new Mozilla Foundation board member to the [Leadership page](https://www.mozilla.org/en-US/about/leadership/)? 

Will forward image to @slightlyoffbeat  Dan Brown.

Thank you!

**Comment by smitbarmase** [comment]
I can work on this issue. Can you assign me?

**Comment by slightlyoffbeat** [comment]
Details can be found here: https://docs.google.com/document/d/1J0LcYSfzGPPkq2WjuKAUNxX1yNHGpIVyngasMo8jrxg/edit?usp=sharing
