### ISSUE TITLE
JS Karma error: Some of your tests did a full page reload!

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9943]
## Description

Occasionally when I run `npm run test` locally, Karma will throw an error saying `Some of your tests did a full page reload!` and abort the test run. I think there's a bug in one of our tests that only occurs depending on the order in which they run (which is intentionally randomised). I can't see any tests that call `window.location.reload()`, so it must be triggered by some other means (maybe a click or form submission). This is a fun doozy.

### Steps to reproduce

Run `npm run test` multiple times until the error occurs.

### Expected result

The test run should always finish.

### Actual result

The test run sometimes gets aborted early with the above error.

### Environment

Firefox & Chrome, macOS

**Comment by Abhra303** [comment]
May be it is not a bedrock's bug. It can be a karma bug. btw This was an issue before version 6.0.0. See [this](https://github.com/karma-runner/karma/issues/3560#issuecomment-759612586).
@alexgibson  are you still getting this error?

**Comment by alexgibson** [comment]
Good to know @Abhra303 thanks! We're on version 6 now, so let's keep an eye on this bug and we can close it if the problem seems to be gone :)

**Comment by alexgibson** [comment]
Going to close this and we can re-open if we still see it happening.
