### ISSUE TITLE
Update performance regression policy

### ISSUE THREAD

**Issue by davehunt** [mozilla/bedrock#9947]
## Description

The performance regression policy at https://www.mozilla.org/en-US/about/governance/policies/regressions/ is out of date. We need to update the contact details, add a section for sheriffing criteria, and a few other small updates. The updated content is here: https://docs.google.com/document/d/1v8Wyl_Bjp1uJxRxstjVPHSRLiQxHVdxa6oYAfomqEdI/edit#

---

#### Success Criteria
- [ ] Performance regression policy content is updated

**Comment by alexgibson** [comment]
@davehunt pushed this to a demo so you can review before it goes out. Let me know if this looks ok? Thanks

https://www-demo2.allizom.org/en-US/about/governance/policies/regressions/

**Comment by davehunt** [comment]
Looks good, thanks @alexgibson
