### ISSUE TITLE
Implement location based pricing for VPN landing page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9948]
## Description

The VPN landing page being created in https://github.com/mozilla/bedrock/issues/9855 will initially show pricing in US$ only. Currency support for Euros is soon to be added to the VPN product and subscriptions flows. Once that is ready in product, then we'll also need to start display pricing in different currencies on the landing page. This should be done using geo-location (not page locale).

---

#### Success Criteria
- [ ] Visitors in France and Germany will see the price in Euros as opposed to $US.

**Comment by alexgibson** [comment]
Update after input from @rraue:

We should try and implement an approach that uses:

1. A server side render of the appropriate currency via page locale.
2. Then a secondary client side render that also check geo-location and then updates the currency if different.

**Comment by alexgibson** [comment]
Back of a napkin logic so far:


- Is VPN available in country?
    - Yes
        - Is visitor in Germany / France and locale in [‘de’, ‘fr’]
            - Yes
                - Display variable pricing options
                    - Monthly, Quarterly, Annually (TBD)
                    - Display in Euros.
            - No
                - Display standard pricing option in $US
    - No
        - Show waitlist signup

**Comment by alexgibson** [comment]
Pricing models (Mozilla Confidential): https://docs.google.com/document/d/13Zcr_isg8gmfIBgNbcNR2WRh0YJSUk7e4UWOlbRuKHQ/edit?usp=sharing

**Comment by birdsarah** [comment]
Staging pricing links are as follows:

* misc USD plan - /r/vpn/subscribe/products/prod_FiJ42WCzZNRSbS?plan=plan_FiJ55YK6UYftP
* 99.99/yearly/eu - /r/vpn/subscribe/products/prod_FiJ42WCzZNRSbS?plan=price_1IXw5oKb9q6OnNsLPMkWOid7
* 49.99/6-month/eu - /r/vpn/subscribe/products/prod_FiJ42WCzZNRSbS?plan=price_1IXw5NKb9q6OnNsLLIyYuhWF
* 4.99/monthly/eu -  /r/vpn/subscribe/products/prod_FiJ42WCzZNRSbS?plan=price_1IXw4eKb9q6OnNsLqnVP4PvO


Production pricing links will be different, and I don't have yet.

**Comment by birdsarah** [comment]
Staging pricing links are as follows:

Mozilla Confidential: https://docs.google.com/document/d/1k9JUJqdMeG4ro8R_-H1FzQl2wOTj9XZrDKvXNcCJP2M/edit?usp=sharing

Production pricing links will be different, and I don't have yet.
