### ISSUE TITLE
Add a feature page for Picture-in-Picture

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#9953]
## Description

Create a new page about the Picture-in-Picture feature in Firefox.

---

#### Success Criteria
- [ ] The new page is live at /firefox/features/picture-in-picture/
- [ ] Add link to the features front page

**Comment by craigcook** [comment]
Rough mockup:

![image](https://user-images.githubusercontent.com/205591/108880386-182d0280-75b7-11eb-926b-01076d4209a8.png)

**Comment by rraue** [comment]
Copy doc: https://docs.google.com/document/d/1qmreZTPBosyJyrkcBK-ptHuPc1UenK9cCOTQvm1V8AY/

Still not reviewed, creative team is on it.
