### ISSUE TITLE
Epic: VPN OS landing pages

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9963]
## Description

We will create 6 OS specific landing pages for VPN:

- Mozilla VPN for PC - url: w.m.o/products/vpn/desktop/
- Mozilla VPN for Windows 10 - url: w.m.o/products/vpn/desktop/windows/
- Mozilla VPN for Mac - url: w.m.o/products/vpn/desktop/mac/
- Mozilla VPN for Linux - url: w.m.o/products/vpn/desktop/linux/
- Mozilla VPN for Mobile - url: w.m.o/products/vpn/mobile/
- Mozilla VPN for iOS - url: w.m.o/products/vpn/mobile/ios/
- Mozilla VPN for Android - url: w.m.o/products/vpn/mobile/android/

Copy doc: https://docs.google.com/document/d/1dAh_1fX9kHe7yDRH1GsS2Ho0l316JI9T1whBi5KdCws/edit?ts=6036c9e1

Trello card: https://trello.com/c/uvPRTFu4/100-develop-vpn-seo-pages

Brief: https://docs.google.com/document/d/1J7KdgsKVypDOS5rpyKByh-wgg5Y3j5gMc4_lGsfoVAQ/edit#heading=h.f6i9jjss4fon

Strategy: https://docs.google.com/document/d/1IX6qErGpA2dfyluXim2QDO15lqaPNY97r17pwoP-yyw/edit#heading=h.9q6ssys9kgot

---

- prepared for translation in pontoon and prod only in en-US for now

---

#### Issues
- [ ] #issue-number

**Comment by alexgibson** [comment]
Before localizing these SEO pages we should speak to Michelle Riband, as right now even the VPN Waitlist emails are still in English only, which does not make for a great experience for non-English languages.

**Comment by alexgibson** [comment]
Closing this epic, but feel free to reopen if there are any unresolved dependencies here.
