### ISSUE TITLE
Update Picture-in-Picture feature page with multi-window in time for March campaign

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#9980]
## Description

We're promoting the new multiple-window PiP feature in relation to a seasonal US sporting tournament and we need to make some changes to the new PiP page to support that campaign. Some changes will be only shown to en-US and temporary, just for the duration of the campaign, but other changes will stay longer and be available to all locales.

---

#### Success Criteria

- [ ] New hero image [en-US-only, temporary]
- [ ] New title [en-US-only, temporary]
- [ ] New pre-title [all locales, permanent]
- [ ] Add a "step 4" to the instructions [all locales, permanent]

**Comment by rraue** [comment]
We landed as well for a new hero title for en-US only, right?

**Comment by craigcook** [comment]
> We landed as well for a new hero title for en-US only, right?

Correct, added to the list.

Copy deck: https://docs.google.com/document/d/1coHqAsb72qW1v0TB7yJ9lovMV12k1YuoEM1C1Nm59-c/edit

**Comment by rraue** [comment]
Do you have all assets to start? Today is deadline for assets. Else I go ping people.
