### ISSUE TITLE
Wrong capitalization of Yandex on the download page, RU locale

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9983]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1696476

**Comment by Kaushal-Dhungel** [comment]
Hello @alexgibson . I would like to work on this issue.

**Comment by alexgibson** [comment]
Pull requests are welcome

**Comment by Kaushal-Dhungel** [comment]
I am unable to locate the bug. I do not know Russian and I do not see the same button as mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1696476
![Screenshot at 2021-03-17 17-07-17](https://user-images.githubusercontent.com/57295839/111463357-98bec900-8747-11eb-86e2-6e8226943b2b.png)

Am I missing something here??

**Comment by Ayushsunny** [comment]
> I am unable to locate the bug. I do not know Russian and I do not see the same button as mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1696476
> ![Screenshot at 2021-03-17 17-07-17](https://user-images.githubusercontent.com/57295839/111463357-98bec900-8747-11eb-86e2-6e8226943b2b.png)
> 
> Am I missing something here??

Exactly, I agree with you Kaushal.
Though I know Russian but still I'm unable to recognise the bug, I was checking the codebase again and again from 7-8 days.
 @alexgibson Please help us to see forward

**Comment by alexgibson** [comment]
I searched for the string in question and it looks to be in this template: https://github.com/mozilla/bedrock/blob/c36684d6468ba5b35582339182d58412331c0297/bedrock/firefox/templates/firefox/new/desktop/download_yandex.html#L80

**Comment by alexgibson** [comment]
You can preview the page via the URL: `/ru/firefox/new/?geo=ru`

**Comment by Kaushal-Dhungel** [comment]
Thanks. If I understood it properly then it should be `Скачать Firefox с Яндексом` in place of `Скачать Firefox без Яндекса` right??
