### ISSUE TITLE
Policy page updates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9984]
## Description

1. A small edit to the [Distribution Policy](https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/), change the third bullet point to:

```
You may not add to, remove, or change any part of the software, including the Mozilla trademarks themselves. For example, you may not add any extensions to Firefox, change default settings, or alter search codes.
```

2. An update to the [Licensing Policy](https://www.mozilla.org/en-US/MPL/license-policy/) page. Copy updates are in track-changes here: https://docs.google.com/document/d/1Qv_jaUQO7XjMymhV5SA0N4u-KyUIZRpT03MtYB0lc3s/edit#)

3. Update to the [Report Fraud](https://www.mozilla.org/en-US/about/legal/fraud-report/) page. The changes are here: https://docs.google.com/document/d/1BRe-bu6_Smy_V99376uOOFq4uojGm3yhrwLCjkuyrsU/edit#heading=h.y1e7hec9q26c

~4. Change the URL of the fraud report page to https://www.mozilla.org/about/legal/report-infringement-of-mozilla-trademarks/ (old URL should redirect to new URL).~

4. Change the URL of the fraud report page to https://www.mozilla.org/about/legal/defend-mozilla-trademarks/ (old URL should redirect to new URL).

---

#### Success Criteria
- [ ] Updates are approved by Daniel Nazer on demo before merging.
- [ ] Pages are updated live in production.

**Comment by Ayushsunny** [comment]
Can I work on this issue?

**Comment by maxxcrawford** [comment]
Daniel and I sync'd up about the URL redirect. New url should be `defend-mozilla-trademarks/`
