### ISSUE TITLE
Make setting env variables for demo deployments easier

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9985]
## Description

Right now, figuring out how / where to set an environment variable for a demo instance isn't so easy. 

- The [www-config repo](https://github.com/mozmeao/www-config/tree/master/configs) has some config files for dev/stage/prod environments.
- For demo deployments there's [app.json](https://github.com/mozilla/bedrock/blob/master/app.json) in the bedrock root folder, but this doesn't seem to work when I test (and is also undocumented?). It might require a backend dev to configure currently.
- There are also a bunch of other files in the [docker/envfiles](https://github.com/mozilla/bedrock/tree/master/docker/envfiles) directory, but I'm not sure if they are still used.
- I can't find any consolidated info in the bedrock docs on how things are set up.

---

#### Success Criteria
- [ ] Document how / where variables are set for different deployments.
- [ ] Front-end devs should be able to configure variables for demo deployments.

**Comment by robhudson** [comment]
The docs now have a "Env vars" section in the demos docs that hopefully clear this up:
https://bedrock.readthedocs.io/en/latest/contribute.html#demo-sites
