### ISSUE TITLE
Adjust Contentful roles according to Mozilla Solution document

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9988]
We need to have some defined rolls. This includes:

- [ ] Developer Roll
- [ ] Removing delete option from everything except admin roll
- [ ] Read-only roll
- [ ] Author Roll
- [ ] Editor Roll

Details:
https://docs.google.com/document/d/15lAotxs4DgEnTBkmMP4I41ZjCh8McOVYVaabfUUinE4/edit?usp=sharing

**Comment by maureenlholland** [comment]
still relevant, we need well-defined roles to create a reliable workflow
