### ISSUE TITLE
Integrate Smartling with Contentful

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9992]
Smartling is available to us on March 16th. Lets activate the Smartling app for Contentful and hook it into our process.

***

**Success criteria**

- [ ] Smartling app is authenticated in contentful
- [ ] Can submit content to be translated
- [ ] Can track submissions
- [ ] Is able to publish page from Contentful with translated content from contentful

**Comment by maureenlholland** [comment]
@stevejalim is this done?

**Comment by stevejalim** [comment]
Not that I'm aware of @maureenlholland 

Can look into it later today

**Comment by stevejalim** [comment]
@slightlyoffbeat This sounds like the Contentful L10N work you mentioned we/I get back on the road, yep? If so, I'm happy to put my face on this

**Comment by maureenlholland** [comment]
I believe this is in place now. Contentful fields can be localized and Bedrock API has a localisation complete check: https://github.com/mozilla/bedrock/pull/12387
