### ISSUE TITLE
Determine workflow for pontoon and community translations

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9993]
Smartling will handle our translations for EN, FR, DE, and 5 of our other top languages. Other languages will still be handled by pontoon and community translators.

Open questions:

- Do we need to include support for languages not handled by Contentful? Or are Contentful pages only available in those 8 languages?
- If we include community languages, how do we handle this?
- Do we build the capability to specifically request community translations?
- Does Contentful even need to be involved with pontoon and community translations at all? Will the current process handle everything with minimal changes?

**Comment by maureenlholland** [comment]
Closing as we decided to move forward with a Smartling only approach for now: https://bedrock.readthedocs.io/en/latest/contentful.html#smartling-our-selected-approach
