### ISSUE TITLE
Content Model: naming

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9997]
Naming is hard. Lets look at our Contentful content model and our Protocol naming scheme and clean up where we can.

We should take advice and input from content creators.

Naming will always be ongoing, so we should determine a reasonable goal for what our v1 content naming.

**Comment by stephaniehobson** [comment]
Here's the Google Doc where I am keeping track of naming decisions: https://docs.google.com/document/d/1DbC-ksBTQtNYw75-GtNwhiSrf7QX4G9pIIIEusOzEUs/edit#heading=h.d7ouznb3df46 (mozilla only)

**Comment by maureenlholland** [comment]
completed and documented for V1: https://bedrock.readthedocs.io/en/latest/contentful.html#naming-conventions-for-content-models
